- frontend/ts/ic-hardware-wallet-cli.ts
Delay can be specified in years, days, minutes, and seconds as opposed to only seconds.
> Enhancements to "Increasing dissolve delay" in HW CLI.

- Cargo.lock
- rs/Cargo.toml
This is to follow the recommendation of `cargo audit`.
> Upgrade tar

- frontend/dart/lib/ui/neurons/detail/neuron_state_card.dart
Split neuron button is now disabled for hotkeys
> Split neuron button is now disabled for hotkeys

- frontend/dart/lib/ui/neurons/tab/neurons_tab_widget.dart
This reverts commit 88ca6301328158488ad50e986421608a02cde3d3.
> Revert "Remove the principal text from the neurons page. (#277)"

- frontend/svelte/src/App.svelte
- frontend/svelte/src/lib/components/Logout.svelte
Redo clear storage after logout as discussed in [#328](https://github.com/dfinity/nns-dapp/pull/328).
- `window.localStorage.clear();`
> feat: clear storage after logout

- frontend/svelte/src/lib/components/Guard.svelte
- frontend/svelte/src/lib/stores/auth.store.ts
- frontend/svelte/src/routes/Auth.svelte
Keep track of recent TODOs
- Jira references added
> docs: add todo references

- update_config.sh
Otherwise the heredoc swallows the error and the script won't fail even
if there is no canister ID
> Extract OWN_CANISTER_ID from heredoc

- frontend/svelte/src/lib/stores/auth.store.ts
Fixes https://dfinity.atlassian.net/browse/FOLLOW-449
> Fix delegation ttl to 30 min

- frontend/svelte/src/lib/components/Guard.svelte
- frontend/svelte/src/lib/components/Spinner.svelte
- frontend/svelte/src/routes/Accounts.svelte
- frontend/svelte/src/tests/lib/components/Guard.spec.ts
Add a spinner that can be used for actions that take a certain time till completion.
- new component `<Spinner />`
- use spinner in `<Guard />`(until agent-js is loaded) and to display main account (until ledget balance is fetched)
> feat: spinner

- e2e-tests/specs/example.e2e.ts
This makes sure that we wait for the background to be loaded before we
take the screenshots.
> Wait for all img tags to be complete

- frontend/svelte/package-lock.json
- frontend/svelte/package.json
- frontend/svelte/src/lib/utils/accounts.utils.ts
- frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
We need the new canister features released in v0.2.0 (`listProposals` etc.)
- bump nns v0.2.0
- update `accounts.utils` to new parameters (no feat, refactoring only)
> build: bump nns v0.2.0

- frontend/dart/lib/data/topic.dart
The algorithm for following another neuron is being updated; the change needs to be communicated to the user.
- Update the "Follow all" description as now this setting causes the neuron to follow for all proposals except governance proposals.
> text changes

- CHANGELOG.md
The nns-dapp was updated via this proposal: https://dashboard.internetcomputer.org/proposal/45369
So:
* The release commit needs to be tagged (done separately)
* The release needs to be added to the changelog.
* Added a changelog entry for the release.
No code, no tests.
> Changelog for proposal 45369

- frontend/dart/lib/ui/home/home_tabs_widget.dart
Routing is broken in current main but works in prod.
Revert the tab bar, that does the tab routing, to prod.
This has been deployed to a testnet.
There are style changes that will have to be re-applied.  But those would be best done in a separate PR.
> reverted home tab bar widget to prod

- frontend/svelte/jest-setup.ts
- frontend/svelte/package-lock.json
- frontend/svelte/package.json
- frontend/svelte/rollup.config.js
- frontend/svelte/src/lib/components/ui/Input.svelte
- frontend/svelte/src/lib/constants/canister-ids.constants.ts
- frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
- frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
- frontend/svelte/src/lib/services/dev.services.ts
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/routes/Neurons.svelte
- frontend/svelte/src/tests/lib/components/ui/Input.spec.ts
- frontend/svelte/src/tests/lib/components/ui/InputValueTest.svelte
- frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
Add stake neuron functionality.
* Neurons services to create neuron and get neurons list.
* StakeNeuronModal creates neuron.
* Neurons services.
* Upgrade CreateNeuronModal test for staking a neuron.
> L2-226: Stake neuron functionality

- frontend/svelte/src/lib/constants/constants.ts
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
- frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
- frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
- frontend/svelte/src/lib/themes/button.scss
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/date.utils.ts
- frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
UI for Dissolve Delay Modal after creating a neuron.
* new SedDissolveDelay component.
* Add SetDissolveDelay step to CreateNeuronModal component.
* Updated CreateNeuronModal tests to check for "Set Dissolve Delay" screen after creating neuron.
> L2-330: Update neuron delay UI

- frontend/svelte/jest-setup.ts
- frontend/svelte/src/routes/NeuronDetail.svelte
Build was broken from a env var.
* Move usage of env var inside the script.
> Fix: REDIRECT_TO_LEGACY

- frontend/svelte/package-lock.json
- frontend/svelte/package.json
Pin nns nightly in package.json
- pin nns nightly in package.json
- add script shortcut to install last nightly
> build: pin nns nightly

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/services/proposals.services.ts
- frontend/svelte/src/routes/ProposalDetail.svelte
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
- frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
- frontend/svelte/src/tests/mocks/proposals.store.mock.ts
Bump nns-js nightly (8.3.2022).
- bump nns-js
- adapt name of the functions that have been refactored in nns-js (breaking)
> build: bump nns-js nightly

- frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
- frontend/svelte/src/lib/components/ui/Card.svelte
- frontend/svelte/src/tests/lib/components/proposal-detail/VotesCard.spec.ts
- frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
- frontend/svelte/src/tests/mocks/neurons.mock.ts
- frontend/svelte/src/tests/routes/NeuronDetail.spec.ts
- frontend/svelte/src/tests/routes/Neurons.spec.ts
Neurons Route test was passing for the wrong reasons.
* Add `data-test` to Card, and NeuronCard to identity cards in tests.
* Changes in Neurons route test.
* Reuse the neurons subscribe mock in multiple tests.
* Fixed some style issues.
All changes are in the tests.
> Fix: Neurons Route Test

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
- frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
- frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
Functionality to updating neuron delay after creating a new neuron.
* Neuron service `updateDelay`.
* Update Delay in SetDissolveDelay component
* Add tests for service `updateDelay`.
* Updated test in CreateNeuronModal to update the delay calles the service.
> L2-330: Update neuron delay

- frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
- frontend/svelte/src/lib/icons/IconThumbDown.svelte
- frontend/svelte/src/lib/icons/IconThumbUp.svelte
- frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
- frontend/svelte/src/tests/lib/components/proposal-detail/VotesCard.spec.ts
- frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
Change attribute for testing purposes from `data-test` to `data-tid`.
* Change html attribute in specific elements.
* Updated tests to use new attribute.
> Fix: Change data-test to data-tid

- frontend/svelte/src/lib/modals/accounts/SelectTypeAccount.svelte
- frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
There is an existing mixin to add interaction to element ("cursor: pointer")
- use `interaction` mixin
> style: use interaction mixin

- frontend/svelte/src/lib/components/common/Banner.svelte
- frontend/svelte/src/lib/components/proposals/ProposalCard.svelte
- frontend/svelte/src/lib/components/ui/Checkbox.svelte
- frontend/svelte/src/lib/components/ui/InfiniteScroll.svelte
- frontend/svelte/src/lib/components/ui/Input.svelte
- frontend/svelte/src/lib/components/ui/Markdown.svelte
- frontend/svelte/src/lib/components/ui/Toast.svelte
- frontend/svelte/src/lib/modals/Modal.svelte
- frontend/svelte/src/lib/modals/accounts/AddNewAccount.svelte
- frontend/svelte/src/lib/modals/proposals/ProposalsFilterModal.svelte
- frontend/svelte/src/lib/services/canisters.services.ts
- frontend/svelte/src/lib/utils/app-path.utils.ts
- frontend/svelte/src/lib/utils/i18n.utils.ts
- frontend/svelte/src/lib/utils/route.utils.ts
- frontend/svelte/src/lib/utils/utils.ts
- frontend/svelte/src/routes/Accounts.svelte
- frontend/svelte/src/routes/Auth.svelte
Fix lint issues regarding the rule `@typescript-eslint/strict-boolean-expressions`
* Fix issues with `@typescript-eslint/strict-boolean-expressions` in many files.
No new tests. Thankful for the current tests.
> Fix: Lint rule issues strict-boolean-expressions

- frontend/svelte/env.config.mjs
The possible values for REDIRECT_TO_LEGACY have changed.  The changes need to be documented.
- Update the documentation for REDIRECT_TO_LEGACY in the code.
Non needed
> Update docs for redirect to legacy

- frontend/svelte/package.json
- frontend/svelte/src/lib/components/proposals/Proposer.svelte
- frontend/svelte/src/lib/modals/proposals/ProposerModal.svelte
Make CI pipeline green again.
* Remove `npm run lint` temporarily from `npm run check`.
No tests.
> Fix: Green CI

- frontend/svelte/src/lib/components/neurons/VotingHistoryCard.svelte
- frontend/svelte/src/lib/components/proposals/ProposalShortSummary.svelte
- frontend/svelte/src/lib/modals/proposals/ProposerModal.svelte
- frontend/svelte/src/lib/services/proposals.services.ts
- frontend/svelte/src/lib/utils/proposals.utils.ts
- frontend/svelte/src/routes/ProposalDetail.svelte
- frontend/svelte/src/tests/lib/components/proposals/ProposalShortSummary.spec.ts
- frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
- frontend/svelte/src/tests/mocks/governance.canister.mock.ts
- frontend/svelte/src/tests/mocks/proposals.store.mock.ts
Initialize the feature "Voting history"
- create two dedicated components
- list all distinctive proposals of the `recentBallots`
- refactor code to use existing `loadProposal` feature
> feat: init voting history

- frontend/svelte/src/lib/components/proposal-detail/IneligibleNeuronsCard.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/routes/ProposalDetail.svelte
- frontend/svelte/src/tests/lib/components/proposal-detail/IneligibleNeuronsCard.spec.ts
- frontend/svelte/src/tests/mocks/proposal.mock.ts
Display ineligible neurons in proposal detail page [](https://dfinity.atlassian.net/browse/L2-284)
- Didn't find how to test/mock ballots locally
- IneligibleNeuronsCard 
- IneligibleNeuronsCard.spec
> L2 284 ineligible neurons card

- frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
- frontend/svelte/src/routes/ProposalDetail.svelte
- frontend/svelte/src/tests/lib/components/proposal-detail/VotesCard.spec.ts
Adapt `VotesCard` to follow same pattern as the other components in ProposalDetail.
* `VotesCard` expects array of neurons.
* Tests on `VotesCard` have been updated.
> Fix: Change VotesCard props pattern

- e2e-tests/package.json
- frontend/svelte/.eslintrc.js
- frontend/svelte/package.json
- frontend/svelte/src/lib/components/ic/GetICPs.svelte
- frontend/svelte/src/lib/components/ui/Input.svelte
- frontend/svelte/src/lib/components/ui/Markdown.svelte
- frontend/svelte/src/lib/services/proposals.services.ts
- frontend/svelte/src/lib/stores/auth.store.ts
- frontend/svelte/src/lib/utils/error.utils.ts
- frontend/svelte/src/lib/utils/optimization.utils.ts
- frontend/svelte/src/lib/utils/utils.ts
- frontend/svelte/src/routes/Auth.svelte
- frontend/svelte/src/routes/Canisters.svelte
- frontend/svelte/src/routes/Proposals.svelte
- frontend/svelte/src/tests/routes/Accounts.spec.ts
- frontend/svelte/src/tests/routes/Canisters.spec.ts
Fix last eslint issues.
* Fix no-any lint issue.
* Add comments enabling eslint issues.
No new tests.
> Fix: Eslint issues any types and others

- frontend/svelte/README.md
Describe the Svelte project in the Readme file.
* Readme in svelte directory.
No tests.
> L2-193: Readme NNS Svelte Project

- frontend/svelte/src/routes/ProposalDetail.svelte
Error handling was done in queryAndUpdate PR
> chore: remove outdated comment

- frontend/svelte/src/lib/utils/proposals.utils.ts
Remove unused code.
- remove `formatProposalSummary`
> chore: remove unused function

- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/IncreaseDissolveDelayButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/IncreaseStakeButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/JoinCommunityFundButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/SplitNeuronButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/StartDissolvingButton.svelte
- frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
- frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.svelte
- frontend/svelte/src/lib/components/ui/Tooltip.svelte
- frontend/svelte/src/lib/constants/constants.ts
- frontend/svelte/src/lib/constants/icp.constants.ts
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/icons/IconInfo.svelte
- frontend/svelte/src/lib/modals/proposals/VoteConfirmationModal.svelte
- frontend/svelte/src/lib/themes/button.scss
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/date.utils.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/lib/utils/proposals.utils.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronMetaInfoCard.spec.ts
- frontend/svelte/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts
- frontend/svelte/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.spec.ts
- frontend/svelte/src/tests/lib/utils/date.utils.spec.ts
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/svelte/src/tests/lib/utils/proposals.utils.spec.ts
- frontend/svelte/src/tests/mocks/neurons.mock.ts
- frontend/svelte/src/tests/routes/NeuronDetail.spec.ts
UI for the NeuronMetaInfoCard in Neuron Details page.
* NeuronMetaInfoCard html and css.
* Move `formatVotingPower` to neuron utils.
* Expand NeuronCard to manage child elements.
* New utils regarding voting power calculations.
* New type button: `warning`.
* Test NeuronMetaInfoCard.
* Test utils.
> L2-352: NeuronMetaInfoCard UI

- frontend/svelte/src/lib/api/ledger.api.ts
- frontend/svelte/src/lib/services/neurons.services.ts
Improve comment and enable a call to be update or query.
* Ledger API getNeuronBalance can be both query or update call.
* Improve comment in checkNeuronBalances flow.
No changes.
> Chore: getNeuronBalance certified or not

- frontend/dart/lib/ui/proposals/proposal_state_card.dart
- frontend/dart/lib/ui/widgets/flutter_json_viewer.dart
Proposal payload data is in an unreadable format.
JsonViewer widget is now being used to show the json data 
Widget code copied from : https://pub.dev/packages/flutter_json_viewer
The widget has not been put in directly as a dependancy , since the colour , text parameters are not passed as arguments. Hence it has been copied and changes have been made to the colour parameters for the NNSDapp
> json viewer for proposal payload data

- frontend/svelte/src/tests/lib/components/neurons/VoteHistoryCard.spec.ts
> refactor: move test to correct package

- frontend/svelte/src/lib/components/neuron-detail/NeuronMaturityCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/MergeMaturityButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/format.utils.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronMaturityCard.spec.ts
- frontend/svelte/src/tests/lib/utils/format.utils.spec.ts
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
Show Maturity Card in Neuron Detail Page. Only UI.
* Implement UI in the component NeuronMaturityCard.
* New format util `formatPercentage`.
* New neuron util `maturityByStake`.
* Test the new UI in NeuronMaturityCard.
* Test new format util formatPercentage.
* Test new neuron util maturityByStake.
> L2-353: MaturityCard UI

- frontend/svelte/env.config.mjs
- frontend/svelte/src/lib/types/i18n.d.ts
Fix local development.
* Check for ENVIRONMENT instead of DEPLOY_ENV.
No test
> Fix: Local development

- frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/svelte/src/lib/components/ui/Collapsible.svelte
https://dfinity.atlassian.net/browse/L2-407
Switched custom collapsible with Collapsible component
- applied Collapsible
- add iconSize param to Collapsible
https://user-images.githubusercontent.com/98811342/161065737-1a0e8bd3-706e-4386-a34d-fcf0547313bd.mov
> feat: add Collapsible to FollowTopicSection

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/api/accounts.api.ts
- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/DisburseButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/DissolveActionButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/JoinCommunityFundButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/StartDissolvingButton.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/services/accounts.services.ts
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/themes/mixins/_confirmation-modal.scss
- frontend/svelte/src/lib/types/account.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/tests/lib/api/governance.api.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronMetaInfoCard.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/DissolveActionButton.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/JoinCommunityFundButton.spec.ts
- frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
- frontend/svelte/src/tests/mocks/accounts.store.mock.ts
User can start and stop dissolving process in a neuron.
* Neuron services: isNeuronControllable, startDissolving and stopDissolving.
* Governance api: startDissolving and stopDissolving.
* Upgrade nns-js.
* Change button to DissolveActionButton that handles both cases.
* Account services: getAccountByPrincipal
* New tests for the neuron services
* New tests for the governance api
* Test for the new button.
* New test for the account services.
> L2-364: Neuron start dissolving

- frontend/dart/assets/libs/dummy-proposals.utils.js
- frontend/svelte/src/lib/api/dev.api.ts
- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/services/neurons.services.ts
Ship within prod bundle what needs to be shipped only.
- `await import` to load dummy proposal script
- assert feature can only be called on testnet
> feat: await import dummy proposal script

- frontend/svelte/src/lib/components/neuron-detail/NeuronFollowingCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/FollowNeuronsButton.svelte
- frontend/svelte/src/lib/components/neurons/EditFollowNeurons.svelte
- frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/svelte/src/lib/components/neurons/KnownNeuronFollowItem.svelte
- frontend/svelte/src/lib/components/ui/Collapsible.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/WizardModal.svelte
- frontend/svelte/src/lib/modals/neurons/FollowNeuronsModal.svelte
- frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
- frontend/svelte/src/lib/services/accounts.services.ts
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/themes/mixins/_modal.scss
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/accounts.utils.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/svelte/src/tests/lib/modals/FollowNeuronsModal.spec.ts
- frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
- frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
User can edit followees from neuron details page.
* New modal FollowNeuronsModal used in Neuron Details.
* Read followees and use them in EditFollowNeurons screen.
* Test FollowNeuronsModal.
> L2-365: Neuron Detail follow functionality

- frontend/svelte/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/FollowNeuronsModal.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/NewFolloweeModal.spec.ts
- frontend/svelte/src/tests/lib/modals/proposals/ProposalsFilterModal.spec.ts
- frontend/svelte/src/tests/lib/modals/proposals/ProposerModal.spec.ts
- frontend/svelte/src/tests/lib/modals/proposals/VoteConfirmationModal.spec.ts
> refactor: move modal tests

- frontend/svelte/src/lib/api/dev.api.ts
- frontend/svelte/src/lib/components/common/Guard.svelte
- frontend/svelte/src/lib/components/ui/Tooltip.svelte
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/utils/optimization.utils.ts
- frontend/svelte/src/lib/utils/utils.ts
- frontend/svelte/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
- frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
Clean test logs and fix lint warnings.
* Mock some dependencies causing logs in test.
* Fix some type and lint warnings.
No new tests.
> Chore: Remove logs and warnings

- frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/tests/lib/components/neurons/NeuronCard.spec.ts
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
The remaining time until dissolution was wrong.
* Add an util that calculated the remaining time.
* Use the new util that calculated the remaining time.
* Test the new util.
> Bug: Fix dissolve delay when dissolving

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/tests/mocks/neurons.mock.ts
Remove unnecessary parameters when using nns-js methods in new version.
* Drop the "principal" parameter in "getNeuron" and "listNeurons" of the governance canister.
Fix mock for new type.
> Chore: Upgrade nns-js

- frontend/svelte/src/lib/components/neuron-detail/NeuronProposalsCard.svelte
- frontend/svelte/src/lib/components/neurons/KnownNeuronFollowItem.svelte
- frontend/svelte/src/lib/components/ui/Spinner.svelte
- frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
Fix UI issue with some Spinners in small buttons.
* Add proper classes to button when using Spinner.
* Add size prop to Spinner for a smaller spinner.
No tests. Only UI changes.
> Fix: Small Button with Spinner Issue

- frontend/svelte/README.md
Upgrade Svelte Readme
* Svelte readme updated.
No tests
> Chore: Update Svelte Readme

- frontend/svelte/package-lock.json
- frontend/svelte/package.json
- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/components/accounts/CurrentBalance.svelte
- frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/SplitNeuronButton.svelte
- frontend/svelte/src/lib/constants/icp.constants.ts
- frontend/svelte/src/lib/constants/neurons.constants.ts
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/tests/lib/api/governance.api.spec.ts
- frontend/svelte/src/tests/lib/components/accounts/CurrentBalance.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/SplitNeuronButton.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/SplitNeuronModal.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/svelte/tsconfig.json
User can split the neuron in two.
* Implement functionality of the Split Neuron button.
* Add splitNeuron service.
* Add splitNeuron api.
* New Modal to split the neuron by entering the amount.
* New neuron util neuronCanBeSplit.
* Upgrade nns-js.
* Upgrade dfinity agent, principal, and auth-client dependencies.
* Test the new service
* Test the new api
* Test the new modal
* Test new neuron util
> Feat: Neuron detail split

- frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalDetailCard.svelte
Fix title with long words (see screenshots)
https://user-images.githubusercontent.com/98811342/163041275-eddae308-2bd5-43ae-91c0-c34a7ead535c.mov
> fix: broken layout of proposal detail long title

- frontend/svelte/src/lib/components/neuron-detail/NeuronFollowingCard/NeuronFollowingCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMaturityCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/DissolveActionButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/JoinCommunityFundButton.svelte
- frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/types/errors.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/error.utils.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronFollowingCard/NeuronFollowingCard.spec.ts
- frontend/svelte/src/tests/lib/components/neurons/NeuronCard.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
Manage Authentication in Neuron Functionality and show errors accordingly.
* New helpers to get identity in neurons services "getIdentityByNeuron" and "getIdentityByNeuronOrHotkey".
* Custom Error classes for different types of errors.
* Neurons services share functionality to show toast errors on catch.
* Remove "isCurrentUserController", it was not needed.
* Add "isHotKeyControllable" neuron util.
* Adapted tests to new refactor.
* New test for new neuron util.
> Feat: Neuron Detail Manage Errors

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
Adjustment after refactoring in nns-js
- renaming: notVotedNeurons -> votableNeurons
no related tests
> refactor: notVotedNeurons -> votableNeurons

- frontend/svelte/src/lib/components/accounts/Address.svelte
- frontend/svelte/src/lib/components/accounts/NewTransactionInfo.svelte
- frontend/svelte/src/lib/components/accounts/TransactionInfo.svelte
- frontend/svelte/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/SelectDestinationAccount.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/DisburseButton.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/neurons/DisburseNeuronModal.svelte
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/DisburseButton.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/JoinCommunityFundButton.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/SplitNeuronButton.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/DisburseNeuronModal.spec.ts
User can open the Disburse Neuron Modal and select a destination account.
* New DisburseNeuronModal modal component.
* New Component TransactionInfo to share UI between steps of different wizards.
* New test for DisburseNeuronModal.
> L2-432: Disburse Neuron UI

- frontend/dart/lib/ui/neurons/following/neuron_followees_card.dart
Unknown neuron id was not being displayed when a change was made to display the names for known neurons
Unknown neuron id is now displayed
> spawn neuron id for unknown neurons is now displayed

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/AddHotkeyButton.svelte
- frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/tests/lib/api/governance.api.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/AddHotkeyButton.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/AddHotkeyModal.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
User can add a hotkey to a neuron.
* New governance api: addHotkey.
* New neuron service: addHotkey.
* New neuron action button: AddHotkeyButton.
* New modal: AddHotkeyModal.
* New test for new api function.
* New test for new neuron service.
* New test for new action button.
* New test for new modal.
> L2-357: Add hotkey functionality

- frontend/svelte/src/lib/api/governance.api.ts
eslint warning "'await' has no effect on the type of this expression"
- remove unused response object
> fix: 'await' has no effect on the type of this expression

- frontend/svelte/src/lib/api/governance.api.ts
Remove redundancy - await and return response in `Promise<void>` functions
- no test is affected
> chore: remove redundant returns

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/components/accounts/Address.svelte
- frontend/svelte/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/error.utils.ts
- frontend/svelte/src/tests/lib/api/governance.api.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/DisburseNeuronModal.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
User can disburse a neuron.
* New governance api method to disburse neuron.
* New neuron service to disburse neuron.
* "ConfirmDisburseNeuron" uses neuron service to disburse neuron.
* Test for new governance api method.
* Test for new neuron service.
* Test functionality in "DisburseNeuronModal".
> L2-432: Neuron disburse functionality

- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/IncreaseStakeButton.svelte
- frontend/svelte/src/lib/modals/accounts/NewTransactionModal.svelte
- frontend/svelte/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/actions/IncreaseStakeButton.spec.ts
- frontend/svelte/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts
User can increase the stake of a neuron with a transaction.
* New Modal IncreaseStakeNeuronModal. Reuses elements from NewTransactionModal.
* IncreaseStakeButton opens new modal.
* New test for new modal.
* New test for IncreaseStakeButton that opens modal.
> L2-362: Increase Neuron Stake

- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/AddHotkeyButton.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/tests/lib/api/governance.api.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronHotkeysCard.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
User sees the hotkeys and can remove them.
* Render list of hotkeys on NeuronHotkeysCard.
* Governance API to remove hotkey.
* Neuron service to remove hotkey.
* Test for the functionality of NeuronHotkeysCard.
* Test for new governance api function.
* Test for new neuron service.
> L2-358: Neuron Hotkey Card UI and remove function

- frontend/svelte/src/lib/constants/constants.ts
Revert https://github.com/dfinity/nns-dapp/pull/772. There was a miscommunication on the issue.
- rever constant `LIST_PAGINATION_LIMIT` to `100`
> feat: revert list proposals to 100

- frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
Resolve eslint "Hint: Variable 'title' implicitly has an 'any' type, but a better type may be inferred from usage. (ts)"
- declare title
> chore: declare title for eslint checker

- frontend/svelte/package-lock.json
- frontend/svelte/package.json
- frontend/svelte/src/lib/components/accounts/HardwareWalletConnect.svelte
- frontend/svelte/src/lib/components/accounts/HardwareWalletConnectAction.svelte
- frontend/svelte/src/lib/components/accounts/HardwareWalletInfo.svelte
- frontend/svelte/src/lib/components/accounts/HardwareWalletName.svelte
- frontend/svelte/src/lib/components/proposals/ProposalMeta.svelte
- frontend/svelte/src/lib/constants/ledger.constants.ts
- frontend/svelte/src/lib/errors/ledger.errors.ts
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/identities/ledger.identity.ts
- frontend/svelte/src/lib/keys/secp256k1.ts
- frontend/svelte/src/lib/modals/accounts/AddAccountModal.svelte
- frontend/svelte/src/lib/proxy/ledger.services.proxy.ts
- frontend/svelte/src/lib/services/ledger.services.ts
- frontend/svelte/src/lib/themes/button.scss
- frontend/svelte/src/lib/themes/mixins/_modal.scss
- frontend/svelte/src/lib/themes/variables.scss
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/ledger.utils.ts
- frontend/svelte/src/tests/lib/components/accounts/HardwareWalletConnect.spec.ts
- frontend/svelte/src/tests/lib/components/accounts/HardwareWalletConnectAction.spec.ts
- frontend/svelte/src/tests/lib/components/accounts/HardwareWalletInfo.spec.ts
- frontend/svelte/src/tests/lib/components/accounts/HardwareWalletName.spec.ts
- frontend/svelte/src/tests/lib/keys/secp256k1.spec.ts
- frontend/svelte/src/tests/lib/services/ledger.services.spec.ts
- frontend/svelte/src/tests/lib/utils/ledger.utils.spec.ts
- frontend/svelte/src/tests/mocks/auth.store.mock.ts
- frontend/svelte/src/tests/mocks/ledger.identity.mock.ts
Add feature to connect hardware wallet to an account.
- integrate `ledger.identity` and `secp256k1`
- add `connectToHardwareWallet` service
- chunk service
- implement component to connect hardware wallet
- translate and throw errors
- add dependencies `@ledgerhq/hw-transport-node-hid-noevents`, `@ledgerhq/hw-transport-webhid` and `@zondax/ledger-icp`
> feat: connect hardware wallet

- frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
- frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronHotkeysCard.spec.ts
Hide button to remove hotkeys unless user is controller.
* Hide button to remove hotkeys unless user is controller.
* Add test case in component test.
> L2-512: Hide remove hotkeys if not controller

- frontend/svelte/package-lock.json
Bump the nns-js to fix payload rendering (candid update)
> bump nns-js

- frontend/svelte/src/lib/components/ui/Toasts.svelte
- frontend/svelte/src/lib/stores/toasts.store.ts
- frontend/svelte/src/lib/types/toast.ts
- frontend/svelte/src/tests/lib/components/ui/Toasts.spec.ts
- frontend/svelte/src/tests/lib/components/ui/ToastsTest.svelte
Clean code.
* Remove wrapper always present in Toasts.
* Use symbol instead of number for ToastMsg id.
* Update Toasts Tests
> Fix: Clean Notifications Code

- frontend/ts/src/ServiceApi.ts
Update message displayed for new features that are not yet supported with the hardware wallet.
Mischa's input.
> feat: update verify hardware wallet v2 message

- frontend/svelte/src/lib/modals/Modal.svelte
- frontend/svelte/src/lib/themes/theme.scss
Style of scrollbar will have dark theme so that anytime a scrollbar will be shown, the default style is shown.
Also light modal will have light theme scrollbar.
> L2 345 style scrollbar

- frontend/dart/lib/ic_api/platform_ic_api.dart
- frontend/dart/lib/ic_api/web/service_api.dart
- frontend/dart/lib/ic_api/web/web_ic_api.dart
- frontend/dart/lib/ui/neurons/detail/neuron_rewards_card.dart
Spawning neuron for hardware wallet with slider option has not been implemented yet
For hardware wallet , we will show Spawn neuron based on full maturity
> spawn neuron will not give slider option for hardware wallet

- frontend/svelte/src/lib/api/governance.api.ts
- frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
- frontend/svelte/src/lib/identities/ledger.identity.ts
- frontend/svelte/src/lib/services/accounts.services.ts
- frontend/svelte/src/lib/services/neurons.services.ts
- frontend/svelte/src/tests/lib/api/governance.api.spec.ts
- frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
User can create a neuron from a hardware wallet linked account.
* Change "stakeNeuron" governance api function's signature.
* Add methods to LedgerIdentity.
PENDING TESTS
> L2-516: Create neuron hardware wallet

- frontend/svelte/package.json
Fix broken local setup.
* Local build points to nnsdapp_both instead of testnet.
Not Applicable
> Fix: local setup uses nnsdapp_both environment

- dfx.json
Add small06 testnet to dfx to deploy and connect local development.
* Add a new network "small06" to dfx.json
> Chore: add small06 to dfx

- frontend/svelte/src/lib/components/accounts/AddAccountType.svelte
- frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
- frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/svelte/src/lib/modals/Modal.svelte
- frontend/svelte/src/lib/themes/mixins/_modal.scss
Review PR #820 and provide suggestions.
It contains some changes for the modal height ("small and medium height modals") but also some few changes for the spacing on mobile devices as I tested the size on the modal on such devices too.
> style: modal height review

- frontend/svelte/package-lock.json
- frontend/svelte/src/lib/components/accounts/Address.svelte
- frontend/svelte/src/lib/components/ui/Input.svelte
- frontend/svelte/src/lib/components/ui/InputWithError.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/accounts.utils.ts
- frontend/svelte/src/tests/lib/components/accounts/Address.spec.ts
- frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
- frontend/svelte/src/tests/mocks/accounts.store.mock.ts
User sees an invalid account error on blur.
* Use same nns-js validation on blur for the Address component.
* Update broken tests.
* Add new test for new use case of error appearing on blur.
> L2-479: Validate account id client

- e2e-tests/components/accounts-tab.ts
- e2e-tests/specs/user-A02-create-linked-account.e2e.ts
- frontend/svelte/src/lib/components/accounts/AccountCard.svelte
- frontend/svelte/src/lib/components/accounts/AddAccountType.svelte
We need end to end tests for all the manual tests.  This PR addresses [User_A02 Create new linked account](https://www.notion.so/NNS-Dapp-Manual-Testing-Accounts-87b7b439dd6a4f94b1459916f6b6a09c#028295f8c51e4c8fac692371602c4bc4)
- Fix the method for getting an account - wdio selectors don't work like that.
- Add a method to the accounts tab for creating a linked account
- Add a test to verify that the account appears
This is a test - see CI for the results! :-)
> E2e Accounts: Can create linked account

- frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
- frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
- frontend/svelte/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte
- frontend/svelte/src/lib/types/i18n.d.ts
Change some wordings to adapt better to the use case and meanings.
* SetDissolveDelay and ConfirmDissolveDelay have a new prop to set the button text.
* Change Kyc to KYC. KYC is an acronym: Know Your Customer.
> Fix: Change wordings

- frontend/svelte/package-lock.json
- frontend/svelte/package.json
We need nicely formatted bitcoin proposals
Bump nns-js
> Upgrade nns-js

- frontend/svelte/src/lib/api/canisters.api.ts
- frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
- frontend/svelte/src/lib/components/canister_details/DetachCanisterButton.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/services/canisters.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/routes/CanisterDetail.svelte
- frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
- frontend/svelte/src/tests/lib/canisters/nns-dapp.canister.spec.ts
- frontend/svelte/src/tests/lib/components/canister_details/DetachActionButton.spec.ts
- frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
User can detach a canister.
* Add a DetachCanisterButton in CanisterDetails route.
* New detachCanister method in NNSDappCanister.
* New canister api detachCanister.
* New canister service detachCanister.
* Test user flow to detach a canister.
* Test for NNSDappCanister method detachCanister and attachCanister (I forgot before).
* Test api function detachCanister.
* Test canister service detachCanister.
> L2-597: Detach Canister

- frontend/svelte/src/lib/components/canisters/SelectCyclesCanister.svelte
> style: align center cycle inputs

- frontend/svelte/src/App.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/services/seed-neurons.services.ts
- frontend/svelte/src/lib/types/i18n.d.ts
Function to claim seed neurons. Not exposed yet to the user.
* Add service "seed-neurons" with single function.
* Bump nns-js. Needed to use the Genesis Token Canister.
* This is temporary until users all the proper users claim their neurons.
> Feat: Claim Seed Neurons

- frontend/svelte/src/lib/components/canister_details/RemoveCanisterControllerButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/icons/IconClose.svelte
- frontend/svelte/src/lib/themes/mixins/_card.scss
Use IconClose instead of letter X for buttons that remove delete a resource.
* Change the X in two buttons for IconClose
* Add size prop to IconClose.
Only UI changes, no extra tests added.
> L2-601: Change X for IconClose

- frontend/svelte/src/lib/i18n/en.json
- frontend/svelte/src/lib/services/debug.services.ts
- frontend/svelte/src/lib/services/seed-neurons.services.ts
- frontend/svelte/src/lib/stores/busy.store.ts
- frontend/svelte/src/lib/types/i18n.d.ts
- frontend/svelte/src/lib/utils/dev.utils.ts
User can claim seed neurons.
* Add option in "triggerDebugReport" to claim seed neurons.
No tests.
> L2-711: Add claim neurons debug store

- frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalActions.svelte
Improves semantic: the Json component contains `ul` which semantically should not be children of `p`.
`<ul><h4><p>` -> `<dl><dt><dd>`
> fix: ProposalAction semantic

- frontend/svelte/README.md
Update Svelte Readme.
* Change Svelte Readme.
> Chore: Update Readme

- frontend/svelte/src/App.svelte
- frontend/svelte/src/lib/components/sns-project-detail/ProjectInfoSection.svelte
- frontend/svelte/src/lib/components/sns-project-detail/ProjectStatusSection.svelte
- frontend/svelte/src/lib/components/ui/TwoColumns.svelte
- frontend/svelte/src/lib/constants/routes.constants.ts
- frontend/svelte/src/lib/themes/variables.scss
- frontend/svelte/src/lib/utils/app-path.utils.ts
- frontend/svelte/src/routes/SNSProjectDetail.svelte
- frontend/svelte/src/tests/lib/utils/app-path.utils.spec.ts
- frontend/svelte/src/tests/routes/SNSProjectDetail.spec.ts
User has access to an emtpy SNS Project Detail page in Testnets.
* Add new Route SNSProjectDetail which redirects to accounts if not testnet.
* Add new path SNSProjectDetail to AppPath `/sns-project/...`.
* Add new path to exceptions for isAppPath.
* Setup SNSProjectDetail route test.
* Add test cases in isAppPath test suite.
> L2-732: SNS Project Detail Setup

- frontend/svelte/src/lib/stores/neurons.store.ts
- frontend/svelte/src/lib/utils/neuron.utils.ts
- frontend/svelte/src/routes/NeuronDetail.svelte
- frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
Remove unnecessary neuronSelectStore.
* Use an util to get the neuron instead of using a store.
* Remove unused neuronSelectStore.
* Add tests for the new util.
> Chore: Remove unnecessary neuronSelectStore

- frontend/svelte/src/lib/components/header/Back.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/MergeMaturityButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte
- frontend/svelte/src/lib/components/neuron-detail/actions/SplitNeuronButton.svelte
- frontend/svelte/src/tests/lib/components/common/Layout.spec.ts
User on Android can't merge maturity or spawn neuron.
* Do not show Tooltip on enabled buttons.
* Change test of Back button.
> L2-761: Cannot merge maturity and spawn on Android

- frontend/svelte/src/lib/components/sns-launchpad/SNSProjectCard.svelte
- frontend/svelte/src/lib/components/sns-launchpad/SNSProjects.svelte
- frontend/svelte/src/lib/components/sns-launchpad/SNSProposals.svelte
- frontend/svelte/src/lib/components/ui/CardGrid.svelte
- frontend/svelte/src/routes/SNSLaunchpad.svelte
- frontend/svelte/src/tests/lib/components/sns-launchpad/SNSLaunchpadProjects.spec.ts
- frontend/svelte/src/tests/lib/components/sns-launchpad/SNSProject.spec.ts
- frontend/svelte/src/tests/lib/components/ui/CardGrid.spec.ts
- frontend/svelte/src/tests/lib/components/ui/CardGridTest.svelte
- frontend/svelte/src/tests/routes/SNSLaunchpad.spec.ts
Show sns projects in the grid.
https://dfinity.atlassian.net/browse/L2-750
https://user-images.githubusercontent.com/98811342/176287827-7b1e03e1-1305-4e5c-b335-5f97e28f2434.mov
- CardsGrid component
- move titles to the launchpad to apply styling in one place
- SNSProject -> SNSProjectCard
- CardsGrid component
> L2 750 cards container

- frontend/svelte/src/lib/components/sns-launchpad/SNSProjectCard.svelte
- frontend/svelte/src/lib/constants/routes.constants.ts
- frontend/svelte/src/lib/stores/route.store.ts
- frontend/svelte/src/routes/ProposalDetail.svelte
Update sns routing.
[L2-773](https://dfinity.atlassian.net/browse/L2-773)
- `/sns-launchpad` -> `/launchpad`
- navigation to project details
- navigation back to launchpad from proposal info
> L2 773 update sns routing

- frontend/svelte/src/lib/components/sns-project-detail/ProjectStatusSection.svelte
- frontend/svelte/src/lib/components/ui/TwoColumns.svelte
- frontend/svelte/src/lib/themes/variables.scss
- frontend/svelte/src/tests/mocks/sns-projects.mock.ts
Button to participate in a swap is not attached to the bottom.
* TwoColumns does not extend second column the whole height.
* Actions do not align at the end.
* Only CSS changes.
> Fix: Button in Project Detail not bottom

- frontend/svelte/src/lib/components/neuron-detail/NeuronFollowingCard/NeuronFollowingCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronJoinFundCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMaturityCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
- frontend/svelte/src/lib/components/neuron-detail/NeuronProposalsCard.svelte
- frontend/svelte/src/routes/NeuronDetail.svelte
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronJoinFundCard.spec.ts
- frontend/svelte/src/tests/lib/components/neuron-detail/NeuronMetaInfoCard.spec.ts
Realign buttons in the Neuron Detail page
* Move Join Community Fund to its own card.
* Realign buttons to the left.
* Refactor some classes and CSS.
* Update tests for NeuronMetaInfoCard.
* New test for NeuronJoinFundCard.
> L2-789: Neuron detail realignment

- frontend/svelte/src/lib/themes/themes/dark.scss
> fix: remove header glow

- frontend/svelte/src/lib/components/header/Logout.svelte
Fix the size of the logout icon on the top right menu.
* Set height as well as width for svg inside the Logout button.
Only style changes
> Fix: Logout svg size

- frontend/svelte/src/lib/components/accounts/SelectAccountDropdown.svelte
- frontend/svelte/src/lib/components/project-detail/ParticipateScreen.svelte
- frontend/svelte/src/lib/components/ui/Dropdown.svelte
- frontend/svelte/src/lib/components/ui/DropdownItem.svelte
- frontend/svelte/src/lib/themes/button.scss
- frontend/svelte/src/lib/themes/variables.scss
- frontend/svelte/src/lib/types/common.ts
- frontend/svelte/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
- frontend/svelte/src/tests/lib/components/ui/Dropdown.spec.ts
- frontend/svelte/src/tests/lib/components/ui/DropdownTest.svelte
User sees a nice Dropdown.
* New Dropdown UI component.
* SelectAccountDropdown uses new Dropdown UI Component.
* Test for Dropdown UI component
* Test for SelectAccountDropdown component
> L2-800: Dropdown Select Account

- frontend/svelte/src/routes/Wallet.svelte
Fix transaction text duplication in Wallet Page.
* Remove duplication text.
> Fix: New transaction text

- frontend/svelte/src/lib/components/common/MaxButton.svelte
- frontend/svelte/src/lib/components/project-detail/ParticipateScreen.svelte
- frontend/svelte/src/lib/components/ui/AmountInput.svelte
- frontend/svelte/src/lib/icons/IconSubdirectory.svelte
- frontend/svelte/src/tests/lib/components/common/MaxButton.spec.ts
- frontend/svelte/src/tests/lib/components/ui/AmountInput.spec.ts
Add icon to the Max button for amount of ICP
* New component MaxButton.
* New icon component IconSubdirectory.
* Reuse AmountInput also in ParticipationScreen.
* Tests for new MaxButton component
> L2-825: Max button with icon

- frontend/svelte/src/lib/api/ledger.api.ts
> chore: log typo

- frontend/svelte/src/lib/components/ui/Dropdown.svelte
- frontend/svelte/src/lib/components/ui/Input.svelte
- frontend/svelte/src/lib/themes/button.scss
- frontend/svelte/src/lib/themes/mixins/_form.scss
- frontend/svelte/src/lib/themes/mixins/_select.scss
- frontend/svelte/src/lib/themes/themes/dark.scss
- frontend/svelte/src/lib/themes/themes/light.scss
Adapt some elements to Dark mode for the new design.
* Use css variables that are changed per theme for inputs.
* Change secondary button style to adapt to new dark model
Only style changes.
> L2-824: Elements in Dark Mode

- frontend/svelte/package-lock.json
Upgrade nns-js to be able to leave community fund.
* Change nns-js version.
* Not applicable
> Fix: Upgrade nns-js

- .gitignore
- CHANGELOG.md
Release candidate for 18th of July of 2022. Deployed 19th of July of 2022.
* Changelog
> Release 2022-07-19

- frontend/svelte/src/lib/components/project-detail/CommitmentProgressBar.svelte
- frontend/svelte/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/svelte/src/lib/components/project-detail/ProjectStatusSection.svelte
- frontend/svelte/src/tests/lib/components/project-detail/CommitmentProgressBar.spec.ts
- frontend/svelte/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts
Display min and max swap commitment.
- extract content to a dedicated component
- display values from swap store
- add todo for current commitment
- fix progress bar by displaying max value as well
> feat: display swap commitment

- frontend/svelte/package-lock.json
- frontend/svelte/package.json
Redo sns and nns js nightly to easily get last nns and sns js changes
> build: redo sns and nns js nightly

- CHANGELOG.md
Release candidate for 20th of July of 2022.
* Changelog
Not applicable
> Release 2022-07-20

- frontend/svelte/src/lib/stores/projects.store.ts
The demo does not find place therefore we can redo the sns projects store.
> feat: redo open sns projects store

- .gitignore
- frontend/package-lock.json
- frontend/src/lib/api/sns.api.ts
- frontend/src/lib/components/project-detail/ReviewParticipate.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/sns.services.ts
- frontend/src/lib/stores/busy.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/api/sns.api.spec.ts
- frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
Use can participate in a swap
* New sns service "participateISwap"
* New sns api function " participateInSnsSwap"
* ParticipateSwapModal uses new sns service to submit participation.
* Finish test of ParticipateSwapModal
* Add test for new sns service
* Add test for new sns api function
> L2-797: Swap participation functionality

- frontend/src/lib/components/accounts/HardwareWalletInfo.svelte
Update color of values  in HW modal.
- added `value` class
Only style update.
> style: attach HW values

- frontend/src/lib/components/neuron-detail/ConfirmSpawnHW.svelte
- frontend/src/lib/components/neuron-detail/NeuronMaturityCard.svelte
- frontend/src/lib/components/neuron-detail/SelectPercentage.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/icp.utils.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NeuronMaturityCard.spec.ts
- frontend/src/tests/lib/modals/neurons/MergeMaturityModal.spec.ts
- frontend/src/tests/lib/modals/neurons/SpawnNeuronModal.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Display maturity as an absolute value.
- update maturity formatting
- adjusted current tests
> Update maturity formatting

- frontend/src/lib/api/dev.api.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/static/assets/libs/dummy-proposals.utils.js
Create SNS proposals in testnet using pending proposals in the testnet.
* Add swapCanisterId param to make proposal functions.
* Read snsSummariesStore in makeDummyProposals service and select a pending proposal.
Only for testnet.
> Chore: Make Pending Sns Proposal

- CHANGELOG.md
> Release: 2022-07-28

- frontend/src/lib/i18n/en.json
Update text of maturity description.
> i18n: update maturity description

- CHANGELOG.md
Release for 29th of July of 2022
> Release 2022-07-29

- dfx.json
- e2e-tests/scripts/nns-canister.Dockerfile
- e2e-tests/scripts/nns-canister.patch
Some changes needed for demos
* Added a testnet config for dalves
* Patched the swap canister to allow closing in the "past"
> Demo tweaks

- frontend/package-lock.json
- frontend/package.json
Update nightly version of the lib that use agent-js v0.12.2
> build: update nns, sns and agent-js

- frontend/src/lib/api/sns.api.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/api/sns.api.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Add functionality only to add a hotkey to an sns neuron.
* New sns api function addNeuronPermissions
* New sns neuron service addHotkey which uses addNeuronPermissions.
* Add test for new sns api function
* Add test for new sns neuron service
> L2-871: Add Hotkey Functionality

- frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
Fix highlighted project value colors.
- remove color from `dd`
- add selectively `value` class
> style: fix highlighted project value colors

- frontend/src/lib/components/project-detail/ReviewParticipate.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
- frontend/src/lib/components/sns-neuron-detail/actions/AddSnsHotkeyButton.svelte
- frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
- frontend/src/lib/constants/style.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/themes/variables.scss
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/routes/SnsNeuronDetail.svelte
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts
- frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
- frontend/src/tests/routes/SnsNeuronDetail.spec.ts
Users can see the details of their sns neurons.
* Implement page component SnsNeuronDetail
* New component SnsNeuronHotkeysCard
* New component SnsNeuronMetaInfoCard
* New sns neuron utils canIdentityManageHotkeys and getSnsNeuronHotkeys
* Test for new components
* Test for new utils
* Update test for SnsNeuronDetail
> L2-866: SNS Neuron Details UI

- e2e-tests/package-lock.json
Update chrome driver for e2e test
Update chromedriver
Not applicable
> Fix: Update chromedriver

- frontend/src/lib/i18n/en.json
Improve message when user needs to open IC app on hardware wallet.
* Message change.
Only text change.
> Fix: Improve HW message

- frontend/package-lock.json
- frontend/src/App.svelte
- frontend/src/lib/components/common/Footer.svelte
- frontend/src/lib/components/common/Layout.svelte
- frontend/src/lib/components/common/RouteModule.svelte
- frontend/src/lib/components/neurons/NnsNeuronsFooter.svelte
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/stores/layout.store.ts
- frontend/src/lib/themes/legacy.scss
- frontend/src/routes/Accounts.svelte
- frontend/src/routes/CanisterDetail.svelte
- frontend/src/routes/Canisters.svelte
- frontend/src/routes/Launchpad.svelte
- frontend/src/routes/NeuronDetail.svelte
- frontend/src/routes/Neurons.svelte
- frontend/src/routes/ProjectDetail.svelte
- frontend/src/routes/ProposalDetail.svelte
- frontend/src/routes/Proposals.svelte
- frontend/src/routes/SnsNeuronDetail.svelte
- frontend/src/routes/Wallet.svelte
- frontend/src/tests/lib/components/neurons/NnsNeuronsFooter.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
The position of the footer in the legacy layout is broken, these components aren't sticky anymore
This PR introduces no function changes. Code that moved was refactored 1 to 1.
- update `gix-components` that defer responsibility of using `main` and `footer` elements to consumer
- add `main` or `main class="legacy" to all pages
- refactor `<Neurons />` page because `footer` needs to be a direct descendant to inherit position in all set up
- `footer` style position absolute move to `gix-components`
> fix: legacy layout footer

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
User should not be able to commit if the amount is over the total maximum.
* Add one more check in "validParticipation" project util.
* Add test for new case.
> L2-944: Do not allow commitments above max

- CHANGELOG.md
Propose feature "optimistic voting update".
Release Aug. 16 2022.
> Release 2022-08-16

- CHANGELOG.md
keep track of proposals in changelog.
> docs: document last proposals

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/transactions.utils.ts
User can see the Participate Swap in the transaction list.
* Add ParticipateSwap in the AccountTransactionType enum.
* Add related entry in i18n key.
> L2-946: Handle ParticipateSwap transaction type

- frontend/src/lib/components/ui/Tag.svelte
Fix incorrect tag height on proposal.
> style: fix tag height

- CHANGELOG.md
Release for 24th of August of 2022
> Release: 2022-08-23

- frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
- frontend/src/lib/components/ui/SkeletonDetails.svelte
- frontend/src/routes/ProjectDetail.svelte
User has a nice loading page while project is loading.
* New SkeletonDetails component.
* Use new SkeletonDetails component and keep grid while loading in ProjectDetail.
None. Only substituted a Spinner for a nicer loading UI.
> L2-702: Project Detail skeleton

- frontend/src/lib/services/debug.services.ts
- frontend/src/lib/stores/debug.store.ts
- frontend/src/lib/types/sns.ts
- frontend/src/lib/utils/anonymize.utils.ts
- frontend/src/routes/ProjectDetail.svelte
Debugger is not working.
* Add an empty store for those stores that are initialized in a component.
* Add projectDetailStore to the debug store.
> L2-898: Fix debugger

- frontend/package-lock.json
- frontend/src/lib/components/proposal-detail/IneligibleNeuronsCard.svelte
- frontend/src/lib/components/proposal-detail/ProposalDetailCard/ProposalMeta.svelte
- frontend/src/lib/components/proposal-detail/ProposalDetailCard/ProposalSummary.svelte
- frontend/src/lib/components/proposal-detail/ProposalProposerInfoSection.svelte
- frontend/src/lib/components/proposal-detail/ProposalSystemInfoEntry.svelte
- frontend/src/lib/components/proposal-detail/ProposalSystemInfoProposerEntry.svelte
- frontend/src/lib/components/proposal-detail/ProposalSystemInfoSection.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.svelte
- frontend/src/lib/components/ui/Collapsible.svelte
- frontend/src/lib/components/ui/KeyValuePairInfo.svelte
- frontend/src/tests/lib/components/proposal-detail/ProposalSystemInfoProposerEntry.spec.ts
Review input from Mischa about current new design of the proposal detail page. 
This PR 👉 PR #1298 👉 main
- some style updates
- move proposal title next to rendered markdown and style the div with a background
> style: review proposal detail page current new design

- frontend/package-lock.json
- frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingCard.spec.ts
If there are no neurons at all, the "Neurons" collapsible element can be simply not displayed.
- display voting section only if there are neurons
> feat: don't display neurons collapsible if no neurons

- .github/workflows/checks.yml
- rs/src/accounts_store.rs
- rs/src/assets.rs
- rs/src/proposals.rs
> update cargo-test rust version

- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/types/i18n.d.ts
- rs/Cargo.toml
- rs/src/periodic_tasks_runner.rs
- rs/src/proposals.rs
Add new proposal payload type `ChangeSubnetMembershipPayload`
- update to latest blessed version - https://dashboard.internetcomputer.org/proposal/80992 (8a5509ebb162d084d8b38fc5213f3a78c9fc9801)
- add ChangeSubnetMembershipPayload to payloads
> feat: add new payload type AddSnsWasm:31

- frontend/src/lib/i18n/en.governance.json
- rs/src/proposals.rs
Update payload `ChangeSubnetMembership` description.
> i18n: update description

- dfx.json
- rs/src/accounts_store.rs
Set features flags for release of 21st September 2022
* VOTING_UI set to "modern".
Not applicable
> Chore: Set feature flags release

- frontend/src/tests/lib/api/sns.api.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
- frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
Follow-up of #1347 which was auto-merged even though tests were failing.
- adapt tests for new candid files generated with last didc
> test: fix conversion for last candid files generated with didc

- dfx.json
- e2e-tests/scripts/nns-canister-download
- e2e-tests/scripts/nns-canister.Dockerfile
Fix e2e test failing.
* Change IC_COMMIT
> Fix: Use latest IC commit

- frontend/package-lock.json
- frontend/src/lib/components/ui/Input.svelte
- apply custom style for input on iOS
- fix button width when toggling disable and enable
> style: apply custom style on iOS and button width

- frontend/src/lib/modals/LegacyModal.svelte
> style: fix ipad modal height

- frontend/package-lock.json
- frontend/src/lib/api/sns-ledger.api.ts
- frontend/src/lib/components/accounts/NewTransactionAmount.svelte
- frontend/src/lib/components/accounts/NewTransactionReview.svelte
- frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
- frontend/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
- frontend/src/lib/components/neurons/NeuronCard.svelte
- frontend/src/lib/components/project-detail/CommitmentProgressBar.svelte
- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
- frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte
- frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
- frontend/src/lib/derived/main-transaction-fee.derived.ts
- frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
- frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
- frontend/src/lib/modals/accounts/NewTransaction/TransactionReview.svelte
- frontend/src/lib/modals/neurons/SplitNeuronModal.svelte
- frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/utils/transactions.utils.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
- frontend/src/tests/lib/api/ledger.api.spec.ts
- frontend/src/tests/lib/components/accounts/NewTransactionInfo.spec.ts
- frontend/src/tests/lib/components/accounts/NewTransactionReview.spec.ts
- frontend/src/tests/lib/services/accounts.services.spec.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
- frontend/src/tests/lib/utils/icp.utils.spec.ts
- frontend/src/tests/lib/utils/transactions.utils.spec.ts
Upgrade nns-js.
* Fix usage of `TokenAmount` factory functions to pass always `token` parameter.
* Remove casting when using `fromNumber`.
* Fixed broken tests.
> GIX-1005: Improve Token Amount Class

- frontend/src/lib/components/project-detail/ProjectTimeline.svelte
- frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
- frontend/src/lib/modals/accounts/NewTransaction/TransactionReview.svelte
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/lib/utils/sns.utils.ts
- frontend/src/tests/lib/components/project-detail/ProjectTimeline.spec.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
Fix timeline after API breaking changes. Only show the deadline, no progress bar.
* Remove ProgressBar from ProjectTimeline component.
* Remove swapDuration and durationTillSwapStart utils.
* Use token param in ReviewTransaction instead of token from context. We are in a project context, but using ICPs.
* Enable logo to be nullish from backend. For now added empty string. Issue to use a default logo created.
* Remove test cases for progress bar in ProjectTimeline.
* Remove tests for utils.
> GIX-1031: Project timeline

- frontend/package-lock.json
Bump ic-js nightly libraries that introduce stake maturity and auto stake maturity features.
> build: ic-js nightly

- frontend/src/lib/components/accounts/HardwareWalletInfo.svelte
- frontend/src/lib/components/accounts/TransactionInfo.svelte
- frontend/src/lib/components/canister-detail/NewControllerReview.svelte
- frontend/src/lib/components/canisters/CanisterIdInfo.svelte
- frontend/src/lib/components/canisters/ConfirmCyclesCanister.svelte
- frontend/src/lib/components/neuron-detail/ConfirmSpawnHW.svelte
- frontend/src/lib/components/neuron-detail/SelectPercentage.svelte
- frontend/src/lib/components/neurons/AddUserToHotkeys.svelte
- frontend/src/lib/components/neurons/ConfirmDissolveDelay.svelte
- frontend/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
- frontend/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/neurons/StakeNeuron.svelte
- frontend/src/lib/components/project-detail/ProjectTimeline.svelte
- frontend/src/lib/modals/LegacyWizardModal.svelte
- frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
- frontend/src/lib/modals/accounts/NewTransaction/TransactionReview.svelte
- frontend/src/lib/modals/canisters/AddCyclesModal.svelte
- frontend/src/lib/modals/neurons/SplitNeuronModal.svelte
Add consistency in labels.
* Change h5 used as labels for `p class="label"`.
* Use KeyValuePair in ProjectTimeline
* Set color in LegacyWizardModal to background-contrast.
Only style changes.
> Chore: UI Improvements

- frontend/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/src/lib/i18n/en.json
All topics followees does not include SNS Decentralized Sale topic.
* Change title and description for "All Topics" to make clear it does not include SNS.
Only text changes.
> GIX-1060: Rename text for all topics followees

- dfx.json
- frontend/jest-setup.ts
- frontend/jest-spy.ts
- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/lib/utils/app-path.utils.ts
- frontend/src/routes/Accounts.svelte
- frontend/src/routes/LegacyWallet.svelte
SNS-1 does not include sns accounts.
* Add a new feature flag ENABLE_SNS_2
* Use the new feature flag in all sns accounts related components.
Not applicable
> GIX-1041: Add feature flag sns-2

- frontend/package-lock.json
- frontend/src/lib/components/ui/ProgressBar.svelte
- frontend/src/lib/themes/mixins/_select.scss
The css variable for the input box-shadow has been renamed.
- update css variable name
- update gix-cmp
> style: fix input box-shadow

- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/workers/auth.worker.ts
Bump agent-js v0.14.0.
Release notes: https://github.com/dfinity/agent-js/releases/tag/v0.14.0
Related ic-js PR: https://github.com/dfinity/ic-js/pull/212
> build: bump agent-js v0.14.0

- CHANGELOG.md
Release of 7th of October of 2022
* Changelog
> Release 2022-10-07

- CHANGELOG.md
Release for 13th October of 2022
* Changelog
> Release: 2022-10-13

- dfx.json
Enable Stake Maturity functionality in prod.
* Set STAKE_MATURITY to "true" for staging and mainnet
> Chore: Enable STAKE_MATURITY

- CHANGELOG.md
Second release for 13th of October of 2022
* Changelog
> Release: 2022-10-13-2

- CHANGELOG.md
Third release of 13th of October 2022.
* Changelog
> Release: 2022-10-13-3

- frontend/src/lib/components/neuron-detail/actions/StakeMaturityButton.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neuron-detail/actions/StakeMaturityButton.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
>  But I agree if maturity =0 then we can disable the button. - Product
- disable stake maturity button is maturity is zero or less
> feat: disable stake maturity button if maturity zero or less

- Cargo.lock
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/types/i18n.d.ts
- rs/Cargo.toml
- rs/src/accounts_store.rs
- rs/src/canisters/ledger.rs
- rs/src/ledger_sync.rs
- rs/src/main.rs
- rs/src/multi_part_transactions_processor.rs
- rs/src/periodic_tasks_runner.rs
- rs/src/proposals.rs
Add `UpdateSnsWasmSnsSubnetIds` nnsFunction support.
https://dfinity.atlassian.net/browse/GIX-1083
[related `ic` update](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/8107/diffs)
- add nnsFunction labels
- updated revision hashes
- add `UpdateSnsSubnetListRequest` proposal
- tested manually with available demo proposals
> feat: UpdateSnsWasmSnsSubnetIds proposal support

- frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/types/i18n.d.ts
"Type" shows undefined for OpenSnsTokenSwap actions.
* Add i18n label for OpenSnsTokenSwap action
> Fix: Add i18n label for OpenSnsTokenSwap action

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Branch for release of 19th of October 2022.
* Changelog
* NNS-Dapp version
> Release: 2022-10-19

- HOWTO.md
Extend the HOWTO with `Payload Definition Search Sample Steps` using `UpdateSnsWasmSnsSubnetIds` as a sample.
> Payload update sample howto

- frontend/src/lib/i18n/en.governance.json
According @dylancm4 there should be a period at the end of the descriptions in `en.governance.json`.
> feat: add period at the end of description

- dfx.json
Be able to work locally pointing to small14
* Add small14 to list of networks in dfx.json
Not applicable
> Chore: Add small14 to dfx.json

- HOWTO.md
- frontend/package-lock.json
- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
- frontend/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/src/lib/components/proposals/ProposalsFilters.svelte
- frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/constants/proposals.constants.ts
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/proposals/ProposalsFilterModal.svelte
- frontend/src/lib/services/sns.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/proposals/ProposalsFilters.spec.ts
- frontend/src/tests/lib/modals/proposals/ProposalsFilterModal.spec.ts
- frontend/src/tests/lib/utils/enum.utils.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/static/assets/libs/dummy-proposals.utils.js
Add new proposals topics.
Fix minor issues brought up after SNS-1
* Remove `detailed` in the stake amount of the SnsNeuronCard. Otherwise the amount in the stake and in the balance after disbursing the neuron didn't match, for example: 0.99995 in the neuron, was 1 in the balance.
* Change "Decentralized Sale" for "Decentralizatoin Sale"
* Improvements in the HOW_TO for adding a new proposal topic.
* Update next libraries
* Filter out deprecated topics (SNS in the list of topics to follow: "SnsDecentralizationSale" for now.
* Remove sns decentralization sale proposal from dummy proposals.
* Add new topics labels.
* New test case in topicsToFollow.
> GIX-1061: New proposal topic sns sale

- frontend/package-lock.json
- frontend/src/lib/components/launchpad/Projects.svelte
- frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte
- frontend/src/lib/constants/proposals.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/routes/Launchpad.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/launchpad/Projects.spec.ts
- frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts
- frontend/src/tests/lib/routes/Launchpad.spec.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
- frontend/src/tests/mocks/sns.api.mock.ts
Final and minor improvements for SNS-1 launch.
* Hide Committed projects title if no committed projects.
* Change message when no current launches.
* Add total amount of SNS tokens in Project Details page.
* Add new SnsAndCommunityFund topic to default topics.
* Test new case in Launchpad.
* Test new info in ProjectSwapDetails.
> GIX-1101: Minor improvements SNS-1

- frontend/package-lock.json
Switch ic-js libs version to next minor `next` versions.
> build: bump ic-js v0.10.0 next

- e2e-tests/common/navigator.ts
- e2e-tests/components/nav.ts
- frontend/package-lock.json
- frontend/src/tests/lib/components/common/Layout.spec.ts
- frontend/src/tests/lib/components/common/RouteModule.spec.ts
Update gix cmp that contains an improvement to sanitize `_blank` target in links and the new menu design.
> build: update gix cmp for link _blank and menu

- frontend/package-lock.json
Small spinner is notably broken because there was a typo in the new fonts CSS sizes.
Fix in gix-cmp https://github.com/dfinity/gix-components/pull/108
> style: fix spinner

- frontend/package-lock.json
An offset for the content was mising when the test banner - and only when - is displayed.
- integrate gix-cmp PR https://github.com/dfinity/gix-components/pull/109
> style: content banner offset

- CHANGELOG.md
- frontend/package.json
- rs/Cargo.toml
Release-2022-11-09
- update changelog
> Release-2022-11-09

- frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
Improve the location of the Participate button for small devices.
* Wrap Participate button with BottomSheet.
No tests, only UI changes.
> Chore: Improve Participate Button

- frontend/package-lock.json
- frontend/src/lib/api/sns-wrapper.api.ts
- frontend/src/lib/api/sns.api.ts
- frontend/src/lib/components/neurons/SnsNeuronsFooter.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/NewTransaction/TransactionReview.svelte
- frontend/src/lib/modals/sns/StakeSnsNeuronModal.svelte
- frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/sns.query.ts
- frontend/src/lib/types/sns.ts
- frontend/src/lib/utils/sns.utils.ts
- frontend/src/tests/lib/api/sns.api.spec.ts
- frontend/src/tests/lib/modals/sns/StakeSnsNeuronModal.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/utils/sns.utils.spec.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/mocks/sns-response.mock.ts
User is able to stake SNS neurons.
* New sns api function: stakeNeuron.
* Implement sns neurons service: stakeNeuron.
* Add governanceCanisterId to SnsSummary type.
* Change how slot "destination-info" is rendered inside TransactionReview.
* Test for new sns api function.
* Test for new sns neurons service.
> GIX-1115: Stake SNS neuron functionality

- frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
Button to participate in sale should be in the middle on tablet.
* Add a media query to change the style of the button in ProjectStatusSection.
No tests
> Fix: Participate button on tablet

- frontend/src/lib/components/common/Layout.svelte
- frontend/src/lib/pages/NnsNeuronDetail.svelte
My last PR https://github.com/dfinity/nns-dapp/pull/1531 had issue and "auto-merge" option ignored these and merged the PR anyway
- fix lint issue
> fix: lint errors

- TESTING.md
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/workflows/CreateSubaccount.spec.ts
Have tests that check the main flows of the application with different edge cases and complex states.
* Route level tests is allowed to mock only the api level. Test a main flow like creating a subaccount.
All changes are in tests.
> Chore: Integration Tests

- frontend/package-lock.json
Bump gix-cmp to integrate PRs [#116](https://github.com/dfinity/gix-components/pull/116), [#117](https://github.com/dfinity/gix-components/pull/117), [#118](https://github.com/dfinity/gix-components/pull/118) and its fix for the CI [#119](https://github.com/dfinity/gix-components/pull/119).
> build: update gix-cmp

- frontend/package-lock.json
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/lib/routes/Accounts.svelte
- frontend/src/lib/routes/Neurons.svelte
Prepare candid files and feature flags for SNS-1
SNS-1 includes SNS accounts and all neuron actions, but not Staking Neuron which has not yet gone through security review.
* Change ENABLE_SNS_2 by ENABLE_SNS in accounts.
* Add ENABLE_SNS_2 to render Stake Neuron button.
* Upgrade ic-js related libraries.
> GIX-1138: Preparation for SNS-1

- Cargo.lock
- HOWTO.md
- dfx.json
- rs/Cargo.toml
- rs/src/proposals.rs
A new property was added to a payload and the crypto team needs it for a proposal.
* Upgrade the commit of registry-canister dependency to the one deployed 2022-11-23
> Chore: Upgrade proposal payload revisions

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Release branch for 23rd of November 2022
* Changelog.
> Release: 2022-11-23

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Branch release for 23rd November 2022. Second one.
* Change log
> Release 2022-11-23-2

- frontend/package-lock.json
- frontend/src/lib/components/ui/BadgeNew.svelte
- frontend/src/lib/i18n/en.json
Review "new" badge according design.
> style: review new badge

- frontend/src/routes/(app)/launchpad/+page.svelte
- frontend/src/routes/(app)/project/+page.svelte
Enable launchpad
* Disable redirect for prod in launchpad and project page.
> Fix: Enable launchpad

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Branch for both releases of 24th of November 2022.
* Changelog.
* Dapp versions.
> Releases 2022-11-24

- frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
Remove hack to change action name OpenSnsTokenSwap
* Show action name directly instead of changing it.
* There was no test for the hack.
> Chore: Remove hack action name open swap

- frontend/package-lock.json
- frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
- frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
User had an issue with the amount 0.3319 and we discovered a rounding issue.
* Upgrade ic-js with fix to problem.
* Manage possible errors raised from fromNumber.
* No new functionality.
> Fix: Transaction amount issue with rounding

- frontend/package-lock.json
- frontend/src/lib/components/common/Footer.svelte
Adapt secondary buttons colors as envisionned by designers.
- update gix cmp
- set background color for footer
> style: secondary button colors tweak

- frontend/src/lib/services/$public/app.services.ts
- frontend/src/lib/services/app.services.ts
- frontend/src/tests/lib/services/_public/app.services.spec.ts
Until we understand better the implications of syncTime, we'll comment the call.
* Comment syncTime calls
* Comment also tests.
> Chore: comment syncTime call

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Branch for release of 30th of November 2022.
* Changelog
> Release 2022-11-30

- HOWTO.md
Improve the documentation of how to update payloads when there are changes. The scenario of changes in an nnsFunction was not well explained
* HOWTO.md
* Only docs changes
> Chore: Update HOWTO

- .github/workflows/build.yml
- deploy.sh
- dfx.json
- e2e-tests/README.md
- e2e-tests/components/auth.ts
- e2e-tests/package-lock.json
- e2e-tests/package.json
- e2e-tests/specs/home.e2e.ts
- e2e-tests/specs/multi-tab-auth.e2e.ts
- e2e-tests/specs/user-V01-open-proposals-are-shown.e2e.ts
- e2e-tests/specs/user-V02-proposal-filters-work.e2e.ts
- frontend/src/lib/modals/neurons/DisburseNnsNeuronModal.svelte
Enable end-to-end tests in CI.
* Upgrade dfx version
* Fix broken e2e tests after last changes.
* Fix a UX bug discovered with CI!
* Enable e2e tests in CI
* Disable nns_canisters step because it's not needed.
* All changes are in tests and CI pipeline.
> Chore: Enable end-to-end test in CI

- frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/utils/anonymize.utils.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/lib/utils/utils.ts
There was few lint warning that could be solved.
> chore: solve lint warnings

- dfx.json
The `dfx.json` file provided in PR #1623 made it to main without being formatted which makes the CI fails.
> build: fix dfx.json format

- frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
Add spacing within and around table in the decoded proposal summary.
> style: proposal summary <table /> spacing

- PROPOSAL_TEMPLATE.sh
Improve the proposal summary for nns-dapp proposals.
* Changes in PROPOSAL_TEMPLATE.sh
Not applicable
> Fix: Improve proposal template

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Release candidate 2022-12-08
- update changelog
> Release candidate 2022-12-08

- frontend/src/lib/i18n/en.json
Update the error text because the ledger app version is not yet available.
- text update
> i18n: ledger upgrade text update

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Release candidate 2022-12-20
- Changelog update
> Release candidate 2022-12-20.2

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/i18n/en.json
Let's redo "Canisters" until we have the "Devs" flag. Discussed with Pete.
- redo "Canisters" in the menu
- move it as last entry of the menu
> feat: redo canisters

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Ultimately it's "My Canisters" too.
> feat: my canisters

- frontend/src/lib/routes/Neurons.svelte
Enable staking sns neuron since the security fix was deployed.
- remove flag from the button
> enable staking sns neuron

- CHANGELOG.md
- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
- rs/Cargo.toml
Release 2022-12-23
- update changelog
- update patch versions
> Release 2022-12-23

- dfx.json
- frontend/jest-setup.ts
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte
- frontend/src/lib/components/summary/Summary.svelte
- frontend/src/lib/components/summary/SummaryProjectLogo.svelte
- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/lib/services/$public/app.services.ts
- frontend/src/lib/services/app.services.ts
Simplify feature flags by removing unused ENABLE_SNS
* Remove ENABLE_SNS where it was used and consider it as "true".
> GIX-1013: Clean up feature flag after enabling SNS

- frontend/src/lib/directives/debug.directives.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Allow users to remove the followees for deprecated topic for Decentralized Sale of their neurons.
* New LogType "RemoveFolloweesDecentralizedSale" in debug directives.
* New directive removeFolloweesDecentralizedSale
> Feat: New debug directive to unfollow all neurons of Sns decentralized sale

- rs/src/proposals.rs
Upgrades the II init type again.
Copies the new type definitions from the II repo.
There are no tests for the init type.
> chore: update II init type

- frontend/package-lock.json
- frontend/src/lib/components/common/MenuMetrics.svelte
- frontend/src/lib/components/login/LoginFooter.svelte
Particularly noticable on android, the TVL block makes its appearance in the menu without a fixed width which feels like a glitch.
- use layout store from gix-component
- mitigate glitch with some animation
> fix: tvl appearance in menu as block

- frontend/package-lock.json
Bump ic-js to inherit next versions.
> build: bump to ic-js next

- frontend/src/lib/api/sns-wrapper.api.ts
- frontend/src/lib/constants/canister-ids.constants.ts
- frontend/src/lib/constants/environment.constants.ts
Group wasm canister id with canister ids constants.
> refactor: move wasm canister id

- frontend/scripts/build.csp.mjs
We want to deploy to small12
* Move cachingCanisterUrl in build script outside of the function to be used in other functions.
Not applicable
> Fix: Broken build step for small12

- frontend/package-lock.json
Upgrade ic-js to fix issue with encoding and decoding icrc-1 subaccounts.
* ic-js versions upgraded
Not applicable
> Fix: Encode decode ICRC-1 subaccounts

- frontend/package-lock.json
> build: bump ic-js next

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
Release for Saturday 28th January 2023
* Changelog
* Versions
Not applicable
> Release 2023-01-28

- frontend/src/lib/components/neuron-detail/ConfirmSpawnHW.svelte
- frontend/src/lib/components/neuron-detail/NeuronJoinFundCard.svelte
Use global style for external links instead of custom non contrating colors.
> style: global style for external link

- e2e-tests/README.md
Improve docs on how to run e2e tests.
* Change readme in e2e directory
> Chore: Improve e2e readme

- config.sh
- dfx.json
The nns-app will be supporting ckbtc, so needs the ckbtc canister IDs.
At first we need just the index and ledger canisters, which appears to be easy because they appear to be standard icrc1 canisters.
- Add ckbtc index and ledger canisters to dfx.json.  Source: https://forum.dfinity.org/t/ckbtc-a-canister-issued-bitcoin-twin-token-on-the-ic-1-1-backed-by-btc/17606/46?u=bitdivine
- Add code to get the ID and provided it in the standard ways to builds. 
- I have run:
`DFX_NETWORK=mainnet ./config.sh` and verified that it returns the values in `dfx.json` and in Manu's post.
> Ckbtc config

- .github/workflows/aggregator.yaml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/docker-build.yaml
- .github/workflows/nightly.yaml
- .github/workflows/reproducible-assets.yaml
- .github/workflows/reproducible.yaml
- .github/workflows/tag.yaml
- Dockerfile
- dfx.json
Bump dfx version to have the latest dfx features, e.g., dfx sns download and creating canisters via boundary nodes on testnets, available in SNS end-to-end tests.
> bump dfx version to 0.13.0-beta.3 and update ubuntu version in Dockerfile

- .github/workflows/aggregator.yaml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/docker-build.yaml
- .github/workflows/nightly.yaml
- .github/workflows/reproducible-assets.yaml
- .github/workflows/reproducible.yaml
- .github/workflows/tag.yaml
- Dockerfile
- dfx.json
Rollback to Ubuntu 20.04 and dfx 0.12.1
* Change ubuntu version in CI and dockerfile.
* Change dfx version in dfx.json
* Build steps
> Fix: Rolback ubuntu and dfx

- CHANGELOG.md
- dfx.json
- frontend/package-lock.json
- frontend/package.json
Release branch for 8th February 2023
* Changelog
* Bump nns-dapp frontend version.
* Enable ckBTC for staging environment.
Not applicable
> Release: 2023-02-07

- frontend/src/tests/lib/services/_public/sns-proposals.services.spec.ts
Remove error log from test run.
- mock console error in sns-proposals.services.spec.ts
> fix: remove error log

- dfx.json
I had changed the dfx version in dfx.json locally as a work around but I didn't mean to commit it.
Change dfx version in dfx.json back to 0.13.0-downgrade.1.
none
> Restore dfx.json to what it was before it was accidentally changed

- frontend/src/lib/services/ckbtc-minter.services.ts
Failing tests in `main`.
* Change order of error type check in ckbt-minter updateBalance service.
* Tests fixed
> Fix: ckBTC services test issues

- frontend/package-lock.json
Build gix-cmp to fix Firefox collapsible height reported and fixed in https://github.com/dfinity/gix-components/pull/158.
> build: bump gix-cmp to fix Firefox collapsible height

- frontend/src/tests/lib/modals/neurons/DisburseSnsNeuronModal.spec.ts
- frontend/src/tests/mocks/sns-response.mock.ts
My solution to GIX-1328 requires changes to this test (among others) otherwise the SNS neuron won't be available.
I decided to do a separate cleanup of the test to keep the PR that fixes GIX-1328 more readable.
Changes to DisburseSnsNeuronModal.spec.ts:
1. Use real stores instead of mocking them.
2. Mock `sns-governance.api` instead of `sns-neurons.services`
3. Mock `getAuthenticatedIdentity` explicitly with a specific test identity, instead of relying on `frontend/jest-spy.ts`.
4. Populate `snsQueryStore` such that `snsTokenSymbolSelectedStore` (which is no longer mocked) can find the correct token metadata.
5. Add an additional convenience function to `sns-response.mock.ts` to create responses with specified principal. Reuse it for another function in the same file.
Tests only.
> Clean up DisburseSnsNeuronModal.spec.ts

- frontend/src/lib/components/layout/Footer.svelte
Because the text has been modified from "New Transaction" to "Send", the footer button has become small on mobile devices.
Is:
pr:
ms
> style: footer button width on mobile devices

- frontend/src/lib/services/sns-sale.services.ts
It doesn't add any value to reload the state to validate whether the user can or not participate.
This same validation is done when creating the ticket.
* Remove call to `reloadSnsState` in the participation flow.
* Remove helper `reloadSnsState` because it's not used anymore.
* Tests didn't check that the call was made. Therefore, no changes in the tests were necessary.
> GIX-1318: Remove reloadSnsState from participation flow

- frontend/src/lib/derived/selected-universe.derived.ts
- frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
Deep links to sns neurons were not working.
* Revert changes done in #1926 
* Skip breaking test that should be fixed when we find a better way to manage the deep link issue.
> Fix: Fix sns neuon deep link

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release 2023-02-23
- changelog
> changelog update

- frontend/src/lib/i18n/en.json
Change text when the user gets an open ticket.
* Change i18n key `sns_sale_proceed_with_existing_ticket`
Only i18n key
> Chore: Change existing ticket text

- scripts/sns/aggregator/release
- scripts/sns/aggregator/release-template
The aggregator is to be upgraded by proposal, like the NNS.  We need at least a minimal release Standard Operating Procedure.
See also the corresponding NOTION page: https://www.notion.so/SNS-Aggregator-release-SOP-d6cd1b14eb6b466cb903da6d3e76e254
* Make a proposal template based on the nns-dapp template.
* I have run the scripts and eyeballed the templates & command.
> Minimum viable aggregator release template

- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/ProjectDetail.svelte
- frontend/src/lib/services/sns-swap-metrics.services.ts
- frontend/src/lib/stores/sns-swap-metrics.store.ts
- frontend/src/lib/types/i18n.d.ts
Display `sale_bayer_count` from sale swap metrics (oc sample - https://2hx64-daaaa-aaaaq-aaana-cai.raw.ic0.app/metrics)
- loadSnsSwapMetrics service
- SnsSwapMetrics store
- only manual tests are done, unit tests TBD
> feat: sale_buyer_count field

- frontend/src/tests/lib/components/proposal-detail/IneligibleNeuronsCard.spec.ts
- frontend/src/tests/lib/modals/neurons/VotingHistoryModal.spec.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
Be more specific in tests.
* Change the expected article tag with the actual test id expected to be rendered.
* Changes in IneligibleNeuronsCard.spec, VotingHistoryModal.spec, NnsAccounts.spec and NnsProposals.spec
> Chore: Expect by test id instead of generic tag

- frontend/src/lib/services/accounts.services.ts
Fix typo
Change overried to override.
none
> Fix typo overried

- frontend/src/tests/lib/services/sns.services.spec.ts
https://github.com/dfinity/nns-dapp/pull/2007 cleaned up a number of tests in a certain way to remove `await null` calls.
In parallel a new similar test was added that does `await null`.
This PR cleans up that test in the same way.
Clean up `src/tests/lib/services/sns.services.spec.ts` to remove `await null` and follow the same style as in https://github.com/dfinity/nns-dapp/pull/2007
Test only
> Cleanup watchSnsTotalCommitment test

- frontend/src/lib/i18n/en.json
"Total Tokens" is a bit confusing.
* Change text to "Tokens Distributed to Participants".
Only text changes
> Text: Change "Total Tokens" text

- frontend/src/lib/constants/environment.constants.ts
Go back to secure update calls.
* Set `FORCE_CALL_STRATEGY` to not fore any strategy.
Not applicable
> Chore: Reenable update calls

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
Release candidate 2023-03-07
* Changelog updated
> Release 2023-03-07

- e2e-tests/specs/user-N03-neurons-merged.e2e.ts
- frontend/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
- frontend/src/lib/components/neurons/NnsNeuronInfo.svelte
- frontend/src/lib/components/neurons/SelectNeuronsToMerge.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronInfo.spec.ts
- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
Merge neurons is a source of confusing and bad UX for users.
While we work on a better and more sophisticated solution, this PR addresses main pain points and tries to explain better what's happening.
It uses only text to do so. No new UX is added in this PR.
* Add explanation text in SelectNeuronsToMerge.svelte
* Add explanation text in ConfirmNeuronsMerge.svelte
> Feat: Improve merge neurons flow

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release candidate for 2023-03-13.
* Changelog
* Update versions in cargo.toml and package.json
Not applicable
> Release: 2023-03-13

- frontend/src/lib/pages/Login.svelte
- frontend/src/lib/services/worker-auth.services.ts
- frontend/src/lib/stores/auth.store.ts
- frontend/src/lib/utils/canisters.utils.ts
- frontend/src/routes/+layout.svelte
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/mocks/auth.store.mock.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
Improve `auth.store` types to avoid Webstorm to displays issue for types it cannot interfer.
> chore: auth store better typed

- frontend/package-lock.json
- frontend/src/lib/components/accounts/AddAccountType.svelte
- frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
- frontend/src/lib/components/accounts/NnsAddAccount.svelte
- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/lib/themes/legacy.scss
Move action "Add Nns Account" from footer to a button card
- move function to a new component
- use new scss style and new icon
- add legacy style for card in modal
> feat: add account button card

- .github/workflows/aggregator.yaml
- .github/workflows/build.yml
- dfx.json
Just staying up to date.
- Bump ic and snsdemo commits
None
> Bump snsdemo and ic-repo commits

- frontend/package-lock.json
Include PR https://github.com/dfinity/gix-components/pull/175
> build: bump gix-cmp

- frontend/src/tests/lib/pages/SnsWallet.spec.ts
Show how to avoid mocking stores in tests and instead filling them accordingly.
Example with SnsWallet page.
* Remove store mocks in SnsWallet.spec.ts page test.
> Chore: Remove mocking stores in SnsWallet page test

- frontend/src/lib/api/sns-governance.api.ts
- frontend/src/tests/lib/api/sns-governance.api.spec.ts
User sees the details of a proposal for an SNS project.
This PR: Add api function the get the proposal by id
* New api function `queryProposal`.
* Test new api function.
> GIX-1219: Add api function to get proposal

- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/lib/modals/sns/proposals/SnsFilterStatusModal.svelte
- frontend/src/lib/pages/SnsProposals.svelte
- frontend/src/lib/services/sns-filters.services.ts
- frontend/src/lib/stores/sns-filters.store.ts
- frontend/src/tests/lib/derived/sns/sns-filtered-proposals.derived.spec.ts
- frontend/src/tests/lib/modals/sns/SnsFilterStatusModal.spec.ts
- frontend/src/tests/lib/services/_public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-filters.services.spec.ts
- frontend/src/tests/lib/stores/sns-filters.store.spec.ts
There was a typo in the snsFiltersStore, it was "snsFiltesStore", an "r" was missing.
* Rename snsFiltesStore to snsFiltersStore
* Renaming
> Chore: Fix typo in snsFiltersStore

- frontend/package-lock.json
- frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte
- frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
- integrate PR https://github.com/dfinity/gix-components/pull/177 to fix qr code memory leak on mobile devices
- add safe are around qr code to make them readable by the new qr code reader
> fix: qr code reader

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release candidate for 21st of March 2023
* Changelog.
* Bump nns-dapp versions.
Not applicable
> Release 2023-03-21

- frontend/__mocks__/$app/navigation.ts
- frontend/src/tests/routes/app/settings/layout.spec.ts
Test click on "back" action on Settings layout.
Did not found another solution to mock the referrer path.
- add test to layout
> test: settings back

- scripts/clap.bash
The clap.bash argument parser is imported from the snsdemo repo.  The upstream code now has tests.  The functionality has hardly changed but it would be better to use the tested version.
*  Update clap.bash to the latest version.
See CI.
> chore: Sync clap.bash

- rs/backend/src/accounts_store.rs
Clean up unnecessary code after state migration.
We don't need the old transaction and transaction types anymore.
* Do not convert to old transaction before encoding.
* Remove all old types.
* No additional tests needed.
> Chore: Clean up after state migration

- frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
- frontend/src/lib/pages/SnsNeuronDetail.svelte
- frontend/src/tests/fakes/sns-ledger-api.fake.ts
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronFollowingCard.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronHotkeysCard.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronMaturityCard.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronMetaInfoCard.page-object.ts
- frontend/src/tests/page-objects/Summary.page-object.ts
There was a bug in the SNS neuron detail page:
* User arrives to the sns neuron detail with the deep link.
* User clicks the button "Increase Stake".
* The accounts are shown as loading and are never loaded.
This PR: Improves testing the SNS Neuron Detail page to make a test that replicates the bug.
* New test ids in different components.
* Change testing in SnsNeuronDetail.svelte to mock the api layer and use the page object for testing.
* Add new page objects.
> Chore: Improve SNS Neuron detail testing

- frontend/src/lib/components/transaction/TransactionReview.svelte
- frontend/src/lib/components/ui/AmountInput.svelte
- frontend/src/lib/components/ui/InputWithError.svelte
- frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
- frontend/src/lib/modals/transaction/TransactionModal.svelte
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/routes/Wallet.svelte
- frontend/src/tests/e2e/accounts.spec.ts
- frontend/src/tests/page-objects/AccountCard.page-object.ts
- frontend/src/tests/page-objects/AmountInput.page-object.ts
- frontend/src/tests/page-objects/App.page-object.ts
- frontend/src/tests/page-objects/Dropdown.page-object.ts
- frontend/src/tests/page-objects/IcpTransactionModal.page-object.ts
- frontend/src/tests/page-objects/NnsAccounts.page-object.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
- frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts
- frontend/src/tests/page-objects/Toggle.page-object.ts
- frontend/src/tests/page-objects/TransactionForm.page-object.ts
- frontend/src/tests/page-objects/TransactionModal.page-object.ts
- frontend/src/tests/page-objects/TransactionReview.page-object.ts
- frontend/src/tests/page-objects/Wallet.page-object.ts
- frontend/src/tests/page-objects/jest.page-object.ts
- frontend/src/tests/page-objects/playwright.page-object.ts
- frontend/src/tests/page-objects/simple-base.page-object.ts
- frontend/src/tests/types/page-object.types.ts
Test that the user is able to transfer funds.
1. Add a step to transfer funds in `frontend/src/tests/e2e/accounts.spec.ts`
2. Add page objects `AmountInputPo`, `DropdownPo`, `NnsWalletPo`, `SelectDestinationAddressPo`, `TogglePo`, `TransactionFormPo`, `TransactionModalPo`, `TransactionModalPo`, `WalletPo`.
3. Add additional functionality to existing page objects `AccountCardPo`, `AppPo`, `NnsAccountsPo`.
4. Add `data-tid` attribute in components `AmountInput`, `InputWithError`, `TransactionModal`, `NnsWallet`, `Wallet`, 
5. Add `selectOption` to `PageObjectElement` and its implementations.
6. Add `click()` and `getText()` to `SimpleBasePageObject`
Ran `npm run test-e2e` against state saved by snsdemo.
> E2E accounts test: transfer funds

- HACKING.md
- frontend/package-lock.json
- frontend/src/lib/api/ckbtc-minter.api.ts
- frontend/src/lib/components/accounts/BitcoinEstimatedFee.svelte
- frontend/src/lib/services/ckbtc-minter.services.ts
- frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
- frontend/src/tests/lib/components/accounts/BitcoinEstimatedFee.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
- scripts/ckbtc/deploy-ckbtc
- scripts/ckbtc/download-ckbtc
- Integrate ckBTC minter breaking change `estimate_fee` renamed in `estimate_withdrawal_fee`.
- Sum up (for now, all scheme related to fees is being described by product team) bitcoin and minter estimated fee for display purpose
- bump `ic-js`
- update for breaking changes
- sum up estimated fees
- update scripts and docs to deploy ckBTC locally
> feat: ckBTC estimate withdrawal fee

- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
Explain better the nature of the SNS neurons coming from the Community Fund.
* Add a subtitle in the SNS Neurons from the CF.
* Check that subtitle text is present.
> Feat: Add Subtitle to SNS CF neurons section

- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/ui/DayInput.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/ui/DayInput.spec.ts
Instead of "amount" use "Delay in days" as placeholder for the dissolve delay in days input field.
- update placeholder
> Review dissolve delay in days input placeholder

- deploy.sh
Fix deploy.sh script for nns-dapp
* Change deploy command for nns-dapp
Not applicable
> Chore: Fix deploy script

- frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.svelte
- frontend/src/lib/derived/debug.derived.ts
- frontend/src/lib/stores/proposals.store.ts
- frontend/src/lib/stores/vote-registration.store.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingCard.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.spec.ts
- frontend/src/tests/lib/stores/proposals.store.spec.ts
- frontend/src/tests/lib/stores/vote-registration.store.spec.ts
Move votingNeuronSelectStore to voting store file because it's directly related to the voting.
- no logic changes
> refactor: move votingNeuronSelectStore to voting

- frontend/package-lock.json
- frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
- frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
- frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
- frontend/src/lib/modals/neurons/DisburseNnsNeuronModal.svelte
- frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
- frontend/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte
- frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
- frontend/src/lib/modals/neurons/SpawnNeuronModal.svelte
- frontend/src/lib/modals/neurons/StakeMaturityModal.svelte
- frontend/src/lib/modals/sns/neurons/AddPermissionsModal.svelte
- frontend/src/lib/modals/sns/neurons/IncreaseSnsDissolveDelayModal.svelte
- frontend/src/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.svelte
- frontend/src/lib/modals/sns/neurons/SnsStakeNeuronModal.svelte
- frontend/src/lib/modals/sns/neurons/SnsTransactionModal.svelte
- frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
- frontend/src/tests/lib/components/neurons/NnsNeuronsFooter.spec.ts
- frontend/src/tests/lib/modals/transaction/TransactionModalTest.svelte
Fix wizard modal opening glitch by integrating gix-cmp PR https://github.com/dfinity/gix-components/pull/198
The related PR is a tricky PR!
- bump gix-cmp
> fix: wizard modal opening glitch

- frontend/src/lib/i18n/en.json
> Shorter confirm dissolve delay text cta

- frontend/src/lib/modals/neurons/SpawnNeuronModal.svelte
> Spawn neuron spacing

- dfx.json
Simplify dfx.json
* Use default config for `FETCH_ROOT_KEY` and `FEATURE_FLAGS` in most testnets.
> Feat: Use default config for testnets

- frontend/src/lib/components/canisters/ConfirmCyclesCanister.svelte
- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/NeuronFollowingCard.svelte
- frontend/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte
- frontend/src/lib/components/ui/SkeletonFollowees.svelte
- frontend/src/lib/components/ui/TagsList.svelte
Few style improvements noticed while testing the release candidate.
Before
After
> Style improvement for release candidate

- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/page-objects/AccountCard.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronCard.page-object.ts
Continuing with the SNS end-to-end test.
Check that the user can see the neuron and its stake.
> E2E: Get stake of the staked SNS neuron

- frontend/package-lock.json
- frontend/src/tests/mocks/nns-reward-event.mock.ts
Governance is adding a new Action variant.
This PR: Updates ic-js with latest candid file.
* Upgrade ic-js libraries
I tested that this version works against an older version of the Governance canister.
> Chore: Upgrade ic-js libraries

- frontend/package-lock.json
I need the `data-tid` on the header component for https://github.com/dfinity/nns-dapp/pull/2356
`npm run update:gix`
Limited manual testing on localhost.
> bump gix-components

- config.test
- dfx.json
- frontend/jest-setup.ts
- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/stores/feature-flags.store.ts
Remove unused feature flag `ENABLE_SNS_2`.
* Remove it from `dfx.json`.
* Remove it from the featureFlags store.
* Remove it from default feature flags.
* Remove it from config test
* Remove it from jest setup.
> Chore: Remove ENABLE_SNS_2 feature flag

- .github/workflows/build.yml
Nightly releases do not have wasms.
Add nightly tag check in the "build" job
Pushed a test nightly tag and the release included the wasms: https://github.com/dfinity/nns-dapp/releases/tag/nightly-test-2023-04-24
> Chore: Add wasms nightly release

- frontend/package-lock.json
As requested revert narrowed desktop modal.
> feat: revert desktop narrow modal

- .github/workflows/docker-build.yaml
This reverts commit c87b09ec5582f20bca9e20ac930fcd7b6fc1e158.
It didn't work.
> Revert "Fix nightly tagging (#2375)"

- .github/actions/release_nns_dapp/action.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/nightly.yaml
Nightly releases are not working reliably.
- Factor out the release code into an action
- Call the action from nightly
- Increase the frequency of the nightly job to hourly
Ultimately:  Delete the release for today, wait an hour, check.
I have triggered the build manually but there is no guarantee that manual triggers behave in the same way.
> Factor out release

- frontend/src/lib/i18n/en.json
-> "Updated available ckBTC : New confirmed BTC." as requested
> Update ckBTC balance success msg

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release candidate of 28th of April 2023
* Changelog
* Bump version
Not applicable
> Release 2023-04-28

- HOWTO.md
I just added a new NNS function in https://github.com/dfinity/nns-dapp/pull/2403 and I figured out a number of things and wanted to document them here.
I also struggled a bit with the existing instructions so I tried to make them clearer.
Please check that I didn't remove something useful just because I didn't understand it.
1. Overview of steps to add a new NNS function.
2. Detailed instruction of every step.
3. Use links that either fix a specific commit, or use a text search fragment to point to a specific line. The existing links were broken because the lines they pointed to changed.
4. Includes steps about testing the changes in addition to making the changes
I went through the steps to verify that they work for me.
> Update HOWTO.md instruction to add a new NNS function proposal type

- frontend/package-lock.json
- frontend/src/lib/api/ckbtc-ledger.api.ts
- frontend/src/lib/api/icrc-ledger.api.ts
Bump ic-js and use type `IcrcAccount` instead of `BalanceParams` in function that we refactored yesterday `getCkBTCAccount`.
> build: bump ic-js

- frontend/src/lib/i18n/en.json
> chore: warning text update

- frontend/package-lock.json
Introduces following gix-cmp PRs
> Bump gix-cmp

- frontend/src/lib/services/ckbtc-convert.services.ts
- frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
If the withdrawal account has already been loaded in store in a certified way, we can reuse this account to proceed with the ckBTC to BTC conversion and skip an update call.
If not yet loaded, then we proceed as currently and we call the minter to get the account.
I decided to not overengineer this process - i.e. if there isn't an account in store and if we fetch it, this process won't save for the moment the resulting account in store. It isn't the goal of the function and it doesn't arm the UI/UX to not do so.
- in `convertCkBTCToBtc`, check for account, if present use it else continue as existing
> Improve performance by not necessary getting the withdrawal account again

- dfx.json
- frontend/src/lib/constants/ckbtc-canister-ids.constants.ts
Set the effective ckBTC minter canister id on mainnet.
> ckBTC minter canister id on mainnet

- frontend/src/lib/components/accounts/BitcoinFeeDisplay.svelte
- frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte
- frontend/src/lib/components/transaction/TransactionSource.svelte
- frontend/src/lib/components/transaction/TransactionSummary.svelte
Revert vertical display of the transaction PR #2416.
> Revert PR #2416

- frontend/src/lib/components/accounts/BitcoinAddress.svelte
Do not display bitcoin explorer link until proposal to enable ckBTC to BTC conversion would be accepted.
Before
After
> Do not display bitcoin explorer link

- HOWTO.md
There was a missing step in the documentation when a new Action is added in the Governance candid interface.
* Changes in HOWTO.md
Only documentation changes.
> Feat: Improve HOWTO

- frontend/src/lib/i18n/en.json
> A canister explorer type

- frontend/src/lib/components/accounts/BitcoinAddress.svelte
- frontend/src/lib/components/accounts/CkBTCReceiveButton.svelte
- frontend/src/lib/components/accounts/CkBTCWalletActions.svelte
- frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
- frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
- frontend/src/lib/pages/CkBTCAccounts.svelte
- frontend/src/lib/services/ckbtc-minter.services.ts
- frontend/src/lib/types/ckbtc-accounts.modal.ts
- frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
- frontend/src/tests/lib/pages/CkBTCAccounts.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
Enable conversion of ckBTC from / to BTC by solving various TODO that used to make various features accessible only ckTESTBTC.
> Enable conversion of ckBTC from / to BTC

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release 2023-05-09
- changelog update
- patch version increase
> WiP Update changelog

- config.sh
- config.test
- frontend/src/lib/constants/ckbtc-canister-ids.constants.ts
- frontend/src/lib/utils/env-vars.utils.ts
> ckBTC minter canister config

- HOWTO.md
There was a missing step when a new Topic is added to NNS proposals.
* Upgrade HOWTO.md
Only documentation changes.
> Chore: Improve HOWTO Docs

- frontend/package-lock.json
> upgrade gix-components

- frontend/src/lib/constants/ledger-app.constants.ts
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/services/neurons.services.ts
Ledger version constants were in the `neurons.constants` file.
Move them to their own file.
* Move the constants related to ledger app versions.
Only moving variables around.
> Chore: Move ledger version constants

- frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
- frontend/src/tests/page-objects/ProjectDetail.page-object.ts
If there is an error getting the country of the user, we enable the button to participate.
No functionality changes.
* Add a test in the ParticipateButton and ProjectDetail with the scenario that getting the country fails.
> GIX-1543: Allow user participate if error getting country

- frontend/src/lib/stores/feature-flags.store.ts
Make voting flag editable to improve testing experience.
> chore: extend feature flags

- frontend/src/lib/components/header/Banner.svelte
Make test banner sticky and review design colors.
> Style test banner

- frontend/package-lock.json
I want to pull in the changes from https://github.com/dfinity/ic-js/pull/341
`npm run upgrade:next`
Limited manual testing (splitting and merging a neuron)
> Bump ic-js

- e2e-tests/components/accounts-tab.ts
- e2e-tests/components/neurons-tab.ts
- frontend/package-lock.json
- frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
- frontend/src/tests/lib/modals/accounts/IcpTransactionModal.spec.ts
- frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
- frontend/src/tests/utils/toggle.test-utils.ts
Bump gix-cmp to fix warning about duplicate form field ids
> Fix duplicate form field id in the same form

- frontend/src/lib/components/canisters/CanisterCardCycles.svelte
- frontend/src/lib/components/metrics/Metrics.svelte
- frontend/src/lib/services/$public/worker-metrics.services.ts
- frontend/src/lib/services/worker-auth.services.ts
- frontend/src/lib/services/worker-cycles.services.ts
- frontend/src/routes/+layout.svelte
Extract interfaces types for worker services instead of duplicating types in components
No features. Only type declarations extracted.
> Extract interfaces types for worker services

- frontend/scripts/build.csp.mjs
Add [Kinic](https://nns.ic0.app/project/?project=7jkta-eyaaa-aaaaq-aaarq-cai) metrics api endpoint to the csp list to get the number of participants.
- add the url to connect-src list
> Add kinic metrics url

- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
Current status:
NNS: Topic | Reward | Proposal
Sns: Reward | Proposal
After PR:
NNS: Topic | Reward | Proposal
Sns: Proposal | Reward
> Sns invert Sns proposals filter for consistency

- scripts/ckbtc/deploy-ckbtc
- scripts/ckbtc/download-ckbtc
Review the local ckBTC download and deploy scripts according last commit in IC repo.
> Update ckBTC scripts

- frontend/vite.config.ts
Add new package `worker-utils` to related build chunk.
> Worker-utils chunk

- frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/lib/services/$public/proposals.services.ts
- frontend/src/lib/services/$public/sns.services.ts
- frontend/src/lib/services/accounts.services.ts
- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/services/ckbtc-accounts.services.ts
- frontend/src/lib/services/ckbtc-info.services.ts
- frontend/src/lib/services/ckbtc-tokens.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/services/sns-parameters.services.ts
- frontend/src/lib/services/sns-tokens.services.ts
- frontend/src/lib/services/sns.services.ts
- frontend/src/lib/services/transaction-fees.services.ts
- frontend/src/lib/utils/ckbtc.utils.ts
- frontend/src/lib/utils/env.utils.ts
Extract utils to check force call strategy and avoid code duplication.
> Extract utils to check force call strategy

- frontend/src/lib/components/sns-neurons/SnsNeuronAge.svelte
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronAge.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts
- frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
- frontend/src/tests/page-objects/SnsNeuronAge.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronMetaInfoCard.page-object.ts
Show the neuron's age for SNS neurons.
* Implement the code in SnsNeuronAge that was commented.
* New sns neuron util `neuronAge`.
* New page object SnsNeuronAge.
* New test file for SnsNeuronAge component.
* Add tests cases to SnsNeuronMetaInfoCard spec file
* Add methods to SnsNeuronMetaInfoCard page object.
* Add tests for new sns neuron util `neuronAge`.
> Feat: Render SNS Neuron age

- frontend/src/tests/lib/api/ckbtc-index.api.spec.ts
I spotted a test in which I most probably copy/pasted the titles of the tests and forgot to update these.
> Correct copy pasted titles

- frontend/src/tests/lib/services/ledger.services.spec.ts
Improve the ledger services test spec.
Inside the ledger services test file:
* Move clear mocks to main beforeEach.
* Mock ledger creation for error test cases instead of relying in resetting the mocks.
Only changes in tests.
> Test: Improve Ledger Services tests

- frontend/src/lib/components/neuron-detail/NeuronProposalsCard.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronMetaInfoCard.svelte
- frontend/src/lib/components/proposal-detail/NnsProposal.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/components/proposals/ProposalCard.svelte
- frontend/src/lib/routes/ProposalDetail.svelte
- frontend/src/lib/routes/Proposals.svelte
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotesResults.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalVotingSection.spec.ts
- frontend/src/tests/page-objects/App.page-object.ts
- frontend/src/tests/page-objects/MenuItems.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronMetaInfoCard.page-object.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
- frontend/src/tests/page-objects/NnsProposal.page-object.ts
- frontend/src/tests/page-objects/NnsProposalList.page-object.ts
- frontend/src/tests/page-objects/ProposalCard.page-object.ts
- frontend/src/tests/page-objects/ProposalDetail.page-object.ts
- frontend/src/tests/page-objects/Proposals.page-object.ts
- frontend/src/tests/page-objects/SnsProposalVotingSection.page-object.ts
- frontend/src/tests/page-objects/VotesResults.page-object.ts
- frontend/src/tests/page-objects/VotingCard.page-object.ts
e2e test for proposal voting.
- extend neurons spec to do a basic voting
- add all required POs
https://github.com/dfinity/nns-dapp/assets/98811342/fc506e40-d177-41db-ba1a-2189adbb3d74
> E2e nns voting

- frontend/package-lock.json
`npm audit` found some vulnerabilities.
Run `npm audit fix` in `frontend/`
none
> npm audit fix

- CHANGELOG-Nns-Dapp.md
Documents stuffs I did for the CHANGELOG.
> docs: release notes web worker, cronjob and payment

- frontend/package-lock.json
Fix two visual quirks.
- modal content height: https://github.com/dfinity/gix-components/pull/230
- header button width: https://github.com/dfinity/gix-components/pull/229
> Fix header button and modal ui quirks

- rs/backend/src/accounts_store.rs
Refactor the sort canisters function for a method.
* Add `sort` method to `canisters` field in `AccountsStore`.
* Substitut calls to `sort_canisters` for new method.
* No changes in functionality, just in implementation.
Nothing changed for the user, it's a code style change.
> Refactor: sort_canisters backend

- CHANGELOG-Nns-Dapp.md
- frontend/src/lib/components/common/Json.svelte
- frontend/src/lib/components/proposal-detail/NnsProposalProposerActionsEntry.svelte
- frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerActionsEntry.spec.ts
- frontend/src/tests/lib/components/proposal-detail/ProposalProposerActionsEntry.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
Update proposal action data rendering. Display always as object.
- `Json` styles image style
- Refactor proposal actions block to display data as an object instead of key/value list.
- adjust current styles
| ![image](https://github.com/dfinity/nns-dapp/assets/98811342/d2a26857-d276-4b1a-835c-c025fc5960bf) | ![image](https://github.com/dfinity/nns-dapp/assets/98811342/da386133-fece-40a2-9a61-55415a1e8c6f) | 
| ![image](https://github.com/dfinity/nns-dapp/assets/98811342/2b9948f2-c8e2-4023-a665-2667431534fd) | ![image](https://github.com/dfinity/nns-dapp/assets/98811342/a5a09279-97e3-4dc5-a85c-a0dfb42d5a8b) |
> Json formatting

- CHANGELOG-Nns-Dapp.md
Add ckBTC observer feature to changelog.
> Add ckBTC observer to changelog

- frontend/src/lib/components/ic/AmountDisplay.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeader.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/ui/Separator.svelte
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeader.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/page-objects/NnsNeuronPageHeader.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts
We are reshuffling the neuron detail page to give a better UX.
In this PR: New component for the NNS neuron detail page.
* Upgrade gix-components library.
* New component NnsNeuronPageHeader that goes at the beginning of the new neuron detail page.
* Test the new component `NnsNeuronPageHeader`.
Not yet worth an entry.
> GIX-1683: NnsNeuronPageHeader Component

- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/pages/SnsNeuronDetail.svelte
Fix ENABLE_NEURON_SETTINGS usage. It's not a anymore boolean.
- use flag as a store
Manual
> fix: ENABLE_NEURON_SETTINGS

- frontend/package-lock.json
Update gix-components library to 2023-07-13.1
It works locally.
> Update gix-components library

- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release candidate changes.
- Changelog
- Patch versions
> Release 2023 07 13 3

- frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte
- frontend/src/lib/components/neurons/NnsNeuronAge.svelte
- frontend/src/lib/components/ui/Hash.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts
- frontend/src/tests/page-objects/NnsNeuronAdvancedSection.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronAge.page-object.ts
We are shuffling the data of the neuron detail page.
In this PR: First step of the Advanced Section in NNS neuron detail page.
* Implement the `NnsNeuronAdvancedSection`. PENDING actions.
* Add `neuron` prop to `NnsNeuronAdvancedSection` in `NnsNeuronDetail`.
* Fix `Hash` style issue with copy button.
* Add test file for component `NnsNeuronAdvancedSection` with PO.
> GIX-1686: NnsNeuronAdvancedSection Part 1

- frontend/src/lib/components/neuron-detail/NnsStakeItemAction.svelte
Remove unused mixin.
* Remove unused mixing in NnsStakeItemAction
Not applicable
Not worth an entry
> Chore: Remove unused mixin

- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release branch for NNS Dapp upgrade: 24th of July 2023
* Changelog
* NNS Dapp version
> Release: Version and Changelog

- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronVotingPowerSection.page-object.ts
- frontend/src/tests/page-objects/SnsStakeItemAction.page-object.ts
Add tests with neuron settings feature flag enabled to SNS neuron detail page specs.
* Test increase stake functionality in SnsNeuronDetail page for new UI.
* New methods in related POs.
Covered by entry of new UI.
> GIX-1745: SnsNeuronDetail page test new UI

- frontend/jest-setup.ts
Unit tests use the new neuron details UI.
* Set `true` for `ENABLE_NEURON_SETTINGS` in jest setup.
Covererd by another entry.
> GIX-1745: Enable new neuron UI for unit tests

- frontend/src/lib/components/common/PageHeading.svelte
UI Improvements in the new neuron details UI:
In this PR: Use h4 for the subtitle.
* Use h4 in the PageHeading subtitle.
* Only UI changes.
Covered already by a changelog entry.
> GIX-1777: UI Improvements

- CHANGELOG-Nns-Dapp.md
- frontend/package-lock.json
- frontend/src/lib/utils/neuron.utils.ts
New icon for dissolving neuron state.
* Upgrade gix-components
* Use new icon for dissolving state
* Only UI changes
> GIX-1777: New dissolving icon

- frontend/src/lib/i18n/en.json
> Remove ICP from few texts

- .github/workflows/aggregator.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/e2e-testnet.yml
- .github/workflows/security-audit.yaml
- .github/workflows/selenium.yml
- .github/workflows/testnet.yml
This is the follow-up to https://github.com/dfinity/nns-dapp/pull/3028
The workflows deleted workflows have now been renamed to "ZZZ ...":
https://github.com/dfinity/nns-dapp/actions
Delete the workflow files once again now that the workflows have been renamed.
no
Already covered by https://github.com/dfinity/nns-dapp/pull/3028
> Deleted renamed deleted workflows again

- CHANGELOG-Nns-Dapp.md
- frontend/package-lock.json
Fix the unnecessary scrollbar in notifications.
* Upgrade gix-components where the UI issue was fixed.
> Chore: Upgrade gix-components

- frontend/package-lock.json
Update `ic-js` to get 1-proposal changes
- 'npm run update:next`
Tested locally against the latest governance canister:
> Update ic-js to get 1-proposal changes

- CHANGELOG-Nns-Dapp.md
Fix misplaced two changelog entries.
> fix: misplaced changelog entries

- CHANGELOG-Nns-Dapp.md
- frontend/package-lock.json
> Bump gix-cmp to fix card hover color and copy propagation

- frontend/package-lock.json
Bump gix-cmp to introduce narrower scrollbars.
> Bump gix-cmp to narrow scrollbars

- frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronMaturitySection.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts
Improve copy of the new neuron details sections.
* Maturity section, set same color as other sections.
* Advanded section: no description.
* Voting Power section: copy change.
* Fix tests after changing copy.
Covered by the entry of the new neuron details UI.
> Chore: Improve Neuron Details copy

- frontend/src/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.svelte
Remove unnecessary check of present value.
* Remove check that `neuron` is non nullish in SnsNeuronAdvancedSection.
Not necessary entry in the changelog.
> Chore: Remove unnecessary neuron check

- frontend/src/tests/lib/api/sns-aggregator.api.spec.ts
Improve testing.
Source comment: https://github.com/dfinity/nns-dapp/pull/3037#discussion_r1284111853
* Add expect in sns aggregator api with two pages.
Not necessary a changelog entry.
> Chore: Add test case SNS aggregator api

- frontend/src/tests/fakes/governance-api.fake.ts
- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
While cleaning up the `ENABLE_SIMULATE_MERGE_NEURONS` feature flag, I noticed a test was missing for when the simulate call fails.
1. Add a test to check that the merge result section is hidden and a toast is shown when the simulate call fails.
2. In the fake, make `mergeNeurons` and `simulateMergeNeurons` fail if not both neurons are locked. This allows for a simple and realistic way to test scenarios where these calls fail.
3. Implement `startDissolving` on the fake API to make `simulateMergeNeurons` fail.
Test only
not necessary
> Test simulate merge neuron failure

- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Branch for release of 14th August 2023
* Changelog
* Versions in cargo.toml and package.json
> Release: Update changelog and versiosn

- frontend/src/tests/lib/components/launchpad/Projects.spec.ts
- frontend/src/tests/lib/derived/sns/sns-projects.derived.spec.ts
Remove unnecessary code in two test files.
* Clean up unnecessary code in Projects.spec.
* Clean up unnecessary code in sns-projects.derived.spec
> Fix: Remove unnecessary code in tests

- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts
1. `proposalPayloadsStore.reset()` wasn't called in `beforeEach` because `beforeEach` was only passed an arrow function which returns `proposalPayloadsStore.reset` but doesn't call it.
2. This means that the second function to run wouldn't load the proposal payload but would have it cached in the store.
3. So when the component is rendered it would be correct immediately without having to wait.
4. The `waitFor()` in the second function wasn't actually working because `queryByTestId("json-wrapper")` was called outside the `waitFor()` and once we got the incomplete element, it would never pass the `expect`.
5. But this didn't matter because the store was pre-populated by the first test and thus the component rendered fast enough.
1. Actually run `proposalPayloadsStore.reset()` in …
> Fix randomized test NnsProposalProposerPayloadEntry.spec.ts

- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
In this PR: Migrate ProjectDetail.spec file to new setSnsProjects test util.
In ProjectDetail.spec
* Stop uisng snsQueryStore.setData and use setSnsProjects test util.
> GIX-1823: Use new sns test util

- CHANGELOG-Nns-Dapp.md
We did a release with 2 cherry-pick fixes.
Add a section for proposal 124252 in `CHANGELOG-Nns-Dapp.md`.
no
> Update CHANGELOG for cherry-pick release

- CHANGELOG-Nns-Dapp.md
- CHANGELOG-Sns_Aggregator.md
- scripts/fmt
- scripts/fmt-changelogs
Revert https://github.com/dfinity/nns-dapp/pull/2964
> Revert changelogs formatter

- frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts
- frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
ProjectSwapDetails.spec failed because the white space what not the same.
* Normalize the white space in the test of ProjectSwapDetails.spec.
Not necessary.
> Fix: Flaky test ProjectSwapDetails.spec

- HOWTO.md
- frontend/src/tests/e2e/README.md
Fix a couple of typos seen when looking at md files recently.
> A couple of typos

- frontend/src/tests/routes/layout.spec.ts
The test expecting a call to `toastsStore.reset` didn't wait long enough for the call to have happened but it passed because the call also happened in an earlier test.
1. Use `beforeEach` instead of `beforeAll` and `afterAll`.
2. Remove `jest.clearAllMock` because `jest.restoreAllMocks` does the same and more.
3. Expect calls not to have happened yet at the start of the test.
4. Use `runResolvedPromises` to make sure all calls that will happen, have happened.
Each test passes individually.
covered
> Fix order dependence of layout.spec.ts

- CHANGELOG-Nns-Dapp.md
- frontend/package-lock.json
- frontend/src/lib/components/common/EmptyCards.svelte
- frontend/src/lib/pages/SignInAccounts.svelte
- frontend/src/lib/pages/SignInCanisters.svelte
- frontend/src/lib/pages/SignInNeurons.svelte
- frontend/src/lib/pages/SignInSettings.svelte
- frontend/src/lib/themes/global.scss
New landing pages when the user is not logged in.
Remove the current login page and redirect instead to accounts.
* Use new PageBanner in SignIn pages.
* New component EmptyCards used in SignIn pages.
* Only UI changes.
> GIX-1834: New Visitor Landing Page

- frontend/package-lock.json
Image of PageBanner is not rendered in Safari.
The fix was added in gix-components: https://github.com/dfinity/gix-components/pull/280
* Upgrade gix-components
Not necessary
> Fix: Fix image not shown in Safari

- frontend/package-lock.json
- frontend/package.json
See PR https://github.com/dfinity/ic-js/pull/397 for the reason behind bumping agent-js and de facto ic-js.
> Bump ic-js and agent-js

- frontend/src/tests/lib/pages/NnsProposals.spec.ts
`"should render proposals"` expects `neuronsStore` to be empty.
So if `"should hide proposal card if already voted"`, which mocks `neuronStore`, is run before it, `"should render proposals"` fails.
`neuronStore` is already reset in `beforeEach` but resetting the real store doesn't help once the store is mocked.
So we either need to restore the mock, or use the real store instead of mocking it.
Why not both?
Also `"should render proposals"` expects `proposalsFiltersStore` to be empty so it needs to be reset after other tests fill it.
Lastly, the tests in `"log in and out"` expect `authStore` and `GovernanceCanister` to be already mocked, so those setups need to go to the top-level as well.
1. Use real `neuronStore` instead of mocking it.
2. Restore all mocks in top-level `beforeEach` to …
>  Fix order dependence in NnsProposals.spec.ts

- frontend/package-lock.json
Use new functionality in sns-js that throws a specific error when method is not supported by the canister.
* Upgrade next dependencies.
* Not applicable.
Not necessary.
> Chore: Upgrade next dependencies

- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
Clean up an unnecessary describe in Nns and Sns neuron detail pages.
* Remove describe in NnsNeuronDetailPage.spec
* Remove describe in SnsNeuronDetailPage.spec
Not necessary.
> Chore: Clean up extra describe in NeuronDetails

- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release candidate changes.
- Changelog
- Patch versions
> Update changelog after release

- frontend/package-lock.json
We released a version of ic-js so this PR integrates the next version (numbers) of ic-js.
> Bump ic-js next

- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release candidate changes.
- Changelog
- Patch versions
> Release 2023 09 06

- frontend/package-lock.json
- frontend/src/lib/utils/anonymize.utils.ts
- frontend/src/lib/utils/sns-ledger.utils.ts
- frontend/src/tests/mocks/icrc-transactions.mock.ts
Bump ic-js which was updated with last did files of the CMC, ledger and index canisters.
- bump lib
- update anonymize function to leverage new `approve` type.
No particular test added for `approve` and `spender` fields because those are related to ICRC-2 which NNS dapp does not implement yet in any features.
> Bump bump ic-js

- .github/workflows/update-snsdemo.yml
- CHANGELOG-Nns-Dapp.md
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_swap.patch
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.patch
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
- scripts/mk_nns_patch.test
- scripts/update-snsdemo
- scripts/update_ic_commit
We would like to have the latest NNS and SNS canisters to test against.
* Update snsdemo to the latest version - this provides a snapshot with the latest canisters.
* Update .did files to match the latest canisters.
* Add action to repeat this process.
- See CI
> Snsdemo update

- CHANGELOG-Nns-Dapp.md
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
- rs/sns_aggregator/src/types/ic_sns_governance.patch
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.patch
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.patch
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.patch
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
Bring the IC commit & testing environment up to date.
* Bump the snsmdemo
* To match the snsdemo:
* Bump the IC commit
* Bump the dfx version
See CI
> Bump snsdemo

- CHANGELOG-Nns-Dapp.md
- frontend/src/lib/i18n/en.json
Inconsistency in how the topic is displayed in the proposals and in the list of topics for followees.
* Change the value of `topic_8_title`.
Text not tested directly.
> Chore: Change i18n value

- frontend/src/tests/lib/services/sns.services.spec.ts
- frontend/src/tests/lib/stores/sns.store.spec.ts
Clean up after removing `ENABLE_SNS_AGGREGATOR_STORE` feature flag.
* Remove the "describe"s related to `ENABLE_SNS_AGGREGATOR_STORE` feature flag.
Not necessary.
> Chore: Remove describes of aggregator store feature flag

- frontend/package-lock.json
I want to use some new functionality in ic-js.
In this PR, upgrade the ic-js dependencies.
Only changes from running `npm run upgrade:next`.
Tests still pass.
Not necessary.
> Chore: Upgrade next deps

- frontend/package-lock.json
`npm run gix:update` to get access to new component(s)
Still works.
Not necessary
> Update gix-components 2.7.0-next-2023-09-22.1 -> 2.7.0-next-2023-10-05

- frontend/src/vitests/tsconfig.json
VSCode was no able to understand the global `vi` nor the imports of vitests directory.
* Add `tsconfig.json` within the `vitests` directory.
Only changes in tests.
Not necessary.
> Chore: Improve VSCode with vitest

- frontend/src/vitests/lib/components/sns-proposals/SnsProposalCard.spec.ts
Enable and fix a skipped test in SnsProposalCard.spec.
* Mock timers in SnsProposalCard.spec. Fix related tests.
* Add expectations in `"should render deadline"`.
Not necessary.
> Chore: Enable and fix skipped test

- frontend/src/lib/components/accounts/WalletPageHeader.svelte
- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/tests/page-objects/WalletPageHeader.page-object.ts
- frontend/src/tests/page-objects/WalletPageHeading.page-object.ts
- frontend/src/vitests/lib/components/accounts/WalletPageHeader.spec.ts
- frontend/src/vitests/lib/components/accounts/WalletPageHeading.spec.ts
Change the header of the wallet details page.
In this PR, I introduce the components that will be used in the NnsWallet, SnsWallet and CkBTCWallet in another PR.
* New components WalletPageHeader and WalletPageHeading.
* Test and PO for WalletPageHeader.
* Test and PO for WalletPageHeading.
Not yet.
> GIX-1860: Wallet Header Components

- frontend/src/lib/components/proposal-detail/NnsProposal.svelte
- frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
Redesign proposal summary block (behind the flag)
~~- [ ] Related PR https://github.com/dfinity/gix-components/pull/306~~ (not required anymore)
- redesign
No new logic presented.
Not necessary
> Redesign proposal summary

- CHANGELOG-Nns-Dapp.md
Remove duplication from the changelog.
- remove duplications.
Work
Not necessary.
> Cleanup changelog

- frontend/src/vitests/lib/components/project-detail/ProjectCommitment.spec.ts
- frontend/src/vitests/lib/modals/sns/SnsActiveDisbursementsModal.spec.ts
Migrate tests to vitest.
In this PR, migrate ProjectCommitment and SnsActiveDisbursementsModal.
* Migrate ProjectCommitment and SnsActiveDisbursementsModal.
* Move local variable in SnsActiveDisbursementsModal inside `describe`.
Not necessary.
> Chore: Fix open handles tests

- declarations/nns_governance/nns_governance.did
- dfx.json
Use the new field for Neurons' Fund enhancements in SNS Aggregator.
From running workflow "Update snsdemo".
Still passing.
Not necessary.
> GIX-1960: Upgrade IC Commit

- frontend/package-lock.json
- frontend/src/tests/lib/components/proposal-detail/ProjectSystemInfoSection.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalSystemInfoSection.spec.ts
- frontend/src/tests/page-objects/ProjectCommitment.page-object.ts
- frontend/src/tests/page-objects/ProposalSystemInfoSection.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronVotingPower.page-object.ts
- frontend/src/tests/page-objects/SnsProposalSystemInfoSection.page-object.ts
`npm run update:gix` to make new icons available.
Work
Not necessary
> Update gix components

- frontend/package-lock.json
- frontend/src/lib/utils/anonymize.utils.ts
Upgrade ic-js depenencies.
* Changes in package.lock.json. Using npm script `npm run upgrade:next`.
* Add `isGenesis` to anonymize.
* Return `undefined` from anonymize helpers if `neuron` is undefined or null.
Still passing
Not necessary.
> Feat: Upgrade next dependencies

- frontend/src/lib/components/proposal-detail/ProposalNavigation.svelte
- frontend/src/lib/components/universe/UniverseLogo.svelte
- frontend/src/lib/pages/NnsProposalDetail.svelte
- frontend/src/lib/pages/SnsProposalDetail.svelte
- frontend/src/tests/lib/components/proposal-detail/ProposalNavigation.spec.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/page-objects/ProposalNavigation.page-object.ts
Update proposal navigation style.
- move title into navigation block
- add universe logo
- buttons style
Updated.
Not necessary
> Redesign proposal navigation

- declarations/nns_governance/nns_governance.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.patch
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
* Updated the NNS canister `.did` file imports and derived rust code.
* DONE: The code will probably NOT compile if there have been significant changes to the NNS-dapp APIs.
DONE: Please check the Rust code and make minimal changes to make the code compile.
* Patch files after the job "SNS Aggregator patches" fails. The changes needed are in the failed job.
> Update snsdemo commit

- CHANGELOG-Nns-Dapp.md
We can't merge the branch with the hotfix to update the Changelog wiht a new proposal entry.
Instead, to keep the changelog accurate, I added an entry manually.
* Changelog NNS Dapp.
No.
> Chore: Update changelog after hotfix proposal

- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
When withdrawinig BTC, the transactions can reloaded twice. Once while the modal is open and showing the 4 steps (reloading is the last ste) and once after the modal is closed.
The second reload is unnecessary.
Before I fix this issue, I want to add a test that demonstrates it so it's clear that the issue is fixed when it is.
Add tests that check that the balance and transactions are reloaded after making a BTC withdrawal. These test mirror the 2 tests before it which test the same for making ckBTC transactions.
The final expectation shows the additional unnecessary reload.
Only tests
not necessary
> Add tests for withdrawing BTC

- dfx.json
> Update snsdemo to release-2023-11-02

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/proposal-detail/ProposalNavigation.svelte
- frontend/src/lib/components/proposal-detail/ProposalVotingSection.svelte
- frontend/src/lib/components/proposal-detail/VotesResults.svelte
- frontend/src/lib/components/proposal-detail/VotesResultsMajorityDescription.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalVotingSection.svelte
- frontend/src/lib/components/universe/UniverseLogo.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Redesign of the proposal voting section.
- new progressbar logic (yes, no, total)
- simple majority + absolute majority
Works
> Voting block redesign

- frontend/src/lib/components/proposals/NnsProposalCard.svelte
- frontend/src/lib/components/proposals/ProposalCard.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalCard.svelte
- frontend/src/lib/components/ui/ProposalStatusTag.svelte
- frontend/src/lib/constants/proposals.constants.ts
- frontend/src/lib/constants/sns-proposals.constants.ts
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/tests/lib/components/proposals/NnsProposalCard.spec.ts
- frontend/src/tests/lib/components/proposals/ProposalCard.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalCard.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
Replace proposal tags in proposal cards.
- replace tags with ProposalStatusTag component
- remove unused consts
Worsk
> Replace all status tags with the new component

- frontend/src/lib/components/common/TreeJson.svelte
- frontend/src/lib/components/project-detail/ProjectProposal.svelte
- frontend/src/lib/components/proposal-detail/ProposalNavigation.svelte
- frontend/src/lib/components/proposal-detail/VotesResults.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
A set of small style changes after review.
- project proposal title gaps
- adjust proposal navigation mobile gaps
- use yes/no labels
- decrease json 1st level key size
Works. No logic changes.
> Style adjustments 

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC .did files

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/common/JsonPreview.svelte
- frontend/src/lib/components/common/TreeJson.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Add collapse all functionality to json tree view.
- removed unused var `_collapsed`
- add collapse all button
> Tree json collapse all

- CHANGELOG-Nns-Dapp-unreleased.md
- dfx.json
See https://github.com/dfinity/nns-dapp/pull/3697
Add `devenv_dskloet` network section to `dfx.json`.
Tested manually with
```
$ scripts/canister_ids --import-from-index-html https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/ --network devenv_dskloet
$ DFX_NETWORK=devenv_dskloet ./config.sh
$ cd frontend
$ npm run dev
```
> Add devenv_dskloet to dfx.json

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files

- frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
More readable and maintainable.
Use page objects in `frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts`.
yes
not necessary
> Use page objects in CkBTCTransactionsList.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Branch for the release candidate merged in 13th of November 2023.
* Changelog update.
* NNS Dapp version bump
Not necessary.
> Release branch: 2023-11-13

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- dfx.json
- scripts/nns-dapp/downgrade-upgrade-test
- scripts/nns-dapp/test-account.test
- scripts/sns/aggregator/downgrade-upgrade-test
- scripts/sns/aggregator/test-config
* Update snsdemo to a release built with dfx v15
* Update dfx to v15
* Add --yes to those remaining `dfx canister install` calls where do don't do so yet; there are more interactive questions.
- See CI
> Update snsdemo to release-dfx-15

- frontend/src/lib/components/proposal-detail/VotesResults.svelte
Update absolute majority progress symbol as part of the voting section design changes.
style
Not necessary.
> style: update absolute majority progress symbol

- dfx.json
> Update snsdemo to release-2023-11-15

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store/schema/label_serialization.rs
- rs/backend/src/assets.rs
- rust-toolchain.toml
> Update rust version to 1.74.0

- frontend/src/lib/pages/SignInAccounts.svelte
- frontend/src/lib/pages/SignInCanisters.svelte
- frontend/src/lib/pages/SignInNeurons.svelte
- frontend/src/lib/pages/SignInSettings.svelte
- frontend/src/lib/themes/global.scss
Remove unnecessary code.
The style is already in the PageBanner from the new gix-components.
* Remove style for `main.sign-in`.
* Remove adding the class.
Not necessary.
> Chore: Remove unnecessary class

- frontend/src/lib/components/tokens/TokensTable/actions/SendButton.svelte
Icon for the Send action in TokensTable has changed.
* Change the icon in the SendButton.
Not necessary
Not necessary
> GIX-2089: Update Send icon

- CHANGELOG-Sns_Aggregator.md
[Proposal 126006](https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=126006) has passed, updating the aggregator in production.
- Move changelog entries from "unreleased" into the section for this proposal.
None
> Update SNS aggregator changelog

- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
Split tests in NnsAccounts depending on feature flag.
* Move tests within `"when tokens flag is disabled"`.
Not necessary.
> Chore: Move test to describe

- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
There was a text not using i18n.
* Use i18n instead of a hardcoded text.
* Not necessary, it's a static text.
Not necessary.
> Chore: Remove hardcoded text

- dfx.json
> Update snsdemo to release-2023-11-22

- frontend/src/lib/components/proposal-detail/JsonRepresentationModeToggle.svelte
- frontend/src/tests/lib/components/common/JsonRepresentationModeToggle.spec.ts
- frontend/src/tests/page-objects/JsonRepresentationModeToggle.page-object.ts
Test for `JsonRepresentationModeToggle` component.
- po
- test
Yes
Not necessary
> test: for JsonRepresentationModeToggle

- .github/workflows/checks.yml
- scripts/nns-dapp/migration-test
- scripts/nns-dapp/migration-test.getters
- scripts/nns-dapp/migration-test.getters.test
The function that sets the schema in arguments needs tests.
- Define a schema getter - useful for checking whether the setter has worked correctly.
- Write tests for the getter and setter.
- Fix bug.
- Exercise the tests in CI
Tests form the majority of this PR.
- Covered by an existing entry
> Schema getter setter tests

- frontend/src/lib/routes/Accounts.svelte
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
Add services to load the token and accounts of ICRC tokens.
* New icrc accounts services `loadIcrcToken`, `loadIcrcAccount` and `loadIcrcBalances`
* Test new services.
> GIX-2117: Add cketh services

- frontend/package.json
There is no way I could remember the command to start a snapshot and given that I use multiple laptop, setting a local alias isn't an option neither.
Therefore this adds a command to start a snapshot with a npm command.
> Start-snapshot command

- frontend/src/lib/api/dev.api.ts
- frontend/src/lib/components/ic/GetTokens.svelte
- frontend/src/lib/services/dev.services.ts
Get ckETH tokens in dev environment to test features.
* Implement the "GetTokens" component for ICRC Token universe.
* New dev apis `getIcrcTokenTestAccountBalance` and `acquireIcrcTokens`.
* New dev service `getIcrcTokens`.
No tests. Only for dev environment.
Not necessary.
> GIX-2121: Get ckETH test tokens

- dfx.json
Extend `dfx.json` with `devenv_mstr`.
Not necessary.
> Add mstr to dfx config

- frontend/package-lock.json
- frontend/src/tests/mocks/sns-proposals.mock.ts
Upgrade ic-js to 2.1.0-next-2023-11-21.1
`npm run upgrade:next`
Works
Not necessary.
> Upgrade ic-js to 2.1.0-next-2023-11-21.1

- CHANGELOG-Nns-Dapp-unreleased.md
The changelog entry came back with a bad merge in https://github.com/dfinity/nns-dapp/pull/3929
Remove the entry.
no
> Remove zombie CHANGELOG entry

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
There is a vulnerability when running `npm audit`. Not important, but let's keep dependencies clean of vulnerability.
* Changes in package-lock.json after running `npm audit fix`.
Still passing.
> Chore: Fix npm vulnerability

- CHANGELOG-Nns-Dapp-unreleased.md
- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
Release branch for new deployment of 5th December 2023
* Changelog files: `scripts/nns-dapp/split-changelog`.
* Cargo and package.json files: `./scripts/nns-dapp/bump-patch`.
Not applicable
> Release for 2023-12-04

- dfx.json
> Update snsdemo to release-2023-12-06

- rs/backend/src/accounts_store.rs
We are getting more users.
* Increase the account limit.
- Existing tests should suffice.
> Bump the account limit

- frontend/src/lib/types/tokens-page.ts
Better understand the Tokens page types.
* Add a comment at the top of the `tokens-page.ts`.
Not necessary.
Not necessary.
> Docs: Improve tokes page types

- dfx.json
> Update snsdemo to release-2023-12-18

- frontend/src/lib/pages/Launchpad.svelte
Change proposals-block position on launch page (on mobile).
From:
1. Current Launches
2. Launched
3. Proposals
To:
1. Current Launches
2. Proposals
3. Launched
- styles on launchpad page
Still works
> style: rearrange proposals on launchpad page

- frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
Somehow this is only caught after reverting SvelteKit. https://github.com/dfinity/nns-dapp/pull/4149
Fix import lint.
no
no
> Fix import lint

- frontend/src/tests/lib/components/accounts/TransactionList.spec.ts
Make the test more maintainable and easier to read.
Use a page object in `TransactionList.spec.ts`.
only
not necessary
> Use page object in TransactionList.spec.ts

- frontend/package-lock.json
There is a UI bug when the user has many subaccounts the "Add Account" button is in front of the footer.
The fix was to remove the `z-index` in the `"ghost"` button.
In this PR, I upgrade gix-components to add the fix.
* package.lock.json with `npm run update:gix`.
Still passing.
> Fix: Add button in front footer

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/canisters/ic-management.canister.spec.ts
- frontend/src/tests/lib/utils/enum.utils.spec.ts
- frontend/src/tests/lib/worker-api/canisters.worker-api.spec.ts
Add "management of api boundary nodes" topic support.
- add topic title and description (copied from the dashboard)
- add new fields to mock data
- pass
The last one:
> Add management of api boundary nodes topic

- frontend/package-lock.json
Update theme colors.
* Changes in package-lock.json by running `npm run update:fix`.
Still passing.
Not necessary.
> Fix: Change theme colors

- frontend/src/tests/e2e/ckbtc.spec.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
Enable the My Tokens flag in mainnet.
In this PR, migrate the ckbtc e2e test to the tokens page.
* Enable tokens flag in ckbtc.spec and adapt some flows.
* Add method `waitForBalance` to TokensTableRow.
Not necessary.
> GIX-2080: Fix ckbtc e2e test

- frontend/package-lock.json
- frontend/src/lib/api/canisters.api.ts
There was a breaking change in ic-js. Therefore, I upgrade the depenencies with the fix.
The breaking changes was the new parameters when calling `notifyCreateCanister` on the CMC canister.
* Changes in package.lock.json come from running `npm run upgrade:next`.
* Add new parameters to the `notifyCreateCanister` call. We don't expose them because we don't support those features yet.
Still passing.
Not necessary. No new features were added.
> Chore: Upgrade ic-js

- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/page-objects/SnsNeurons.page-object.ts
1. Use page objects
2. Remove some redundant tests that check for static content that doesn't depend on logic.
yes
not necessary
> Use page objects in SnsNeurons.spec.ts

- frontend/src/tests/lib/modals/sns/SnsStakeNeuronModal.spec.ts
Use page objects in `SnsStakeNeuronModal.spec.ts`.
only
not necessary
> Use page objects in SnsStakeNeuronModal.spec.ts

- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
- frontend/src/tests/lib/components/neuron-detail/NeuronFollowingCard/Followee.spec.ts
- frontend/src/tests/page-objects/Followee.page-object.ts
- frontend/src/tests/page-objects/Tag.page-object.ts
- frontend/src/tests/page-objects/VotingHistoryModal.page-object.ts
1. Add testId.
2. Add page objects.
3. Use page objects.
yes
no
> Use page objects in Followee.spec.ts

- frontend/vitest.setup.ts
Enable tokens flag to true in mainnet.
In this PR, set tokens flag to true in vitest.
* Set `ENABLE_MY_TOKENS` to `true` in vitest.setup.ts
Not necessary
> GIX-2080: Set ENABLE_MY_TOKENS true in vitest

- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/neurons/SetNnsDissolveDelay.svelte
- frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
- frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
Requested in point 12-13 of https://www.notion.so/dfinityorg/Wording-Changes-4411020138ce4d09b6605ad1fdbb9555
1. Add an extra description about dissolve delay.
2. Change the description about voting power.
Both NNS and SNS.
NNS
SNS
covered
> Text change in dissolve delay

- dfx.json
> Update snsdemo to release-2024-01-24

- frontend/src/lib/derived/debug.derived.ts
- frontend/src/lib/directives/debug.directives.ts
Access to information in production in case of bugs or issues.
In this PR, add stores that were not included in the debugStore.
* Add icrcAccountsStore, icrcCanistersStore and tokensStore to debugStore.
* Anonymize the data in icrcAccountsStore.
Not necessary.
Not necessary.
> Feat: Add missing store to debug store

- rust-toolchain.toml
> Update rust version to 1.75.0

- dfx.json
> Update snsdemo to release-2024-01-31

- frontend/package-lock.json
Upgrade `ic-js` to get latest `NnsFunction` enum changes.
Needed for https://github.com/dfinity/nns-dapp/pull/4310
Pass
Not yet
> npm run upgrade:next

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
Build gix-cmp to:
- Fix QR-code reader incorrectly mirrored on Samsung S23.
- Prevent the 1Password extension from appearing in input fields.
> Bump gix to fix qr-code reader mirroring and 1pwd plugin

- rs/backend/src/perf.rs
- rs/proposals/src/lib.rs
- rs/proposals/src/main.rs
- rs/sns_aggregator/src/fast_scheduler.rs
- rs/sns_aggregator/src/lib.rs
- rs/sns_aggregator/src/types/slow.rs
- rs/sns_aggregator/src/upstream.rs
Reduce the number of clippy::pedantic warnings.
- Fix some pedantic warnings.
-  See CI
Too minor
> chore: Reduce pedantic warnings

- frontend/src/tests/lib/pages/SnsWallet.spec.ts
Remove usage of ENABLE_MY_TOKENS flag.
In this PR, remove it from SnsWallet.spec
* Remove using the flag in SnsWallet.spec. It's not used in the actual component anymore. Therefore, no other changes were required.
Not necessary.
> Chore: Remove flag from SnsWallet

- .github/workflows/update-sns-aggregator-response.yml
Fix failing CI.
* The name of the shell file was wrong.
Not necessary.
Not necessary.
> Fix: Name of the script in the workflow

- dfx.json
> Update snsdemo to release-2024-02-07

- scripts/nns-dapp/release-sop
Replace the log in `release-sop` script to post in nns group.
- log update
No
Not necessary.
> Replace gix with nns group for posting the RC

- .config/spellcheck.dic
- rs/proposals/src/def.rs
- rs/proposals/src/lib.rs
The rustdoc is still incomplete.
- Add rustdoc by changing `\\` comments to `<<<` and formatting them appropriately. 
- Add more missing function documentation.
N/A
> docs: Add missing rustdocs

- frontend/package-lock.json
I've provided some maintainance PR to ic-js today and also remove/replaced few types. This PR bumps the libraries.
- https://github.com/dfinity/ic-js/pull/542
- https://github.com/dfinity/ic-js/pull/541
- https://github.com/dfinity/ic-js/pull/540
- https://github.com/dfinity/ic-js/pull/539
> Bump next ic-js

- scripts/nns-dapp/release-sop
- scripts/nns-dapp/release-sop-test-successful-release.json
Add a calendar group name because of the changes. The checklist has been updated as well.
- text changes only.
- `release-sop-test-successful-release.json` updated.
Not necessary
> Specify a group for the voting appointment

- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
Cover the no-ballots-fix ([the pr](https://github.com/dfinity/nns-dapp/pull/4420)) with a test.
Steps done:
1. undo the fix
2. describe the correct behaviour in the test
3. test that it fail
4. restore the fix
- test++
Yes
not necessary.
> test: should reload sns proposal

- dfx.json
> Update snsdemo to release-2024-02-14

- frontend/package-lock.json
Fix minor vulnerability.
Ran `npm audit fix`
n/a
not necessary
> SCAVM-745: run npm audit fix

- dfx.json
> Update snsdemo to release-2024-02-20

- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
NNS dapp bots are maintained by the NNS team.
In this PR, I remove myself from the reviewers of the PRs created by the bots.
* Remove "lmuntaner" from reviewers of different workflows.
Not necessary
Not necessary.
> Chore: Remove lmuntaner from reviewers

- frontend/src/tests/workflows/Launchpad/sns-agg-page-0.json
- frontend/src/tests/workflows/Launchpad/sns-agg-page-1.json
- frontend/src/tests/workflows/Launchpad/sns-agg-page-2.json
We would like to keep the ProdLaunchpad.spec up to date with mainnet data.
* Update the files used for the fetch mock in ProdLaunchpad.spec.
> Update SNS Aggregator Response

- rs/backend/src/state/partitions.rs
- rs/backend/src/stats.rs
- rs/backend/src/time.rs
As the code is being handed over to a new team, it is important to document work that still needs to be done.
- Add docs, including two TODOs
N/A
Too minor
> doc: Record some TODOs

- dfx.json
> Update snsdemo to release-2024-02-28

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/nns-dapp/release-sop
- scripts/nns-dapp/release-sop-test-successful-release.json
Andrew is agreed to take care of the forum post.
Update the message about the forum post int he `release-sop` script.
updated
> Update forum post message in release-sop

- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
If a transaction happens from a different tab/browser and you reopen the NNS wallet, you see the new transaction but not the new balance.
1. When mounting the `NnsWallet` component, reload the balance of the account. Only do this if there was already a balance, otherwise `pollAccounts` will already be loading the balance and we want to avoid doing it twice unnecessarily.
2. Don't reload transactions every time the accounts store is updated because it also triggers when the value doesn't change. Instead, generate a string and only reload transactions when the string changes, because this does not trigger when the store is set but the string remains the same. There is a corner case here where the transactions won't be reloaded if there were multiple transactions that together add up to the …
> NNS1-2857: Reload balance when opening NNS wallet

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/proposal-detail/IneligibleNeuronsCard.spec.ts
Extend the ineligible neurons description with more details.
- text only
- adjusted
> Improve ineligible neuron description

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/ic/GetTokens.svelte
Upgrade gix-components.
- `npm run update:gix`.
- replace main menu icons.
- fix "Get Tokens" test button.
- manually in different browsers.
| 🌞 | 🌚 |
| <img width="264" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/a31e9df8-35eb-40f4-9de6-cb57806d259e"> | <img width="288" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/005f5d39-513f-4569-a004-1be94b486fae"> |
> Update gix for menu style

- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts
- frontend/src/tests/page-objects/SnsProposalFilters.page-object.ts
Create and apply `SnsProposalsFiltersPo` to use it in upcoming `Actionable Segment` pr.
- create `SnsProposalsFiltersPo`
- utilise it in  SnsProposalsFilters specs
Yes
Not necessary.
> test: add SnsProposalsFiltersPo

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
Upgrade gix-components to fix collapsed main menu width.
- `npm run upgrade:gix`
Manually that menu width is updated.
> upgrade gix

- rust-toolchain.toml
> Update rust version to 1.77.0

- dfx.json
> Update snsdemo to release-2024-03-20

- rust-toolchain.toml
> Update rust version to 1.77.1

- rs/backend/src/accounts_store/schema/proxy/migration.rs
- rs/backend/src/state/partitions/schemas.rs
The security review found some incorrect comments.
- Correct the rustdocs.
None
> Fix comments

- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotableNeuronList.spec.ts
- frontend/src/tests/page-objects/VotableNeuronList.page-object.ts
- frontend/src/tests/page-objects/VotingNeuronSelectList.page-object.ts
1. Add page object `VotableNeuronListPo` for `VotableNeuronList`.
2. Use `VotableNeuronListPo` in `VotableNeuronList.spec.ts`.
only tests
not necessary
> Use page objects in VotableNeuronList.spec.ts

- rust-toolchain.toml
> Update rust version to 1.77.2

- dfx.json
> Update snsdemo to release-2024-04-10

- frontend/package-lock.json
Update gix components to get style adjustments for the `Segment` component.
Locally.
Not needed.
> npm run update:gix

- dfx.json
> Update snsdemo to release-2024-04-17

- frontend/src/lib/components/proposals/ActionableProposalsNotSupported.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
Change unsupported actionables description.
- text changed
- Pass
Not necessary.
> Unsupported actionables description text changes

- rs/backend/src/accounts_store.rs
There is some code to remove duplicates in the vectors of hardware wallet transaction indices.
We no longer append to these vectors so duplicates can no longer appear.
We also no longer read these vectors so we don't care if they have duplicates.
There are also some unused functions to append transaction indices.
1. Remove deduping code.
2. Remove append functions.
Still pass
not necessary
> NNS1-2905: Remove unused transaction code from canister

- frontend/package-lock.json
Pull in the tooltip fix from https://github.com/dfinity/gix-components/pull/416
`npm run update:gix`
not tested
not necessary
> NNS1-2966: Bump gix-components

- CHANGELOG-Sns_Aggregator.md
Add an entry in SNS Aggregator changelog about the code snippets that have been added in PR [#4086](https://github.com/dfinity/nns-dapp/pull/4086).
- add text `Add common code snippets for developers to the "Documentation" chapter on the landing page.`
> docs: add entry for added code snippets in aggregator

- dfx.json
> Update snsdemo to release-2024-05-01

- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/lib/components/proposals/ActionableProposalCountBadge.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
Changes in actionable labels.
- labels.
- Manually.
- Tests updated.
Not necessary.
> Actionable proposals label update

- .github/workflows/update-ic-cargo-deps.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/update-ic-cargo-deps
If we don't keep our IC cargo dependencies up to date it can be very hard to update them later.
Add a script and workflow to automatically create PRs to keep our IC cargo dependencies up to date.
Inspired by: https://github.com/dfinity/nns-dapp/blob/main/.github/workflows/update-ic.yml
Created [this PR](https://github.com/dfinity/nns-dapp/pull/4829) with it.
> NNS1-3047: Job to update IC cargo deps

- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
To make it easier to add new tests for new fields of `TableNeuron`.
1. Define default input and output values for the conversion function.
2. Let individual tests test only a single field by settings all other fields with default values and expect default values.
Only tests.
not necessary
> Simplify individual tests in neurons-table.utils.spec.ts

- frontend/package-lock.json
We released gix-cmp [v4.4.0](https://github.com/dfinity/gix-components/releases/tag/v4.4.0) and we want to hook on the new version number.
- `npm run update:gix`.
> build: bump gix

- frontend/package-lock.json
Update gix-components to make [resetScrollPosition](https://github.com/dfinity/gix-components/pull/444) function available.
Pass
Not necessary
> Update gix-components 2024-06-19

- .github/workflows/update-didc.yml
- .github/workflows/update-ic-cargo-deps.yaml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
Make it easier to recognize PRs made by automatic workflows.
Prefix the PR title of all automated PRs with `bot: `.
Not tested.
not necessary
> Prefix all bot PRs with 'bot: '

- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
Many tests in `NeuronsTable.spec.ts` share the same test neurons.
This makes it challenging to update the tests when changing the logic while making sure all the tests still test what they intended to test.
If each test defines its own input values, the tests can be less dependent on each other.
Remove most of the fields from the globally defined test neurons and specify only the relevant values for individual tests.
yes
not necessary
> Use per-test values in NeuronsTable.spec.ts

- frontend/src/tests/workflows/Launchpad/sns-agg-page-0.json
- frontend/src/tests/workflows/Launchpad/sns-agg-page-1.json
- frontend/src/tests/workflows/Launchpad/sns-agg-page-2.json
- frontend/src/tests/workflows/Launchpad/sns-agg-page-3.json
We would like to keep the ProdLaunchpad.spec up to date with mainnet data.
* Update the files used for the fetch mock in ProdLaunchpad.spec.
> bot: Update SNS Aggregator Response

- dfx.json
> bot: Update snsdemo to release-2024-07-08

- dfx.json
> bot: Update snsdemo to release-2024-07-10

- dfx.json
> bot: Update snsdemo to release-2024-07-17

- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
We want the projects table to be sorted as follows:
1. Internet Computer
2. Projects with neurons alphabetically
3. Projects without neurons alphabetically
1. Add sorting function
2. Using sorting function in `ProjectsTable` component.
1. Unit tests added for sorting function.
2. Unit test added for ProjectsTable.
not yet
> NNS1-3094: Sort projects in the table

- frontend/src/tests/lib/components/ic/AmountDisplay.spec.ts
1. Use page object.
2. Use and expect specific values rather than just re-implementing the rendering logic in the test.
only tests
not necessary
> Clean up AmountDisplay test

- frontend/package-lock.json
We want to pull in the latest changes.
* Ran `npm run upgrade:next`
* CI should pass
* The pulled in changes should have been tested before being committed to their repositories.
> bot: Bump ic-js

- frontend/package-lock.json
We want to pull in the latest changes.
* Ran `npm run update:gix`
* CI should pass
* The pulled in changes should have been tested before being committed to their repositories.
> bot: Bump gix-components

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/utils/anonymize.utils.ts
- frontend/src/tests/mocks/neurons.mock.ts
Bump ic-js version and fix the build
Adding the new field `visibility` in `Neuron` and `NeuronInfo` and pass them through in anonymization
N/A
- [ x] Add entry to changelog (if necessary).
> Fix build issue after bumping ic-js

- rust-toolchain.toml
If manual changes are required, please make a separate PR.
PRs created by bots should only contain automated changes to avoid any confusion.
> bot: Update rust version to 1.80.1

- dfx.json
> bot: Update snsdemo to release-2024-08-07

- dfx.json
> bot: Update snsdemo to release-2024-08-14

- dfx.json
> bot: Update snsdemo to release-2024-08-21

- frontend/src/lib/components/warnings/TestEnvironmentWarning.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
To enhance the visibility and effectiveness of the warning message displayed when users are accessing the beta version of the site, we have updated the text and adjusted the button color. These changes are intended to draw more attention to the message, ensuring that users recognize its importance.
- Text and style changes.
- Redundant DOM paragraph elements have been removed since their labels are no longer needed.
- Tested locally. No changes in the logic.
| <img width="525" alt="image" src="https://github.com/user-attachments/assets/f796a77f-de24-47b0-937b-39c98d406062"> | <img width="528" alt="image" src="https://github.com/user-attachments/assets/ef57f97a-bd2c-41fc-bd50-0d1d47b47a7d"> | 
Not necessary.
> Update test environment warning

- .github/workflows/update-aggregator.yml
Since Arshavir and I are maintaining the SNS backend, and the aggregator feels like it's more part of the sns backend than the frontend, it makes sense that we review some of the PRs to the aggregator, and IIUC these are the most common PRs. @dskloetd has been reviewing them until now, so if we have questions for what to look for during the reviews, we can maybe ask him for help.
> ci: add Andre and Arshavir as reviewers of automatic aggregator .did updates

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/stores/busy.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
Imported tokens should meet the following requirements:
- to be not a duplication,
- not an SNS,
- not an important ck token (CKBTC etc),
- able to provide metadata,
- the index canister’s ledgerId API returns the entered ledger ID.
**Note:** The busy screen should be shown only for validations that require remote calls.
- Add validation logic to the import token form.
- Error labels added.
- Tests added.
Not necessary.
> Import token form validation

- rs/backend/src/accounts_store.rs
The account limit was put in place to limit the number of accounts before the migration to stable memory.
But we want to keep the account limit in place to mitigate attacks, even with accounts in stable memory.
Rename `PRE_MIGRATION_LIMIT` to `ACCOUNT_LIMIT` and change the comment to make sure the limit doesn't get removed as part of the migration cleanup.
not necessary
> Rename PRE_MIGRATION_LIMIT to ACCOUNT_LIMIT

- frontend/src/tests/lib/pages/NnsProposals.spec.ts
We normally mock the API layer unless we are testing the API.
`NnsProposals.spec.ts` was mocking the canister and even had a TODO not to do that.
Mock `proposalsApi.queryProposals` instead of `GovernanceCanister`.
Test only change.
not necessary
> Mock proposals API instead of GovernanceCanister in NnsProposals.spec.ts

- rust-toolchain.toml
If manual changes are required, please make a separate PR.
PRs created by bots should only contain automated changes to avoid any confusion.
> bot: Update rust version to 1.81.0

- dfx.json
> bot: Update snsdemo to release-2024-09-04

- dfx.json
> bot: Update snsdemo to release-2024-09-17

- dfx.json
> bot: Update snsdemo to release-2024-09-18

- frontend/src/tests/lib/services/public/proposals.services.spec.ts
Make the test easier to maintain.
Using stores is cheap. We shouldn't care how the store got its content. What matters is that the contents is what it should be.
So instead of mocking store methods, we should expect the store contents itself.
1. Use `resetIdentity` and `setNoIdentity` instead of mocking the `authStore`.
2. Check the contents of the `toastsStore` instead of mocking the calls to `toastsShow`.
1. Also check the actual error message in the toast rather than only that there is a toast.
3. Check the contents of `proposalsStore` instead of mocking its methods.
4. Check the contents of `proposalPayloadsStore` instead of mocking its methods.
5. On the remaining mocks, replace `mockImplementation` with simpler methods that directly specify return/resolve/reject values.
1. In 1 case …
> Clean up public/proposals.services.spec.ts

- frontend/package-lock.json
Keeping our dependencies up to date.
Ran `npm audit fix`.
CI passes.
not necessary
> Bump rollup

- dfx.json
> bot: Update snsdemo to release-2024-09-25

- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
Cleanup should go into the top-level `beforeEach` because it makes it less likely that tests start with a different environment left over from a previous test.
1. Move all reset/cleanup calls from `beforeEach` in sub-blocks to the top-level `beforeEach`.
2. Use `resetIdentity`/`setNoIdentity` consistently instead of sometimes calling `authStore.setForTesting()`.
Test only
not necessary
> Do cleanup in top-level beforeEach in SnsProposalDetail.spec.ts

- frontend/package-lock.json
npm audit found 2 low severity issue.
Ran `npm audit fix`.
CI
not necessary
> Run npm audit fix

- CHANGELOG-Nns-Dapp-unreleased.md
Inconsistent bullet point syntax.
- Replace `-` with `*`.
No, changelog update only.
Not necessary.
> Fix the bullet point syntax

- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic-cargo-deps.yaml
- .github/workflows/update-next.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
NNS dapp bots are maintained by the NNS team.
In this PR, I remove myself from the reviewers of the PRs created by the bots.
* Added "yhabib" to reviewers of different workflows.
Not necessary
Not necessary.
> Chore: Add yhabib to reviewers

- dfx.json
> bot: Update snsdemo to release-2024-11-13

- dfx.json
To be able to connect with dfx remotely to the DevEnv. This is done during the release process, for example.
- Adds devenev_yhabib to list of envs.
Not required
> Adds devenev_yhabib 

- .github/workflows/update-didc.yml
- .github/workflows/update-ic-cargo-deps.yaml
- .github/workflows/update-next.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
This is part of a larger effort to replace PATs generated my service accounts with GitHub Apps. Context: https://github.com/dfinity/ic/pull/2717
No functional changes.
> chore(IDX): replace PAT with GitHub App

- frontend/src/lib/utils/transactions.utils.ts
This comment was added in #2164, but the referenced function was later removed in #3777.
- Removes unnecessary comment
> housekeeping: Removes outdated comment

- frontend/package-lock.json
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Users should be notified about neurons that are losing rewards. For these neurons, a "Missing Rewards" tag should be displayed. 
Note: This feature should be behind a flag. The "Losing Soon" tag will be added in a separate PR.
- Make getNeuronTags function to return new tag data.
- Updated.
Not necessary.
> New "Missing rewards" neuron tag

- README.md
Original #5931
- Updated the Discord link in the README.
Not necessary
Not necessary
> update discord link 

- frontend/package-lock.json
Prodsec inquiry related to [security vulnerability in nanoid](https://github.com/advisories/GHSA-mwcw-c2x4-8c55).
- `npm audit fix`
> fix: low security vulnerability in nanoid

- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/neurons/LosingRewardsBanner.spec.ts
Refine the wording for labels related to confirming following.
- Labels.
- Updated.
Not necessary.
> Confirming following labels update

- frontend/src/lib/components/reporting/ReportingNeuronsButton.svelte
- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/reporting/ReportingNeuronsButton.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
Refine the wording for the labels on the Reporting page.
- Changed labels
- Added copy for the busy screen.
- Updated tests
Not necessary
> NNS1-3485: updates the copy on the Reporting page

- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/reporting/ReportingNeuronsButton.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
Changes to the copy in the Reporting page.
- Changes copy in the Reporting page
> NNS1-3485: changes copy  in the reporting page

- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
Replace the check icon to match the design.
- Replaced with the filled version.
- Manually
| <img width="712" alt="image" src="https://github.com/user-attachments/assets/04578ac9-a121-48d8-84b4-73a3b62a8191" /> | <img width="661" alt="image" src="https://github.com/user-attachments/assets/ceff87cc-0e6c-4d54-a198-600efe3042f7" /> | 
It intentionally became smaller.
Not necessary.
> Replace check icon

- frontend/package-lock.json
Update the Gix components to the next version to make `--banner-background` available.
- Quickly tested random pages in both themes to ensure they look good.
Not necessary.
> Bump gix components version

- frontend/src/lib/components/portfolio/Card.svelte
- frontend/src/lib/components/portfolio/LoginCard.svelte
- frontend/src/lib/pages/Portfolio.svelte
Get closer to the design reference.
Ticket [NNS1-3519](https://dfinity.atlassian.net/browse/NNS1-3519)
- Some style changes to improve how cards are shown.
Not necessary
Next PR: #6087 
[NNS1-3519]: https://dfinity.atlassian.net/browse/NNS1-3519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(styles): adjust Portfolio components styling

- frontend/src/lib/i18n/en.json
- Update empty state card messages
Not necessary
> style(portfolio): updates the copy for the empty cards

- rs/backend/src/accounts_store.rs
The `AccountsStore` has a field called `pending_transactions`, which has been unused for 2 years.
https://github.com/dfinity/nns-dapp/pull/2059 added a TODO to remove it.
1. Remove the `pending_transactions` field from `AccountsStore`.
2. When encoding the slot of `pending_transactions`, encode a map of `candid::Empty` instead.
3. When decoding the slot of `pending_transactions`, decode into `candid::Reserved` instead.
4. Remove the unused type `TransactionType`.
1. Existing tests pass.
no necessary
> Remove unused pending_transactions

- frontend/src/lib/i18n/en.json
We want to update the content of the portfolio page.
- Changes to content
- They should pass as before
Not necessary
> style(portfolio): content changes to the portfolio cards

- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
To simplify the token import process, the user can import a custom icrc1 token by clicking a link, and the import token form will be pre-filled with the parameters from the URL (e.g. //nns.ic0.app/tokens/?import-ledger-id=m7h5t-euaaa-aaaaa-qabia-cai&import-index-id=myg3h-jmaaa-aaaaa-qabiq-cai). Having the ledger canister ID is sufficient to add an imported token.
In this PR, a separate duplication flow was introduced. When a user tries to import a token that has already been imported, they will be navigated to the token’s wallet page with a warning toast.
- Update validation logic.
- Updated.
- The essential part of "should wait for imported tokens to be loaded before validation" was moved to ["imports from URL"](https://github.com/dfinity/nns-dapp/pull/6277/files#diff-7745ff6765e1e8431163 …
> Import token same token validation

- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
- frontend/src/tests/page-objects/ProjectDetail.page-object.ts
- frontend/src/tests/page-objects/SaleInProgressModal.page-object.ts
1. Add `SaleInProgressModalPo`.
3. Update `ProjectDetailPo`
3. Use page objects in `ProjectDetail.spec.ts`
Tests only
not necessary
> Use page objects in ProjectDetail.spec.ts

- config.json
- declarations/used_by_proposals/nns_governance/nns_governance.did
- declarations/used_by_proposals/nns_registry/nns_registry.did
- declarations/used_by_proposals/sns_wasm/sns_wasm.did
- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
- scripts/nns-dapp/test-proposal-payload
#6435 failed because some expected fields were removed from one of our tests. 
This PR updates the proposal candid binding and additionally fixes the issue with the test.
- Checked out #6435
- Fixed tests by removing expectation on `ecdsa_config`.
- Tests should pass as before.
Not necessary
> chore: update proposals candid bindings

- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
The purpose of `runResolvedPromises()` is to make sure things that should have already happened, have happened.
Adding more `await runResolvedPromises()` to a test should never cause it to fail, because the things that it causes to happen could have happened anyway, if the framework changes what is sync/async etc.
So the following pattern is wrong and brittle and should be avoided
```
expect state A
await runResolvedPromises()
expect state B
```
If we want something like that, we should always explicitly make sure that whatever causes state B doesn't happen at first and happens later.
The wrong pattern was used `ImportTokenModal.spec.ts`.
This caused the test to fail when trying to upgrade to Svelte 5.
1. Change tests that use the wrong pattern described above, to explicitly block by …
> Fix usage of runResolvedPromises() in ImportTokenModal.spec.ts

- .github/workflows/update-didc.yml
- .github/workflows/update-ic-cargo-deps.yaml
- .github/workflows/update-next.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
Following up on #6476, we want to remove reviewers that are no longer part of the team.
- Removes reviewers
Not necessary
> chore(workflows): remove reviewer

- frontend/src/lib/components/portfolio/LoginCard.svelte
New Cards will be introduced to the top section of the Portfolio page. These changes will require the `LoginCard` to adapt to the size defined by the new cards. 
This PR adds base styles for the `LoginCard` to maintain a consistent appearance regardless of size.
- Adds size related styles to the `LoginCard`
Not necessary
> refactor(portfolio): ui tweaks to LoginCard

- frontend/src/lib/pages/Portfolio.svelte
New cards will be added to the top section of the Portfolio page. We need to create space for them in this section. This PR refactors the grid logic to facilitate the integration of new cards in future PRs.
- Changes grid styles
Not necessary
> refactor(portfolio): restructure top section grid layout

- frontend/src/tests/page-objects/playwright.page-object.ts
Updated error message to "Not implemented" for grammatical correctness and to match error messages in another file for consistency.
- Change error text.
- Pass
Not necessary.
> Update POs error text

- frontend/src/lib/i18n/en.json
Update sns-topics label for improved clarity and consistency in the voting delegation UI.
- Labels.
- Verified locally that the label was replaced
Not necessary.
> i18n(sns-topics): Label update

- .github/workflows/checks.yml
A project has changed its name and our Get SNS job is [failing](https://github.com/dfinity/nns-dapp/actions/runs/14852392195/job/41698299461?pr=6791).
- Change the expectation regarding the project's name.
- Pipeline should pass.
Not necessary.
> chore(ci): update golden data for small-tests

- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic-cargo-deps.yaml
- .github/workflows/update-next.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
For some reason, the #6669 Status Check is not going through, so merging the PR is not working. This PR is a copy of that one.
> build(deps): bump actions/create-github-app-token from 1 to 2

- frontend/src/lib/components/portfolio/StackedCards.svelte
We aim to introduce swipe actions for mobile devices in the `StackedCard` component. This initial pull request prepares the component by migrating it to Svelte 5.
- Refactored code to use Svelte runes.
- There are no logical changes, so tests should pass as before.
-  [ ] Add an entry to the changelog (if necessary). 
Not necessary.
[NNS1-3641]: https://dfinity.atlassian.net/browse/NNS1-3641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(portfolio): migrate stacked card to runes

- frontend/src/lib/components/header/ToggleBalancePrivacyOption.svelte
We want to better understand how users interact with the nns-dapp and which features they utilize.
- New event for the privacy toggle.
Not necessary.
Not necessary.
> feat(events): add privacy toggle interaction event

- .github/pull_request_template.md
Update the PR template to include a to-do for accessibility checks, ensuring they are always part of new pull requests and their reviews.
- Update template with a new check for a11y.
- Reword existing one to simplify flow.
Not necessary.
Not necessary.
> docs(pr): update checklist in PR template

- CHANGELOG-Sns_Aggregator.md
Update SNS Aggregator release notes
> chore: Update SNS Aggregator release notes

- config.json
- declarations/used_by_proposals/nns_governance/nns_governance.did
- declarations/used_by_proposals/nns_registry/nns_registry.did
- declarations/used_by_proposals/sns_wasm/sns_wasm.did
- declarations/used_by_sns_aggregator/sns_governance/sns_governance.did
- declarations/used_by_sns_aggregator/sns_ledger/sns_ledger.did
- declarations/used_by_sns_aggregator/sns_root/sns_root.did
- declarations/used_by_sns_aggregator/sns_swap/sns_swap.did
- declarations/used_by_sns_aggregator/sns_wasm/sns_wasm.did
- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
Support new metrics in API.
New metrics:
SNS
* `treasury_metrics`
* `voting_power_metrics`
* `genesis_timestamp_seconds`
NNS
* `spawning_neurons_count`
This will be followed by manual tests.
> chore: Bump IC types

- frontend/src/lib/utils/agnostic-neuron.utils.ts
- frontend/src/lib/utils/staking-rewards.utils.ts
- frontend/src/tests/lib/utils/staking-rewards.utils.spec.ts
Addresses [NNS1-3921](https://dfinity.atlassian.net/browse/NNS1-3921) by adding a full variety of unit testing among the different possible conditions.
Added unit testing. 
Fixes small calculation bugs in the process.
Verified the numbers agains Bjorn script, verified that the new tests pass.
[NNS1-3921]: https://dfinity.atlassian.net/browse/NNS1-3921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(testing): unit testing for the calculations of the staking rewards 

- frontend/src/lib/i18n/en.json
Improve copy of the Portfolio page.
[NNS1-3989](https://dfinity.atlassian.net/browse/NNS1-3989)
- Update copy
[NNS1-3989]: https://dfinity.atlassian.net/browse/NNS1-3989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> content(portfolio): improve page text

- frontend/package-lock.json
Right now, `npm audit` shows 1 low-severity issue.
- Run `npm audit fix`
- Current tests should pass.
> chore(deps): npm audit fix

- frontend/src/lib/constants/sns.constants.ts
- frontend/src/lib/utils/launchpad.utils.ts
- frontend/src/tests/lib/utils/launchpad.utils.spec.ts
Improve how projects are displayed in the Launchpad page.
[NNS-4022](https://dfinity.atlassian.net/browse/NNS1-4022)
- Add new project to featured projects.
- Prioritized market cap over activity when sorting projects.
- Update tests to match new sorting logic.
> feat(launchpad): update projects sorting

- frontend/src/app.html
- frontend/src/lib/i18n/en.json
- frontend/static/manifest.json
Update the copy of the nns-dapp to make it clearer and more understandable for users.
[NNS1-4067](https://dfinity.atlassian.net/browse/NNS1-4067)
- Update copy
- No impact, tests should pass as before.
[NNS1-4067]: https://dfinity.atlassian.net/browse/NNS1-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> content(copy): improve application text clarity

- frontend/package-lock.json
- frontend/src/tests/lib/canisters/ic-management.canister.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NeuronFollowingCard/Followee.spec.ts
- frontend/src/tests/lib/components/proposals/NnsProposalCard.spec.ts
- frontend/src/tests/lib/worker-api/canisters.worker-api.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
There is a new `Action` type for Proposals.
Related to:
* https://github.com/dfinity/nns-dapp/pull/7367
* https://github.com/dfinity/ic-js/pull/1043
* https://github.com/dfinity/nns-dapp/pull/7366
- Run `npm run upgrade:next`
- Updated types and mocks.
> chore: bump ic-js
