rs/src/accounts_store.rs

This is a followup to #215 where we update the logic of the post upgrade hook.
Note that I made a new change to the `pre_upgrade_hook` as well to make it more
efficient, which will require an additional change to the `post_upgrade_hook` once
this PR is deployed.

NNS1-642-p3: Change temporary logic in post-upgrade hook

---

ic-hardware-wallet-cli/ic-hardware-wallet-cli

When using the CLI, an error `Cannot find canister id.` was present in the output of the CLI.
Right now, the TS code assumes the presence of a config file, even though it's not being used by the CLI. In the future, I'll refactor the code such that its independent of this file.

HW CLI: Remove benign error 'Cannot find canister id.'

---

frontend/dart/lib/ic_api/web/web_ic_api.dart
frontend/dart/lib/ui/neurons/detail/neuron_rewards_card.dart
frontend/ts/src/ledger/identity.ts

* Spawning used to return an error - now fixed.
* Instead of disabling the "Merge Maturity" button it is now clickable and
users will get a message that merge maturity isn't yet supported.
* Improvements on error messages when connecting to a Ledger device.

EXC-547, EXC-548, EXC-549: Enhancements to HW wallet UX

---

frontend/dart/lib/ic_api/web/balance_sync_service.dart
frontend/dart/lib/ic_api/web/service_api.dart
frontend/dart/lib/ic_api/web/web_ic_api.dart
frontend/ts/src/ServiceApi.ts
frontend/ts/src/canisters/ledger/Service.ts
frontend/ts/src/canisters/ledger/model.ts

This PR adds additional security when fetching ICP balances from
Ledger.getBalances.
Instead of only having a query call, we now do two calls in parallel:
1. A query call, which is fast but uncertified. We show this result
immediately.
2. An update call, which is certified. We update the page with this
result as soon as it is received.
In 99% of the cases, the result of both calls will be the same and this
change will be completely unnoticeable to the user. There's a slight
chance of some race condition, but in that case, updating the UI with
the certified response remains a sensible approach.

EXC-566: Add "certification" to Ledger.getBalances calls.

---

frontend/dart/lib/main.dart
frontend/dart/lib/ui/transaction/wizard_overlay.dart

In `main.dart` the theme is dependent on the context so we switched it to use the 'builder' pattern which takes the context as an input.
In `wizard_overlay.dart` we have hardcoded the font size rather than pulling it from the context since when using context, `didChangeDependencies` was being called multiple times causing issues on iOS.
This is a bit hacky... it would be better to retrieve the font styles from the context... if any flutter expert out there knows how to make this work your help would be greatly appreciated!

Fix text entry fields on iOS

---

frontend/dart/lib/ic_api/platform_ic_api.dart
frontend/dart/lib/ic_api/web/account_sync_service.dart
frontend/dart/lib/ic_api/web/web_ic_api.dart
frontend/dart/lib/ui/wallet/attach_hardware_wallet.dart

With the latest changes related to PUQ certification, the flow of adding
hardware wallets worked, but the dialog didn't properly close and the
user wasn't redirected to the account's page.
This PR fixes the flow - the dialog now disappears and the user is
redirected to the hardware wallet account's page as before.

EXC-583: Fix flow of adding hardware wallet accounts.

---

build.sh

Based on experimentation, switching to the HTML renderer avoids
the flickering issues users are reporting on Monterey, and fixes the
rendering issues iOS 15 users are reporting.
There are likely some minor UI issues that will be introduced with
this change (especially on Firefox), but that's something we can
live with until we replace Flutter with Svelte.

EXC-704: Switch to HTML renderer.

---

Dockerfile

The previous PR updated the testnet deployment scripts to use the HTML renderer. This PR updates the configuration for mainnet.

Use HTML renderer on mainnet

---

rs/src/assets.rs

Loading javascript modules via script tag fails if the returned mime type is incorrect.  I have observed this with new code and this requirement is documented in the [Mozilla modules guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).
- Provide mime types for static assets, including but not limited to javascript.
- I have verified manually that these mime types are set and that the module loading error goes away.
- There are no full automated tests; I assume that we need a test framework that we currently don't have here (see the comment with details of my attempt writing a test below).  I have one test for the new function but it is trivial; I didn't create an enum for mime types so complete coverage is not robust.
- I have run cargo-clippy and it is clean.
- …

Add mime types to HTTP responses

---

frontend/dart/lib/ui/neurons/tab/neurons_tab_widget.dart

It serves no purpose and can be a potential source of confusion once
HW wallets are released.

Remove the principal text from the neurons page.

---

frontend/dart/lib/ic_api/web/web_ic_api.dart

This PR fixes #273. The fundamental problem lies in the fact that `getPrincipal`
returned a "null" string when the user's session has expired, as opposed to return an
`Option<String>`.
Updating the API to return `Option<String>` (i.e. the proper fix) will involve quite a bit
of changes. The solution I have here is a stop gap measure until we migrate to Svelte.
In the current solution, when fetching the principal, if the principal isn't found, we simply
redirect to the login page.

Redirect to login page if principal is null

---

frontend/ts/src/ServiceApi.ts
frontend/ts/src/canisters/cyclesMinting/Service.ts
frontend/ts/src/canisters/cyclesMinting/builder.ts
frontend/ts/src/canisters/cyclesMinting/canister.did
frontend/ts/src/canisters/cyclesMinting/canister.did.js
frontend/ts/src/canisters/cyclesMinting/canisterId.ts
frontend/ts/src/canisters/cyclesMinting/model.ts
frontend/ts/src/canisters/cyclesMinting/rawService.ts
frontend/ts/src/canisters/nnsDapp/Service.ts
frontend/ts/src/canisters/nnsDapp/canister.did.js
frontend/ts/src/canisters/nnsDapp/model.ts
frontend/ts/src/canisters/nnsDapp/rawService.ts
rs/nns-dapp.did
rs/src/main.rs

This PR makes the NNS Dapp frontend get the ICP to cycles conversion rate from the cycles minting canister rather than from the registry.

Get the ICP to cycles conversion rate from the CMC

---

frontend/svelte/nns-js/package-lock.json
frontend/svelte/nns-js/package.json
frontend/svelte/package-lock.json
frontend/svelte/package.json

`agent-js` (as of `0.10.2`) avoids `ic0.app` subdomains, and thus 307 redirects.

feat: update agent-js from `0.10.1` to `0.10.2`

---

frontend/ts/src/canisters/governance/Service.ts

This is to identify whether the issue we're seeing in
https://forum.dfinity.org/t/8-year-locked-neuron-missing-from-neurons-tab/9619/32
is due to a FE issue or a governance canister issue.

Log response from list_neurons. 

---

.dockerignore
.gitignore
Dockerfile
build.sh
deploy.sh
scripts/deploy-docker-build-to-testnet

The dockerfile and build.sh duplicated code, fell out of sync and eventually caused a deploy to fail.  Therefore we wish to:
- call build.sh in the dockerfile rather than duplicating the code
- be able to deploy docker builds to the testnet, so that we can verify that docker builds work
- Call build.sh in the dockerfile instead of replicating the steps.
- Take the target network as an env var.
- Cleanup and fix until testnet deployments work.
- A difference:  Before assets/NOTICES was included in the docker build.  In build .shit is removed with:
```
rm assets/NOTICES
```
That might explain why test deployments have more space than prod....
If the NOTICES file is left in, new docker builds are identical to the old.  But I will remove the NOTICES file as that seems to be the intent.  The …

Deduplicate build.sh

---

frontend/dart/lib/ic_api/web/web_ic_api.dart
frontend/dart/lib/ui/home/auth_widget.dart
frontend/dart/web/index.html
frontend/dart/web/logout.js
frontend/svelte/rollup.config.js
frontend/svelte/src/App.svelte
frontend/svelte/src/Auth.svelte
rs/src/assets.rs

We wish to use the svelte login page, now that that svelte assets are included in the canister.
This reverts commit bab9ee9ed4949eda7fdc940024e116b079c2226e.
Does it work?  A docker-built canister has been deployed to: https://qhbym-qaaaa-aaaaa-aaafq-cai.peopleparty01.dfinity.network/  using `scripts/deploy-docker-build-to-testnet` (with --no-wallet, which should perhaps be added to the script permanently).
Note: `s/nnsdapp/peopleparty01/g` due to testnet availability.
Are the svelte assets included in mainnet builds?
Yes, as of the dockerfile fix, these assets are in mainnet docker builds:
```
./v2/build/
./v2/build/bundle.css
./v2/build/bundle.js
./v2/build/bundle.js.map
./v2/global.css
./v2/index.html
```
*  Pre-deployment, verify again that the /v2/ files are in the assets.tar.xz …

Revert "Revert "Svelte login cross link (#298)" (#304)"

---

.github/workflows/checks.yml
.github/workflows/docker-build.yaml
Dockerfile

The Dockerfile specifies Ubuntu 20.10, which is beyond end of life and failing to build on github.  It is necessary to update this.  It seems sensible to switch to along term release.
The current state is:
- Our github actions use ubuntu-latest which is Ubuntu 20.04 (see https://github.com/actions/virtual-environments).
- Our dockerfile uses 20.10 which reached end of life in July 2021 (see https://lists.ubuntu.com/archives/ubuntu-announce/2021-July/000270.html).
- The current long term release, 20.04, has standard support until 2025 and reaches end of life in 2030  (see https://wiki.ubuntu.com/Releases).
Use Ubuntu 20.04 explicitly everywhere.
- The github actions should be unaffected as there is no ubuntu version change there, the version is stated explicitly.  No special tests are …

Use Ubuntu 20.04 for everything

---

frontend/svelte/rollup.config.js
frontend/svelte/src/Auth.svelte

There are two environment variables for the internet identity URL.  There should be only one.
- `IDENTITY_SERVICE_URL` already existed in `update_config.sh` and `frontend/ts`
- `IDENTITY_SERVICE_URL` was newly added in svelte
- `s/INTERNET_IDENTITY_URL/IDENTITY_SERVICE_URL/g`

Cleanup: Deduplicate internet identity env var

---

README.md

This PR is currently only relevant for internal developers since the testnets are not currently accessible to the public.
This PR shows the steps involved to setup a testnet where a specific ledger account is pre-loaded with some ICP. The private key of this ledger account is hardcoded into the frontend code so that users wanting to use the NNS Dapp on the testnet can send ICP from this account to their own.

Add instructions for deploying the core NNS canisters to a testnet

---

frontend/svelte/package-lock.json
frontend/svelte/package.json

The local test server was referenced as a bundle dependency.
- Moves `sirv` from a `dependency` to a `devDependency`
- Removes start params `--no-clear` which does not seem to be supported according [README](https://github.com/lukeed/sirv/tree/master/packages/sirv-cli)

build: sirv dev dependency

---

frontend/svelte/rollup.config.js

When developing in svelte with live reloading of the single page app, it is not usually desirable to switch to the legacy app, however such switching will be needed in production during the transition phase.
- Added a compile time environment variable `REDIRECT_TO_LEGACY` that controls whether the switch is made.
- If set to "true" or "1" the flag is considered to be enabled.
- If set to "false" or "0" the flag is considered to be disabled.
- Otherwise the default should match production.  The production default will change over time.
I changed the main app code to:
```
{#if process.env.REDIRECT_TO_LEGACY}
<Auth bind:signedIn bind:principal />
{/if}
```
and ran:
```
REDIRECT_TO_LEGACY=asdfhlkjsdf npm run dev
```
with various values and none.

Env var to control switching between front ends

---

frontend/ts/src/ServiceApi.ts

This PR adds a console command that allows users to add hotkeys to
their neurons. Example:
```
await nns.governance.addHotKey("<neuron-id>", "<principal>");
```
The motivation for this is to resolve https://forum.dfinity.org/t/8-year-locked-neuron-missing-from-neurons-tab

EXC-805: Add console command for `addHotKey`.

---

frontend/dart/web/index.html

Jan Camenisch: Also „getting NNS dapp ready for you“ -> „getting NNS frontend dapp ready for you“ (text that shows while loading after login)

Update wording as requested by Jan

---

.github/workflows/build.yml
build.sh

This adds a non-Docker, full build which is more easily cachable than
the Docker build. This is also much faster than a Docker build (~5mn instead of ~22mn).
This will be used by the end-to-end tests
(embryo here: https://github.com/dfinity/nns-dapp/pull/341)
This will be used by or reuse builds artefacts from checks.yml as soon as I have time to link the two, see https://dfinity.atlassian.net/browse/L2-191.

Add non-Docker build to CI

---

.dockerignore
.github/workflows/docker-build.yaml
Dockerfile
frontend/svelte/README.md

This adds caching to our docker build through [`buildx` Github Actions support](https://github.com/moby/buildkit#github-actions-cache-experimental). This saves 75% of the build time (22mn -> 5mn). The `.dockerignore` is also updated to fix some issues when local files ending up polluting the build.
Big, big thanks @crazy-max for your help!

Cache docker build

---

build.sh
frontend/dart/build.sh

This makes the top-level `build.sh` more readable and is more in line
with e.g. `frontend/ts`'s `build.sh`.

Create build script for dart code

---

frontend/svelte/src/App.svelte
frontend/svelte/src/lib/components/Nav.svelte
frontend/svelte/src/routes/Proposals.svelte

In current Flutter app, the "Voting" page actually points to route `#/proposals`. For backwards compatibility between this app and the current rewrite, we want to maintain the same route name.
- rename route `#/voting` to `#/proposals`

refactor: rename voting to proposals

---

Dockerfile
update_config.sh

The `update_config.sh` script needs to know which canister ID we build
for, and so far has called out to `dfx` to know which canisters have
been deployed locally (for local deploys). This is a problem in the
docker build since we don't deploy canisters. Instead, we allow
specifying the canister ID. Stop gap measure while we find a better
solution.

Allow specifying OWN_CANISTER_ID

---

.dockerignore
Dockerfile
README.md
build.sh
dfx.json
frontend/dart/build.sh
frontend/ts/build.sh
scripts/deploy-docker-build-to-testnet
scripts/docker-build

This scratches an old itch I had and fixes some documentation for running the docker build. In particular:
* Adds `scripts/docker-build` which outputs `nns-dapp.wasm` in the top-level (that's the final, optimized wasm).
* Removes `source` from dfx.json. `source` (i.e. `assets.tar.xz`) isn't used in `custom` builds AFAICT. 
* Specifies `nns-dapp.wasm` as the wasm input for `dfx`, there's no reason to actually modify cargo's generated files in `target` with `ic-cdk-optimizer`; instead we only read those files, and place the (optimized) output in the top-level.
* Performs some checks on the tar version used. Not only does this not obfuscate tar errors anymore (which was done with `||`) but also clarifies the intent. It also gives the user directions on how to install GNU tar.
* Clarifies …

Update build script

---

Dockerfile

A small discrepancy in build systems:  The node version:
- The dockerfile specifies NODE_VERSION=14.15.4
- But if I npm install with 14.15.4 the lockfile changes quite a lot.
- The github actions use the default for Ubuntu 20.04 github image, which is 16.13.2
- Bump the Docker npm version to 16.13.2
This SHOULD produce the same wasm build hash as main.
- At the time of writing, the builds to compare are:
- https://github.com/dfinity/nns-dapp/actions/runs/1740097395
- https://github.com/dfinity/nns-dapp/actions/runs/1740855380 (building...)

Use the same npm version in gh and docker

---

frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/tests/lib/modals/Modal.spec.ts

The `<Modal />` component is a dialog, therefore is role should be set as such ([MDN doc](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role))
- set `role=dialog` and aria information

feat: improve modal a11y

---

frontend/svelte/src/lib/components/Guard.svelte
frontend/svelte/src/lib/components/Toast.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/stores/toasts.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/Auth.svelte
frontend/svelte/src/tests/lib/components/Toast.spec.ts

Display unexpected auth sync and sign-in errors to users.
- add `<Toasts />` to login page (it does not use the main layout)
- stack a toast message for unexpected auth sync errors
- stack a toast message for sign-in errors
- add `detail` to toast store to display an optional string error in addition to an internationalized label
- display 5 lines in toast instead of 4 on mobile devices to display more details about the error

feat: display unexpected auth sync and sign-in errors

---

frontend/svelte/package-lock.json

`npm audit` showed a moderate severity vulnerability in frontend/svelte.
- `npm audit fix`
- REDIRECT_TO_LEGACY=false npm run dev <-- shows multiple svelte tabs correctly.
- REDIRECT_TO_LEGACY=true npm run dev <-- shows blank; as expected it tries to redirect but I am not running flutter.

npm audit fix in svelte

---

frontend/svelte/src/lib/components/Checkbox.svelte
frontend/svelte/src/lib/components/VotingFilters.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/icons/IconBack.svelte
frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/themes/variables.scss
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/components/Checkbox.spec.ts
frontend/svelte/src/tests/lib/modals/Modal.spec.ts

Add the dark version of the modal.
- Add `dark` prop to `Modal` component.
- Changed `Modal` title to h3. Previous Modal had different sizes for dark and light modals. Some dark modals had long titles. I changed to a midway solution. Old dark modal title was too small.

L2-214: Dark Modal

---

frontend/svelte/.prettierignore

When run in the svelte app, prettier currently format the "public" folder except sub-folder "build".
The sub-folder "assets" can also contains js files such as `public/assets/assets/ic_agent.js` which takes 7017ms to be formatted.
Neither does this file nor any files of the "public" folder need actually to be formatted.
- prettier ignores all "public" folder

build: prettier ignore all public folder

---

frontend/svelte/jest-setup.ts
frontend/svelte/src/lib/components/ui/InfiniteScroll.svelte
frontend/svelte/src/tests/lib/components/ui/InfiniteScroll.spec.ts
frontend/svelte/src/tests/lib/components/ui/InfiniteScrollTest.svelte
frontend/svelte/tsconfig.json

Proposals and other list are not fetched integrally when displayed but through subsets that are displayed when the user scrolls a specified distance from the bottom or top of the page.
This PR introduces an "infinite scroll" component which implements such behavior for any lists ("for each").
- new `<InfiniteScroll />` component
The component relies on the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).
Such API is [not supported](https://caniuse.com/?search=intersection%20Observer) on Safari version older than v12.1 on desktop and v12.2 on mobile. There browsers are out of the scope of the browser we are currently supporting ("latest 2"). That's why the PR does not include any polyfill or some sort of custom code for old browsers. …

feat: infinite scroll component

---

frontend/svelte/src/lib/components/ic/GetICPs.svelte
frontend/svelte/src/lib/themes/button.scss
frontend/svelte/src/lib/themes/theme.scss

Currently two button styles overlap each other (type=submit & .primary)
The idea was to refactor / rename the existing style [type="submit"] to .primary.
[L2-237](https://dfinity.atlassian.net/browse/L2-237)
- Blue button colours were reversed to submit.
- Was refactored only `Get ICPs` button
- section padding was updated to avoid separate PR

Refactor submit button

---

frontend/svelte/jest-setup.ts
frontend/svelte/package-lock.json
frontend/svelte/package.json
frontend/svelte/rollup.config.js
frontend/svelte/scripts/i18n.types.mjs
frontend/svelte/src/lib/stores/auth.store.ts
frontend/svelte/src/lib/stores/i18n.ts
frontend/svelte/src/lib/utils/accounts.utils.ts
frontend/svelte/src/tests/App.spec.ts
frontend/svelte/src/tests/lib/components/accounts/AccountCard.spec.ts
frontend/svelte/src/tests/lib/components/common/Guard.spec.ts
frontend/svelte/src/tests/lib/components/ic/ICP.spec.ts
frontend/svelte/src/tests/lib/components/ui/Toast.spec.ts
frontend/svelte/src/tests/lib/modals/VotingFilterModal.spec.ts
frontend/svelte/src/tests/lib/stores/auth.store.spec.ts
frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
frontend/svelte/src/tests/lib/utils/auth.utils.spec.ts
frontend/svelte/src/tests/lib/utils/route.utils.spec.ts
frontend/svelte/src/tests/mocks/accounts.store.mock.ts
frontend/svelte/src/tests/mocks/auth.store.mock.ts
frontend/svelte/src/tests/routes/Accounts.spec.ts
frontend/svelte/src/tests/routes/Neurons.spec.ts
frontend/svelte/src/tests/routes/Proposals.spec.ts

To ease the review of PR and to improve our DX, automatically organize and sort the `import`
- add [prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports)
- the plugin does not organize imports in `.svelte` [yet](https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/39) but will do so in all other files (all `.ts` and `.spec.ts` files)

build: organize imports in ts and spec files with prettier

---

frontend/svelte/src/lib/components/ui/Badge.svelte
frontend/svelte/src/tests/lib/components/ui/Badge.spec.ts
frontend/svelte/src/tests/lib/components/ui/BadgeTest.svelte

A new inline block element `<Badge />` to display notification or status.
- new `<Badge />` element

feat: badge component

---

frontend/svelte/src/lib/components/common/Nav.svelte
frontend/svelte/src/lib/components/ic/ICP.svelte
frontend/svelte/src/lib/components/ui/Card.svelte
frontend/svelte/src/lib/components/ui/Toast.svelte
frontend/svelte/src/lib/components/ui/Toolbar.svelte
frontend/svelte/src/lib/components/voting/VotingFilters.svelte
frontend/svelte/src/lib/themes/button.scss
frontend/svelte/src/lib/themes/mixins/_media.scss
frontend/svelte/src/routes/Accounts.svelte
frontend/svelte/src/routes/Auth.svelte

To provide a unique approach for styling “small to wide”. And make adjustment of current media queries if needed.
https://dfinity.atlassian.net/browse/L2-228
- new mixin `media`
- all `max-width` refactored to be `min-width`
- replace all `@media...` occurrences with the `media` mixin
- Unfortunately I didn't find the appropriate way to make max-width forbidden by ESLint
- Breakpoints:
`$breakpoint-xsmall: 320px;`
`$breakpoint-small: 576px;`
`$breakpoint-medium: 768px;`
`$breakpoint-large: 880px;`

Cleanup media queries

---

frontend/svelte/rollup.config.js
frontend/svelte/src/lib/constants/utils.constants.ts
frontend/svelte/src/lib/stores/auth.store.ts
frontend/svelte/src/lib/utils/accounts.utils.ts
frontend/svelte/src/lib/utils/agent.utils.ts
frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts

NNS-JS should make requests to testnet during development.
* Create an agent that expects a host as optional parameter and use it with nns-js.
* Rename `IDENTITY_SERVICE_URL` to `SERVICE_URL`. It is more than just for identity.
No new functionality added; therefore, no new tests added. Yet, a current test had to be edited to mock importing a module.

L2-251: Development agent for nns

---

frontend/svelte/package.json
frontend/svelte/scripts/i18n.types.js

As of Node v16.14.0, json import requires an addition assertion (as in the [tc39 proposal](https://github.com/tc39/proposal-import-assertions).
Unfortunately, until v16.13.x, such assertion is not supported nor ignored.
Since we are using misc Node version and because we cannot add the assertion while remaining backwards compatible, the current easiest way to solve the issue it to transform the module script to a standard js script aka use good old `require`. 
- transform `.mjs` i18n script to `.js`
- use `require`
Add some modification in auto-generated i18n files, run a build, changes were correctly overwritten by build.

build: i18n script mjs to js

---

frontend/svelte/src/lib/types/i18n.d.ts

Some i18n keys were not generated and added to the description file
- generate keys from `en.json` and update `i18n.d.ts` with the related keys

fix: i18n type definition keys

---

frontend/svelte/src/index.html

Remove implicit `defer` attribute in `script` tag.
> There is no need to use the defer attribute (see [<script> attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes)) when loading a module script; modules are deferred automatically.
[MDN Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)

build: remove implicit defer

---

frontend/svelte/src/lib/components/ui/Input.svelte
frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte

Prefer CSS variables over properties for styling purpose.
Exception: block of styles such as applying a all theme or color - i.g. options that affect multiples styles.
- remove `fullWidth`
- add CSS variable
Follow-up of last week PR [Create Neuron UI](https://github.com/dfinity/nns-dapp/pull/423). Works for you @lmuntanerDfinity?

feat: replace input fullWidth property with CSS variable

---

frontend/svelte/package-lock.json
frontend/svelte/package.json

Bump agent-js to [v0.10.3](https://github.com/dfinity/agent-js/releases/tag/v0.10.3) with latest security improvements
- bump `auth-client` and `identity`
- bump `nns-js`
- remove implicit dependencies `candid`, `agent` and `principal` inherited from `nns-js`
- remove unused `authentication`
Local tests with existing features - sign in, sign out, list proposals, get main account (gives expected 0.0 but no error). All good.

build: bump agent-js v0.10.3 and clean up dependencies

---

.github/workflows/build.yml

Do not commit of screenshots if `main` build.
Prevent issue such as https://github.com/dfinity/nns-dapp/actions/runs/1852192135
- add test `${{ github.ref != 'refs/heads/main' }}` in build actions

build: prevent screenshots commit on main build

---

frontend/svelte/jest-spy.ts
frontend/svelte/jest.config.cjs
frontend/svelte/rollup.config.js
frontend/svelte/src/lib/components/common/PrivateRoute.svelte
frontend/svelte/src/lib/constants/identity.constants.ts
frontend/svelte/src/lib/constants/utils.constants.ts
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/services/dev.services.ts
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/lib/stores/auth.store.ts
frontend/svelte/src/lib/utils/agent.utils.ts
frontend/svelte/src/lib/utils/auth.utils.ts
frontend/svelte/src/routes/Auth.svelte
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/Neurons.svelte
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/App.spec.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/lib/stores/auth.store.spec.ts
frontend/svelte/src/tests/lib/utils/auth.utils.spec.ts
frontend/svelte/src/tests/mocks/auth.store.mock.ts
frontend/svelte/src/tests/routes/Canisters.spec.ts

Canisters calls shall be identified with user' identity.
Host and fetch root key are useful to develop locally and use testnet.
- refactor `authStore` to contain user' `Identity` instead of `Principal` ("one level of information higher)
- rename constant `serviceURL` to `identityServiceURL`
- add `Identity`, optional `host` and `fetchRootKey` to agent utils
- `createAgent` is now promise based
- use `Identity` and `identityServiceURL` in `accounts.services` to fetch account balance
- use `Identity` and `host` in `proposals.services` to fetch the list of proposals (was only done in prod, now support testnet)
- globally mock `createAgent` for all tests
- extend rollup config to build app with `HOST` and `FETCH_ROOT_KEY` information

feat: add identity, host and fetch root key to create agent 

---

frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/themes/mixins/_select.scss

Product - UX mgmt rather like square check-boxes (material design instead of ios round design).
- make check-boxes square
- align modal close button

style: square check-boxes and align close modal

---

frontend/svelte/src/lib/components/proposals/ProposalsFilters.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/types/i18n.d.ts

The title of the filters' modal "proposal status" is not rendered
- rename i18n according correct category definition ("status" instead of "proposals")
Before:
After:

fix: missing modal status title

---

frontend/svelte/package.json

Even though we do not need it for dev, not having the favicon at the root display an error in the Chrome debugger. This PR also copy the favicon when we start the dev server.
- copy favicon to public dir on `npm run dev`

build: import favicon for dev

---

frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/Neurons.svelte

UX inquiry to remove " around principals displayed as text since they don't adds much.
- remove " around principals displayed as text
i

feat: remove double quotes around principals

---

frontend/svelte/src/lib/themes/fonts.scss
frontend/svelte/src/lib/themes/theme.scss
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/Neurons.svelte
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/routes/Canisters.spec.ts
frontend/svelte/src/tests/routes/Neurons.spec.ts
frontend/svelte/src/tests/routes/Proposals.spec.ts

Titles displayed on pages (except "Accounts") are redundant information. The "blue indicator" in the navbar already highlights which page is selected.
The paragraphs that introduce the pages is rendered with a large font-size.
As we aim to spare spaces for what's matter, UX had the idea to get rid of the redundant titles and make the paragraphs font-size less big.
- remove redundant pages' title
- style paragraph with an inherited font-size
- adds a bit of spacing next to the paragraphs if needed
- remove large space around paragraphs to inherits default compact spacing
In above screenshots the spacing looks a-ok on the "Voting" page but #478 will improve this.

feat: remove pages title

---

frontend/dart/lib/ui/home/home_tabs_widget.dart

We wish to serve some tabs via svelte.  For that we need to break the current UI into distinct tabs rather than having them all flow together.
* Make the transition very fast.
Max:
* This PR is deployed here: https://wmio3-kqaaa-aaaaa-aaasq-cai.nnsdapp.dfinity.network
* I imagine that "scrolling fast" may still generate the intermediate tabs, so I temporarily added redirects to svelte and back to check that our desired goal works.  It does, so I believe that this is fine for our purposes.
* That demo is deployed here: https://w6ozc-gaaaa-aaaaa-aaarq-cai.nnsdapp.dfinity.network/v2/
* Try clicking on the various tabs, including e.g. first neurons (to the left of the svelte voting tab) then canisters (to the right, so it "swipes past" the voting tab very fast).  The page does not reload or …

remove page transition animation

---

frontend/dart/lib/ui/home/home_tabs_widget.dart

The flutter navbar style needs to match svelte.  This style had already been changed, but with a refactoring that has been reverted so it needs to be reimplemented.
* Make the nav bar buttons square except at the outside corners of the first and last button.
* Note: This is done with a clip box rather than tracking the index of the current selection and applying conditional styles.
* Also: I have removed the radius of the grey background and let the clipping box round the corners of that as well.  This is because the background radius had a different radius from the one used in svelte.  In svelte the background radius is the same as the button radius.  Using the clipping box achieves that effect.
The code has been deployed here: …

Style flutter navbar

---

frontend/svelte/jest-setup.ts
frontend/svelte/rollup.config.js
frontend/svelte/src/App.svelte
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.types.ts
frontend/svelte/src/lib/components/accounts/AccountCard.svelte
frontend/svelte/src/lib/constants/canister-ids.constants.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/stores/accounts.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/icp.utils.ts
frontend/svelte/src/routes/Accounts.svelte
frontend/svelte/src/tests/App.spec.ts
frontend/svelte/src/tests/lib/canisters/nns-dapp.canister.spec.ts
frontend/svelte/src/tests/lib/modals/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/dev.services.spec.ts
frontend/svelte/src/tests/lib/stores/accounts.store.spec.ts
frontend/svelte/src/tests/lib/utils/icp.utils.spec.ts
frontend/svelte/src/tests/mocks/accounts.store.mock.ts
frontend/svelte/src/tests/routes/Accounts.spec.ts

Fetch account and subaccount details and render them in Accounts page.
* `syncAccounts` calls to addAccount from NNSDapp canister. To ensure the user has an account in NNS.
* `syncAccounts` calls `getAccount` to get account details. Then gets the balances of all accounts.
* Route `Accounts` renders main and subaccounts.
* After creating a subaccount, `syncAccounts` is called to syncrhonize all accounts at once.
* `accountsStore` simplified to only set or subscribe.
* new icp util `addICPs` to add ICPs.
* updated `App` test.
* updated `AddAccoountModal` test.
* updated `Accounts` route test.
* Test for `createSubAccount`, `getAccount` and `addAccount` in NNSDappCanister.
* Test for `addICPs`.
* updated `accounts.services.ts` test.

L2-301: Fetch accounts subaccounts on init

---

frontend/svelte/src/lib/components/accounts/AccountCard.svelte
frontend/svelte/src/routes/Accounts.svelte
frontend/svelte/src/tests/lib/components/accounts/AccountCard.spec.ts

AccountCard can be role `"link"`
Add type `"link"` to role prop in AccountCard.
Add test to check role prop

L2-317: AccountCard link role

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/modals/ProposalsFilterModal.svelte
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/lib/modals/ProposalsFilterModal.spec.ts

To improve the UX, we are not going to fetch new proposals every time a checkbox is clicked but rather make it as a user choice. To do so, we add a "filter" button in the filter modals for the list of proposals.
- add button "Filter"
- apply filtering only if button is clicked
- add `footer` slot to modal
- improve `content` slot scrolling in modal

feat: list proposals - "filter" modal footer button

---

frontend/svelte/package-lock.json
frontend/svelte/package.json
frontend/svelte/src/lib/components/proposals/ProposalCard.svelte

Bump nns-js nightly 2022/02/28 to introduce the new exposed typings and `getProposalInfo`
- bump nns-js nightly 2022/02/28
- use types in proposal card

bump: nns-js nightly 2022/02/28

---

frontend/svelte/src/lib/components/common/Banner.svelte
frontend/svelte/src/lib/components/common/Header.svelte
frontend/svelte/src/lib/components/common/HeadlessLayout.svelte
frontend/svelte/src/lib/components/common/Layout.svelte
frontend/svelte/src/lib/components/common/Nav.svelte
frontend/svelte/src/routes/Auth.svelte

Some users find their way to the application deployed on testnet (source [forum](https://forum.dfinity.org/t/internet-identity-doubt-in-creating-a-new-ii-anchor/11179/8?u=peterparker)). To make them aware they are accessing a version that has only test purpose, we can display a banner about it.
- test purpose banner displayed if environment is "testnet" and not "local development"
- css variable `--header-offset` for layout

feat: testnet banner

---

frontend/svelte/scripts/build.index.mjs

The CSP for the svelte app is not injected because there is no more `env.PRODUCTION` config.
- fix `env.PRODUCTION` with `env.ENVIRONMENT`

fix: missing csp

---

frontend/svelte/env.config.mjs
frontend/svelte/scripts/build.index.mjs

Provide the own canister url and not only id in the csp.
- parse full url instead of id in the csp rule (same behavior as other canisters we allow)

feat: provide own canister url in csp

---

frontend/svelte/src/App.svelte
frontend/svelte/src/lib/stores/route.store.ts
frontend/svelte/src/lib/utils/app-path.utils.ts
frontend/svelte/src/routes/ProposalDetail.svelte
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/lib/stores/route.store.spec.ts
frontend/svelte/src/tests/lib/utils/app-path.spec.ts

To make the transition between "Proposal detail" and "Proposals list - Voting" pages smooth in case of "back" action, the proposals shall not be fetched again if already exist.
Scenario example: 
- Neurons > Voting > Fetch proposals > select Proposal > Detail > Back > No fetch - display existing proposals from store
- Proposal details > Fetch proposal > Back > Voting > Fetch proposals
- Neurons > Voting -> Fetch proposals  > Neurons > Voting > Fetch proposals
- add `referrerPath` to route store
- do not reset proposals store on mount in `Proposals.svelte` if referrer is "Proposal detail" page and store not empty
- fix `navigate` and `replace` called at the same time on back in `ProposalDetail.svelte`

feat: do not reload list of proposals on back

---

frontend/dart/lib/ui/neurons/following/configure_followers_page.dart

We currently hide the ManageNeuron topic from the followee options. But some neurons may be created with followees on the ManageNeuron topic. In these cases it is currently impossible for the neuron owner to remove the followee via the UI.
- Show the ManageNeuron followee configuration options for neurons who already have followees on the ManageNeuron topic.
I removed the topic filter, then followed a neuron on the ManageNeuron topic, then applied this change. I could then see the ManageNeuron topic on the followee options page. But when I removed the neuron from the ManageNeuron topic, the topic itself disappeared, as intended.

Display the ManageNeuron topic if a neuron has followees on it

---

frontend/ts/package-lock.json

```
frontend/ts (13)$ npm audit
ansi-regex  >2.1.1 <5.0.1
Severity: moderate
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
node_modules/cliui/node_modules/ansi-regex
node_modules/eslint/node_modules/ansi-regex
node_modules/string-width/node_modules/ansi-regex
node_modules/table/node_modules/ansi-regex
node_modules/wide-align/node_modules/ansi-regex
node_modules/wrap-ansi/node_modules/ansi-regex
strip-ansi  4.0.0 - 5.2.0
Depends on vulnerable versions of ansi-regex
node_modules/wide-align/node_modules/strip-ansi
string-width  2.1.0 - 4.1.0
Depends on vulnerable versions of strip-ansi
node_modules/wide-align/node_modules/string-width
node-fetch  <2.6.7
Severity: high
node-fetch is …
```

npm audit fix

---

frontend/svelte/src/lib/components/ui/Toast.svelte
frontend/svelte/src/tests/lib/components/ui/Toast.spec.ts

Some long error messages are not fully visible (see screenshot)
- Added title attribute to the message (quick solution)
- Added title test

feat: add title to <Toast> message

---

.github/workflows/checks.yml

The svelte linter rules have been or will soon be updated.  This causes, as expected, a lot of errors.  According to our plan, we are going to allow these errors to appear for a while, to give people time to fix them.  However for that github must not block PR merges on account of lint failures.
* Put the svelte lint job in a separate task.
* Make a new dummy task that controls whether we may merge, rather than listing requirements in the admin panel.
* Update the merge rules, but this can be done a few fays after this has been merged to minimise disruption.
Let's see whether this PR is mergeable with a failed lint result....

Let the svelte linter fail

---

CHANGELOG.md
PROPOSAL_TEMPLATE.md

A new release has been made: https://dashboard.internetcomputer.org/proposal/47824
* Update CHANGELOG.
commit-id: e40bd206e28343b8c8b90d621802aa448277c250
deployment:
* https://nns.winning.gold
* https://txssk-maaaa-aaaaa-aaanq-cai.nnsdapp.dfinity.network/v2/
* ![Screenshot from 2022-03-03 16-34-36](https://user-images.githubusercontent.com/5982633/156597474-0a0c36b9-1cc4-4d11-82b3-6d1518e3d8d3.png)
Sha:
```
git-notes: 5eb3b0da3a9eb89bbf921cbe67361b7a0c5cfe2bf3e60dd84a6b42b92f1f0fed  -
ci: 5eb3b0da3a9eb89bbf921cbe67361b7a0c5cfe2bf3e60dd84a6b42b92f1f0fed
max: 5eb3b0da3a9eb89bbf921cbe67361b7a0c5cfe2bf3e60dd84a6b42b92f1f0fed
```
https://dashboard.internetcomputer.org/proposal/47824
- Authenticated with II Anchor 10000
- Used 'Get ICPs' to get 10 ICP
- Created a subaccount
- Sent 4 ICP from …

Changelog for proposal 47824

---

frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalSummary.svelte
frontend/svelte/src/lib/utils/proposals.utils.ts

Because of switching to the markdown component `formatProposalSummary` function is not necessary anymore.
- remove `formatProposalSummary`
- remove it's usage
**no changes**

chore: remove unused formatProposalSummary

---

frontend/svelte/tsconfig.json

Ignore `.spec.ts` and `*.mock.ts` for the TypeScript includes resolution.
- redo `"**/*.mock.ts"` and  `"**/*.spec.ts"` in `tsconfig.json`

build: redo ignore test and mock in tsconfig

---

frontend/svelte/src/lib/modals/Modal.svelte

Modal's backdrop dismiss should not be propagated. For example, in the list of proposals, dismissing the modal leads to navigating to detail page 🤪.
- add `stopPropagation` to backdrop dismiss

fix: backdrop dismiss click propagation

---

.github/workflows/docker-build.yaml
scripts/deploy-ci-to-testnet

We now have three levels of `REDIRECT_TO_LEGACY`:
- never == false == pure svelte
- prod == as in production, which currently means that all tabs are served by flutter
- staging == as in production, but wit hone more tab served as svelte.
As M1 macs cannot make docker builds, it would be useful if CI could produce at least "never" and "staging" for development.
We keep the existing names for existing builds to avoid disruption.
- Add a third build for staging
- Rename "true" to "prod" as "true" will be misleading as soon as we have 1 tab in svelte in prod.
The docker builds in CI have succeeded.
- The mainnet build should be unaltered by this change.  Checking:
- The CI mainnet build hash is: 
- 1e3a424407eac5a8dc1eeb27109cd48b0005264624302eec86a6d735b111dc9d
- The merge root is: …

Make staging builds in CI

---

frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.types.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.types.ts
frontend/svelte/src/lib/utils/dev.utils.ts

The nns-dapp canister uses some types of the ledge and account canisters and overwrite some types. This PR clean up the typescript code that did not implement the distinction.
- reuse `BlockHeight, E8s, NeuronId` from nns-js
- make `AccountIdentifier` and `Subaccount` dinstinctive from the types defined in nns-js
- rename canister options type filename

refactor: clean up canister types

---

frontend/svelte/.eslintrc.js
frontend/svelte/tsconfig.eslint.json

Fix 36 errors:
>   0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: src/tests/lib/utils/route.utils.spec.ts.
> The file must be included in at least one of the projects provided
- provide a `tsconfig.eslint.json` for eslint that includes test files

build: eslint fix parsing error parserOptions.project has been set for @typescript-eslint/parser

---

frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
frontend/svelte/src/lib/components/proposals/ProposalCard.svelte
frontend/svelte/src/lib/components/proposals/Proposer.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/modals/proposals/ProposerModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/themes/mixins/_interaction.scss
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/components/proposals/ProposalCard.spec.ts
frontend/svelte/src/tests/lib/components/proposals/Proposer.spec.ts
frontend/svelte/src/tests/lib/modals/ProposerModal.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/mocks/governance.canister.mock.ts
frontend/svelte/src/tests/mocks/proposals.store.mock.ts
frontend/svelte/src/tests/routes/Proposals.spec.ts

- Load and display the neuron of a proposer of a proposal in a modal.
- Fix modal click propagation
- Style neuron card
- add `getNeuron` to `neurons.services.ts`
- add `NeuronCard` to `ProposerModal`
- load neuron in `ProposerModal` and display a spinner until loaded
- `Modal` click propagation
- `NeuronCard` (font, spacing, etc.) and move elements for display purpose
- default cursor and touch action for `Modal` (it is not clickable but Svelte propagate style to children)
- refactor double code to a single function that init agent and governance canister in `neurons.services.ts`
- extract `Proposer` (action button) from `ProposerModal` to standalone component
- extract governance canister mock to a dedicated file

feat: load and display neuron for proposer

---

frontend/svelte/src/lib/modals/accounts/SelectTypeAccount.svelte

Current hover background on accounts (in modal) is blue. We can use the same color as for card to make it follows the same style.
- replace blue with `--background-hover`
Is:
With PR:

style: account hover background

---

frontend/svelte/env.config.mjs

The config currently set the default value for `HOST` to empty `""`. This property is ignored in our agent-js utils if `undefined`.
- set `HOST` as `undefined` for default value in config

build: fix default host empty

---

frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
frontend/svelte/src/lib/components/ui/Card.svelte
frontend/svelte/src/lib/themes/mixins/_display.scss

If I am not wrong, "Stake" text can be displayed even if no ICP.
This PR also fix the alignment in case not hotkey are displayed and no community fund are displayed.
- display "Stake" text also without ICP
- align state and stake for all cases
Is:
Will be:

fix: display stake and align state and stake

---

frontend/svelte/src/lib/modals/Modal.svelte

When the wizard is used in the modal, the transition are glitchy because an horizontal scroll is briefly displayed on transitions.
When the content of the modal fits, a vertical scrollbar is displayed. That should not be the case. Such a scroll should be displayed only if the content can be scrolled.
- style `overflow-x` and `overflow-y` of the modal's content

style: fix modal overflow

---

frontend/svelte/src/lib/constants/constants.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

Show new neuron details when updating the delay after creating it.
* SetDissolveDelayModal expects a neuron and uses the data to render the details.
* votingPower util.
* Upgraded CreateNeuronModal tests to check that information used to create a neuron is there.
* votingPower util tests

L2-330: Display new neuron details

---

frontend/svelte/src/lib/services/proposals.services.ts

Fix `npm run check` failing.
* `identity` can also be `null`.
No extra tests.

Fix: npm run check fails

---

frontend/svelte/.eslintrc.js
frontend/svelte/jest-setup.ts
frontend/svelte/src/lib/stores/accounts.store.ts
frontend/svelte/src/lib/utils/agent.utils.ts
frontend/svelte/src/tests/lib/components/common/Guard.spec.ts
frontend/svelte/src/tests/lib/components/neurons/NeuronCard.spec.ts
frontend/svelte/src/tests/lib/components/proposal-detail/ProposalDetailCard/ProposalDetailCard.spec.ts
frontend/svelte/src/tests/lib/components/proposal-detail/ProposalDetailCard/ProposalMeta.spec.ts
frontend/svelte/src/tests/lib/components/proposal-detail/ProposalDetailCard/ProposalSummary.spec.ts
frontend/svelte/src/tests/lib/components/proposal-detail/VotesCard.spec.ts
frontend/svelte/src/tests/lib/components/proposals/ProposalCard.spec.ts
frontend/svelte/src/tests/lib/components/proposals/ProposalsFilters.spec.ts
frontend/svelte/src/tests/lib/components/proposals/Proposer.spec.ts
frontend/svelte/src/tests/lib/components/ui/InfiniteScroll.spec.ts
frontend/svelte/src/tests/lib/modals/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/modals/Modal.spec.ts
frontend/svelte/src/tests/lib/modals/ProposalsFilterModal.spec.ts
frontend/svelte/src/tests/lib/modals/ProposerModal.spec.ts
frontend/svelte/src/tests/lib/modals/VoteConfirmationModal.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/lib/stores/auth.store.spec.ts
frontend/svelte/src/tests/lib/utils/date.utils.spec.ts
frontend/svelte/src/tests/mocks/auth.store.mock.ts
frontend/svelte/src/tests/mocks/governance.canister.mock.ts
frontend/svelte/src/tests/mocks/infinitescroll.mock.ts
frontend/svelte/src/tests/mocks/proposals.store.mock.ts
frontend/svelte/src/tests/routes/Proposals.spec.ts

Fix eslint errors, part 2
* Fix no-require.
* Fix no-empty-function.
* Allow `ts-ignore` with description.
* Fix no-unused-var
No extra tests.

Fix: Eslint errors 2

---

frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts

Currently `queryProposal` uses query to fetch the data. But all request should use update instead.
- getProposal function -> certified: true
- updated getProposal.spec

Fix query proposal certified

---

frontend/svelte/scripts/build.index.mjs

```
Refused to load manifest from 'https://qsgjb-riaaa-aaaaa-aaaga-cai.nnsdapp.dfinity.network/manifest.json' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.
```
Added a manifest-src to the CSP.
The above error is seen in deployments such as:  https://qsgjb-riaaa-aaaaa-aaaga-cai.nnsdapp.dfinity.network/v2/#/neurons
But not a on a deployment of this branch: https://wflfh-4yaaa-aaaaa-aaata-cai.nnsdapp.dfinity.network/#/accounts

Define manifest src

---

frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/routes/ProposalDetail.svelte
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts

🪲🪲🪲
1. the proposal detail info was shown before the neurons were loaded. That could make wrong impression that for example there was no voting done
2. after successful voting an error was always shown
3. in case the proposal id is changed directly in URL there was no visible feedback that the new proposal is loading
- for now the unknown store state is fixed on the component level (could be changed after update/query research).
- added test to not show error messages on successful response

L2 387 no neurons initially on proposal detail

---

.github/workflows/docker-build.yaml

Builds are failing because of the git notes.
A quick resolution is needed to stop breaking other PRs, a deeper solution can follow.
Diagnosis:
The code does a git fetch to get the notes, however it looks as if it should be doing something like a git reset --hard origin/notes/* of just the notes.  Doing that properly will require learning more about notes.
- Ignore git note failures

Unblock builds

---

frontend/svelte/src/lib/components/proposals/BallotSummary.svelte
frontend/svelte/src/lib/components/ui/Markdown.svelte
frontend/svelte/src/lib/components/ui/SkeletonParagraph.svelte
frontend/svelte/src/lib/components/ui/SkeletonText.svelte
frontend/svelte/src/tests/lib/modals/VoteHistoryCard.spec.ts

Loading voting history can take time and displaying another or multiple additional spinners would look weird. That's why we can present skeleton text while we are loading all the proposals of the selected voting history.
- add ui element `SkeletonText`
- display skeleton texts until voting history proposal is loaded

feat: display skeleton text while loading voting history

---

frontend/svelte/package.json
frontend/svelte/src/lib/components/neuron-detail/NeuronFollowingCard.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronMaturityCard.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronProposalsCard.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronVotingHistoryCard.svelte
frontend/svelte/src/tests/App.spec.ts
frontend/svelte/src/tests/mocks/governance.canister.mock.ts

Max Lint Warnings of 0.
* Change in `npm run lint` to set max warnings to 0.
* Fix current lint warnings.
No new tests

Fix: Do not allow Eslint warnings

---

frontend/svelte/src/lib/components/ui/CardBlock.svelte

Fix CardBlock max height (see screenshots)

fix: card-block max height

---

frontend/svelte/package-lock.json

Bump minimist to fix high severity vulnerability
> $ nmp audit
> minimist <=1.2.5
> Severity: high
> Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
- bump `minimist` with `npm audit fix`

build: bump minimist to fix high severity vulnerability

---

frontend/svelte/src/lib/components/common/Guard.svelte
frontend/svelte/src/lib/components/ic/GetICPs.svelte
frontend/svelte/src/lib/modals/accounts/AddNewAccount.svelte
frontend/svelte/src/lib/modals/proposals/ProposerModal.svelte
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/lib/stores/toasts.store.ts
frontend/svelte/src/routes/Auth.svelte
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/Neurons.svelte
frontend/svelte/src/routes/Proposals.svelte

Reduce or remove duplicate code. Simplify error logging.
- defer `consoler.error` and error parsing to `toastStore`

refactor: toast error

---

frontend/svelte/jest.config.cjs
frontend/svelte/src/lib/components/ui/Markdown.svelte
frontend/svelte/src/lib/utils/markdown.utils.ts
frontend/svelte/src/tests/lib/components/ui/Markdown.spec.ts
frontend/svelte/tsconfig.spec.json

This PR is a branch of a branch so that @mstrasinskis can have a look and use what he think is useful or not for his PR.
I extracted the function to a utils because it was easier to debug.
I think the tests did not work out mostly because the mock had to be extended with the new `Rendered()` class.
I also extracted the `tsconfig` for the jest spec tests to a separate file. Not sure it is needed but it does not arm in any case.

feat: marked rendered types

---

frontend/svelte/src/lib/api/accounts.api.ts
frontend/svelte/src/lib/api/governance.api.ts
frontend/svelte/src/lib/api/utils.api.ts
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/modals/neurons/SelectAccount.svelte
frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/account.ts
frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts

User can stake a neuron from subaccounts.
* Add subaccounts to SelectAccount screen in CreatenNeuronModal.
* Add `fromSubAccount` parameter to all the stake neuron flow.
* New helper to transform from SubAccountArray to number that is needed for nns-js.
* New test to check that user can select a subaccount in CreatenNeuronModal.

L2-322: Stake neurons from subaccounts

---

frontend/svelte/src/lib/api/governance.api.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/proposals/ProposerModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/api/governance.api.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

Switch to queryAndUpdate approach for loading a neuron
[L2-417](https://dfinity.atlassian.net/browse/L2-417)
- `i18n.error.get_neuron` was removed because the error handling is done in neuron service
- no extra tests are necessary

L2 417 apply query and update strategy to get neuron

---

frontend/svelte/jest-spy.ts
frontend/svelte/src/App.svelte
frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
frontend/svelte/src/lib/components/proposals/BallotSummary.svelte
frontend/svelte/src/lib/modals/accounts/AddNewAccount.svelte
frontend/svelte/src/lib/modals/neurons/ConfirmDissolveDelay.svelte
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/modals/proposals/ProposerModal.svelte
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/services/auth.services.ts
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/services/dev.services.ts
frontend/svelte/src/lib/services/knownNeurons.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/lib/services/utils.services.ts
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/NeuronDetail.svelte
frontend/svelte/src/routes/Neurons.svelte
frontend/svelte/src/routes/ProposalDetail.svelte
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/lib/services/knownNeurons.services.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/lib/utils/api.spec.ts
frontend/svelte/src/tests/mocks/auth.store.mock.ts

- Refactor the way services access the identity - i.e. instead of passing the identity all the way down from the component, access to the identity on a `services` level.
- Solve the many todo that were open to display properly the error message for the edge case of the identity becoming null or undefined
- With the same approach of an auth becoming idle, logout the user automatically if a function of a service is queried but for some reason no identity was provided
This is an edge case. The auth - i.e. the identity - is guarded both in terms of session timeout and storage changes. Therefore in a normal behavior mode the automatic signout should already happen even before any call to a service.
- add new function `getIdentity` that either return a valid `Identity` or proceed with a …

feat: refactor get identity for services and logout if no identity is provided

---

frontend/svelte/src/lib/api/constants.api.ts
frontend/svelte/src/lib/api/governance.api.ts
frontend/svelte/src/lib/api/utils.api.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.certified.idl.js
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.idl.js
frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
frontend/svelte/src/lib/components/neurons/KnownNeuronFollowItem.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/stores/neurons.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/api/governance.api.spec.ts
frontend/svelte/src/tests/lib/api/utils.api.spec.ts
frontend/svelte/src/tests/lib/modals/NewFolloweeModal.spec.ts
frontend/svelte/src/tests/lib/stores/neurons.store.spec.ts

User can follow and unfollow known neurons.
* Hardcode two known neurons in the governance api.
* New Component `KnownNeuronFollowItem`.
* Upgrade NewFolloweeModal to use new component.
* Add features to service `getNeuron` to not get cached data.
* neuronsStore.pushNeurons should not add duplicated neurons to store.
* New tests in NewFolloweeModal to test for the unfollow functionality.
* New test for api util `toSubAccountId`.
* New test for pushNeurons.

L2-403: Follow and unfollow known neurons

---

frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.svelte
frontend/svelte/src/lib/components/ui/Markdown.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/error.utils.ts
frontend/svelte/src/lib/utils/proposals.utils.ts
frontend/svelte/src/lib/utils/security.utils.ts
frontend/svelte/src/lib/utils/utils.ts
frontend/svelte/src/routes/ProposalDetail.svelte
frontend/svelte/src/tests/lib/components/proposal-detail/ProposalDetailCard/ProposalMeta.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/lib/utils/proposals.utils.spec.ts
frontend/svelte/src/tests/lib/utils/utils.spec.ts

To improve error handling we switch from Promise.all to Promise.allSettled. Display individual errors (one per failure neuron update) in detail of the error message.
[L2-369](https://dfinity.atlassian.net/browse/L2-369)
- display individual neuron errors (in detail)
- listNeurons error handling (refresh)
- reorganisation of register vote tests (error blocks are combined in single describe block)
- proposal service
@peterpeterparker Probably it makes sense to change the detail rendering style. So it doesn't look like a part of the error message.
**empty error message fallback**

L2 369 switch to promise all settled for the cast vote function

---

frontend/ts/ic-hardware-wallet-cli.ts
ic-hardware-wallet-cli/ic-hardware-wallet-cli

We always assumed that the user wants to use subaccount `0`. This PR
expands the scope of the CLI tool to allow specifying any subaccount.
Example command:
```
./ic-hardware-wallet-cli --subaccount 1 info
```

EXC-1030: Users can specify the subaccount in the CLI tool.

---

e2e-tests/package-lock.json
frontend/ts/package-lock.json

`npm audit` shows vulnerable dependencies.
```
max@sinkpad:~/dfn/nns-dapp/e2e-tests (42)$ npm audit
minimist  <=1.2.5
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
node_modules/minimist
nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
node_modules/nanoid
mocha  8.2.0 - 9.1.4
Depends on vulnerable versions of nanoid
node_modules/mocha
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g …
```

Update 2022 04 04

---

frontend/svelte/src/lib/components/accounts/Address.svelte
frontend/svelte/src/lib/components/accounts/SelectAccount.svelte
frontend/svelte/src/lib/components/accounts/SelectDestination.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/WizardModal.svelte
frontend/svelte/src/lib/modals/accounts/AddAccountModal.svelte
frontend/svelte/src/lib/modals/accounts/NewTransactionModal.svelte
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/stores/steps.state.ts
frontend/svelte/src/lib/themes/modal.scss
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/Accounts.svelte
frontend/svelte/src/tests/lib/components/accounts/Address.spec.ts
frontend/svelte/src/tests/lib/components/accounts/SelectAccount.spec.ts
frontend/svelte/src/tests/lib/components/accounts/SelectDestination.spec.ts
frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/NewTransactionModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/stores/steps.state.spec.ts
frontend/svelte/src/tests/mocks/accounts.store.mock.ts
frontend/svelte/src/tests/mocks/modal.mock.ts
frontend/svelte/src/tests/routes/Neurons.spec.ts

Init "New transaction" modal and two first steps to select account and destination (without any logic here).
- init new modal `NewTransaction`
- refactor step to define `title` per step
- several UI improvements discussed with Mischa (display of title "My Accounts", "Max" color and texts on "Select destination" and modal wrapper spacing)

feat: init new transaction

---

frontend/svelte/src/lib/components/accounts/Address.svelte
frontend/svelte/src/lib/components/accounts/SelectDestination.svelte
frontend/svelte/src/lib/components/ui/Input.svelte
frontend/svelte/src/lib/constants/accounts.constants.ts
frontend/svelte/src/lib/utils/accounts.utils.ts
frontend/svelte/src/tests/lib/components/accounts/Address.spec.ts
frontend/svelte/src/tests/lib/components/ui/Input.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/NewTransactionModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
frontend/svelte/src/tests/mocks/accounts.store.mock.ts
frontend/svelte/src/tests/mocks/modal.mock.ts

Implement address input rules as in Dart.
- input is of type `test` and should be min 40 characters
- modify component `Input` to support `minlength`

feat: account address input rules

---

frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/EditFollowNeurons.svelte
frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/components/neurons/ConfirmDissolveDelay.spec.ts
frontend/svelte/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
frontend/svelte/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
frontend/svelte/src/tests/mocks/neurons.mock.ts

Stake Neuron flow: manage edge cases, show errors gracefully and give a better UX on errors.
* Add "invalidStates" array in the CreateNeuronModal. Error should be shown and modal closed on unexpected edge cases.
* Show busy screen when updating delay and staking neuron.
* Manage errors in services instead of component during the flow.
* Components ConfirmDissolveDelay, SetDissolveDelay and EditFollowNeurons are not rendered without a neuron.

L2-329: Manage errors stake neuron

---

frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/IncreaseDissolveDelayButton.svelte
frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
frontend/svelte/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts
frontend/svelte/src/tests/lib/components/ui/Toasts.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/IncreaseDissolveDelayModal.spec.ts
frontend/svelte/src/tests/mocks/modal.mock.ts

Modal in neuron details to increase the dissolve delay.
* New modal IncreaseDissolveDelayModal that uses SetDissolveDelay and ConfirmDissolveDelay screens.
* Minor changes in SetDissolveDelay and ConfirmDissolveDelay to adapt for different use cases.
* IncreaseDissolveDelayButton opens IncreaseDissolveDelayModal.
* Test flow for IncreaseDissolveDelayModal.

L2-361: Neuron detail dissolve delay

---

frontend/svelte/scripts/build.index.mjs

Current main does not load on iOS.  The console gives the error:
With this PR the page loads in Safari and there are no console errors.
Note:  There is a "worker-src" directive but it is [not supported by Safari](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src).
- Added `child-src: 'self'` to the CSP.
With this PR the page loads in Safari and there are no console errors.

Add CSP for the web worker

---

frontend/svelte/src/lib/components/accounts/CurrentBalance.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionDestination.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionInfo.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionSource.svelte
frontend/svelte/src/lib/components/ic/ICP.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/components/ui/AmountInput.svelte
frontend/svelte/src/lib/components/ui/Input.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/accounts/NewTransactionModal.svelte
frontend/svelte/src/lib/stores/transaction.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/components/accounts/CurrentBalance.spec.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionAmount.spec.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionInfo.spec.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionReview.spec.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionTest.svelte
frontend/svelte/src/tests/lib/components/ui/AmountInput.spec.ts
frontend/svelte/src/tests/lib/components/ui/Input.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/NewTransactionModal.spec.ts
frontend/svelte/src/tests/lib/stores/transaction.store.spec.ts

Follow-up of the "New transaction" wizard that implements the step to enter the amount of the transaction and initialize the review step.
- implement "New transaction - Enter amount" step
- init "New transaction - Review" step
- new component `CurrentBalance`
- new component `NewTransactionInfo` to display information (source, dest and amount) in multiple steps
- new prop `inline` to display ICP on one line ("value ICP" or "value \n ICP")
- add option `max` to `Input` component
- use `max` option in `StakeNeuron`
- refactor `StakeNeuron` input to enter "amount" to a new component `AmountInput`
- add new step to new transaction modal wizard
- add "amount" field to contextual transaction store

feat: implement transaction step "enter amount" and init step "review"

---

frontend/svelte/src/lib/utils/markdown.utils.ts
frontend/svelte/src/tests/lib/components/ui/Markdown.spec.ts
frontend/svelte/src/tests/lib/utils/markdown.utils.spec.ts

To have the same behavior as in the dashboard-app all the summary images should be rendered as images.
https://dfinity.slack.com/archives/C01EWN833KN/p1649311351785469?thread_ts=1649163857.576849&cid=C01EWN833KN
- added imageToLinkRenderer
- tests for imageToLinkRenderer

Markdown img to link

---

e2e-tests/specs/redirect-to-legacy.e2e.ts
frontend/dart/lib/data/env.dart
frontend/svelte/src/lib/constants/routes.constants.ts

The proposals tab will now be deployed in production using svelte.
- Update the svelte and flutter values:
- showProposalsRoute now uses svelte for production
- showNeuronsRoute now uses svelte for staging
- Update redirect test.
```
REDIRECT_TO_LEGACY=prod ./scripts/test-winning --spec /specs/redirect-to-legacy.e2e.ts
```

Proposals tab is shown in prod

---

e2e-tests/wdio.conf.ts

The e2e log level is too noisy for most purposes, it floods the screen with hard-to-read data and by its sheer volume hides errors.  Personally, when developing I use `logLevel: warn` and switch back to `logLevel: info` if I really need the data for debugging.
However, when changing the log level in the code, one ends up with a diff which I have to remove every time I commit or make a PR.  Better to have a default in the code and an external override.
- Override the log level with an environment variable.
I use this control regularly.  It works.

Environment argument for controlling the log level

---

e2e-tests/scripts/deploy-local-canisters

Sometimes tests fail because the canister installation wasn't ready:
```
2022-04-10T05:44:35.8392589Z [0-0]   Code: 404 (Not Found)
2022-04-10T05:44:35.8393240Z [0-0]   Body: Requested canister does not exist
2022-04-10T05:44:35.8394445Z [0-0] " class="svelte-ksskaf">An error occurred while loading the accounts information. Server returned an error:
2022-04-10T05:44:35.8397503Z [0-0]   Code: 404 (Not Found)
2022-04-10T05:44:35.8397996Z [0-0]   Body: Requested canister does not exist
```
Note: I checked whether the installation had failed; the installation was fine, some later checks worked, it just took a while for the canister to be ready.
- Support `nobuild` for faster testing.
- Wait for the local network to be ready before deploying canisters.
- Wait for the nns-dapp canister to be …

Fix flaky tests: Wait for canister to be ready

---

frontend/svelte/src/lib/modals/Modal.svelte

fix: too long text in the modal title

---

frontend/svelte/src/lib/components/neuron-detail/NeuronMaturityCard.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
frontend/svelte/src/tests/lib/components/neuron-detail/NeuronMaturityCard.spec.ts
frontend/svelte/src/tests/lib/components/neuron-detail/NeuronMetaInfoCard.spec.ts

Follow up PR #670 to fix wildcard import.
- es6 naming import instead of wildcard to helps bundler chunking process (if we ever use chunking)

fix: neuron utils wildcard import

---

.github/workflows/build.yml
README.md
deploy.sh
dfx.json
e2e-tests/README.md
e2e-tests/scripts/deploy-local-canisters
scripts/deploy-ci-to-testnet
scripts/deploy-docker-build-to-testnet
update_config.sh

The dfx version 0.8.4 is now well behind the default version (0.9.2).  It is generally sensible to stay reasonably up to date.  Also, looking at the changelog, there are changes that would help us clean up our code.  Examples:
- `DFX_NETWORK` is available as an environment variable to the build command.
- There is [a standardized location](https://github.com/dfinity/sdk/blob/master/CHANGELOG.adoc#feat-remote-canister-support) for external canister IDs, such as governance, ledger and II.
- Update dfx from 0.8.4 to 0.9.2
- Removed `--no-wallet` everywhere as it is now the default and using it throws an error.
These may be affected:
- Local development environments
- Deployment to testnets
- CI
- Production is not deployed with dfx but it is built with dfx.
See CI
- Deploy nns-dapp to a …

Update dfx to 0.9.2

---

frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalSummary.svelte
frontend/svelte/src/lib/components/proposals/BallotSummary.svelte

Fix broken layout in proposal summary
https://www.loom.com/share/a326ded572f04af9a1e90e587b7707d1

fix: broken summary layout (too wide <pre>)

---

frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte

Not sure it's important for prod but locally it's possible to have a neuron w/o voting power.
1. stake a neuron w/ amount === 1
2. make dummy proposals (not enough for all but at least one should be created)
As result:
- the neuron has cachedNeuronStake === neuronFees => 0
- votingPower === 0
And the user is able to select the neuron but it doesn't update the total. In case of multiple neurons in theory user could still try vote using this neuron.
- filter out from selections neurons w/o votingPower
https://user-images.githubusercontent.com/98811342/162806652-1292cdae-9282-4537-be0e-04c870d89eee.mov

fix: remove from selection neurons w/o votingPower

---

frontend/svelte/src/lib/components/ui/Tooltip.svelte

See screenshots
~tablet view
mobile

fix: hidden/cut-off tooltip on mobile

---

frontend/svelte/src/lib/modals/proposals/ProposalsFilterModal.svelte
frontend/svelte/src/lib/types/proposals.ts
frontend/svelte/src/tests/lib/modals/proposals/ProposalsFilterModal.spec.ts

We shouldn't include Unknown or Unspecified as options for the filters, since those values should never appear on proposal fields.
- do not provide `Unspecified` respectively `0` value as option for the proposal filters

feat: do not provide "Unspecified" as proposal filter option

---

frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte

Unify display of current balance and input field to enter amount on "New transaction" and "Create neuron" wizard modal.
Discussed with Mischa: balance and field comes first, therefore this PR sort the elements of the "Stake neuron" step accordingly.
- sort elements and remove unused div
Before:
After:

style: sort stake neuron information

---

frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionInfo.svelte
frontend/svelte/src/tests/lib/components/accounts/NewTransactionAmount.spec.ts

In the "New transaction" wizard displaying "source" and "destination" information on the "amount" step does not particularly add much values because the next step is a "review" step that repeat these information.
Discussed wish Mischa.
- display only the "fee" on amount step and "fee+source+destination" on "review step"
Before:
After:

feat: display fee only on amount step

---

frontend/svelte/src/lib/components/ui/Toast.svelte
frontend/svelte/src/tests/lib/components/ui/Toast.spec.ts
frontend/svelte/src/tests/lib/components/ui/Toasts.spec.ts

Users seems to not get that the toast messages are not disappearing automatically. After some discussions w/ Mischa the first solution - to replace the ( x ) with more visible call-to-action.
The tooltip was removed and the message visible area was increased to be always 3 lines with a scroll if needed (aligned w/ Mischa)
- Design update only, no tests needed.
https://user-images.githubusercontent.com/98811342/163381000-8f3699f7-cb7a-4cf0-a3f6-d595c320ae0c.mov
https://user-images.githubusercontent.com/98811342/163381020-18be7817-a74a-4419-9b15-a21c99f765ec.mov
https://user-images.githubusercontent.com/98811342/163381036-0c7ba437-5a29-4a10-974a-94d40d2690bb.mov

feat: redesign toasts

---

frontend/svelte/src/lib/components/proposals/ProposalsFilters.svelte
frontend/svelte/src/lib/utils/enum.utils.ts
frontend/svelte/src/tests/lib/components/proposals/ProposalsFilters.spec.ts

Because we removed the "Unspecified" options of the proposal filters, the counter total was not displaying the correct total value anymore - e.g. 5/11 instead of 5/10 filters.
In addition, found out that `Topic` was used in a generic utils that was fortunately only used so far for such filter.
- fix counter without "Unspecified" value
- fix generic utils
Counters are now correct:

fix: proposal filters counter

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/ProposalDetail.svelte
frontend/svelte/src/tests/mocks/neurons.mock.ts
frontend/svelte/src/tests/routes/ProposalDetail.spec.ts

We want to voting feature to be available only when the neurons store has been fully initialized but we also want to provide a smooth UI. That's why instead of hiding the all proposal detail page while we load the information we need we can display the static content - i.e. the proposal detail - as fast as we can and display another spinner dedicated to the loading of the neurons.
Worth to note that the store is now loaded only once, therefore user should only face this spinner the first time the store is loaded.
- split `ProposalDetail` checks for `proposalInfoStore` and `neuronsReady` to display two distinct spinner - i.e. display the `ProposalDetailCard` as fast as possible

feat: "Loading your neurons..." spinner

---

frontend/svelte/src/lib/api/proposals.api.ts
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts

If user has for example two neurons with one neuron (B) following another neuron (A). Then if user select both A and B to cast a vote on a proposal, A will first vote for itself and then vote for the followee B. Then our function `Promise.allSettled` that register all votes process next neuron B and try to vote again. This leads to an error `"Neuron already voted on proposal."` thrown by the [Governance canister](https://github.com/dfinity/ic/blob/936d234f2e6179cbaf6e5628df0f77e594e03505/rs/nns/governance/src/governance.rs#L5264) because it has indeed already been registered by A.
Vote are correctly cast therefore we can safely ignore this particular error.
This has been thankfully found by [justmythoughts](https://forum.dfinity.org/u/justmythoughts) on the …

feat: ignore error "Neuron already voted on proposal."

---

frontend/svelte/src/routes/Proposals.svelte

PR [#698](https://github.com/dfinity/nns-dapp/pull/698) had a missing flow. It indeed did not reset the list of proposals but had for effect to make the changes of the filters ignored after navigating back from the proposal detail page.
This PR resolves the issue.
- if we don't reset the filter and list explicitly, we can consider the component as `initialized`

fix: filters have no effect after back from detail page

---

Dockerfile

Flutter builds in docker are failing.
Notes:
- Builds started failing at about 8pm last night.  See:  https://github.com/dfinity/nns-dapp/actions/workflows/docker-build.yaml
- Builds failed equally in CI and on local docker
- Non-docker builds still work.
- Several new errors were observed in docker.  One was:
```
#30 28.24 fatal: unsafe repository ('/flutter' is owned by someone else)
#30 28.24 To add an exception for this directory, call:
#30 28.24
#30 28.24 	git config --global --add safe.directory /flutter
```
- Taking this suggestion seems to work.
- Added a git config line to the dockerfile.
- See CI
- Local (non-CI) docker builds work.

Fix docker builds of the flutter frontend

---

frontend/svelte/package-lock.json
frontend/svelte/src/lib/api/governance.api.ts
frontend/svelte/src/lib/components/accounts/SelectAccount.svelte
frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
frontend/svelte/src/lib/components/ui/Card.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/MergeNeuronsModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/lib/themes/mixins/_interaction.scss
frontend/svelte/src/lib/types/errors.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/error.utils.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/api/governance.api.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

User can merge neurons.
There are two types of checks. Individual and in pairs.
* Neurons might not be mergeable for their attributes (ex: joined community fund).
* Pairs of neurons might not be mergeable by the combination of their attributes (ex: both have different controller).
* Add Functionality to the MergeNeuronsModal to check if neurons are mergeable or not and perform action.
* Add util "canBeMerged" to check if neurons can be merged
* Add governance api "mergeNeurons"
* Add prop "disabled" to NeuronCard and Card.
* Add util "mapMergeableNeurons" to wrap NeuronInfo with information about mergeability.
* Add neuron service "mergeNeurons".
* Test new functionality in the MergeNeuronsModal.
* New tests for "mergeNeurons" governance api.
* New tests for "mergeNeurons" service.
* New …

Feat: Merge neurons functionality

---

frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
frontend/svelte/src/tests/lib/components/accounts/NewTransactionReview.spec.ts

Disable "Confirm transaction" action while processing to prevent misbehavior and to follow pattern of other steps / wizards.
- button `disabled` if `busy`

feat: disable confirm button while processing

---

frontend/svelte/src/lib/components/ui/Input.svelte
frontend/svelte/src/tests/lib/components/ui/Input.spec.ts

Per default, we do not want to use the autocomplete feature for `<input />` set as type text. It notably fixes a styling issue on Webkit.
- set `autocomplete` to `off` per default

feat: autocomplete to off as default value for input type text

---

frontend/svelte/src/lib/services/neurons.services.ts

eslint warning "JSDoc '@param' tag has name 'callback', but there is no parameter with that name. "
- declare first the param object and then the param variables in jsdoc

docs: fix jsdoc params definition

---

frontend/svelte/src/lib/utils/dev.utils.ts

eslint warning "Rest parameter 'args' implicitly has an 'any[]' type, but a better type may be inferred from usage. "
- define args as type `string[]`

chore: missing types for log function

---

frontend/svelte/src/lib/modals/accounts/NewTransactionModal.svelte
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/utils/app-path.utils.ts
frontend/svelte/src/routes/Accounts.svelte
frontend/svelte/src/routes/Wallet.svelte
frontend/svelte/src/tests/lib/modals/accounts/NewTransactionModal.spec.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/lib/utils/app-path.utils.spec.ts
frontend/svelte/src/tests/routes/Accounts.spec.ts
frontend/svelte/src/tests/routes/Wallet.spec.ts

Access "New transaction" feature / modal from the "Wallet" page with the selected account prefilled to current account (the account displayed on the detail page).
- path `selectedAccount` to `NewTransactionModal`
- resolve identifier from route path
- get account for identifier from store
- add utils to resolve last detail of path as `string`
- display spinner while loading accounts on wallet page
- enabled - disabled action on wallet page until data are loaded
- bind "new transaction" action modal with button

feat: add "new transaction" feature to wallet page

---

frontend/svelte/src/lib/components/accounts/AddNewAccount.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts

Follow defined UX rule "actions modals should be closed on action error"
- close modal "add sub account" in case of submit error
- close modal "transfer icp" in case of submit error

feat: close accounts action modal on error too

---

frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User controlled by Hotkey can manage followees, except ManageNeuron topic.
* Logic to get identity for followees actions, depends on topic.
* Disable button to Follow or Unfollow depending on topic and controller.
* New test to check hotkeys can control followees.
* New test to check hotkeys can't controll followees on Manage Neuron.

L2-477 and L2-480: Hotkey manages followees not ManageNeuron

---

frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

Neuron can't follow another neuron twice on the same topic, nor can follow itself. These validations are done in the frontend.
* Add the validations in the neuron service addFollowee.
* Change return type of neuron util "followeesByTopic" to "NeuronId[]".
* Clean up some code.
* New tests for new validations.
* Change test in neuron util "followeesByTopic".

L2-474: Follow neuron validations

---

frontend/svelte/src/lib/constants/constants.ts

Increase the number of paginated proposals to 500 requested by user with long history.
- update constant `LIST_PAGINATION_LIMIT`

feat: increase the number of paginated proposals to 500

---

frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalDetailCard.svelte
frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalMeta.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
frontend/svelte/src/lib/components/proposals/ProposalCard.svelte
frontend/svelte/src/lib/components/proposals/ProposalMeta.svelte
frontend/svelte/src/lib/components/proposals/Proposer.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/proposals.utils.ts
frontend/svelte/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts

Some users find themselves lost on the proposal detail page after some scroll and might not be sure on what proposal they are about to vote. That's why we add a sentence next to the vote actions that display the proposal id and topic again.
- refactor proposal info destruction that is shared in various component
- display sentence “Do you want to adopt or reject Proposal 56789 for Governance?” with related proposal id and topic

feat: display question "accept reject proposal"

---

frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts

Display the title of the proposal in the question "accept / reject voting" as well.
Follow-up of #774
- display `title` in question

feat: display title in proposal question

---

frontend/svelte/src/lib/api/proposals.api.ts
frontend/svelte/src/lib/components/neuron-detail/Ballots/Ballots.svelte
frontend/svelte/src/lib/components/proposals/ProposalCard.svelte
frontend/svelte/src/lib/components/proposals/ProposalMeta.svelte
frontend/svelte/src/lib/components/ui/InfiniteScroll.svelte
frontend/svelte/src/lib/constants/constants.ts
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/lib/components/ui/InfiniteScroll.spec.ts
frontend/svelte/src/tests/lib/components/ui/InfiniteScrollTest.svelte

Do not fetch from the backend the proposal for each ballot that the neuron has voted, until the user needs to see it.
* Use the `InfiniteScroll` in the `Ballots` components to load ballots per page.
* Add two props in `InfiinteScroll` for new use case: `pageLimit` and `containerElement`.
* New test cases in InfiniteScroll

L2-483: Lazy load voted proposals in Neuron Voting History

---

deploy.sh

Fix deployments to testnets.
* `dfx 0.9.2` removed `--no-wallet` from many commands, so existing commands with `--no-wallet` broke.  So I removed `--no-wallet` from all out `dfx` calls.
* svelte hard-wires a canister ID - something it should never ever do but hey - this includes a quick fix and we can provide a deeper solution later.
* Remove all hard-wired values for OWN_CANISTER_ID from svelte.
Deployed with:
```
REDIRECT_TO_LEGACY=both ./deploy.sh testnet
```
To: https://wzp7w-lyaaa-aaaaa-aaara-cai.nnsdapp.dfinity.network/
and again from scratch to: https://wljip-hiaaa-aaaaa-aaasa-cai.nnsdapp.dfinity.network/v2/
Weirdly, it says:
```
max@sinkpad:~/dfn/nns-dapp/branches/fix-deploy (1:36:28)$ REDIRECT_TO_LEGACY=both ./deploy.sh testnet
Deploying nns-dapp to testnet...
canister may have …
```

Fix deploy

---

frontend/svelte/env.config.mjs

Some domains are malformed on main.  Here are the env vars used by svelte:
```
"svelteEnvironmentVariables": {
"ENVIRONMENT": "mainnet",
"DEPLOY_ENV": "mainnet",
"FETCH_ROOT_KEY": false,
"REDIRECT_TO_LEGACY": "prod",
"MAINNET": "https://ic0.app/",
"HOST": "https://ic0.app/",
"OWN_CANISTER_ID": "qoctq-giaaa-aaaaa-aaaea-cai",
"OWN_CANISTER_URL": "https://qoctq-giaaa-aaaaa-aaaea-caiic0.app/", <---
"IDENTITY_SERVICE_URL": "https://identity.ic0.app/",
"GOVERNANCE_CANISTER_ID": "rrkah-fqaaa-aaaaa-aaaaq-cai",
"LEDGER_CANISTER_ID": "ryjl3-tyaaa-aaaaa-aaaba-cai",
"GOVERNANCE_CANISTER_URL": "https://rrkah-fqaaa-aaaaa-aaaaq-caiic0.app/", <-----
"LEDGER_CANISTER_URL": "https://ryjl3-tyaaa-aaaaa-aaaba-caiic0.app/", <-----
"ROLLUP_WATCH": false
}
```
The cause for this is this code, which is missing …

Fix CSP domains

---

frontend/svelte/src/lib/api/accounts.api.ts
frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/api/nns-dapp.api.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.errors.ts
frontend/svelte/src/lib/components/accounts/HardwareWalletConnect.svelte
frontend/svelte/src/lib/components/accounts/HardwareWalletConnectAction.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/proxy/ledger.services.proxy.ts
frontend/svelte/src/lib/services/ledger.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/canisters/nns-dapp.canister.spec.ts
frontend/svelte/src/tests/lib/components/accounts/HardwareWalletConnect.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/services/ledger.services.spec.ts
frontend/svelte/src/tests/mocks/nns-dapp.canister.mock.ts

Attach hardware wallet - i.e. create an account for the selected hardware wallet.
Follows PR [connect](https://github.com/dfinity/nns-dapp/pull/785) hardware wallet.
- refactor duplicate code to instantiate nns-dapp canister agent
- add `registerHardwareWallet` to nns-dapp canister
- uses previous function and add `registerHardwareWallet` in `ledger.service`
- add function to proxy for lazy loading / chunking reason
- implement feature in component
- call busy store and close modal in the component as well
Note: even if I would not have used my hw before the account would not have been displayed in the list of accounts anyway, this is something that will be solve in next PR. There is a TODO within code / this PR about it.

feat: attach hardware wallet

---

frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/svelte/src/lib/components/accounts/HardwareWalletConnect.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/ledger.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/canisters/nns-dapp.canister.spec.ts
frontend/svelte/src/tests/lib/services/ledger.services.spec.ts

Follow label pattern for errors
- two underscores instead of one in i18n label `error__attach_wallet`

refactor: ledger error label key with two underscores

---

frontend/svelte/src/lib/components/accounts/SelectAccount.svelte
frontend/svelte/src/tests/lib/components/accounts/SelectAccount.spec.ts

The title "My accounts" was displayed even if no accounts were listed.
- display title only if at least one account can be selected

fix: display select account title only if accounts are selectable

---

frontend/svelte/src/lib/components/neuron-detail/SelectPercentage.svelte
frontend/svelte/src/lib/modals/neurons/MergeMaturityModal.svelte
frontend/svelte/src/lib/modals/neurons/SpawnNeuronModal.svelte
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/modals/neurons/SpawnNeuronModal.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

User should not be able to confirm spawning a neuron if amount is not enough for a new neuron.
* Calculate if percentageToSpawn is enough to create new neuron.
* Add disabled prop in SelectPercentage.
* Add test for new use case.

L2-527: Disable Confirm Spawn if not enough

---

e2e-tests/common/constants.ts
e2e-tests/common/navigator.ts
e2e-tests/common/register.ts
e2e-tests/package.json
e2e-tests/specs/home.e2e.ts
e2e-tests/specs/multi-tab-auth.e2e.ts
e2e-tests/specs/redirect-to-legacy.e2e.ts
e2e-tests/tsconfig.json
e2e-tests/wdio.conf.ts

There are a lot of typescript errors in the e2e tests, strangely not caught by eslint.  This makes it easy to write typos and similar mistakes that SHOULD be caught at compile time but that wdio either swallows silently or causes wdio to die with very hard to debug error messages.
So let's catch the typescript errors.
Running tsc on the e2e test code does just that, and actually finds problems.
- Run tsc as part of `npm run lint`
- Fix 36 errors.
- Add esModuleInterop due to tsc warnings in third party libraries.
The e2e tests pass locally, and should also pass on CI.

Fix typescript in e2e tests

---

frontend/svelte/package.json

Testnet has been redeployed, fix the canister id that has changed.
- update nns-both canister id in `package.json`

build: fix canister id for local development

---

frontend/svelte/package-lock.json
frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
frontend/svelte/src/lib/components/neurons/SelectNeuronsToMerge.svelte
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/utils/error.utils.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

User is able to manage a neuron from a Hardware Wallet.
* Get the identity based on the neuron controller where suited.
* Prefer the user identity if the functionality can be managed by a hotkey.
* Split and Join Community Fund only available for neurons whose controller is the nns dapp user. Like in Svelte.
* New neuron util "getIdentityByPrincipal" and "isNeuronControllableByUser".
* Helper "getAndLoadNeuron" uses user principal.
* Add tests for HW cases in Merge Neurons Modal and "mapMergeable" util.
* Tests for "getIdentity" helpers.

L2-486: Neurons functionality compatible with hardware wallet

---

frontend/svelte/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
frontend/svelte/src/lib/components/neuron-detail/NeuronHotkeysCard.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/DissolveActionButton.svelte
frontend/svelte/src/lib/components/neurons/AddUserToHotkeys.svelte
frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/components/ui/BusyScreen.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
frontend/svelte/src/lib/modals/neurons/MergeMaturityModal.svelte
frontend/svelte/src/lib/modals/neurons/SpawnNeuronModal.svelte
frontend/svelte/src/lib/services/busy.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/components/neuron-detail/NeuronHotkeysCard.spec.ts
frontend/svelte/src/tests/lib/components/neuron-detail/actions/DissolveActionButton.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/AddHotkeyModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/DisburseNeuronModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/IncreaseDissolveDelayModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/MergeMaturityModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/SpawnNeuronModal.spec.ts
frontend/svelte/src/tests/lib/services/busy.services.spec.ts

Show a message to the user when confirmation from the Hardware Wallet is needed.
* Change Busy Store to an array of objects that can take a message.
* BusyScreen component reads and displays message if present.
* Busy service to show the message if the neuron is controlled from hardware wallet.
* Add a test for new busy service.

L2-520: Show message busy screen

---

frontend/svelte/src/lib/components/ui/BusyScreen.svelte
frontend/svelte/src/tests/lib/services/busy.services.spec.ts

Design is personal but I feel like the text of the busy screen was screaming at me 😂.
- display text with `p`
- add spacing
- limit width in case passed text would be really long
Is:
Will be:

style: busy text as paragraph

---

frontend/svelte/src/lib/components/accounts/AddSubAccount.svelte
frontend/svelte/src/lib/components/accounts/HardwareWalletConnect.svelte
frontend/svelte/src/lib/components/accounts/HardwareWalletListNeuronsButton.svelte
frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
frontend/svelte/src/lib/components/accounts/RenameSubAccountAction.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/JoinCommunityFundButton.svelte
frontend/svelte/src/lib/components/neurons/AddUserToHotkeys.svelte
frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
frontend/svelte/src/lib/components/neurons/KnownNeuronFollowItem.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
frontend/svelte/src/lib/services/busy.services.ts
frontend/svelte/src/lib/services/proposals.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/tests/lib/components/ui/BusyScreen.spec.ts
frontend/svelte/src/tests/lib/services/busy.services.spec.ts
frontend/svelte/src/tests/lib/services/proposals.services.spec.ts
frontend/svelte/src/tests/lib/stores/busy.store.spec.ts

Path object to start busy screen.
- refactor `startBusy` to provide the state object
- remove double entry `remove-followee` in list of initiator
- rename type to interface `BusyState`

refactor: start busy with object params

---

frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/modals/WizardModal.svelte
frontend/svelte/src/lib/modals/accounts/HardwareWalletListNeuronsModal.svelte
frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
frontend/svelte/src/lib/modals/neurons/FollowNeuronsModal.svelte
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
frontend/svelte/src/lib/modals/neurons/VotingHistoryModal.svelte
frontend/svelte/src/lib/themes/variables.scss

I noticed in the demo provided in PR #852 that modal are really big on big screen. This PR limits their `height`.
- refactor property value name `medium` to `big` 
- set max height to 610px or screen size minus some spacing

style: fix modal max height

---

frontend/svelte/src/lib/components/neurons/AddUserToHotkeys.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/NewTransactionModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/AddHotkeyModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/CreateNeuronModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User can keep with the New Neuron flow when creating a neuron from a hardware wallet.
* Separate staking neuron and loading in store.
* On skipping adding the current user as hotkey, it closes the modal.
* Export the neuron service "getAndLoadNeuron".
* CreateNeuronModal reads neuron from store.
* Fix broken tests
* Add test case in CreateNeuronModal for Hardware Wallet.

L2-524: New Neuron Flow working for HW

---

frontend/svelte/src/lib/components/neurons/AddUserToHotkeys.svelte
frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
frontend/svelte/src/lib/components/neurons/KnownNeuronFollowItem.svelte
frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
frontend/svelte/src/lib/components/ui/ConfirmActionScreen.svelte
frontend/svelte/src/lib/modals/ConfirmationModal.svelte
frontend/svelte/src/lib/modals/neurons/MergeMaturityModal.svelte
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/lib/modals/neurons/SpawnNeuronModal.svelte
frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
frontend/svelte/src/tests/lib/components/ui/ConfirmActionScreen.spec.ts
frontend/svelte/src/tests/lib/components/ui/ConfirmActionScreenTest.svelte

Instead of spinner replacing buttons when work is in progress, make buttons disabled if `$busy`. This to avoid two display two spinners on screen.
- remove `loading` and `spinner`
- make buttons disabled if `$busy`
No particular tests were provided because such use case was not tested before anyway.

feat: instead of spinner, make buttons disabled if busy

---

frontend/svelte/src/lib/components/accounts/HardwareWalletListNeuronsButton.svelte
frontend/svelte/src/lib/components/accounts/RenameSubAccountAction.svelte
frontend/svelte/src/lib/components/accounts/RenameSubAccountButton.svelte
frontend/svelte/src/lib/components/accounts/WalletActions.svelte
frontend/svelte/src/lib/modals/accounts/HardwareWalletNeuronAddHotkeyModal.svelte
frontend/svelte/src/lib/modals/accounts/RenameSubAccountModal.svelte
frontend/svelte/src/lib/types/hardware-wallet-neurons.context.ts
frontend/svelte/src/tests/lib/components/accounts/HardwareWalletAddNeuronHotkeyTest.svelte
frontend/svelte/src/tests/lib/components/accounts/HardwareWalletListNeuronsButton.spec.ts
frontend/svelte/src/tests/lib/components/accounts/HardwareWalletNeuronsTest.svelte
frontend/svelte/src/tests/lib/components/accounts/RenameSubAccountAction.spec.ts
frontend/svelte/src/tests/lib/components/accounts/RenameSubAccountButton.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/HardwareWalletNeuronAddHotkeyModal.spec.ts
frontend/svelte/src/tests/lib/modals/accounts/RenameSubAccountModal.spec.ts
frontend/svelte/src/tests/mocks/context-wrapper.mock.ts
frontend/svelte/src/tests/mocks/hardware-wallet-neurons.store.mock.ts
frontend/svelte/src/tests/mocks/modal.mock.ts
frontend/svelte/src/tests/mocks/selected-account.store.mock.ts

A dedicated context and store has been introduced for the selected account of the "Wallet -Account" details page. It can be used to avoid passing properties through components and to replace existing store information that duplicate the information.
- use selected account context and store instead of passing props
- remove `selectedAccount` from hardware wallet neurons store and use selected account store instead

refactor: use selected account context

---

frontend/svelte/src/lib/components/neurons/KnownNeuronFollowItem.svelte
frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/svelte/src/tests/lib/modals/neurons/NewFolloweeModal.spec.ts

Modal to add new followee or unfollow known neurons closes after action (like in Flutter).
* Dispatch the "nnsClose" action in NewFolloweeModal after followee action.
* Dispatch "nnsUpdate" from KnownNeuronFollowItem and listen for it in NewFolloweeModal to close modal.
* Expect that the modal closes in the tests.

Fix: Close After New Followee change

---

.github/CODEOWNERS

The CODEOWNERS is required by @dfinity/idx in order for this repo to
accept external contributions.

Add CODEOWNERS file (#647)

---

scripts/setup

`ic-admin` is not installed by the setup script but it should be, as it is used for deployments and creating proposals on testnets.
- Add ic-admin
- Tested installation on:
- An M1 Mac
- An Ubuntu 20.04 Linux machine.

Install ic-admin

---

e2e-tests/package.json

e2e tests have been using a proxy, using ports to distinguish between canisters.  This is not standard for the IC and is not actually needed.
- Use localhost subdomains directly in ee2 tests, rather than the proxy.
- It may be that the proxy turns out to be needed after all.  Let us wait for quiet and if there are no contra-indications, delete the proxy.  That will mean less code to maintain and save about 16 seconds from every CI run.
See the e2e tests run in CI

Use subdomains for e2e tests

---

frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User can see the proposer modal
* `loadNeuron` does not check if the user is authorized or not to see the neuron.
* Test for bug.

Fix: Propose can load neuron

---

frontend/svelte/src/lib/components/ui/Input.svelte
frontend/svelte/src/lib/components/ui/InputWithError.svelte

Refactor `Input` and remove the prop `withErrorMessage`.
* Use a css variable instead of a prop to change Input style.
No test changes.

Fix: Style variable instead of prop for Input

---

frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

ICP class doesn't support exponential format (e.g. "1e-8").
icp.d.ts
```ts
/**
* Initialize from a string. Accepted formats:
*
* 1234567.8901
* 1'234'567.8901
* 1,234,567.8901
*/
static fromString(amount: string): ICP | FromICPStringError;
```
Refactoring suggestions are welcome.
https://user-images.githubusercontent.com/98811342/169790101-edc7935f-3262-4adc-8f4c-ab7f44f55176.mov
https://user-images.githubusercontent.com/98811342/169790340-5519db02-4e39-4df0-8024-0120fc061397.mov
- String() -->  toFixed(8) (According to validation and display formatting 8 is enough precision)
- neuron.utils.spec `expect(convertNumberToICP(0.00000001)?.toE8s()).toBe(BigInt(1));`

fix: replace exponential format for ICP amount

---

frontend/svelte/src/App.svelte
frontend/svelte/src/routes/Neurons.svelte
frontend/svelte/src/tests/App.spec.ts

Some users feel like voting is currently a bit slow because the neurons have to be loaded. This behavior happens because most user jump in the "Voting" tab in svelte from the other tabs that are still written with "Flutter".
e.g. user sign in -> flutter -> load neurons in the background -> go to "voting" tab -> select proposal -> neurons have to be loaded again
It will be improved once we will have launch the other tabs rewritten in Svelte. However, in current implementation, the neurons - unlike the accounts - are not loaded after each sign-in but "only" when user access the "Neurons" tab.
This PR change this behavior by loading the neurons after each sign-in. This behavior is identical to what Flutter does and has for end effect to make feel that the proposal detail page is faster …

feat: load neurons after sign-in

---

.github/workflows/build.yml
deploy.sh
e2e-tests/common/constants.ts
e2e-tests/components/proposals-tab.ts
e2e-tests/scripts/nns-canister-install
e2e-tests/scripts/nns-canister.Dockerfile

The CMC canister needs to be patched in order for cycle creation commands to work on a testnet.  The patch allows the exchange rate for buying the initial canister cycles to be set directly.
- Commit 1: Build the patched canister in Docker, with the other patched NNS canisters.
- Commit 2: Rename `--users` in deploy.sh to `--populate`
- Commit 3: Set the exchange rate as part of `--populate`
- Commit 4: Make a proposal to allow CMC to create canisters; do this as part of `--populate`
- Cleanup:
- Run only relevant parts of `--populate`:
-  On local `dfx` networks, there are no subnets so don't try to authorize subnets.  It will fail.
- If the network uses flutter, don't try to use e2e tests to create users and neurons.  It will fail.
- Bust the NNS canister cache, as otherwise the old …

Build patched CMC canister and deploy

---

frontend/svelte/src/App.svelte
frontend/svelte/src/lib/components/canisters/CanisterCard.svelte
frontend/svelte/src/lib/constants/routes.constants.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/services/debug.services.ts
frontend/svelte/src/lib/stores/canisters.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/app-path.utils.ts
frontend/svelte/src/routes/CanisterDetail.svelte
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/tests/lib/components/canisters/CanisterCard.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/lib/stores/canisters.store.spec.ts
frontend/svelte/src/tests/mocks/canisters.mock.ts
frontend/svelte/src/tests/routes/CanisterDetail.spec.ts
frontend/svelte/src/tests/routes/Canisters.spec.ts

User can see the attached canisters in a list of cards.
* New component "CanisterCard".
* New route "CanisterDetails". Empty for now with TODOs inside.
* Add new route to the accepted routes.
* Change in the canisters store to also keep whether the data is "certified" or not. Following the other store patterns.
* Test for the new components: CanisterCard and route CanisterDetails.
* Extend route Canisters testing.
* Fix canisters store tests.

L2-335: List CanisterCards

---

frontend/svelte/src/App.svelte
frontend/svelte/src/lib/components/common/Header.svelte
frontend/svelte/src/lib/components/common/HeadlessLayout.svelte
frontend/svelte/src/lib/components/ui/BusyScreen.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/Modal.svelte
frontend/svelte/src/lib/proxy/debug.services.proxy.ts
frontend/svelte/src/lib/services/debug.services.ts
frontend/svelte/src/lib/stores/debug.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/dev.utils.ts

To be able to get the debug log also on mobile devices the trigger was added to the headlines and the busy spinner (see [descriptions](https://www.notion.so/Debug-state-trigger-99c2bcdd972c48fbbcdcea98965ba76b))
- `triggerDebugReport` directive
- confirm dialog before log
only manual

Debug store trigger

---

frontend/dart/lib/ic_api/web/web_ic_api.dart

Currently merging neurons which are controlled via hardware wallet is not supported, so this PR makes the NNS Dapp display an error message if trying to merge hardware wallet controlled neurons, rather than failing and displaying an obscure message containing minified code.
- Display error message if trying to merge hardware wallet controlled neurons.
This version is deployed here - https://wqmuk-5qaaa-aaaaa-aaaqq-cai.nnsdapp.dfinity.network/
On this version, neurons controlled by the user's NNS Dapp principal can still be merged and now the error message displays when trying to merge hardware wallet neurons.

Display error message if user tries to merge hardware wallet neurons

---

frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/components/accounts/AddAccountType.svelte
frontend/svelte/src/lib/components/canisters/AttachCanister.svelte
frontend/svelte/src/lib/components/canisters/SelectNewCanisterType.svelte
frontend/svelte/src/lib/components/ui/CardItem.svelte
frontend/svelte/src/lib/components/ui/PrincipalInput.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
frontend/svelte/src/tests/lib/components/accounts/AddAccountType.spec.ts
frontend/svelte/src/tests/lib/components/ui/CardItem.spec.ts
frontend/svelte/src/tests/lib/components/ui/InputValueTest.svelte
frontend/svelte/src/tests/lib/components/ui/PrincipalInput.spec.ts
frontend/svelte/src/tests/lib/components/ui/PrincipalInputTest.svelte
frontend/svelte/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
frontend/svelte/src/tests/lib/modals/canisters/CreateOrLinkCanisterModal.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/routes/Canisters.spec.ts

User can link an existing canister to the nns dapp user.
* New Modal CreateOrLinkCanisterModal with two screens: SelectNewCanisterType and AttachCanister.
* New canister api: "attachCanister".
* New cansiter service: "attachCanister".
* Button in "Canisters" route opens CreateOrLinkCanisterModal.
* New UI Component: CardItem, created from cards in AddAccountType and reused there.
* New UI Component: PrincipalInput.
* Test the Link Canister flow.
* Test the new canister api "attachCanister".
* Test the new canister service "attachCanister"
* Test that Canisters route opens CreateOrLinkCanisterModal.
* Test new UI Components.

L2-596: Link existing canister

---

frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
frontend/svelte/src/lib/modals/accounts/NewTransactionModal.svelte
frontend/svelte/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
frontend/svelte/src/lib/modals/neurons/VotingHistoryModal.svelte
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/transaction.context.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionReview.spec.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionTest.svelte
frontend/svelte/src/tests/lib/modals/accounts/NewTransactionModal.spec.ts
frontend/svelte/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User sees always new neuron stake after transaction.
* "loadNeuron" checks balance when fetching a single neuron, same as when fetching the list of neurons.
* Check in "loadNeuron" can be skipped with `skipCheck` flag.
* "loadNeuron" also accepts the query strategy as param.
* Add a callback in the Transaction modal to be called when transaction is finished.
* Test that the new callback in Transaction modal is called.
* Test new flags in "loadNeuron"

L2-608: Fix neuron stake update after transaction

---

frontend/svelte/src/lib/components/ui/Collapsible.svelte

Do not show scroll bar if not needed in Follow Neurons Modal
* Overflow-y in Collapsible depends on the height and prop maxHeight passed.
No extra tests.

Fix: Scroll on Collapsible only when needed

---

frontend/svelte/src/lib/components/canisters/ControllersCard.svelte
frontend/svelte/src/lib/components/canisters/CyclesCard.svelte
frontend/svelte/src/lib/components/ui/SkeletonParagraph.svelte
frontend/svelte/src/lib/components/ui/SkeletonTitle.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/stores/debug.store.ts
frontend/svelte/src/lib/types/canister-detail.context.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/canisters.utils.ts
frontend/svelte/src/routes/CanisterDetail.svelte
frontend/svelte/src/tests/lib/components/neurons/ConfirmDissolveDelay.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/lib/stores/canisters.store.spec.ts
frontend/svelte/src/tests/lib/utils/canisters.utils.spec.ts
frontend/svelte/src/tests/mocks/canisters.mock.ts
frontend/svelte/src/tests/routes/CanisterDetail.spec.ts

User can see the canister title in the canister detail page.
* New canister service "loadCanisterDetails" that fetches canister details and adds them to the store.
* New store "canisterDetailsStore" which stores the data of a canister. It's a different type than from nns dapp.
* New canister service "routePathCanisterId" to read the canister id from the url.
* Setup of "ControllersCard" and "CyclesCard" to help parallel development.
* CanisterDetails route component triggers fetching canisters and details and read them from the stores.
* New test for new two canister services.
* Extend CanisterDetails route tests.

L2-334: Setup Canister Detail Page

---

frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
frontend/svelte/src/lib/components/canisters/ConfirmCyclesCanister.svelte
frontend/svelte/src/lib/components/canisters/SelectCyclesCanister.svelte
frontend/svelte/src/lib/components/canisters/SelectNewCanisterType.svelte
frontend/svelte/src/lib/components/ui/Input.svelte
frontend/svelte/src/lib/constants/icp.constants.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/canisters.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/icp.utils.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
frontend/svelte/src/tests/lib/components/canisters/SelectCyclesCanister.spec.ts
frontend/svelte/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
frontend/svelte/src/tests/lib/components/ui/CardItem.spec.ts
frontend/svelte/src/tests/lib/components/ui/CardItemTest.svelte
frontend/svelte/src/tests/lib/modals/canisters/CreateOrLinkCanisterModal.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/lib/testHelpers/clickByTestId.ts
frontend/svelte/src/tests/lib/utils/icp.utils.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts

User can enter ICP or TCycles amount and move to confirm create canister screen.
* Add different steps in CreateOrLinkCanisterModal depending on initial selection.
* New screen: SelectCyclesCanister.
* Move neuron util "convertNumberToICP" to icp utils.
* New icp utils: "convertIcpToTCycles" and "convertTCyclesToE8s".
* New canister api function "getIcpToCyclesExchangeRate".
* New canister service "getIcpToCyclesExchangeRate".
* Test new steps in CreateOrLinkCanisterModal
* Test that SelectCyclesCanister synchronizes inputs.
* Move "convertNumberToICP" test to icp utils.
* New tests for new icp utils.

L2-227: Create canister flow Part I

---

frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/components/accounts/SelectAccount.svelte
frontend/svelte/src/lib/components/canisters/ConfirmCyclesCanister.svelte
frontend/svelte/src/lib/components/canisters/SelectCyclesCanister.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
frontend/svelte/src/tests/lib/components/accounts/SelectAccount.spec.ts
frontend/svelte/src/tests/lib/components/canisters/SelectCyclesCanister.spec.ts
frontend/svelte/src/tests/lib/modals/canisters/CreateOrLinkCanisterModal.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/mocks/accounts.store.mock.ts
frontend/svelte/src/tests/routes/Canisters.spec.ts

User can create a canister from the main account or a subaccount.
* Implemented the "ConfirmCyclesCanister" to create the canister on click.
* New canister service: "createCanister".
* Added the step to select an account when creating a canister.
* Added a prop to SelectAccount: "hideHarwareWalletAccounts"
* Added the parameter to create a canister from a subaccount in the canister api "createCanister"
* Extend testing case in CreateOrLinkCanisterModal until canister creation.
* New test case in CreateOrLinkCanisterModal to check that hardware wallet accounts are not shown.
* New test for new canister service.
* New test case in SelectAccount for the new prop.

L2-227: Create Canister part II

---

frontend/svelte/src/lib/components/accounts/SelectAccount.svelte
frontend/svelte/src/lib/components/common/HeadlessLayout.svelte
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/tests/lib/components/accounts/SelectAccount.spec.ts

On select accounts component, the title "My accounts" can be displayed if user has sub-accounts. It can also be displayed if user has hardware wallets.
- if `displayTitle` prop is set and user has no subaccounts but has hardware wallet, display title as well

feat: display title "My accounts" on select accounts component if user has hardware wallets too

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User can see the splitted or spawned neurons immediately after the action.
The amount to split a neuron will be the amount of the new neuron. This is more user friendly.
* Add transaction fee to the amount on `splitNeuron` service.
* Neuron services "splitNeuron" and "spawnNeuron" do not load only one neuron, but call "listNeurons".
* Test to check that the transaction fee is added to the amount when splitting a neuron.

Fix: Improve split and spawn neuron

---

frontend/svelte/src/lib/components/canisters/SelectCyclesCanister.svelte
frontend/svelte/src/lib/utils/icp.utils.ts
frontend/svelte/src/tests/lib/utils/icp.utils.spec.ts

- feat: use type "icp" for cycles input (1.234 instead of 1,234)
- fix: `Uncaught (in promise) RangeError: The number 4320000000000.0005 cannot be converted to a BigInt because it is not an integer`
- refactor: remove double code and extract local functions
- set type `icp` for cycles `Input`
- extract local functions `setAmount` and `setCycles`
- spare double code of `onMount`
- rename function `convertTCyclesToE8s` to `convertTCyclesToIcp`, change method signature to `Number` and fix conversion with number casting
Error and input type number:

fix/feat: canister icp <-> cycles

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/tests/routes/Canisters.spec.ts

Discussed with Mischa, as for other screens, try to spare some not useful texts to spare spaces for what's useful - i.e. more spaces for the list of canisters.
- update canister introduction text

feat: simplify canister introduction text

---

frontend/svelte/src/lib/components/ui/CardBlock.svelte

Card blocks on proposal detail page used to be presented with a different background. This redo this ui colors.
it used to be `--gray100` and now will be `-gray50` because I deprecated 100.
- set background and contrast to `-gray50` for card block.

style: redo a different background for card block on the proposal detail page

---

frontend/svelte/src/lib/utils/navigation.utils.ts
frontend/svelte/src/lib/utils/proposals.utils.ts
frontend/svelte/src/lib/utils/utils.ts
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/tests/lib/utils/navigation.utils.spec.ts
frontend/svelte/src/tests/lib/utils/proposals.utils.spec.ts

To smoothness the ux, do not reload the canisters data on "back" from canister detail page.
This PR aligns the behavior to the "Voting" behavior.
- test if data should be reloaded on back
- refactor existing test of "Voting" tab to be reused for "Canisters" tab

feat: do not reload canisters data on back

---

frontend/svelte/src/lib/components/ui/Toast.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/stores/toasts.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/types/toast.ts
frontend/svelte/src/tests/lib/components/ui/Toast.spec.ts
frontend/svelte/src/tests/lib/modals/canisters/CreateOrLinkCanisterModal.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts

Improve UX when creating a canister.
* Toasts now accept an object for substitutions for the label key.
* Service "createCanister" returns new canister id when successful.
* Create canister success toast shows new canister id.
* Added a message in the busy screen when creating a canister.
* Fix tests.
* New test case in Toast to check that it replaces placeholders.

L2-653: Improve Canister Creation UX

---

frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalMeta.svelte
frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalSummary.svelte
frontend/svelte/src/lib/themes/fonts.scss

To have the same button height for the buttons with the long text the line-height was decreased.
- Change A and Button default line-height to be default
- remove redundant styles

fix: improve mobile button long text support

---

frontend/svelte/package-lock.json
frontend/svelte/package.json

Bump nns-js to `v0.4.3` and agent-js `v0.11.3` to provide a polyfill for `setBigUint64` in `agent-js` for users on iOS < v15.
- bump nns-js and agent-js

build: bump nns-js and agent-js

---

frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
frontend/svelte/src/lib/components/neuron-detail/SelectPercentage.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/MergeMaturityButton.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/SplitNeuronButton.svelte
frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
frontend/svelte/src/tests/lib/components/neurons/NeuronCard.spec.ts

Community wish more precision in the display of the neurons ICP. Therefore this PR extends the display of the ICP in the neurons tabs to the `detailed` display. See previous PR #947 and #949 for details.
- in neurons route and component use `formatICP` and `<ICP/>` cmp with option `detailed`

feat: ICP decimals detailed for neurons

---

frontend/svelte/package-lock.json
frontend/svelte/package.json

This PR aims to redo the nns-js nightly dependency that was temporary replaced with an actually release in #953.
- redo nns-js dependency to nightly of Friday Jun. 3

build: redo nns-js nightly dependency

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/types/neurons.errors.ts
frontend/svelte/src/lib/utils/error.utils.ts
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User can perform neuron actions before accounts are loaded.
* Check first if principal in authStore is the controller of a neuron in getIdentityOfControllerByNeuronId
* Rename NotAuthorizedError to NotAuthorizedNeuronError to customize the error message to neurons.
* getAccountIdentityByPrincipal does not throw an error when no account, instead returns null.
* Add tests for getIdentityOfControllerByNeuronId.
* Add test case for getAccountIdentityByPrincipal

L2-665: Improve getting neuron identity

---

frontend/svelte/src/lib/services/accounts.services.ts
frontend/svelte/src/lib/utils/accounts.utils.ts
frontend/svelte/src/routes/Wallet.svelte
frontend/svelte/src/tests/lib/services/accounts.services.spec.ts
frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts

Follow-up of #957 - refactor `getAccountFromStore` to not access the store directly but gets it as parameter
- `getAccountFromStore` function's declaration

refactor: get account from store path store

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/types/canister-detail.context.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/CanisterDetail.svelte
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/mocks/canisters.mock.ts
frontend/svelte/src/tests/routes/CanisterDetail.spec.ts

User gets a message when he or she can't view the canister details.
* Add an errorDetailsKey to SelectCanisterDetailsStore.
* Use erroDetailsKey to display an error message in Canister Details route.
* getCanisterDetails throws the same as the canister api getCanisterDetails.
* Test that service getCanisterDetails throws.
* Test that CanisterDetails route shows error message if user is not the controller.

L2-618: Message when user not canister controller

---

frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/canisters/ic-management/converters.ts
frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.types.ts
frontend/svelte/src/lib/components/canister_details/AddCanisterControllerButton.svelte
frontend/svelte/src/lib/components/canister_details/ControllersCard.svelte
frontend/svelte/src/lib/components/canister_details/NewControllerReview.svelte
frontend/svelte/src/lib/components/ui/PrincipalInput.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/canisters/AddControllerModal.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/stores/busy.store.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/CanisterDetail.svelte
frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
frontend/svelte/src/tests/lib/canisters/ic-management.canister.spec.ts
frontend/svelte/src/tests/lib/components/canister_details/ControllersCard.spec.ts
frontend/svelte/src/tests/lib/components/canister_details/ControllersCardTest.svelte
frontend/svelte/src/tests/lib/modals/canisters/AddControllerModal.spec.ts
frontend/svelte/src/tests/lib/modals/canisters/AddControllerModalTest.svelte
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/mocks/canisters.mock.ts

User can add controllers to canisters.
* New IC Management Canister method "updateSettings".
* New Canister api function: "updateSettings".
* New Canister services: "updateSettings" and "addController".
* AddControllersCard uses new canister service to add a controller.
* ControllersCard and NewControllerReview use the canister details context to get the data instead of props.
* Test for new IC Management method.
* Test for new canister api.
* Test for new canister services.
* Extend test case to add a new controller.

L2-600: Add Controller Part 2

---

frontend/svelte/src/lib/canisters/cmc/cmc.canister.ts
frontend/svelte/src/lib/canisters/cmc/cmc.constants.ts
frontend/svelte/src/lib/components/canisters/ConfirmCyclesCanister.svelte
frontend/svelte/src/lib/components/canisters/SelectCyclesCanister.svelte
frontend/svelte/src/lib/modals/canisters/AddCyclesModal.svelte
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/utils/icp.utils.ts
frontend/svelte/src/tests/lib/canisters/cmc.canister.spec.ts
frontend/svelte/src/tests/lib/components/canisters/SelectCyclesCanister.spec.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts
frontend/svelte/src/tests/lib/utils/icp.utils.spec.ts

Simplify the code of the conversion of ICPs to TCycles and back.
* Remove all calculations along the way.
* Utils gets the same exchange rate that CMC sends.
* Rename "ratio" to "exchangeRate".

L2-676: Simplify icp to tcycles conversion

---

frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.errors.ts
frontend/svelte/src/lib/components/canisters/AttachCanister.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/error.utils.ts
frontend/svelte/src/tests/lib/canisters/nns-dapp.canister.spec.ts

User has appropriate feedback when something goes wrong in the Canisters tab.
* nns-dapp canister throws different error classes depending on response when attaching or detaching canisters.
* canister services check errors in the catch and show errors accordingly.
* Test that nns-dapp canister throws errors according to response.

L2-615: Manage Canister Errors

---

frontend/svelte/src/lib/services/seed-neurons.services.ts

Fix lint warning:
> Hint: 'await' has no effect on the type of this expression. 
>    const identity = await getLedgerIdentityProxy(hardwareWallet?.identifier);
>    const governance = await GenesisTokenCanister.create({
>      agent: await createAgent({ identity, host: HOST }),
>    });

fix: 'await' has no effect on the type of this expression

---

frontend/svelte/src/lib/constants/neurons.constants.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/ledger.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/error.utils.ts
frontend/svelte/src/lib/utils/utils.ts
frontend/svelte/src/tests/lib/services/ledger.services.spec.ts
frontend/svelte/src/tests/lib/utils/utils.spec.ts
frontend/svelte/src/tests/mocks/ledger.identity.mock.ts

User sees proper error when merging maturity of a HW neuron with old version.
* Add ledger service "assertLedgerVersion" that throws if Ledger version is less than minVersion.
* Use ledger service in "mergeMaturity" service.
* New util "smallerVersion" that returns boolean comparing two versions.
* Manage LedgerErrorMessage type errors separately in error mapping.
* Test for new util.
* Test for new ledger service.

L2-679: Improve merge maturity error with HW

---

frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
frontend/svelte/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.svelte
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/lib/utils/proposals.utils.ts
frontend/svelte/src/tests/lib/components/proposal-detail/VotesCard.spec.ts
frontend/svelte/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
frontend/svelte/src/tests/lib/utils/proposals.utils.spec.ts

User sees voting power of the proposal ballot instead of neuron voting power in the Proposal Detail.
* Pass the proposal to the util "selectedNeuronsVotingPower".
* Add prop proposalInfo to VotingNeuronsSelect.
* New util "getVotingBallot".
* In VotesCard, use the voting power from the ballot instead of neuron's one.
* In VotingNeuronsSelect, use the voting power from the ballot instead of neuron's one.
* Fix broken tests after changes.
* New test for getVotingBallot.
* Adapt tests to check the voting power of the ballots, not the neurons.

L2-685: Voting Power from proposal's ballot

---

README.md
deploy.sh
e2e-tests/specs/redirect-to-legacy.e2e.ts
frontend/dart/lib/data/env.dart
frontend/dart/web/index.html
frontend/svelte/src/lib/constants/routes.constants.ts

We would like to release the svelte version of the canisters tab.
* Update REDIRECT_TO_LEGACY so that prod and staging use the svelte version of the canisters tab.
* Update documentation.
* Enable testnet population for "prod" builds; this requires svelte.
- See CI.
- Also, I will test this with the redirect e2e test against a deployment to the nns-dapp testnet.....  Testing...done. OK

Move the canisters tab to svelte

---

frontend/svelte/src/lib/components/common/HeadlessLayout.svelte

"Neuron" detail page overflows again on mobile devices. Therefore we should redo the `overflow-x` on the headless layout even though we have improved the positioned of the tooltip that leads to this styling issue.

style: redo overflow-x on headless layout

---

frontend/svelte/src/lib/components/accounts/WalletSummary.svelte
frontend/svelte/src/lib/components/ui/Tooltip.svelte

Tooltip `display` property breaks list of cards ("Merge neurons") width if displayed
- make `display` property optional

fix: tooltip breaking list of cards width

---

frontend/svelte/src/routes/Canisters.svelte

"No transactions" is displayed "left" aligned therefore I think we can also align "No canisters" that way too.
- align text left

style: align no canisters left

---

frontend/svelte/src/lib/components/canister-detail/DetachCanisterButton.svelte
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/routes/CanisterDetail.svelte
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts

User should not see error notifications after detaching a canister successfully.
* "routePathCanisterId" checks whether the path is a Canister Detail path.
* Show error message of canister not found in CanisterDetails only if there was never a canister before.
* Add test case in "routePathCanisterId".

L2-692: Detach canister remove extra notifications

---

frontend/svelte/src/lib/api/ledger.api.ts
frontend/svelte/src/lib/modals/neurons/VotingHistoryModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/tests/App.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

Do not check neuron balance every time we load a neuron.
* Remove logic to check the neuron balance and claim the neuron if it doesn't match the stake.
* Call claimOrRefresh only on "reloadNeuron".
* Remove test cases.
* Add test case for reloadNeuron.

L2-718: Do not check neuron balance always

---

frontend/svelte/package-lock.json

```
ejs  <3.1.7
Severity: critical
Template injection in ejs - https://github.com/advisories/GHSA-phwq-j96m-2c2q
node_modules/ejs
1 critical severity vulnerability
To address all issues, run:
npm audit fix
```
* `npm audit --fix` which:
* Updated ejs from 3.1.6 to 3.1.8
* Updated `node_modules/async` from 0.9.2 to 3.2.4
* Updated `node_modules/filelist` from 1.0.2 to 1.0.4
* Updated/replaced transitive dependencies.

Update vulnerable dependencies

---

frontend/svelte/package-lock.json
frontend/svelte/src/lib/api/ledger.api.ts
frontend/svelte/src/lib/services/canisters.services.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/tests/lib/services/canisters.services.spec.ts

nns-js uses ledger candid interface by default. When interacting with hardware wallet, we want to keep using protobuf.
* Upgrade nns-js
* Pass "hardwareWallet" param when creating the LedgerCanister.
* Get identity based on the account when creating and topping up canisters.
No new tests.

L2-715: Ledger use candid

---

frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/utils/utils.ts
frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
frontend/svelte/src/tests/lib/utils/utils.spec.ts

CMC notify calls might fail because the nns dapp canister also makes the calls. Ignore the error if it fails because of that.
* Poll notifyCreateCanister or notifyTopUpCanister from CMCanister in canister api createCanister and topUpCanister.
* Add new util "poll" to poll any function.
* Add test cases in Canister api functions.
* New test for util "poll".

Chore: Handle Multiple Request to CMC

---

frontend/svelte/src/lib/utils/utils.ts

Docs fix
> Hint: JSDoc '@param' tag has name 'currentVersion', but there is no parameter with that name. 
>  * @param minVersion Ex: "1.0.0"
>  * @param currentVersion Ex: "2.0.0"
>  * @returns boolean

docs: fix there is no parameter with that name

---

frontend/svelte/src/lib/api/canisters.api.ts
frontend/svelte/src/lib/api/errors.api.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/types/i18n.d.ts

Errors from polling service in canisters api are translatable.
* New Error type `ApiErrorKey` thrown when polling is exceeded.
No extra tests

L2-721: i18n Canister api errors

---

frontend/svelte/src/App.svelte
frontend/svelte/src/lib/api/ledger.api.ts
frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
frontend/svelte/src/lib/components/accounts/TransactionInfo.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/MergeMaturityButton.svelte
frontend/svelte/src/lib/components/neuron-detail/actions/SplitNeuronButton.svelte
frontend/svelte/src/lib/components/neurons/StakeNeuron.svelte
frontend/svelte/src/lib/constants/icp.constants.ts
frontend/svelte/src/lib/constants/neurons.constants.ts
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/canisters/AddCyclesModal.svelte
frontend/svelte/src/lib/modals/canisters/CreateOrLinkCanisterModal.svelte
frontend/svelte/src/lib/modals/neurons/SplitNeuronModal.svelte
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/services/transaction-fees.services.ts
frontend/svelte/src/lib/stores/transaction-fees.store.ts
frontend/svelte/src/lib/utils/icp.utils.ts
frontend/svelte/src/lib/utils/neuron.utils.ts
frontend/svelte/src/tests/lib/api/canisters.api.spec.ts
frontend/svelte/src/tests/lib/api/ledger.api.spec.ts
frontend/svelte/src/tests/lib/components/accounts/NewTransactionAmount.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts
frontend/svelte/src/tests/lib/services/transaction-fee.services.spec.ts
frontend/svelte/src/tests/lib/stores/transaction-fees.store.spec.ts
frontend/svelte/src/tests/lib/utils/icp.utils.spec.ts
frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
frontend/svelte/src/tests/lib/utils/utils.spec.ts

Get the transaction fee from the Ledger Canister instead of using a hardcoded one.
* New store for transaction fees.
* New transactionFee services to get the fee from the Ledger Canister
* New ledger api function to get the transaction fee.
* Transform some neurons constants into neuron utils.
* Read the transaction fee from the neuron utils instead of constant in components.
* Test for the new store.
* Test for the new service.
* Test for the new ledger api function.
* Update broken tests after changes.

L2-716: Load transaction fee from Ledger Canister

---

frontend/svelte/src/lib/components/canisters/ConfirmCyclesCanister.svelte

Prevent cycles conversion text to overflow on small screen.

style: align canister review cycles on small screen

---

frontend/svelte/src/routes/Neurons.svelte

Apply width to neuron footer tooltip button as any footer button.
- custom style in neuron page (I thought about making it global but it seems like an exception to use a tooltip in footer button)

style: neuron footer tooltip button width

---

frontend/svelte/src/lib/services/auth.services.ts
frontend/svelte/src/tests/lib/services/auth.services.spec.ts

UI has become glitchy on signout.
- There might be cleaner way to solve this, like detecting through events the next re-rendering of the auth page and triggering the reload only when it happens but, meanwhile, this small `timeout` seems to be the pragmatic solution.
- tried `await tick()` but it did not work out
- reload window after 50ms on signout instead of instant
Glitch:
Ok:

fix: glitchy ui on signout

---

frontend/svelte/src/lib/components/accounts/NewTransactionReview.svelte
frontend/svelte/src/lib/components/ui/BusyScreen.svelte

Users using hardware wallet want to be able to confirm what's on the device and what's on the screen.
* Reduce opacity of the BusyScreen.
* Add hardware wallet message on busy screen for new transactions.

Fix: Opacity of busy screen

---

frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/routes/NeuronDetail.svelte
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

Fix issue when user tries to navigate out of the neurons detail page with the menu.
* Skip checks in the NeuronDetail page when route changes but it's not a neuron detail page.
* Add extra check when getting the neuron id from the path in "routePathNeuronId".
* Add test cases in routePathNeuronId.

Fix: Navigation issue on Neuron Detail

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/identities/ledger.identity.ts
frontend/svelte/src/lib/types/i18n.d.ts

Users that try to connect a hardware wallet with Firefox should know why it's failing.
* Check the error thrown when trying to connect to the ledger device and change the message key for the error.

L2-738: Improve FF error message with HW

---

frontend/svelte/src/lib/services/auth.services.ts
frontend/svelte/src/routes/Auth.svelte

Follow-up of #1020. Adding a fixed background and removing the lazy loading of the images (that is loaded anyway) seems to make the signout less glitchy for the eyes.
Still has to be tested on mobile devices.
- remove `loading=lazy` for the image as it is always loaded
- add a scree background behind login screen
- remove timeout for reload

fix: glitchy signout

---

frontend/svelte/env.config.mjs
frontend/svelte/jest-setup.ts
frontend/svelte/rollup.config.js
frontend/svelte/src/App.svelte
frontend/svelte/src/lib/constants/routes.constants.ts
frontend/svelte/src/routes/Accounts.svelte
frontend/svelte/src/routes/CanisterDetail.svelte
frontend/svelte/src/routes/Canisters.svelte
frontend/svelte/src/routes/NeuronDetail.svelte
frontend/svelte/src/routes/Neurons.svelte
frontend/svelte/src/routes/ProposalDetail.svelte
frontend/svelte/src/routes/Proposals.svelte
frontend/svelte/src/routes/Wallet.svelte

Remove redirections from svelte to flutter.
* Remove usage of `REDIRECT_TO_LEGACY` in svelte app.
* Remove all `SHOW_XXX` constants.
* Remove all checks with `SHOW_XXX` onMount to redirect to flutter.

L2-727: Remove redirections to Flutter

---

frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalActions.svelte
frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalDetailCard.svelte
frontend/svelte/src/tests/lib/components/proposal-detail/ProposalDetailCard/ProposalActions.spec.ts

Handle proposal id that can be undefined. Once properly typed, following lint error is thrown:
> Error: Type 'bigint | undefined' is not assignable to type 'bigint'.
>  Type 'undefined' is not assignable to type 'bigint'. (ts)
>
>  <ProposalActions proposalId={id} {proposal} />
> </CardInfo>
- properly type variable
- handle undefined value

fix: proposal id can be undefined

---

frontend/svelte/src/lib/api/ledger.api.ts

Return type for `transactionFee` feature was not set.
> Hint: JSDoc types may be moved to TypeScript types. 
>  */
> export const transactionFee = async ({ identity }: { identity: Identity }) => {
>   logWithTimestamp(`Getting transaction fee call...`);
- set return type
- add missing jsdoc

chore: set missing return type

---

frontend/svelte/src/lib/components/sns-project-detail/ProjectInfoSection.svelte
frontend/svelte/src/lib/components/sns-project-detail/ProjectStatusSection.svelte
frontend/svelte/src/lib/components/ui/KeyValuePair.svelte
frontend/svelte/src/lib/components/ui/ProgressBar.svelte
frontend/svelte/src/lib/components/ui/TwoColumns.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/routes/SNSProjectDetail.svelte
frontend/svelte/src/tests/lib/components/sns-project-detail/ProjectStatusSection.spec.ts
frontend/svelte/src/tests/lib/components/ui/ProgressBar.spec.ts
frontend/svelte/src/tests/lib/components/ui/ProgressBarTest.svelte
frontend/svelte/src/tests/routes/SNSProjectDetail.spec.ts

User can see the project commitment status in the project detail page.
* Implement the ProjectStatusSection UI.
* The second part of TwoColumns takes over all the remaining space.
* Expand the SNSProjectDetail to have the height of at least the whole screen.
* New UI Component: ProgressBar. NOT IMPLEMENTED YET, just setup.
* Setup test for ProgressBar.
* Setup test for ProjectStatusSection.
* Add test case in SNSProjectDetail.

L2-734: SNS Project Detail Status UI

---

frontend/svelte/src/lib/components/header/Banner.svelte

Following our change in the layout, if the dev banner gets hidden, the spacing isn't removed because Svelte does not remove the style in head.
- instead of `svelte:head` use style property on the document

fix: hide dev banner

---

frontend/svelte/src/lib/components/ui/Tooltip.svelte

Tooltip is displayed with an offset if menu is open.
- instead of using `main` width, consider `window` width minus the `scrollbar` width
Issue:
Solution:

style: tooltip displayed with offset if menu open

---

frontend/svelte/src/lib/components/sns-launchpad/SNSProjectCard.svelte
frontend/svelte/src/lib/components/sns-project-detail/CommitmentProgressBar.svelte
frontend/svelte/src/lib/components/sns-project-detail/ProjectInfoSection.svelte
frontend/svelte/src/lib/components/sns-project-detail/ProjectStatusSection.svelte
frontend/svelte/src/lib/components/ui/Logo.svelte
frontend/svelte/src/lib/components/ui/ProgressBar.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/services/sns.mock.ts
frontend/svelte/src/lib/services/sns.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/lib/utils/sns.utils.ts
frontend/svelte/src/routes/SNSProjectDetail.svelte
frontend/svelte/src/tests/lib/components/sns-launchpad/SNSProject.spec.ts
frontend/svelte/src/tests/lib/components/sns-project-detail/ProjectInfoSection.spec.ts
frontend/svelte/src/tests/lib/components/sns-project-detail/ProjectStatusSection.spec.ts
frontend/svelte/src/tests/mocks/sns-projects.mock.ts
frontend/svelte/src/tests/routes/SNSProjectDetail.spec.ts

User sees the actual project (but still mocked) details instead of hardcoded data.
* Link from launchpad to project details.
* Load project details in SnsProjectDetail page.
* Read project from store in SnsProjectDetail.
* Add data props in ProjectStatusSection and ProjectInfoSection.
* Fix tests with updated changes.

L2-763: Mock data sns project detail

---

frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
frontend/svelte/src/lib/components/sns-project-detail/ProjectInfoSection.svelte
frontend/svelte/src/lib/components/sns-project-detail/ProjectStatusSection.svelte
frontend/svelte/src/lib/components/ui/CardBlock.svelte
frontend/svelte/src/lib/components/ui/Collapsible.svelte
frontend/svelte/src/lib/components/ui/InfoContextKey.svelte
frontend/svelte/src/lib/components/ui/KeyValuePair.svelte
frontend/svelte/src/tests/lib/components/ui/Collapsible.spec.ts
frontend/svelte/src/tests/lib/components/ui/InfoContextKey.spec.ts
frontend/svelte/src/tests/lib/components/ui/InfoContextKeyTest.svelte
frontend/svelte/src/tests/lib/components/ui/KeyValuePair.spec.ts
frontend/svelte/src/tests/lib/components/ui/KeyValuePairTest.svelte

User can see the information on max and min commitment items when clicking on them.
* Changes in Collapsible component: add "none" to the iconSize prop values. Which hides the button.
* Move the extra clickable space to the CardBlock.
* Use the Collapsible in the ProjectInfoSection.
* Remove info icon from KeyValuePair.
* New InfoContextKey component that adds info icon and makes content collapsible.
* Add proper test case to Collapsible component.
* Text for new component InfoContextKey.
* Remove test case for KeyValuePair.

L2-735: Use Collapsible component in ProjectInfoSection

---

deploy.sh

When deploying, the sns version needs to match the canisters or else there can be hard-to-diagnose failures.
The matching `sns` binary is already downloaded, it just needs to be called explicitly in `deploy.sh`, rather than picking up whichever `sns` is in `PATH`.
* Use the `sns` from the ic artifacts directory in `deploy.sh`
* I have run `./deploy.sh --sns testnet` and it worked.  It still deploys "old" canisters from a week ago but that is orthogonal.

Use the SNS version matching the canisters

---

frontend/svelte/src/lib/components/neuron-detail/actions/MergeMaturityButton.svelte

User should not see merge maturity enabled without maturity.
* Update enable or disable with neuron props changes.

L2-803: Bug, Merge maturity enabled w/out maturity

---

frontend/svelte/src/lib/components/accounts/SelectAccountDropdown.svelte
frontend/svelte/src/lib/components/project-detail/Participate.svelte
frontend/svelte/src/lib/components/project-detail/ParticipateScreen.svelte
frontend/svelte/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/svelte/src/lib/components/project-detail/ProjectStatusSection.svelte
frontend/svelte/src/lib/components/project-detail/ReviewParticipate.svelte
frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/modals/sns/ParticipateSwapModal.svelte
frontend/svelte/src/lib/services/sns.mock.ts
frontend/svelte/src/lib/stores/transaction-fees.store.ts
frontend/svelte/src/lib/themes/button.scss
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
frontend/svelte/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/svelte/src/tests/mocks/sns-projects.mock.ts

User can select an account and enter an amount to participate in a swap.
* New modal ParticipateSwapModal.
* New screens Participate and ReviewParticipate (setup only) used in the modal.
* New button class "secondary".
* Setup of new component "SelectAccountDropdown.
* Add minParticipationCommitment and maxParticipationCommitment to SNS Project mock data.
* Tests for new Modal.
* Add test case in ProjectStatusSection that opens modal.

L2-795: Swap Participation Flow 1 UI

---

frontend/svelte/src/lib/i18n/en.json
frontend/svelte/src/lib/identities/ledger.identity.ts
frontend/svelte/src/lib/services/neurons.services.ts
frontend/svelte/src/lib/types/i18n.d.ts
frontend/svelte/src/tests/lib/services/ledger.services.spec.ts
frontend/svelte/src/tests/lib/services/neurons.services.spec.ts

User error reported showed i18n key instead of the message.
* Add error mapper to catch when staking a neuron.
* Make the error of HW connect more generic. It might happen that the device is not even connected.

L2-815: Fix, ledger Error shows i18n key

---

frontend/svelte/src/lib/components/neuron-detail/actions/JoinCommunityFundCheckbox.svelte

Fix notification message when toggling community fund.
* Set the message before making the call.
* Only messaging changes.

Fix: Error message when toggling community fund

---

scripts/setup

When sns canisters are created via the sns-wasms canister, not dfx, they are no longer added to the `canister_ids.json`.  It is possible to use `idl2json` and `jq` to use the `sns` cli response to populate `canister_ids.json`, and so create  
a better developer experience.  This requires `idl2json` to be available.
* Add code to install idl2json to the setup script
* Installation works on:

Install idl2json

---

frontend/svelte/src/lib/api/sns.api.ts
frontend/svelte/src/lib/components/common/RouteModule.svelte
frontend/svelte/src/lib/components/launchpad/Projects.svelte
frontend/svelte/src/lib/services/sns.services.ts
frontend/svelte/src/lib/stores/projects.store.ts
frontend/svelte/src/lib/themes/themes/dark.scss
frontend/svelte/src/tests/lib/api/sns.api.spec.ts
frontend/svelte/src/tests/lib/components/launchpad/Projects.spec.ts

Added more granular loading state display to improve user experience during the sns data loading (could take some time because of big request quantity)
- initially display a spinner, then the correct amount of project skeleton cards
- fix multiple loading of snsWrappers
- wrappers call should update snsesCountStore
https://user-images.githubusercontent.com/98811342/178949103-e6a685f4-fecb-4e02-a0fd-f00d756121bb.mp4

L2 830 sns summary data loading state

---

deploy.sh

When deploying an sns, the case where there is no existing `canister_ids.json` is not handled yet.  It should be.
* Back up the `canister_ids.json` only if it exists
* If there is no `canister_ids.json`, create one with an empty dictionary.
I have used the code like this: `rm canister_ids.json ; ./deploy.sh --sns small11`.  This part of the deployment worked fine.

Fix: Handle case where canister_ids.json does not exist yet

---

frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
frontend/svelte/src/lib/utils/neuron.utils.ts

Governance canister will be deployed first with the new spawning functionality. Until the new nns-dapp is release, the spawning neurons break the UI and show a blank page.
Fix the error and show only 0 ICP and that's it. At this point, we can't use the new state nor the new property. We just need to avoid the blank page.
* stateInfo can be undefined for unknown states.
* Do not show state information if stateInfo is undefined.
* Type changes only

Fix: Do not fail spawning neurons

---

dfx.json

It is sometimes useful to have yet another small temporary testnet.  3 should really be enough though.
* Add `small12` to the list of testnets in `dfx.json`.
See https://qhbym-qaaaa-aaaaa-aaafq-cai.small12.dfinity.network

Add small12

---

deploy.sh
dfx.json
e2e-tests/scripts/nns-canister-download
e2e-tests/scripts/nns-canister.Dockerfile

The SNS now uses a different ledger canister, and the swap canister can now be uploaded.
* Download the new SNS wasm canister in addition to the existing ledger, which is still needed for the NNS.
* Get wasm paths from dfx.json when uploading wasm canisters
* Include the swap canister in the list that is uploaded

Use new ledger

---

e2e-tests/scripts/nns-canister.patch

Cycle minting rate limiting is now applied in the CMC canister.  Creating an SMS is expensive enough that we run into the rate limit quite quickly (although it seems to me that we hit the limit much too quickly - need to check).  If we hit the rate limiter, no more cycles can be minted for an hour, which significantly slows down test deployments, especially if there are bugs and the deployment needs to be repeated.
* Reduce the rate limit time from 1 hour to 2 minutes.  Long enough that we can see that the limit exists but not so long that testnet deployment times are impacted seriously.
* Deleted a CMC patch that we don't need any more.

Make cycles fast

---

frontend/svelte/src/lib/components/ui/Tooltip.svelte

The tooltip is not centered per default on safari because it's parent is for some reason not an inherited block
- set default css value for tooltip parent to block

style: fix tooltip not centered per default in Safari

---

frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/svelte/src/lib/components/launchpad/Projects.svelte
frontend/svelte/src/lib/components/launchpad/Proposals.svelte
frontend/svelte/src/lib/stores/projects.store.ts
frontend/svelte/src/lib/utils/anonymize.utils.ts
frontend/svelte/src/lib/utils/utils.ts
frontend/svelte/src/routes/ProjectDetail.svelte
frontend/svelte/src/tests/lib/utils/utils.spec.ts

To remove confusion, rename `nullable` to `nullish`.
Goal:
- `null` | `undefined` → `nullish` 
- `[]` → `nullable`
Renaming only

refactor: *Nullable -> *Nullish

---

Cargo.lock
rs/Cargo.toml
rs/src/accounts_store.rs
rs/src/accounts_store/tests.rs
rs/src/canisters/ledger.rs
rs/src/ledger_sync.rs
rs/src/proposals.rs

Currently the NNS Dapp is not able to deserialize proposal payloads.
To fix this we need to update the proposal definitions to the latest versions, that is what this PR does.
- Update dependencies on packages contained in the IC repo (https://github.com/dfinity/ic/).
- Add 2 new proposal types (`PrepareCanisterMigration` and `CompleteCanisterMigration`).
- Update the payload definition for `RerouteCanisterRangesPayload` proposals.
- Fix type mismatches due to the ledger canister having recently split its protobuf types into a separate module.
This has been tested by myself, @lmuntaner and @mstrasinskis on the testnet (https://si2b5-pyaaa-aaaaa-aaaja-cai.nnsdapp.dfinity.network/)

Update proposal definitions

---

deploy.sh

`./deploy.sh --delete-canister-ids` does not work correctly.  Given this input:
```
{
"__Candid_UI": {
"small06": "qaa6y-5yaaa-aaaaa-aaafa-cai",
"small11": "qaa6y-5yaaa-aaaaa-aaafa-cai",
"testnet": "su63m-yyaaa-aaaaa-aaala-cai"
},
"internet_identity": {
"small06": "qjdve-lqaaa-aaaaa-aaaeq-cai",
"small11": "qjdve-lqaaa-aaaaa-aaaeq-cai"
},
"nns-dapp": {
"small06": "sbzkb-zqaaa-aaaaa-aaaiq-cai",
"small11": "qhbym-qaaaa-aaaaa-aaafq-cai",
"testnet": "s55qq-oqaaa-aaaaa-aaakq-cai"
},
"sns_governance": {
"small06": "q4eej-kyaaa-aaaaa-aaaha-cai"
},
"sns_ledger": {
"small06": "q3fc5-haaaa-aaaaa-aaahq-cai"
},
"sns_root": {
"small06": "qvhpv-4qaaa-aaaaa-aaagq-cai"
},
"sns_swap": {
"small06": "sgymv-uiaaa-aaaaa-aaaia-cai"
},
"wasm_canister": {
"small06": "qsgjb-riaaa-aaaaa-aaaga-cai"
}
}
```
if we …

Fix DELETE_CANISTER_IDS

---

frontend/src/lib/components/launchpad/Proposals.svelte
frontend/src/lib/stores/projects.store.ts
frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
frontend/src/tests/lib/stores/projects.store.spec.ts

Display only `state=open` SNS proposals on the launchpad page
- update store logic
- rename store
- updated according to the new logic

Filter sns proposals by open status

---

frontend/src/lib/constants/identity.constants.ts
frontend/src/lib/stores/auth.store.ts

As NNS-dapp observes the local storage and sync the delegation status if anything changes it leads to some UX issues / quirks with the new idle manager of agent-js. Until we got time to implement it properly we decided to disable it.
Session duration of 30min, sync of the auth on storage change cronjob that verifies the delegation validity and warning about automatic logout are not affected by this PR - remains the same as they are since months. 
- disable idle manager of auth client
- extract session duration to a constant

feat: disable auth idle manager

---

frontend/src/lib/components/accounts/SelectAccount.svelte
frontend/src/lib/components/canisters/ConfirmCyclesCanister.svelte
frontend/src/lib/components/canisters/SelectCyclesCanister.svelte
frontend/src/lib/modals/canisters/AddCyclesModal.svelte
frontend/src/tests/lib/modals/canisters/AddCyclesModal.spec.ts

User is able to use secondary buttons to go back in the Add Cycles flow.
* Listen for the "nnsBack" event in the AddCyclesModal.
* Add test for the specific fix added here.

Fix: Back buttons working in add cycles flow

---

deploy.sh
dfx.json

For demos, and also for providing stable sns-wasm canister IDs, it is desirable to deploy the sns-wasm canister by itself without creating an SNS.
* Separate wasm canister deployment out into a separate step, with a separate flag.
* Note: If an SNS is requested and there is no wasm canister, one will be deployed even without the new explicit `--sns-wasm`, so existing scripts will not break on account of the new flag.
* Used to deploy small12 - with a small hiccup with the II canister IDs.  Added a fix (deleting unnecessary configuration) to this PR.
* Deployed to small06 repeatedly until I observed no usability or functionality issues.

Deploy wasm canister only

---

frontend/package-lock.json
frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
frontend/src/lib/components/project-detail/ProjectCommitment.svelte
frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
frontend/src/lib/services/sns.services.ts
frontend/src/lib/types/sns.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/components/launchpad/ProjectCardSwapInfo.spec.ts
frontend/src/tests/mocks/sns-projects.mock.ts

User can see whether he or she is participating in a decentralized sale.
* Change myCommitment prop type to SnsSwapBuyerState in SnsSwapCommitment
* Use new sns method getUserCommitment in the querySnsSwapCommitment sns api instead of mocked data.
* Upgrade sns-js
* Add test for querySnsSwapCommitment sns api function.
* Fix broken test after type change.

L2-888: Fetch user commitment

---

frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/project-detail/ReviewParticipate.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns.services.ts
frontend/src/lib/types/sns.query.ts
frontend/src/lib/types/sns.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts
frontend/src/tests/mocks/sns-projects.mock.ts

User can see the account where ICP is transferred when participating in a swap.
User participates in a Decentralized Sale, not in a swap.
* Change Swap reference to Decentralized Sale in user facing communication.
* New sns api function querySwapCanisterAccount.
* Use new sns api function when participating.
* New sns service to get the account which uses new sns api querySwapCanisterAccount.
* Use new sns service in the ReviewParticipate component.
* Fix broken test.
* New test for new sns api function.
* New test for new sns service function

L2-836 and L2-891: Add title swap and account

---

frontend/package-lock.json

Bump sns-js which contains the renaming of the canister with prefix `Sns`. Because we use the wrapper this needs no changes in nns-dapp.
- bump sns-js nightly

build: bump sns-js

---

deploy.sh

After redeploying a testnet, all wallet canisters are gone.  This is correct and expected, however if there are wallets in the user's config, they will fail to work with a confusing message.  There is  already a command that cleans local user state, for use after deploying a testnet, however it only deleted the wallet for one identity.  Now that we use several identities, that is no longer enough.
* `--delete` now deletes the wallets for a network from all identities.
I have run this and examined the wallet files.

Delete the network for all IDs

---

frontend/src/lib/proxy/sns.services.proxy.ts
frontend/src/lib/services/app.services.ts

When user access the login screen, the JavaScript code related to Sns should not be loaded until he/she sign-in.
- lazy load sns services initialization
Before PR:
After PR:

feat: lazy load sns at boot time

---

frontend/package-lock.json
frontend/package.json

Bump to the last nightly version of `sns-js` that requires `agent-js` as a peer dependencies.
`nns-js` cannot be upgraded as well. It first needs PR https://github.com/dfinity/ic-js/pull/162 because otherwise the `jest` test suite won't run.
- bump `sns-js` nightly
- add mandatory `agent-js` dependencies to dependencies
- clean up `package-lock` by removing local path (`../../../ic-js/...`) added for development purpose

build: bump sns nightly with peer agent-js

---

deploy.sh
dfx.json

The SNS has a new flag to prevent uploading wasms to the wasms canister.  We need to set it to false for testing.
* Bump IC
* Set the `sns-wasm` canister `access_controls_enabled` to `false`.
I have deployed small12 with this change.

chore: Bump IC to the latest version

---

frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

Show the sns neuron id encoded in hex.
* Implement the getSnsNeuronId like they do in the governance canister to display the neuron id.
* Updated test for getSnsNeuronId

L2-902: Sns Neuron Id Display

---

frontend/package-lock.json

We couldn't bump nns-js nightly yesterday because the google-protobuf was breaking the tests. As it was patched yesterday, this bump finally introduces nns-js that has peer dependencies on agent-js.
sns-js bumped at the same time but no changes there.

build: bump nns-js (update google-protobuf) and sns-js

---

frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/src/lib/components/project-detail/ReviewParticipate.svelte
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/lib/types/project-detail.context.ts
frontend/src/lib/types/sns.query.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/routes/ProjectDetail.svelte
frontend/src/tests/lib/components/launchpad/Projects.spec.ts
frontend/src/tests/lib/components/project-detail/ProjectInfoSection.spec.ts
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/stores/projects.store.spec.ts
frontend/src/tests/lib/stores/sns.store.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts
frontend/src/tests/mocks/sns-response.mock.ts
frontend/src/tests/routes/ProjectDetail.spec.ts

Issues:
- because we moved away from `currentCommitment` to `derived` information (#1196), the "overall current commitment" information was not updated anymore after user participate to a swap
- we have moved the loading of the sns on the app scale (#1172) but the project detail was still loading a particular sns if directly accessed. as a result the same sns project could have been queried twice (actually four times, 2 query calls, 2 update calls)
Solution:
- query sns summary and swap state after user participate to swap and update the root store that contains the fetched sns data from the backend - the one store that is the source for all derived store
- do not (re)load particular sns when the detail page is accessed but use the global store which already load these information
- both …

feat: reload sns data after participate swap & use global data for detail page

---

frontend/src/App.svelte
frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/common/RouteModule.svelte
frontend/src/lib/constants/routes.constants.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/sns-neurons.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/app-path.utils.ts
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/lib/utils/utils.ts
frontend/src/routes/SnsNeuronDetail.svelte
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts
frontend/src/tests/lib/utils/app-path.utils.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
frontend/src/tests/lib/utils/utils.spec.ts
frontend/src/tests/routes/SnsNeuronDetail.spec.ts

Setup the SNS Neuron Detail page and connect it to the SNS governance canister.
* New route SnsNeuronDetail
* New AppPath SnsNeuronDetail which means adding it to a few helpers.
* New utils to interact with the new path: routePathSnsNeuronId, routePathSnsNeuronCanisterId and getThirdLastPathDetail
* New sns neuron service to get neuron details.
* New sns api to get the neuron data.
* Test the new route.
* Test the new utils.
* Test the new sns api function.
* Test the new sns neuron service.

L2-865 and L2-868: SNS Neuron detail page setup

---

dfx.json

If a remote canister Id is specified, the canister is not deployed.
- Don't specify the wasm canister ID on small11
- deploying...

Remove remote canister ID for small11

---

frontend/src/lib/i18n/en.json

There is no "agreement" therefore the confirmation to participate to a decentralized sale should display the act of proceeding. 
- update i18n label

feat: update label to replace "agree" with "proceed" as there is no agreement

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/launchpad/ProjectCard.svelte
frontend/src/lib/components/neurons/SelectProjectDropdown.svelte
frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/src/lib/components/project-detail/ReviewParticipate.svelte
frontend/src/lib/components/ui/Logo.svelte
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/sns-neurons.store.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/lib/types/sns.query.ts
frontend/src/lib/types/sns.ts
frontend/src/lib/utils/dev.utils.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/routes/ProjectDetail.svelte
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts
frontend/src/tests/lib/components/neurons/SelectProjectDropdown.spec.ts
frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
frontend/src/tests/lib/components/project-detail/ProjectInfoSection.spec.ts
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/lib/stores/sns.store.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts
frontend/src/tests/mocks/sns-projects.mock.ts
frontend/src/tests/mocks/sns-response.mock.ts
frontend/src/tests/mocks/sns.api.mock.ts

Load sns project (title, description, etc.) and token (name and symbol) metadata from backend.
At least for MVP, these information are mandatory. If not provided, then the corresponding project will be filter from NNS-dapp. This for code simplification and because users need information to invest in projects they trust.
Corresponding `sns-js` PR is https://github.com/dfinity/ic-js/pull/167
#1211 👉 This PR 👉 main
- rename api `querySnsSummaries` to `queryAllSnsMetadata` and effectively implement backend call
- update sns store to contains query metadata instead of mock summaries
- add effective type nns-dapp will use for token (name and symbol) and project (title, etc.) metadata
- update `sns.utils` to filter and map mandatory data from the backend to data that can be used in the derived …

feat: load sns project and token metadata from backend

---

frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
frontend/src/lib/components/ui/Copy.svelte
frontend/src/lib/components/ui/Hash.svelte
frontend/src/lib/components/ui/Identifier.svelte
frontend/src/lib/components/ui/ShortenMiddleEllipsis.svelte
frontend/src/lib/components/ui/Tooltip.svelte
frontend/src/lib/utils/format.utils.ts
frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts
frontend/src/tests/lib/utils/format.utils.spec.ts

Improve the display of sns neuron id.
* New component ShortenMiddleEllipsis that shortens and adds tooltip with all the text.
* New format util that shortens text.
* Use new ShortenMiddleEllipsis in SNSNeuronCard.
* Add the copy icon and functoinality in the SNS Neuron Card for the id.
* Test new format util.
* Fix broken SNSNeuronCard test.

L2-905: Improve Neuron Id Display

---

rs/src/assets.rs

Add font `woff2` to the list of supported mime type.
Found the mime type `font/woff2` mentioned in various discussion on SO and also in this link: https://www.iana.org/assignments/media-types/media-types.xhtml#font
- add response mime type `font/woff2` to the asset canister

feat: woff2 mime type support

---

frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/busy.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts

User is able to remove a hotkey in an SNS neuron.
* Add sns api function removeNeuronPermissions.
* Add sns neuron service removeHotkey which uses removeNeuronPermissions.
* Use new sns neuron service in SnsNeuronHotkeysCard.
* Test new case in SnsNeuronHotkeysCard.
* Test new sns neuron service
* Test new sns api function.

L2-705: SNS Remove Hotkey

---

frontend/src/lib/components/launchpad/ProjectCard.svelte

Clamp project title to 2 lines and description to 6 lines in launchpad. Align logo top. Developed with Mischa.
- clamp style for title and desc
- align logo top

style: clamp project title and description to x lines

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
frontend/src/lib/components/sns-neuron-detail/actions/AddSnsHotkeyButton.svelte
frontend/src/lib/modals/sns/AddSnsHotkeyModal.svelte
frontend/src/lib/types/sns-neuron-detail.context.ts
frontend/src/routes/SnsNeuronDetail.svelte
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/actions/AddSnsHotkeyButton.spec.ts
frontend/src/tests/lib/modals/sns/AddSnsHotkeyModal.spec.ts
frontend/src/tests/mocks/context-wrapper.mock.ts

User sees new neuron details after adding or removing hotkeys.
* Add context in the SnsNeuronDetail "SelectedSnsNeuronContext".
* Children components of SnsNeuronDetail read from context instead of relying on props.
* A function to reload the neuron is added in the SelectedSnsNeuronContext.
* Reload sns neuron is used after successfully removing or adding hotkeys.
* Fix and change test components.
* Add check that the reload function is called after adding and removing hotkey.

L2-914: Sync neuron after hotkey mgt

---

frontend/src/lib/components/neurons/NeuronCard.svelte
frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

User can easily identify SNS neurons managed by hotkeys.
* New sns neuron util isHotkeyControllable that returns true if neuron is hotkey.
* Use new util in SnsNeuronCard.
* Add test case in SnsNeuronCard.
* Test new sns neuron util.

L2-899: Add Hotey label to SNS Neuron Card

---

config.sh
deploy.sh
dfx.json
scripts/sns/wasm_canister/list_deployed_snses

Governance canisters are listed upstream [here](https://github.com/dfinity/ic/blob/master/rs/nns/dfx.json) as governance, ledger and so on.  Per the draft SNS deployment spec, nns governance canisters should be imported with the `nns-` prefix, chosen to be minimally disruptive with the existing use of `nns-governance`.  However the wasm canister in the nns-dapp dfx file does not match this pattern
- Rename `wasm_canister` to `nns-` + `sns-wasm` == `nns-sns-wasm`
See CI.  This is not expected to break any code but MAY break some demos.

Consistent wasm canister name

---

frontend/src/lib/components/project-detail/ParticipateScreen.svelte
frontend/src/lib/components/project-detail/ReviewParticipate.svelte
frontend/src/lib/components/ui/AmountInput.svelte
frontend/src/lib/components/ui/InputWithError.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/services/canisters.services.ts
frontend/src/lib/services/neurons.services.ts
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/projects.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/types/ledger.errors.ts
frontend/src/lib/utils/accounts.utils.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/stores/projects.store.spec.ts
frontend/src/tests/lib/utils/accounts.utils.spec.ts
frontend/src/tests/lib/utils/projects.utils.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts
frontend/src/tests/mocks/sns-projects.mock.ts

Avoid sale participation that won't succeed.
* New sns util validParticipation.
* Use new util in sns service "participate".
* Check selected account balance with amount inline.
* New account util that raises error if account doesn't have enough balance.
* Use new account util in stake neuron service.
* Add test for the new sns util validParticipation.
* Add test cases for sns service.
* Test for new accout util.
* Add test case when staking neurons.

L2-919: Manage Errors In Sale Participation

---

frontend/src/lib/services/sns.services.ts
frontend/src/tests/lib/services/sns.services.spec.ts

Account balance is updated after participating in a decentralized sale.
* Call `syncAccounts` in sns service participate.
* Add expected new call.

L2-933: Sync accounts after participating in Sale

---

scripts/testnet-set-canister-ids

The script that saves canister_ids fails if they haven't changed.  This isn't wanted.
- If there have been no changes, don't commit the changes.
Verify that if there are no changes, everything works:
```
max@sinkpad:~/dfn/nns-dapp/branches/no-change-ok (14:02)$ git show origin/testnets:testnets/canister_ids.json > canister_ids.json
max@sinkpad:~/dfn/nns-dapp/branches/no-change-ok (14:11)$ bash -x scripts/testnet-set-canister-ids
+ set -euo pipefail
+ : 'Print help, if applicable...'
+ (( 0 > 0 ))
+ : Get the absolute path
++ realpath canister_ids.json
+ to_add=/home/max/dfn/nns-dapp/branches/no-change-ok/canister_ids.json
+ : Assuming that the testnets worktree already exists:
++ git worktree list --porcelain
++ awk '/^worktree .*branches[/]testnets$/{print $2}'
+ cd …
```

Commit only if there are changes

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
frontend/src/lib/modals/sns/AddSnsHotkeyModal.svelte
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/types/sns-neuron-detail.context.ts
frontend/src/routes/SnsNeuronDetail.svelte
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
frontend/src/tests/lib/modals/sns/AddSnsHotkeyModal.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts

If the user arrived to the sns neuron detail page from the neurons page, the neuron was loaded from the store. Reloading meant to get the same neuron from the store.
That meant that after updating the neuron, we still got the old one.
* Add a "forceFetch" flag to the getSnsNeuron service that forces call to the api.
* Use the new flag after adding or removing hotkeys in sns neurons.
* Change tests to check that the flag is properly set after adding or removing hotkeys.
* Check that the flag calls api instead of retrieving from the store.

Fix: Force sns neuron fetch after hotkey mgt

---

frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/stores/projects.store.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/tests/lib/stores/projects.store.spec.ts
frontend/src/tests/lib/utils/projects.utils.spec.ts

User should not get an error message when selecting NNS project in neurons dropdown.
* Load sns project when selected project store changes, but only if new one is not OWN_CANISTER_ID
* Not applicable.

L2-934: Fix error coming back to NNS neurons

---

dfx.json
frontend/jest-setup.ts
frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/modals/neurons/SpawnNeuronModal.svelte
frontend/src/lib/services/app.services.ts
frontend/src/lib/utils/utils.ts
frontend/src/routes/Neurons.svelte
frontend/src/tests/lib/modals/neurons/SpawnNeuronModal.spec.ts

1. remove `ENABLE_NEW_SPAWN_FEATURE` active in production
2. rename `ENABLE_SNS_NEURONS` to `ENABLE_SNS` because flag is used generally speaking for sns
3. add `VOTING_UI`
- update `dfx.json` and `environment.constant` accordingly
- remove deprecated code in `<SpawnNeuronModal />`

feat: feature flags clean up and new flag

---

frontend/src/lib/components/common/Layout.svelte

The title in the header in light mode does not inherit the original contrasting color we had set.
- use `HeaderTitle` gix-components
Is:
Will be:

style: fix title color

---

frontend/src/lib/components/neurons/NnsNeuronsFooter.svelte

If displayed in a tooltip, the footer button "merge neurons" does not inherit the proper width.
- replace global style with scoped style
Is:
Fixed:

style: fix tooltip footer button width

---

frontend/src/lib/i18n/en.json
frontend/src/lib/services/debug.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/neuron.utils.ts
frontend/src/tests/lib/utils/neuron.utils.spec.ts

Context: A user is the controller of a neuron. The same user adds the principal as hotkey.
Edge case: If the user then removes the hotkey, the neuron disappears.
Added a new flow in the debug store to add the user as a hotkey again.
More info here: https://forum.dfinity.org/t/8-year-locked-neuron-missing-from-neurons-tab/9619/42?u=ielashi
* Add new LogType "ah" in the debug flow that adds the user's principal to a neuron.
* Take care of the edge case in the neuron util is "isHotKeyControllable"
* No tests for the debug flow.
* Test for the edge case added in isHotKeyControllable

Feat: Add hotkey debug flow

---

frontend/src/lib/modals/Modal.svelte

Modal on Android devices are presented behind footer and url bar when used in the browser - i.e. not in standalone
- set a modal max-height of `100%`
- goodie: set the proper modal max-height `-webkit-fill-available` for ios

style: fix modal height on android devices

---

frontend/src/lib/components/project-detail/ReviewParticipate.svelte
frontend/src/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.svelte
frontend/src/lib/utils/html.utils.ts
frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingCard.spec.ts
frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/routes/Accounts.spec.ts

Sanitize proposal title and account identifier for placeholders.
Deployed with https://github.com/dfinity/nns-dapp/releases/tag/proposal-76202
- expose function `sanitizeHTML` with `purify`
- sanitize proposal title and topic for voting card
- sanitize account identifier when participate to a sns sale

fix: sanitize proposal title and account identifier for placeholders

---

frontend/src/lib/components/ic/ICPText.svelte
frontend/src/lib/components/project-detail/ParticipateScreen.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/sns/ParticipateSwapModal.svelte
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/types/project-detail.context.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/routes/ProjectDetail.svelte
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/lib/utils/projects.utils.spec.ts

Improve UI when user increases participation.
Fix also the minimum to participate. If the user has already participated, the increase can be as small as wished.
* Check whether the user is participating in the Participate Modal and change UI slightly.
* New project util currentUserMaxCommitment to calculate the maximum participation allowed for that user for that project.
* commitmentTooSmall util takes into account current commitment.
* Fix a bug in validParticipation when user wanted to participate until max.
* Test new participation and increasing in ParticipateSwapModal
* Test for new util currentUserMaxCommitment
* Add more tests to validParticipation to cover the bug and more test cases.

L2-943: Improve Increase Participation Flow

---

frontend/src/lib/services/sns.services.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/utils/projects.utils.spec.ts

User of the last commitment received an error notification because the notify was failing. The problem is that the backend might be faster to notify than the frontend. That causes the project to change state to Committed and the subsequent notify to fail.
Catch that error specifically and ignore it.
* Check for last commitment notify error in the participateInSwap sns service.
* Export project util commitmentExceedsAmountLeft to be used in participateInSwap.
* Test exported project util commitmentExceedsAmountLeft
* Test the service for the new use case.

L2-956: Ignore last commitment error on notify

---

frontend/src/lib/components/ui/Toast.svelte

Redo max-height for toast content.
Previously height was set on the all toast, I reused same value for the content so that one line still remains displayed in a compact way. Per extension the toast max height is then a bit bigger than before but it's fine in my opinion.
- redo max height but set to toast content

style: redo toast max-height

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/types/sns-neuron-detail.context.ts
frontend/src/routes/SnsNeuronDetail.svelte
frontend/src/tests/routes/SnsNeuronDetail.spec.ts

User should be redirected to neurons if trying to access a wrong sns neuron page.
* Check for valid root canister id and redirect to neurons in SnsNeuronDetail page.
* Add skeleton while loading.
* Add test cases to SnsNeuronDetail test.

L2-921: Manage error sns neuron detail page

---

frontend/src/lib/types/project-detail.context.ts
frontend/src/routes/ProjectDetail.svelte
frontend/src/tests/routes/ProjectDetail.spec.ts

User should be redirected to launchpad when trying to access details of a non-existing project.
* Changes in the ProjectDetail page to manage edge case. Specifically in mapProjectDetail.
* Provide test for not found or wrong canister id in the url of Project Detail.

L2-958: Manage error project not found

---

frontend/package-lock.json
frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/src/lib/components/project-detail/ProjectStatus.svelte
frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
frontend/src/lib/components/proposal-detail/ProposalDetailCard/NnsFunctionDetails.svelte
frontend/src/lib/components/proposal-detail/ProposalDetailCard/ProposalActions.svelte
frontend/src/lib/components/proposal-detail/ProposalDetailCard/ProposalSummary.svelte
frontend/src/lib/components/proposal-detail/ProposalModern.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerDataSection.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerInfoSection.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerPayloadEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalSystemInfoEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalSystemInfoSection.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/date.utils.ts
frontend/src/lib/utils/proposals.utils.ts
frontend/src/tests/lib/components/proposal-detail/ProjectSystemInfoEntry.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProjectSystemInfoSection.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalModern.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerActionsEntry.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerDataSection.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerInfoSection.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerPayloadEntry.spec.ts
frontend/src/tests/lib/utils/date.utils.spec.ts
frontend/src/tests/lib/utils/proposals.utils.spec.ts

Add more system information to proposal detail new UI.
- add timestamps, proposer, status and reward status
- map above dynamic info with `proposal.utils`
- sync description with dashboard
- extract a component to avoid to duplicate `KeyValuePairInfo` and sanitizer code
- new date + time formatter

feat: proposal new UI more system info

---

frontend/scripts/build.index.mjs
frontend/src/index.html

As in II, use a script loader for main script.
- add a script that load `main.js` in `index.html`
- adapt csp accordingly with hashes instead of nonce

feat: script loader

---

frontend/src/index.html

Neat pick from @tmu0 would rather like to have the csp added as first child of the `<head />` tag
- move csp placeholder to first child of `<head />` tag in `index.html`

feat: move csp rules at the top of the <head/>

---

frontend/.eslintrc.js
frontend/scripts/i18n.types.js
frontend/src/lib/utils/dev.utils.ts

Avoid leaving debugging logs in production.
* Add `no-console` to eslint.

Chore: Add no-console rule

---

frontend/jest-setup.ts
frontend/src/index.html
frontend/src/lib/constants/stores.constants.ts
frontend/src/lib/stores/proposals.store.ts
frontend/src/lib/stores/theme.store.ts
frontend/src/lib/stores/writable-stored.ts
frontend/src/lib/utils/theme.utils.ts
frontend/src/routes/Proposals.svelte
frontend/src/tests/lib/stores/writable-stored.spec.ts
frontend/src/tests/lib/utils/theme.utils.spec.ts
frontend/src/tests/mocks/local-storage.mock.ts

Proposals filters are persisted across browser refresh.
* New util to create a store that gets stored in local storage "writableStored".
* Use writableStored in themStore
* Use writableStored in proposalsFiltersStore.
* Add tests for writableStored
* Mock localStorage in jest.

L2-833: Store filters in local storage

---

frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/src/lib/components/project-detail/ProjectStatusSection.svelte

Following the introduction of the last utility classes and improvements to the grid, the "Participate" button and the summary data of the project have a lack of spacing.
- set padding with utility class for grid `.content-cell-details`
is:
will be:

style: fix project info and action spacing

---

dfx.json
frontend/src/lib/stores/auth.store.ts

Long story short: on iOS, click on the "Login" have no effect 👉 user cannot sign-in on iOS with the current development version which uses agent-js `v0.13.x` (mainnet uses currently `v0.12.x` which is fine).
More details and context in related agent-js issue https://github.com/dfinity/agent-js/pull/618
- keep `authClient` object in memory to not call `authClient.create` before `authClient.login` - i.e. avoid any async callback within the same function that should ultimately call `window.open`

fix: iOS login blocked

---

frontend/src/lib/components/accounts/NewTransactionAmount.svelte
frontend/src/lib/components/neurons/StakeNeuron.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/utils/icp.utils.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/tests/lib/utils/icp.utils.spec.ts
frontend/src/tests/lib/utils/projects.utils.spec.ts

Max button in sale participation didn't consider the remaining amount of the project.
* Add maxAmount parameter to TransactionModal.
* Use new maxAmount when calculating the max of the transaction amount.
* Rename and refactor maxICP to use e8s to getMaxTransactionAmount
* New project util to expose the remaining amount of a project projectRemainingAmount
* New tests for project util projectRemainingAmount
* Create new test cases for refactored util getMaxTransactionAmount

Fix: Max button in sale participation

---

frontend/package-lock.json
frontend/src/lib/api/accounts.api.ts
frontend/src/lib/api/dev.api.ts
frontend/src/lib/api/governance.api.ts
frontend/src/lib/api/ledger.api.ts
frontend/src/lib/api/sns.api.ts
frontend/src/tests/lib/api/accounts.api.spec.ts
frontend/src/tests/lib/api/canisters.api.spec.ts
frontend/src/tests/lib/api/ledger.api.spec.ts
frontend/src/tests/lib/services/app.services.spec.ts
frontend/src/tests/mocks/governance.canister.mock.ts
frontend/src/tests/mocks/ledger.canister.mock.ts

Upgrade nns-js. Fix broken changes in nns-dapp.
This is in preparation for the refactor to start using AmountToken instead of ICP.
* Upgrade nns-js, sns-js and utils to latest next version.
* LedgerCanister and GovernanceCanister don't expect ICP anymore but bigint.

L2-991: Upgrade nns-js with breaking changes

---

frontend/src/lib/components/launchpad/ProposalCard.svelte
frontend/src/lib/components/launchpad/Proposals.svelte
frontend/src/lib/components/proposals/ProposalCard.svelte
frontend/src/tests/lib/components/launchpad/Proposals.spec.ts

For consistency reason, use the new proposals' cards layout on launchpad.
- use new cards "modern" layout
- `li` for the grid

feat: use new proposals card on launchpad

---

frontend/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
frontend/src/lib/canisters/nns-dapp/nns-dapp.certified.idl.js
frontend/src/lib/canisters/nns-dapp/nns-dapp.did
frontend/src/lib/canisters/nns-dapp/nns-dapp.errors.ts
frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js
frontend/src/lib/canisters/nns-dapp/nns-dapp.types.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/canisters/nns-dapp.canister.spec.ts
rs/nns-dapp.did
rs/src/accounts_store.rs
rs/src/accounts_store/tests.rs
rs/src/main.rs

We only add pending transaction from the caller instead of expecting the principal as parameter.
* Add a check "check_pending_transaction_buyer" before adding pending transaction.
* Return NotAuthorized if false.
* Adapt all candid and related files to new response.
* New test for check_pending_transaction_buyer.

L2-1001: Allow pending transactions only caller

---

rs/src/accounts_store.rs

Upgrading the canister was failing due to the change in the state.
The problem was that when decoding, the code was expecting the new state of `pending_transactions` to be already present.
* Remove `pending_transactions` when decoding the state and add it as a hash map when creating the new state.
No extra test.

Fix: Upgrade failing with new canister state

---

frontend/package-lock.json
frontend/src/lib/components/proposal-detail/MyVotes.svelte
frontend/src/lib/components/proposal-detail/ProposalVotingSection.svelte
frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.svelte
frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectContainer.svelte
frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.svelte
frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectModern.svelte
frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelectModern.spec.ts

Integrating the "my votes" section into the collapsible section of the proposal detail in new design makes the screen even more readable. Following this integration, we also discussed with Mischa how the "Voting Power" and number of selected should be displayed. This PR implements this too.
- integrate "My votes" in collapsible between the selection of the neurons and the ineligible neurons
- display "Neurons (A/B)" where A is the number of selected neurons and B the number of selectable neurons
- display "(A/B)" and "Voting Power: XXX" only of the number of selectable neurons > 0
- in new design the collapsible should always be visible even if voting period is over otherwise user looses the information
- some minor style / spacing improvements

feat: integrate "my votes" in collapsible section of proposal detail new design

---

frontend/package-lock.json
frontend/src/lib/themes/mixins/_overlay.scss

More z-index issue following the introduction of the new bottom sheet
- integrate last z-index changes of `gix-components`
- set popover to same z-indexes as modals
Issues:
Afterwards:

style: fix popover z-index

---

frontend/package-lock.json
frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/components/common/RouteModule.svelte
frontend/src/lib/components/header/AccountMenu.svelte
frontend/src/lib/components/header/Logout.svelte
frontend/src/lib/components/header/ThemeToggle.svelte
frontend/src/lib/components/ic/GetICPs.svelte
frontend/src/lib/components/proposals/ProposalCard.svelte
frontend/src/lib/constants/proposals.constants.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/themes/mixins/_overlay.scss
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/types/theme.ts
frontend/src/routes/Accounts.svelte
frontend/src/tests/lib/components/common/MenuItems.spec.ts
frontend/src/tests/lib/components/header/ThemeToggle.spec.ts
frontend/src/tests/routes/Accounts.spec.ts

Review & refresh of the UI look & feel
- "Accounts" navigation renamed in "Tokens"
- "Accounts" placeholder renamed in "Total"
- new menu icons for "Neurons" and "Canisters"
- keyword "Theme" in theme switcher removed
- various padding and spacing updated
- those inherited from related gix-component PR
- proposal "Failed" and "Rejected" color light red emphasis
- new proposal card ID moved and colored
- blockquote use for proposal title

style: review & refresh of UI look & feel

---

frontend/src/lib/modals/Modal.svelte
frontend/src/lib/themes/legacy.scss

Fix modal `.meta` information overflow
- apply legacy meta style to modal as well
- add break word
issue:
fix:

style: fix modal meta overflow

---

frontend/src/lib/themes/legacy.scss

Not all the `.legacy` style should be inherited.

style: fix legacy modal spacing

---

rs/src/accounts_store.rs

Do not lose the pending_transactions when upgrading canisters.
* When decoding, expect also the pending_transactions Hashmap.
* Use the decoded to create the AccountsStore.
Not applicable

L2-1020: Decode pending_transactions

---

frontend/scripts/build.index.mjs

CSP rule `'strict-dynamic'` is supported by major modern browsers. However Safari does support it only since Marc 2022.
Therefore, to support older devices, we add `'unsafe-inline'` and `https:` to the `script-src` rule.
Note that this unsecure rule will be ignored by the modern browsers that does support `'strict-dynamic'` and therefore remain secure.
- add `'unsafe-inline'` and `https:` to the `script-src` rule

feat: csp script-src fallback for older devices

---

frontend/src/lib/components/accounts/Address.svelte
frontend/src/lib/components/accounts/AddressInput.svelte
frontend/src/lib/components/accounts/SelectAccountDropdown.svelte
frontend/src/lib/components/accounts/SelectDestinationAddress.svelte
frontend/src/lib/components/accounts/SelecteDestinationAddress.svelte
frontend/src/lib/components/ui/Dropdown.svelte
frontend/src/lib/components/ui/Input.svelte
frontend/src/lib/components/ui/InputWithError.svelte
frontend/src/lib/derived/accounts-list.derived.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionReview.svelte
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/types/i18n.d.ts
frontend/src/routes/Accounts.svelte
frontend/src/routes/Wallet.svelte
frontend/src/tests/lib/components/accounts/AddressInput.spec.ts
frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
frontend/src/tests/lib/derived/accounts-list.derived.spec.ts
frontend/src/tests/lib/modals/accounts/IcpTransactionModal.spec.ts
frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
frontend/src/tests/mocks/accounts.store.mock.ts
frontend/src/tests/routes/Accounts.spec.ts
frontend/src/tests/routes/Wallet.spec.ts

Implement the new transaction flow.
This will also allow us to implement the new modal UI.
* Change TransactionModal so that the user can select a destination or pass a selected account.
* New IcpTransactionModal to transafer ICPs.
* New SelectDestinationAddress to select a destination from current accounts with dropdown or address input.
* Extract AdressInput from Adress to be used in SelectDestinationAddress.
* Changed skipHardwareWallets prop in SelectAccountDropdown for a function to filter accounts. Used to filter the already selected account and also hardware wallets.
* Change UI of the dropdown to make it look more similar to the input.
* New prop showInfo in Input component. There was an extra space from the gap otherwise.
* Add test cases in Transaction modal when user passes a …

L2-841: New transaction flow

---

frontend/src/App.svelte
frontend/src/lib/components/accounts/AccountsTitle.svelte
frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/components/common/RouteModule.svelte
frontend/src/lib/constants/routes.constants.ts
frontend/src/lib/pages/NnsAccounts.svelte
frontend/src/lib/pages/SnsAccounts.svelte
frontend/src/lib/utils/app-path.utils.ts
frontend/src/routes/Accounts.svelte
frontend/src/routes/Launchpad.svelte
frontend/src/routes/ProjectDetail.svelte
frontend/src/routes/Wallet.svelte
frontend/src/tests/lib/derived/selected-project.derived.spec.ts
frontend/src/tests/lib/pages/NnsAccounts.spec.ts
frontend/src/tests/lib/pages/SnsAccounts.spec.ts
frontend/src/tests/lib/stores/route.store.spec.ts
frontend/src/tests/lib/utils/app-path.utils.spec.ts
frontend/src/tests/routes/Accounts.spec.ts

User can select different sns projects in the accounts page.
* Move current Accounts page to `/pages/NnsAccounts`.
* Setup Sns Accounts page in `/pages/SnsAccounts`.
* New component for the footer of the NNS accounts.
* In the route/Accounts we render dropdown component and NnsAccounts or SnsAccounts.
* Add new path LegacyAccounts to AppPath, while `AppPath.Accounts` uses context: `/u/:id/accounts`.
* All redirects to `AppPath.Accounts` redirect for now to `AppPath.LegacyAccounts`.
* Moved test for Accounts to pages/NnsAccounts
* routes/Accounts tests dropdown and which component is rendered.
* Setup SnsAccounts test file.
* Changed and added tests for app-path utils after changes.

L2-992: Project dropdown for accounts

---

frontend/src/lib/components/accounts/SelectDestinationAddress.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/accounts/NewTransaction/TransactionReview.svelte
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts

UI Improvements in the Transaction flow.
* TransactionReview: Account name is not using the label color.
* TransactionReview: Show the text "Balance" next to the balance of the source account
* TransactionForm: Hide toggle to select destination from dropdown if no accounts to choose.
* Test that SelectDestinationAddress doesn't show toggle if no extra accounts to choose from.

L2-1023: Transaction UI improvements

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker-build.yaml
.github/workflows/nightly.yaml
.github/workflows/tag.yaml

If a developer (e.g. myself) pushes a branch, then notices a change that needs to be made and pushes again, the earlier job still runs to completion even though it is no longer of interest.  It would be nice to kill the earlier job when it is superseded.
Github's concurrency provides setting to do just this:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
I have opted for the configuration where each workflow has its own groups, so that a kill command from one workflow doesn't kill others.  This lets us choose for which workflows this policy is applied.  I have applied the concurrency limit to every workflow but we may decide that it is only appropriate for some.
* Set each workflow …

Kill earlier runs

---

frontend/package-lock.json
frontend/src/lib/api/sns-ledger.api.ts
frontend/src/lib/api/sns-wrapper.api.ts
frontend/src/lib/api/sns.api.ts
frontend/src/lib/derived/sns/sns-project-accounts.derived.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/pages/NnsAccounts.svelte
frontend/src/lib/pages/SnsAccounts.svelte
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/stores/sns-accounts.store.ts
frontend/src/lib/stores/sns-neurons.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/api/sns-ledger.api.spec.ts
frontend/src/tests/lib/api/sns-wrapper.api.spec.ts
frontend/src/tests/lib/derived/sns/sns-project-accounts.derived.spec.ts
frontend/src/tests/lib/pages/NnsAccounts.spec.ts
frontend/src/tests/lib/pages/SnsAccounts.spec.ts
frontend/src/tests/lib/services/sns-accounts.services.spec.ts
frontend/src/tests/lib/stores/sns-accounts.store.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts
frontend/src/tests/lib/utils/utils.spec.ts
frontend/src/tests/mocks/sns-accounts.mock.ts

User can see the balance of the main account in an SNS project.
* New store: snsAccountsStore.
* New derived store: snsProjectAccountsStore which combines the selectedProject and the snsAccountsStore.
* New sns api in "sns-ledger.api": getSnsAccounts. For now it returns only a Main account.
* New sns accounts service: loadSnsAccounts that users getSnsAccounts api and snsAccountsStore.
* loadSnsAccounts service is called in SnsAccounts page.
* Render AccountCard for each account in SnsAccounts and the total of tokens.
* Test new store and derived.
* Test new sns api function
* Test new sns service
* Test new functionality in SnsAccounts.

L2-993: User can see SNS main balance account

---

frontend/src/lib/components/canisters/ConfirmCyclesCanister.svelte
frontend/src/lib/modals/canisters/AddCyclesModal.svelte
frontend/src/lib/modals/canisters/CreateCanisterModal.svelte

Back buttons are displayed on the first step of the canisters' related modal.
- don't display back button on such steps

fix: modal back button on canister

---

frontend/package-lock.json
frontend/src/routes/Proposals.svelte

The label "No proposals found for filter" was not always displayed or stick to screen.
- link refresh of label with appropriate derived store

fix: display no proposals found

---

frontend/src/lib/components/accounts/SelectAccountDropdown.svelte
frontend/src/lib/components/ic/SelectProjectDropdownHeader.svelte
frontend/src/lib/components/ui/Dropdown.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/routes/Accounts.svelte
frontend/src/routes/Neurons.svelte

Fix the hidden slice of word in the Project Dropdown selector of Accounts and Neurons.
* Refactor the Dropdown used in the pages to its own component: SelectProjectDropdownHeader.
* Apply the width of the `select` of the dropdown as content-box not as border-box.

L2-1024: Fix dropdown hidden content

---

e2e-tests/scripts/nns-canister-download
scripts/propose

There has been a breaking change in the NNS manage neuron API, so we need to be careful to use a version of ic-admin that matches the canisters.
- When downloading NNS canisters, download ic-admin as well.
- When making a proposal with ic-admin, use the downloaded tool.
I have used this to deploy small14

Use current ic-admin

---

e2e-tests/scripts/nns-canister.patch

The sns code has changed significantly.  One of our patches fails to apply and may well no longer be relevant.
- Remove broken patch that allowed an SNS start time to be in the past.
I have verified that the patchfile now applies cleanly.

Remove outdated patch

---

frontend/src/lib/api/governance.api.ts
frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/canisters/SelectCyclesCanister.svelte
frontend/src/lib/components/neuron-detail/ConfirmSpawnHW.svelte
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/services/neurons.services.ts
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/transaction-fees.store.ts
frontend/src/lib/utils/anonymize.utils.ts
frontend/src/lib/utils/icp.utils.ts
frontend/src/lib/utils/neuron.utils.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/tests/lib/api/governance.api.spec.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/utils/icp.utils.spec.ts
frontend/src/tests/lib/utils/neuron.utils.spec.ts
frontend/src/tests/lib/utils/projects.utils.spec.ts
frontend/src/tests/mocks/sns-response.mock.ts

Keep cleaning the usage of deprecated ICP class.
* Change usage of ICP class for TokenAmount class.
* Remove convertNumberToICP and use TokenAmount.fromNumber instead.

GIX-990: Remove ICP class dependency v3

---

rs/src/assets.rs

Add mime types for new `robots.txt`.
Follow-up of #1377.

feat: support txtmime types

---

frontend/src/lib/components/accounts/TransactionList.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/services/debug.services.ts
frontend/src/lib/stores/debug.store.ts
frontend/src/lib/types/selected-account.context.ts
frontend/src/tests/lib/components/accounts/TransactionList.spec.ts
frontend/src/tests/lib/components/accounts/WalletActions.spec.ts
frontend/src/tests/lib/components/accounts/WalletSummary.spec.ts
frontend/src/tests/mocks/context-wrapper.mock.ts
frontend/src/tests/mocks/modal.mock.ts
frontend/src/tests/mocks/selected-account.store.mock.ts

Remove "transactions" from SelectedAccountStore to make it more reusable for SNS Wallet.
* Remove "transactions" from SelectedAccountStore.
* Add "transactions" prop in TransactionsList.
* Use a local variable in NnsWallet to track transactions.
* Fix broken tests after refactor.

GIX-995: Transactions out of SelectedAccountStore

---

frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/constants/routes.constants.ts
frontend/src/lib/derived/paths.derived.ts
frontend/src/lib/pages/NnsAccounts.svelte
frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/lib/pages/NnsNeurons.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/pages/SnsAccounts.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/utils/app-path.utils.ts
frontend/src/tests/lib/derived/paths.derived.spec.ts

Menu items and back buttons should keep the same context.
* New paths.derived store with four new derived stores for neurons, neuronDetails, accounts and wallet. The idea is to read the selectedProject (as well as the feature flag for now) and return the according path.
* routes inside MenuItems is dynamic and use new paths.derived.
* new paths helper in app-path.utils to return a path interpolating the context.
* Use the new paths.derived when navigating back from Wallet and NeuronDetail pages.
* Use the new paths.derived when navigation from NeuronCard or AccountCard.
* New tests for the new paths.derived.

GIX-1017: Menu items keep context

---

frontend/src/lib/utils/error.utils.ts
frontend/src/tests/lib/utils/error.utils.spec.ts

Localise toast error prop to fix the current `undefined_project` issue.
- Apply translate to the error text
- "should translate error"

feat: apply translate to toast error messages

---

frontend/src/lib/components/common/Layout.svelte

Revert "smooth transition". It has for effect to briefly adds two split pane and header in the tree which make the ui a bit shaky on smaller screen. Note the user icon not in place in enclosed screenshot.
- revert PR #1368

style: revert smooth transition

---

frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/services/sns.services.ts
frontend/src/tests/lib/services/sns.services.spec.ts

Last user to participate in an SNS sale got an error that can be safely ignored.
* Change text to match when ignoring error when participating.
* Use the currentUserMax amount as maximum for the participation transfer.
* Fix test.

GIX-1050: Handle error last sns participation

---

frontend/package-lock.json
frontend/src/lib/api/dev.api.ts
frontend/src/lib/api/sns-wrapper.api.ts
frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/components/ic/GetICPs.svelte
frontend/src/lib/components/ic/GetTokens.svelte
frontend/src/lib/services/dev.services.ts
frontend/src/tests/lib/api/sns-wrapper.api.spec.ts

Testnet users can get any kind of tokens.
* Use the context to differentiate between transferring from NNS or from SNS.
* Change modal text to use token of the SNS project.
Not applicable, this is just a feature for testnets.

GIX-998: Get SNS tokens from test account

---

frontend/src/lib/api/sns-ledger.api.ts
frontend/src/lib/components/accounts/WalletSummary.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/routes/Wallet.spec.ts

User has access to the details page with main data of SNS account.
* Implement SnsWallet to set up the context to be able to render WalletSummary.
* Encode the Sns Account in the "identifier" property.
* Test SnsWallet page.
* Fix ugly comment in Wallet page test.

GIX-995: SNS Wallet details

---

frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

Fix the edge case when the initial sns neuron `dissolve_state` = `{DissolveDelaySeconds: 0}`
- `getSnsNeuronState` returns `Dissolved` status when `DissolveDelaySeconds=0`
- update getSnsNeuronState specs
Initial sns neuron state

feat: DissolveDelaySeconds=0 neuron state

---

frontend/package-lock.json
frontend/src/lib/api/sns-ledger.api.ts
frontend/src/lib/derived/sns/sns-selected-transaction-fee.store.ts
frontend/src/lib/pages/SnsAccounts.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/transaction-fees.services.ts
frontend/src/lib/stores/transaction-fees.store.ts
frontend/src/tests/lib/api/sns-ledger.api.spec.ts
frontend/src/tests/lib/derived/sns/sns-selected-transaction-fee.store.spec.ts
frontend/src/tests/lib/pages/SnsAccounts.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/lib/services/sns-accounts.services.spec.ts
frontend/src/tests/lib/services/transaction-fee.services.spec.ts
frontend/src/tests/lib/stores/transaction-fees.store.spec.ts
frontend/src/tests/routes/Accounts.spec.ts
frontend/src/tests/routes/Wallet.spec.ts

Each SNS project might have a different transaction fee. Extend the current functionality to accommodate that.
* Add "transactionFee" function to sns-ledger api.
* Extend the transactionFeeStore with a "projects" property to store different transaction fees.
* New transaction fee service to load sns transaction fee to the store.
* Load SNS transaction fees in SnsAccounts and SnsWallet.
* New derived store that returns the fee of the current project context in a TokenAmount type.
* New test new api function.
* New test for extended transactionFeeStore functionality.
* New test for transaction fee service.
* Add calls check on SnsAccounts and SnsWallet.
* New test for new derived store.

GIX-1044: Extend transaction fee store

---

frontend/src/lib/components/common/AuthLayout.svelte
frontend/src/routes/Auth.svelte

There is some overflows or hidden content on the login page in the landscape mode. A problem affects some mobile devices like iphone 11+ and pixels. 
- lock the mobile view till there is not enough vertical space
- make the login main content scrollable on mobile

fix: preserve login page mobile view in landscape mode

---

frontend/src/lib/components/neurons/SelectProjectDropdown.svelte

The Spinner of the ProjectDropdown was aligned to the right, not in the middle like the dropdown.
* Wrap Spinner inside ProjectDropdown with a `div` to center it.
Not applicable. Only UI changes.

GIX-1063: Fix Spinner Dropdown

---

frontend/src/lib/api/sns-ledger.api.ts
frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/api/sns-ledger.api.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts
frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts
frontend/src/tests/lib/modals/neurons/DisburseSnsNeuronModal.spec.ts
frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
frontend/src/tests/mocks/sns-projects.mock.ts

Manage the possible situations where sns token might not be present.
* Throw an error when loading sns accounts and token is not present.
* Cast the token in components when we know the token is present otherwise the component would not be rendered.
* Add test to check an error is thrown when token is not present.

GIX-1045: Manage when sns token not defined

---

frontend/package.json
frontend/scripts/i18n.types.js
frontend/src/lib/api/dev.api.ts

Script that creates i18n key types was not working.
There was a warning from Vite.
* Add a comment for Vite to ignore a dynamic import.
* Fix i18n script.
Not applicable

Fix: i18n script

---

frontend/src/tests/tsconfig.json
frontend/tsconfig.json

There was an error in VS Code with test files that the module was not found.
* Add tsconfig in `tests` folder.

FIx: Import module not found in VS Code

---

deploy.sh
dfx.json
e2e-tests/scripts/nns-canister-download
e2e-tests/scripts/nns-canister.Dockerfile

The latest SNS has an index canister.
- Bump IC_COMMIT to get the latest SNS canister versions.
- Add the index canister to the set of SNS cansters listed in dfx.json
- Download the index canister wasm and did files
- Upload the index canister in deploy.sh
None added.
I have confirmed that the wasm and did files are downloaded.

chore: SNS index canister

---

frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts

User can make sns transactions from the wallet page.
* Add "New Transaction" button to SnsWallet page.
* Add selectedAccount prop to SnsTransactionModal.
* Add test for new functionality in SnsWallet page.
* Add test for new prop in SnsTransactionModal

GIX-1070: Sns Transfer from wallet page

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/docker-build.yaml
.github/workflows/nightly.yaml
.github/workflows/tag.yaml

We have a warning in the Gibhub actions:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
- Upgrade some of the node.js github actions.
Not applicable

Fix: Node.js 12 actions deprecated

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/nightly.yaml

This avoids the CI warning about deprecated `node12` (for this action..., though others still trigger it).

chore: bump `EndBug/add-and-commit` GH action

---

frontend/src/lib/components/accounts/AddressInput.svelte
frontend/src/lib/components/accounts/SelectAccountDropdown.svelte
frontend/src/lib/components/accounts/SelectDestinationAddress.svelte
frontend/src/lib/constants/accounts.constants.ts
frontend/src/lib/derived/accounts-list.derived.ts
frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/utils/accounts.utils.ts
frontend/src/tests/lib/components/accounts/Address.spec.ts
frontend/src/tests/lib/components/accounts/AddressInput.spec.ts
frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
frontend/src/tests/lib/derived/accounts-list.derived.spec.ts
frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts
frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
frontend/src/tests/lib/pages/SnsAccounts.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/lib/utils/accounts.utils.spec.ts
frontend/src/tests/mocks/sns-accounts.mock.ts

The form to participate in the swap was not working.
* Add a prop rootCanisterId to: "TransactionModal", "SelectAccountDropdown" and "SelectDestinationAddress".
* Remove minLength in AddressInput.
* New accounts utils: "getAccountByProject" and "getAccountsByProject".
* Remove derived store "accountsSelectedProjectStore".
* Fix broken tests because of new prop.
* Add new tests to test new prop.
* New tests for new accounts utils.
* Remove tests for min length.

Fix: Participation in Swap

---

frontend/package-lock.json
frontend/src/lib/components/accounts/AddressInput.svelte
frontend/src/lib/components/accounts/HardwareWalletName.svelte
frontend/src/lib/components/ui/InputWithError.svelte
frontend/src/lib/components/ui/PrincipalInput.svelte

- Show info in input a level higher because `PrincipaInput` always pass a `slot`
- Fix style modal height on Safari and in landascape

feat: show input info and modal

---

frontend/package-lock.json
frontend/package.json
frontend/src/routes/+layout.ts
frontend/vite.config.ts

Same issue as https://github.com/vitejs/vite/discussions/2785#discussioncomment-1452855
Basicall the ledger needs Buffer which is a NodeJS library which we have to polyfill.
Adding a polyfill (`window.Buffer =...`) works great for local development but does not always work on mainnet.
Indeed, `_layout.js` (which contains the polyfill) might be loaded after a `page.js` therefore, we might hit the issue `start-4e5e2afa.js:1 ReferenceError: Buffer is not defined`.
Use rollup plugin as well to inject Buffer (as we used too with rollup bundler) so that the Buffer also gets polyfied within the page
With this PR we polyfill in to places, therefore the bundle will be a bit more heavy. We can probably spare the dev polyfill for prod build.
- inject Buffer polyfill with Rollup for prod build

build: fix buffer polyfill for mainnet

---

frontend/scripts/build.csp.mjs
frontend/src/app.html

Using a CSP `'strict-dynamic'` with SvelteKit breaks in Firefox.
Extracting the script content that gets injected by SvelteKit in `index.html` into a separate JS script that gets appended with a script loader.
Exact same "script loader" as the one we use to use for Rollup.
- SvelteKit https://github.com/sveltejs/kit/issues/3558 
- update `build.csp.mjs` to extract script
- add script loader to `app.html`

build: fix SvelteKit CSP 'stric-dynamic' issue in Firefox

---

rs/Cargo.toml

When running cargo audit, it shows a vulnerability in a dependency.
But we can't update it because newer versions are not compatible with IC.
* Add a comment on top of the chrono version to remember why we can't fix the vulnerability.

Chore: Comment on chrono version

---

e2e-tests/README.md
e2e-tests/components/accounts-tab.ts
e2e-tests/components/neurons-tab.ts
e2e-tests/components/proposals-tab.ts
e2e-tests/specs/home.e2e.ts
e2e-tests/specs/multi-tab-auth.e2e.ts
e2e-tests/specs/user-A02-create-linked-account.e2e.ts
e2e-tests/specs/user-N03-neurons-merged.e2e.ts
e2e-tests/specs/user-V01-open-proposals-are-shown.e2e.ts
e2e-tests/specs/user-V02-proposal-filters-work.e2e.ts
e2e-tests/wdio.conf.ts
frontend/src/lib/components/proposal-detail/ProposalSystemInfoSection.svelte
frontend/src/lib/components/proposals/ProposalCard.svelte

Improve documentation of how to execute e2e tests.
Fix selectors and other minor broken e2e tests.
This does NOT fix all the e2e yet. But it's one step towards adding them to our CI.
What is still pending:
* Deploy the SNS-W canister locally. Better to wait until the next dfx release which will include an easy way to do so: `dfx nns install`.
* When making a new proposal to be tested, it should be Open and not fail immediately.
* I also added a couple more of TODOs in the code that would add nice functionality, but are not necessary for the current e2e tests.
* Improve Readme in e2e-tests directory.
* Fix some broken e2e tests.
* Add some data-tid in nns-dapp frontend.
All changes are in tests.

Chore: Fix e2e running locally

---

frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

A SNS Hotkey is not just NEURON_PERMISSION_TYPE_VOTE permission but also NEURON_PERMISSION_TYPE_SUBMIT_PROPOSAL.
* Add and remove NEURON_PERMISSION_TYPE_SUBMIT_PROPOSAL permission when adding or removing hotkeys.
* Fix tests.

GIX-1073: SNS Hotkey more permissions

---

frontend/src/lib/api/governance.api.ts
frontend/src/lib/components/neuron-detail/ConfirmSpawnHW.svelte
frontend/src/lib/services/neurons.services.ts
frontend/src/lib/stores/transaction-fees.store.ts
frontend/src/lib/utils/neuron.utils.ts
frontend/src/tests/lib/api/governance.api.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/lib/utils/neuron.utils.spec.ts

Reduce usage of TokenAmount for non-UI related functionality and use e8s instead.
* Remove dependency of TokenAmount in "neuron.utils", "governance.api" and "neuron.services".

Chore: Reduce token amount usage

---

frontend/src/lib/api/sns.api.ts
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/stores/sns.store.spec.ts

User might try to participate in a decentralization sale and fail because the information is stale. We only load it once at the initialization.
To avoid edge cases and bad UX where refunds need to happen, we refresh the swap state before validating the user participation.
* New sns service "reloadSnsState" used only internally in "participateInSwap".
* New method in sns store "updateSwapState" that loads in store only the swap state.
* A test case that participateInSwap fetches new data.
* A test case in sns store for updateSwapState.

GIX-1092: Refresh SNS sale before participation

---

frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/utils/app-path.utils.ts
frontend/src/tests/lib/components/common/MenuItems.spec.ts

When the user is in the project details and clicked in Tokens or Neurons menu item was redirected to the Neurons or Tokens of that project.
That was not correct because we don't consider the project details to be part of an SNS universe, rather to be part of the NNS universe
* MenuItems in Tokens and Neurons redirect to NNS project if they are in the project details instead of relying in the context.
* Add projectDetail to paths util
* Add tests that menu items keep this exception.

GIX-1085: Project does not keep context

---

frontend/package-lock.json
frontend/src/lib/api/sns-index.api.ts
frontend/src/lib/components/accounts/SnsTransactionsList.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/sns-transactions.services.ts
frontend/src/lib/stores/sns-transactions.store.ts
frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/lib/services/sns-accounts.services.spec.ts
frontend/src/tests/lib/services/sns-transactions.services.spec.ts
frontend/src/tests/lib/stores/sns-transactions.store.spec.ts
frontend/src/tests/mocks/sns-accounts.mock.ts
frontend/src/tests/mocks/sns-projects.mock.ts
frontend/src/tests/mocks/sns-transactions.mock.ts

Setup getting the SNS transactions for an account.
Rendering the transactions will come in another PR.
* New sns api function "getTransactions".
* Setup of the new component SnsTransactionList.
* New sns transactions service "loadAccountTransactions".
* New snsTransactionsStore
* Fix mock issue after upgrading sns-js
* Add new SnsTransactionList in SnsWallet
* Test new snsTransactionsStore
* Test new sns transaction service loadAccountTransactions
* Use correct string representation in sns mock accounts. Fix broken test.
* New test case in SnsWallet

GIX-996: Setup getting SNS transactions

---

frontend/src/lib/i18n/en.json
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts

Improve the UX by inlining the error message in sale participation.
* New prop in TransactionModal "validateAmount".
* Use new prop validateAmount in "ParticipateSwapModal" with helper validParticipation.
* Improve error message when commitment is too large.
* Test new prop in TransactionModal specs.

Chore: Validate amount participation inline

---

dfx.json

We wish to deploy to small09.  We are not yet using dfx v 0.12.0 that allows us to define networks in an external file.
- Add small09 to the list of networks
- I have deployed  atestnet to small09 using this.  See: https://qvhpv-4qaaa-aaaaa-aaagq-cai.small09.dfinity.network/#/u/qvhpv-4qaaa-aaaaa-aaagq-cai/neuron/2603623906375990293

chore(networks): Add small09

---

frontend/src/lib/components/accounts/NnsTransactionCard.svelte
frontend/src/lib/components/accounts/TransactionCard.svelte
frontend/src/lib/components/accounts/TransactionList.svelte
frontend/src/lib/components/accounts/WalletSummary.svelte
frontend/src/lib/utils/accounts.utils.ts
frontend/src/lib/utils/anonymize.utils.ts
frontend/src/lib/utils/transactions.utils.ts
frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts
frontend/src/tests/lib/utils/accounts.utils.spec.ts
frontend/src/tests/lib/utils/transactions.utils.spec.ts
frontend/src/tests/mocks/transaction.mock.ts

Refactor needed to render the list of Sns Transactions.
* New component NnsTransaction used in NnsTransactionList.
* TransactionCard is now agnostic to nns-dapp transaction type.
* New transaction card: `Transaction` to be used with both types of transactions.
* Move `accountName` helper to accounts utils.
* New test for TransactionCard.
* Move accountName util test.

GIX-996: TransactionCard refactor

---

frontend/scripts/build.csp.mjs

SvelteKit injects an empty (since we do not configure it) CSP tag that is ignored because it finds place after our CSP policy. Still cleaner to remove it.
- remove tag before calculting script

build: remove empty unused default csp tag

---

frontend/package-lock.json
frontend/src/lib/api/sns-index.api.ts
frontend/src/lib/services/sns-transactions.services.ts
frontend/src/tests/lib/api/sns-index.api.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/lib/services/sns-transactions.services.spec.ts

Use sns-wrapper to interact with Index canister instead of the canister directly.
* Remove rootCanisterId temporary checks in transactions services and api.
* Use wrapper to call getTransactions in sns-index api.
* Add test for getTransactions api function.

GIX-1093: Get Transactions uses sns wrapper

---

frontend/scripts/build.csp.mjs

We use the `https:` in the `script-src` rules of the CSP for backwards compatibility as displayed by [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src). However we have a report from a user who cannot access NNS-dapp on his Android v10 device. We are not sure what his issue is but, using Android Simulator, we can reproduce a blank screen on OS <= Android v12. That's why, in accordance with Security team, we remove the `https:` rule that solves the issue in the simulator and which is in any case not used in modern browsers that support `strict-dynamic`.
- remove `https:` rules from CSP `script-src`

build: remove https: from CSP script-src

---

frontend/src/lib/i18n/en.json
frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/services/sns-transactions.services.ts
frontend/src/lib/services/transaction-fees.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts
frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/lib/routes/Accounts.spec.ts
frontend/src/tests/mocks/transaction-fee.mock.ts

User should get feedback when something doesn't work well.
User should not get a blank page when something goes bad.
* Try/catch when loading transactions and show a toast error in the catch.
* Make transactionFee prop as mandatory in TransactionModal.
* Show Modal with Spinner in SnsTransactionModal while transaction fee is not loaded. The fee is loaded along the accounts; therefore, it should be there by the time the user clicks to make a transaction.
* Show a toast error when there is an error loading the sns transaction fee.

GIX-1026: Manage errors in SNS Accounts pages gracefully

---

frontend/src/lib/types/assets.ts
frontend/src/lib/types/sns.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/utils/utils.spec.ts

For security reasons, we need to check that the SNS logo from the canister is PNG.
* Changed type of logo to `Png` instead of `string`.
* Add util to assert that an assert is of type `Png`: "isPngAsset"
* Use new util in "mapOptionalMetadata".
* Cast default logo as Png.
* Add test for the new util "isPngAsset"

GIX-1668: Check SNS logo is Png

---

frontend/src/lib/components/proposals/ProposalsFilters.svelte
frontend/src/tests/lib/components/proposals/ProposalsFilters.spec.ts

If the user had selected DecentralizationSale topic before it was hidden, it was still being counted in the amonut of active filters.
* Do not count deprecated filters in the count of active filters.
* Add a test case for the change.

Fix: Do not count deprecated selected topics

---

frontend/src/lib/services/auth.services.ts
frontend/src/lib/stores/busy.store.ts
frontend/src/tests/lib/services/auth.services.spec.ts

Display the busy screen on logout to hide not working UI on reload.
- show the screen
- added the test that the busy store should be called on logout.

feat: show busy screen on logout

---

frontend/src/lib/components/accounts/NnsTransactionCard.svelte
frontend/src/lib/components/accounts/SnsTransactionCard.svelte
frontend/src/lib/components/accounts/SnsTransactionsList.svelte
frontend/src/lib/components/accounts/TransactionCard.svelte
frontend/src/lib/components/accounts/TransactionList.svelte
frontend/src/lib/constants/constants.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/sns-transactions.services.ts
frontend/src/lib/stores/sns-transactions.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns-transactions.utils.ts
frontend/src/lib/utils/transactions.utils.ts
frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts
frontend/src/tests/lib/components/accounts/SnsTransactionCard.spec.ts
frontend/src/tests/lib/components/accounts/SnsTransactionsList.spec.ts
frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
frontend/src/tests/lib/services/sns-accounts.services.spec.ts
frontend/src/tests/lib/services/sns-transactions.services.spec.ts
frontend/src/tests/lib/stores/sns-transactions.store.spec.ts
frontend/src/tests/lib/utils/sns-transactions.utils.spec.ts
frontend/src/tests/lib/utils/transactions.utils.spec.ts
frontend/src/tests/mocks/sns-transactions.mock.ts

Render the sns account transactions in the SNS wallet page.
* New SnsTransactionCard component to render a TransactionCard from and SnsTransaction.
* Use SnsTransactionCard in SnsTransactionList.
* Use InfiniteScroll in SnsTransactionList to lead more.
* Add token prop to TransactionCard.
* Use a different page size for SNS transactions: DEFAULT_SNS_TRANSACTION_PAGE_LIMIT
* Two sns transaction services: loadAccountNextTransactions and loadAccountTransactions.
* Load new transactions after performing an sns transaction from SnsWallet page.
* New sns transactions utils: "getSortedTransactionsFromStore", "getOldestTxIdFromStore", "isTransactionsCompleted" and "mapSnsTransaction".
* New SnsTransactionCard test
* New SnsTransactionList test
* Test for new sns transaction utils.
* Fix broken …

GIX-996: Render SNS transactions

---

frontend/src/lib/components/ic/GetTokens.svelte
frontend/src/lib/components/neurons/SelectProjectDropdown.svelte
frontend/src/lib/components/neurons/SnsNeuronsFooter.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
frontend/src/lib/derived/selected-project-new-tx-data.derived.ts
frontend/src/lib/derived/selected-project.derived.ts
frontend/src/lib/derived/sns/sns-project-accounts.derived.ts
frontend/src/lib/derived/sns/sns-selected-transaction-fee.store.ts
frontend/src/lib/derived/sns/sns-token-symbol-selected.store.ts
frontend/src/lib/derived/sorted-sns-neurons.derived.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/modals/sns/AddSnsHotkeyModal.svelte
frontend/src/lib/modals/sns/StakeSnsNeuronModal.svelte
frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/routes/Accounts.svelte
frontend/src/lib/routes/Neurons.svelte
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/busy.store.ts
frontend/src/lib/stores/transaction-fees.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/neurons/SelectProjectDropdown.spec.ts
frontend/src/tests/lib/components/neurons/SnsNeuronsFooter.spec.ts
frontend/src/tests/lib/derived/selected-project-new-tx-data.derived.spec.ts
frontend/src/tests/lib/derived/selected-project.derived.spec.ts
frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts
frontend/src/tests/lib/modals/sns/StakeSnsNeuronModal.spec.ts
frontend/src/tests/lib/pages/SnsNeurons.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts
frontend/src/tests/mocks/commont.mock.ts

User can stake SNS Neurons. First step, UI modal.
* New SnsNeuronsFooter.
* New StakeSnsNeuronModal.
* Rename snsProjectSelectedStore to snsProjectIdSelectedStore.
* New derived store snsProjectSelectedStore that returns the project of the current universe.
* New derived store snsSelectedProjectNewTxData that checks and returns all data needed for a new SNS transaction.
* Load sync sns accounts when visiting SnsNeurons page.
* Test SnsNeuronsFooter
* Test StakeSnsNeuronModal
* Test new derived stores snsProjectSelectedStore and snsSelectedProjectNewTxData

GIX-1115: Stake SNS Neuron UI

---

frontend/package-lock.json

Font size < 16px in inputs makes iOS automatically ping zoom for a11y reason. We do not want such issue.
https://css-tricks.com/16px-or-larger-text-prevents-ios-form-zoom/
Therefore we revert to a base font size of 16px.

style: revert to base font 16px

---

frontend/package-lock.json
frontend/src/routes/+layout.svelte

When deployed on the IC, it is possible that fetching the worker takes more time than fetching the code to sync the identity. This can lead to a race condition in the case the user proceed as following:
- user access nns-dapp
- user sign-in
- user refresh the browser
- synchronize the auth worker not only when the auth changes but also right after the worker has been loaded
This has been debuged locally by setting a delegation that least only 20s and tested manually in various scenario.

fix: init auth worker race condition

---

frontend/src/lib/pages/Auth.svelte
frontend/src/tests/lib/pages/Auth.spec.ts

Link sub-pages (Accounts etc.) with their corresponding categories on main login page.
- add links

feat: link to sub-pages on main login screen

---

Cargo.lock
frontend/package-lock.json
frontend/src/lib/components/accounts/SnsTransactionCard.svelte
frontend/src/lib/components/accounts/SnsTransactionsList.svelte
frontend/src/lib/utils/sns-transactions.utils.ts
frontend/src/tests/lib/components/accounts/SnsTransactionCard.spec.ts
frontend/src/tests/lib/utils/sns-transactions.utils.spec.ts
frontend/src/tests/mocks/sns-neurons.mock.ts
frontend/src/tests/mocks/sns-transactions.mock.ts

In SNS transactions, use the fee from the transactions instead of the fee from the project.
* Remove fee prop from `SnsTransactionCard`.
* Remove fee parameter from `mapSnsTransaction` and use instead the `fee` from the transaction if present.
* Adapt tests accordingly.

GIX-1121: Use fee from transaction data

---

frontend/package-lock.json
frontend/src/lib/components/common/Layout.svelte
frontend/src/lib/pages/CanisterDetail.svelte
frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/lib/pages/ProposalDetail.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/lib/stores/layout.store.ts
frontend/src/routes/(app)/accounts/+page.svelte
frontend/src/routes/(app)/canister/+layout.svelte
frontend/src/routes/(app)/canisters/+page.svelte
frontend/src/routes/(app)/launchpad/+page.svelte
frontend/src/routes/(app)/neuron/+layout.svelte
frontend/src/routes/(app)/neurons/+page.svelte
frontend/src/routes/(app)/project/+layout.svelte
frontend/src/routes/(app)/proposal/+layout.svelte
frontend/src/routes/(app)/proposals/+page.svelte
frontend/src/routes/(app)/wallet/+layout.svelte
frontend/src/tests/lib/components/common/LayoutTest.svelte

The `layoutBackStore` was deprecated. In addition, updating the store after all components are mounted might lead to some glitch refreshing the navigation header - updating menu and back buttons - on route changes.
- deprecate `$layoutBackStore` and replace with property defined on `+layout`

feat: use back property instead of store

---

frontend/src/lib/components/common/Footer.svelte

Firefox seems to have issue to interpret `auto-fit` in a `grid-template-columns` which has for effect to stack the footer buttons.
- remove `auto-fit` and replace by `var(--footer-columns)` since we now have a value for the number of columns of the footer
Before
After

style: fix auto-fit usage for Firefox

---

frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte
frontend/src/lib/stores/proposals.store.ts

When navigating between proposals, it's possible that the next proposal gets mounted while the previous still destroy some components therefore it's possible that component `<VotingCard />` has its function `onDestroy` called after the next proposal is mounted. Because this function reset the scoped `votingNeuronSelectStore`, it's possible that as a side effect, these neurons gets resetted and the voting option per extension becomes disabled.
User -> proposal 1 -> voting neurons = 1,2,3
User -> proposal 2 -> voting neurons = 1,2,3
Destroy -> voting neurons = _
User -> still on proposal 2 -> ui re-rendered -> no voting neurons
- remove `reset` from `onDestroy`. it can be ignored because on mount the `VotingCard` component first `set` the voting neurons and since we navigate between pages, …

fix: votingNeuronSelectStore reset race condition

---

frontend/src/lib/components/neurons/SnsNeuronsFooter.svelte

Remove a shadow below the Stake Neuron button in SNS Neurons page.
* Remove `Toolbar` from `SnsNeuronsFooter`. It's already included in the `Footer`.
Only UI changes, no test required.

Fix: Shadow below sns neuron button

---

frontend/package-lock.json
frontend/src/lib/api/sns-governance.api.ts
frontend/src/lib/constants/sns-neurons.constants.ts
frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/services/sns-neurons-check-balances.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/sns-neurons.store.ts
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/api/sns-governance.api.spec.ts
frontend/src/tests/lib/pages/SnsNeurons.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts
frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts
frontend/src/tests/lib/stores/sns-neurons.store.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

Check sns neuron balances with the stake and claim or refresh accordingly if they don't match
* New sns-governance api: "getNeuronBalance", "refreshNeuron", "claimNeuron".
* Rename sns neuron service "loadSnsNeurons" to "syncSnsNeurons". Add balance check there.
* Add balance check in getSnsNeuron service.
* Balance check and refreshing is done in "checkSnsNeuronBalances". No recursion, each neuron refreshed is loaded independently.
* New method in sns neurons store "addNeurons".
* Test new cases in syncSnsNeurons and getSnsNeuron services.
* Test new sns neurons method.
* Test new sns governance apis.

GIX-1116: Syns SNS Neuron Balances

---

frontend/__mocks__/$app/stores.ts
frontend/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
frontend/src/lib/components/sns-neuron-detail/actions/DissolveSnsNeuronButton.svelte
frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/routes/(app)/neuron/+layout.svelte
frontend/src/routes/(app)/wallet/+layout.svelte
frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

Fix some navigation issues and hides dissolve buttons depending on permissions.
* Change the button of the SNS Disburse modal. It was "back" but that was the first screen. Switched to "Cancel".
* New sns neuron util "hasPermissionToDissolve" used in SnsNeuronMetaInfoCard to hide Dissolve button.
* Check the path from the store before raising an error if neuron or wallet not found.
* Use `accountsPathStore` and `neuronsPathStore` to maintain the universe when going back from Wallet and Neuron detail.
* Test the new util hasPermissionToDissolve
* Add test to SnsNeuronMetaInfoCard for new cases and also disburse cases.
* Fix test SnsNeuronDetail after new check.

Fix: Navigation and SNS Neuron Detail issues

---

frontend/src/lib/api/sns-wrapper.api.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns-ledger.utils.ts

We are using different identities to interact with SNSes. For now logged in and anonymous.
Therefore, we need to cache the sns wrapper by identity so that we don't use the wrong wrapper. For example, using the anonymous identity wrapper to get the balance.
* Change implementation of "wrappers" to cache by identity principal instead of only by certified or not.
* Map transfer errors and show a proper message according to each error.
* No changes. Same functionality.

FIX: Cache sns wrapper by identity

---

frontend/src/lib/components/accounts/SnsTransactionCard.svelte
frontend/src/lib/components/accounts/SnsTransactionsList.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/utils/sns-transactions.utils.ts
frontend/src/tests/lib/components/accounts/SnsTransactionCard.spec.ts
frontend/src/tests/lib/utils/sns-transactions.utils.spec.ts

User can identify transactions related to neurons in the SNS Wallet page.
* Add "rootCanisterId" prop to SnsTransactionCard.
* In SnsTransactionCard get the project related to the "rootCanisterId" prop and pass the governanceCanisterId to "mapSnsTransaction"
* Add new parameter to "mapSnsTransaction": governanceCanisterId. This is used to identify transactions related to neurons.
* Add the token symbol in the headline of transactions related to neurons.
* Test new case in mapSnsTransaction.
* Test new case in SnsTransactionCard.

GIX-1148: SNS Stake Neuron Transaction

---

frontend/src/routes/+layout.svelte
frontend/src/tests/routes/layout.spec.ts

When user are signed out automatically, they have to manully close the toast. It makes sense that it does not fade away - because you never know when the user comeback - but it can be more user friendly to automatically close the toast on sign-in.
- `toastReset` on sign-in

feat: reset toast on signin

---

frontend/src/lib/components/neurons/NnsNeuronAge.svelte
frontend/src/lib/components/sns-neurons/SnsNeuronAge.svelte
frontend/src/lib/utils/neuron.utils.ts
frontend/src/tests/lib/components/neuron-detail/NnsNeuronMetaInfoCard.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts
frontend/src/tests/lib/utils/neuron.utils.spec.ts
frontend/src/tests/mocks/context-wrapper.mock.ts

Instead of the stake created date, display the "Age" of a neuron. Information is more user friendly.
- adds utils to calculate `neuronAge`
- display "Age" on NNS neuron detail page
How to display the age of Sns neuron is currently discussed therefore this PR focus only Nns.

feat: nns neuron age

---

frontend/src/lib/components/neurons/EditFollowNeurons.svelte
frontend/src/lib/components/neurons/FollowNnsTopicSection.svelte
frontend/src/lib/components/neurons/FollowTopicSection.svelte
frontend/src/lib/constants/sns-neurons.constants.ts
frontend/src/lib/modals/sns/FollowSnsNeuronsModal.svelte
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/components/neurons/FollowTopicSection.spec.ts
frontend/src/tests/lib/components/neurons/FollowTopicSectionTest.svelte
frontend/src/tests/lib/modals/sns/FollowSnsNeuronsModal.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

List the topics that the user can follow for an SNS project.
* Rename FollowTopicSection to FollowNnsTopicSection
* New component FollowTopicSection agnostic to NNS or SNS that renders the UI of a topic.
* Implement FollowSnsNeuronsModal. Access snsFunctions and render a FollowTopicSection for each followable section.
* New sns neuron util "functionsToFollow".
* Add test cases for FollowSnsNeuronsModal.
* Test new component FollowTopicSection

GIX-1111: Render SNS Topics

---

frontend/src/lib/canisters/ic-management/ic-management.errors.ts

Users sees a generic error message when he or she is not the controller of the canister.
The new error message is:
```
Server returned an error:
Code: 403 ()
Body: Only controllers of canister wxns6-qiaaa-aaaaa-aaaqa-cai can call ic00 method canister_status
Retrying request.
```
I believe they added the `()` and that messed up with the current parsing method.
* Change the way we parse the error message.
Updated tests with new error message.

Fix: Error message not canister controller

---

frontend/src/lib/derived/proposals.derived.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/neurons/NewFolloweeModal.svelte
frontend/src/lib/pages/Proposals.svelte
frontend/src/lib/stores/proposals.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/proposals.utils.ts
frontend/src/tests/lib/pages/Proposals.spec.ts
frontend/src/tests/lib/utils/proposals.utils.spec.ts

The filter to show only the ones you can vote on was being used even though the user was not logged in.
Therefore, logged out users that had that turned on had an empty list of proposals.
* Pass the identity to the proposals utils to check whether it's present or not before hiding proposals.
* Load proposals when auth store changes.
* Add test cases for new scenario.
* Fix broken tests because of new API.

Fix: Proposals not shown

---

dfx.json
frontend/src/lib/components/launchpad/Proposals.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte
frontend/src/lib/i18n/en.json
frontend/src/tests/lib/components/launchpad/Proposals.spec.ts

Enable SNS-1 features!
* Launchpad.
* Universes in Tokens and Neurons.
* Set ENABLE_SNS to `true` for mainnet and staging.
* Hide Dissolve delay behind ENABLE_SNS_2 because it's not ready.
* Change wording for empty launchpad.

GIX-1104: Enable SNS-1

---

frontend/src/tests/lib/pages/Proposals.spec.ts
frontend/src/tests/lib/stores/proposals.store.spec.ts

I literally dreamed of that missing test this night (😅) so let's add a test for the new proposal filter `reload()` function.
- test `reload` store and call

test: reload filters

---

frontend/src/lib/components/neurons/ConfirmDissolveDelay.svelte
frontend/src/lib/components/neurons/SetDissolveDelay.svelte
frontend/src/lib/components/sns-neurons/ConfirmSnsDissolveDelay.svelte
frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte
frontend/src/lib/utils/neuron.utils.ts
frontend/src/tests/lib/components/sns-neurons/ConfirmSnsDissolveDelay.spec.ts
frontend/src/tests/lib/components/sns-neurons/SetSnsDissolveDelay.spec.ts
frontend/src/tests/lib/utils/neuron.utils.spec.ts

Calculation of the dissolve delay modal didn't consider the neuron's age.
* Make ageSeconds mandatory when calculating voting power.
* Fix broken tests after change.
* The rest of the tests were ok, the problem was that it was not used.

Fix: Voting power calculation nns

---

frontend/package-lock.json
frontend/src/lib/api/sns-governance.api.ts
frontend/src/lib/api/sns.api.ts
frontend/src/lib/components/neurons/FollowNnsTopicSection.svelte
frontend/src/lib/components/sns-neuron-detail/FollowSnsTopicSection.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/sns/FollowSnsNeuronsModal.svelte
frontend/src/lib/modals/sns/NewSnsFolloweeModal.svelte
frontend/src/lib/services/sns-neurons-check-balances.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/busy.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/error.utils.ts
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/api/sns-governance.api.spec.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/FollowSnsTopicSection.spec.ts
frontend/src/tests/lib/modals/sns/NewSnsFolloweeModal.spec.ts
frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts
frontend/src/tests/mocks/context-wrapper.mock.ts

User can add followees to SNS neurons.
NOTE: Followees are still not rendered.
* FollowsSnsNeuronModal uses a new component: FollowSnsTopicSection to render each Topic.
* FollowSnsTopicSection uses a new Component NewSnsFolloweeModal to created the new followee.
* NewSnsFolloweeModal uses a new sns-neuron service addFollowee.
* In sns-neurons.services, addFollowe uses new apis "setFollowees" and "querySndNeuron" and a new sns-neuron utils "followeesByFunction"
* In sns.api.ts, rename "querySnsNeuron" to "getSnsNeuron". This api raises an error if the neuron is not found. The one we use so far.
* In sns.api.ts, new api "querySnsNeuron" that returns `undefined` if neuron does not exist. Useful to check easily whether a followee exists.
* In sns-governance.api.ts, New api "setFollowees".
* …

GIX-1113: Add SNS Neuron Followee

---

frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/proposals.utils.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerActionsEntry.spec.ts
frontend/src/tests/lib/utils/proposals.utils.spec.ts

Users should not see the word Swap in the nns-dapp.
We want to show also the properties of the actions that are undefined. We show them as `NULL`.
* Include `undefined` as the type of action field value that we support.
* Check when the action is OpenSnsTokenSwap and show a different title.
* Add test for new support for `undefined` properties in action fields.
* Add test to check that ProposalProposerActionsEntry renders `NULL` for undefined properties.

FIx: Rename action OpenSnsTokenSwap

---

Cargo.lock
frontend/src/lib/components/common/Json.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerPayloadEntry.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerActionsEntry.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerPayloadEntry.spec.ts
frontend/src/tests/lib/utils/utils.spec.ts
rs/Cargo.toml
rs/src/proposals.rs

The payload of the proposal when upgrading a canister has an arg property. This property is a candid blob that in the case of Internet Identity is important to deserialize to be able to properly validate the proposal.
* Create a helper that given the value of "arg" and the canister id returns a json representation of it.
* In ProposalProposerPayloadEntry.svelte expand the object to parse any string value that is JSON.
* Util "expandObject" that parses JSON strings of an object.
* Render "null" instead of "NULL" for undefined properties in payloads. For consistency with "null" in JSON stringify.
* Json component uses "stringifyJson" util instead of it's own "stringify".
* CSS Style changes in Json component.
* Test new use cases for ProposalProposerPayloadEntry.
* Test new util …

Fix: Decode II proposal payload's arg

---

frontend/package-lock.json
frontend/src/lib/pages/CanisterDetail.svelte

Looks ugly too now, flatten the skeleton card on caniste detail island.
I also use this PR to bump the gix cmp to update the button colors as in the reviewed design.
Afterwards

style: fix skeleton card display on canister detail

---

frontend/package-lock.json
frontend/src/lib/components/launchpad/Projects.svelte
frontend/src/lib/components/launchpad/Proposals.svelte
frontend/src/lib/components/project-detail/ParticipateButton.svelte
frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/src/lib/components/project-detail/ProjectMetadataSection.svelte
frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
frontend/src/lib/components/proposal-detail/Proposal.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerInfoSection.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerPayloadEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
frontend/src/lib/components/proposal-detail/ProposalVotingSection.svelte
frontend/src/lib/components/proposals/ProposalCard.svelte
frontend/src/lib/components/ui/Logo.svelte
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/routes/(app)/project/+layout.svelte
frontend/src/routes/(app)/proposal/+layout.svelte
frontend/src/tests/lib/components/project-detail/ProjectInfoSection.spec.ts
frontend/src/tests/lib/components/project-detail/ProjectMetadataSection.spec.ts

Review the design of the "Proposal" and "Project" detail views as defined by the designer.
- set few text as `.description`
- use `.content-cell-island` and adapt spacing when needed
- fix `BottomSheet` usage in "Project" view to present a bottom sheet only when needed - i.e. to not present an empty bottom sheet
- extract title, logo, url, description of project to a new `ProjectMetadataSection` to present these information in a separate spot
- adapt skeleton loader accordingly
- I pinged designers about the fact that there is not much accessibility difference between cards that are clickable and cards that are static - contain information only. This is currently discussed.
- There is also an on going discussion on the description of the Project that can becomes quite long
- I also asked …

feat: proposal and project detail new design

---

frontend/src/lib/components/accounts/WalletSummary.svelte
frontend/src/lib/routes/Wallet.svelte
frontend/src/tests/lib/components/accounts/WalletSummary.spec.ts
frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts

Make account title dynamic when user scroll to keep important information visible.
- use intersection directive to display either the "Account" title or the name of the account and its balance
- fix account title not set when "Wallet" page accessed directly
- fix neuron detail test skipped

feat: account title

---

frontend/package-lock.json
frontend/src/app.d.ts
frontend/src/lib/components/accounts/WalletSummary.svelte
frontend/src/lib/components/canister-detail/AddCanisterControllerButton.svelte
frontend/src/lib/components/canister-detail/DetachCanisterButton.svelte
frontend/src/lib/components/canister-detail/RemoveCanisterControllerButton.svelte
frontend/src/lib/components/common/Footer.svelte
frontend/src/lib/components/neuron-detail/NnsNeuronMetaInfoCard.svelte
frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
frontend/src/lib/components/project-detail/ProjectMetadataSection.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
frontend/src/lib/directives/intersection.directives.ts
frontend/src/lib/modals/canisters/CanisterDetailModals.svelte
frontend/src/lib/modals/canisters/RemoveCanisterControllerModal.svelte
frontend/src/lib/pages/CanisterDetail.svelte
frontend/src/lib/types/canister-detail.context.ts
frontend/src/lib/types/canister-detail.modal.ts
frontend/src/lib/types/intersection.types.ts
frontend/src/lib/utils/events.utils.ts
frontend/src/tests/lib/components/canister-detail/ControllersCardTest.svelte
frontend/src/tests/lib/components/canister-detail/DetachActionButtonTest.svelte
frontend/src/tests/lib/components/canister-detail/RemoveCanisterControllerButton.spec.ts
frontend/src/tests/lib/components/canister-detail/RemoveCanisterControllerButtonTest.svelte
frontend/src/tests/mocks/canisters.mock.ts

Replace usage of context store to trigger the canister details modal opening, closing and passing extra data.
- use `CustomEvent` to trigger opening of modals used in "Canister" detail page
- adapt `Intersection` types to pattern use in this PR
- remove few unused imports

feat: canister detail modals with custom event

---

frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
frontend/src/lib/components/neurons/FollowNnsTopicSection.svelte
frontend/src/lib/components/sns-neuron-detail/FollowSnsTopicSection.svelte
frontend/src/lib/components/sns-neuron-detail/SnsFollowee.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte
frontend/src/lib/components/sns-neurons/SnsNeuronCardTitle.svelte
frontend/src/lib/components/summary/PrincipalText.svelte
frontend/src/lib/components/ui/Hash.svelte
frontend/src/lib/components/ui/IdentifierHash.svelte
frontend/src/lib/components/ui/SkeletonFollowees.svelte
frontend/src/lib/components/ui/TagsList.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsModal.svelte
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/sns-functions.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/components/sns-neuron-detail/FollowSnsTopicSection.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.spec.ts
frontend/src/tests/lib/components/ui/Hash.spec.ts
frontend/src/tests/lib/components/ui/TagsList.spec.ts
frontend/src/tests/lib/components/ui/TagsListTest.svelte
frontend/src/tests/lib/modals/sns/FollowSnsNeuronsModal.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts
frontend/src/tests/lib/stores/sns-functions.store.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

User can see the followees of the sns neurons.
* Extracted UI component TagsList from Followee component.
* Followee component uses new TagsList component
* New sns neuron util followeesByNeuronId.
* SnsNeuronFolloweingCard uses new util followeesByNeuronId and renders new component SnsFollowee.
* SnsFollowee is the counterpart of Followee and implements TagsList for sns neurons.
* New prop to Hash component to show or not the copy button. It was needed for Followee.
* New skeleton component SkeletonFollowees. Used while nsFunctions are loaded in sns neuron details.
* Add error management in loadSnsNeurvousSystemFunctions.
* Test new TagsList component
* Test new sns neuron util followeesByNeuronId and followeesByFunction (which was not tested)
* Test new functionality in …

GI-1114: List SNS Followees

---

frontend/src/lib/components/sns-neuron-detail/FollowSnsTopicSection.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/stores/busy.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/sns-neuron-detail/FollowSnsTopicSection.spec.ts
frontend/src/tests/lib/modals/sns/FollowSnsNeuronsModal.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts

User can unfollow other neurons in SNS projects.
* New sns neuron service "removeFollowee".
* FollowSnsTopicSection uses new service to unfollow a neuron and access store to reload the neuron after calling the service.
* Fix broken test FollowSnsNeuronModal because now it needs to be wrapped with the sns neuron context.
* Add test case to FollowSnsTopicSection to unfollow a neuron.
* Test new sns neuron service removeFollowee.

GIX-1112: Remove SNS Followee

---

frontend/src/lib/i18n/en.json
frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsModal.svelte
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/modals/sns/FollowSnsNeuronsModal.spec.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

Users can set followees for all topics using on nervous system function.
* Remove the util functionsToFollow that filtered out the function with id 0.
* In the service loadSnsNervousSystemFunctions, change the name of the function with id 0 from "Unspecified" to "All Topics" to be more user friendly.
* Remove test for functionsToFollow.
* Fix test that show topic with id 0.

Chore: Enable Unspecific topic in sns

---

frontend/src/lib/directives/debug.directives.ts
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/lib/pages/SnsWallet.svelte
frontend/src/lib/stores/debug.store.ts
frontend/src/lib/stores/sns-transactions.store.ts
frontend/src/lib/utils/anonymize.utils.ts

To be able to debug we need information. The SNS data was not added to the debug store and therefore not accessible throght the debug prompt.
* Add sns related stores to debug store.
Not applicable

GIX-1043: Add sns stores to debug store

---

frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
frontend/src/lib/components/sns-neuron-detail/SnsFollowee.svelte
frontend/src/lib/components/ui/Hash.svelte
frontend/src/lib/components/ui/TagsList.svelte
frontend/src/lib/directives/debug.directives.ts
frontend/src/tests/lib/components/ui/TagsList.spec.ts

User has not yet access to the voting history of followees in SNS. Therefore, we should not render it as a button.
* TagsList doesn't render a button. Just the slot for the title.
* Followee component passes a button as title to TagsList.
* SnsFollowee component passes an h5 as title to TagsList.

Chore: Disable Followee button SNS

---

rs/src/proposals.rs

User can see the latest "memory_migration_batch_size" argument name used when upgrading the II canister.
* Add "memory_migration_batch_size" to InternetIdentityInit hardcoded type.
Not applicable, only UI changes.

Chore: Update Internet Identity Init type

---

frontend/__mocks__/$app/stores.ts
frontend/src/lib/constants/routes.constants.ts

Last version of SvelteKit (bumped in #1612) contains another breaking changes. The route id of the `$app/stores.page` store now also prefix route group with `/`.
Used to be: `(app)/neuron`
Is now:  `/(app)/neuron`
This breaks our route matcher `pathForRouteId`
- the related constant for the group `(app)` should be adapted to `/(app)`
We cannot detect this with unit test because we have to mock the SvelteKit store. We could have detect it with e2e tests. I detected it on the "Sns neuron detail" page because the Skeleton did not disappeared.

fix: page store path for SvelteKit breaking changes

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/lib/utils/page.utils.ts
frontend/src/tests/lib/utils/page.utils.spec.ts

Enable followee management and increasing dissolve delay.
* Add comment in `pathForRouteId`
* Remove ENABLE_SNS_2 from SnsNeuronFollowingCard and IncreaseSnsDissolveDelayButton

Chore: Enable followees and dissolve delay in SNS neurons

---

frontend/package-lock.json

ic-js `v0.10.0` has been released so we can jump to `next` versions.
- bump nns, sns, cmc and utils to next / nightly versions

build: bump ic-js to next

---

frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte
frontend/src/lib/constants/constants.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/date.utils.ts
frontend/src/tests/lib/utils/date.utils.spec.ts

Replace static sns min. dissolve delay with dynamic prop.
Slider wasn't updated because its destiny is not clear yet.
- util `secondsToDissolveDelayDuration`
- `secondsToDissolveDelayDuration`

feat: secondsToDissolveDelayDuration

---

frontend/src/lib/components/proposal-detail/ProposalVotingSection.svelte
frontend/src/tests/lib/components/proposal-detail/ProposalVotingSection.spec.ts

- When the proposal reward status has settled, the `ballots` array of the proposal objects are emptied in the canister to spare memory space. 
- The `recentBallots` provided in the neurons can contain up to 100 proposal information
Above two statements could lead to a display misinterpretation in NNS-dapp. Indeed, the frontend might not be able to determine if a neuron has voted and if proposal that has settled are browsed, it might also display these with an incorrect labelling such as having a dissolve delay < 6 months while it is not the case.
Therefore, at least as shorterm solution, we have decided to hide the "Neurons" voting pane from the proposal detail page when, and only when, the reward status as settled.
Not displaying misinterpreted information is safer that displaying these. …

feat: if proposal reward status has settled hide vote pane from detail page

---

frontend/src/lib/i18n/en.json

The T cycles fee to create a canister is 0.1 not 1 as displayed in a static hint we are displaying on the interactive modal to create canister.
Source: https://internetcomputer.org/docs/current/developer-docs/deploy/computation-and-storage-costs/
Resolves #1635
- update i18n label with cycles

feat: update tcycles fee in static label

---

rs/src/proposals.rs

This PR is required so that the next II migration proposal argument is properly rendered.
* Change of the `InternetIdentityInit` rust type to be in line with the latest II release.
* There is no test for this typing I assume?

chore: update II init argument type

---

build.sh

WASM too big.  Zipping helps.
- gzip the wasm file
Deployed nns-dapp to small12 by proposal using thiscompressed wasm code.

Zip the wasm

---

frontend/src/lib/pages/SignInAccounts.svelte
frontend/src/lib/pages/SignInCanisters.svelte
frontend/src/lib/pages/SignInNeurons.svelte
frontend/src/lib/themes/global.scss
frontend/src/routes/+layout.svelte

We have build reproducibility with last releases.
CI: hash a2c0186f49a3d3201575ade95bc6610e4a30ebe6 for  https://github.com/dfinity/nns-dapp/actions/runs/3764587278
Local: hash 187a34a440503da62c161e679baa02b431455c17c2b6e51bc433d63dbcae2d8f
Root cause of the issue is the build of the NNS-dapp frontend that generates different entries ("keys") in the ouputed `vite-manifest.json`.
The real solution still needs to be found but to fix the reproducibitility of current state we can avoid the use of CSS mixin in favor of a global style.
If a global CSS style is used => a unique  CSS is generated
If mixins are used => Svelte or Vite tries to optimize the CSS and generate a single outputed CSS for the common code. In this process it generates a file and the algorithm uses the name of the first …

style: extract global style to ensure build reproducibility

---

frontend/src/lib/utils/sns-transactions.utils.ts
frontend/src/tests/lib/components/accounts/SnsTransactionCard.spec.ts
frontend/src/tests/lib/utils/sns-transactions.utils.spec.ts

Differentiate the transaction of staking and topping up SNS neurons in the Wallet page.
* Add case in `getSnsTransactionType` for sns transactions that differentiates staking and topping up a neuron.
* Add test for new case.

GIX-1151: Identify SNS top up neuron transaction

---

frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.svelte
frontend/src/lib/modals/sns/neurons/SnsStakeNeuronModal.svelte
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/utils/token.utils.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/lib/services/sns-accounts.services.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts
frontend/src/tests/lib/utils/token.utils.spec.ts

Fix two bugs:
* Rounding issue in SNS transactions.
* Account balance was not updated after staking or topping up sns neurons.
* Change implementation of `numberToE8s` to use `TokenAmount.fromNumber`.
* Call `loadSnsAccounts` service after staking or topping up sns neuron.
* Fix test.
* Add test for new test cases of loadSnsAccounts call.
* Add tests for token utils `numberToE8s`.

Fix: Rounding error in sns transactions

---

frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

User can't disburse sns neurons because data shows "WhenDissolvedTimestampSeconds" state.
* Check whether WhenDissolvedTimestampSeconds is in the past and set it to Unlocked state.
* Add test with new case.

Fix: Dissolved neuron if dissolved in the past

---

frontend/package-lock.json

Under certain circonstances (see related PRs) the "voting history" on the "neuron detail" view was not active /refreshed. 
This PR bumps the gix-cmp that contains a fix for the `InfiniteScroll` component that, per extension, resolve the issue.
- bump gix-cmp

fix: neuron voting history infinite scroll not triggered

---

frontend/src/lib/components/ic/AmountDisplay.svelte
frontend/src/lib/components/neurons/NnsNeuronCard.svelte
frontend/src/lib/components/neurons/NnsNeuronCardTitle.svelte
frontend/src/lib/components/neurons/SelectNeuronsToMerge.svelte
frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
frontend/src/lib/components/sns-neurons/SnsNeuronCardTitle.svelte
frontend/src/lib/modals/neurons/VotingHistoryModal.svelte
frontend/src/lib/pages/NnsNeurons.svelte
frontend/src/lib/themes/mixins/_neuron.scss
frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts

- inline neuron card big amount (`999'999'999.0000000 ICP`)
- refactor `NeuronCard` to `NnsNeuronCard`
- align Sns neuron card style (title and same inline for values)

feat: neuron card icp inline and align sns card style

---

frontend/src/lib/components/neuron-detail/NnsNeuronHotkeysCard.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/neurons/ConfirmRemoveCurrentUserHotkey.svelte
frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/neuron-detail/NnsNeuronHotkeysCard.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts

User should confirm before removing itself from hotkeys. Both NNS and SNS neurons.
* Rename NeuronHotkeysCard.svelten to NnsNeuronHotkeysCard.svelte.
* Add extra function to [Sns / Nns]NeuronHotkeysCard called "maybeRemove" to check whether it should open the modal or remove hotkey.
* New UI component ConfirmRemoveCurrentUserHotkey to share modal in Sns and Nns.
* New state `showConfirmationHotkey` in [Sns / Nns]NeuronHotkeysCard to open ConfirmRemoveCurrentUserHotkey.
* Change tests after file rename.
* Add test case to NnsNeuronHotkeysCard.
* Add test case to SnsNeuronHotkeysCard.

GIX-1137: Confirmation remove current user hotkey

---

frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte
frontend/src/lib/constants/neurons.constants.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/neurons/NnsStakeMaturityModal.svelte
frontend/src/lib/services/neurons.services.ts
frontend/src/tests/lib/components/neuron-detail/NnsNeuronMaturityCard.spec.ts
frontend/src/tests/lib/modals/neurons/NnsStakeMaturityModal.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts

Users with hardware wallet can turn auto-stake maturity on and off and use the endpoint stake_matyrity instead of merge_maturity with the redirection
* Enable AutoStakeMaturity always.
* Add constant with new HW version.
* Change message of version not supported to make it more general.
* NnsStakeMaturityModal uses always service stakeMaturity.
* Add a version assert in service stakeMaturity.
* Change test for NnsStakeMaturityModal
* Add case for stakeMaturity service.
* Add case for autoStakeMaturity service.

Feat: Support stake maturity hw

---

frontend/src/lib/components/launchpad/Proposals.svelte
frontend/src/lib/components/proposals/Countdown.svelte
frontend/src/lib/components/proposals/NnsProposalCard.svelte
frontend/src/lib/components/proposals/ProposalCard.svelte
frontend/src/lib/components/proposals/ProposalsList.svelte
frontend/src/tests/lib/components/proposals/Countdown.spec.ts
frontend/src/tests/lib/components/proposals/NnsProposalCard.spec.ts
frontend/src/tests/lib/components/proposals/ProposalCard.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/actions/SplitSnsNeuronButton.spec.ts

Refactor the ProposalCard into NnsProposalCard and a NNS agnostic one ProposalCard.
Preparing for adding Voting for SNS projects.
* Split current ProposalCard into two: NnsProposalCard and ProposalCard.
* New ProposalCard expects primitive props and renders them in the UI.
* Refactored the rendering of ProposalCard to use KeyValuePair component.
* New NnsProposalCard expects a proposal, extracts the details and renders a ProposalCard.
* Refactor ProposalCountdown to Countdown and pass only the timestamp deadline in seconds to make it agnostic of NNS Proposal.
* Tests for both splited components ProposalCard and NnsProposalCard.
* Fix other tests after change in props and renamings.
* Fix warning during test.

Refactor: ProposalCard agnostic of NNS

---

frontend/src/lib/components/neuron-detail/Ballots/BallotSummary.svelte
frontend/src/lib/components/proposal-detail/NnsProposal.svelte
frontend/src/lib/components/proposal-detail/NnsProposalProposerActionsEntry.svelte
frontend/src/lib/components/proposal-detail/NnsProposalProposerDataSection.svelte
frontend/src/lib/components/proposal-detail/NnsProposalProposerInfoSection.svelte
frontend/src/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerInfoSection.svelte
frontend/src/lib/components/proposal-detail/ProposalProposerPayloadEntry.svelte
frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
frontend/src/lib/pages/ProposalDetail.svelte
frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerActionsEntry.spec.ts
frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerDataSection.spec.ts
frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerInfoSection.spec.ts
frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts
frontend/src/tests/lib/components/proposal-detail/NnsProposalTest.svelte
frontend/src/tests/lib/components/proposal-detail/ProposalProposerActionsEntry.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerInfoSection.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalProposerPayloadEntry.spec.ts

Split some cards in ProposalDetails into NNS specific and NNS agnostic.
Preparing for adding Voting for SNS projects.
* Change prop in ProposalSummary to be just the string summary.
* Split current ProposalProposerInfoSection into NnsProposalProposerInfoSection and ProposalProposerInfoSection.
* Split current ProposalProposerDataSection into NnsProposalProposerDataSection and ProposalProposerDataSection.
* Split current ProposalProposerActionsEntry into NnsProposalProposerActionsEntry and ProposalProposerActionsEntry.
* Split current ProposalProposerPayloadEntry into NnsProposalProposerPayloadEntry and ProposalProposerPayloadEntry.
* Rename Proposal.svelte to NnsProposal.svelte.
* Adapt tests after refactor.

Refactor: ProposalDetails components NNS agnostic

---

dfx.json
frontend/jest-setup.ts
frontend/src/lib/components/common/RouteModule.svelte
frontend/src/lib/components/proposals/ProposalsFilters.svelte
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/pages/NnsProposals.svelte
frontend/src/lib/pages/SnsProposals.svelte
frontend/src/lib/routes/Proposals.svelte
frontend/src/tests/lib/pages/NnsProposals.spec.ts
frontend/src/tests/lib/routes/Proposals.spec.ts

Set up the page for the SNS proposals list.
* Rename current pages/Proposals to NnsProposals
* New route component Proposals that renders project dropdown and then chooses either NnsProposals or SnsProposals.
* Add new feature flag: `ENABLE_SNS_VOTING`
* Fix tests after renaming and refactor.
* New test for new route Proposals.

GIX-1209: Setup SNS proposals list page

---

frontend/src/lib/routes/Proposals.svelte

The `referrerPath` was not forwarded when the Sns proposals list was introduced in PR #1690.
- fix "<Proposals> was created with unknown prop 'referrerPath'"

fix: <Proposals> was created with unknown prop 'referrerPath'

---

frontend/src/lib/components/proposal-detail/ProposalSummary.svelte

Hard to style with `:global` and without that a huge variety of test content but following style rules should improve a bit the display of the markdown of the proposals. Let me know if you have better ideas!
- tweak `:global` of the `.markdown`

style: proposal markdown display improvements

---

.github/workflows/docker-build.yaml

The threshold for ingress message size is lower than the threshold in the CI test.
- Update (lower) the ingress message size to the one given in the error message when making a proposal.
- Perhaps probe mainnet to detect if the threshold changes.
- Do an upgrade test; we could replicate the problem on a testnet when  installing via proposal instead of when installing directly.

chore: Update threshold

---

rs/src/proposals.rs

This PR updates the II init argument to include the flag to switch the archive from push to pull.
The II init arguments need to be rendered correctly -> types need to be up to date.
* Change the II init argument type.
No tests.

chore: Update II init arguments for archive pull integration

---

frontend/src/lib/i18n/en.json

According Maurice, the copyright year should always be current year.
- no over-engineering, just 2022 changed in 2023

feat: update copyright IC 2023

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte

Make `split sns neuron` and `increase sns stake` buttons publicly available.
- remove `ENABLE_SNS_2` flag from `split sns neuron` and `increase sns stake` buttons.

chore: remove sns2 flag from split neuron and increase stake

---

frontend/src/lib/utils/sns-neuron.utils.ts
frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts

The user would see an invalid simulated voting power calculation if it had some maturity or staked maturity.
* Take into account the staked_maturity_e8s_equivalent not maturity_e8s_equivalent for SNS neuron voting power.
* Add a test for the new case.

Fix: votingPower calculation for SNS neurons

---

frontend/src/lib/components/accounts/WalletSummary.svelte
frontend/src/lib/components/ic/AmountDisplay.svelte
frontend/src/lib/components/universe/ProjectBalance.svelte

We need the "copy" amount button because that's the way user can copy the effective amount with decimals. However, if there are many tokens, the "universe / token switcher" becomes crowded of "copy" buttons.
That's why this PR removes it from the switcher and add move the feature to wallet details.
This PR -> #1677 -> main

feat: remove "copy" amount from token switcher and move it to wallet details

---

frontend/src/lib/components/proposals/FiltersWrapper.svelte
frontend/src/lib/components/proposals/NnsProposalsFilters.svelte
frontend/src/lib/components/proposals/NnsProposalsList.svelte
frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
frontend/src/lib/modals/common/FilterModal.svelte
frontend/src/lib/modals/sns/proposals/SnsFilterStatusModal.svelte
frontend/src/lib/pages/SnsProposals.svelte
frontend/src/lib/services/sns-filters.services.ts
frontend/src/lib/stores/sns-filters.store.ts
frontend/src/tests/lib/components/proposals/NnsProposalsFilters.spec.ts
frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts
frontend/src/tests/lib/modals/sns/SnsFilterStatusModal.spec.ts
frontend/src/tests/lib/pages/SnsProposals.spec.ts
frontend/src/tests/lib/routes/Proposals.spec.ts
frontend/src/tests/lib/services/sns-filters.services.spec.ts
frontend/src/tests/lib/stores/sns-filters.store.spec.ts

User can filter proposal by decision status.
IMPORTANT: This PR includes setup of filters, button, modal and store. Not yet updating the proposals list.
Main changes:
* SnsProposalsFilters.svelte will include all filters buttons and render each modal.
* SnsFilterStatusModal.svelte shows filters and performs the actions in the store.
* sns-filters.store manages filters for SNS projects.
* loadSnsFilters in sns-filters.services.
The idea to store the Filter type in the store is to use the same concept for all SNS filters. Recall that SNS topics is not an enum, instead is the list of nervous functions. Which have a name, id and description.
I believe this is a good idea also for NNS. (for later) This way the UI doesn't care or know where the filters come from. Whether an enum or from a …

GIX-1212: Add Proposal Status filter

---

frontend/src/lib/pages/SignInAccounts.svelte
frontend/src/lib/pages/SignInCanisters.svelte
frontend/src/lib/pages/SignInNeurons.svelte
frontend/src/lib/themes/global.scss
frontend/src/routes/+layout.svelte

We have once again build reproducibility issue and despite the fact that we have fully remove the `vite-manifest.json` I suspect the style reproducibility we had to be the root cause.
Therefore undo the redo of the global style - i.e. undo PR #1671

style: undo scoped styles

---

frontend/src/lib/i18n/en.governance.json
frontend/src/lib/types/i18n.d.ts

Add labels and descriptions to `en.governance.json` for new proposal type Insert SNS-WASM Upgrade Path Entries.
- Added labels and descriptions to `en.governance.json` for new proposal type Insert SNS-WASM Upgrade Path Entries.
- Improved consistency of "SNS-WASM" canister terminology.

i18n: Add proposal type Insert SNS-WASM Upgrade Path Entries to en.governance.json

---

frontend/src/routes/(login)/+layout.svelte

We noticed a weird issue that leads - under edge case conditions - to the main "Login" elements not being removed from the DOM after navigation - i.e. the route being not fully destroyed.
This looks pretty similar to SvelteKit known issue https://github.com/sveltejs/kit/issues/5434
1. not the fastest login flow - i.e. after II has granted the authorization, fetching JS and navigating from "Login" to "Accounts" take a bit of time. I simulated this by adding 2000ms of delay in the `auth.store` that handles `onSuccess` callback
2. user on purpose does not stay in NNS-dapp tab while the sign-in is in progress
3. no JS should be cached
- open a browser in incognito (it seems to happen more often with Safari but locally could reproduce with Chrome too)
- go to google.com
- open new tab with …

fix: SvelteKit route not destroyed - "Login" over "Accounts" page

---

frontend/src/lib/components/common/MenuMetrics.svelte
frontend/src/lib/components/login/LoginHeader.svelte
frontend/src/lib/constants/environment.constants.ts

Until we use proper certified endpoints, no need to stress the network with such queries when we are developing.

feat: disable TVL display when developing

---

frontend/package-lock.json
frontend/src/lib/i18n/en.json
frontend/src/lib/services/neurons.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/neuron.utils.ts
frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts

Users can merge neurons controlled by HWs.
* Check HW version in mergeNeurons service.
* Change in isMergeableNeuron util, check whether neuron is controllable instead checking if it's HW controlled.
* Remove case of HW controlled neuron in getMergeableNeuronMessageKey.
* Change test case that allows merging HW controlled neurons.
* Add new test to check that mergeNeurons checks the HW version.

Chore: Enable Merge HW controlled neurons

---

frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte
frontend/src/lib/components/neuron-detail/actions/AutoStakeMaturity.svelte
frontend/src/lib/components/neuron-detail/actions/NnsAutoStakeMaturity.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.svelte
frontend/src/lib/components/sns-neuron-detail/actions/SnsAutoStakeMaturity.svelte
frontend/src/lib/i18n/en.json
frontend/src/tests/lib/components/neuron-detail/actions/NnsAutoStakeMaturity.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsAutoStakeMaturity.spec.ts

Users can see whether the neuron has auto-stake enabled or not for hotkey neurons.
* Move `NnsAutoStakeMaturity` outside the `isControlled` case in NnsNeuronDetail.
* Move `SnsAutoStakeMaturity` outside the `isControlled` case in SnsNeuronDetail.
* Add `disabled` to AutoStakeMaturity component.
* Use `disabled` new prop in `NnsAutoStakeMaturity` and `SnsAutoStakeMaturity`.
* Change "Staked" key to "Of which staked". See screenshot.
* Add a test case to check that checkbox is disabled for not controlled neurons. Both SNS and NNS.

Chore: Show auto-stake for non-controlled neurons

---

frontend/src/lib/i18n/en.json
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/modals/sns/neurons/SnsStakeNeuronModal.svelte
frontend/src/lib/modals/sns/neurons/SnsTransactionModal.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/lib/services/sns-parameters.services.ts
frontend/src/lib/services/transaction-fees.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/types/transaction.ts
frontend/src/tests/lib/modals/accounts/TransactionModal.spec.ts
frontend/src/tests/lib/modals/sns/SnsStakeNeuronModal.spec.ts
frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
frontend/src/tests/lib/services/sns-parameters.services.spec.ts

User should see an error if the amount to stake a sns neuron is lower than allowed.
Main change:
* Use validateAmount of TransactionModal in SnsStakeNeuronModal.
Other changes:
* Call `loadSnsParameters` and `loadSnsTransactionFee` in SnsNeuronDetail. The service is the responsible to check whether it needs to load the resource or not.
* Change a `toString` for a `toText` in the principal in `loadSnsTransactionFee`.
* New test case in SnsStakeNeuronModal.
* Change test case in SnsNeuronDetail.
* New test case in loadSnsParameters.

Fix: Check minimum sns neuron stake

---

frontend/src/lib/components/accounts/SelectAccountDropdown.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/lib/modals/sns/neurons/SnsStakeNeuronModal.svelte
frontend/src/lib/pages/Launchpad.svelte
frontend/src/lib/proxy/sns.services.proxy.ts
frontend/src/lib/services/app.services.ts
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
frontend/src/tests/lib/components/launchpad/Projects.spec.ts
frontend/src/tests/lib/pages/ProjectDetail.spec.ts
frontend/src/tests/lib/services/app.services.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts

Two main motivations:
* Handle gracefully when something is not loaded (such as accounts for the transaction modal)
* Load resources in the page that they are needed, to reduce load in the IC.
* Use a Spinner in SelectableDropdownAccount when accounts are being loaded.
* Move "loadSnsSwapCommitments" to Launchpad instead of on init.
* "loadSnsSwapCommitments" does not query commitments again if they already loaded.
* Add test for spinner in SelectableDropdownAccount.
* New test for loadSnsSwapCommitments.

GIX-1192: Handle overload in UI

---

build-frontend.sh

We are taking steps towards reproducible builds.
Because the frontend builds much faster than the entire canister, we separately check if the assets tarball is reproducible.
There are several potential reasons why the frontend tarball might differ:
1. The contents are different.
2. The same contents create different `.tar` archives because different metadata is included.
3. The same archive is compressed differently because different metadata is included.
Add additional flags to the tar command to make the archive (more) reproducible.
I found these on https://reproducible-builds.org/docs/archives/
This change improves #2 from the list above.
When inspecting the generated tarballs, I previously noticed that the same content produced different tarballs and I didn't see that after adding …

Additional tar flags to improve nns-dapp frontent reproducibility

---

scripts/tarxzhash

We are trying to make the build reproducible.
We are first working on the assets.tar.xz with the frontend build.
In my investigation why the build isn't reproducible, I've found it useful to automate the extraction and apply SHA256 at different level of the archive.
Adds a shell script which extracts a .tar.xz and computes the SHA256 of the .tar.xz, the .tar and the individual files.
Ran the tool on the assets.tar.xz generated by build-frontend.sh.

Add a tool to compute the SHA256 of a .tar.xz at different levels.

---

build-rs.sh
build.sh

We now have two rust canisters.  They need the same commands to run so factor out the build script.
- Move the Rust build steps into a separate script.
- Both yield `e72857b431955309b4b0d1d8423320f32bee9a6178db46b177ef9b0d4b16e549`
- This PR:  https://github.com/dfinity/nns-dapp/actions/runs/4025418459/jobs/6918615826
- Main: https://github.com/dfinity/nns-dapp/actions/runs/4024511085/jobs/6916629090

refactor: Factor out the rust build command

---

frontend/src/lib/pages/Launchpad.svelte
frontend/src/tests/lib/pages/Launchpad.spec.ts

Non logged in users can access Launchpad.
* Do not call loadSnsSwapCommitments if not logged in.
* Add test for this case.

Fix: Publich Launchpad

---

frontend/src/lib/api/sns-ledger.api.ts
frontend/src/lib/api/sns.api.ts
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/tests/lib/api/sns-ledger.api.spec.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/services/sns-accounts.services.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts

Prepare for SNS support for hardware wallets.
To ensure that HW users signs what's really happening, we added the fee in the SNS transactions.
* Add "fee" param to sns.api function "stakeNeuron".
* Add "fee" param to sns-ledger.api function "transfer".
* Read fee and fail if not present in sns-accounts service "snsTransferTokens".
* Read fee and fail if not present in sns-neurons service "stakeNeuron".
* Upgrade ic-js
* Adapt tests to new requirement.

Chore: Add fee in SNS transactions

---

scripts/tarxzhash

The tarxzhash script leaves behind temp dirs if called on more than 1 input.
I assumed that trap would take care of all of them but setting a trap for a signal seems to replace the previous trap.
Explicitly remove the temp dir for each input.
Called manually with 2 inputs, both with and without -k arg.

Explicitly remove temp dir in tarxzhash

---

rs/backend/src/proposals.rs

The properties of the `SnsVersion` directly represent the WASM hashes  ([bug report](https://dfinity.slack.com/archives/C01S03NBM7S/p1675290921397399))
- calculate_hash_string -> format_bytes

fix: avoid hash generation for hash string

---

frontend/src/lib/api-services/neurons.api-service.ts
frontend/src/lib/api/governance.api.ts
frontend/src/lib/services/neurons.services.ts
frontend/src/tests/lib/api-services/neurons.api-service.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts

Setup the api service layer for neurons. This will allow us to use caching in upcoming PRs.
* New neuronsApiService object that is used in neuron.services and uses governance.api.
* The neuron services do not use the governance api anymore.
* Create types for all api function signatures to be used in neuronsApiService.
The idea is the following:
```
// Move from:
neuron service --> governance api
// To:
neuron service --> neuron api service (can provide caching) --> governance api
```
* Change tests in neuron.services.
* Add test for all neuron api services methods.

GIX-1187: Api Service Layer Setup

---

frontend/scripts/build.csp.mjs
frontend/src/lib/api/sns-aggregator.api.ts
frontend/src/lib/constants/environment.constants.ts

Add the sns aggregator url to the build step for nns-dapp frontend.
* Use exposed env var VITE_AGGREGATOR_CANISTER_URL in build.csp.mjs to set correct CSP rules.
* Use VITE_AGGREGATOR_CANISTER_URL to set SNS_AGGREGATOR_CANISTER_URL

GIX-1245: Add aggregator url to build step

---

frontend/src/tests/lib/services/neurons.services.spec.ts

I was trying to improve the listNeurons test and I noticed it didn't start with clean state.
It turns out there was a mixture of afterEach and beforeEach and together they didn't guarantee every test starts with a clean state.
1. In the list neurons test, verify the store before (as well as after) making the call.
2. Add one global `beforeEach()` which does all the state cleanup and remove all the other clean call.
Normally I wouldn't put these things in the same PR, but (1) demonstrates well why (2) is important so I kept it together.
only tests

Cleanup neurons.services.spec.ts

---

frontend/src/lib/components/accounts/CkBTCAccountsFooter.svelte
frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
frontend/src/lib/pages/CkBTCWallet.svelte
frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
frontend/src/tests/lib/pages/CkBTCWallet.spec.ts

Add CTA to execute a ckBTC transaction on wallet detail page.
- add footer action to instantiate ckBTC transaction and pass selected account
- modify dispatch on success to reload account data
- duplicate properties fee and token as [requested](https://github.com/dfinity/nns-dapp/pull/1812#discussion_r1095949160)

feat: ckBTC transactions on wallet detail page

---

frontend/src/tests/lib/services/neurons.services.spec.ts

In https://github.com/dfinity/nns-dapp/pull/1815 I discovered that two tests don't actually test what they're supposed to test. I didn't want to hide the fixes between many other changes so I made a separate PR.
Without the change, the error toast is actually about not being the controller of the neuron in one case, and about not merging neurons with the same ID in another case, rather than about the HW version being behind.
Push the mock neurons to the store before calling the function under test.
Additional minor change: Move resetAccountIdentity() to beforeEach. If we rely on the tests to clean this up, then if one of those tests fails, then other tests start failing as well for confusing reasons.
Changes are test-only. But https://github.com/dfinity/nns-dapp/pull/1815 will have …

Correct setup for HW version test in neurons.services.spec.ts

---

frontend/src/lib/utils/icrc-transactions.utils.ts
frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts

`getOldestTxIdFromStore` does not handle empty transactions which can lead to an "Cannot read properties of undefined (reading 'id')" issue.
Accounts -> SNS-1 -> Wallet -> No transactions -> Back -> Wallet -> Issue.
- `accountData.transactions` can be empty => `accountData.transactions[0]?.id` instead of `accountData.transactions[0].id`
Mainnet:
Reproduced locally:

fix: getOldestTxIdFromStore cannot read properties of undefined

---

frontend/src/tests/lib/services/neurons.services.spec.ts

There is no need to mock light weight objects like Svelte stores.
This change demonstrates using the real toasts store in `neurons.services.spec.ts` instead of mocking it.
Don't mock `$lib/stores/toasts.store` but instead let the neurons service put messages in the real store.
Subscribe to the store and have tests check the actual messages in the store.
Additionally we expect specific strings instead of just expecting there to be a toast.
Note that all expected toasts are error toasts even though the code uses a mix or toastsShow and toastsError to produce them.
only tests

Use real toasts store in neurons service test.

---

config.sh
dfx.json
frontend/src/lib/constants/canister-ids.constants.ts
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/utils/utils.spec.ts

Enable ckBTC ledger and index on mainnet and propose it in next version.
- enable ckBTC on **mainnet**
- enable ckBTC per default
- integrate ckBTC canister IDs configuration and fallback to mainnet canister IDs
- update order of fields in script
- add a new utils to test if a string is not null, not undefined and not empty

build: enable ckBTC ledger and index for mainnet

---

frontend/src/tests/lib/api-services/neurons.api-service.spec.ts

This makes it easier to mock individual functions on the governance api.
Import the governance API with `* as api` instead of all the functions into the global namespace.
test only change

GIX-1187: Import * as api instead of mocking individual functions.

---

frontend/src/routes/(app)/(u)/(detail)/wallet/+layout.svelte

For the same SvelteKit issue as for the "Login" page we noticed that on destroy of the CkBTCWallet page was not called. 
This fixes the issue for that particular page. We might want to have  a look to apply it to all routes later.
SvelteKit issue https://github.com/sveltejs/kit/issues/5434
- destroy layout and all children on navigation to "force" the destroy of the components

fix: force destroy wallet page

---

frontend/src/tests/lib/api-services/neurons.api-service.spec.ts
frontend/src/tests/mocks/auth.store.mock.ts
frontend/src/tests/mocks/neurons.mock.ts

Improve test coverage in neurons.api-service.spec.ts in anticipation of adding caching functionality.
Change the test to expect the service api functions to return the results from the api.
Also add some convenience functions for create mock identities and neurons.
test-only change

GIX-1187 For neurons api service, test call results, not just calls.

---

frontend/src/lib/components/accounts/TransactionCard.svelte

We noticed while testing an existing style issue in the alignment of the transaction on medium screen.

style: transaction list alignment

---

rs/sns_aggregator/src/assets.rs
rs/sns_aggregator/src/conversion.rs
rs/sns_aggregator/src/lib.rs
rs/sns_aggregator/src/state.rs
rs/sns_aggregator/src/types.rs
rs/sns_aggregator/src/types/ic_sns_governance.rs
rs/sns_aggregator/src/types/ic_sns_ledger.rs
rs/sns_aggregator/src/types/ic_sns_root.rs
rs/sns_aggregator/src/types/ic_sns_swap.rs
rs/sns_aggregator/src/types/ic_sns_wasm.rs
rs/sns_aggregator/src/types/slow.rs
rs/sns_aggregator/src/types/state.rs
scripts/did2rs.sh

The aggregator code is largely uncommented.  The code is not stable but a lot of the comments can be filled in already.
* Add a clippy for undocumented code.
* Exempt autogenerated code from the clippy.
* Document code
* Minor cleanup
There is no change in functionality.  Tests are sorely needed, but not in this PR.

Comments in aggregator code + cleanup

---

frontend/src/lib/api-services/neurons.api-service.ts
frontend/src/tests/lib/api-services/neurons.api-service.spec.ts

We want to reduce the load on the IC.
So we cache the response of certified queries (updates) for neurons.
This first implementation is as simple as possible with the following decisions:
* We only cache 1 list of neurons at a time for a single identity.
* We only cache certified responses.
* If we have a cached response, we also use it to respond to uncertified requests.
* We only cache resolved results and not in-flight promises.
* We only cache successful results and not errors.
Implement the neurons cache.
Extensive tests in `neurons.api-service.spec.ts`.

GIX-1187: Cache neurons response for 5 minutes in neurons api service

---

frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/tests/lib/pages/ProjectDetail.spec.ts

Two small bugs:
* Dissolve delay message for sns neurons.
* loadSnsSummary and loadSnsSwapCommitment were not called when user accessed ProjectDetail.
* Use minDissolveDelayDescription in SetSnsDissolveDelay.svelte
* Reload data in ProjectDetail when rootCanister changes. Loaded also when the user enters here.
* Fix broken test in ProjectDetail

Fix: Dissolve delay msg sns neuron & Project detail fix

---

rs/sns_aggregator/src/state.rs

The sns aggregator provides a logo URL for every SNS.  This can be used directly in HTML without a custom API call.  The code that generates this URL does not, however, handle the case where the logo is not provided.
- If the logo is not provided, provide an empty file.  Note: It can be debated whether we should return a 404, an empty file or some default image.  The priority now is to make the canister not break.  _maybe_ the 404 is the better option, as it allows fallback images, although it will print error messages in the console and red error messages shout "page is broken" which isn't nice either.  Maybe certify a pretty HTML message explaining that the SNS has no logo along with the 404 so that there are no error messages in the console and users have a good experience.  Once we …

Handle missing logo

---

rs/sns_aggregator/src/assets.rs
rs/sns_aggregator/src/index.html
rs/sns_aggregator/src/lib.rs

It would be useful for the sns aggregator to have a home page with basic health check information.
This PR adds a home page with nothing but a description and a link to the latest SNS info.  To be expanded and made pretty but as a question of priority, more data and pretty can come later.
* Add an index.html
* You can see it live here: https://s55qq-oqaaa-aaaaa-aaakq-cai.benchmarklarge.dfinity.network/ (note that the canister is being redeployed frequently so the link in the page will often show nothing.
Clicking the link goes to the JSON for the latest SNSs

Minimal landing page for the sns aggregator

---

dfx.json

Using, e.g., large05 results in the sns aggregator canister created on the NNS subnet. Using the BN URL as the network allows us to create the sns aggregator canister on the SNS subnet.

add static testnets with url names to support multiple subnets

---

frontend/src/lib/services/app.services.ts
frontend/src/lib/services/transaction-fees.services.ts
frontend/src/tests/lib/services/transaction-fee.services.spec.ts

Reduce number of update calls.
In this instance, the ICP transaction fee call.
* Remove `loadMainTransactionFee` call from app.services.ts
* Remove service `loadMainTransactionFee`.
* Remove test for service `loadMainTransactionFee`.

Chore: remove loadMainTransactionFee

---

frontend/src/lib/pages/NnsNeurons.svelte
frontend/src/lib/pages/NnsProposalDetail.svelte
frontend/src/lib/pages/NnsProposals.svelte
frontend/src/lib/services/app.services.ts
frontend/src/lib/services/neurons.services.ts
frontend/src/tests/lib/pages/NnsNeurons.spec.ts
frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
frontend/src/tests/lib/pages/NnsProposals.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts
frontend/src/tests/lib/routes/ProposalDetail.spec.ts
frontend/src/tests/lib/routes/Proposals.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/workflows/NnsProposalDetail.spec.ts
frontend/src/tests/workflows/NnsProposals.spec.ts

Reduce number of update calls.
Do not load neurons unless they will be used. To accomplish that, we load the neurons in the pages they are needed.
* Remove `listNeurons` from `app.services.ts`.
* Add `listNeurons` call in NnsNeurons.svelte.
* Add `listNeurons` call in NnsProposals.svelte if user is signed in.
* Add `listNeurons` call in NnsProposalDetail.svelte if user is signed in.
Minor change:
* `listNeurons` relied on the order of the responses to set the neurons. I changed that.
* Test new functionality in the page tests.
* Mock import in the routes tests.
* Test new functionality in the workflows NnsProposalDetail and NnsProposals.
* Test change in `listNeurons` service.

GIX-1187: List neurons per page

---

frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/tests/lib/pages/ProjectDetail.spec.ts

Reduce number of update calls.
In the Project Detail page, the project summary doesn't need to be loaded. But the commitment yes, only for logged in users.
* Call `loadCommitment` in ProjectDetail.svelte only for logged in users.
* Rename `loadSwapState` to `loadCommitment` in ProjectDetail.svelte helper.
* Add test for the new case.

Chore: Load commitment for logged in Project Detail

---

frontend/src/tests/lib/api/governance.api.spec.ts

Cleaning up before a test is safer than after because you never know which test ran before you and whether it also cleaned up after itself.
In governance.api.spec.ts reset all mocks before each test instead of after each test.
Test only change

In governance.api.spec.ts reset all mocks before each test

---

dfx.json

The medium testnets medium05 till medium10 now have the right topology (one NNS and two application subnets) to be used in SNS end-to-end tests. This PR adds the corresponding definitions to dfx.json for these medium testnets.

add medium testnet URL definitions to dfx.json

---

frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts

User sees a loading page when going directly to the neuron page deep link.
* Call `listNeuron` on mount of NnsNeuronDetail.svelte
* Add test to NnsNeuronDetail.svelte to check that api is called.
* Adapt test use the api mock instead of filling store direclty.

Fix: Neurons Detail Page issue

---

frontend/jest-setup.ts
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.svelte
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/constants/stores.constants.ts
frontend/src/lib/derived/selectable-universes.derived.ts
frontend/src/lib/derived/selected-universe.derived.ts
frontend/src/lib/pages/CkBTCWallet.svelte
frontend/src/lib/pages/SnsProposalDetail.svelte
frontend/src/lib/pages/SnsProposals.svelte
frontend/src/lib/routes/Accounts.svelte
frontend/src/lib/routes/ProposalDetail.svelte
frontend/src/lib/routes/Proposals.svelte
frontend/src/lib/services/$public/app.services.ts
frontend/src/lib/stores/feature-flags.store.ts
frontend/src/routes/(app)/(u)/(list)/proposals/+layout.svelte
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

Be able to manage feature flags in mainnet.
First step: feature flags are read from a store instead of env vars.
* New store `faetureFlagsStore` in `feature-flags.store.ts`.
* Export `FEATURE_FLAGS` in `environment.constants` instead of the individual flags.
* Read from the store when a flag wants to be read. These are most files changes.
* Change the jest.mock import to the whole `FEATURE_FLAGS` in the setup.
* Add a test to check that store is initialized to the env vars values.

GIX-1322: Setup featureFlags store

---

frontend/src/tests/lib/services/neurons.services.spec.ts

Small cleanup.
I didn't know about `get()` from svelte before.
Use `get()` on the toastsStore instead of subscribing.
Test only.

Use get() instead of subscribing to the toastsStore.

---

frontend/src/lib/stores/feature-flags.store.ts
frontend/src/tests/lib/components/ContextWrapperTest.svelte
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.spec.ts
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

We want to be able to toggle feature flags in mainnet.
* Add `setFlag` method to `overrideFeatureFlagsStore`.
* Expose `overrideFeatureFlagsStore` to `window`.
* Test for `setFlag` method in `overrideFeatureFlagsStore`.
* Test functionality of `overrideFeatureFlagsStore` in a component using the feature flag.

GIX-1322: Add featureFlags store to window and method

---

frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte
frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
frontend/src/lib/modals/accounts/CkBTCTransactionWalletModal.svelte
frontend/src/lib/modals/accounts/CkBTCWalletModals.svelte
frontend/src/lib/pages/CkBTCWallet.svelte
frontend/src/lib/types/wallet.context.ts
frontend/src/lib/types/wallet.modal.ts
frontend/src/tests/lib/components/accounts/CkBTCWalletContextTest.svelte
frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts

Ultimately the "Transaction" modal will / might most probably be used for ckBTC conversion too therefore we can move it - as we discussed in the footer, now worth the effort - and integrate it as the other modal.
For the same reason the "Receive" CTA can become a secondary button.
No functional changes.
- integrate button to open modal with ckBTC wallet footer
- call modal with an event 
- style "Receive" as secondary

refactor: ckBTC transation modal move and call

---

frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.svelte
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/derived/selectable-universes.derived.ts
frontend/src/lib/derived/selected-universe.derived.ts
frontend/src/lib/pages/CkBTCWallet.svelte
frontend/src/lib/pages/SnsProposalDetail.svelte
frontend/src/lib/pages/SnsProposals.svelte
frontend/src/lib/routes/Accounts.svelte
frontend/src/lib/routes/ProposalDetail.svelte
frontend/src/lib/routes/Proposals.svelte
frontend/src/lib/services/$public/app.services.ts
frontend/src/lib/stores/feature-flags.store.ts
frontend/src/routes/(app)/(u)/(list)/proposals/+layout.svelte
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

This makes using a feature flag more similar to how it was before https://github.com/dfinity/nns-dapp/pull/1874.
It let's you import and write `$ENABLE_SNS_2` instead of `$featureFlagsStore.ENABLE_SNS_2`.
Export feature flags from the module as individual boolean stores.
Also add a type `FeatureKey = keyof FeatureFlags<boolean>` for convenience.
Added a test that each defined feature flag is also exported. And updated existing tests.

Export individual feature flags

---

frontend/jest-setup.ts
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/stores/feature-flags.store.ts
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

Do not allow to set any feature flags. Ideally, we would only allow the ones approved by security.
* Rename `assertFeatureFlag` to `assertValidFeatureFlag` in `features-flags.store.ts`.
* Add list of EDITABLE_FEATURE_FLAGS.
* Check that flag is included in EDITABLE_FEATURE_FLAGS in `assertValidFeatureFlag`.
* Test new functionality.

Chore: Restrict feature flags functionality

---

Dockerfile

The dockerfile no longer uses the "build" container. The default docker target is scratch, which uses:
```
FROM scratch AS scratch
COPY --from=build_nnsdapp /build/nns-dapp.wasm /
COPY --from=build_nnsdapp /build/assets.tar.xz /
COPY --from=build_aggregate /build/sns_aggregator.wasm /
COPY --from=build_aggregate /build/sns_aggregator_dev.wasm /
```
Some users _may_ be using docker, giving `build` explicitly as the target.  If so, now is the time to say.  We can look at your use case and figure out the best way forwards.
- Remove the `build` target from docker.
See CI

Rm unused docker container

---

frontend/src/lib/stores/feature-flags.store.ts
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

Making it easier to find the correct feature flags in the console.
By having the names of the feature flags directly on the object, instead of passed as strings, the console will autocomplete those names for you.
Enabling a feature now goes like this:
`> __featureFlags.ENABLE_SNS_AGGREGATOR.overrideWith(true);`
You can also get a list of features and states like this:
```
> __featureFlags.list()
ENABLE_CKBTC_LEDGER false (override undefined default false )
ENABLE_CKBTC_RECEIVE false (override undefined default false )
ENABLE_SNS_2 true (override undefined default true )
ENABLE_SNS_AGGREGATOR false (override undefined default false )
ENABLE_SNS_VOTING true (override undefined default true )
```
Expose the feature flags in the console with fields with the names of the features on the …

Expose feature flags in the console in a way that allows for autocomplete

---

frontend/jest-setup.ts
frontend/package-lock.json
frontend/package.json
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

It can be useful to debug a test if some expectations have a custom message conveying some state.
NPM package  `jest-expect-message` lets you pass a second (message) parameter to expect which is display when the expectation fails.
This is especially useful when an expectation inside a for loop fails because the message can indicate which iteration of the loop fails.
It's also useful when helper functions do expectation.
Install jest-expect-message.
And use it as an example in `feature-flags.store.ts` to indicate which feature flag isn't exported if any of them isn't.

Install jest-expect-message

---

frontend/src/lib/derived/selected-universe.derived.ts
frontend/src/lib/stores/feature-flags.store.ts
frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
frontend/src/tests/lib/stores/feature-flags.store.spec.ts

1. `npm run lint` was accidentally removed from `npm run check` (in https://github.com/dfinity/nns-dapp/pull/1397) and therefore not run on CI.
2. So we failed to catch an unused variable and were using a store (always true) instead of the value of the store (true or false).
The specific issue is that we always consider ENABLE_CKBTC_LEDGER to be true for the purpose of determining the selectedUniverseId.
1. Correctly use the value of the ENABLE_CKBTC_LEDGER.
2. Add a unit test where we disabled ENABLE_CKBTC_LEDGER and verify that it affects the selected universe.
3. Change `feature-flags.store.ts` to allow overriding non-editable feature flags.
4. Add unit tests to make sure that non-editable feature flags still can't be set through the console interface.
Unit tests in …

Fix actually using the ENABLE_CKBTC_LEDGER store.

---

Cargo.lock
rs/sns_aggregator/Cargo.toml
rs/sns_aggregator/sns_aggregator.did
rs/sns_aggregator/src/lib.rs

We would like to monitor the cycle balance and usage of the `sns_aggregator` canister.  The balance is available externally to controllers only, so we need to make the relevant API call ourselves to get the canister info and return the value.
- Add a method to get the standard canister info.
- Add documentation to the Notion [on-call page](https://www.notion.so/SNS-Aggregator-Change-Log-6bcd4370e5704cc08c473975c8252fdf?pvs=4#8050c6b7660442a8a1ca6252b076ca4b) for the sns-aggregator.
Note: This is the same underlying call made by a number of other canisters.  E.g. here is the call being made by the sns swap canister: https://github.com/dfinity/ic/blob/master/rs/sns/swap/src/clients.rs#L167
Note: The call changes no values, however the inner api call to get the balance still needs to be an …

Expose cycles

---

frontend/package.json
frontend/src/lib/components/common/Json.svelte
frontend/src/tests/lib/components/common/Json.spec.ts

I was seeing lint warnings about the Json element having a click event handler but not a key event handler.
Looking at the element I also noticed quite some code duplication.
A different element was rendered when the json is expanded than when it is collapsed.
This results in the element losing focus when expanded or collapsed, which means even if it has a key event handler, you can't press space/enter multiple times to collapse/expand multiple times.
Button elements automatically receive click events when space/enter is pressed so changing the element to a button solved the original problem.
1. Changed the element to be a button so it receives click events on space/enter.
2. Removed code duplication so the button retains focus when rerendered.
3. Added a test to make sure the button …

Allow Json expand/collapse with keyboard navigation

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/reproducible-assets.yaml
e2e-tests/.npmrc
e2e-tests/package.json
frontend/package.json
proxy/.npmrc
proxy/package.json

Using an incompatible version of nodejs breaks builds, formatting and lockfiles.
- Cause node to fail if an incompatible version of nodejs or npm is used.
- Note: I have specified this individually in the .npmrc of each node project.  We may want to make a global entry, but must the n also remember to include it in docker builds that take just one directory and named other files.
- Specify the version of nodejs in CI.
- Note: It would be nice to be able to read the node version from the package.json.  Ideally that should be done in both CI and in the dockerfile.  Should be possible, but in another PR.

Enforce npm and nodejs version range

---

frontend/src/tests/lib/pages/SnsNeurons.spec.ts

Having `it.only` merged was most likely a mistake.
The other tests pass with `.only` removed.
Replace `it.only` with just `it` in SnsNeurons.spec.ts.
pass

Remove it.only from SnsNeurons.spec.ts

---

frontend/src/lib/api/sns.api.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/pages/ProjectDetail.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/stores/sns.store.spec.ts

Provide up to date data on how the sale is going.
SNS Aggregator takes a while to update. Therefore, for the total amount of commitments we shouldn't rely on it for users that want to participate.
* New sns api function `querySnsDerivedState`.
* New sns service `loadSnsTotalCommitment` that loads the derived state in the summary.
* New method `updateDerivedState` in SnsQueryStore to update only the derived state.
* Use the new sns service in the ProjectDetail.
* Test that ProjectDetail uses new service when appropiate.
* Test new sns api function.
* Test new method in SnsQueryStore.
* Test new sns service.

GIX-1329: Fetch derived state

---

frontend/src/lib/utils/format.utils.ts
frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts
frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts
frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
frontend/src/tests/lib/components/ui/DateSeconds.spec.ts
frontend/src/tests/lib/utils/date.utils.spec.ts
frontend/src/tests/utils/utils.test-utils.ts

With Node 18.13.0 there was an update to ICU 72 which means date formatting has a slightly different output (whitespace only). This broke some tests which have expectations on formatted dates.
I originally just updated the expected values, but this breaks the test when using a Node version < 18.13.0.
My current solution is to normalize the whitespace before comparing. This allows the test to pass both with older and newer Node versions.
Normalize whitespace in tests where ICU 72 introduced a different whitespace separator in front of AM/PM.
Tests only

Fix date formatting tests for Node 18.13.0

---

frontend/tsconfig.json

Webstorm does not resolve the path set by `.svelte-kit/tsconfig.json` and therefore we ends up with broken workspaces that cannot resolve dependencies and open imports.
This fix the issue providing the paths already in the `tsconfig.json` of the project.

chore: fix webstorm resolution

---

dfx.json

Allow mainnet nns-dapp to integrate with SNS Aggregator.
* Add mainnet data for SNS aggregator in `dfx.json`.
* Not applicable

GIX-1247: Add SNS Aggregator mainnet in config

---

frontend/src/tests/lib/modals/sns/IncreaseSnsDissolveDelayModal.spec.ts

My solution to GIX-1328 requires changes to this test (among others) otherwise the SNS neuron won't be available.
I decided to do a separate cleanup of the test to keep the PR that fixes GIX-1328 more readable.
Changes to IncreaseSnsDissolveDelayModal.spec.ts:
1. Mock sns-governance.api instead of sns-neurons.services
2. Expect a specific value for the dissolve delay on the API call
3. Mock getAuthenticatedIdentity explicitly with a specific test identity, instead of relying on frontend/jest-spy.ts.
4. reset all mocks in beforeEach
5. Use `roundUpSecondsToWholeDays` instead of `daysToSeconds(secondsToDays(seconds))` because the latter sounds like it doesn't do anything.
Tests only.

Clean up IncreaseSnsDissolveDelayModal.spec.ts

---

frontend/src/tests/lib/derived/sns/sns-selected-transaction-fee.store.spec.ts
frontend/src/tests/lib/derived/sns/sns-sorted-neurons.derived.spec.ts
frontend/src/tests/lib/derived/sns/sns-token-symbol-selected.store.spec.ts
frontend/src/tests/lib/pages/SnsAccounts.spec.ts

My solution to GIX-1328 requires changes to these tests (among others) otherwise the SNS neuron won't be available.
I decided to do a separate cleanup of the tests to keep the PR that fixes GIX-1328 more readable.
1. beforeEach instead of afterEach.
2. Use real snsAccountsStore instead of mock.
Tests only

GIX-1328 Small test cleanups

---

rs/sns_aggregator/src/index.html

The SNS aggregator has  a very simple home page showing a few sample links.
- Show the logo and link to the metadata of the most recent SNSs.
The index page now shows a list of recent SNSs with logo and link to metadata:

Add more demonstration URLs to the SNS aggregator

---

frontend/src/lib/derived/selected-universe.derived.ts
frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
frontend/src/tests/lib/derived/sns/sns-project-accounts.derived.spec.ts
frontend/src/tests/lib/derived/sns/sns-selected-project.derived.spec.ts
frontend/src/tests/lib/derived/sns/sns-selected-transaction-fee.store.spec.ts
frontend/src/tests/lib/derived/sns/sns-sorted-neurons.derived.spec.ts
frontend/src/tests/lib/derived/sns/sns-token-symbol-selected.store.spec.ts
frontend/src/tests/lib/modals/sns/IncreaseSnsDissolveDelayModal.spec.ts
frontend/src/tests/lib/pages/SnsAccounts.spec.ts
frontend/src/tests/lib/pages/SnsNeurons.spec.ts
frontend/src/tests/lib/pages/SnsProposals.spec.ts
frontend/src/tests/lib/pages/SnsWallet.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts
frontend/src/tests/lib/routes/ProposalDetail.spec.ts
frontend/src/tests/lib/routes/Wallet.spec.ts
frontend/src/tests/mocks/sns-response.mock.ts

It's currently possible to see uncommitted sns neurons by deep linking the root canister id.
The issue seems to be that while `selectedUniverseStore` only gives a universe from `selectableUniversesStore`, `selectedUniverseIdStore` doesn't care whether the universe is in `selectableUniversesStore`.
The solution is to make both respect selectableUniversesStore by having one derive from the other.
As a side effect we no longer need to check if the selected universe is the ckBTC universe because selectableUniversesStore already does this check.
frontend/src/lib/derived/selected-universe.derived.ts: Make sure selectedUniverseIdStore only holds a universe id from selectableUniversesStore.
Many tests had to change because they didn't set up the selectableUniversesStore to allow the selected …

GIX-1328 Only select selectable universes.

---

frontend/package.json
frontend/src/lib/components/login/LoginMenuItems.svelte

This is the last remaining lint warning.
For a11y, lint wants every element with a click handler to also have a key handler.
Buttons etc. do this automatically but div/span/etc. not.
We have a div wrapping the theme toggle on the logged-out menu on mobile, which stops propagation on click to keep the menu open to allow toggling multiple times without having to reopen the menu each time.
It's currently not possible to use the toggle with the keyboard because it's not in the tab order (and only appears on mobile) but if it were possible, we'd probably want to keep the menu op in that case as well.
So for now, adding this handler just stops lint from complaining.
1. Stop propagation of keyboard events from the theme toggle inside the logged-out menu.
2. Limit the allowed number of lint …

Add key event handler on theme toggle

---

.github/workflows/aggregator.yaml
.github/workflows/build.yml
declarations/sns_governance/sns_governance.did
declarations/sns_swap/sns_swap.did
dfx.json
rs/sns_aggregator/src/types/ic_sns_governance.rs
rs/sns_aggregator/src/types/ic_sns_swap.rs

We need to test against the latest SNS.
- Advance the IC commit to `ced285287d5513832ba8c66fc3793e438c74b531`  (Wed Feb 22 23:25:09 2023 +0000)
- Note: This was done with the update script.  No further changes or fixes were needed.
- Advance the snsdemo version used for testing to `34133493140b01b14a07c1b9fa5e9aee7290ea6d` (Thu Feb 23 04:22:12 2023 +0100)
- Note: The snsdemo uses dfx version `0.13.1`, so this PR is stacked on top of the nns-dapp PR that introduces 0.13.1.
See CI
- Deployed snsdemo to small09.  Verifying a couple of canister IDs to ensure that the SNS wasms are as expected:
```
max@sinkpad:~/dfn/snsdemo (1:44:51)$ cat sns_ZUNAP_canister_ids.json
{
"sns_governance": {
"small09": "sbzkb-zqaaa-aaaaa-aaaiq-cai"
},
"sns_index": {
"small09": "s24we-diaaa-aaaaa-aaaka-cai"
}, …
```

Bump ic commit

---

frontend/src/lib/api/canisters.api.ts
frontend/src/lib/components/project-detail/ParticipateButton.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/sns/SwapModal/ParticipateSwapModal.svelte
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/stores/sns-tickets.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/stores/sns-ticket.store.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts

Many users trying to participate at the same time might overload the sns sale canister.
We want to be the ones managing that experience, instead of showing errors.
Therefore, we retry getting the open ticket from the sale canister if we get a not identified error.
Main changes to review:
* New helper `pollGetOpenTicket` used in `loadOpenTicket`.
* New property `keepPolling` in the SnsTicketsStore.
* New methods in `stopPolling` and `enablePolling` in SnsTicketsStore.
Other changes:
* Changes in error handling in `loadOpenTicket`.
* New parameter in `poll` util: `millisecondsToWait`
* Move `pollingLimit` next to the `poll` util.
* Changes in the onDestroy of the `ParticipateButton`.
* Refactor `hasOpenTicketInProcess` to pass the store so that it's recalculated when store changes.
* More …

GIX-1340: Retry get open ticket

---

frontend/package-lock.json
frontend/src/lib/api/sns-aggregator.api.ts
frontend/src/lib/api/sns-sale.api.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/tests/lib/api/sns-sale.api.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts
frontend/src/tests/mocks/sns-aggregator.mock.ts
frontend/src/tests/mocks/sns-projects.mock.ts
frontend/src/tests/mocks/sns-response.mock.ts

Handling of the `TransferError::TooOld`.
- upgrade swap canister types (based on candid)
- upgrade `ic-js` to get `notifySwapFailure` api
- `notifySwapFailure` api
- `isInternalRefreshBuyerTokensError`
- update the sale flow
- refactor `notifyParticipationAndRemoveTicket`
- call `notifySwapFailure` to manually remove the ticket
- notifyPaymentFailure api
- sale services update (notifyParticipationAndRemoveTicket)
- isInternalRefreshBuyerTokensError

GIX-1331: Manage TxTooOld error in Participation flow

---

Dockerfile

I have rewritten the Dockerfile to address issues encountered recently, especially in the context of using docker builds on nns-dapp for testnets.  Docker builds play an important role for non-team members who want something that "just works" without too many knobs to configure.  That rewrite is broken down into small chunks.
There has been discussion about how we specify tool versions.  However changing _where_ we specify a tool version causes the tool installation to have to be rebuilt.
- Separate getting tool versions from installing tools.
- See CI
- I have verified that the result of `./scripts/docker-build` (with no further arguments or relevant env vars) is unaffected by this change.

Separate getting tool versions from tool installation

---

frontend/src/tests/lib/pages/SnsAccounts.spec.ts

`SnsAccounts.spec.ts` has a test which tests that no amount is rendered when there are no accounts. 
But it makes no difference to the test whether there are accounts or not so the test doesn't actually test anything.
1. Added an equivalent test which tests that an amount *is* rendered when there are accounts, to make sure the 2 situations actually differ.
2. Added a helper function to make sure the component finished loading.
3. Added a helper function to check whether an amount is rendered.
4. Used the helper functions where appropriate.
Test only

Fix SnsAccounts.spec.ts

---

frontend/src/lib/api/sns-sale.api.ts
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/tests/lib/api/sns-sale.api.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts

Retry on refresh_buyer_tokens for specific errors.
Major changes:
* New helper `pollNotifyParticipation`.
* Use the new helper `pollNotifyParticipation` in `notifyParticipationAndRemoveTicket`.
* New util `isRetryRefreshBuyerToken` to identify errors that trigger a retry on `refresh_buyer_tokens`.
Minor changes:
* New sns api util `notifyParticipation` for easy mocking the error. It will also be easier for mocking. It shuold be the way to go.
* Test new scenario in `participateInSnsSale`.
* Test new sns sale api `notifyParticipation`.

Feat: Retry refresh_buyer_tokens

---

frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingCard.spec.ts

6 tests in VotingCard.spec.ts were disabled by an accidental `it.only`.
3 of them actually don't pass but it's still better to have 4 enabled than only 1.
Remove `it.only` and add `it.skip` to the tests that currently don't pass.
Ran the test.

Remove it.only from VotingCard.spec.ts

---

frontend/src/lib/i18n/en.json
frontend/src/lib/services/sns-sale.services.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts

We want to retry and don't show error if creating the new sale ticket fails for unknown reasons. For example, replica is overloaded.
* New helper `pollNewSaleTicket` in sns sale services.
* Use new helper `pollNewSaleTicket` instead of calling api function directly in sns service `newSaleTicket`
* Change test that handles unknown errors and add a new one.

Feat: Retry new sale ticket

---

frontend/src/lib/api/sns.api.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/lib/services/sns.services.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/api/sns.api.spec.ts
frontend/src/tests/lib/components/launchpad/ProjectCardSwapInfo.spec.ts
frontend/src/tests/lib/pages/ProjectDetail.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/lib/stores/sns.store.spec.ts

Use new and fewer endpoints to load data after participation.
loadSnsSummary loaded data that didn't change after participation.
* New sns api function `querySnsLifecycle`.
* Remove `loadSnsSummary`.
* New sns service `loadSnsLifecycle`.
* Use `loadSnsTotalCommitment` and `loadSnsLifecycle` instead of `loadSnsSummary` after participation.
* New method `updateLifecycle` in `snsQueryStore`.
* Test for new sns api function `querySnsLifecycle`.
* Remove tests for `loadSnsSummary`.
* New test for sns service `loadSnsLifecycle`.
* Test new method `updateLifecycle` in `snsQueryStore`.

Feat: Use new and fewer endpoints after participation

---

scripts/canister_ids

When we deploy new canisters to testnets, it's sometimes useful to share ids of multiple canisters to add to canister_ids.json.
This script lets one person do `scripts/canister_ids export medium06` and it will output something like:
```
{
"internet_identity": {
"medium06": "qhbym-qaaaa-aaaaa-aaafq-cai"
},
"nns-dapp": {
"medium06": "qsgjb-riaaa-aaaaa-aaaga-cai"
},
"sns_aggregator": {
"medium06": "5v3p4-iyaaa-aaaaa-qaaaa-cai"
}
}
```
This can then be shared and then other people can do `scripts/canister_ids import` and paste the shared partial config to apply it to their own `canister_ids.json`.
Add new script.
Tested export and import manually.

Script to share canister ids.

---

scripts/dev-local.sh
scripts/dev-testnet.sh

Running development against testnet requires several steps:
You need
1. a canister_ids.json file
2. several tools installed
3. to run `DFX_NETWORK=$network ./config.sh`
4. to run `npm ci` and `npm run dev` from `frontend/`
It's easy to forget something, especially if you're new to the team.
This scripts checks all the inputs and runs all the steps so you can't forget something.
1. Add `dev-testnet.sh` analogous to `dev-local.sh`.
2. The script needs to be run from a git repo and will work from any directory inside the repo so you don't need to `cd` into or out of `frontend/`.
3. Change to `dev-local.sh` to make the previous point work for it as well.
Tested manually with a new user account on my Mac.

Script to set up testnet development

---

frontend/src/lib/services/sns-sale.services.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts

UI retries transfer in the sns participation flow during unkown errors.
* New helper `pollTransfer` in sns-sale services.
* Use new helper `pollTransfer` in sns-sale services `participateInSnsSale`.
* Test new functionality.

GIX-1348: Retry transfer participation

---

frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/utils/utils.spec.ts

We want to use exponential backoff for sns sale retries.
This PR only adds the optional functionality to the poll function which is used by the `sns-sale-services.ts`.
1. Adds an optional `useExponentialBackoff` parameter to `poll()`.
2. Adds missing tests to test linear retry timestamps.
3. Adds tests to test exponential retry timestamps.
1. Unit tests.
2. Manual test by adding a fail counter before `getOpenTicketApi()` in `sns-sale.services.ts`, both with and without exponential backoff.

GIX-1346 Add exponential backoff option to poll

---

Dockerfile
build-frontend.sh
build.sh
scripts/docker-build

The build steps for the nns-dapp  frontend and backend currently run ./config.sh.  For config.sh to work properly for environments other than hard-wired entries such as mainnet, it needs access to the environment such as `.dfx/`.  The environment contains a huge amount of information that is not relevant and that makes it harder to reason about the build and breaks caches.  If we put this "config extraction" into a separate step, the inputs to the build can stay small.
- Add a separate docker stage to get build configuration
- Move ./config.sh out of the frontend build command.
- Minimize inputs to the build commands, e.g. removing env vars.

Reduce inputs to build steps

---

frontend/src/lib/pages/NnsNeuronDetail.svelte

**Reprodusable not on all testnets**
After staking the neuron if user navigates fast to the neuron details
1. listNeurons query call returns no new neuron (update call does)
2. error message appears (screen 1)
3. User navigates back to the neuron list
- skip the query result if there is no open neuron information. In the worst case scenario, when a user opens the neuron details page directly with unknown/wrong neuronId, the skeletons will be shown till the update call is done and only then the error message will be displayed + navigation to the list
The Error
After the fix
https://user-images.githubusercontent.com/98811342/221493098-b5767694-8f02-45e5-9495-c60b4f282de1.mp4

fix: error and back navigation after neuron staking

---

frontend/src/lib/components/universe/SelectUniverseNav.svelte
frontend/src/lib/derived/title-token-selector.derived.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/modals/universe/SelectUniverseModal.svelte
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/derived/title-token-selector.derived.spec.ts

Change title of the universe selector depending on the page.
* New derived store `titleTokenSelectorStore` that returns the title for the universe selector.
* Use `titleTokenSelectorStore` in the universe selector navbars.
* Test new derived store.

GIX-1345: Change Select Universe navigation title

---

frontend/src/lib/services/accounts.services.ts
frontend/src/lib/services/app.services.ts
frontend/src/tests/lib/services/accounts.services.spec.ts
frontend/src/tests/lib/services/app.services.spec.ts

Do not show errors from loading accounts on init.
* Add a parameter to `syncAccounts` which is an error handler.
* Extract the current logic on error to a default error handler for `syncAccounts`.
* New `initAccounts` service that uses `syncAccounts` with an empty function as error handler.
* Test new functionality of `syncAccounts`.
* Test for new service `initAcconts`.

GIX-1352: Init accounts service

---

frontend/src/app.html
frontend/static/robots.txt
frontend/static/sitemap.xml

`nns.ic0.app` is (still) main url of NNS-dapp therefore `robots.ts`, `sitemap.xml` and other static meta tags should still use it.

feat: nns.ic0.app is (still) main url of NNS-dapp

---

frontend/src/lib/modals/neurons/DisburseNnsNeuronModal.svelte
frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
frontend/src/lib/modals/neurons/StakeNeuronModal.svelte
frontend/src/tests/lib/components/neuron-detail/actions/DisburseButton.spec.ts
frontend/src/tests/lib/components/neuron-detail/actions/NnsIncreaseStakeButton.spec.ts
frontend/src/tests/lib/components/neurons/NnsNeuronsFooter.spec.ts
frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts
frontend/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts
frontend/src/tests/lib/modals/neurons/StakeNeuronModal.spec.ts

Some nns neuron modals use the accounts: IncreaseStake, StakeNeuron, Disburse.
If initAccounts fail, use `pollAccoutns` to make sure the accounts are loaded.
* Call `pollAccounts` on mount of DisburseNnsNeuronModal.svelte
* Call `pollAccounts` on mount of IncreaseNeuronStakeModal.svelte
* Call `pollAccounts` on mount of StakeNeuronModal.svelte
* Load accounts store in tests that open the modals.
* Add scenario in each modal test that accounts are requested if they are not present in the store.
* Add a describe in the current tests for the modals with the acconts store loaded with accounts.

GIX-1353: Poll accounts in neuron related modals

---

frontend/src/lib/pages/NnsAccounts.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/routes/Accounts.svelte
frontend/src/tests/lib/pages/NnsAccounts.spec.ts
frontend/src/tests/lib/pages/NnsWallet.spec.ts
frontend/src/tests/lib/routes/Accounts.spec.ts
frontend/src/tests/lib/routes/Wallet.spec.ts

In case the accounts fail to load on init. Retry to fetch them in the nns wallet and accounts.
* Add a call to `onMount` in NnsWallet.
* Add a call to `onMount` in NnsAccounts.
* Add for NnsWallet and NnsAccounts tests.
* Fill accounts store in Wallet and Accounts tests.

GIX-1353: Add pollAccounts to nns wallet and accounts

---

frontend/src/lib/components/project-detail/ParticipateButton.svelte
frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/types/project-detail.context.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts

Fix visibility logic of the "actual commitment not equals to ticket amount" warning to work not only for the first participation.
- replace (ticket.amount != finalCommitment) with (ticket.amount + userCommitment != finalCommitment)
- updated tests for warning visibility
**Increasing participation w/o warning**

Fix not equal to amount warning

---

frontend/src/lib/i18n/en.json

Change text in waiting modal "Sending ICP" to "Confirming ICP transfer".
* i18n keys.
Not applicable

Chore: Change "Sending ICP" text

---

frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
frontend/src/lib/services/accounts.services.ts
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/lib/services/accounts.services.spec.ts

Improve performance and handle more concurrent users.
* Add `certified = true` param to `pollAccounts`.
* Pass `false` in `pollAccounts` call in ParticipateSwapModal.svelte.
* Test that requests are query calls in ParticipateSwapModal.
* Test new functionality in `pollAccounts`.

Chore: Query call in pollAccounts in participation

---

frontend/src/lib/services/sns-sale.services.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts

A tiny adjustment to take transfer errors into consideration for modal close waiting time.
- return the error state of the transfer
- not provided

fix: take transfer errors into consideration for modal close waiting

---

frontend/jest-setup.ts
frontend/src/lib/api/sns-wrapper.api.ts
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/services/$public/proposals.services.ts
frontend/src/lib/services/$public/sns.services.ts
frontend/src/lib/services/accounts.services.ts
frontend/src/lib/services/canisters.services.ts
frontend/src/lib/services/ckbtc-accounts.services.ts
frontend/src/lib/services/ckbtc-tokens.services.ts
frontend/src/lib/services/neurons.services.ts
frontend/src/lib/services/sns-accounts.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/lib/services/sns-parameters.services.ts
frontend/src/lib/services/sns-tokens.services.ts
frontend/src/lib/services/sns.services.ts
frontend/src/lib/services/transaction-fees.services.ts

Improve performance of the nns dapp by dropping update calls.
* Add a new constant FORCE_CALL_STRATEGY
* Use the new constant in all the `queryAndUpdate` calls reviewed by security and accepted to be query calls.
* No tests were broken. Tests checked that calls were made, but not the number of them.

Chore: Force query calls

---

frontend/src/lib/modals/neurons/DisburseNnsNeuronModal.svelte
frontend/src/lib/modals/neurons/StakeNeuronModal.svelte
frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
frontend/src/lib/pages/NnsAccounts.svelte
frontend/src/lib/pages/NnsWallet.svelte
frontend/src/lib/services/accounts.services.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts
frontend/src/tests/lib/modals/neurons/StakeNeuronModal.spec.ts
frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
frontend/src/tests/lib/pages/NnsAccounts.spec.ts
frontend/src/tests/lib/pages/NnsWallet.spec.ts
frontend/src/tests/lib/services/accounts.services.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/utils/utils.spec.ts

Make sure the polling doesn't repeat and it lasts forever.
New functionality:
* Poll won't poll twice
* Cancel pollAccounts when navigating away.
* Add a `pollId` parameter to the `poll` util.
* Add functionality to cancel poll by `pollId`.
* Don't poll twice with the same `pollId`.
* Use the new `pollId` in `pollAccounts`
* Add a service `cancelPollAccounts`.
* Use the new service `cancelPollAccounts` when the component that triggered the `pollAccounts` is destroyed.
* Test new functionality in the `poll` util.
* Test `cancelPollAccounts`
* Test in each page where `pollAccounts` is started, that it's cancelled when component is unmounted.

Feat: Do not poll twice

---

dfx.json
frontend/src/lib/api/sns-sale.api.ts
frontend/src/lib/api/sns-wrapper.api.ts
frontend/src/lib/components/launchpad/ProjectCard.svelte
frontend/src/lib/components/project-detail/ParticipateButton.svelte
frontend/src/lib/pages/Launchpad.svelte
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/lib/services/$public/sns.services.ts
frontend/src/lib/services/app.services.ts
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/services/sns.services.ts
frontend/src/tests/lib/api/sns-sale.api.spec.ts
frontend/src/tests/lib/api/sns-wrapper.api.spec.ts
frontend/src/tests/lib/services/app.services.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts
frontend/src/tests/mocks/sns.api.mock.ts

Avoid unnecessary update calls.
Our calls to SNS canisters use the sns wrapper. The sns wrapper calls the SNS-W and Root canister on initialization.
Yet, we don't really need to because the canister ids for each SNS project are already provided by the SNS Aggregator.
Therefore, this PR builds the wrappers after getting the data from SNS Aggregator and adds them to the cache.
Otherwise, there would be two extra update calls to SNS canisters when we get the open ticket with the update call.
* New util `buildAndStoreWrapper` in `sns-wrapper.api`.
* Use the new util `buildAndStoreWrapper` after fetching the data from the SNS Aggregator.
* In ParticipateButton, wait until summary is present to load the ticket. This way the cached wrapper will be used.
* Changes in `loadSnsSwapCommitment`. …

Feat: get_open_ticket update call

---

rs/sns_aggregator/src/types/slow.rs

The downstream API does not include the needed `decentralization_sale_open_timestamp_seconds`.
* Add `decentralization_sale_open_timestamp_seconds` to the downstream fields.
* Deployed to a testnet and verified that the field appears.

Bump downstream api to include sale time

---

frontend/src/tests/mocks/infinitescroll.mock.ts

IntersectionObserverPassive being a mock which is initialized once breaks with tests that do jest.resetAllMock() in beforeEach(). Doing a full cleanup in beforeEach is good practice in general.
Provide a real stub implementation of IntersectionObserver as IntersectionObserverPassive.
`npm run test`

Don't use a mock for IntersectionObserverPassive

---

frontend/src/lib/constants/sns.constants.ts
frontend/src/lib/pages/CanisterDetail.svelte
frontend/src/lib/pages/NnsProposalDetail.svelte
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/services/sns-swap-metrics.services.ts
frontend/src/lib/services/sns.services.ts
frontend/src/tests/lib/pages/CanisterDetail.spec.ts
frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
frontend/src/tests/lib/pages/ProjectDetail.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/services/sns.services.spec.ts

UI refreshes in real time the total committed for a project.
* New services `watchDerivedState` that calls `loadSnsTotalCommitment` at intervals.
* Add new param to `loadSnsTotalCommitment` to specify the strategy.
* Allow `loadSnsTotalCommitment` to be called by non-logged in users.
* Render non-certified canister details.
* Force listNeurons in ProposalDetail to be `query_and_update`.
* New service `watchSnsMetrics` that calls `loadSnsMetrics` at intervals.
* ProjectDetail watches sns metrics and total commitments.
* Destroy watchers when ProjectDetail is unmounted.
* Show the toast while existing ticket as error.
* Add test for `watchDerivedState`.
* Add test for new param in `loadSnsTotalCommitment`.
* Add test in ProjectDetail that watch is called and unsubscribed.
* Fix tests after …

Feat: Watch derived state

---

rs/sns_aggregator/src/fast_scheduler.rs

If the cached state of an SNS is approved and its sale start time has passed, assume that it is open and update the swap state rapidly.
Otherwise the rapid updates have to wait for the slow round robin, which would delay the sale by about 2 minutes.
This is how it looks like to a user waiting eagerly for a sale to start:
The user sees this and keeps hitting refresh, watching the countdown.
Then the countdown reaches zero, then the countdown value is blank, then the sale starts.  The blank period is undesirable. This PR reduces it from about 2 minutes (default settings) to a few seconds.
This is deployed on small09.  I have made several SNSs and verified the improvement.

Quick updates if start time has passed

---

frontend/README.md
frontend/scripts/build.csp.mjs

Add OC swap canister URL to CSP rules.
* Add url in CSP rules
Not applicable

Fix: Add CSP url

---

frontend/.eslintrc.cjs
frontend/src/lib/utils/date.utils.ts
frontend/src/lib/utils/dev.utils.ts
frontend/src/lib/utils/ledger.utils.ts
frontend/src/lib/utils/route.utils.ts

`===` and `!==` express more explicit intent than `==` and `!=` and it's good practice to avoid the latter.
1. Enable lint to enforce `===` and `!==`.
2. Fix existing violations.
`npm run lint` and `npm run test`

Enforce === and !==

---

dfx.json
scripts/ckbtc/deploy-ckbtc
scripts/ckbtc/download-ckbtc

Use ckbtc scripts to deploy ckbtc canisters to a testnet.
* Change dfx.json with where the ckbtc related wasms and did files live once downloaded with script.
* Rename the canisters in the ckbtc file to match the ones in dfx.json
Not applicable

Chore: ckbtc scripts deploy to testnet

---

dfx.json

Out of the box, `dfx` commands such as `dfx canister call nns-dapp XXX --network ic` do not work.  Our `OWN_CANISTER_ID` predates the `dfx.json` remote entries.  Moving to the newer standard location for specifying a canister ID seems to break no flows and enable this use case.
Note: I have _not_ set a remote canister ID for `local` as we do deploy to local directly, not necessarily by proposal, and doing so would break related flows.
- Remove the mainnet nns-dapp `OWN_CANISTER_ID`  in dfx.json.
- Add nns-dapp remotes for the ic and mainnet networks.
- I have verified that the config output when building for mainnet is unchanged by this commit:
```
max@sinkpad:~/dfn/nns-dapp/branches/own-canister-id (11:20)$ DFX_NETWORK=mainnet ./config.sh 
~/dfn/nns-dapp/branches/own-canister-id …
```

Provide mainnet nns-canister ID to dfx

---

frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/tests/lib/pages/ProjectDetail.spec.ts

Avoid unnecessary calls from Project Detail page.
Do not watch the number of participants nor the total commitment if the project is not open.
* In ProjectDetail.svelte, add a new variable `enableWatchers` and use it to call the watch services or not.
* Add test for new scenario in ProjectDetail.svelte

Feat: Don't watch not open projects

---

frontend/src/lib/api-services/governance.api-service.ts
frontend/src/lib/services/neurons.services.ts
frontend/src/lib/services/vote-registration.services.ts
frontend/src/tests/lib/api-services/governance.api-service.spec.ts
frontend/src/tests/lib/pages/NnsNeurons.spec.ts
frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
frontend/src/tests/lib/pages/NnsProposals.spec.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/workflows/NnsProposalDetail.spec.ts
frontend/src/tests/workflows/NnsProposals.spec.ts

We had a bug that neurons cache should have been reset after voting.
Calling the api service "NeuronsApiService" is misleading because all communication regarding the Governance canister should go through it.
As a first step, rename from NeuronsApiService to GovernanceApiService
* Rename file.
* Rename Api Service.
* Rename imports
* Rename test files and imports

GIX-1363: Rename NeuronsApiService

---

rs/backend/src/accounts_store.rs
rs/backend/src/accounts_store/tests.rs
rs/backend/src/multi_part_transactions_processor.rs

MultiPartTransactionsProcessor has 2 unused fields: `statuses` and `errors`.
We want to remove these fields but this has to be done carefully because there are part of stable state which is encode/decoded when the canister is upgraded.
Candid::from_bytes actually deals fine with additional data for removed fields, so removing the fields would be fine, but we want to be able to roll back to an earlier version of the canister, and in that case we would be adding the fields back.
And trying to decode bytes which do not include new fields does cause the decoding to fail.
My solution is to temporarily fork MultiPartTransactionsProcessor to have 2 versions: 1 with the unused fields removed and 1 with the unused fields intact.
We use the type with the extra fields for encoding and we use the …

Remove unused fields from MultiPartTransactionsProcessor

---

scripts/dev-local.sh

`dfx start --clean` has started deleting `.dfx/local/`, causing `scripts/dev-local.sh` to fail when it tries to create `.dfx/local/canister_ids.json`.
Make sure the directory exists before we try to write a file to it.
Manually ran the script.

In scripts/dev-local.sh make sure .dfx/local/ exists.

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.svelte
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.spec.ts

Enable staking maturity for SNS neurons.
I haven't removed nor changed the feature flag ENABLE_SNS_2. We might use it for upcoming functionality like disbursing maturity and voting history.
* Remove usage of ENABLE_SNS_2 for staking maturity.
* Remove test that showed or hid Stake Maturity button when ENABLE_SNS_2 changed.

Chore: Enable stake maturity

---

e2e-tests/components/ii-add-device-page.ts

E2e tests were failing; therefore, CI pipeline was failing.
* Change the id of the element to register the alias in II.
* Fix e2e test.

Fix: E2e tests failing

---

frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/utils/env.utils.ts
frontend/src/tests/lib/utils/env.utils.spec.ts

When we develop in localhost, we can't work with the data from the SNS aggregator because it fails.
After discussing with the trust team, the best way is to use `raw` when we're developing locally.
The problem is explained in a comment.
* New env util `addRawToUrl` that adds `raw` to urls.
* Use `addRawToUrl` in environment constants when DEV is enabled.
* Add tests for new util `addRawToUrl`.

GIX-1333: Fix aggregator with localhost

---

dfx.json
frontend/src/lib/constants/environment.constants.ts

Set features flags of testnets at last as restrictive as mainnet, but not less.
Except the environments used for sns-testing `https___<network>_testnet_dfinity_network`, which require ckbtc to be disabled by default.
* Changes in the flags in dfx.json
Only config changes

Chore: Add flags dfx json

---

frontend/src/lib/directives/debug.directives.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/stores/feature-flags.store.ts
frontend/src/lib/types/i18n.d.ts

We want to be able to enable feature flag on mobile where we can't open the JS console.
https://user-images.githubusercontent.com/122978264/223469577-0c34374d-ed90-40cf-914f-a0d3c77e0552.mov
In the 6-click debug directive add 3 new commands:
1. "fft" for "feature-flag true" to override a feature flag to true.
2. "fff" for "feature-flag false" to override a feature flag to false.
3. "ffr" to remove a feature flag override.
Tested manually on testnet.

Debug commands to enable feature flags.

---

frontend/src/lib/services/accounts.services.ts
frontend/src/lib/utils/utils.ts
frontend/src/tests/lib/utils/utils.spec.ts

If we move to a different view while polling for accounts, we cancel the polling.
This works through a mechanism which uses a race between 2 promises and we reject one of them when we cancel.
This is intended and the rejection should not cause any visible errors.
But if the rejection happened during the call rather than during the wait, it would be swallowed and logged if shouldExit returns falls.
Instead, we should rethrow it to really bail out of the polling.
This didn't cause anything to break because in the next round we would wait (also in a race with the same promise) not inside a try/catch block and there we would actually bail out of the polling. Except if it had been the last attempt and then we would throw PollingLimitedExceededError instead of the intended …

Fix PollingCancelledError appearing in the console

---

frontend/src/tests/utils/console.test-utils.ts

We don't want distracting logs in test output.
1. Remove the message that says your test has passed because it may or may not have passed.
2. Explain that the log failure only happens after the test finished.
3. Don't use mocks to replace loggers because that breaks when a test does `jest.resetAllMocks()`.
4. Ban `console.warn` in addition to the other logs we ban.
5. Use `$tests` in the import path in the error message.
`npm run test` with and without `console.warn`.

Improve console log check during tests.

---

frontend/src/lib/components/accounts/SnsTransactionsList.svelte
frontend/src/lib/components/launchpad/Projects.svelte
frontend/src/lib/derived/selectable-universes.derived.ts
frontend/src/lib/derived/sns/sns-projects.derived.ts
frontend/src/lib/derived/sns/sns-selected-project.derived.ts
frontend/src/lib/pages/Launchpad.svelte
frontend/src/lib/routes/Accounts.svelte
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/utils/projects.utils.ts
frontend/src/tests/lib/derived/sns/sns-projects.derived.spec.ts

snsSummariesStore is declared to hold SnsSummary[] so snsProjectsStore can't hold undefined. As a result a number of other things can't be undefined either and declare them as potentially undefined is confusing.
I recommend reviewing this PR 1 commit at a time.
Commits:
1. snsSummariesStore is declared to hold SnsSummary[] so snsProjectsStore can't hold undefined.
2. snsProjectsStore never holds undefined, so filterActiveProjects is never called with undefined, so declare it to not take nor return undefined.
3. filterActiveProjects can't return undefined so snsProjectsActivePadStore can't hold undefined.
4. filterCommittedProjects is never called with undefined so declare it to not accept undefined.
5. filterProjectsStatus is never called with undefined so declare it to not accept and not …

cleanup: Remove impossible return type undefined

---

frontend/src/lib/api-services/governance.api-service.ts
frontend/src/lib/api/governance.api.ts
frontend/src/lib/api/proposals.api.ts
frontend/src/lib/services/vote-registration.services.ts
frontend/src/tests/lib/api-services/governance.api-service.spec.ts
frontend/src/tests/lib/api/governance.api.spec.ts
frontend/src/tests/lib/api/proposals.api.spec.ts
frontend/src/tests/lib/services/vote-registration.services.spec.ts

The fix of the voting button used a test feature.
This is the fix we intended. Calls to governance canister should be done through the governance api service and this one decides when to reset or not the cache.
* Add method "registerVote" in the GovernanceApiService. It clears the cache after it.
* Move "registerVote" api function to "governace.api". Slowly, start implementing the agreed pattern that api should be grouped by canister.
* Voting service uses governance api service instead of the api function directly. That means we can remove the call to `resetNeuronsApiService`.
* Move test for the api function "registerVote" to the "governace.api.spec".
* Add test for registerVote in the governance api service.
* Change mocks due to moving api function to another file.

GIX-1363: Register Vote through GovernanceApiService

---

frontend/src/lib/services/neurons.services.ts
frontend/src/lib/services/sns-neurons.services.ts
frontend/src/tests/lib/services/neurons.services.spec.ts
frontend/src/tests/lib/services/sns-neurons.services.spec.ts

Allow SNS and NNS neurons to follow themselves.
* Remove check in addFollowee for the same neuron id in sns-neurons and neurons services.
* Change test to allow the behavior explicitly.

Feat: Allow neurons to follow themselves

---

frontend/src/lib/pages/SnsWallet.svelte

Deep link to an SNS Wallet wasn't working.
The problem was that the `load` function that sets the context store was not called after the accounts were loaded in the store.
It was called only when the identifier was there.
It worked with normal navigation because the store was already filled with the accounts. But if the user arrives with the deep link, the accounts are loaded. Therefore, the `load` function was called before they were loaded, but not after they were in the store.
* Call `load` function also when sns accounts store changes in SnsWallet.svelte page.
* Upcoming in another PR along with other test for deep links.

Fix: SNS Wallet page infinite loading

---

README.md

A user could not build the Wasm image with `scripts/docker-build`, the command resulted in the following error 
```sh
ERROR: BuildKit is enabled but the buildx component is missing or broken.
Install the buildx component to build images with BuildKit:
https://docs.docker.com/go/buildx/
```
Added the steps necessary to install `docker-buildx`

Update README to reflect the need to install docker-buildx

---

frontend/src/lib/components/launchpad/Projects.svelte
frontend/src/lib/components/launchpad/Proposals.svelte
frontend/src/lib/services/$public/sns.services.ts
frontend/src/lib/stores/sns.store.ts
frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
frontend/src/tests/lib/stores/sns.store.spec.ts

snsQueryStore and snsProposalsStore use `undefined` to mean reset and `null` to mean loading. But then when checking whether they are loading we just use isNullish. This is confusing and it's also not super clear that setLoadingState actually resets all the data.
To make this obvious we use reset() instead of setLoadingState() and expose separate stores to check whether the store is loading via isNullish.
1. Remove setLoading from snsQueryStore and snsProposalsStore.
2. Add snsQueryStoreIsLoading and snsProposalsStoreIsLoading
3. Use `.reset()` instead of `.setLoading()`.
4. Use `snsQueryStoreIsLoading` instead of `isNullish($snsSummariesStore) || isNullish($snsQueryStore)`. [snsSummariesStore](https://github.com/dfinity/nns-dapp/blob/4588644d282a9a3bbe4df3bac35215021f277361/frontend/src/l …

cleanup: Remove setLoading on snsQueryStore and snsProposalsStore

---

frontend/src/lib/components/common/TestIdWrapper.svelte
frontend/src/lib/components/neurons/NnsNeuronCard.svelte
frontend/src/lib/components/sns-neurons/SnsNeuronCard.svelte
frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/lib/pages/NnsNeurons.svelte
frontend/src/lib/pages/SnsNeuronDetail.svelte
frontend/src/lib/pages/SnsNeurons.svelte
frontend/src/lib/routes/NeuronDetail.svelte
frontend/src/lib/routes/Neurons.svelte
frontend/src/tests/lib/routes/NeuronDetail.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts
frontend/src/tests/page-objects/Hash.page-object.ts
frontend/src/tests/page-objects/NeuronDetail.page-object.ts
frontend/src/tests/page-objects/Neurons.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeurons.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/SnsNeurons.page-object.ts

The getters on page objects that return page objects can be a bit confusing, especially then the component name is in plural. For example getNnsNeurons does not return multiple neurons but the page object for the component NnsNeurons.
We also had to add the same css to a number of different components just to be able to wrap it in an element with a test ID.
1. For getters that return a page object, make the name end with "Po".
2. For getters that return a list of page objects, make the name end with "Pos".
3. For getters that return whether a page object is non-nullish, make the name end with "Po".
4. Add TestIdWrapper to wrap multiple element with a data-tid and apply display:contents.
1. `npm run test`
2. Manual testing.

Page object cleanups based on feedback from PR 2062

---

frontend/src/lib/derived/sns/sns-selected-project.derived.ts
frontend/src/lib/routes/Neurons.svelte
frontend/src/tests/lib/derived/sns/sns-selected-project.derived.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts

Currently it's possible to see founder neurons before the sns project is committed by manually change a URL parameter.
The current code checks that the URL parameter represents an existing project but not that the project is committed.
In Neurons.svelte, instead of only rendering SnsNeurons if the selected project exists, also check that it's committed.
Unit tests and manual testing.

GIX-1328 Only show sns neurons for committed projects

---

.github/workflows/build.yml
scripts/nns-dapp/downgrade-upgrade-test

We are making more changes to the nns-dapp  backend and in particular to the stable memory.  It would be good to have at least a very basic downgrade-upgrade test in CI.
Requirements:
- Fast; should not slow down CI significantly.
- Verify that there are no panics in the pre and post-upgrade hooks.
Not covered:
- Detailed checks that might be applicable to a specific upgrade, e.g. making sure that stable data is preserved or manipulated in a  certain way.
- Add a script that performs a downgrade and then an upgrade.  Given that the current code is usually deployed when testing, a downgrade-upgrade test is quicker to implement than an upgrade-downgrade test, which would really be a downgrade-upgrade-downgrade-upgrade test.
- Perform a health check by calling the stats endpoint.  This is …

Downgrade upgrade test

---

frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronInfoStake.spec.ts
frontend/src/tests/page-objects/AmountDisplay.page-object.ts
frontend/src/tests/page-objects/Button.page-object.ts
frontend/src/tests/page-objects/SnsNeuronInfoStake.page-obejct.ts

User should not be able to increase the stake of a Community Fund owned SNS neuron.
NOTE: Functionality is permitted in the backend. But the fix for now is to disable it in the frontend.
* Check whether neuron is part of the CF in SnsNeuroInfoStake.svelte to render the SnsIncreaseStakeButton.
* New PO SnsNeuronInforStake.
* New PO Button
* Use new PO in SnsNeuronInfoStake test file.
* Add scenario for Incrase Stake neuron belonging and not belonging to CF.

Feat: Hide Increase Stake for SNS CF neurons

---

frontend/src/lib/services/accounts.services.ts
frontend/src/lib/services/canisters.services.ts
frontend/src/lib/services/sns-sale.services.ts
frontend/src/tests/lib/services/accounts.services.spec.ts
frontend/src/tests/lib/services/canisters.services.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/mocks/sns.mock.ts

Continuing with the task of reducing the number of update calls by using `loadBalance` instead of `syncAccounts`.
* Use `loadBalance` in the accounts service `transferICP`.
* Use `loadBalance` in the canister service `createCanister`.
* Use `loadBalance` in the canister service `topUpCanister`.
* Use `loadBalance` in the sns sale service `participateInSnsSale`.
* Change expectations of calling `syncAccounts` service for only the `queryAccountBalance` api.
* Major change in `canister.services.spect.ts`. Mock only api layer.
* Use new `blockAllCallsTo` in canister and accounts services test files.

GIX-1401: Use loadBalance instead of syncAccounts

---

rs/backend/src/accounts_store.rs
rs/backend/src/accounts_store/tests.rs
rs/backend/src/assets.rs
rs/backend/src/main.rs
rs/backend/src/stats.rs
rs/backend/src/stats/tests.rs

Stats and metrics are currently calculated inside the accounts store.  This is limiting, given that there are interesting statistics to be had from other parts of the canister.
* Move the stats code out of the accounts store, leaving behind just the part that populates account stats.
This changes no externally functionality so no new tests are required.

Refactor: Move stats out of the accounts store

---

frontend/package.json
frontend/src/lib/components/ui/Logo.svelte

Running `svelte-check` which is part of `npm run check` currently gives 1 warning:
```
frontend/src/lib/components/ui/Logo.svelte:28:5
Warn: Unknown property: 'user-drag' (scss)
-webkit-user-drag: none;
user-drag: none;
}
```
According to https://caniuse.com/webkit-user-drag:
> There is currently no unprefixed `user-drag` or other version of the property implemented in browsers or on a standards track as the HTML `draggable` attribute/property is the preferred solution.
1. Remove `user-drag: none;` from Logo.svelte.
2. Add `draggable="false"` to the `<img>` tag in Logo.svelte.
3. Add `--fail-on-warnings` to `npm run check` to prevent new warnings.
Manually tried dragging an affected logo in both Chrome and Firefox and was not able to drag it.

Remove use of non-existing user-drag property which causes a warning in svelte-check

---

frontend/src/lib/modals/neurons/NnsAutoStakeMaturityModal.svelte
frontend/src/lib/modals/sns/neurons/SnsAutoStakeMaturityModal.svelte
frontend/src/tests/lib/components/neuron-detail/actions/NnsAutoStakeMaturity.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsAutoStakeMaturity.spec.ts

Success messages on enabling auto stake were the other way around.
It said: "Automatically staking new maturity." when disabling it.
And: "Stopped automatically staking new maturity." when enabling it.
* Change which message to use in NnsAutoStakeMaturityModal and SnsAutoStakeMaturityModal.
* Add tests that proper message is added to toastsStore.

Fix: Message on auto stake

---

frontend/src/lib/services/sns-sale.services.ts
frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts

Simplify the payment flow code to make it more maintainable.
Main change
* Remove access to ticketStore in `participateInSnsSwap` and pass ticket as parameter.
Minor change
* Started some renaming from "Sale" to "Swap" for consistency.
* Fixed tests after the refactor and rename

GIX-1336: Refactor sns participation flow 1

---

e2e-tests/README.md

End to end tests can run headless or with a visible browser.
Currently the README does not explain how to configure this.
Add a paragraph in `e2e-tests/README.md` explaining how to use `WDIO_VIEW` to disable headless.
Ran `WDIO_VIEW=yes npm run test`

Explain headless in the e2e-tests README

---

frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
frontend/src/lib/modals/accounts/NewTransaction/TransactionModal.svelte
frontend/src/lib/modals/sns/neurons/SnsStakeNeuronModal.svelte
frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
frontend/src/lib/types/transaction.ts

Instead of exposing the selected account in the transaction modal we decided to pass it as a parameters of the validation function.
Follow-up of #2080.

refactor: validateAmount parameters

---

Cargo.lock
rs/backend/Cargo.toml
rs/backend/src/accounts_store.rs
rs/backend/src/assets.rs
rs/backend/src/multi_part_transactions_processor.rs
rs/backend/src/state.rs

Testing state transition requires being able to compare state.  That is hard when most of the structures in state don't implement the Eq trait.
Adding this trait touches many files in many places, so it makes sense to isolate this in a separate PR.
* Bump RbTree to a version that implements the Eq trait.
* Add the Eq and PartialEq traits to the backend State and all the structures in it.
* Add the Debug trait as required for `assert_eq(...)`

Eq trait for state

---

frontend/src/lib/components/project-detail/ParticipateButton.svelte
frontend/src/lib/services/sns-sale.services.ts
frontend/src/lib/stores/sns-tickets.store.ts
frontend/src/lib/types/sale.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
frontend/src/tests/lib/pages/ProjectDetail.spec.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts
frontend/src/tests/lib/stores/sns-ticket.store.spec.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts

Simplify the flow to participate in SNS swap.
Remove the `keepPolling` state.
* Add cancel `cancelPollOpenTicket` to the sns swap services.
* Use `cancelPollOpenTicket` on destroy of the ParticipateButton.
* Remove `keepPolling` from the snsTicketsStore.
* Remove all usages of `keepPolling` in different utils and services. It's not needed anymore.
* Add a test to check that `cancelPollOpenTicket` is called on destroy of ParticipateButton.

GIX-1336: Refactor SNS Swap Participation

---

.github/workflows/checks.yml
Dockerfile
dfx.json
rs/backend/src/accounts_store.rs
rs/backend/src/assets.rs
rs/backend/src/main.rs
rs/backend/src/time.rs
rs/sns_aggregator/src/assets.rs
rs/sns_aggregator/src/lib.rs
rust-toolchain.toml
scripts/docker-build

The latest cdk-rs requires Rust version `1.66` or later.  We currently use `1.64`
- Bump Rust to the latest stable release, which is 1.48.0 at the time of writing.
- Fix lint issues.
- There are no changes in functionality.  Existing tests _should_ suffice.

Bump rust 68

---

.github/workflows/docker-build.yaml
scripts/docker-build

Normally, when docker build runs it minimizes the output.  This is normally a nice user experience but it is unhelpful when debugging docker build issues, when the full printout would be helpful.
All `snsdemo` and many `nns-dapp` scripts support a `--verbose` option; it would be nice if docker-build did the same.
- parse the docker-build command line arguments.
- Support these flags:
- `--verbose`
- `--help`
- `--network`
- I have used `--verbose` locally and am happy to report that the output has filled many screens with text.
- I have added tests for `--help` and garbage input to CI.  I have not added a test for `--network` or `--verbose` as it seems that the test run time would outweigh the benefit.
- I have checked that the docker build with no flags, as used for creating mainnet …

Verbose docker build

---

e2e-tests/scripts/update-chromedriver

e2e-tests/scripts/update-chromedriver currently doesn't work on Mac.
1. Call `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version` if `google-chrome` doesn't exist.
2. Use `[[:space:]]` in sed instead of `\s`. Supposedly the latter only work on GNU sed.
1. Used it manually on Mac.
2. Tested the part to determine chrome_major_version on my personal Linux laptop.

Make e2e-tests/scripts/update-chromedriver work on Mac.

---

.github/workflows/aggregator.yaml

Faster CI.  There are two things that take a lot of time in the current CI.  One of those is creating many SNS for the aggregator test.
- Use the snsdemo command that creates SNSs in parallel
This is a change to a test; see CI for the result...
In particular, at present the aggregator test currently takes between 18 and 21 minutes.  That includes several other steps but 7m of that is creating 11 SNSs.  If successful, this PR should take a few minutes off that.  It is hard to estimate how much less as the github runners are small single core VMs and that limits the value of running things in parallel.
Result: The aggregator test took 14 minutes, so the speedup is worthwhile.

Create SNSs in parallel

---

Dockerfile

If any rust code is changed, all rust code is recompiled in Docker.  Changes in the `nns-dapp` cause the aggregator to be rebuilt and vice versa.  This is unnecessary work.
- Keep the toy implementation of every rust project created in builder to warm the cache.
- When building a rust project, copy in only the code for that project and use the placeholder for the other project.
See docker builds in CI

Cache rs projects separately

---

frontend/src/lib/components/proposals/ProposalCard.svelte
frontend/src/lib/derived/sns/sns-filtered-proposals.derived.ts
frontend/src/lib/pages/SnsProposals.svelte
frontend/src/lib/services/$public/sns-proposals.services.ts
frontend/src/lib/services/sns-filters.services.ts
frontend/src/lib/stores/sns-filters.store.ts
frontend/src/lib/stores/sns-proposals.store.ts
frontend/src/tests/fakes/sns-governance-api.fake.ts
frontend/src/tests/lib/derived/sns/sns-filtered-proposals.derived.spec.ts
frontend/src/tests/lib/pages/SnsProposals.spec.ts
frontend/src/tests/lib/services/_public/sns-proposals.services.spec.ts
frontend/src/tests/lib/services/sns-filters.services.spec.ts
frontend/src/tests/lib/stores/sns-filters.store.spec.ts
frontend/src/tests/mocks/sns-proposals.mock.ts

User can filter SNS proposal by decision status.
* New derived store `snsFilteredProposalsStore` that combines the snsFiltersStore and snsProposals store to return the proposals that match the current filters.
* Change in how data is loaded in SnsProposals page. Filters and nervous functions are loaded when root canister id changes. Proposals when filters change.
* New simple derived store `snsSelectedFiltersStore` that returns the selected filters in snsFiltersStore.
* Changes in service `loadSnsProposals`. Now it reads the snsSelectedFiltersStore and applies the decision filters when asking for the proposals.
Minor change:
* Change type in snsProposals store to match current pattern.
* Service `loadSnsFilters` checks if filters are already loaded and skips if so.
* Test new derived …

GIX-1212: Filter SNS Proposals

---

frontend/src/lib/services/$public/sns.services.ts
frontend/src/tests/lib/routes/NeuronDetail.spec.ts
frontend/src/tests/lib/services/_public/sns.services.spec.ts
frontend/src/tests/lib/services/app.services.spec.ts

Current SNS Aggregator doesn't persist data between upgrades. Therefore, it might be that for a few minutes the users of the NNS Dapp do not see OC and SNS-1 in the UI.
As a temporary solution, we'll revert to the fallback if the number of projects returned from the aggregator is less than 2.
* Add a check after receiving the response from the aggregator. If less than 2 projects, raise an error to use the fallback.
* Fix tests so that they don't run into the issue of less than 2.
* Add a test case to check that the fallback is used in case the number of SNSes is less than 2.

Chore: Fail SNS aggregator with less than 2 SNSes

---

frontend/src/lib/services/sns-sale.services.ts
frontend/src/tests/lib/services/sns-sale.services.spec.ts

Simplify the code in the Sns participation flow.
Add `swapCanisterId` as a parameter in swap service `participateInSnsSale`.
* Add `swapCanisterId` param to `participateInSnsSale` sns swap service.
* Pass the new param where `participateInSnsSale` is used.

Chore: Add swapCanisterId ro `participateInSnsSale`

---

scripts/dfx-canister-check-wasm-hash
scripts/dfx-nns-deploy-custom
scripts/nns-dapp/downgrade-upgrade-test

Whenever deploying, it is useful, and sometimes important, to verify that the deployment succeeded in updating the wasm.  The testnet deployment script performs this check.  Why not make the test more generally available?
- Factor out the wasm hash comparison check into a standalone script.
- Call the script in the downgrade-upgrade test.
- It can probably be used profitably in many more places, I have looked only in the places that seemed most important to me.  Further suggestions are welcome but may be implemented in later PRs.
- Test in production, of course:
- Check out tags/prod
- `./scripts/docker-build`
- Verify that mainnet has the same wasm:
```
1e3e3bc28177e8665fc3b87f7fe143fae784dd5a99660f8c143aeb80f0ed820d  assets.tar.xz …
```

Factor out the wasm comparison test

---

scripts/clap.bash
scripts/deploy-snsdemo-testnet
scripts/dfx-canister-check-wasm-hash
scripts/dfx-canister-set-id
scripts/dfx-nns-deploy-custom
scripts/dfx-software-ii-cache
scripts/dfx-software-nd-cache
scripts/dfx-software-nns-dapp-latest
scripts/nns-dapp/downgrade-upgrade-test
scripts/sns/aggregator/downgrade-upgrade-test
scripts/sns/aggregator/get_candid
scripts/sns/aggregator/get_log
scripts/sns/aggregator/get_stable_data
scripts/update_ic_commit

The bash argument parser may be close enough to be being clean that we can apply `set -euxo pipefail` before invoking it.
- Move `set -euxo pipefail` to the beginning of files using the bash clap.
- Handle unset vars correctly in a couple of places in clap.
Let's see CI
There may well be feedback from manual usage.

Constrain clap errors

---

frontend/src/lib/services/sns.services.ts
frontend/src/lib/utils/sns.utils.ts
frontend/src/tests/lib/utils/sns.utils.spec.ts

Simplify and refactor to simplify the PR #2112 
* Refactor sns util `getCommitment`.
* Make `forceFetch` optional in `loadSnsSwapCommitment`.
* Test the new `getCommitment` functionality

Chore: Refactor getCommitment

---

frontend/src/tests/page-objects/AmountDisplay.page-object.ts
frontend/src/tests/page-objects/Button.page-object.ts
frontend/src/tests/page-objects/Hash.page-object.ts
frontend/src/tests/page-objects/NeuronDetail.page-object.ts
frontend/src/tests/page-objects/Neurons.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeurons.page-object.ts
frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
frontend/src/tests/page-objects/SkeletonCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/SnsNeuronInfoStake.page-obejct.ts
frontend/src/tests/page-objects/SnsNeurons.page-object.ts
frontend/src/tests/page-objects/Tooltip.page-object.ts

We want to reuse page objects for e2e tests.
Some things, such as getting element attributes, have to be async in e2e and so they will have to be async in shared page objects.
This means we can't do it in a constructor.
Currently, page objects check that the element has the expected data-tid in the constructor.
1. Remove attribute checking in page object constructors.
2. Make constructors private to make sure page object classes still have full control over what can be used as their root elements.
`npm run test`

Remove attribute checking from page object constructors.

---

frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts

Instead of default "Bitcoin" segment, make "ckBTC" (or ckTESTBTC) the default
- invert segment
- also same default ckBTC

feat: make ckBTC default segment of receive modal with Bitcoin

---

frontend/src/tests/page-objects/AmountDisplay.page-object.ts
frontend/src/tests/page-objects/Button.page-object.ts
frontend/src/tests/page-objects/Hash.page-object.ts
frontend/src/tests/page-objects/NeuronDetail.page-object.ts
frontend/src/tests/page-objects/Neurons.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeurons.page-object.ts
frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
frontend/src/tests/page-objects/SkeletonCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/SnsNeuronInfoStake.page-object.ts
frontend/src/tests/page-objects/SnsNeurons.page-object.ts
frontend/src/tests/page-objects/Tooltip.page-object.ts
frontend/src/tests/types/page-object.types.ts

We want to reuse page objects between unit tests and e2e tests.
Currently page objects each have a root element of type `Element`, which can not be used for e2e tests.
I want to introduce an interface `PageObjectElement` which abstracts the functionality of Element and will have separate implementations for unit tests and e2e tests.
In this PR, I introduce the `PageObjectElement` but it's still equal to `Element`. This allows me to let page objects work with `PageObjectElement` while not changing anything else yet.
1. Add `type PageObjectElement = Element`
2. Declare the root elements of page objects of type PageObjectElement instead of Element (or instead of HTMLElement in some accidental cases).
`npm run test`

Add PageObjectElement type

---

frontend/src/tests/lib/api/sns-sale.api.spec.ts

There was a flaky test that would fail unexpectedly.
* Fix the test in sns sale api spec. The expectation compares to what the mocked method returns.
The reason it was flaky was because it was comparing to another ticket created at the beginning of the test. Creating this test tickets uses Date.now(), which meant that it was comparing two different tickets created with the same parameters, but because of Date.now, they could be different tickets.

Chore: Fix flaky test

---

frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts
frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronInfoStake.spec.ts
frontend/src/tests/lib/routes/NeuronDetail.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts
frontend/src/tests/page-objects/jest.page-object.ts
frontend/src/tests/types/page-object.types.ts

We want to share page objects between Jest unit tests and Playwright e2e tests.
So we provide an interface abstracting the element to use by page objects.
This interface will have different implementations per platform.
This PR adds a first version of the Jest implementation.
1. Add JestPageObjectElement and use it in all the tests to create page objects.
2. Change PageObjectElement to an interface implemented by JestPageObjectElement.
3. Add just a few methods on PageObjectElement to make current tests pass.
In the future we will change the interface to be more async so that it can be compatible with e2e but this will require more changes to the tests and page objects to accommodate so it will be different PRs.
npm run test
npm run check

Add Jest specific implementation of PageObjectElement

---

frontend/src/lib/pages/SnsProposalDetail.svelte
frontend/src/tests/fakes/sns-governance-api.fake.ts
frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts

User should be redirected to the SNS proposals list if there is some problem loading the specific proposal.
Changes in SnsProposalDetail.svelte page:
* Redirect if the parameter can't be parsed to a bigint.
* Redirect if there is an error when loading the proposal
* Add test for SnsProposalDetail.svelte page. Add test case for each of the above scenarios.
* Add error capabilities to the sns governance api fake.

GIX-1219: Manage errors when fetching SNS proposal data

---

frontend/src/tests/page-objects/AmountDisplay.page-object.ts
frontend/src/tests/page-objects/Button.page-object.ts
frontend/src/tests/page-objects/Hash.page-object.ts
frontend/src/tests/page-objects/NeuronDetail.page-object.ts
frontend/src/tests/page-objects/Neurons.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeurons.page-object.ts
frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
frontend/src/tests/page-objects/SkeletonCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/SnsNeuronInfoStake.page-object.ts
frontend/src/tests/page-objects/SnsNeurons.page-object.ts
frontend/src/tests/page-objects/Tooltip.page-object.ts
frontend/src/tests/page-objects/base.page-object.ts

There will be some things convenient to share between all page objects like click() and isPresent().
Having a share base class makes these easy to add.
1. Add BasePageObject class which holds the root element.
2. Make all page objects extend BasePageObject.
3. Pass the root element to the super constructor instead of holding on to it in each page object class.
npm run test
npm run check

Add Base class for page objects.

---

frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
frontend/src/lib/modals/sns/neurons/SnsTransactionModal.svelte
frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
frontend/src/lib/modals/transaction/TransactionModal.svelte
frontend/src/lib/types/transaction.ts
frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts

Transaction modal has various properties. Some are values, some are initial parameters, such as providing the default source account.
When we will implement payment deep linking, there will be also muliple parameters (destination, token, amount). 
That's why this PR introduce an object for the initial parameters of the transaction modal. That way we can distinguish better what a parameters and also prepare the deep linking (as we will be able to pass down a single objects).
No features change, refactoring of properties only.

refactor: transaction modal init param

---

.dockerignore
Dockerfile

Strange bug, whereby locally `./scripts/docker-build --network XXX` was not picking up the aggregator canister ID.
The dockerfile pulls in .dfx, precisely to support locally deployed, non-standard canister IDs.
On closer inspection, .dfx was being pulled in but as an empty directory.
`.*` is listed in .dockerignore.  But exempting `.dfx` in `.dockerignore` alone does not help.
In the COPY documentation, it states that if `src` is a directory, it must end in a `/`.  That did not help.
But having a separate copy command for `.dfx` does work.
* Exempt `.dfx` from `.dockerignore`.
* Move the `.dfx` copy command to a separate step.
* Manually tested that a local aggregator canister ID is now picked up.
* Manually tested that if I then remove `.dfx`, the locally deployed aggregator canister ID …

Fix: Copy contents of .dfx

---

frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts

"Estimated amount received: xxxxx BTC" should not be displayed for ckBTC.
- use related component according network

fix: "estimated amount received BTC" should not be displayed for ckBTC network

---

frontend/src/lib/components/sns-proposals/SnsProposalDataSection.svelte
frontend/src/lib/components/sns-proposals/SnsProposalPayloadSection.svelte
frontend/src/lib/components/sns-proposals/SnsProposalSummarySection.svelte
frontend/src/lib/components/sns-proposals/SnsProposalSystemInfoSection.svelte
frontend/src/lib/components/sns-proposals/SnsProposalVotingSection.svelte
frontend/src/lib/components/ui/SkeletonDetails.svelte
frontend/src/lib/pages/SnsProposalDetail.svelte
frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
frontend/src/tests/page-objects/SkeletonDetails.page-object.ts
frontend/src/tests/page-objects/SnsProposalDetail.page-object.ts

User sees details of a specific SNS proposal.
In this PR: Setup the cards for the SnsProposalDetail page.
* New components `SnsProposal<Xxx>Section.svelte` as placeholders. This will help develop the cards in parallel withour conflicts.
* SnsProposalDetail.svelte page renders SkeletonDetails or the placeholders when the proposal is loaded.
* New test cases in SnsProposalDetail page spec. Skeleton is displayed initially and then content is loaded afterwards.
* New POs: SnsProposalDetailPo and SkeletonDetailsPo.

GIX-1220: Display general SNS proposal info setup

---

Cargo.lock
rs/backend/Cargo.toml

General tidiness - unused crates obscure the code and add weight.
- Remove two unused crates from the backend dependencies.
See CI.  It builds!

Rm unused crates

---

frontend/src/tests/fakes/governance-api.fake.ts
frontend/src/tests/fakes/sns-governance-api.fake.ts
frontend/src/tests/lib/routes/NeuronDetail.spec.ts
frontend/src/tests/lib/routes/Neurons.spec.ts

When expecting a component to be in loading state we shouldn't rely on arbitrary promises not to be resolved yet.
1. Make it possible to pause fake governance API same as fake SNS governance API.
2. Pause the API in tests that explicitly expect a component to be in loading state.
3. Add missing `isPaused = false` in resume of fake SNS governance API.
`npm run test`

Make it possible to pause fake governance API

---

frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
frontend/src/lib/routes/Accounts.svelte
frontend/src/tests/e2e/example.spec.ts
frontend/src/tests/page-objects/Accounts.page-object.ts
frontend/src/tests/page-objects/Button.page-object.ts
frontend/src/tests/page-objects/NnsAccountsFooter.page-object.ts
frontend/src/tests/page-objects/jest.page-object.ts
frontend/src/tests/page-objects/playwright.page-object.ts
frontend/src/tests/types/page-object.types.ts

Page objects now work with both Jest unit tests and Playwright e2e tests.
The example test now demonstrates this.
In the next PR I want to write a proper e2e for the accounts tab.
1. Add a Playwright specific implementation of `PageObjectElement`.
2. Add a click function to PageObjectElement and ButtonPo.
3. Add minimal page objects for `Accounts` and `NnsAccountsFooter`.
4. Add TestIdWrappers to the components for their page objects.
npm run test-e2e
npm run test

Use page objects in example e2e test

---

rs/backend/src/proposals.rs

The init type has changed again. This PR updates the type.
Note: I did not test this change, but just copied the types from the Internet Identity repo.

chore: Update II init type

---

frontend/src/routes/(app)/(u)/(detail)/proposal/+layout.svelte
frontend/src/tests/routes/app/proposals/layout.spec.ts

User is in an SNS proposal detail page.
User clicks in the back icon.
User should see the list of proposals of the same SNS project.
Current: User sees the list of NNS proposals.
* Use the `proposalsPathStore` in the back button of the layout used for the ProposalDetail page.
* Add a test that renders the layouts and clicks in the back button. Add different scenarios testing the different functionality.

Chore: Back button from SNS Proposal Detail page keeps universe

---

scripts/setup

`yq` now has readonly support for toml.  This allows us to read values from Cargo.toml.  E.g. when mocking out crates to warm the cargo cache, we could now potentially use:
```
yq -r .workspace.members[] Cargo.toml -o json | xargs -I{} cargo new "{}"
```
Similarly the newer `yq` can be used to probe the cargo lockfiles.
- Install `yq` from source, to be sure to get the version released a few hours ago.
See CI.
For toml, I have used `yq` on the toml feature branch and verified that the code still works in the release.

Bump yq version

---

frontend/src/tests/fakes/governance-api.fake.ts
frontend/src/tests/fakes/sns-governance-api.fake.ts
frontend/src/tests/utils/module.test-utils.ts

`governance-api` and `sns-governance-api` can both be paused and resumed.
The code to make that work is pretty much duplicate.
And making other fake apis pausable would mean more duplicate code.
1. Add a helper function `makePausable` to make a fake API pausable.
2. Use the helper instead of the duplicated code in `governance-api` and `sns-governance-api`.
Tests still pass.

Helper function to make a fake api pausable

---

frontend/src/tests/page-objects/Accounts.page-object.ts
frontend/src/tests/page-objects/AmountDisplay.page-object.ts
frontend/src/tests/page-objects/Hash.page-object.ts
frontend/src/tests/page-objects/NeuronDetail.page-object.ts
frontend/src/tests/page-objects/Neurons.page-object.ts
frontend/src/tests/page-objects/NnsAccountsFooter.page-object.ts
frontend/src/tests/page-objects/NnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeurons.page-object.ts
frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
frontend/src/tests/page-objects/SkeletonDetails.page-object.ts
frontend/src/tests/page-objects/SnsNeuronCardTitle.page-object.ts
frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/SnsNeuronInfoStake.page-object.ts
frontend/src/tests/page-objects/SnsNeurons.page-object.ts
frontend/src/tests/page-objects/SnsProposalDetail.page-object.ts
frontend/src/tests/page-objects/Tooltip.page-object.ts
frontend/src/tests/page-objects/jest.page-object.ts
frontend/src/tests/page-objects/playwright.page-object.ts
frontend/src/tests/types/page-object.types.ts

We get page object elements by test ID a lot. Add `byTestId` function for convenience and
1. Add `byTestId` function to `PageObjectElement` for convenience and readability.
2. Use it instead of querySelectorAll in places where the selector only specifies a test ID.
npm run test

Add PageObjectElement.byTestId

---

frontend/jest-setup.ts
frontend/src/lib/components/project-detail/ParticipateButton.svelte
frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/pages/ProjectDetail.svelte
frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
frontend/src/tests/lib/pages/ProjectDetail.spec.ts

Move logic to restore participation from the button component to the page component.
There is no new functionality in this PR. This is just refactoring.
Main changes
* Move logic to restore participation from ParticipateButton to ProjectDetail.
* Refactor and organize the code in ProjectDetail.svelte to make it more understandable.
* It's worth taking a look at the ProjectDetail.svelte alone instead of the changes to better understand the flow. I'd like to simplify a bit this, but that will come in another PR.
* In ParticipateButton, I removed all the tests regarding the restoring participation flow.
* In ProjectDetail page, I mocked apis instead of service and adapted tests to it.
* Main and biggest test: make sure that the commitment is updated if there is an open ticket in …

GIX-1336: Refactor restoring participation flow to project detail

---

frontend/src/lib/components/accounts/AddressInput.svelte
frontend/src/tests/lib/components/accounts/AddressInput.spec.ts

Depending where the focus was set, the new QR code button hijacked submitting the form on transaction edit modal first step with "Enter" key.
- explicitely set `type` to `button`

fix: transaction edit submit form with "Enter"

---

frontend/src/tests/e2e/accounts.spec.ts
frontend/src/tests/page-objects/AccountCard.page-object.ts
frontend/src/tests/page-objects/Accounts.page-object.ts
frontend/src/tests/page-objects/App.page-object.ts
frontend/src/tests/page-objects/NnsAccounts.page-object.ts

Moving to Playwright tests which reuse page objects from unit tests.
Starting with accounts tests for the 4 accounts related requirements.
1. Add frontend/src/tests/e2e/accounts.spec.ts with just the beginnings of the e2e test, testing that there is a Main account by default.
2. Add page objects for NnsAccounts and AccountCard.
3. Add AppPo to refer to top-level page objects.
I'm not sure about AppPo but it's easy to change later so I think it makes sense to go with it for now and have another look when there is some more stuff there.
But happy to do something different if you have a suggestion.
In 3 different terminals:
```
dfx start --clean
scripts/dev-local.sh
npm run test-e2e
```

First bit of accounts e2e test.

---

.github/workflows/build.yml
scripts/dfx-nns-deploy-custom
scripts/dfx-software-nd-cache

Faster CI.  We already have builds cached in docker.  Reusing the cache means that we don't need to rebuild unless we need to.  Furthermore, even on cache miss, a docker build takes about 4 minutes which is about as long as it takes just to install the native build tools without even starting to build.
- docker-build the nns-dapp
- Don't build locally
- Remove unneeded tool installation and an unused env var.
See CI

Docker build e2e

---

.github/workflows/build.yml

`run` commands don't give detailed output unless set -x is set at the beginning of every multiline run command. Invariably the log one needs is one where set -x has not yet been set, so one has to add set -x and rerun, which costs time. Better set it at the beginning of the build once for all.
Note: This does cause several lines of startup bash commands to be printed for every `run` command.  On balance, I think it is worth it.
-  Set `-euxo pipefail` by default for every run command in `build.yaml`
See CI

Set -eu by default

---

frontend/src/lib/components/sns-proposals/SnsProposalSystemInfoSection.svelte
frontend/src/lib/components/sns-proposals/SnsProposerEntry.svelte
frontend/src/lib/components/ui/Hash.svelte
frontend/src/lib/pages/SnsProposalDetail.svelte
frontend/src/lib/utils/sns-proposals.utils.ts
frontend/src/tests/lib/components/sns-proposals/SnsProposalSystemInfoSection.spec.ts
frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
frontend/src/tests/page-objects/KeyValuePair.page-object.ts
frontend/src/tests/page-objects/SnsProposalDetail.page-object.ts
frontend/src/tests/page-objects/SnsProposalSystemInfoSection.page-object.ts

User should be able to see the metadata of an SNS proposal.
Main change:
* Implement SnsProposalSystemInfoSection.svelte.
Minor changes:
* New component SnsProposerEntry.svelte to handle the logic of the proposal key value. Not now, it will be in another PR, but that will open the neuron modal if the user is logged in.
* Add new prop `className` to the Hash.svelte component.
* Minor changes in the SnsProposalDetail.svelte to add `rootCanisterId` in the scope so that it can be passed to SnsProposalSystemInfoSection. No change in functionality. The other component that will need it is the SnsProposalVotingSection.
* New scenario in  SnsProposalDetail that tests presence of the metadata.
* Test all the functionality of SnsProposerEntry
* New POs: KeyValuePairPo and …

GIX-1220: SNS proposal - Render system info

---

frontend/src/lib/components/proposal-detail/NnsProposal.svelte
frontend/src/lib/components/proposal-detail/NnsProposalSummarySection.svelte
frontend/src/lib/components/proposal-detail/ProposalSummarySection.svelte
frontend/src/lib/components/sns-proposals/SnsProposalSummarySection.svelte
frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
frontend/src/tests/lib/components/proposal-detail/NnsProposalSummarySection.spec.ts
frontend/src/tests/lib/components/proposal-detail/ProposalSummarySection.spec.ts
frontend/src/tests/lib/components/sns-proposals/SnsProposalSummarySection.spec.ts
frontend/src/tests/page-objects/ProposalSummarySection.page-object.ts
frontend/src/tests/workflows/NnsProposalDetail.spec.ts

Rename components to make clearer what they render.
* Rename file NnsProposalProposerInfoSection.svelte to NnsProposalSummarySection.svelte
* Rename file ProposalProposerInfoSection.svelte to ProposalSummarySection.svelte
* Rename data tid to be consistent with file rename.
* Rename testing file for each of the renamed files.
* Change data tids after change.

Chore: Rename ProposalProposerInfoSection

---

dfx.json

It's not yet easy to run ckBTC canisters locally and without them there are lots of errors in the console when ENABLE_CKBTC is enabled.
Change dfx.json to disable ENABLE_CKBTC on local network.
`__featureFlags.list()` in the console to verify it's disabled by default.

Disable ENABLE_CKBTC on local by default

---

frontend/src/lib/pages/Login.svelte

When subscribing to a Svelte store, you need to make sure to unsubscribe at the appropriate time to avoid a memory leak.
When access a store via `$store` in a Svelte component, the subscribe/unsubscribe is automatic and can't be forgotten.
1. In Login.svelte, use `$authStore` instead of subscribing/unsubscribing explicitly.
Added logging in Login.svelte and auth.store.ts to understand when and how often is subscribed and unsubscribed and manually tested that it's the same with and without this change.

Use auto subscription instead of onDestroy in Login.svelte

---

scripts/sns/aggregator/release
scripts/sns/aggregator/release-template

The nns-dapp is about to get arguments as well, which makes "args.did" ambiguous.
- Rename `arg` to `sns_aggregator_arg`.
None

Rename sns aggregator arg

---

scripts/nns-dapp/release-template

We now have two projects that both need releases, so "PROPOSAL_TEMPLATE" is ambiguous.
* Move the propsal template and update the relative paths to match.
TODO: Update [the release SOP](https://www.notion.so/SOP-Deploy-NNS-dapp-to-mainnet-5347d7438dc04b088c61abd0edb3abd4).
I have run the release template script from the new location and verified that the template was populated.

Move the nns-dapp release template

---

frontend/src/lib/components/sns-proposals/SnsProposalPayloadSection.svelte
frontend/src/tests/lib/components/sns-proposals/SnsProposalPayloadSection.spec.ts
frontend/src/tests/page-objects/SnsProposalPayloadSection.page-object.ts

User can see the payload of an SNS Proposal.
* Implement SnsProposalPayloadSection.svelte using ProposalSummary.svelte.
* New page object SnsProposalPayloadSectionPo
* Test SnsProposalPayloadSection component with new PO.

GIX-1220: SNS Proposal payload card

---

frontend/src/tests/e2e/accounts.spec.ts
frontend/src/tests/page-objects/AccountCard.page-object.ts
frontend/src/tests/page-objects/NnsAccounts.page-object.ts
frontend/src/tests/utils/e2e.test-utils.ts

Continuing with the accounts end-to-end test, we check the next requirement.
1. Check the list of account names in the e2e test.
2. Required page object changes.
3. (not really related but somehow started causing trouble now) While signing in, make sure that we click the correct "Next" button otherwise we might click the same one a second time and get stuck on the next one.

E2E: The user MUST be able to see a list of all their accounts

---

frontend/src/lib/api/dev.api.ts
frontend/src/lib/api/sns-dummy.api.ts

Testnet users should create more types of dummy SNS proposals for better testing.
* Add more dummy proposals in sns-dummy.api.
* Use allSettled and log individual fails for better debugging in testnet.
* Not applicable. Functionality only for testnet.

Chore: Add more dummy SNS proposals

---

frontend/src/lib/components/common/MenuItems.svelte
frontend/src/lib/components/ic/GetTokens.svelte
frontend/src/tests/e2e/accounts.spec.ts
frontend/src/tests/page-objects/App.page-object.ts
frontend/src/tests/page-objects/Backdrop.page-object.ts
frontend/src/tests/page-objects/GetTokens.page-object.ts
frontend/src/tests/page-objects/MenuItems.page-object.ts
frontend/src/tests/page-objects/playwright.page-object.ts
frontend/src/tests/page-objects/simple-base.page-object.ts

We want to test that it's possible to make transactions. For that we need some tokens.
So the "Get ICP" button should be usable from the end-to-end test.
1. Add getting 20 ICP to the accounts e2e test.
2. Add required page objects.
3. Add test IDs to components.
4. Add `.first()` to the locator in in `querySelector()` in PlaywrightPageObjectElement to make the behavior similar to actual querySelector and to get the first backdrop without error.
`npm run test-e2e -- --headed`

E2E: Get ICP

---

rs/backend/src/arguments.rs

The nns-dapp arguments code encodes arguments as JSON.  Unfortunately JSON encoding doesn't work for HTML attributes.  For HTML attributes the only relevant character that we need to escape is `"` and that needs to be encoded as `&quot;` not `\"`.
* Change the argument encoding to the attribute encoding recommended by OWASP.

Escape the quotes

---

config.sh

The argument template has two errors, due to erroneous copying from the testing branch to the small slice merged into main:
* The argument is optional, but `opt` is missing from the code in main.
* Quotes are escaped in the rust code, so the escapes are no longer needed in the template.

Fix argument autoconfig

---

e2e-tests/wdio.conf.ts

E2e tests broke earlier this morning; every test timed out.  But it took 15-18 minutes to see the screenshots of each test.  This test run time is significantly higher than usual, but this error state occurred and the slow response time slowed attempts to diagnose the cause.
The screenshots are available only after the test has complete in its entirety.
* Set the mocha flag to bail out on error.
Note: If some tests in a spec file fail, the test does not exit immediately.  The spec completes and then the e2e tests are killed.
See CI

Fail fast for e2e errors

---

scripts/fmt-yaml

If a yaml file is malformed, the existing yaml formatter will delete it.
- Use `yq --inplace`
- I have verified that it does not change the original file if it fails.
- `--inplace` [writes to a temp file and replaces the original only if there is no error.](https://github.com/mikefarah/yq/blob/5fd2890d1b7faa2cda61c016e81bce0c841b10cb/cmd/evalute_sequence_command.go#L70)
Here we corrupt a yaml file and demonstrate that "formatting" it erases the file.
```
max@sinkpad:~/dfn/nns-dapp (1day,09:42:23)$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
max@sinkpad:~/dfn/nns-dapp (1day,09:42:28)$ printf "%s\n" foo bar >> .github/workflows/build.yml 
max@sinkpad:~/dfn/nns-dapp (1day,09:42:33)$ tail .github/workflows/build.yml
needs: ["build"]
if: ${{ always() }} …
```

Do not delete malformed yaml files

---

scripts/docker-build
scripts/fmt-yaml

If docker-build fails and the user fails to notice, the user may believe that some old artifacts are the output and deploy or validate the wrong files.  Let's remove that risk.
* Delete artifacts before building
See CI

Delete assets before build

---

.github/workflows/docker-main.yaml

The workflow to update the docker cache is supposed to run only on main and one development branch.  But it is running on all pushes.  Because the correct name for the filter is `branches` not `branch`.
* Change `branch` to `branches`
See CI - the "Populate docker cache" workflow should not run.

Fix branch restriction

---

frontend/src/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.svelte

Update toast message after successful increase sns neuron stake.
- update i18n path to be the same as nns version.

fix: change the message after successful increase sns neuron stake

---

scripts/clap.bash

The upstream bash argument parser fixed an issue whereby a missing `print_help()` could cause an error.  The fix was implemented in https://github.com/dfinity/snsdemo/pull/99 and tested in https://github.com/dfinity/snsdemo/pull/102  Pulling in the latest code will fix that issue in our copy of the argument parser.
* Bump the bash argument parser to the latest version in snsdemo.
* The parser is tested upstream
* There are no breaking changes in the API
* CI should verify that there are no unintended breaking changes.

chore: Update bash argument parser

---

.dockerignore

Building the wasm doesn't depend on the frontend tests.
So if we only make changes to frontend tests, we don't need to rebuild the wasm.
If we make Docker ignore the frontend tests, it will take the wasm from the cache instead of rebuilding it, if all the changes are only in the frontend tests.
Add `frontend/src/tests/` to `.dockerignore`.
CI

Add frontend/src/tests to .dockerignore

---

Dockerfile

Sometimes docker builds fail with:
```
#52 0.714    Compiling nns-dapp v2.0.26 (/build/rs/backend)
#52 0.790 error[E0432]: unresolved import `nns_dapp::arguments`
#52 0.790  --> rs/backend/src/bin/nns-dapp-check-args.rs:3:15
#52 0.790   |
#52 0.790 3 | use nns_dapp::arguments::CanisterArguments;
#52 0.790   |               ^^^^^^^^^ could not find `arguments` in `nns_dapp`
#52 0.790 
#52 0.802 For more information about this error, try `rustc --explain E0432`.
```
The code is correct and builds succeed outside docker.
Docker differs from local builds in that it pre-compiles libraries to cache them.  If we do not pre-compile, builds work again but are slow.
The code that pre-compiles the libraries replaces the actual code with aplaceholder, but the placeholder does not include files for …

Fix build flakiness

---

Dockerfile
dfx.json

Docker builds on M1 macs are hard.  One sticking point is building the optimizer, which seems to consume inordinate resources.  Given that the optimizer is now available as a pre-built download, let's use it.
- In the dockerfile, download the optimizer instead of building it.
- Put the optimizer version in dfx, along with other versions.
- Bump the optimizer to the latest available version.
* See CI
* And let's see whether this gets M1 mac builds further

Install a pre-built optimizer

---

frontend/package-lock.json

Fix `SvelteKit vulnerable to Cross-Site Request Forgery - https://github.com/advisories/GHSA-5p75-vc5g-8rv2` (screenshot)
- npm run fix

fix: npm audit fix

---

scripts/dev-local-state.sh

`scripts/dev-local-state.sh` set `-e` which means that it kills itself on any error.
It also traps to restore the state before exiting.
But `dfx start` runs in the background and we want to stop it before restoring the state.
So we should disable `set -e` once the replica is running.
`set +e` once the local replica is running.
1. Ran `scripts/dev-local-state.sh`
2. Deleted `frontend/node_modules` while the script was running
3. Witnessed Vite server crashing
4. Checked that replica was stopped before state was restored.

Wait for replica to stop before restoring state

---

.github/workflows/aggregator.yaml
.github/workflows/build.yml

`xz` does an amazing job of compressing replica state files, reducing our 333Mb snapshots to around 66Mb.
* Bump snsdemo to a version using xz compressed state snapshots
* See CI

Bump snsdemo to xz

---

Dockerfile

Apt packages are installed at the beginning of the dockerfile.  The apt installation of `xxd` was, however, deliberately temporarily placed later to get faster CI builds in a more complicated PR.  Now that it is merged, we can put the installation in the normal place.
* Mv xxd installation to the other apt-installs.
See CI

Mv xxd installation

---

.github/workflows/docker-build.yaml

Deployments of the nns-dapp now need arguments.  It is good if a reference set of arguments is created in CI to check against, in the same way that local builds of the wasm are checked against CI builds.
* Include the build configuration in the CI artifacts.  In particular:
* `deployment-config.json` - the config from which all other config is derived.
* `nns-dapp-arg.did` - the text format of the argument, used when deploying directly
* `nns-dapp-arg.bin` - the binary form of the argument, used when deploying by proposal
* `frontend-config.sh` - the contents of the .env file, used when doing front end develpment.
* See the artifacts when CI runs.  As an added bonus, the wasm may no longer be double-unzipped by mac.  Let's see.

Include arguments with the artifacts

---

.dockerignore

We don't run tests in Docker and we don't need test specific files to run the Docker build.
Add test specific frontend files to `.dockerignore`.
CI

Add more test specific files to .dockerignore

---

.github/workflows/checks.yml

Faster CI.  At present, unit tests and linters wait for the formatting check before proceeding.  This saves CPU cycles but extends the runtime of our slowest workflow by a couple of minutes.
* Remove formatting as a dependency of other checks.  It is still required for the workflow to succeed.

Run formatting in parallel to other CI checks

---

scripts/nns-dapp/ci-link
scripts/nns-dapp/release-template

We now merge PRs in github by means of a merge queue.  As a result, the link to a CI build in the proposal template is now wrong.
* Add a script to search through CI builds for a build of the current commit.
* Use the script to populate the release template.
```
max@sinkpad:~/dfn/nns-dapp/branches/ci-link (28:06)$ ./scripts/nns-dapp/ci-link --commit "$(git rev-parse main)"
https://github.com/dfinity/nns-dapp/actions/runs/4620117942
https://github.com/dfinity/nns-dapp/actions/runs/4619881512
max@sinkpad:~/dfn/nns-dapp/branches/ci-link (31:19)$ git rev-parse main
64f5dfa7d6637d7b5b4f3a4771924351497fa901
max@sinkpad:~/dfn/nns-dapp/branches/ci-link (32:01)$ 
```
Visiting these links should show the same commit.  And it does see the 64f5...
The template uses `tags/release-candidate` and should …

Put the correct CI build link in proposals

---

.github/workflows/docker-build.yaml

When comparing wasm hashes, one possible reason for a mismatch is that different commits were compiled.  To make it easy to spot such an error, why not include the commit and any tags together with the assets from CI?
- Add the first line of git log to the zip file created by CI containing the wasm.
See CI assets

Include the commit in the wasm zip file

---

frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
frontend/src/tests/page-objects/SnsProposalDetail.page-object.ts

Add missing test cases in SnsProposalDetail spec.
* Expose Payload and Summary Section in SnsProposalDetail page object.
* Add test case for payload section specifically that renders the actual payload. It's important that we test that the payload field is rendered, not just the card.
* Add expect for SystemInfoSection and SymmarySection presence in test case for content loaded. Test on contents are done in each component test.
* Pause and resume the fake in the test for the skeleton. This way the test case is controlled.
List of changes above.

Chore: Expand SnsProposalDetail test cases

---

frontend/.prettierignore

`npm run check` complains about `playwright-report/index.html` not being formatted by prettier.
Add `/playwright*` to `frontend/.prettierignore`
After `npm run check` complained, added the line to `frontend/.prettierignore` and ran `npm run check` again.

Ignore playwright dirs for prettier

---

frontend/src/lib/components/proposals/ProposalCard.svelte
frontend/src/lib/components/sns-proposals/SnsProposalCard.svelte
frontend/src/lib/components/sns-proposals/SnsProposalSystemInfoSection.svelte
frontend/src/lib/utils/sns-proposals.utils.ts
frontend/src/tests/lib/components/sns-proposals/SnsProposalSystemInfoSection.spec.ts
frontend/src/tests/lib/pages/SnsProposals.spec.ts
frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
frontend/src/tests/page-objects/SnsProposalSystemInfoSection.page-object.ts

Align NNS Dapp with the agreements reached within the team on how to deal with Type and Topic for SNS proposals.
Result:
* Topic does not exist yet for SNS proposals.
* The type is the name of the nervous function.
* Change mapProposalInfo in sns proposal utils to return the type and typeDescription instead of topic and topicDescription.
* Do not render topic and type items in the SnsProposalSystemInfoSection. Render only the type item.
* Render the type as title in the SnsProposalSystemInfoSection component.
* Adapt tests to new functionality and also change the test descriptions to match the changes.
* Remove getTopicText from SnsProposalSystemInfoSection page object.
* Change testId in SnsProposalCard and add it to the type. This is used to test that the nervous functions are properly …

Feat: Use only type for SNS proposals, no topic

---

.github/workflows/reproducible-assets.yaml
.github/workflows/reproducible.yaml

The reproducibility tests run against different versions of MacOs and Ubuntu.
But https://github.com/dfinity/nns-dapp/pull/1825 and https://github.com/dfinity/nns-dapp/pull/1836 changed the version of Ubuntu we use everywhere, making the different versions in the matrix the same versions.
Make the versions in the workflow matrix of .github/workflows/reproducible-assets.yaml and .github/workflows/reproducible.yaml different again, as before https://github.com/dfinity/nns-dapp/pull/1825.
CI

Fix ubuntu version in workflow matrix

---

frontend/src/tests/e2e/README.md

Document how Playwright end-to-end tests are used.
Add a README.md file in frontend/src/tests/e2e
None

README.md in frontend/src/tests/e2e

---

frontend/src/lib/components/accounts/TransactionList.svelte
frontend/src/tests/e2e/accounts.spec.ts
frontend/src/tests/page-objects/NnsAccounts.page-object.ts
frontend/src/tests/page-objects/NnsWallet.page-object.ts
frontend/src/tests/page-objects/SkeletonCard.page-object.ts
frontend/src/tests/page-objects/TransactionCard.page-object.ts
frontend/src/tests/page-objects/TransactionList.page-object.ts

We want to have end-to-end test for product requirements.
In this PR we add:
AU005: The user MUST be able to see the transactions of a specific account.
1. In the accounts e2e test, after making the transaction, check that the transaction can be seen in the subaccount.
2. Add a test ID to TransactionList.
3. Add page objects for TransactionList and TransactionCard
4. Add functionality in page objects for NnsAccounts, NnsWallet and SkeletonCard
npm run test-e2e

E2E: Verify account transactions

---

frontend/src/tests/e2e/sns-governance.spec.ts
frontend/src/tests/page-objects/Accounts.page-object.ts
frontend/src/tests/page-objects/BaseAccounts.page-object.ts
frontend/src/tests/page-objects/NnsAccounts.page-object.ts
frontend/src/tests/page-objects/SnsAccounts.page-object.ts

Continue with end-to-end tests for SNS.
1. In `frontend/src/tests/e2e/sns-governance.spec.ts`, check the Main account balance after getting tokens.
2. Factor out `BaseAccountsPo` from `NnsAccountsPo` and make `NnsAccountsPo` extend `BaseAccountsPo`.
3. Add `SnsAccountsPo` also extending `BaseAccountsPo`.
`npm run test`

E2E: Check SNS balance after getTokens

---

dfx.json

Revert which build scripts are set in dfx.json for NNS Dapp and SNS Aggregator.
docker-build script is not yet working for M1.
* Revert dfx.json "build" field for nns-dapp and sns_aggregator
Not applicable

Chore: Revert build scripts

---

dfx.json

Deploying II from nns-dapp repo to a testnet deploys a broken II for testnets.
This PR sets the II version to be used, instead of relying in the latest version.
* Change build step for internet_identity project in dfx.json
Not applicable

Fix: Set II release to be used

---

frontend/src/tests/page-objects/jest.page-object.ts

We use page objects for both e2e tests and jest unit tests.
The e2e tests and unit tests that use page objects will overlap more and more and it is good to use the same patterns in both of them.
Also, JestPageObjectElement.isPresent wasn't using the most recent state of the DOM to determine if an element is present.
1. Add a private method `getRootAndFullSelector` to `JestPageObjectElement` to get the furthest available ancestor of the current element and the full selector to point from it to the current element.
2. Use `getRootAndFullSelector` to implement `isPresent` and update this.element.
3. Use `isPresent` to implement both `waitFor` and `waitForAbsent`.
`waitForAbsent` currently isn't used by any unit tests, but the new implementation is so straightforward that it will likely work …

Implement waitForAbsent on JestPageObjectElement

---

.github/workflows/docker-build.yaml
.github/workflows/docker-main.yaml

Releases are blocked by non-reproducible builds.  Builds are reproducible when run without a cache.
- Allow docker builds to be triggered manually, with or without cache.
Docker builds on CI match local builds when the cache is disabled.  Example:
```
Previous HEAD position was 29ebcc863 GIX-1220: SNS proposal - Render system info (#2171)
HEAD is now at 2e010aee0 Improve aggregator test logs (#2177)
Commit: 2e010aee0597aeeba4987beed471945d8068e453
Build hashes for nns-dapp.wasm:
b8945925745ac559fe412e3bd6b72e33d7123c63154068039a4cbf575f404842 4545507226
b8945925745ac559fe412e3bd6b72e33d7123c63154068039a4cbf575f404842 4545354957
0cf7bce91ca1d36cc7a036b78ff8e9c6b1f767c4713d29429c3baf3e52f612bd Local docker build
Local native build
Commit: 2e010aee0597aeeba4987beed471945d8068e453
Build …
```

Manual triggers for docker builds

---

frontend/vite.config.ts

The purpose of the hw chunk was to load hardware wallet logic dynamically only when it's needed.
This does not appear to be working as the vendor chunk currently imports the hw chunk and the hw chunk can be seen to be loaded on initial load.
Additionally, the circular dependency between the chunks seems to occasionally trip up Rollup again to cause build reproducibility issues as well as E2e test flakiness.
Remove the hw chunk from `frontend/vite.config.ts`.
I did limited manual testing but I did not do any testing with hardware wallets.

Remove hw chunk

---

frontend/src/lib/api-services/governance.api-service.ts
frontend/src/lib/services/known-neurons.services.ts
frontend/src/tests/lib/api-services/governance.api-service.spec.ts

Reduce the number of calls by caching the known neurons.
* Service to load known neuron  `listKnownNeurons` uses api service layer.
* Implemet caching for `queryKnownNeurons` in the Governance Api Sevice. Caching doesn't depend on identity because it's the same for all users.
* Test that caching works as expected.

Feat: Add caching for known neurons calls

---

frontend/package-lock.json
frontend/src/lib/api-services/governance.api-service.ts
frontend/src/lib/api/governance.api.ts
frontend/src/lib/pages/NnsNeuronDetail.svelte
frontend/src/lib/services/nns-reward-event.services.ts
frontend/src/tests/fakes/governance-api.fake.ts
frontend/src/tests/lib/api-services/governance.api-service.spec.ts
frontend/src/tests/lib/api/governance.api.spec.ts
frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
frontend/src/tests/mocks/nns-reward-event.mock.ts

We want to show the last time that maturity was distrubuted.
This PR: It implements the api functions to get latest reward events and sets up the service.
Upcoming PRs: Store the event in a store and use it in the component.
* Upgrade next dependencies.
* New governance api function `queryLastestRewardEvent`.
* Add new method in Governance Api Service `queryLastestRewardEvent`. For now, no caching is done.
* Setup reward service `loadLatestRewardEvent` and use it in NnsNeuronDetail page mount.
* Test new api function.
* Test new governance api service method.
* Mock api function where needed to pass current tests.

GIX-1481: Fetch the latest reward event

---

frontend/src/lib/components/ui/EmptyMessage.svelte
frontend/src/tests/e2e/sns-governance.spec.ts
frontend/src/tests/page-objects/App.page-object.ts
frontend/src/tests/page-objects/MenuItems.page-object.ts
frontend/src/tests/page-objects/SnsNeurons.page-object.ts
frontend/src/tests/page-objects/simple-base.page-object.ts

Continuing with SNS end-to-end test.
1. In `frontend/src/tests/e2e/sns-governance.spec.ts` Navigate to the Neuron staking tab.
2. Add tid in `frontend/src/lib/components/ui/EmptyMessage.svelte`
3. Change `frontend/src/tests/page-objects/SnsNeurons.page-object.ts` to check whether the first skeleton card is present rather than whether the number of skeleton cards is 0. This is easier to use with waitFor.
4. For convenience, add optional `tid` arguments to `getText()` and `click` in SImpleBasePageObject to allow specifying specific child elements.
`npm run test`

SNS E2E: Navigate to the neurons tab

---

frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte
frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturityCard.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/themes/mixins/_neuron.scss
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/neuron-detail/NnsNeuronMaturityCard.spec.ts
frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeuronMaturityCard.page-object.ts

We want to show the last time that maturity was distributed.
This PR implements rendering the date of the last reward in the maturity card.
* Render another KeyValuePair in NnsNeuronMaturityCard with the latest maturity distribution date.
* Adapt styles to combine both staked maturity and latest distribution pairs.
* Add test in NnsNeuronDetail page to check that last maturity distribution date is rendered.
* Add test in NnsNeuronMaturityCard to check that last maturity distribution date is rendered or not.

GIX-1481: Render last maturity distribution date

---

deploy.sh

Clean `./deploy.sh`. Most of the functionality there was outdated or not used anymore.
Current script offers only two options:
* Deploy the nns dapp to a network.
* Deploy II to a network
* Changes in `./deploy.sh`

Chore: Clean deploy.sh

---

.github/workflows/build.yml

Apparently e2e tests are flaking out because the aggregator doesn't have enough data when the e2e tests run.
* Configure the aggregator collect data quickly.
* Note: The local replica has an artificial delay to make timing realistic.  In the next dfx that delay is configurable, so it can be made short for fast CI tests or it can be made long to simulate usage in a stressed environment.  This would help here as well, once we upgrade.
*  Wait for the aggregator to have 12 SNS before running e2e tests
See CI

Wait for aggregator

---

rs/sns_aggregator/src/state.rs

It would be really convenient to have timestamps in logs, surprise surprise.
We have very basic logs in the sns_aggregator, basically because a nice clean solution should be coming for all canisters with https://dfinity.atlassian.net/browse/IC-272 so it is not worth putting a huge amount of effort into a custom solution.  However work on the "nice" implementation has not started on that yet.  So we need a minimally better stop-gap solution.
* Add timestamps to logs.
* Note: The timestamps use the IC's native time, which provides nanoseconds.  No attempt is made to spend cycles to format the timestamps or do anything fancy whatsoever.
```
max@sinkpad:~/dfn/nns-dapp/branches/log-timestamps (6:25)$ dfx-snapshot-restore --snapshot ~/.cache/dfinity/versions/0.13.1/snapshots/state.tar.xz …
```

feat (aggregator): Include timestamps in logs

---

scripts/nns-dapp/ci-consistency

We need to be able to find inconsistent builds across CI and local docker builds, as used by verifiers.
* Add a script that looks for CI builds of a commit and compares  those builds with the local docker build.
* Add the ability to scan a range of commits
Sample output.  This shows that CI run 4701442653 produced a different hash from other CI runs and the local docker build.
You can see the run here: https://github.com/dfinity/nns-dapp/actions/runs/4701442653
```
Build hashes for nns-dapp.wasm:
dce3d050e0826e5586ac196ae620de3979d3b778d998e401dc9f25928772460a 4703965352
3350f1ec42a95d7d1196ca1ec62900e7bb82769e02ec3d0bf4ec8e0d182cc362 4701442653
dce3d050e0826e5586ac196ae620de3979d3b778d998e401dc9f25928772460a 4690422724
dce3d050e0826e5586ac196ae620de3979d3b778d998e401dc9f25928772460a …
```

Hash comparison tool

---

frontend/src/lib/constants/environment.constants.ts

When the frontend runs on localhost but the aggregator on testnet, we have to add `.raw` to the URL to avoid CORS issues.
But when the aggregator also runs on localhost, this is not necessary and doesn't work.
We had logic for this but it was broken.
Check if the hostname contains `localhost` or `127.0.0.1` instead of checking if it's equal.
Manually tested against local and against testnet.

Fix aggregator URL on local

---

frontend/src/lib/components/accounts/BitcoinTransactionInfo.svelte
frontend/src/lib/components/transaction/TransactionDescription.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/accounts/BitcoinTransactionInfo.spec.ts
frontend/src/tests/lib/components/transaction/TransactionDescription.spec.ts

On ICP network, display transaction information "Seconds" in review step.
- display transaction time info for all transaction and seconds if icp

Display transaction seconds information

---

frontend/src/lib/components/accounts/BitcoinEstimatedAmountReceived.svelte
frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/accounts/BitcoinEstimatedAmountReceived.spec.ts
frontend/src/tests/lib/components/transaction/TransactionReceivedTokenAmount.spec.ts

Instead of repeating "Estimated..." on review step, display a notice.
- update label and display notice
Before:
After:

Transaction ckBTC simplify estimation label

---

frontend/.eslintrc.cjs
frontend/src/tests/page-objects/NnsWallet.page-object.ts

Unreachable code is usually not intended.
Not allowing it helps to avoid mistakes.
1. Configure eslint to forbid unreachable code.
2. Fix the place where we had unreachable code.
CI

Lint: Forbid unreachable code

---

frontend/scripts/build.csp.mjs
frontend/src/lib/constants/sns.constants.ts
frontend/src/tests/lib/api/sns-aggregator.api.spec.ts

We want wasms that are agnostic to the testnet they will be installed in.
In this PR: I added a missing env var (SNS_AGGREGATOR_URL) used for the CSP rule.
* Add placeholder `SNS_AGGREGATOR_URL` in CSP content-src rule.
Not applicable

Fix: Add SNS Aggregator URL placeholder in CSP

---

frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/components/neuron-detail/NnsNeuronMaturityCard.spec.ts
frontend/src/tests/page-objects/KeyValuePairInfo.page-object.ts
frontend/src/tests/page-objects/NnsNeuronMaturityCard.page-object.ts

Show an explanation of the last distributed maturity in NNS.
* Use a `KeyValuePairInfo` instead of just a `KeyValuePair` to render the last distributed maturity.
* Test that description is also rendered.

Feat: Show info text for Last Distribution

---

frontend/src/lib/components/canisters/ConfirmCyclesCanister.svelte

Just a patch. Someday we should take the time to review the all canister creation flow and integrate the `Transaction` components.
Is:
After:

Fix confirm cycles overflow style

---

Dockerfile

In order to cache the dependency building, the rust source code is replaced by dummy code.  However there is then a risk that the dummy wasm is mistaken for the final output.
- Remove wasms after pre-compiling libraries.
- Touch the source code, as cargo decides whether to rebuild based on timestamps.

Remove dummy wasm

---

frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte

There is too much space when the information about the last maturity distribution is rendered.
* Add a wrapper around the KeyValuePairInfo that renders the description so that the container style do not apply to the header and description.
Not applicable. Only style has changed.

Fix: Spacing in last maturity distribution

---

frontend/package-lock.json
frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts
frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
frontend/src/tests/mocks/accounts.store.mock.ts
frontend/src/tests/mocks/icrc-transactions.mock.ts
frontend/src/tests/mocks/sns-accounts.mock.ts

Bump ic-js to implement what might be the definitive textual encoding for ICRC-1 account.
Source of encoding 👉 https://github.com/dfinity/ICRC-1/pull/98
- bump ic-js
- test: fix mock data from / to that were incorrectly set
- test: use object param to avoid from / to to be incorrectly set in the future
- test: partial mock subaccount array isn't supported anymore to encode/decode ICRC account as the decoded checks the validity of the checksum

ICRC account textual representation

---

frontend/src/routes/+layout.ts

There is a bug in Rollup that non-deterministically fails to detect cyclic
dependencies. https://github.com/rollup/plugins/issues/1425
As a result `lru-cache` is sometimes wrapped in a `requireLruCache` function and sometimes it is not.
This makes our build non-deterministic.
`lru-caceh` is not itself part of a circular dependency but `semver/classes/range.js`, which depends on `lru-cache`, is.
By depending on `lru-cache` directly from our app, we change the order in which modules are analyzed by Rollup, hopefully avoiding the buggy behavior.
It probably doesn't matter where we put this import, so I put it as close to the root of the app as I could find.
Add `import "lru-cache"` in frontend/src/routes/+layout.ts
Inspected generated `vendor` chunk to see that it does not have …

Potential work-around for Rollup cyclic dependency bug

---

rs/backend/src/main.rs

We are concerned that the pre-upgrade cycle count may be too high and may cause the canister to fail to upgrade.
Storing pre-upgrade cycle counts in the stats structure is a bit tricky, as data would have to be stored in stable memory and the cycles are consumed by storing data in stable memory.  This can be solved if we upgrade the memory structure (extremely carefully!) to the new stable memory library.  That also supports stable structures, which makes this problem go away.
In the meantime, a simple solution is to print out the instruction counter counter and look at the replica logs; we run one of the servers on the nns subnet so have access to logs there.  Longer term, logs will be available to all canisters via a ring buffer but that is work in progress.
- Print the instruction …

Log pre-upgrade cycle count

---

frontend/src/lib/components/proposal-detail/ProposalContentCell.svelte

Fix the missing voting button gap (see screenshots)
- ~~use custom div to provide last-of-type style and test id.~~
- add test-id to the content details div

fix: broken gap by tid

---

.github/workflows/docker-build.yaml
.github/workflows/nightly.yaml
dfx.json

We wish to test a recent build (not prod) against the rest of the IC test environment.
* Nightly release
* No need to make a new release if there is an existing release
* The nns-dapp wasm should be available with the commit in the filename.
* To the nightly workflow, add a job that tags the head of main with `nightly-YYY-mm-dd`
* In the docker-build job that creates releases:
* Make a copy of the wasm that includes the commit in the name and include it in the release artefacts.
* Make nightly releases public, so that the wasms are accessible
* I have triggered the workflow manually by pushing to the develop branch.  It is hard to get workflows to get tags, so I have not been able to confirm that no new releases are created if there are no changes.  I have been able to confirm that the …

Nightly tag

---

frontend/src/tests/e2e/sns-governance.spec.ts
frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
frontend/src/tests/page-objects/App.page-object.ts
frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
frontend/src/tests/page-objects/NnsNeuronMaturityCard.page-object.ts
frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts

Continue with SNS end-to-end test.
1. Check the neuron detail in the e2e test.
2. Make the SnsNeuronDetailsPo accessible via AppPo.
3. Add convenience getStake method to SnsNeuronDetailsPo.
4. Conveniently trim the result of getTitle() in SnsNeuronDetailsPo.
5. Update existing `frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts` to use the new convenience methods as well.
6. Change relative imports that break Playwright to absolute imports.
`npm run test e2e -- sns`
`npm run test`

E2E: Check SNS neuron detail

---

scripts/nns-dapp/ci-consistency

Default `sed` on Mac is different from `sed` on Linux and does not support all the same features.
Use a simpler grep command to get the hash from the log.
`scripts/nns-dapp/ci-consistency -c  9820416751a40d477ae33d15dcd6e5736ca46fd6..0a78d9c380901d26e5841b58bc2467209544e1cb`

Use grep instead of sed in ci-consistency

---

scripts/ckbtc/deploy-ckbtc

I understand that the test environment ckbtc canister names should have the prefix ckbtc_ with no test.
* `s/ckbtc_test_/ckbtc_/g`
None.

No test in ckbtc canister names

---

frontend/src/tests/e2e/sns-governance.spec.ts

Avoid flakiness in the end-to-end test.
Previously I assumed that when the stake neuron modal is closed, the neurons are already loaded.
But I noticed at least once that the test failed because the neurons weren't loaded.
Wait for sns neurons to be loaded before checking that the neuron cards are there.

E2E: Wait for SNS neurons to be loaded.

---

frontend/package-lock.json
frontend/src/tests/page-objects/KeyValuePairInfo.page-object.ts

The page object of the KeyValuePairInfo was relying in the parent to get the description because the data-tid was not added at the root.
The PR in GIX Components: https://github.com/dfinity/gix-components/pull/199 sets the test id of KeyValuePairInfo in the root component.
* Upgrade gix-components library.
* Change the way KeyValuePairInfoPo accesses the description text. There is no need to keep a reference to the parent.
Changes only in test implementations, not no test changes.

Chore: Use parent data-tid in KeyValuePairInfo

---

.github/workflows/checks.yml

Cleaning up.
1. `npm run test` and `npm run test` don't need `dfx` or `.env` so remove those steps from the `svelte-tests` and `svelte-lint` jobs.
2. Remove comment about temporarily disabling lint. It's already no longer disabled.
3. Add default `bash -euxlo pipefail {0}` to fail in a more predictable way and log what happens.
CI

Remove unnecessary steps from checks.yml workflow

---

frontend/src/tests/e2e/sns-participation.spec.ts
frontend/src/tests/page-objects/App.page-object.ts
frontend/src/tests/page-objects/MenuItems.page-object.ts

We want to test SNS swap participation.
This just puts the test file in place to be extended in future PRs.
1. Add frontend/src/tests/e2e/sns-participation.spec.ts which just signs in and navigates to the launchpad. It contains TODOs for what to test.
2. Add PO functionality for navigating to the launchpad.
3. Make sure the app is loaded before we check if we need to open the menu or not.
4. Make click methods in `MenuItems.page-object.ts` return a `Promise`. It was an oversight that they didn't.

E2E: SNS swap participation

---

frontend/src/lib/components/launchpad/ProjectCard.svelte
frontend/src/tests/lib/components/launchpad/Projects.spec.ts

I'm adding a testId to `ProjectCard` in https://github.com/dfinity/nns-dapp/pull/2361 but it overrides the testId of the `Card` component, which causes an existing test to fail.
Because the test is unrelated to that PR, I'm updating it in this separate PR.
1. Add testId on `Card` in `frontend/src/lib/components/launchpad/ProjectCard.svelte`.
2. Update `frontend/src/tests/lib/components/launchpad/Projects.spec.ts` to use that testId instead of the default `"card"` testId.
`npm run test`

Add testId to ProjectCard

---

frontend/src/lib/components/launchpad/Projects.svelte
frontend/src/lib/pages/Launchpad.svelte
frontend/src/tests/lib/components/launchpad/Projects.spec.ts

I'm adding a required testId to the `Projects` component in #2361 which causes warnings in an existing test.
Because the test is unrelated to that PR, I'm updating it in this separate PR.
1. Add testId wrapper to frontend/src/lib/components/launchpad/Projects.svelte
2. Add testIds in frontend/src/tests/lib/components/launchpad/Projects.spec.ts
`npm run test`

Add testId to Projects component

---

.github/workflows/build.yml
.github/workflows/docker-build.yaml
.gitignore
Dockerfile
config.sh
config.test
deploy.sh
scripts/docker-build
scripts/nns-dapp/downgrade-upgrade-test
scripts/nns-dapp/release
scripts/nns-dapp/release-check
scripts/nns-dapp/release-template

How is it possible to mess up when deploying to production?  One answer: It is possible to deploy testnet artefacts to mainnet.  Testnet and mainnet now use the same wasm, however it is possible to accidentally use testnet args on mainnet, especially when we test deployments beforehand on local and static testnets.
- Rename nns-dapp-args.did and nns-dapp-args.bin to `nns-dapp-args-${$DFX_NETWORK}.did` and `...bin`

Include network in arg file paths

---

.github/workflows/docker-build.yaml

The wasm build no longer depends on network, so there is no need to build it for two networks.
The only difference between the docker build outputs is whether the arguments are prepared for mainnet or localhost.  The mainnet arguments can be used for release verification.  If we really need the localhost arguments we can generate them by running ./config.sh.
* run the docker build for mainnet only.
See CI

Build only one wasm

---

frontend/playwright.config.ts

Reduce CI time.
Tests that run in parallel do run quite a bit slower per test, but overall they finish sooner because they don't have to wait for each other.
I tried 6 workers but it made the tests significantly slower.
We can try more once we have the more powerful runners.
1. Set `workers: 3` in `frontend/playwright.config.ts` to allow Playwright e2e tests to run in parallel.
2. Increase timeout of individual tests.
CI

Run e2e tests in parallel on CI.

---

frontend/src/tests/page-objects/AddSubAccount.page-object.ts
frontend/src/tests/page-objects/App.page-object.ts
frontend/src/tests/page-objects/AppPo.spec.ts
frontend/src/tests/page-objects/simple-base.page-object.ts

Somehow, Playwright doesn't do typechecking.
So page objects which are only used in Playwright tests, often have type errors which are only caught when those page objects are first used in a Jest test.
Most/all page objects used by Playwright tests are (indirectly) depended on by `AppPo`.
1. Add a dummy Jest test which depends on AppPo.
2. Fix discovered issues.
`npm run test`

Typecheck page objects

---

frontend/package.json

Vite transpile only. We are fine because we have checks and are using editors as recommended by vite.
For even more safety, this PR adds `tsc` to the build as we did yesterday in II ([#1467](https://github.com/dfinity/internet-identity/pull/1467)).
Documentation: https://vitejs.dev/guide/features.html#transpile-only

Add tsc types check

---

rs/sns_aggregator/Cargo.toml

The `sns_aggregator` has a feature flag.  Rather surprisingly, it works even though it is not set in the Cargo.toml.  Still, it is better to declare it.
- Declare the feature flag
- Using the `--features` flag did not work but does now:
```
Main:
max@sinkpad:~/dfn/nns-dapp (4)$ cargo check -p sns_aggregator --features reconfigurable
error: none of the selected packages contains these features: reconfigurable
max@sinkpad:~/dfn/nns-dapp (11)$ 
This branch:
max@sinkpad:~/dfn/nns-dapp/branches/declare-feature (12:58)$ cargo check -p sns_aggregator --features reconfigurable
[successful output]
```
- [By default features are not enabled](https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature), so the feature flag should not be enabled for non-dev builds. Still, to double …

Declare feature flag

---

HACKING.md
frontend/package.json
frontend/src/lib/constants/environment.constants.ts
frontend/src/lib/utils/env-vars.utils.ts
frontend/src/lib/utils/env.utils.ts
frontend/src/tests/lib/utils/env.utils.spec.ts

Fix `npm run preview` which runs a production-like environment.
Main change:
* Logic inside `getEnvVars`. Force to use the build env vars if the port is set. This is the case for local dev server and preview.
Minor changes:
* Add `raw` to the SNS aggregator url when running from localhost as well. This is skipped if the `url` of the aggregator already includes `localhost`.
* New env util `isLocalhost`.
* Test new env util.
I tested the three ways:
* Deploy to testnet
* Local dev server
* Preview
Add a comment on how to run `npm run preview`.

GIX-1505: Fix prod preview

---

.github/workflows/docker-build.yaml
.github/workflows/nightly.yaml

Triggering builds with tags is unreliable.  Presumably there is a race condition between adding a tag to git and triggering the run, so the list of tags known to git may or may not include the tag that triggered an event.
- Check whether a docker-build workflow was triggered by a tag.  If so, add the tag to the list of tags for this commit, if it is not already there.
Only time will tell for sure.  But pushing a tag does show the tag being identified in the github workflow.

Fix nightly tagging

---

frontend/src/lib/i18n/en.json
frontend/src/lib/services/ckbtc-minter.services.ts
frontend/src/lib/types/ckbtc.errors.ts
frontend/src/lib/types/i18n.d.ts
frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts

> The "error" message when there are no new UXTOs looks to "error" like to me ("Sorry, the balance cannot be updated. There are no new UTXOs to process."). This is expected behaviour, not an error. I'm not sure users know what UXTOs are. Can we remove the (!) symbol and simply say "Updated available ckBTC : No new confirmed BTC "
- display UTXO error as info

ckBTC display error as info

---

.github/workflows/docker-build.yaml

Argument files were not in the zip file from docker-build job.
* There is a typo in the name of the files.
Wait for the CI to create and upload the files.

Fix: Typo in file names in docker build uploads

---

rs/sns_aggregator/src/types/slow.rs
rs/sns_aggregator/src/types/upstream.rs
rs/sns_aggregator/src/upstream.rs

The SNS aggregator uses the deprecated endpoint `get_state`.
We want to move away from this endpoint.
This PR: Fetch swap parameters from new endpoint `get_init`.
* Add new property `init` to `UpstreamData`.
* Fetch the data from `get_init` when we fetch the other data.
* Add new property `init` to `SlowSnsData` which is used to render the JSON.
* There is no data transformation. And we still don't have integration tests to check calls to the backend.

GIX-1519: Stop using deprecated endpoint in SNS Aggregator. Part 2

---

frontend/src/lib/api/sns-aggregator.api.ts
frontend/src/lib/services/$public/sns.services.ts
frontend/src/tests/lib/api/sns-aggregator.api.spec.ts
frontend/src/tests/lib/services/_public/sns.services.spec.ts
frontend/src/tests/mocks/sns-aggregator.mock.json
frontend/src/tests/mocks/sns-aggregator.mock.ts

A few weeks ago we added a new field in the SNS aggregator. The NNS Dapp upgraded first and to handle backwards compatibility we set the field as optional.
Now that SNS aggregator was upgraded we can set the field `icrc1_total_supply` as required.
Main change:
* Set field icrc1_total_supply required in the data from aggregator `CachedSnsMetadataDto`.
Minor change:
* No need to filter out by icrc1_total_supply not defined when setting the `snsTotalTokenSupplyStore` from SNS aggregator.
* Add the new field in the SNS Aggregator mocks.
* Remove icrc1_total_supply specific test cases. The field is now required and expected with the mock.

GIX-1416: Set icrc1_total_supply as required

---

frontend/src/lib/api/tvl.api.cjs.ts
frontend/src/lib/constants/canister-ids.constants.ts
frontend/src/tests/lib/api/tvl.api.spec.ts

TVl calls create an error on testnet where there is no TVL canister.
* Return `undefined` and skip call If TVL_CANISTER_ID is not present in tvl api.
* Add a test in tvl api to check new use case.

Chore: No TVL call if no TVL canister id
