.github/workflows/build.yml
[In CI](https://github.com/dfinity/nns-dapp/actions/runs/4794994667/jobs/8529002330) I'm seeing this message:
```
╔═══════════════════════════════════════════════════════════════════════════════╗
║ WARNING: It looks like you are running 'npx playwright install' without first ║
║ installing your project's dependencies.                                       ║
║                                                                               ║
║ To avoid unexpected behavior, please install your dependencies first, and     ║
║ then run Playwright's install command:                                        ║
║                                                                               ║
║     npm install                                                               ║
║     npx playwright install …
```
=> npm ci before playwright install

rs/backend/src/assets.rs
The Kibana logs are flooded with print statements about inserting assets.  We can probably survive with fewer and the mass of messages makes it harder to pick out other activity.
- Print a count of asset insertions rather than a blow by blow narrative of every wonderful chunk that is now available.
- Print the canister install/upgrade arguments as a one-liner.  It's not as pretty when running locally but is much easier when getting the data in Kibana.  Not just easier, it turns out that a multi-line printout in Kibana logs the first line N times where N is the number of lines.  Spammy and information free.
See a deployment log now:
```
[Canister st75y-vaaaa-aaaaa-aaalq-cai] post_upgrade with args: Some(CanisterArguments { args: [("CYCLES_MINTING_CANISTER_ID", …
```
=> Summarize insertion

Cargo.lock, rs/backend/Cargo.toml, rs/backend/nns-dapp-exports.txt, rs/backend/src/proposals.rs
We need to be able to deal with the new `Action` variant `CreateServiceNervousSystem` in `rs/nns/governance/canister/governance.did` added in https://github.com/dfinity/ic/commit/878bc1d335d3ad9056b6384ddd0c2bbcaf925ec9
According to [this forum post](https://forum.dfinity.org/t/nns-updates-announcing-nns-updates-breaking-changes-on-next-release/19601/2), the new governance canister release is cut from commit https://github.com/dfinity/ic/commit/89129b8212791d7e05cab62ff08eece2888a86e0
1. Updated `Cargo.toml` to change all ic repo commits from `21d3a113dc765b5e5803d9ad4dc68e14880ae6a0` to `89129b8212791d7e05cab62ff08eece2888a86e0`.
2. Ran `cargo update`
3. Updated the fully qualified name of `AddCanisterProposal`, `ChangeCanisterProposal`, `StopOrStartCanisterProposal` which were moved to …
=> Update IC commit in Cargo.toml

rs/sns_aggregator/src/types/slow.rs, rs/sns_aggregator/src/types/upstream.rs, rs/sns_aggregator/src/upstream.rs
The SNS aggregator uses the deprecated endpoint `get_state`.
We want to move away from this endpoint.
This PR: Fetch swap parameters from new endpoint `get_derived_state`.
* Add new property `derived_state` to `UpstreamData`.
* Fetch the data from `get_derived_state` when we fetch the other data.
* Add new property `derived_state` to `SlowSnsData` which is used to render the JSON.
* There is no data transformation. And we still don't have integration tests to check calls to the backend.
=> GIX-1519: Stop using deprecated endpoint in SNS Aggregator. Part 3

frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte, frontend/src/lib/modals/sns/proposals/SnsFilterRewardsModal.svelte, frontend/src/lib/services/sns-filters.services.ts, frontend/src/lib/stores/sns-filters.store.ts, frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts, frontend/src/tests/lib/modals/sns/SnsFilterRewardsModal.spec.ts, frontend/src/tests/lib/services/sns-filters.services.spec.ts, frontend/src/tests/lib/stores/sns-filters.store.spec.ts
Users want to filter SNS proposal by reward status.
* New filters modal `SnsFilterRewardsModal`.
* Add rewards filters button in SnsProposalsFilters component.
* Open `SnsFilterRewardsModal` when rewards filter button is clicked.
* Load reward status filters in `loadSnsFilters` service.
* Add new methods to `snsFiltersStore` to manage reward status.
* Test new modal `SnsFilterRewardsModal`.
* Add test case in `SnsProposalsFilters` for new button.
* Add test case in `loadSnsFilters` service.
* Add test case for new functionality in `snsFiltersStore`.
=> GIX-1212: Add sns proposal filters reward status

Cargo.lock, frontend/src/lib/i18n/en.governance.json, frontend/src/lib/types/i18n.d.ts, rs/backend/Cargo.toml, rs/backend/src/proposals.rs
A new nns function proposal type `BitcoinSetConfigProposal` was added in https://github.com/dfinity/ic/commit/a8e08f558c4db1dd009556d60af64fdb3e8e9c19#diff-98b58f03b1cbc116d2def85c2e6a81c4be8cda5e6f3cc994f0177db15d62c85e
We should be able to render the payload properly.
1. Added dependency `ic-btc-interface` in `rs/backend/Cargo.toml`
2. (I would have had to update the ic revision in the Cargo.toml as well, to pull in the new proposal type, but it was already done in https://github.com/dfinity/nns-dapp/pull/2401)
3. Ran `cargo update` to update `Cargo.lock`
4. Changes in `proposals.rs` to parse the payload of `BitcoinSetConfigProposal` as `SetConfigRequest`.
5. Added i18n labels.
1. `dfx start --clean`
2. `rm $(dfx cache show)/wasms/*`
3. …
=> GIX-1518 Render BitcoinSetConfig proposal payload

scripts/nns-dapp/test-exports
When dependencies change, the build can fail with output like this:
```
Sanity check
0a1
> canister_global_timer
9a11
> canister_update <ic-cdk internal> timer_executor
```
This is quite confusing.
1. Explain the failure
2. Give instructions for what to do
3. Add functionality to update the `nns-dapp-exports.txt` file.
Now it looks like this:
```
Sanity check
0a1
> canister_global_timer
9a11
> canister_update <ic-cdk internal> timer_executor
Exports do not match
If this looks correct, run 'scripts/nns-dapp/test-exports --wasm nns-dapp.wasm --update-golden' to update the golden file
```
1. Manually changed `nns-dapp-exports.txt` and ran `DFX_NETWORK=local ./build.sh` to see it fail.
2. Followed the instructions and ran the build again to see it pass.
=> Make test-exports failure less confusing

frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte, frontend/src/lib/utils/bitcoin.utils.ts, frontend/src/tests/lib/components/transaction/TransactionReceivedTokenAmount.spec.ts, frontend/src/tests/lib/utils/bitcoin.utils.spec.ts
Remove symbol estimation `≈` for ckBTC amounts as requested.
=> Remove symbol estimation ≈ for ckBTC amounts

frontend/src/lib/api/ckbtc-ledger.api.ts, frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/lib/api/sns-ledger.api.ts, frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
We need to query the balance of Icrc ledger for other accounts than `main`. This PR extends the API to supports the `owner` as an argument.
=> Extend getIcrcAccount with owner and subaccount

frontend/src/tests/e2e/sns-participation.spec.ts, frontend/src/tests/page-objects/Launchpad.page-object.ts
Continuing with the SNS participation end-to-end test
1. Test that the user can see a list of committed projects.
2. Add a getter for the list of the committed projects to the Launchpad page object.
1. Created a dfx snapshot in the snsdemo repository at tag release-2023-04-27, which is what we run on CI.
2. Ran `npm run test-e2e` against that snapshot.
=> E2E: See committed swaps

frontend/src/lib/utils/sns-proposals.utils.ts, frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
There was a bug in the `snsRewardStatus` sns proposal util
* The reward status is accepting votes if the deadline is in the future. Duh!
* Adapt tests.
=> GIX-1212: Fix SnsRewardStatus util

frontend/src/lib/constants/stores.constants.ts, frontend/src/lib/stores/feature-flags.store.ts, frontend/src/lib/stores/proposals.store.ts, frontend/src/lib/stores/writable-stored.ts, frontend/src/tests/lib/stores/writable-stored.spec.ts
Enums commonly and in our code base starts with an uppercase.
- `storeLocalStorageKey` -> `StoreLocalStorageKey`
=> Uppercase enum storeLocalStorageKey

rs/sns_aggregator/src/types/slow.rs, rs/sns_aggregator/src/types/upstream.rs, rs/sns_aggregator/src/upstream.rs
The SNS aggregator uses the deprecated endpoint `get_state`.
We want to move away from this endpoint.
This PR: Fetch swap parameters from new endpoint `get_lifecycle`.
* Add new property `lifecycle` to `UpstreamData`.
* Fetch the data from `get_lifecycle` when we fetch the other data.
* Add new property `lifecycle` to `SlowSnsData` which is used to render the JSON.
* There is no data transformation. And we still don't have integration tests to check calls to the backend.
=> GIX-1519: Stop using deprecated endpoint in SNS Aggregator. Part 4

frontend/src/lib/services/ckbtc-convert.services.ts, frontend/src/lib/services/ckbtc-minter.services.ts, frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
We will need `getWithdrawalAccount` in PR #2430 for a new feature. Therefore this PR extract the dedicated service function that handle errors in the `minter.service`. That way we can avoid the try/catch/toastError.
Refactor  only.
=> refactor: extract getWithdrawalAccount to minter service

frontend/src/lib/api/ckbtc-ledger.api.ts, frontend/src/lib/services/ckbtc-accounts-balance.services.ts, frontend/src/lib/services/ckbtc-accounts-loader.services.ts, frontend/src/lib/services/ckbtc-accounts.services.ts, frontend/src/tests/lib/api/ckbtc-ledger.api.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts-balance.services.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts-loader.services.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts.services.spec.ts, frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
We will need to fetch the balance of another pseudo ckBTC account - the withdrawal account - in PR #2430.
That's why this PR makes the ckBTC ledger API returns a single account and extract the logic of fetching the main account into a new service. That way we can in the other PR add a new function that will fetch the account using the same API..
Refactor  only.
=> Make ckBTC ledger API return a single account

frontend/static/assets/libs/dummy-proposals.utils.js
Add a dummy proposal to create Exchange Rate proposals.
There is an issue with those proposals where the user is always able to vote, even after voting.
The problem seems in the data coming from the backend.
This PR will help us debug the issue faster by being able to create the proposal responsible for the problem.
* Add a new dummy proposal to the list of dummy proposals for NNS.
Not applicable
=> Chore: Add exchange rate proposal

frontend/src/lib/constants/stores.constants.ts, frontend/src/lib/stores/sns-filters.store.ts
Users commonly use the same filters for proposals.
Persist the selection of the filters in local storage.
* Create the sns filters store with our `writableStored` instead of `writable` from Svelte.
Same functionality. Maybe there could be an end-to-end test for this in the future?
=> Chore: Persist Sns Proposal Filters

frontend/package-lock.json, frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte, frontend/src/lib/components/accounts/NnsAddAccount.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/accounts/CkBTCWithdrawalAccount.spec.ts
On ckBTC accounts page, once per session, query and display the potential remaining balance of the withdrawal account (function introduced in PR #2430).
- If balance is bigger than zero, display a call to action that will ultimately open the transaction modal to unblock the funds (not part of this PR).
- If balance is zero, display a feedback to the user before hiding the information.
- bump gix-cmp for styling and new icons
- implement UI logic
=> Display ckBTC withdrawal account and animation

frontend/src/lib/components/transaction/TransactionForm.svelte, frontend/src/lib/components/transaction/TransactionFormFee.svelte, frontend/src/lib/components/transaction/TransactionReview.svelte, frontend/src/lib/components/transaction/TransactionSummary.svelte, frontend/src/lib/modals/transaction/TransactionModal.svelte, frontend/src/lib/types/transaction.ts, frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
In case of retry of the conversion of ckBTC to BTC stuck in the withdrawal account, there is no transfer to the ledger and therefore no ledger fee to display in the transaction modal
- add `showLedgerFee` option in transaction modal
- hide ledger fees if set to `false`
=> Option to hide ledger fee in transaction

scripts/update-ii
internet_identity stopped offering non-gzipped artifacts.
I'm not sure what this is used for but it seems to be (one of many reasons?) why the Nightly Publication workflow is failing.
Add `.gz` to the internet_identity wasm URL in scripts/update-ii
Ran the script and instead of causing an error, it updated `dfx.json`.
=> Add .gz to internet-identity wasm URL

frontend/src/lib/services/accounts.services.ts, frontend/src/tests/lib/services/accounts.services.spec.ts
`syncAccounts` has an errorHandler parameter but this is only used by `initAccounts` in the same file.
By limiting the functionality we export out of the file it becomes easier to refactor without breaking anything.
1. Add `syncAccountsWithErrorHandler` (which is not exported) and called by both `initAccounts` and `syncAccounts`.
2. Remove the optional errorHandler parameter from `syncAccounts`.
3. Remove the tests that test this parameter.
Unused functionality is removed so the corresponding tests are removed.
`initAccounts` is still tested separately as it was before.
=> Don't expose syncAccounts error handler

frontend/src/lib/components/launchpad/ProjectCard.svelte, frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte, frontend/src/lib/components/project-detail/ParticipateButton.svelte, frontend/src/lib/types/sns.ts, frontend/src/lib/utils/sns.utils.ts, frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts, frontend/src/tests/lib/components/launchpad/ProjectCardSwapInfo.spec.ts, frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts, frontend/src/tests/lib/utils/sns.utils.spec.ts, frontend/src/tests/page-objects/ProjectCard.page-object.ts
Users could not participate in a swap because the button was not enabled.
Main change:
* Fix logic in `getCommitmentE8s`. Differentiate better values of `0` (no commitment) and `undefined` (commitment not yet loaded).
Minor change:
* In ProjectCard, change the logic to find if the card needs to be highlighted or not.
* In ProjectCardSwapInfo, change the logic to know when to render user commitment.
* Add a test in ParticipateButton component with no commitment.
* Add test case in ProjectCard for the highlighted logic.
* Add test case in ProjectCardSwapInfo for the commitment data rendering.
* Add test case in `getCommitmentE8s` to have a test for all cases.
* Add some functionality in ProjectCard page object to be used in the unit test.
=> Fix: Participation flow

frontend/src/lib/services/accounts.services.ts, frontend/src/lib/stores/accounts.store.ts, frontend/src/lib/stores/queued-store.ts, frontend/src/tests/lib/services/accounts.services.spec.ts, frontend/src/tests/lib/stores/accounts.store.spec.ts, frontend/src/tests/lib/stores/queued-store.spec.ts
There is a race condition with queryAndUpdate. If you call queryAndUpdate again before the "update" from the first queryAndUpdate responds, then when the first update does respond, it can overwrite responses from the second queryAndUpdate with old data.
This is causing end-to-end tests to be flaky.
To mitigate this I implemented a "store wrapper" which keeps the pending mutations in a queue. Then if an older mutation responds later, it is placed in the correct place in the queue and all mutations are reapplied in the correct order.
By "correct" order, I mean the order in which the original queryAndUpdate calls happened.
Whether this is actually the correct order, we can't know unless we get the block height in the response, which we currently don't.
To match responses from the same …
=> queuedStore to mitigate queryAndUpdate race condition

scripts/dfx-snapshot-start
We have `scripts/dev-local-state.sh` which starts a replica (`dfx start`) *and* the frontend (`npm run dev`) with a given snapshot. I originally thought this would be convenient but it hasn't been for 2 reasons:
1. `npm ci` often causes the vite server to kill itself. This then makes the script also kill the replica, which is unnecessary.
2. Some scripts (e.g. in snsdemo) run a replica and start by killing any existing running replicas. Because `dev-local-state.sh` runs the replica in the background, it doesn't notice that it's killed and then it doesn't get an opportunity to restore the state.
Add `scripts/dfx-snapshot-start` which is just like [dev-local-state.sh](https://github.com/dfinity/nns-dapp/blob/main/scripts/dev-local-state.sh) but it runs `dfx start` in the foreground instead …
=> Script to start dfx with snapshot

frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte, frontend/src/lib/services/ckbtc-accounts-loader.services.ts, frontend/src/lib/services/ckbtc-convert.services.ts, frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
When ckBTC are converted to BTC from the withdrawal account, it does not make much sense to reload the related transactions as these are nowhere used in NNS-dapp.
- on `retrieveBTC` from withdrawal account, skip reload of the transactions.
=> No reload of the transactions for withdrawal account

frontend/src/lib/stores/accounts.store.ts, frontend/src/tests/lib/components/accounts/SelectAccount.spec.ts, frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts, frontend/src/tests/lib/components/neuron-detail/actions/DisburseButton.spec.ts, frontend/src/tests/lib/components/neuron-detail/actions/NnsIncreaseStakeButton.spec.ts, frontend/src/tests/lib/components/neurons/NnsNeuronsFooter.spec.ts, frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts, frontend/src/tests/lib/derived/accounts-list.derived.spec.ts, frontend/src/tests/lib/derived/universes-accounts.derived.spec.ts, frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts, frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts, frontend/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts, frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts, frontend/src/tests/lib/modals/neurons/SpawnNeuronModal.spec.ts, frontend/src/tests/lib/modals/neurons/StakeNeuronModal.spec.ts, frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts, frontend/src/tests/lib/pages/NnsAccounts.spec.ts, frontend/src/tests/lib/pages/NnsWallet.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/routes/Wallet.spec.ts, frontend/src/tests/lib/services/accounts.services.spec.ts, frontend/src/tests/lib/services/busy.services.spec.ts, frontend/src/tests/lib/services/neurons.services.spec.ts, frontend/src/tests/lib/services/sns-sale.services.spec.ts, frontend/src/tests/workflows/CreateSubaccount.spec.ts
https://github.com/dfinity/nns-dapp/pull/2445 introduced a new interface for the `accountsStore`.
It kept the old interface temporarily for backwards compatibility so we didn't have to update all the existing tests in the same PR.
This PR removes the old interface.
1. Remove `set`, `setBalance` and `reset` from `accountsStre`.
2. Add `setForTesting` to be used by tests only.
3. Update tests to use `setForTesting` and `resetForTesting`.
4. (Re)move a few occasional cleanups from tests/afterEach to beforeEach.
`npm run test`
=> Cleanup: Remove old methods from accountsStore

frontend/src/lib/derived/debug.derived.ts, frontend/src/lib/pages/SnsProposalDetail.svelte
Add selected sns proposal to the debug store. Otherwise there is currently no another way to see the sns proposal details.
- new debug store `snsProposalStore`
=> feat: bind snsProposalStore

frontend/package-lock.json, frontend/src/lib/components/accounts/BitcoinEstimatedFee.svelte, frontend/src/lib/components/accounts/BitcoinFeeDisplay.svelte, frontend/src/lib/components/accounts/BitcoinKYTFee.svelte, frontend/src/lib/components/ic/AmountDisplay.svelte, frontend/src/lib/components/transaction/TransactionFormFee.svelte, frontend/src/lib/components/transaction/TransactionReceivedTokenAmount.svelte, frontend/src/lib/components/transaction/TransactionSource.svelte, frontend/src/lib/components/transaction/TransactionSummary.svelte, frontend/src/lib/constants/icp.constants.ts, frontend/src/lib/utils/token.utils.ts, frontend/src/tests/lib/components/accounts/BitcoinEstimatedAmountReceived.spec.ts, frontend/src/tests/lib/components/transaction/TransactionReceivedAmount.spec.ts, frontend/src/tests/lib/components/transaction/TransactionReceivedTokenAmount.spec.ts, frontend/src/tests/lib/components/transaction/TransactionSource.spec.ts, frontend/src/tests/lib/components/transaction/TransactionSummary.spec.ts, frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts, frontend/src/tests/lib/utils/token.utils.spec.ts
We must display height decimals on transaction review.
- add `height_decimals` display
=> Height decimals on transaction review

frontend/scripts/build.csp.mjs, frontend/src/lib/api/location.api.ts, frontend/src/tests/lib/api/location.api.spec.ts
We want to restrict participation of users from certain countries to participate in SNS swap.
This PR: Integrate with two location services that return the user location.
* Implement two services in location api function.
* Add CSP rules for both new services.
* Add test for location api function.
=> GIX-1546: Integrate Geo Location Services

frontend/src/lib/components/project-detail/ProjectStatusSection.svelte, frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts, frontend/src/tests/page-objects/ProjectStatusSection.page-object.ts
Don't show commitment info if the user has no commitment.
* Do not render the commitment line in ProjectStatusSection if the commitment is 0 or not present.
* Add tests for commitment rendering in ProjectStatusSection.
=> Fix: Commitment project detail

.github/workflows/docker-build.yaml
If a PR makes no changes to the docker build, the hash of the build artefacts is not available.  This is inconvenient when checking whether CI still produces the same outputs as local builds.
Always print the sha256 hashes of docker outputs.
See CI
=> Always print asset hashes

frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte, frontend/src/lib/utils/ckbtc.utils.ts, frontend/src/tests/lib/utils/ckbtc.utils.spec.ts
It is now requested to not consider the btc and kyt fees for the comparison of the minimal amount to convert ckBTC to BTC.
=> feat: btc and kyt fees should not be considered for minimal input amount

frontend/src/lib/constants/bitcoin.constants.ts, frontend/src/lib/utils/bitcoin.utils.ts, frontend/src/tests/lib/utils/bitcoin.utils.spec.ts
Estimated BTC and inter-network fees should be displayed with height decimals.
No test environment no problem, could not have detected it locally because I work with a value that has 8 decimals...
After PR with mocked value that is not my working value:
=> Estimated BTC and inter-network fees height decimals

frontend/src/lib/i18n/en.json
> One minor niggle "Estimated Fees" could just be "Estimated" as the '*' applies to the received amount too.
=> Simplify estimated text

frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
On ckBTC wallet page there is newly a "Refresh balance" button that used to be in the modal.
When executed it reloads the account but, did not reload anymore the transactions because well, it was moved without it.
This PR load the next transactions after such actions.
I just load the next transactions and do not reload everything because a successful "refresh balance" produces a new transaction.
- instead of `onMount` call load on any account changes
=> Load next transactions after refresh balance

frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte, frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
When converting ckBTC to BTC from the withdrawal account there is no transfer to the ledger, therefore no related fee and therefore when user click "Max", such fee should not be deducted from the account balance.
=> ckBTC max input should not reduce ledger fee

README.md
The aggregator is not mentioned in the README.  In particular, I became aware while writing an sns deploy script that the flavours of the aggregator build are not documented anywhere.
* Add the sns aggregator to the README.
I actually expect that we would prefer to have the aggregator documentation in a  separate README but let's discuss first.
=> Add aggregator to the docs

frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/stores/icrc-transactions.store.ts, frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCTransactionsListTest.svelte, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/lib/routes/Wallet.spec.ts, frontend/src/tests/lib/stores/icrc-transactions.store.spec.ts
I transferred new bitcoin on mainnet and despite the fact that load next transactions was effectivelly called after update balance, the new transactions were not displayed. I'm not sure if it's a timing issue or not that's why I though about reload all transactions after such process.
- if account change, reload all transactions of the account
Load next transactions happen but no new transaction displayed
Here locally update balance simulated to display the all reload
=> Reload all ckBTC transactions after update balance

frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts
We want to restrict participation of users from certain countries to participate in SNS swap.
In this PR: Load the location of the user when needed.
Note: Not fully functional yet because the backend is missing the necessary field.
* New project util `userCountryIsNeeded`.
* Use new project util in ProjectDetail to call the service `loadUserCountry`.
* Add tests for new project util
* Add test in ProjectDetail for new functionality.
=> GIX-1541: Get user location if needed

frontend/src/lib/services/sns-neurons.services.ts
To make sure we have a good UX when there are a lot of visitors we want to avoid update calls. There is a flag (`FORCE_CALL_STRATEGY`) that changes all query calls to "query".
In this PR: Use the flag also in SNS neurons.
* Use `FORCE_CALL_STRATEGY` flag in sns neurons services.
We don't have specific tests for this flag.
=> Chore: Prepare for force query calls

frontend/src/lib/pages/SnsProposals.svelte
Fixes the bug when there is no sns proposals shown on the project switch.
- add projectId listener for reload function
=> fix: reload proposals on sns switch

frontend/src/lib/components/sale/AdditionalInfoForm.svelte, frontend/src/tests/lib/components/sale/AdditionalInfoForm.spec.ts, frontend/src/tests/lib/components/sale/AdditionalInfoFormTest.svelte, frontend/src/tests/page-objects/AdditionalInfoForm.page-object.ts
We want to allow SNS params to include conditions that have to be agreed to by swap participants.
This PR only updates the component that will display the conditions and the checkbox.
It is not hooked up to anything yet.
1. In `frontend/src/lib/components/sale/AdditionalInfoForm.svelte` render conditions and a checkbox if conditions are passed as optional props.
2. Add a page object for `AdditionalInfoForm`.
3. Add a `AdditionalInfoFormTest` component to assist in testing by passing a svelte store to read out the value of the checkbox.
4. Add tests.
1. Added a unit test.
2. Confirmed manually that nothing is displayed yet because the props aren't passed to the component.
=> GIX-1555 Support conditions in AdditionalInfoForm

Dockerfile, dfx.json
We would like to include the git commit and API did in the nns-dapp and sns_aggregator wasm metadata sections.  The ic-wasm tool is currently the preferred method for adding custom sections.
Unfortunately its pre-built binaries do not work on the standard production linux (Ubuntu 20.04), due to the same issue that plagued a number of other ic projects in recent months.  So we have to fall back to cargo install, which works reliably but is slow.  CI will similarly be slow until ic-wasm is in the main branch docker cache.  So let's get it there soon.
- Add ic-wasm to the toolchain
- Use ic-wasm to add the desired custom sections.
I have used ic-wasm locally to add custom sections
=> feat: Add ic-wasm to the toolchain

frontend/src/lib/services/sns-neurons.services.ts, frontend/src/lib/services/user-country.services.ts, frontend/src/lib/stores/user-country.store.ts, frontend/src/lib/types/location.ts, frontend/src/tests/lib/services/user-country.services.spec.ts, frontend/src/tests/lib/stores/user-country.store.spec.ts
We need to handle three states in the country store: loading, error and success.
In this PR: We change the type of the data in the store to better manage the different states.
* Change the type inside `userCountryStore`.
* Add two derived stores with the logic for the error and the loading state.
* New type `Country`.
* Fix tests accordingly.
* Add tests for two new derived stores.
=> Feat: Change user country store type

frontend/src/lib/components/neurons/SetDissolveDelay.svelte, frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts, frontend/src/tests/lib/components/neurons/SetNnsDissolveDelay.spec.ts, frontend/src/tests/lib/modals/neurons/IncreaseDissolveDelayModal.spec.ts, frontend/src/tests/lib/modals/neurons/StakeNeuronModal.spec.ts, frontend/src/tests/lib/modals/sns/IncreaseSnsDissolveDelayModal.spec.ts, frontend/src/tests/page-objects/Button.page-object.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
Neurons with dissolve delay of almost 8 years (8 years - some seconds) could not update the dissolve delay to 8 years.
The issue was raised in the forum: https://forum.dfinity.org/t/peculiar-issue-7-years-and-365-days-neuron/19910?u=diegop
The fix is to move the range input, max and min buttons to use seconds instead of days.
Main changes:
* SetDissolveDelay component uses seconds instead of days.
* Add a test for the specific bug in SetDissolveDelay.spec.ts
* Change tests that were using the range in days to use the range in seconds.
* New SetDissolveDelay page object.
=> Fix: Update dissolve delay for almost 8 years neurons

scripts/did2rs.sh
`sed` works slightly differently on Mac vs. Linux.
`sed` on Mac doesn't support `\<` and `\>` as word boundary.
`[[:<:]]` and `[[:>:]]` work on Mac but not on Linux.
1. In the `sed` command in `scripts/did2rs.sh`, instead of using word boundaries, expect specific characters.
2. Remove the `g` modifiers because they mean "multiple times per line" but each of these substitutions happens once per line.
3. Use @ instead of / in one of the substitutions to limit escaping.
Ran `scripts/mk_nns_patch.sh` and checked that no patch files were changed.
Without the fix, that script results in much longer patch files on Mac.
=> Fix sed command in scripts/did2rs.sh

.github/workflows/checks.yml, rs/sns_aggregator/src/types/ic_sns_governance.patch, scripts/did2rs.sh, scripts/mk_nns_patch.sh, scripts/mk_nns_patch.test
We generate files with rust types from import `.did` files and apply some changes to them.
The changes are in patch files.
If people make manual changes, the patch files are might not be usable anymore.
1. Change `scripts/mk_nns_patch.sh` to allow running without arguments to apply to all canisters.
2. Make sure the `git diff` command always uses the same abbreviation length for hashes to get consistent output.
3. Add `scripts/mk_nns_patch.test` that verifies that the patch files are what they would be when the update script is run.
4. Run the test from CI.
5. Remove a few `set -x` to make scripts less verbose.
This is what a failed run looks like:
https://github.com/dfinity/nns-dapp/actions/runs/4960612014/jobs/8876323282
The output ends with:
```
FAILED: Patch files should be updated to …
```
=> Verify aggregator patch files in CI

frontend/src/lib/components/neuron-detail/NnsNeuronMaturityCard.svelte, frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronMaturityCard.spec.ts, frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts, scripts/did2rs.sh
Fix the issue that in case of rollover rounds the last reward distribution date was displayed wrong. 
[Discussions](https://dfinity.slack.com/archives/C01S03NBM7S/p1683906720696299)
- util function `maturityLastDistribution`
- maturityLastDistribution
=> feat: maturityLastDistribution util

frontend/src/lib/components/project-detail/ParticipateButton.svelte, frontend/src/lib/i18n/en.json, frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
User can not participate while the dapp fetches location.
* In ParticipateButton, check user country store to decide whether location is needed and is loading. Keep disabled button if so.
* Change text of loading indicator.
* Add a test for the specific case.
=> GIX-1554: Show loading while fetching location

frontend/scripts/build.csp.mjs
We get the number of participants from the metrics endpoint of SNS governance.
To do so, we need the endpoint in our CSP rules.
* Add new endpoint to CSP rules.
Only build changes
=> Chore: Add Sonics SNS Gov canister to CSP

frontend/src/lib/components/neuron-detail/NnsNeuronMetaInfoCard.svelte, frontend/src/lib/constants/neurons.constants.ts, frontend/src/lib/modals/neurons/SplitNnsNeuronModal.svelte, frontend/src/lib/services/neurons.services.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronMetaInfoCard.spec.ts, frontend/src/tests/lib/services/neurons.services.spec.ts
In the ICP Ledger App version 2.3.0 it's enabled to split neurons.
Therefore, we should enable the UI in NNS Dapp as well.
* "Split Neuron" button is always present. Also HW controlled neurons.
* Neuron service splitNeuron checks the controller of the neuron and the ledger app version before splitting
* New Ledger app version constant: 2.3.0
* Test that "Split Neuron" button is present for HW controlled neurons.
* Test that neuron service split neurons checks ledger app version before continuing.
=> Chore: Enable split HW controlled neuron

declarations/sns_governance/sns_governance.did, declarations/sns_ledger/sns_ledger.did, declarations/sns_root/sns_root.did, declarations/sns_swap/sns_swap.did, declarations/sns_wasm/sns_wasm.did, dfx.json, rs/sns_aggregator/src/types/ic_sns_governance.patch, rs/sns_aggregator/src/types/ic_sns_governance.rs, rs/sns_aggregator/src/types/ic_sns_ledger.patch, rs/sns_aggregator/src/types/ic_sns_ledger.rs, rs/sns_aggregator/src/types/ic_sns_root.patch, rs/sns_aggregator/src/types/ic_sns_root.rs, rs/sns_aggregator/src/types/ic_sns_swap.patch, rs/sns_aggregator/src/types/ic_sns_swap.rs, rs/sns_aggregator/src/types/ic_sns_wasm.patch, rs/sns_aggregator/src/types/ic_sns_wasm.rs
We need to access the `confirmation_text` [field in the SNS init params](https://github.com/dfinity/ic/blob/master/rs/sns/swap/canister/swap.did#:~:text=confirmation_text%20:%20opt%20text;) to show it in the UI.
We will access it through the sns_aggregator so it needs to be aware of the field.
The field was added in commit [3d4752b...](https://github.com/dfinity/ic/commit/3d4752b2a717334006a5e35330a132b08f890ffc).
The first *published* commit after it, according to snsdemo/bin/dfx-software-ic-latest is 10779a35b683eb991777bfdffda94145d33759db.
1. Updated commit, did files and rust types with `scripts/update_ic_commit --ic_commit 10779a35b683eb991777bfdffda94145d33759db`.
2. Updated patch files with `scripts/mk_nns_patch.sh`.
I did not make any manual changes.
Since I did not make manual …
=> Update IC commit

frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts
Update last maturity distribution calculation logic to be based no `settled_proposals` absence.
- `maturityLastDistribution` logic
- updated related tests
=> feat: updates logic for last maturity distribution time calculation

frontend/src/lib/components/neurons/SetDissolveDelay.svelte
Clicking on "Min" when dissolve delay was adding 1 day even thought the disssolve delay was the maximum.
The button was anyway disabled, but the user could see "8 years and 1 day"
* Check the bound of dissolve delay when using the "Min" and "Max" buttons.
UI fix only.
=> Fix: Min should not increase more than max

frontend/scripts/build.csp.mjs, frontend/src/lib/api/sns-swap-metrics.api.ts
Link to get metrics is in the domain icp0.io not icp0.app now.
* Change metrics api endpoint.
* Change CSP to use new endpoint.
* Change the canister id in the Sonic CSP. It was using the governance canister, and it should be the swap canister.
No new functionality
=> Fix: Point to icp0.io not icp0.app

frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts
The status of the Participate Button is becoming complex.
To manage the complexity, in this PR, we add a helper function to encapsulate all the logic for the button status.
* New project util `participateButtonStatus` and new type `ParticipationButtonStatus`.
* Change return type in `getDeniedCountries`
* Test new util.
=> Feat: Add Participate Button Status helper

frontend/src/lib/api/sns-swap-metrics.api.ts
Fix the metrics api endpoint to get the number of participants.
* Add a missing "p" in "ic0". It shuold be "icp0". Like in CSP rules.
Only endpoit change.
=> Fix: metrics api fix

frontend/src/lib/constants/mockable.constants.ts, frontend/src/lib/services/known-neurons.services.ts, frontend/src/lib/services/nns-reward-event.services.ts
We want a good UX for the upcoming swap. Therefore, we enable using only query to request data.
* Add the flag in two calls: known neurons and latest reward event.
* Set `FORCE_CALL_STRATEGY` to `"query"`.
=> Chore: Enable query updates

frontend/src/lib/pages/ProjectDetail.svelte
Users in the phone that access the Project Detail through the Launchpad sometimes had the participation button always loading.
The problem is that the BottomSheet component triggers two mount and unmounts.
Issue to investigate this further: https://dfinity.atlassian.net/browse/GIX-1574
* Do not cancel polling getting the open ticket when ProjectDetail is destroyed.
There are no tests that checked that the polling was cancelled.
=> Fix: Forever loading participation button

frontend/src/lib/services/ckbtc-accounts-loader.services.ts
During the SNS swap we rely on just query calls to be prepared for heavy load.
The getCkBTCWithdrawalAccount code assumed that there will always be an update response, even though we apply the value of FORCE_CALL_STRATEGY when making the call here:
https://github.com/dfinity/nns-dapp/blob/main/frontend/src/lib/services/ckbtc-withdrawal-accounts.services.ts#:~:text=strategy:%20FORCE_CALL_STRATEGY
Check the value of FORCE_CALL_STRATEGY before assuming there will be an update call, in `getCkBTCWithdrawalAccount`.
Manually verified that there isn't an infinite spinner for "Checking for incomplete BTC transfers".
Will add unit test separately.
=> Take FORCE_CALL_STRATEGY into account getCkBTCWithdrawalAccount

frontend/src/lib/components/accounts/CkBTCWalletActions.svelte, frontend/src/lib/services/ckbtc-minter.services.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletActions.spec.ts
The `index` canister needs 30sec or so and soon less to populate new transaction but still, takes a bit of time. That's why after a "ckBTC refresh balance" currently only the balance is updated and not the list of transactions.
In the future we will fetch the list of transactions and balance from the index but, it isn't there yet. Likewise we plan to implement some crontab refresh but it's tasky.
That's why this PR just adds a bit of delay.
- delay call of `reload` function in `updateBalance` of few seconds
=> Delay ckBTC account and transactions reload

frontend/src/lib/services/ckbtc-accounts-loader.services.ts, frontend/src/lib/services/ckbtc-minter.services.ts, frontend/src/lib/services/ckbtc-withdrawal-accounts.services.ts, frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
We reload in any case because the user might hit "Refresh balance" in the UI thinking the feature is meant to reload the account and transactions even though it is actually meant to confirm the conversion of BTC -> ckBTC
In addition this PR integrates #2535 to reuse pseudo query and update call to load the withdrawal account.
- always reload regardless if `updateBalance` ends in error or success
=> Always reload account and transactions on "Refresh balance"

frontend/src/lib/components/project-detail/ParticipateButton.svelte, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts, frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts
The status of the Participate Button is becoming complex.
In this PR, we use the helper to get the participation button status in the ParticipateButton component.
Not in this PR, manage the new scenarios with restricted countries.
* ParticipateButton, use the button status from the helper instead of other variables to render and not render.
* Change the type of the `userCountry` in util `participateButtonStatus`.
* Add new test case for "loading" in ParticipateButton spec file.
* Fix tests for participateButtonStatus after refactor.
* One test in ParticipateButton was broken and was passing for the wrong reasons. I fixed it and added an extra expect to ensure the scenario is the expected one.
* Fix one text in ProjectStatusSection. No commitment means loading state, not present. Earlier, …
=> Chore: Refactor Participate Button with status helper

frontend/src/routes/(app)/(u)/(detail)/proposal/+layout.svelte
Resolve the problem related to the incorrect back navigation from the launchpad proposal details page, which currently directs users to the proposals page instead of the launchpad page.
- add `referrerPath` based back navigation
A way to include unit tests for this specific scenario was not found.
| ![Screen Recording 2023-05-19 at 11 25 41](https://github.com/dfinity/nns-dapp/assets/98811342/7382e63a-ca91-4a42-bc66-48a28ba37a87) | ![Screen Recording 2023-05-19 at 11 24 16](https://github.com/dfinity/nns-dapp/assets/98811342/315cfa29-5b5e-4767-b42c-ffc42b3e36d9) |
=> fix: back navigation from the launchpad proposal details page

frontend/jest-setup.ts, frontend/src/lib/constants/mockable.constants.ts, frontend/src/lib/services/ckbtc-withdrawal-accounts.services.ts, frontend/src/tests/lib/services/ckbtc-accounts-loader.services.spec.ts, frontend/src/tests/lib/services/ckbtc-withdrawal-accounts.services.spec.ts, frontend/src/tests/utils/mockable-constants.test-utils.ts
https://github.com/dfinity/nns-dapp/pull/2536 fixed a loading ckBTC withdrawal accounts by no longer taking `FORCE_CALL_STRATEGY` into account when loading those accounts.
But it did not add a unit test for that fix.
This PR adds the unit test.
1. Add a util to make mockable constants mockable per individual test.
2. Add a test which sets `FORCE_CALL_STRATEGY` to `"query"` and verifies that withdrawal accounts are still loaded. (It duplicates the test above it with the only difference being `FORCE_CALL_STRATEGY = "query"`.)
3. Remove a check on `FORCE_CALL_STRATEGY` in the error handler since it's now irrelevant.
Unit test is added.
I also verified that the test fails without the `FORCE_CALL_STRATEGY` change from https://github.com/dfinity/nns-dapp/pull/2536.
=> Unit test for ckBTC FORCE_CALL_STRATEGY fix

frontend/static/assets/libs/dummy-proposals.utils.js
Make proposals in parallel to speed up testing. And continue testing on the testnet without interruption, even if the first dummy proposal contains errors.
- apply `Promise.allSettled` to proposals creation
Only manual tests were done.
**Successful creation**
**Erroneous creation**
=> refactor: make dummy proposals in parallel

rs/backend/src/proposals.rs
CMC proposal had a proposal to upgrade using as argument `()`. This is not a valid argument for the nns-dapp serializer because the arguments must always be `opt <something>`. Yet, to install canisters, this is a valid argument.
We need to support this argument and not fail to show the payload.
* Return an emtpy array json instead of an error if `Decode` fails.
There are no tests for this. But it would be good to add a few. In another PR.
=> Fix: Issue with arguments in CMC proposal

frontend/src/lib/api/dev.api.ts, frontend/src/lib/components/ic/GetTokens.svelte, frontend/src/lib/services/dev.services.ts
FOR TESTNET OR LOCAL ENVIRONMENT ONLY
Users tried to get tokens when the test account balance was 0.
Instead, revert to get ICPs if the balance for those tokens is 0.
* New dev api "getTestAccountBalance" to get the balance of the test account.
* New dev services "getTestBalance" that uses "getTestAccountBalance" dev api.
* Use the new service in the GetTokens component to change the name of the button and get from different accounts dependeing on the balance.
ONLY TESTNET AND LOCAL FEATURE
=> Fix: Do not try to get tokens if balance 0

.github/workflows/checks.yml, scripts/setup
The didc version was not always taken from dfx.json.  While the versions were all correct, updating the version in dfx.json would have caused them to go out of sync.
- Always get the didc version from dfx.json
- See CI for the changes to github actions.
- I have run the local development setup script locally
=> clean: Didc version in setup

frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/mocks/sns-response.mock.ts
Remove mocking the getter `getDeniedCountries` in tests.
Instead, create a swap summary with the desired state.
* New mockInit.
* New helper createSummary to create a swap summary data based on lifecycle and restricted countries.
* Remove the `jest.spyOn(summaryGetters, "getDeniedCountries")` and instead build a swap summary.
All are test changes.
=> GIX-1543: Remove getDeniedCountries mock

frontend/src/lib/components/ic/GetTokens.svelte
`npm run build` is broken.
The problem: Code that depends on `window` was executed at build time.
Ideally: That component should not be executed at build time.
Workaround: Check whether the environment is the browser before calling the problematic code.
* Check whether we're in the browser in `GetTokens` before getting the balance of the test account.
This component is not tested because it's used only in testnets or loca environments.
=> Fix: npm run build

frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte, frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/ParticipateSwapModal.page-object.ts
We want to allow SNS creators to specify conditions that have to be accepted by swap participants.
For this purpose there is a field `confirmation_text` in the swap summary.
This PR only displays the confirmation text and checkbox.
It does not yet require that the checkbox is checked or send the confirmation text in the refresh buyer tokens request.
1. In `frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte` pass the `confirmation_text` from the summary to the `AdditionalInfoForm` component.
2. Add a convenience getter in `frontend/src/lib/getters/sns-summary.ts`
3. Add 2 tests to verify that the text is rendered if and only if it's present in the summary.
4. Add `renderSwapModalPo` in the test, convenient for the case where the test only needs the po, and use it in existing …
=> GIX-1555 Show conditions to accept if confirmation_text is present

frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts, frontend/src/tests/page-objects/ParticipateSwapModal.page-object.ts, frontend/src/tests/page-objects/TransactionReview.page-object.ts
The `AdditionalInfoReview` component is specific to the `ParticipateSwapModal` component and the `TransactionReview` component is more generic.
But the `AdditionalInfoReviewPo` getter is currently defined inside `TransactionReviewPo`
Move `getAdditionalInfoReviewPo` from `frontend/src/tests/page-objects/TransactionReview.page-object.ts` to `frontend/src/tests/page-objects/ParticipateSwapModal.page-object.ts`.
Existing tests still pass.
=> Move AdditionalInfoReviewPo to ParticipateSwapModalPo

frontend/src/tests/e2e/sns-participation.spec.ts, frontend/src/tests/e2e/tsconfig.json
`tsconfig.spec.json` exclude `e2e` tests which lead to editor not understand `paths`.
- extend tsconfig for e2e and reset exclusion of `e2e` path
- add requested `type` (detected once `tsconfig` properly applied)
=> Fix e2e tsconfig exclude

frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
`ParticipateSwapModal.spec.ts` has some redundant test and some tests that don't appear to make sense anymore.
I was very confused trying to figure this out so please review carefully.
1. Remove redundant test. See review comments.
2. Change "when user has participated" to "when user has existing swap commitment" for clarity.
3. Move cleanup to the top level `beforeEach`.
4. Resolve the `queryAccounts` results explicitly to make the test that the accounts dropdown is absent until accounts are loaded less brittle.
5. In the test "loads accounts with query only", actually verify that the corresponding update calls aren't made.
Verified that if update calls are made, the "query only" test does indeed fail.
=> Clean up ParticipateSwapModal.spec.ts

Cargo.lock, rs/backend/Cargo.toml, rs/backend/src/proposals.rs, rs/backend/src/proposals/tests/args.rs, rs/backend/src/proposals/tests/mod.rs
Argument rendering is currently imperfect.  It has no tests, though, making it hard to evaluate improvements.
- Add tests for argument rendering.
- The test vector includes both the current behaviour and the value that we would probably like.  A PR that makes the actual and desired values align more closely is potentially a good thing.
- Split the argument rendering function into two parts, for more comprehensive testing.
- This PR provides almost nothing but tests.
=> Argument rendering test vectors

frontend/src/lib/api/sns-aggregator.api.ts, frontend/src/lib/constants/sns.constants.ts, frontend/src/tests/lib/api/sns-aggregator.api.spec.ts
We only fetch one page of the SNS aggregator.
When there are more than 10 SNSes, the latest never appear.
* Get the next page if the SNS Aggregator returns 10 SNSes.
* Test the new functionality of the sns aggregator api.
=> Feat: Support SNS pagination

frontend/src/tests/e2e/sns-participation.spec.ts
Finishing the swap participation end-to-end test.
In `frontend/src/tests/e2e/sns-participation.spec.ts` test that the user can increase swap participation after participating for the first time.
=> GIX-1437 E2E: Increase participation

frontend/src/lib/components/project-detail/ParticipateButton.svelte
Change participation button tooltip to make the whole tooltip content visible.
- change tooltip position
=> style: make participation button tooltip on top

frontend/scripts/test-reproducibility
In `test-reproducibility` script, print filename first and sort entries. Makes easier to compare diffs.
Also save results for manual comparison.
=> Split and sort filename and hash in test script

frontend/src/tests/e2e/sns-governance.spec.ts, frontend/src/tests/page-objects/AddSnsHotkeyModal.page-object.ts, frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/SnsNeuronHotkeysCard.page-object.ts
Continuing with SNS end-to-end coverage.
1. Add a hotkey to an SNS neuron in `frontend/src/tests/e2e/sns-governance.spec.ts`.
2. Add missing page object functionality.
=> E2E: Add SNS neuron hotkey

frontend/src/lib/components/ic/GetTokens.svelte, frontend/src/lib/constants/environment.constants.ts, frontend/src/lib/utils/env-vars.utils.ts, frontend/src/lib/utils/env.utils.ts
@dskloetd figured out that our frontend reproducibility issue started with PR #2377. After having a look at the PR we noticed it introduced an explicit import of a CJS module of agent-js within the code that is bundled with ESM. As I suspected that our issue was linked to pollyfying the Node modules for the browser, we replaced the import by inline code and as a result, the reproducibility was improved.
Using the `./script/test-reproducibility` script, on my machine, I am now able to run 100 successful check in a row.
- remove explicit CJS `import`
- use SvelteKit `browser` information when possible
- when not (see PR for explanation) use a custom `isBrowser` information
=> Fix reproducibility by not explicitly importing cjs modules from agent-js in esm

frontend/src/tests/e2e/accounts.spec.ts
I want to delete the old (non-Playwright) e2e tests, but before I do I want to make sure that everything they test is covered by the new Playwright e2e tests.
For the accounts related tests, the only thing the old e2e tests test that the new tests don't yet test, is that the linked account is still present after reloading the page.
In `frontend/src/tests/e2e/accounts.spec.ts`, reload the page and check that the linked account is still there.
=> E2E: Check linked account after page reload

frontend/src/tests/e2e/accounts.spec.ts, frontend/src/tests/e2e/sns-governance.spec.ts, frontend/src/tests/e2e/sns-participation.spec.ts, frontend/src/tests/utils/e2e.test-utils.ts
If a test uses `test.step` you can see the name of the step in the terminal when running a headless e2e test.
The intended way to do this is to put all the code for a step inside a closure passed to `test.step()` but this makes the code hard to read and prevents sharing constants created in one step to another step.
1. Add a utility function that lets you call `test.step` without passing a closure. It simulates that all the code until the next call to `step()` runs inside the passed closure.
2. Use `step()` inside existing e2e tests to make it easy to follow progress.
Tested by running `npm run test-e2e` and observing the result in the terminal.
=> E2E: Use test step to follow progress when headless

.github/workflows/aggregator.yaml, .github/workflows/build.yml, .github/workflows/docker-build.yaml, .github/workflows/docker-main.yaml, .github/workflows/nightly.yaml, Dockerfile, dfx.json, scripts/dfx-wasm-metadata-add, scripts/dfx-wasm-metadata-add.test, scripts/docker-build
Requests from the nns & testing teams to publish the commit of our canisters.  In fact, it is becoming common to publish both the commit and the API did file so we cover both on both canisters.  Four with one stroke.
* Created a new command to add metadata.  This is NOT in the canister build command so that the canister build can be cached, and commits that do not affect a canister wasm don't cause a rebuild just because the commit has changed.
* Created a test for the command
* Called the command in the dockerfile
* Created a test for deployments from the docker build
* Tests are included.  See CI for the results.
=> Commit in metadata

.github/workflows/docker-build.yaml
The `sns_aggregator` built in the docker-build workflow is not available for download.  Having it would be convenient when making releases.
- Add a separate upload for sns artefacts, including the dev and prod sns_aggregator wasms.
- Rename the nns-dapp upload to make naming consistent across the two uploads and minimize confusion.
See CI, there are assets:
I have checked manually that the zip file contents are as expected.
=> Upload aggregator assets

frontend/src/routes/(login)/+layout.svelte
The navigation between login screen to main page can take some times on testnet and mainnet when the JS chunks and other resources have to be downloaded.
Because we have to hide the content of the login mask on navigation, the UI results as being rendered empty while it is loading.
As a bare minimial improvement, we can display a spinner while it's loading.
Currently - fast network
Currently - slow network
PR - fast network
PR - slow network
=> Display spinner on navigation after sign-in

.github/workflows/build.yml
Installing `ic-wasm` is slow.
Considerations:
- Upstream does build `ic-wasm` binaries, however they work only in very specific environments and break for us.
- Building upstream with musl fails due to some C++ wrapped by `ic-wasm`.
- `zigbuild` does work, locally, but the last time I tried to get `zigbuild` into a github action it failed.  That could be made to work but there is no guarantee how quickly it would be done.
- Cache the `ic-wasm` installed in github.
Bumping this PR should hit the cache.  And it does: https://github.com/dfinity/nns-dapp/actions/runs/5123623571/jobs/9214397492?pr=2604
=> Cache the ic-wasm installation

frontend/src/tests/e2e/accounts.spec.ts
We used to have a race condition in the accounts store when an update result for an old queryAndUpdate overwrites a query result for a newer queryAndUpdate.
This should be fixed by https://github.com/dfinity/nns-dapp/pull/2445
Remove the work-around in frontend/src/tests/e2e/accounts.spec.ts that is no longer necessary.
Deployed nns-dapp locally and ran:
`CI=true npm run test-e2e -- account --repeat-each 20 --workers 20`
All 20 passed.
=> E2E: Remove race condition work-around

frontend/src/lib/api/ckbtc-ledger.api.ts, frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/lib/api/sns-ledger.api.ts, frontend/src/tests/lib/api/ckbtc-ledger.api.spec.ts, frontend/src/tests/lib/api/icrc-ledger.api.spec.ts, frontend/src/tests/lib/api/sns-ledger.api.spec.ts
Because we have replaced the balance of the `Account` in Token by the inherited value in E8s (PR #2594), we can remove the calls that were added to fetch the metadata.
In other word we can spare not required query+update calls to ICRC-1 ledgers.
=> Remove deprecated ICRC ledger calls

frontend/playwright.config.ts
We disabled Firefox tests because the tests were flaky.
https://github.com/dfinity/nns-dapp/pull/2445 should have fixed most or all of the flakiness.
If the tests are flaky again, I'll investigate and disable if necessary.
1. Enable Firefox in `frontend/playwright.config.ts`
2. Increase the timeout on CI because the tests are close to the limit. Lower the timeout on non-CI because CI machines are really quite slow compared to our development machines.
3. Set the number of workers for non-CI to 6 so all (now 6) tests can run in parallel by default. Apparently `undefined` defaults to 5 workers.
=> Re-enable Firefox on Playwright tests

scripts/dfx-wasm-metadata-add
Unless you pass `-n`, `gzip` adds a timestamp, making the result not reproducible.
Add `-n` to `gzip` in `scripts/dfx-wasm-metadata-add`
Before:
```
$ cp nns-dapp.wasm-without-meta nns-dapp.wasm && scripts/dfx-wasm-metadata-add --canister_name nns-dapp --wasm nns-dapp.wasm && sha256sum nns-dapp.wasm
2e1de8f235b1e2be9282cbdfaf7de4cba139d72f7e29eff94875f305f0f6a3ae  nns-dapp.wasm
$ cp nns-dapp.wasm-without-meta nns-dapp.wasm && scripts/dfx-wasm-metadata-add --canister_name nns-dapp --wasm nns-dapp.wasm && sha256sum nns-dapp.wasm
57a40e9170dd27b539de22cbf96e3c79ea7afd0d7cb1dc3f430870deb47cac27  nns-dapp.wasm
```
After:
```
$ cp nns-dapp.wasm-without-meta nns-dapp.wasm && scripts/dfx-wasm-metadata-add --canister_name nns-dapp --wasm nns-dapp.wasm && sha256sum nns-dapp.wasm …
```
=> gzip without timestamp

.github/actions/start_dfx_snapshot/action.yaml, .github/workflows/build.yml
Run tests in parallel to make CI faster.
1. Split the `build` job into 3 jobs: `build`, `test-playwright-e2e` and `test-rest`
2. Create an action to download and install a snapshot and use it in bot test jobs.
3. Move uploading `nns-dapp.wasm` up to right after building.
4. Also upload both `sns_aggregator` wasms.
5. Download the wasms in both test jobs.
6. Add the new jobs to the `needs` of the last job.
See CI
=> Split e2e test workflow

scripts/nns-dapp/release-check
There are some minor problems in the proposal verification command.
- Fix typo
- Correct the `cd` that does nothing.
The command is already tested in CI.
=> Typo and bug

rs/backend/src/assets.rs
We would like to upload asset tarballs.  The code for adding a tarball of assets already exists, it just needs to be decoupled from `init()`.
- Separate the code for installing an assets tarball from the assets baked into the binary.
None; existing tests should suffice.
=> Separate out code for inserting a tarball

rs/backend/src/main.rs, rs/backend/src/metrics_encoder.rs, rs/backend/src/proposals.rs
Clippy, in pedantic mode, produces a lot of warnings.  It would be nice to reduce them.  Pedantic warnings can be useful but interesting lints are hidden by a mass of uninteresting warnings.
- Address about 10% of pedantic warnings.
None.  There is no change in functionality so existing CI should suffice.
=> Reduce warnings

.github/workflows/checks.yml, scripts/nns-dapp/split-assets, scripts/nns-dapp/split-assets.test
The assets are too large to upload as a single tarball.
- Add a command to split `assets.tar.xz` into smaller `.tar.xz` files.
- A test is included and is exercised in CI.
=> Script to split assets into several tarballs

frontend/src/tests/e2e/sns-governance.spec.ts, frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/SnsNeuronHotkeysCard.page-object.ts
Adding more end-to-end test coverage.
1. In `frontend/src/tests/e2e/sns-governance.spec.ts` check that the user can see the added hotkey.
2. Add page object functions.
=> E2E: SN005: User can see the list of hotkeys of a neuron

frontend/src/tests/lib/services/neurons.services.spec.ts
Be more confident about the test.
In `frontend/src/tests/lib/services/neurons.services.spec.ts`:
1. Set spy implementations in `beforeEach` such that if a test change a spy implementation, it's properly reset for the next test.
2. Remove resetting spy implementation at the end of `"should call setNeuron even if the neuron doesn't have fullNeuron"` as it's now properly reset in `beforeEach`.
3. When expecting a function to be called, expect an explicit number of times.
4. When expecting a function to be called, expect specific arguments.
5. When expecting a function to be called, expect it not to be called before it should have been.
6. Consistently use `toBeCalled` instead of a mix of `toBeCalled` and `toHaveBeenCalled`.
Test only
=> Clean up neurons.services.spec.ts

frontend/src/tests/utils/e2e.test-utils.ts
Fix in `e2e.test-utils`:
> TS2322: Type '(value: unknown) => void' is not assignable to type '() => void'.
=> Fix lint warning Type '(value: unknown) => void' is not assignable to type '() => void'.

scripts/setup
Fix the `ic-admin` setup. The darwin link was outdated (screenshot).
- change the download path.
*Broken link*
=> fix: update the ic-admin download link

.github/actions/release_nns_dapp/action.yaml, .github/workflows/build.yml
The wasm we have on mainnet should be identical to the one used on local networks.  Let's test that.
- Add a test that compares wasm builds for mainnet and local.
- There is a separate issue of whether all parts of the code are using the dynamic configuration passed in with arguments.  That is not covered in this PR.
- There is  a question of where the test should live. I am personally of the opinion that we should build the wasm once, then use that one wasm across many tests.  Why?  Why waste CPU cycles repeating work?  That means that we should not have separate e2e and testing workflows but rather one workflow with separate jobs inside it.
See above.
=> One wasm to rule them all

.github/workflows/docker-build.yaml, scripts/clap.bash, scripts/docker-build
Consistency.  I would like to add another flag but feel as if I am reinventing the wheel when modifying the docker-build arguments.  So why not use the standard argument parser in docker-build?
- Use standard argument parsing in `docker-build`
- Surface the `--verbose` flag in the `clap.bash` environment variables, so that it can be used to make the docker output verbose, as before.
See CI.  I have also used it locally.
=> Use standard arg parsing for docker-build

frontend/src/lib/api/canisters.api.cjs.ts, frontend/src/lib/api/tvl.api.cjs.ts, frontend/src/lib/utils/cjs.utils.ts
Refactor (move) Cjs dedicated import and common functions in a specific utils.
That way we spare the duplicate code and we make the functions also available for upcoming workers such as in #2639.
- move import (and rexport)  `"@dfinity/agent/lib/cjs/index"` to `cjs.utils`
- move a common `createCanisterCjs` to `cjs.utils`
- add the `if fetch_root_key then fetch_root_key` to that create function
=> Refactor Cjs import and common functions in a dedicated utils

frontend/src/lib/canisters/tvl/tvl.canister.ts
As for any canister objects we use in ic-js, the `TVLCanister` implemented in NNS-dapp can also extend the abstract class `Canister` of `@dfinity/utils`.
=> Inherit standard abstract Canister class

frontend/src/lib/api/sns.api.ts, frontend/src/lib/services/$public/sns.services.ts, frontend/src/lib/types/sns.query.ts, frontend/src/lib/types/sns.ts, frontend/src/lib/utils/sns.utils.ts, frontend/src/tests/lib/utils/sns.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/mocks/sns-response.mock.ts
Regardless if Sns, ckBTC or ICP we want to be able to fetch balance and transactions uses the ICRC-1 ledger.
In Snses we generally use the "wrapper" to access the canister but, in the particular crontab feature #2639 we want to avoid the use of such object and use `@dfinity/ledger` library directly regardless of the context.
That is why we need to access the ledger canister Id of a Sns project.
- export `ledgerCanisterId` in `SnsSummary` (as we already did for swap and governance)
=> Expose ledger canister id in sns summary

frontend/src/lib/services/worker-cycles.services.ts
Following PR #2641 which extracts interfaces types for worker services, I noticed that I can simplify few parameters typings in `worker-cycles.services.ts`.
=> Inherits params in worker cycles

frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts
Making it clear who is not eligible in an SNS swap.
Display "Persons Excluded: <country code>" in `ProjectSwapDetails.svelte`.
Tested manually with and without restricted_countries and with multiple.
Unit test will be added in next PR.
=> SNS: display excluded country codes

frontend/src/lib/derived/title-token-selector.derived.ts, frontend/src/tests/lib/derived/title-token-selector.derived.spec.ts, frontend/src/tests/lib/modals/universe/SelectUniverseModal.spec.ts
In universe selector, on the proposal tab, display "Select Network Nervous System" instead of "Select Token"
=> Display "Select NNS" instead of "Select Token" on proposals

.github/workflows/build.yml, .github/workflows/checks.yml
Some jobs in our workflow are quite slow.
- Use large runners for the two jobs on the critical path:  The wasm build and the svelte tests.
- See CI run times and compare with the normal run times.
=> Use big iron

frontend/src/lib/pages/SnsProposalDetail.svelte, frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
When navigating from a Sns proposal detail to a Nns universe, such as for example the launchpad, the reload feature is triggered again with the same Id but with the a universe Id extracted from the route that is Nns.
- add a check to load the Sns proposal only if not Nns
- added a `TODO` to use another source of information to load the universe
I found the issue with a breakpoint in the browser.
=> Fix Sns proposal reload with correct ID but NNS as universe

frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte, frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts, frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
Was missing from https://github.com/dfinity/nns-dapp/pull/2653
1. Test that excluded countries are rendered if present and not if not.
unit test
=> Unit test for 'Excluded Persons'

scripts/docker-build
The commit added to the metadata wasm currently includes a `-dirty` suffix if any of the committed files is changed.  Unfortunately this means that the wasm hash can change, surprisingly, due to otherwise inconsequential changes.
The `-dirty` suffix does provide some protection against users thinking that one commit has been deployed, e.g. to a testnet, when actually the commit plus some changes has been deployed.  Even with the suffix there is a risk of uncommitted files causing a change, so the protection is not absolute.  However we have no evidence that this has actually been a problem but we do have evidence that the `-dirty` suffix has caused problems when testing builds.
- Remove the `-dirty` suffix.
I have run `docker-build` locally and verified that it builds.
=> No dirty flag

frontend/src/tests/fakes/governance-api.fake.ts, frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
I'll be making changes to this test when implementing the simulate merging neurons UI so now seems like a good time to change it from mocking the service and store to using a fake.
In `frontend/src/tests/fakes/governance-api.fake.ts`:
1. Add `mergeNeurons`. It only adds the stakes together in the target neuron and sets the stake to 0 in the source neuron. This is very simplistic but should be good enough to verify in the test that neurons have been merged.
2. Add `getNeuron({identity, neuronId})` for use in the fake itself as well as in tests for convenience.
3. Allow setting the `stake` on neurons in the fake.
4. Add `addNeurons` to insert multiple fake neurons with a single call.
In `frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts`:
1. Create and use a test identity to …
=> Use fake governance API in MergeNeuronsModal.spec.ts

dfx.json
This is publicly accessible, so can be used for reviews of a release candidate:
https://ptid5-maaaa-aaaaa-aacnq-cai.nnsdapp.dfinity.network/
This is not:
https://ptid5-maaaa-aaaaa-aacnq-cai.nnsdapp.testnet.dfinity.network/
The release SOP actually states that the testnet needs to be removed and I was shown how to edit dfx to remove the testnet.
We actually never need the `testnet` in that URL.
* Remove `testnet` from the staging URL.
* Deployments to staging already have this change applied manually.
=> Use the public URL as the staging host

frontend/src/lib/services/neurons.services.ts, frontend/src/tests/lib/services/neurons.services.spec.ts
Simulating merging hotkey-controlled neurons is now supported by the governance canister and I tested it with a snapshot based on the latest ic commit.
1. Remove the check that a neuron is not hardware wallet controlled.
2. Use the authenticated identity instead of the controller identity.
3. Updated the test accordingly.
1. Unit test is updated in the PR.
2. Tested manually with the latest backend canisters that it works.
=> Enable simulating merge hotkey neurons

frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
Add the minimum of participants needed for a Swap to pass in the Project Detail page.
* Add one more KeyValuePair in the ProjectSwapDetails with the value of `min_participants`.
* Add a test case for the new value rendered.
=> Feat: Add Min Participants to Project Detail Page

frontend/src/lib/components/neurons/ConfirmNeuronsMerge.svelte, frontend/src/lib/components/neurons/NnsNeuronInfo.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/fakes/governance-api.fake.ts, frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts, frontend/src/tests/page-objects/ConfirmNeuronsMerge.page-object.ts, frontend/src/tests/page-objects/NnsNeuronInfo.page-object.ts
We want to show users the result of merging neurons before committing.
This PR just wires the results up to the UI but doesn't actually show much, just neuron ID and stake.
But having the scaffolding in place is useful when iterating.
1. If `ENABLE_SIMULATE_MERGE_NEURONS` is enabled, simulate the merge in the `ConfirmNeuronsMerge` component.
2. Show a skeleton card while waiting for the result.
3. Show an `NnsNeuronInfo` component when the result is there.
Unit tests:
1. simulateNeurons is not called when the feature is disabled.
2. merge result is show when the feature is enabled
3. skeleton card is shown while waiting
=> First version of simulate merge UI

.github/workflows/build.yml, .github/workflows/checks.yml, Dockerfile, e2e-tests/scripts/nns-canister.Dockerfile, scripts/setup
`cargo install` builds from source, making it slow.  So we pre-build many tools and download the pre-built binaries.  Now we have the problem that we have a bunch of scripts to find available versions and install them by curl.  `cargo binstall` does that for us.  For the versions, it uses the list of versions published as rust crates.  And it installs pre-built binaries, if available, else builds from source.
Pros:
- Using `binstall` saves us from having to write a bunch of custom curl-based installers and version finders.
Cons:
- We have to install `binstall`
- We have to put our pre-built executables at standardized locations.
- I have done this for `idl2json`, so `cargo binstall idl2json_cli` works.  It isn't that hard.
- I have made a PR to support binstall for `ic-wasm`.
- Change …
=> Use binstall

.github/workflows/aggregator.yaml, .github/workflows/build.yml, .github/workflows/checks.yml
`sns_demo` and `nns-dapp` now both use dfx v 0.14.1.
- Update the snsdemo commit.
See CI
=> Bump snsdemo

HACKING.md, e2e-tests/scripts/nns-canister-download, scripts/setup
I tried to build outside of Docker on my M1 and required a few interventions. This is only a partial list of the issues I discovered with @dskloetd help, but I'll make another PR once I test some more.
- `sns` binary url for Darwin was wrong
- `realpath` on my M1 exists on `/bin` so `./setup` didn't `brew install coreutils`, so I changed the condition to `sha256sum`
Manual tests
=> Fix some setup issues on a new M1 installation

frontend/src/lib/components/proposal-detail/MyVotes.svelte, frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.svelte, frontend/src/lib/components/sns-proposals/SnsVotingCard.svelte, frontend/src/lib/services/sns-vote-registration.services.ts, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/lib/utils/sns-proposals.utils.ts, frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts, frontend/src/tests/lib/services/sns-vote-registration.services.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts, frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
There was a bug where the voting power shows in the SNS proposals matched the voting power of the neuron, instead of the voting power of the ballot.
Voting power of a neuron for a proposal is set when the proposal is created. If the voting power of the neuron changes afterwards, it doesn't affect the voting power for earlier proposals.
* New sns proposal util `ballotVotingPower` to get the voting power of a neuron for a specific proposal.
* Change the voting power calculation in the sns vote registration service `proposalAfterVote`.
* Change the voting power calculation in the sns neuron util `votedSnsNeuronDetails`.
* Change the voting power calculation in the sns proposal util `snsNeuronToVotingNeuron`.
* Remove the unused property `parameters` in the changed functions and in the …
=> Fix: Use ballot voting power in SNS proposals

frontend/jest-resolver.cjs, frontend/jest.config.cjs, frontend/src/lib/api/canisters.api.cjs.ts, frontend/src/lib/services/worker-cycles.services.ts, frontend/src/lib/types/post-message.canister.ts, frontend/src/lib/types/post-messages.ts, frontend/src/lib/workers/cycles.worker.ts, frontend/src/tests/lib/api/canisters.api.cjs.spec.ts, frontend/src/tests/lib/services/worker-cycles.services.spec.ts
As described in https://dfinity.atlassian.net/browse/GIX-1584 a build environment variables was being used instead of the one from the initialization.
The problem was that the workers can't access `window` and therefore do not have access to the initialization env vars.
Solution for now: Pass the parameter in the post message instead of accessing the env vars directly.
Food for thought: Should we substitute the variables in the JS files instead of setting them in HTML during canister installation and upgrade?
* `queryCanisterDetails` expects two new optional params: `host` and `fetchRootKey`.
* PostMessage to the cycles worker includes `host` and `fetchRootKey`.
* Cycles service `initCyclesWorker` passes `host` and `fetchRootKey` in the post message to the worker.
* Cycles worker uses new …
=> GIX-1584: Build env var being used in worker

scripts/dfx-canister-url
The snsdemo repo has a command for getting canister URLs.  It is useful and can replace some of the logic in config.sh with something more maintainable.
Note:
* We could use `dfx-canister-url` directly from the snsdemo repo, however that assumes that we have the snsdemo repo bin in the path every time we call `config.sh` and that is not the case and can not trivially be made so.
* I have proposed putting the polyfill upstream in dfx proper, however that might take a while.  https://app.slack.com/client/T43F9UHS5/threads/thread/CGA566TPV-1685628863.824769
- Import `dfx-canister-url`
- Tweak due to slightly different linter settings.
The command is tested upstream
=> Import canister url command

frontend/src/lib/api/proposals.api.ts, frontend/src/lib/derived/proposals.derived.ts, frontend/src/lib/services/$public/proposals.services.ts, frontend/src/lib/utils/proposals.utils.ts, frontend/src/tests/lib/api/proposals.api.spec.ts, frontend/src/tests/lib/services/_public/proposals.services.spec.ts, frontend/src/tests/lib/utils/proposals.utils.spec.ts
Bring consistency in proposal filters.
Inconsistency: SNS filters showed all proposals if no filter was selected. Whereas NNS had a hack coming from flutter to not render any proposal if a filter was empty.
Solution: Along with product, we agreed to remove the legacy hack and consider no filter selected as "any". This is also the behavior of the backend endpoint.
* Remove hack in `findProposals` proposal service that would set an empty store if a filter was empty.
* Change the behavior of the queryProposals api when the topics filter is empty.
* Change behavior of the `matchFilters` helper inside the proposal utils.
* Add a test case for the `queryProposals` api new logic.
* Change the test case for the findProposals service.
* Change the test case for the `hide` proposal util.
=> Feat: Change functionality empty NNS Proposal filters

frontend/src/lib/pages/SnsProposalDetail.svelte, frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
Update the page layout title with selected sns proposal. Similar to nns proposal details page.
- update the layout title.
- update should be called on page render
=> Sns proposal layout title

frontend/src/lib/components/sns-proposals/SnsVotingCard.svelte, frontend/src/lib/pages/SnsProposalDetail.svelte, frontend/src/lib/stores/auth.store.ts, frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts, frontend/src/tests/page-objects/SnsProposalDetail.page-object.ts, frontend/src/tests/page-objects/SnsProposalVotingSection.page-object.ts, frontend/src/tests/page-objects/SnsVotingCard.page-object.ts, frontend/src/tests/page-objects/VotingConfirmationToolbar.page-object.ts
User was not able to vote on SNS proposal if was logging in directly from the SNS proposal detail page.
Problem: The neurons were not fetched.
* The `update` call in the SnsProposalDetail page depends on the `authStore`.
Main test:
* New test case in SnsProposalDetail to simulate the bug.
Additional changes:
* SnsVotingCard page object.
* New method `setForTesting` in `authStore`. This allows to fake logging in in unit tests.
* New methods in SnsProposalDetail page object.
* New methods in SnsProposalVotingSection page object.
* New SnsVotingCard page object.
* New ConfirmationToolBar page object.
=> Fix: Users are not able to vote in sns proposal

.github/workflows/build.yml
We have a test that checks that the wasm is the same, regardless of which network we are building for.  This test is commonly the last to finish in CI:
It would be nice if CI were to finish sooner.
* That the wasm does not depend on the network is guaranteed by the fact that the network is not an input to any of the wasm build steps in the Dockerfile.  As such, it probably suffices to perform the check only if the dockerfile has changed.
* If the test needs to be performed, use a larger runner.
* See CI
=> Faster wasm network independence test

Dockerfile
Deploying to an application subnet requires installing the wasm without assets, then installing assets afterwards.
Add a new docker build stage that builds the nns-dapp wasm with an empty assets tarfile.
None.  This should be tested in combination with the chunk uploading PR, once merged.
=> Build wasm without assets

frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/utils/sns-swap.utils.ts, frontend/src/tests/lib/utils/sns-swap.utils.spec.ts
We want to use the data from the derived state instead of getting the swap buyer count from the metrics from the raw endpoint.
Not all SNSes support the new field in the derived state with the count or buyers.
This PR: Prepare the util that will select the buyers count either from current swap metrics store or from derived state.
* New sns-swap util `swapSaleBuyerCount`.
* Use the new util in `ProjectCommitment.svelte` component.
* Add tests for new sns-swap util `swapSaleBuyerCount`
=> Feat: Swap Metrics util

frontend/src/lib/constants/stores.constants.ts, frontend/src/lib/stores/user-country.store.ts, frontend/src/lib/types/store.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/lib/utils/store.utils.ts, frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/services/user-country.services.spec.ts, frontend/src/tests/lib/stores/user-country.store.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/lib/utils/store.utils.spec.ts
We want stores to hold the error, loading and success states.
This PR: Introduces a type that should be used by the stores and a helper to convert the type to the success type.
The type is already used in the useCountryStore.
The util will be used in the util from PR #2700 [swapSaleBuyerCount](https://github.com/dfinity/nns-dapp/pull/2700/files#diff-aa44a48b94ac01459ed5ebb708a264a70bbd0b1c1afc4616da02d00053131738R4)
* New type `StoreData`.
* Use new type in `userCountryStore`.
* New store util `isStoreData`. Not used yet, only tested.
* New test file for new store util `isStoreData`.
=> Feat: Store data utils and type

frontend/src/lib/components/proposal-detail/NnsProposal.svelte, frontend/src/lib/components/proposal-detail/ProposalNavigation.svelte, frontend/src/tests/lib/components/proposal-detail/ProposalNavigation.spec.ts
Fix the missing proposal navigation buttons during a vote registration.
Sns fix will be implemented in another pr.
- Combine the ids for navigation component from available for voting proposal ids and currently in voting process.
- ProposalNavigation cares about the ids order and sorts them (because the combined list).
- ProposalNavigation sorts the ids
- The issue itself could be better addressed by an end-to-end test to ensure that the navigation is functioning properly even during the registration process.
=> Fix proposal navigation visibility during voting

frontend/src/lib/api/sns-aggregator.api.ts, frontend/src/lib/services/$public/sns.services.ts, frontend/src/lib/stores/sns.store.ts, frontend/src/tests/lib/services/_public/sns.services.spec.ts, frontend/src/tests/lib/stores/sns.store.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.json, frontend/src/tests/mocks/sns-aggregator.mock.ts
Use the new field `direct_participant_count` from derived state to display the number of participants of a swap instead of relying in the metrics raw endpoint.
In this PR: Use the SNS aggregator field derived_state which supports the latest properties.
* Add `derived_state` to the type of the SNS Aggregator resposne.
* Convert the type of the aggregator to the type needed by the snsQueryStore.
* Update the snsQueryStore with the value in the field `derived_state` from the aggregator.
* Fix the method `updateDerivedState` of the snsQueryStore that was ignoring the new fields.
* Add new field to the sns aggregator response mocks and converted mock.
* Test that the new field is used to update the snsQueryStore in the sns service.
* Check also the new fields in the tests for …
=> Feat: Support derived_state field in SNS Aggregator

frontend/src/lib/services/transaction-fees.services.ts
Correct esm import path for a type `Principal` that referenced cjs.
=> Correct esm import path for type

frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/utils/sns-swap.utils.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/utils/sns-swap.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/mocks/sns-response.mock.ts
Use the new field `direct_participant_count` from derived state to display the number of participants of a swap instead of relying in the metrics raw endpoint.
In this PR: Use the new field from derived state `direct_participant_count` instead of relying in the metrics.
* New util `hasBuyersCount` to check whether derived state supports new field.
* Do not watch raw metrics if derived_state supports new field.
* Extend swap util `swapSaleBuyerCount` with the derived state.
* Use the derived state in ProjectCommitment `swapSaleBuyerCount`.
* Test new util `hasBuyersCount`.
* Add new test cases for `swapSaleBuyerCount` test util.
* Add test cases in ProjectDetail.
* Add test case in ProjectCommitment
=> Feat: Use derived state for buyers count

frontend/src/lib/worker-api/icrc-index.worker-api.ts, frontend/src/lib/worker-api/icrc-ledger.worker-api.ts, frontend/src/tests/lib/worker-api/icrc-index.worker-api.spec.ts, frontend/src/tests/lib/worker-api/icrc-ledger.worker-api.spec.ts
In #2639 we will need to fetch Icrc balances and transactions from workers, this PR provides specific API for it.
In the future  we might be able to refactor the app to just use the same API for any UI and workers but, thought it's a first step.
- new `icrc-index.worker-api` and `icrc-ledger.worker-api`
=> Icrc balance and transactions api for workers

.github/actions/start_dfx_snapshot/action.yaml, .github/workflows/aggregator.yaml, .github/workflows/build.yml, .github/workflows/checks.yml, Dockerfile, dfx.json, e2e-tests/scripts/nns-canister.Dockerfile, scripts/setup
`idl2json` has a newer version that exposes the `--bytes-as hex` option.
Additionally, the new version supports binstall, which is a standard installer for rust executables, so we can deprecate the custom installer (`dfxsoftware-idl2json-install`).
- Update idl2json version
- use binstall to install idl2json.
See CI.  Existing tests should suffice.
=> Update idl2json & use binstall

.github/workflows/deploy-to-app.yaml
The workflow for deploying to an app subnet is live now, but has imperfections and bugs.
- The installation mode default is the first entry on the list of choices, but currently the first entry is "install" which is almost never wanted.
- The logic for choosing which canisters to deploy uses the wrong key (mode instead of canisters.  D'oh)
- Make "upgrade" and "reinstall": the first entries on the list of deployment types.
- Use the correct key for the canister selection.
Unfortunately this can only be tested by merging to main.
=> Fixes and tweaks for the app deploy workflow

.github/workflows/build.yml, Dockerfile
The code that runs on dockerfile change never runs.  This is because the wrong namespace is used for the github variable.
- `s/needs/steps/g`
- No run with no change to the dockerfile:
- Run with a trivial change to the dockerfile:
=> Fix: steps not needs

scripts/setup
On M1 macs (and possibly Intel as well) coreutils tools may be installed but not front-of-path.  This can cause undefined behaviour, when ancient apple tools are invoked instead.
* Check that tools such as date use the coreutils versions, and if not install coreutils (as before) and put the coreutils front of path.
* None.  Can someone with an M1 mac test please?
=> Put coreutils front of path on mac

.github/workflows/build.yml, scripts/dfx-software-nd-cache, scripts/nns-dapp/downgrade-upgrade-test
*  The nns-dapp wasm used to be different depending on which network it was deployed to.  So we had a `_local` build for use on localhost and CI.
* Then the wasm was the same for all networks, but we retained `_local` to avoid breaking workflows.
* The time has come to sunset _local.
* Transition all remaining references to `nns-dapp_local.wasm` to `nns-dapp.wasm`
* None.  Existing functionality should be unaffected.
* Third parties who haven't yet transitioned to the universal build will have to do so now.
=> Cleanup: Sunset nns-dapp_local.wasm

frontend/src/lib/services/ledger.services.ts, frontend/src/tests/lib/services/ledger.services.spec.ts, frontend/src/tests/mocks/ledger.identity.mock.ts
The user was getting "Send ICP" in the HW screen instead of "Stake Neuron" if they were staking two neurons in a row without refreshing the page.
Problem: The agent from `createAgent` is cache. Therefore it was using the identity from the first staking. Yet, the service to stake a neuron was getting a new identity and setting the flag to stake neuron in that identity.
* Cache the ledger identity.
* Add a test to the ledger service to check that the identity is cached.
=> Fix: Screen Title in HW when staking two neurons

frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronVestingPeriodRemaining.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVestingPeriodRemaining.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts, frontend/src/tests/page-objects/SnsNeuronMetaInfoCard.page-object.ts, frontend/src/tests/page-objects/SnsNeuronVestingPeriodRemaining.page-object.ts
SNS neurons for developers might have a vesting period. During this vesting period, the functionality of the neuron is limited.
Therefore, the UI should tell the user how long is until the neuron will have it's full capability.
The UI might change. Product is looking into it but it shouldn't be very different. We can change after releasing the feature if needed.
* New SnsNeuronVestingPeriodRemaining to render the vesting period if still active.
* Use the new component in the SnsNeuronMetaInfoCard.
* New sns neuron utils `isVesting` and `vestingInSeconds`.
* Test the new component SnsNeuronVestingPeriodRemaining
* Add a test case in SnsNeuronMetaInfoCard
* Test new sns neuron utils.
=> GIX-1637: Show Vesting Period in SNS Neuron

scripts/nns-dapp/release-template
https://github.com/dfinity/nns-dapp/pull/2236 intended to add arguments verification instructions to the proposal template but it actually only added them to the rollback proposal template.
Also the instructions there suggest to check the sha256sum but the proposal payload contains the binary hex so I think it makes more sense to provide instructions to output that because that's what can actually be compared to the proposal payload, as displayed on the dashboard, for example.
1. Change the instructions to output binary hex.
2. Copy the same instructions from `ROLLBACK.md` to `PROPOSAL.md`
3. For convenience, mention the `arg_hex` field in the proposal payload to compare to.
Ran `scripts/nns-dapp/release-template` and checked the sections in `PROPOSAL.md`:
````
You may also want to verify …
```
=> Fix args verification in release template

frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronInfoStake.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts, frontend/src/tests/mocks/sns-neurons.mock.ts, frontend/src/tests/page-objects/SnsNeuronMetaInfoCard.page-object.ts
SNS neurons for developers might have a vesting period. During this vesting period, the functionality of the neuron is limited.
UI should not show unavailable functionality. Therefore, the following buttons are hidden during the vesting period:
* Increase Dissolve Delay
* Start or Stop Dissolving
* Disburse
* Split
* In `SnsNeuronInfoStake` use `isVesting` for `allowedToDissolve` and `allowedToDisburse`.
* In `SnsNeuronMetaInfoCard` use `isVesting` for `allowedToSplit`.
* Extend `createMockSnsNeuron` to return neuron with vesting configuration.
* Extend `SnsNeuronMetaInfoCardPo` to check the Split button.
* Add test case for the hidden buttons during vesting in `SnsNeuronInfoStake`.
* Add test case for the hidden buttons during vesting in `SnsNeuronMetaInfoCard`.
=> GIX-1642: Hide unavailable buttons when vesting

.gitattributes, .github/pull_request_template.md, CHANGELOG-Nns-Dapp.md, CHANGELOG-Sns_Aggregator.md
Improve the release process. Creating the Changelog before the release is a lot of work. With some time spent on each PR by each author the Changelog can be kept up to date.
* Add new section "Todos" in Github PR template.
* Rename current CHANGELOG.md to CHANGELOG-Nns_Dapp.md
* New file CHANGELOG-Sns_Aggregator.md
* New types of changes inside the CHANGELOG files.
Only documentation changes.
=> Chore: New Changelog setup

.github/workflows/build.yml, Dockerfile, config.sh, dfx.json, scripts/dfx-canister-url
Storing network configuration in dfx.json is deprecated.  Removing the network config from dfx.json requires, among other things, using the standard logic for how to calculate URLs.
- Update `dfx-canister-url` to the latest version.  This is a command that gets URLs using the current IC policies.
- Compute URLs in the nns-dapp config using `dfx-canister-url`.
- Update the dockerfile to include `dfx-canister-url` where needed.
- CI should check that the parameters have not changed for mainnet, and work for localhost.
- I checked manually that the config is unchanged for `benchmarklarge`.  I used the following one-liner but it's probably not very easy to follow.  The steps are:
- On the feature branch and on main, set canister IDs as if all the canisters had been deployed.
- Compute the …
=> Use standard tool for getting canister URLs

frontend/package-lock.json, frontend/package.json
Fix semver vulnerable to Regular Expression Denial of Service [CVE-2022-25883](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw).
- pin `semver` to v7.3.5
=> Bump semver

frontend/src/lib/worker-api/canisters.worker-api.ts, frontend/src/lib/worker-utils/canister.worker-utils.ts, frontend/src/tests/lib/worker-api/canisters.worker-api.spec.ts, frontend/vite.config.ts
Web Workers ES modules are required to build easily  #2639 and are now supported by all browsers.
- active ESM for Web Workers
- drop explicit usage of agent-js CJS
=> Build Web Workers ESM

frontend/package-lock.json
Fix semver vulnerable to Regular Expression Denial of Service [CVE-2022-25883](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw).
- bump ic-js and gix-cmp
=> Bump ic-js and gix-cmp for semver

.github/workflows/build.yml, .github/workflows/checks.yml, scripts/nns-dapp/download-ci-wasm, scripts/nns-dapp/download-ci-wasm.test
We want to make the release a less manual process.
One of the steps in the release process is to download the WASM from CI.
Add a script to download the nns-dapp WASM from CI.
Ran the script, also with wrong commit and wrong filename to exercise the error code paths.
Added a test which checks that the downloaded file is a gzip file.
=> Script to download wasm from CI

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/download-ci-wasm, scripts/nns-dapp/download-ci-wasm.test, scripts/nns-dapp/get-ci-build-run, scripts/nns-dapp/get-hash-from-ci-log
Trying to make the release a less manual process.
One of the steps in the release process is getting the WASM hash from the build log from CI.
1. Add a script to get the WASM hash from the build log from CI.
2. Factor out common code to get the GitHub CI run number for a given commit.
Changed `scripts/nns-dapp/download-ci-wasm.test` to verify that the hash of the downloaded file matches the hash from the log.
=> Script to get hash from CI log

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/sns-neuron-detail/SnsNeuronInfoStake.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte, frontend/src/lib/components/sns-neuron-detail/VestingTooltipWrapper.svelte, frontend/src/lib/components/sns-neuron-detail/actions/DisburseSnsButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/DissolveSnsNeuronButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SplitSnsNeuronButton.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronContextTest.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronInfoStake.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/VestingTooltipWrapper.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/DisburseSnsButton.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/DissolveSnsNeuronButton.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/DissolveSnsNeuronButtonTest.svelte, frontend/src/tests/lib/components/sns-neuron-detail/actions/SplitSnsNeuronButton.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts, frontend/src/tests/mocks/sns-neurons.mock.ts, frontend/src/tests/page-objects/VestingTooltipWrapper.page-object.ts
Instead of hiding the unavailable functionality while neuron is vesting, we want to disable it and explain why it's disabled.
* New component `VestingTooltipWrapper` that checks whether a neuron is vesting and renders only the child or the child wrapped in a tooltip.
* Use `VestingTooltipWrapper` in `IncreaseSnsDissolveDelayButton`
* Add new param `neuron` in `IncreaseSnsDissolveDelayButton`.
* Use `VestingTooltipWrapper` in `DissolveSnsNeuronButton`
* Use `VestingTooltipWrapper` in `SplitSnsNeuronButton`
* Add new param `neuron` in `DissolveSnsNeuronButton` instead of the neuronState.
* Change test cases from expecting no button to a disabled button.
* Add test cases in the button components to check the tooltip is present when vesting.
* New page object for the new compoment …
=> Feat: Disable functionality while vesting

CHANGELOG-Nns-Dapp.md, config.sh
The nns-dapp config script currently relies on a network config entry being present in dfx.json.  The network config in dfx.json is not always present for all networks, and is indeed deprecated so will be removed entirely.
- Make per-network config optional.
- The config script works exactly as before if there is a config entry, which there is for prod.
- For local deployments, CI should suffice.
=> Don't require a config field in the network

CHANGELOG-Nns-Dapp.md, frontend/package-lock.json, frontend/src/lib/i18n/en.json, frontend/src/lib/modals/common/FilterModal.svelte, frontend/src/lib/modals/proposals/NnsProposalsFilterModal.svelte, frontend/src/lib/modals/sns/proposals/SnsFilterRewardsModal.svelte, frontend/src/lib/modals/sns/proposals/SnsFilterStatusModal.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/modals/common/FilterModal.spec.ts, frontend/src/tests/lib/modals/proposals/NnsProposalsFilterModal.spec.ts, frontend/src/tests/lib/modals/sns/SnsFilterRewardsModal.spec.ts, frontend/src/tests/lib/modals/sns/SnsFilterStatusModal.spec.ts
Allow the user to easily select or clear all the proposal filters.
* Upgrade gix-components which adds a new slot to Modal.
* FilterModal uses the new slot in the modal to add two buttons "Select All" and "Clear" which trigger two new events "nnsSelectAll" and "nnsClearSelection".
* Implement the two new events in NnsProposalsFiltersModal
* Implement the two new events in SnsFilterRewardsModal
* Implement the two new events in SnsFilterStatusModal
* Test that FilterModal triggers two new events.
* Test that NnsProposalsFiltersModal selects all and clears selection.
* Test that SnsFilterRewardsModal selects all and clears selection.
* Test that SnsFilterStatuModal selects all and clears selection.
=> Feat: Add "Select All" and "Clear" buttons to proposals filters

frontend/src/lib/utils/before-unload.utils.ts, frontend/src/routes/(app)/+layout.svelte
Listeners were probably copied a long time ago from Papyrs that's why they mention "sync...". 
We can rename those to be more generic.
=> Rename close listeners

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/get-ci-build-run
We have a script that downloads the WASM from CI. It uses `gh` to get a successful run by using `--status success`. This was working before but at commit `8ac5bef5427b0e3b003794fd2545eb9fd92cee83` it does not find any runs. But if I remove the flag, I do see runs that are successful.
Instead of using the `--status success` flag of `gh`. Parse the `.conclusion` field of the result to find the successful runs.
This was found because `scripts/nns-dapp/download-ci-wasm.test` was failing so the test was working.
The test passed on this PR: https://github.com/dfinity/nns-dapp/actions/runs/5399373231/jobs/9806423017?pr=2775
=> Parse build run conslusion instead of using --status of gh

frontend/src/lib/stores/icrc-accounts.store.ts, frontend/src/tests/lib/stores/icrc-accounts.store.spec.ts
Add an `update` feature to `icrc-accounts` which can be use to update accounts when those are refreshed by a worker.
=> feat: icrc-accounts.store update

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/sns-proposals/SnsVotingCard.svelte, frontend/src/lib/utils/sns-proposals.utils.ts, frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts, frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts, frontend/src/tests/mocks/sns-proposals.mock.ts
Users couldn't vote on proposals that were decided (executed, or failed, ...) but still accepting proposals.
* Fix logic in `snsProposalOpen` to check the reward status of the proposal.
* Rename `snsProposalOpen` to `snsProposalAcceptingVotes` to more accurately describe what it does.
* Add two new params to `createSnsProposal`: ballots and created at.
* Change test for `snsProposalOpen` and add more test cases.
* Add test case in SnsVotingCard to replicate the issue and make it pass.
=> Fix: Voting after SNS proposal has closed

frontend/src/lib/components/header/AccountSyncIndicator.svelte, frontend/src/tests/lib/components/header/AccountSyncIndicator.spec.ts
If user click on the indicator while in progress, a popover is displayed.
The popover and indicator goes hidden as soon as the worker is idle.
When the worker starts again, the indicator is displayed and because the state might not have been resetted, the popover is currently displayed again automatically, which is a bit surprising.
To avoid this behavior, let's close the popover state as soon as the indicator turns idle.
=> Auto close sync indicator

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
Tooltip is misplaced for the Split SNS neuron button.
* Add style to wrapper of the button to set the tooltip.
Only style issues.
=> Fix: Tooltip Split Sns Neuron Button

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/common/SignIn.svelte, frontend/src/lib/components/header/LoginIconOnly.svelte, frontend/src/lib/services/auth.services.ts, frontend/src/tests/lib/services/auth.services.spec.ts
Agent-js bubbles the error `UserInterrupt` when user interrupts the sign-in flow which per extension is displayed in a toast error in NNS dapp. Because this has not much value for most of the users, we are going to ignore these particular "error".
- if `UserInterrupt` then no toast
- refactor duplicated code and solve TODO
=> Ignore sign-in "error" UserInterrupt

rs/backend/nns-dapp-exports.txt, rs/backend/nns-dapp.did, rs/backend/src/accounts_store.rs, rs/backend/src/accounts_store/tests.rs, rs/backend/src/main.rs
Users want to be able to add names to their canisters.
We already enabled canisters to be created with a name, but we were missing an endpoint to rename canisters.
This PR introduces the nns-dapp canister endpoint to rename canisters.
In another PR: Use this endpoint from the NNS Dapp frontend.
* New endpoint `rename_canister` in NNS Dapp canister.
* New method `rename_canister` in AccountsStore to rename a canister.
* Related types.
* Test the new method in the AccountsStore.
Not yet entry in the changelog until I add all the renaming functionality.
=> GIX-1656: Rename Canister Endpoint

CHANGELOG-Nns-Dapp.md, rs/backend/src/proposals.rs
When the proposal payload cache was written, `pop_first()` existed but only in unstable rust.  Now it is available in stable, so we can close the TODO.
* Simplify code with `pop_first()`
* Existing tests should suffice.
=> Address TODO: Use pop_first

frontend/src/lib/api/canisters.api.ts, frontend/src/lib/canisters/nns-dapp/nns-dapp.canister.ts, frontend/src/lib/canisters/nns-dapp/nns-dapp.certified.idl.js, frontend/src/lib/canisters/nns-dapp/nns-dapp.did, frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js, frontend/src/lib/canisters/nns-dapp/nns-dapp.types.ts, frontend/src/lib/i18n/en.json, frontend/src/lib/services/canisters.services.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/api/canisters.api.spec.ts, frontend/src/tests/lib/canisters/nns-dapp.canister.spec.ts, frontend/src/tests/lib/services/canisters.services.spec.ts
Users want to be able to add names to their canisters.
In this PR: I extend the nns-dapp canister to support the endpoint for renaming and create the api and service functions.
* Extend nns dapp canister candid files and related.
* New method in nns-dapp canister class `renameCanister`.
* New canister api function `renameCanister`.
* New canister service `renameCanister`.
* Test new nns-dapp canister method `renameCanister`.
* Test new api function `renameCanister`
* Test new service `renameCanister`
Not yet any entry in the changelog because nothing is exposed to the user yet.
=> GIX-1656: Add renaming canister api and service

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/ci-link, scripts/nns-dapp/get-ci-build-run, scripts/nns-dapp/release-template
https://github.com/dfinity/nns-dapp/pull/2744 changed workflow names.
`scripts/nns-dapp/ci-link` expects there to be a workflow named "Docker build" but it no longer exists.
Change `scripts/nns-dapp/ci-link` to use `scripts/nns-dapp/get-ci-build-run` which is tested.
The only difference is that `ci-link` used to output multiple links and now only 1.
But the only place where it's used, it was followed by `tail -n 1` so this fine.
None, but now most of the work is done by `scripts/nns-dapp/get-ci-build-run`, which is used by `scripts/nns-dapp/download-ci-wasm` and thus tested here: https://github.com/dfinity/nns-dapp/blob/75936135f738040a3cdfeec73d626cb4e3b9eb46/.github/workflows/checks.yml#L271
=> Update CI workflow name used by ci-link

CHANGELOG-Nns-Dapp.md, dfx.json
There is a currently a custom URL for II for mainnet deployments, but not for deployments to the app subnet.
When the app subnet deployment was using the mainnet config, this was not a problem.  Now that the app deployment uses its own config, we need correct values.
- Move the custom URL to the canister config, as the network entries are deprecated.
- Add a custom URL for deployments to the ic.
- Tested manually for the `ic` network.
- CI has a test to confirm that the mainnet config is unchanged.
- Making a full config test similar to that used to test the mainnet config requires more changes, so I would rather do this in a separate PR.
=> Set custom URL for II on the ic

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/canisters/CanisterCardTitle.svelte, frontend/src/tests/lib/pages/CanisterDetail.spec.ts
Improve the tests of the CanisterDetail page.
This will allow me to add a test for the rename canister flow later.
* Mock api level instead of services layer in CanisterDetail.spec.ts.
=> Test: Improve Canister Details Tests

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neurons/ConfirmNeuronsMerge.svelte, frontend/src/lib/components/neurons/NnsNeuronDetailCard.svelte, frontend/src/tests/lib/components/neurons/NnsNeuronDetailCard.spec.ts, frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts, frontend/src/tests/page-objects/ConfirmNeuronsMerge.page-object.ts, frontend/src/tests/page-objects/NnsNeuronDetailCard.page-object.ts
We want to show the results or merging neurons before the user commits.
This PR adds more details in the `ConfirmNeuronsMerge` steps.
Here you can see what it looks like but the details are not important because this is behind a feature flag just to try it out and iterate on:
1. Add new component `NnsNeuronDetailCard`
2. Use it instead of `NnsNeuronInfo` in `ConfirmNeuronsMerge`
1. `frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts` is modified to work with the new card.
2. A new test is added for the new component.
3. A page object is added for the new component.
=> More details in merge neurons simulation

CHANGELOG-Nns-Dapp.md, scripts/clap.bash
Short arguments should be optional.
They were made optional in snsdemo in https://github.com/dfinity/snsdemo/pull/104 but not yet in nns-dapp.
Copy `snsdemo/bin/clap.bash` to `nns-dapp/scripts`.
`clap` itself is tested in `snsdemo`.
For `nns-dapp`, CI should still pass.
=> Copy newest clap.bash from snsdemo

CHANGELOG-Nns-Dapp.md, rs/backend/src/accounts_store.rs, rs/backend/src/accounts_store/tests.rs
User wants to add a name when creating a canister.
There was a bug in the create canister flow.
When creating a canister, the nns-dapp backend has a runner task that attached a newly created canister. This method was overriding the previous attched canister by the method `attach_canister` with an empty name.
* Attach the canister in the runner flow only if canister_id is not alreay attached.
* Manage race condition in `attach_canister` method. The runner could be faster than the call to this request.
* Add tests for `attach_newly_created_canister`.
* Add test for new condition in `attach_canister`.
=> GIX-1658: Fix task runner substitutes canister

frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/components/accounts/CkBTCWalletTransactionsObserver.svelte, frontend/src/lib/components/accounts/SnsWalletTransactionsObserver.svelte, frontend/src/lib/services/observer.services.ts, frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletTransactionsObserver.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletTransactionsObserverTest.svelte, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/lib/services/oberserver.services.spec.ts
Use the new web workers to observe the ckBTC transactions in the dedicated wallet page.
- extract `SnsWalletTransactionsObserver` web worker transactions callback to a service to reuse it for ckBTC
- create `CkBTCWalletTransactionsObserver`
=> Observe ckBTC transactions

frontend/package-lock.json, frontend/src/lib/canisters/ic-management/converters.ts, frontend/src/lib/canisters/ic-management/ic-management.canister.types.ts, frontend/src/lib/worker-api/canisters.worker-api.ts, frontend/src/tests/lib/canisters/ic-management.canister.spec.ts, frontend/src/tests/lib/worker-api/canisters.worker-api.spec.ts, frontend/src/tests/mocks/canisters.mock.ts
Bump ic-js to next after release of ic-js v0.0.18.
Implement the usage of the `@dfinity/ic-management` library because the definition in agent-js is not up-to-date anymore and ship a fix to use this library locally.
=> build: upgrade next and ic-management

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/canister-detail/RenameCanisterButton.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/modals/canisters/CanisterDetailModals.svelte, frontend/src/lib/modals/canisters/RenameCanisterModal.svelte, frontend/src/lib/pages/CanisterDetail.svelte, frontend/src/lib/stores/busy.store.ts, frontend/src/lib/types/canister-detail.modal.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/canister-detail/RenameCanisterButton.spec.ts, frontend/src/tests/lib/components/canister-detail/RenameCanisterButtonTest.svelte, frontend/src/tests/lib/modals/canisters/RenameCanisterModal.spec.ts, frontend/src/tests/lib/modals/canisters/RenameCanisterModalTest.svelte, frontend/src/tests/lib/pages/CanisterDetail.spec.ts, frontend/src/tests/page-objects/CanisterDetail.page-object.ts, frontend/src/tests/page-objects/RenameCanisterButton.page-object.ts, frontend/src/tests/page-objects/RenameCanisterModal.page-object.ts, frontend/src/tests/page-objects/TextInputForm.page-object.ts
Users want to be able to add a name to their canisters.
In this PR: Users can add a name after the canister has been attached to the user.
* New button RenameCanisterButton.
* New modal RenameCanisterModal.
* Render new button in CanisterDetail page.
* Test that RenameCanisterButton opens modal.
* Test that modal calls api RenameCanisterModal.
* Test that user can rename from CanisterDetail.
* Add related page objects.
=> GIX-1656: Rename canister modal

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/common/TextInputForm.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/modals/canisters/CreateCanisterModal.svelte, frontend/src/lib/modals/canisters/RenameCanisterModal.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/canisters.utils.ts, frontend/src/tests/lib/components/common/TextInputForm.spec.ts, frontend/src/tests/lib/modals/canisters/CreateCanisterModal.spec.ts, frontend/src/tests/lib/modals/canisters/RenameCanisterModal.spec.ts, frontend/src/tests/lib/utils/canisters.utils.spec.ts
The rules when naming canisters on creating or afterwards was not consistent and there was no feedback to the user about them
In this PR: I apply the same rules in both flows and show an error message to the user when needed.
* Add `errorMessage` parameter to `TextInputForm`.
* New canister util `errorCanisterNameMessage` that returns error or `undefined`.
* Use new parameter with new util in `RenameCanisterModal`.
* Use new parameter with new util in `CreateCanisterModal`.
* Change the rules to disable the button in `RenameCanisterModal`.
* Test new parameter in `TextInputForm`.
* Test new cansiter util `errorCanisterNameMessage`.
* Add a test case in `CreateCanisterModal`.
* Add a test case in `RenameCanisterModal` and change the expectation when input is empty.
=> GIX-1656: Apply same rules and show errors when creating and renaming canisters

CHANGELOG-Nns-Dapp.md, frontend/src/lib/api/canisters.api.ts, frontend/src/tests/lib/api/canisters.api.spec.ts
Fail in the client if we know that the backend will fail when attaching, creating, or renaming a canister.
* Add a check for the canister name length in canister api layer.
* New test case for `attachCanister`, `createCanister` and `renameCanister`.
=> GIX-1658: Add canister name check api

CHANGELOG-Nns-Dapp.md, frontend/src/lib/i18n/en.json, frontend/src/lib/modals/canisters/LinkCanisterModal.svelte, frontend/src/lib/services/canisters.services.ts, frontend/src/tests/lib/modals/canisters/LinkCanisterModal.spec.ts, frontend/src/tests/lib/services/canisters.services.spec.ts
Users want to have name in their canisters. Also when they link a canister.
In this PR: Add an input field for the name in the flow to link a canister.
* Remove the WizardModal and instead add a new field for the name in the LinkCanisterModal.
* Add `name` parameter in the `attachCanister` service.
* Fix tests for `attachCanister` service.
* Add name in the `LinkCanisterModal` main test case and add a couple of more cases.
=> GIX-1657: Add name when linking canister

CHANGELOG-Nns-Dapp.md
Improve to changelog to make it clear that the "canister name" is not implemented on the protocol level.
=> Improve changelog about canister name

frontend/src/lib/components/accounts/NnsDestinationAddress.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronInfoStake.svelte, frontend/src/lib/modals/neurons/DisburseNnsNeuronModal.svelte, frontend/src/lib/modals/neurons/NnsNeuronModals.svelte, frontend/src/tests/e2e/disburse.spec.ts, frontend/src/tests/page-objects/App.page-object.ts, frontend/src/tests/page-objects/ConfirmDisburseNeuron.page-object.ts, frontend/src/tests/page-objects/DisburseNnsNeuronModal.page-object.ts, frontend/src/tests/page-objects/MenuItems.page-object.ts, frontend/src/tests/page-objects/NnsDestinationAddress.page-object.ts, frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/NnsNeuronInfoStake.page-object.ts, frontend/src/tests/page-objects/NnsNeuronModals.page-object.ts, frontend/src/tests/page-objects/NnsNeuronsFooter.page-object.ts, frontend/src/tests/page-objects/NnsSelectAccount.page-object.ts, frontend/src/tests/page-objects/NnsStakeNeuronModal.page-object.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
I want to replace this old wdio e2e test with a Playwright e2e test so we can delete the old test:
https://github.com/dfinity/nns-dapp/blob/main/e2e-tests/specs/user-N02-neurons-disbursed.e2e.ts
I tried to follow the same steps as that test.
1. Add `disburse.spec.ts` which does the e2e test to disburse a neuron.
2. Add necessary page objects and test IDs.
3. Allow specifying the dissolve delay when staking a neuron. Right now it only supports `"max"` and `0`. It's easy to support other numbers but the code path wouldn't be used so let's do that when we use it.
yes
Is it worth mentioning? It's not new coverage just the same coverage in a different way.
=> E2E: Disburse NNS neuron

CHANGELOG-Nns-Dapp.md
An entry in the changelog for the previous proposal is wrong because the functionality is not yet released.
It was previously added in https://github.com/dfinity/nns-dapp/pull/2804.
* Move entry in the changelog.
Only doc changes
=> Chore: Move changelog entry

.github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md, scripts/past-changelog-test
I've seen twice that people added or tried to add an entry in the change log to an already existing release.
I suspect this is because they started the PR before the change log was updated and weren't careful enough when reviewing the results of the merge.
Test that no changes are made to `CHANGELOG-Nns-Dapp.md` below the first `## Proposal [0-9]+` line.
We can look at doing the same for `CHANGELOG-Sns_Aggregator.md` but so far there aren't any changes there.
Also added missing entries to `checks-pass.needs` in `checks.yml`.
This is a test.
=> Test that no new change log entries are added to past releases.

CHANGELOG-Sns_Aggregator.md, rs/sns_aggregator/src/types/ic_sns_governance.patch, rs/sns_aggregator/src/types/ic_sns_ledger.patch, rs/sns_aggregator/src/types/ic_sns_root.patch, rs/sns_aggregator/src/types/ic_sns_swap.patch, rs/sns_aggregator/src/types/ic_sns_wasm.patch, scripts/did2rs.sh
The patch files applied when generating Rust from SNS .did files are quite large and break easily.  There are a few changes in the automatic generation that can make the patch files significantly smaller.  Here is the first:
Service definitions have return type `CallResult` but `didc` generates `Result` in the rust code, with the expectation that the `CallResult` will be imported as `Result`.  Unfortunately that expectation can often not be met as `Result` is used for other purposes.  So the patch files have many lines dedicated to changeing the `Result` in the API signatures to `CallResult`.  This can be automated.
- Use `CallResult` instead of `Result` when auto-generating code.
- Delete patch file lines that used to do the same.
Observe that the test "IC Commit" generates the rust …
=> Call result patches

CHANGELOG-Nns-Dapp.md, frontend/src/tests/e2e/merge-neurons.spec.ts, frontend/src/tests/page-objects/MergeNeuronsModal.page-object.ts, frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts, frontend/src/tests/page-objects/NnsNeuronsFooter.page-object.ts, frontend/src/tests/page-objects/SelectNeuronsToMerge.page-object.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts, frontend/src/tests/page-objects/TextInput.page-object.ts, frontend/src/tests/page-objects/playwright.page-object.ts
I want to replace this old wdio e2e test with a Playwright e2e test so we can delete the old test:
https://github.com/dfinity/nns-dapp/blob/main/e2e-tests/specs/user-N03-neurons-merged.e2e.ts
I tried to follow the same steps as that test.
1. Add `merge-neurons.spec.ts` which does the e2e test to merge neurons.
2. Add necessary page objects and test IDs.
3. Allow specifying the dissolve non-zero delay when staking a neuron.
4. Allow `TextInputPo` to be used for `<input type="number"` as well since the interface is the same.
5. Implement `getAttribute` and `getClasses` on `PlaywrightPageObjectElement` because it's needed for `NnsNeuronCardPo.isSelected`.
yes
Is it worth mentioning? It's not new coverage just the same coverage in a different way.
=> E2E: Merge neurons

.github/workflows/checks.yml, scripts/past-changelog-test
In https://github.com/dfinity/nns-dapp/pull/2825 I added a test to make sure new changelog entries aren't incorrectly merged into an existing release.
The test prevented merging PRs without new entries in `CHANGELOG_Nns-Dapp.md` so I disabled it.
1. Make the test pass if there are no new entries in `CHANGELOG_Nns-Dapp.md`.
2. Enable the test again.
It's a test.
Entry already exists.
And not adding an entry verifies that it's allowed now.
=> Fix an re-enabled change log entries test

scripts/dfx-canister-url
We are getting this mysterious error very often:
```
/home/runner/work/nns-dapp/nns-dapp/scripts/dfx-canister-url: line 139: echo: write error: Broken pipe
```
Example: https://github.com/dfinity/nns-dapp/actions/runs/5484564664/jobs/9992356558
Setting `set -x` to make the script output what it does, might help debugging.
`set -x` in `scripts/dfx-canister-url`
none
None
=> Set -x scripts/dfx-canister-url

.github/workflows/build.yml, CHANGELOG-Nns-Dapp.md, frontend/playwright.config.ts
VITE_OWN_CANISTER_URL should not be used by the frontend code so we want to remove it.
But it's also used in the Playwright config to determine where to connect to.
We can use `scripts/dfx-canister-url` to determine where to connect instead.
1. In `frontend/playwright.config.ts` use environment variable `PLAYWRIGHT_BASE_URL` instead of `VITE_OWN_CANISTER_URL`.
2. Remove `dotenv` from `frontend/playwright.config.ts` because it's no longer used.
3. In `.github/workflows/build.yml` use `scripts/dfx-canister-url` to set `PLAYWRIGHT_BASE_URL`.
Yes
=> GIX-1677: Remove VITE_OWN_CANISTER_URL from e2e tests

scripts/dfx-canister-url, scripts/did2rs.sh
CI has failed several times over the last day or so.  Let's address some of the issues.
- A pipefail when getting the first entry from `dfx canister url`.
- A failure when rustfmt self-updates in a pipe.
- Remove the failing pipe by getting the first line using bash.  This is also nicer as it doesn't have to spin up another process.
- Call rustfmt on its own before use.  This costs a process call but makes rustfmt self-update in isolation before use.
See CI.
=> Make CI more robust

.github/workflows/update-didc.yml, .github/workflows/update-rust.yml, CHANGELOG-Nns-Dapp.md
II has some cute GitHub actions for updating dependencies automatically.
In our case, our code is closely intertwined with other canisters and codebases, in a way that II is not, so these automated PRs will often require manual intervention but they are still nice to have.
* Import the didc and rust update workflows from the II repo.
* Adapt the didc versioning code for our repo.
* Format.
* Wait and see what PRs it produces.
=> Steal II code to update didc and rust

.github/workflows/build.yml
We have a separate GitHub action which does all the steps to start a dfx snapshot.
But the `aggregator_test` does all the individual steps.
Use the action for the aggregator_test.
CI
This is in preparation to use the new snapshot which has the aggregator preloaded.
I'll add an entry when for that PR.
=> Use dfx snapshot GitHub action for aggregator_test

.github/workflows/build.yml
The newest snsdemo snapshot (which we don't use yet), has the sns_aggregator installed and SNSes preloaded.
We have a test that tests that data is collected by checking that there are 10 SNSes on the first page.
But we don't (yet) check that those SNSes were loaded during the test.
Add a step in the workflow where we check that the number of loaded SNSes is < 10 to make sure that data is actually collected during the test.
yes
This is in preparation to use the new snapshot which has the aggregator preloaded.
I'll add an entry when for that PR.
=> Make sure aggregator data collection happens during the test

.github/actions/start_dfx_snapshot/action.yaml, .github/workflows/build.yml
We probably always want to be consistent in which snsdemo commit and snapshot release the `start_dfx_snapshot` action uses and right now we have to update those every time in multiple places.
1. Provide default values for `snsdemo_ref` and `snapshot_url` in the `start_dfx_snapshot` action.
2. Stop passing the values for which defaults are provided.
CI
This is in preparation to use the new snapshot which has the aggregator preloaded.
I'll add an entry when for that PR.
=> Provide default values for dfx snapshot action

.github/workflows/checks.yml, rs/sns_aggregator/src/types/ic_sns_governance.patch, rs/sns_aggregator/src/types/ic_sns_governance.rs, rs/sns_aggregator/src/types/ic_sns_ledger.patch, rs/sns_aggregator/src/types/ic_sns_ledger.rs, rs/sns_aggregator/src/types/ic_sns_root.patch, rs/sns_aggregator/src/types/ic_sns_root.rs, rs/sns_aggregator/src/types/ic_sns_swap.patch, rs/sns_aggregator/src/types/ic_sns_swap.rs, rs/sns_aggregator/src/types/ic_sns_wasm.patch, rs/sns_aggregator/src/types/ic_sns_wasm.rs, scripts/dfx-canister-url, scripts/did2rs.sh
The patch files applied when generating Rust from SNS .did files have grown quite large and break easily.  There are a few changes in the automatic generation that can make the patch files significantly smaller.  Here is the fourth, or forth for the FORTH programmers of Fife:
The patch files contain ~150 lines of diff due to formatting.  If we format the auto-generated code, the patch files change but in total the patch files become significantly smaller and more consistent.
Normally it is advisable to change only one of the code or the patch files, but when formatting it is impossible to avoid changing both.
The Rust files are changed in these ways:
* Remove the header in the autogenerated rust that prevents rustfmt from formatting the files.  (See commit …
=> Fmt autogenerated rust

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/release-sop.test
When we change `release-sop` we also have to update the test json files.
This might be tedious.
Add `--update` flag to `release-sop.test` to automatically update the test golden files.
I manually change a test json file and ran the test:
```
$ scripts/nns-dapp/release-sop.test 
PASSED: release-sop-test-no-args
PASSED: release-sop-test-new-and-continue
PASSED: release-sop-test-invalid-name
1c1
< Branch Release-2001-02-29 already exists.
---
> XBranch Release-2001-02-29 already exists.
ERROR: actual output differs from expected output. See diff above.
Run 'scripts/nns-dapp/release-sop.test --update release-sop-test-branch-exists' to update the test.
FAILED: release-sop-test-branch-exists
```
Then I followed the instruction:
```
$ scripts/nns-dapp/release-sop.test --update …
```
=> A flag to update the golden files for release-sop.test

.github/workflows/update-didc.yml, .github/workflows/update-rust.yml, CHANGELOG-Nns-Dapp.md
It would be useful to be able to trigger the didc and rust update workflows manually rather than either by waiting for the next cron time or by adding a temporary trigger in a toy PR.
* Add a manual trigger, in the form of `workflow_dispatch`, for the rust and didc update workflows.
Workflow dispatch cannot be tested until it is merged in main, as the button is the button in the UI is defined in main.
=> Add a manual update trigger for didc and rust updates

rs/sns_aggregator/src/types/ic_sns_governance.patch, rs/sns_aggregator/src/types/ic_sns_swap.patch, scripts/did2rs.sh
The patch files applied when generating Rust from SNS .did files have grown quite large and break easily.  There are a few changes in the automatic generation that can make the patch files significantly smaller.  Here is the fifth:
* `EmptyRecord` is (almost always) used in enum entries without data.  That can be automated.
* Note: Interestingly, one empty enum entry has no `EmptyRecord`.  It would be interesting to know why.  Is the whole `EmptyRecord` dance not needed any more, or at least, not in enums?  Or is that a special case that works for some reason?  However that is not the focus of this PR.
* Proof of correctness: Note that the Rust code is unchanged, so the sns aggregator will behave in the same way.  The patch files have dropped from 339 lines to 266.
There is already an …
=> Empty record for enums as well

CHANGELOG-Nns-Dapp.md, frontend/src/lib/api/sns-governance.api.ts, frontend/src/lib/services/sns-neurons.services.ts, frontend/src/tests/lib/api/sns-governance.api.spec.ts, frontend/src/tests/lib/modals/sns/IncreaseSnsDissolveDelayModal.spec.ts, frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Dragginz SNS project has a max dissolve delay of 888 years.
The manageNeuron endpoint with IncreaseDissolveDelay doesn't support such a large number because it uses nat32.
In this PR: The NNS Dapp uses SetDissolveTimestamp which uses a nat64.
* Change sns governance api `increaseDissolveDelay` for `setDissolveDelay` that uses the `SetDissolveTimestamp` manage neuron endpoint.
* Sns neuron service `updateDelay` uses the `setDissolveDelay`.
* Substitute sns governance api test in `increaseDissolveDelay` for `setDissolveDelay`.
* Fix broken spec files after refactor.
=> GIX-1715: Use SetDissolveDelay for SNS neurons

frontend/src/lib/components/ui/Hash.svelte, frontend/src/lib/components/ui/IdentifierHash.svelte, frontend/src/tests/lib/components/ui/Hash.spec.ts
We don't need to cut NNS neuron ids in the new neuron settings.
Current IdentifierHash can't be configured to when start splitting and uses the default of the `shortenWithMiddleEllipsis` util.
* Expose the `splitLength` parameter of `shortenWithMiddleEllipsis` within `Hash` component.
* Expose the `splitLength` parameter of `Hash` within `IdentifierHash` component.
* Test that the new prop in `Hash` is being used.
Not worth mentioning in the changelog.
=> GIX-1683: IdentifierHash new prop splitLength

frontend/src/lib/components/universe/UniverseLogo.svelte, frontend/src/lib/components/universe/UniversePageSummary.svelte, frontend/src/tests/lib/components/universe/UniversePageSummary.spec.ts, frontend/src/tests/page-objects/UniversePageSummary.page-object.ts
The new neuron settings page shows the summary different from now.
In this PR: New component reusing UniverseLogo and UniverseName components.
* New component `UniversePageSummary`.
* New prop `horizontalPadding` in `UniverseLogo`.
I didn't want to reuse `Summary` because it has many different configurations and I didn't want to extend it even more.
* Test new component `UniversePageSummary`.
* New page component `UniversePageSummaryPo`.
Not worth a changelog entry yet.
=> GIX-1683: UniversePageSummary Component

frontend/src/lib/components/ic/AmountDisplay.svelte, frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
New neuron settings has as title the stake of the neuron in a similar display but huge font.
In this PR: Add one prop "huge" to `AmountDisplay`.
* New prop "huge" to `AmountDisplay` that uses the `font-size-huge`
Not worth mentioning changes yet.
=> GIX-1683: Add "huge" to AmountDisplay

frontend/package-lock.json, frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/routes/(app)/(u)/(detail)/+layout.svelte, frontend/src/routes/(login)/+layout.svelte
Svelte transitions are executed by default in components regardless if their parent components destroy those or not. This behavior is known as the `|global` transitions.
This leads NNS dapp to various issues in which components are not destroyed and therefore, there context remains active.
Until today we solved this by applying a workaround in which we destroyed the all layout in case of navigation. While it solved the issue, this had for side effect to be a bit unpleasant for the eyes as the all page layout disappeared on navigation.
By setting all the animation to `|local` we can solve the issue and make the navigation more fluid.
- documentation: https://svelte.dev/docs/v4-migration-guide#transitions-are-local-by-default
- svelte issue: https://github.com/sveltejs/svelte/issues/6686
- …
=> Set transitions as |local to solve populating destroy

CHANGELOG-Nns-Dapp.md, dfx.json
There are two version fields for the `ic-cdk-optimizer` in `dfx.json`.  Only one is used.  Confusing.
* Delete the unused version field.
See CI.
=> Rm unused field

CHANGELOG-Nns-Dapp.md, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts
As explained [here](https://forum.dfinity.org/t/52-year-neuron-fixes/21301),  only neurons in the Locked state are mergeable until further notice.
To avoid confusion with the users, we should apply this condition on top of the rest of conditions we use to disable neurons when merging them.
* Add a new case in neuron util helper `isMergeableNeuron`.
* Add the same case in neuron util helper `getMergeableNeuronMessageKey`.
* Add a new teste case in `mapMergeableNeurons` which uses the helpers.
* Add the Locked state explicitly in the merging neurons tests. This was not strictly necessary because the mock neuron is already in the locked state. But I preferred to be explicit that the locked state is required for a mergeable neuron.
=> GIX-1725: Merge Only Locked Neurons

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/sns-proposals/SnsProposerEntry.svelte, frontend/src/lib/components/ui/Hash.svelte, frontend/src/lib/components/ui/Tooltip.svelte
The sns proposal proposer ID text is shortened so it's not possible to copy it from the UI. This pr adds the copy button to solve it.
- add `flowLessCopy` param. Otherwise the button is not centered and stretch out the card bottom.
- add the copy button to proposer id
- manually, because only style changes
| Before | Now |
| ![image](https://github.com/dfinity/nns-dapp/assets/98811342/e2802dc0-0095-47b5-94fc-6ac071cfcc43) | ![image](https://github.com/dfinity/nns-dapp/assets/98811342/afee09b1-5c75-4937-86a3-f0cb12089f2f) |
=> feat: add copy button to the sns proposal proposer id

frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/routes/(app)/(u)/(detail)/+layout.svelte, frontend/src/routes/(login)/+layout.svelte
Reverting layout based fix for missing onDestroy after disbursing sns neuron ([more info](https://github.com/dfinity/nns-dapp/pull/2861))
Revert PR #2865
- apply the workaround from the wallet page to all detail pages.
- set local to global animation flag
Tested manually
=> fix: broken onDestroy on navigation

frontend/src/lib/components/common/PageHeader.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronPageHeader.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeader.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeader.spec.ts, frontend/src/tests/mocks/sns-response.mock.ts, frontend/src/tests/page-objects/SnsNeuronPageHeader.page-object.ts
We are reshuffling the data displayed in the neuron details.
In this PR: Add the new header for the SNS neuron detail page. See screenshot attached.
* New common component `PageHeader` in `common`.
* `NnsNeuronPageHeader` uses new `PageHeader`.
* Implement `SnsNeuronPageHeader` that uses also `PageHeader`.
* Add spec file for `SnsNeuronPageHeader`.
* New page object `SnsNeuronPageHeaderPo`.
Not yet worth a changelog entry.
=> GIX-1683: SnsPageHeader and PageHeader

frontend/src/lib/components/neuron-detail/NnsNeuronVotingPowerSection.svelte, frontend/src/lib/components/neuron-detail/NnsStakeItemAction.svelte, frontend/src/lib/components/neuron-detail/StakeItemAction.svelte, frontend/src/lib/components/neuron-detail/actions/NnsIncreaseStakeButton.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/NnsNeuronDetail.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/neuron-detail/NeuronContextTest.svelte, frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsStakeItemAction.spec.ts, frontend/src/tests/lib/components/neuron-detail/actions/NnsIncreaseStakeButton.spec.ts, frontend/src/tests/page-objects/NnsNeuronVotingPowerSection.page-object.ts, frontend/src/tests/page-objects/NnsStakeItemAction.page-object.ts
We want to shuffle the information displayed in the neuron detail page.
In this PR: Setup the voting power section rendering the stake only. See screenshot.
* Implement `NnsNeuronVotingPowerSection`.
* New component `NnsStakeItemAction`.
* Test the implementation of `NnsNeuronVotingPowerSection`.
* Test the new component `NnsStakeItemAction`.
This is not yet worth an entry in the changelog.
=> GIX-1684: Nns neuron voting power section

frontend/src/lib/api/ckbtc-ledger.api.ts, frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/lib/api/sns-ledger.api.ts, frontend/src/lib/services/ckbtc-accounts.services.ts, frontend/src/tests/lib/api/ckbtc-ledger.api.spec.ts, frontend/src/tests/lib/api/icrc-ledger.api.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts.services.spec.ts
`ckBTCTransfer` is actually already generic and can be used as it to perform any ICRC transfer, which we aim to do for ICP. Therefore this PR moves and rename the function to `icrc-ledger.api.icrcTransfer()`.
=> Refactor ckBTCTransfer moved and renamed to icrcTransfer

frontend/src/lib/api/accounts.api.ts, frontend/src/lib/api/icp-ledger.api.ts, frontend/src/lib/components/accounts/BitcoinAddress.svelte, frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte, frontend/src/lib/pages/NnsWallet.svelte, frontend/src/lib/services/accounts.services.ts, frontend/src/lib/services/ckbtc-minter.services.ts, frontend/src/lib/stores/bitcoin.store.ts, frontend/src/lib/stores/icrc-transactions.store.ts, frontend/src/lib/types/account.ts, frontend/src/lib/types/icrc.ts, frontend/src/lib/worker-services/icrc-transactions.worker-services.ts
This cleanup of the `AccountIdentifierText` type allow us to make a visual difference between `IcpAccountIdentifierText` (current "old" account identifier text representation) and `IcrcAccountIdentifierText` (new Icrc textual representation).
Will be useful for the conversion of ICP to Icrc, it improves readability.
- no functional changes, only types were modified
=> Cleanup account identifier text types

CHANGELOG-Nns-Dapp.md, frontend/package-lock.json, frontend/src/lib/components/neurons/NeuronStateInfo.svelte, frontend/src/lib/constants/layout.constants.ts, frontend/src/lib/utils/neuron.utils.ts
Use the new icons for the change to the new neuron detail page.
* Upgrade gix-components.
* Change two icons for the NeuronState mapper.
* Set the size of the neuron state icon instead of relying on the default.
Only UI changes. No test needed.
=> Chore: Use new neuron state icons

rs/sns_aggregator/src/index.html
More verbose and therefore a bit more heavier but, this review of the JS code of the `index.html` of the aggregator makes it a bit easier to manipulate if we want to add in the future additional information within the list of Snses.
- create element and append those to the DOM instead of parsing HTML (`innerHTML = ...`)
- move the script to the end of the body
- wait for HTML elements to be loaded before starting the script
- add a comment and variable for the root url (useful for local development)
- size of the image through css
- image load set as `lazy`
- `article` instead of `div` to improve semantic
=> feat: aggregator html page js review

frontend/src/lib/components/neuron-detail/NnsNeuronStateItemAction.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronVotingPowerSection.svelte, frontend/src/lib/components/neuron-detail/actions/DissolveActionButton.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronStateItemAction.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/page-objects/NnsNeuronStateItemAction.page-object.ts, frontend/src/tests/page-objects/NnsNeuronVotingPowerSection.page-object.ts
We are shuffling how data is displayed in the neuron detail page.
In this PR: Adds the item that will show the neuron state along with the related actions.
* New component `NnsNeuronStateItemAction`.
* Render new component `NnsNeuronStateItemAction` in `NnsNeuronVotingPowerSection`.
* Add test case in `NnsNeuronVotingPowerSection` that new component is rendered.
* Add spec file for new compoment `NnsNeuronStateItemAction` and related PO.
Not yet worth an entry in the changelog.
=> GIX-1684: New Nns Neuron State Item Action

frontend/src/lib/components/neuron-detail/NnsAvailableMaturityActionItem.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronMaturitySection.svelte, frontend/src/lib/components/neuron-detail/NnsStakedMaturityActionItem.svelte, frontend/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte, frontend/src/lib/components/ui/CommonItemAction.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/neuron-detail/NnsAvailableMaturityActionItem.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronMaturitySection.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsStakedMaturityActionItem.spec.ts, frontend/src/tests/page-objects/NnsAvailableMaturityActionItem.page-object.ts, frontend/src/tests/page-objects/NnsNeuronMaturitySection.page-object.ts, frontend/src/tests/page-objects/NnsStakedMaturityActionItem.page-object.ts
We're shuffling data in the neuron detail page.
In this PR: The item to display the available maturity of a NNS Neuron.
* New component `NnsAvailableMaturityItemAction`.
* Use new component `NnsAvailableMaturityItemAction` in `NnsNeuronMaturitySection`.
* New UI component `CommonItemAction` to share the most common styles used for `ItemActions`.
* Use `CommonItemAction` in `NnsStakedMaturityActionItem` and remove the "Stake Maturity" button. This was an error implemented until now.
* Test new component `NnsAvailableMaturityItemAction` using a PO.
* Add new test case in `NnsNeuronMaturitySection` to check new action item is rendered.
* Remove testing for Stake Maturity button in `NnsStakedMaturityActionItem`
=> GIX-1685: NNS neuron available maturity item action

.github/workflows/build.yml, CHANGELOG-Nns-Dapp.md
End-to-end tests take a lot of time and we are adding more of them.
They are sharded in 2 shards, which can easily be increased but that also duplicates the setup overhead.
Set `runs-on: ubuntu-latest-m` for Playwright e2e jobs on CI.
When I tested with a fast runner on 1 of the 2 shards it ran in 4 minutes while the other took 6 minutes.
=> Fast CI runners for e2e tests

CHANGELOG-Sns_Aggregator.md, rs/sns_aggregator/src/index.html
Apply a design to the landing page of the aggregator and display a GitHub link to NNS dapp repo.
- apply pseudo neo-brutalism / david design
- add a GitHub link to NNS dapp
Current look and feel:
After this PR:
=> Design for the landing page of the aggregator and add github link

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
Restyle proposal summary headers to be more distinguishable.
- custom h1-h2, size to be between normal and component header
- h3-h6 to be bold
| <img width="708" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/5dd2c492-f0d9-4206-a4db-142da980056d"> | <img width="708" alt="Screenshot 2023-07-18 at 10 25 20" src="https://github.com/dfinity/nns-dapp/assets/98811342/11c9abe0-b76d-4f77-bef1-0a1e98eb87a1"> |
=> style: proposal summary header styles

frontend/src/lib/components/neuron-detail/NnsNeuronStateItemAction.svelte
Avoid style duplications in two components.
* Use CommonItemAction in NnsNeuronStateItemAction.
* Only refactor, no new tests nor functionality needed.
=> GIX-1684: Refactor to use CommonItemAction

frontend/src/lib/services/accounts.services.ts, frontend/src/lib/stores/icp-accounts.store.ts, frontend/src/tests/lib/stores/icp-accounts.store.spec.ts
Renaming function was missing in #2897
- rename `getSingleMutationAccountsStore` to `getSingleMutationIcpAccountsStore`
=> Rename getSingleMutationAccountsStore to getSingleMutationIcpAccountsStore

frontend/src/lib/services/dev.services.ts, frontend/src/tests/e2e/disburse.spec.ts, frontend/src/tests/e2e/merge-neurons.spec.ts, frontend/src/tests/e2e/neurons.spec.ts, frontend/src/tests/e2e/sns-participation.spec.ts
When getting tokens for testing, a main account needs to be already loaded or you get an error.
End-to-end tests are fast enough to be burned by this so many of them need to explicitly wait for the main account to appear before trying to get tokens.
In the `getICPs` function, wait for the main account to be loaded if it isn't already.
Tests still pass even though they no longer wait for the main account to be present.
Not note worthy (?)
=> Wait for the main account when getting test tokens

frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityActionItem.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.svelte, frontend/src/lib/components/sns-neuron-detail/SnsStakedMaturityActionItem.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsStakeMaturityButton.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsAvailableMaturityActionItem.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsStakedMaturityActionItem.spec.ts, frontend/src/tests/page-objects/SnsAvailableMaturityActionItem.page-object.ts, frontend/src/tests/page-objects/SnsNeuronMaturitySection.page-object.ts, frontend/src/tests/page-objects/SnsStakedMaturityActionItem.page-object.ts
We are shuffling some data in the neuron details to make it more user friendly.
In this PR: Create the component that will show the maturity section for SNS neurons.
* New component SnsAvailableMaturityActionItem.
* New component SnsStakedMaturityActionItem.
* Implement SnsNeuronMaturitySection using both previous components.
* Add variant prop to SnsStakeMaturityButton.
* New test SnsAvailableMaturityActionItem with PO.
* New test SnsStakedMaturityActionItem with PO.
* New test SnsNeuronMaturitySection with PO.
Not worth entry in the changelog yet.
=> GIX-1685: SnsNeuronMaturitySection and related

CHANGELOG-Nns-Dapp.md, frontend/package.json, frontend/src/tests/page-objects/NnsNeuronsFooter.page-object.ts, frontend/src/tests/page-objects/NnsStakeNeuronModal.page-object.ts, frontend/src/tests/page-objects/playwright.page-object.ts
Currently, type errors in e2e tests are not caught.
1. Compile e2e test before running them when using `npm test-e2e`.
2. Fix existing type errors.
test only
=> E2E: Compile tests (with --noEmit) to catch type errors

CHANGELOG-Sns_Aggregator.md, rs/sns_aggregator/src/index.html
The dashboard used to not display the status of the swap and some used the opportunity to took screenshots of the Snses to claim they were active. By displaying the status, we prevent the same thing to happen with the landing page of the aggregator.
- display swap status on aggregator landing page
=> Display swaps lifecycle on aggregator landing page

frontend/src/lib/utils/accounts.utils.ts, frontend/src/tests/lib/utils/accounts.utils.spec.ts
When ICP will use Icrc, we will need to get the ICP identifier from an Icrc textual representation to query NNS dapp backend. This PR introduces a utils that tries such conversion and fallback to ICP.
- new utils function `toIcpAccountIdentifier` that tries to either map an ICRC textual account identifier or fallback to value provided
=> feat: utils to try to convert an Icrc account identifier to Icp

frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeading.spec.ts, frontend/src/tests/page-objects/SnsNeuronPageHeading.page-object.ts
The voting power was incorrect in the new SNS neuron page heading.
* Use util to formatVotingPower in the SnsPageHeading
* Add a test to check the value of the voting power in the SnsPageHeading.
=> Fix: Sns Voting Power in PageHeading

CHANGELOG-Nns-Dapp.md, frontend/src/lib/i18n/en.json, frontend/src/lib/services/icp-accounts.services.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/accounts.utils.ts, frontend/src/tests/lib/components/accounts/AddressInput.spec.ts, frontend/src/tests/lib/services/icp-accounts.services.spec.ts, frontend/src/tests/lib/utils/accounts.utils.spec.ts
Support for ICP transactions with Icrc addresses as the destination.
- extend `transferICP` to either use existing `sendICP` or if destination address is an Icrc address `icrcTransfer`
- extend `invalidAddress` to accept Icrc for Nns, that way user can enter an Icrc address in the input field of the transaction modal
=> ICP transfer with Icrc addresses as destination

rs/backend/nns-dapp.did
The nns-dapp .did file does not match the rust code.
* Update the names and types of the memory sizes returned by `get_stats`.
Running `get_stats()` on the app subnet deployment now returns values, for the memory size, not null.
Note: The sns aggregator has tests that the .did file matches the rust code, obtained by getting the dynamically generated .did file.  However if I recall correctly, the nns-dapp libraries need to be updated before we can do the same here.  It is planned, and that would provide blanket coverage of issues like this.
- Covered by the existing changelog entry to add these stats.
=> Fix types declared in .did

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neuron-detail/actions/IncreaseDissolveDelayButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.svelte, frontend/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte, frontend/src/lib/modals/sns/neurons/IncreaseSnsDissolveDelayModal.svelte, frontend/src/tests/lib/components/neuron-detail/actions/IncreaseDissolveDelayButton.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.spec.ts
Improve the text in the "Increase Dissolve Delay" button. If neuron is unlocked, there is no dissolve delay to increase. Instead, the user sets the dissolve delay.
* Check the state and render a different text in `IncreaseDissolveDelayButton`.
* Check the state and render a different text in `IncreaseSnsDissolveDelayButton`.
* Add missing test file for component `IncreaseDissolveDelayButton`.
* Add missing test file for component `IncreaseSnsDissolveDelayButton`.
=> Feat: Improve Increase Dissolve Delay buttons

frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
`SnsNeuronDetail.spec.ts` has 2 identical test:
* "when project is an invalid canister id"
* "when neuron is not found"
Both use an invalid universe ID but the second one was supposed to use a valid universe ID but a neuron ID for a neuron that can't be found.
In "when neuron is not found":
1. Use a correct `universe`.
2. Use an unknown neuron ID.
3. Expect `snsGovernanceApi.getSnsNeuron` to have been called twice (query + update).
In "when project is an invalid canister id", expect `snsGovernanceApi.getSnsNeuron` not to have been called to distinguish it from the other test as both tests expect a redirect to the neurons overview page.
yes
no
=> Fix SnsNeuronDetail.spec.ts

frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte, frontend/src/lib/components/sns-neuron-detail/SnsStakeItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsIncreaseStakeButton.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsStakeItemAction.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/SnsNeuronVotingPowerSection.page-object.ts, frontend/src/tests/page-objects/SnsStakeItemAction.page-object.ts
We are reshuffling the data in the neuron detail page.
In this PR: Setup voting power section for sns neuron detail page
* Implement SnsNeuronVotingPowerSection.
* New component SnsStakeItemAction.
* Add "variant" prop to SnsIncreaseStakeButton.
* Add Separator between Maturity and Voting Power sections in SnsNeutonDetail.
* Test file and PO for SnsNeuronVotingPowerSection.
* Test file and PO for SnsStakeItemAction
Not yet worth an entry.
=> GIX-1684: SnsNeuronVotingPowerSection

frontend/src/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.spec.ts, frontend/src/tests/mocks/sns-neurons.mock.ts, frontend/src/tests/page-objects/SnsNeuronAdvancedSection.page-object.ts
We are reshuffling data around in the neuron details page.
In this PR: First part of the advanced section for SNS neuron details page.
* Implement SnsNeuronAdvancedSection.
* Pass necessary props from SnsNeuronDetail.
* Add Separator between Maturity and Advanced sections.
* Test file and PO for SnsNeuronAdvancedSection.
Not yet worth an entry in the changelog.
=> GIX-1686: SnsNeuronAdvancedSection Part 1

frontend/src/lib/components/sns-neuron-detail/SnsNeuronStateItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronStateItemAction.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/page-objects/SnsNeuronStateItemAction.page-object.ts, frontend/src/tests/page-objects/SnsNeuronVotingPowerSection.page-object.ts
We are reshuffling the data in the neuron details page.
In this PR: the item that has the information and actions about the SNS neuron state.
* New component SnsNeuronStateItemAction.
* Use new component in SnsNeuronVotingPowerSection.
* Test that new component is present in SnsNeuronVotingPowerSection.
* New test file and PO for SnsNeuronStateItemAction.
=> GIX-1684: SnsNeuronStateItemAction

CHANGELOG-Nns-Dapp.md, frontend/src/tests/fakes/sns-governance-api.fake.ts, frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts, frontend/src/tests/page-objects/SnsNeuronHotkeysCard.page-object.ts
There is a race condition with query and update calls when adding/removing SNS neuron hotkeys.
I want to use `queuedStore` to fix the race condition for which I will want to add unit test coverage.
Currently there is no unit test coverage in `SnsNeuronDetail.spec.ts` for adding/removing hotkeys.
So before fixing the race condition I want to improve the existing test coverage so it's easier to test the fix later.
1. Support adding/removing SNS neuron permissions in `frontend/src/tests/fakes/sns-governance-api.fake.ts`.
2. In `frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts` test adding and removing hotkeys and also not having permission to add hotkeys.
yes
=> Test SNS hotkey management

frontend/src/tests/page-objects/CanisterDetail.page-object.ts, frontend/src/tests/page-objects/ConfirmDissolveDelay.page-object.ts, frontend/src/tests/page-objects/NnsAccountsFooter.page-object.ts, frontend/src/tests/page-objects/NnsNeuronsFooter.page-object.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts, frontend/src/tests/page-objects/SnsNeuronMetaInfoCard.page-object.ts, frontend/src/tests/page-objects/SnsNeuronsFooter.page-object.ts, frontend/src/tests/page-objects/TextInputForm.page-object.ts, frontend/src/tests/page-objects/VotingCard.page-object.ts
There is a convenience method `getButton(testId: string)` in `BasePageObject` but it's not used in many places where it could be used.
Replace `return ButtonPo.under({ element: this.root, testId});` with `return this.getButton(testId)`.
test-only
not worth mentioning?
=> Cleanup: Use this.getButton() in page objects

rs/sns_aggregator/src/index.html
When we deploy the Sns aggregator its landing page is not able to fetch the list of projects anynmore.
This is an issue of the refactoring of the root URL developed in PR #2896.
- shorten root url and move prefix `/v1/sns/` to effective fetch
=> Fix Sns aggregator root url to fetch projects

frontend/src/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.spec.ts, frontend/src/tests/page-objects/SnsNeuronAdvancedSection.page-object.ts
We are shuffling the data in the neuron detail to make it more user friendly.
In this PR: Add the action items in the sns neuron advanced section.
* Render the auto stake maturity and split button in the SnsNeuronAdvancedSection.
* Add test to check that actions are present.
Not yet worth an entry in the changelog.
=> GIX-1686: SnsNeuronAdvancedSection actions

frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayActionItem.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte, frontend/src/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayActionItem.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.spec.ts, frontend/src/tests/page-objects/Button.page-object.ts, frontend/src/tests/page-objects/SnsNeuronDissolveDelayActionItem.page-object.ts, frontend/src/tests/page-objects/SnsNeuronVotingPowerSection.page-object.ts
We are shuffling data in the neuron details to make it more user friendly.
In this PR: Render the information about the dissolve delay in the sns neuron detail.
* New component SnsNeuronDissolveDelayActionItem.
* Use new component in SnsNeuronVotingPowerSection.
* Add new prop "variant" to IncreaseSnsDissolveDelayButton.
* New test file and PO for new component SnsNeuronDissolveDelayActionItem.
* Test that new action is rendered in SnsNeuronVotingPowerSection.
Not yet worth an entry in the changelog.
=> GIX-1684: SnsNeuronDissolveDelayActionItem

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neuron-detail/NeuronJoinFundCard.svelte, frontend/src/lib/pages/NnsNeuronDetail.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts, frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts, frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
We are shuffling data in the neuron details page.
In this PR: The feature flag flips between the old and new UI.
* Add the old cards of NnsNeuronDetails inside the "else" statement of the ENABLE_NEURON_SETTINGS
* Add the old cards of SnsNeuronDetails inside the "else" statement of the ENABLE_NEURON_SETTINGS
* Increase spacing between sections to adapt to old design. There is a task to fix that onece we are fully in the new design.
* Test new sections are rendered in NnsNeuronDetails and SnsNeuronDetails. Add getters to the POs.
=> GIX-1745: Neuron Settings Feature Flags flips between old and new UI

frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronStateItemAction.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPower.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerExplanation.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/mocks/sns-neurons.mock.ts
Rename the parameter `ageSinceSeconds` of `createMockSnsNeuron` due to misunderstanding that it's a timestamp, not a duration.
* Rename parameter `ageSinceSeconds` to `ageSinceTimestampSeconds` in `createMockSnsNeuron`.
Only rename, no new tests.
=> Chore: Rename ageSinceSeconds parameter

frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.spec.ts
Refactor the SnsNeuronMaturitySection to expect the neuron as prop instead of reading the context.
* Add prop `neuron` in SnsNeuronMaturitySection.
* Pass the neuron as prop.
=> Chore: Refactor SnsNeuronMaturitySection to have neuron prop

.github/workflows/deploy-to-app.yaml, CHANGELOG-Sns_Aggregator.md
When deploying to the app subnet often, it is easy to forget what version was last deployed.
* Prominently display which canisters were deployed with which mode with which branch or tag and commit.
* See a workflow run; note the body of the workflow was disabled, so the canister commits are "none".  This is expected.  https://github.com/dfinity/nns-dapp/actions/runs/5647370743
=> tweak: Show app subnet deployment ref

frontend/src/tests/fakes/governance-api.fake.ts, frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts, frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/NnsNeuronPageHeader.page-object.ts
We are shuffling data in the neuron details page to make it more user friendly.
In this PR: Add same tests for neuron detail when new UI is enabled.
In another PR: There are two pending tests that need logic in the component and will be done in another task: https://dfinity.atlassian.net/browse/GIX-1764
* Add the same test cases in NnsNeuronDetail for old UI in the new UI.
* Add some methods in NnsNeuronDetailPo and NnsNeuronPageHeaderPo.
Not worth a specific changelog entry.
=> GIX-1745: Test NnsNeuronDetail with new UI

CHANGELOG-Sns_Aggregator.md, rs/sns_aggregator/src/assets.rs, rs/sns_aggregator/src/index.html
The sns aggregator index.html is not updating.  This is because the index.html is saved with stable memory and not replaced if present.
* Always replace the index.html when requested to install the index.html, rather than checking whether it is already there.
* Ditto for the favicon.
* Deployed this PR to the app subnet, then again with a different HTML content, then again with the original HTML content.  In every case the displayed HTML after deployment was correct.
=> fix: Always update the index.html

frontend/src/lib/components/neuron-detail/NnsAvailableMaturityActionItem.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronDissolveDelayActionItem.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronStateItemAction.svelte, frontend/src/lib/components/neuron-detail/actions/JoinCommunityFundCheckbox.svelte, frontend/src/tests/lib/components/neuron-detail/NeuronContextActionsTest.svelte, frontend/src/tests/lib/components/neuron-detail/NnsAvailableMaturityActionItem.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronDissolveDelayActionItem.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronStateItemAction.spec.ts, frontend/src/tests/lib/components/neuron-detail/actions/JoinCommunityFundCheckbox.spec.ts, frontend/src/tests/page-objects/NnsNeuronAdvancedSection.page-object.ts, frontend/src/tests/page-objects/NnsNeuronStateItemAction.page-object.ts
Some neuron actions are available only for controllers.
In this PR: Apply same rules to show/hide neuron buttons in new NNS neuron detail.
Except one difference. The Join Neuron's fund is rendered but disabled if neuron is not controlled by user. This is similar to what we do for the auto stake checkbox. Currently, the whole card of Neurons' Fund doesn't appear if neuron is not controlled by the user.
* Hide actions if user not controller in NnsAvailableMaturityActionItem.
* Hide split button and disable join neurons' fund checkbox if user not controller in NnsNeuronAdvancedSection.
* Hide actions if user not controller in NnsNeuronDissolveDelayActionItem.
* Hide actions if user not controller in NnsNeuronStateItemAction.
* Add `disabled` prop to JoinCommunityFundCheckbox
* Test that …
=> GIX-1765: Manage permissions in NNS neuron buttons

CHANGELOG-Nns-Dapp.md, frontend/src/lib/i18n/en.json
With the pervious error message I was confused because I thought I had to upgrade the Ledger firmware but the version didn't match. So I thought the error message could be clearer.
Change the error message to mention "Internet Computer app on your Ledger device".
Temporarily increase the required version to manually test the error message:
=> Improve Ledger app version error message

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/layout/LayoutNavGuard.svelte, frontend/src/routes/(app)/(u)/(detail)/neuron/+layout.svelte, frontend/src/routes/(app)/(u)/(detail)/proposal/+layout.svelte, frontend/src/routes/(app)/(u)/(detail)/wallet/+layout.svelte, frontend/src/routes/(login)/+layout.svelte
Implementing the workaround for `onDestroy` at the top level of the `+layout` of the detail pages (PR #2880) had for side effect to make the navigation callbacks of its pages/layouts to not being called. As those are not called, the dapp is not able to determine which was the `referrer` of these pages and per extension, to effectivelly use the referrer in back action.
Long story short, on mainnet, navigation from the "Launchpad" to a "Proposal" and clicking back lead the users to "Proposals" page instead of going back to "Launchpad".
- refactor workaround in a dedicated component `LayoutNavGuard`
- use component within the layouts
- remove top layout as unused
I noticed a type in the CHANGELOG and since I was already there, I also improved the communication of the fix #2950 which is not …
=> Proposal detail page back referrer

frontend/src/lib/components/proposals/ProposalCard.svelte, frontend/src/lib/constants/proposals.constants.ts, frontend/src/tests/e2e/neurons.spec.ts, frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/NnsNeuronMetaInfoCard.page-object.ts, frontend/src/tests/page-objects/NnsProposalList.page-object.ts, frontend/src/tests/page-objects/ProposalCard.page-object.ts, frontend/src/tests/utils/e2e.nns-proposals.test-utils.ts
End-to-end tests run in parallel against the same environment.
Proposals or global objects and so proposals created in one test can be seen by proposals created in another test.
This causes flakiness when a proposal gets more votes than expected because another test is voting for it at the same time.
This is likely to happen because we run the same test with Chrome and Firefox, potentially at the same time.
1. In `frontend/src/tests/e2e/neurons.spec.ts` record the proposer ID and then choose a proposal with that proposer to vote on. This makes sure that different tests vote on different proposals.
2. In `createDummyProposal` return the neuron ID used to create the dummy proposals.
3. Page object changes.
I was able to reliably reproduce the issue by adding a delay after creating the …
=> E2E flakiness: Don't vote on proposal created by a different test

scripts/docker-build
In docker builds, changing the target is a way of building a subset of resources and is useful when iterating fast in development.  A flag was added in bc8d3cf8d0278132d0360f62acbee64e8836543d to allow setting the target without editing `docker-build.sh` but unfortunately the flag was not passed through.
- Pass the `--target` flag value through to docker.
- Running docker build with `--target configurator` now tests the build configuration.
Note that as this target is not a scratch image, it outputs an entire OS image.  To do this well, the build also needs to set output to none, caching only, or to define more scratch targets.  Once that is done it might make sense to test this in CI.  As it is, it is useful to tell, quickly, whether a step succeeds or fails but not more than that.
- I …
=> fix: Pass the target

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/downgrade-upgrade-test, scripts/propose-to/propose-to-upgrade-nns-dapp, scripts/sns/aggregator/downgrade-upgrade-test
`docker-build` now specifies the network by means of a flag.  Some code still passes it as a command line argument, which happens to work if the relevant arguments have already been computed before but not otherwise.  This should be fixed.
- Use the `--network` flag instead of an environment variable, whenever `docker-build` is called.
- See CI
=> fix: Use docker-build --network flag

frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityActionItem.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayActionItem.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronStateItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/SnsStakeItemAction.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsAvailableMaturityActionItem.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayActionItem.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronStateItemAction.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsStakeItemAction.spec.ts, frontend/src/tests/mocks/sns-neurons.mock.ts, frontend/src/tests/page-objects/SnsNeuronStateItemAction.page-object.ts
Use SNS neuron permissions to hide buttons for users without permission for the action.
* Hide / show stake neuron button in SnsAvailableMaturityActionItem.
* Hide / show split neuron button in SnsNeuronAdvancedSection.
* Hide / show increase dissolve delay button in SnsNeuronDissolveDelayActionItem.
* Hide / show disburse or start/stop dissolve button in SnsNeuronStateItemAction.
* Hide / show increase stake button in SnsStakeItemAction. This is not related to permissions, but to avoid the users from doing something unexpected.
* Check stake neuron button in SnsAvailableMaturityActionItem.
* Check split neuron button in SnsNeuronAdvancedSection.
* Check increase dissolve delay button in SnsNeuronDissolveDelayActionItem.
* Check disburse or start/stop dissolve button in …
=> GIX-1766: Add permissions SNS neuron buttons

CHANGELOG-Nns-Dapp.md, build-backend.sh, deploy.sh, scripts/nns-dapp/test-exports
Fix the convenient script to deploy current nns dapp branch to a testnet `./deploy.sh`.
PENDING: Fix `scripts/nns-dapp/test-exports` for Mac.
* Do not use `dfx deploy` which isn't working and instead, build the wasm and then install it.
I deployed to nnsdapp testnet https://vh6yy-miaaa-aaaaa-aaaya-cai.nnsdapp.testnet.dfinity.network/
=> Fix: deploy script

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/ic/GetTokens.svelte, frontend/src/tests/e2e/accounts.spec.ts, frontend/src/tests/e2e/disburse.spec.ts, frontend/src/tests/e2e/merge-neurons.spec.ts, frontend/src/tests/e2e/neurons.spec.ts, frontend/src/tests/e2e/sns-governance.spec.ts, frontend/src/tests/e2e/sns-participation.spec.ts, frontend/src/tests/page-objects/App.page-object.ts, frontend/src/tests/page-objects/GetTokens.page-object.ts
We want trustworthy e2e tests.
In this PR: Fix a flakyness in the E2E test sns-governance when getting the SNS tokens.
* Change test id for the get tokens button. It relies now on the token symbol. This way we can wait for it in playwright.
* Getting tokens methods expect a new argument "token" to get the button.
* Use the new parameter in the sns-governance e2e test.
=> Fix: SNS Governance E2E flakyness

frontend/src/tests/e2e/neurons.spec.ts
Move e2e tests to the new neuron details UI.
In this PR: Move the neurons.spec.ts e2e test to new neuron details UI.
* Set feature flag `ENABLE_NEURON_SETTINGS` to true in e2e test neurons.spec and make it pass.
=> GIX-1745: Neurons e2e test uses new neurons UI

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/estimate-upgrade-cycles
Now that the state is large and _should_ be prod-like, the upgrade cycle count estimate is now very wrong.
Instead we give just the upgrade cycle count and compare the size of the mainnet and test states.  This way a reader has access to the key data and can see how realistic the cycle estimate is.
* Remove projected cycle counts, leaving just the actual counts.
* Add a state size table, comparing the local testnet with mainnet.
* Truncate floats; three decimal places can make the decimal separator look like a thousands separator.  One decimal place is probably enough.
* Run in CI: https://github.com/dfinity/nns-dapp/actions/runs/5680844725#summary-15395895036
* Run locally:
```
$ scripts/nns-dapp/estimate-upgrade-cycles 2>/dev/null
| Name …
```
=> Update cycle count estimates

frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronVotingPowerSection.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeading.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts
Communicate better when a neuron can't vote.
In this PR: Improve the subtitle of the new neuron details page when neuron has no voting right and also the value in the voting power section.
* Check whether neuron can vote and show a related message in NnsNeuronPageHeader and SnsNeuronPageHeading.
* Check whether neuron can vote and show a related text in NnsNeuronVotingPowerSection and SnsNeuronVotingPowerSection.
* Test new cases in the page heading subtitle.
* Test new cases in the voting power section.
Covered by changelog entry related to new neuron details UI.
=> GIX-1777: Communicate when No Voting Power

frontend/src/lib/components/layout/LayoutNavGuard.svelte, frontend/src/routes/(login)/+layout.svelte
Refactoring the navigation spinner in #2962 within the component that prevents SvelteKit issue [#5434](https://github.com/sveltejs/kit/issues/5434) actually also lead to the same issue of duplicating the `split-pane` in the DOM. Therefore we have to undo the refactor and keep the spinner within the `+layout` of the sign-in page.
- Open the wallet (e.g. of the main account)
- Make a transaction
- Click the back button
- Where the menu button should now reappear, there is only a non-functional back button
- revert moving spinner from login layout to navigation guard
- remove spinner from nav component
- redo spinner in +layout of login (same code as on mainnet)
=> Fix back to accounts after transaction in wallet page

frontend/src/lib/components/common/HeadingTag.svelte, frontend/src/lib/components/common/PageHeading.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte, frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeading.spec.ts, frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts, frontend/src/tests/page-objects/SnsNeuronPageHeading.page-object.ts
Identify hotkey neurons and those belonging to Neurons' Fund.
This is already a feature in the current neuron details page. In this PR, it adds the same functionality in the new neuron details page.
* New UI component HeadingTag.
* Use new HeadingTag in NnsNeuronPageHeading to render a tag when neuron is part of Neurons' Fund or the user is a hotkey.
* Use new HeadingTag in SnsNeuronPageHeading to render a tag when the user is a hotkey of the neuron.
* Test new functionality in NnsNeuronPageHeading and SnsNeuronPageHeading.
Covered already by an entry in the changelog.
=> GIX-1777: Hotkey and NF's tags

frontend/src/lib/api/dev.api.ts
We have a "Get ICP" feature we used for development purpose which does not transfer ICP anymore if the `ENABLE_ICP_ICRC` flag is activated.
This PR checks if the transfer destination address is an Icrc address and if so, uses the Icrc ledger definition to proceed.
=> Get development ICP with Icrc accounts

.github/workflows/reproducible-assets.yaml, CHANGELOG-Nns-Dapp.md, build-frontend.sh
The reproducible assets test is getting a different hash on Mac OS 13.
The full WASM build is already only reproducible on Linux, which is why we run it in Docker.
Don't run reproducible assets against Mac OS 13
CI
=> Don't run reproducible assets against Mac OS 13

frontend/src/lib/components/header/Title.svelte, frontend/src/tests/lib/components/header/Title.spec.ts
Follow best practice and invert tab titles. e.g. instead of `NNS Dapp / My Tokens` render `My Tokens / NNS Dapp`.
=> Invert tab title

frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts, frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/NnsNeuronMetaInfoCard.page-object.ts
"Po" already stands for "page object".
"PageObjectPo" is redundant.
Rename `NnsNeuronMetaInfoCardPageObjectPo` to `NnsNeuronMetaInfoCardPo`.
Still pass.
not worth it
=> Rename NnsNeuronMetaInfoCardPageObjectPo to NnsNeuronMetaInfoCardPo

frontend/src/lib/components/proposals/FiltersWrapper.svelte
I guess the filters used to be aligned but, following the introduction of the Sns universes those aren't aligned gracefuly with the overall content.
- align filters with top of the universe
Is:
Afterwards:
=> Fix proposals filters style alignment

.github/workflows/reproducible-assets.yaml, build-frontend.sh
Our reproducible assets test started failing recently because we got different hashes on MacOS 13.
It turns out that gnu-tar 1.35 creates different binary files than 1.34 (confirmed with [this run](https://github.com/dfinity/nns-dapp/actions/runs/5738350606/job/15551756916)).
Looking at the binary, there are some 0x30 bytes (character '0') that became 0x00 bytes, so my guess that this is caused by the change
> Leave the devmajor and devminor fields empty (rather than zero) for non-special files, as this is more compatible with traditional tar.
listed [here](https://www.gnu.org/software/tar/).
We are currently using `--format=ustar`. The only reason I used `ustar` in [this PR](https://github.com/dfinity/nns-dapp/pull/1766) is that it is listed …
=> Use tar format gnu instead of ustar for frontend assets

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/proposal-detail/NnsProposal.svelte, frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
Currently the proposal navigation uses all type proposals (based on selected filters), so even not related to the launchpad proposals are in the list. The quick workaround is to not display proposal navigation block in this case.
- remove navigation when navigated from the /launchpad
- "should not render proposal navigation when on launchpad"
=> Hide proposal navigation when on launchpad

.github/workflows/aggregator.yaml, .github/workflows/docker-build.yaml, .github/workflows/e2e-testnet.yml, .github/workflows/security-audit.yaml, .github/workflows/selenium.yml, .github/workflows/testnet.yml, CHANGELOG-Nns-Dapp.md
The GitHub Actions tab still lists workflows that we've already deleted:
This makes it harder than necessary to find a workflow you're looking for.
Since the workflows are listed alphabetically I want to rename the deleted workflows to something starting with "ZZZ" so that the ones we still use appear at the top and don't require clicking "Show more workflows..."
Recreate the deleted workflow files and give the workflows a name starting with "ZZZ".
I plan to delete these files again as soon as the workflows have been renamed on GitHub.
no
=> Rename deleted workflows

CHANGELOG-Nns-Dapp.md, frontend/src/lib/services/$public/app.services.ts, frontend/src/lib/services/$public/sns.services.ts, frontend/src/tests/lib/services/_public/app.services.spec.ts, frontend/src/tests/lib/services/_public/sns.services.spec.ts
Clean up unused code and fail early.
* Remove `loadSnsSummaries` service.
* `loadSnsProjects` does not fallback to `loadSnsSummaries`. Instead, it shows a toast error. Which was the error management of the fallback `loadSnsSummaries`.
* Clean up some unnecessary code in the related services.
=> Chore: Remove SNS aggregator fallback

CHANGELOG-Nns-Dapp.md, frontend/src/lib/api/sns-aggregator.api.ts, frontend/src/tests/lib/api/sns-aggregator.api.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts
There were some inconsistencies in the types of SNS Aggregator. These were discovered when adding a test that checked the converter.
* New types from aggregator: `CachedFunctionTypeDto` and `GenericNervousSystemFunctionDto`.
* Fix some type errors.
* Expose the converter and some type to be able to use them outside.
* Add a test that converter transforms the JSON data into the expected type.
=> Refactor: Fix type issues sns aggregator

CHANGELOG-Nns-Dapp.md, frontend/src/lib/api/sns-aggregator.api.ts, frontend/src/tests/lib/api/sns-aggregator.api.spec.ts
Bug in current mainnet. The NNS Dapp sees that the first SNS aggregator page is full; therefore, it tries to get the second page. Yet, the second page fails, and the whole process of getting the info from the aggregator fails and uses the fallback.
In this PR: Ignore errors for pages higher than 0.
* Ignore errors for pages higher than 0 in `querySnsAggregator` helper.
* I added first a test, it failed, and then I implemented the solution.
=> Fix: SNS Aggregator page 2 doesn't exist

frontend/src/lib/api/sns-aggregator.api.ts, frontend/src/lib/services/$public/sns.services.ts, frontend/src/tests/fakes/sns-aggregator-api.fake.ts, frontend/src/tests/lib/api/sns-aggregator.api.spec.ts, frontend/src/tests/lib/services/_public/sns.services.spec.ts, frontend/src/tests/lib/services/app.services.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts
Add aggregator data in a Svelte store.
In this PR: Move the conversion of the aggregator data to the sns service `loadSnsProjects` before loading the stores.
* Remove conversion of data in sns aggregator api.
* Use `convertDtoData` in `loadSnsProjects` before loading the data in the Svelte stores.
* Change the test in sns aggregator api that checked the conversion.
This is a refactor. Not worth an entry.
=> Refactor: SNS Aggregator API doesn't convert data

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/release-template
When we create a proposal, we need to do some manual copy/paste/editing to add in the change log section.
This is mechanical so can be automated.
1. In `scripts/nns-dapp/release-template` populate the change log section from the "Application" part of the unreleased changes in `CHANGELOG-Nns-Dapp.md`.
2. Output at the end which files were created, for convenience.
Ran the script manually. It created this output:
````
Wasm sha256 hash: `25d0749441efd9c03baee2a52cf491f0ec73d3c671f0de0dae5a09653d6836fb` (`https://github.com/dfinity/nns-dapp/actions/runs/5739002244`)
* Enable merge neurons preview.
* Display page title in browser's tab.
* Refactor storage to prepare for schema migration.
* Enhance user experience by rendering hyperlinks for the cards displayed on the Accounts, Neurons, …
```
=> Populate the change log in scripts/nns-dapp/release-template

CHANGELOG-Nns-Dapp.md, frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/services/sns-swap-metrics.services.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts
Remove unnecessary code in Project Detail page.
All new SNSes will have the field of number of buyers in the derived state. There is no need to rely on the swap raw metrics.
* Do not call `loadSnsSwapMetrics` after participation.
* Remove `watchSnsMetrics` because all new SNSes support the count in derived state.
* Fix tests after changes.
=> Fix: Remove unnecessary code ProjectDetail

.github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md, scripts/past-changelog-test, scripts/past-changelog-test.test
We have a test `past-changelog-test` to make sure no change log entries are added in existing releases.
But the way it compared line numbers, using `[[ "$x" > "$y" ]]` seems to be doing string comparison instead of number comparison.
Using `(( ))` instead o `[[ ]]` does number comparison instead.
1. Fix `past-changelog-test` to do proper number comparison.
2. Add a test for the test.
3. Add the test to the GitHub workflow.
Added
=> Fix past-changelog-test line number comparison

scripts/past-changelog-test.test
I recently added a test for `past-changelog-test` in https://github.com/dfinity/nns-dapp/pull/3046
but it fails when a PR adds a new release because in that case adding new changes in the newly created release is allowed.
`past-changelog-test` handles this correctly but `past-changelog-test.test` doesn't.
1. In `past-changelog-test.test` when making a change below the first `## Proposal` heading in order to expect it to fail, make sure the change happens below the first `## Proposal` heading that exists in `origin/main` and not the first heading in the current commit if it adds a new `## Proposal` heading.
2. Add one more test to make sure that a new `## Proposal` heading with changes below it is allowed.
test only
Covered because it should have been done correctly in the previous PR.
=> Allow new releases in scripts/past-changelog-test.test

frontend/src/tests/lib/services/neurons.services.spec.ts, frontend/src/tests/mocks/icp-accounts.store.mock.ts
Mock of the HW account has the same principal as the mockIdentity. This is not possible and it's better to avoid having it as default mock.
* Change the principal in the `mockHardwareWalletAccount`.
* Fix broken test after change.
Not worth an entry in the changelog.
=> Chore: Fix mock HW account principal

frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte, frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts
Bug: Current functionality doesn't show the Neurons' Fund checkbox if user can't control it. There is already the tag to show that the user is part of the Neurons' Fund for informational purposes.
* Do not render the Neurons' Fund in NnsNeuronAdvancedSection instead of disabled if user is not the controller.
* Edit tests after change in functionality.
Not worth an entry. This is part of the unpublished new neuron details.
=> GIX-1751: Hide neurons fund in advanced section

frontend/src/lib/services/$public/sns.services.ts, frontend/src/lib/stores/sns-aggregator.store.ts, frontend/src/tests/lib/services/_public/sns.services.spec.ts, frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts
Stop using deprecated get_state data.
In this PR: Store the aggregator data in its own store.
Then this data will be used in derived store `snsSummariesStore` so that we can use the new endpoints that the aggregator already collects.
* New store: snsAggregatorStore.
* Load store in sns service `loadSnsProjects`.
* Test new store.
* Test that service loads data in the store.
=> Feat: SNS Aggregator Store

CHANGELOG-Nns-Dapp.md, scripts/past-changelog-test
`scripts/past-changelog-test` has been flaky recently, occasionally failing with exit code 141.
I believe the issue is that `grep -m 1` stops reading input as soon as it finds a match and then the process before the pipe fails because it can no longer write to the pipe.
I'm not sure why this happens only sometimes.
Some references:
https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q
https://unix.stackexchange.com/questions/582844/how-to-suppress-sigpipe-in-bash
When the line with `grep -m 1` fails, ignore it if it failed with exit code 141.
Difficult to test because I couldn't reproduce the issue (well, only once) in this script.
But it reproduces quite well with `yes | head -1` so I did some manual tests with that.
=> Ignore SIGPIPE in past-changelog-test

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/canisters/SelectCyclesCanister.svelte, frontend/src/lib/utils/canisters.utils.ts, frontend/src/tests/lib/components/canisters/SelectCyclesCanister.spec.ts, frontend/src/tests/lib/utils/canisters.utils.spec.ts
When topping up a canister, on mainnet and locally, the "Review Cycles Purchase" is not disabled per default, therefore user can submit it without entering any amount which lead the wizard to an empty step.
- if no minimal amount, request at least an amount to be entered
=> Fix disabled review cycles submit button

CHANGELOG-Nns-Dapp.md, frontend/src/lib/identities/ledger.identity.ts, frontend/src/lib/services/icp-ledger.services.ts, frontend/src/lib/utils/ledger.utils.ts, frontend/src/lib/utils/utils.ts, frontend/src/tests/lib/identities/ledger.identity.spec.ts, frontend/src/tests/lib/utils/utils.spec.ts
Improve the UX of HW users.
In this PR: Users are required to confirm the transactions only ONCE with the device. Not twice as until now.
In a nutshell, the read_state call is signed at the same time than the other request. This is possible because the request id is deterministic of the request and can be calculated before hand. We cache the read_state signature so that we can reused it in the following request call which is the read_state one.
* LedgerIdentity uses app method "signUpdateCall" instead of "sign" that requires the blob of the read_state call also.
* Store the read_state body and signature in the LedgerIdentity to be reused in the following call.
* Do not use the new method if the transaction is to stake a neuron because there is an issue in the Ledger App. This will be …
=> GIX-1712: One confirmation with Ledger device

frontend/package.json
Add flags to package.json for better definition.
`"license": "SEE LICENSE IN LICENSE.md",`
source: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#license
> If you are using a license that hasn't been assigned an SPDX identifier, or if you are using a custom license, use a string value like this one...
=> Package json license

.github/workflows/build.yml, CHANGELOG-Nns-Dapp.md
Iterative testing on CI can be quite slow if every time you have to wait for the build step before your actual test runs.
If you're only changing your test and not your code under test it can be useful to skip the build step and reuse the artifacts from the previous build.
In `.github/workflows/build.yml`, add a step to skip the build and reuse a previous build.
By default it's disabled, but with the code in place it's easy to enable.
When the build is skipped, the "Check that metadata is present" test will fail but everything else should pass as normal.
With skipping disabled: https://github.com/dfinity/nns-dapp/actions/runs/5806927625
With skipping enabled: https://github.com/dfinity/nns-dapp/actions/runs/5807123115
=> Make it easy to skip the CI build step for quick testing

frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/neuron.utils.ts, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronAdvancedSection.spec.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts, frontend/src/tests/page-objects/NnsNeuronAdvancedSection.page-object.ts, frontend/src/tests/page-objects/SnsNeuronAdvancedSection.page-object.ts
Add the dissolve date for dissolving neurons in the Advanced Section.
* New utils to get the dissolve date from SNS and NNS neurons.
* New utils are used in another related util.
* New utils are used to get the dissolve date (if any) and render it in the SNS and SNS NeuronAdvancedSection.
* Test new utils.
* Test new functionality in SNS and SNS NeuronAdvancedSection.
Not yet necessary, it's covered by the entry of the new neuron details UI.
=> GIX-1795: Add Dissolve Date in Advanced Section

.github/actions/test-e2e/action.yml, CHANGELOG-Nns-Dapp.md
It can be useful for iterative testing on CI to be able to specific a specific e2e test to run.
Add a `test_filter` input to the e2e test action.
I checked CI that all the e2e tests are still executed.
=> Allow specifing a test filter to test-e2e/action.yml

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neuron-detail/Ballots/BallotSummary.svelte, frontend/src/lib/components/neuron-detail/Ballots/Ballots.svelte, frontend/src/tests/lib/components/neurons/BallotSummary.spec.ts, frontend/src/tests/page-objects/BallotSummary.page-object.ts, frontend/src/tests/page-objects/KeyValuePairInfo.page-object.ts, frontend/src/tests/page-objects/jest.page-object.ts, frontend/src/tests/page-objects/playwright.page-object.ts, frontend/src/tests/types/page-object.types.ts
Improve the UX of the voting ballots by hiding the proposal summary by default.
Proposal summaries can be very long and it's hard to navigate the ballots with so much text.
* Use the KeyValuePairInfo in the BallotSummary.
* Add a test to check that BallotSummary shows description on info click.
* BallotSummary PO.
=> Feat: Collapse proposal summary in ballots summary

frontend/src/lib/api/sns-governance.api.ts, frontend/src/lib/i18n/en.json, frontend/src/lib/services/sns-neurons.services.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Add `disburseMaturity` service. Needs for the upcoming sns disburse maturity feature.
- disburseMaturity sns api
- disburseMaturity sns service
- "Should call api.disburseMaturity"
=> Add disburseMaturity service

CHANGELOG-Nns-Dapp.md, frontend/src/tests/lib/components/accounts/SnsAccountsFooter.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronInfoStake.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeader.spec.ts, frontend/src/tests/lib/derived/sns/sns-selected-project-new-tx-data.derived.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/mocks/sns-response.mock.ts, frontend/src/tests/utils/sns.test-utils.ts
Final motivation: Stop using get_state. But on the way, clean the unnecessary complexity of `snsQueryStore`.
In this PR: Create a test util that abstracts the filling and resetting of snsQueryStore in tests.
* New test utils: resetSnsProjects, setSnsProject.
* Use new test utils in SnsAccountsFooter.spec.ts
=> Chore: Test util to set SNS projects

frontend/src/tests/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.spec.ts, frontend/src/tests/lib/components/sns-neurons/SnsNeuronCard.spec.ts, frontend/src/tests/lib/derived/selected-universe.derived.spec.ts, frontend/src/tests/lib/derived/sns/sns-project-accounts.derived.spec.ts, frontend/src/tests/lib/derived/sns/sns-selected-transaction-fee.store.spec.ts, frontend/src/tests/lib/derived/sns/sns-sorted-neurons.derived.spec.ts, frontend/src/tests/lib/derived/sns/sns-token-symbol-selected.store.spec.ts, frontend/src/tests/lib/derived/sns/sns-total-supply-token-amount.derived.spec.ts, frontend/src/tests/utils/sns.test-utils.ts
In this PR: Use the new test util `setSnsProjects` in more tests.
* Move from `snsQueryStore.setData` to `setSnsProjects` in some test files.
=> Chore: Use new sns project test util

frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte, frontend/src/lib/derived/sns-ns-functions-project.derived.ts, frontend/src/lib/services/$public/sns.services.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/derived/sns-ns-functions-project.derived.spec.ts, frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts, frontend/src/tests/lib/services/_public/sns.services.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts
No need to request the nervous functions of an SNS. The aggregator already provides the data.
* New derived store factory `createSnsFunctionsProjectStore`. It checks first the functions store and then aggregator to return the nervous functions.
* Use the new derived store factory in `SnsNeuronFollowingCard`.
* Check the new derived store in `loadSnsNervousSystemFunctions`.
* Test `createSnsFunctionsProjectStore`.
* The changes in `loadSnsNervousSystemFunctions` exposed a missing store reset in the SnsProposalDetail test.
* Add test case in `loadSnsNervousSystemFunctions`.
Not worth an entry, only refactor.
=> Chore: Use SNS Aggregator for nervous system functions

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/nightly.yaml
All wdio e2e tests have been replaced with playwright e2e tests.
Remove everything related to the old wdio e2e tests from GitHub workflow files.
none
Will add when everything related to wdio e2e tests has been removed.
=> Remove wdio e2e test related steps from CI

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte, frontend/src/lib/components/neurons/NnsNeuronCardTitle.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts, frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts, frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts, frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts
Users can identify which neurons are controlled by an attached hardware wallet.
In this PR, I introduce a new neuron tag: "Hardware Wallet".
* New util `isHotkeyFlag`.
* Use `isNeuronControlledByHardwareWallet` and `isHotkeyFlag` in NnsNeuronPageHeading to render the tags. 
* Use `isNeuronControlledByHardwareWallet` and `isHotkeyFlag` in NnsNeuronCardTitle to render the tags.
* Add a test case for `NnsNeuronPageHeading`.
* Add a test case for `NnsNeuronCard` where `NnsNeuronCardTitle` is tested.
* Add method to POs `NnsNeuronPageHeading` and `NnsNeuronCardPo`.
* Test new util `isHotkeyFlag`.
=> GIX-1797: Add HW controller tag

frontend/src/lib/api/agent.api.ts, frontend/src/lib/api/ckbtc-index.api.ts, frontend/src/lib/api/ckbtc-minter.api.ts, frontend/src/lib/api/dev.api.ts, frontend/src/lib/api/governance.api.ts, frontend/src/lib/api/icp-ledger.api.ts, frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/lib/api/nns-dapp.api.ts, frontend/src/lib/api/sns-wrapper.api.ts, frontend/src/lib/worker-utils/canister.worker-utils.ts, frontend/src/tests/lib/api/governance.api.spec.ts, frontend/src/tests/lib/api/sns-governance.api.spec.ts, frontend/src/tests/lib/api/sns-wrapper.api.spec.ts, frontend/src/tests/lib/api/sns.api.spec.ts, frontend/src/tests/lib/services/icp-ledger.services.spec.ts, frontend/src/tests/lib/services/sns-sale.services.spec.ts
`HttpAgent` is an implementation of `Agent`.
I plan to add another implementation which wraps another agent.
So when we don't care what the implementation is, we should refer to the type `Agent` instead of `HttpAgent`.
When referring to the type `HttpAgent`, refer to type `Agent` instead unless we're actually constructing an instance.
Still pass
not worth an entry
=> Use Agent instead of HttpAgent when possible

frontend/src/tests/lib/services/sns.services.spec.ts
While working on another PR I noticed that some tests in this file depend on other tests in the same file.
1. Move all general cleanup to a top level `beforeEach`.
2. Remove all `afterEach`.
3. Remove an unused `.setSystemTime(now);` since no test cares about the value of `now`.
4. Add an `expect` to validate the cause of a later corresponding `expect`.
Ran `npm run test -- src/tests/lib/services/sns.services.spec.ts --randomize` 20 times.
not necessary
=> Clean up sns.services.spec.ts

CHANGELOG-Nns-Dapp.md, frontend/src/tests/lib/api-services/governance.api-service.spec.ts, frontend/src/tests/lib/api/canisters.api.spec.ts
These tests fail if you change the order in which tests are run:
`frontend/src/tests/lib/api-services/governance.api-service.spec.ts` because some tests set mock behavior to make a mock fail while other tests don't set mock behavior and expect the mock calls not to fail.
`frontend/src/tests/lib/api/canisters.api.spec.ts` because one group of tests did its cleanup in `beforeEach` and the other in `afterEach`.
1. `resetAllMocks` in beforeEach.
2. Remove `afterEach`.
3. Add some expectations about the state before the test
Tests only
Added an entry which should cover similar PRs as well.
=> Clean up some api tests

frontend/src/tests/e2e/proposals.spec.ts, frontend/src/tests/page-objects/NnsProposalList.page-object.ts
Fix the flaky proposals test. The e2e test did assumption that the first Governance proposal it sees is one that was created. But e2e tests run in parallel and sometime this behaviour throws [an error](https://github.com/dfinity/nns-dapp/actions/runs/5833943590/job/15822555814).
- replace `getFirstProposalCardPoForTopic` with `getFirstProposalCardPoForProposer`
- move filters test before proposal details (to be sure that filtering works as expected)
- apply filters before `getFirstProposalCardPoForProposer` to be sure that just created dummy proposals are on the first page.
Yes
=> Fix flaky proposals test

frontend/src/lib/stores/known-neurons.store.ts, frontend/src/tests/lib/components/neuron-detail/NeuronFollowingCard/Followee.spec.ts
Fix src/tests/lib/components/neuron-detail/NeuronFollowingCard/Followee.spec.ts test.
The problem was that the knownNeuronsStore was filled in one test, but never reset. Yet, most of the tests relied on that neuron to NOT be a known neuron.
The solution is to reset the knownNeuronsStore before each test.
* New method in knownsNeuronsStore "reset".
* Reset the knownNeuronsStore beforeEach for Followee.spec.
* Remove unnecessary `waitFor` in the last test case of Followee.spec.
=> Fix: Nns Followee component test

frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte, frontend/src/lib/components/neurons/NnsNeuronCardTitle.svelte, frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts, frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts, frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts, frontend/src/tests/mocks/i18n.mock.ts, frontend/src/tests/page-objects/NnsNeuronCard.page-object.ts, frontend/src/tests/page-objects/NnsNeuronCardTitle.page-object.ts, frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts
Couple the logic of the neuron tags in one helper. Tags are related to each other, therefore, it makes sense to use one helper to get them all.
* New neuron util `getNeuronTags`
* Remove neuron util `isHotkeyTag`.
* Use new util in NnsNeuronPageHeading.
* Use new util in NnsNeuronCardTitle.
* Change methods to get presence of a tag, to get the list of tags.
* Change test in NnsNeuronPageHeading
* Change test in NnsNeuronCardTitle.
* Test new util `getNeuronTags`
Not worth an entry. Only refactor.
=> Refactor: getNeuronTags helper

CHANGELOG-Nns-Dapp.md, rust-toolchain.toml
There is a security advisory that recommends updating rust to 1.71.1.
Note: This is not super critical for us and we could just wait for the bot to make this PR but it's a line line change so why take the risk?
Note: The bot _may_ make a PR to downgrade to 0.71.0 but we can reject the PR.
*  Update Rust from 1.71.0 to 1.71.1.
CI should suffice.
=> Security: Bump Rust version

frontend/src/tests/lib/components/launchpad/Projects.spec.ts, frontend/src/tests/lib/derived/sns/sns-projects.derived.spec.ts
In this PR: Use the new test util setSnsProjects in more tests.
* Move Projects.spec to use new test util.
* Move sns-projects.derived to use new test util.
=> Refactor: Use new setSnsProjects

CHANGELOG-Nns-Dapp.md
Git incorrectly merged the change log after running the merge queue on https://github.com/dfinity/nns-dapp/pull/3090
Move the change log entry `* Fixed some tests that depended on execution order.` to the unreleased section.
Also move it to `Operations` instead of `Application.
I plan to improve the `scripts/past-changelog-test` in another PR.
no
=> Move change log entry

frontend/jest-spy.ts, frontend/src/tests/lib/components/accounts/BitcoinAddress.spec.ts, frontend/src/tests/lib/components/accounts/BitcoinEstimatedFee.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletActions.spec.ts, frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts, frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts, frontend/src/tests/lib/pages/NnsAccounts.spec.ts, frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts, frontend/src/tests/lib/routes/NeuronDetail.spec.ts, frontend/src/tests/lib/routes/Neurons.spec.ts
Follow-up to https://github.com/dfinity/nns-dapp/pull/3092.
The goal is to remove `jest-spy.ts`.
1. Stop mocking `getAuthenticatedIdentity` in `frontend/jest-spy.ts`.
2. Fix remaining tests that relied on `getAuthenticatedIdentity` being mocked by calling `resetIdentity()` in order to populate the real `authStore`.
Only tests.
I will add an entry when jest-spy.ts is fully removed.
=> Remove mocking getAuthenticatedIdentity from jest-spy.ts

.github/actions/release_nns_dapp/action.yaml, .github/actions/release_nns_dapp/template, CHANGELOG-Nns-Dapp.md, build.sh
Zipped `.wasm` extensions are now deprecated by `dfx`; such files must use the `.wasm.gz` suffix.  We switched to the `.wasm.gz` suffix in 394e50672ce8791934e85582b4cf07d7452474e9.  We continued supplying `.wasm` files alongside `.wasm.gz` files, to give projects that use our builds time to upgrade.  We would like to drop support for the deprecated extension now.
* Drop `.wasm` files from releases; retain only `.wasm.gz`.
* Fix bug in the release text.
* Note: In markdown, backticks are used to format code `like this.`  Backticks in markdown inside a shell script were not escaped, so treated as text to execute.  `shfmt` then joined into the action by changing the backticks to `$(the text to format)`.  This yielded an error message in the action:
``` …
```
=> Stop publishing .wasm except with .gz

frontend/src/lib/i18n/en.json, frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts
`dissolvde_...` => `dissolved_...`
=> fix: dissolvde typo

frontend/src/tests/lib/services/auth.services.spec.ts
Some tests in `frontend/src/tests/lib/services/auth.services.spec.ts` mock `AuthClient.create` but others rely on the real behavior of `AuthClient`.
The exists `jest.restoreAllMocks` which is even stronger than `jest.resetAllMocks` because in addition to resetting mock behavior, it also restores real behavior for mocks created with `jest.spyOn`.
1. `jest.restoreAllMocks()` before each test to restore real behavior of `AuthClient`.
2. `authStore.signOut()` before each test to reset the `authStore`.
3. Use real `authStore` with `resetForTesting()` instead of `mutableMockAuthStoreSubscribe`.
Ran with `--randomize` a number of times.
covered
=> Fix order dependency of auth.services.spec.ts

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neuron-detail/StakeItemAction.svelte, frontend/src/lib/i18n/en.json, frontend/src/tests/lib/components/neuron-detail/NnsStakeItemAction.spec.ts, frontend/src/tests/lib/components/neuron-detail/StakeItemAction.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsStakeItemAction.spec.ts, frontend/src/tests/page-objects/StakeItemAction.page-object.ts
There is a bug because the StakeItemAction always shows the description "ICP Stake".
Instead, it should show "ICP staked" or "CHAT staked" as in the Figma.
* Change "ic_stake" message with a placeholder.
* Use the token for the message in StakeItemAction.svelte
* Add test case in StakeItemAction.svelte
* Add test case in NnsStakeItemAction.svelte
* Add test case in SnsStakeItemAction.svelte
* Add method in StakeItemAction PO: getDescription.
=> Fix: ICP Staked depends on token

frontend/src/tests/lib/components/common/Json.spec.ts, frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts, frontend/src/tests/lib/components/proposal-detail/ProposalProposerPayloadEntry.spec.ts, frontend/src/tests/utils/json.test-utils.ts
`NnsProposalProposerPayloadEntry.spec.ts` and `ProposalProposerPayloadEntry.spec.ts` were importing `Json.spec.ts` to get access to `simplifyJson` but this meant that when running any of these tests, it would run the tests from `Json.spec.ts` as well.
Tests shouldn't be importing other tests.
1. Move `simplifyJson` into a separate file: `frontend/src/tests/utils/json.test-utils.ts`.
2. Import `frontend/src/tests/utils/json.test-utils.ts` instead of `Json.spec.ts`.
only tests
not worth it
=> Move simplifyJson out of Json.spec

frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
In `CkBTCWalletFooter.spec.ts` a test opens `CkBTCReceiveModal` which calls `loadBtcAddress`, which calls `getBTCAddress` which calls `getAuthenticatedIdentity()`. If no identity is set, `getAuthenticatedIdentity` tries to log the user out and reload the page, which is not possible during the test.
But the test manages to finish and pass before all of this happens. But then later this results in some confusing output such as:
```
PASS  src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "error while attempting to recover localstorage: TypeError: Cannot read properties of null (reading '_origin')".
12 | function replaceRealLogger(logType: LogType) {
13 |   const realLogger …
```
=> Set identity in CkBTCWalletFooter.spec.ts

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/accounts/NnsTransactionCard.svelte, frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/lib/derived/sns-swap-canisters-accounts.derived.ts, frontend/src/lib/i18n/en.json, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts, frontend/src/tests/lib/derived/sns-swap-canister-accounts.derived.spec.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts
Users can identify transactions related to participating in a swap.
* New derived store creator "createSwapCanisterAccountsStore". Returns a derived store of AccountIdentifiers based on the passed controller and the present swap canisters.
* New parameter "swapAccounts" in "mapNnsTransaction" util.
* New parameter "swapAccounts" in "transactionType" util. It uses this new parameter to identify swap participation transactions.
* NnsTransactionCard uses the new derived store and passes it to "mapNnsTransaction" so that the swap participation can be identified.
* New test case in NnsTransactionCard spec file.
* Test new derived store.
* Fix tests with new signature.
* Add test case in "transactionType" to check it identifies swap participation transaction.
* Add test case in …
=> GIX-1819: Identify Swap Participation Transaction

frontend/src/lib/derived/sns-swap-canisters-accounts.derived.ts
Remove unnecessary code in sns swan canisters accounts store.
Changes in sns-swap-canisters.accounts.derived.ts
* Remove extra `Set` around the array.
* Use `[]` instead of undefined when we want an empty set.
Not necessary.
Not necessary.
=> Fix: Remove unnecessary set

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/transaction/TransactionForm.svelte, frontend/src/lib/modals/transaction/TransactionModal.svelte, frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts, frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts, frontend/src/tests/page-objects/Dropdown.page-object.ts, frontend/src/tests/page-objects/IcpTransactionModal.page-object.ts, frontend/src/tests/page-objects/ParticipateSwapModal.page-object.ts, frontend/src/tests/page-objects/SnsIncreaseStakeNeuronModal.page-object.ts, frontend/src/tests/page-objects/SnsStakeNeuronModal.page-object.ts, frontend/src/tests/page-objects/TransactionForm.page-object.ts, frontend/src/tests/page-objects/TransactionFromAccount.page-object.ts, frontend/src/tests/page-objects/TransactionModal.page-object.ts
We still don't allow HW to participate in the swap. Yet, there was a bug where the HW account was selectable in the modal to participate.
In case that the user selected the HW, they wouldn't participate with the HW. Instead, they would participate with the main account. Therefore, what the user selected, was ignored.
* New variable "filterSourceAccounts" in TransactionForm using the prop "skipHardwareWallets".
* Pass the "filterSourceAccounts" to "TransactionFromAccount".
* Remove using the prop "skipHardwareWallets" when filtering the destination accounts. This was an error never seen because the TransactionForm had never "skipHardwareWallets" with selectable destination account.
* Add methods to related POs to expose the available source accounts.
* Add a test case in …
=> Fix: HW cannot participate in swap

frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
NnsStakeNeuronModal.spec file was failing when randomizing unit tests.
The problem: if the case "when accounts are not loaded" was run first, it was getting the authenticated identity and failing.
* "resetIdentity" in the beforeEach of the test.
* Remove unnecessary clearing mocks and resetting store.
=> Fix: Randomized test NnsStakeNeuronModal

.github/workflows/nightly.yaml
The essential step in the `update-chromedriver` job was already removed in https://github.com/dfinity/nns-dapp/pull/3084 so the job doesn't really do anything now.
Remove the `update-chromedriver` job entirely from `.github/workflows/nightly.yaml`.
no
Will add when everything related to wdio e2e tests has been removed.
=> Remove update-chromedriver job from nightly.yaml

frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Test sns-neuron-services.spec fails when randomizing unit tests order.
The problem was that one test was mocking a service used in another test. Preventing from reaching the call to the api.
Solution: remove the mock and test that api is called instead.
* In sns-neuron services remove mock to "loadNeurons". Instead, check that "querySnsNeurons" is called.
Not worth an entry in the changelog.
=> Fix: Randomized test sns neuron services

frontend/src/tests/lib/modals/sns/SnsIncreaseStakeNeuronModal.spec.ts
Test SnsIncreaseStakeNeuronModal.spec fails when randomizing unit tests order.
The problem was that the tests in "accounts and params are not loaded" relied in the stores to be empty. Yet, when the order changed and the ones below were executed, the store mocks returns data.
I could have fixed it by adding a "resetAllMocks". But instead, I decided to remove the store mocks because it's not our current pattern to do so.
In SnsIncreaseStakeNeuronModal.spec
* Remove the jest.spyOn mocks.
* Instead, prepare the stores to be as expected.
=> Fix: Randomized test SnsIncreaseStakeNeuronModal

frontend/src/lib/services/$public/sns.services.ts
Remove a TODO comment because it's already done.
* In the "loadSnsProjects" there was a todo to add the aggregator data to a store. This is already done.
Only comment changes.
Not worth an entry.
=> Fix: Remove done TODO comment

frontend/src/tests/lib/derived/sns/sns-selected-project.derived.spec.ts, frontend/src/tests/lib/services/sns.services.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts
In this PR: Use new test util in sns-selected-project.derived.spec and sns.services.spec
* Change from snsQueryStore.setData to setSnsProjects in both test files.
=> Refactor: Use new sns test util

CHANGELOG-Nns-Dapp.md, frontend/src/lib/services/$public/proposals.services.ts, frontend/src/lib/services/$public/sns.services.ts, frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
The launchpad renders the open proposals related to SNSes. We were fetching all the proposals of the topic and then filtering only the Open ones. We had a problem because there were big SNS proposals and the message limit was reached.
The way to solve it for the launchpad is to request only the OPEN and SNS topic.
* Remove service "loadProposalsByTopic".
* Use queryProposals api in "loadProposalsSnsCF" with the topic and status filter.
* Change the test of the Proposals.spec to spy on the api function and test that it's called with the proper values.
=> GIX-1821: Use "Open" filter for lauchpad proposals

CHANGELOG-Nns-Dapp.md, frontend/src/lib/i18n/en.json, frontend/src/lib/services/$public/proposals.services.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/error.utils.ts, frontend/src/tests/lib/services/_public/proposals.services.spec.ts, frontend/src/tests/lib/utils/error.utils.spec.ts
We had a problem because there were big SNS proposals and the message limit was reached. The current UX was not the best and didn't explain what the user could do.
In this PR: We catch that specific message and change it for a message that the user can understand and act upon.
* New error util "isPayloadSizeError".
* Use new util in "handleFindProposalsError" which is used in "listProposals" service.
* Test new error util.
* Add test cases in "listProposals" service for when api fails.
=> GIX-1822: Fail gracefully on list proposal payload size error

.github/workflows/build.yml, CHANGELOG-Sns_Aggregator.md, dfx.json, scripts/sns/aggregator/test-pagination
We are about to change the pagination; it would be good to be sure that the pagination is as expected.
* Add a test that the pages are present and contain the expected SNS indices.
* Update the `nns-sns-wasm` .did file path to use the file we have committed in the repo.
* Note: This means that the .did file is available and can be used without building, unlike the previous code.
* Note: The existing path was built when building custom sns canisters for e2e tests, however the old e2e tests with the custom builds may be deleted soon.
* Note: There are probbaly other .did paths that should be updated, but only this update is needed for the API call made in the test.
* This PR contains a test and the test is exercised in CI.
* I have run this test against mainnet and the app subnet …
=> Test pagination

frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/types/transaction.ts, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts
The transactions list in the ICP wallet identifies the swap participation transaction. Therefore, we should also identify the refunds.
* Add a transaction type in `AccountTransactionType`.
* Add a check in `transactionType` util to identify swap refunds.
* Test new case in `transactionType`.
* Test new case in `mapNnsTransaction`.
=> GIX-1820: Identify Swap Refund Transaction

CHANGELOG-Nns-Dapp.md, frontend/src/lib/services/sns.services.ts, frontend/src/lib/stores/sns-lifecycle.store.ts, frontend/src/tests/lib/services/sns.services.spec.ts, frontend/src/tests/lib/stores/sns-lifecycle.store.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts
In this PR: Introduce a new Svelte store that will store the data from the get_lifecycle call.
This store is needed to store the latest lifecycle after the user's participation.
* New sns lifecycle store creator with caching.
* Load the store when the derived state is fetched directly in "loadSnsLifecycle".
* Test the new store
* Test that "loadSnsTotalCommitment" also loads the new store.
=> GIX-1823: New sns lifecycle store

frontend/src/tests/lib/api/agent.api.spec.ts
I want add a wrapper for `Agent` which provides a different `Identity` instance and use that to wrap agents cached in the agent API.
But before I do, I'm adding some test coverage to the agent API because currently there is none.
Add tests for `createAgent` from `agent.api.ts`.
yes
will add when I add the agent wrapper
=> Add tests for createAgent

frontend/src/tests/lib/pages/Canisters.spec.ts
Some test cases in Canisters.spec relied on the page to be rendered in previous unit tests to pass.
* Render the page in the specific test cases instead or relying in the previous renders.
* Clear all mocks to make sure the call belong to the test.
=> GIX-1824: Fix Canisters.spec

frontend/src/tests/lib/modals/canisters/LinkCanisterModal.spec.ts
Fix LinkCanisterModal.spec
The problem was that `"should attach a canister by id if name is maximum length"` test should be failing, but it was passing because the mock was not being cleared and the api was called in a previous test. If I cleared to mocks in the beforeEach, the test was failing with the normal order.
The problem with the test was that the principal was not a valid principal. It was mixing up principalText and name. I changed so that the name had the max length, and set a valid principalText. That fixed the test.
I also added an expect before clicking the button that the api was not called.
In LinkCanisterModal.spec
* Add jest.clearAllMocks in beforeEach.
* Add a valid principal in "principalText" for `"should attach a canister by id if name is maximum length"` and the max …
=> GIX-1824: Fix LinkCanisterModal.spec

frontend/src/tests/lib/pages/SnsAccounts.spec.ts
Fix SnsAccounts.spec.
The problem was that two mocks were messing up with the test cases if set in a different order. Some test cases relied on the mocks, others not. Clearing mocks was not enough, we had to resetAllMocks. Yet, instead of resetting the mocks, I removed the mocks and relied on filling the stores properly.
In SnsAccounts.spec
* Remove mock on "snsProjectSelectedStore".
* Move page.mock to the main beforeEach.
* Remove mock on "snsProjectAccountsStore".
=> GIX-1824: Fix SnsAccounts.spec

frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
In this PR: Introduce the converter from sns aggreagator data to SnsSummary.
The SnsSummary type is used in the `snsSummariesStore` to return a list of SnsSummary.
After this PR, we can enable using the aggregator data instead of snsQueryStore.
Then, we can remove snsQueryStore.
* New sns aggregator converter `convertDtoToSnsSummary`. Some of the utils are similar to utils in sns.utils.ts. I didn't use those on purpose because I want to remove them along the snsQueryStore.
* Add a test for the new converter `convertDtoToSnsSummary`.
Not yet worth an entry.
=> GIX-1823: Converter agg data to SnsSummary

HACKING.md, frontend/README.md, scripts/fmt, scripts/fmt-e2e
Wdio e2e tests have been replaced with Playwright e2e tests.
1. Removing section about e2e config from `HACKING.md`. The new e2e tests have their own documentation in `frontend/src/tests/e2e/README.md`.
2. Link to the new e2e tests instead of the old ones from `frontend/README.md`.
3. Remove scripts to format `e2e-tests/`.
no
Will add an entry once `e2e-tests/` is removed entrirely.
=> Remove references to old e2e-tests/

frontend/src/lib/services/sns.services.ts, frontend/src/lib/stores/sns-derived-state.store.ts, frontend/src/tests/lib/services/sns.services.spec.ts, frontend/src/tests/lib/stores/sns-derived-state.store.spec.ts
We want to use the snsDerivedStateStore in the derived store `snsSummariesStore`. To do that, we can't use dynamic creationg of the store. To allow dynamic creation of the store, we would need to also create dynamically `snsSummariesStore`. This is a bigger refactor than expected and not sure it's worth the effort now.
Therfore, I implemented the same pattern of storing all project data in one single store using the root canister id as key in the snsDerivedStateStore.
* `snsDerivedStateStore` doesn't create store dynamically. It's one store to rule them all.
* Refactor where this store was created.
* Test new capabilities and remove old ones.
* Change test after refactor.
=> GIX-1823: Use one store for sns derived state

CHANGELOG-Nns-Dapp.md, frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts, frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts, frontend/src/tests/lib/components/proposals/NnsProposalCard.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
Two days ago, I had a unit test failure because a test was relying on real time instead of setting the system time.
In this PR: I looked at all the tests that were using real time and changed it.
* Set time for NnsNeuronCard.spec.
* Set time and clarify dependencies of creation times with a variable in SnsVotingCard.spec.
* Set time in NnsProposalCard.spec
* Set time in sns-neuron.utils.spec
=> Fix: Do not use real time in tests

frontend/src/lib/services/sns.services.ts, frontend/src/lib/stores/sns-lifecycle.store.ts, frontend/src/tests/lib/services/sns.services.spec.ts, frontend/src/tests/lib/stores/sns-lifecycle.store.spec.ts
Similar to #3144 
We want to use the snsLifecycleStore in the derived store snsSummariesStore. To do that, we can't use dynamic creation of the store. To allow dynamic creation of the store, we would need to also create dynamically snsSummariesStore. This is a bigger refactor than expected and not sure it's worth the effort now.
Therefore, I implemented the same pattern of storing all project data in one single store using the root canister id as key in the snsLifecycleStore.
* Change snsLifecycleStore to use only one store to rule them all.
* Change usage of the store.
* Change test cases for snsLifecycleStore.
* Change related tests after refactor.
Not worth a changelog entry
=> GIX-1823: Use one snsLifecycleStore

frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/services/sns.services.ts, frontend/src/tests/lib/services/sns.services.spec.ts
Rename the service loadSnsTotalCommitment to loadSnsDerivedState to make it clearer what it does.
* Rename `loadSnsTotalCommitment` to `loadSnsDerivedState` and where is imported and used.
* Add the rename in the test file where it's used.
=> Rename: loadSnsTotalCommitment

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte, frontend/src/lib/utils/projects.utils.ts
Modclub set `"min_participant_icp_e8s":100000278` which we round in the UI to 1.00 ICP.
Then when you try to participate with 1 ICP you get an error saying
"Sorry, the amount is too small. You need a minimum of 1.00 ICP to participate in this swap."
Call `formatToken` with `detailed: true`. This renders all significant digits if amount >= 0.01 (if I understand the code correctly).
no
=> detailed min participation

frontend/src/lib/types/sns-aggregator.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
Type of the SNS aggregator for `swap_params` was wrong. It was "CachedSwapParamsDto | null", not just "CachedSwapParamsDto".
* Change the type of `CachedSnsDto`.
* Change converter accordingly.
* Add a test with the specific field.
Not worth a new entry yet.
=> Fix: Aggregator type and subsequent converter

frontend/src/tests/page-objects/App.page-object.ts, frontend/src/tests/page-objects/Neurons.page-object.ts
Some [flakiness was observed](https://github.com/dfinity/nns-dapp/actions/runs/5925864493/job/16066262925?pr=3155) in the e2e test that disburses a neuron.
What happened is that after going to the neurons tab, no neuron cards were visible.
When I tried manually going from the accounts tab to the neurons tab, I noticed that the accounts tab was still there for a short time before the neurons tab renders.
In `AppPo.goToNeurons()` wait for the neurons tab to be loaded before continuing.
I wasn't able to reproduce the flakiness but the tests still pass with this change as well and it seems like it should help.
not necessary
=> E2E: Wait for content to load after going to the neurons tab

frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte, frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/ProjectSwapDetails.page-object.ts
I wanted to add unit tests for https://github.com/dfinity/nns-dapp/pull/3150 but I noticed some issues in `ProjectSwapDetails.spec.ts` so I wanted to fix those first.
`ProjectSwapDetails.spec.ts` expects token values to appear in a certain order in the UI and it queries all of them with the same query and then uses a magic index into that list.
Because of this it also relies on different values being different otherwise we wouldn't notice of some swapped places in the order.
1. Use page objects in all the tests in `ProjectSwapDetails.spec.ts`.
2. Set specific values on the input and expect those specific values to be rendered instead of depending on what happens to be in the mock data.
3. Add necessary test IDs.
4. Add getters on `ProjectSwapDetails.page-object.ts`.
5. Allow more …
=> Improve ProjectSwapDetails.spec.ts

frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
The test sets mock behavior in a describe block, outside beforeEach or it.
This gets executed in a surprising order, because first the framework collects all the tests that should be executed by running the describe blocks, and then it runs all the tests.
This means that the structure of the code may suggest a certain test runs with a certain mock behavior, while it actually runs with the mock behavior define in another test or `describe` block.
Additionally, `beforeEach(() => ckBTCWithdrawalAccountsStore.reset);` has no effect because `() => ckBTCWithdrawalAccountsStore.reset` returns the `reset` function but doesn't call it.
1. Make sure all mock behavior is defined in either `beforeEach` or inside a test.
2. Be explicit about which steps we expect to be performed.
3. Reset …
=> Clean up ckbtc-convert.services.spec.ts

frontend/src/tests/workflows/Launchpad/LaunchpadWithLayout.svelte, frontend/src/tests/workflows/Launchpad/ProdLaunchpad.spec.ts
We had a bug because the type of the aggregator in ths NNS Dapp was not correct and when it tried to convert a certain field it failed.
In this PR, I try to add a test that renders the Launchpad with prod data from the aggregator. I then check that there are committed projects and no errors.
* New test  in workflows/Launchpad/ProdLaunchpad.spec.ts.
* New test component in workflows/Launchpad/LaunchpadWithLayout.svelte. This is used to trigger the same flows as the svelte app. In this scenario, the call to the SNS aggregator.
=> Chore: Add Launchpad test with prod data

CHANGELOG-Nns-Dapp.md, frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts, frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts, frontend/src/tests/page-objects/AmountInput.page-object.ts
https://github.com/dfinity/nns-dapp/pull/3150 was merged in a hurry without unit tests.
1. Unit test in `ProjectSwapDetails.spec.ts` for detailed min participation rendering.
2. Unit test in `ParticipateSwapModal.spec.ts` for "not enough commitment" error message with detailed min participation.
only
=> Unit tests for detailed min participation

.github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md, rs/backend/src/accounts_store.rs, rs/backend/src/arguments.rs, rs/backend/src/assets.rs, rs/backend/src/lib.rs, rs/backend/src/main.rs, rs/backend/src/perf.rs, rs/backend/src/proposals.rs, rs/backend/src/state.rs, rs/backend/src/stats.rs, rs/sns_aggregator/src/assets.rs, rs/sns_aggregator/src/conversion.rs, rs/sns_aggregator/src/fast_scheduler.rs, rs/sns_aggregator/src/lib.rs, rs/sns_aggregator/src/state.rs, rs/sns_aggregator/src/types.rs, scripts/lint-rustdoc, scripts/nns-dapp/doc, scripts/sns/aggregator/doc
Rust code documentation can be parsed and displayed in a nice, readable way by rustdoc.
The sns aggregator documentation is available in this way, but unfortunately most of the nns-dapp code is inaccessible, making it unnecessarily to read.
* Make the nns-dapp code accessible to the nns-dapp lib, which is the entry point for rustdoc.
* Note: `rustdoc` _does_ have limited support for documentation of binaries, however it is not good.
* Fix rustdoc links
* Test the rustdoc in CI.
* Add two utility scripts to make it easy to generate documentation without retyping a bunch of flags.
* Note: `rustdoc` flags such as `--open` are passed through the script.
* Performed a quick pass checking spelling and formatting.  E.g. code `should be in backticks`.
*  `cargo doc` is now tested in CI.
=> Rustdoc - fix

frontend/src/lib/types/sns-aggregator.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
We realized that some of our SNS aggregator types were not correct. It seems that the changes were not exhaustive and there are more fields that can still be optional.
I based my findings on the actual types of the canisters. Where the response said `[] | [T]`, I changed it to `null | T`.
* Change value of some fields in SNS aggregator to make them optional.
* Fix converters after change.
* Test the new functionality when converting the summary that might return undefined if swap params are not defined.
* Add a test for `convertNervousFuncttion` (typo will be addressed in another PR)
=> Fix: More SNS aggregator optional types

CHANGELOG-Nns-Dapp.md, frontend/src/lib/api/agent.api.ts, frontend/src/tests/lib/api/agent.api.spec.ts
We cache created agents for performance (according to https://github.com/dfinity/nns-dapp/pull/1600).
But the agent keeps a reference to the identity used to create the agent which means the identity is implicitly cached as well.
This has been causing problems with hardware wallet interactions where we need to keep state on the identity to indicate that a ledger transfer is for the purpose of staking a neuron.
1. Add a wrapper agent which uses a newly specified identity instead of the identity used to create the agent originally.
2. When returning an agent from the cache, wrap it in the wrapper such that the current identity is used instead of the previously cached one.
1. Method calls are forwarded to the underlying agent.
2. The identity can be invalidated.
3. Method calls on different …
=> IdentityAgentWrapper to use cached agent with specified identity

frontend/src/tests/lib/utils/html.utils.spec.ts
Test `"should call markedjs/marked with custom renderers"` literally depended on the test before it calling `markdownToHTML()`.
1. Change `beforeAll` to `beforeEach` to give each test a clean slate.
2. Reset `renderer` in `beforeEach`.
3. Call `markdownToHTML()` in both tests rather than one test relying on the other.
Passed with 5 different randomize seeds.
Already covered
=> Fix ordered dependence in html.utils.spec.ts

.github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/release-sop.test, scripts/past-changelog-test.test
CI uses a third party action to run shellcheck, rather than `./scripts/lint-sh`.  Unsurprisingly the two have got out of sync, resulting in warnings whenever shellcheck is run locally.
* Use `./scripts/lint-sh` in CI, instead of the third party action.
* Fix shellcheck issues.
* See CI.
=> Rm unused var

CHANGELOG-Nns-Dapp.md, frontend/src/lib/stores/sns-derived-state.store.ts, frontend/src/lib/stores/sns-lifecycle.store.ts, frontend/src/lib/stores/sns.store.ts, frontend/src/tests/e2e/sns-participation.spec.ts, frontend/src/tests/lib/stores/sns.store.spec.ts
We want to move away from get_state deprecated endpoint. Before doing that, we need to move away from snsQueryStore.
In this PR, the snsAggregatorStore and other stores are used in the snsSummariesStore instead of the snsQueryStore.
* Use new stores in snsSummariesStore.
* Test store in different cases.
=> GIX-1823: Use sns aggregator store in snsSummariesStore

frontend/src/tests/lib/services/_public/sns-proposals.services.spec.ts
Some tests were generating errors on the console but only one of the tests mocked the console.
So if another test logged to the console, it would fail.
Explicitly mock `console.error` in the tests that require it and restore the mock before every test.
Pass with random seeds 1 - 20.
covered
=> Fix order dependence in sns-proposals.services.spec.ts

rs/backend/src/accounts_store.rs
The `add_account()` function is obscured by a long and rarely used migration for early accounts.  This is awkward and the lack of clarity is potentially dangerous as we migrate the data yet again.
* Move the transaction migration into a separate function.
* There is already a test for the migration, so existing CI should suffice.
- Not necessary, IMO.
=> Refactor, removing a rarely used legacy migration out of the main flow

frontend/src/tests/lib/utils/ckbtc.utils.spec.ts
One of the tests sets `mockedConstants.FORCE_CALL_STRATEGY = "query"` but doesn't reset it.
Call `resetMockedConstants()` in `beforeEach`.
passed
covered
=> Fix orderer dependency in ckbtc.utils.spec.ts

frontend/src/lib/pages/NnsProposals.svelte
I've seen a few failures like this:
https://github.com/dfinity/nns-dapp/actions/runs/5949476993/job/16135403216
In the `neurons.spec.ts` e2e test, after navigating to the proposals tab, it waits for content to be loaded but then see 0 proposal cards.
I was able to reproduce this locally after adding some logging, but unfortunately only once.
But my guess is that the component renders in non-loading state (without skeletons) before the skeletons are rendered.
At this point the test assumes loading is finished and expects the proposals to be already there.
Initialize `frontend/src/lib/pages/NnsProposals.svelte` in loading state.
I'm not sure how to test this given that `loading` is anyway immediately set to true in `onMount`.
But when I logged the value of `loadingAnimation`, it did log as …
=> Initialize NnsProposals as loading

frontend/src/tests/e2e/images.spec.ts
An e2e was skipped in #3179 
In this PR, I enable it and fix it.
* Enable the images e2e test.
* Change the expected images.
Not necessayr.
=> Fix: Enable images e2e test

frontend/src/tests/lib/components/accounts/BitcoinEstimatedFee.spec.ts
One test was expecting a specific number of calls to a mock but the mock was not being cleared between tests.
1. Call `jest.clearAllMocks()` in `beforeEach`.
2. Expect no calls at the start of the test.
pass
covered
=> Fix order dependency in BitcoinEstimatedFee.spec.ts

frontend/src/app.html, frontend/src/routes/(app)/+layout.svelte, frontend/src/tests/e2e/design.spec.ts, frontend/src/tests/routes/app/layout.spec.ts
We have no control on the way the chunks are loaded. As a result, it's possible that it waits until most chunks are loaded before displaying the hints - the spinner - that the dapp is booting which is leading to an unfriendly UX as a blank screen might be displaying for a while.
By rendering a spinner within the static html page and removing it once most of the JS files are loaded, we can overcome this "race condition".
- add (copy) spinner in `app.html`
- when the auth is ready, which indicates most JS resources are loaded, remove the spinner
https://kgqse-raaaa-aaaaa-aactq-cai.nnsdapp.dfinity.network/
https://kgqse-raaaa-aaaaa-aactq-cai.nnsdapp.dfinity.network/accounts
https://xnjld-hqaaa-aaaal-qb56q-cai.icp0.io/
Mainnet - current main - Fast 3g network => spinner appears for a milli …
=> Static loading spinner

frontend/src/lib/pages/SignInAccounts.svelte, frontend/src/lib/pages/SignInCanisters.svelte, frontend/src/lib/pages/SignInNeurons.svelte, frontend/src/lib/pages/SignInSettings.svelte
PageBanner in Safari doesn't render properly.
In this PR, it fixes the overflow.
In another PR: upgrade gix-components and svg should be visible.
* Wrap the PageBanner within a div. Having a grid inside a flexbox doesn't work well for Safari.
Already covered by the changelog entry of the new landing pages. They have not yet been released.
=> Fix: Safari page banner

frontend/src/tests/lib/components/accounts/HardwareWalletName.spec.ts
One of the tests updates global state in `addAccountStoreMock` and a test (that normally runs before it) expects the global state to be empty.
The global state was only set in `beforeAll`.
1. Change `beforeAll` to `beforeEach`.
2. Remove `afterAll`.
pass
covered
=> Fix order dependence in HardwareWalletName.spec.ts

frontend/src/tests/lib/services/_public/proposals.services.spec.ts
The test would fail when run in randomized order.
The test sets mock behavior in a `describe` block, outside `beforeEach` or `it`.
This gets executed in a surprising order, because first the framework collects all the tests that should be executed by running the `describe` blocks, and then it runs all the tests.
This means that the structure of the code may suggest a certain test runs with a certain mock behavior, while it actually runs with the mock behavior defined in another test or `describe` block.
1. Move mock behavior defined in `describe` blocks, inside `beforeEach` in that block.
2. Move all cleanup to top-level `beforeEach`.
3. Remove all `beforeAll`, `afterEach` and `afterAll`.
4. Explicitly mock `authStore.subscribe` with either `mockAuthStoreSubscribe` or …
=> Fix order dependence in proposals.services.spec.ts

frontend/src/tests/lib/components/accounts/NnsSelectAccount.spec.ts
Some tests mocked `icpAccountsStore` while other tests tried to set the real `icpAccountsStore`.
Setting the real `icpAccountsStore` had no effect for tests that tried to do that and those test only passed by coincidence of what the last test that mocked `icpAccountsStore` happened to mock it with.
Stop mocking `icpAccountsStore` in `frontend/src/tests/lib/components/accounts/NnsSelectAccount.spec.ts` and instead set the real store in each of the tests.
Pass with 20 different random seeds.
covered
=> Fix order dependence in NnsSelectAccount.spec.ts

frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
One test sets `referrerPathStore` but it's never reset, which can affect other tests depending on the order.
Reset `referrerPathStore` in `beforeEach`.
Pass with 20 different random seeds.
covered
=> Fix order dependence in NnsProposal.spec.ts

frontend/src/tests/lib/components/universe/SelectUniverseDropdown.spec.ts
One test relies on a clean `snsAccountsStore` but another test sets data on `snsAccountsStore` and it wasn't reset between tests.
1. Reset `snsAccountsStore` in top-level `beforeEach`.
2. Change sub-level `beforeAll` to `beforeEach` to make sure it's run after the top-level `beforeEach`.
3. Move other cleanup from `beforeAll` and `afterAll` to `beforeEach`. (drive-by)
Pass with random seeds 1-20.
covered
=> Fix order denpendence in SelectUniverseDropdown.spec.ts

frontend/src/tests/lib/components/warnings/Warnings.spec.ts
`metricsCallback` is initialized while rendering the component.
One of the tests explicitly waited for this but the others didn't and may have reused the value from the other test.
1. Reset `metricsCallback` before each test.
2. Wait for `metricsCallback` to be initialized in each test.
Pass with random seed 1 - 20.
covered
=> Fix order dependence in Warnings.spec.ts

frontend/src/tests/lib/derived/selectable-universes.derived.spec.ts
One test mocked `snsProjectsCommittedStore` but other tests expected to be empty.
1. Restore mocks in top-level `beforeEach`.
2. Change `beforeAll` to `beforeEach` so it runs after the top-level `beforeEach`.
3. Remove `clearAllMocks` which became redundant with `restoreAllMocks`.
Passes with random seed 1 - 20.
covered
=> Fix order dependence in selectable-universes.derived.spec.ts

frontend/src/tests/lib/modals/accounts/HardwareWalletNeuronAddHotkeyModal.spec.ts
Fix test HardwareWalletNeuronAddHotkeyModal.spec that fails when randomized.
* Resetting all mocks in a beforeEach fixed the problem and cleaned up the code.
Not necessary.
=> Fix: Ordering test HardwareWalletNeuronAddHotkeyModal

frontend/src/tests/lib/pages/CkBTCAccounts.spec.ts
One of the tests required to go first because the mocks were not cleared and it checked that a function was not called.
I also changed all the beforeAll to beforeEach.
In ckBTCAccounts.spec
* Add clear mocks in main beforeEach
* Change beforeAll for beforeEach
Not necessary
=> Fix: CkBTCAcconts.spec

frontend/src/lib/derived/sns-ns-functions-project.derived.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/derived/sns-ns-functions-project.derived.spec.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
There was a typo in the function `convertNervousFuncttion` with two `t`.
* Rename from `convertNervousFuncttion` to `convertNervousFunction`.
* Rename also in tests.
* 
Not necessary.
=> Fix: Typo in convertNervousFuncttion

frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
One test expected `bitcoinAddressStore` to start out empty but another test filled it and didn't reset it.
1. Reset `bitcoinAddressStore` in `beforeEach` to fix the test.
2. Reset some other state to provide a more consistent environment for the tests.
3. Change `beforeEach` to `beforeAll`.
Passes with random seed 1 - 20.
covered
=> Fix order dependency in CkBTCReceiveModal.spec.ts

frontend/src/tests/lib/directives/intersection.directives.spec.ts
There are 2 tests: one tests with `IsIntersecting = true` and the other with `IsIntersecting = false`.
But `IsIntersecting = true` is assumed implicitly as default value.
Set `IsIntersecting` explicitly in both tests.
Tests now pass in both orders.
covered
=> Fix order dependence in intersection.directives.spec.ts

frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
`"should render progress without step transfer"` relied on (one of) the previous 2 tests mocking `services.retrieveBtc` (by calling `testRetrieveBTC`) so it failed when run individually.
1. Explicitly mock `services.retrieveBtc` in `"should render progress without step transfer"`
2. Restore all mocks in top-level `beforeEach` to make sure no tests depend on mocks defined in other tests.
3. Defined mock behavior of `ckBTCTransferTokens` instead of in the global scope, otherwise it will now be restored in `beforeEach`.
Passes with random seed 1 - 20.
covered
=> Fix order dependence in CkBTCTransactionModal.spec.ts

frontend/src/tests/lib/routes/Settings.spec.ts
`"should render a skeleton while loading expired session time"` expects `authRemainingTimeStore` to start out empty but it's never reset when other tests fill it.
Reset `authRemainingTimeStore` in top-level `beforeEach`.
Pass with random seeds 1 - 20.
covered
=> Fix order dependence in Settings.spec.ts

frontend/src/tests/lib/routes/ProposalDetail.spec.ts
When tests run in a different order, both `beforeAll`s are run before either test and then both tests are run.
1. Change `beforeAll` to `beforeEach`.
2. Remove `afterEach`.
The two tests pass in both orders.
covered
=> Fix order dependence in ProposalDetail.spec.ts

frontend/src/tests/lib/pages/NnsWallet.spec.ts
`"should display receive modal information"` expects `icpAccountsStore` to be filled with certified data to avoid calling `queryAccount` via `pollAccounts`.
The certified test data was put in `icpAccountsStore` in `beforeAll` rather than `beforeEach`.
If `"should reload account after finish receiving tokens"` was run first, it would end up with non-certified data in `icpAccountsStore` and so `"should display receive modal information"` would fail when doing `queryAccount` which wasn't mocked.
The solution is to put the certified data in `icpAccountsStore` in `beforeEach` so that each test gets a fresh store.
1. Change `beforeAll` to `beforeEach`.
2. Move all cleanup to top-level `beforeEach` (drive-by)
Passes with random seeds 1 - 20
covered
=> Fix order dependence in NnsWallet.spec.ts

frontend/package-lock.json
We want to show in the project status whether the swap is finalizing.
In this PR, upgrade the next dependencies to be able to use a new method added in sns-js: [getFinalizationStatus](https://github.com/dfinity/ic-js/pull/400)
* Upgrade next dependencies.
Not necessary
Not necessary.
=> GIX-1841: Upgrade ic-js

CHANGELOG-Nns-Dapp.md
This reverts commit 042437bf53097518bd23f1cad35cbea72abbdbff.
The above commit was accidentally pushed to main.
- Following the NNS dapp SOP, the Release branch upstream ended up  having main as the upstream.  Not sure how.
- The github repository settings required branch protections to be enabled explicitly. (They have been enabled now)
- Revert the unintended commit.
None
=> Revert "Cut release"

frontend/src/lib/components/accounts/NnsDestinationAddress.svelte, frontend/src/tests/lib/components/accounts/NnsDestinationAddress.spec.ts
`NnsDestinationAddress` has a prop `filterIdentifier` which is not passed in from anywhere so it's always `undefined`.
1. Remove `filterIdentifier` from `NnsDestinationAddress`.
2. Remove the test that tests the filter.
Remaining tests still pass.
not worth it
=> Remove unused filter from NnsDestinationAddress

CHANGELOG-Nns-Dapp.md, frontend/src/lib/services/worker-balances.services.ts, frontend/src/tests/lib/services/worker-balances.services.spec.ts
There is a bug where if you quickly switch between SNS universes multiple times, we show the balance of one token for a different token.
There are several issues that might contribute to this:
1. `rootCanisterId` and `ledgerCanisterId` are passed independently from `SnsAccountsBalancesObserver` to `SnsBalancesObserver` and are acquired from different stores which are not guaranteed to be in sync at the time these values are passed.
2. When the callback in `SnsBalancesObserver` is called from the `BalancesWorker`, it uses the value of `rootCanisterId` at the time the callback is called, rather than the value it had at the time the worker was initialized with the corresponding `ledgerCanisterId`.
3. If the `BalancesWorker` receives a response, it will still call the callback on …
=> Don't call callback after balance worker is stopped

rs/backend/src/accounts_store/schema.rs, rs/backend/src/accounts_store/schema/map.rs, rs/backend/src/accounts_store/schema/tests.rs
The first production implementation of the accounts DB trait will be the status quo: Accounts are stored in a hash map.
We actually already have an implementation of the accounts db trait as a map in the mock, so we can just rename it and move it out of the tests file.
* Rename `MockAccountsDb` to `AccountsDbAsMap`.
* The existing tests have been updated.
- Not needed, as this is minor and doesn't make any user-facing changes.
=> Rename MockAccountsDb to AccountsDbAsMap

frontend/src/tests/lib/components/accounts/NnsDestinationAddress.spec.ts, frontend/src/tests/page-objects/AccountCard.page-object.ts, frontend/src/tests/page-objects/NnsDestinationAddress.page-object.ts, frontend/src/tests/page-objects/NnsSelectAccount.page-object.ts
I want to bring `NnsDestinationAddress`, which is only used in `DisburseNnsNeuronModal`, more in line with the account picker in the transaction modal.
But before I do, I want to make sure there is proper test coverage so I don't break anything.
1. Use page objects in `frontend/src/tests/lib/components/accounts/NnsDestinationAddress.spec.ts`.
2. Create spies in `beforeEach` instead of directly in the `describe` block.
3. Add a test where it selects an account from the list.
4. Add a test where it enters an identifier in the input field.
5. Add required functionality to page objects.
Only tests
not worth it
=> Improve NnsDestinationAddress.spec.ts

.github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/bump-patch, scripts/nns-dapp/bump-patch.test
The nns dapp release process includes incrementing the patch version of the frontend and cargo versions.  Let's automate that.
- Add a script that increments the patch versions.
- The effect of running this command can be seen here: https://github.com/dfinity/nns-dapp/compare/bump-patch...test-patch
- A minimal test is included and exercised in CI.
=> Scipt to increment the patch version

frontend/src/lib/components/accounts/SelectAccountDropdown.svelte, frontend/src/tests/page-objects/Dropdown.page-object.ts
In `frontend/src/lib/components/accounts/SelectAccountDropdown.svelte` dropdown options were formatted such that extra whitespace appears in the option text. This makes it harder to find the right option in tests and is simply unnecessary.
1. Format the options such that no additional whitespace appears in the options.
2. Remove a `trim()` which is now unnecessary.
Still pass.
not necessary
=> Format dropdown options without whitespace

frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts, frontend/src/tests/page-objects/NnsSelectAccount.page-object.ts
I plan to change `DisburseNnsNeuronModal` to use `SelectDestinationAddress` to bring it more in line with `TransactionModal`.
The test will be easier to adapt when it uses page objects already.
1. Use page objects in `DisburseNnsNeuronModal.spec.ts`.
2. When the test expects a promise to have not yet resolved (when loading accounts) use an explicitly not-yet-resolved promise.
only tests
not necessary
=> Use page objects in DisburseNnsNeuronModal.spec.ts

frontend/src/tests/lib/pages/ProjectDetail.spec.ts
Final motivation: remove dependency on get_state. Middle step, remove snsQueryStore.
In this PR: When I set the enable sns aggregator store feature flag to true, the ProjectDetail.spec fails because some parameters are not set properly.
It's passing with snsQueryStore because the defaults are aligned with the test.
* Add parameters when setting sns projects in ProjectDetails.spec file
Not necessay.
=> GIX-1823: Fix ProjectDetail.spec

frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts, frontend/src/tests/page-objects/Toggle.page-object.ts, frontend/src/tests/page-objects/jest.page-object.ts, frontend/src/tests/page-objects/playwright.page-object.ts, frontend/src/tests/types/page-object.types.ts
There is a TODO in `frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts` to only toggle the input method if necessary.
I'm working on a PR to reuse the `SelectDestinationAddress` component in the `DisburseNnsNeuronModal` component and for that's it's useful to finally do this TODO.
1. Fix the type of `isChecked`. There is no reason for it to return `null`.
2. Add functionality to `frontend/src/tests/page-objects/Toggle.page-object.ts` to check the value and set a specific value.
3. Add functions to `frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts` to specifically enable select input or text input.
4. Specifically choose select input before selecting an account.
test changes only
not necessary
=> E2E: Only toggle the address select if necessary

rs/backend/src/accounts_store/schema.rs, rs/backend/src/accounts_store/schema/map.rs, rs/backend/src/accounts_store/schema/tests.rs
The accounts store tests include an iterator over values.  We will need that in account databases, if we are to keep that test in the current form.  There seems no harm in having such an iterator so just add it.
* Add an iterator over accounts.
- This PR includes a simple test that inserts a few values and verifies that the account IDs from the iterator are as expected.
- The iterator will be used in this test: https://github.com/dfinity/nns-dapp/blob/main/rs/backend/src/accounts_store/tests.rs#L1378
I think this is not necessary; this is a small PR currently affecting tests only and has no user-facing changes.
=> Add an iterator over values

frontend/src/lib/components/sns-proposals/SnsProposalSystemInfoSection.svelte, frontend/src/lib/derived/sns-ns-functions-project.derived.ts, frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsModal.svelte, frontend/src/lib/pages/SnsProposals.svelte, frontend/src/lib/services/sns-vote-registration.services.ts, frontend/src/lib/stores/sns-functions.store.ts
The service `loadSnsNervousSystemFunctions` checked the dynamic derived store `createSnsNsFunctionsProjectStore` to check whether it should load more nervous functions or not.
If that store has data, then call to get the functions and load then in snsFunctionsStore is skipped.
That means, that we can't rely on the data in snsFunctionsStore, because it might not be populated.
At the moment, this is working because after getting the aggregator data, we also load the data in snsFunctionsStore. But, just like we stop loading snsQueryStore, we will also stop loading snsFunctionsStore.
In this PR, I changed the usage of snsFunctionsStore for the dynamic derived store `createSnsNsFunctionsProjectStore`.
* `` accepts rootCanisterId undefined or null. This make it easy to be used in components.
* …
=> GIX-1823: Use aggregator ns functions

CHANGELOG-Nns-Dapp.md, rs/backend/src/accounts_store.rs
We wish to be able to iterate over accounts in a consistent way so that we can migrate accounts from one schema to another in chunks.  `HashMap` does not guarantee a stable order for iterating whereas BTree does.  Let us convert, but be cautious of any change in cycle consumption.
Notes:
- The Candid serialization of `HashMap` and `BTreeMap` is the same: As a vector of `(key, value)` tuples.
- The pre-upgrade cycle count was last measured as 5% of the limit, so it is almost certainly not a concern.  It would be nice to have this available as a statistic in PRs though.
- `BTreeMap` does support [`Cursor`](https://doc.rust-lang.org/std/collections/btree_map/struct.Cursor.html) but unfortunately all the useful cursor API methods are still labelled experimental.  Why is this relevant? …
=> Change account storage from HashMap to BTreeMap

frontend/src/lib/stores/sns-finalization-status.store.ts, frontend/src/lib/utils/sns.utils.ts, frontend/src/tests/lib/stores/sns-finalization-status.store.spec.ts, frontend/src/tests/lib/utils/sns.utils.spec.ts, frontend/src/tests/mocks/sns-finalization-status.mock.ts
We want to add a new sns project status: Finalizing.
In this PR, I introduce the store where the data from the endpoint will be saved and a derived store with the logic to return whether the project is finalizing or not.
* New dynamic store creator: `getOrCreateSnsFinalizationStatusStore`.
* New dynamic derived store: `createIsSnsFinalizingStore`.
* Test new stores.
=> GIX-1841: Add sns finalization status stores

frontend/src/tests/e2e/sns-governance.spec.ts, frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts, frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts, frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
Rename some methods that were specific to a feature flag in Neuron Details POs.
* Rename some methods to not reference "newUI" or similar.
* Remove unused method `hasJoinFundCard`
=> Chore: Clean newUI methods of neuron detail PO

frontend/src/lib/components/neuron-detail/NnsAvailableMaturityItemAction.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.svelte, frontend/src/lib/components/neuron-detail/StakeItemAction.svelte, frontend/src/lib/components/neuron-detail/actions/IncreaseDissolveDelayButton.svelte, frontend/src/lib/components/neuron-detail/actions/IncreaseStakeButton.svelte, frontend/src/lib/components/neuron-detail/actions/NnsIncreaseStakeButton.svelte, frontend/src/lib/components/neuron-detail/actions/NnsStakeMaturityButton.svelte, frontend/src/lib/components/neuron-detail/actions/SplitNnsNeuronButton.svelte, frontend/src/lib/components/neuron-detail/actions/StakeMaturityButton.svelte, frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsIncreaseStakeButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsStakeMaturityButton.svelte, frontend/src/tests/lib/components/neuron-detail/StakeItemAction.spec.ts, frontend/src/tests/lib/components/neuron-detail/actions/IncreaseStakeButton.spec.ts, frontend/src/tests/lib/components/neuron-detail/actions/NnsIncreaseStakeButton.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/IncreaseSnsDissolveDelayButton.spec.ts, frontend/src/tests/page-objects/IncreaseStakeButton.page-object.ts
A "variant" prop was introduced to reused the same buttons when implementing a new UI for neuron details.
The old UI has already been removed.
In this PR, I remove the "variant" prop which is not needed anymore and set the buttons to "secondary".
* Remove "variant" prop in neuron related buttons.
* Remove tests regarding the variant prop.
Not necessary. Already covered by the changelog entry specifying cleaning components.
=> GIX-1759: Remove unnecessary variant prop

frontend/src/lib/modals/transaction/QrWizardModal.svelte, frontend/src/lib/modals/transaction/TransactionModal.svelte, frontend/src/lib/types/qr-wizard-modal.ts, frontend/src/tests/lib/modals/transaction/QrWizardModal.spec.ts
Using the QR code scanner requires adding an extra step to a `WizardModal` and switching back and forth between them.
This is currently done in `TransactionModal`.
I want to reuse the QR code scanner in the `DisburseNnsNeuronModal` so I want to streamline its usage.
1. Add `QrWizardModal` which manages going to and from the QR Code step.
2. Use `QrWizardModal` in `TransactionModal`.
3. Tests for `QrWizardModal`.
Tested manually on local that scanning a QR code when making a transaction still works.
not necessary for a small refactoring
=> Add QrWizardModal component

frontend/src/tests/lib/pages/SnsProposals.spec.ts
SnsProposals.spec doesn't depend on setting SNS projects. Therefore, setting it was unnecessary.
* Remove `setSnsProjects` call from `SnsProposals.spec`
Not necessary
=> GIX-1823: Remove setSnsProjects from SnsProposals.spec

CHANGELOG-Nns-Dapp.md, frontend/jest-setup.ts, frontend/src/tests/lib/pages/SnsProposals.spec.ts, frontend/src/tests/lib/routes/NeuronDetail.spec.ts, frontend/src/tests/lib/services/sns.services.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/utils/sns.test-utils.ts
Set ENABLE_SNS_AGGREGATOR_STORE `true` for tests.
* Set ENABLE_SNS_AGGREGATOR_STORE to `true` in jest.setup.ts
* Use snsQueryStore in sns services spec file. This should have never been setSnsProjects.
* Add more parameters to `aggregatorSnsMockWith`.
* Use aggregatorStore in setSnsProjects test util.
=> GIX-1823: Set sns aggregator store flag true for tests

frontend/src/lib/components/neuron-detail/NeuronFollowingCard/NeuronFollowingCard.svelte, frontend/src/lib/components/neuron-detail/NeuronProposalsCard.svelte, frontend/src/lib/components/neuron-detail/NeuronVotingHistoryCard.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronHotkeysCard.svelte, frontend/src/lib/components/ui/CardInfo.svelte, frontend/src/lib/components/ui/SkeletonCard.svelte, frontend/src/lib/components/ui/SkeletonCardContent.svelte, frontend/src/lib/pages/NnsNeuronDetail.svelte
The different sections of NnsNeuronDetails page had the vertical spacing set in different places. This made it easy to have a different spacing between them.
In this PR, all the spacing is set in the parent and the children have no vertical spacing.
* Add `noMargin` prop to CardInfo.
* Add `noMargin` prop to SkeletonCard.
* All sections and separators in NnsNeuronDetails are siblings in the html. Just like it looks like in the UI.
* Use the `noMargin` prop and remove the separator in NeuronFollowingCard, NeuronProposalsCard, NeuronVotingHistoryCard and NnsNeuronHotkeysCard.
* Moved the testnet only MakeProposalsCard above the NeuronVotingHistoryCard to have the beginning like the mainnet. I didn't move it below NeuronVotingHistoryCard because this one has an infinite scroll.
Only CSS …
=> GIX-1760: Fix spacings nns neuron detail

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/project-detail/ProjectStatus.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/services/sns-finalization.services.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/project-detail/ProjectStatus.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/services/sns-finalization.services.spec.ts
Sns projects perform a finalization process after the swap finishes. This process might take a few hours. During this time, the users don't get the neurons yet, even though the project has finished.
To improve the UX, we want to show a different status in the project detail page during this process takes place.
In this PR, the finalization information is loaded when a user visits the project detail page and also after participation.
* Use new store `isFinalizingStore` in ProjectStatus.svelte to show the new status or the lifecycle status.
* New service `loadSnsFinalizationStatus` to fetch and load the finalization in a store.
* Use the new service `loadSnsFinalizationStatus` in ProjectDetai page when the project is committed.
* Test new functionality in ProjectStatus
* Test that …
=> GIX-1841: SNS Project "finalizing" status

frontend/src/lib/components/neuron-detail/SnsPermissionsCard.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte
The different sections of SnsNeuronDetails page had the vertical spacing set in different places. This made it easy to have a different spacing between them.
In this PR, all the spacing is set in the parent and the children have no vertical spacing.
* All sections and separators in SnsNeuronDetails are siblings in the html. Just like it looks like in the UI.
* Use the noMargin prop and remove the separator in SnsNeuronPermissionsCard, SnsNeuronFollowingCard, SnsNeuronHotkeysCard.
Only CSS changes.
Not necessary.
=> GIX-1761: Align spacings sns neuron detail

frontend/src/lib/components/universe/UniverseAccountsBalance.svelte, frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts, frontend/src/tests/page-objects/Card.page-object.ts, frontend/src/tests/page-objects/SelectUniverseCard.page-object.ts, frontend/src/tests/page-objects/UniverseAccountsBalance.page-object.ts, frontend/src/tests/page-objects/UniverseLogo.page-object.ts
It's easier to modify the test when it uses page objects.
I want to modify the test in another PR in order to show the universe selector, but without balances, even when the user is not logged in.
1. Add required functionality to page objects.
2. Add required `data-tid` to `frontend/src/lib/components/universe/UniverseAccountsBalance.svelte`.
3. Use page objects in `frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts`
4. Use real `icpAccountsStore` instead of mocking it.
5. Set and expect explicit values for the balances.
yes
not necessary
=> Use page objects in SelectUniverseCard.spec.ts

frontend/src/lib/components/universe/SelectUniverseDropdown.svelte, frontend/src/tests/lib/components/universe/SelectUniverseDropdown.spec.ts, frontend/src/tests/page-objects/Card.page-object.ts, frontend/src/tests/page-objects/SelectUniverseDropdown.page-object.ts, frontend/src/tests/page-objects/UniverseAccountsBalance.page-object.ts, frontend/src/tests/page-objects/simple-base.page-object.ts
It's easier to modify the test when it uses page objects.
I want to modify the test in another PR in order to show the universe selector, but without balances, even when the user is not logged in.
1. Add test ID to `frontend/src/lib/components/universe/SelectUniverseDropdown.svelte`
2. Add `SelectUniverseDropdownPo`.
3. Add `isButton` to `CardPo`.
4. Allow passing a test ID to `.isPresent()` to check presence of a child with a specific ID.
5. Change `SelectUniverseDropdown.spec.ts` to use page object and specify and expect explicit values.
Manually checked that the dropdown still looks the same.
not necessary
=> Use page objects in SelectUniverseDropdown.spec.ts

frontend/src/lib/components/accounts/AccountCard.svelte, frontend/src/lib/pages/CkBTCAccounts.svelte, frontend/src/lib/pages/NnsAccounts.svelte, frontend/src/lib/pages/SnsAccounts.svelte, frontend/src/tests/lib/components/accounts/AccountCard.spec.ts, frontend/src/tests/page-objects/AccountCard.page-object.ts
Since https://github.com/dfinity/nns-dapp/pull/3268, every component that uses `AccountCard`, sets the `hash` prop.
So there is no reason to have it.
Remove the `hash` prop from `AccountCard` and assume it's always true.
pass
not necessary
=> Removed unused prop hash from AccountCard

scripts/canister_ids
The canister import command fails if there is no `canister_ids.json` file (a common case in a clean new repository).  Likewise if `JSON_FILE` is specified as the empty string (an uncommon case spotted when looking for the cause of the earlier error).
- Provide the variables `CREATE` and `JSON_FILE` with defaults so that bash does not crash on using an unassigned variable.
- Specify `nargs=0` for the `--create` flag.  As it is, it will try to consume the next argument as the value.  This will cause the command to fail or to parse the line otherwise than intended.
Before:
```
$ ./scripts/canister_ids
./scripts/canister_ids: line 33: CREATE: unbound variable
```
After:
```
$ ./scripts/canister_ids
./canister_ids.json is missing.
```
Before:
```
$ ./scripts/canister_ids …
```
=> Fix empty and missing parameters in canister import

frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts, frontend/src/tests/page-objects/InputRange.page-object.ts, frontend/src/tests/page-objects/InputWithError.page-object.ts, frontend/src/tests/page-objects/NeuronSelectPercentage.page-object.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
Currently we don't allow setting a dissolve delay on a neuron that would not result in voting power because the delay is too short.
We want to start allowing this.
But currently `SetDissolveDelay` is very complicated and also has several bugs:
1. Error messages are only updated on text input and not on slider input.
2. When the current dissolve delay is not a whole number of days, increasing it by less than a day to a whole number of days is allowed. But we still show an error message that it's not allowed even though the button is enabled.
3. The slider has second granularity but we only display days so we might display X days but that will not actually be the dissolve delay you get.
I want to simplify the code and fix the bugs but I want to make sure I don't break the component.
But …
=> Add tests for SetDissolveDelay component

frontend/src/tests/page-objects/NnsProposalList.page-object.ts, frontend/src/tests/page-objects/simple-base.page-object.ts
Once again we had an [e2e flake](https://github.com/dfinity/nns-dapp/actions/runs/6110153913/job/16582777946?pr=3280) because no proposal cards were present even though the skeleton cards had disappeared.
So I want to try a different approach for `waitForContentLoaded`.
1. Instead of waiting for the skeleton card to go away, wait for either at least one proposal card or the "no proposals" message to be present.
2. Support passing a `tid` parameter to `waitFor` to specify a specific child element, same as with `isPresent`, `click`, etc.
test only
not necessary
=> E2E: Wait for proposal card instead of skeleton card

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neurons/SetDissolveDelay.svelte, frontend/src/lib/components/neurons/SetNnsDissolveDelay.svelte, frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte, frontend/src/lib/utils/date.utils.ts, frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts, frontend/src/tests/lib/modals/neurons/IncreaseDissolveDelayModal.spec.ts, frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts, frontend/src/tests/lib/modals/sns/IncreaseSnsDissolveDelayModal.spec.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
`SetDissolveDelay.svelte` has several bugs:
1. Error messages are only updated on text input and not on slider input.
2. When the current dissolve delay is not a whole number of days, increasing it by less than a day to a whole number of days is allowed. But we still show an error message that it's not allowed even though the button is enabled.
3. The slider has second granularity but we only display days so we might display X days but that will not actually be the dissolve delay you get.
It is also overly complicated because:
1. The slider has granularity in seconds while the text input has granularity in days and both numbers need to be kept in sync.
2. Disabling the button has logic based on seconds while the error message has separate logic based on days.
3. There is a …
=> Fix and simplify SetDissolveDelay.svelte

rs/sns_aggregator/src/index.html
Make it more obvious how developers can integrate with SNS Aggregator.
* Add an example of how to fetch the SNS Aggregator data in the landing page.
Not necessary.
=> GIX-1874: Dev example SNS Aggregator landing page

.github/actions/build_nns_dapp/action.yaml, .github/actions/start_dfx_snapshot/action.yaml, .github/workflows/deploy-to-app.yaml, dfx.json
The snsdemo version is currently specified as a commit in `dfx.json`.  Unfortunately this version is not applied to the snsdemo snapshot.
- Use a release tag to specify which version the nns-dapp should use, instead of a commit.
- Use the release tag to get the sns snapshot.
See CI.
I think this is too minor a tweak to warrant a chnagelog entry.  No frontend or canister changes and only a minor operations tweak.
=> Snsdemo release

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/accounts/TransactionCard.svelte
The background of the Sent transaction icon is not visible. See screenshot.
* Change the background on dark theme of the send icon for transactions.
* Only UI changes.
=> GIX-1848: Fix Sent transaction icon background color dark

rs/sns_aggregator/src/index.html
Follow-up of #3295.
This PR propose a code highlighter for the "block of code" displayed in the Sns aggregator index web page and style the new section.
It also adds a sentence to highlight the fact that the aggregator is meant for developers.
Prismjs used to highlight the code is fetched from the [Juno's CDN](https://github.com/buildwithjuno/cdn) on the raw domain of the IC.
=> feat: highlight code in new block of Sns aggregator and style

CHANGELOG-Sns_Aggregator.md, rs/sns_aggregator/src/types/slow.rs
The logo to the SNS Metadata needs to be hardcoded by the frontend following a specific pattern.
In this PR, I add the relative path of the logo so that the logic of where the logo lives lies only in the SNS aggregator canister.
Another reason is because the logo is optional. Therefore, this way it's easier to know whether the logo is present or not. Otherwise, we would need to try to fetch the asset and check it.
* New field `logo` in `SlowMetadata`.
* Change `SlowMetadata::from` to use `UpstreamData` to access the root canister id.
Tests are skipped.
=> Feat: Add metadata logo path to SNS aggregator data

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/metrics/TotalValueLocked.svelte
TVL title text is not clearly visible in light theme. See screenshot of "Before".
The reason is that `--text2-color` was not present in the light theme.
The solution is to use `--description-color`. `--text2-color` will be removed because it's not used anywhere else.
* Change the color of TotalValueLocked to `--description-color`.
* Only CSS changes
=> GIX-1878: Fix TVL text color

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/universe/SelectUniverseCard.svelte
The logo of ICP in the token selector doesn't have enough contrast when user hovers or when it's the selected one.
In this PR, I add an outline to the logo to help with the contrast. See screencast.
* Use `noPadding` prop in Card for `SelectUniverseCard` and change the variable that sets the logo frame color on hover, focus and selected.
* Only CSS changes.
=> GIX-1864: Improve ICP logo token selector

CHANGELOG-Nns-Dapp.md, frontend/src/lib/constants/constants.ts, frontend/src/lib/utils/date.utils.ts, frontend/src/tests/lib/utils/date.utils.spec.ts
We use both `secondsToDuration` and `daysToDuration` to render the same time period so they should be consistent but currently they are not.
This PR fixes https://dfinity.atlassian.net/browse/GIX-1872.
It does not aim to fix https://dfinity.atlassian.net/browse/GIX-1770 which is still being discussed.
I think it's worthwhile to fix GIX-1872 and put a test in place that the rendering is consistent before we have a decision on GIX-1770.
1. Reimplement `secondsToDuration`.
2. Update tests for `secondsToDuration` for the new implementation.
3. Test that both functions return the same string for periods that are a whole number of days between 1 and 3000.
Extensive unit test are updated.
=> GIX-1872 Make secondsToDuration consistent with daysToDuration

frontend/src/lib/derived/debug.derived.ts, frontend/src/lib/directives/debug.directives.ts
To help debug possible problems in mainnet, we should add the snsAggregatorStore and snsQueryStore to the debug store to access the values stored there.
* Add `snsAggregatorStore` and `snsQueryStore` to `initDebugStore`.
I downloaded the JSON from localhost and the data was there.
Not necessary.
=> Chore: Add sns agg to debug store

frontend/src/lib/services/$public/sns.services.ts, frontend/src/lib/stores/sns.store.ts, frontend/src/lib/utils/sns.utils.ts, frontend/src/tests/lib/utils/sns.utils.spec.ts
Part of the response of `get_state` is the derived state, which we can also get from `get_derived_state`. Yet, the endpoint returns different fields and different precision for one of the fields (`sns_tokens_per_icp`).
When we were populating the snsQueryStore in the service `loadSnsProjects`, we were using first the data from the `get_state`, and right after we were updating it with the data from `get_derived_state`.
This caused that the sns summary from snsQueryStore and from snsAggregatorStore didn't match for some time.
* Use the data from `get_derived_state` in the first place instead of updating it afterward.
* The tests didn't cover the moment when the stores were different because it happens in the middle of the function. Yet, when I removed the call to `updateDerivedState`, the …
=> Fix: Partial different derived state in snsQueryStore

.config/spellcheck.dic, CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/downgrade-upgrade-test
The downgrade-upgrade test needs to be able to verify that accounts are preserved across schema updates.
- Make it possible to specify a wasm to downgrade to.  This way the test can be run with a wasm that implements the future schema `S0.early` and another, `undefined.late` that is not yet in production.
- Get account data; this was already present but commented out as prod did not have account data in a stable, usable form.
=> Update downgrade-upgrade test

frontend/src/lib/stores/sns.store.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/stores/sns.store.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts
We want to stop using snsQueryStore and use snsAggregatorStore instead.
To be sure this is safe, we will log a warning if they create different summaries.
PENDING: Merge #3312 
* Compare summaries from snsQueryStore and snsAggregatorStore in snsSummariesStore.
* New project util `differentSummaries`.
* Test new project util `differentSummaries`.
* Test that `snsSummariesStore` logs warning if summaires don't match.
Not necessary.
=> Chore: Add warn log if summaries are different

.github/actions/build_nns_dapp/action.yaml, .github/actions/release_nns_dapp/action.yaml, CHANGELOG-Nns-Dapp.md
We would like to monitor Wasm sizes.  We agreed that it might make sense to include the Wasm size printout that we currently have for merges to main in the nightly build, so that we would have a place where we can get the size periodically.  ([GIX-1857](https://dfinity.atlassian.net/browse/GIX-1857))  It turned out, though, that the nice printout we have when the build job is run is not readily accessible in a programmatic way.  We actually have plenty of runs, the trouble is access to the data.
* Log Wasm sizes.
* Include the list of Wasm sizes in release artefacts.
Before the assets printout looked like this:
```
02e20e8e4313facfd0b6caa0e7eca0c453c1884b878bce0e52611b1709dbc193  out/sns_aggregator.wasm.gz
e90b508eb38de35f2a836f610b12bd12e26432bf3ba98a92e5a76c08257891ef …
```
=> Include artefact sizes in printout

frontend/src/lib/components/neuron-detail/NeuronSelectPercentage.svelte, frontend/src/lib/modals/neurons/DisburseMaturityModal.svelte, frontend/src/lib/modals/neurons/NnsStakeMaturityModal.svelte, frontend/src/lib/modals/neurons/SpawnNeuronModal.svelte, frontend/src/lib/modals/neurons/StakeMaturityModal.svelte, frontend/src/lib/modals/sns/neurons/SnsDisburseMaturityModal.svelte, frontend/src/lib/modals/sns/neurons/SnsStakeMaturityModal.svelte, frontend/src/lib/utils/neuron.utils.ts, frontend/src/tests/lib/modals/sns/SnsDisburseMaturityModal.spec.ts, frontend/src/tests/lib/utils/neuron.utils.spec.ts
There was a bug when NeuronSelectPercentage was used for maturity above 1000.
That's because now we started calculating the maturity of the percentage. Yet, the maturity was passed as a string and then converted to a number. If the number was larger than 1000, then the string couldn't be converted successfully to a number.
The solution was to expect a number instead of a string.
* Change `formttedMaturity` in NeuronSelectPercentage for `availableMaturityE8s`. Change accordingly.
* Change where the NeuronSelectPercentage was used to pass the maturity as e8s instead of as a string.
* Remove unnecessary util `maturityPercentageToE8s`. Now it's a simple multiplication and division. No need to use an util for that. There is no logic to reuse.
* I added a test that fails in `main` but succeeds …
=> GIX-1889: Fix blank modal disburse maturity

frontend/src/lib/components/sns-neuron-detail/SnsViewActiveDisbursementsItemAction.svelte, frontend/src/lib/modals/sns/neurons/SnsActiveDisbursementsModal.svelte, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsViewActiveDisbursementsItemAction.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts, frontend/src/tests/mocks/sns-neurons.mock.ts, frontend/src/tests/page-objects/SnsViewActiveDisbursementsItemAction.page-object.ts
Disbursing maturity should count for the total maturity. Therefore, we also want to include the total maturity being disburse, instead of the count of disbursements.
* `formattedTotalMaturity` for sns neurons includes the disbursing maturity.
* New neuron util `totalDisbursingMaturity`.
* Use `totalDisbursingMaturity` in SnsViewActiveDisbursementsItemAction instead of the count.
* Use `totalDisbursingMaturity` in SnsActiveDisbursementsModal
* Add active disbursements in the test for SnsNeuronMaturitySection.
* Add field `activeDisbursementsE8s` to `createMockSnsNeuron`.
* Move a mock of active disbursements to sns-neurons.mock.
* Change tests accordingly in SnsViewActiveDisbursementsItemAction
* Add a test case for `formattedTotalMaturity`.
Covered already by the entry of disbursing …
=> GIX-1891: Include active disbursements in maturity section count

frontend/src/lib/utils/date.utils.ts
We want `daysToDuration` and `secondsToDuration` to be consistent when the number of seconds is a whole number of times the number of seconds in a day. So there is no need to have 2 completely separate implementations.
Make `daysToDuration` call `secondsToDuration`.
Existing test coverage is good and passes.
not necessary
=> Make daysToDuration call secondsToDuration

frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/lib/api/sns-ledger.api.ts, frontend/src/lib/services/ckbtc-accounts.services.ts, frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/lib/services/sns-accounts.services.ts
The type `IcrcTransferParams` is defined as
```
export interface IcrcTransferParams {
to: IcrcAccount;
amount: bigint;
memo?: Uint8Array;
fromSubAccount?: SubAccountArray;
createdAt?: bigint;
fee: bigint;
transfer: (params: TransferParams) => Promise<IcrcBlockIndex>;
}
```
The field `transfer` is only used by `executeIcrcTransfer` and every other place where `IcrcTransferParams` is used, it's used as `Omit<IcrcTransferParams, "transfer">`.
Remove `transfer` from `IcrcTransferParams` and at it back only to the params of `executeIcrcTransfer`.
`npm run build`
`npm run test`
All still pass.
not necessary
=> Remove transfer from IcrcTransferParams

frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsStakeMaturityButton.svelte, frontend/src/tests/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsStakeMaturityButton.spec.ts
Simplify testing and components.
Remove the usage of the neuron context in SnsAvailableMaturityItemAction.svelte.
* Expect the neuron as a prop.
* Adapt tests.
Not necessary.
=> Chore: Remove dependency on neuron context

frontend/src/lib/modals/sns/neurons/SnsDisburseMaturityModal.svelte, frontend/src/tests/lib/modals/sns/SnsDisburseMaturityModal.spec.ts
Fix broken setup in SnsDisburseMaturityModal test.
* SnsDisburseMaturityModal: Use the rootCanisterId passed instead of accessing the derived store of the page store.
* Set the tokenStore with a mock token. Fix the expected value.
Not necessary.
=> Fix: Setup SnsDisburseMaturityModal.spec

frontend/src/lib/components/neuron-detail/actions/DisburseMaturityButton.svelte, frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.svelte, frontend/src/lib/components/sns-neuron-detail/actions/SnsStakeMaturityButton.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/SnsNeuronDetail.svelte, frontend/src/lib/utils/sns-neuron.utils.ts, frontend/src/tests/lib/components/neuron-detail/actions/DisburseMaturityButton.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.spec.ts, frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.spec.ts, frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts, frontend/src/tests/page-objects/DisburseMaturityButton.page-object.ts
Check the fee to enable the disburse maturity button.
* DisburseMaturityButton: Change prop to `disabledText`.
* Add prop feeE8s to SnsDisburseMaturityButton
* Add prop feeE8s to SnsAvailableMaturityItemAction.
* Add prop feeE8s to SnsNeuronMaturitySection.
* New sns neuron util hasEnoughMaturityToDisburse
* Rename hasEnoughMaturityToStakeOrDisburse to hasEnoughMaturityToStake
* Use new util `hasEnoughMaturityToDisburse` and new prop `disabledText` in SnsDisburseMaturityButton.
* Change copy in "disburse_maturity_disabled_tooltip" i18n key.
* Adapt tests to new props.
* Adapt tests to `disabledText` prop name.
* Change test case in SnsDisburseMaturityButton.spec to check agains a maturity less than fee.
* New test case in SnsAvailableMaturityItemAction
Not worth an entry. Covered by …
=> GIX-1890: Check tx fee to disable disburse maturity button

CHANGELOG-Nns-Dapp.md, Dockerfile
docker-build script isn't working.
The problem seems to be when installing ic-wasm with cargo-binstall.
There was a new release of cargo-binstall and this one started breaking the build script.
In this PR, I install the previous version of cargo-binstall manually instead of relying in the installer script.
* In Dockerfile, install a specific version of cargo-binstall manually.
Tested in the gix machine.
=> Fix: Docker build

frontend/src/lib/modals/sns/neurons/SnsDisburseMaturityModal.svelte
Remove unused vars.
* Remove variable `maturity` and `destinationAddress` in SnsDisburseMaturityModal.
Not necessary.
=> Chore: Remove unused vars in SnsDisburseMaturityModal

frontend/src/lib/modals/neurons/StakeMaturityModal.svelte, frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte, frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsStakeMaturityButton.spec.ts
One test for SnsStakeMaturityButton was not correct. The test passed because the expected text (title of the modal) was the same text as the button.
In this PR, I added a testId to the modal and checked the presence of the modal with test id. The test failed.
The test also failed because it required a token in the store to be present. That is not necessary for the modal, but it was inside an `if` checking the presence of the token.
Therefore, in this PR, I also refactored the SnsNeuronModals to check for presence next to the type of the modal. This way it's easier to understand what is strictly necessary in each modal.
* Add testId to StakeMaturityModal.
* Move modals and conditions in SnsNeuronModals.
* Use `SnsNeuronContextTest` in `SnsStakeMaturityButton.spec` to check that modal is …
=> Fix: SnsStakeMaturityButton spec file

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/ui/Tooltip.svelte
Part of the tooltip of the disabled "Disburse" button is hidden behind the island.
That's because the tooltip uses the window to calculate whether there is enough space to the left or right. The problem happens when the container where the tooltip lives has `overflow: hidden`.
The tooltip already received a containerSelector. Therefore, it can use the container to calculate the space to the left and right.
* Use the container element instead of the width to calculate the space in the left or right of the tooltip.
* Purely CSS changes.
=> Fix: Tooltip is hidden if container has overflow hidden

frontend/src/lib/modals/neurons/DisburseMaturityModal.svelte, frontend/src/lib/utils/token.utils.ts, frontend/src/tests/lib/modals/sns/SnsDisburseMaturityModal.spec.ts, frontend/src/tests/lib/utils/token.utils.spec.ts, frontend/src/tests/page-objects/DisburseMaturityModal.page-object.ts
The range of the predicted tokens in the disbursing flow is an approximation of two decimals. By default, the decimals were rounded the standard way. That meant that the min range could be rounded up and give a wrong min, or the max range rounded down and give a wrong max.
In this PR, we add the `roundingMode` parameter to `formatToken` and use it for the range.
* Add `roundingMode` param to `formatToken`.
* Use param `roundingMode` for the range in DisburseMaturityModal confirmation screen.
* Add skipped tests because the new parameter is only supported in node 19 and we are in node 18.
Not necessary. Covered by an entry.
=> Fix: Better min and max range in disburse maturity

frontend/src/lib/pages/NnsProposals.svelte, frontend/src/tests/page-objects/NnsProposalList.page-object.ts
We've seen flakiness with `e2e/neurons.spec.ts` for a while. I think I finally figured out what happens.
The `NnsProposals` component loads neurons and proposals at the same time.
But once neurons are loaded, it loads proposals again. So it's possible
that the component goes back into loading state immediately after
proposals are loaded.
I was able to reproduce this by adding an artificial delay in `listNeurons`. Then you consistently see the skeletons reappear after the disappear.
Unfortunately the component is very complicated so it's not easy to fix without a major cleanup.
So until we have time to clean this up, we should work around the issue to avoid flakiness with the test.
Once proposals are loaded, wait 1 second and wait again for proposals to be loaded if necessary.
Still pass. …
=> E2E: Work around flakiness loading proposals

frontend/src/tests/e2e/images.spec.ts
We have an e2e test that tests that images load.
Sometimes images don't load and the test times out:
https://github.com/dfinity/nns-dapp/actions/runs/6245207559?pr=3337
I'm not sure why they don't always load on CI but let's retry the test when they don't.
1. Set a timeout on waiting for images to be loaded.
2. Retry the test up to 2 times when it fails.
Still pass, hopefully less flaky.
not necessary
=> E2E: Work around images not loading

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/launchpad/ProjectCard.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/e2e/sns-participation.spec.ts, frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts
Remove the word "Project" from the ProjectCard. Leave instead only the SNS name.
* Remove the "Project" word from ProjectCard.svelte.
* Remove i18n keys.
* Adapt test.
=> Feat: Remove "Project" from ProjectCard

frontend/src/lib/api/governance.api.ts, frontend/src/tests/lib/api/governance.api.spec.ts
We want to stake neurons using an ICRC-1 transfer when possible.
Support the new `stakeNeuronIcrc1` function in the governance API.
Improved existing test for `stakeNeuron` and added an analogous test for `stakeNeuronIcrc1`.
Will add when it's all hooked up.
=> Add governance API function stakeNeuronIcrc1

CHANGELOG-Nns-Dapp.md, frontend/src/lib/services/neurons.services.ts, frontend/src/tests/lib/services/neurons.services.spec.ts
We want to use ICRC-1 transfers when possible.
Note: I made a separate commit to duplicate the tests to make reviewing easier.
Use `stakeNeuronIcrc1` when `ENABLE_STAKE_NEURON_ICRC1` is enabled, except for when a hardware wallet is used.
Duplicated the existing tests. One group with ENABLE_STAKE_NEURON_ICRC1 disabled and one enabled.
=> Call stakeNeuronIcrc1 behind a feature flag

frontend/src/lib/api/icp-ledger.api.ts, frontend/src/tests/lib/api/icp-ledger.api.spec.ts
We want to use the ICRC-1 interface of the ICP ledger canister when participating in a swap or topping up a canister etc.
Add `sendIcpIcrc1` function to `icp-ledger.api` similar to the existing `sendICP` function on the same API.
Duplicated the existing tests for `sendICP` and added a test for the fee that can be passed in.
Will add when it's used.
=> Add sendIcpIcrc1 to ICP ledger API

frontend/src/lib/components/project-detail/CommitmentProgressBar.svelte, frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/getters/sns-summary.ts, frontend/src/tests/lib/components/project-detail/CommitmentProgressBar.spec.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts
We want to differentiate between direct and Neurons' Fund participation.
In this PR, the differentiation is done only in the progress bar.
This is not yet supported because it's missing the field in the API response. Therefore, I used a getter that returns undefined.
I don't think there is any need for a feature flag. As soon as the field is available, we should support it.
* Add a new sns summary getter `getNeuronsFundParticipation` that returns `undefined`.
* Change prop `value` in CommitmentProgressBar to two props `directParticipation` and `nfParticipation`.
* Use the new `segments` prop of the ProgressBar instead of the `value`.
* Use the new getter `getNeuronsFundParticipation` in ProjectCommitment to use new props in CommitmentProgressBar.
* Adapt tests of CommitmentProgressBar to …
=> GIX-1911: Split participation in progress bar

frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts
We want to add the deails of how much the NF is participating in a swap.
* New project util `getProjectCommitmentSplit` that returns a variant with the commitments split or only the total commitment.
* Add the details of NF and direct commitments below the current overall commitment in ProjectCommitment if NF commitment is present.
* Test new project util.
* Add test cases for new functionality.
Not yet worth an entry because the functionality is not available.
=> GIX-1911: Split total commitment

CHANGELOG-Nns-Dapp.md, frontend/src/lib/services/icp-accounts.services.ts, frontend/src/tests/lib/services/icp-accounts.services.spec.ts
When you use an ICRC-1 address, we make an ICRC-1 transfer but currently we use the generic ICRC-1 ledger interface for that, specifying the ICP ledger canister ID.
But the ICP ledger interface has its own ICRC-1 transfer method.
Use the direct `icrc1Transfer` method on the ICP ledger API instead of using the generic ICRC-1 ledger API.
Unit test updated.
Tested manually and noticed that for HW transactions, an empty memo is rendered as 422710814078008.
This will be fixed with https://github.com/dfinity/ic-js/pull/423
=> Use icrc1Transfer on ICP ledger canister

frontend/src/lib/api/sns-governance.api.ts, frontend/src/lib/services/sns-neurons.services.ts, frontend/src/tests/lib/api/sns-governance.api.spec.ts, frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Add `toAccount` to disburse maturity service and api.
* Add parameter `toAccount` to disbrse maturity sns governance api.
* Add `toAccountAddress` to disburseMaturity sns service. Convert string to ICRC account to send it to api.
* Add tests for disburseMaturity sns governance api (it was missing).
* Add test case for disburseMaturity sns service.
* I moved the `jest.clearMocks` to a main `beforeEach` in both files.
Not yet necessary. I'll add an entry when the new parameter is used from the UI.
=> GIX-1881: toAccount disburse maturity service & api

frontend/src/tests/e2e/proposals.spec.ts
E2e test `propopsals.spec.ts` [flaked](https://github.com/dfinity/nns-dapp/actions/runs/6275972422/attempts/1) because it expects < 20 votes on a proposal on line 189.
But on line 67 it casts 20 votes on some proposal. So the expectation only passes if those 2 proposals are different and the test doesn't do anything to make sure they are different.
The expectation was added in https://github.com/dfinity/nns-dapp/pull/3033 and the voting was added in https://github.com/dfinity/nns-dapp/pull/3224.
Make the expectation less specific by expecting any > 0 number of votes. If should have some votes because the proposer vote "yes" by default.
Pass. Hopefully less flaky.
not necessary
=> E2E: Don't expect < 20 votes on proposal

CHANGELOG-Nns-Dapp.md, frontend/src/lib/modals/neurons/DisburseMaturityModal.svelte, frontend/src/lib/modals/sns/neurons/SnsDisburseMaturityModal.svelte, frontend/src/tests/lib/modals/sns/SnsDisburseMaturityModal.spec.ts, frontend/src/tests/page-objects/AddressInput.page-object.ts, frontend/src/tests/page-objects/DisburseMaturityModal.page-object.ts, frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts, frontend/src/tests/page-objects/jest.page-object.ts, frontend/src/tests/page-objects/playwright.page-object.ts, frontend/src/tests/page-objects/simple-base.page-object.ts, frontend/src/tests/types/page-object.types.ts
Users can select a destination when disbursing maturity.
* Use `QrWizardModal` and `SelectDestinationAddress` in DisburseMaturityModal.
* Add props `rootCanisterId`, `token` and `selectedNetwork` to DisburrseMaturityModal.
* SnsDisburseMaturityModal passes new props to DisburseMaturityModal. `selectedNetwork` is left `undefined` on purpose because it means using ICRC accounts.
* Add `destinationAddress` to the `nnsDisburseMaturity` event caught by SnsDisburseMaturityModal.
* Use the new parameter `toAccount` of the disburse maturity service.
* Add a test case that user can disburse maturity to another account and that it gets an error if a non-ICRC account is used.
* Add `blur` method to jest-page-object.
* Add a few methods to the related POs.
=> GIX-1881: Add destination disburse maturity

frontend/src/lib/modals/neurons/DisburseMaturityModal.svelte, frontend/src/lib/modals/sns/neurons/SnsDisburseMaturityModal.svelte
Prop `tokenSymbol` is not necessary anymore. We already have the `token`.
* Remove the prop `tokenSymbol` from DisburseMaturityModal and use the `token.symbol` instead.
* Only refactor of props not test changes required.
Not necessary.
=> Chore: Refactor prop tokenSymbol in DisburseMaturityModal

CHANGELOG-Nns-Dapp.md
The command that splits the changelog after a release added both proposals at that commit, not just the `nns-dapp` proposal.
- Delete the aggregator proposal number from the `nns-dapp` changelog.
Note: There is a CI check that ensures that the changelog is not modified.  That will have to be overridden.
- Not applicable
=> Fix changelog

CHANGELOG-Nns-Dapp.md, scripts/nns-dapp/split-changelog
The `nns-dapp/split-changelog` command erroneously matches aggregator proposal tags.
- `nns-dapp` proposals are tagged `proposal-$PROPOSAL_NUMBER` e.g. `proposal-1234`.
- `sns_aggregator` proposals are tagged `proposal-$PROPOSAL_NUMBER-agg` e.g. `proposal-1234-agg`.
The pattern in `nns-dapp/split-changelog` matches both.
- Match only nns-dapp proposal tags.
The last release commit has the following tags:
```
max@sinkpad:~/dfn/nns-dapp/branches/fix-changelog (7)$ git tag --contains 05982aef608988cd2f88855723560203d288cc38
aggregator-prod
aggregator-release-candidate
nightly-2023-09-22
nightly-2023-09-23
nightly-2023-09-24
nightly-2023-09-25
nightly-2023-09-26
prod
proposal-124787
proposal-124788-agg
release-candidate
tip
```
The old pattern matched these tags:
``` …
```
=> Fix pattern for nns-dapp proposals

frontend/src/tests/lib/components/project-detail/CommitmentProgressBar.spec.ts, frontend/src/tests/page-objects/CommitmentProgressBarPo.page-object.ts
I merged the PR before making a requested change in a comment.
https://github.com/dfinity/nns-dapp/pull/3365#discussion_r1336020288
* Rename method in CommitmentProgressBarPo
Not necessary.
=> Chore: Rename CommitmentProgressBarPo method

frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/KeyValuePair.page-object.ts, frontend/src/tests/page-objects/ProjectCommitment.page-object.ts
Improve testing with a new PO for ProjectCommitment component.
* Wrap ProjectCommitment with TestIdWrapper.
* New PO: ProjectCommitmentPo.
* Trim the value in getValueText of KeyValuePairPo and change the return value. It was wrong always saying `null`. I don't know why TS didn't catch it.
* Add new params to `createSummary` helper.
* Use new PO and `createSummary` helper in ProjectCommitment.spec file.
Not necessary.
=> Chore: ProjectCommitmentPO

.github/actions/install_binstall/action.yaml, .github/actions/start_dfx_snapshot/action.yaml, .github/workflows/build.yml, .github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md, Dockerfile, dfx.json, scripts/setup
There have been several breakages in the last few hours caused by the latest `binstall` being unavailable.
* Specify the version of `binstall` in `dfx.json`, with the other tool versions.
* Create an action to install `binstall` with the specified version and use it, rather than other methods, wherever `binstall` is installed in GitHub workflows.
* Elsewhere, use the version from `dfx.json` directly.
- See CI
=> Get binstall version from dfx.json

frontend/src/lib/modals/neurons/DisburseMaturityModal.svelte, frontend/src/tests/lib/modals/sns/SnsDisburseMaturityModal.spec.ts
Disable the disburse maturity next step when no/wrong destination address.
- update disabled logic
- add address selection tests
not necessary
https://github.com/dfinity/nns-dapp/assets/98811342/d41b1ae0-c24c-4a0d-a891-169fe9055bca
https://github.com/dfinity/nns-dapp/assets/98811342/ac0aa937-5cef-4342-b2a5-0a73de1e246e
=> Disburse maturity validation update

rs/backend/src/accounts_store/toy_data.rs
We need sample accounts of various sizes for use in low level unit tests.
There is already code for creating toy accounts as part of an `AccountStore`, but this is unsuitable when we don't need the `AccountStore` or its execution environment.  We need just the banana, not the gorilla holding it or the jungle around the gorilla.
- Add test code for creating toy accounts.
- A test is included that checks that the toy account has the specified size.
=> Toy accounts for unit tests

rs/backend/src/accounts_store.rs
The `pub enum TransactionToBeProcessed` was replaced by `MultiPartTransactionToBeProcessed` in https://github.com/dfinity/nns-dapp/pull/83 and has been unused for over 2 years.
Keeping it around is confused.
Remove `TransactionToBeProcessed`.
The canister still builds.
not necessary
=> Remove unsed TransactionToBeProcessed

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/neuron-detail/NeuronConfirmActionScreen.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/modals/neurons/DisburseMaturityModal.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/neuron-detail/NeuronConfirmActionScreen.spec.ts, frontend/src/tests/lib/components/neuron-detail/NeuronConfirmActionScreenTest.svelte
Make the edit button label dynamic for `ConfirmActionScreen`.
- new prop `editLabel`
- set custom value for disburse maturity
Manually
not needed
=> Replace "Edit percentage" with custom label

CHANGELOG-Nns-Dapp.md, frontend/package-lock.json, frontend/src/lib/api/icp-ledger.api.ts, frontend/src/tests/lib/api/icp-ledger.api.spec.ts
ic-js was changed to rename the `memo` parameter on the ICRC-1 interface of the ICP ledger canister.
1. `npm run update:next`
2. Use the new parameter name.
3. Add a warning about the memos being different.
Updated
=> Bump ic-js; rename icrc1Memo

frontend/src/lib/components/ic/AmountDisplay.svelte, frontend/src/tests/page-objects/KeyValuePair.page-object.ts
https://github.com/dfinity/nns-dapp/pull/3379 had to add a `trim()` which shouldn't be necessary.
It was necessary because `AmountDisplay` renders an unnecessary space.
`AmountDisplay` has an optional copy icon. If the copy icon is rendered, we want there to be a space between the amount and the copy icon. But if there is no copy icon, there also shouldn't be a space.
I think this might be a bug in Svelte template parsing but we can work around it.
1. Render the space separating the amount and the copy icon inside the `{#if copy}` block.
2. Remove the `trim()` from `frontend/src/tests/page-objects/KeyValuePair.page-object.ts`
Pass
Also manually checked that it renders correctly with copy icon (in the wallet summary) and without (in the transaction history).
Try it here: …
=> Remove extra space from AmountDisplay

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/ui/SkeletonHeader.svelte, frontend/src/lib/components/ui/SkeletonHeading.svelte, frontend/src/lib/pages/NnsNeuronDetail.svelte, frontend/src/lib/pages/SnsNeuronDetail.svelte
Skeletons in the neuron details don't match the new headers.
* New SkeletonHeader and SkeletonHeading components.
* Use the new sleketon components in NnsNeuronDetails and SnsNeuronDetails.
Only UI changes while loading. Tests still pass.
=> Feat: New skeleton components

build-frontend.sh
In PR #3392 we aim to review the chunking strategy of the frontend dapp which results in an higher consumption of memory when the dapp is build. As a result, the CI is unable to run few jobs because not enough memory is allocated within the CI. For example see the result of this job: https://github.com/dfinity/nns-dapp/actions/runs/6325689226/job/17177726097?pr=3392
To overcome the issue, this PR set a larger memory using the option [--max-old-space-size](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) provided by NodeJS.
This job for example confirms the solution: https://github.com/dfinity/nns-dapp/actions/runs/6326554570/job/17180366956?pr=3392
The high usage of memory is confirmed by the team of Rollup for example in this …
=> build: increase JavaScript heap memory for CI build

frontend/src/lib/components/canister-detail/CanisterHeadingTitle.svelte, frontend/src/lib/components/canister-detail/CanisterPageHeader.svelte, frontend/src/lib/components/canister-detail/CanisterPageHeading.svelte, frontend/src/lib/components/common/PageHeading.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/CanisterDetail.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/canister-detail/CanisterHeadingTitle.spec.ts, frontend/src/tests/lib/components/canister-detail/CanisterPageHeader.spec.ts, frontend/src/tests/lib/components/canister-detail/CanisterPageHeading.spec.ts, frontend/src/tests/page-objects/CanisterHeader.page-object.ts, frontend/src/tests/page-objects/CanisterHeadingTitle.page-object.ts, frontend/src/tests/page-objects/CanisterPageHeading.page-object.ts
Change the canister details header to be more consistent with the new header in neuron details.
In this PR, I introduce, but not use the components needed to render it.
In another PR, I'll use them in the CanisterDetails and I'll change the tests in there as well.
* New component CanisterHeadingTitle.
* New component CanisterPageHeader.
* New component CanisterPageHeading that uses new component CanisterHeadingTitle.
* Check whether the "subtitle" slot is present in the PageHeading. Otherwise, there is an empty space because it uses flex and gap with an empty element.
* Test files and POs for CanisterHeadingTitle, CanisterPageHeader, CanisterPageHeading
Not yet. I'll add it with the PR that uses the components.
=> GIX-1859: New components for the new Canister Details page header

CHANGELOG-Sns_Aggregator.md
The aggregator changelog was invalid with "Proposal 124250" repeated and multiple empty sections.
It appears that the earlier entry corresponded to the actual [proposal 124250](https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=124250); that contains some empty sections that should have been purged but otherwise that section is correct.
The duplicate section is:
> Various minor style improvements: favicon, spacing, status "open" color and text clamp
This appears to match the rejected [proposal 124535](https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=124535) although that proposal has a different summary.
The proposal was rejected due to reproducibility issues, not due to any fundamental rejection by the community of the changes, so the changes from …
=> Fix aggregator changelog

frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts
We agreed with design and product to hide the split of direct and NF commitment until the NF commitment is more than 0.
* Change the condition to show the split to the NF commitment greater than 0.
* Remove unused helper `isFullProjectCommitmentSplit`.
I even did TDD in for this task. First I changed the test. It failed. Then I changed the code and see it pass 🚀 
* Change the description and expectation of the test case when NF is zero.
=> GIX-1931: Hide commitment split if NF participation is 0

.github/workflows/update-didc.yml, CHANGELOG-Nns-Dapp.md
The bot that updates `didc` to the latest release makes PRs without a meaningful description.  See [an example](https://github.com/dfinity/nns-dapp/pull/3403).
The PR description:
- Should broadly follow our usual template
- Should have separate sections for changes made by the bot and changes made by a human.
- Update the proposal text.
- The body is well formed:
```
max@sinkpad:~/dfn/nns-dapp/branches/doc-didc-update (18:56)$ yq -r '.jobs["didc-update"].steps[2].with.body' .github/workflows/update-didc.yml
max@sinkpad:~/dfn/nns-dapp/branches/doc-didc-update (24:39)$ 
```
- Here is an example, showing the actor being filled in: …
=> Better PR body

frontend/src/lib/components/ui/SkeletonHeading.svelte
The width of the SkeletonHeading was almost zero.
Problem: the width was set as %. But the parent's width is determined by the content.
* Set a width in pixels for title text in `SkeletonHeading`.
Not necessary.
Not necessary. New skeletons were recently introduced and this fix is covered by the entry of those.
=> Fix: SkeletonHeading width

scripts/nns-dapp/release-sop-test-html-in-template.json
There is a `release-sop` tests what happens when HTML is found.
But the mocking behavior for the test didn't cause that step to fail with non-zero exit code.
1. Fix the behavior of `no_html_in_templates` to return 1 instead of 0.
2. Update the expected output with `scripts/nns-dapp/release-sop.test --update`
Change is test only.
not necessary
=> Fix release-sop test

.github/workflows/checks.yml, CHANGELOG-Nns-Dapp.md
`scripts/dfx-nns-proposal-args.test` is failing.
Disable until we fix it.
* Comment the lines in the workflow that run the script.
Tests should be now green.
=> Chore: Disable NNS proposal args

scripts/nns-dapp/release-sop
When `release-sop` is tested, we provide mock behavior for the commands it executes.
Newlines are removed from the output provided in the mock behavior, using `| tr -d '\n'`.
But this is not necessary because we also pass `-n` to `echo` when outputting the output.
And it turns out that `| tr -d '\n'` actually removes inner newlines as well which is interfering with other improvements I want to make to the script.
Remove `| tr -d '\n'` applied to the mock output.
Still pass
not necessary
=> Don't trim newlines on mock outputs for release-sop

frontend/src/lib/components/canister-detail/CanisterHeadingTitle.svelte, frontend/src/lib/components/canister-detail/CanisterPageHeading.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/canister-detail/CanisterHeadingTitle.spec.ts, frontend/src/tests/lib/components/canister-detail/CanisterPageHeader.spec.ts, frontend/src/tests/lib/components/canister-detail/CanisterPageHeading.spec.ts, frontend/src/tests/lib/pages/CanisterDetail.spec.ts
The title "Balance unavailable" was not very user friendly when the user was not the controller.
Instead, the title will be now the canister name or the id when the user is not the controller. In that case, there is no need for the subtitle.
* Change the title in CanisterHeadingTitle when the user is not the controller. To access the name, I added the prop `canister`.
* Pass the `canister` prop to CanisterHeadingTitle in CanisterPageHeading.
* Add the logic of not the controller to render the PageHeading without title in CanisterPageHeading.
* Remove the `balance_unavailable` i18n key.
* Change and add test cases for new functionality in CanisterHeadingTItle.spec
* Change and add test cases for new functionality in CanisterPageHeading.spec
* Change and add test cases for new functionality …
=> Feat: Change canister detail page title

frontend/src/app.html
In Juno, I encountered a runtime issue in SvelteKit: "Cannot read properties of undefined (reading '$$')" along with a white screen of death in the production build. After reviewing my chunking strategy, I eventually identified the problem as a loading race condition within Svelte. This issue can be resolved by injecting the loader script tag within the body instead of the head, which is a common strategy for executing a script tag.
While we currently do not encounter this issue in the NNS dapp, I believe it's worth preparing for it in advance.
- move `SCRIPT_LOADER` in HTML page from `head` to `body`
=> Move script loader to body

frontend/package-lock.json
We have release v1.0.0 of all ic-js libs (see [release notes](https://github.com/dfinity/ic-js/releases/tag/v1.0.0)). This PR bump the next versions accordingly.
=> Bump ic-js v1.0.0-next

CHANGELOG-Nns-Dapp.md, declarations/nns_governance/nns_governance.did, dfx.json, scripts/update_ic_commit
The path to the `nns-governance` `.did` file listed in `dfx.json` is incorrect; it is a leftover from when the file was provided as part of a custom build of the NNS canisters.
- Add the `nns-governance` did file under `declarations` and update `dfx.json`
- Include the `nns-governance` candid file in the list of did files updated by `update_ic_commit`.
This canister call to list proposals now works:
```
dfx canister call nns-governance --network mainnet --query list_proposals "(record{include_reward_status= vec{}; omit_large_fields = opt true;limit=1;exclude_topic=vec{};include_all_manage_neuron_proposals=opt true;include_status=vec{};})"
```
- There are more `.did` files at old, invalid paths in `dfx.json` but they will not be covered in this PR.
=> Correct nns_governance did file

frontend/src/lib/components/project-detail/CommitmentProgressBar.svelte, frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/tests/lib/components/project-detail/CommitmentProgressBar.spec.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/page-objects/CommitmentProgressBarPo.page-object.ts
The new participation UI doesn't show a progress bar with commitments of NF and direct as different colors. Instead, if shows only the direct participation only.
In this PR, I remove the props, logic and tests that allow the CommitmentProgressBar to show multiple commitments.
I have also adapted the commitment when NF is present, to show only the direct participation. Yet, the UI still needs some changes that will be done in another PR.
* Change props `directParticipation` and `nfParticipation` for `participationE8s` in CommitmentProgressBar. Adapt logic inside.
* In ProjectCommitment, use the overall commitment or the direct commitment for the CommitmentProgressBar. I also moved the label and value of the NF commitment after the progress bar. Even though this UI is not available, I …
=> GIX-1922: Undo CommitmentProgressBar split commitments

CHANGELOG-Nns-Dapp.md, scripts/did2rs.sh
`did2rs` currently hand-parses command line arguments.  With `clap` this parsing can be standardized.
- Add the `clap` CLI parser to `did2rs`
- Add a flag to specify the canister name, but support the former positional argument as well.
- Add a flag to override the default location of the `.did` file.
See CI - usage should work exactly as before.
=> Use clap in did2rs

frontend/src/tests/lib/api/sns-aggregator.api.spec.ts
Increase test coverage of SNS aggregator api.
In this PR, check that when a page returns empty, the api function still works as expected.
* Add one test case to sns-aggregator.api.spec.
Not necessary
=> Chore: Add test when second page of agg is empty

frontend/src/tests/lib/pages/SnsWallet.spec.ts, frontend/src/tests/lib/routes/Neurons.spec.ts, frontend/src/tests/lib/services/sns-sale.services.spec.ts
Final motivation is to remove snsQueryStore.
In this PR, remove unnecessary references to snsQueryStore in some tests.
* Remove resetting snsQueryStore in three tests.
Tests still pass
Not necessary.
=> Chore: Remove unnecessary snsQueryStore reset

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/project-detail/CommitmentProgressBar.svelte, frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/components/project-detail/CommitmentProgressBar.spec.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/page-objects/CommitmentProgressBarPo.page-object.ts
Rearrange the UI and use the new fields for min and max direct participation.
* New prop to CommitmentProgress bar "color".
* New summary getters `getMiniumDirectParticipation` and `getMaximumDirectParticipation`.
* In the ProjectCommitment, move the section with direct participation progress bar above the overall commitment.
* In the ProjectCommitment, use a `KeyValuePairInfo` for the NF Commitment.
* Add two fields in `FullProjectCommitmentSplit` for max and minimum direct commitment.
* New project util `isCommitmentSplitWithNeuronsFund`.
* Check whether the commitment is `FullProjectCommitmentSplit` to show the direct commitment and NF values.
* Test that CommitmentProgress uses prop "color".
* Divide test cases in describes and change cases accordingly in ProjectCommitment.spec
* Add …
=> GIX-1922: New UI for participation

scripts/did2rs.sh
Traits are now provided to `did2rs` using a command line flag.  Unfortunately the traits are still hard wired.
Annoying, as I removed the hard-wired code but probably in the wrong branch or failed to commit the change. :-(
No longer hard-wire the traits.
The traits passed in by `./scripts/sns/aggregator/did2rs` are the same as the formerly hard-wired ones.  This should mean that there are no changes to the aggregator source code and patch files.  Furthermore consistency of this is checked in CI.
Locally, I am able to generate Rust code with different traits.
- Not needed, I think.
=> Fix: Do not hard-wire traits

frontend/src/tests/lib/services/sns.services.spec.ts
Final motivation: remove snsQueryStore.
In this PR, sns services spec file was filling up the snsQueryStore and then checking the values. The services being tested do not use the snsQueryStore. Therefore, it was a mistake to add those checks and those filling stores.
* Remove filling up and checking the snsQueryStore in sns.services.spec
Only changes in test files.
Not necessary.
=> Chore: Clean up sns services spec from snsQueryStore

frontend/src/lib/services/$public/sns.services.ts, frontend/src/tests/lib/services/_public/sns.services.spec.ts
The snsQueryStore is not read anymore. Therefore, writing to it is fruitless.
* Remove the code that fills the snsQueryStore in the `loadSnsProjects` sns service.
* Remove the checks and test cases of the snsQueryStore in the related test file.
Not necessary.
=> Chore: Remove writing to snsQueryStore in sns public services

frontend/package.json
Fix timezone for running vitest locally.
```
FAIL  src/vitests/lib/components/accounts/IcrcTransactionCard.spec.ts > IcrcTransactionCard > displays transaction date and time
AssertionError: expected 'Jan 1, 1970 1:00 AM' to include '12:00 AM'
❯ src/vitests/lib/components/accounts/IcrcTransactionCard.spec.ts:163:51
161|
162|     expect(div?.textContent).toContain("Jan 1, 1970");
163|     expect(normalizeWhitespace(div?.textContent)).toContain("12:00 AM");
|                                                   ^
164|   });
165|
```
=> Fix vitest timezone

rs/sns_aggregator/src/types/ic_sns_governance.patch, rs/sns_aggregator/src/types/ic_sns_governance.rs, rs/sns_aggregator/src/types/ic_sns_ledger.patch, rs/sns_aggregator/src/types/ic_sns_ledger.rs, rs/sns_aggregator/src/types/ic_sns_root.patch, rs/sns_aggregator/src/types/ic_sns_root.rs, rs/sns_aggregator/src/types/ic_sns_swap.patch, rs/sns_aggregator/src/types/ic_sns_swap.rs, rs/sns_aggregator/src/types/ic_sns_wasm.patch, rs/sns_aggregator/src/types/ic_sns_wasm.rs, scripts/did2rs.sh, scripts/sns/aggregator/did2rs.header
`didc2rs` changes every principal to `candid::Principal`.  This is unnecessary.
- Import `candid::Principal` in the the header.
- Remove the code that changes `Principal`.
See CI.
- Too minor, IMO, and covered by existing changelog entries about simplifying `did2rs`.
=> Use Principal instead of candid::Principal

frontend/__mocks__/$app/stores.ts, frontend/src/vitests/routes/app/accounts/layout.spec.ts, frontend/src/vitests/routes/app/accounts/page.spec.ts, frontend/src/vitests/routes/app/canister/page.spec.ts, frontend/src/vitests/routes/app/canisters/layout.spec.ts, frontend/src/vitests/routes/app/canisters/page.spec.ts, frontend/src/vitests/routes/app/layout.spec.ts, frontend/src/vitests/routes/app/neuron/page.spec.ts, frontend/src/vitests/routes/app/neurons/layout.spec.ts, frontend/src/vitests/routes/app/neurons/page.spec.ts, frontend/src/vitests/routes/app/proposals/layout.spec.ts, frontend/src/vitests/routes/app/root/page.spec.ts, frontend/src/vitests/routes/app/settings/layout.spec.ts, frontend/src/vitests/routes/app/settings/page.spec.ts, frontend/src/vitests/routes/app/wallet/page.spec.ts, frontend/src/vitests/routes/layout.spec.ts, frontend/vitest.setup.ts
- migrate routes related tests to vitest.
- mock `navigating` object of svelte (otherwise it throws an undefined issue)
=> Migrare routes tests to vitest

frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts
Use the summary fields for Neurons' Fund and direct commitments.
That doesn't mean that the functionality is available in mainnet. The functionality depends yet on two more fields that are not yet supported. The fields to give the min and max direct commitment.
* Use the summary field for NF commitment in `getNeuronsFundParticipation`.
* Use the summary field for direct commitment in `getProjectCommitmentSplit`. We didn't expect it to have a field, that's why we didn't use a getter initially. But better use it than rely on the calculation.
* Add new fields to test util `createSummary`.
* Tests don't rely on mocking the `getNeuronsFundParticipation` and instead build the desired summary.
Not yet.
=> GIX-1930: Use NF and direct commitment fields

CHANGELOG-Nns-Dapp.md, frontend/package.json
`npm run update:next` doesn't install the next dependencies for ledger-icp and ledger-icrc.
Instead, we can upgrade using `npm run upgrade:next`. There is no reason to have two scripts that do the same thing anyway, so I'm removing one.
* Remove update:next from packgage.json scripts
Not necessary.
=> Chore: Remove update:next script

frontend/src/lib/api/governace-test.api.ts, frontend/src/lib/components/neuron-detail/NnsNeuronTestnetFunctionsCard.svelte, frontend/src/lib/modals/neurons/NnsNeuronModals.svelte, frontend/src/lib/modals/sns/neurons/AddMaturityModal.svelte, frontend/src/lib/modals/sns/neurons/NnsAddMaturityModal.svelte, frontend/src/lib/pages/NnsNeuronDetail.svelte, frontend/src/lib/services/neurons.services.ts, frontend/src/lib/services/nns-neurons-dev.services.ts, frontend/src/lib/stores/busy.store.ts, frontend/src/lib/types/nns-neuron-detail.modal.ts
Test maturity related functionality easily with NNS neurons.
In this PR, add a card with a modal to add maturity to NNS neurons with the `update_neuron` endpoint in the governance test canister.
* New governance test api: `updateNeuron`.
* New card in nns neuron detail page: NnsNeuronTestnetFunctionsCard.
* New modal `NnsAddMaturityModal`.
* Add new modal in NnsNeuronModals only for Testnet.
* New dev service for nns neurons `addMaturity`.
Only dev environment feature.
Not necessary.
=> GIX-1928: Add maturity in NNS neurons

frontend/playwright.config.ts
Some tests have become quite long.
We also have a faster machine on CI then we used to have in the beginning.
So having a different timeout on CI vs. locally isn't really warranted anymore.
Set the Playwright timeout to 5 minutes regardless of whether the test runs locally or on CI.
CI passes
not necessary
=> Increase local Playwright timeout

CHANGELOG-Nns-Dapp.md, Cargo.lock, rs/proposals/Cargo.toml, rs/proposals/src/canisters/mod.rs, rs/proposals/src/canisters/sns_wasm.rs, rs/proposals/src/canisters/sns_wasm/api.rs, rs/proposals/src/lib.rs
We would like to free the nns-dapp from the code and libraries pulled in by the nns-sns-wasm canister.
* Remove the dependency on the `sns_wasm` canister from the proposals rendering crate.
* Derive the `nns-sns-wasm` canister types from `.did`.
Note: The `.didc` is from 2023-09-27 whereas the removed library is from `2023-08-01`.
There are existing Rust tests for proposal rendering; these should suffice.
We can get a rough measure of the number of dependencies in the proposal rendering crate with:
```
cargo tree -p proposals | wc -l
```
For the current release candidate, i.e. a recent commit on main, this yields 1555 entries.  In this branch this has dropped to 1172 and, critically, no longer contains the timer crate.
=> feat (proposal rendering): Get sns_wasm types from .did file

frontend/src/lib/components/canister-detail/CanisterPageHeading.svelte, frontend/src/lib/components/common/HeadingSubtitle.svelte, frontend/src/lib/components/common/PageHeading.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte
Avoid the problem with the PageHeading spacing when the subtitle was not defined.
At the same time, we learned that the PageHeading might get two subtitles; therefore, a slot without being wrapped makes it more flexible.
* Remove the `h4` wrapping the "subtitle" slot in PageHeading.
* New component "HeadingSubtitle" which has the style of the `h4` inside the PageHeading.
* Use the new component as subtitle slot for PageHeading in NnsNeuronPageHeading, SnsNeuronPageHeading and CanisterPageHeading.
Only refactor of purely UI components. Functionality didn't change which is confirmed by tests passing without extra changes.
Not necessary.
=> GIX-1860: Refactor PageHeading subtitle slot

frontend/src/lib/components/ic/GetTokens.svelte
We have a Get Tokens button which gives either ICP or SNS tokens.
It only gives SNS tokens if an SNS universe is selected and the faucet address has positive balance for that SNS.
Currently we also try to fetch the SNS faucet balance if the universe is not an SNS universe, for example with ckBTC.
This results in an error on the console.
Only try to fetch SNS faucet balance if the selected universe is an SNS.
Manually tried getting ICP while ckBTC or ICP or SNS without faucet balance universe is select.
And getting SNS tokens while an SNS with balance is selected.
not necessary
=> GetTokens: Don't check SNS balance for ckBTC

CHANGELOG-Nns-Dapp.md, frontend/src/lib/api/dev.api.ts, frontend/src/lib/components/ic/GetTokens.svelte, frontend/src/lib/services/dev.services.ts
We want to be able to test ckBTC locally and on CI.
We can get ckBTC by requesting a BTC deposit address from the minter and sending BTC to it.
Using the mock bitcoin canister we can fake send BTC to the deposit address.
1. When the ckBTC universe is selected show a "Get BTC" button instead of the "Get ICP" button.
2. When the button is clicked, we request a BTC address and tell the mock bitcoin canister to fake a transation to that address.
After this the use can click "Refresh Balance" in the ckBTC wallet to mint ckBTC into their account.
It's not much code so I didn't make it a dynamic import, but let me know if I should make it a dynamic import instead.
Tested manually with a new snsdemo snapshot.
=> Get BTC button

frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts, frontend/src/tests/lib/pages/NnsNeurons.spec.ts, frontend/src/tests/lib/pages/SnsNeurons.spec.ts
Our CI has issue with last few tests that were migrated to vitest. As a results, lots of build never ends - hangs forever.
Of those problematic tests we identitied two in https://github.com/dfinity/nns-dapp/actions/runs/6460468191/job/17538215849.
That's why this revert those two PRs for now.
- SnsNeurons.spec.ts
Failed to terminate worker while running /home/runner/work/nns-dapp/nns-dapp/frontend/src/vitests/lib/pages/SnsNeurons.spec.ts.
- CkBTCTransactionModal.spec.ts
Error: Global crypto was not available and none was provided. Please inlcude a SubtleCrypto implementation. See https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
ReferenceError: localStorage is not defined
❯ _openDbStore node_modules/@dfinity/auth-client/src/db.ts:17:29
❯ Function.create …
=> test: revert migrated tests

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/accounts/CkBTCWalletActions.svelte, frontend/src/lib/components/accounts/IcrcTransactionsList.svelte, frontend/src/lib/components/accounts/TransactionList.svelte, frontend/src/lib/components/accounts/WalletPageHeading.svelte, frontend/src/lib/pages/CkBTCWallet.svelte, frontend/src/lib/pages/NnsWallet.svelte, frontend/src/lib/pages/SnsWallet.svelte, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/lib/pages/NnsWallet.spec.ts, frontend/src/tests/lib/pages/SnsWallet.spec.ts, frontend/src/tests/page-objects/WalletPageHeading.page-object.ts, frontend/src/vitests/lib/components/accounts/CkBTCWalletActions.spec.ts, frontend/src/vitests/lib/components/accounts/WalletPageHeading.spec.ts
Adapt the wallet pages to the new header UI.
* Use the new WalletPageHeader and WalletPageHeading in NnsWallet.
* Use the new WalletPageHeader and WalletPageHeading in SnsWallet.
* Use the new WalletPageHeader and WalletPageHeading in CkBTCWallet.
* Add Tooltip with detailed balance to WalletPageHeading.
* Remove the menu bar from CkBTCWalletActions. Not needed anymore.
* Remove padding top in IcrcTransactionsList. Not needed anymore.
* Wrap TransactionsList with an element to prevent the parent from setting the spacing of the elements.
* Add a test in NnsWallet page to check that HW buttons are displayed.
* Remove tests regarding menu bar in CkBTCWalletActions.
* Fix NnsWallet.spec, SnsWallet.spec and CkBTCWallet.spec
=> GIX-1860: Change Wallet Header

frontend/src/vitests/lib/modals/canisters/RenameCanisterModal.spec.ts
Migrate tests to vitest.
In this PR, migrate RenameCanisterModal.
* Move RenameCanisterModal to vitest.
* Remove `blockAllCallsTo`. That it was passing before it was an error. This should be used with a fake at the same time. This test has no fakes; therefore, the call to `blockAllCallsTo` is not necessary.
Not necessary.
=> Chore: Migreate rename canister modal

CHANGELOG-Nns-Dapp.md, frontend/src/lib/components/project-detail/ProjectStatus.svelte, frontend/src/vitests/lib/components/project-detail/ProjectStatus.spec.ts
Improve the information on the status of a swap by changing the Tag style when the swap is open.
* Set the "intent" of the Tag to "success" when the swap is open.
* Test that the Tag has "success" when open and "info" when not.
=> GIX-1948: Use success intent for accepting participation tag

frontend/vitest.config.ts
Another possible solution to try to solve #3516.
Source: https://github.com/vitest-dev/vitest/issues/2008#issuecomment-1436415644
=> build: use atomics to synchronize vitest threads

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/canister-detail/CanisterHeadingTitle.svelte, frontend/src/vitests/lib/components/canister-detail/CanisterHeadingTitle.spec.ts, frontend/src/vitests/lib/components/canister-detail/CanisterPageHeading.spec.ts, frontend/src/vitests/lib/pages/CanisterDetail.spec.ts
Cycles are not displayed as T Cycles on canister detail page - i.e. value is 10000 too high.
- use cycles utils to format value
Is:
Fix:
=> T Cycles display on canister page

declarations/nns_governance/nns_governance.did, declarations/nns_registry/nns_registry.did, declarations/sns_swap/sns_swap.did, declarations/sns_wasm/sns_wasm.did, dfx.json, rs/sns_aggregator/src/types/ic_sns_swap.patch, rs/sns_aggregator/src/types/ic_sns_swap.rs, rs/sns_aggregator/src/types/ic_sns_wasm.patch, rs/sns_aggregator/src/types/ic_sns_wasm.rs
* Updated the NNS canister `.did` file imports and derived rust code.
* Changes in the Rust types.
* `.patch` files. I got the changes from the failing [test of the automatic changes](https://github.com/dfinity/nns-dapp/actions/runs/6480889411/job/17597322117?pr=3526#step:5:43).
=> GIX-1935: Add fields SNS aggregator

scripts/nns-dapp/release-sop
We moved unreleased changes in the changelog to a different file.
The Slack message in the `release-sop` script links to the changelog.
Update the Slack message in the `release-sop` script to point to the unreleased changelog.
no
not necessary
=> Update changelog link in Slack message

frontend/src/lib/types/sns.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/vitests/lib/utils/sns-aggregator-converters.utils.spec.ts
Stop using deprecated endpoint `get_state`.
In this PR, add the data from `get_sale_parameters` and `get_lifecycle` to SnsSummary.
* Add optional new fields `lifecycle` and `swapParams` to SnsSummary.
* Populate new fields in `convertDtoToSnsSummary`.
* Fix tests with new expectations.
Not necessary.
=> GIX-1823: Add swap params and lifecycle to SnsSummary

frontend/src/vitests/lib/routes/Neurons.spec.ts
Migrate `Neurons.spec` route test to vitest.
It does not seem to need particular changes and our improvement of the configuration seems to handle hanging process, so let's see in the CI.
=> Migrate remaining route test to vitest

frontend/package-lock.json, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/vitests/lib/utils/sns-aggregator-converters.utils.spec.ts
Support new fields for the Neurons' Fund enhancements.
In this PR, upgrade "next" dependencies and fix types.
Not in this PR, use the aggregator fields to populate the fields for SnsSummary. Here I'm only fixing the type inconsistencies by adding the fields empty.
* `package.lock.json` by `npm run upgrade:next`.
* Add new fields in the SNS Aggregator converters.
* Add new fields in the mocks.
* Fix tests for sns-aggregator.converters
=> GIX-1936: Upgrade next dependencies

frontend/src/lib/services/sns-sale.services.ts, frontend/src/vitests/lib/services/sns-sale.services.spec.ts
Migrate sns-sale services to vitest.
* Normal migration changes. Plus an extra `spyOnToastsShow.mockReturnValue(Symbol("toast-id"));` on beforeEach because the services rely on the return value of `toastsShow`. And with vi it was `undefined`.
Not necessary.
=> Chore: Migrate sns-sale services

frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Code in `describe` blocks is called before any of the tests are executed.
For example the `jest.spyOn(` at the top of the `"removeFollowee "` block is called after the `jest.spyOn(` at the top of the `"addFollowee "` but before any of the tests in the `"addFollowee "` blocks.
This can cause confusing behavior if the tests depend on code from its own `describe` block.
Additionally, when we migrate to vitest, defining mock behavior on the same function again, prevents an earlier spy from spying. This means the following fails in vitest while the equivalent does not fail in Jest:
```
const obj = { func: function() { } };
const spy1 = vi.spyOn(obj, 'func');
const spy2 = vi.spyOn(obj, 'func').mockImplementation(() => { });
obj.func();
expect(spy2).toBeCalled();
expect(spy1).toBeCalled();
``` …
=> Don't define mocks directly in describe blocks.

frontend/src/vitests/lib/services/icp-ledger.services.spec.ts
Migrate the icp-ledger services.
* Common migration changes.
* In a `beforeAll`, do not return the vi.spyOn and add `{ }` around it. That does something to the test which tries to do something with the SpyInstance.
Not necessary.
=> Chore: Migrate icp-ledger services

frontend/src/vitests/lib/services/sns-neurons.services.spec.ts
Migrate sns-neurons.services.spec.ts to vitest
- jest replaced by vi + done() deprecation replaced as recommanded by vitest
=> Migrate sns-neurons.services.spec.ts to vitest

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/launchpad/ProjectCard.svelte, frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte, frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/services/sns-finalization.services.ts, frontend/src/lib/stores/sns-finalization-status.store.ts, frontend/src/lib/utils/sns.utils.ts, frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts, frontend/src/tests/lib/components/launchpad/ProjectCardSwapInfo.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/services/sns-finalization.services.spec.ts, frontend/src/tests/lib/utils/sns.utils.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/ProjectCard.page-object.ts, frontend/src/tests/page-objects/ProjectCardSwapInfo.page-object.ts, frontend/src/tests/utils/sns.test-utils.ts
Issue reported by a user: https://forum.dfinity.org/t/bug-projectpage-sns-launchpad-direct-url/23029/7?u=lmuntaner
Add the "Finalizing" status in the Launchpad, when we show all the SNSes.
Yet, to do that, we need to fetch the finalizing status of all the projects.
To not make unnecessary calls, I added a check that the project has finished within the last week. This way we don't make calls to for open or old projects.
* Changes in `loadSnsFinalizationStatus` to not call the API unless it's possible that the project is finalizing. Also change the argument to accept another parameter `forceFetch`.
* Call `loadSnsFinalizationStatus` on mounting the ProjectDetailCard.
* Use `createIsSnsFinalizingStore` on ProjectCardSwap to render "Finalizing" instead of "Completed" when needed.
* Force …
=> Fix: Finalizing status in ProjectCard

frontend/src/lib/types/sns-aggregator.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
Add functionality after Neurons' Fund enhancements.
In this PR, we use the new fields from the SNS Aggregator when we convert the data to SnsSummary.
* Populate new fields `min_direct_participation_icp_e8s` and `max_direct_participation_icp_e8s` from the different places into the SnsSummary. Those fields are in the `Init` from `get_init`, but they are also in the `init` inside the `swap` and also in the `params` of the `swap`.
* Add the fields in the test case for the NF's enhancements fields. The other tests have those fields not populated and are converted to `[]` as it was hardcoded before.
=> GIX-1937: Use min max direct participation fields from aggregator

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/getters/sns-summary.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts
Add support for the new Neurons' Fund enhancements.
In this PR, the getters `getMinDirectParticipation` and `getMaxDirectParticipation` return the actual value from the SNS project.
* Return the values in the `init` field of the SnsSummary.
* Add two fields to createSummary helper.
* Remove the mocks of the getters and instead create a summary with the desired values.
=> GIX-1937: Use fields in min/max participation getters

.github/workflows/tag.yaml, CHANGELOG-Nns-Dapp-unreleased.md
There is a GitHub action that tags the tip of master, so that there is an unstable release called `tip` that always has the latest artefacts.  This _should_ be run whenever a PR is merged to `main`.
Unfortunately GitHub does not have workflow triggers that correspond to "PR merged to main".  It _does_ have a trigger for when a PR to main is closed, so we use that and then tag main if the PR was closed by merging.  So far, so good.  All that works fine.
However there is a final job in the workflow that checks that all (one) previous jobs have succeeded.  That has no conditional, so it runs and fails if a PR was closed without merging.  [Example.](https://github.com/dfinity/nns-dapp/pull/3552)
We can either make that final job conditional in the same way as the tagging step or - just delete …
=> fix: Rm exit step

CHANGELOG-Nns-Dapp-unreleased.md, rs/proposals/HACKING.md, rs/proposals/README.md
The proposal payload rendering code has been spun out to a separate crate.  To ease development, the crate has a command line tool so that payloads can be rendered locally without a network or any additional setup.  However the development process is still undocumented.
- Add documentation explaining what the proposals rendering crate is for and what the typical development flow looks like.
- There are no code changes.
- I have used commands similar to those advertised in the documentation.  There is no CI test that extracts the commands and runs them, though.
=> doc: How to use the proposal rendering crate

CHANGELOG-Nns-Dapp-unreleased.md, frontend/package-lock.json
There was a UI bug when the commitment was very low.
This was fixed in https://github.com/dfinity/gix-components/pull/312
* Changes in package.lock.json by running `npm run update:gix`.
Still passing.
=> GIX-1991: Fix low commitment progress bar

frontend/src/tests/lib/pages/SnsWallet.spec.ts
Remove services and store mocks in SnsWallet test to improve testing.
This will allow me to then test a transaction and check that the desired data is passed to the api.
* Remove all services and store mocks in SnsWallet.spec. Instead, mock the api layer.
Not necessary.
=> Feat: change SnsWallet

.github/actions/test-e2e/action.yml
I've noticed many times that the playwright-failure-results artifact contains only an index.html file and nothing else, which makes it useless for debugging.
When deliberately making an e2e fail, I was not able to reproduce this.
I'm not sure if Playwright fails to generate the right files or if GitHub fails to upload them.
List the files generated by Playwright, so that we compare the logs with the artifact to see if the problem is with Playwright or with Github.
I made a test fail deliberately and checked the GitHub Actions log.
not necessary
=> List playwright results

frontend/src/lib/components/accounts/SnsAccountsFooter.svelte, frontend/src/lib/modals/accounts/SnsTransactionModal.svelte, frontend/src/lib/pages/SnsWallet.svelte, frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts, frontend/src/tests/lib/pages/SnsWallet.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/utils/transaction-modal.test-utils.ts
Implement the MyTokens page.
In this PR, the SnsTransactionModal is decoupled from the page it is rendered. Instead, it receives the data needed as props.
* Add props `rootCanisterId`, `token` and `transactionFee` to SnsTransactionModal.
* Pass the new props where the modal was used: SnsWallet and SnsAccountsFooter.
* Pass props in the SnsTransactionModal and remove related mocks.
* Add sns setup in routes/Accounts.spec
Not necessary.
=> GIX-1986: Make SnsTransactionModal page agnostic

.config/spellcheck.dic, .github/workflows/checks.yml, CHANGELOG-Nns-Dapp-unreleased.md, scripts/spellcheck-changelog
Fixing a typo in a changelog entry can cause the line to be duplicated.  Better to get it right first time, every time.
* Update the `spellcheck-changelog` so that it runs against the new "unreleased" NNS-dapp changelog file.
* Run `spellcheck-changelog` in CI.
* Make corrections and add dictionary entries as required for the test to pass.
See CI
=> Spellcheck changelog

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
We want to use ICRC-2 (transfer approval) for ckBTC withdrawals.
Add `approveTransfer` to the ICRC ledger API layer.
Added unit tests with and without optional params.
Manually tested in another branch for actual ckBTC withdrawal to mock bitcoin canister.
=> Add approveTransfer to icrc-ledger API

CHANGELOG-Nns-Dapp-unreleased.md, scripts/dfx-snapshot-start
We are considering using DevEnv instead of testnet to test release candidates.
To make a local replica accessible remotely, one needs to pass `--host 0.0.0.0:8080` to `dfx`.
Add flag `--host` to `dfx-snapshot-start`. If set, the flag is passed on to `dfx`.
I ran `scripts/dfx-snapshot-start -s ~/snapshots/pinned-2023-10-05.tar.xz --host 0.0.0.0:8080` on my DevEnv, and it is accessible from https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
If I don't pass the flag, it gives "502 Bad Gateway".
=> Add --host to scripts/dfx-snapshot-start

CHANGELOG-Nns-Dapp-unreleased.md
There is an entry in the "Changed" section, but it hasn't yet been released from the backend.
Therefore, I'm moving it to "Unreleased".
* Changelog.
Only docs changes.
=> Fix: Changelog entry

frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte, frontend/src/lib/modals/accounts/AccountsModals.svelte, frontend/src/lib/modals/accounts/SnsReceiveModal.svelte, frontend/src/tests/lib/modals/accounts/SnsReceiveModal.spec.ts, frontend/src/tests/lib/pages/SnsWallet.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts
Create a page for all tokens.
In this PR, make the SnsReceiveModal agnostic of the page where it's rendered.
* Add props to SnsReceiveModal instead of relying stores that rely in the pageStore.
* Pass those props from AccountsModal, which is coupled with the page where it's rendered.
* Add a test in SnsWallet and Accounts route that the receive modal renders the logo of the project.
* Add missing test file for SnsReceiveModal.
Not yet.
=> GIX-1992: SnsReceiveModal page agnostic

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/api/ckbtc-minter.api.ts, frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
We want to support ICRC-2 (transfer approval) for BTC withdrawal.
Add `retrieveBtcWithApproval` to the ckbtc-minter API.
The code was also test manually in another branch which has a proof of concept of the full flow.
=> Add retrieveBtcWithApproval to ckbtc-minter API

frontend/src/lib/modals/common/FilterModal.svelte
Migrate to svelte 4.
In this PR, I remove the usage of `$$Generics` which is not supported in Svelte 4.
* Change the generic type in FilterModal for all the possible allowed types.
* Still passing.
Not necessary.
=> Chore: Remove generic

frontend/package-lock.json, frontend/src/lib/utils/anonymize.utils.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts, frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts, frontend/src/tests/lib/utils/sns.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts
Use new field for NF enhancements.
In this PR, upgrade ic-js dependencies.
* In package.lock.json with `npm run upgrade:next`.
* Fix mocks and converters with new fields.
* Add new field in expected value of the sns aggregator converters.
Not necessary.
=> GIX-1960: Upgrade next dependencies

frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte, frontend/src/lib/pages/CkBTCWallet.svelte, frontend/src/lib/types/wallet.context.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletContextTest.svelte
Using a context makes it difficult to see what is used where.
Some of these props might not be necessary and when we stop using them it should be clear that we can remove them completely.
1. Remove `CkBTCWalletContext`.
2. Pass `store, reloadAccount, reloadAccountFromStore` directly as props from `CkBTCWallet` to `CkBTCWalletFooter`
`CkBTCWalletContextTest.svelte` has been updated to make the existing test pass again.
Manual testing seems to work.
You can try it here: https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
not necessary
=> Use props instead of Context CkBTCWallet

CHANGELOG-Nns-Dapp-unreleased.md, config.sh, scripts/nns-dapp/test-config-assets/mainnet/arg.did
We want search engines to crawl the NNS Dapp.
There was a bug with the logic of the robots confused. We only want them to crawl mainnet.
* Change the `config.sh` to set as ROBOTS `""` on mainnet.
* Change the config test expected value for mainnet.
=> Fix: Allow robots to crawl

frontend/src/lib/components/tokens/MainWrapper.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/Tokens.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/routes/(app)/(nns)/tokens/+layout.svelte, frontend/src/tests/routes/app/tokens/layout.spec.ts
Implement the new Tokens page.
In this PR, setup the layout as expected in Figma.
This is the first time for this layout, but it seems to follow the rules of the current detail pages. Therefore, I applied the same rules and created a ticket to confirm them with Artem once he's back.
* New component `MainWrapper.svelte`. For now used only in the Tokens page and therefore only in `components/tokens`. It might be moved in the future.
* New i18n key for the Tokens page title.
* New `MainWrapper` in the `Tokens` page.
* Use the new i18n key for LayoutList in tokens layout.
* Add test for tokens layout.
Not necessary.
=> GIX-1982: Tokens page layout

frontend/package-lock.json
Upgrade `ic-js` version to make new proposals ([40&41](https://github.com/dfinity/ic-js/pull/413)) available.
Proposals tested manually against the testnet.
Not necessary
=> Upgrade ic-js to next-2023-10-23.1 version

frontend/src/lib/types/sns-aggregator.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
Support the new Neurons' Enhancements features.
In this PR, support the field `neurons_fund_participation` from the aggretagor.
* Add field `neurons_fund_participation` to SNS aggregator type.
* Support new field in the converter.
* Add a test where the field is present with `true`.
=> GIX-1960: Add new field from SNS Aggregator

.config/spellcheck.dic, .github/workflows/checks.yml, CHANGELOG-Nns-Dapp-unreleased.md
The NNS Dapp frontend npm version should match the backend cargo version.  This should be enforced in CI.
- Add a github check that the versions match.
See CI
- Here CI failed when the versions did not match: https://github.com/dfinity/nns-dapp/actions/runs/6614628537/job/17965039428
- CI should succeed now that they do match.
=> Test that nns-dapp has a consistent version

CHANGELOG-Nns-Dapp-unreleased.md, scripts/nns-dapp/release-sop
NPM audit provides issues as links.  Joining links with commas makes them into a single, long URL to a non-existent location.
- Join npm audit URLs with spaces
None: It doesn't appear to be possible to run the npm audit step without running everything before it in the release command.
=> fix: Join URLs with spaces

frontend/src/lib/components/project-detail/ProjectCommitment.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/projects.utils.ts, frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts, frontend/src/tests/lib/utils/projects.utils.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts
If the participation of the NF is not requested in a swap, we want to display a suited message.
* Change the field `nfCommitment` in `FullProjectCommitmentSplit` to also accept a `null`.
* Change logic in project util `getProjectCommitmentSplit` to return `null` for `nfCommitment` when NF participation is not requested.
* In ProjectCommitment, check whether `nfCommitmentE8s` is `null` to show "N/A".
* Add i18n key for "N/A".
* Add a test in ProjectCommitment for new case.
* Add two tests in `getProjectCommitmentSplit` that use the new field and logic.
Not yet published. Part of another entry.
=> GIX-1939: Use NF participation field to show N/A

CHANGELOG-Nns-Dapp-unreleased.md, Cargo.lock, rs/backend/Cargo.toml, rs/backend/src/accounts_store/schema/accounts_in_stable_memory.rs
We would like to use the variable memory sizes introduced in `ic-stable-structures 0.6.0`
- Update `stable-structures` to version `0.6.0`
- Update the code to match:
- Instead of having a separate `BoundedStorable` trait, `stable-structures` now has a `BOUND` in the `Storable` trait.
Existing tests should suffice.
=> Bump stable structures

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/neurons/NnsNeuronDetailCard.svelte, frontend/src/tests/lib/components/neurons/NnsNeuronDetailCard.spec.ts, frontend/src/tests/page-objects/NnsNeuronDetailCard.page-object.ts
A i18n key was changed to replace a value instead of concatenating strings.
A usage of this key was forgotten and didn't replace the value.
* Use `replacePlaceholders` for key "neurons.ic_stake" in NnsNeuronDetailCard.svelte.
* Add a check of the key in the related test case in NnsNeuronDetailCard.spec.
* Add a method in NnsNeuronDetailCardPo to get the neuron stake key.
=> Fix: Merge neurons label

frontend/src/lib/components/launchpad/ProjectCard.svelte, frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte, frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts, frontend/src/tests/lib/components/launchpad/ProjectCardSwapInfo.spec.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/page-objects/ProjectCard.page-object.ts, frontend/src/tests/page-objects/ProjectCardSwapInfo.page-object.ts
Improve testing.
In this PR, migrate the test files for ProjectCard and ProjectCardSwapInfo to use page objects.
* Add a couple of data-tid to elements in ProjectCard and ProjectCardSwapInfo.
* Add methods to ProjectCardPo and ProjectCardSwapInfoPo.
* Add new fields to test helper `createMockSnsFullProject`.
* Rewrite tests that weren't using PO and the helper.
Not necessary.
=> Chore: Refactor ProjectCard and ProjectCardSwapInfo tests

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/accounts/SelectNetworkDropdown.svelte
When sending ckBTC you can enter either a ckBTC address or a BTC address.
We derive the "network" (Internet Computer/Bitcoin) from the address.
This is debounced so there is a small delay.
The derivation does not require any network requests, and once the network is derived we don't change it (if you later change to an address to a different network, we consider it invalid unless you change the network manually), so this delay does not prevent any jarring experience.
So I see no reason to have the debounce there.
Additionally it makes unit testing slightly harder so there is a benefit in removing the debounce.
Remove the debounce on deriving the network from the address.
Removing it didn't cause any tests to fail so it wasn't tested before.
Manual testing looks good and can be tried here:
=> Remove debounce on deriving network from BTC address

rs/backend/src/ledger_sync.rs
There was a bug when we have an approve transaction with amount zero.
In this PR, we catch errors decoding blocks and ignoring when an error is found.
* Identify if there is an error decoding blocks and ignore if so.
No tests.
=> fix: zero approve workaround

CHANGELOG-Nns-Dapp-unreleased.md, rs/backend/src/ledger_sync.rs, rs/backend/src/perf.rs, rs/backend/src/perf/tests.rs
Some special, zero-value, transaction types currently fail to parse.  We would like visibility of which transactions fail to parse.
* Keep a bounded vector of exceptional transaction IDs.
There is a unit test that verifies that the list does not exceed the limit and that it retains the most recent transactions.
=> Keep a list of exceptional transactions

frontend/package-lock.json, frontend/src/lib/components/accounts/CkBTCWalletFooter.svelte, frontend/src/lib/components/layout/Footer.svelte, frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte, frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/page-objects/CkBTCReceiveModal.page-object.ts, frontend/src/tests/page-objects/CkBTCTransactionModal.page-object.ts, frontend/src/tests/page-objects/CkBTCWallet.page-object.ts, frontend/src/tests/page-objects/CkBTCWalletFooter.page-object.ts, frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts, frontend/src/tests/page-objects/TransactionForm.page-object.ts, frontend/src/tests/page-objects/TransactionModal.page-object.ts, frontend/src/tests/page-objects/WalletPageHeader.page-object.ts, frontend/src/tests/page-objects/jest.page-object.ts, frontend/src/tests/page-objects/playwright.page-object.ts, frontend/src/tests/types/page-object.types.ts
Making the test more readable.
1. Use page objects in `CkBTCWallet.spec.ts`.
2. Add test IDs where necessary.
3. Add necessary methods to exiting page objects.
4. Add new page objects.
5. In `frontend/src/tests/page-objects/SelectDestinationAddress.page-object.ts` check whether the dropdown input is present before trying to check the state of the checkbox. In some contexts there is no checkbox and if the input is already the type of input we need (dropdown vs. text), this is fine.
6. Add missing types to `frontend/src/tests/page-objects/WalletPageHeader.page-object.ts`
7. Add `innerHtmlForDebugging` to PageObjectElement to help probe the state of an element when debugging.
yes
not necessary
=> Use page objects in CkBTCWallet.spec.ts

rs/backend/nns-dapp-exports-production.txt, rs/backend/nns-dapp-exports-test.txt, rs/backend/nns-dapp.did, rs/backend/src/main.rs
We keep a list of exceptional transactions; we would like to be able to access it.
* Add a query method to get the list.
There is a PR to add the NNS Dapp ledger candid to the repo.  When that has been merged it will be possible to write meaningful tests.
- Covered sufficiently by an existing changelog entry about storing this data.
=> API to get exceptional transactions

rs/backend/src/perf.rs, rs/backend/src/stats.rs, scripts/nns-dapp/e2e-test-metrics-present.keys
We would like to have visibility of the number of exceptional transactions and potentially alerts for their number.
Provide a metric with a count of the number of stored exceptional transactions.
Note: If the exceptional transactions log ever becomes full, this metric will plateau.  If that happens before we switch to the index canister we may need revise this statistic, e.g. with a dedicated counter.
Awaiting #3629 to write an e2e test.
- Covered by an existing changelog entry
=> Include exceptional transactions in stats

CHANGELOG-Nns-Dapp-unreleased.md
The entry "Added approveTransfer in icrc-ledger API." is already in the release CHANGELOG, [here](https://github.com/dfinity/nns-dapp/blob/bf1eeaf0f49b5002a3c68b95d068de03a1f72a19/CHANGELOG-Nns-Dapp.md?plain=1#L38).
But [this commit](https://github.com/dfinity/nns-dapp/commit/c6a5f4d3262b914368278bd16a7c0d825a026282) put it back into the the unrelease CHANGELOG as well, probably by accident.
Remove the unwanted entry.
no
=> Remove wrong CHANGELOG entry

CHANGELOG-Nns-Dapp-unreleased.md, rs/backend/src/accounts_store.rs, rs/backend/src/accounts_store/tests.rs
[Here](https://github.com/dfinity/nns-dapp/blob/5642420e1cadc0fe4c80c11ed2be9d34293c8630/rs/backend/src/accounts_store.rs#L794) we treat TransferFrom the same as Transfer and turn into a `Send` or a `Receive`. But [here](https://github.com/dfinity/nns-dapp/blob/5642420e1cadc0fe4c80c11ed2be9d34293c8630/rs/backend/src/accounts_store.rs#L821) we pass the transaction type which might be TransferFrom . But [in the frontend](https://github.com/dfinity/nns-dapp/blob/5642420e1cadc0fe4c80c11ed2be9d34293c8630/frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js#L87), we don't know TransactionType TransferFrom and thus it fails to decode the transaction.
Use transaction type `Transfer` on the `Send` or `Receive` created from a `TransferFrom`.
Added a test with a `TransferFrom` and check that it get …
=> Use transaction type Transfer for Send/Receive derived from TransferFrom

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/neurons/ConfirmDissolveDelay.svelte, frontend/src/lib/components/neurons/InputRangeDissolveDelay.svelte, frontend/src/lib/components/neurons/RangeDissolveDelay.svelte, frontend/src/lib/components/neurons/SetDissolveDelay.svelte, frontend/src/lib/components/neurons/SetNnsDissolveDelay.svelte, frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte, frontend/src/lib/components/ui/DayInput.svelte, frontend/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte, frontend/src/lib/modals/neurons/NnsStakeNeuronModal.svelte, frontend/src/lib/utils/date.utils.ts, frontend/src/tests/lib/components/neurons/ConfirmDissolveDelay.spec.ts, frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts, frontend/src/tests/lib/components/ui/DayInput.spec.ts, frontend/src/tests/lib/components/ui/DayInputTest.svelte, frontend/src/tests/lib/modals/neurons/IncreaseDissolveDelayModal.spec.ts, frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts, frontend/src/tests/lib/modals/sns/IncreaseSnsDissolveDelayModal.spec.ts, frontend/src/tests/lib/utils/date.utils.spec.ts, frontend/src/tests/page-objects/RangeDissolveDelay.page-object.ts, frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
There is a bug raised in the [forum](https://forum.dfinity.org/t/changing-future-max-lock-up-for-sns-1-dkp/23576/34).
This screen has already been fixed with other bugs. The source of the bugs is the duality of seconds and days and synchronizing the slider with the input.
In this PR, we remove the slider and show a read-only progress bar instead.
We use days to be user friendly, but the code uses the values in seconds.
* New component RangeDissolveDelay instead of the InputRange.
* Days are not managed in SetDissolveDelay, instead in the child components DayInput and RangeDissolveDelay.
* New props and functionality in DayInput, like managing Min and Max buttons.
* Change delayInSeconds of ConfirmDissolveDelay to `bigint` to avoid issues with decimals.
* Remove rounding in …
=> Fix: Dissolve Delay Max

frontend/src/lib/components/project-detail/ProjectProposal.svelte, frontend/src/lib/components/proposals/ProposalCard.svelte, frontend/src/lib/getters/sns-summary.ts, frontend/src/lib/i18n/en.json, frontend/src/lib/pages/ProjectDetail.svelte, frontend/src/lib/types/i18n.d.ts, frontend/src/tests/lib/components/project-detail/ProjectProposal.spec.ts, frontend/src/tests/lib/pages/ProjectDetail.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/utils/sns.test-utils.ts
Users can easily find the proposal that opened a swap.
* A new ProjectProposal component
* Move the ProjectMetadataSection outside of the grid in ProjectDetail. The grid is used for the other sections.
* Render the new component `ProjectProposal` in ProjectDetail below the `ProjectInfoSection`.
* Add getters `getProjectProposal` to get the proposal id or a summary. This will be useful because we might want to hardcode the proposals before 1-Proposal was deployed.
* Test the new component ProjectProposal.
* Add a test to ProjectDetail when the project has a related NNS proposal id in the information it renders a proposal card.
* Add nnsProposalId to helpers.
=> GIX-2018: Add proposal card project detail

CHANGELOG-Nns-Dapp-unreleased.md, dfx.json, frontend/src/tests/utils/e2e.test-utils.ts
The current used version of Internet Identity is from April. It has a bug where it tries to connect to mainnet when it doesn't recognize the FE URL. This prevents us from using it on a DevEnv.
1. Use the latest snsdemo snapshot which uses version 2023-10-27 of Internet Identity.
2. Update `signInWithNewUser` to the new ii UI.
Pass on CI
=> Update E2E tests to new version of Internet Identity

frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/utils/module.test-utils.ts
It's easier to refactor code if the test mocks lower layers because we don't care which service calls the API.
1. Stop mocking several services in `CkBTCWallet.spec.ts`
2. Instead mock the necessary APIs and block non-mocked calls to those APIs
3. In `beforeEach`, reset stores that are filled by the service layer
4. Use `resetIdentity` instead of `mockAuthStoreSubscribe`
5. Merge the tests that the spinner is visible/not visible into one test where the spinner starts visible and then goes away
6. Fix an error message about using `jest.mock` to say `vi.mock` instead
Pass
not necessary
=> Mock API layer in CkBTCWallet.spec.ts

frontend/src/lib/components/proposal-detail/ProposalProposerPayloadEntry.svelte, frontend/src/lib/utils/utils.ts, frontend/src/tests/lib/utils/utils.spec.ts
Add array support to `expandObject` util.
- Returns array as array, not an object.
Extended.
Not necessary
=> fix: expandObject to respect arrays

.github/workflows/checks.yml, .github/workflows/deploy-to-app.yaml, .github/workflows/reproducible-assets.yaml, CHANGELOG-Nns-Dapp-unreleased.md
We're moving away from using `curl ... install.sh` in GitHub Actions, in favor of `dfinity/setup-dfx`
dfx install step in 3 workflow yml files
hoping it will be covered by CI
=> ci: use `dfinity/setup-dfx` to install `dfx`

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/tests/lib/components/launchpad/ProjectCard.spec.ts, frontend/vitest.setup.ts
This [test failure](https://github.com/dfinity/nns-dapp/actions/runs/6730359901/job/18292918007) seems to be the result of a unit test making a real request:
```
Server returned an error:
❯ src/tests/lib/components/launchpad/ProjectCard.spec.ts > ProjectCard > not signed in > should not display a spinner when the swapCommitment is not loaded
Code: 400 (Bad Request)
Body: Specified ingress_expiry not within expected range: Minimum allowed expiry: 2023-11-02 09:03:58.649355448 UTC, Maximum allowed expiry: 2023-11-02 09:09:28.649355448 UTC, Provided expiry:        2023-10-24 09:28:28 UTC
Retrying request.
```
Unit test should never (try to) make actual network requests.
This PR tries to catch it when a unit test tries to call `global.fetch`. Strangely there seems to be some interference …
=> Don't call global.fetch from unit tests.

scripts/dfx-snapshot-start
When you start a snapshot with `scripts/dfx-snapshot-start` your current `dfx` configuration is moved into a backup directory. The name of this directory contains a timestamp. But this timestamp is not very useful in figuring out when the backup was made because it is in seconds instead of a human readable date format.
The similar script `dfx-snapshot-install`, does use a human readable date format [here](https://github.com/dfinity/nns-dapp/blob/d92dc292e86eb73f02a2954488e1c099613563ba/scripts/dfx-snapshot-install#L85).
Use a human readable date format in `scripts/dfx-snapshot-start`.
Ran the script manually and checked the restore directory.
not necessary
=> Use a human readable timestamp in the snapshot restore dir

.github/actions/release_nns_dapp/action.yaml, CHANGELOG-Nns-Dapp-unreleased.md
The `prod` releases should be public.  In particular, CI expects the `aggregator-prod` to be public.
- Add the two `prod` releases to the set  of releases that should be public.
None
=> fix: Make the prod releases public

frontend/src/lib/i18n/en.json
Improve the text that explains the new Neurons' Fund commitment.
* Edit the value of an i18n key.
Not necessary.
Not necessary. Not seen by any user yet.
=> Feat: Improve text for NF commitment

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/canisters/ic-management/ic-management.errors.ts, frontend/src/tests/lib/canisters/ic-management.canister.spec.ts, frontend/src/tests/lib/canisters/ic-management.errors.spec.ts
There was a bug where the user would see a loading skeleton instead of the canister name when they were not the controllers.
The cause of this bug was a change in the error message from the IC Management canister when the caller is not the controller.
The error message is parsed and expects a certain structure and wording.
I also changed splitting the error message to get the error code line. This was not the cause of the bug, because the code checked whether 403 was in the error message. But that would not be accurate because 403 could be part of a request id.
* Change the `mapError` function for the IC Management canister.
* Added a test with an up to date error message.
=> Fix: Canister title when not controller

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte, frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
By using ICRC-2 for BTC withdrawal we can't transfer to the wrong account because it's the minter itself that makes the transfer.
When `ENABLE_CKBTC_ICRC2` is enabled use `convertCkBTCToBtcIcrc2` instead of `convertCkBTCToBtc` and tell the `ConvertBtcInProgress` component to use the ICRC-2 steps.
1. In `frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts` duplicate the tests that expect a call to `convertCkBTCToBtc` and expect a call to `convertCkBTCToBtcIcrc2` instead if `ENABLE_CKBTC_ICRC2` is enabled.
2. In `frontend/src/tests/lib/pages/CkBTCWallet.spec.ts` duplicate the tests that expect a call to `icrcLedgerApi.icrcTransfer` and expect calls to `icrcLedgerApi.approveTransfer` and `ckbtcMinterApi.retrieveBtcWithApproval` instead if `ENABLE_CKBTC_ICRC2` is enabled. …
=> Use ICRC-2 in BTC withdrawal

frontend/src/lib/components/common/JsonPreview.svelte, frontend/src/lib/components/common/RawJson.svelte, frontend/src/lib/components/common/TreeJson.svelte, frontend/src/lib/components/common/TreeJsonValue.svelte, frontend/src/lib/components/proposal-detail/ProposalProposerActionsEntry.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/json.utils.ts, frontend/src/lib/utils/utils.ts, frontend/src/tests/lib/utils/utils.spec.ts
This is the second iteration of json tree improvement.
- mobile layout for actions (header and horizontal scroll)
- values with known units
- for utils
Not necessary
| <img width="390" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/3902c72c-ace1-4e7b-a149-089ece2215ac"> | <img width="388" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/9d1691fa-3a44-4c7c-a044-c7c269706eb6"> |
=> Json tree view optimization

frontend/package-lock.json
Fix the background in the new tokens table. The new colors are in a new version of gix-components.
In this PR, I upgrade gix-components.
* Changes in `package.lock.json` with `npm run update:gix`.
Still passing.
Not necessary.
=> Chore: Upgrade gix-components

frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts, frontend/src/tests/mocks/icrc-transactions.mock.ts, frontend/src/tests/page-objects/TransactionCard.page-object.ts
Tests with page objects are easier to read and maintain.
I will be changing these tests when making UI changes for ckBTC transactions.
1. Extend `createIcrcTransactionWithId` to make `to` and `from` params optional and accept additional optional `amount` and `fee` params.
2. Add `getHeadline` and `getDate` and static `under` to `TransactionCardPo` page object.
3. Use page objects in `IcrcTransactionCard` and `IcrcTransactionsList`.
4. Fix `"displays identifier for sent for main sns account"` to expect the destination to be the subaccount rather than the main account. It didn't fail because the main account identifier is a substring of the subaccount identifier (for ICRC-1) and the test used `toContain` instead of `toBe`.
5. Fix `"displays identifier for sent for sub sns account"` such …
=> Use page objects in IcrcTransactionCard and -List tests

CHANGELOG-Nns-Dapp-unreleased.md, dfx.json
Use the `--network` tag and variable `DFX_NETWORK` also for the dev environments.
Alloes us:
* `dfx` calls with `--network`.
* Use `./deploy.sh` script.
* Point locally to a devenv with `DFX_NETWORK=devenv_llorenc ./config.sh`.
Examples:
```
DFX_NETWORK=devenv_llorenc ./config.sh
./deploy.sh --nns-dapp devenv_llorenc
dfx canister create nns-dapp --network devenv_llorenc
dfx canister id nns-dapp --network devenv_llorenc
dfx canister install --network devenv_llorenc ...
```
This should allow to run the SOP script from local machine more easily.
In this PR, I added my dev environment. This show how each of us can add their dev environment.
* Add a new network in dfx.json
The release candidate of 2023-11-09 was deployed using this network.
=> Chore: Add devenv llorenc

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/pages/NnsWallet.svelte, frontend/src/tests/lib/pages/NnsWallet.spec.ts
Bug: Rename subaccount button is not available.
* Add the RenameSubAccountButton in the PageHeading when the account is a Subaccount.
* Add a test to check that the button is there if the account is a subaccount.
=> Fix: Add Rename button to subaccount page

.github/workflows/update-snsdemo.yml, CHANGELOG-Nns-Dapp-unreleased.md
If the update workflow runs again while we are still considering a previous update, we don't want the previous update to be overwritten.
It might have additional manual changes or a custom PR description that we don't want to lose.
By using a fixed branch name, we might lose these changes, so we want to use a unique branch name.
The GitHub action to create a PR already supports this out of the box:
https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch
Note that the documentation does mention the follow:
> This strategy is not recommended because if not used carefully it could result in multiple pull requests being created unnecessarily.
Since this workflow runs only once a week or when triggered manually, I don't think creating …
=> Use a unique branch name for snsdemo updates

frontend/src/lib/components/tokens/DesktopTokensTable/DesktopTokensTable.svelte, frontend/src/lib/components/tokens/DesktopTokensTable/DesktopTokensTableRow.svelte
TokensTable background color was not themed.
In this PR, we use the new colors introduced for the table in gix-components
* Use new variables for colors in Tokens table headers and row.
Only styling changes. No new tests needed.
Not necessary.
=> Fix: TokensTable background colors

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/accounts/TransactionCard.svelte
We have new icons for sent/received transactions in the [ckBTC UI update design](https://www.figma.com/file/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?type=design&node-id=475-5782&mode=design&t=DZsyUIvKZoKJmlPj-4).
I asked Artem if these icons are specific to ckBTC or if we should use them everywhere and he said we should use them everywhere.
1. Replace the diagonal arrows for sent/received transaction with up/down arrows.
2. The diagonal arrows were the same icons but differently rotated so I also removed the rotation.
Old:
New:
=> Update sent/received icons

frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/components/accounts/IcrcTransactionCard.svelte, frontend/src/lib/components/accounts/IcrcTransactionsList.svelte, frontend/src/lib/components/accounts/SnsTransactionsList.svelte, frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts
For ckBTC withdrawal transactions we want to render the BTC address as the "To:" address.
This address is encoded in the memo of burn transactions and we want to place it in the `to:` of the transaction rendered in the `TransactionCard`.
This can be done in `mapIcrcTransaction` but the logic is specific to ckBTC so shouldn't be applied to all tokens.
My solution is to be able to pass a different `mapTransaction` function per token.
This PR only makes it possible to pass a `mapTransaction` to `IcrcTransactionsList` but does not use it for any custom mapping for ckBTC.
1. Add `mapTransaction` prop to `IcrcTransactionsList` and pass it on to `IcrcTransactionCard` which will call the passed function instead of `mapIcrcTransaction`.
2. Pass `mapIcrcTransaction` from `CkBTCTransactionsList` and …
=> mapTransaction prop on IcrcTransactionsList

frontend/src/lib/services/ckbtc-tokens.services.ts, frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/lib/services/ckbtc-tokens.services.spec.ts
We want to show the tokens table also for non-logged in users.
Therefore, we need to fetch the token information about CkBTC.
In this PR, I introduce a service `loadCkBTCTokens` that will be used for the tokens route to load the token data.
* New ckBTC token service `loadCkBTCTokens`.
* Test new service
Not necessary.
=> GIX-1979: Load ckBTC tokens

frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
More readable and maintainable.
Use page objects in `frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts`
yes
not necessary
=> Use page objects in TransactionCard.spec.ts

.github/workflows/update-snsdemo.yml
The update-snsdemo workflow used to also update candid files and rust types.
Now it only updates the snsdemo release that we use for test environment scripts and snapshot.
The TODOs in the automated PR description no longer apply to this workflow.
Remove the TODOs that no longer apply to the update-snsdemo workflow.
Not tested. Fingers crossed that the workflow will work correctly next week.
not necessary.
=> Remove irrelevant TODOs from update-snsdemo PR description

.github/workflows/checks.yml, .github/workflows/update-snsdemo.yml
The GIX bot uses two different e-mail addresses.  This makes tracking it in scripts unnecessarily complicated.  It also makes it mess up the insights stats, for example by having its commits split over two columns here:
- Use one e-mail address consistently for GIX bot.  Of the options, I picked the github "noreply" email address.  I'd be surprised if we reply to the other e-mail address.
Update:  I e-mailed gix-bot@dfinity.org and got this reply:
> 550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser c10-20020a50f60a000000b0053f8411973esor240121edn.4 - gsmtp
None
- Not worth a mention, I think.
=> Consistent e-mail address for the GIX bot

frontend/package-lock.json, frontend/package.json
The "Refactoring" feature of Webstorm had for results to remove all imports when code was moved between modules.
https://youtrack.jetbrains.com/issue/WEB-50178#focus=Comments-27-8352541.0-0
https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/110#issuecomment-1804775453
- bump `prettier-plugin-organize-imports`
=> build: fix for prettier-plugin-organize-imports which deletes imports in WebStorm 

.github/workflows/update-didc.yml, .github/workflows/update-ic.yml, .github/workflows/update-proposals.yml, .github/workflows/update-rust.yml, CHANGELOG-Nns-Dapp-unreleased.md
Keep bots consistent.  In #3703, one bot was changed to create a separate branch and PR every time the bot was run.
Note: I am concerned that this will make the bots spammier, which in turn will want developers to run the bots less frequently, which in turn will increase the time between e.g. a new proposal type appearing in the nns and being supported in the nns-dapp.  But we can see and revert if necessary.
- Convert all the nns-dapp bots to branch-per-run.
None
=> feat: Separate branches everywhere

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/stores/icrc-transactions.store.ts, frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts, frontend/src/tests/lib/stores/icrc-transactions.store.spec.ts, frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts, frontend/src/tests/mocks/icrc-transactions.mock.ts
When you make a transaction where the "from" and "to" are the same (sub)account we render this as 2 transactions: 1 sent and 1 received.
To do this we rely on the index canister returning 2 copies of this transaction as well.
But this is a bug in the index canister that might be fixed at some point and also it makes our code fragile.
For example, in the transactions works, we [dedupe transaction](https://github.com/dfinity/nns-dapp/blob/d4a4d206db95027b58653ccd7ab0da6014497939/frontend/src/lib/worker-services/icrc-transactions.worker-services.ts#L63) which means that actually most of the time we fail to render 2 transactions.
1. Add a utility function `getUniqueTransactions` to dedupe transactions.
2. In `icrcTransactionsStore` always dedupe all transactions instead of only removing …
=> Stop relying on duplicate transactions from index

frontend/src/lib/components/tokens/DesktopTokensTable/DesktopTokensTableRow.svelte, frontend/src/lib/pages/SignInTokens.svelte, frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/page-objects/DesktopTokensTableRow.page-object.ts, frontend/src/tests/page-objects/SignInTokens.page-object.ts, frontend/src/tests/page-objects/TokensRoute.page-object.ts, frontend/src/tests/routes/app/tokens/page.spec.ts
Show the tokens table without balance to the non logged in user.
In this PR, render the table in the SignInTokens using the derived store with base data.
In the upcoming PRs I will improve the UX. I will add a "goToDetail" action and logic that will redirect the user to login on row click.
* Render `DesktopTokensTable` in `SignInTokens`.
* Expect `userTokensData` in `SignInTokens`.
* Pass `tokensListBaseStore` to `SignInTokens` in the route.
* Add methods to get the name of the project of the row.
* Add a test in the route component to check that there are tokens when the user is not logged in.
=> GIX-1979: Render table visitors

.github/workflows/update-didc.yml, .github/workflows/update-ic.yml, .github/workflows/update-proposals.yml, .github/workflows/update-rust.yml, .github/workflows/update-snsdemo.yml, CHANGELOG-Nns-Dapp-unreleased.md
The snsdemo repo was added accidentally.  (Not the whole repo but as a link.)
This looks as if it was caused by an incorrect pattern.
- Remove the spurious directory.
- Fix incorrect patterns.
We can trigger workflows but given that the workflows do nothing most of the time, the only real test will be to wait for changes that cause non-trivial changes and check whether the bot creates correct outputs.
=> Fix add-paths lines

rs/proposals/src/canisters/nns_governance/api.rs, rs/proposals/src/canisters/nns_registry/api.rs, rs/proposals/src/canisters/sns_wasm/api.rs
We would like to render all the latest proposal types.
* Updated the Rust code derived from `.did` files in the proposals payload rendering crate.
* Note: The candid files under `declarations/nns-$CANISTER` are used as inputs.
- Created an issue: https://dfinity.atlassian.net/browse/GIX-2050
- Before deployment, there are tests in prod so we should see recent proposals rendered correctly.
=> Update proposal rendering

.github/workflows/update-didc.yml, .github/workflows/update-ic.yml, .github/workflows/update-proposals.yml, .github/workflows/update-rust.yml, .github/workflows/update-snsdemo.yml
Update actions have insufficient logging for rapid debugging.
- Log the git status, so that the log can be compared with the the PR generated by the action.
- Include the version being updated to in the PR title, where applicable, to make it easier to find.
=> Better logging for update actions

frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/routes/app/tokens/page.spec.ts
Tokens page should also render the ckBTC token.
It was missing before before it wasn't loading the token in the tokensStore.
* Call service to load the enabled ckBTC tokens in the store in the Tokens route.
* Add tests to the route to check for ckBTC tokens.
=> GIX-1979: Render ckBTC token

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/derived/debug.derived.ts
There is a bug with the debug store and the command "fo" isn't working.
The issue is that a specific store was `undefined` by default.
* Add a default store for `addAccountStore` in debug.derived.
Not tested.
=> Fix_debug-store

frontend/package-lock.json
A new version of ic-js has been released ([Release 2023.10.15-0600Z](https://github.com/dfinity/ic-js/releases/tag/2023.10.15-0600Z)) following which I triggered a next version to integrate the new version number. This PR bump the libs to those next versions.
=> Bump ic-js next

frontend/src/lib/derived/tokens-list-user.derived.ts, frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
We want to render the tokens page with the logged in user data.
In this PR, I add a new derived store with the user balances.
* New derived store `tokensListUserStore`.
* Test new derived store `tokensListUserStore`.
=> GIX-1981_LM_new-derived-store-user-tokens

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
For ckBTC -> BTC withdrawals we want to list the withdrawal address in the "To:" of the transactions.
The withdrawals address in encoded in the memo of the ckBTC burn transaction.
We already have a custom `mapCkbtcTransaction` function which can be used instead of `mapIcrcTransaction` to map the transaction such that if it is a burn transaction with a memo, the decoded address will be set in the "To:".
In `TransactionCard.svelte` we render either To/Source for a Transfer or a custom description for either transaction types. We never render both, but technically `TransactionCard` currently supports rendering both, even though it doesn't look right in the UI.
1. Pass `mapCkbtcTransaction` instead of `mapIcrcTransaction` to `IcrcTransactionsList` from `fCkBTCTransactionsList.svelte` to take …
=> Render BTC withdrawal address

frontend/src/lib/i18n/en.json, frontend/src/tests/e2e/accounts.spec.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
The opposite of "To" is "From".
The opposite of "Source" is "Destination".
Currently we write "To: address" for Sent transaction but "Source: address" to Received transactions.
But we also write "From: BTC Network" rather than "Source: BTC Network" for ckBTC mint transactions.
And new UI mocks (here) use "From:" everywhere.
Change "Source:" to "From:" for consistency.
Existing tests are updated.
=> Change Source: to From:

frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
Tokens table design has a rounded border radius.
* Add rounded border radius to TokensTable.
=> Fix: Adapt tokens table border radius

frontend/src/lib/derived/tokens-list-visitors.derived.ts, frontend/src/lib/pages/SignInTokens.svelte, frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/lib/derived/tokens-list-visitors.derived.spec.ts, frontend/src/tests/routes/app/tokens/page.spec.ts
Tokens table is also interactive for non logged in users.
The requirement was to send them to login.
* New derived store for the tokens table: `tokensListVisitorsStore`.
* Listen for the event `nnsAction` in the Tokens route and SignInTokens.
* Trigger a login in any `nnsAction` if the user is not logged in.
* Add a test in the tokens route that the user is sent to login when clicking in a row.
* Test new store `tokensListVisitorsStore`.
=> GIX-1979: Login action visitors

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/pages/SnsProposalDetail.svelte
Fix sns proposal initial update. For undiscovered reason data changes in `SnsProposalDetail` don't trigger auto-subsribers (maybe the lazy loading of the component on slow internet provokes this behaviour)
- wait for component finished current updates before applying new data changes.
Manually tested with network throttling.
=> fix: stuck loading of the sns proposal

frontend/src/lib/derived/tokens-list-base.derived.ts, frontend/src/lib/utils/universe.utils.ts
Simplify universes code.
In this PR, use the fields `title` and `logo` of the Universe instead of using a helper.
* In `convertUniverseToBaseTokenData` use the universe `logo` and `title`.
* Remove unused helpers `getUniverseTitle` and `getUniverseLogo`.
Tests still passing. Helpers didn't have tests of their own.
Not necessary.
=> Refactor: Use Universe title and logo fields

.github/workflows/deploy-to-app.yaml, CHANGELOG-Nns-Dapp-unreleased.md, dfx.json
Test deployments to the app subnet currently fail.
- Add logging
- Change provider to match what dfx 15 expects.  See [this thread on the forum](https://forum.dfinity.org/t/replica-error-not-allowed-to-call-ic00-method-provisional-create-canister-with-cycles/23709/6) for details.
- See this deployment: https://github.com/dfinity/nns-dapp/actions/runs/6879490121
=> Fix deploy to app

CHANGELOG-Nns-Dapp-unreleased.md, scripts/network-config, scripts/network-config.test
`DFX_NETWORK` is typically provided to dfx build commands as an exported environment variable.  When checking that `DFX_NETWORK` is provided, we need to check specifically that it is exported as otherwise it is possible to get very confusing behaviour in which the network is defined in one part of the deployment but not another.
- Check that `DFX_NETWORK` is exported.
- Tests have been added that the error message specifically mentions `DFX_NETWORK` not being exported.
=> Error if network is defined but not exported

frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte, frontend/src/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.svelte, frontend/src/lib/components/neurons/ConfirmDissolveDelay.svelte, frontend/src/lib/components/neurons/NeuronStateRemainingTime.svelte, frontend/src/lib/components/neurons/NnsNeuronAge.svelte, frontend/src/lib/components/neurons/NnsNeuronDetailCard.svelte, frontend/src/lib/components/project-detail/ProjectTimelineUserCommitment.svelte, frontend/src/lib/components/proposals/Countdown.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronVestingPeriodRemaining.svelte, frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte, frontend/src/lib/components/sns-neuron-detail/VestingTooltipWrapper.svelte, frontend/src/lib/components/sns-neurons/ConfirmSnsDissolveDelay.svelte, frontend/src/lib/components/sns-neurons/SnsNeuronAge.svelte, frontend/src/lib/routes/Settings.svelte, frontend/src/lib/utils/date.utils.ts, frontend/src/tests/lib/components/project-detail/ProjectTimelineUserCommitment.spec.ts, frontend/src/tests/lib/components/proposals/Countdown.spec.ts, frontend/src/tests/lib/components/proposals/NnsProposalCard.spec.ts, frontend/src/tests/lib/components/sns-neurons/ConfirmSnsDissolveDelay.spec.ts, frontend/src/tests/lib/components/sns-neurons/SetSnsDissolveDelay.spec.ts, frontend/src/tests/lib/utils/date.utils.spec.ts
`secondsToDuration` has been moved to `@dfinity/utils` therefore this PR replaces the usage of the function by the one in the library. It also remove the duplicate implementation within NNS dapp which becomes unused.
=> Replace secondsToDuration with utils move to ic-js

frontend/src/lib/components/proposal-detail/VotingCard/VotingCard.svelte, frontend/src/lib/components/sns-proposals/SnsVotingCard.svelte
Keep adapt/reject buttons visible but disabled after voting. Part of voting section redesign.
- update visibility logic for nns and sns proposals
Works
=> feat: do not hide voting buttons after voting

frontend/src/lib/components/tokens/MainWrapper.svelte
Width on tablet was too wide.
Instead, use the logic of the `Island` to set the max-width. This has been agreed with design, although it's open to change.
* Add a max-width on the token page `MainWrapper`.
Not necessary
=> GIX-2005_LM_fix-tablet-horizontal-spacing

CHANGELOG-Nns-Dapp-unreleased.md, deploy.sh
With dfx 0.15.1 this fails with a confusing error message:
```
./deploy.sh --nns-dapp local
```
This is due to the network being defined but not exported.
- Export `DFX_NETWORK`.
* Tested locally.  CI tests are underway but I am unlikely to get them finished this morning so this is to unblock developers.
* Fixes and tests for appropriate error messages are in #3771
=> Fix local deployments

frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte, frontend/src/lib/types/tokens-page.ts, frontend/src/tests/lib/components/tokens/TokensTable.spec.ts, frontend/src/tests/page-objects/TokensTableRow.page-object.ts
The view of the ICP accounts includes subaccounts and hardware wallets. Those are identified with a subtitle.
See design [here](https://www.figma.com/file/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?type=design&node-id=408-2886&mode=design&t=96zreK0AABYejpwI-0).
* Add new optional field `subtitle` to `UserTokenData`.
* Render new field (if present) and adapt styles in `TokensTableRow`.
* Add test in TokensTable.spec for the new field.
* Add method to TokensTableRow page object to get subtitle.
Not necessary.
=> GIX-2082: Add subtitle to TokensTable

frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts
We used to have tokens symbols in transaction headlines, like "Received $token".
We no longer do, but we still try to replace the placeholder that's no longer there.
The code died in https://github.com/dfinity/nns-dapp/pull/2164
Stop trying to replace the token symbol in transaction headlines.
Existing (updated) tests pass.
not necessary
=> Remove dead code to place token symbol in transactions

frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts, frontend/src/tests/mocks/transaction.mock.ts
With page objects tests are easier to read and maintain.
1. Add `createMockSendTransaction` and `createMockSendTransaction` functions to specify amount and fee explicitly in the tests.
2. Use `TransactionCardPo` in `NnsTransactionCard.spec.ts` to make expectations on the rendered component.
yes
Not necessary
=> Use page objects in NnsTransactionCard.spec.ts

frontend/src/lib/pages/NnsAccounts.svelte, frontend/src/lib/routes/Accounts.svelte, frontend/src/tests/lib/pages/NnsAccounts.spec.ts, frontend/src/tests/page-objects/NnsAccounts.page-object.ts, frontend/src/tests/routes/app/accounts/page.spec.ts
When we migrate to the tokens page, we also want a similar view for the ICP accounts, subaccounts and hardware wallet accounts.
In this PR, I introduce the TokensTable for NNS Accounts.
* Render `TokensTable` in `NnsAccounts` depending on feature flag.
* Expect an optional list of `UserTokenData` in `NnsAccounts`.
* Hard code a list of `UserTokenData` in the Accounts route and pass it to `NnsAccounts`.
* Add test in NnsAccounts.spec that the tokens table is there if feature flag is enabled. I added myself some TODOs comments to remember improving the test before adding more features here.
* Add methods to NnsAccountsPo.
* Add test in Accounts route to check that tokens table is rendered if flag is enabled.
=> GIX-1980: Setup icp accounts with tokens table

frontend/src/lib/components/accounts/IcrcTransactionCard.svelte, frontend/src/lib/components/accounts/NnsTransactionCard.svelte, frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/lib/types/transaction.ts, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/components/accounts/NnsTransactionCard.spec.ts, frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts, frontend/src/tests/mocks/transaction.mock.ts
We currently pass `mapTransaction` from `CkbtcTransactionsList` to `IcrcTransactionsList` to `IcrcTransactionCard` and then we apply the mapping and pass a lot of props to `TransactionCard`.
My goal is to simplify this and give the higher level component more direct control over how the transactions are rendered.
In this PR I introduce the `UiTransaction` type which contains all information necessary to render the `TransactionCard` component. This allows us to pass a single prop to `TransactionCard`.
My goal is to eventually return `UiTransaction` from `mapTransaction` and possibly retire the intermediate `Transaction` type.
Also, I want to map all the transactions in the higher level component to avoid sending down all these different props.
This is the first step.
1. Introduce a new …
=> Pass a single prop to TransactionCard

frontend/src/lib/types/sns.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/mocks/sns-projects.mock.ts
To better start using the new fields in SnsSummary, we should make them mandatory.
In this PR, make `init`, `swapParams` and `lifecycle` mandatory in SnsSummary.
* Make `init`, `swapParams` and `lifecycle` mandatory in SnsSummary type.
* Add checks in `isValidSummary` for those fields except `lifecycle` which already couldn't be `undefined`.
* Add mandaotry fields to mocks.
Not necessary
=> Refactor: New mandatory SnsSummary fields

dfx.json
=> Update didc release to 2023-11-16

frontend/src/lib/components/tokens/MainWrapper.svelte, frontend/src/lib/pages/SignInTokens.svelte, frontend/src/lib/pages/Tokens.svelte, frontend/src/routes/(app)/(nns)/tokens/+layout.svelte
Width of tokens page for logged and non-logged in visitors was different.
Solution, move the wrapper to the layout.
* Make `testId` optional in MainWrapper. Only used in NnsAccounts.
* Remove `<main>` wrapper in `SignInTokens`.
* Remove `MainWrapper` from Tokens page.
* Add `MainWrapper` in the tokens layout.
No new tests. Only UI changes reshuffling some elements.
Not necessary.
=> Fix: SignIn Tokens width page

.github/workflows/update-rust.yml, CHANGELOG-Nns-Dapp-unreleased.md
The title and body of PRs created by the Rust update action are bad.  [Example](https://github.com/dfinity/nns-dapp/pull/3781)
- Title tries to declare which version is updated to but the version number is missing
- The PR has no meaningful body
- Fix the title (by making the version number available unconditionally)
- Add a body
This PR was generated by this action: #3788
=> Update rust workflow text

dfx.json
=> Update snsdemo to release-2023-11-17

frontend/src/lib/components/accounts/IcrcTransactionCard.svelte, frontend/src/lib/components/accounts/IcrcTransactionsList.svelte, frontend/src/lib/components/accounts/NnsTransactionCard.svelte, frontend/src/lib/types/transaction.ts, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts
To simplify transactions list rendering and give the higher level components more control over it, I'm moving the conversion to `UiTransaction` up the component chain.
The ultimate goal is to create the list of `UiTransaction`s directly from the list of `TransactionWithId`s without intermediate `IcrcTransactionData` or `Transaction`. Then it will also be easier to render multiple transactions as 1 (to hide the approval step) or 1 as multiple (such as with a to-self transaction).
In this PR we move creation of `UiTransactions` from the IcrcTransactionCard` to the `IcrcTransactionsList`.
1. Add a field `domKey` to `UiTransaction` to keep consistent list rendering.
2. Pass transaction ID to `toUiTransaction` to use for the `domKey`.
3. Remove all props from `IcrcTransactionCard` and keep …
=> Create UiTransactions in IcrcTransactionsList

frontend/src/lib/derived/icp-tokens-list-visitors.derived.ts, frontend/src/tests/lib/derived/icp-tokens-list-visitors.derived.spec.ts
The user might arrive directly to the accounts page of the ICP without going through tokens.
The route is the current `/accounts` page. Although for now, it will be available only when `u=OWN_CANISTER`.
In case a non-logged in user lands there, they should see a table like in `/tokens` but with only ICP main account.
In this PR, I introduce the derived store for those visitors.
* New derived store `icpTokensListVisitors`.
* Test new derived store.
Not necessary.
=> GIX-2058: Derived store ICP Tokens visitor

frontend/src/routes/(app)/(u)/(accounts)/+page.svelte, frontend/src/routes/(app)/(u)/(accounts)/accounts/+page.svelte, frontend/src/tests/page-objects/AccountsPlusPage.page-object.ts, frontend/src/tests/routes/app/accounts/page.spec.ts
There was a mismatch with the PO used in one test and the actual component being tested.
The spec for the `+page` in the accounts route was using the PO for the `routes/Accounts.svelte`. Which is really a child of that component.
In this PR, I add a new PO `AccountsPlusPagePo`. I added the `PlusPage` in reference to `+page` used in the route. I hope this will help with the misconcenption.
* New PO AccountsPlusPagePo
* Use the new PO in `routes/app/accounts/page.spec.ts`
Not necessary.
=> GIX-2085: AccountsPlusPagePo

frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts
The logic in `showTransactionFee` is unnecessary.
Burn and Mint transactions don't have a fee so even if we tried to add it, there's nothing to add.
If `toSelfTransaction` is true, then `isReceive` is also true, so there's no need to check `toSelfTransaction` separately.
1. Remove `showTransactionFee` and just use `!isReceive` instead.
2. Remove test for `showTransactionFee`.
Existing unit tests pass.
Transaction list, including Burn, Mint, Approve and TransferFrom, looks correct.
I also changed `transactionDisplayAmount` to add a fee when it shouldn't or not add a fee when it should and in both cases there was a failing test so that confirms there is test coverage.
not necessary
=> Remove unnecessary showTransactionFee

CHANGELOG-Nns-Dapp-unreleased.md, scripts/docker-build
There is a typo in the global config fallback, causing docker builds to fail on machines that have never set a global config.
Note: Local configs have been deprecated since February 2022, so most active developers will have a global config, but not all.
Note: In CI we call docker directly so that we can cache builds use the buildx action.  Maybe we could have tests that are run only when the `release-candidate` tag is pushed.  That way we could test the docker build script pre-release without slowing down every PR.
- Fix the typo - with a var so that the same filename is used on both branches.
- Built locally with and without a global config.
=> Fix: global config fallback

frontend/src/lib/components/accounts/IcrcTransactionsList.svelte, frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts, frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts, frontend/src/tests/mocks/icrc-transactions.mock.ts
In `IcrcTransactionsList` we map `IcrcTransactionData`s to `Transaction`s and then to `UiTransaction`s.
This is not necessary and by doing it in 1 step we can give the custom `mapTransaction` function more control over the rendering of the transactions.
This will make it easier to implement ckBTC UI improvements.
1. Change `mapIcrcTransaction` and `mapCkbtcTransaction` to return `UiTransaction` instead of `Transaction`.
2. In `IcrcTransactionsList` map transactions with the new single mapping function. Then filter out `undefined` transactions.
3. 
1. Accept optional `timestamp` and `memo` params to `createIcrcTransactionWithId`.
2. Change unit tests for `mapTransaction` to expect the full result instead of just a few properties. Define default values so we still only have to specify the …
=> Map directly to UiTransaction

frontend/src/lib/components/common/EmptyCards.svelte, frontend/src/lib/pages/NnsAccounts.svelte, frontend/src/lib/pages/SignInAccounts.svelte, frontend/src/routes/(app)/(u)/(accounts)/+layout.svelte, frontend/src/routes/(app)/(u)/(accounts)/+page.svelte, frontend/src/routes/(app)/(u)/(accounts)/accounts/+page.svelte, frontend/src/routes/(app)/(u)/(detail)/wallet/+page.svelte, frontend/src/tests/page-objects/AccountsPlusPage.page-object.ts, frontend/src/tests/page-objects/SignInAccounts.page-object.ts, frontend/src/tests/routes/app/accounts/layout.spec.ts, frontend/src/tests/routes/app/accounts/page.spec.ts
The accounts page for non-logged in users should be similar to the logged-in page.
Therefore, we use the TokensTable in SignInAccounts when flag is enabled.
* Move the `MainWrapper` to the layout of the route accounts and apply it when flag is enabled.
* Add logic in the `SignInAccounts` to render different components depending on flag value.
* Use the `icpTokensListVisitors` when rendering `SignInAccounts` in the accounts route pages.
* New SignInAccountsPo.
* Add methods to PO
* Add a test in the routes layout spec to check that token navigation is present or not depending on the flag.
* Add tests in the routes page to check that either tokens table or empty cards are present depending on the flag.
Not necessary.
=> GIX-2085: Use TokensTable in SignInAccounts

frontend/src/lib/derived/icp-tokens-list-user.derived.ts, frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
Render the tokens table with ICP accounts.
In this PR, introduce the derived store that combines the NNS universe and the icp accounts to return  the data for the TokensTable.
* New derived store `icpTokensListUser`.
* Test new store `icpTokensListUser`.
=> GIX-2058: IcpTokensListUser derived store

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/proposal-detail/ProposalSystemInfoProposerEntry.svelte, frontend/src/lib/components/proposals/ProposalCard.svelte, frontend/src/lib/components/ui/Hash.svelte, frontend/src/tests/e2e/proposals.spec.ts, frontend/src/tests/lib/components/proposal-detail/ProposalSystemInfoProposerEntry.spec.ts
Optimise nns proposals for middle-size android devices (eg.Galaxy S21).
- apply sns proposer UI for nns proposer
- fix broken ellipsis in proposal card
| <img width="390" alt="Screenshot 2023-11-22 at 10 58 12" src="https://github.com/dfinity/nns-dapp/assets/98811342/8a094ee9-e59f-449f-80ec-4a70f4893b26"> | <img width="364" alt="Screenshot 2023-11-22 at 10 59 29" src="https://github.com/dfinity/nns-dapp/assets/98811342/f259c75e-6017-452f-a1b3-aa63140b1917"> |
| <img width="310" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/7ebe642e-2e02-45f2-805d-5a77b103c299"> | <img width="312" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/6257e584-6f4f-424f-827e-39da00fafc37"> |
=> Fix proposal details for small devices

frontend/src/lib/modals/accounts/SnsTransactionModal.svelte, frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/page-objects/SnsTransactionModal.page-object.ts, frontend/src/tests/page-objects/TokensPage.page-object.ts, frontend/src/tests/page-objects/TokensRoute.page-object.ts, frontend/src/tests/page-objects/TokensTable.page-object.ts, frontend/src/tests/routes/app/tokens/page.spec.ts
Users can make SNS transactions from the tokens view.
* Add a `modal` local variable in the Tokens route +page to control whether a modal should be open or not.
* Populate `modal` when an action is triggered.
* Render the SnsTransactionModal when `modal.type` matches an SNS transaction.
* Add test id in SnsTransactionModal.svelte
* New PO for SnsTransactionModal.
* New methods in TokensTable, TokensPage and TokensRoute POs.
* Add a test case in the Tokens route page that user can transfer SNS tokens.
Not necessary.
=> GIX-1983: Add SnsTransaction functionality

frontend/src/lib/pages/NnsAccounts.svelte, frontend/src/lib/pages/SignInAccounts.svelte, frontend/src/tests/lib/pages/NnsAccounts.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/routes/app/accounts/page.spec.ts
The tokens table for ICP accounts has a different header than for all tokens view.
In this PR, the new prop `firstColumnHeader` is used to change the column header for ICP accounts.
* Use `firstColumnHeader` in NnsAcconts.
* Use `firstColumnHeader` in SignInAccounts.
* Add a test in the Accounts route (the one that renders NnsAccounts).
* Add a test in NnsAccounts.spec
* Add a test in routes/app/accounts/page.spec (the one that renders SignInAccounts, and tests its logic).
Not necessary
=> GIX-2102: Add column headers to ICP TokensTable

frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/components/accounts/IcrcTransactionsList.svelte, frontend/src/lib/components/accounts/SnsTransactionsList.svelte, frontend/src/lib/types/transaction.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts, frontend/src/tests/mocks/icrc-transactions.mock.ts, frontend/src/tests/mocks/transaction.mock.ts
In CkBTCTransactions list I want to render multiple transactions (such as Approve + transfer) as a single transaction.
This is easier if the conversion from `IcrcTransactionData` to `UiTransaction` happens closer to the CkBTCTransactionsList.
In this PR I move the conversion from `IcrcTransactionData[]` to `UiTransaction[]` from `IcrcTransactionsList` to `CkBTCTransactionsList` and `SnsTransactionsList`.
1. In `CkBTCTransactionsList` convert `IcrcTransactionData[]` to `UiTransaction[]` and pass that to `IcrcTransactionsList`. No longer pass `account` and `token` which were only passed to do the conversion.
2. In `SnsTransactionsList` convert `IcrcTransactionData[]` to `UiTransaction[]` and pass that to `IcrcTransactionsList`. No longer pass `governanceCanisterId`, `account` and `token` …
=> Pass UiTransaction[] to IcrcTransactionList

frontend/src/lib/types/sns.ts, frontend/src/lib/utils/sns-aggregator-converters.utils.ts, frontend/src/tests/mocks/sns-projects.mock.ts
The SnsSummarySwap mirrors the `Swap` type in sns-js.
There were two (unused) fields missing in `SnsSummarySwap`.
The aggregator converter was adding them, but because the values in the `.toEqual(...)` were not typed, it didn't care that there were extra fields.
I found that out when I put the `toEqual` inside the `SnsSummaryWrapper` from #3825 
* Add two missing fields in `SnsSummarySwap`.
* Add two fields in the `SnsSummarySwap` mock.
Not necessary.
=> Chore: Add missing fields to SnsSummarySwap

CHANGELOG-Nns-Dapp-unreleased.md, scripts/nns-dapp/migration-test, scripts/nns-dapp/migration-test.canister, scripts/nns-dapp/migration-test.getters, scripts/nns-dapp/migration-test.linters
Testing migration is very similar to the downgrade-upgrade test.  The downgrade-upgrade test can almost certainly be expanded to make it appropriate for this use case.  However the schema change tests are likely to need a lot of modification over the next few weeks, so I would prefer to have a separate test for schema changes that can "move fast and experiment" and then migrate useful code back into the original, eventually deleting the experimental code.
Why not keep the test in a branch?  Most development is on Rust code.  Importing tests into every rust development branch has been a real pain.
* Make a copy of the downgrade upgrade test dedicated to schema changes:
* Copy the test script
* Mark the new test as unstable.
* Split the test into small chunks, as the file is huge!
* Add …
=> Draft Migration test

frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte, frontend/src/lib/pages/SignInTokens.svelte, frontend/src/lib/pages/Tokens.svelte, frontend/src/tests/lib/components/tokens/TokensTable.spec.ts, frontend/src/tests/routes/app/tokens/page.spec.ts
Remove default value for `firstColumnHeader` to make it configurable from outside always.
* Remove default value from `firstColumnHeader` in TokensTable.svelte
* Add the old default value in the usages of TokensTable without the prop `firstColumnHeader`.
* Remove a test for the default column header in TokensTable.
* Add tests in the tokens route to check the header's title, both logged in and out.
Not necessary
=> GIX-2102: Remove default firstColumnHeader

frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte, frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte, frontend/src/lib/components/tokens/TokensTable/actions/GoToDetailButton.svelte, frontend/src/lib/types/tokens-page.ts, frontend/src/lib/utils/user-token.utils.ts, frontend/src/tests/lib/components/tokens/TokensTable.spec.ts, frontend/src/tests/mocks/tokens-page.mock.ts, frontend/src/tests/page-objects/TokensTableRow.page-object.ts
Give a better user experience in the tokens table pages.
In this PR, I introduce two new types `UserTokenBase` and `UserTokenLoading`. Both are accepted in the props of TokenTable. But only the initial one `UserTokenData` can be used to dispatch actions.
I guess the loading could also dispatch events, but we should use another event name, not `nnsAction`. This way, we know for certain that when `nnsAction` is triggered, it has the token and fee available. This is important to open modals at the moment, but could be important for other actions in the future.
* Add two new types `UserTokenBase` and `UserTokenLoading`.
* Render a Spinner if UserTokenLoading in TokensTableRow.
* Support a union of `UserTokenLoading` and `UserTokenData` in TokensTable and TokensTableRow
* Add a test in …
=> GIX-2062: Add loading balance

frontend/src/lib/stores/icrc-canisters.store.ts, frontend/src/tests/lib/stores/icrc-canisters.store.spec.ts
Support for ckETH.
In this PR, I introduce a store that will hold the canister ids of the ckETH set of canisters. It might be used for other ICRC compatible tokens.
* New store `icrcCanistersStore`.
* Test new store
=> GIX-2116: New icrcCanistersStore

frontend/src/lib/stores/ckbtc-pending-utxos.store.ts, frontend/src/tests/lib/stores/ckbtc-pending-utxos.store.spec.ts
We want to show pending incoming BTC deposit transactions.
This PR just adds a store to store these transactions after we receive them from the minter so that we can display them in the wallet.
1. Adds a store for pending UTXOs. There is a separate list per universeId (ckBTC vs. ckTESTBTC). UTXOs are sorted by number of confirmations so that they will be listed with newer transactions above older transactions.
2. Unit tests for the store.
Unit tests pass.
Tested manually in a branch which uses the store.
will add when it's used
=> Add pending UTXOs store

frontend/src/lib/components/accounts/TransactionCard.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/types/transaction.ts, frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/lib/utils/transactions.utils.ts, frontend/src/tests/lib/components/accounts/IcrcTransactionCard.spec.ts, frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts, frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts, frontend/src/tests/lib/utils/transactions.utils.spec.ts, frontend/src/tests/mocks/transaction.mock.ts, frontend/src/tests/page-objects/TransactionCard.page-object.ts
When converting BTC to and from ckBTC, it takes a while before the transaction on one network results in a transaction on the other network.
We want to render this as a "pending" transaction, which should look like this:
1. Add a field `isPending` to the type `UiTransaction`.
2. Make the field `timestamp` optional in `UiTransaction`. Since pending transaction haven't happened yet, they don't have a timestamp.
3. In `TransactionCard` make the icon orange, by adding class `pending`, when the transaction is pending.
4. In `TransactionCard` don't render a timestamp if it's absent, and render "Pending..." if it's pending.
5. Add `isPending: false` to existing instances.
1. Add a unit test for rendering a pending transaction.
2. Test that a non-pending transaction does not have a pending icon. …
=> Support rendering pending transactions

declarations/nns_governance/nns_governance.did, declarations/nns_ledger/nns_ledger.did, declarations/nns_registry/nns_registry.did, declarations/sns_governance/sns_governance.did, declarations/sns_ledger/sns_ledger.did, declarations/sns_root/sns_root.did, declarations/sns_swap/sns_swap.did, declarations/sns_wasm/sns_wasm.did, dfx.json
=> Update IC candid files to release-2023-11-23_23-01

frontend/src/lib/stores/icrc-canisters.store.ts, frontend/src/tests/lib/stores/icrc-canisters.store.spec.ts
There was a typo in the IcrcCanistersStore: "ledgerCansisterId" instead of "ledgerCanisterId".
* Fix typo.
* Also in tests.
Not necessary.
=> Chore: Fix typo icrcCansitersStore

frontend/src/lib/i18n/en.json, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/utils/icrc-transactions.utils.ts, frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
When converting BTC to ckBTC, the minter only credits the ckBTC account when the incoming BTC transaction has 12 confirmations. When a UTXO has fewer than 12 confirmations, we consider it "pending" and we want to render it as a pending transaction.
In this PR I add a function to convert `PendingUtxo` to `UiTransaction` so that we can use `TransactionCard` to render it (already implemented in https://github.com/dfinity/nns-dapp/pull/3839).
The mapping function will be used in a future PR.
1. Add `mapCkbtcPendingUtxo` which converts a `PendingUtxo` to a `UiTransaction`.
2. Add a unit test. The conversion is so straightforward that a single test seemed sufficient, but let me know if you agree.
3. Drive-by: Use a ckBTC token instead of `ICPToken` in another ckBTC related unit test. This …
=> Map PendingUtxo to UiTransaction

.github/workflows/checks.yml, scripts/nns-dapp/migration-test, scripts/nns-dapp/migration-test.on-exit, scripts/nns-dapp/migration-test.on-exit.test
The migration test has an `on_exit` handler and a backtrace printing function.  These lack tests.
* Move the functions out into utilities (as I found myself using them in other code as well).
* Add tests
This PR consists primarily of unit tests.
- Covered by an existing changelog entry
=> test on_exit

frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
Get token data and balance of ICRC tokens easily.
Add new icrc ledger api functions: `queryIcrcToken` and `queryIcrcBalance`. This make a call to the endpoint of the ledger canister passed.
* New icrc ledger functions `queryIcrcToken` and `queryIcrcBalance`.
* Test new functions.
Not necessary.
=> GIX-2117: Add ledger api endpoints

CHANGELOG-Nns-Dapp-unreleased.md, scripts/nns-dapp/release-sop, scripts/nns-dapp/release-sop-test-continue-after-success.json, scripts/nns-dapp/release-sop-test-continue-different-staging-canister.json, scripts/nns-dapp/release-sop-test-different-built-args-hash.json, scripts/nns-dapp/release-sop-test-different-built-wasm-hash.json, scripts/nns-dapp/release-sop-test-different-staging-wasm-hash.json, scripts/nns-dapp/release-sop-test-successful-release.json
Staging testnet is dead. We now use DevEnv to stage our release candidate for testing.
1. Add two new flags to `release-sop`: `--test_network` (defaults to `devenv_$USER`) and `--test_domain` (defaults to `${USER}-ingress.devenv.dfinity.network`).
2. Replace all occurrences of "staging" with more appropriate replacements. Mostly `$TEST_NETWORK`.
3. Drive-by change: Remove `remove_staging_nns_dapp_from_canister_ids_json` which is no longer used.
1. In the test vectors, pass parameters to make the test network/domain not depend on the user running the test.
2. Update the mock behavior and expected output.
=> Update release-sop for DevEnv

frontend/src/lib/derived/icrc-universes.derived.ts, frontend/src/tests/lib/derived/icrc-universes.derived.spec.ts, frontend/src/tests/mocks/cketh-accounts.mock.ts, frontend/src/tests/mocks/universe.mock.ts
Convert the ICRC tokens stored in `icrcCanistersStore` into a `Universe`.
* New derived store `icrcTokensUniversesStore`. For now, it works only for ckETH canisters.
* Add mocks for ckETH universes and tokens.
* Add test for new derived store `icrcTokensUniversesStore`.
=> GIX-2118: Add ckETH universe derived

frontend/src/lib/derived/selectable-universes.derived.ts, frontend/src/lib/derived/selected-universe.derived.ts, frontend/src/lib/utils/universe.utils.ts, frontend/src/tests/lib/utils/universes.utils.spec.ts
Util `pathSupportsCkBTC` can also be used for ckETH and other ICRC tokens.
* Rename `pathSupportsCkBTC` to `pathSupportsIcrcToken`.
* Rename tests
Not necessary.
=> Chore: Rename pathSupportsCkBTC

frontend/src/lib/api/ckbtc-ledger.api.ts, frontend/src/lib/api/icrc-ledger.api.ts
- mark `getIcrcToken` as deprecated
- use new `queryIcrcToken` in `getCkBTCToken`
=> Use queryIcrcToken for getCkBTCToken

frontend/src/lib/derived/icrc-universes.derived.ts, frontend/src/tests/mocks/universe.mock.ts
Use the new ETH logos for ckETH related universes.
* Import and use the ckETH logos in the icrc-universes derived store.
* Change the mocks to use the new logos. Those are used in test expects.
Not necessary.
=> GIX-2118: Add ckETH logos to universe

frontend/src/lib/routes/Accounts.svelte, frontend/src/lib/services/cketh-canisters.services.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/services/cketh-canisters.services.spec.ts
Load ckETH and ckETHSepolia (if needed) in Accounts page.
* Use services `loadCkETHCanisters` and `loadIcrcAccounts` in Accounts page.
* Test that the store is filled with proper data in Accounts route.
I added this test because the Accounts page doesn't render the token selector sidebar. Therefore, I can't test that the token is present in the UI from that component.
This will change with the new Tokens page. Therefore, there is no need to improve it for now.
Not necessary
=> GIX-2117: Load ckETH on Accounts page

frontend/src/lib/derived/selected-universe.derived.ts, frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
New derived store `isIcrcTokenUniverseStore` to be used when rendering the component for a specific universe.
Similar to `isCkBTCUniverseStore` or `isNnsUniverseStore`, which are used to render NnsAccounts or CkBTCAccounts components in Accounts.svelte
* New derived store `isIcrcTokenUniverseStore`.
* Test new derived store
Not necessary.
=> GIX-2121: Add ICRC Token universe selected store

frontend/src/tests/lib/routes/Accounts.spec.ts
There were a few unnecessary checks in one test of Accounts.spec
The test fails as expected before those lines.
* Remove unnecessary expects.
Not necessary.
=> Chore: Remove unnecessary expects

frontend/src/lib/derived/selected-universe.derived.ts, frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
Add derived store that returns the selected ICRC Token universe id.
* New derived store `selectedIcrcTokenUniverseIdStore`.
* Refactor `isIcrcTokenUniverseStore` to use `selectedIcrcTokenUniverseIdStore`.
* Test new derived store `selectedIcrcTokenUniverseIdStore`.
Not necessary.
=> GIX-2121: selectedIcrcTokenUniverseIdStore

CHANGELOG-Nns-Dapp-unreleased.md, config.sh, dfx.json, scripts/nns-dapp/test-config-assets/app/env, scripts/nns-dapp/test-config-assets/mainnet/env
The NNS dapp needs to be aware of the ckETH ledger and index canister IDs.
1. Include entries for `cketh_ledger` and `cketh_index` in `dfx.json`. The don't have mainnet IDs yet.
2. Update `./config.sh` to include entries for ckETH similar as for ckBTC but without minter.
Ran `scripts/nns-dapp/test-config --update` to update golden files.
=> Include ckETH canisters in env config

frontend/src/lib/pages/IcrcTokenAccounts.svelte, frontend/src/lib/routes/Accounts.svelte, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/page-objects/Accounts.page-object.ts, frontend/src/tests/page-objects/IcrcTokenAccounts.page-object.ts
Render a specific Accounts page when the selected universe is an ICRC Token.
* Setup empty IcrcTokenAccounts.svelte
* In Accounts.svelte, render IcrcTokenAccounts for ICRC Token universes.
* Add new PO IcrcTokenAccountsPo.
* Add method to get the new accounts page in AccountsPo
* Test in Accounts.spec to check that the new component is rendered.
Not necessay.
=> GIX-2121: Setup IcrcTokenAccounts

frontend/src/lib/derived/universes.derived.ts, frontend/src/tests/lib/derived/universes.derived.spec.ts
Add the ICRC Tokens universes to the main `universesStore`.
After this, the token appears in the token selector (if present)
* Add `icrcTokensUniversesStore` as part of the `universesStore`.
* Test that `universesStore` includes ICRC Tokens when present.
Not necessay.
=> GIX-2118: Add ckETH to universesStore

frontend/src/lib/api/icrc-index.api.ts, frontend/src/lib/api/wallet-index.api.ts, frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/constants/wallet.constants.ts, frontend/src/lib/services/ckbtc-convert.services.ts, frontend/src/lib/services/ckbtc-minter.services.ts, frontend/src/lib/services/wallet-transactions.services.ts, frontend/src/tests/lib/api/wallet-index.api.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletActions.spec.ts, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/lib/routes/Wallet.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts.services.spec.ts, frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts, frontend/src/tests/lib/services/wallet-transactions.services.spec.ts
- rename `ckbtc-index.api` -> `wallet-index.api` + add TODO to ultimately migrate the function to `icrc-index.api`
- rename `ckbtc-transactions.services` -> `wallet-transactions.services`
- rename ckbtc constant to wallet
=> Refactor ckbtc index / transactions -> wallet

frontend/src/lib/constants/cketh-canister-ids.constants.ts
ckETHSEPOLIA Index is already present in mainnet.
In this PR, I add the mainnet canister id for that canister.
* Changes in `cketh-canister-ids.constants`.
Still pass.
Not necessary.
=> Chore: Add ckETHSEPOLIA index canister id

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/constants/cketh-canister-ids.constants.ts, frontend/src/lib/utils/env-vars.utils.ts
We want to use ckETH canister IDs from the environment/configuration.
1. Add `ckethLedgerCanisterId` and `ckethIndexCanisterId` fields to `EnvironmentVars` type.
2. Set the fields in `getBuildEnvVars`.
3. Use the fields in `frontend/src/lib/constants/cketh-canister-ids.constants.ts`.
Tested manually on `http://localhost:5173/` and `http://qsgjb-riaaa-aaaaa-aaaga-cai.localhost:8080/`
=> ckETH canisters in envVars

frontend/src/lib/routes/Accounts.svelte
Editor throw a warning "Void function return value is used " because the function is not a promise.
=> fix: warning "Void function return value is used"

frontend/src/lib/components/accounts/IcrcTokenAccountsFooter.svelte, frontend/src/lib/routes/Accounts.svelte, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/page-objects/Accounts.page-object.ts, frontend/src/tests/page-objects/IcrcTokenAccountsFooter.page-object.ts
Users can Send and Receive ICRC tokens such as ckETH.
In this PR, I setup the IcrcTokenAccontsFooter
* Render the IcrcTokenAccontsFooter in Accounts accordingly.
* Add an expect in the test for ckETH universe in Accounts.spec
* New IcrcTokenAccontsFooterPo
* New methods in AccountsPo 
Not necessary
=> GIX-2123: Setup IcrcTokenAccountsFooter

frontend/src/lib/api/icrc-ledger.api.ts, frontend/src/lib/api/wallet-ledger.api.ts, frontend/src/lib/routes/Accounts.svelte, frontend/src/lib/services/ckbtc-accounts-loader.services.ts, frontend/src/lib/services/ckbtc-accounts.services.ts, frontend/src/lib/services/ckbtc-tokens.services.ts, frontend/src/lib/services/wallet-accounts.services.ts, frontend/src/lib/services/wallet-loader.services.ts, frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/lib/api/wallet-ledger.api.spec.ts, frontend/src/tests/lib/components/accounts/CkBTCWithdrawalAccount.spec.ts, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts-loader.services.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts.services.spec.ts, frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts, frontend/src/tests/lib/services/ckbtc-tokens.services.spec.ts, frontend/src/tests/lib/services/ckbtc-withdrawal-accounts.services.spec.ts, frontend/src/tests/lib/services/wallet-accounts.services.spec.ts, frontend/src/tests/lib/services/wallet-loader.services.spec.ts, frontend/src/tests/routes/app/accounts/page.spec.ts, frontend/src/tests/routes/app/tokens/page.spec.ts
We need more generic api and services to implement the Icrc wallet page without duplication and I also want ultimately to improve the loading the accounts because with current implementation we duplicate code and calls.
- `ckbtc-ledger.api` -> `wallet-ledger.api`
- `ckbtc-accounts-balance.servies` -> `wallet-accounts.services`
- `ckbtc-accounts-loader` -> `wallet-loader.services`
- remove `ckBTC` from various function name - e.g. `getCkBtcToken` -> `getToken`
No functional changes in this PR.
=> Refactor ckBTC loading services and api -> wallet

frontend/src/lib/pages/IcrcTokenAccounts.svelte, frontend/src/tests/lib/pages/IcrcTokenAccounts.spec.ts, frontend/src/tests/mocks/icrc-accounts.mock.ts, frontend/src/tests/page-objects/IcrcTokenAccounts.page-object.ts
Render the Main account when the user selects a ckETH universe.
* Implement the IcrcTokenAccounts logic to render AccountCard from the accounts store.
* New IcrcTokenAcconuts.spec: test that AccountCard or SkeletonCard are rendered accordingly.
=> GIX-2121: Render accounts in IcrcTokenAccounts

frontend/src/lib/derived/sns/sns-selected-project.derived.ts, frontend/src/tests/lib/components/accounts/SnsTransactionsList.spec.ts, frontend/src/tests/lib/components/accounts/SnsWalletTransactionsObserver.spec.ts, frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts, frontend/src/tests/lib/derived/sns/sns-selected-project.derived.spec.ts, frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts, frontend/src/tests/lib/pages/SnsProposals.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts
snsOnlyProjectStore should not return universes of ICRC Tokens. It's used in specifically SNS only places.
* Fix `snsOnlyProjectStore` to check whether the current universe is an ICRC Token universe.
I know that SNS universes are actually ICRC Tokens. But in our current code, that is not the case, and until we refactor to use the same, we consider them differently.
* Add a test case for `snsOnlyProjectStore`.
Test was failing without the fix.
=> GIX-2121: Fix snsOnlyProjectStore

frontend/src/lib/components/accounts/CkBTCAccountsFooter.svelte, frontend/src/lib/derived/selected-universe.derived.ts, frontend/src/lib/pages/CkBTCAccounts.svelte, frontend/src/lib/pages/CkBTCWallet.svelte, frontend/src/lib/routes/Accounts.svelte, frontend/src/lib/services/ckbtc-accounts.services.ts, frontend/src/lib/services/ckbtc-convert.services.ts, frontend/src/lib/services/ckbtc-tokens.services.ts, frontend/src/lib/services/wallet-accounts.services.ts, frontend/src/lib/services/wallet-tokens.services.ts, frontend/src/lib/services/wallet-uncertified-accounts.services.ts, frontend/src/routes/(app)/(nns)/tokens/+page.svelte, frontend/src/tests/lib/components/accounts/CkBTCAccountsFooter.spec.ts, frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts, frontend/src/tests/lib/pages/CkBTCAccounts.spec.ts, frontend/src/tests/lib/pages/CkBTCWallet.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/routes/Wallet.spec.ts, frontend/src/tests/lib/services/ckbtc-accounts.services.spec.ts, frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts, frontend/src/tests/lib/services/ckbtc-tokens.services.spec.ts, frontend/src/tests/lib/services/wallet-accounts.services.spec.ts, frontend/src/tests/lib/services/wallet-tokens.services.spec.ts, frontend/src/tests/lib/services/wallet-uncertified-accounts.services.spec.ts
This PR allow us in #3894 to extract a common WalletPageContent that can be used by Icrc and ckBTC wallet pages without the need of duplicating any loading logic.
- extract sync/load functions from `ckbtc-accounts.services` -> `wallet-accounts.services`
- extract load function from `ckbtc-token.services` -> `wallet-token.services` (I'm not sure here we do not have a duplicate but moving it was a must to be able to move above functions. we can clean up in another PR if duplicate)
- rename current `ckbtc-accounts.services` to `ckbtc-uncertified-accounts.services` to resolve name clashes
- remove ckBTC in function names - e.g. `syncCkBTCAccounts` -> `syncAccounts` (one of the function that will be use in the generic Wallet Page)
No functional changes.
=> Refactor ckBTC sync/load tokens and accounts to wallet

frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
Avoid unnecessary calls to data that almost never changes.
In this PR, add functionality in `loadIcrcToken` to not request data when already loaded.
This will help call `loadIcrcToken` whenever is needed and not worry about making unnecessary calls.
* In `loadIcrcToken` do not fetch data if already present in store.
* Test the new functionality in `loadIcrcToken`.
Not necessary yet. This is not used in prod yet.
=> GIX-2144: Do not request token data if present

frontend/src/app.d.ts, frontend/src/lib/components/accounts/IcrcTokenAccountsFooter.svelte, frontend/src/lib/modals/accounts/IcrcTokenAccountsModals.svelte, frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte, frontend/src/lib/routes/Accounts.svelte, frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/lib/types/icrc-accounts.modal.ts, frontend/src/lib/utils/modals.utils.ts, frontend/src/tests/lib/modals/accounts/IcrcTokenTransactionModal.spec.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/services/icrc-accounts.services.spec.ts, frontend/src/tests/page-objects/Accounts.page-object.ts, frontend/src/tests/page-objects/IcrcTokenAccountsFooter.page-object.ts, frontend/src/tests/page-objects/IcrcTokenTransactionModal.page-object.ts
User can send ICRC Tokens
It's a fairly big PR, but the functionality was better tested once all was in.
* Add new event name `nnsIcrcTokenModal` to HTMLAttributes.
* Implement the button to open the Send modal.
* New component IcrcTokenAccountsModals to render the Icrc Token modals. For now only `IcrcTokenTransactionModal`. The type of the data needed differes from ckBTC and SNS; therefore, I couldn't easily reuse any. I bet we can further improve this, but in another PR.
* New IcrcTokenTransactionModal that renders a TransactionModal and makes the ICRC Token transfer.
* Render IcrcTokenAccountsModals in Accounts
* New icrc accounts service `icrcTransferTokens`. There is some duplication with ckBTC. We can improve this further.
* New types for icrc-accounts modals.
* New modal util …
=> GIX-2122: Send CkETH Tokens

frontend/src/lib/routes/Accounts.svelte, frontend/src/lib/services/$public/app.services.ts, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/services/_public/app.services.spec.ts, frontend/src/tests/utils/cketh.test-utils.ts
CkETH will also be visible for non-logged in users.
In this PR, load the ckETH canisters on public init along the SNS projects.
This is not enough. We also need to load the tokens. That will come in another PR.
* Move `loadCkETHCanisters` to app.services and remove it from Accounts.svelte.
* Add a test util `setCkETHCanisters`.
* The Accounts tests now need to ckETH set because it's not loading them.
* Add tests for `initAppPublicData` to check that loads the ckETH canisters accordingly.
Not necessary.
=> GIX-2144: Load ckETH canisters on init public

frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte, frontend/src/lib/components/accounts/IcrcWalletTransactionsList.svelte, frontend/src/tests/lib/components/accounts/IcrcWalletTransactionsList.spec.ts
We want the ckBTC wallet component to have full control over the transactions list in order to:
1. Include pending transactions mapped from `PendingUtxo`s
2. Merge some transactions into a single transaction, such as Approve+Transfer or Failed+Reimbursed.
This control was accomplished with https://github.com/dfinity/nns-dapp/pull/3828 by passing a `UITransaction[]` from `CkBTCTransactionsList` to `IcrcTransactionsList`.
Unfortunately, before we could make use of this, the effort was reversed in https://github.com/dfinity/nns-dapp/pull/3884 by passing only `mapCkbtcTransaction` (which maps individual transactions) from `CkBTCTransactionsList` to `IcrcWalletTransactionsList`.
In this PR we, once again, give `CkBTCTransactionsList` control over the full list by passing a function that maps a …
=> Map the list of transactions instead of individual transactions

dfx.json, scripts/nns-dapp/test-config-assets/mainnet/arg.did, scripts/nns-dapp/test-config-assets/mainnet/env
Include ckETH canister IDs in mainnet module args.
1. Set mainnet canister IDs for ckETH canisters in `dfx.json`.
2. Run `scripts/nns-dapp/test-config --update`.
Configs were updated by `scripts/nns-dapp/test-config --update` so the canister IDs were picked up.
not necessary
=> Set ckETH canister IDs in dfx.json

frontend/src/lib/services/$public/app.services.ts, frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/lib/services/icrc-tokens.services.ts, frontend/src/tests/lib/services/_public/app.services.spec.ts, frontend/src/tests/lib/services/icrc-tokens.services.spec.ts
Non-logged in users should also have available the ICRC Tokens.
What was missing was loading the token metadata in the store.
To accomplish that, I added a listener on icrcCanistersStore that loads the tokensStore for each ledgerCanisterId added there.
* New icrc token service `watchIcrcTokensLoadTokenData`.
* Set the watcher in the service `initAppPublicData`.
* Allow querying the token from `loadIcrcToken` for non logged in users.
* Test that tokens are loaded in `initAppPublicData`.
* Test new service `watchIcrcTokensLoadTokenData`.
Not necessary.
=> GIX-2144: Watch new IcrcToken canisters load token data

frontend/src/lib/components/accounts/IcrcTokenAccountsFooter.svelte, frontend/src/lib/components/accounts/NnsAccountsFooter.svelte, frontend/src/lib/components/accounts/ReceiveButton.svelte, frontend/src/lib/components/accounts/SnsAccountsFooter.svelte, frontend/src/lib/i18n/en.json, frontend/src/lib/modals/accounts/AccountsModals.svelte, frontend/src/lib/modals/accounts/IcrcReceiveModal.svelte, frontend/src/lib/pages/NnsWallet.svelte, frontend/src/lib/pages/SnsWallet.svelte, frontend/src/lib/routes/Accounts.svelte, frontend/src/lib/types/accounts.modal.ts, frontend/src/lib/types/i18n.d.ts, frontend/src/lib/types/icrc-accounts.modal.ts, frontend/src/lib/utils/modals.utils.ts, frontend/src/lib/utils/universe.utils.ts, frontend/src/tests/lib/components/accounts/IcrcTokenAccountsFooter.spec.ts, frontend/src/tests/lib/modals/accounts/IcrcReceiveModal.spec.ts, frontend/src/tests/lib/modals/accounts/SnsReceiveModal.spec.ts, frontend/src/tests/lib/pages/AccountsTest.svelte, frontend/src/tests/lib/routes/Accounts.spec.ts, frontend/src/tests/lib/utils/universes.utils.spec.ts
Implement CkETH receive modal feature.
- refactor and pass additional parameters to `ReceiveButton` and related modal to make the receive modal generic for icrc
- implement the parameters (either constant for ICRC or those of the universe)
- rename `SnsReceiveModal` to `IcrcReceiveModal`
- add modal for Icrc univeser on Accounts page
- adapt arial label for logo for icrc
=> Icrc receive modal

frontend/src/lib/components/accounts/IcrcTokenWalletFooter.svelte, frontend/src/lib/modals/accounts/IcrcTokenAccountsModals.svelte, frontend/src/lib/pages/IcrcWallet.svelte, frontend/src/lib/routes/Wallet.svelte, frontend/src/lib/types/icrc-accounts.modal.ts, frontend/src/tests/lib/routes/Wallet.spec.ts, frontend/src/tests/page-objects/Wallet.page-object.ts
Users can send ckETH from the wallet page.
* New IcrcTokenWalletFooter
* Add `sourceAccount` as optional field in `IcrcTokenTransactionModalData`.
* Pass the source account in IcrcTokenAccountsModal.
* Render IcrcTokenWalletFooter in IcrcWallet
* Render IcrcTokenAccountsModals accordingly in IcrcTokenWalletFooter
* Add some methods to WalletPo.
* Add a test in Wallet route to check that user can send ckETH tokens.
=> GIX-2122: Send from Wallet

CHANGELOG-Nns-Dapp-unreleased.md, frontend/src/lib/components/accounts/BitcoinAddress.svelte, frontend/src/lib/components/accounts/CkBTCWalletActions.svelte, frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte, frontend/src/lib/pages/CkBTCWallet.svelte, frontend/src/lib/services/ckbtc-minter.services.ts, frontend/src/tests/lib/components/accounts/CkBTCWalletActions.spec.ts, frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
In order to get a BTC deposit credited as ckBTC, we need to call `update_balace` on the minter.
If (and only if!) there are no new deposits with enough confirmations, the minter returns (as an error) any deposits that do not yet have enough confirmations.
This means that if there are new completed deposits, we need to call `update_balace` again to know if there are also any pending deposits.
1. In `frontend/src/lib/services/ckbtc-minter.services.ts` call `update_balance` until we get pending transactions (if there are any) and then put them in the store.
2. Pass `universeId` to `updateBalance` and to components that call `updateBalance` because it's used as a key in the store.
Test manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/ …
=> Add pending UTXOs to store after updateBalance

frontend/src/lib/components/accounts/IcrcTokenWalletFooter.svelte, frontend/src/lib/components/accounts/IcrcWalletPage.svelte, frontend/src/lib/pages/CkBTCWallet.svelte, frontend/src/lib/pages/IcrcWallet.svelte, frontend/src/lib/routes/Wallet.svelte, frontend/src/tests/lib/components/accounts/CkBTCAccountsTest.svelte, frontend/src/tests/lib/components/accounts/CkBTCWalletContextTest.svelte, frontend/src/tests/lib/pages/IcrcWallet.spec.ts, frontend/src/tests/page-objects/IcrcWallet.page-object.ts, frontend/src/tests/page-objects/IcrcWalletFooter.page-object.ts, frontend/src/tests/page-objects/ReceiveModal.page-object.ts
Add receive modal on Wallet page.
I did not manage to set up the test `should reload on close receive modal` correctly and ultimately thought we should not block moving forward because of it.
@lmuntaner can you have a look at the test after merge? or before merge?
- refactor `reloadAccount` from `CkBTCWallet` to `IcrcWallet`
- integrate `ReceiveButton` in icrc wallet footer
- connect existing reload account action with new integrated button
No function change in the reload process.
=> Icrc receive modal on wallet page

frontend/src/lib/derived/selected-universe.derived.ts, frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
ckETH doesn't have neurons nor proposals. It should not be visible and the page should default to NNS.
In this PR, the page defaults to NNS, but the token is still selectable in the Token Selector. That will come in another PR.
* Edit `selectedUniverseIdStore` to take into account the `icrcCanistersStore` when using NNS fallback or not.
* Add tests for new functionality.
=> GIX-2152: ckETH not selected in governance

frontend/src/lib/derived/selectable-universes.derived.ts, frontend/src/tests/lib/derived/selectable-universes.derived.spec.ts, frontend/src/tests/utils/cketh.test-utils.ts, frontend/vitest.setup.ts
CkETH has no neurons or proposals.
In this PR, the CkETH universe is not selectable when the user is in Neurons or Proposals.
* Use the `icrcCanistersStore` in `selectableUniversesStore` to determine whether ICRC Token universe is selectable based on the page.
* Add tests for new functionality.
* Add a helper to reset after setting CkETH canisters.
* Add new env vars to vitest setup.
Not necesary.
=> GIX-2152: Non Selectable ICRC Tokens in Governance page

frontend/src/lib/components/accounts/IcrcTokenWalletFooter.svelte, frontend/src/lib/modals/accounts/IcrcTokenAccountsModals.svelte, frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte, frontend/src/lib/pages/IcrcWallet.svelte, frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/lib/types/icrc-accounts.modal.ts, frontend/src/tests/lib/routes/Wallet.spec.ts, frontend/src/tests/page-objects/Wallet.page-object.ts
User sees the updated balance after making a transaction from the Wallet page.
* Add optional field `reloadSourceAccount` to the modal props.
* Add prop `reloadTransactions` to IcrcTokenWalletFooter. Pass a `reloadSourceAccount` when opening the `"icrc-send"` modal.
* Add same field to IcrcTokenTransactionModal props. Call it on transfer success.
* Add expects to current test `"user can transfer ckETH tokens"`.
* Add method to WalletPo
=> GIX-2151: Reload after transaction

frontend/vitest.setup.ts
We want to enable CkETH for mainnet.
In this PR, enable the feature flag only for tests as a first step.
* Set `true` for `ENABLE_CKETH` in vitest.
Not yet.
=> Chore: Enable CkETH for tests

frontend/src/lib/components/accounts/TransactionCard.svelte
The icon for received transactions changes color based on light/dark theme.
This is done with a `@include media.dark-theme` selector which has a higher specificity than the `.pending` class for the orange icon for pending transactions.
Because of this, the pending transactions aren't orange in the dark them.
Use themed color constants for the transaction icon instead of the `@include media.dark-theme` selector.
Before:
After:
Covered by existing entry about pending transactions.
=> Use themed colors instead of theme selector

frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte, frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/lib/utils/token.utils.ts, frontend/src/tests/lib/utils/token.utils.spec.ts, frontend/src/tests/mocks/cketh-accounts.mock.ts
Support tokens with different decimal precision.
In this PR, add optional parameter to helper `numberToE8s`.
* Add new optional parameter `token` in `numberToE8s`.
* New optional param `token` in `IcrcTransferTokensUserParams`.
* New optional `token` param in the `transferTokens` icrc service
* Use new param in the IcrcTokenTransactionModal.
* Add test in `numberToE8s` for the new functionality.
=> GIX-2154: Support decimals numberToE8s

frontend/src/lib/types/icrc.ts, frontend/src/lib/utils/icrc-tokens.utils.ts, frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts, frontend/src/tests/mocks/cketh-accounts.mock.ts, frontend/src/tests/mocks/icrc-tokens.utils.spec.ts, frontend/src/tests/mocks/sns-aggregator.mock.ts, frontend/src/tests/mocks/sns-projects.mock.ts
`Token.decimals` in the next version of `ic-js` is a `number`, so `IcrcTokenMetadata.decimals` needs to be a number too.
Change `IcrcTokenMetadata.decimals` from `bigint` to `number`.
Manual spot check.
not necessary
=> Make decimals number instead of bigint

frontend/package-lock.json, frontend/src/lib/components/accounts/BitcoinEstimatedAmountReceived.svelte, frontend/src/lib/derived/sns/sns-token-symbol-selected.store.ts, frontend/src/lib/derived/universes-tokens.derived.ts, frontend/src/lib/types/icrc.ts, frontend/src/tests/lib/components/tokens/TokensTable.spec.ts, frontend/src/tests/lib/derived/sns/sns-selected-project-new-tx-data.derived.spec.ts, frontend/src/tests/lib/derived/universes-tokens.derived.spec.ts, frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts, frontend/src/tests/lib/modals/neurons/DisburseSnsNeuronModal.spec.ts, frontend/src/tests/lib/modals/sns/SnsStakeNeuronModal.spec.ts, frontend/src/tests/lib/modals/sns/SplitSnsNeuronModal.spec.ts, frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts, frontend/src/tests/mocks/ckbtc-accounts.mock.ts, frontend/src/tests/mocks/cketh-accounts.mock.ts, frontend/src/tests/mocks/sns-projects.mock.ts, frontend/src/tests/mocks/tokens-page.mock.ts, frontend/src/tests/mocks/transaction-fee.mock.ts
ic-js has a breaking change that requires the `decimals` field in `Token` and `TokenAmount` rejects tokens with `decimals !== 8`.
This PR bumps the next version of ic-js.
We don't yet use `TokenAmountV2` so this PR breaks ckETH.
1. Ran `npm run upgrade:next`
2. Remove the `decimals` field from `IcrcTokenMetadata`. It's now inherited from `Token`.
3. Set `token.decimals` in tests and mocks.
4. Set `mockCkETHToken.decimals = 8` to make tests pass while keeping this PR small. It will be set back to 18 when we use `TokenAmountV2`.
5. Set `token.decimals` in `frontend/src/lib/components/accounts/BitcoinEstimatedAmountReceived.svelte` which creates an ad hoc token instead of getting it from the store.
6. Set `token.decimals` in `frontend/src/lib/derived/sns/sns-token-symbol-selected.store.ts`. …
=> Bump ic-js with Token.decimals

frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte, frontend/src/lib/services/ckbtc-accounts.services.ts, frontend/src/lib/services/ckbtc-convert.services.ts, frontend/src/lib/services/icrc-accounts.services.ts, frontend/src/lib/services/sns-accounts.services.ts, frontend/src/lib/utils/token.utils.ts, frontend/src/tests/lib/services/icrc-accounts.services.spec.ts, frontend/src/tests/lib/utils/token.utils.spec.ts
`transferTokens` currently takes a `amount: number` and optional `token` to convert the number to `e8s`.
When we use `TokenAmountV2`, the `token` can't be optional because if we need to use a fallback we can't be certain that we use the token when we have to.
So instead pass `ulps` to `transferToken` and convert on the calling side. The calling side knows better whether it's safe to use `numberToE8s` or whether numbsToUlps` with `token` should be used.
This PR also includes most of the changes from https://github.com/dfinity/nns-dapp/pull/3931
1. Change the parameters of `transferToken` to accept `amountUlps: bigint` and don't use `numberToE8s`.
2. Change functions that used to share the params type with `transferTokens` but which now accept `amount: number` instead of `amountUlps: …
=> Pass ulps to transferTokens

scripts/nns-dapp/migration-test
The migration test provides backtraces on error.  This is useful, however if we break the long main test function into smaller functions, the backtrace tells us at which stage the test failed.  The backtrace does provide line numbers but typically just knowing the stage is enough, so providing the name avoids having to look in the code for the line number.
- Split the migration test into smaller functions.
Sample backtrace before:
```
ERROR: Schema is not as expected.
Expected: AccountsInStableMemory
Actual:   Map
=============================================
at: ./scripts/nns-dapp/migration-test.canister:1: assert_schema_is
at: ./scripts/nns-dapp/migration-test:104: test_upgrade_downgrade
at: ./scripts/nns-dapp/migration-test:117: main
```
Sample backtrace after:
```
ERROR: Schema is not …
```
=> tweak: Finer backtrace for migration test

CHANGELOG-Nns-Dapp-unreleased.md, scripts/nns-dapp/test-exports
When the nns-dapp canister API  changes, there are checks to make sure that the change is intentional.  There is a "golden file" that stores the expected API for each flavour of build.  If there is a mismatch in a test build, the check prints:
```
Exports do not match
If this looks correct, run 'scripts/nns-dapp/test-exports --wasm nns-dapp_test.wasm.gz --update-golden' to update the golden file
```
That looks helpful.  But what is not helpful is that the above command updates the production golden file with the test API.
- In the suggested command, specify which flavour of golden file to update.
The message is now:
```
Exports do not match
If this looks correct, run 'scripts/nns-dapp/test-exports --wasm nns-dapp_test.wasm.gz --update-golden --flavour test' to update the golden file
``` …
=> fix: Specify which flavour to update

frontend/src/lib/api/sns.api.ts, frontend/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte, frontend/src/lib/constants/icp.constants.ts, frontend/src/lib/constants/neurons.constants.ts
Clean up after fast development to support different decimals.
In this PR, remove usage of `E8S_PER_ICP` and introduce a new constant `ULPS_PER_MATURITY` instead.
* Remove division by `E8S_PER_ICP` in logging info.
* Use `ULPS_PER_MATURITY` instead of `E8S_PER_ICP` in maturity properties. (Not all places yet).
* Hardcode the e8s for `MIN_NEURON_STAKE`, it has nothing to do with `E8S_PER_ICP` anyway.
Still passing
Not necessary.
=> GIX-2150: New constant ULPS_PER_MATURITY

declarations/nns_governance/nns_governance.did, declarations/nns_ledger/nns_ledger.did, declarations/nns_registry/nns_registry.did, declarations/sns_governance/sns_governance.did, declarations/sns_ledger/sns_ledger.did, declarations/sns_root/sns_root.did, declarations/sns_swap/sns_swap.did, declarations/sns_wasm/sns_wasm.did, dfx.json
=> Update IC candid files to release-2023-11-29_23-01

scripts/nns-dapp/migration-test
The name of the help text function is incorrect in the migration test, so the help does not include the intended text.
- Rename the help text function to the correct value.
- Run locally, `$ scripts/nns-dapp/migration-test --help` now shows the desired text.
- Too minor to warrant a changelog entry
=> Fix function name
