- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/accounts_store/schema/proxy/enum_boilerplate.rs
The `ProxyDb` acts as an intermediary during a migration, keeping data in the main database up to date until a second database is ready.  The implementation is however currently partial and does not store the main and secondary db.
- This PR fills out the contents of the ProxyDB struct so that we now actually have these two databases.
- Existing CI should suffice
> feat: Accounts ProxyDb has authoritative/secondary DB

- frontend/src/tests/lib/components/project-detail/ProjectSwapDetails.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingConfirmationToolbar.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelect.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/SnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/utils/ckbtc.utils.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Remove `E8S_PER_ICP` from NNS Dapp.
In this PR, remove the usage of the constant in the test files.
* Remove usage of `E8S_PER_ICP` by not multiplying and adding the value directly or using `ulpsToNumber`.
> GIX-2150: Remove E8S_PER_ICP from tests

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/derived/paths.derived.ts
- frontend/src/lib/utils/navigation.utils.ts
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/lib/derived/paths.derived.spec.ts
- frontend/src/tests/lib/utils/navigation.utils.spec.ts
The menu item "Tokens" in the left sidebar should redirect the user to `/tokens`.
* Add the `AppPath.Tokens` to the selected paths for "Tokens" menu item.
* Add optional param `tokensEnabled` to util `buildAccountsUrl`.
* Add `ENABLE_MY_TOKENS` flag store in `accountsPathStore`.
* Test the MenuItems with flag enabled.
* Add test for `accountsPathStore` when flag is enabled.
* Add test case for `buildAccountsUrl` with new param `tokensEnabled`.
> GIX-1989: Use /tokens in menu items

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/derived/icp-tokens-list-visitors.derived.ts
- frontend/src/lib/derived/tokens-list-base.derived.ts
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-base.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/mocks/tokens-page.mock.ts
Use TokenAmountV2 in the `/tokens` page. Otherwise it won't work becuase ckETH is also there.
In this PR, change the type of `fee` and `balance` in `UserTokenData` to be of type `TokenAmountV2`.
* Change the type of the fields of `UserTokenData`.
* Change the tokens list derived stores to create `TokenAmountV2` for balance and fee.
* Change mock data of `UserTokenData` to use `UserTokenData`.
* Change test files for tokens list derived stores to expect `TokenAmountV2`.
> GIX-2150: Use TokenAmountV2 new tokens page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
- frontend/src/tests/mocks/icrc-transactions.mock.ts
When withdrawing ckBTC to BTC with ICRC-2 we first make an Approve transaction and then the minter makes a Burn transaction. Since this is part of a single process, we want to render it as a single transaction in the wallet.
1. Pass both the previous `IcrcTransactionWithId` and previously returns `UiTransaction` to `mapCkbtcTransaction`. Note that transactions are mapped in reverse chronological order, so the previous transaction happened later in time.
2. In `mapCkbtcTransaction`, if the current transaction is an Approve transaction, check if it was followed by a Burn transaction, and if so, add the fee to the amount burned and remove the Approve transaction from the list.
1. Added a test for `mapCkbtcTransaction` with a transaction that should be merged and with one that shouldn't be …
> ckBTC: Merge Approve and Burn transactions into one

- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/routes/app/tokens/page.spec.ts
Tokens pages supports ckETH.
In this PR, load the token and balances of the ICRC Canisters. Which ckETH belongs to.
* New function called on init in Tokes page route: `loadIcrcTokenAccounts`.
* Refactor `loadCkBTCAccountsBalances` to share code with `loadIcrcTokenAccounts`. This is the same that we have at the moment in the Accounts.svelte.
* Test that if there are ICRC Canisters loaded, the tokens are present in the Tokens page.
> GIX-2150: Add ckETH to tokens page

- frontend/src/routes/(app)/(u)/(accounts)/+page.svelte
- frontend/src/tests/routes/app/home-page.spec.ts
When Tokens is enabled, the home page should be the tokens page.
The current home page is the one in `routes/(app)/(u)/(accounts)/+page.svelte`.
In this PR, I change the logic of this component to render the Tokens route instead of the current Accounts route.
In another PR I'll move the layout and this home page to `routes/(app)/(home)`.
* Change logic in `(app)/(u)/(accounts)/+page.svelte` to render either the Accounts route or the Tokens route.
* New test for this page to check which component is rendered depending on the flag.
> GIX-2171: Use Tokens in "/"

- frontend/src/routes/(app)/(u)/(accounts)/+layout.svelte
- frontend/src/tests/routes/app/accounts/layout.spec.ts
User can go back to the main tokens pages from the ICP accounts page.
In this PR, add the back button when user is in ICP accounts page with Tokens Table.
* Pass the `back` prop to `Content` in accounts layout.
* Add two test cases in accounts layout to check when the back button should be present.
> GIX-2084: Add Back button to ICP Tokens page

- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
- frontend/src/lib/types/tokens-page.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
The whole row on the Tokens page is really a link to another page.
In this PR, introduce a new optional field in UserTokenData: `"rowHref"`. Optional, because in the icp tokens page the rows are not clickable.
* Add optional field `rowHref` in UserTokenData type.
* TokensTableRow uses the new field to render a link with href or not.
* Test that Tokens table renders row with href when present.
> GIX-2110: Use AnchorTag for row if needed

- frontend/src/lib/derived/universes-tokens.derived.ts
- frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
- frontend/src/lib/modals/accounts/CkBTCTransactionTokenModal.svelte
- frontend/src/tests/lib/derived/universes-tokens.derived.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
Use CkBTCTransactionModal in Tokens page. To do that, I need the `CkBTCTransactionModal` to accept `TokenAmountV2` as fee and the token to be type `Token` instead of `IcrcTokenMetadata`.
* Change prop type `transactionFee` and `token` in CkBTCTransactionModal.
* Change the type of derived store `ckBTCTokenFeeStore`.
* Change type of local variable in CkBTCTransactionTokenModal
* Change expect type in `ckBTCTokenFeeStore`.
* Change the prop type in CkBTCTransactionModal test file.
Not necessary.
> GIX-1983: Add TokenAmountV2 ckBTC transaction modal

- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
Users can navigate to Wallet or ICP Accounts page from the Tokens page.
* Populate the rowHref field in `tokensListUserStore`.
* Add new field in `tokensListUserStore` test files. Rename some local variables to `xxxNoBalance` to better represent what they are.
> GIX-2110: Populate rowHref Tokens page

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
Users can navigate to the wallet page from the ICP accounts page with the tokens table.
* Populate `rowHref` in `icpTokensListUser` derived store.
* Add new field to the `icpTokensListUser` test data.
> GIX-2110: Populate rowHref icp accounts

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/package.json
Latest NodeJS comes with npm v10.2.3. Yet, in package.json we don't allow npm to be greater than 10.
In this PR, allow npm to be greater than 10.
* Change the accepted version range of `npm` in package.json of frontend.
* Changes in package-lock.json after runnin `npm i`.
Tests should be fixed now.
> Fix: Allow npm > v10

- frontend/src/lib/modals/accounts/AccountsModals.svelte
- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/lib/types/accounts.modal.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/page-objects/Accounts.page-object.ts
- frontend/src/tests/page-objects/NnsAccounts.page-object.ts
Users can add an account from the ICP tokens table.
* New AccountsModalType: "add-icp-account"
* Add AddAccountModal to AccountsModals.
* Trigger a `openAccountsModal` when the "Add Account" row is clicked.
* Add click attributes to the "Add Account" row in NnsAccounts.
* Add a test in NnsAccounts that the tabindex is properly added to the Add Account row.
* Add a test in the Accounts route that the user can add an account.
* Add methods to POs
> GIX-2059: Add Account from ICP tokens table

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
The derived debug implementation for the accounts store tries to print e.g. all the accounts in the database.  The printout is huge and not useful.  Much more useful is a summary, such as how many accounts there are in in the authoritative database.
- Provide a custom Debug implementation for `AccountsStore` that summarizes the contents instead of trying to print everything.
Here is a sample debug printout in compact form, before and after:
```
AccountsStore { accounts_db: AccountsDbAsProxy { authoritative_db: UnboundedStableBTreeMap(AccountsDbAsUnboundedStableBT
reeMap { accounts: StableBTreeMap{.. 1000 entries} }), migration: None }, hardware_wallets_and_sub_accounts: {AccountIde
ntifier { hash: [228, 151, 180, 173, 185, 89, 137, 231, 11, 131, 115, 103, 149, 207, 216, 1, 84, 172, 45, …
```
> chore: Useful debug print for accounts store

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store/schema/proxy.rs
When migrating from one database to another, we need to store the migration state.
- Replace the secondary db with a container that holds both the second db and the migration state.
None - there are no functional changes.
> Placeholder for migration state

- frontend/src/lib/components/accounts/CkBTCWithdrawalAccount.svelte
- frontend/src/lib/services/ckbtc-minter.services.ts
- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/routes/app/tokens/page.spec.ts
Users might not understand that they need to update the balance after converting BTC to ckBTC. Therefore, the NNS Dapp makes the call to the minter in the background.
In this PR, I add that functionality currently present in the ckBTC Accounts to the Tokens page.
* Call service ckBTC Minter `updateBalance` in the Tokens page.
* Add a test that simulates the api returning completed UTXOs and checking that the balance is updated.
I also tested manually that after getting some test bitcoins, the balance was never updated even after refreshing. When I introduced the call, the balance was refreshed when the user visited the page.
> GIX-2057: Add ckBTC logic to Tokens page

- frontend/src/lib/components/tokens/TokensTable/actions/ReceiveButton.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/SendButton.svelte
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/page-objects/jest.page-object.ts
- frontend/src/tests/page-objects/playwright.page-object.ts
- frontend/src/tests/types/page-object.types.ts
There was a navigation and full refresh when the user clicked directly in one of the action buttons.
We need to prevent the default behavior of the link as well as stop propagation.
* Add `preventDefault` directive to ReceiveButton and SendButton.
The GoToDetailButton will be refactoring into a single span with no clicking functionality because we should rely on the rowHref instead.
* Test that when clicking Send or Receive, the default is prevented.
Not necessary.
> Fix: TokensTable actions triggering link

- frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte
- frontend/src/lib/utils/universe.utils.ts
- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/lib/utils/universes.utils.spec.ts
- frontend/src/tests/page-objects/TokensRoute.page-object.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Users can send ICRC Tokens like ckETH from the Tokens page.
* Change the type of `token` in IcrcTokenTransactionModal to be able to pass the token from UserTokenData. There is an issue to combine "Token" and "IcrcTokenMetadata" together.
* New universe utils `isIcrcTokenUniverse`.
* Add new modal type `"icrc-send"` in tokens route page and render IcrcTokenTransactionModal whe this type is triggered.
* Test new universe util.
* Test that user can send ckETH from Tokens route.
* Add convenient methods to TokensRoute page object.
> GIX-1983: Add ICRC Send Transaction

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2023-12-06_23-01+p2p

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/TransactionCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/transaction.ts
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
- frontend/src/tests/page-objects/TransactionCard.page-object.ts
When withdrawaing ckBTC to BTC fails, the minter will mint the previously burned amount (minus fees) back into the user's account.
We want to render these transactions as Reimbursement transactions.
1. Add `isReimbursement` field to `UiTransaction`.
2. Decode the memo on mint transactions. If we can decode them as failed KYT, mark the transaction as a reimbursed transaction.
3. Render `isReimbursement` transactions with `IconReimbursed` and alert colors.
> Render ckBTC reimbursement transactions

- rs/proposals/src/lib.rs
A proposal failed to render the payload: https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=126392
The problem was a [breaking change in the IC for the payload types](https://github.com/dfinity/ic/blob/master/rs/nervous_system/root/src/change_canister.rs#L137). One field was removed from two types and also renamed.
Yet, updating the IC depedency is becoming a huge pain. Therefore, to solve the issue in the short term, I hardcoded the types in the PR instead of importing them.
* Do not import AddNnsCanisterProposal but hardcode it.
* Do not import ChangeNnsCanisterProposal but hardcode it.
* Remove the field `authz_changes` from both `XxxTrimmed` type and transform functions.
* I downloaded the proposal. It was failing withuot this changes, but with this changes it was …
> Fix: Proposal payload rendering

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/derived/tokens-list-visitors.derived.ts
- frontend/src/lib/pages/SignInTokens.svelte
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/tokens-page.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-visitors.derived.spec.ts
Populate the loading state for the Tokens page.
* New convenience type `UserToken`.
* Use the new type instead of the union of types or `UserTokenData` in the components.
* Use the new type in the derived stores.
* Return a `UserTokenLoading` when the balance or the token are not available in `tokensListUserStore` and `tokensListVisitorsStore`.
* Adapt tests for `tokensListUserStore`. It returns a loading state, not a `xxxNoBalance`.
* Implement better tests for `tokensListVisitorsStore` and add tests for the loading state.
> GIX-2062: Use loading status Tokens Page

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store/schema.rs
- rs/backend/src/accounts_store/schema/map.rs
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/accounts_store/schema/proxy/enum_boilerplate.rs
To migrate data from one database to another, we wish to use ranges to get the next N accounts.
- Add `range()` to the `AccountsDb` trait.
- None.  These are straight proxies to the `BTreeMap` so tests probably aren't warranted.
> feat: Add range to AccountsDb trait

- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
Fix broken nf commitment title dots on small mobile screens like galaxy S8  (screenshots)
- remove text clamp
- limit dots minimal size
| <img width="307" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/08335465-e77c-422d-8eee-eaeea49a5104"> | <img width="310" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/8588d0d3-04d5-4340-b37e-a352bfc4877c"> |
Not necessary since the feature is not on prod yet.
> style: fix broken nf commitment title on mobile

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/proposals/src/lib.rs
Proposal schemas change, and not always in a forwards and backwards compatible fashion.  If that happens, the proposal rendering needs to not break.
- If proposals fail to parse strictly with the expected types, use `idl2json` for a best-effort conversion.
This proposal previously failed to parse:
```
$ ./scripts/proposals/mk-test-vector --network mainnet --proposal 126392
```
It now parses as:
```
[{"arg":"4449444c00017f","canister_id":"rdmx6-jaaaa-aaaaa-aaadq-cai","compute_allocation":[],"memory_allocation":[],"mode":{"upgrade":null},"query_allocation":[],"stop_before_installing":true,"wasm_module":"Bytes with sha256: 1950912f23acea10a63ea1c0a70ac316f2cea6055acde3044e24cb79682c6d40"}]
```
> Proposal rendering fallback

- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/page-objects/TokensPage.page-object.ts
- frontend/src/tests/page-objects/TokensRoute.page-object.ts
- frontend/src/tests/page-objects/TokensTable.page-object.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
User can open the Receive modal for ckBTC in the Tokens page.
* Add the `CkBtcReceiveModal` in the tokens route page.
* Add a test that the balance is updated after a click in the receive modal.
* Add convenience methods in POs
Not necessary.
> GIX-1983: Add ckBTC receive modal

- frontend/package-lock.json
Use `retrieveBtcStatusV2ByAccount` added in https://github.com/dfinity/ic-js/pull/503
Ran `npm run upgrade:next`
Manually tested in a separate branch.
not necessary
> Bump ic-js

- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/page-objects/TokensRoute.page-object.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Users can use the receive button of the Tokens Page for SNS and ICRC tokens like ckETH.
* In Tokens page: new modal type "icrc-receive" that opens the IcrcReceiveModal.
* Change `createReloadAccountBalance` to call the SNS service instead of `loadAccountsBalances`.
* Add convenience method in PO
* Add two tests, one for the receive modal for SNS projects, another for ckETH.
> GIX-1983: Tokens Page Receive Modal ICRC

- frontend/src/lib/components/universe/UniverseAccountsBalance.svelte
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/derived/universes-accounts-balance.derived.ts
- frontend/src/tests/lib/derived/universes-accounts-balance.derived.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/wallet-uncertified-accounts.services.spec.ts
`UniverseAccountsBalance` also holds balances that are not 8 decimals so it's misleading to call them `balanceE8s`.
Change `UniverseAccountsBalance.balanceE8s` to `balanceUlps`.
Updated
not necessary
> Rename UniverseAccountsBalance.balanceE8s to balanceUlps

- frontend/src/lib/components/transaction/TransactionForm.svelte
- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/sns-sale.services.ts
- frontend/src/lib/utils/accounts.utils.ts
- frontend/src/lib/utils/ckbtc.utils.ts
- frontend/src/tests/lib/utils/accounts.utils.spec.ts
`assertEnoughAccountFunds` is also used for accounts with decimals other than 8.
So it's misleading to call the parameter `amountE8s`.
Rename the parameter to `amountUlps`.
Updated
not necessary
> Rename parameter of assertEnoughAccountFunds from amountE8s to amountUlps

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/derived/paths.derived.ts
- frontend/src/lib/utils/navigation.utils.ts
- frontend/src/routes/(app)/(u)/(detail)/wallet/+layout.svelte
- frontend/src/tests/lib/derived/paths.derived.spec.ts
- frontend/src/tests/lib/utils/navigation.utils.spec.ts
- frontend/src/tests/routes/app/wallet/layout.spec.ts
There was a bug that the user was redirected to the Tokens page from an ICP wallet.
Instead, the user should go to the ICP Accounts.
* Change implementation of `buildAccountsUrl` to build an accounts page for NNS only.
* Add tests for `buildAccountsUrl`.
* Add tests for `accountsPathStore` which uses `buildAccountsUrl`.
* Add a test file for the wallet layout component which is were the bug was.
> Fix: Wallet back button tokens enabled

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
Add loading state in the ICP tokens table.
* Return the `UserToken` instead of `UserTokenData` in `icpTokensListUser`.
* Expect list of `UserToken` in NnsAccounts.
* Return a UserTokenLoading instead of an empty balance when the ICP account is not there.
* Change the test expectation when the accounts are not present in `icpTokensListUser`.
> GIX-2062: Loading state ICP tokens table

- frontend/src/lib/utils/accounts.utils.ts
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
`sumAmountE8s` is not specific to 8 decimals (or even to amounts, for that matter).
It just adds up a list of `bigint`s.
Rename `sumAmountE8s` to `sumAmounts`.
Updated
not necessary
> Rename sumAmountE8s to sumAmounts

- frontend/src/lib/components/accounts/BitcoinEstimatedAmountReceived.svelte
- frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/neurons/NnsNeuronAmount.svelte
- frontend/src/lib/components/neurons/NnsNeuronDetailCard.svelte
- frontend/src/lib/components/project-detail/CommitmentProgressBar.svelte
- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte
- frontend/src/lib/components/sns-neurons/SnsNeuronAmount.svelte
Migration to TokenAmountV2
Perform simple change from TokenAmount to TokenAmountV2 where it didn't require additional change because TokenAmountV2 is already supported.
Still passing.
Not necessary.
> GIX-2150: Migrate to TokenAmountV2

- frontend/src/lib/api/ckbtc-minter.api.ts
- frontend/src/tests/lib/api/ckbtc-minter.api.spec.ts
We want to fetch the status of BTC retrievals from the ckBTC minter canister so that we can display which transactions are pending and which have failed.
Add `retrieveBtcStatusV2ByAccount` to ckbtc-minter api to call `retrieveBtcStatusV2ByAccount` from ic-js.
Unit test was added.
not yet
> Add retrieveBtcStatusV2ByAccount to API

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api/sns-wrapper.api.ts
One SNS's root canister was frozen and it broke all SNSes in nns-dapp.
Don't throw an error when one of the SNSes is broken but just filter it out of the wrapper.
Tested manually by calling `dfx stop` on one of the root canisters.
Without the fix:
https://drive.google.com/file/d/1xF5zRp62HMpQTmlIWTcuWyl9r5JU0ZT7/view
With the fix:
https://drive.google.com/file/d/19VpUbd27HImQDAe0ywrB78tpFc8zQq9D/view
> GIX-2181: Work around frozen sns canister

- rs/backend/src/accounts_store/schema.rs
- rs/backend/src/accounts_store/schema/label_serialization.rs
- rs/backend/src/accounts_store/schema/label_serialization/tests.rs
Labels are serialized as `u32`.  On parsing, a u32 may not correspond to a valid schema.  There is an error type for tyhis, but it does not indicate what the invalid u32 is, which can be unhelpful.
- Include the u32 in the error.
- The corresponding test has been updated.
- Too minor
> chore: Show which invalid label

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/map.rs
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/state.rs
Unit tests require `Eq` to verify that state, accounts etc have the expected content.  However the implementations can be prohibitively inefficient with large data so we would prefer to have them present only in test code.
- Configure `Eq` and `PartialEq` to be created only in test code.
- For the ProxyDb, the implementation of PartialEq previously depended on converting an arbitrary database format into a `BTreeMap`.  This is unnecessarily expensive as we can iterate of the elements of the two databases regardless of the underlying implementation.
- Existing tests should suffice.
Too minor.
> clean: Implement Eq for tests only

- dfx.json
> Update didc release to 2023-12-15

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2023-12-13_23-01

- .github/workflows/update-snsdemo.yml
We have a bot that updates the snsdemo release we use in CI.
The automatic PR description also claims that it updates the IC commit but it does not.
Remove the line about the IC commit.
none
no necessary
> Fix automatic update PR description

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/lib/utils/accounts.utils.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/utils/accounts.utils.spec.ts
To open the TransactionModal or ReceiveModal in the ICP tokens table, I need to know which account to use based on the row clicked.
I could use the title, but that is fragile because the title might change and not be the name of the account.
Instead, I added an optional field to UserTokenData: accounIdentifier.
* New field `accountIdentifier` in `UserTokenData`.
* Populate the new field in `icpTokensListUser`.
* Populate the new field in `tokensListUserStore`. I changed the implementation to read all the universes accounts instead of the balance. I needed it to get the account identifier.
* Use function overloading in helper `sumAccounts`. Convenient to make sure the return is a `bigint` if there are accounts. I also changed the functionality slightly to return 0 when the list is empty. …
> GIX-2180: Add accountIdentifier UserTokenData

- CHANGELOG-Nns-Dapp-unreleased.md
- clippy.toml
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/assets.rs
- rs/backend/src/bin/nns-dapp-check-args.rs
- rs/backend/src/ledger_sync.rs
- rs/backend/src/main.rs
- rs/backend/src/state/partitions.rs
- rs/proposals/src/main.rs
- rs/sns_aggregator/src/state.rs
- scripts/lint-rs
Move more code from `dfn_core` to `ic_cdk`.
Note: Apparently `ic_cdk::println` defaults to printing to stdout in e.g. unit tets.  Could be useful.
- Change calls to `dfn_core..print` to `ic_cdk::println!`.
- Given that `std::println!` does nothing in production, prevent accidental usage of `std::println` in wasms by:
- Prohibiting `std::println!` and similar macros in `clippy.toml`
- Running clippy only against `wasm32-unknown-unknown` as `ic_cdk::println` is `std::println` when run natively, so triggers the lint.
- Note: It would be nicer if the prohibition in `clippy.toml` could be applied only when the target arch is `wasm32`.  I do not see a way of doing that.  It may perhaps be possible in other ways.
- See CI
- Fail to build for wasm32? - Nope, it builds.
- Build but fail at …
> Use ic-cdk println

- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/page-objects/Accounts.page-object.ts
Users can open the Receive modal from ICP tokens
* Listen for nnsAction in NnsAccounts and handle the `ActionType.Receive`.
* Add a test for the receive modal when Tokens enabled.
* Add methods to AccontsPo.
> GIX-2180: Receive in ICP tokens page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/ui/DayInput.svelte
- frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
- frontend/src/tests/lib/components/ui/DayInput.spec.ts
Solves the remaining error message after clicking on min/max button.
Steps:
- Add a too big number for the dissolve delay.
- Click on the Min/Max
- Input updated to a valid value, but the error is still displayed.
- update error visibility after min/max click
- "should update error message after Min/Max click"
> fix: error visibility after clicking on min/max

- frontend/src/tests/e2e/design.spec.ts
- frontend/src/tests/utils/e2e.test-utils.ts
I noticed a CI run where the token symbols were not masked out in the screenshot.
And I noticed we don't await the `page.evaluate` call that replaces the content.
I don't know if this is the reason but awaiting the call is the right thing to do.
Await the Playwright `page.evaluate` call in `replaceContent`.
test only
not necessary
> Await Playwright page.evaluate

- rs/proposals/src/lib.rs
@frederikrothenberger pointed out that functions are in fact sometimes sent over the wire.  While none of the types we currently convert include funstions, and IDLType disappears in Candid v10, it is a simple thing to support more types.
- In `type_2_idltype` include conversions for functions, classes and variables.
- None.  Not worth the effort for something that is not used now and will be discarded soon.
> feat: Convert more candid types

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/common/MaxButton.svelte
- frontend/src/lib/components/common/MinButton.svelte
- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/ui/DayInput.svelte
- frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
- frontend/src/tests/lib/components/ui/DayInput.spec.ts
The Min button set available minimum value.
- min button logic (+1)
- disable editing when maximum was set
- SetDissolveDelay should disable input when maximum is already selected
- DayInput supports disabled prop
> Fix min dissolve delay

- frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
- frontend/src/lib/modals/accounts/AccountsModals.svelte
- frontend/src/lib/types/accounts.modal.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/page-objects/Accounts.page-object.ts
Users can open the Send ICP modal from the tokens table in the ICP tokens page.
In this PR, I move the IcpTransactionModal from the NnsAccountsFooter to the AccountsModals.
This will make it easy to then open it when clicking in the icon of the tokens table.
* Add `"nns-send"` to AccountsModalsType.
* Remove IcpTransactionModal from NnsAccountsFooter and dispatch an event instead.
* Add IcpTransactionModal to AccountsModals.
* Added a test in the Accounts route that the user can send ICP by clicking in the button of the footer.
Not necessary.
> GIX-2180: Move IcpTransactionModal

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
We wish to store accounts in stable memory.
- Implement the `Storable` trait for `Account`s
- A unit test is included.
> feat: Implement Storable for Account

- frontend/src/lib/components/accounts/CurrentBalance.svelte
- frontend/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/neurons/SetNnsDissolveDelay.svelte
- frontend/src/lib/components/sns-neurons/SetSnsDissolveDelay.svelte
- frontend/src/lib/modals/neurons/DisburseNnsNeuronModal.svelte
- frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
- frontend/src/lib/modals/neurons/SplitNnsNeuronModal.svelte
- frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/components/neuron-detail/ConfirmDisburseNeuron.spec.ts
- frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
Migrate from TokenAmount to TokenAmountV2 that supports different decimals.
In this PR, migrate components related to neurons.
* Change TokenAmount to TokenAmountV2 in some places.
* Remove the helper `formattedTransactionFee` which was used by e8s converted to TokenAmount because the helper expected a TokenAmount, to create another TokenAmount, to get the e8s and call `formatToken`. The `token` was not really used anywhere.
Not necessary.
> GIX-2150: Migration to TokenAmountV2

- rs/backend/src/stats.rs
We define `WASM_PAGE_SIZE` but it is already provided by the CDK, so we can deduplicate.
- Use the ic_cdk definition of Wasm page size.
- I have verified that the two constants have the same value.
- Too minor
> refactor: WASM_PAGE_BYTES is provided by the cdk

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
Update `gix-component` to get multiline toast fix.
The fix: https://github.com/dfinity/gix-components/pull/342
By @dskloetd: use the icon test IDs added in https://github.com/dfinity/gix-components/pull/343
- npm run update:gix
None
> update:gix components

- frontend/src/lib/services/ckbtc-minter.services.ts
- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
These statuses are not part of the transactions themselves but come from the ckBTC minter.
Add a service method `loadRetrieveBtcStatuses` which loads BTC retrieval statuses and puts them in the store.
Unit tests were added.
will add when it's used
> Service method to load BTC retrieval statuses

- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/tests/lib/routes/Accounts.spec.ts
Users can use the Send icon from the ICP Tokens table.
* Trigger the "nns-send" event when the tokens table triggers the Send action.
* Add a test to send tokens from a subaccounts of the ICP tokens table.
> GIX-2180: Open IcpTransactionModal from tokens table

- frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
- frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
- frontend/src/tests/page-objects/TransactionCard.page-object.ts
`TransactionCard` renders both an icon image and class.
So far we only tested the class.
Also test that we have the right icon image in `TransactionCard.page-object.ts`.
only tests
not necessary
> Check icons in TransactionCard test

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/transaction.ts
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
These statuses are not part of the transactions themselves but come from the ckBTC minter and then put in a store.
In this PR we change the mapping function to take the status into account when creation the `UiTransaction`.
1. Add a new `isFailed` field to `UiTransaction` to indicate a failed transaction.
2. Add an optional parameter to `mapCkbtcTransaction` to pass the retrieval status if there is one.
3. If there is a status, output a pending or failed transaction if appropriate.
4. Add i18n strings for the transaction headlines.
Tested manually in another branch with more changes.
not yet
> Take retrieval status into account in mapCkbtcTransaction

- frontend/src/lib/services/ckbtc-minter.services.ts
- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
In mainnet, when the user visits twice the Tokens page a toast error might appear because of the background task to call update_balance on the ckBTC minter.
In this PR, do not show the toast error if `uiIndicators` is set to `false`.
* In `updateBalance` ckbtc minter service, show error toast only when `uiIndicators` is `true`.
* Add a test for the new functionality.
* Tested manually that when the api endpoint raises this error the toast is not shown.
Not necessary.
> GIX-2183: Unnecessary error toast

- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
The token's title should be bold per design.
I used h5 because it matches the style and it makes sense from semantics perspective also.
* Wrap the row title with h5 instead of span. Remove default margin on h5.
* No test, only UI changes.
Not necessary.
> GIX-2184: Bold token title

- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
There was a typo in the "Confirmed" retrieval status in `mapCkbtcTransaction`.
The test would have failed before of the error logging, but another test mocked out the error logging and it wasn't reset.
1. `vi.restoreAllMocks` in `beforeEach`.
2. Fix the typo.
3. Fix another test which started logging an error about the memo not being decodable.
updated
not necessary
> Fix mapCkbtcTransaction issue

- frontend/src/lib/derived/accounts-title.derived.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/derived/accounts-title.derived.spec.ts
Change the title of the accounts page to have the name of the token on it.
This is a change requested regarding the new tokens page, but I believe that it's a good change even for the current accounts page. Therefore, I didn't put it behind the feature flag.
In this PR, I introduce the store that I want to use in the layout to set the title. But I don't use it yet.
* New store `accountsTitleStore`.
* New i18n key
* Test new store `accountsTitleStore`.
> GIX-2184: Add accountsTitleStore

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store/schema.rs
- rs/backend/src/accounts_store/schema/accounts_in_unbounded_stable_btree_map.rs
We wish to store accounts in stable memory.
- Define an account store using `StableBTreeMap`s.
-  The standard unit tests for account stores are applied.
- There are unit tests for the constructors.
> feat: unbounded stable btree account storage

- frontend/src/lib/routes/Accounts.svelte
There was a visual bug in the ICP Tokens page because the outer paddings weren't the same as in the Tokens page. This bug was visible in mobile devices.
The problem came from an extra padding added by a `main`'s default padding inside the Accounts route. This `main` will be removed when the flag is removed, but for now, I fixed it by passing a class and setting the padding to 0 when the flag is enabled.
* Add a new class `noPadding` to the `main` in Accounts route and set it when ENABLE_MY_TOKENS is enabled.
Not necessary.
> GIX-2184: Fix padding icp tokens page

- frontend/src/lib/derived/selectable-universes.derived.ts
- frontend/src/lib/derived/selected-universe.derived.ts
- frontend/src/lib/utils/universe.utils.ts
- frontend/src/tests/lib/utils/universes.utils.spec.ts
Improve readability of utils.
In this PR, rename util isNonGovernanceTokenPath to isAllTokensPath
Change triggered by [this discussion](https://github.com/dfinity/nns-dapp/pull/3872#discussion_r1406695028).
* Rename isNonGovernanceTokenPath to isAllTokensPath
* Fix rename
Not necessary.
> Rename: isNonGovernanceTokenPath to isAllTokensPath

- frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
These statuses are not part of the transactions themselves but come from the ckBTC minter and then put in a store.
In this PR we pass the status from `mapCkbtcTransactions` (plural) to `mapCkbtcTransaction` singular.
We don't yet pass the statuses to `mapCkbtcTransactions` (plural).
1. Add a `retrieveBtcStatuses` parameter to `mapCkbtcTransactions`.
2. Convert the array to a map and use the map to pass the correct status to each invocation of `mapCkbtcTransaction`.
1. Extract some test values from test and put them in a larger scope so they can be used.
2. Add a unit test with multiple statuses for different transactions and test that they are applied correctly.
not yet
> GIX-2079: Take retrieval status into account in mapCkbtcTransactions

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/accounts_store/schema/proxy/tests.rs
When accounts are stored in stable memory, it no longer makes sense to save the accounts with all the other data on the heap.
- Serialize accounts in the `pre_upgrade` hook only when accounts are stored as a `BTreeMap` on the heap.
- Existing tests for `Map` to `Map` upgrades still suffice.
> feat: Don't save a map on the heap except when it makes sense

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
Currently, in the post_upgrade hook stats are computed over all accounts.  This will become too expensive once accounts are stored in stable memory.
Instead we would like to preserve these stats on upgrade.
- Save the `accounts_db` stats in the `pre_upgrade()` hook.
- In the `post_upgrade()` hook, compute stats only if they are not already available.
- The downgrade-upgrade test verifies that this is forwards and backwards compatible.
> Save stats

- frontend/src/lib/components/accounts/TransactionCard.svelte
- frontend/src/tests/lib/components/accounts/TransactionCard.spec.ts
- frontend/src/tests/page-objects/TransactionCard.page-object.ts
We want to render failed "Sending BTC" transactions as such.
This PR has just the UI changes to render failed transaction.
Detecting failed transactions is done in other PRs.
1. If `UiTransaction.isFailed` is true render a different icon.
2. Use a CSS class that renders the icon in a red color. This is the same color that reimbursed transactions also use.
3. Add a method to the page object to check for the failed icon and class.
4. Test that `isFailed` results in using the failed icon.
Unit test is included.
not yet.
> Render failed BTC withdrawal transactions

- frontend/src/lib/components/accounts/ReceiveAddressQRCode.svelte
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/page-objects/ReceiveModal.page-object.ts
- frontend/src/tests/page-objects/SnsWallet.page-object.ts
Make the test easier to maintain and less fragile.
1. Add test IDs to existing components.
2. Add necessary page object functionality.
3. Use page objects in `frontend/src/tests/lib/pages/SnsWallet.spec.ts`.
only
not necessary
> Use page objects in SnsWallet.spec.ts

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/accounts_in_unbounded_stable_btree_map.rs
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/accounts_store/schema/proxy/enum_boilerplate.rs
- rs/backend/src/accounts_store/schema/proxy/tests.rs
Stable storage has been defined but needs to be added to the enum of possible databases before the proxy can use it.
- Add stable storage to the `AccountsDb` enum.
- Apply the `ProxyDb` migration test to migrations between stable and maps.
- Simplify the constructors - we have a choice between adding constructors and deleting constructors but having slightly more verbose code.  On balance I would rather have fewer methods that are exercised more often.
- Unit tests for migrations are included.  The `ProxyDb` exists purely to support migrations.
- Covered by an existing changelog entry.
> chore:  Add stable storage to AccountsDb enum

- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/page-objects/jest.page-object.ts
`JestPageObjectElement` is used to reference an element in the DOM in unit tests that use page objects.
The object can reference elements before they actually exist by referencing a parent element and a selector pointing from the parent element to the desired element.
We can then call `isPresent` to check if the element is already there and if so, `this.element` is populated.
However this can lead to confusing situations because if you don't call `isPresent` the element might actually be there but `this.element` is not populated until we check if the element is there.
To avoid this kind of situation we should just always look for the element based on the ancestor and selector rather than mixing sometimes already having the element and sometimes looking for it from the selector.
1. Remove …
> Consistently use selector in JestPageObjectElement

- CHANGELOG-Nns-Dapp-unreleased.md
- dfx.json
Currently I have to manually add this entry every time I want to make calls to the bitcoin canister or to the mock bitcoin canister installed by snsdemo.
Add an entry to `dfx.json` for the bitcoin canister.
Tested manually:
```
$ dfx canister info bitcoin
Controllers: xoner-xjuk3-73eim-3t4hg-wbe5m-s76az-sii6q-7f34l-qclzc-tce2s-eae
Module hash: 0xf0f29e3c5638b368b7c37516c3e0da7975730ce4964e75ea1f159de4b6f7cfbc
$ dfx canister info bitcoin  --network mainnet
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x09f5647a45ff6d5d05b2b0ed48613fb2365b5fe6573ba0e901509c39fb9564ac
```
> Add bitcoin entry to dfx.json

- frontend/src/lib/components/accounts/CkBTCTransactionsList.svelte
- frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
These statuses are not part of the transactions themselves but come from the ckBTC minter and will be put in a store (in a future PR).
In this PR we take the statuses from the store and pass them to `mapCkbtcTransactions` so they can be used to map the transactions.
In `CkBTCTransactionsList.svelte`, pass statuses from `ckbtcRetrieveBtcStatusesStore` to `mapCkbtcTransactions`.
Added a unit test where we put a status in the store and verify that it renders the corresponding transaction according to the status.
will add when we fill the store
> Pass BTC retrieval statuses when mapping ckBTC transactions

- frontend/src/lib/utils/sns.utils.ts
- frontend/src/tests/lib/utils/sns.utils.spec.ts
- frontend/src/tests/mocks/sns-functions.mock.ts
Helpers to get the nsFunction type.
Part of https://github.com/dfinity/nns-dapp/pull/3801
- extend nsFunction mock
- `isNativeNervousSystemFunction`
- `isGenericNervousSystemFunction`
- tests for new utils
Not necessary
> Ns function helpers

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/CkBTCWallet.svelte
- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
These statuses are not part of the transactions themselves but come from the ckBTC minter.
In this PR we call the service method that loads the statuses and puts them in the store.
This is the final PR that ties it all together.
1. Call `loadRetrieveBtcStatuses` when opening the `CkBTCWallet` component.
2. Also call `loadRetrieveBtcStatuses` after making a transaction.
2 unit tests added.
> Load BTC retrieval statuses in ckBTC wallet

- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
When you go to a wallet page without an account identifier in the URL, this is invalid and you are redirected to the accounts page.
We want to instead show the main account for that universe.
Currently there are no tests covering this behavior at all.
So before changing the behavior I'm adding missing test coverage.
This PR adds the missing test coverage for ICRC wallet pages (ckBTC and ckETH).
1. Add tests for navigation on missing, invalid and correct account identifiers.
only tests
not necessary
> GIX-2187: Test incorrect account identifier on ICRC wallet page

- frontend/src/lib/api/proposals.api.ts
- frontend/src/lib/api/sns-dummy.api.ts
- frontend/src/lib/components/accounts/BitcoinEstimatedAmountReceived.svelte
- frontend/src/lib/components/accounts/HardwareWalletNeurons.svelte
- frontend/src/lib/components/launchpad/ProjectCard.svelte
- frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
- frontend/src/lib/components/neuron-detail/ConfirmSpawnHW.svelte
- frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte
- frontend/src/lib/components/project-detail/ProjectTimelineUserCommitment.svelte
- frontend/src/lib/components/proposals/Countdown.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalSystemInfoSection.svelte
- frontend/src/lib/constants/api.constants.ts
- frontend/src/lib/constants/sns-neurons.constants.ts
- frontend/src/lib/derived/proposals.derived.ts
- frontend/src/lib/modals/neurons/SplitNnsNeuronModal.svelte
- frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
- frontend/src/lib/services/$public/sns.services.ts
- frontend/src/lib/services/sns-neurons-check-balances.services.ts
- frontend/src/lib/utils/anonymize.utils.ts
- frontend/src/lib/utils/ckbtc.utils.ts
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/lib/utils/sns.utils.ts
- frontend/src/lib/utils/token.utils.ts
- frontend/src/lib/workers/auth.worker.ts
- frontend/static/assets/libs/dummy-proposals.utils.js
`bigint`s can be written as `123n` but in many places we write `BigInt(123)`.
The former is more concise and also more accurate if the number actually requires a `bigint` for full accuracy.
1. Replace `BigInt(???)` with `???n`.
2. Add underscore separators for numbers with more than 3 digits if they weren't there already.
This PR only does non-test files. There are a lot more cases in tests and it would make this PR too big.
Still pass
not necessary
> Use concise bigint notation

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
When you go to a wallet page without an account identifier in the URL, this is invalid and you are redirected to the accounts page.
But not for SNS wallets. There you just get an infinite loading spinner.
For consistency, SNS wallets should also redirect to the accounts page.
In `SnsWallet.svelte`, when the account identifier does not match any of the accounts, go back to the accounts page of the same universe.
This is similar to what [IcrcWalletPage.svelte](https://github.com/dfinity/nns-dapp/blob/fd4ce83c1fc11801b43041359bdebfb58b5d3b6d/frontend/src/lib/components/accounts/IcrcWalletPage.svelte#L74) does (although there it doesn't keep the universe which is a bug that should be fixed in another PR).
Added unit tests for missing, invalid and valid account identifier.
> GIX-2187: Redirect from SNS wallet to accounts for wrong account identifier

- frontend/package-lock.json
- frontend/src/lib/components/common/JsonPreview.svelte
- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
Replace custom classes for island card w/ `content-cell-island__card` class.
- `npm update:gix`
- replace card styles with `content-cell-island__card`
Not needed
> Replace markdown container styles

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/pages/WalletTest.svelte
In `IcrcWalletPage` (and other wallets) when there is no or an incorrect account identifier, we navigate back to the accounts page.
In `SnsWallet` it navigates to the accounts page of the same universe but in `IcrcWalletPage` it reverts to the ICP universe.
Instead it should stay with the universe of the wallet we were on.
In an earlier version of this PR, the test would end up in an infinite loop because navigating to a different URL would trigger the `selectedIcrcTokenUniverseIdStore` which would result in `IcrcWalletPage` trying again to load the data and again trying to go back to the accounts page etc.
In reality this would not happen, because as soon as the app navigates away from the wallet page, the component would be unmounted and it wouldn't try to load data anymore. To make the …
> Keep universe in goBack in IcrcWalletPage

- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
Making `NnsWallet.spec.ts` more reliable and easier to maintain.
1. Use page objects.
2. Extend the page object with necessary methods.
3. Expect explicit values defined in the test instead of values on a mock defined somewhere else.
4. Do not rely on being able to make expectations before the component goes into loaded state but instead explicitly block API calls to simulate loading state.
5. Remove all usages of `waitFor`.
Still pass
not necessary
> Use page objects in NnsWallet.spec.ts

- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
When you go to a wallet page without an account identifier in the URL, this is invalid and you are redirected to the accounts page.
We want to instead show the main account for that universe.
Currently there are no tests covering this behavior for the NNS wallet.
So before changing the behavior in all wallets I'm adding missing test coverage.
This PR adds the missing test coverage for NNS wallet.
1. Add tests for navigation on missing, invalid and correct account identifiers.
2. Fix a typo in a related test description that has been copied around.
pass
not necessary
> GIX-2187: Test incorrect account identifier for NNS wallet

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/lib/utils/accounts.utils.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/lib/utils/accounts.utils.spec.ts
People want to be able to link from external websites to the ckBTC wallet page, which has information about converting BTC to ckBTC.
This should work whether the user is signed-in or not.
When linking from an external website, the account identifier of the user is not known so it can't be included in the URL.
To make this work we want the wallet deep-link URL work even when know account identifier is specified.
In that case we default to the main account for the given wallet.
For consistency we do the same SNS and NSS wallets.
1. Default to the main account when no account identifier is specified in the `IcrcWallet` component.
2. Default to the main account when no account identifier is specified in the `SnsWallet` component. 
3. Default to the main account when no account identifier is …
> GIX-2187: Default to main account when accountIdentifier is missing

- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/tests/lib/components/accounts/WalletPageHeading.spec.ts
The `WalletPageHeading` component has logic to show the account name and balance in the layout title when they scroll out of the viewport (i.e. no longer "intersect" with the viewport). The logic is such that if there is no balance, it always puts the balance in the layout title, even if it's not out of the viewport.
This seems backwards since then it renders as "0 undefined".
So I'm guessing it was intended the other way around, where if there is no balance, it is never (rather than always) rendered in the title.
Note that currently we never pass an `undefined` balance to the `WalletPageHeading` component, so I'm not even sure why this logic exists, but we plan to make the wallet page accessible when not signed in so then we do need `WalletPageHeading` to work with undefined balance.
1. …
> GIX-2187: Fix wallet title when balance is undefined

- frontend/src/lib/components/accounts/CkBTCInfoCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/CkBTCInfoCard.spec.ts
- frontend/src/tests/page-objects/CkBTCInfoCard.page-object.ts
We want to allow deep linking into the ckBTC wallet page so people can learn about BTC -> ckBTC conversion.
This should work even when users are not signed in.
The components on the wallet page currently assume that the user is always signed in or the wallet page wouldn't be shown. So this needs to change.
In this PR we support not being signed in for the `CkBTCInfoCard` component by allowing to not pass the `account` prop.
When signed in:
When not signed in:
A placeholder for the address QR code will be added later.
This change is not yet user visible because it's still not possible to see the wallet page without being signed in.
1. Change the types of `account` and `identifier` to include `undefined.
2. Load the BTC address whenever the identifier is defined, instead of only on mount. …
> GIX-2187: Allow CkBTCInfoCard without account

- frontend/src/lib/components/accounts/WalletPageHeader.svelte
- frontend/src/tests/lib/components/accounts/WalletPageHeader.spec.ts
- frontend/src/tests/page-objects/WalletPageHeader.page-object.ts
We want to make deep links to wallet pages, render a logged-out version of the wallet page.
When the user is not logged in, there is no wallet address known.
So we need to be able to render the `WalletPageHeader` component without wallet address.
This PR does not change anything user visible because it's not yet possible to see the wallet page while not logged in.
Allow not passing a wallet address to the `WalletPageHeader` component. Then don't render the `IdentifierHash` component.
1. Merge the existing tests for the wallet address and universe name.
2. Add an extra test where the wallet address is absent.
not yet
> Allow absent wallet address in WalletPageHeader

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/proposal-detail/MyVotes.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/ExpandableProposalNeurons.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VoteResultIcon.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotedNeuronList.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingCard.spec.ts
- frontend/src/tests/page-objects/VotingCard.page-object.ts
In order to improve voted state readability, the voting state is displayed in the "voted neurons" header. When not all neurons voted the same way, no state is displayd.
- Display `thumb-up` icon in gree when all voted neuron voted `Yes`
- Display `thumb-down` icon in red when all voted neuron voted `No`
- Removed bottom line from the last element (designer's request)
- "Voted neurons headline state"
| Yes only | No only | Mixed |
|--------|--------|--------|
| <img width="373" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/2e94536b-d5c2-406b-9cb7-c124c90b6431"> | <img width="373" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/75ea12d6-93b2-4e8e-a030-3f07f8c13350"> | <img width="373" alt="image" …
> Voted neurons update

- scripts/nns-dapp/release
`scripts/nns-dapp/release` has a flag to write the created proposal ID to a file.
This functionality depended on `ic-admin` writing only a single line to stdout.
But newer versions of `ic-admin` write more to stdout, breaking the proposal ID parsing.
`grep` for the specific line containing the proposal ID and ignore everything else.
Tested manually on local with
```
$ PATH=$PATH:../../snsdemo/tree2/bin scripts/nns-dapp/release --save-proposal-id-to-file tmp-id --network local --neuron "$(cat ~/.config/dfx/identity/snsdemo8/neurons/local)"
$ cat tmp-id
```
> Fix parsing the proposal ID in scripts/nns-dapp/release

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/IcrcBalancesObserver.svelte
- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/components/accounts/SnsBalancesObserver.svelte
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/tests/lib/components/accounts/IcrcBalancesObserver.spec.ts
- frontend/src/tests/lib/components/accounts/SnsBalancesObserver.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
We want to be able to render wallet pages to signed-out users.
When the user is not signed in, there is no balance to observer so the observer should be separated from the content that can be displayed to signed-out users. So the content should not be passed as a slot of the observer, but should be a sibling of the observer.
After I made this change, I tested if the observer (still) worked, and I realized that the observer was actually already broken before.
It was broken by https://github.com/dfinity/nns-dapp/pull/3995 which changed `Account.balanceE8s` to `Account.balanceUlps` while the observers kept setting the `balanceE8s` field. This was not caught by the test because the test also checked that the `balanceE8s` field was set.
So in addition to fixing the usage of the field, I wanted …
> Fix balances observers

- frontend/package-lock.json
Bump ic-js next that introduces the patch for iOS 15 ([PR](https://github.com/dfinity/ic-js/pull/513)) which we temporarely solved by rolling back Sveltekit from v2 to v1 ([PR](#4149)).
> Bump next for iOS 15

- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/tests/lib/components/accounts/WalletPageHeading.spec.ts
- frontend/src/tests/page-objects/WalletPageHeading.page-object.ts
We want to be able to render a wallet page (with placeholders) to a user who's not signed in.
Currently if you don't pass a balance to `WalletPageHeading` it renders a skeleton.
But the code currently never renders a `WalletPageHeading` when no balance is available.
When we show a wallet page while the user is not signed in, we want to render `-/-` as a wallet place holder.
Remove the code to render a skeleton balance and replace it with rendering `-/-` when no balance is passed to `WalletPageHeading`.
This is not yet user visible because it's not yet possible to visit a wallet page without being signed in.
Unit test is updated.
not yet
> Balance placeholder instead of skeleton in wallet page

- frontend/src/lib/routes/Accounts.svelte
- frontend/src/tests/lib/routes/Accounts.spec.ts
When the new tokens page is enabled, the `/accounts` page is only accessible for NNS universe.
* Redirect to `/tokens` from `/accounts` if the universe is not NNS.
* Add tests for the redirection logic.
Not yet necesary.
> GIX-1984: Redirect from /accounts to /tokens accordingly

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/ReceiveButton.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/SendButton.svelte
- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
User couldn't access the buttons in the footer with the keyboard.
Fix, use tabindex="0" instead of incrementing them.
There is an issue that the buttons are not highlighted nicely when focused. I raised the issue with @meodai who is now working on colors.
* Set tabindex of the TokensTableRow to `"0"`.
* Remove the prop index from the TokensTableRow.
* Typo in the class `"icon"` of the button. It should have been `"icon-only"`. This way they come with the proper focus (and buggy) style.
* Set the last row's tabindex of the NNS Tokens Table to `"0"` as well and to `"-1"` for the button to avoid going there and moving directly to the footer.
* This logic was not tested and now it's a fixed attribute. Therefore, no extra tests are needed.
> GIX-2176: Fix tabindex Tokens footer buttons

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/nns-dapp/migration-test.canister
- scripts/nns-dapp/migration-test.getters
- scripts/nns-dapp/migration-test.linters
The migration to stable memory needs a more tests than our downgrade-upgrade tests provide.  In previous PR,  a copy of the downgrade-upgrade test was made and refactored to allow it to test any migration rather than just to prod and back.  This test was used locally during stable memory development but not (yet) exercised in CI.  Let's test the simplest case first - just upgrade to self - to gain confidence that the test works as expected.
Note: This does NOT yet replace the downgrade-upgrade test.  Given  that there have been many changes to the test it would be nice to know that it works reliably in the simplest setting possible before using it for more complicated cases.
- Exercise the new migration test, just for a simple upgrade-to-self with classic stable-memory-on-heap storage.
- …
> test: Use the new migration test in CI

- frontend/src/lib/components/proposal-detail/VotesResults.svelte
Replace the missing after the redesign `--purple-600` colour w/ the closest `--orchid`. No additional missing CSS variables were found.
- css
No code changes
Not necessary
| <img width="387" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/0671fd03-5819-4e6e-bbe8-6791f0acdb37"> | <img width="388" alt="Screenshot 2024-01-11 at 10 50 55" src="https://github.com/dfinity/nns-dapp/assets/98811342/3ec97c60-a1fa-4899-a9d4-d3282ac5bff3"> | 
| | <img width="390" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/8754a495-f061-44d8-ac2a-76bfd100e2bc"> |
> style: replace missing purple with orchid colour

- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerActionsEntry.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotesResults.spec.ts
- frontend/src/tests/lib/stores/writable-stored.spec.ts
Remove redundant imports in tests.
- remove `beforeEach`
- remove `describe`
pass
Not necessary
> chore: remove redundant imports

- scripts/dfx-snapshot-start
We want to serve dfx snapshots from DevEnv for manual testing.
Since dfx 0.15.3 this requires passing a `--domain` flag.
Forward the `--domain` flag from `dfx-snapshot-start` to `dfx`.
Tested manually on my DevEnv.
> Forward --domain flag from dfx-snapshot-start to dfx

- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
User should be redirected to tokens page if enabled from SnsWallet.
* SnsWallet redirect to Tokens path if flag is enabled.
* Test that redirection when identifier is invalid is to the Tokens if flag is enabled.
Not necessary.
> GIX-1984: Redirect to /tokens from SnsWallet

- frontend/src/lib/api/canisters.api.ts
- frontend/src/lib/api/icp-ledger.api.ts
- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/services/icp-accounts.services.ts
- frontend/src/lib/services/sns-sale.services.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
- frontend/src/tests/lib/api/icp-ledger.api.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
Stop using TokenAmount.
In this PR, remove TokenAmount from ledger api `sendICP` and use `bigint` instead.
* Change parameter's type `amount` in `sendICP` to `bigint`.
* Change usage of `sendICP` to pass a `bigint`.
* Change patameter's type `amount` in canister api functions.
* Change canister services to stop using `TokenAmount`.
* Fix tests after changes in ledger and canister api spec files.
Not necessary.
> GIX-2150: Remove usage of TokenAmount in api layer

- frontend/src/lib/components/accounts/CkBTCInfoCard.svelte
- frontend/src/tests/lib/components/accounts/CkBTCInfoCard.spec.ts
- frontend/src/tests/page-objects/CkBTCInfoCard.page-object.ts
We want to be able to render the wallet pages when the user is not signed in.
On the ckBTC wallet page we show a QR code with the BTC deposit address.
When the user is not signed in, there is no deposit address so we want to show a placeholder icon instead.
1. Remove the white background for the QR code if the user is not signed in.
2. Show the QR code icon instead.
Existing tests updated.
not user visible yet
> Use QR code placeholder icon on ckBTC wallet page

- frontend/src/lib/components/accounts/TransactionCard.svelte
- frontend/src/lib/components/accounts/TransactionIcon.svelte
- frontend/src/lib/types/transaction.ts
- frontend/src/tests/lib/components/accounts/TransactionIcon.spec.ts
- frontend/src/tests/page-objects/TransactionCard.page-object.ts
- frontend/src/tests/page-objects/TransactionIcon.page-object.ts
Design asked to put a transaction icon as a placeholder when there are no transactions, [here](https://www.figma.com/file/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?type=design&node-id=1319-1085&mode=design&t=c9WzuZezrkC9IYMo-4).
Also, in the future we might use them in transaction detail modals.
This PR just extracts the icon component to make it available in future PRs.
1. Create `TransactionIcon.svelte` to render a transaction icon.
2. Use it in `TransactionCard.svelte` instead of rendering inline.
3. Add a unit test.
4. Add a page object.
5. Update existing page object.
Unit test added.
Looks good on manual inspection:
not necessary
> Extract TransactionIcon from TransactionCard component

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/IcrcTransactionsList.svelte
- frontend/src/lib/components/accounts/NoTransactions.svelte
- frontend/src/lib/components/accounts/TransactionList.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/accounts/IcrcTransactionsList.spec.ts
- frontend/src/tests/lib/components/accounts/TransactionList.spec.ts
- frontend/src/tests/page-objects/IcrcTransactionsList.page-object.ts
- frontend/src/tests/page-objects/TransactionList.page-object.ts
[The design](https://www.figma.com/file/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?type=design&node-id=1319-1085&mode=design&t=BiIOfY7BQjiYMj8P-4) for the logged-out wallet page has a new placeholder for when there are no transactions.
We should use this also when the user is logged in but there are no transactions.
This PR introduces a simple component to use as the placeholder when there are no transactions and uses it just for the logged-in case.
1. Add `NoTransactions` component.
2. Use it instead of just text when there are no transactions.
Unit tests and page objects were updated.
> Transaction list placeholder

- frontend/src/lib/components/tokens/MainWrapper.svelte
The `main` element of the My Tokens table is a scrolling container, but it exists in another scroll container.
This results in a strange cut-off at the top and bottom and strange placement of the scroll bar.
See https://github.com/dfinity/nns-dapp/pull/4182 for details.
1. Remove `height` and `overflow-y` from the `main` element.
2. Remove custom padding that was necessary because of the double scroll container.
Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
not necessary
> Remove double scroll container from My Tokens table

- frontend/src/lib/components/ic/GetTokens.svelte
- frontend/src/lib/components/ic/GetTokensModal.svelte
With the new tokens view, we don't have a universe anymore in the tokens view. Therefore, the button "Get Xxxx" is always "Get ICP". I want to add a dropdown of all the available tokens within the modal.
Before doing that and to avoid checking the balances of all the test accounts always, I refactored the Modal into another component so that then, the balances of the tokens is checked only when the modal is open.
In this PR, I'm only moving the modal to another file. The main changes will come in a subsequent PRs.
* Create a new GetTokensModal and use it in GetTokens instead of rendering the Modal directly.
This is a dev feature only. There are no tests.
Not necessary.
> Refactor: GetTokensModal

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/pages/IcrcWallet.svelte
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/page-objects/IcrcWallet.page-object.ts
We want to be able to show wallet pages when the user is not logged in.
This PR makes it possible to render the `IcrcWallet.svelte` page when the user is not logged in.
This is not a user visible change because `wallet/+page.svelte` still doesn't render any wallet when the user is not logged in.
1. Don't load data until the user is logged in.
2. Don't render `IcrcBalancesObserver` if the user is not logged in.
3. Treat `selectedAccountStore.account` as nullable because we want to render most of the page when there is no account.
4. Use `SignInGuard` to render a sign in button if the user is not logged in.
5. Render the no-transactions placeholder instead of the `IcrcWalletTransactionsList` component if there is no account.
not yet
> GIX-2187: Make ICRC wallet renderable when not signed in.

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/CkBTCInfoCard.svelte
When using the `Spinner` component, it renders in the current color.
By default, this is dark in the light theme and light in the dark theme.
But the QR code for the BTC deposit address is always rendered on a white background, so it should always have a dark spinner.
Set `color` to `black` in the `qr-code` element.
Tested manually:
> Fix BTC address QR code spinner in dark theme

- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/page-objects/SnsWallet.page-object.ts
We want to be able to show wallet pages when the user is not logged in.
This PR makes it possible to render the `SnsWallet.svelte` page when the user is not logged in.
This is not a user visible change because `wallet/+page.svelte` still doesn't render any wallet when the user is not logged in.
1. Don't load data until the user is logged in.
2. Don't render `SnsBalancesObserver` if the user is not logged in.
3. Treat `selectedAccountStore.account` as nullable because we want to render most of the page when there is no account.
4. Use SignInGuard to render a sign in button if the user is not logged in.
5. Render the no-transactions placeholder instead of the SnsWalletTransactionsList component if there is no account.
6. Hide Send/Receive buttons if there is no account.
Unit tests are …
> GIX-2187: Make SNS wallet renderable when not signed in.

- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
We want to be able to show wallet pages when the user is not logged in.
This PR makes it possible to render the `NnsWallet.svelte` page when the user is not logged in.
This is not a user visible change because `wallet/+page.svelte` still doesn't render any wallet when the user is not logged in.
1. Don't `pollAccounts` until the user is logged in.
2. Treat `selectedAccountStore.account` as nullable because we want to render most of the page when there is no account.
3. Use SignInGuard to render a sign in button if the user is not logged in.
4. Render the no-transactions placeholder instead of the SnsWalletTransactionsList component if there is no account.
5. Hide Send/Receive buttons if there is no account.
Drive-by: Use the real …
> GIX-2187: Make NNS wallet renderable when not signed in.

- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/modals/sns/proposals/SnsFilterTypesModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts
- frontend/src/tests/lib/modals/sns/SnsFilterTypesModal.spec.ts
Display the `Types` filter modal behind the `ENABLE_SNS_TYPES_FILTER` flag till it's ready. The final pull request will incorporate the selected options into the getProposal request.
- `Types` filter button (behind the feature flag)
- `SnsFilterTypesModal`
- button should be visible and clickable
- modal should work
Not yet.
| Button | Modal |
| <img width="560" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/a94dddbe-c979-44ad-a7b6-253ecdef9064"> | <img width="519" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/a1f80bbd-e5ea-4112-95d0-fb14b4a20d80"> |
> feat: TypesFilterModal

- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
There was an issue with the e2e tests clicking the Receive button in the tokens table. The reason was that the selector was getting the mobile button is hidden in desktop.
In this PR, I remove the duplicated button while maintaining the flexibility of adding new columns.
* Set the grid style using inline style in the TokensTableRow.svelte. Because inline style is more than a media query, I needed to use `!important`.
No new tests, this is a refactor of the same current functionality.
Not necessary.
> Feat: Remove duplicated actions cell

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/sns-proposals/SnsVotingCard.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
Fix missing NF-neurons in the SNS proposal details voting block.
- switch to use all user neurons `snsSortedNeuronStore`.
- `SnsVotingCard` should display NF neurons as well
> fix: use all neurons in voting card

- dfx.json
> Update didc release to 2024-01-03

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-01-09_23-01+new-p2p

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/dfx-snapshot-start
`dfx` has a flag `--domain` which you need to specify to make the replica accessible remotely at that domain.
But when you do, this overrides the default value, which is `localhost` so then the replica is no longer accessible from the machine itself at `localhost`.
To make the replica accessible on both domains, we need to pass the `--domain` flag twice.
Pass `--domain localhost` to replica when specifying an additional domain to `dfx-snapshot-start`.
Tested manually on my DevEnv.
> Keep local replica accessible locally

- frontend/src/lib/components/accounts/ConvertBtcInProgress.svelte
- frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
- frontend/src/lib/services/ckbtc-convert.services.ts
- frontend/src/lib/types/ckbtc-convert.ts
- frontend/src/tests/lib/components/accounts/ConvertBtcInProgress.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
- frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
There are currently 3 BTC withdrawal flows:
1. Transfer ckBTC to minter withdrawal account, then ask minter to convert (only with ENABLED_CKBTC_ICRC2 disabled)
2. Have existing ckBTC in withdrawal account and ask the minter to convert (regardless of ENABLED_CKBTC_ICRC2)
3. Approve a transfer, then ask the minter to convert directly from your account (only with ENABLED_CKBTC_ICRC2 enabled)
This PR removes the first and keeps the other 2.
The second flow will be remove soon in another PR.
1. Remove the possibility of rendering the "transfer to withdrawal account" step from `ConvertBtcInProgress.svelte
`.
2. Remove the check on `ENABLE_CKBTC_ICRC2` in `CkBTCTransactionModal.svelte` and determine the flow based only on whether we are trying to use an already funded withdrawal address or not. …
> GIX-2172: Remove old BTC withdrawal flow

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/assets/question-mark.svg
- frontend/src/lib/derived/icrc-universes.derived.ts
- frontend/src/lib/stores/icrc-canisters.store.ts
- frontend/src/tests/lib/derived/icrc-universes.derived.spec.ts
Sometimes people accidentally send tokens to their NNS dapp address while those tokens are not supported by NNS dapp.
It would be nice if there was a way to recover those tokens.
The experience could definitely be improved but I don't want to spend more time on this now, so please review based on whether this is an improvement or not.
1. Provide a hard coded logo for unknown tokens.
2. Add a method to the `window` object to add a ledger and index canister to the store.
1. Adjusted an existing unit test for an unknown token.
2. Tested manually adding an unknown ledger.
Currently it happens to work with and without index canister but there are no guarantees:
```
__experimentalAddIcrc1Token('m7h5t-euaaa-aaaaa-qabia-cai');
__experimentalAddIcrc1Token('m7h5t-euaaa-aaaaa-qabia-cai', …
```
> Console feature to temporarily add ICRC-1 token

- CHANGELOG-Nns-Dapp-unreleased.md
- config.test
https://github.com/dfinity/nns-dapp/pull/4027 adds an additional golden config file to test against.
But when the file needs to be updated, the script suggests using `--update` but this doesn't work.
Passing `--network local` in addition to `--update` does change the golden file but puts it in a broken state, depending on files outside the repo.
We need to be able to make changes without having to edit these golden files manually.
Comment out the broken test.
This test was blocking https://github.com/dfinity/nns-dapp/pull/4224 and commenting out the test unblocked CI for that PR.
> Comment out broken local config test

- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
Set `ENABLE_MY_TOKENS` in vitest.setup.
The following were failing because the test expected `ENABLE_MY_TOKENS` to be `false`.
* Move test `"should point Tokens and Neurons to NNS from the project page"` from MenuItems.spec within a describe with `ENABLE_MY_TOKENS` as `false`.
* Set `ENABLE_MY_TOKENS` to `false` in the main `beforeEach` of the Acconts.spec.ts file.
Not necessary.
> GIX-2080: Fix failing tests with default `ENABLE_MY_TOKENS` true

- frontend/src/lib/utils/navigation.utils.ts
- frontend/src/tests/lib/utils/navigation.utils.spec.ts
When user clicks in a row in the Tokens table and is not logged it it should be redirected to the according page. Either wallet page or ICP accounts.
In this PR, allow `buildWalletUrl` without an `account` parameter.
* `buildWalletUrl` can be called without `account`.
* Add a test when `buildWalletUrl` is called without `account`.
Not necessary.
> GIX-2063: Allow buildWalletUrl without account

- frontend/src/tests/workflows/CreateSubaccount.spec.ts
Set `ENABLE_MY_TOKENS` true in vitest.setup.
In this PR, add the CreateSubaccount.spec test for the tokens page and set the ENABLE_MY_TOKENS before testing.
* New test in CreateSubaccount.spec to test the same but with the new UI and set the flag before the tests.
Not necessary.
> GIX-2080: CreateSubaccount workflow test with tokens page

- frontend/src/lib/components/neurons/NnsStakeNeuron.svelte
- frontend/src/lib/services/sns-accounts.services.ts
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/services/sns-sale.services.ts
- frontend/src/tests/lib/components/accounts/SnsAccountsFooter.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/lib/services/sns-accounts.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/services/sns-sale.services.spec.ts
Remove the transactionFeeStore.
In this PR, migrate some components and services.
* Use derived `mainTransactionFeeE8sStore` instead of `transactionsFeesStore` in NnsStakeNeuron and sns-sale services.
* Get the SNS fee from `tokensStore` instead of `transactionsFeesStore` in sns services.
* Change the test setup of related tests to use tokensStore.
Not necessary.
> Refactor: Migration from transactionsFeesStore to tokensStore

- frontend/src/lib/derived/icp-tokens-list-visitors.derived.ts
- frontend/src/tests/lib/derived/icp-tokens-list-visitors.derived.spec.ts
- frontend/src/tests/routes/app/accounts/page.spec.ts
Non-logged in user can navigate across tokens, accounts and wallet.
In this PR, add a link to the ICP wallet from the ICP to the IC row accounts page when the user is not logged in.
* Add `rowHref` to `icpTokensListVisitorsStore`.
* Add the new `rowHref` to the expected result in the `icpTokensListVisitorsStore` test file.
* Add a test to the accounts page spec file that the href is rendered when the user is not logged in.
Not necessary.
> GIX-2063: Add link in ICP tokens table not logged in

- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/page-objects/AddUserToHotkeys.page-object.ts
- frontend/src/tests/page-objects/NnsStakeNeuron.page-object.ts
- frontend/src/tests/page-objects/NnsStakeNeuronModal.page-object.ts
- frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
Make the tests easier to read and maintain.
1. Move some test setup to the top-level `beforeEach` because other tests also depend on it and would fail when run in isolation.
2. Use page objects for the tests.
3. Add some additional expectations to make sure we are testing what we think we're testing.
only
not necessary
> Use page objects in NnsStakeNeuronModal.spec.ts

- frontend/src/tests/lib/components/sns-neurons/SnsNeuronsFooter.spec.ts
1. Remove existing setup from `beforeEach` because it wasn't used.
2. Replace setup inside the test by instead of mocking the store, filling the real stores, and put this setup in `beforeEach`.
3. Use page object.
only tests
not necessary
> Clean up SnsNeuronsFooter.spec.ts

- frontend/src/lib/pages/SnsProposals.svelte
- frontend/src/lib/services/$public/sns-proposals.services.ts
- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/lib/utils/sns.utils.ts
- frontend/src/tests/lib/services/_public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
- frontend/src/tests/lib/utils/sns.utils.spec.ts
Add `excludeType` parameter support. It will be used to filter sns proposals by types.
- pass down `nsFunctions` to the `loadSnsProposals` service (needs to calculate `excludeType` param).
- added `toExcludeTypeParameter` function.
- calculate `excludeType` and add it to the request
- `toExcludeTypeParameter`
- add nsFunctions argument to sns proposal service specs
Not yet
> Add exclude type param

- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/page-objects/GetTokens.page-object.ts
- frontend/src/tests/page-objects/SelectUniverseList.page-object.ts
- frontend/src/tests/page-objects/TokensTable.page-object.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
Enable tokens feature flat for mainnet.
In this PR, set flag to true for sns-governance test.
* Set tokens flag to true in sns-governance.spec and change the flow to adapt to the tokens page.
* Add choosing the dropdown option in `getSnsTokens`. This worked before because it was in the same universe as the SNS and was initially selected.
* Add helper method `clickOnSnsUniverse` to SelectUniverseList.
* Add method to get SNS rows in TokensTable PO and helper constructor in TokensTableRow PO.
Not necessary.
> GIX-2080: Enable tokens flag for sns-governance e2e test

- frontend/src/tests/e2e/merge-neurons.spec.ts
Enable tokens flag in mainnet.
In this PR, set the flag to true for merge-neurons e2e test.
* Set flag to true in merge-neurons test and use the home instead of `/accounts`.
Not necessary.
> GIX-2080: Enable tokens page flag for merge-neurons e2e test

- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/page-objects/App.page-object.ts
Enable tokens page flag for mainnet.
In this PR, enable the flag for disburse e2e test.
* Change disburse e2e test to tokens page.
Not necessary.
> GIX-2080: Enable tokens page for disburse e2e test

- frontend/src/tests/e2e/multi-tab-auth.spec.ts
Enable tokens page in mainnet.
In this PR, enable the flag for the multi-tag e2e test.
* Enable tokens page for multi-tab e2e and fix new expectations.
Not necessary.
> GIX-2080: Enable tokens page in multi-tab e2e test

- frontend/src/tests/e2e/proposals.spec.ts
Enable tokens page in mainnet.
In this PR, enable tokens flag in proposals e2e test.
* Enable tokens flag in proposals e2e test.
Not necessary.
> GIX-2080: Enable tokes flag proposals e2e test

- frontend/src/tests/e2e/sns-participation.spec.ts
Enable tokens page in mainnet.
In this PR, enable tokens page in sns-participation e2e test.
* Enable tokens flag in sns-participation e2e test.
Not necessary.
> GIX-2080: Enable tokens page in sns-participation e2e test

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/environment.constants.ts
Improve installing NNS Dapp on different environments.
In this PR, add some missing feature flags to the default value of the feature flags.
* Change default value of `FEATURE_FLAG_ENVIRONMENT`.
Not test for this default value.
> Chore: Add default feature flags

- CHANGELOG-Nns-Dapp.md
- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsFollowee.svelte
- frontend/src/lib/components/ui/Hash.svelte
- frontend/src/tests/lib/components/neuron-detail/NeuronFollowingCard/Followee.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsFollowee.spec.ts
- frontend/src/tests/page-objects/Followee.page-object.ts
- frontend/src/tests/page-objects/Hash.page-object.ts
- frontend/src/tests/page-objects/SnsFollowee.page-object.ts
Currently the only way to copy the SNS neuron ID of a followee is to look in the DOM inspector.
1. Add copy button to SNS neuron ID for followed SNS neurons.
2. Add a copy button to the ID for followed NNS neurons for completeness.
> Add copy button for followee neuron ID

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/AccountBadge.svelte
- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/AccountBadge.spec.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
Requested in point 3 of https://www.notion.so/dfinityorg/Wording-Changes-4411020138ce4d09b6605ad1fdbb9555
Remove the "Linked Account" badge on subaccounts both in the old accounts page and the new tokens table.
Unit tests modified.
Added an entry which will also cover some future changes.
> Remove 'Linked Account' badge

- frontend/src/lib/derived/main-transaction-fee.derived.ts
- frontend/src/lib/stores/tokens.store.ts
- frontend/src/lib/stores/transaction-fees.store.ts
- frontend/src/tests/lib/derived/transaction-fee.derived.spec.ts
- frontend/src/tests/lib/stores/transaction-fees.store.spec.ts
Remove deprecated `transactionsFeesStore`.
In this PR, remove the usage in the derived stores that returns the fee of the ICP.
* `mainTransactionFeeStore` uses `tokensStore`.
* `mainTransactionFeeE8sStore` uses `tokensStore`.
* `mainTransactionFeeStoreAsToken` uses `tokensStore`.
* Adapt `mainTransactionFeeStoreAsToken` spec file to use tokensStore.
* Adapt `mainTransactionFeeStore` test case to use tokensStore.
Not necessary.
> GIX-2060: Remove deprecated transactionsFeeStore

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/Launchpad.svelte
Fix double gaps on launchpad page (screen 1)
- Replace `grid-areas` with `order` to avoid extra gaps.
Only style changes
| <img width="416" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/8d72c2d0-0e6e-4cba-b7bd-1b16d7ba8ed6"> | <img width="416" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/e4d5c79f-1cc4-4532-a4aa-df466476245b"> |
> style: replace `grid-areas` with `order` to avoid extra gaps

- frontend/package-lock.json
- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/api/sns.api.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsActiveDisbursementEntry.spec.ts
- frontend/src/tests/lib/modals/sns/SnsActiveDisbursementsModal.spec.ts
- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
- frontend/src/tests/lib/stores/sns-finalization-status.store.spec.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/lib/utils/sns.utils.spec.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/mocks/sns-response.mock.ts
Upgrade next dependencies after updating Candid files for sns-js.
* Script `npm run upgrade:next` updated the file package.lock.json
* Add `ideal_matched_participation_function` to the Aggregator type because it's already supported in the aggregator.
* Add `ideal_matched_participation_function` and `decentralization_swap_termination_timestamp_seconds` to the aggregator converters.
* Add new optional fields to quite a few mocks in our tests. I will use this to create another PR to put all those mocks in a separate file to have the changes centralized next time.
Not necessary. No new functionality is added.
> Chore: Upgrade next dependencies

- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-snsdemo.yml
- CHANGELOG-Nns-Dapp-unreleased.md
We have some nice workflows that create PRs to update dependencies. They are accumulating because there are no reviewers.
In this PR, add reviewers for the udpate workflows.
Example PR: https://github.com/dfinity/nns-dapp/pull/4284
* Add `reviewers: mstrasinskis, dskloetd, lmuntaner` to the `update-*.yml` CI workflows.
Not necessary.
> Chore: Add reviewers to update PRs by CI

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/ui/DayInput.svelte
- frontend/src/lib/components/ui/InputWithError.svelte
- frontend/src/tests/lib/components/neurons/SetDissolveDelay.spec.ts
- frontend/src/tests/lib/components/ui/InputWithError.spec.ts
- frontend/src/tests/page-objects/InputWithError.page-object.ts
- frontend/src/tests/page-objects/SetDissolveDelay.page-object.ts
Requested in point 14 of https://www.notion.so/dfinityorg/Wording-Changes-4411020138ce4d09b6605ad1fdbb9555
When the dissolve delay is not enough to have voting power, we should an error message but we don't disable the "Set Delay" button.
Additionally to not disabling the button we should also not put a red outline on the input field.
1. Add an extra prop `warningMessage` on `InputWithError`. Setting the warning message show the message similar to an error message but it does not cause the red outline.
2. Use the `warningMessage` prop for the warning about not having voting power.
1. Use page objects for existing tests in `InputWithError.spec.ts`.
2. Add unit tests for `warningMessage`.
3. Add expects for the error outline in `SetDissolveDelay.spec.ts`.
> Remove input error outline for dissolve delay below project minimum

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-01-18_23-01+dts-off

- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
- frontend/src/tests/page-objects/Accounts.page-object.ts
- frontend/src/tests/page-objects/AddAccountModal.page-object.ts
- frontend/src/tests/page-objects/AddSnsHotkeyModal.page-object.ts
- frontend/src/tests/page-objects/BuyICPModal.page-object.ts
- frontend/src/tests/page-objects/CkBTCReceiveModal.page-object.ts
- frontend/src/tests/page-objects/ConfirmationModal.page-object.ts
- frontend/src/tests/page-objects/DisburseMaturityModal.page-object.ts
- frontend/src/tests/page-objects/DisburseNnsNeuronModal.page-object.ts
- frontend/src/tests/page-objects/FilterModal.page-object.ts
- frontend/src/tests/page-objects/MergeNeuronsModal.page-object.ts
- frontend/src/tests/page-objects/Modal.page-object.ts
- frontend/src/tests/page-objects/NnsStakeNeuronModal.page-object.ts
- frontend/src/tests/page-objects/ReceiveModal.page-object.ts
- frontend/src/tests/page-objects/RenameCanisterModal.page-object.ts
- frontend/src/tests/page-objects/SnsActiveDisbursementsModal.page-object.ts
- frontend/src/tests/page-objects/TransactionModal.page-object.ts
- frontend/src/tests/page-objects/VotingHistoryModal.page-object.ts
To avoid duplicate implementations of modal functionality in page objects and provide convenience methods to all modal page objects.
1. Add a base class for modal page objects.
2. Extend `ModalPo` in modal page objects.
3. Remove duplicate modal functionality from modal page object subclasses.
4. Update tests that need to use a new common method name.
only tests
not necessary
> Add ModalPo base page object

- .github/workflows/build.yml
- frontend/src/tests/e2e/ckbtc.spec.ts
- frontend/src/tests/page-objects/playwright.page-object.ts
The ckbtc.spec e2e test is flaky and sometimes fails.
The issue seems to be that the `waitForAbsent` on the Spinner within the balance is not waiting until it's removed.
It's weird because I would have expected it to fail if the spinner is still there. I wasn't able to replicate it locally, so it's hard to find the cause and the solution.
In this PR, I change the implementation of `waitForAbsent` to use `location.waitFor`.
I will keep monitoring the CI failures.
* Change the implementation of `waitForAbsent` in playwright element.
Not necessary.
> Fix: Flaky ckbtc e2e test

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/derived/proposals.derived.ts
- frontend/src/lib/stores/vote-registration.store.ts
- frontend/src/tests/lib/stores/vote-registration.store.spec.ts
Because "Show only proposals you can still vote for" can be unchecked or voting actions may take a few seconds, it is expected that the proposal will be accessible through navigation until it is complete. 
1. Start from nns proposal list page
2. Uncheck “`Show only proposals you can still vote for`" if checked
3. Start voting process on proposal with id N
4. Quickly click “Older” to navigate to N-1
5. Right after navigation click “Newer”
Expected navigation to proposal N, not N+1.
- ignore the temporal voting status (from `vote registrations store`) in `is proposal hidden` logic. The proposal entry remains in the `voteRegistrationStore` only till the voting is done.
- drop `VoteRegistrationStatus.complete` since it's not used anymore (It's a relic that we still rely on it).
- update …
> Do not hide vote in progress proposals

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/ui/NeuronTag.svelte
- frontend/src/lib/components/ui/Tooltip.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Display the full neuron type text within the tag (no acronyms). Remove tag tooltip since it's not necessary anymore.
- remove neuron type description support.
- update tag texts to have no acronyms.
- adjust tests to have no descriptions.
> Remove neuron tag tooltip

- frontend/src/lib/components/accounts/TransactionInfo.svelte
- frontend/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte
- frontend/src/lib/components/neuron-detail/actions/SplitNnsNeuronButton.svelte
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/derived/main-transaction-fee.derived.ts
- frontend/src/lib/modals/canisters/AddCyclesModal.svelte
- frontend/src/lib/modals/canisters/CreateCanisterModal.svelte
- frontend/src/lib/modals/neurons/SplitNnsNeuronModal.svelte
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/derived/main-transaction-fee.derived.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Use `bigint` for e8s and ulps.
In this PR, Remove deprecated store `mainTransactionFeeStore`.
The reason to stop using it is because it returned e8s in the `number` type instead of `bigint`.
* Remove `mainTransactionFeeStore` and use instead `mainTransactionFeeE8sStore`.
* Convert `MIN_NEURON_STAKE` to `bigint`.
* Change parameter and return type in `minNeuronSplittable` to `bigint`.
* Change parameter type in `neuronCanBeSplit` to `bigint`.
* Remove test for `mainTransactionFeeStore`.
* Convert parameter inputs from number to bigint.
Not necessary.
> GIX-2060: Remove mainTransactionFeeStore

- .gitignore
- CHANGELOG-Nns-Dapp-unreleased.md
The `*.orig` extension is used for some scripts to update candid types but it's only a temporary file. Some PRs from the bots add all the files to git and it might include this temporary files.
In this PR, I add the extension to gitignore.
* Add `.orig` file extension to gitignore
I created `test.orig` file and confirmed that it was ignored by git.
> Chore: Add pattern to gitignore

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.svelte
- frontend/src/lib/components/ui/TooltipIcon.svelte
- frontend/src/tests/lib/components/ui/TooltipIcon.spec.ts
- frontend/src/tests/page-objects/Tooltip.page-object.ts
- frontend/src/tests/page-objects/TooltipIcon.page-object.ts
We have one place where we have an info icon with a tooltip and we want to add more.
For convenience and consistency I'm factoring out the existing one into a separate component.
I'm also giving it the standard icon color and padding.
This makes the existing usage consistent with other info icons.
1. Create `TooltipIcon` component which has an `IconInfo` with a `Tooltip`.
2. Give it a left margin of `--padding` so the parent component doesn't have to style the gap.
3. Give it a color and make it center aligned.
4. Use the `TooltipIcon` in `SnsNeuronHotkeysCard.svelte` to replace the current ad-hoc implementation.
The affected icon is the one next to "Hotkeys".
"Following" is included for comparison.
Before:
After:
> Add TooltipIcon component

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte
- frontend/src/lib/components/ui/CommonItemAction.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.spec.ts
- frontend/src/tests/lib/components/ui/CommonItemAction.spec.ts
- frontend/src/tests/page-objects/SnsNeuronDissolveDelayItemAction.page-object.ts
Requested in point 22 of https://www.notion.so/dfinityorg/Wording-Changes-4411020138ce4d09b6605ad1fdbb9555
1. Add fields to `CommonItemAction` to add an optional tooltip next to the title.
2. Use the fields in `NnsNeuronDissolveDelayItemAction.svelte` and `SnsNeuronDissolveDelayItemAction.svelte` to explain the dissolve delay.
3. Pass the token to `SnsNeuronDissolveDelayItemAction` to use in the tooltip message.
Added a unit test that the tooltip text includes the token symbol.
Added an entry which will also cover the next PR.
> Add tooltip icon to dissolve delay item action

- frontend/src/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.spec.ts
- frontend/src/tests/page-objects/NnsNeuronDissolveDelayItemAction.page-object.ts
In https://github.com/dfinity/nns-dapp/pull/4326, I accidentally mixed up points 22 and 23 of https://www.notion.so/dfinityorg/Wording-Changes-4411020138ce4d09b6605ad1fdbb9555 and put the tooltip text for the neuron state on the item action for the dissolve delay.
In this PR we put the correct tooltip in the dissolve delay item action.
The intended behavior also requires additional logic because the intended tooltip text includes the dissolve delay duration and the tooltip should be hidden if the neuron is unlocked.
1. Include the duration in the dissolve delay item action tooltip.
2. Hide the tooltip if there is no dissolve delay.
covered
> Fix dissolve delay item action tooltip

- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic.yml
- .github/workflows/update-proposals.yml
- CHANGELOG-Nns-Dapp-unreleased.md
Managing dependencies should not overwhelm the team with PRs.
In this PR, I moved the workflows to a weekly frequency.
* Move update-aggregator workflow to every monday and improve PR title and description.
* Move update-didc workflow to every tuesday.
* Move update-ic workflow to every wednesday and improve PR description.
* Move update-proposals workflow to every thursday and improve PR title and description.
I pushed one branch to trigger one of the changed workflows to test that it still run successfully: https://github.com/dfinity/nns-dapp/actions/runs/7709246969
> Chore: Move to weekly workflows

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/derived/icrc-universes.derived.ts
- frontend/src/tests/lib/derived/icrc-universes.derived.spec.ts
Logo of the universe is read from the ledger metadata for added ICRC canisters.
* Use the `logo` field in the token if present in `icrcTokensUniversesStore`.
* Change one test description for unknown logo and add a new test when logo is present in the token.
* I tested by adding a new ICRC canister (which was an SNS) in the console.
> GIX-2140: Read logo from metadata

- frontend/package-lock.json
Ic-js has been released (see [2024.01.30-1600Z](https://github.com/dfinity/ic-js/releases/tag/2024.01.30-1600Z)). This PR propagates the new version number and last changes ("candid query keyword certified fix") to NNS dapp using a next version (that has also been published).
> Bump ic-js after release

- frontend/src/lib/components/accounts/SelectAccountDropdown.svelte
- frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
- frontend/src/tests/page-objects/ReceiveModal.page-object.ts
- frontend/src/tests/page-objects/SelectAccountDropdown.page-object.ts
Add the token symbol at the title of the ReceiveModal.
In this PR, I move the ReceiveModal.spec to use page objects.
* Add TestIdWrapper to SelectAccountDropdown.svelte
* New PO SelectAccountDropdownPo
* Add method to ReceiveModalPo
* Move ReceiveModal.spec to use the ReceiveModalPo.
Not necessary.
> GIX-2189: Use ReceiveModalPo in ReceiveModal.spec

- .github/workflows/checks.yml
- .github/workflows/reproducible-assets.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
GitHub CI is issuing warnings for actions that use Node v16:
Note: When these were all updated, CI failed, so these are updated individually.
* Bump the `setup-node` GitHub action to more recent versions.
See CI.  There should be no more warnings about old node from this action.  There are expected to be warnings from other actions.
> chore: Bump setup-node

- .github/actions/checkout_snsdemo/action.yaml
- .github/actions/start_dfx_snapshot/action.yaml
- .github/actions/test-e2e/action.yml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/deploy-to-app.yaml
- .github/workflows/docker-main.yaml
- .github/workflows/nightly.yaml
- .github/workflows/reproducible-assets.yaml
- .github/workflows/reproducible.yaml
- .github/workflows/tag.yaml
- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-snsdemo.yml
GitHub is emitting warnings for actions based on node16.  `checkout` is one of the affected actions.
* Update the version of the checkout action used in CI.
See CI.  There should be no warnings caused by the checkout action.
- Covered by a generic entry about updating GitHub actions.
> chore: Bump checkout

- .github/actions/install_ic_wasm/action.yaml
- .github/workflows/checks.yml
GitHub actions using node v 16 are deprecated:
* Update GitHub cache version from v3 to v4
- See CI
- Covered by an existing changelog entry for updating GitHub actions.
> chore: Bump GitHub cache action from v3 to v4

- frontend/src/lib/components/accounts/NnsAccountsFooter.svelte
- frontend/src/lib/modals/accounts/BuyIcpModal.svelte
- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/lib/themes/mixins/_button.scss
Remove unnecessary CSS. CSS to style a link like a button was added in the gix-components.
In this PR, remove the duplicated styles in NNS Dapp.
* Remove mixin button.scss
* Remove CSS to use the button mixin
* Remove CSS to style an anchor tag like a button in BuyICPModal
The classes used are the same that were implemented in gix-components. Therefore, there is no need to change them.
I checked that all looked the same as before.
Not necessary.
> Chore: Remove duplicated button styles

- .github/actions/build_nns_dapp/action.yaml
- .github/workflows/build.yml
- .github/workflows/docker-main.yaml
GitHub is emitting warnings for actions based on node16.
* Update `setup-buildx-action` to the latest version.
CI should have no errors about nodejs from this action.
> chore: Update setup-buildx-action

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/accounts/CkBTCReceiveButton.svelte
- frontend/src/lib/components/accounts/ReceiveButton.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
- frontend/src/lib/modals/accounts/IcrcReceiveModal.svelte
- frontend/src/lib/modals/accounts/NnsReceiveModal.svelte
- frontend/src/lib/modals/accounts/ReceiveModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
Help the user understand the context of the transaction.
In this PR, we add the token symbol in the ReceiveModal.
It's missing adding it in the CkBTReveiveModal which will come in ahoter PR.
* Change the i18n key "receive" from "ckBTC" to `"core"`and add `receive_with_token` for the modal title.
* Change `ckBTC.receive` to `core.receive_with_token` in the ReceiveModal and to `core.receive` everywhere else.
* Add `tokenSymbol` as prop in ReceiveModal.
* Pass the new prop to ReceiveModal in IcrcReceiveModal and NnsReceiveModal
* Add a test in ReceiveModal.spec.
> GIX-2189: Add token to ReceiveModal title

- .github/actions/test-e2e/action.yml
- .github/workflows/build.yml
- .github/workflows/reproducible-assets.yaml
- .github/workflows/reproducible.yaml
GitHub actions using node v16 are deprecated.  `download-artifact` is a case in point:
* Update `upload-artifact` and `download-artifact` to version 4.
Note: This is breaking change and requires a couple of small adjustments.  Please see the release notes here: https://github.com/actions/download-artifact/releases/tag/v4.0.0
* CI should contain no Nodejs warnings about this particular action.
- Covered by an existing changelog entry
> chore: Bump up/download-artifact

- frontend/src/lib/modals/accounts/CkBTCReceiveModal.svelte
- frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
Help the user understand the context of the transaction.
In this PR, we add the token symbol in the CkBTCReceiveModal.
* Use `i18n.core.receive_with_token` as title for CkBTCReceiveModal with the token label.
* Add two tests to check that the selected token label is added in the modal's title.
Already added in another PR.
> GIX-2189: Add token to CkBTCReceiveModal

- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/ParticipateSwapModal.spec.ts
- frontend/src/tests/page-objects/SelectAccountDropdown.page-object.ts
- frontend/src/tests/page-objects/TransactionFromAccount.page-object.ts
Be consistent. Use the SelectAccountDropdownPo instead of the DropdownPo directly.
* Add methods to SelectAccountDropdownPo.
* TransactionFromAccountPo uses SelectAccountDropdownPo instead of DropdownPo directly. Change method names.
* Change the tests using TransactionFromAccountPo's dropdown.
Not necessary.
> Chore: Use SelectAccountDropdownPo

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api/canisters.api.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/lib/api/icp-ledger.api.ts
- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/services/icp-accounts.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/sns-sale.services.ts
- frontend/src/tests/lib/api-services/governance.api-service.spec.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
- frontend/src/tests/lib/api/icp-ledger.api.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
Remove proto dependency.
When the fee of a transaction is not passed, the LedgerCanister will get the fee with a request because the fee is mandatory. The hardware wallet doesn't support the action of getting the ledger fee; therefore, that call fails and also the whole transaction call.
In this PR, I added the `fee` as mandatory in both `sendIcp` and `stakeNeuron` api functions.
* Add `fee` in canister api functions that call `sendICP`.
* Add `fee` to `stakeNeuron` governance api function.
* Add `fee` to `sendICP` icp-ledger api function.
* Add `fee` in canister services.
* Add `fee` in icp-account service `transferICP`.
* Add `fee` in call to `sendICP` inside the governance service `stakeNeuron`.
* Add `fee` in call to `sendICP` inside the sns-sale service `participateInSnsSale `.
* Add …
> Feat: Add fee to sendICP and stakeNeuron

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema.rs
- rs/backend/src/accounts_store/schema/proxy/tests.rs
- rs/backend/src/accounts_store/tests.rs
In previous PRs, a trait was defined for account CRUD and implemented for various underlying private implementations.  This trait is now ready to be exposed on the accounts store itself.
* Implement the `AccountsDbTrait` on the `AccountsStore` by passing calls through to the underlying implementation.
The standard accounts db tests are run against `AccountsStore`.
> Expose accounts API on the accounts store

- frontend/src/lib/components/neuron-detail/Ballots/BallotSummary.svelte
- frontend/src/lib/components/proposal-detail/MyVotes.svelte
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/components/neurons/BallotSummary.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
- frontend/src/tests/page-objects/BallotSummary.page-object.ts
Make code easier to read and maintain.
1. Extract code to render a string for a `Vote` to a `util`.
2. Use page objects in `BallotSummary.spec.ts`
Updated and added
not necessary
> Clean up BallotSummary and test

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
- frontend/src/lib/modals/accounts/IcrcTokenTransactionModal.svelte
- frontend/src/lib/modals/accounts/SnsTransactionModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/accounts/IcpTransactionModal.spec.ts
- frontend/src/tests/lib/modals/accounts/IcrcTokenTransactionModal.spec.ts
- frontend/src/tests/lib/modals/accounts/SnsTransactionModal.spec.ts
With the new tokens page the modals are not so clearly defined within a universe. To help the user be aware of the transactions, design proposed to add the token symbol in the Send and Receive modals' title.
In this PR, add the token symbol i the title of Send transactions, except ckBTC.
* New i18n key "core.send_with_token".
* Use new i18n for the title of the first step in IcpTransactionModal.
* Use new i18n for the title of the first step in IcrcTokenTransactionModal.
* Use new i18n for the title of the first step in SnsTransactionModal.
* Add a test to check the modals's title in IcpTransactionModal.spec.
* Add a test to check the modals's title in IcrcTokenTransactionModal.spec.
* Add a test to check the modals's title in SnsTransactionModal.spec.
> GIX-2189: Add token in Send transactions

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Having unused code can be confusing.
I search for all usages of `auth.` messages and found only these:
```
$ for x in $(jq -r '.auth | paths | join(".")' frontend/src/lib/i18n/en.json); do git grep -w -o "auth.$x"; done
frontend/src/lib/components/common/SignIn.svelte:auth.login
frontend/src/lib/components/common/SignInGuard.svelte:auth.login
frontend/src/lib/components/header/LoginIconOnly.svelte:auth.login
frontend/src/tests/lib/components/summary/SummaryLogo.spec.ts:auth.ic_logo
frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts:auth.ic_logo
frontend/src/tests/lib/routes/Accounts.spec.ts:auth.ic_logo
frontend/src/tests/lib/utils/universes.utils.spec.ts:auth.ic_logo
```
So only `login` and `ic_logo` are used and the rest can be removed.
Remove all entries from …
> Remove unused i18n.auth messages

- frontend/src/lib/modals/neurons/DissolveActionButtonModal.svelte
- frontend/src/lib/modals/sns/neurons/DissolveSnsNeuronModal.svelte
Make the code more readable and make it easier to find unused i18n messages.
1. Use `$i18n.neuron_detail.stop_dissolve_description` and `$i18n.neuron_detail.start_dissolve_description` directly instead of through `keyOf`.
2. Don't combine multiple assignments in a single Svelte `$:` block when it's not necessary.
Still pass.
Also tested manually.
not necessary
> Make usage of i18n message clearer

- frontend/src/lib/components/launchpad/Projects.svelte
Make the code easier to understand and make it easier to find unused i18n messages.
In `Projects.svelte` use `$i18n` messages directly instead of through `keyOf`.
Still pass.
And tested manually.
not necessary
> Use i18n messages directly in Projects.svelte

- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
There is no `"errors"` (plural) in `i18n` but `error.neuron_account_not_found` does exist.
Change `errors` (plural) to `error` (singular).
Unit test updated.
I'm not sure how to reproduce this to test it manually.
not necessary
> Fix typo in labelKey error.neuron_account_not_found

- frontend/src/lib/components/common/MenuItems.svelte
There is no benefit in using `keyOf` instead of accessing `$i18n` directly and referencing the entries directly makes it easier to find unused messages.
Instead of using `keyOf` refer to `$i18n.navigation.*` directly.
Existing tests still pass (and fail if I use a different message).
Also tested manually.
not necessary
> Use i18n messages directly in MenuItems.svelte

- frontend/src/lib/components/transaction/TransactionFormItemNetwork.svelte
- frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/page-objects/CkBTCTransactionModal.page-object.ts
- frontend/src/tests/page-objects/TransactionFormItemNetwor.page-object.ts
Help users understand the context better by adding the token symbol in the title of the send modals.
In this PR, add the token label in the ckBTC transaction modal.
* New helper `getTitleForm` inside CkBTCTransactionModal to select the title in the first step depending on the network and the universe id.
* Add test id to TransactionFormItemNetwork and create its page object.
* Add two tests to CkBTCTransactionModal.spec. One to check the ckBTC label and the other one when the network is BTC.
Not necessary. There is already a changelog entry for this.
> GIX-2189: Add token label in ckBTC send modal

- frontend/src/lib/components/accounts/NnsTransactionCard.svelte
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/lib/utils/transactions.utils.ts
- frontend/src/tests/lib/utils/transactions.utils.spec.ts
I'm trying to make it easier to find unused i18n message and I also think this makes the code easier to understand.
1. Instead of passing `i18n.transaction_name` to `transactionName`, pass `i18n`.
2. Instead of using the transaction type as a key, handle each transaction type explicitly.
Updated
not necessary
> Use i18n directly in transactionNames

- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
- frontend/src/lib/components/neurons/FollowNnsTopicSection.svelte
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
I want to set up a test that makes sure there are no unused i18n message.
For this I'm trying to make it easy to find if i18n messages are used.
For this I'm trying to reduce the dynamic usages of i18n messages.
In this PR, I change the dynamic usage of `i18n.follow_neurons["topic_${topic}_title"]` to direct usage of specific messages.
1. Add `getTopicTitle` and `getTopicSubtitle` which each have a map from `Topic` to specific messages.
2. Use these functions in `Followee.svelte` and `FollowNnsTopicSection.svelte`
Unit tests added
not necessary
> Use topic (sub)title i18n messages directly

- frontend/src/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.svelte
Make it easier to find unused i18n messages and make the code easier to understand.
Instead of using `keyOf` access `i18n` directly in `NnsNeuronDissolveDelayItemAction.svelte` and `SnsNeuronDissolveDelayItemAction.svelte`.
not necessary
> Use i18n directly in dissolve delay item action

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
None of these are used directly
```
for x in header.title voting.title voting.text canister_detail.id canister_detail.cycles wallet.address wallet.principal proposal_detail.vote proposal_detail__vote.headline proposal_detail__vote.total ; do git grep -F $x; done
```
And I don't think they are used dynamically.
1. `header.title`
2. `voting.title`
3. `voting.text`
4. `canister_detail.id`
5. `canister_detail.cycles`
6. `wallet.address`
7. `wallet.principal`
8. `proposal_detail.vote`
9. `proposal_detail__vote.headline`
10. `proposal_detail__vote.total`
Still pass
covered
> Remove more unused i18n entries

- frontend/src/lib/components/accounts/IcrcTokenWalletFooter.svelte
- frontend/src/lib/components/accounts/ReceiveButton.svelte
- frontend/src/lib/components/accounts/ReceiveSelectAccountDropdown.svelte
- frontend/src/lib/modals/accounts/IcrcReceiveModal.svelte
- frontend/src/lib/modals/accounts/ReceiveModal.svelte
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
- frontend/src/tests/page-objects/ReceiveModal.page-object.ts
The `ReceiveModal` component has a prop for the `universeId`.
This is only used to list the available accounts when `canSelectAccount` is `true`.
But in most cases `canSelectAccount` is not set to true and `universeId` is ignored.
When we merge the ICRC and SNS wallet components, it can be confusing whether to use the `ledgerCanisterId` or the `rootCanisterId` where previously a `universeId` was required. So to avoid confusion, I'm removing the `universeId` on the `ReceiveModal` when it's not necessary.
1. Make `universeId` optional on the `ReceiveModal` and related components, events and functions.
2. Only render the accounts picker when `canSelectAccount = true` and `universeId` is present.
Drive-by:
1. Add curly brackets on a multi-line function for convenience.
2. Fix the name of …
> Make universeId prop optional on ReceiveModal

- .github/actions/build_nns_dapp/action.yaml
- .github/workflows/build.yml
- .github/workflows/docker-main.yaml
Nodejs v16 actions are deprecated on GitHub.
* Update `build-push-action` to v4.
- See CI
- Covered by an existing changelog entry
> Bump build-push-action@v3 -> v4

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- scripts/unused-i18n
These messages appear to be unused. I checked the following before removing them:
* For `neuron_detail.remove_hotkey_success`, I looked at `git grep remove_hotkey_success`
* For `sns_project_detail.enter_amount`, I looked at ` git grep enter_amount`
* For `sns_neuron_detail.header`, I looked at `git grep -l sns_neuron_detail | xargs grep header`
* For `error__sns.init`, I looked at `git grep -l -w error__sns | xargs grep -w init`
* For `universe.select`, it's hard to grep for something with such generic words. I found that it was added in https://github.com/dfinity/nns-dapp/pull/1677 and it seems to already not be used there.
* For `ckbtc.confirmations`, I looked at `git grep -w confirmations frontend/src`
* For `error__ckbtc.icrc_no_universe`, I looked at `git grep icrc_no_universe`
1. I …
> Remove some unused i18n messages

- frontend/src/tests/e2e/accounts.spec.ts
- frontend/src/tests/e2e/ckbtc.spec.ts
- frontend/src/tests/e2e/design.spec.ts
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/e2e/multi-tab-auth.spec.ts
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/e2e/sns-participation.spec.ts
Remove `ENABLE_MY_TOKENS` flag.
In this PR, remove setting the flag in the e2e tests.
* Remove setting the flag in all e2e tests.
Not necessary.
> GIX-1985: Remove ENABLE_MY_TOKENS from e2e tests

- frontend/src/lib/components/neuron-detail/NeuronSelectPercentage.svelte
Display on top the tooltip on the disabled `Disburse`-maturity button to fix it's visibility on mobile.
- apply `top` to the Tooltip.
| <img width="389" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/22bdfc78-d82f-47d2-9888-a58e1b6e9039"> | <img width="392" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/fff54ae5-b05e-452c-90cd-91417fc4bd5d"> | 
Not needed
> style: display tooltip on top of the button

- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/mocks/icp-accounts.store.mock.ts
We want to pollAccounts when visiting the NnsAccounts. I don't remember why I removed the call when the tokens page was enabled, but it's not correct. We want to poll accounts also there.
This helps only in edge cases when the initial loading of the accounts fails. Probably why we haven't seen any user report about it.
* Enable `pollAccounts` in NnsAccounts when ENABLE_MY_TOKENS is enabled also.
* Use the mocked API data instead of setting the store. This also tests that `pollAccounts` works as expected in NnsAccounts.
Not necessary.
> Feat: Poll accounts in NnsAccounts

- frontend/src/lib/components/neurons/SelectNeuronsToMerge.svelte
Remove unnecessary (after the Tooltip update) `center` attribute usage.
- --`center`
Tested manually, looks the same:
Not necessary.
> chore: remove unnecessary center attr

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
There is a bug in mainnet.
If a user starts staking an SNS neuron, but loses connection after the transfer happens but before the claiming happens, the neuron isn't claimed when the user returns.
The reason was because we were checking the balances only on update calls. We lost that when we forced only query calls with `FORCE_CALL_STRATEGY`.
* Check SNS neuron balances also if `FORCE_CALL_STRATEGY` forces only a `"query"` strategy.
* I added the same test to claim a neuron forcing the strategy to `"query"`, the test failed. As expected with the bug.
* Then I added the fix to also check when `FORCE_CALL_STRATEGY` is `"query"` and it passed.
> Fix: check SNS neuron balances if force query

- frontend/src/lib/components/project-detail/ParticipateButton.svelte
Apply `toolbar` mixin from [gix-components](https://github.com/dfinity/gix-components/pull/375/files#diff-f8bc5f50175daa2d613b1761e0238cb431acaffa1467bb90df250b8820967dd9R31) to fix it's position on mobile (when wrapped w/ a Tooltip).
- Replace custom css w/ `toolbar.base`.
- Add alignment exception for tablet size (should be centered).
Css changes only.
| <img width="442" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/334cd38e-3e86-4420-80e0-d1a402ee03f0"> | <img width="441" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/28975d8a-72ed-409e-b1be-f22d6de870e0"> | 
Not necessary.
> style: use `toolbar.base` instead of custom css

- frontend/src/lib/routes/Accounts.svelte
- frontend/src/tests/lib/routes/Accounts.spec.ts
Remove ENABLE_MY_TOKENS feature flag.
In this PR, remove using the flag in the Accounts route and related spec file.
* Remove usage of `ENABLE_MY_TOKENS` in Accounts route.
* Remove tests that required `ENABLE_MY_TOKENS` to be `false` in Accounts spec file.
* I also cleaned up the related setup.
> GIX-1985: Remove my tokens flag account route

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/SelectNeuronsToMerge.svelte
- frontend/src/lib/pages/SnsProposalDetail.svelte
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
Fix the issue when all user neurons are shown as ineligible to vote.
**HowTo reproduce:**
1. goto sns proposal list page
2. log-in
3. refresh the page
4. wait for 10 seconds (otherwise there could be no certified proposals in the `snsProposalsStore` store)
5. click on any proposal that you are eligible to vote on
6. check the ineligible neurons block
The problem is the calculation of the `reloadForBallots` flag that prevents the dapp from redundant proposals fetching. 
The proposal call is skipped when:
- `reloadForBallots` is false (when no neurons available)
- there is a `certified` version of the proposal data in the `snsProposalsStore`
If this logic is applied before the neurons being loaded, but after the `snsProposalsStore` being updated, the wrong neurons state is shown on the …
> Fix missing ballots issue

- frontend/src/lib/identities/ledger.identity.ts
Remember how to get the Ledger device model in case we need it.
In this PR, I add a comment to the `getVersion` method. I thought that was the easiest way to keep track of that instead of some documentation somewhere else.
* Extend comment in `LedgerIdentity#getVersion` method.
No code changes.
Not necessary.
> Chore: Improve Ledger docs

- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
- scripts/proposals/did2rs.header
- scripts/sns/aggregator/did2rs.header
I am trying to address any missing documentation to help ease the code handover.  If I try to find missing documentation by increasing the sensitivity of the missing docs clippy, I get a huge number of warnings from autogenerated code.
* In autogenerated code, allow missing documentation of all types, not just of private items.
See CI
Too minor
> chore: Allow missing docs in autogenerated code

- rs/backend/src/state.rs
- rs/backend/src/state/with_raw_memory.rs
There will shortly be several state save & restore commands, not just one.  To avoid cluttering up the main state.rs, the existing save/restore command is moved into its own file.
- Move code.
- Existing CI should suffice
Too minor
> refactor: Move & rename

- rs/proposals/src/lib.rs
We would like to ensure that the codebase is well documented.  The proposals library has a lot of documentation which it is not exposed to rustdoc, so is not accessible.
- Change some comment types to make them accessible to rustdoc.
- Tweak the text
None
Too minor
> chore: Add missing rustdocs

- rs/backend/src/accounts_store/constructors.rs
- rs/backend/src/state.rs
We need a couple of small helper functions.
- When state and the accounts_db are stored in separate memories, it is necessary to recombine them post-upgrade.  As the accounts_db is private, we need a method to enable this.
- We need to be able to determine the schema of the state overall; there are two paths depending on whether data is partitioned or not.
None; these are both trivial and will be exercised in tests of the functions that use them.
Too minor
> feat: Stable memory helper functions

- .github/workflows/update-sns-aggregator-response.yml
Checkout v3 uses nodejs v16, which is deprecated in GitHub.
- Update checkout to v4.
See CI
Too minor
> chore: Update checkout

- rs/backend/src/accounts_store/constructors.rs
- rs/backend/src/state.rs
Code was accidentally omitted from #4425 
- `replace_accounts_db()` now returns the original database, as intended.
> fix: Include omitted code

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/SnsWallet.svelte
- frontend/src/lib/routes/Wallet.svelte
- frontend/src/lib/services/$public/sns.services.ts
- frontend/src/tests/lib/pages/AccountsTest.svelte
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
- frontend/src/tests/lib/services/_public/sns.services.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
- frontend/src/tests/page-objects/ReceiveModal.page-object.ts
- frontend/src/tests/page-objects/SnsWallet.page-object.ts
- frontend/src/tests/page-objects/Wallet.page-object.ts
- frontend/src/tests/utils/sns.test-utils.ts
SnsWallet and IcrcWallet have entirely separate implementations even though they should have identical functionality.
The reason for this is that SNS universes are identified by the rootCanisterId while ICRC tokens are identified by the ledgerCanisterId. So at each level of they component hierarchy, tokens, accounts, balances, etc. are identified in a different way.
However if we convert the rootCanisterId to the SNS ledger canister ID, we should be able to reuse the IcrcWalletPage component and the entire hierarchy below it and then delete a lot of code.
Note: the new `SnsWallet.svelte` is based on `IcrcWallet.svelte` and not based on the old `SnsWallet.svelte`. So in the first commit, I made `SnsWallet.svelte` an exact copy of `IcrcWallet.svelte` so that in the next commit it's easy to …
> NNS1-2847: Use IcrcWalletPage in SnsWallet

- rs/proposals/src/canisters/internet_identity.rs
- rs/proposals/src/canisters/mod.rs
- rs/proposals/src/canisters/nns_governance/internal.rs
- rs/proposals/src/canisters/nns_registry/internal.rs
- rs/proposals/src/lib.rs
- rs/proposals/src/tests/mod.rs
The main body of the proposals crate contains types imported from Internet Identity.  It is not immediately obvious which types are from II and some of these types are no longer up to date.
- Move the II types into a dedicated file, so that these are easy to recognize and can potentially be updated automatically.
- Add rustdocs
- None.  There are no code changes, only a move, so existing functionality is completely unchanged.
Too minor
> refactor: Move II types into a dedicated file

- frontend/src/lib/components/proposal-detail/VotingCard/StakeNeuronToVote.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/StakeNeuronToVote.spec.ts
- frontend/src/tests/page-objects/StakeNeuronToVote.page-object.ts
Replace `button` tag with `a` tag in the `Stake Token` button, to be consistent in the application.
- `<button>` -> `<a>`
- apply button utility classes
Tested manually that if works and feels the same.
Not necessary
> refactor: replace "button" with "a" tag

- frontend/src/lib/services/ckbtc-accounts.services.ts
- frontend/src/lib/services/ckbtc-convert.services.ts
- frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
In this PR, remove the ckBTC service `loadCkBTCAccounts`.
* Remove `loadCkBTCAccounts`.
* In ckBTC convert services use `loadAccounts` wallet service instead.
* Rename and change the mock in the ckbtc-convert.services.spec
Not necessary.
> NNS1-2851: Remove loadCkBTCAccounts

- frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte
- frontend/src/lib/derived/selected-token.derived.ts
- frontend/src/lib/modals/sns/neurons/SnsActiveDisbursementsModal.svelte
- frontend/src/tests/lib/derived/selected-token.derived.spec.ts
SNS tokens are in the `tokensStore` keyed by `rootCanisterId` and now also by `ledgerCanisterId`.
We want them only keyed by `ledgerCanisterId` so we need to change all the places that access by `rootCanisterId`.
In some places we use `$tokensStore[$selectedUniverseIdStore.toText()].token` to get the token for the current universe.
In this PR we provide a convenient `selectedTokenStore` which gives the token for the selected universe.
This can then, in the next PR, be changed to use the SNS `ledgerCanisterId` instead of `rootCanisterId`.
1. Add `selectedTokensStore` which holds the token for the selected universe.
2. Use `selectedTokensStore` instead of `$tokensStore[$selectedUniverseIdStore.toText()].token` in `SnsNeuronPageHeading.svelte` and `SnsActiveDisbursementsModal.svelte`.
Unit …
> Add selectedTokenStore

- frontend/src/lib/services/sns-accounts-balance.services.ts
- frontend/src/lib/services/sns-accounts.services.ts
- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/sns-accounts.services.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
In this PR, change the implementation of `uncertifiedLoadSnsAccountsBalances` to use current service `loadSnsAccounts`.
This way merging api functions and stores later will be easier.
* Rename `uncertifiedLoadSnsAccountsBalances` to `uncertifiedLoadSnsesAccountsBalances`. Notice the "Snses".
* `uncertifiedLoadSnsesAccountsBalances` uses `loadSnsAccounts` and doesn't load the SNS token because that's done by the aggregator service.
* Add optional `strategy` param to `loadSnsAccounts`.
* Rename usages of `uncertifiedLoadSnsAccountsBalances`.
* Add test for `strategy` param in `laodSnsAccounts` and change expects on the test that calls `loadSnsAccounts` without `strategy`.
Not necessary.
> NNS1-2851: Refactor uncertifiedLoadSnsesAccountsBalances

- frontend/src/lib/services/dev.services.ts
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
In this PR, remove the sercive `loadIcrcAccount` and use `loadAccounts` from wallet services instead.
* Remove `loadIcrcAccount`.
* Use `loadAccounts` where `loadIcrcAccount` was being used.
* Remove test for `loadIcrcAccount`.
Not necessary.
> NNS1-2851: Remove loadIcrcAccount service

- frontend/src/lib/services/wallet-accounts.services.ts
- frontend/src/lib/services/wallet-uncertified-accounts.services.ts
- frontend/src/tests/lib/services/wallet-accounts.services.spec.ts
- frontend/src/tests/lib/services/wallet-uncertified-accounts.services.spec.ts
In this PR, refactor `uncertifiedLoadAccountsBalance` to use current services instead of creating new ones.
* Change implementation of `uncertifiedLoadAccountsBalance`.
Same functionality.
Not necessary.
> NNS1-2851: Refactor uncertifiedLoadAccountsBalance

- .github/actions/build_nns_dapp/action.yaml
- .github/workflows/build.yml
- .github/workflows/docker-main.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
Node v16 is deprecated in GitHub actions:
- Update the `build-push-action` from `v4` to `v5`.
- See CI
> chore: Update gh build-push-action, as nodev16 is deprecated

- frontend/src/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.svelte
- frontend/src/tests/lib/modals/sns/SnsIncreaseStakeNeuronModal.spec.ts
SnsIncreaseStakeNeuronModal has code to call `loadSnsAccounts` but only if `transactionFee` or `governanceCanisterId` is not available. Both of these come from the aggregator data, which is always loaded on app init. And even if they weren't, calling `loadSnsAccounts` doesn't load the token or the project.
Previously, it would call `syncSnsAccount`, which would at least load the SNS token as well, but that was changed because we always have the SNS token from the aggregator data.
And the accounts are already loaded on the `SnsNeuronDetail` before you can open the `SnsIncreaseStakeNeuronModal`, and even if they weren't, the current code would never call `loadSnsAccounts` because it doesn't check if the accounts are loaded or not, and only checks `transactionFee` and `governanceCanisterId` …
> NNS1-2849: Remove unused code from SnsIncreaseStakeNeuronModal

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/sns_aggregator/src/fast_scheduler.rs
- rust-toolchain.toml
Keep dependencies up to date.
In this PR, upgrade Rust to 1.76.0
* Upgrade Rust.
* Fix lint issue.
Still passing.
> Chore: Upgrade Rust

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api-services/sns-aggregator.api-service.ts
- frontend/src/lib/services/$public/sns.services.ts
- frontend/src/tests/lib/api-services/sns-aggregator.api-service.spec.ts
- frontend/src/tests/lib/services/_public/sns.services.spec.ts
- frontend/src/tests/lib/services/app.services.spec.ts
Requests to the aggregator happens twice during a short time and that triggers extra unnecessary calls.
In this PR, I introduce the SNS Aggregator API Service similar to the Governance API Service to cache calls and avoiding hitting the network unnecessarily.
* Add a sns-aggregator api service.
* Use the sns-aggregator api service instead of the service directly in `loadSnsProjects.
* Add a test for the sns-aggregator api service.
* Clear the sns aggregator api service after every test in sns.services and app.services spec files.
> Feat: Add SNS Aggregator API service

- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/stores/busy.store.ts
- frontend/src/tests/lib/modals/common/FilterModal.spec.ts
Clean up unused code.
Looking at unused busy screen initiators a bug was found because the busy screen started was not the same being stopped in the FilterModal.
The bug was never encountered because the filters were always present when rendering the FilterModal.
Yet, in this PR we use a different approach and remove the unused initiators. Instead of showing a whole busy screen that won't allow the user to do anything, we show a spinner within a modal.
* Remove using busy screens in FilterModal and instead render a modal component with a spinner if the filters are not present.
* Add a test when the filters are not present.
Not necessary.
> Chore: Remove unnecessary busy screens

- .github/workflows/deploy-to-app.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
We have a workflow to release nns-dapp to an app subnet.
We don't use it often, and when we do, we use the manual dispatch.
Most of the time, the app is out of cycles.
No need to waste cycles on weekly deploys that we don't use.
Remove the scheduled deploy and only leave the manual deploy trigger.
no
> Remove cron for app deploy

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/universe.utils.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/page-objects/UniversePageSummary.page-object.ts
- frontend/src/tests/page-objects/WalletPageHeader.page-object.ts
The SNS token logo in the ledger canister metadata can be different from the SNS project logo.
Currently in the wallet, we show the project logo but you could argue that we should show the token logo instead because the wallet is about tokens and also the wallet should probably act the same for SNS tokens as for non-SNS tokens.
But before we fix this, we want to make sure that SNSes can change their token logo if they want to.
So in this PR we add a test to make sure that we don't accidentally fix this until we should.
1. Add a test to make sure the logo displayed on the SnsWallet is the project logo and not the token logo.
2. Support setting the token logo in `setSnsProjects`.
3. Support getting the token logo URL in page object.
Tested by setting `logo: summary.token.logo` instead of …
> Test that we show the project logo on the token wallet

- frontend/src/lib/api/icrc-ledger.api.ts
- frontend/src/lib/api/sns-ledger.api.ts
- frontend/src/lib/services/sns-accounts.services.ts
- frontend/src/tests/fakes/sns-ledger-api.fake.ts
- frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
- frontend/src/tests/lib/api/sns-ledger.api.spec.ts
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/routes/Neurons.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/sns-accounts.services.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Unify wallet implementation.
In this PR, remove `getIcrcAccount` and move `getSnsAccounts` to a service.
Before, the `Account` was created at the api layer.
Now, the api layer exposes the function to get the balance and a service creates the `Account` type for SNSes.
* Remove `getIcrcAccount` icrc-ledger api
* Move `getSnsAccounts` from sns-ledger api to sns-accounts services.
* Add api `querySnsBalance` in sns-ledger api.
* Update sns-ledger-fake api.
* Update tests using sns-ledger-fake api.
* Remove test for `getIcrcAccount` in icrc-ledger api.
* Remove test for `getSnsAccounts` in sns-ledger api spec file.
* Add test for `querySnsBalance` in sns-ledger api spec file.
* Tests that mocked `getSnsAccounts` now mock `querySnsBalance`.
Not necessary.
> NNS1-2852: Remove getIcrcAccount and move getSnsAccounts

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
`test-upgrade-map` is currently flaky on CI.
Example failure: https://github.com/dfinity/nns-dapp/actions/runs/7873570882/job/21481466301?pr=4461
```
Upgrading code for canister nns-dapp, with canister ID bkyz2-fmaaa-aaaaa-qaaaq-cai
Check passed: Installed nns-dapp matches local wasm.
Error: Failed query call.
Caused by: Failed query call.
The replica returned a replica error: reject code CanisterError, reject message IC0502: Canister bkyz2-fmaaa-aaaaa-qaaaq-cai trapped: heap out of bounds, error code Some("IC0502")
=============================================
at: ./scripts/nns-dapp/migration-test.canister:1: verify_healthy
at: ./scripts/nns-dapp/migration-test.canister:146: upgrade_nnsdapp
at: ./scripts/nns-dapp/migration-test:114: downgrade_to_wasm1
at: …
```
> Ignore failures of test-upgrade-map

- frontend/src/lib/derived/sns/sns-canisters.derived.ts
- frontend/src/tests/lib/derived/sns/sns-canisters.derived.spec.ts
In order to deprecate `snsAccountsStore` we'll need to know the ledger canister ID from the root canister ID in many places.
The `snsLedgerCanisterIdsStore` was introduced in https://github.com/dfinity/nns-dapp/pull/4477 but that PR is blocked because we still need to load SNS accounts after getting the tokens.
So I split this PR from that PR.
Add a derived store which maps root canister IDs to ledger canister IDs.
This is not used yet.
Add a unit test for the derived store.
not necessary
> Add snsLedgerCanisterIdsStore

- frontend/src/lib/components/universe/UniverseAccountsBalance.svelte
- frontend/src/lib/derived/universes-accounts-balance.derived.ts
- frontend/src/lib/utils/accounts.utils.ts
- frontend/src/tests/lib/derived/universes-accounts-balance.derived.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/wallet-uncertified-accounts.services.spec.ts
- frontend/src/tests/lib/utils/accounts.utils.spec.ts
Readers of `universesAccountsBalance` never look at whether the data is `certified` and if we don't need to include that field, the store can trivially be derived from `universesAccountsStore`.
1. Change `UniversesAccountsBalanceReadableStore` to just hold the balance and not whether it's `certified`.
2. Change the logic from assembling the data from 3 different accounts store to simply derive it from `universesAccountsStore`.
3. Change readers of `universesAccountsBalance` to use the value directly instead of having to get the `balanceUlps` field from it.
4. Remove `sumNnsAccounts` which became unused.
updated
not necessary
> Simplify universesAccountsBalance derived store

- frontend/src/lib/api/icrc-ledger.api.ts
- frontend/src/lib/api/sns-ledger.api.ts
- frontend/src/tests/fakes/sns-ledger-api.fake.ts
- frontend/src/tests/lib/api/icrc-ledger.api.spec.ts
- frontend/src/tests/lib/api/sns-ledger.api.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
In this PR, remove `getIcrcToken` which was used only in getSnsToken and use the canister directly instead.
* Remove `getIcrcToken` from icrc-ledger api functions.
*Remove `getSnsToken` from sns-ledger api functions.
* Remove test for `getIcrcToken`.
* Remove test for `getSnsToken`.
Not necessary.
> NNS1-2852: Remove getIcrcToken

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-02-07_23-01+feature

- frontend/package-lock.json
We just released a new [version](https://github.com/dfinity/ic-js/releases/tag/2024.02.14-1600Z) of ic-js libs, this PR bump those dependencies to their next version.
In comparison to the libs already included in main, extending ICP `Subaccount.fromId` to accept more than 256 (see [PR](https://github.com/dfinity/ic-js/pull/526)) is the only notable change.
> Upgrade to catch next version of ic-js

- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
We would like to render all the latest proposal types.
* Updated the Rust code derived from `.did` files in the proposals payload rendering crate.
* Note: The candid files under `declarations/nns-$CANISTER` are used as inputs.
> Update proposal rendering dependencies

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/sns-neurons-check-balances.services.ts
- frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
A bug was raised in the forum where an SNS neuron was appearing even though the user transferred ownership of such a neuron.
The issue came from the background task that checks neuron subaccounts. The background task didn't consider whether the user has still some permission with the neuron and refreshes it and adds it to the store.
The fix is to try to query the neuron from the canister directly and then check the permissions before continuing with refresh or not refresh.
* Add code in the main `checkNeuronsSubaccounts` to fetch the neuron when it wasn't passed and compare the permissions with the user's identity.
* Add two tests regarding the bug. One simulating the bug and another one with an edge case to confirm that if a neuron without permissions is found, it doesn't break the loop …
> Fix: Bug with neuron appearing

- frontend/src/lib/derived/tokens.derived.ts
- frontend/src/lib/derived/universes-accounts-balance.derived.ts
- frontend/src/lib/derived/universes-accounts.derived.ts
- frontend/src/lib/derived/universes-tokens.derived.ts
- frontend/src/lib/stores/sns-filters.store.ts
- frontend/src/lib/utils/utils.ts
- frontend/src/tests/lib/utils/utils.spec.ts
In some places we use `.reduce()` to construct an object out of entries.
`Object.fromEntries` is a cleaner more efficient way to do this.
1. Add a util `mapEntries` to combine `Object.entries` and `Object.fromEntries`.
2. Use the util in a few places.
Added unit tests for the new util.
not necessary
> Use fromEntries instead of reduce

- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/api-services/governance.api-service.spec.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
Remove unused code.
The merge maturity functionality is not used anymore.
* Remove mergeMaturity neuron service.
* Remove mergeMaturity api function.
* Remove mergeMaturity api service function.
* Remove test for mergeMaturity neuron service.
* Remove test for mergeMaturity api function.
* Remove test for mergeMaturity api service function.
Not necessary.
> Remove mergeMaturity

- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
Make optional parameter mandatory.
The `userTokensData` was optional while the NnsAccounts rendered the accounts cards instead of the tokens table.
* Make `userTokensData` mandatory in NnsAccounts.
Still passing.
Not necessary.
> Chore: Make prop mandatory in NnsAccounts

- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
We would like to parse all the latest SNS data. To do so, we update the candid interfaces for the SNS aggregator.
* Updated the Rust code derived from `.did` files in the aggregator.
* Note: The candid files under `declarations/nns-$CANISTER` are used as inputs.
> Update aggregator candid bindings

- frontend/package-lock.json
I've released gix-cmp [v4.1.0](https://github.com/dfinity/gix-components/releases/tag/v4.1.0) so this PR bumps the library to catch-up with the new next version number of the ui kit.
> Bump gix next version

- .github/workflows/build.yml
- scripts/nns-dapp/downgrade-upgrade-test
- scripts/nns-dapp/migration-test.canister
- scripts/sns/aggregator/downgrade-upgrade-test
Fix the test-upgrade-map
In testing scripts, always stop a canister before upgrade (and start after upgrade)
The test-upgrade-map passes locally
> Always stop before upgrading a canister, in testing scripts

- .github/workflows/checks.yml
This test had to be disabled to unbreak CI.
Now that CI is fixed, it can be enabled again.
Re-enable the `download-nns-dapp-ci-wasm` test on CI.
pass
https://github.com/dfinity/nns-dapp/actions/runs/7989111051/job/21815071000?pr=4522
https://github.com/dfinity/nns-dapp/actions/runs/7989111051/job/21815071671?pr=4522
not necessary
> Re-enable disabled wasm download test

- frontend/src/lib/stores/actionable-nns-proposals.store.ts
- frontend/src/tests/lib/stores/actionable-nns-proposals.store.spec.ts
Add `actionableNnsProposalsStore` to store proposals that user can vote for. Will be used for displaying voting proposal count and in "Actionable Proposals" tab.
- add a store
- test the new store
Not yet
> New actionable nns proposals store

- frontend/src/lib/constants/canister-ids.constants.ts
- frontend/src/lib/utils/env-vars.utils.ts
- frontend/src/tests/lib/utils/env-vars.utils.spec.ts
- frontend/vitest.setup.ts
We want to read ICP transactions from the ICP index canister.
For this we need to know the canister ID.
Create index canister ID constant from environment.
covered
> NNS1-2862: Add index canister ID to envVars

- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
Read ICP transactions from ICP Index canister.
In this PR, introduce the helper that transforms the type of the canister to the transaction type in the UI.
* New icp-transactions util mapIcpTransaction.
* Add test for new util.
> NNS1-2869: Add mapIcpTransaction

- scripts/canister_ids
- scripts/canister_ids.test
NNS dapp now requires the index canister ID in its arguments.
When installing on DevEnv, we need this canister ID in `canister_ids.json`.
Update `scripts/canister_ids` to include the index canister ID when importing IDs from a URL.
* Test updated.
* Ran manually, then ran `DFX_NETWORK=devenv_dskloet ./config.sh` and check the index canister ID in the output.
covered
> Include index canister when importing canister IDs

- frontend/src/lib/stores/icp-transactions.store.ts
- frontend/src/lib/stores/icrc-transactions.store.ts
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/lib/utils/transactions.utils.ts
- frontend/src/tests/lib/stores/icp-transactions.store.spec.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
- frontend/src/tests/lib/utils/transactions.utils.spec.ts
- frontend/src/tests/mocks/icp-transactions.mock.ts
Read ICP transactions from ICP Index canister.
In this PR, introduce the `icpTransactionsStore`.
It is modeled after the `icrcTransactionsStore` but
* it uses different types, and
* is not keyed by universe ID
I recommend reviewing the second commit separately so you can see the difference between the ICRC and ICP store.
1. Copied `icrc-transactions.store.ts` and `icrc-transaction-store.spec.ts`.
2. Make relevant changes.
3. Make `getUniqueTransactions` generic and move it to a different file.
Unit tests copied from ICRC store and adjusted.
Unit tests for `getUniqueTransactions`, moved to another file.
covered
> NNS1-2866: Add icpTransactionsStore

- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
Fetch ICP wallet transactions from ICP Index instead of NNS Dapp canister.
In this PR, introduce the helper `mapToSelfTransactions` that duplicates transactions to and from the same wallet. A pattern needed for the required UX on transactions to self.
* New icp-transactions util `mapToSelfTransactions`.
* Add tests for the new util `mapToSelfTransactions`.
Not necessary.
> NNS1-2869: Add mapToSelfTransactions

- frontend/src/lib/api/icp-index.api.ts
- frontend/src/tests/lib/api/icp-index.api.spec.ts
Fetch ICP transactions from the ICP Index canister.
In this PR, add an api function to fetch the transactions from the ICP Index canister.
* New api file icp-index and function `getTransactions`.
* I tested it manually as part of #4511 
* Test for the new api function.
> NNS1-2865: icp-index api getTransactions

- .github/actions/start_dfx_snapshot/action.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
Since we upgraded from dfx version 0.14.4 to 0.15.3, if we try to install a canister immediate after starting an snsdemo snapshot, this times out. So in https://github.com/dfinity/nns-dapp/pull/4161 we added a retry loop to make sure the installation succeeds.
While I was fixing CI yesterday (for https://github.com/dfinity/nns-dapp/pull/4518), I realized that this first timeout takes all of 5 minutes and can be avoided with a 20 second sleep. See for example this run (where I've added calls to `date`) that shows the 5 minute timeout:
https://github.com/dfinity/nns-dapp/actions/runs/7987325846/job/21809703130
```
Install:
Wed Feb 21 10:13:51 UTC 2024
Reinstalling code for canister nns-dapp, with canister ID qsgjb-riaaa-aaaaa-aaaga-cai
Error: Failed to install wasm module to canister …
```
> Wait before installing canister on CI

- frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/page-objects/IncreaseNeuronStakeModal.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronModals.page-object.ts
We will load transactions from the index canister instead of from nns-dapp.
We want to make sure transactions are still rendered correctly.
In particular we want to make sure that stake transactions on a neuron with (later) 0 stake are still recognized.
1. Extend the e2e test that merges neurons to check that the stake/increase stake transactions are still recognized after merging.
2. Add test IDs and page objects.
test only
covered
> E2E: Check transactions after merging neurons

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/main.rs
- rs/backend/src/state.rs
- rs/backend/src/state/tests.rs
In previous PRs, `State::from(memory)` was defined.  This recovers state from memory from either managed virtual memory or raw memory.  This `from(memory)` function supersedes `State::restore()` which recovers memory only from raw memory.
Note: `restore()` took no arguments as it read the global stable memory state object.  This makes it impossible to test outside a   canister, while the `from(memory)` function can be tested against memory that is passed in.  There is a gap in the logic when using raw memory with the old API, as that still uses the global object, but the plan is to delete that code path once we no longer use raw memory.
- Replace the call to `restore()` with one to `from(memory)`
- Delete now unused code.
- There is an existing e2e test that verifies that this canister …
> feat: Use State::from instead of restore()

- frontend/src/lib/constants/constants.ts
- frontend/src/lib/services/icp-transactions.services.ts
- frontend/src/lib/services/icrc-transactions.services.ts
- frontend/src/lib/worker-services/icrc-transactions.worker-services.ts
- frontend/src/tests/lib/api/icp-index.api.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/services/icp-transactions.services.spec.ts
- frontend/src/tests/lib/services/icrc-transactions.services.spec.ts
- frontend/src/tests/lib/worker-services/icrc-transactions.worker-services.spec.ts
- frontend/src/tests/mocks/transaction.mock.ts
Fetch the ICP transactions from ICP Index canister instead of NNS dapp canister.
In this PR, introduce two services used to fetch the transactions and load them in the store.
They will be used in the page component in another PR.
* Add icp-transactions services `loadIcpAccountTransactions` and `loadIcpAccountNextTransactions`.
* Move a mock to the mocks file.
* Add tests for the new icp-transactions services.
Not yet necessary,
> NNS1-2866: Add icp-transactions services

- frontend/src/lib/services/actionable-proposals.services.ts
- frontend/src/tests/lib/services/actionable-proposals.services.spec.ts
Add `updateActionableProposals` to fill the `actionableNnsProposalsStore`.
- `updateActionableProposals` service
- `updateActionableProposals` service
Not necessary
> New actionable proposals services

- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
The `merge-neurons` e2e test became flaky after this recent https://github.com/dfinity/nns-dapp/pull/4542
https://github.com/dfinity/nns-dapp/actions/runs/8016517254/job/21898719819?pr=4545
What happened is that we click on the "Internet Computer" row in the tokens table before the balance is loaded.
Even if we explicitly wait for the balance to be loaded, this didn't fix the issue because `waitForBalance` waits for the spinner to be absent but it could be called before the spinner has even appeared.
1. Fix `TokenTableRow.waitForBalance` to make sure that the element that would hold the spinner is rendered before waiting for the spinner to be absent.
2. Override `TokensTableRow.click` to make sure the balance is rendered before clicking.
I was able to reproduce the failure locally and …
> Fix flaky merge neurons e2e test

- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/routes/Wallet.svelte
- frontend/src/lib/stores/neurons.store.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/stores/neurons.store.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
- frontend/src/tests/utils/sns.test-utils.ts
Fetch the ICP transactions from ICP Index canister not the NNS dapp canister.
In this PR, load the transactions in NnsWallet from ICP. Only loads the first page.
In upcoming PRs: loading and paging functionality.
* Load the transactions from ICP Index in NnsWallet as well as the neurons.
* Create a list of UiTransction from the Index type and pass it to UiTransactionsList in NnsWallet.
* New derived store `neuronAccountsStore`.
* Add a test that the transactions are rendered with the flag enabled.
* Add a test that a "stake" transaction is rendered with the flag enabled. This is to test that NnsWallet also loads the neurons.
* Add a test that a "Decentralization Swap" transaction is rendered with the flag enabled. This is to test that NnsWallet checks the aggregator data to calculate …
> NNS1-2868: Load transactions in NnsWallet

- frontend/src/lib/components/canisters/CanisterCardTitle.svelte
- frontend/src/lib/components/canisters/SelectCyclesCanister.svelte
- frontend/src/lib/components/ui/Input.svelte
- frontend/src/lib/modals/canisters/AddCyclesModal.svelte
- frontend/src/lib/modals/canisters/CreateCanisterModal.svelte
- frontend/src/lib/pages/CanisterDetail.svelte
- frontend/src/lib/pages/Canisters.svelte
- frontend/src/tests/e2e/canisters.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/page-objects/AddCyclesModal.page-object.ts
- frontend/src/tests/page-objects/App.page-object.ts
- frontend/src/tests/page-objects/CanisterCard.page-object.ts
- frontend/src/tests/page-objects/CanisterDetail.page-object.ts
- frontend/src/tests/page-objects/Canisters.page-object.ts
- frontend/src/tests/page-objects/ConfirmCyclesCanister.page-object.ts
- frontend/src/tests/page-objects/CreateCanisterModal.page-object.ts
- frontend/src/tests/page-objects/MenuItems.page-object.ts
- frontend/src/tests/page-objects/SelectCyclesCanister.page-object.ts
- frontend/src/tests/page-objects/playwright.page-object.ts
This is prompted by the change to read transactions from the index canister so we want to make sure we still render transaction such as "Create Canister" and "Top-up Canister" correctly.
But we did not yet have any end-to-end test for canisters so I added more than just the minimum to check transactions.
1. Add an end-to-end test which creates a canister, renames a canister and tops-up a canister.
2. Add missing test IDs.
3. Fix one typo in an existing test ID.
4. Add necessary page objects.
5. Factor out a function to navigate to the NNS main account and reuse it.
6. Change `typeText` on the Playwright page object to use `fill()` instead of `type()`. Fill replaces existing text, which we need because when renaming the canister, the input field is prefilled with the existing name. Since …
> Add e2e test for canisters

- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
Fetch the ICP transactoins from the ICP Index instead of NNS dapp canister.
In this PR, introce a helper to sort the transactions by created time.
This will be used when we introduce pagination.
* New icp transaction util `sortTransactionsByTimestamp`.
* Test new util.
Not necessary.
> NNS1-2871: Add sort transactions util

- rs/backend/src/accounts_store/schema/proxy/migration.rs
`dfn_core::api::print()` is deprecated in favour of `ic_cdk::println!()`.
- Convert three instances of the old form to the new.
- See CI
Too minor
> chore: Use println rather than the old dfn_core print

- frontend/src/lib/services/icp-transactions.services.ts
- frontend/src/tests/lib/services/icp-transactions.services.spec.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
- frontend/src/tests/mocks/icp-transactions.mock.ts
Fetch ICP transactions from ICP Index canister.
In this PR, I fix a misunderstanding with the field `oldestTxId` of the response.
The meaning is not the oldest tx id of that specific page, but of the user.
* Adapt code to fetch next page `loadIcpAccountNextTransactions` to the new meaning.
* Adap code to set `complete` in the store in `loadIcpAccountTransactions`.
* Change and add tests with the new meaning.
Not necessary.
> NNS1-2871: Fix meaning of oldestTxId from ICP Index

- rs/backend/src/accounts_store.rs
- rs/backend/src/arguments.rs
- rs/backend/src/assets.rs
- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/state/partitions.rs
- rs/backend/src/state/partitions/schemas.rs
- rs/proposals/src/lib.rs
- rs/sns_aggregator/src/assets.rs
- scripts/lint-rs
Potential panics should be documented.
- Stop ignoring linter errors for missing panic documentation.
- Where panics can be eliminated in a couple of lines of code, do so.
- Where panics are in fact not possible or require more memory than the state of the universe, use `unreachable!("some explanation")` to communicate this.
- Document the remaining panics.
Existing CI should suffice
> doc: Document or eliminate panics

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/accounts_store/schema/proxy/migration.rs
- rs/backend/src/main.rs
- rs/backend/src/periodic_tasks_runner.rs
- rs/backend/src/state.rs
- rs/backend/src/state/partitions.rs
- rs/backend/src/state/partitions/schemas.rs
In main we currently have:
- The ability to create a canister with accounts stored in EITHER stable structures OR on the heap.
- Functions to migrate data step by step, exercised in unit tests.
We would like to enable migration for a canister.
- Use a timer to exercise the existing migration-stepping command, if we need to migrate.
- We use the standard the upgrade-downgrade test to verify that migration across schemas works in an e2e test.
TODO before merging
> feat: Enable data migration on demand

- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
Fetch the ICP transactions from ICP index canister instead of NNS dapp.
In this PR, introduce pagination for transactions with infinite scrolling in the wallet page.
PENDING: Show a nice initial loading indicator in the first load.
* Sort the transactions before rendering them.
* Call an internal `loadNextTransactions` on nnsIntersect.
* New variables to show loading and disable pagination on complete.
* Test `"should render second page of transactions from ICP Index canister"`
> NNS1-2872: Add pagination to ICP transactions

- frontend/src/lib/stores/icp-account-balances.store.ts
- frontend/src/tests/lib/stores/icp-account-balances.store.spec.ts
The current icpAccountStore holds a combination of accounts and balances in a single store. This means all the data has to be loaded together and if we just want to change a balances, we have to manipulate the data in the store, which can interfere with loading the accounts.
The cleaner way is to have a separate store for accounts and a separate store for balances and a derived store which merged both into accounts with balances. That way when we update a balance in the balances store, it will just automatically recreate the accounts with balances.
In this PR, I'm only adding a new store for account balances (separate from accounts). In a later PR this will be used as described above.
Add `icpAccountBalancesStore` which holds a record of `balanceE8s` for each ICP account identifier of the …
> NNS1-2857: Add icpAccountBalancesStore

- frontend/src/lib/derived/icp-accounts.derived.ts
- frontend/src/tests/lib/derived/icp-accounts.derived.spec.ts
The current icpAccountStore holds a combination of accounts and balances in a single store. This means all the data has to be loaded together and if we just want to change a balances, we have to manipulate the data in the store, which can interfere with loading the accounts.
The cleaner way is to have a separate store for accounts and a separate store for balances and a derived store which merged both into accounts with balances. That way when we update a balance in the balances store, it will just automatically recreate the accounts with balances.
In this PR, I'm adding the derived `icpAccountsStore` which is derived from the `icpAccountDetailsStore` and the `icpAccountBalancesStore`. It is designed to be a drop-in replacement for the existing non-derived `icpAccountsStore` so it has the …
> NNS1-2857: Add derived icpAccountsStore

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/perf.rs
- rs/backend/src/periodic_tasks_runner.rs
- rs/backend/src/stats.rs
- scripts/nns-dapp/e2e-test-metrics-present.keys
Pre-migration to stable structures, we would like to de-risk by checking that assumptions about mainnet operation are correct:
- That the frequency of the upgrade counter is as expected; it could be run less frequently due to NNS subnet load.
- That stats are persisted across upgrades, not recomputed.
- Add a counter for the periodic tasks runner top the metrics.
- Add logging that states whether stats were re-computed or read from persisted state.
Note: These can both be deleted once the assumptions have been confirmed; they have no long term value.
- There is an existing test that checks that the expected metrics are exposed; the periodic task run counter has been added to the list of expected metrics.
- Not tested: That the counter increments and that the logging line actually logs. …
> feat: Timer counter

- CHANGELOG-Nns-Dapp-unreleased.md
- Dockerfile
The `dfx` installation procedure changed. This is breaking `./scripts/docker-build`.
In `Dockerfile`:
1. Add `/root/.local/share/dfx/bin` to `PATH`.
2. When installing `dfx`, set a new environment variable: `DFXVM_INIT_YES=true`
Ideally, in 1, we would like to say `${HOME}/` instead of hard-coding `/root/`. I will figure out whether that is possible later, and if it is, do a second PR. For now, we want to unblock things. One thing that is blocked is seeing whether the `upload-artifact` fixes were also applied to the `Reproducible` workflow.
These changes are indicated in the following places:
* [forum]: Here, other users experienced similar problems.
* [Slack]: Here, Eric Swanson advises us to make these changes.
[forum]: https://forum.dfinity.org/t/how-do-i-install-dfx-17-0-non-interactiv …
> Make dfx install again

- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/components/universe/SelectUniverseNav.svelte
- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseNav.spec.ts
- frontend/src/tests/page-objects/ActionableProposalCountBadge.page-object.ts
- frontend/src/tests/page-objects/SelectUniverseCard.page-object.ts
Load and display the actionable proposal count (APC).
- use `ENABLE_VOTING_INDICATION` flag in the `actionableProposalIndicationEnabledStore` to not pollute the components.
- load APC from `SelectUniverseNav`
- new `ActionableProposalCountBadge` component
- render APC on in `SelectUniverseCard` component
- `ActionableProposalCountBadge` page object
- `SelectUniverseCard` should display actionable proposal count
- `SelectUniverseCard` should not display actionable proposal count when no data
- `SelectUniverseNav` should load APC
Not yet
> Display actionable proposals

- .github/workflows/reproducible.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
- Dockerfile
We would like to report failures in reproducible docker builds in slack.
- Rename the title of the docker build workflow.
- At the time it was written there was only one reproducible builds test but now there are two, leading to confusion.
- Add a job to the workflow that checks that the other jobs complete successfully.  If not, it posts a message to slack.
Tested manually thus:
- Injected an error into the Dockerfile
- Forced the workflow to run (by pushing to a branch specified as a push trigger in the workflow)
- Observed:
- All 4 docker builds completed.  The docker build step did not bail out as soon as one build failed.  This is as before, is expected and desired.  If builds fail on one platform but succeed on others, this is useful information.
- The hash comparison job was …
> feat: Notify slack on failed reproduction

- frontend/src/lib/stores/icp-account-balances.store.ts
- frontend/src/tests/lib/derived/icp-accounts.derived.spec.ts
- frontend/src/tests/lib/stores/icp-account-balances.store.spec.ts
We are trying to replace `icpAccountsStore` with a store that's derived from `icpAccountDetailsStore` and `icpAccountBalancesStore`.
`icpAccountsStore` is currently a `queuedStore` which allows it to order queries and updates in the correct order such that old data does not override new data when a new query is made before an old update finishes.
I thought with the simplification brought be the refactoring we would no longer need to use queued stores here but on more careful consideration it will still be possible (especially in fast e2e tests) that an old balance result comes back after a new balance has been queried.
So the new `icpAccountBalancesStore` should also be a `queudStore` just like the old `icpAccountsStore`.
Change `icpAccountBalancesStore` to be a `queuedStore`.
See the …
> NNS1-2857: Make icpAccountBalancesStore a queued store

- frontend/src/tests/lib/derived/accounts-list.derived.spec.ts
This test fails with a refactoring that I'm doing.
But it's using an SNS account as an NNS account so this shouldn't work in the first place.
Use `mockSubAccount` instead of `mockSnsMainAccount` as the NNS subaccount used in `frontend/src/tests/lib/derived/accounts-list.derived.spec.ts`.
Still passes and like this also passes with the refactoring I have in another branch.
not necessary
> NNS1-2857: Use NNS subaccount in accounts-list.derived.spec.ts

- .github/workflows/reproducible.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
`uplaod-artifact@v4` contains a breaking change in the way artifacts are merged.  The [release notes](https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new) describe how to merge with v4.
- Update the way artefacts are merged
- Note: upload-artifact@v4 has a breaking change that forces this.
- Disable mac builders
- Mac builds are broken at the moment; this is being addressed.
- See CI.  I have added the working branch for this PR as a workflow trigger, so the workflow run can be seen there.
> fix: The reproducible workflow is no longer messed up because of breaking changes in the upload-artifacts step

- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
These 2 tests are identical, except that one has the setup inside the test and the other has the setup in the `beforeEach` before it:
https://github.com/dfinity/nns-dapp/blob/c2d47f25488e68194e9945c4873402937f0ae7d5/frontend/src/tests/lib/services/icp-accounts.services.spec.ts#L713
https://github.com/dfinity/nns-dapp/blob/c2d47f25488e68194e9945c4873402937f0ae7d5/frontend/src/tests/lib/services/icp-accounts.services.spec.ts#L398
The newest one was added in [this PR](https://github.com/dfinity/nns-dapp/pull/1969).
I checked with @lmuntaner and he confirmed that he probably wanted to remove the one in the `describe("services"`.
Remove the duplicate test.
removed
not necessary
> Remove duplicate syncAccounts test

- frontend/src/tests/lib/pages/NnsWallet.spec.ts
While testing reloading the balance when opening the wallet, I noticed that transactions were being loaded twice in certain cases.
One such case is when clicking "Finish" in the receive modal.
Surprisingly we had a test for this that didn't catch this.
It turned out the test finished before the additional transaction loading happened.
So I decided to improve the test.
We should fix the code to avoid the additional call but this PR only changes the test to demonstrates the current behavior before we fix it.
1. Change `pauseQueryAccountBalance` and `pauseGetTransactions` so it's allowed to pass a result when resolving the call.
2. Add a missing test that checks that we load (but not too often) balance and transactions when opening the wallet.
3. Update `"should reload account after finish …
> NNS1-2857: Make NnsWallet.spec.ts more realistic

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
Fix the issue of double transaction reloading discovered in https://github.com/dfinity/nns-dapp/pull/4581
Don't explicitly reload transactions when closing the receive modal because reloading the balance also results in reloading transactions.
1. Change the test to expect the transactions to be reloaded only after the balance has reloaded.
2. Expect no additional calls to `getTransactions` like there were before.
> NNS1-2857: Fix double reloading of transactions

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/derived/icp-accounts.derived.ts
- frontend/src/lib/services/dev.services.ts
- frontend/src/lib/types/account.ts
- frontend/src/tests/lib/derived/icp-accounts.derived.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/mocks/icp-accounts.store.mock.ts
Feature flag `ENABLE_ICP_ICRC` was added to display ICRC-1 account identifiers for ICP accounts instead of ICP account identifiers.
But we never figured out a good way to still also access the ICP account identifier, which would be necessary because transactions to/from are ICP account identifiers.
Since we haven't done anything with this for 8 months, it's better to just remove it as it's slowing down development.
1. Remove logic conditional on `ENABLE_ICP_ICRC` (added in https://github.com/dfinity/nns-dapp/pull/2917)
2. Remove type `IcpAccount` which was added for this purpose in the same PR.
Removed and updated.
> Remove ENABLE_ICP_ICRC functionality

- dfx.json
> Update didc release to 2024-02-27

- frontend/package-lock.json
ic-js [2024.03.05-1130Z](https://github.com/dfinity/ic-js/releases/tag/2024.03.05-1130Z) has been released. This PR bumps NNS-dapp with the `next` versions that have been released after publication. 
- bump ic-js dependencies
> Upgrade next version following ic-js release

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-02-28_23-01+p2p-hotfix

- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/lib/services/actionable-sns-proposals.services.ts
- frontend/src/lib/stores/actionable-sns-proposals.store.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
- frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-vote-registration.services.spec.ts
- frontend/src/tests/lib/stores/actionable-sns-proposals.store.spec.ts
Currently, we store `undefined` for the snses w/o ballots support, which is totally enough to display proposal count.
This pr adds a flag `includeBallotsByCaller: bool` (returned by `listProposals` call) to the `actionableSnsProposalsStore`, allowing it to be used later to determine which message needs to be displayed:
- `undefined` - data has not been loaded yet
- `{ includeBallotsByCaller: true, proposals: [] }` - no actionable proposals
- `{ includeBallotsByCaller: false, proposals: [] }` - actionable proposals not supported
- rename method `setProposals` to `set`
- add `includeBallotsByCaller` to the `actionableProposalsStore`
Instead of `[rootCanisterId]: undefined`, sns w/o ballots support well be stored as `[rootCanisterId]: { proposals: [], includeBallotsByCaller: false }`
- …
> Add "includeBallotsByCaller" to actionable sns proposals store

- frontend/src/tests/e2e/accounts.spec.ts
- frontend/src/tests/e2e/canisters.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
We want to enable ENABLE_ICP_INDEX. A few end-to-end tests require minor changes to continue passing.
1. Enable ENABLE_ICP_INDEX in those e2e tests that require changes to pass.
Pass
not necessary
> NNS1-2904: Enable ENABLE_ICP_INDEX in relevant e2e tests

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/tests/page-objects/jest.page-object.ts
- frontend/src/tests/utils/timers.test-utils.ts
While cleaning up a test in another branch, I discovered that `userEvent.selectOption` doesn't work when fake timers are enabled.
I found a work-around here: https://github.com/testing-library/user-event/issues/833
```
userEvent.setup({ advanceTimers: jest.advanceTimersByTime })
```
It also seems that `vitest` does not expose a way to test if fake timers are enabled, but fake timers specific method throw if fake timers are not enabled so this can be used to detect if fake timers are enabled.
1. Add a function `areFakeTimersEnabled` to check if fake timers are enabled.
2. If fake timers are enabled, use the work-around to use `userEvent.selectOption` in `JestPageObjectElement.selectOption`.
Used in another branch to stop a test from timing out after enabling fake timers.
> Make selectOption work when fake timers are enabled

- CHANGELOG-Nns-Dapp-unreleased.md
- CHANGELOG-Nns-Dapp.md
- Cargo.lock
- Cargo.toml
- frontend/package-lock.json
- frontend/package.json
A release has been deployed to production.
- Changelog - split out the changes included in the release + [custom fix entry](https://github.com/dfinity/nns-dapp/pull/4609/files#diff-9d543e5d87a67ec57eb53931d029ba6ce9b0aa358aea50f2e61c928f5f51253eR30).
- Increment the patch version of the nns-dapp.
> Update changelog after release

- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/lib/services/actionable-sns-proposals.services.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
- frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
- frontend/src/tests/page-objects/SelectUniverseCard.page-object.ts
Display a tiny indicator next to Snses that don't support actionable proposals.
Currently not visible on mobile because of using the same colours. Will be fixed in a separate pr.
- change the loading order for actionable sns proposal list:
- from: fetch neurons, when some neurons fetch proposals
- to: fetch proposals, when ballots support fetch neurons
- new derived store `actionableProposalSupportedStore`;
- display `"not-supported-badge"`, when `actionableProposalSupportedStore[canisterId] === false` ;
- SelectUniverseCard should display no-support indicator
Not yet
| 🌞 | 🌚 |
| <img width="280" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/3f181a74-2827-4772-8cc5-2c1b221294a2"> | <img width="272" alt="image" …
> Display actionable not supported indicator

- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/nns-dapp.did
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/proxy/migration.rs
- rs/backend/src/accounts_store/schema/proxy/tests.rs
- rs/backend/src/main.rs
- rs/backend/src/periodic_tasks_runner.rs
If there are several sequential large accounts, migration may fail to move that batch of accounts to stable memory in one call and the migration step will be rolled back.  The migration will keep trying and keep failing.  As transactions are also processed by the periodic runner, transactions would also be rolled back and be stalled permanently until we upgrade.  While fairly unlikely given the conservatively small number of accounts migrated in every step, it is still an unnecessary risk.
- Run migration separately from transactions, in a way that does not cause transactions to fail if migration fails.
- This is done by adding an API method to perform a migration step.  That method is called on the canister itself.  That way, if the migration step panics the periodic task can handle the …
> feat: Async migration

- rs/backend/src/accounts_store/schema/proxy.rs
When migrating, the logs include two lines for ever migration step.  One is intentional, the other isn't.
```
2024-03-13 10:00:31.083847515 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] Stepping migration: UnboundedStableBTreeMap(AccountsDbAsUnboundedStableBTreeMap { accounts: StableBTreeMap{.. 1000 entries} }) -> Map(AccountsDbAsMap{... 920 entries})
2024-03-13 10:00:31.083847515 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] AccountsDb::Proxy: authoritative schema label: AccountsInStableMemory
2024-03-13 10:00:31.699877773 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] Stepping migration: UnboundedStableBTreeMap(AccountsDbAsUnboundedStableBTreeMap { accounts: StableBTreeMap{.. 1000 entries} }) -> Map(AccountsDbAsMap{... 940 entries})
2024-03-13 10:00:32.317025421 UTC: [Canister …
```
> fix: Log less

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- config.sh
- rs/backend/src/accounts_store/schema.rs
- scripts/nns-dapp/test-config-assets/app/arg.did
- scripts/nns-dapp/test-config-assets/local/arg.did
- scripts/nns-dapp/test-config-assets/mainnet/arg.did
We would like to move accounts to stable structures.
- Make accounts in stable memory the default.  On deployment, this will start a migration.
- See CI
> feat: Migrate to stable structures

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- config.sh
- rs/backend/src/accounts_store/schema.rs
- scripts/nns-dapp/test-config-assets/app/arg.did
- scripts/nns-dapp/test-config-assets/local/arg.did
- scripts/nns-dapp/test-config-assets/mainnet/arg.did
This reverts commit 2e5ad13919b135276e55e25f2791b0672117f648.
Tests with 250,000 accounts show no transactions.  I am not sure why this is.  This release also includes the switch to the transactions index canister.  @georgi-dfinity suggests making these two major changes in separate releases.
- Switch back to using Map as the account storage schema.
- See CI
- The changelog entry actually gets reverted :-)
> Revert "feat: Migrate to stable structures (#4598)"

- dfx.json
> Update snsdemo to release-2024-03-13

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/modals/accounts/CkBTCTransactionModal.svelte
- frontend/src/tests/lib/components/accounts/CkBTCWalletFooter.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
When sending BTC directly from the "My Tokens" table, the amount input field shows an error (unless you've previously visited the ckBTC wallet page):
This is because the `CkBTCTransactionModal` assumes that the minter info is already loaded, but this only happens on the ckBTC wallet page.
Load the minter info in the CkBTCTransactionModal if it isn't already loaded.
1. Extend the existing unit test that tests that the amount can't be lower than the minimum amount to verify that the minimum amount corresponds to what's already in the minter info store.
2. Add an additional unit test that tests that the minter info is loaded from the API if not present in the store.
> Load ckBTC info in CkBTCTransactionModal

- .github/workflows/build.yml
- rs/backend/src/state.rs
There is a bug:
- In the pre-upgrade hook, we check the current schema and save state accordingly.  That is fine.
- But we determine the schema by looking at the stable memory, not by checking which schema is currently in use.
- When migrating from the heap to stable structures, the stable structures are written to stable memory, so this gives the correct result IF migration has completed.
- But when migrating from stable structures to map, the migration completes correctly, but then in the `pre_upgrade` hook we look at the stable memory, which is still set up for stable structures, and say "oh, save to stable structures".  This not only un-does the migration but also loses any data added after the migration was completed.
- It also gives the incorrect result part way through a migration …
> fix: Store using the correct schema when migrating from stable memory to map

- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
- frontend/src/lib/pages/SnsProposals.svelte
- frontend/src/tests/lib/components/proposals/NnsProposalsFilters.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsList.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
- frontend/src/tests/page-objects/SnsProposalFilters.page-object.ts
- frontend/src/tests/page-objects/SnsProposalList.page-object.ts
Display actionable proposals on sns proposals page. Current proposal filters should not be available when actionable proposals are selected. More states (not supported, sign-out, empty) will be implemented in a separate PR.
- add actionable segment to sns proposals page
- switch between all and actionable based on segment state
- actionable segment in SnsProposalsFilters
- add `SnsProposalListPo`
- actionable list on sns proposals page
Not yet.
> Display actionable sns proposals

- frontend/src/lib/constants/stores.constants.ts
- frontend/src/lib/stores/hide-zero-balances.store.ts
- frontend/src/lib/stores/writable-stored.ts
- frontend/src/tests/lib/stores/hide-zero-balances.store.spec.ts
- frontend/src/tests/lib/stores/writable-stored.spec.ts
We want to add a setting to hide tokens with zero balance.
We want this setting to persist. For now we will persist it locally in the browser.
1. Add a store `hideZeroBalancesStore` to store the setting to hide tokens with zero balance.
2. Add `resetForTesting` functionality to `writableStored`.
1. Unit tests for `hideZeroBalancesStore`.
2. Unit test for `resetForTesting`.
not necessary
> NNS1-2918: Add hideZeroBalancesStore

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-03-14_23-01-p2p

- frontend/src/lib/components/tokens/TokensTable/HideZeroBalancesToggle.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/tokens/TokensTable/HideZeroBalancesToggle.spec.ts
- frontend/src/tests/page-objects/HideZeroBalancesToggle.page-object.ts
We want to add a setting to hide tokens with a zero balance.
We're adding a settings button in the top right of the tokens table.
This button will open a popup with a toggle.
This PR adds the component that will be used as the content inside this popup.
Add `HideZeroBalancesToggle` component to be used inside the settings popup.
Added unit test for the component.
Here's what the component will look like in context:
not yet
> NNS1-2918: Add HideZeroBalancesToggle component

- frontend/src/lib/components/proposals/ActionableProposalsEmpty.svelte
- frontend/src/lib/components/proposals/ActionableProposalsSignIn.svelte
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/page-objects/NnsProposalList.page-object.ts
- frontend/src/tests/page-objects/PageBanner.page-object.ts
Display more information when a user attempts to view actionable proposals without being logged (Screenshot 1.) in or when no actionable proposals are available for voting (Screenshot 2.).
- [move "all proposals" related blocks](https://github.com/dfinity/nns-dapp/pull/4632/files#diff-1fb3bd8ea562ad07e519536414b00eec641a7271994ed0f75c546432e08cd8dcL63) (loading and no-proposals) under `all-proposal-list` to have the same structure.
- replace ListLoader with LoadingProposals for actionable
- new banner components (`ActionableProposalsEmpty` and `ActionableProposalsSignIn`)
- 
- create PageBannerPo
- extend NnsProposalListPo with banners
- move actionable selection in a separate function to avoid code duplication [`selectActionableProposals`](https://github.com/dfinity/nns-dapp/pull/4632/fil …
> Actionable nns proposal banners

- frontend/src/lib/pages/Tokens.svelte
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/TokensPage.page-object.ts
We want to add a settings to hide tokens with a zero balance.
In this PR we open the popup with the toggle when the settings button is clicked.
1. And the `Popover` component to the `Tokens` page.
2. Open the `Popover` when the settings button is clicked.
Add unit tests for opening and closing the popup.
not yet, still not functional and behind the feature flag
> NNS1-2918: Show setting popup when settings button is clicked

- frontend/src/tests/workflows/Launchpad/ProdLaunchpad.spec.ts
We have a copy of (the 3 pages of) the prod sns aggregator data here: https://github.com/dfinity/nns-dapp/tree/main/frontend/src/tests/workflows/Launchpad
We use this in `ProdLaunchpad.spec.ts` to test that we can correctly parse the prod SNS data.
We also have a weekly job to keep this data up-to-date.
The [most recent update PR](https://github.com/dfinity/nns-dapp/pull/4641) caused `ProdLaunchpad.spec.ts` [to fail](https://github.com/dfinity/nns-dapp/actions/runs/8369291084/job/22914793727?pr=4641).
This is because if an SNS was closed less than a week ago, we try to fetch its finalization status and this call was not mocked. And this is the first time since the automatic update job was added that SNSes (ICLighthouse DAO and ELNA AI) were completed.
Mock `queryFinalizationStatus` in …
> Mock queryFinalizationStatus in ProdLaunchpad.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/tests/lib/pages/Tokens.spec.ts
This PR actually hides the tokens with zero balance based on the setting added in previous PRs.
If the toggle to hide tokens with zero balance is selected, filter tokens based on balance (and always show ICP).
Unit tests were added.
> NNS1-2918: Hide tokens with zero balance

- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/TokensPage.page-object.ts
We have a setting to hide tokens with a zero balance.
To avoid confusion we want to show a button to show all tokens if the setting is enabled:
When zero balance tokens are hidden, show a bottom row with message and button to show all tokens again.
covered by existing entry
> NNS1-2918: Button to show all tokens when zero balances are hidden

- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
Avoid rendering of the actionable count on neurons page.
- do not render badges when `actionableProposalIndicationEnabledStore` contains false.
- add `cleanup` and `runResolvedPromises` to `renderComponent`
- "should not display actionable proposal count when not on neurons page"
Not necessary
> fix: hide actionable badges on neuron page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/derived/tokens-list-visitors.derived.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-visitors.derived.spec.ts
- frontend/src/tests/mocks/tokens-page.mock.ts
Token table rows are `<a>` tags most of the time but in some cases (when token data or account details are still loading) we don't provide an `href` and make the element a `<div>`.
But there is no reason we can't provide an `href` in those cases as well.
And if we do the code is simpler and the rows are always clickable.
An additional benefit is that if every row has a unique `href` we could use this as key in the `{#each}` which would be necessary to provide smooth transitions when hiding zero balance tokens.
1. Make `rowHref` mandatory on `UserTokenLoading` and `UserTokenData`.
2. Make sure `rowHref` is always provided.
3. Make the row always an `<a>` tag.
First I provided `rowHref` in all the tests as required by the compliler.
Then I replaced the newly provided `rowHref` value with …
> Make rowHref on token data non-optional

- frontend/src/lib/components/proposals/ActionableProposalsNotSupported.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/SnsProposals.svelte
- frontend/src/lib/stores/actionable-sns-proposals.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsList.spec.ts
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
- frontend/src/tests/page-objects/SnsProposalList.page-object.ts
We want to display different state banners to provide more information when:
- user is not logged in
- Sns has no ballots support by governance canister
- there is nothing to vote for in selected Sns.
- New banner `ActionableProposalsNotSupported`
- Update SnsProposalList
- rename `isActionable` to `actionableSelected`
- new prop `includeBallots` to control not-supported banner visibility
- remove `ListLoader` because skeletons are enough and there is no pagination
- display banners
- reorganised parameters in `SnsProposals` component (`proposals` is generated sooner to not avoid sorting for actionable)
- updated props in `SnsProposalList` and remove skeleton test (already available in `SnsProposals`)
- banners visibility in `SnsProposals`
Not yet
> Actionable sns proposal banners

- frontend/src/lib/pages/Tokens.svelte
For the tokens settings button I used `@include header.button` to make sure there is some indication when you tab to or click on the button.
But this also adds some padding and margin which makes it look misaligned with the rest of the table.
Use some styles from [@include header.button](https://github.com/dfinity/gix-components/blob/fed837c2fd163048c397e8214b39f477589c3a15/src/lib/styles/mixins/_header.scss#L5) directly without using the margin and padding.
Before:
After:
covered by existing entry
> NNS1-2918: Fix alignment of settings button

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/utils/transition.utils.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/lib/utils/transition.utils.spec.ts
- frontend/src/tests/mocks/tokens-page.mock.ts
When hiding zero balance tokens without transition, the change is very jumpy and it can be disorienting.
Adding a transition makes it obvious what's happening.
Unfortunately the existing transition such as `fade` and `scale` don't look nice.
PS. It turns out that `slide` is close to what I was looking for and I could probably have used that. But it doesn't do the additional scaling, which I think makes it look nicer.
1. Add a new custom transition `heightTransition` which squeezes the element vertically.
2. Use the transition on token table rows and on the row with the "Show all" button.
3. Use `rowHref` as a uniq string key for row in the `{#each}`. A uniq key per element is required when using transitions.
4. Automatically add `rowHref` (based in `universeId`) in `createUserToken` for …
> NNS1-2918: Add a transition when hiding zero balance tokens

- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
- frontend/src/lib/types/actions.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
When the user clicks on a token row, we dispatch an event with type `ActionType.GoToTokenDetail`.
But there is nothing that responds to this event.
This is not a problem because the token row is a link and the intended navigation happens through the link `href` without the need to dispatch an event.
1. Remove the click handler and code to dispatch this event.
2. Remove the event type.
1. Remove the corresponding test.
not necessary
> Remove unused GoToTokenDetail action type

- frontend/package-lock.json
ic-js [2024.03.25-1345Z](https://github.com/dfinity/ic-js/releases/tag/2024.03.25-1345Z) and patch [2024.03.25-1430Z](https://github.com/dfinity/ic-js/releases/tag/2024.03.25-1430Z) were released. This PR bumps the libraries to follow their next version numbers.
- `npm run upgrade:next` executed
> build: bump ic-js after release

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
In order to have timestamps consistent with the dashboard, we need to use [this](https://github.com/dfinity/ic/blob/03de843e2a01f57a8fb5c2ef928e91574396f6c5/rs/rosetta-api/icp_ledger/index/index.did#L61) instead of [this](https://github.com/dfinity/ic/blob/03de843e2a01f57a8fb5c2ef928e91574396f6c5/rs/rosetta-api/icp_ledger/index/index.did#L60).
Use the `timestamp` field if available and fall back on the `created_at_time` field otherwise.
Unit test added and tested manually.
Also tested that it doesn't break with an older version of the index canister that doesn't have the `timestamp` field.
> NNS1-2987: Display block timestamp in transaction history

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
We removed the requirement to depend on protocol buffers for hardware wallet transactions from ic-js.
The actual removal of the nns-proto dependency will be done in a separate PR to keep this PR clean.
But the effect is present with this PR as it reduces the compressed WASM size by ~80KB.
Run `npm upgrade:next`
Manually tested that the following still work with hardware wallet:
* transfer
* listNeurons
* increaseDissolveDelay
* startDissolving
* stopDissolving
* disburse
* spawnNeuron
* addHotkey
* removeHotkey
The following don't seem to be available in the NNS dapp UI so I didn't test them manually:
* joinCommunityFund
* mergeMaturity
> NNS1-2887: Bump: ic-js (proto dependency removal)

- frontend/package-lock.json
- frontend/package.json
- frontend/vite.config.ts
`@dfinity/nns-proto` is no longer required as a peer dependency for `@dfinity/ledger-icp` and `@dfinity/nns`.
Remove all remaining references to `nns-proto` from `nns-dapp`.
1. Ran `npm uninstall @dfinity/nns-proto`
2. Removed `@dfinity/nns-proto` from npm `update:agent` and `upgrade:next` commands.
3. Removed handling of `@dfinity/nns-proto` from chunking configuration.
Tested manually that hardware wallet operations still work.
covered
> NNS1-2887: Remove dependency on @dfinity/nns-proto

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/components/layout/UniverseSplitContent.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/components/universe/SelectUniverseNav.svelte
Update style for project selector on mobile to provide more space for the content. A first step to the new split content design. Uses changes of `gix-component` pr - https://github.com/dfinity/gix-components/pull/403
- add `noMarginBottom` to remove bottom margins. To avoid stretching of a SplitContent start block on mobile.
- redefine some `SplitContent` css values.
Manually.
| <img width="326" alt="image" src="https://github.com/dfinity/gix-components/assets/98811342/bf644db9-ae48-4ab1-a429-500ac6fa2f96"> | <img width="310" alt="image" src="https://github.com/dfinity/gix-components/assets/98811342/46c6e7ef-d428-46de-ac4a-3b932f8a3819"> |
|
> style: dropdown changes

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/identities/ledger.identity.ts
- frontend/src/tests/lib/identities/ledger.identity.spec.ts
In the past, when using a Ledger hardware wallet, you always had approve twice because the read_state call had to be signed separately.
Then functionality was added such that both requests could be signed with a single approval.
But there was a bug in the neuron staking flow so just neuron staking still required 2 approvals.
This was fixed in the Ledger app at some point.
So now that we always require version 2.4.9 of higher, we don't need to ask for double approval anymore and also don't need to have this depend on the Ledger app version.
Remove the special case for neuron staking and just always sign the read_state request together with the call request.
Unit test was adjusted.
Also tested manually.
> Don't sign read-state separately for HW neuron staking

- .github/workflows/reproducible-assets.yaml
- CHANGELOG-Nns-Dapp-unreleased.md
Our asset builds on MacOS 13 started to result in different hashes from the same build on other OSes.
It turned out that while the `.tar.xz` files were different, the `.tar` files were identical.
Looking at the versions, I discovered that on MacOS 13, GitHub gives us version 5.6.1 of xz by default.
This version is actually compromised. See https://nvd.nist.gov/vuln/detail/CVE-2024-3094
By running `brew install xz` we actually downgrade to version 5.4.6, which produces the same hash as version 5.4.5 which we get by default on MacOS 12.
Run `brew install xz` when running on MacOS before building the frontend in `reproducible-assets.yaml`.
The reproducible assets workflow passes again: https://github.com/dfinity/nns-dapp/actions/runs/8519799063/job/23334582917
> NNS1-2992: Install xz in reproducible-assets.yaml

- CHANGELOG-Nns-Dapp-unreleased.md
The feature flag for "hide tokens with zero balance" was added and enabled in the same release.
Having a change log entry for both is misleading.
Remove the changelog entry for the feature flag and just keep the entry (on line 18) for the feature itself.
n/a
> Remove duplicate changelog entry

- rs/backend/Cargo.toml
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema.rs
- rs/backend/src/accounts_store/schema/accounts_in_unbounded_stable_btree_map.rs
- rs/backend/src/accounts_store/schema/map.rs
- rs/backend/src/accounts_store/schema/proxy.rs
- rs/backend/src/accounts_store/schema/proxy/enum_boilerplate.rs
- rs/backend/src/accounts_store/schema/proxy/migration.rs
- rs/backend/src/accounts_store/schema/proxy/tests.rs
The security review recommended sanity checks before finalizing the migration.
- Verify that the following data is the same in the old and new databases before finalizing:
- The number of accounts
- The first and last accounts, ordered by key.
- Existing tests already perform migration, so exercise the happy path of these checks.
- The unhappy path is exercised by changing or removing an account that has already been migrated in one database but not another.
Please let me know if this is wanted.  So far the NNS team has seemed to prefer changelog entries only for user-visible changes.
> Pre completion check

- rs/backend/src/accounts_store/schema/proxy/tests.rs
As part of the security review with @roelstorms, it was considered that we probably want to increase the number of accounts used in randomized migration testing.
The number of accounts is a random number in the range 0..40.  If we migrate 20 accounts per step (increased from 10), half the time the entire migration is completed in one step.  (Plus a second step to point the switch at the new database.)  This gives insufficient opportunity for the test to find any bugs.
- Increase the number of accounts in randomized migration tests to a random number in the range 0..100.
- See CI
> Increase the number of acounts used in randomized tests

- frontend/src/tests/routes/app/wallet/page.spec.ts
When running test `routes/app/wallet/page.spec.ts`, the following appears in the output:
```
TypeError: id.transformRequest is not a function
at HttpAgent.call (/Users/dskloet/dev/nns-dapp/tree4/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:424:33)
at caller (/Users/dskloet/dev/nns-dapp/tree4/frontend/node_modules/@dfinity/agent/src/actor.ts:484:28)
at e.accountBalance (/Users/dskloet/dev/nns-dapp/tree4/frontend/node_modules/@dfinity/ledger-icp/dist/esm/chunk-OUNV42BS.js:4:13050)
at Module.queryAccountBalance (/Users/dskloet/dev/nns-dapp/tree4/frontend/src/lib/api/icp-ledger.api.ts:144:22)
at Module.queryAndUpdate (/Users/dskloet/dev/nns-dapp/tree4/frontend/src/lib/services/utils.services.ts:106:3)
```
However since this only happens after the test already passed, it's not …
> Mock queryAccountBalance in routes/app/wallet/page.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neuron-detail/NnsAvailableMaturityItemAction.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.svelte
- frontend/src/tests/lib/components/neuron-detail/NnsAvailableMaturityItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsStakedMaturityItemAction.spec.ts
- frontend/src/tests/page-objects/NnsAvailableMaturityItemAction.page-object.ts
- frontend/src/tests/page-objects/SnsStakedMaturityItemAction.page-object.ts
A tooltip appears when you hover over a tooltip target.
The tooltip target should have an `aria-describedby` attribute that matches the `id` attribute on the tooltip such that screen readers can associate the two.
And for this for work correctly, the `id` attribute has to be unique.
But I found some tooltip ID which were copied and not unique.
1. Fix the incorrectly copied tooltip IDs to match their context.
2. Add unit tests for the affected tooltip IDs.
3. Add getters on page objects where necessary.
Also, this was caught by another change where the page object getter actually depends on this ID and that caused some tests to fail and this fixed them.
> Fix copied tooltip IDs

- dfx.json
> Update snsdemo to release-2024-04-03

- frontend/src/tests/lib/components/ui/IdentifierHash.spec.ts
- frontend/src/tests/page-objects/Button.page-object.ts
- frontend/src/tests/page-objects/Hash.page-object.ts
- frontend/src/tests/page-objects/IdentifierHash.page-object.ts
To make the test easier to read and maintain.
1. Introduce `IdentifierHashPo`, extended from `HashPo` because the `IdentifierHash` component only consists of an instance of `Hash`.
2. Make `HashPo.TID` not private to reuse in `IdentifierHashPo`.
3. Use `IdentifierHashPo` in `IdentifierHash.spec.ts`.
4. Make expectations in the test more explicit so it's easier to understand what is really expected.
only test changes
not necessary
> Use page object in IdentifierHash test

- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/vitest.setup.ts
In `NnsWallet.spec.ts` in `"should render second page of transactions from ICP Index canister"` we set the global value of `IntersectionObserver` to `IntersectionObserverActive`. This is not being cleaned up so it is unintentionally affecting other tests.
The best way to clean up global value replacements is by always calling `vi.unstubAllGlobals` before each test.
However, currently another work-around in `frontend/vitest.setup.ts` is also set with `stubGlobal` and reverted by calling `vi.unstubAllGlobals`.
1. In `frontend/vitest.setup.ts` use `Object.defineProperty` instead of `vi.stubGlobal` to overwrite `requestAnimationFrame` so that we can safely use `vi.unstubAllGlobals` in tested.
2. In `frontend/src/tests/lib/pages/NnsWallet.spec.ts` use `vi.unstubAllGlobals` to make sure other …
> vi.unstubAllGlobals in NnsWallet.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/ui/IdentifierHash.svelte
- frontend/src/tests/lib/components/ui/IdentifierHash.spec.ts
Whenever we have a tooltip, the tooltip element must have a unique `id` attribute and the tooltip target must have a matching `aria-describedby` attribute to help screen readers associate the tooltip to the target.
Currently, the `IdentifierHash` component uses `identifier` as the `id` which is used for the corresponding tooltip.
When multiple `IdentifierHash` components are on the page (for example, the account identifier and the user principal), this `id` is not unique.
Attach a sequence number to the `id` in `IdentifierHash` to make it unique.
1. Add a unit test which instantiates `IdentifierHash` twice and checks that the tooltip IDs are different.
2. Don't reuse the same container in `render` so that we can have multiple components instances and corresponding page objects in a single …
> Use unique tooltip IDs in IdentifierHash

- frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/VestingTooltipWrapper.spec.ts
- frontend/src/tests/page-objects/DisburseMaturityButton.page-object.ts
- frontend/src/tests/page-objects/Hash.page-object.ts
- frontend/src/tests/page-objects/Tooltip.page-object.ts
- frontend/src/tests/page-objects/TooltipIcon.page-object.ts
- frontend/src/tests/page-objects/WalletPageHeading.page-object.ts
Currently `getText` on `TooltipPo` is masking the `getText` method from the base class.
Rename `getText` on `TooltipPo` to `getTooltipText`.
Still pass
not necessary
> Rename getText on TooltipPo to getTooltipText

- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/mocks/transaction.mock.ts
- frontend/vitest.setup.ts
`ENABLE_ICP_INDEX` has been enabled on mainnet for some time.
Before we can clean up the code, some tests need to be updated.
This is the feature flag to enable reading ICP transactions from the ICP index canister instead of from the NNS dapp canister.
1. Enable `ENABLE_ICP_INDEX` in unit tests.
2. Update unit tests that were still using the old functionality to use the new functionality instead.
Updated
not necessary
> Enable ENABLE_ICP_INDEX in unit tests

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
In the neurons view, we sort neurons by decreasing stake.
If they stakes are equal we want to sort by decreasing dissolve delay.
Change `sortNeuronsByStake` to take dissolve delay into account as a tie breaker.
* Unit tests added.
* Tested manually:
> Sort neurons by decreasing dissolve delay when stake is equal

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/layout/UniverseSplitContent.svelte
Titles currently aren't aligned because of this unnecessary margin.
Remove the top margin in `UniverseSplitContent`.
Tested manually:
Before:
After:
> Remove top margin in UniverseSplitContent

- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronListItem.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronListItem.spec.ts
- frontend/src/tests/page-objects/VotingNeuronListItem.page-object.ts
The `VotingNeuronSelectList` has a list of items, one for each neuron.
To make it easier to test these items in isolation, we make a separate component for the item.
Create a new `VotingNeuronListItem` component and use it in `VotingNeuronSelectList` instead of rendering the items directly in the list.
Unit test added for the new `VotingNeuronListItem` component.
Unit test for `VotingNeuronSelectList` continue to pass.
not necessary
> Split VotingNeuronListItem from VotingNeuronSelectList

- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronSelectList.spec.ts
- frontend/src/tests/page-objects/VotingNeuronListItem.page-object.ts
- frontend/src/tests/page-objects/VotingNeuronSelectList.page-object.ts
Making the test easier to read and maintain.
Also 2 tests are nonsense and are deleted. These tests assume that the component shows a sum of voting powers but `VotingNeuronSelectList` doesn't do that at all. The sum of selected voting powers is rendered in `VotableNeuronList` instead.
`"should not display total voting power of neurons"` tests that the total voting power of neurons (as opposed to the total voting power of ballots) is not displayed. But neither is displayed so obviously this passes but it's meaningless.
`"should recalculate total voting power after selection"` doesn't test anything because the only expectation in the test is an async expectation that's not awaited. If `await` is added to the test, the test fails because the component doesn't render any sum of voting powers. …
> Use page objects in VotingNeuronSelectList

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-04-03_23-01-base

- rs/backend/src/state/partitions.rs
- rs/backend/src/state/partitions/schemas.rs
Partitions SHOULD always have the `schema_label` populated in virtual stable memory.  `Partitions::from(..)` does not write such a  label, relying instead on later code to populate it.  This is an unnecessary risk.
- If `Partiitions::from(..)` creates a memory manager, it should also populate a schema.  Presumably the default schema.  Given that neither of the two places that call `Partitions::from()` would benefit from this code, this seems not the best way to proceed.
- Given that `Partitions::from()` is a tiny function, a simple two-liner, and used only internally in two places it seems best to simply delete it.  Furthermore the two lines are likely to be reduced to one line once we move to the next version of the stable structures library.
- Delete `Partitions::from(memory)`
- None. …
> security: Make it hard to create partitions without a schema label

- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
1. Use `NnsNeuronsPo` in `NnsNeurons.spec.ts`.
2. Add a missing test that it's also possible for the "empty" message not to be displayed.
only tests
not necessary
> Use page objects in NnsNeurons.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/NnsWallet.svelte
`ENABLE_ICP_INDEX` is enabled on mainnet and in tests so the negative code path is not used anymore.
Remove the conditionals on `ENABLE_ICP_INDEX` and only keep the branch where `ENABLE_ICP_INDEX` is true.
All the code that becomes unused as a result will be cleaned up in future PRs.
Still pass
> NNS1-2906: Remove the code path for when ENABLE_ICP_INDEX is disabled

- frontend/src/tests/lib/components/sns-proposals/SnsProposalsList.spec.ts
- frontend/src/tests/lib/components/ui/IdentifierHash.spec.ts
- frontend/src/tests/lib/components/ui/ProposalStatusTag.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
- frontend/src/tests/utils/svelte.test-utils.ts
When you call Svelte `render` multiple times within the same test, it renders both components into the same container.
We recently discovered this through some very surprising test behavior.
Our first solution was to always call `cleanup` before rendering.
This empties the container first, which makes sure that the previous render does not interfere with the new one.
But it doesn't allow you to access both components at the same time.
A better solution is to render each component into a separate container.
Add a custom render function which creates a new container for each invocation.
Use the custom render function in places that were working around the issue.
not necessary
> Custom render function for testing, which doesn't reuse the container

- frontend/src/lib/components/ic/VotingPowerDisplay.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotableNeuronList.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotingNeuronListItem.svelte
- frontend/src/tests/lib/components/ic/VotingPowerDisplay.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotableNeuronList.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronListItem.spec.ts
- frontend/src/tests/page-objects/Tooltip.page-object.ts
- frontend/src/tests/page-objects/VotableNeuronList.page-object.ts
- frontend/src/tests/page-objects/VotingNeuronListItem.page-object.ts
- frontend/src/tests/page-objects/VotingPowerDisplay.page-object.ts
In 2 different places we display rounded voting power with a tooltip for the exact amount.
We want to do this in even more places.
So in this PR I factored out a component for this to reuse.
1. Add `VotingPowerDisplay` component which displays rounded voting power and has a tooltip with exact voting power.
2. Use this in `VotableNeuronList` and `VotingNeuronListItem` instead of duplicating the code.
Added unit tests for `VotingPowerDisplay` and adapted existing unit test for the new structure.
not necessary
> Component to display voting power with tooltip

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/nns-dapp.did
- rs/backend/src/accounts_store.rs
- rs/backend/src/main.rs
The nns-dapp frontend now reads ICP transactions from the ICP index canister.
It no longer needs to read transactions from the nns-dapp canister and we want to clean up the canister code.
In this PR we only remove the possibility to get transactions from the nns-dapp canister. We don't remove the data yet so that it's easy to revert if for whatever reason this causes problems.
Remove the `get_transactions` method from the nns-dapp canister.
Existing unit tests, test the method on the account store, which still exists.
> NNS1-2905: Remove get_transactions method from nns-dapp canister

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
We are going to change some topics and proposal types and want to make sure the users are informed.
Add a message linking to the forum post on top of the neurons page for users who have neurons.
Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
> NNS1-3004: Message informing about topic renames

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/launchpad/ProjectCard.svelte
Align launchpad card content to shift blocks after the description down.
- css
Manually.
> style: align launchpad card text

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/layout/UniverseSplitContent.svelte
- frontend/src/lib/components/proposals/NnsProposalsFilters.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/components/universe/SelectUniverseNav.svelte
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
Improve mobile styles of sns selector.
- Move `--nav-component-title-display` to have both hide-title-on-mobile and add a gap when not title in one place.
- Add extra gap before Sns mobile selector.
- Increase the gap between actionable segment and filter buttons.
- Remove selected icon from Sns dropdown (there is still a border shown for the selection) (second screenshot).
| <img width="382" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/86276cdd-10f9-4d99-a19d-d53cfc7e601d"> | <img width="380" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/6223a07d-171e-488c-97c9-b0e063ce8ddd"> | 
| <img width="379" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/5c77f955-8f5a-447b-9 …
> Sns selector style adjustments for mobile

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/Launchpad.svelte
Reorder launchpad sections to be the same on mobile and desktop:
1. Proposals
2. Upcoming (hidden if no upcoming)
3. Current launches
4. Launched
- change section order
- remove obsolete styles
- (Manu|Loc)ally
| Mobile | Desktop |
| <img width="390" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/05092df4-ce06-4f3d-afdb-4b8536948b26"> | <img width="1261" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/33faca84-df29-4c8d-89c6-c8f6f9be2562"> |
> Reorder launchpad sections

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/pages/Launchpad.svelte
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
Order ICP subaccounts based on balance from high to low. Always have “Main” on top.
- new util `sortUserTokens`
- sort subaccounts in `icpTokensListUser` derived store (the store is used only in one place - icp accounts page)
- `sortUserTokens`
- `icpTokensListUser` store should sort user tokens
> Order icp subaccounts

- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/lib/components/ui/ProposalStatusTag.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsList.spec.ts
- frontend/src/tests/lib/components/ui/ProposalStatusTag.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/page-objects/ProposalStatusTag.page-object.ts
Add a tooltip when hovering over the blue dot that appears for actionable proposals.
Copy to read: “You can still vote on this proposal.”
- Make the dot a separate DOM element to have anything to wrap with the tooltip.
- Add a tooltip.
- Add a simple initial animation.
- 📜 Side quest: added `role="status"` to the actionable count badge.
- Extend PO to get the tooltip.
- Tooltip is presented.
not necessary
> Tooltip to voting cards for the blue dots

- frontend/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/src/tests/lib/modals/neurons/FollowNeuronsModal.spec.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
- frontend/src/tests/routes/app/wallet/page.spec.ts
Some of our tests produce output like this:
```
TypeError: id.transformRequest is not a function
at HttpAgent.call (/Users/dskloet/dev/nns-dapp/tree9/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:424:33)
at caller (/Users/dskloet/dev/nns-dapp/tree9/frontend/node_modules/@dfinity/agent/src/actor.ts:484:28)
at getTransactions (/Users/dskloet/dev/nns-dapp/tree9/frontend/node_modules/@dfinity/ledger-icp/dist/esm/chunk-SUVDEL6N.js:3:3602)
at Module.getTransactions (/Users/dskloet/dev/nns-dapp/tree9/frontend/src/lib/api/icp-index.api.ts:35:37)
at Module.loadIcpAccountTransactions (/Users/dskloet/dev/nns-dapp/tree9/frontend/src/lib/services/icp-transactions.services.ts:23:42)
at reloadTransactions (/Users/dskloet/dev/nns-dapp/tree9/frontend/src/lib/pages/NnsWallet.svelte:1245:3) …
```
> Fix confusing test output caused by missing mocks

- .cargo/config.toml
- .github/workflows/checks.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store/schema/proxy/tests.rs
- rs/backend/src/state/partitions.rs
Build warnings are distracting and confusing.
There is one type of build warning that can start appearing without any changes in the code: future incompatibility.
When there is a breaking change in a future version of a dependency, this will start causing build warnings without changes in the repository. We need to disable these warning in order to safely disallow any build warnings in Rust and prevent the introduction of new warnings.
1. Add `RUSTFLAGS="-D warnings"` in front of `cargo test` in CI to disallow build warning.
2. Disable the "future incompatibility" warning by adding a `config.toml` file.
3. Fix a warning by removing unused `use candid::types::number;` from `rs/backend/src/accounts_store/schema/proxy/tests.rs`.
4. Fix a warning by removing unused `schema_label` from …
> Disallow build warnings for Rust

- Cargo.lock
- rs/backend/Cargo.toml
`rs/backend/Cargo.toml` has an explicit dependency on `chrono` version 0.4.19.
But no code in nns-dapp depends directly on `chrono` (nor did it when the dependency was added).
Removing the explicit dependency does not seem to break anything.
If I increase the explicit dependency to 0.4.20 (or higher), I do get the error from the comment but not if I just remove it.
And having the dependency prevents us from updating other dependencies which require different versions of `chrono`.
1. Remove the `chrono` dependency from `rs/backend/Cargo.toml`.
CI passes
not necessary
> Remove explicit chrono dependency

- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
Ignore the "show only votable" flag when "actionable proposals" enabled (because the checkbox is hidden).
- update the filtering util function to ignore the filter selection when actionable proposals feature is enabled.
- updated.
Not necessary
> Ignore exclude voted proposals filter

- dfx.json
> Update didc release to 2024-04-11

- rs/backend/src/accounts_store/histogram.rs
- rs/backend/src/accounts_store/histogram/tests.rs
- rs/backend/src/accounts_store/tests.rs
We no longer read transactions from the nns-dapp canister, but from the index canister instead.
We want to remove the transactions from nns-dapp canister so we need to remove all the code that is still using the transactions.
https://github.com/dfinity/nns-dapp/pull/3273 added a method to get histogram stats about the accounts stored in nns-dapp. Some of the histograms are about transactions. When we remove the transactions, we no longer can or need to include transaction stats in the histogram.
Remove transaction stats from the histogram.
Removed tests specific to transactions in histograms.
not necessary
> NNS1-2905: Remove transactions from histogram

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
We no longer read transactions from the nns-dapp canister, but from the index canister instead.
We want to remove the transactions from nns-dapp canister so we need to remove all the code that is still using the transactions.
Staking a neuron used to involve 2 ledger transactions:
1. Transferring the stake to the neuron account.
2. Transferring 0 ICP to the neuron account with a memo pointing to the previous transaction.
The second transaction would prompt the nns-dapp to claim the neuron.
But this is no longer how neurons are staked.
The second transaction would have transaction type `StakeNeuronNotification`.
Detecting this transaction type requires looking at previous transactions.
Because we want to remove the transactions from the nns-dapp canister, we can no longer do this.
1. Treat …
> NNS1-2905: Stop detecting StakeNeuronNotification transactions

- rs/backend/src/accounts_store.rs
We no longer read transactions from the nns-dapp canister, but from the index canister instead.
We want to remove the transactions from nns-dapp canister so we need to remove all the code that is still using the transactions.
At some point in the past, transactions didn't have a transaction type.
New transactions were assigned a type and there was also code in place to fix old transactions for old users once they logged in.
We want to stop storing the transactions so we no longer need to care about fixing the type of a few very old transaction.s
1. Stop calling `fix_transactions_for_early_user` and remove resulting unused code.
2. Mark `get_transaction` which is no longer used, but is still used in a test (that will be deleted in another PR) as test-only.
Still pass
not necessary
> NNS1-2905: Stop fixing old transactions

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/toy_data.rs
- scripts/nns-dapp/migration-test
- scripts/nns-dapp/migration-test.canister
The NNS dapp FE no longer reads transactions from the nns-dapp canister, but instead from the index canister.
In this PR we remove the `transactions` field on the `AccountsStore`. To be able to do this we also need to remove a few remaining usages (most usages were already removed in https://github.com/dfinity/nns-dapp/pull/4756, https://github.com/dfinity/nns-dapp/pull/4757, https://github.com/dfinity/nns-dapp/pull/4758, https://github.com/dfinity/nns-dapp/pull/4759, https://github.com/dfinity/nns-dapp/pull/4760) for stats and metrics and encode/decode something in its place for compatibility in the stable memory format between upgrades.
This PR does not remove the transactions related stats fields and also doesn't remove the transaction index vectors from accounts. Those will be cleaned …
> NNS1-2905: Remove transactions field from AccountsStore

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-04-17_23-01-hotfix-bitcoin-query-stats

- .github/workflows/build.yml
Our Playwright tests started failing when trying to install browsers with the following error:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```
For example: https://github.com/dfinity/nns-dapp/actions/runs/8813756690/job/24193274978?pr=4762
I guess either the GitHub runner or the Microsoft server got a bad configuration. 
If we switch `runs-on:` from the high performance Ubuntu 22.04 environment named `ubuntu-latest-m` to `ubuntu-20.04`, the tests are a bit slower but at least they pass.
We used `ubuntu-latest-m` when the e2e tests were the slowest …
> Change playwright runs-on 20.04

- Cargo.lock
- rs/backend/Cargo.toml
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
- rs/proposals/Cargo.toml
If I update the IC deps rev from release-2023-08-01_23-01 to release-2023-08-09_23-01 (which is the next release after it), I get multiple build problems.
If I only update to [2bc1a2bef3c9e5ec5e15da11e1f46531b3daa063](https://github.com/dfinity/ic/commit/2bc1a2bef3c9e5ec5e15da11e1f46531b3daa063) which is a commit in between those releases, I get only one build problem, caused by `TransferFrom having been merged with `Transfer`.
1. Update the IC deps rev to `2bc1a2bef3c9e5ec5e15da11e1f46531b3daa063`.
2. Merge our usage of `TransferFrom` with that of `Transfer`. We already did the same for both cases.
Still pass.
not necessary
> Update IC deps rev and remove TransferFrom

- CHANGELOG-Nns-Dapp-unreleased.md
- Cargo.lock
- rs/backend/Cargo.toml
Use the newest version of stable structures.
Update the dependency of `ic-stable-structure` in `rs/backend/Cargo.toml`.
CI
> Update ic-stable-structure dep from 0.6.0 to 0.6.4

- frontend/src/lib/components/accounts/TransactionList.svelte
- frontend/src/lib/derived/debug.derived.ts
- frontend/src/lib/directives/debug.directives.ts
- frontend/src/lib/services/icp-accounts.services.ts
- frontend/src/lib/utils/anonymize.utils.ts
https://github.com/dfinity/nns-dapp/pull/4714 created a lot of dead code.
If we try to clean if up all at once, it will be hard to make sure it's really all deleted.
So I went over the removed imports from that PR and marked the ones that aren't used anywhere else to be deleted.
And then only actually deleted dead code from the debug store.
The other dead code will be removed in future PRs because it will generate further dead code and by making sure we always mark newly dead code it will be easy to see that nothing is missed.
1. Remove unused `debugTransactions` and related code.
2. Mark other dead code for deletion.
Still pass.
not necessary
> NNS1-2906: Remove unused transactions from debug store

- frontend/src/lib/utils/transactions.utils.ts
- frontend/src/tests/lib/utils/transactions.utils.spec.ts
- frontend/src/tests/mocks/transaction.mock.ts
`mapToSelfTransaction` from `frontend/src/lib/utils/transactions.utils.ts` is unused.
It became unused in https://github.com/dfinity/nns-dapp/pull/4775 but I missed it because there is still another `mapToSelfTransaction` in `frontend/src/lib/utils/icp-transactions.utils.ts` which is used.
1. Remove `mapToSelfTransaction` from `frontend/src/lib/utils/transactions.utils.ts`.
Removed
not necessary
> NNS1-2906: Remove unused mapToSelfTransaction

- frontend/src/lib/canisters/nns-dapp/nns-dapp.certified.idl.js
- frontend/src/lib/canisters/nns-dapp/nns-dapp.did
- frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js
- frontend/src/lib/canisters/nns-dapp/nns-dapp.types.ts
The `nns-dapp` canister no longer has the `get_transactions` method and we removed all the code that used it from the FE.
Remove `get_transactions` and all the types used by (only) it from 
* `frontend/src/lib/canisters/nns-dapp/nns-dapp.certified.idl.js`
* `frontend/src/lib/canisters/nns-dapp/nns-dapp.did`
* `frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js`
* `frontend/src/lib/canisters/nns-dapp/nns-dapp.types.ts`
Still pass
not necessary, it was already removed from https://github.com/dfinity/nns-dapp/blob/main/rs/backend/nns-dapp.did and this candid was only internal to the FE code.
> NNS1-2906: Remove get_transactions from nns-dapp candid

- frontend/src/lib/types/transaction.ts
- frontend/src/tests/mocks/transaction.mock.ts
These variables are not used.
1. Remove `mockTransactionReceiveDataFromMain` and `mockTransactionSendDataFromMain` from `frontend/src/tests/mocks/transaction.mock.ts`.
2. Remove the now unused type `Transaction` from `frontend/src/lib/types/transaction.ts`.
Still pass
not necessary
> Remove unused mock data

- frontend/package-lock.json
- frontend/src/tests/mocks/sns-proposals.mock.ts
Upgrade `ic-js` to get new proposal types mapping.
- Add new `action_auxiliary` property to mock data.
Pass.
Not yet.
> Upgrade ic js 2024 04 26

- Cargo.lock
- Cargo.toml
- rs/backend/Cargo.toml
- rs/proposals/Cargo.toml
- rs/sns_aggregator/Cargo.toml
- rs/sns_aggregator/src/lib.rs
Since https://github.com/dfinity/nns-dapp/pull/4751 the `backend` and `proposals` crates use the same `rev` for the IC repo dependencies.
But `sns_aggregator` still uses an older `rev`.
Using the same `rev` for all crates makes it less likely that dependencies will interfere.
And `sns_aggregator` builds fine with the same `rev` as `backend` and `proposals`, except for 1 issue.
The issue is that `sns_aggregator` uses `ic_nervous_system_common::get_canister_status` which was removed in https://gitlab.com/dfinity-lab/public/ic/-/commit/bac55cb48c342112f8f20756e67e813eb3f2be2d
The function is small so I inlined it in `sns_aggregator` instead.
Defining the dependencies in the workspace makes it easier to keep them in sync.
1. Define IC repo dependencies in `/Cargo.toml`.
2. Use workspace …
> Use same IC deps for sns_aggregator as for proposals and backend

- dfx.json
> Update snsdemo to release-2024-04-24

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
This is a restored from https://github.com/dfinity/nns-dapp/pull/4719 PR w/o any changes.
We are going to change some topics and proposal types and want to make
sure the users are informed.
Add a message linking to the forum post on top of the neurons page for
users who have neurons.
- Unit tests added.
> Restore NNS1-3004: Message informing about topic renames (#4719)

- frontend/src/lib/components/universe/SelectUniverseNav.svelte
- frontend/src/routes/+layout.svelte
- frontend/src/tests/lib/components/universe/SelectUniverseNav.spec.ts
- frontend/src/tests/routes/layout.spec.ts
To display total actionable proposal count in the main navigation, we need to load them at the dapp startup.
- Move actionable loading into +layout file, where the other initializations are done.
- Tests were moved and adjusted.
Not yet
> Load actionables at app startup

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/proposal-detail/MyVotes.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/VotedNeuronList.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotedNeuronList.spec.ts
- frontend/src/tests/page-objects/MyVotes.page-object.ts
- frontend/src/tests/page-objects/VotedNeuronList.page-object.ts
- frontend/src/tests/page-objects/VotingPowerDisplay.page-object.ts
Voting power of neurons is displayed as rounded numbers. We want to give people access to the exact numbers.
This PR adds a tooltip on voting power of voted neurons, similar to what https://github.com/dfinity/nns-dapp/pull/4713 did for votable neurons.
1. Use `VotingPowerDisplay` component for the total voted neuron voting power in `VotedNeuronList` and the individual voted neurons in `MyVotes`.
1. Unit tests for both tooltips were added in `frontend/src/tests/lib/components/proposal-detail/VotingCard/VotedNeuronList.spec.ts`.
2. Page objects were updated.
> NNS1-2966: Tooltip on voted neuron voting power

- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
A new store to get a total number of all actionable proposals.
- `actionableProposalTotalCountStore`
- Added.
Not needed.
> New actionableProposalTotalCount Store

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
- scripts/did2rs.sh
- scripts/sns/aggregator/mk_nns_patch.sh
The latest automatically generated candid bindings update PR had errors on CI: https://github.com/dfinity/nns-dapp/pull/4792
The problem was that the latest [sns_ledger.did](https://github.com/dfinity/nns-dapp/blob/main/declarations/sns_ledger/sns_ledger.did) adds a type `GetBlocksResult` which has a field that is a callback.
This type is not found by Rust after the bindings are generated.
We already had similar issues before and they were solved with an additional [patch file](https://github.com/dfinity/nns-dapp/blob/abf9d48de02a9c4ebd8ed9da897601601395a1aa/rs/sns_aggregator/src/types/ic_sns_ledger.patch#L9).
So the current issue could have been fixed by adding more changes to the patch file. But to make things easier in the future, I decided to make the callback handling automatic.
1. …
> Improve did2rs and update aggregator candid bindings

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/lib/components/proposals/ActionableProposalTotalCountBadge.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/page-objects/MenuItems.page-object.ts
Display the total count of actionable proposals in main navigation.
- Add new total count tooltip support to the count badge.
- Add `noAnimation` prop to skip animation (on navigation).
- New component `ActionableProposalTotalCountBadge`.
- Add the count badge to the main menu.
- MainMenu should display `ActionableProposalTotalCountBadge`.
> Actionable proposals total badge

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-04-24_23-01-storage-layer

- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/tests/lib/components/proposals/ActionableProposalCountBadge.spec.ts
Add unique id to actionable count tooltip to let screen readers know which tooltip applies to which badge.
- Add global counter and use it for id generation.
- Added.
Not necessary.
> Actionable count tooltip

- scripts/sns/aggregator/release
- scripts/sns/aggregator/release-template
Our Docker build runs out of memory on M1 Mac.
It would be nice to be able to do most of the SNS aggregator release process on a Mac, even if we need to run the Docker build separately on a DevEnv.
To get the SNS aggregator WASM to release, download it from CI instead of building it with Docker.
Used for this week's SNS aggregator release.
not necessary
> Do not rely on Docker build for SNS aggregator release template

- rs/backend/src/accounts_store.rs
We process transactions in the NNS dapp, but only `Transfer` transactions.
We ignore `Burn`, `Mint` and `Approve` transactions so we don't care about their fields.
Specifying their fields makes adding optional fields a breaking change and makes it harder to update our dependencies.
Stop checking for fields of `Burn` and `Mint` transactions that we don't process anyway.
not necessary
> NNS1-3047: Ignore Burn and Mint fields

- rs/sns_aggregator/src/lib.rs
SNS aggregator uses the type `ic_ic00_types::CanisterStatusResultV2` to decode the result from calling `canister_status` on the management canister.
This means that if new fields are added to this type, we can't update our IC dependencies unless we wait for a version of the replica that includes these fields in the `canister_status` response.
This coupling makes it harder to keep our dependencies up to date.
Instead we should have our local copy of the type which we can update independently from our dependencies and the replica version.
1. I ran `didc bind --target rs rs/sns_aggregator/sns_aggregator.did >temp.rs` then copied the types I needed out of the temporary file into `rs/sns_aggregator/src/lib.rs`.
2. Disabled warning for missing docs on private fields. As we [have in other …
> NNS1-3047: Local copy of CanisterStatusResultV2

- frontend/src/lib/api/proposals.api.ts
- frontend/src/lib/services/$public/proposals.services.ts
- frontend/src/lib/services/$public/sns.services.ts
- frontend/src/lib/services/actionable-proposals.services.ts
- frontend/src/tests/lib/api/proposals.api.spec.ts
- frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
- frontend/src/tests/lib/services/actionable-proposals.services.spec.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
The API layer shouldn't depend on the stores.
Instead of passing the `filters` to `queryProposals`, pass `includeTopics`, `includeRewardStatus` and `includeStatus` individually.
Updated.
not necessary
> Removed dependency on stores from proposals.api.ts

- rs/backend/src/accounts_store/schema.rs
- rs/backend/src/accounts_store/schema/map.rs
- rs/sns_aggregator/src/upstream.rs
- rust-toolchain.toml
We update the Rust version automatically but the new version has a stricter lint so some issues needed to be fixed manually.
1. Update `channel` in `rust-toolchain.toml`.
2. Mark some methods and traits only used in tests with `#[cfg(test)]` to satisfy the linter.
3. Use `clone_from` to satisfy the linter.
Lint passes.
not necessary
> Update rust version to 1.78.0 (+ lint fixes)

- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
Improve actionable count badge min width.
- Set minimum width and center the content
- Manually
Not necessary
| <img width="480" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/07b490d0-b4eb-48e0-84b3-9a6346ac21e0"> | <img width="485" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/b1121f9d-4f23-4668-a320-bdcb9a6fcd9f"> |
> css: improve badge with narrow content width

- frontend/src/lib/components/proposals/NnsProposalsFilters.svelte
- frontend/src/lib/constants/proposals.constants.ts
- frontend/src/lib/derived/proposals.derived.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/lib/stores/proposals.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/components/proposals/NnsProposalsFilters.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/stores/proposals.store.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
- frontend/src/tests/page-objects/NnsProposalFilters.page-object.ts
Remove "Show only proposals you can still vote for" checkbox. This is the first step to get rid of `ENABLE_VOTING_INDICATION` feature flag.
- Remove the `<Checkbox>`  from `NnsProposalsFilters` component.
- Remove obsolete code from `ProposalsFiltersStore`:
- Remove `excludeVotedProposals` (reflects the removed checkbox state).
- Remove `lastAppliedFilter` (it was used only to render a preloader when `excludeVotedProposals` is checked).
- Removed `reload()` that was there to fix — “The filter to show only the ones you can vote on was being used even though the user was not logged in” (#1562).
- Remove `isExcludedVotedProposal` util.
- Remove unused arguments because neurons and identity were needed only for `isExcludedVotedProposal()`.
- Remove `getVotableProposalsOnlyCheckboxPo`.
- …
> Remove exclude voted proposals feature

- frontend/src/lib/components/neuron-detail/NnsNeuronAdvancedSection.svelte
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts
- frontend/src/tests/page-objects/NnsNeuronAdvancedSection.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronVotingPowerSection.page-object.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
- frontend/src/tests/page-objects/playwright.page-object.ts
The nns-dapp canister has a process where it finishes refreshing a neuron if ICP is transferred to a neuron account but the frontend got interrupted before it could refresh the neuron.
Recently I needed to test this several times manually so I decided it would be good to have an e2e test for it.
1. Implement `getDocumentBody()` on `PlaywrightPageObjectElement` to allow getting tooltip text in e2e test.
2. Use `HashPo.getFullText()` to get the full neuron account instead of the truncated one.
3. Update unit test that previously expected a truncated neuron account identifier to now expect the full identifier.
4. Add an e2e test that tests that neuron stake can be increased both the normal way and by making a direct transfer to the neuron account.
Drive-by:
5. Fix test description in …
> E2e test stake increase recovery process

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/nns-dapp/migration-test
- scripts/nns-dapp/migration-test.canister
We no longer store transactions in the nns-dapp canister because the frontend now reads transactions from the index canister.
However we still store transaction indexes on individual accounts. These indexes used to point into the vector of transactions which we no longer have and are now completely unused. So we want to clean these up.
Because these accounts are stored in stable memory we have to be careful about removing fields from them or we might get errors when decoding stable memory.
In particular, we should be able to revert to a previous release of nns-dapp in case of an emergency.
So we have to stop reading the fields at least 1 release before we stop writing the fields and we can't just remove the fields directly.
However when testing the changes necessary for this, I noticed …
> NNS1-2905: Improve upgrade-downgrade-test

- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
> Update IC candid files to release-2024-05-01_23-01-storage-layer

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/tests.rs
- rs/backend/src/accounts_store/tests.rs
- rs/backend/src/accounts_store/toy_data.rs
We no longer store transactions in the nns-dapp canister because the frontend now reads transactions from the index canister.
However we still store transaction indexes on individual accounts. These indexes used to point into the vector of transactions which we no longer have and are now completely unused. So we want to clean these up.
Because these accounts are stored in stable memory we have to be careful about removing fields from them or we might get errors when decoding stable memory.
In particular, we should be able to revert to a previous release of nns-dapp in case of an emergency.
So we have to stop reading the fields at least 1 release before we stop writing the fields.
For this purpose we introduce "Old" types for each of the account types which still have the removed fields …
> NNS1-2905: Remove transactions fields from accounts (step 1)

- .github/workflows/update-snsdemo.yml
In https://github.com/dfinity/nns-dapp/pull/4058 I removed a line from the automatic PR description of snsdemo updates.
But I should have only removed part of that line.
We still check that the dfx version matches. Only the IC commit is moved to a separate update job.
Restore part of the line that was removed in https://github.com/dfinity/nns-dapp/pull/4058
no
not necessary
> Fix description of snsdemo update PRs

- .github/workflows/build.yml
- scripts/nns-dapp/test-proposal-payload
Adding support for new NNS functions is usually quite easy but manually testing a new proposal type can be a lot of work.
This has always lacked testing coverage so I decided to add a testing script for it.
1. Add a script which creates proposals of various types and tests getting their payload with the nns-dapp `get_proposal_payload` method. I didn't add coverage for every function but did for some recently relevant ones. We should add more as we add/change more proposal types.
2. Test that no new proposal types were added that we were not aware of.
3. Run the test script on CI.
test-only
not necessary
> End-to-end test for nns-dapp get_proposal_payload

- CHANGELOG-Nns-Dapp-unreleased.md
- declarations/nns_governance/nns_governance.did
- declarations/nns_ledger/nns_ledger.did
- declarations/nns_registry/nns_registry.did
- declarations/sns_governance/sns_governance.did
- declarations/sns_ledger/sns_ledger.did
- declarations/sns_root/sns_root.did
- declarations/sns_swap/sns_swap.did
- declarations/sns_wasm/sns_wasm.did
- dfx.json
- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
- rs/proposals/src/def.rs
- rs/proposals/src/lib.rs
- scripts/nns-dapp/test-proposal-payload
The proposal type to add API Boundary nodes [now supports](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19097) adding multiple nodes in one proposal.
This is a breaking change but it's OK because proposals of this type have never been created and will not be created for a few more weeks.
Also note that the candid in `rs/registry/canister/canister/canister.rs` was regenerated automatically and because of how the tool works, this resulted in `UpdateApiBoundaryNodesVersionPayload` being removed and replaced by `AddApiBoundaryNodesPayload`, which is structurally the same. We work around this in `rs/proposals/src/def.rs` with
```
pub type UpdateApiBoundaryNodesVersionPayload = crate::canisters::nns_registry::api::AddApiBoundaryNodesPayload;
```
Note that we were already in a …
> Support proposal type AddApiBoundaryNodesPayload 

- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/page-objects/NnsProposalFilters.page-object.ts
- frontend/src/tests/page-objects/NnsProposalList.page-object.ts
- frontend/src/tests/page-objects/NoProposals.page-object.ts
In the near future the actionable proposals will be selected by default. To be able to switch between all and actionable proposals in the spec file, they should use page object for rendering.
- Add missing PO getters.
- Switch from `render()` to using a page object.
- Yes.
Not necessary.
> test: replace render with po in NnsProposals spec

- .github/workflows/update-ic-cargo-deps.yaml
- scripts/update-ic-cargo-deps
We have a job to update IC repo cargo dependencies.
But when dependencies are updated, the `Cargo.lock` file needs to be updated as well.
This normally happens automatically when you run `cargo build`, but on IC we run `cargo build --locked` to ensure the `Cargo.lock` file is not changed.
So we need to update the `Cargo.lock` file in the same script that updates the dependencies, and include it in the bot PR.
1. Run `cargo update --workspace` at the end of `scripts/update-ic-cargo-deps`.
2. Include `Cargo.lock` in files added to the bot PR.
Manually:
1. Ran `scripts/update-ic-cargo-deps` without the change.
2. Ran `cargo build` to see what updates were needed to the `Cargo.lock` file.
3. Made a copy of the `Cargo.lock` file.
4. Restored `Cargo.lock`.
5. Ran `cargo update --workspace` …
> Update Cargo.lock in deps update PR

- CHANGELOG-Nns-Dapp-unreleased.md
- dfx.json
- rs/proposals/src/def.rs
- rs/proposals/src/lib.rs
- scripts/nns-dapp/test-proposal-payload
There is a new proposal type to rent subnets, using NNS function 52.
1. Copy Rust types `SubnetRentalRequest` and `RentalConditionId` from the IC repo to `rs/proposals/src/def.rs`.
2. Render the payload as json without transformation.
1. Added a test in `scripts/nns-dapp/test-proposal-payload`.
2. Use `--test-neuron-proposer` because `ic-admin` doesn't work for subnet rental with `--secret-key-pem`.
3. Update snsdemo to a release that supports subnet rentals.
> Support SubnetRentalRequest NNS function 52

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/enum.utils.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Pull in the `SubnetRental` topic from https://github.com/dfinity/ic-js/pull/627
1. Ran `npm run upgrade:next`
2. Updated mapping code and tests to take the new topic enum into account.
2. Manually tested filtering proposals by "Subnet Rental" topic and adding followees to "Subnet Rental".
> Bump ic-js for subnet rental topic

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts
The current message `"Minimum participation has been reached, the swap is successful"` erroneously displays even when the number of participants in a swap falls below the configured threshold (`min_participants`). This PR rectifies this issue by enhancing the logic to consider both directly committed ICPs and the total participant count.
- Extend the success message visibility logic.
- "should hide success message when current saleBuyerCount is less then min_participants"
> Fix sale success message

- dfx.json
> Update didc release to 2024-05-14

- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTableRow.svelte
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTableRow.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/NeuronsTable.page-object.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
Add more scaffolding for the neurons table without implementing anything real.
1. Add `TableNeuron` type (with just 1 field for now) to be used to render neurons in the table. This abstracts away the difference between NNS neurons and SNS neurons so we'll be able to reuse the table for SNS.
2. Add `tableNeuronsFromNeuronInfos` to convert NNS `NeuronInfo`s to `TableNeuron`.
3. Create and pass `TableNeuron`s from `NnsNeurons` to `NeuronsTable`.
4. Add `NeuronsTableRow` component and use it in `NeuronsTable` component.
Added unit tests and page objects.
Drive-by: Fix `"should not render the neurons table"` test description which was incorrectly copied.
not yet
> Add NeuronsTableRow component

- .github/workflows/checks.yml
- dfx.json
- rs/proposals/HACKING.md
- scripts/update_ic_commit
See https://github.com/dfinity/nns-dapp/pull/4861 for motivation.
This PR is to make it possible to update candid for `proposals` and `sns_aggregator` independently.
In a future PR we'll use that possibility to make the proposed changes to the workflows.
1. Add a `--crate` flag to `scripts/update_ic_commit` to specify for which crate we want to update the IC commit and Candid files.
2. Allow `all` (which is default) to keep the original behavior of updating all Candid files.
3. Keep separate fields in `dfx.json` instead of the single `IC_COMMIT` fields.
1. Manually tested with `--crate proposals`, with `--crate sns_aggregator` and without `--crate`.
2. Updated the workflow test.
not necessary
> Update Candid for proposals and sns_aggregator independently

- .github/workflows/checks.yml
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
We're using a new [version](https://github.com/dfinity/nns-dapp/blob/c96d253521c13db187a7693b1c8dd3e61141fe4b/dfx.json#L377) of `didc` in nns-dapp.
This new version no longer adds blank lines between generated Rust types, and imports slightly different traits.
After generating Rust code we sometimes apply patch files.
Currently the patch files are thrown off by the line numbers differing too much (I think).
1. Adjust the generated Rust files to be in line with the new `didc`.
2. Regenerate the patch file.
1. Before the changes `scripts/sns/aggregator/mk_nns_patch.sh` broke ([like this](https://github.com/dfinity/nns-dapp/actions/runs/9116533871/job/25065348685)). With the changes it runs again without having to make changes to the generated code.
2. Added extra steps to the workflow to …
> Update generated Rust files based on new didc

- dfx.json
> Update snsdemo to release-2024-05-15

- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
To avoid having everything in one PR, this is the store that will be used in the actionable tab. It contains SNS universes (which support actionable proposals) and their actionable proposals, listed in the same order as they are displayed in the UI.
- New store `actionableSnsProposalsByUniverseStore`.
- Refactor `actionable-proposals.derived.spec` to reuse mock data and `beforeEach`.
- Tests for `actionableSnsProposalsByUniverseStore`.
Not necessary.
> New actionable sns proposals store

- scripts/dfx-snapshot-install
When running an snsdemo snapshot, your dfx state (including identities) is replaced with state from the snapshot.
A `restore.sh` script is created, which is run when the replica is stopped.
If something goes wrong the restore script can also be run manually.
But you shouldn't do this if the replica is still running.
Add a check in the restore script whether the replica is still running.
Ran a snapshot and tried to restore it manually while it was still running.
Then checked that it got restored correctly when I stopped the replica.
not necessary
> Don't restore state while replica is still running.

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/canister_ids
- scripts/canister_ids.test
When installing a release candidate on DevEnv, one of the steps is importing canister IDs from a URL so they can be used to deploy the release candidate.
Include ckUSDC canister IDs when importing from URL in `scripts/canister_ids`.
Test was updated.
> Include ckUSDC canisters when importing IDs from URL

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
Currently we always display tokens with 8 decimal precision on the transaction review screen.
Even for ckETH, which supports 18 decimals because we don't think there is value in displaying so many decimals.
But ckUSDC only has 6 decimals, so we should add 2 meaningless zeros to display 8.
1. Change `formatTokenE8s` to `formatTokenUlps` and make it generic in the number of decimals.
2. Call `formatTokenUlps` from `formatTokenE8s` with specific values for the number of displayed and detailed decimals.
3. Call `formatTokenUlps` instead of `formatTokenE8s` from `formatTokenV2`.
2. Looked manually that the transaction screen looks good.
> Display 6 decimals for ckUSDC.

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/transaction/TransactionForm.svelte
- frontend/src/lib/components/ui/AmountInput.svelte
- frontend/src/lib/components/ui/Input.svelte
- frontend/src/lib/components/ui/InputWithError.svelte
- frontend/src/tests/lib/components/ui/AmountInput.spec.ts
- frontend/src/tests/mocks/tokens.mock.ts
When entering an amount we allow entering up to 8 decimals.
Even though ckETH supports 18 decimals, we decided to support 8.
But ckUSDC only supports 6 decimals so we don't want to allow entering more than 6.
`Input` from gix-component already supports choosing the number of decimals if you use `inputType = "currency"` instead of `"icp"` but then the value is given as a string instead of a number.
1. Allow setting `decimals` and `inputType = "currency"` on `Input` and `InputWithError`.
2. Use `inputType = "currency"` in `AmountInput` and convert back to a number.
3. Accept an optional `token` prop on `AmountInput` and pass `decimals` based on the token.
Added unit tests with ckETH, ckUSDC and without token.
> Support fewer than 8 decimals in AmountInput

- frontend/package-lock.json
- frontend/src/tests/lib/canisters/ic-management.canister.spec.ts
- frontend/src/tests/lib/worker-api/canisters.worker-api.spec.ts
Propagate last weekly Candid definition ([631](https://github.com/dfinity/ic-js/pull/631)).
Query stats has been added to the spec in this PR [305](https://github.com/dfinity/interface-spec/pull/305).
- extend `CanisterStatusResponse` mock with `query_stats` in ic-mgmt and canister worker tests
> Bump ic-js next with last Candid definition

- frontend/src/lib/constants/routes.constants.ts
- frontend/src/lib/derived/page.derived.ts
- frontend/src/lib/utils/navigation.utils.ts
- frontend/src/routes/(app)/+layout.ts
- frontend/src/tests/lib/utils/navigation.utils.spec.ts
- frontend/src/tests/lib/utils/universes.utils.spec.ts
To enable linking to an actionable tab and allow navigation using browser history, a new query parameter - `actionable` has been added. It will serve as a flag indicating that the actionable tab should be displayed. The plan is to set this additional parameter when the user:
1.	Clicks on “Voting” in the main menu.
2.	Navigates to the proposals page without a specified universe query parameter (`u`).
- New const `ACTIONABLE_PARAM`.
- Make layout to provide `actionable`  as a bool value.
- Make `actionable` available through the `pageStore`.
- New util `buildActionableProposalsUrl`
- Update layout tests mock (expect actionable param).
- Test `buildActionableProposalsUrl`.
- Manually verified that the `pageStore` reflects the `actionable` parameter in the URL. Currently, there appears to be …
> Actionable query param support

- scripts/dfx-snapshot-install
When installing an snsdemo snapshot we moving a bunch of directories.
When uninstalling the snapshot we move those directories in the opposite direction in reverse order.
These moves are coded separately, which is fragile if we change what needs to be moved for the install.
We want to change what's installed so existing identities (such as `hsm`) can still be used while a snapshot is running.
In this PR we don't change what's installed but we generate the restore instructions from what's installed so it's less likely to get out of sync.
1. When creating a directory, record a `rmdir` command for the restore.
2. When moving a file or directory, record a reverse `mv` command for the restore.
3. When generating the restore script, output the recorded restore commands in reverse order.
4. Use …
> Create restore instructions from snapshot install operation

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/dfx-snapshot-install
When installing an snsdemo snapshot, the entire `~/.config/dfx` directory gets replaced with the one from the snapshot.
This includes all your identities.
So while a snapshot is running, you can't use your normal identities.
Instead of replacing the entire `~/.config/dfx` directory, replace all its contents (according to the snapshot), except the `identity` directory, then replace only those identities that exist in the snapshot, keeping the others.
Ran a snapshot. Checked that identities were still there.
> Keep existing identities when installing snapshot

- dfx.json
- scripts/nns-dapp/test-config-assets/app/arg.did
- scripts/nns-dapp/test-config-assets/app/env
- scripts/nns-dapp/test-config-assets/mainnet/arg.did
- scripts/nns-dapp/test-config-assets/mainnet/env
We need the canister IDs to support ckUSDC in NNS dapp.
I got these canister IDs from:
```
$ dfx canister --network ic call vxkom-oyaaa-aaaar-qafda-cai get_orchestrator_info
(
record {
cycles_management = record {
cycles_top_up_increment = 10_000_000_000_000 : nat;
cycles_for_ledger_creation = 150_000_000_000_000 : nat;
cycles_for_archive_creation = 50_000_000_000_000 : nat;
cycles_for_index_creation = 100_000_000_000_000 : nat;
};
managed_canisters = vec {
record {
erc20_contract = record {
chain_id = 1 : nat;
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48";
};
ledger = opt variant {
Installed = record {
canister_id = principal "xevnm-gaaaa-aaaar-qafnq-cai";
installed_wasm_hash = "4ca82938d223c77909dcf594a49ea72c07fd513726cfa7a367dd0be0d6abc679";
}
};
index = opt variant { …
```
> Set mainnet ckUSDC canister IDs

- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
In the `TokensTableRow` component there is a comment explaining why we duplicate the actions.
But we don't actually duplicate the actions so this comment shouldn't be there.
Remove the comment.
I checked with @lmuntaner who added it.
not necessary
> Remove outdated comment

- frontend/src/lib/components/proposals/ActionableProposalsNotSupportedSnses.svelte
- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/proposals/ActionableProposalsNotSupportedSnses.spec.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
- frontend/src/tests/page-objects/ActionableProposalsNotSupportedSnses.page-object.ts
- frontend/src/tests/page-objects/PageBanner.page-object.ts
Because not all projects support actionable proposals (return neuron ballots), not all actionable proposals will be shown on the actionable proposals page. To make it clear that there could be more votable proposals, we display a banner with a list of projects that do not have actionable support. In this PR, we create a banner component that will be shown on the actionable proposals page.
- Add new component `ActionableProposalsNotSupportedSnses`
- PO for `ActionableProposalsNotSupportedSnses`
- Tests for `ActionableProposalsNotSupportedSnses`
not yet.
> Snses without actionables banner

- frontend/src/tests/lib/utils/env-vars.utils.spec.ts
Unit tests can depend on environment variables set in `frontend/.env` which can be different depending on how `./config.sh` is run.
In `frontend/src/tests/lib/utils/env-vars.utils.spec.ts` we stub out environment variables that we expect to read, but additional environment variables could potentially affect the test as well.
Currently, the following
```
DFX_NETWORK=mainnet ./config.sh
npm run test -- env-vars
```
fails with
```
FAIL  src/tests/lib/utils/env-vars.utils.spec.ts > env-vars-utils > TVL canister ID is not mandatory
AssertionError: expected { …(20) } to deeply equal { …(18) }
- Expected
+ Received
Object {
"ckbtcIndexCanisterId": "olzyh-buaaa-aaaaa-qabga-cai",
"ckbtcLedgerCanisterId": "oz7p6-neaaa-aaaaa-qabfa-cai",
"ckbtcMinterCanisterId": "o66jk-a4aaa-aaaaa-qabfq-cai", …
```
> Remove existing environment in env-vars.utils.spec.ts

- frontend/src/lib/components/tokens/TokensTable/TokenActionsCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenTitleCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTableRow.svelte
We want to try to reuse the tokens table structure and style for the neurons table.
The `TokensTable` component is currently very specific to the tokens table.
By extracting tokens specific subcomponents, I'm hoping to separate the generic table structure from the tokens specific rendering.
And this should make it easier to subsequently create a generic table component and use that for both the tokens table and the neurons table.
1. Create `TokenTitleCell`, `TokenBalanceCell` and `TokenActionsCell` component.
2. Use those components in `TokensTableRow.svelte`
All tokens table functionality continues to be covered by `src/tests/lib/components/tokens/TokensTable.spec.ts`.
not necessary
> Extract cell components from TokensTableRow

- CHANGELOG-Nns-Dapp-unreleased.md
- rust-toolchain.toml
There is a bug in Rust 1.78: https://github.com/rustwasm/wasm-bindgen/issues/3801
I'm not sure if it affects us but better safe than sorry.
Go back to the version of Rust (1.77.2) we were using before https://github.com/dfinity/nns-dapp/pull/4822
CI
> Downgrade rust from 1.78 to 1.77

- dfx.json
> Update snsdemo to release-2024-05-22

- frontend/src/tests/e2e/accounts.spec.ts
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/page-objects/Accounts.page-object.ts
- frontend/src/tests/page-objects/App.page-object.ts
- frontend/src/tests/page-objects/TokensTable.page-object.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Having an attribute on the `TokensTableRow` which is specific to the tokens data makes it more difficult to make the table generic so it can be reused for the neurons table.
This attribute was only used for testing.
1. Remove `data-title` attribute.
2. Instead of using the `data-title` attribute to find a specific row, iterate over the rows and return the one that matches.
3. Use `await` where necessary because the method now has to be async.
Pass
not necessary
> Remove data-title from TokensTableRow

- frontend/__mocks__/$app/stores.ts
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/ui/Separator.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/components/universe/SelectUniverseDropdown.svelte
- frontend/src/lib/components/universe/SelectUniverseList.svelte
- frontend/src/lib/components/universe/SelectUniverseNavList.svelte
- frontend/src/lib/modals/universe/SelectUniverseModal.svelte
- frontend/src/lib/pages/ActionableProposals.svelte
- frontend/src/lib/routes/Proposals.svelte
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseDropdown.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseList.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseNav.spec.ts
- frontend/src/tests/lib/routes/Proposals.spec.ts
- frontend/src/tests/page-objects/ActionableProposals.page-object.ts
- frontend/src/tests/page-objects/Proposals.page-object.ts
- frontend/src/tests/page-objects/SelectUniverseCard.page-object.ts
- frontend/src/tests/page-objects/SelectUniverseList.page-object.ts
- frontend/vitest.setup.ts
The `Actionable Proposals` page should be shown when the user clicks `Voting` in the main navigation or when the `Actionable Proposals` card in the universe navigation is clicked. With this PR, we add the card to the universe navigation and update the main navigation link to navigate to “Actionable Proposals” when the user is logged-in.
There should be no actionable proposals visible for logged-out users.
- Update main menu proposals link to navigate to "Actionable proposals".
- Add empty component for "Actionable proposals" page.
- Add "Actionable proposals" card to `SelectUniverseList` (Desktop. The card is always visible with the separator).
- Add "Actionable proposals" card to `SelectUniverseDropdown` (Mobile. The card is shown only when selected, w/o the separator).
- Add `testId` …
> Actionable universe navigation

- frontend/src/lib/components/tokens/TokensTable/TokenActionsCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenTitleCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
We want to evolve `ResponsiveTable`, which is currently specific to tokens to a fully generic table.
So its props should not refer to tokens in the name.
The token table cell components will remain specific to the tokens table, but because they will have to interact with the generic table, their props need to be generic as well.
1. In `frontend/src/lib/components/ui/ResponsiveTable.svelte` change `userTokensData` to `tableData` and `userTokenData` to `rowData`.
2. In `frontend/src/lib/components/ui/ResponsiveTableRow.svelte` and in all the cell components, change `userTokenData` to `rowData`.
Note that each cell gets the data for the full row because it's the cell's responsibility to know which data from the row it needs to render.
Existing tests continue to pass.
Tested manually as well. …
> Rename userTokenData prop to rowData

- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
We need to determine when the actionable proposals are fully loaded to display a loader. Here, we add a new store that returns true only when everything is preloaded. We can’t display a loader per SNS because we only know if the Sns needs to be displayed after fetching, based on the `includeBallotsByCaller` flag.
- New derived store `actionableProposalsLoadedStore`
- tests for the new store.
Not necessary.
> New actionable proposals loaded store

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/lib/types/responsive-table.ts
- frontend/src/lib/types/tokens-page.ts
We want to make `ResponsiveTable` generic to reuse it for the neurons table.
For this we need to customize which columns will be rendered for each row.
1. Add type `ResponsiveTableColumn` which specifies a title for a single column and how to render cells in that column.
2. Pass a list of `ResponsiveTableColumn` from `TokensTable` to `ResponsiveTable`.
3. In `ResponsiveTable` render column headers based on the column specification.
4. In `ResponsiveTableRow` use components from the column specification to render the cells.
Existing tokens table tests pass.
Will add tests for responsive table when it's fully generic.
not necessary
> Pass column specification to ResponsiveTable

- frontend/src/lib/components/proposals/UniverseWithActionableProposals.svelte
- frontend/src/tests/lib/components/proposals/UniverseWithActionableProposals.spec.ts
- frontend/src/tests/lib/components/proposals/UniverseWithActionableProposalsTest.svelte
- frontend/src/tests/page-objects/UniverseWithActionableProposals.page-object.ts
The “Actionable Proposals” page should display all actionable proposals grouped by universe (Nns/Sns). Here, we add a wrapper component that will represent a universe and provide a slot for rendering universe proposals. Proposals can’t be provided via props because `Nns` and `Sns` have different types.
- Add a new component.
- Add PO for the new component.
- Add tests for UniverseWithActionableProposals.
Not necessary.
> Universe with actionable proposals component

- .github/workflows/checks.yml
We have workflows to automatically update Candid files and generate Rust code from them.
We have tests to make sure the Rust code is always equal to what would be generated to make sure it's not manually edited.
I recently updated the workflows (https://github.com/dfinity/nns-dapp/pull/4875) and made a copy-paste mistake in the test, which now prevents us from updating the code.
Fix the `--crate` flag passed to `./scripts/update_ic_commit` to match the IC commit the Candid files are from and the Rust generated from them.
Not tested.
This test is currently failing in bot-generated PRs and needs to be fixed before we can test creating another bot PR through the workflow.
not necessary
> Fix crate flag on code generation test

- Cargo.lock
- Cargo.toml
> Update IC Cargo Dependencies to release-2024-05-22_23-01-base

- .github/workflows/checks.yml
- .github/workflows/update-aggregator.yml
- .github/workflows/update-proposals.yml
In https://github.com/dfinity/nns-dapp/pull/4879 I combined the workflow to update Candid with the workflows to update Rust from Candid. Unfortunately I couldn't fully test it at the time because the IC release had failed that week.
Now it turns out that while the Candid may be updated correctly, it's not added to the PR created at the end.
1. Add the paths that used to be added to the PR in that updated Candid ([here](https://github.com/dfinity/nns-dapp/blob/c2f02ac390759f9dbcd87da0712fadede589854d/.github/workflows/update-ic.yml#L87-L89)) to the PRs that now update Candid and Rust.
These PRs were created from this branch:
1. https://github.com/dfinity/nns-dapp/pull/4936
2. https://github.com/dfinity/nns-dapp/pull/4935
not necessary
> Add missing paths to candid bindings workflows

- declarations/used_by_proposals/nns_governance/nns_governance.did
- declarations/used_by_proposals/nns_registry/nns_registry.did
- declarations/used_by_proposals/sns_wasm/sns_wasm.did
- dfx.json
- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
We would like to render all the latest proposal types.
* Update the version of `IC_COMMIT_FOR_PROPOSALS` specified in `dfx.json`.
* Updated the `proposals` candid files to the versions in that commit.
* Updated the Rust code derived from `.did` files in the proposals payload rendering crate.
> bot: Update proposals candid bindings

- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
We want to use the `ResponsiveTable` with different types of data.
Declare the `tableData` in `ResponsiveTable` and `rowData` in `ResponsiveTableRow` to be of a generic type.
I found this syntax [here](https://github.com/ciscoheat/sveltekit-superforms/issues/245#issuecomment-1698928562) and it seems to satisfy both the linter and the compiler.
I've also tested this with a preliminary neurons table in another branch.
not necessary
> Use a generic type for ResponsiveTable data

- .github/workflows/update-aggregator.yml
We have 2 workflows that update candid (for [proposals](https://github.com/dfinity/nns-dapp/blob/main/.github/workflows/update-proposals.yml) and [sns_aggregator](https://github.com/dfinity/nns-dapp/blob/main/.github/workflows/update-aggregator.yml)).
They update [adjacent fields](https://github.com/dfinity/nns-dapp/blob/c2459e808ae46e54c58580a44ce2b26a3d8cb568/dfx.json#L391-L392) in dfx.json, which make their PRs conflict, requiring manual intervention.
Run the `update-aggregator.yml` workflow on Tuesday instead of Monday to avoid conflicts between simultaneous PRs.
not tested
not necessary
> Change schedule day for sns_aggregator candid workflow

- frontend/src/lib/components/proposals/ActionableNnsProposals.svelte
- frontend/src/lib/pages/ActionableProposals.svelte
- frontend/src/tests/lib/pages/ActionableProposals.spec.ts
- frontend/src/tests/page-objects/ActionableNnsProposals.page-object.ts
- frontend/src/tests/page-objects/ActionableProposals.page-object.ts
The actionable proposals page should include all votable proposals. Here, we display Nns proposals that users can vote for.
- Add `ActionableNnsProposals` component.
- Display actionable Nns proposals.
- Add `ActionableNnsProposalsPo`.
- Test that actionable Nns proposals have been rendered.
Not yet.
> Display actionable proposals nns

- frontend/src/lib/components/proposals/UniverseWithActionableProposals.svelte
To match the design, we are adding a missing spacing between the heading and the list.
- Style changes only.
- Manually.
| From | To |
| <img width="292" alt="Screenshot 2024-05-27 at 11 39 13" src="https://github.com/dfinity/nns-dapp/assets/98811342/7002a21c-1b17-44e6-a7f7-cf54ffe25c95"> | <img width="263" alt="Screenshot 2024-05-27 at 11 39 26" src="https://github.com/dfinity/nns-dapp/assets/98811342/e5d802fa-65ff-4ed6-a3d2-f38b4e71d681"> |
Not necessary.
> style: Add a space between universe title and proposals

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/lib/components/ui/TestTableAgeCell.svelte
- frontend/src/tests/lib/components/ui/TestTableNameCell.svelte
- frontend/src/tests/page-objects/ResponsiveTable.page-object.ts
- frontend/src/tests/page-objects/ResponsiveTableRow.page-object.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
A generic `ResponsiveTable` component was extracted from `TokensTable`.
So far we relied only on `TokensTable.spec.ts` for testing but the `ResponsiveTable` is now generic enough that it makes sense for it to have its own test.
I'll continue making it more generic but now it will also be possible to test separately.
1. Add `testId` prop to `ResponsiveTable`.
2. Change `data-tid` on `ResponsiveTableRow`. This doesn't need to be a prop since once table only has one kind of row so there can never be confusion.
3. Add some cell components for testing.
4. Add page objects.
5. Add tests.
Old and new tests pass.
Also did a quick manual check.
not necessary
> Add test for ResponsiveTable

- Cargo.lock
- Cargo.toml
- rs/backend/Cargo.toml
- rs/sns_aggregator/Cargo.toml
When [dependabot tried to update](https://github.com/dfinity/nns-dapp/pull/4924) our pocket-ic dependency, this broke because the upgrade of ic-cdk from 0.13.2 to 0.13.3 was unintentionally a breaking change.
They have now withdrawn version 0.13.3 and release version 0.14.
1. Downgrade ic-cdk back to 0.13.2.
2. Upgrade pocket-ic to 3.1.0
CI passed.
not necessary
> Update pocket-ic dependency (and downgrade ic-cdk)

- frontend/src/lib/components/proposals/LoadingActionableProposals.svelte
- frontend/src/lib/pages/ActionableProposals.svelte
- frontend/src/tests/lib/pages/ActionableProposals.spec.ts
- frontend/src/tests/page-objects/ActionableProposals.page-object.ts
Added a preloader to improve the UX. The preloader provides feedback to the user, indicating that the proposals are still loading.
- Add `LoadingActionableProposals` component (PO is not needed since there are no plans to reuse it elsewhere).
- Display `LoadingActionableProposals` while loading.
- 
- Extend `ActionablePagePO` with `hasSkeletons`.
- Update other `ActionablePage` tests to respect loading state (to Nns proposals be shown, Sns proposals needs to be loaded and vice versa).
- Move some vars outside of a description block to reuse them in another test.
- Test that skeletons are shown while everything is not loaded and hidden afterwards.
Not necessary.
| Desktop loading | Mobile loading | Loaded |
|--------|--------|--------|
| <img width="1331" alt="image" …
> Actionable proposals loading state

- frontend/src/lib/pages/ActionableProposals.svelte
- frontend/src/tests/lib/pages/ActionableProposals.spec.ts
- frontend/src/tests/page-objects/ActionableProposals.page-object.ts
To improve the UX with actionables, we display a banner when there are no actionable proposals available. Because SNS without actionable proposals are not displayed, it’s enough to handle only a single state for all universes.
- Display `ActionableProposalsEmpty` banner in `ActionableProposals` component.
- Add `hasActionableEmptyBanner` to PO.
- Test that the banner is shown.
Not necessary.
| Mobile | Desktop |
| <img width="407" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/a8f00e49-e379-47b4-b892-d78aff5c285e"> | <img width="1220" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/b12c6eaf-60f2-46bf-aa3a-645d6200b6ef"> |
> No actionable proposals banner

- declarations/used_by_sns_aggregator/sns_governance/sns_governance.did
- declarations/used_by_sns_aggregator/sns_ledger/sns_ledger.did
- declarations/used_by_sns_aggregator/sns_root/sns_root.did
- declarations/used_by_sns_aggregator/sns_swap/sns_swap.did
- declarations/used_by_sns_aggregator/sns_wasm/sns_wasm.did
- dfx.json
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
We would like to parse all the latest SNS data. To do so, we update the candid interfaces for the SNS aggregator.
* Update the version of `IC_COMMIT_FOR_SNS_AGGREGATOR` specified in `dfx.json`.
* Updated the `sns_aggregator` candid files to the versions in that commit.
* Updated the Rust code derived from `.did` files in the aggregator.
> bot: Update sns_aggregator candid bindings

- scripts/deploy-devenv
`scripts/deploy-devenv` uses `--mode reinstall` by default.
It can be nice to use `upgrade` sometimes.
1. Add a flag `--mode` to `scripts/deploy-devenv`, which is passed on to `dfx canister install`.
2. Add help text, which can be accessed with `--help`, instead of just a comment.
Used on DevEnv.
not necessary
> Add --mode flag to scripts/deploy-devenv

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
This message was always meant to be temporary.
It was first added in https://github.com/dfinity/nns-dapp/pull/4719, then removed in https://github.com/dfinity/nns-dapp/pull/4743 and added back in https://github.com/dfinity/nns-dapp/pull/4795.
Undo most changes from https://github.com/dfinity/nns-dapp/pull/4719
Also removed
> Remove topic rename message

- frontend/src/lib/components/proposals/ActionableSnses.svelte
- frontend/src/lib/components/proposals/LoadingActionableProposals.svelte
- frontend/src/lib/components/proposals/UniverseWithActionableProposals.svelte
- frontend/src/lib/pages/ActionableProposals.svelte
Different types of components will be rendered on the actionable page, and it will be easier to control the gaps between them from the page component itself. This PR changes how the gaps are set, switching from `margin-bottom` in child components to flex `gap` in the parent component.
- Use flex `gap` to set the spacing between the direct children of the page component..
- Remove bottom margin from `UniverseWithActionableProposals`, but the same gap was added to it's parent component `ActionableSnses`.
- Switch from `TestIdWrapper` to `div` in skeleton component to avoid container gaps.
- Pass.
Not necessary.
> Update actionable page gaps

- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/derived/icp-tokens-list-visitors.derived.ts
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/derived/tokens-list-visitors.derived.ts
- frontend/src/lib/types/responsive-table.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/icp-tokens-list-visitors.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-visitors.derived.spec.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
- frontend/src/tests/mocks/tokens-page.mock.ts
- frontend/src/tests/page-objects/ResponsiveTableRow.page-object.ts
- frontend/src/tests/page-objects/jest.page-object.ts
- frontend/src/tests/page-objects/playwright.page-object.ts
- frontend/src/tests/types/page-object.types.ts
When rendering table rows in a `{#each}` we need to assign a uniq DOM key to each row so Svelte can keep track of rows for the purpose of transitions.
For the tokens table we used the token URL for this because each row had a unique URL anyway.
But for the neurons table, we need to be able to render rows for spawning neurons, which do not have a details page and so do not have a URL.
So we need another way to assign the DOM key without have a URL.
1. Add a new `domKey` field to `ResponsiveTableRowData`.
2. Make `rowHref` optional.
3. Use `domKey` instead of `rowHref` in the `{#each}` in `frontend/src/lib/components/ui/ResponsiveTable.svelte`.
4. Render rows which do not have a URL as `div` instead of `a`. (This was also done before https://github.com/dfinity/nns-dapp/pull/4647)
5. Remove …
> NNS1-3091: Make rowHref optional on ResponsiveTable

- frontend/src/lib/components/proposals/ActionableProposalsEmpty.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/i18n.utils.ts
- frontend/src/tests/lib/components/proposals/ActionableProposalsEmpty.spec.ts
- frontend/src/tests/lib/components/proposals/ActionableProposalsNotSupportedSnses.spec.ts
- frontend/src/tests/lib/utils/i18n.utils.spec.ts
- frontend/src/tests/page-objects/PageBanner.page-object.ts
In cases where the user has voted on all available actionable proposals, we currently display the `ActionableProposalsEmpty` banner with the text "You’re all caught up." However, if some SNSes still don’t support actionable proposals, we cannot be sure that there are no votable proposals for these SNSes. To make this clear, the `ActionableProposalsEmpty` banner should display more detailed information. In this PR, we update the description to display the SNSes that may contain votable proposals.
- New `joinWithOr` util.
- Display unsupported Snses in `ActionableProposalsEmpty` banner description.
- Not related refactoring: removed redundant array creation [here](https://github.com/dfinity/nns-dapp/pull/4960/files#diff-bdabfefb322354658061b1e40e4e4b5a1fc2feab676ffcd43e37d91b9b7d4894R12).
- …
> Display unsupported snses in all-voted banner

- frontend/src/lib/components/neurons/NeuronsTable/NeuronActionsCell.svelte
- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
Spawning neurons don't have a neuron details page. The current neuron cards are not clickable for spawning neurons.
So the rows in the neurons table also should not be clickable for spawning neurons.
1. Make `rowHref` an optional field on `TableNeuron`.
2. Create `TableNeuron` objects without `rowHref` for spawning neurons.
3. Render `TableNeuron`s without `rowHref` also without "go-to-detail" action (i.e. the right pointing chevron).
4. 
Added unit tests for
1. `frontend/src/lib/utils/neuron.utils.ts`
2. `frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts`, and
3. `frontend/src/tests/lib/pages/NnsNeurons.spec.ts`
not yet
> NNS1-3092: Make spawning neurons non-clickable in neurons table

- frontend/src/lib/components/neurons/NeuronsTable/NeuronDissolveDelayCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
Showing neuron dissolve delay in the neurons table.
1. Add `NeuronDissolveDelayCell` to render the dissolve delay.
2. Add column to column spec in `frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte`
3. Add `dissolveDelaySeconds` field to `TableNeuron` type.
4. Add dissolve delay conversion in `tableNeuronsFromNeuronInfos`.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
not yet
> NNS1-3092: Add dissolve delay column to neurons table

- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
While the neurons page is loading, we currently show skeleton cards.
This doesn't make sense if after loading a table appears instead of cards.
Also, if there are zero neurons, we should not show anything except the empty message.
With cards this is automatic because we just show zero cards.
But we don't want to show a table header with zero rows if there are zero neurons.
1. If neurons are loading, show a spinner.
2. If neurons are loaded but there are no neurons, hide the table.
Unit tests added for spinner, skeleton cards and empty message with and without feature flag.
Drive-by: Update `isContentLoaded` to take into account that we might have a spinner instead of skeleton cards. This is not used yet but we're going to need it eventually.
not yet
> NNS1-3092: Show spinner while neurons table is loading

- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
We'll want to provide custom sorting in the neurons table by clicking on the column headers.
So we'll need to be able to sort based on different criteria.
In this PR we provide some utilities for custom sorting.
1. Implement neuron comparators based on stake, dissolve delay and neuron ID. We'll add more later.
2. Implement a neuron sorting function which takes an ordered list of comparators to define the sorting order.
not yet
> NNS1-3092: Sorting utils for neurons table

- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
Spawning neurons don't have stake but do have maturity. This means that they always appear last when we sort neurons by descending stake.
In `frontend/src/tests/lib/pages/NnsNeurons.spec.ts` there is a spawning neuron with positive stake, which makes the test unrealistic and confusing.
1. Give the spawning neuron a stake of 0 and a large maturity.
2. Update the test to reflect that after sorting the spawning neuron comes last.
pass
not necessary
> Make NnsNeurons.spec.ts more realistic

- dfx.json
> Update snsdemo to release-2024-05-29

- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
Neuron cards are sorted by stake and then dissolve delay.
We want the same for the neurons table until we implement custom sorting.
Currently we tie break on creation time but:
1. That's not guaranteed to be unique because on the IC time is constant for the duration of a message
2. Is not visible in the UI
So we decided to tie break on neuron ID instead.
1. Order neurons by decreasing stake, then decreasing dissolve delay, then increasing ID.
1. Unit tests added and updated.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> NNS1-3092: Sort neurons in table

- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
I originally added `tableNeuronsFromNeuronInfos` to `neuron.utils.ts`, which is already very big.
Then I added `neurons-table.utils.ts` specifically for the neurons table.
So it seems suitable to put `tableNeuronsFromNeuronInfos` there as well.
1. Move `tableNeuronsFromNeuronInfos`.
2. Update imports.
3. Move tests.
4. Put existing tests in `frontend/src/tests/lib/utils/neurons-table.utils.spec.ts` in a separate `describe` block.
5. Use `makeStake` from `neurons-table.utils.ts` for the tests that moved there.
moved
pass
not necessary
> Move tableNeuronsFromNeuronInfos to neurons-table.utils.ts

- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/tests/page-objects/NeuronIdCell.page-object.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
The neuron ID can take up a lot of space, especially for SNS neurons, and is not very meaningful.
Use `IdentifierHash` component to shorten the neuron ID and add a copy button.
1. Page object updated.
2. Tested manually.
not yet
> NNS1-3092: Shorten neuron ID in table

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/app.services.ts
- frontend/src/routes/+layout.svelte
- frontend/src/tests/lib/services/app.services.spec.ts
- frontend/src/tests/routes/layout.spec.ts
Move the initialization of actionable proposals to `initAppPrivateData` to ensure that all necessary Nns and Snses data has already been loaded.
- Change the return type of `initAppPrivateData` function to be void, since its result is not used anywhere.
- Wait for Nns and Snses  initialization inside `initAppPrivateData`. This should not affect [the current behaviour](https://github.com/dfinity/nns-dapp/blob/150c24f17ef684633cbfebb222faaa4dc8a2da9b/frontend/src/routes/%2Blayout.svelte#L42).
- Move the actionable initialization to `initAppPrivateData`.
- Remove from layout tests.
- Added to app.services.spec.
> Improve initialization of actionable proposals

- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
We want to use the neurons table for SNS neurons as well.
The neurons table takes neurons in a specific `TableNeuron` type.
So we need to convert `SnsNeuron`s to `TableNeuron`s.
Add utility function `tableNeuronsFromSnsNeurons` to convert `SnsNeuron`n to `TableNeuron`s.
1. Conveniently set the neuron state in `createMockSnsNeuron` if it wasn't provided but a dissolve delay was specified.
2. Add unit tests for `tableNeuronsFromSnsNeurons`.
not yet
> NNS1-3093: Convert SNS neurons for table rendering

- Cargo.lock
- Cargo.toml
> Update IC Cargo Dependencies to release-2024-05-29_23-02-base

- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
We want to render neuron state in the neurons table.
For this, we need the neuron state in the `TableNeuron` type which is used to render the neurons table.
1. Add `state` field to `TableNeuron` type.
2. Populate the state field in `frontend/src/lib/utils/neurons-table.utils.ts` for both NNS and SNS neurons.
3. Destructure `mockTableNeuron` in neurons in `NeuronsTable.spec.ts` so new fields don't need to be added immediately in the test and can be updated in a separate PR when we update the UI.
4. Remove `rowHref` from `mockTableNeuron` as it's an optional field and it should be possible to destructure `mockTableNeuron` and not specify `rowHref`.
1. Unit tests added for `frontend/src/lib/utils/neurons-table.utils.ts`.
2. Tested manually in another branch which also has UI changes.
not yet
> NNS1-3092: Add state field to TableNeuron

- frontend/src/lib/components/neurons/NeuronsTable/NeuronStateCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/page-objects/NeuronStateInfo.page-object.ts
- frontend/src/tests/page-objects/NeuronsTable.page-object.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
- frontend/src/tests/page-objects/ResponsiveTable.page-object.ts
Add more information to the neurons table.
1. Add `NeuronStateCell` comonent.
2. Add neuron state column to `NeuronsTable` component.
1. Add missing unit test for table headers.
2. Add unit test for state column.
3. Add page object.
4. Make `NeuronsTablePo` extend `ResponsiveTablePo` to access `getColumnHeaders()`.
not yet
> NNS1-3092: Add neuron state column to neurons table

- frontend/src/lib/components/proposal-detail/NnsProposal.svelte
- frontend/src/lib/components/proposal-detail/ProposalNavigation.svelte
- frontend/src/lib/pages/SnsProposalDetail.svelte
- frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
In the [previous PR](https://github.com/dfinity/nns-dapp/pull/4956), the whole navigation component was mistakenly hidden on the active proposal details page. Unfortunately, this component is also responsible for displaying the header with the project logo. Here we are restoring the header display (see screenshots).
- Remove the hide-on-actionable-page logic from `ProposalNavigation` component and apply it to navigation buttons only.
- Tests updated.
Not necessary since the feature is behind the feature flag.
| <img width="1255" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/4bd41f8e-3520-4c3c-bbdf-6b5a57b23c57"> | <img width="1251" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/554fb5b6-a526-4d8d-92af-d7ea0 …
> Restore proposal detail title

- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
We want to render tags such as "Hardware Wallet Controlled" and "Hotkey control" in the neurons table.
NNs neurons have a specific function to produce these tags: https://github.com/dfinity/nns-dapp/blob/29f6ac77d2c0cde192e513c3adcca28c99e6a7ae/frontend/src/lib/utils/neuron.utils.ts#L406
And SNS neurons don't.
1. Add `getSnsNeuronTags` similar to `getNeuronTags`.
not yet
> NNS1-3093: Add getSnsNeuronTags

- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
We want to render tags such as "Hardware Wallet Controlled" and "Hotkey control" in the neurons table.
In this PR we add the information to the `TableNeuron` type.
Actually rendering it will happen in the next PR.
1. Add `tags: string[]` field to `TableNeuron`.
2. Include tags in result in `tableNeuronsFromNeuronInfos` and `tableNeuronsFromSnsNeurons`.
3. Pass newly required parameters from `NnsNeurons.svelte` and `SnsNeurons.svelte`.
Added unit tests.
not yet
> NNS1-3092: Add tags field to TableNeuron

- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/page-objects/NeuronIdCell.page-object.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
We want to render tags such as "Hardware Wallet Controlled" and "Hotkey control" in the neurons table.
1. Render tags in the `NeuronIdCell'.
The alignment is not great but will be addressed in another PR.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> NNS1-3092: Render neuron tags in table

- frontend/package-lock.json
We released gix-cmp v4.3.0 and updated the library to this new version. This update advances the library to the latest version number.
> build: bump gix-cmp for next version

- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/lib/types/responsive-table.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/page-objects/ResponsiveTableRow.page-object.ts
- frontend/src/tests/page-objects/TokensTable.page-object.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
We want icons in the neurons table to be aligned across columns.
In this PR we address the neuron state icons by left-aligning the cells in that column.
1. Add `alignment` field to the `ResponsiveTableColumn` type.
2. Add a class to cells in the `ResponsiveTable` based on the `alignment` field on the column spec.
3. Align cells based on the class.
4. Set `alignment` on all the columns in the `NeuronsTable` and `TokensTable` components.
5. Set `left` alignment for the "State" column.
1. Make tokens table POs extend responsive table POs.
2. Add unit tests for `ResponsiveTable`, `TokensTable` and `NeuronsTable`.
3. Manually tested at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> NNS1-3092: Left-align neuron state column

- frontend/package-lock.json
We release ic-js [2024.06.05-0835Z](https://github.com/dfinity/ic-js/releases/tag/2024.06.05-0835Z) earlier today. This PR hooks the libraries to their new version number for the next versions.
```
npm rm @dfinity/nns @dfinity/cmc @dfinity/sns @dfinity/utils @dfinity/ledger-icrc @dfinity/ledger-icp @dfinity/ckbtc @dfinity/ic-management && npm i @dfinity/utils@next @dfinity/ledger-icrc@next @dfinity/ledger-icp@next @dfinity/nns@next @dfinity/cmc@next @dfinity/sns@next @dfinity/ckbtc@next @dfinity/ic-management@next && ../scripts/revert-next.sh
```
> build: bump to next version numer

- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/lib/types/responsive-table.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/page-objects/ResponsiveTable.page-object.ts
We want to align the neuron ID copy icons across different rows in the neuron table.
For this we nee a subgrid within the neuron ID cell, with an extra grid line aligning the icons.
The first step for this is to allow customizing the template columns.
In the next step we'll allow multiple grid columns/rows per table column/row so the `templateColumns` field on the `ResponsiveTableColumn` is already an array, even though for now, arrays with a size unequal to 1 don't work yet.
Currently we assume that the template columns are always `1fr` for the first column and `max-content` for every other column. In this PR we make that explicit. And in a future PR we'll actually customize it.
1. Add `TemplateItem` type and `templateColumns` field in `ResponsiveTableColumn`.
2. Specify the …
> NNS1-3092: Support custom column templates in responsive table

- frontend/src/lib/components/ui/ResponsiveTable.svelte
The neurons can be cut off on a narrow viewport and we plan to add even more columns.
We need to make sure that the whole table can be reached.
Change `overflow: hidden` to `overflow-y: auto` on the responsive table.
Manually.
I tried to make a screen recording but somehow while recording the scrollbar doesn't appear.
not yet
> NNS1-3092: Add horizontal scrollbar to neurons table

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/SnsProposalDetail.svelte
- frontend/src/lib/services/$public/sns-proposals.services.ts
- frontend/src/tests/lib/services/_public/sns-proposals.services.spec.ts
After the recent Sns Governance behavior change, `list_proposals: payload_text_rendering` is no longer returned as part of a proposal. This breaks the `nns-dapp`, causing the Sns payload to not be rendered under certain conditions.
To reproduce:
- Sign in
- Open any Sns proposals page.
- Wait about 10 seconds to ensure a certified version of the `list_proposals` response is received.
- Click on any proposal card to see its details.
- The proposal payload is not rendered.
- Make `getSnsProposalById` to not use the `snsProposalsStore`.
- Removed `getProposalFromStoreById`.
- Updated.
> Always call sns get proposal on details page

- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/page-objects/NeuronIdCell.page-object.ts
Because we don't use a fixed-width font for the neuron IDs, they don't all have exactly the same width.
This means the copy icons right after them are not aligned, which looks off.
To solve this we define extra grid lines in the table and use them to align the copy icons.
1. Allow specifying multiple grid columns per table columns and multiple grid rows per table row.
2. Specify 2 grid rows per table row and 3 grid columns for the first table column of the neurons table.
3. Use the extra grid columns for the copy icon and the empty space and the extra row for the neuron tags.
4. Change the `NeuronIdCell` component to use separate elements for the ID and the copy icon so they go into separate columns.
2. Tested manually at …
> NNS1-3092: Align neuron ID copy icons in table

- dfx.json
> Update snsdemo to release-2024-06-05

- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
Share the additional space more equally between columns.
1. Apply `1fr` column template to every column except the actions column.
2. Make the neuron state right-aligned again.
Drive-by: Remove the `gap` style on the `ResponsiveTableRow` because the table already defines a `column-gap` [here](https://github.com/dfinity/nns-dapp/blob/c8319c303d93cbc0c12181a78054ed0ae815ed85/frontend/src/lib/components/ui/ResponsiveTable.svelte#L113).
not yet
> NNS1-3092: Neurons table column spacing

- frontend/src/lib/components/neurons/NeuronsTable/NeuronStateCell.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/page-objects/NeuronStateCell.page-object.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
- frontend/src/tests/page-objects/Tooltip.page-object.ts
Spawning neuron cards have a tooltip explaining spawning.
To keep feature parity, we should have the same tooltip in the neurons table.
Add a tooltip on the neuron state table cell if it's a spawning neuron state.
1. Unit test added
2. Page objects added/updated.
not yet
> NNS1-3092: Tooltip on spawning neuron state

- CHANGELOG-Nns-Dapp-unreleased.md
Remove [already released entry](https://github.com/dfinity/nns-dapp/blob/cfa63fc45bd2e6c751fe2eb0a38e4246b23439ef/CHANGELOG-Nns-Dapp.md?plain=1#L20) from the unreleased changelog to keep it clean.
This line was already removed in https://github.com/dfinity/nns-dapp/pull/5008 after the previous release.
But it was accidentally merged back in https://github.com/dfinity/nns-dapp/pull/5014.
- Remove 1 entry.
Changelog only changes.
Not necessary.
> Remove obsolete record from the unreleased changelog

- rust-toolchain.toml
> Update rust version to 1.78.0

- frontend/src/tests/page-objects/Tooltip.page-object.ts
Tooltip targets have a `describedby` attribute that should match the `id` attribute of the tooltip.
This helps both screen readers and tests match targets too the correct tooltip.
In `Tooltip.page-object.ts` throw an error if there is not exactly one tooltip matching the ID.
This does not catch cases where only one tooltip is created during the test so this is not guaranteed to help screen readers.
But it does help avoid confusion when debugging tests.
Changed the [tooltip ID](https://github.com/dfinity/nns-dapp/blob/4c3d659b021f418be35d4e28934cebc6eb3cda54/frontend/src/lib/components/neurons/NeuronsTable/NeuronStateCell.svelte#L13) in NeuronStateCell to be not unique and noticed the `NeuronsTable.spec.ts` test fail.
not necessary
> Check that there is only 1 tooltip with matching ID

- frontend/src/lib/components/ic/VotingPowerDisplay.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/lib/components/ui/Hash.svelte
- frontend/src/lib/components/ui/IdentifierHash.svelte
- frontend/src/lib/components/ui/TooltipIcon.svelte
- frontend/src/tests/lib/components/ui/TooltipIcon.spec.ts
We have several components where we create tooltip IDs dynamically because they need to be uniq across multiple tooltips.
This is now supported by the `Tooltip` component itself via `idPrefix`.
1. Remove custom code to generate unique tooltip IDs and use `idPrefix` instead.
2. Support forwarding `idPrefix` in `Hash` and `TooltipId` components.
2. Existing tests pass.
not necessary
> Use Tooltip idPrefix to make the code cleaner

- frontend/src/lib/components/ui/Logo.svelte
- frontend/src/lib/components/ui/LogoWrapper.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/components/universe/UniverseLogo.svelte
- frontend/src/lib/components/universe/VoteLogo.svelte
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/components/universe/VoteLogo.spec.ts
- frontend/src/tests/page-objects/Logo.page-object.ts
- frontend/src/tests/page-objects/LogoWrapper.page-object.ts
- frontend/src/tests/page-objects/SelectUniverseCard.page-object.ts
- frontend/src/tests/page-objects/UniverseLogo.page-object.ts
- frontend/src/tests/page-objects/VoteLogo.page-object.ts
For consistency, the logo on the "all actionable proposals" tab should have the same size as the logos on the other universe tabs.
1. Extract `LogoWrapper` component from `Logo` component. The wrapper takes care of the size and framing.
2. Use the `LogoWrapper` component in a new `VoteLogo` component.
3. Use the `VoteLogo` component in `UniverseLogo` component.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/proposals/?u=qsgjb-riaaa-aaaaa-aaaga-cai
Before:
After:
not necessary
> Make vote icon consistent with universe icons

- frontend/package-lock.json
We release release ic-js [2024.06.11-1630Z](https://github.com/dfinity/ic-js/releases/tag/2024.06.11-1630Z). This PR upgrade the libraries to hook on the new version number.
> build: bump next

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/dfx-snapshot-install
When extracting an snsdemo snapshot, we put the data in a directory in the dfx cache.
There are several problems with this:
1. The snapshot determines which version of dfx it is run with. But we don't know this until after the state is extracted. So when we determine the dfx cache directory, it might be a cache directory for a different version than the snapshot is created for.
2. This also means that if your dfx version is updated, the install script will look for the state in a different cache directory and not find it. This means you get a clean snapshot while you may have wanted to reuse the state you've created earlier.
3. On DevEnv, the cache directory exists on a different disk volume. This means that moving the directories in place is as slow as copying.
1. Search across all dfx …
> Change dfx state directory logic

- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/page-objects/NeuronIdCell.page-object.ts
When there are no tags, the empty tags element can still cause line wrapping in the neuron ID cell.
See
https://github.com/dfinity/nns-dapp/assets/122978264/1cc50a20-0fde-416c-85e5-e919d1a130cf
Remove the tags element if there are no tags.
2. Tested manually.
not necessary
> NNS1-3092: Fix wrapping of empty tags element

- dfx.json
> Update snsdemo to release-2024-06-12

- scripts/sort-svelte-imports
- scripts/sort-svelte-imports.vim
I made a Vim keyboard shortcut for myself to sort Svelte imports and I thought it could be useful if made available as a script.
1. Add a Vim script file to provide a function to sort Svelte imports.
2. Add a bash script which can run the Vim function on specified files.
Manually
not necessary
> Vim script to sort svelte imports

- rs/backend/src/accounts_store/schema/proxy/migration.rs
- rust-toolchain.toml
The automatic [Rust version upgrade](https://github.com/dfinity/nns-dapp/pull/5051) failed because of a [lint error](https://github.com/dfinity/nns-dapp/actions/runs/9510216178/job/26214335680?pr=5051).
1. Bump Rust to 1.79.0
2. Fix the lint error.
`scripts/lint-rs` passes
not necessary
> Bump Rust to 1.79 and fix lint

- frontend/src/lib/services/nns-vote-registration.services.ts
- frontend/src/lib/services/vote-registration.services.ts
- frontend/src/tests/lib/services/sns-vote-registration.services.spec.ts
Voting for the SNS proposals should not trigger the reloading of NNS actionable items.
- Moved the NNS actionable reloading logic from the general function (used by both NNS and SNS) to an NNS-specific function.
- Added a test to ensure that voting on SNS proposals does not trigger NNS reloading. Verified that the test fails without the changes.
Not necessary.
> Move nns actionable reloading

- frontend/src/lib/derived/sns/sns-sorted-neurons.derived.ts
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/tests/lib/derived/sns/sns-sorted-neurons.derived.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
We don't show neurons without stake or maturity.
With the neurons table for SNS neurons, this logic was accidentally lost.
Because the neurons table does its own sorting, we weren't using the sorted stores, but the sorted stores also took care of the filtering.
1. Define `definedSnsNeuronStore`, analogous to [definedNeuronsStore](https://github.com/dfinity/nns-dapp/blob/3315aa7c51fe405c3139673bc269ece6979ea70d/frontend/src/lib/stores/neurons.store.ts#L87) for NNS neurons.
2. Use `definedSnsNeuronStore` in `SnsNeurons.svelte`.
1. Unit tests for `definedSnsNeuronStore`.
2. Add tests for `SnsNeurons`.
3. Add analogous tests for `NnsNeurons`.
4. Test manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=br5f7-7uaaa-aaaaa-qaaca-cai
not yet
> NNS1-3093: Filter out SNS neurons without stake

- frontend/src/lib/components/neurons/NeuronsTable/NeuronStakeCell.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
In the neuron cards we set the `detailed` prop on the `AmountDisplay` to show more digits if necessary:
https://github.com/dfinity/nns-dapp/blob/a85f919cbde9f18faae5bed08c70d6a91b72b0a3/frontend/src/lib/components/neurons/NnsNeuronAmount.svelte#L32
So for consistency we should do the same in the neurons table.
Add `detailed` prop in `NeuronStakeCell.svelte`.
Unit test added.
not yet
> NNS1-3092: Show detailed neuron stake in table

- frontend/src/lib/components/ui/TooltipIcon.svelte
We want to put tooltip icons in the neurons table rows.
On mobile, you have to touch the tooltip target for the tooltip to appear.
The table rows are actually links so if you touch anything in it, it opens the neuron details view.
1. Add a `preventDefault` click handler on the tooltip icon component.
Can't really be unit tests because of limitations in the testing framework.
not necessary
> Prevent clicking on tooltip icons to follow links

- frontend/src/tests/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronDissolveDelayItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronMaturitySection.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronStateItemAction.spec.ts
- frontend/src/tests/lib/components/ui/CommonItemAction.spec.ts
- frontend/src/tests/lib/components/ui/TooltipIcon.spec.ts
- frontend/src/tests/page-objects/TooltipIcon.page-object.ts
`TooltipIconPo.getText()` is masking `getText()` on the base class.
I want to add the possibility to pass the tooltip content as a slot to the `TooltipIcon` component and I want to add a test which calls `TooltipIconPo.getText()` (from the base class) to make sure the slot doesn't end up in the tooltip target as opposed to the tooltip content.
Rename TooltipIconPo.getText() to getTooltipText()
Unit tests updated.
not necessary
> Rename TooltipIconPo.getText() to getTooltipText()

- frontend/src/lib/components/ui/TooltipIcon.svelte
- frontend/src/tests/lib/components/ui/TooltipIcon.spec.ts
- frontend/src/tests/lib/components/ui/TooltipIconTest.svelte
We want to be able to use rich tooltips with tooltip icons to display maturity in the neurons table.
Tooltips already support rich content by using a slot instead of a prop.
1. Make `text` optional on `TooltipIcon`
2. Pass the `slot` (if present) on to `Tooltip` as tooltip content.
2. Tested manually in another branch.
not necessary
> Support content slot in TooltipIcon

- scripts/sort-svelte-imports
I found some issues when trying to use the Svelte import sort script:
1. It breaks when no arguments are passed
2. It breaks when it wants to fix zero files
1. Check arguments as `${1:-}` which doesn't break if the variable is empty.
2. Output what strategy it uses for choosing which files to fix.
3. Check if the list is empty and do nothing if it is.
Manually ran the script:
1. From a branch without changes
2. From a branch with changes but none of them svelte files
3. From a branch with changes in svelte files
4. With a svelte file as an argument
not necessary
> Svelte import sort script fixes

- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
We want to show maturity in the neurons table.
In this PR we just add fields to the `TableNeuron` type and don't display anything yet.
1. Add `availableMaturity` and `stakedMaturity` fields to the `TableNeuron` type.
2. Populate the fields in `tableNeuronsFromNeuronInfos` and `tableNeuronsFromSnsNeurons`.
2. Mock updated.
3. Fixed a few cases where we weren't using the default test values but we hadn't noticed yet because the value we used didn't differ in relevant way (but now it does).
not yet
> NNS1-3134: Add maturity fields to TableNeuron

- dfx.json
> Update snsdemo to release-2024-06-19

- scripts/did2rs.sh
`did2rs.sh` uses `didc` to create Rust from Candid files.
It adds a step to make types and fields public.
But newer versions of `didc` already do this.
So the extra step is not necessary anymore.
And in a beta version I tried this unnecessary step was causing problems.
Remove the step to add `pub` to types and fields.
CI has [tests](https://github.com/dfinity/nns-dapp/blob/ca8d8c26be5d64d9319e3ccfce8a2b7e4e3a1a1d/.github/workflows/checks.yml#L146-L153) to make sure generated code is the same.
not necessary
> Remove unnecessary step from did2rs.sh

- Cargo.lock
- Cargo.toml
> Update IC Cargo Dependencies to release-2024-06-19_23-01-base

- CHANGELOG-Nns-Dapp-unreleased.md
- declarations/used_by_proposals/nns_governance/nns_governance.did
- declarations/used_by_proposals/nns_registry/nns_registry.did
- declarations/used_by_proposals/sns_wasm/sns_wasm.did
- dfx.json
- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
There are new proposal parameters to support tSchnorr.
See https://forum.dfinity.org/t/threshold-schnorr-facilitating-brc-20-trading-solana-integration-certificate-signing-and-more/28993
We want to be able to render them in NNS dapp.
Ran
```
./scripts/update_ic_commit --crate proposals --ic_commit 2538538e0132b394f302c49fd91da23fc4cee284
./scripts/proposals/did2rs
```
I'll add a test to `scripts/nns-dapp/test-proposal-payload` once `ic-admin` supports the new parameters.
> Update proposals candid bindings for tSchnorr

- frontend/src/lib/components/ui/ResponsiveTable.svelte
The rendering logic for the first column header in the `ResponsiveTable` component is now identical to the logic for the middle columns. So we can simply this by merging the logic.
Remove the logic for the first column header and rely on the logic for the middle columns.
not necessary
> Merge logic for first and middle column headers

- HACKING.md
Make the documentation more usable for external people.
And a step to run `scripts/setup` at the beginning of instructions to run nns-dapp.
not tested
not necessary
> Add scripts/setup to HACKING

- frontend/src/lib/types/responsive-table.ts
- frontend/src/lib/utils/responsive-table.utils.ts
- frontend/src/tests/lib/utils/responsive-table.utils.spec.ts
When we make the neurons table sortable we want to use the following logic:
1. If you click on a column header, the rows should be sorted by that column.
2. If you click again on the same column header, the rows should be sorted by the reverse of that column.
3. When changing sort order, ties in the chosen column should be broken based on the previous order.
So if you sort by stake and then by dissolve delay, neurons with the same dissolve delay should be sorted by stake because that was the previous order.
This PR does not make any UI changes but adds the utility that implements the above logic.
1. Add optional `reversed` field to the elements of `ResponsiveTableOrder`.
2. Add `selectPrimaryOrder` function which creates a new order following the above logic.
3. Support the `reversed` …
> NNS1-3135: Add util for table resorting logic

- frontend/src/lib/stores/neurons-table.store.ts
- frontend/src/tests/lib/stores/neurons-table.store.spec.ts
When changing the sorting order on the neurons table, we want to be able to navigate without losing the order.
(Resetting the order on page reload is OK, at least for now.)
This PR adds a Svelte store to keep the ordering across navigation but does not use it yet.
Add `neuronsTableOrderStore`.
2. Tested manually in another branch.
not necessary
> NNS1-3135: Neurons table order store

- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/page-objects/ResponsiveTable.page-object.ts
We want to make table columns sortable by clicking on them, if there is a sort order defined for that column.
In mobile view we only show the first column, but sorting is not done by clicking on the column headers.
So we might have to show 2 versions of the first column header.
To make this easier, this PR only changes the way by which columns are hidden by using an explicit class instead of always hiding everything but the first and last column headers.
1. Add a `desktop-only` class to column headers that should be hidden on mobile.
2. Change the CSS to use this class instead of `:first-child` and `:last-child` selectors.
Add separate unit tests for mobile and desktop column headers.
not necessary
> NNS1-3135: Refactor column header hiding logic

- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
Once we support custom sorting, we want to keep the sort order between navigations.
In this PR we just hook up the sort order to the store. There is no visible difference because there is no way yet for the user to change the contents of the store.
Sort the neurons table based on the order in the `neuronsTableOrderStore` instead of a constant in the component.
Unit test added where the store contents is changed.
not necessary
> NNS1-3135: Sort neurons table based on store order

- frontend/src/tests/lib/routes/Proposals.spec.ts
To maintain clean and up-to-date tests, we’re removing an outdated describe block as the `ENABLE_ACTIONABLE_TAB` feature flag has been removed and the feature is always enabled.
- Unwrap the outdated describe block (not the content).
- Fix a typo ([second commit](https://github.com/dfinity/nns-dapp/commit/3482ddc44fae66dcab27c5fdc7e36e5a589ce959)).
- Pass
Not necessary.
> Unwrap enable actionable tab tests

- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
When implementing custom neurons table sorting, we want to support sorting by maturity and state as well.
1. Add `compareByMaturity` which compares by the sum of available and staked maturity.
2. Add `compareByState` which defines a specific order of the states.
2. Also added coverage for the existing compare function. They were previously tested with `sortNeurons` but that was removed in https://github.com/dfinity/nns-dapp/pull/5104
not necessary
> NNS1-3135: Add comparators for maturity and neuron state

- frontend/src/lib/components/universe/SelectUniverseCard.svelte
- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
The store `actionableProposalIndicationEnabledStore` has a misleading name because it can’t be enabled/disabled but relies on the current page. Additionally, the old name can be confused with enabling the actionable by selector state.
- Rename `actionableProposalIndicationEnabledStore` to `actionableProposalIndicationVisibleStore`.
- Pass.
Not necessary.
> Rename actionable indication store

- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
Some small things I noticed that I don't want to clutter another large PR with.
1. Use `runResolvedPromises` instead of `setTimeout`.
2. Remove `getRowStyle` from tests for which it's unrelated.
3. Put `getRowStyle` related tests together. 
yes
not necessary
> Small test cleanups

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api/governance.api.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
NNS dapp does not display empty neurons and just filters them out.
The governance canister is going to have a new feature where empty neurons can be excluded.
The API was already added so we can start passing the relevant parameter to benefit from it as soon as it's available.
Pass `includeEmptyNeurons: false` to `listNeurons`.
1. Unit test updated.
2. Tested manually that nothing breaks, but the functionality is not implemented yet so couldn't be tested.
> Exclude empty neurons with listNeurons

- dfx.json
> bot: Update snsdemo to release-2024-06-26

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-06-26_23-01-base

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
- frontend/src/lib/stores/neurons-table.store.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/stores/neurons-table.store.spec.ts
It's not really useful to sort neurons by ID and it can also be confusing. So UX asked to disable sorting by neuron ID.
1. Disable sorting by neuron ID.
2. Sort neurons by neuron ID in the `NeuronsTable` component before passing them to the `ResponsiveTable` component. This makes sure ties are always broken by neuron ID even though we can no longer indicate this in the table order.
Unit test updated.
> Disable sorting by neuron ID

- scripts/sort-svelte-imports
- scripts/sort-svelte-imports.vim
The svelte import sorting script sort import statements based on the imported path, but it does not sort the things imported within a single import statement.
Also the script wasn't working properly when run from a different directory.
1. Add code to the Vim script that finds imports that import multiple things, puts those things on individual lines and then sorts them (putting imports prefixed with `type ` last, similar to how `pretties` does it.
2. Drive-by: Some small changes to make the regexes more strict.
3. Fix the shell script to produce the correct absolute paths with the script is run from a different directory.
Manually
> Svelte import sorting fixes

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/common/ResponsiveTableSortModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/common/ResponsiveTableSortModal.spec.ts
- frontend/src/tests/page-objects/ResponsiveTableSortModal.page-object.ts
When sorting the table on desktop, you can click on the column headers.
For mobile we need a different UI with a modal to select a sorting option.
This PR just adds that modal but does not connect it to the table yet.
Here is a demo of it integrated in the neurons table: https://mecbw-6maaa-aaaaa-qabkq-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=mecbw-6maaa-aaaaa-qabkq-cai
Add `frontend/src/lib/modals/common/ResponsiveTableSortModal.svelte` component.
The modal binds and updates the `order` prop and closes as soon as a selection is made.
2. Manually
not yet
> NNS1-3136: Add modal for mobile table sorting

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/ui/ResponsiveTable.svelte
UX asked to be changed to make the icon look more actionable and for consistency with the icon that will be added to the neurons table for sorting.
Before:
<br>
After:
<br>
Change the table header icon to `--primary` color.
Manually
> Change top-right table icon color

- scripts/nns-dapp/test-proposal-payload
This adds the test for https://github.com/dfinity/nns-dapp/pull/5097
1. Added a test to `scripts/nns-dapp/test-proposal-payload` which includes schnorr fields in the `RecoverSubnetPayload`.
2. Add a `wdiff` step to make debugging easier.
pass
not necessary
> Test for schnorr proposal

- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/e2e/neurons-table.spec.ts
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/routes/Neurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
- frontend/src/tests/page-objects/simple-base.page-object.ts
Feature flag `ENABLE_NEURONS_TABLE` has been enabled since 2 releases.
1. Remove the code conditional on `ENABLE_NEURONS_TABLE`.
2. Remove unused i18n messages.
1. Remove tests where `ENABLE_NEURONS_TABLE` is disabled.
3. Stop enableing `ENABLE_NEURONS_TABLE` in unit tests and e2e tests.
4. Remove unused methods from page objects.
5. Remove `timeout` param from `waitForAbsent`, which was added in https://github.com/dfinity/nns-dapp/pull/2542 and never used.
6. Add `tid` param to `waitForAbsent` so it can be used to wait for the spinner to disappear instead of the skeleton cards.
not necessary
> Clean up ENABLE_NEURONS_TABLE

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/modals/common/ResponsiveTableSortModal.svelte
- frontend/src/tests/lib/modals/common/ResponsiveTableSortModal.spec.ts
To provide feedback that a selection was made, we add a delay before closing the mobile table sort modal.
In `frontend/src/lib/modals/common/ResponsiveTableSortModal.svelte` add a delay before dispatching the close event.
1. Use fake timers to test the delay in unit tests.
2. Manually at https://mwewp-s4aaa-aaaaa-qabjq-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=mwewp-s4aaa-aaaaa-qabjq-cai
> Add a delay before closing the sorting modal

- frontend/src/lib/modals/common/ResponsiveTableSortModal.svelte
- frontend/src/tests/lib/modals/common/ResponsiveTableSortModal.spec.ts
PM/UX wanted a shorter delay.
Change the delay from 400ms to 250ms.
1. Unit test updated.
2. Manually at https://mwewp-s4aaa-aaaaa-qabjq-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=mwewp-s4aaa-aaaaa-qabjq-cai
not necessary
> Shorter sort modal delay

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/constants/routes.constants.ts
- frontend/src/lib/routes/Staking.svelte
- frontend/src/routes/(app)/(nns)/staking/+layout.svelte
- frontend/src/routes/(app)/(nns)/staking/+page.svelte
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
Currently the neurons view has a universe picker on the left.
We plan to make it more like the tokens table where there is no left-nav but rather a first step where you choose the project and then a view with a back button just for that project.
The table with projects with be at `/staking` and the neurons table , but without universe picker left-nav, will continue to be at `/neurons.
In this PR we just add the scaffolding for the `/staking` path.
1. Add `AppPath.Staking` constant.
2. Add mostly empty route files for `/staking`.
3. Making the "Neurons Staking" tab navigate to `/staking` instead of `/neurons?u=...` when `ENABLE_PROJECTS_TABLE` is enabled.
2. Tested manually.
not yet
> NNS1-3094: Add staking path

- frontend/src/routes/(app)/(u)/(list)/neurons/+layout.svelte
- frontend/src/tests/routes/app/neurons/layout.spec.ts
When we have the staking projects table, it will replace the universe navigation for neurons.
In that case we also need a back button to get back from the neurons page to the staking projects page.
When `ENABLE_PROJECTS_TABLE` is enabled on the neurons page:
1. Remove the universe navigation
2. Add a back button
2. Tested manually on https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
not yet
> NNS1-3094: Remove universe nav and add back button on neurons page

- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
We want to use the `ResponsiveTable` component for the staking projects table.
In this PR we define a `TableProject` type to use as the row data for the table and add a simple first version of a function to create the row data.
1. Add `frontend/src/lib/types/staking.ts` with the `TableProject` type.
2. Add `frontend/src/lib/utils/staking.utils.ts` with `getTableProjects` to create the row data for the projects table (which will be added in another PR).
2. Tested manually in another branch which already has a simple projects table: https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: Add TableProject type

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/proposals.constants.ts
- frontend/src/tests/workflows/NnsProposalDetail.spec.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
When you choose "All Proposals" on the Voting tab, by default we do not show all proposals.
By default we only show proposals with 8/15 topics and 1/5 proposal statuses.
I checked with PM and they see no reason for doing this.
Make the default topic and status filters empty.
2. Tested manually at: https://mrfq3-7eaaa-aaaaa-qabja-cai.dskloet-ingress.devenv.dfinity.network/proposals/?u=mrfq3-7eaaa-aaaaa-qabja-cai
3. Also tested that this only applies if you hadn't already used nns dapp with your browser profile.
> Clear default proposal filters

- frontend/src/lib/components/staking/ProjectActionsCell.svelte
- frontend/src/lib/components/staking/ProjectTitleCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/routes/Staking.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/staking.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/mocks/staking.mock.ts
- frontend/src/tests/page-objects/ProjectTitleCell.page-object.ts
- frontend/src/tests/page-objects/ProjectsTable.page-object.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
To render a table of staking projects to choose from to navigate to a neurons page.
1. Add `ProjectTitleCell` which is mostly a copy of [TokenTitleCell](https://github.com/dfinity/nns-dapp/blob/main/frontend/src/lib/components/tokens/TokensTable/TokenTitleCell.svelte).
2. Add `ProjectActionsCell` which just has the right angle icon indicating that there are more details.
3. Add `ProjectsTable` with just 2 columns. More will be added later.
4. Page objects added.
5. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: Use responsive table on staking page

- dfx.json
- frontend/src/tests/e2e/sns-governance.spec.ts
This PR replaces the bot PR at https://github.com/dfinity/nns-dapp/pull/5151.
The test environment now has deterministic names instead of random 5 letter names.
1. Updated snsdemo version in dfx.json.
2. Change the expectation on the SNS name in `frontend/src/tests/e2e/sns-governance.spec.ts`.
CI
not necessary
> human: Update snsdemo to release-2024-07-03

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-07-03_23-01-storage-layer-disabled

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/convert-id
- scripts/convert-id.test
I was looking for a tool to conveniently convert between text, hex, blob and account_identifier but I couldn't find one so I made this.
Script to convert between text, hex, blob and account_identifier formats.
2. Tested manually to create a canister by using the script to create the CMC subaccount to transfer ICP to.
> Script to convert between ID formats

- frontend/src/lib/pages/SnsNeuronDetail.svelte
- frontend/src/lib/services/sns-neurons-check-balances.services.ts
- frontend/src/lib/stores/checked-neurons.store.ts
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
- frontend/src/tests/lib/stores/checked-neurons.store.spec.ts
Topping up a neuron is a 2 step process.
1. Transfer tokens to the neuron account.
2. Notifying the governance canister to refresh the neuron.
If the process is interrupted between step 1 and 2, your tokens are now missing.
Because of this possibility, we compare the neuron account balance of SNS neurons with the neuron stake and refresh the neuron if there is a difference.
Currently we do this for all neurons of an SNS every time we load the neurons of that SNS, which is when you navigate to the neurons table for that SNS. This is overkill since this is really only a fallback mechanism. It also resulted in loading neurons in a different way for actionable proposals to avoid doing the check even more often.
It should be enough to only check a neuron when opening its details page and at …
> Refresh SNS neuron from details page if needed

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/nns-dapp/test-cmc-notify
Creating or topping up a canister is a 2-step process:
1. Sending ICP to a subaccount of the CMC.
2. Notifying the CMC about the transaction.
Both steps are done in the frontend, but if the process is interrupted and
the second step is not performed, the ICP could go missing.
So the nns-dapp canister monitors the ledger for such transactions and also
notifies the CMC about them.
Because this is fallback behavior, it's easy not to notice it when this is not working.
And indeed this recently got broken on the test environment because in order to fix a vulnerability in the CMC, the nns-dapp got exclusively whitelisted to do this notifying on behalf or other principals. But on the test environment, nns-dapp has a different canister ID so it wasn't whitelisted.
This is now fixed and I want to …
> Test CMC notify fallback

- .github/workflows/checks.yml
- scripts/convert-id
- scripts/convert-id.test
It can be useful to create or parse addresses in the [ICRC1 format](https://internetcomputer.org/docs/current/references/icrc1-standard#textual-encoding-of-accounts).
Add `icrc1` as a supported input and output format to `scripts/convert-id`.
1. Unit test script extended.
2. Unit test script added to CI.
not necessary
> Support icrc1 format in convert-id

- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-ic-cargo-deps.yaml
- .github/workflows/update-proposals.yml
- .github/workflows/update-rust.yml
- .github/workflows/update-sns-aggregator-response.yml
- .github/workflows/update-snsdemo.yml
Reduce the maintenance burden on IDX.
Use the `GIX_CREATE_PR_PAT` GitHub secret instead of `GIX_BOT_PAT`.
CI should still pass.
If things break later, we'll deal with it then.
not necessary
> Replace GIX_BOT_PAT with GIX_CREATE_PR_PAT

- scripts/convert-id
- scripts/convert-id.test
I had to figure out how to create a neuron subaccount to debug something and once I figured it out, I thought it would be useful to add it to the conversion script so I don't have to figure it out again in the future.
Add `--as_neuron_subaccount` flag to `convert-id` which can be used to create the subaccount used to create neuron accounts.
1. Added unit test with made up data.
2. Added unit test with data matching my test environment.
3. Tested manually to recreate my own prod neuron account, like this:
```
MY_PRINCIPAL="..." # from my account
MY_NEURON_NONCE="..."  # from the staking transaction on the dashboard
GOVERNANCE_CANISTER_ID="rrkah-fqaaa-aaaaa-aaaaq-cai"
NEURON_SUBACCOUNT="$(scripts/convert-id --input text --output hex --as_neuron_subaccount "$MY_PRINCIPAL" …
```
> Support neuron subaccounts in convert-id

- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/TokensPage.page-object.ts
This PR introduces a button to initiate the import token process, as part of the broader import token feature. It’s behind a feature flag, ensuring no changes are visible to the end user.
- Added a new label.
- Added a new button in the token table.
- Tested the button visibility with and without the feature flag enabled.
Not yet
> Import token button

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/canisters/ledger.rs
- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/periodic_tasks_runner.rs
When an NNS dapp user creates or tops up a canister, the FE make a transaction to the CMC. The nns-dapp canister sees this transaction (because it looks at every ICP ledger transaction) and then notifies the CMC to finish the creation/topup.
More than 2 years ago we had a different mechanism where the FE makes a transaction to the nns-dapp. Then nns-dapp sees that transaction of forwards the ICP to the CMC and notifies it.
The code for this second mechanism still exists in the nns-dapp canister but hasn't been used by the frontend for over 2 years.
Having the extra code is confusing and a maintenance burden so we should remove it.
Remove the canister code for the old canister creation/topup flow.
The test added in https://github.com/dfinity/nns-dapp/pull/5166 still passes.
> Remove old CMC notify mechanism

- frontend/src/lib/services/sns-neurons-check-balances.services.ts
- frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
Staking an SNS neuron is a 2-step process:
1. Transfer tokens to the neuron account.
2. Notify the governance canister to claim the neuron.
If the process is interrupted between steps 1 and 2, the tokens are now missing.
To be able to recover from this, we create neuron accounts in a deterministic sequence.
Currently every time you go to the neurons table view we check all the neuron accounts of all the existing neurons and the non-existing neurons until the first account without balance. This is all done in a single function.
Because this is just a fall-back mechanism, this is overkill.
We want to only check neuron accounts once per neuron per session.
1. For existing neurons we do this only when you visit their neuron details page. This is done in …
> Add claimNextNeuronIfNeeded function

- frontend/src/lib/services/sns-neurons-check-balances.services.ts
- frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
It's possible for an SNS neuron to be transferred to another user by removing the permissions for one user and adding permissions for another user. For example idgeek.app has a service to sell SNS neurons. This service also works with NNS dapp controlled neurons because they fully take over your Internet Identity. Since this will not change the ID of the neuron, it will still appear in the sequence of neuron IDs for the original user. So we must take extra care to make sure it does not appear in the UI for the original user.
This actually happened and was reported by a user on the forum here: https://forum.dfinity.org/t/staking-problems-within-nns-app/3204/83
It was fixed in https://github.com/dfinity/nns-dapp/pull/4484 but would have been broken again by the [recently …
> Do not show transferred SNS neurons after claiming

- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
We refresh a neuron if needed once per session per neuron if you visit the neuron details page.
This is a fallback mechanism only needed in case a neuron top-up gets interrupted so we don't need to do it very often as long as there is some way to recover.
I found that `getSnsNeuron` actually also does this every time.
This is overkill.
Remove the neuron refresh code from `getSnsNeuron`.
1. Unit tests adapted and removed.
2. Tested manually that transferring tokens to the neuron account still results in a top-up after visiting the neuron details page.
not necessary
> Remove refresh from getSnsNeuron

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
Staking or topping up an SNS neuron is a 2-step process:
1. Transfer tokens to the neuron account
2. Claim or refresh the neuron
If the process is interrupted after step 1, your tokens might go missing. So we want to be able to recover from this.
Currently we check the neuron account balance of all your neurons every time neurons are synced, for example when you navigate to the neurons table.
We already added checking a neuron when you navigate to its details page in https://github.com/dfinity/nns-dapp/pull/5169
So as long as we are able to recover newly staked neurons we can stop doing this every time we sync neurons.
1. Call `claimNextNeuronIfNeeded` from `SnsNeurons`.
2. Remove neuron checking code from `syncSnsNeurons`.
1. Unit test added for `SnsNeurons.svelte`.
2. Unit test removed …
> Reduce fallback neuron refreshing

- .github/workflows/checks.yml
We have a number of small bash scripts which are used to test something on CI.
Currently each of these is run on a separate GitHub runner instance which installs its own tools it needs.
This seems like overkill.
1. Combined a number of jobs into a single `small-tests` job.
2. Run this job on both MacOS and Linux.
There are a few more small jobs that don't currently work on MacOS so I didn't change them.
See https://github.com/dfinity/nns-dapp/actions/runs/9892524481
not necessary
> Combine small CI tests in a single job

- frontend/src/lib/services/actionable-sns-proposals.services.ts
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
We load neurons for all SNSes for actionable proposals. If we put them in the store they can be used to display on the neurons table etc.
There was a comment saying we shouldn't do this because it prevents `syncSnsNeurons` from checking neurons but
1. It doesn't actually prevent anything, and
2. We no longer check neurons in `syncSnsNeurons`.
1. Rename `loadNeurons` to `loadSnsNeurons` so the context is clearer when the function is used in another file.
2. Use `loadSnsNeurons` to load neurons into the store instead of just querying them in `actionable-sns-proposals.services.ts`.
3. Drive-by: Remove a comment from `syncSnsNeurons` about checking neurons which it no longer does.
Unit test adapted to check that the `snsNeuronsStore` is populated.
not necessary
> Store SNS neurons after querying for actionable proposals

- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/mocks/staking.mock.ts
We want to render the number of neurons per project in the staking projects table.
This PR just added the field to the data but does not render it yet.
1. Add `neuronCount` field to `TableProject`.
2. Pass `neuronsStore` and `snsNeuronsStore` to `getTableProjects` to get the number of neurons for each project.
Unit test added for `getTableProjects`.
not yet
> NNS1-3094: Add neuronCount field to TableProject

- frontend/src/lib/components/staking/ProjectNeuronsCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/page-objects/ProjectNeuronsCell.page-object.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
We want to show the number of neurons a user has in each project.
1. Add `ProjectNeuronsCell` component.
2. Add a column for the `ProjectNeuronsCell` to the `ProjectsTable` component.
2. Page objects added.
3. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: And neuron count column to projects table

- frontend/src/lib/components/launchpad/ProjectCardSwapInfo.svelte
- frontend/src/lib/components/project-detail/ParticipateButton.svelte
- frontend/src/lib/components/project-detail/ProjectMetadataSection.svelte
- frontend/src/lib/components/project-detail/ProjectStatusSection.svelte
- frontend/src/lib/components/project-detail/ProjectTimelineUserCommitment.svelte
- frontend/src/lib/components/project-detail/ProjectUserCommitmentLabel.svelte
- frontend/src/lib/derived/sns/sns-projects.derived.ts
- frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
- frontend/src/lib/pages/ProjectDetail.svelte
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/sns-finalization.services.ts
- frontend/src/lib/stores/sns.store.ts
- frontend/src/lib/types/project-detail.context.ts
- frontend/src/lib/types/sns-summary-wrapper.ts
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/tests/lib/components/project-detail/ProjectCommitment.spec.ts
- frontend/src/tests/lib/components/project-detail/ProjectInfoSection.spec.ts
- frontend/src/tests/lib/components/project-detail/ProjectMetadataSection.spec.ts
- frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
- frontend/src/tests/lib/components/project-detail/ProjectTimelineUserCommitment.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseList.spec.ts
- frontend/src/tests/lib/types/sns-summary-wrapper.spec.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/mocks/sns.mock.ts
We want to stop using the `summary.swap` field because it's deprecated and everything on it is available in other ways.
One of the things we get from the `swap` field is the `lifecycle`.
In this PR we introduce a getter on `SnsSummaryWrapper` to determine in a single place how we get the lifecycle.
This will make it easy to switch over in another PR.
1. Add `getLifecycle()` to `SnsSummaryWrapper` which returns the lifecycle from an `SnsSummary`.
2. Use `SnsSummaryWrapper` and `getLifecycle()` instead of getting `summary.swap.lifecycle` directly.
3. Add `override()` to `SnsSummaryWrapper` because `SnsSummaryWrapper` can't be spread into a new `SnsSummary` object.
1. Unit tests added for `SnsSummaryWrapper`.
2. Existing unt tests updated.
not necessary
> Get summary lifecycle through SnsSummaryWrapper

- .github/workflows/update-next.yml
When making changes in gix-components or ic-js, we always need to pull in the changes into nns-dapp.
This is very straightforwards and is kind of pointless to review.
If those changes can be made by a bot, only one person needs to review it so nobody needs to be blocked.
Add a workflow which can be used to automatically update gix-components and/or ic-js.
This PR was [created](https://github.com/dfinity/nns-dapp/actions/runs/9938705200/job/27451714562) with it: https://github.com/dfinity/nns-dapp/pull/5194
I just changed the PR title after doing that test.
not necessary
> Bot for bumping gix-components or ic-js

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/lib/services/icp-ledger.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/services/icp-ledger.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/workflows/NnsProposalDetail.spec.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
`list_neurons` is broken with the Ledger HW (current version 2.4.9) because it does not accept a `ListNeurons` with the `includeEmptyNeurons` field.
1. Make `includeEmptyNeurons` a parameter on `queryNeurons`.
2. Set `includeEmptyNeurons` to `undefined` when calling `queryNeurons` for the hardware wallet.
3. and to `false` otherwise.
2. Manually tested.
> Work around list_neuron not working with HW

- frontend/src/lib/components/staking/ProjectNeuronsCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
To make it clear that the neuron count is not 0 when the user is not signed in or the neurons haven't loaded yet.
1. Pass `neuronsStore` instead of `definedNeuronsStore` to be able to tell if NNS neurons were loaded.
2. Filter NNS neurons without valid stake as was previously done in `definedNeuronsStore`.
3. Use `undefined` when the user is not signed in, or neurons haven't loaded, to indicate that neuron count is unavailable.
4. Render `undefined` as `-/-` in the neurons cell.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: Show -/- instead of 0 when neuron count not available

- frontend/src/lib/routes/Staking.svelte
- frontend/src/tests/lib/routes/Staking.spec.ts
To give the user extra information about staking if we know the user has never staked.
If neurons are loaded and we can tell the user has 0 neurons, show the same banner we show when the user is not signed in, but without the sign-in button.
2. Tested manually with anchor 10002 at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: Show banner when user never staked

- frontend/src/lib/components/staking/ProjectActionsCell.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
We don't want people to navigate to an empty neurons table.
So the table rows for projects without neurons should not be clickable and should not have an `>` icon.
1. Set `rowHref` to `undefined` for rows that don't have a positive number of neurons.
2. Do not render the action icon if `rowHref` is undefined.
1. Row href is now tested in the same tests as neuron counts to make the relationship clear.
2. Unit test added.
3. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: Make rows without neurons not clickable

- frontend/static/manifest.json
Using `.raw` for the mobile icons is no longer necessary.
- remove `.raw` from the manifest icon section.
Demo link: https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/
- Manually added to the home screen and tested that the icon looks the same as the current version from the mainnet on both iOS and Android.
Not necessary
> Remove raw from icons url

- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/mocks/staking.mock.ts
We want to show total stake in the staking projects table.
In this PR we just add the data but don't show it in the UI yet.
1. Add `stake` field to `TableProject` type.
2. Calculate the stake for each project in `getTableProjects`.
2. Tested manually in a branch including UI changes.
not yet
> NNS1-3094: Add stake field to TableProject

- frontend/src/lib/components/header/Logout.svelte
- frontend/src/lib/components/header/SettingsButton.svelte
Some account menu entries are rendered as links, while others are rendered as buttons. By default the buttons have an extra padding before and after them.
- Remove default button padding from account menu entries.
- Manually.
| <img width="255" alt="Screenshot 2024-07-16 at 17 32 11" src="https://github.com/user-attachments/assets/82b0f31a-1773-46e6-99ed-b46948a22861"> | <img width="254" alt="Screenshot 2024-07-16 at 17 40 47" src="https://github.com/user-attachments/assets/dc15da3d-2ac3-4652-b844-42bcbbe1f183"> | 
Not necessary.
> Remove default button padding

- frontend/src/lib/api/icrc-ledger.api.ts
- frontend/src/lib/identities/ledger.identity.ts
- frontend/src/lib/services/sns-sale.services.ts
- frontend/src/lib/types/ledger.errors.ts
- frontend/src/lib/utils/ledger.utils.ts
- frontend/src/tests/lib/identities/ledger.identity.spec.ts
- frontend/src/tests/lib/services/icp-ledger.services.spec.ts
- frontend/src/tests/lib/utils/ledger.utils.spec.ts
When a function or constructor has multiple parameters, we agreed to use named parameters.
The `LedgerErrorKey` constructor has 2 (optional) parameters which are positional parameters.
Use named parameters in the `LedgerErrorKey` constructor.
Updated.
not necessary
> Use named parameters in LedgerErrorKey

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/identities/ledger.identity.ts
- frontend/src/lib/stores/toasts.store.ts
- frontend/src/lib/types/ledger.errors.ts
- frontend/src/lib/utils/error.utils.ts
- frontend/src/tests/lib/identities/ledger.identity.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/icp-ledger.services.spec.ts
- frontend/src/tests/lib/utils/error.utils.spec.ts
- frontend/src/tests/lib/utils/ledger.utils.spec.ts
Some error messages include URL params, for example if the URL contains a canister ID or account ID that's invalid.
The invalid ID is that repeated in the error message and rendered as HTML instead of text.
This allows HTML injection.
For examples (require being signed in):
* https://nns.ic0.app/wallet/?u=qoctq-giaaa-aaaaa-aaaea-cai&account=%3Ch1%3Ehello%3C/h1%3E
* https://nns.ic0.app/canister/?canister=%3Ch1%3Ehello%3C/h1%3E
One error message needs to be rendered as HTML because it includes a link.
This message was added in https://github.com/dfinity/nns-dapp/pull/4373
To facilitate this, the PR changes error rendering to HTML by default, which is not safe.
We should render text by default and only render HTML when we know the error does not contain user input.
1. Instead of always …
> Do not render error messages as HTML by default

- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
In https://github.com/dfinity/nns-dapp/pull/5202 I made projects without neurons not clickable.
But this makes it not possible to stake those tokens.
We are still working on a way to stake tokens from the projects table but this doesn't need to be part of the MVP.
So we want to make all projects clickable again for now.
Give every `TableProject` a `rowHref` regardless of neurons.
1. As we may go back again on this once there is a way to stake from the projects table, I kept the structure of the tests the same but just changed the expectations.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not necessary
> NNS1-3094: Make projects without neurons clickable again

- frontend/src/lib/components/staking/ProjectStakeCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/page-objects/ProjectStakeCell.page-object.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
We want to show the total stake per project in the projects table.
1. Add `ProjectStakeCell` component to render the stake. When neurons aren't loaded, we render `-/-`. When neurons are loaded but the user doesn't have neurons we render nothing. This matches Figma.
2. Add a column in `ProjectsTable.svelte`
1. Page objects and unit tests added.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> NNS1-3094: Render stake in the projects table

- frontend/src/lib/components/project-detail/ProjectCommitment.svelte
- frontend/src/lib/components/project-detail/ProjectSwapDetails.svelte
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/types/sns-summary-wrapper.ts
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/lib/utils/sns.utils.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
We want to stop using the `summary.swap` field because it's deprecated and everything on it is available in other ways.
One of the things we get from the `swap` field is the `params` object which in turn has several fields.
In this PR we introduce a getters on `SnsSummaryWrapper` to get the fields we care about from `swap.params`.
This will make it easy to switch over in another PR.
1. Add `getSwapDueTimestampSeconds`, `getMinIcpE8s`, `getMaxIcpE8s`, `getMinParticipants`, `getMinParticipantIcpE8s`, `getMaxParticipantIcpE8s`, and `getSnsTokenE8s` to `SnsSummaryWrapper` which returns the corresponding fields from `summary.swap.params`.
2. Use these getters instead of getting fields directly from `summary.swap.params`.
3. Drive-by: Restore `// Use 1 instead of using enum to avoid importing …
> Add getters on SnsSummaryWrapper for fields from swap.params

- frontend/package-lock.json
- frontend/package.json
Agent-js version 1.4.0 does not require `unsafe-eval` anymore which means that we might be able to remove it from our CSP.
Ran `npm install @dfinity/agent@^1.4.0`.
Not tested. Existing tests should pass.
not necessary
> Bump agent-js

- frontend/src/lib/components/ic/AmountDisplay.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
- frontend/src/tests/lib/components/ic/AmountDisplay.spec.ts
- frontend/src/tests/page-objects/AmountDisplay.page-object.ts
Make it easy to render absent token amounts as -/- in a consistent way.
This will be reused in another PR for the stake in the projects table when unavailable.
1. Support `UnavailableTokenAmount` type in `AmountDisplay`.
2. Never render the copy button when the amount is unavailable.
3. Pass `UnavailableTokenAmount` from `TokenBalanceCell` to `AmountDisplay` instead of having separate logic.
1. Added missing unit tests for the copy button in `AmountDisplay`.
2. Added unit tests for `UnavailableTokenAmount`.
3. Existing tokens table tests for `-/-` pass.
not necessary
> Support UnavailableTokenAmount in AmountDisplay

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Currently, if a new topic is added in NNS Governance, we need to follow the following steps:
1. Define new topics in NNS Governance, while disallowing to set followees on them
2. Add new topics to ic-js and NNS Dapp, so that following on them can be shown, but cannot be set
3. Update NNS Governance to allow following to be set
4. Update NNS Dapp to allow following to be set.
After this change, the procedure will be the following:
1. Define new topics in NNS Governance, while followees CAN be set on them
2. Add new topics to ic-js and NNS Dapp, so that following can be shown and set
Show unrecognized topic as "Unknown Topic ($topicId)"
unit tests and manual test
> fix: Show unrecognized topic and "Unknown Topic (...)"

- frontend/src/lib/components/staking/ProjectStakeCell.svelte
- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
In the staking projects table, we show total stake per project.
When the user isn't signed in, or neurons aren't loaded yet, we show `-/-` for the total stake of a project.
We want to include the token symbol in this, as we do in the tokens table.
1. Use `UnavailableTokenAmount` instead of `undefined` to indicate that a stake amount isn't available for a project.
2. Rely on `AmountDisplay` to render the unavailable token amount. (Zero is still not rendered at all.)
2. Tested manually on [DevEnv](https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/) (with feature flag ENABLE_PROJECTS_TABLE)
Before:
After:
not yet
> NNS1-3094: Show token symbol for unavailable stake

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/scripts/build.csp.mjs
We allow `'unsafe-eval'` in the Content Security Policy because it's required by:
1. agent-js
2. protobuf
However
1. Agent-js no longer requires it since [version 1.4.0](https://github.com/dfinity/agent-js/releases/tag/v1.4.0) because "ObservableLog no longer extends Function".
2. NNS dapp no longer depends on protobuf since https://github.com/dfinity/nns-dapp/pull/4672
Remove `'unsafe-eval'` from the CSP.
1. Deployed to https://mkam6-f4aaa-aaaaa-qablq-cai.dskloet-ingress.devenv.dfinity.network/
2. Manually checked that the CSP no longer contains `unsafe-eval`.
3. Clicked around and things don't seem to be completely broken.
Current CSP element:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'none';
connect-src 'self' …
```
> Remove 'unsafe-eval' from CSP

- frontend/src/lib/components/staking/ProjectNeuronsCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
Currently the "Nervous Systems", "Stake" and "Neurons" columns each get an equal amount of space.
Because the first one is left aligned and the other 2 are right aligned but at the same time the project name tends to be longer, it looks like the gaps between the columns are divided equally.
But if one project has a really long name, it might have to wrap while there is actually still enough space if the other columns would give up some.
In the neurons table, we switched to the content columns getting the width they need and adding additional columns in between to take up the additional space.
1. Add empty columns between the "Nervous Systems", "Stake" and "Neurons" columns.
2. Give the empty columns style `1fr` to take up additional space.
3. Give the "Nervous Systems" column style …
> NNS1-3094: Projects table column styling

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/origin.constants.ts
- frontend/src/tests/lib/utils/env.utils.spec.ts
- frontend/static/.well-known/ic-domains
- frontend/static/.well-known/ii-alternative-origins
We want to be able to deploy unreleased versions of the NNS dapp which can be used with the same mainnet principal as the real NNS dapp.
This PR is based on https://github.com/dfinity/nns-dapp/pull/3255
1. Add the domains to `.well-known/ic-domains` so that the boundary node can see that the canister wants to serve on those domains.
2. Add the domains to `.well-known/ii-alternative-origins` so the internet identity known those domains are allowed to use the same derivation origin.
3. Add the domains to `NNS_IC_ORG_ALTERNATIVE_ORIGINS` so that nns-dapp knows to request the canonical derivation origin from internet identity when serving from those domains.
2. Downloaded https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/.well-known/ic-domains and …
> Add beta subdomains

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/environment.constants.ts
We will release code that hasn't been voted on by the community to beta.nns.ic0.app.
To make sure people are aware they are using a test deployment, we have a warning dialog on sign-in.
This was already implemented a while ago in https://github.com/dfinity/nns-dapp/pull/2570 but never enabled.
Enable `IS_TEST_MAINNET` when the `DFX_NETWORK` in the canister args is set to `"app"`, which is the network we currently use to deploy the beta.
1. The warning dialog itself was tested in https://github.com/dfinity/nns-dapp/pull/2570
2. Enabling it was tested manually by deploying to https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/ with different values in the canister args.
When you sign in, you see this every time:
> Activate warning dialog for beta deployment

- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
Make getting available/staked maturity from nns/sns neurons consistent and straightforward.
I plan to use these for the projects table as well as the neurons table.
1. Add utility functions get available and staked maturity from NNS and SNS neurons.
2. Use them in `neurons-table.utils.ts` instead of getting the maturity directly.
1. Unit tests added for the new functions.
2. Existing `frontend/src/lib/utils/neurons-table.utils.ts` tests pass.
not necessary
> NNS1-3139: Utils to get maturity from nns/sns neurons

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/nns-dapp.did
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/tests.rs
- rs/backend/src/accounts_store/tests.rs
- rs/backend/src/accounts_store/toy_data.rs
- rs/backend/src/main.rs
We want to allow users to import custom tokens in NNS dapp by specifying a ledger canister ID and optional index canister ID.
The imported tokens should be persisted with the account so we need to store them in the nns-dapp backend canister.
We need to limit the number of tokens per user to have a bound on the amount of storage used.
We arbitrarily set the limit to 10 and can increase it later if we want.
We store the tokens in the user account which is stored in stable structures.
To keep things simple we just support setting and getting the full list of tokens.
Add `set_imported_tokens` and `get_imported_tokens` canister methods.
2. Tested manually with dfx:
```
$ dfx canister call nns-dapp get_imported_tokens --candid rs/backend/nns-dapp.did
(variant { …
```
> Add canister method to store imported tokens

- dfx.json
> bot: Update snsdemo to release-2024-07-24

- rs/proposals/src/canisters/nns_governance/internal.rs
- rust-toolchain.toml
The [bot PR](https://github.com/dfinity/nns-dapp/pull/5241) failed because the new rust version has stricter linting.
```
error: doc list item missing indentation
--> rs/proposals/src/canisters/nns_governance/internal.rs:12:5
|
12 | /// The public type is probably better.  Maybe we can ask upstream to use the public type?
|     ^
|
= help: if this is supposed to be its own paragraph, add a blank line
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
= note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`
help: indent this line
|
12 | ///    The public type is probably better.  Maybe we can ask upstream to use the public type?
| …
```
> Update rust version to 1.80.0

- .github/workflows/update-rust.yml
PRs created by bots should never contain manual changes. That way, when reading through a list of PRs, it's always obvious that bot PRs are fully automated.
Replace the section about manual changes in the Rust update bot PR descriptions.
Not tested.
not necessary
> Fix bot PR instructions

- frontend/src/lib/components/neurons/MaturityWithTooltip.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronMaturityCell.svelte
- frontend/src/tests/lib/components/neurons/MaturityWithTooltip.spec.ts
- frontend/src/tests/page-objects/MaturityWithTooltip.page-object.ts
- frontend/src/tests/page-objects/NeuronMaturityCell.page-object.ts
We want to show maturity in the projects table, similar to the neurons table, with a tooltip that shows separate available and staked maturity. However there will be some different logic for when the value isn't available so we can't reuse the full cell component.
Extract `MaturityWithTooltip` component from `NeuronMaturityCell`.
2. Existing NeuronsTable tests pass.
not necessary
> NNS1-3139: Extract MaturityWithTooltip from NeuronMaturityCell

- frontend/src/tests/e2e/accounts.spec.ts
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/page-objects/App.page-object.ts
There are 2 issues with the back button in end-to-end tests:
1. After clicking the back button, it may be replaced with the menu button or there might still be a back button.
2. When navigating to another tab, we need to click on the menu button, but this is not possible if there is a back button.
This PR solves this by making the `AppPo` aware of which views have a back button.
1. Add `getCurrentViewWithBackButton` method to `AppPo` which knows which views have a back button and checks if any of them is currently present to return it.
2. Remove the conditional option to wait for the back button to be absent from `AppPo.goBack` and instead wait for the current view to be absent.
3. Add a `goBackAllTheWay` method which can be used before navigating to another tab without having to know if …
> Making e2e navigation less brittle

- .github/workflows/deploy-to-app.yaml
There have been issues with the uploading of assets causing "heap out of bounds" so we output logs to help debug when it happens again.
Fetch logs before installing the canister and between uploading of each asset chunk.
Tested in this run: https://github.com/dfinity/nns-dapp/actions/runs/10113087618/job/27968618074
not necessary
> Output canister logs during deploy-to-app

- frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js
During testing, we found that `non-certified` types were missing after adding [imported tokens api](https://github.com/dfinity/nns-dapp/pull/5239). This occurred because only certified calls were tested.
- Add missing type definitions (copied from [certified version](https://github.com/dfinity/nns-dapp/pull/5239/files#diff-2b4b1800a3d79b37a6d64bc8a3f292b923ed05ff68546470c4b32f41858494a0R148)).
- Manually tested against a local replica.
Not necessary.
> Add missing imported tokens api types

- dfx.json
> bot: Update snsdemo to release-2024-07-31

- rs/sns_aggregator/src/types/ic_sns_swap.edit
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/slow.rs
We have custom code that adds the `PartialEq` trait to some sns aggregator Rust types derived from Candid.
Sometimes this breaks the build because a new type must receive the `PartialEq` trait as well for the old types to be able to keep the `PartialEq` trait.
But removing the `PartialEq` trait and the custom code that adds it doesn't seem to break anything.
Remove custom code to add `PartialEq` to types that don't need it.
CI passes.
not necessary
> Remove custom added PartialEq from SNS aggregator types

- dfx.json
> bot: Update snsdemo to release-2024-08-05

- .github/workflows/checks.yml
We are trying to move some CI jobs to DFINITY's custom runners.
One difference between GitHub runners and DFINITY runners is that GitHub runners have a default Rust version specified while DFINITY runners don't.
If `cargo` is run from within the repo directory, the version from `rust-toolchain.toml` is taken, but outside of the repo, the version must be specified or default.
The spellcheck job moves outside the repo to avoid getting the configuration from the repo according to [this comment](https://github.com/dfinity/nns-dapp/pull/3378/files#r1343204264),
> To avoid any `.cargo` configuration intended for the local project affecting the build. Not normally necessary but this crate fails to install with just a vanilla `cargo install spellcheck` so I am being (possibly excessively) …
> Remove cd / from spellcheck

- Cargo.lock
- Cargo.toml
Updating the IC cargo dependencies has been failing:
https://github.com/dfinity/nns-dapp/actions/workflows/update-ic-cargo-deps.yaml
https://github.com/dfinity/nns-dapp/actions/runs/10244577609/job/28337826321
```
error: failed to select a version for `num-bigint`.
... required by package `icrc-ledger-types v0.1.6 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
... which satisfies git dependency `icrc-ledger-types` of package `cycles-minting-canister v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
... which satisfies git dependency `cycles-minting-canister` of package `nns-dapp v2.0.85 (/home/runner/work/nns-dapp/nns-dapp/rs/backend)`
versions that meet the requirements `^0.4.6` are: 0.4.6
all possible versions conflict with …
```
> Fix IC cargo dependencies

- frontend/package-lock.json
We have release gix-cmp. It might be useful to upgrade as it contains support for `sass` v1.77.8. Useful if the dependency is ever upgraded here as well.
> build: update gix-cmp

- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/mocks/staking.mock.ts
We want to show aggregate maturity in the staking projects table.
This PR includes the data in the type, but does not yet display it on the page.
1. Add `availableMaturity` and `stakedMaturity` fields to `TableProject` type.
2. Rename `getNeuronCountAndStake` to `getNeuronAggregateInfo` and include the maturity values in the result.
2. Fields added to mock.
not yet
> NNS1-3139: Include maturity in TableProject type

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/e2e/following.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Previously, following on the new topics cannot be set on the NNS Dapp, because NNS Governance did not support it yet. Now NNS Governance has supported it.
Remove a filtering of topic enums that prevented the new topics from appearing on the followee edit modal. Note that the mechanism to disable following by `TOPICS_WITH_FOLLOWING_DISABLED` won't be needed in the future because of https://github.com/dfinity/nns-dapp/pull/5213.
* Unit tests
* Manual test to set followees on the new topics:
> Enable following on the new topics

- frontend/src/lib/components/staking/ProjectMaturityCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/page-objects/ProjectMaturityCell.page-object.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
We want to make it easy to see all the maturity on all projects by adding a column to the staking projects table.
1. Add `ProjectMaturityCell` component which renders either `-/-` of there is no data, the maturity if there is data, or nothing if the user doesn't have neurons for that project.
2. Use the cell component to add a column in the `ProjectsTable`.
1. Page objects and unit tests added.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
We haven't done a release yet since the projects table was enabled so that entry covers this as well.
> NNS1-3139: Add maturity column in projects table

- frontend/src/lib/utils/tokens-table.utils.ts
- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/lib/utils/tokens-table.utils.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Important tokens should be displayed together with SNS tokens that have a balance (between the important ck-tokens with a balance and ck-tokens without a balance). All tokens should be sorted alphabetically.
- Replace `compareTokensWithBalanceFirst` with `compareTokensWithBalanceOrImportedFirst` comparator.
- Provide imported tokens id to the token table sorting function.
- Unit tests were updated.
Not yet.
> Imported tokens table sorting

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/MaturityWithTooltip.svelte
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/components/neurons/MaturityWithTooltip.spec.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
To make numbers more aligned in the neurons/projects tables we agreed to always round maturity to 2 decimals.
The tooltip will still show the detailed amount for available and staked maturity.
1. Add an optional parameter `extraDetailForSmallAmount` to `formatToken*` functions, to configure the detault behavior of showing more decimals for numbers < 0.01.
2. In the `MaturityWithTooltip` component, which is used in the neurons table and projects table, set `extraDetailForSmallAmount: false` and also render 0.00 as 0.
1. Unit tests for `formatToken`.
2. Unit tests for `MaturityWithTooltip`.
3. Drive-by: Remove an old TODO.
> Round maturity to 2 decimals in neurons tables

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/neuron-detail/StakeItemAction.svelte
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/neuron-detail/StakeItemAction.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeading.spec.ts
The neuron details page shows details for a single neuron. There's no reason not to show the stake in full detail.
Also we want to round the stake in the table (in another PR) so it's good to have the detailed stake displayed on the details page.
1. Show detailed stake in the heading (for both NNS and SNS).
2. Show detailed stake in the stake action (which is shared between NNS and SNS).
1. Unit test updated
2. Test manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
> Show detailed stake on neuron details page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/NeuronsTable/NeuronStakeCell.svelte
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
To make numbers more aligned in the neurons table we agreed to round stake to 2 decimals.
Remove the `detailed` attribute from `AmountDisplay` in the `NeuronStakeCell` component.
Unit test updated.
> Round neuron stake in table

- frontend/src/lib/components/accounts/ImportTokenForm.svelte
- frontend/src/lib/components/ui/PrincipalInput.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/ImportTokenForm.spec.ts
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/ImportTokenForm.page-object.ts
- frontend/src/tests/page-objects/ImportTokenModal.page-object.ts
- frontend/src/tests/page-objects/TokensPage.page-object.ts
To allow users to import custom tokens, we need to provide a modal with a form for entering the ledger and optional index canister IDs. This PR focuses on creating the form to input these IDs, without including validation, reviewing or additional functionality at this stage.
Demo is available at [beta](https://beta.nns.ic0.app/).
- New ImportTokenForm component.
- New ImportTokenModal component.
- Bind canister IDs to be editable in the form and accessible in the modal.
- Show modal on "Import token" button click. The button is behind the feature flag.
**Ancillary changes**
- Move the `import_token` label under the `import_token`, because same wordings we user for the modal title.
- Expose `testId` and `require` props for the `PrincipaInput` component.
- Added.
Not necessary.
> Import token modal

- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
We need a way to fetch imported token metadata to display it during the review step.
- Introduced a new service `fetchIcrcTokenMetaData`.
- Tests have been added.
- Tested against localhost replica.
Not necessary.
> Fetch icrc token metadata

- frontend/src/lib/components/staking/ProjectActionsCell.svelte
When a user has no neurons for a project, instead of navigating to the (empty) neurons table page to stake there, we want to open the staking modal when the user click on the row for that project. After the user stakes a neuron, they should then be navigated to the neurons table page for that project.
This means that rows for projects without neurons should not be a link anymore, but they should still have the `>` icon.
So in this PR we once again always show the `>` regardless of whether the row is a link or not.
This is a partial rollback of https://github.com/dfinity/nns-dapp/pull/5202
Change `ProjectActionsCell` to always show the `IconRight` component.
Because the component was already showing the icon for all rows with a URL, and currently all rows have a URL, there is no change in …
> NNS1-3250: Always show arrow icon on projects table row

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/proposals/src/def.rs
- rs/proposals/src/lib.rs
- rs/proposals/src/tests/mod.rs
The InstallCode proposal can be large, and we want to avoid letting the client download the entire WASM to calculate the hash.
Returns wasm hash and upgrade args hex and hash for InstallCode proposals
* Unit tests
> Parse and trim InstallCode proposal payload

- frontend/package-lock.json
- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
To make [getLedgerId api](https://github.com/dfinity/ic-js/pull/693) available in `nns-dapp` the `ic-js` package needs to be upgraded.
- `npm run upgrade:next`.
- Add `[]` to some new optional fields in `convertSwapInitParams` to fix type checking errors.
- Pass
Not necessary
> Upgrade ic-js

- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/mocks/staking.mock.ts
We want to add a button on staking project rows for which the user doesn't have any neurons yet, to allow the user to start staking those tokens.
We need to know the token symbol to render the button, and the universe ID to open the staking modal when the button is clicked.
So this PR adds those 2 pieces of information to the `TableProject` type to be used in the next PR.
1. Add `universeId` and `tokenSymbol` fields to `TableProject`.
2. Fix `compareIcpFirst` to use the new `universeId` field instead of depending on the `domKey`.
not yet
> Add universeId and tokenSymbol to TableProject

- rs/sns_aggregator/src/state.rs
The aggregator outputs a lot which makes looking at replica logs while testing not so easy.
Remove the `println` statement from `log`. It still logs to memory, which can be retrieved via canister call.
1. Installed sns_aggregator
2. Checked that the replica logs are quiet
3. Ran `dfx canister call sns_aggregator tail_log | idl2json | jq -r '.'` to make sure it still outputs logs.
not necessary
> Remove log spam from sns aggregator

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.svelte
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
- frontend/src/tests/mocks/proposal.mock.ts
The InstallCode proposal can be large, and we want to avoid letting the client download the entire WASM to calculate the hash.
Calls `get_proposal_payload` endpoint so that the parts of the proposal that can be large will be rendered.
* Unit tests
* Manual test
> Render the payload section for InstallCode

- frontend/package-lock.json
- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
In the [forum](https://forum.dfinity.org/t/dogmi-sns-transfer-wrong-transfer-fee/34114/1) it was reported that the fees of the DOGMI SNS DAO were correctly interpreted in the NNS dapp and Oisy. After debugging, we discovered that the issue was linked to the SNS aggregator providing ICRC fees encoded in Candid Nat, and our transformation to BigInt wasn't accurate. It only interpreted the lower parts of a 64-bit value, i.e., only interpreting the first 32 bits.
To resolve the issue, we implemented a new utility, `candidNatArrayToBigInt`, which is included in `@dfinity/utils`.
The upgrade of the utils that provides the new function was provided in PR #5315.
- Use new function to convert the SNS aggregator response to ICRC fee.
- We also use the new utility to convert potential `Value.Int`.
- …
> fix: dogmi fee interpretation

- frontend/src/lib/components/ui/ResponsiveTableRow.svelte
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
In the staking projects table, when you click on a project for which you don't have any neurons, instead of navigating to the (empty) neurons table for that project, we want to open the staking modal.
This means that those rows should not be links (which would cause navigation) but should clicks should instead dispatch an event which can be used to open the modal.
This PR only implements dispatching the event for non-link rows and does not yet do anything with it.
When a non-link row is clicked in the `ResponsiveTable`, dispatch an `nnsAction` event with the `rowData` for that row as event payload.
2. Tested manually in another branch which already has the staking modal implemented: https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not …
> NNS1-3250: Dispatch event for click on non-link table row

- scripts/nns-dapp/release-sop
- scripts/nns-dapp/split-changelog
In the NNS dapp release SOP checklist there is a step:
> gh release upload "proposal-$PROPOSAL_ID" scripts/nns-dapp/Release-*.json
To upload the release-sop JSON file to the release assets. Using `*` makes it easy to copy/paste the command but in the `release-sop` script we can be more precise and avoid matching other JSON.
When running the test there is a different JSON file but if an actual release is ongoing the test would see that file too.
1. Explicitly upload the checklist file for the current release instead of using wild cards.
2. Drive-by: Fix typos of "relese" to "release".
1. The existing `release-sop.test` still passes.
2. I tried running the test after doing `touch scripts/nns-dapp/Release-2024-02-29.json` and it failed without the change and passed with the change.
not …
> Explicitly upload checklist file in release-sop

- frontend/src/tests/mocks/auth.store.mock.ts
When writing a unit test of a larger component, it's easy to forget to mock out some of the API requests.
In that case the agent might try to make a real request. This will fail when the agent tries to call `transformRequest` on the mock identity, resulting in the following in the test output:
```
Error polling: id.transformRequest is not a function
```
This is not very clear or useful.
By implementing `transformRequest` on the mock identity, we can get something like that following instead:
```
It looks like the agent is trying to make a request that should have been mocked at Error: 
at Object.transformRequest (/Users/dskloet/dev/nns-dapp/tree5/frontend/src/tests/mocks/auth.store.mock.ts:14:104)
at HttpAgent.call (/Users/dskloet/dev/nns-dapp/tree5/frontend/node_modules/@dfinity/agent/src …
```
> Implement transformRequest on mockIdentity

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/tests/mocks/proposal.mock.ts
ic-js has a recent change (https://github.com/dfinity/ic-js/pull/699) for interpreting `InstallCode` within proposals differently based on whether it's request/response. Bumping its version so that NNS Dapp can interpret the proposal correctly.
* Bump ic-js version and fix a test.
* Unit test
> Bump ic-js and fix test

- frontend/src/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.svelte
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
Now that we implemented the ideal solution for displaying `InstallCode` proposals - NNS Governance returning the hashes for `wasm_module` and `arg`, we don't need a separate "Payload" section to display them.
* Revert most of the previous change https://github.com/dfinity/nns-dapp/pull/5288 related to displaying the "Payload" section.
* Keeping the change to introduce the i18n for proposal types
* Keeping some changes on unit tests regarding showing the payload section.
* Unit tests
> Revert the change to display the Payload section for `InstallCode`

- frontend/src/lib/components/proposal-detail/ProposalNavigation.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Currently, the `Next` and `Previous` labels displayed next to the proposal navigation buttons. While `Next` navigates to the next item in the list, some users find it confusing because the next item is an older proposal. To improve this, here we’ve removed the labels, leaving only the arrow icons for navigation.
- Remove the text labels from the navigation buttons.
- Pass.
- Locally.
| <img width="345" alt="image" src="https://github.com/user-attachments/assets/615fc720-6a62-4aad-b457-f04a911b6404"> | <img width="325" alt="image" src="https://github.com/user-attachments/assets/94bf42e0-3dd9-4e67-bf5c-7d43189dc3f6"> | 
Not necessary.
> Remove text labels from proposal navigation buttons

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/staking/ProjectNeuronsCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/routes/Staking.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/e2e/following.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/e2e/neurons-table.spec.ts
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
- frontend/src/tests/page-objects/App.page-object.ts
- frontend/src/tests/page-objects/ProjectNeuronsCell.page-object.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
- frontend/src/tests/page-objects/Staking.page-object.ts
- frontend/src/tests/page-objects/TransactionForm.page-object.ts
- frontend/src/tests/page-objects/TransactionFormFee.page-object.ts
- frontend/src/tests/page-objects/TransactionFromAccount.page-object.ts
- frontend/src/tests/utils/sns.test-utils.ts
When a user has 0 neurons for a project, instead of showing "0" in the table, we want to show a button to stake tokens for that project.
Clicking the button (or anywhere else on the row) will open the staking modal, and if the user does stake a neuron they will navigate to the neurons table afterwards.
1. Show a "Stake XYZ" button in the neurons cell in the projects table, if the user has zero neuron.
2. When the user clicks on a non-link row in the projects table, dispatch a `nnsStakeTokens` event.
3. In the `Staking` component, when an `nnsStakeTokens` event is received, open the corresponding staking modal.
4. When the staking modal closes, check if there are now a positive number of neurons and if so, navigate to the neurons table.
5. Don't provide a `rowHref` for projects without …
> NNS1-3250: Stake button for projects without neurons

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/staking/ProjectActionsCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
We don't want users to navigate to the neurons table if they have no neurons.
For this reason, we added the "Stake XYZ" button when the user has 0 neurons for a project.
But we also don't want to navigate if the user is not signed in or neurons aren't loaded yet.
1. When the number of neurons is not known, don't make the project row a link.
2. When a non-link project row is clicked, only dispatch `nnsStakeTokens` if the number of neurons is known to be 0.
3. Don't show the `>` icon when the row is neither a link nor clickable to stake a neuron.
1. Unit test updated and added.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
> NNS1-3250: Make project rows not clickable when neuron count not available

- frontend/src/lib/components/accounts/WalletPageHeader.svelte
- frontend/src/lib/components/tokens/LinkToDashboardCanister.svelte
- frontend/src/lib/components/universe/UniversePageSummary.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/tokens/LinkToDashboardCanister.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/page-objects/LinkToDashboardCanister.page-object.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
With the introduction of the import token feature, a new token popup with additional actions was added. Each token will have two entries:  "View in Dashboard" and "Token Details". Imported tokens will have an extra entry: "Remove".
In this pr, we’ve added the popup with the "View in Dashboard" button. The same popup for the IcrcWallet page will be added in a separate pr.
[Demo](https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/wallet/?u=qsgjb-riaaa-aaaaa-aaaga-cai)
- New `LinkToDashboardCanister` component.
- Add "actions" slot to the `WalletPageHeader` to display 3 dots button next to the token title.
- Add a popup to the `Nns` wallet page with the "View in Dashboard" button.
- Unit tests for LinkToDashboardCanister.
- Added tests for Nns wallet page.
- Tested …
> Nns wallet popup

- frontend/src/lib/api/icrc-index.api.ts
- frontend/src/tests/lib/api/icrc-index.api.spec.ts
To validate the index/ledger canister IDs, we need to retrieve the associated ledger canister from the index canister.
- Add `getLedgerId` api.
- Unit tests have been added.
Not necessary.
> Get ledger id api

- CHANGELOG-Sns_Aggregator.md
We forgot to update the SNS aggregator changelog after the [upgrade](https://dashboard.internetcomputer.org/proposal/129614) back in May.
Move the entries that were already there before the previous upgrade, to a separate section.
I also updated the release SOP for the aggregator to include an item about the changelog.
n/a
> Update SNS aggregator changelog for proposal 129614

- frontend/src/lib/components/accounts/ImportTokenCanisterId.svelte
- frontend/src/lib/components/tokens/LinkToDashboardCanister.svelte
- frontend/src/tests/lib/components/accounts/ImportTokenCanisterId.spec.ts
- frontend/src/tests/page-objects/ImportTokenCanisterId.page-object.ts
- frontend/src/tests/page-objects/ImportTokenModal.page-object.ts
The `ImportTokenCanisterId` component will be reused in different places on the token page. To simplify its reusability, we are providing some small refactoring and enhancements.
**ImportTokenCanisterId**
- Add a `testId` parameter to accommodate the use of multiple components within a single parent.
- Provide canisterId as a Principal (instead of a string) to enforce stricter typing.
- Use `LinkToDashboardCanister` instead of `LinkIcon`, as it is more appropriate for linking to the canister on the dashboard.
**LinkToDashboardCanister**
- Add a `noLabel` parameter to have an icon-only component version.
- POs and tests updated.
- Can be tested on [beta](https://beta.nns.ic0.app/).
Not necessary.
> Refactor import token canister

- scripts/update-ic-cargo-deps
The latest run of "Update IC Cargo Dependencies" failed with:
```
error: failed to select a version for `ic-cdk`.
... required by package `pocket-ic v4.0.0`
... which satisfies dependency `pocket-ic = "^4.0.0"` (locked to 4.0.0) of package `nns-dapp v2.0.87 (/home/runner/work/nns-dapp/nns-dapp/rs/backend)`
versions that meet the requirements `^0.13.2` (locked to 0.13.2) are: 0.13.2
all possible versions conflict with previously selected packages.
previously selected package `ic-cdk v0.13.5`
... which satisfies dependency `ic-cdk = "^0.13.5"` of package `icp-ledger v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-21_15-36-canister-snapshots#3d6a76ef)`
... which satisfies git dependency `icp-ledger` of package `nns-dapp v2.0.87 (/home/runner/work/nns-dapp/nns-dapp/rs/backend)` …
```
> cargo update without --worksapce

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-08-21_15-36-canister-snapshots

- frontend/src/lib/utils/imported-tokens.utils.ts
- frontend/src/lib/utils/sns.utils.ts
- frontend/src/tests/lib/utils/imported-tokens.utils.spec.ts
- frontend/src/tests/lib/utils/sns.utils.spec.ts
For validating the addition of imported tokens, we need to ensure that the entered ledger canister hasn’t already been imported and that it isn’t an SNS ledger canister ID. To facilitate this, we’ve added a pair of utility functions that will simplify the validation process.
- Add `isImportedToken` util.
- Add `isSnsLedgerCanisterId` util.
- Added unit tests for new utils.
Not necessary.
> Imported tokens utils

- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/icrc-index.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/services/icrc-index.services.spec.ts
For validating the ledger and index canister IDs entered by the user, we will use the `ledgerId` API of the index canister. When the entered ledger canister ID matches the ledgerId response from the entered index canister ID, we can confirm that this pair of IDs is suitable for each other. Here, we add a service that validates the ID matching.
- New `matchLedgerIndexPair` service.
- Unit test for it.
Not necessary.
> Match ledger index pair

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/proposals/src/def.rs
- rs/proposals/src/lib.rs
- rs/proposals/src/tests/mod.rs
The latest [Candid import](https://github.com/dfinity/nns-dapp/pull/5355) breaks rendering of `InstallCode` proposal payload in the nns-dapp canister because its fields have changed.
But we no longer fetch the proposal payload for `InstallCode` proposals from the nns-dapp canister anyway (since https://github.com/dfinity/nns-dapp/pull/5332) so we no longer need to maintain this code.
Remove code to render `InstallCode` payload from the nns-dapp backend canister.
Unit test removed.
> Remove payload rendering for InstallCode proposal

- rs/backend/src/time.rs
We had a TODO to replace a usage of `ic0::time()` with `ic_cdk::api::time()`.
Both return time in nanoseconds:
https://github.com/dfinity/ic/blob/62c2ed16a02cd0155964013cb0849eadafe22069/rs/rust_canisters/dfn_core/src/api.rs#L223
https://github.com/dfinity/cdk-rs/blob/3e54016734c8f73fb3acabc9c9e72c960c85eb3b/src/ic-cdk/src/api/mod.rs#L27C1-L27C72
1. Fulfill the TODO by using `ic_cdk::api::time()` instead of `ic0::time()`.
2. Document what it actually returns.
Not tested. Existing tests pass.
not necessary
> Use icd_cdk::api::time() instead of ic0::time()

- Cargo.lock
- rs/backend/Cargo.toml
- rs/backend/src/canisters/governance.rs
- rs/backend/src/lib.rs
- rs/backend/src/main.rs
- rs/backend/src/state.rs
- rs/backend/src/state/tests.rs
- rs/backend/src/tvl.rs
- rs/backend/src/tvl/state.rs
- rs/backend/src/tvl/tests.rs
The NNS dapp displays the USD value of the total amount of ICP locked in neurons.
It gets this information from the TVL canister but we want to move this functionality to the nns-dapp canister and remove the TVL canister.
There are 2 inputs to this data:
1. The amount of ICP locked in neurons
2. The price of ICP in USD.
We plan to periodically load both values and cache them in the canister state. When the user requests the TVL, it will be computed from the currently cached state.
In this PR we only add a function which can load the amount of locked ICP into the nns-dapp state.
The function is not yet called, and the state is not yet persisted in this PR.
1. Add `get_metrics` function to call the `get_metrics` function on the governance canister. There is a separate implementation for …
> NNS1-3281: Add update_locked_icp_e8s for TVL

- dfx.json
> bot: Update snsdemo to release-2024-08-28

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/mockable.constants.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
`FORCE_CALL_STRATEGY` is currently used to limit the number of update calls made to the Internet Computer for certain cases.
We want to stop doing this to avoid the possibility of displaying incorrect data from a malicious node.
Change `FORCE_CALL_STRATEGY` from `"query"` to `undefined`.
This makes sure we do a query and update in all the [places where FORCE_CALL_STRATEGY is used](https://github.com/search?q=repo%3Adfinity%2Fnns-dapp+%22%3A+FORCE_CALL_STRATEGY%22&type=code).
1. Fixed an e2e test which got broken because some caching started working again because it only caches certified results.
2. Other existing tests pass (`FORCE_CALL_STRATEGY` was [still set to](https://github.com/dfinity/nns-dapp/blob/e09ed215565c5521b6403a02ddeb15f8e3876365/frontend/vitest.setup.ts#L67) `undefined` …
> FOLLOW-1337: Disable FORCE_CALL_STRATEGY

- .github/actions/test-e2e/action.yml
When a Playwright e2e test fails, we upload the failure results to GitHub so we can debug the failed test.
The e2e tests are run in 2 separate shards.
But the name for the uploaded failure results is the same for both shards.
So if both shards fail, one of the failure results overrides the other and we can only debug one of the shards.
Include the shard number in the failure results artifact name.
Deliberately made both shards fail in this run and checked that there were 2 separate failure results artifacts:
https://github.com/dfinity/nns-dapp/actions/runs/10632674253
not necessary
> Include the shard number in the playwright failure results name

- CHANGELOG-Nns-Dapp-unreleased.md
- scripts/nns-dapp/release
- scripts/nns-dapp/release-template
- scripts/propose-to/propose-to-upgrade-nns-dapp
- scripts/sns/aggregator/release
The `InstallCode` proposal type is replacing the `NnsCanisterUpgrade` NNS function. Adapt the NNS Dapp and SNS aggregator release scripts for the new type.
* Since the `InstallCode` proposal type returns hash of the upgrade args, change the verification instruction to verify the hash.
* Pass an additional argument `--use-explicit-action-type` to ic-admin
N/A
> Switch to the `InstallCode` proposal type for canister upgrade proposals

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/mockable.constants.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
This reverts commit [3e064af8b3988c818d7422e7cdb69a7378aa0d87](https://github.com/dfinity/nns-dapp/commit/3e064af8b3988c818d7422e7cdb69a7378aa0d87).
In https://github.com/dfinity/nns-dapp/pull/5376 we disabled `FORCE_CALL_STRATEGY`.
This has resulted in [flakiness](https://github.com/dfinity/nns-dapp/actions/runs/10663467367/job/29552954194?pr=5391) in the end-to-end test `proposals.spec.ts` caused by a response to an update call for an old request coming back after a query call for a newer request, resulting in old data being display in the UI.
We've had similar issues in the past. They can be solved using the `queuedStore` but until we make the change for loading proposals, we don't want the test to be so flaky.
Additionally, there have been some concerns regarding extra load caused by …
> Revert "FOLLOW-1337: Disable FORCE_CALL_STRATEGY (#5376)"

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-08-29_01-30-base

- frontend/src/lib/components/tokens/TokensTable/TokenTitleCell.svelte
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
To distinguish the imported tokens from the default ones, we display a special tag next to the token’s name.
- Display the import token tag when the token canister ID belongs to imported tokens.
- Unit test added.
Not necessary.
> Imported token tag

- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/imported-tokens.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/services/imported-tokens.services.spec.ts
It's possible to import a custom token w/o providing the index canister ID. There should be an option to add the index canister later. Here we introduce the function that adds the missing index canister and safes it.
- Add addIndexCanister service.
- Added.
Not necessary.
> Add index canister service

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/components/accounts/WalletMorePopover.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/stores/busy.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/page-objects/IcrcWallet.page-object.ts
- frontend/src/tests/page-objects/WalletMorePopover.page-object.ts
- frontend/src/tests/utils/utils.test-utils.ts
The imported tokens should be removable. This PR addresses the issue by providing a workflow for removing imported tokens, allowing users to open the context menu on the wallet page, click "Remove", and be navigated to the tokens list after successful removal.
- Add "Remove" button in WalletMorePopover.
- Extend busy initiator with "import-token-removing" entry.
- Show a remove confirmation dialog when the ‘Remove’ button is clicked, and proceed with the token removal.
- Add createDeferredPromise helper.
- Added "should remove imported tokens".
- Tested manually as well.
Not necessary.
> Remove imported token

- frontend/src/tests/lib/pages/NnsProposals.spec.ts
`NnsProposals.spec.ts` was mocking several the `proposalsStore` and the `authStore`.
Mocking stores is fragile and unnecessary.
Because the test mocked the `proposalsStore` it completely ignored the fact that the component empties the store and then fills it with the result of `queryProposals`.
As a result one test was supposed to check that a spinner is shown while proposals are being loaded, but this is not even the case. Skeleton cards are being shown while proposals are loaded. A spinner is shown when additional proposals are loaded into the infinite scroll. Because of the mocked proposals store, the component thought there were already proposals loaded and additional ones were being loaded, showing the spinner instead of the skeleton cards as a result.
1. Stop mocking `authStore` and …
> Clean up NnsProposals.spec.ts

- rs/backend/src/tvl.rs
- rs/backend/src/tvl/tests.rs
The NNS dapp displays the USD value of the total amount of ICP locked in neurons.
It gets this information from the TVL canister but we want to move this functionality to the nns-dapp canister and remove the TVL canister.
We already have a function to fetch the current amount of ICP locked in neurons. We want to call this periodically to have a reasonably up-to-date value.
Given that the total_locked_e8s exposed by the governance canister only updates once a day, updating the exchange rate 4 times a day, seems often enough.
1. Add `init_locked_icp_timers` to set up both a 1-time timer (for a quick initial value) and an interval timer.
1. Added a unit test that verifies the timers are set up and do the right thing when called.
2. Tested manually in a more fully developed branch.
not yet
> NNS1-3281: Function to initialize locked ICP timers for TVL

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/components/accounts/ImportTokenForm.svelte
- frontend/src/lib/components/ui/PrincipalInput.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/AddIndexCanisterModal.svelte
- frontend/src/lib/pages/IcrcWallet.svelte
- frontend/src/lib/stores/busy.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/ImportTokenForm.spec.ts
- frontend/src/tests/lib/components/ui/PrincipalInput.spec.ts
- frontend/src/tests/lib/components/ui/PrincipalInputTest.svelte
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/page-objects/AddIndexCanisterModal.page-object.ts
- frontend/src/tests/page-objects/IcrcWallet.page-object.ts
Users can import a custom token without providing an index canister ID. It should be possible to add the canister afterwards, and this PR addresses that.
**Note:** the transactions are loaded automatically by the transaction sync mechanism.
**Demo:**  https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network
ckRED token for testing:
- ledger canister ID: `mrfq3-7eaaa-aaaaa-qabja-cai`
- index canister ID: `mwewp-s4aaa-aaaaa-qabjq-cai`
- Display "Add index canister" button and description.
- Add `AddIndexCanisterModal` component.
- Add index canister logic.
- New mode `addIndexCanisterMode` to import token form.
- Expose `disabled` prop of PrincipalInput.
- Added.
| 1 | 2 | 3 | 4 |
|--------|--------|--------|--------|
| <img width="804" alt="image" …
> Add index canister

- rs/backend/src/constants.rs
- rs/backend/src/tvl.rs
- rs/backend/src/tvl/tests.rs
The NNS dapp displays the USD value of the total amount of ICP locked in neurons.
It gets this information from the TVL canister but we want to move this functionality to the nns-dapp canister and remove the TVL canister.
There are 2 inputs to this data:
1. The amount of ICP locked in neurons
2. The price of ICP in USD.
We already have functions which periodically fetch this data and store it in the canister state.
This PR adds a function to get the TVL calculated from these 2 inputs.
Add `get_tvl` which returns the current TVL. The return type is the way it is to make it compatible with the existing TVL canister. This allows us to migrate the frontend from using the TVL canister to getting the same data from the nns-dapp canister without changing frontend code.
2. …
> NNS1-3281: Add function to get TVL

- frontend/src/tests/page-objects/Staking.page-object.ts
Before you have your first neuron, you can't navigate to the neurons page.
So the first neuron is staked from the staking page and if successful, you automatically navigate to the neurons page.
This caused some flakiness in e2e tests when we try to navigate back after staking the first neuron, but before the redirect happens.
To make this more consistent we should wait for the redirect to happen before returning from `stakeFirstNnsNeuron`.
Since this happens from `StakingPo`, we can't wait for `NnsNeuronsPo` to be present but we can at least wait for `StakingPo` to be absent.
Wait for `StakingPo` to be absent after staking the first NNS neuron.
On my local machine, `e2e/proposals.spec.ts` was failing consistently without this change and passed with this change.
not necessary
> Wait for navigation after staking first neuron

- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/page-objects/NnsProposalList.page-object.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
There used to be a checkbox on the `NnsProposals` page to only show proposals that you can vote on.
This applied a filter on `list_proposals` to only load proposals with ballots matching your neurons.
For this reason we needed to reload the proposals when your neurons changed.
But we no longer have this checkbox (we have the actionable proposals tab instead) so we no longer need:
1. load neurons in `NnsProposals`
2. reload proposals when the neurons change
1. Stop loading neurons in `NnsProposals`.
2. Stop listening to `definedNeuronsStore` to reload proposals.
1. With the reloading on neurons removed, the tests no longer hit the debounce, so instead we use an unresolved promise to test the skeleton cards and the spinner.
2. Two tests were setting `proposalsFiltersStore` immediate after …
> Stop loading neurons in NnsProposals

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/routes/Staking.svelte
- frontend/src/tests/lib/routes/Staking.spec.ts
In https://github.com/dfinity/nns-dapp/pull/5339 we added the staking button to the staking table.
This opens the SNS staking modal via a different code path, which didn't load the SNS parameters.
This meant that the minimum neuron stake wasn't available.
Instead of requiring the minimum stake to be available, the `SnsStakeNeuronModal` component happily ignores this and allows the user to try staking any amount.
But if the amount it too small, claiming the neuron after transferring the tokens fails.
This PR makes sure the parameters are loaded.
We should additionally fix `SnsStakeNeuronModal` to require the minimum stake to be present but that will be a separate PR.
Make sure the SNS parameters (which include the minimum stake) are loaded before opening the `SnsStakeNeuronModal` from the …
> Load minimum stake when staking from staking table

- scripts/propose-to/propose-to-upgrade-nns-dapp
- scripts/sns/aggregator/release
Remove the --use-explicit-action-type flag since it's already the default behavior of ic-admin.
Remove the flag.
N/A
The change log entry "Change the release process to submitting `InstallCode` proposals." is still accurate. Some of the release process is changed (verifying hash), but part of it was reverted (the flag)
> Remove the --use-explicit-action-type flag since it's no longer needed

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-09-06_01-30-canister-snapshots

- .github/workflows/update-ic-cargo-deps.yaml
Dependabot often sends PRs on Monday morning.
We also update our cargo dependency to the latest IC release on Monday morning.
The IC release is usually made on Thursday or Friday.
I prefer to merge the IC cargo dependencies PR first because
1. It makes sure the dependabot changes aren't incompatible with the newest IC release
2. Some of the dependabot changes tend to become obsolete once the IC deps are updated.
Currently I wait until 9:30 on Monday for the IC dependencies PR to be created. It would be nice to be able to do it earlier.
Change the schedule of `.github/workflows/update-ic-cargo-deps.yaml` to run on Sundays.
n/a
not necessary
> Update IC Cargo Dependencies on Sundays

- scripts/setup
One of the first things people do when developing on nns-dapp is running `scripts/setup`.
This installs (among other things) `ic-admin` and `sns`.
But you need to set `IC_COMMIT` to be able to do this, and there is no good way in the nns-dapp repo to get it.
The `bin/dfx-sns-demo-install` in `snsdemo` also [installs these tools](https://github.com/dfinity/snsdemo/blob/fdaf0fb392a88880c93a589f096957680acac523/bin/dfx-sns-demo-install#L29) and has the `IC_COMMIT` [configured in the repo](https://github.com/dfinity/snsdemo/blob/fdaf0fb392a88880c93a589f096957680acac523/bin/versions.bash#L5) and [updated periodically](https://github.com/dfinity/snsdemo/blob/main/.github/workflows/update-ic.yml).
So let's just remove `ic-admin` and `sns` from `scripts/setup`.
Removed installing `ic-admin` and …
> Remove ic-admin and sns from scripts/setup

- dfx.json
> bot: Update snsdemo to release-2024-09-10

- .github/workflows/build.yml
- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/nns-dapp.did
- rs/backend/src/main.rs
- rs/backend/src/tvl.rs
- scripts/nns-dapp/test-tvl
The NNS dapp displays the USD value of the total amount of ICP locked in neurons.
It gets this information from the TVL canister but we want to move this functionality to the nns-dapp canister and remove the TVL canister.
The functionality to fetch the amount of locked ICP and the exchange rate and to get the TVL was already implemented in the `tvl` module.
This PR exposes the `get_tvl` method (which just calls `tvl::get_tvl`) on the canister and initializes the timers to fetch the necessary data.
1. Initialize the timers to update the amount of locked ICP and exchange rate periodically, when installing or upgrading the canister.
2. Add `get_tvl` canister method.
3. Updated the candid file to match the canister interface.
4. Ran `scripts/nns-dapp/test-exports --wasm nns-dapp_test.wasm.gz …
> NNS1-3281: Add get_tvl to nns-dapp

- rs/backend/src/state.rs
- rs/backend/src/state/tests.rs
- rs/backend/src/tvl/state.rs
The nns-dapp loads the input to the TVL calculation right after upgrade. But if this is slow or it fails, it might not be able to provide a TVL value. So we also want to store the TVL state in stable memory during the upgrade.
We can't read the TVL state from stable memory unless it's first written to stable memory.
So we implement the encoding first and only implement the decoding once we've had 1 release that has written the state to stable memory.
1. Implemented both encoding and decoding of the TVL state, but commented out the decoding and added TODOs.
1. Added a test that encoding is done but decoding is not.
2. Added a commented-out assert that decoding is done.
3. Existing upgrade-downgrade test still passes: https://github.com/dfinity/nns-dapp/actions/runs/10792784452/job/299334222 …
> NNS1-3281: Encode TVL state to stable memory

- frontend/src/lib/derived/icrc-canisters.derived.ts
- frontend/src/lib/derived/imported-tokens.derived.ts
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/stores/imported-tokens.store.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/derived/icrc-canisters.derived.spec.ts
- frontend/src/tests/lib/derived/imported-tokens.derived.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/stores/imported-tokens.store.spec.ts
There is no guarantee that the imported token ledger canister’s API won’t be updated in a way that makes it incompatible, or the canister became unreachable. As a result, any call to this canister could potentially fail. To provide appropriate user feedback, the NNS-dapp should display all such imported tokens as failed. As the first step toward this, we will collect the failed imported token ledger IDs and display only the remaining valid ones.
- Add `failedImportedTokenLedgerIdsStore` to store failed ledger canister IDs.
- Update `failedImportedTokenLedgerIdsStore`. Currently, `IcrcWalletPage` calls [syncAccounts](https://github.com/dfinity/nns-dapp/blob/c80f3f202d8a90c329a3c283b00f9daf027e74ac/frontend/src/lib/services/icrc-accounts.services.ts#L220), which calls `loadAccounts` and …
> NNS1-3158: Failed imported tokens store

- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.json
The SNS aggregator has exposed `nervous_system_parameters` since https://github.com/dfinity/nns-dapp/pull/4014 but it wasn't used in the NNS dapp frontend yet.
We want to start using it instead of loading the params separately.
This PR just adds the types to the CachedSnsDto.
This PR does not implement any kind of conversion.
The plan is to replace the `snsParametersStore` with a derived store based on this data, rather than exposing it in the `SnsSummary`.
1. Manually added types to `frontend/src/lib/types/sns-aggregator.ts` based on the [Rust type](https://github.com/dfinity/nns-dapp/blob/712fd337ae5cf6cdcfae39badc5a389751f67720/rs/sns_aggregator/src/types/ic_sns_governance.rs#L85-L106).
1. Updated `frontend/src/tests/mocks/sns-aggregator.mock.json` by copying …
> Add aggregator types for nervous system parameters

- dfx.json
> bot: Update snsdemo to release-2024-09-11

- frontend/src/lib/components/sns-neurons/ConfirmSnsDissolveDelay.svelte
- frontend/src/tests/lib/components/sns-neurons/ConfirmSnsDissolveDelay.spec.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
- frontend/src/tests/page-objects/ConfirmSnsDissolveDelay.page-object.ts
Make the test in `ConfirmSnsDissolveDelay.spec.ts` easier to read and maintain and less brittle.
1. Use a page object.
2. Don't use fake timers as they serve no purpose.
3. Use `beforeEach` instead of `beforeAll` and remove `afterAll`.
4. Use explicit test values and define them in the specific tests that use them.
5. Make `id` in `createMockSnsNeuron` optional so it's easier to create mock neurons when we don't care about the `id`.
6. Use `mockSnsToken` instead of `ICPToken` since it's unrealistic and potentially confusing to use ICP as an SNS token.
Test change only
not necessary
> Test cleanup ConfirmSnsDissolveDelay.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/main.rs
The perf counter was recorded right before getting wiped by replacing the state, so `init set_canister_arguments` is never visible through `get_stats`. Although, this is not very important for mainnet since we don't expect init to execute there.
* Similar to `post_upgrade`, the counter is saved before the state initialization, but recorded (to the state) after initialization
* Additional changes to make `init` more consistent with `post_upgrade`
N/A
> Fix a bug where the perf counter is blown away in init

- rs/backend/src/assets.rs
- rs/backend/src/ledger_sync.rs
- rs/backend/src/lib.rs
- rs/backend/src/main.rs
- rs/backend/src/perf.rs
- rs/backend/src/periodic_tasks_runner.rs
- rs/backend/src/state.rs
- rs/backend/src/state/tests.rs
- rs/backend/src/state/with_accounts_in_stable_memory.rs
- rs/backend/src/stats.rs
- rs/backend/src/tvl.rs
- rs/backend/src/tvl/tests.rs
The initialization of the `STATE` currently is rather complicated - it had a `State::default()` before reading from the stable memory, and there is some logic to replace it with the correct value, which makes it difficult to reason about the value of each of its field. Instead, making `STATE` itself a `RefCell<Option<State>>` seems simpler - there is a `Some(State)` or None. 
Each field in `State` does not need `Default`, which is helpful because not all objects have reasonable `Default` (like `Partitions` and `AccountStore`)
* Encapsulate `STATE` within `state.rs` and define its accessors
* Replace `STATE.with(...)` with those accessors
* Remove the `Default` of `State`
* Change default->replace to initializing `State` directly in the post_upgrade
N/A
> Simplify the lifecycle and access points of `State`

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-09-12_01-30-base

- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
Instead of loading nervous system parameters from the SNS governance canister, we want to use the parameters present in the SNS aggregator data that is already loaded. We'll do this by making `snsParametersStore` a derived store so that we don't have to change how the parameters are accessed.
However, the type of the parameters in the aggregator data is different from the type used in the store. So we'll have to convert the data.
In this PR we just add the conversion function.
1. Fix the type of `CachedDefaultFolloweesDto` which was wrong before but wasn't caught until used.
2. Add `convertNervousSystemParameters` to convert the parameters from `CachedNervousSystemParametersDto` to `SnsNervousSystemParameters`.
Added unit tests for full and empty values.
not necessary
> Add convertNervousSystemParameters function

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/services/imported-tokens.services.ts
- frontend/src/tests/lib/services/imported-tokens.services.spec.ts
Currently the imported token can be removed only from the wallet page. With the upcoming functionality to remove failed imported tokens from the tokens table, we need to apply the same logic in another place. To avoid code duplication, the removal logic has been moved to the service function.
- Simplify the `removeImportedTokens` arguments.
- Move the busy screen handling into the service.
- Updated.
Not necessary.
> Move more logic of remove imported into service

- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
We apply several bonuses to the voting power, such as dissolve delay bonus and age bonus.
This is implemented by multiplying the voting power with a "multiplier".
For example, if you have a bonus percentage of 25, this means the voting power gets multiplied by 1.25.
This number 1.25 is the bonus multiplier.
The code was using the name `multiplier` for things that were not multipliers, which made the code very confusing.
1. Fix inappropriate usages of the term "multiplier".
2. Add a comment on the `bonusMultiplier` function clarifying the parameters.
Updated.
not necessary
> Fix confusing use of 'multiplier'

- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/page-objects/SnsNeurons.page-object.ts
- frontend/src/tests/page-objects/Staking.page-object.ts
I noticed some flakiness in `e2e/sns-governance.spec.ts` because it was waiting for skeleton cards to disappear while the neurons table we have now has a spinner instead of skeleton cards.
This was already fixed for NNS in https://github.com/dfinity/nns-dapp/commit/2395a228b10930469e1f3165e67bf7fc5faeff64#diff-34fb0aee6c9d4c7899b1a1d5a88c149c53c205559da5a91eb977e2798203500a but we somehow skipped SNS.
1. Wait for the spinner to go away in `waitForContentLoaded`.
2. Remove irrelevant code in the PO related to skeleton cards.
3. Drive-by: Make `stakeFirstSnsNeuron` consistent with `stakeFirstNnsNeuron` by waiting for the staking view to disappear after staking the SNS neuron.
Without the change, `e2e/sns-governance.spec.ts` failed 2 out of 12 times. With the change I ran it 24 times without …
> Fix flakiness in e2e/sns-governance.spec.ts

- frontend/package-lock.json
- frontend/package.json
The markdown component has been moved to gix-cmp. The `marked` library is inherited therefore we can remove it as explicit dependency.
- `npm rm marked`
> build: remove marked from package.json

- frontend/src/lib/components/tokens/TokensTable/TokenActionsCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenTitleCell.svelte
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/lib/utils/user-token.utils.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Imported tokens that fail to load still need to be displayed in the table to avoid confusing users about missing tokens. With this PR, we display failed imported tokens in the tokens table using a custom UI (since we don’t have other token information when loading fails).
Note: Sorting and updating the actions cell for failed tokens will be handled in a separate PR.
- New type `UserTokenFailed` to represent failed tokens.
- Extend the `tokensListUserStore` with the records of the failed tokens.
- Added `UserTokenFailed` support to the token table’s title and balance cell components.
- Updated POs (getProjectName returns the hash for the failed projects)
- Moved imported tokens related setup to the top of the test file.
- Added tests for failed rows.
- Locally.
Not necessary.
> Display failed imported tokens

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/routes/(app)/(u)/(list)/neurons/+layout.svelte
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/e2e/following.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/e2e/neurons-table.spec.ts
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/routes/app/neurons/layout.spec.ts
The feature has been enable a while ago.
Remove the code paths for when `ENABLE_PROJECTS_TABLE` is disabled.
The feature flag itself will be removed in another PR.
Removed/updated
not necessary
> Clean up ENABLE_PROJECTS_TABLE feature flag code

- .github/workflows/checks.yml
`dind-small` is having network issues making our tests flaky.
For example: [one](https://github.com/dfinity/nns-dapp/actions/runs/10918905453/job/30305412108), [two](https://github.com/dfinity/nns-dapp/actions/runs/10918905453/job/30305412765), [three](https://github.com/dfinity/nns-dapp/actions/runs/10920886302/job/30311750178).
I also [heard from IDX](https://dfinity.slack.com/archives/CL7Q2RXUM/p1726661669207729) that using `dind-small` wasn't actually necessary.
Basically the opposite of https://github.com/dfinity/nns-dapp/commit/9c0d83da34ee9892b12e9e197eef84ffbf9e9618 except we don't re-introduce the unnecessary singleton matrix.
not necessary
> Use GitHub runners instead of dind-small

- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
We recently had an issue where the `SnsStakeNeuronModal` failed to check the minimum stake amount, which resulted in some people trying to stake too little.
In this PR I add an extra check in the service to make sure we don't try to stake too little.
Providing a proper error message requires passing in more information about the token and i18n so I didn't do this.
It's still the responsibility of the component calling the service to check this, but now we have an extra safety check.
1. When staking SNS tokens, check that the staked amount is at least the minimum stake.
1. Update some tests that were accidentally affected by this.
2. Add a test with a staked amount that's too small.
3. Tested manually after temporarily removing the check in the component.
4. Tested manually that increasing …
> Check for minimum stake when staking SNS tokens

- frontend/src/lib/derived/sns-aggregator.derived.ts
- frontend/src/lib/derived/sns-functions.derived.ts
- frontend/src/lib/derived/sns-parameters.derived.ts
- frontend/src/lib/derived/sns-total-token-supply.derived.ts
- frontend/src/tests/lib/derived/sns-aggregator.derived.spec.ts
We have a number of stores derived from `snsAggregatorStore` which all map the aggregator data to some record with the root canister ID as the key.
These all have very similar code.
Extracted the duplicate code into a function and used it for `snsFunctionsStore`, `snsParametersStore` and `snsTotalTokenSupplyStore`.
1. Added a unit test for the new function.
2. The changed derived stores were already covered by tests that are still passing.
not necessary
> Extract snsAggregatorDerived function

- scripts/convert-id
- scripts/convert-id.test
The textual address format of an ICRC-1 account with subaccount has leading zeros removed from the subaccount.
The address also contains a checksum of the account and subaccount but when calculating the checksum, the leading zeros should not be removed from the subaccount.
The `convert-id` script did this wrong.
Calculate the checksum with the subaccount without leading zeros removed.
Test updated.
not necessary
> Fix checksum for ICRC-1 addresses

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/project-detail/ProjectProposal.svelte
- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
When there is an open SNS swap on the project detail page, we make a request every 10 seconds for the number of participants and commitment, as these might change during an open SNS.
However, this also caused the proposal to be refetched each time. This happened because the proposal fetch logic was derived from the summary store, which is updated each time the derived state is fetched. This is useless because the SNS proposal won't change if the swap is already open.
By adding an intermediate `proposalId` variable, we make sure that we don't fetch the proposal again when the summary changes, but the proposal ID doesn't.
Change `ProjectProposal.svelte` to only load the proposal when the proposal ID changes.
1. I first created the test to see the proposal being fetched multiple times. After …
> FOLLOW-1337: Stop making unnecessary requests for SNS proposal

- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts
These 2 tests had some unexplained numbers in them.
I tried to make the numbers in the setup more explicit so it's clearer where the numbers in the tests come from.
1. Declare constants with specific value.
2. Explain how the expected results derive from the inputs.
3. Merge `"should render voting power"` into `"should render voting power and description if neuron can vote"` because the second expectation explains the value of the first expectation.
Only tests.
not necessary
> Clean up magic numbers from SNS neuron tests

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-09-19_01-31-base

- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
The age of a neuron can be more than 4 years but the maximum age bonus is reached at 4 years.
Taking this into account, the parameter `maxAmount` of `bonusMultiplier` is a bit confusing.
Because the amount can actually bigger.
`amountForMaxBonus` is more accurate.
Change `maxAmount` to `amountForMaxBonus`.
Updated
not necessary
> Clarify parameter of bonusMultiplier

- scripts/nns-dapp/release
`ic-admin` now installs canisters with the `InstallCode` proposal type instead of with an NNS function.
This also results in different output from `ic-admin`.
Additionally, https://github.com/dfinity/nns-dapp/pull/5415 missed one of the instances of `--use-explicit-action-type` that should have been removed.
1. Stop passing `--use-explicit-action-type` to `ic-admin`.
2. Change the way we parse the proposal ID out of the output.
3. Make sure the output is also visible on the terminal (with `tee /dev/tty`) so nothing is hidden in case anything goes wrong.
Tested manually on Mac against a local network.
not necessary
> Fix release script for new proposal type

- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.spec.ts
https://github.com/dfinity/nns-dapp/pull/5497 simplified some numbers which makes it less clear that the correct formatting function is used.
Change the minimum dissolve delay back to being 30 days and 10 hours to keep the original test coverage.
only
not necessary
> Add back lost test coverage in SnsNeuronVotingPowerSection.spec.ts

- frontend/src/lib/utils/tokens-table.utils.ts
- frontend/src/tests/lib/utils/tokens-table.utils.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
Failed imported tokens should be placed in the tokens table below tokens with a balance, so the user is aware of the issues.
- Update the `compareTokensWithBalanceOrImportedFirst` comparator to treat failed tokens as tokens w/o balance.
- New comparator `compareFailedTokensFirst`.
- Updated.
Not necessary.
> Failed tokens sorting

- .github/workflows/build.yml
- scripts/canister_ids
- scripts/canister_ids.local.golden
- scripts/canister_ids.mainnet.golden
The replica with dfx 0.23.0 does not appear to serve `.raw.` URLs correctly.
Before the service worker was removed, we could only use `curl` to fetch raw URLs.
So when importing canister IDs from a URL, we would insert `.raw` into the URL before fetching it with `curl`.
This no longer works, but is also no longer necessary.
Remove the code that inserts `.raw` into the URL to fetch canister IDs from.
1. Tested manually.
2. Added golden tests to CI that use the script on the local replica and on mainnet.
not necessary
> Fix canister IDs import script

- .github/workflows/checks.yml
- scripts/sns/aggregator/get-sns
I wrote this script for some investigation and it seemed useful enough to keep.
It lets you find some quick information about an SNS based on a partial match of the name, symbol or canister ID.
Example:
```
$ scripts/sns/aggregator/get-sns dog
Name:   DOGMI
Symbol: DOGMI
Aggregator URL:         https://3r4gx-wqaaa-aaaaq-aaaia-cai.icp0.io/v1/sns/root/nb7he-piaaa-aaaaq-aadqq-cai/slow.json
Root canister ID:       nb7he-piaaa-aaaaq-aadqq-cai
Governance canister ID: ni4my-zaaaa-aaaaq-aadra-cai
Ledger canister ID:     np5km-uyaaa-aaaaq-aadrq-cai
Index canister ID:      n535v-yiaaa-aaaaq-aadsq-cai
Swap canister ID:       n223b-vqaaa-aaaaq-aadsa-cai
Transaction fee:      50
Minimum neuron stake: 100
Proposal fee:         15000
```
The listed information is just what I needed but we can add more …
> Add get-sns convenience script

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/components/accounts/ImportTokenRemoveConfirmation.svelte
- frontend/src/tests/lib/components/accounts/ImportTokenRemoveConfirmation.spec.ts
- frontend/src/tests/page-objects/ImportTokenRemoveConfirmation.page-object.ts
In the case of a failed imported token, we don’t have the token metadata, such as the logo and token name, but users should still be able to remove the imported token. To achieve this, we first need to make the confirmation dialog work with the ledger canister ID only.
- Change the confirmation component props to work seamlessly with either the universe or the ledger canister ID.
Updated.
Not necessary.
> Update remove imported dialog props to support principal only

- dfx.json
- scripts/canister_ids.local.golden
Snsdemo install an ICP index canister but `dfx nns install` now also installs one (it didn't before) so each snapshot has 2 ICP index canisters.
Before we can stop installing the second one in snsdemo, we need to make sure we are using the default one in nns-dapp.
The one installed by `dfx nns install` has a [hardcoded](https://github.com/dfinity/dfx-extensions/blob/5471d0353f8395c33daf7a6ba9a0778f8b6fc7a8/extensions-utils/src/dependencies/download_wasms/nns.rs#L149) canister ID of `q3fc5-haaaa-aaaaa-aaahq-cai`.
Set the canister ID of `nns-index` in `dfx.json` so that the one installed by `dfx nns install` will be used.
1. I ran `DFX_NETWORK=local ./config.sh` and verified that the new canister ID is used.
2. I ran `npm run dev` and checked that transactions load correctly locally.
3. …
> Use hardcoded nns-icp-index canister ID

- frontend/src/tests/lib/pages/NnsProposals.spec.ts
We want to re-enable the update calls that are disabled via `FORCE_CALL_STRATEGY`.
But this currently results in the following race condition:
1. Load proposals, a certified and an uncertified request are made.
2. The uncertified response data is displayed.
3. Change filters, 2 new requests are made.
4. The second uncertified request returns but then the first certified request returns.
5. This results in displayed proposals going back and forth between different responses.
This PR just adds a test that demonstrates the problem.
The issue will be fixed in a follow-up PR.
Add a test the goes through the above scenario and expects the wrong result.
Drive-by: Remove unused `overrideFeatureFlagsStore` from the test.
Test only
not necessary
> FOLLOW-1337: Expose race condition in NnsProposals

- frontend/src/lib/components/tokens/TokensTable/TokenActionsCell.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/GoToDashboardButton.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/GoToDetailIcon.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/ReceiveButton.svelte
- frontend/src/lib/components/tokens/TokensTable/actions/SendButton.svelte
- frontend/src/lib/types/tokens-page.ts
- frontend/src/lib/utils/user-token.utils.ts
- frontend/src/tests/page-objects/TokensTableRow.page-object.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
To improve the failed imported tokens UI (because we don't display the whole failed ledger canister ID) we add a button to check the ledger canister on the dashboard.
- Extended current token table action buttons to support `UserTokenFailed`, to unify the action types.
- Added new `GoToDashboardButton` action button to the failed token rows.
- A unit test added.
- Tested locally
Not necessary.
> Failed tokens goto dashboard action

- frontend/src/lib/api/sns-dummy.api.ts
Clicking the "Make dummy proposals" on an SNS neuron in the test environment resulted in an error because the "transfer funds" proposal tried to transfer too many funds.
Reduce the amounts of funds transferred in the SNS dummy proposal.
Tested manually
not necessary
> Fix Transfer Funds dummy SNS proposal

- frontend/src/lib/routes/Wallet.svelte
- frontend/src/tests/lib/routes/Wallet.spec.ts
When the user is on the imported token wallet page and the sign-out timer expires, the page reloads, leaving the user on an empty page. This happens because imported tokens are available only when the user is signed in. Upon sign-out, we no longer know the type of the token (whether it’s ICRC or not). Rather than making guesses, it’s more reliable to navigate the user to the main tokens page in this case.
- Navigate to the tokens table when it’s not possible to identify the token. Since this logic is not intended to be reused, it is implemented directly in the component rather than in a derived store.
- Added.
Not necessary.
> Redirection on unknown token.

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/page-objects/WalletPageHeading.page-object.ts
Custom tokens can use metadata like name and symbol from trusted tokens. In the token list they can be distinguished by the "Imported Token" tag. However, on the wallet page this tag is missing and the tokens become indistinguishable.
- Display "imported token" tag on wallet page.
- Added.
Not necessary.
> Display "imported token" tag

- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/lib/services/nns-vote-registration.services.ts
- frontend/src/lib/services/public/proposals.services.ts
- frontend/src/lib/stores/proposals.store.ts
- frontend/src/tests/lib/derived/proposals.derived.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
- frontend/src/tests/lib/stores/proposals.store.spec.ts
We want to re-enable the update calls that are disabled via FORCE_CALL_STRATEGY.
But this currently results in a race condition. See https://github.com/dfinity/nns-dapp/pull/5522 for details.
To fix the race condition, we use a `queuedStore`, similar to https://github.com/dfinity/nns-dapp/blob/main/frontend/src/lib/stores/icp-account-balances.store.ts
1. Change `proposalsStore` to use a `queuedStore`.
2. Change calls to modify `proposalsStore` to use the single-mutation store as necessary to use a queued store.
1. Update tests to use `...ForTesting` mutation functions which hide the use of a single-mutation store.
2. Resolve the TODO in `frontend/src/tests/lib/pages/NnsProposals.spec.ts` which was added to observe the race condition.
3. Add unit tests for `proposalsStore` which check the …
> FOLLOW-1337: Use queuedStore for proposalsStore

- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
- frontend/src/tests/page-objects/NnsProposal.page-object.ts
Make the test easier to maintain.
Also there was a bug in the `"should NOT query neurons"` test. Because the setup was mixing `mutableMockAuthStoreSubscribe` and `mockAuthStoreSubscribe`, the user was actually signed in.
But
```
await waitFor(() =>
expect(governanceApi.queryNeurons).not.toHaveBeenCalled()
);
```
succeeded before the code had a chance to query the neurons.
This is why we should never use `waitFor` and always use `runResolvedPromises` instead.
1. Import the component as its actual name instead of as `ProposalDetail`.
2. Use `resetIdentity()` and `setNoIdentity()` instead of mocking the `authStore`.
3. Don't mock `proposalsStore` or `neuronsStore`.
4. `proposalsApi.queryProposal` instead of mocking the governance canister.
5. Use a page object.
6. Use `runResolvedPromises` …
> Clean up pages/NnsProposalDetail.spec.ts

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-09-26_01-31-no-canister-snapshots

- frontend/src/lib/services/icrc-index.services.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/services/icrc-index.services.spec.ts
Use an update call to make sure that the canister ID is correct and was not manipulated by a malicious node.
- Call `ledger_id` with certified request.
Drive-by change: fixed a typo.
- Updated.
Not necessary.
> Verify imported ledger with certified call

- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/StakeNeuronToVote.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseNav.spec.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
The `aggregatorSnsMockDto` has data for an aborted SNS. This makes it very non-standard/surprising when used in a test.
While in principal, a test should specify all the fields that it cares about, I think it's reasonable to expect the test data not to be for an aborted SNS.
1. Use `aggregatorMockSnsesDataDto[4]` instead of `aggregatorMockSnsesDataDto[7]` as `aggregatorSnsMockDto`.
2. Added a comment explaining why `4`.
3. `export convertDtoToTokenMetadata` to make sure `aggregatorTokenMock` matches `aggregatorSnsMockDto` (as required by the comment) without having to hard code the same data.
Updated tests that started failing by specifying more data explicitly in the tests.
not necessary
> Use a non-aborted SNS as mock data

- CHANGELOG-Nns-Dapp-unreleased.md
After last week's upgrade, we had to revert to the previous version.
I kept the changelog for the proposal but I think it makes sense to restore the unreleased changelog so that the changes are reflected in the next proposal as what has changed since the current prod release.
Revert just `CHANGELOG-Nns-Dapp-unreleased.md` from https://github.com/dfinity/nns-dapp/pull/5536
no
> Restore changelog after rollback

- .config/spellcheck.dic
- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/public/sns.services.ts
- frontend/src/lib/stores/sns-aggregator.store.ts
- frontend/src/tests/lib/derived/sns-aggregator.derived.spec.ts
- frontend/src/tests/lib/derived/sns-functions.derived.spec.ts
- frontend/src/tests/lib/derived/sns-parameters.derived.spec.ts
- frontend/src/tests/lib/derived/sns-swap-canister-accounts.derived.spec.ts
- frontend/src/tests/lib/derived/sns-total-token-supply.derived.spec.ts
- frontend/src/tests/lib/derived/sns/sns-tokens.derived.spec.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
- frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts
- frontend/src/tests/lib/stores/sns.store.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
- frontend/src/tests/utils/sns.test-utils.ts
We had a bug because we tried to parse nervous system parameters on aborted SNSes.
All live SNSes do have nervous system parameters and we don't display aborted SNSes so there is no reason to parse them.
1. Rename `snsAggregatorStore` to `snsAggregatorIncludingAbortedProjectsStore` to avoid confusion and add `snsAggregatorStore` as a derived store which does not contain aborted SNSes.
1. Update sets which (re)set data on `snsAggregatorStore` to set it on `snsAggregatorIncludingAbortedProjectsStore`.
2. Add a utility to test with prod SNS data.
3. Updated `setSnsProjects` to allow setting `nervousSystemParameters: null`.
4. Add tests that `SnsProposalDetail` can render with aborted SNSes (explicitly) and with prod SNSes (which also contain aborted SNSes).
5. Add unit tests for new derived …
> Filter aborted SNSes from snsAggregatorStore

- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/stores/icrc-accounts.store.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/stores/icrc-accounts.store.spec.ts
When testing under real network conditions (not locally), there’s a high chance that when a call fails, some unrelated balances in the tokens table will display a loading state, even though all of them were successfully loaded. The reason for this behaviour is that, on a failed call (e.g. failed imported token) in the `loadAccounts` function, the whole accounts store gets reset.
To reproduce, there should be at least one failed imported token in the table.
Presumably, this was implemented this way because initially, [only a single ICRC1 token](https://github.com/dfinity/nns-dapp/pull/1918/files#diff-4be3667b0d4ed46a702674d48f6e1e4c2b18ef0bf68e2e89170d78ea1bf22758R48) was supported by the NNS dapp.
To avoid this, we now reset the store only for the failed account.
- Added `resetUniverse` …
> Fix not loaded balances on failed imported

- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
Due to backend validation, it is currently not possible to import more than 20 tokens. To improve the user experience, we disable the import button when the user has already imported the maximum number of custom tokens.
- Display a disabled import button when maximum reached.
- Don’t display the import button until the imported tokens have loaded, to ensure its correct status is shown.
- Unit tests updated.
- Manually:
| Enabled | Disabled |
| <img width="166" alt="image" src="https://github.com/user-attachments/assets/1e3b656f-d9a2-4479-831b-e7fde16ec533"> | <img width="213" alt="image" src="https://github.com/user-attachments/assets/8d35cec2-585a-4759-b21a-2feb66a835d7"> | 
Not necessary.
> Disable import button on maximum

- frontend/src/tests/lib/services/neurons.services.spec.ts
https://github.com/dfinity/nns-dapp/pull/5553 added 2 tests that produce `console.error()` output.
They relied on a third test, that mocks out `console.error` to be run first so that the logging is ignored.
So these tests fail when run in isolation.
And the third test didn't even need `console.error` to be mocked out.
1. Restore and recreate the `console.error` spy before each test.
2. Remove mocking `console.error` from the test that doesn't need it.
3. Add mocking `console.error` to the tests that do need it.
Tests only
not necessary
> Restore console.error spy between tests

- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/workflows/Launchpad/ProdLaunchpad.spec.ts
In `loadIcrcToken` we try to ignore errors on query calls if there is also an update call.
For this we use the following logic:
```
if (!certified && notForceCallStrategy()) {
return;
}
```
This assumes that we make an update call unless `notForceCallStrategy()` returns `false`.
But it's also possible to pass `certified: false` into `loadIcrcToken` and then we also don't make an update call, but the error is still skipped on query calls so in that case we ignore all errors.
1. Take the `certified` that's passed `loadIcrcToken` into into account to determine whether to ignore errors.
1. Add unit tests for `loadIcrcToken`.
2. Mock `queryIcrcToken` in `workflows/Launchpad/ProdLaunchpad.spec.ts` as it is now showing errors that were always there about not being able to destructure its result. …
> Fix uncertified error in loadIcrcToken

- dfx.json
> bot: Update snsdemo to release-2024-10-02

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/components/proposal-detail/VotingCard/NnsVotingCard.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/NnsVotingCard.spec.ts
- frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
- frontend/src/tests/lib/services/actionable-proposals.services.spec.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
- frontend/src/tests/page-objects/VotingCard.page-object.ts
There are multiple reports from users who can’t vote. We believe the root cause of this issue is the 100-ballot limit for neurons. If a user has voted on more than 100 proposals (a likely scenario over a 4-day period), they don’t receive ballots for proposals they’ve already voted on, which remain technically votable due to this limit. The suggested solution is to switch from using neuron ballots to proposal ballots when calculating the votable state.
The utilities have already been already updated in `ic-js` - https://github.com/dfinity/ic-js/pull/725
- Update the displayed votable neurons on proposal changes as well, since we use the proposal ballots to determine the neurons’ voting state.
- Updated.
- Manually
1.	Created 100+ proposals.
2.	Voted on them.
3. …
> Use proposal ballots for voting state

- scripts/sns/aggregator/get-sns
With the latest "Update SNS Aggregator Response" PR, the CI test for the `get-sns` script started failing with [Error: writing output failed: Broken pipe](https://github.com/dfinity/nns-dapp/actions/runs/11181791065/job/31086597771).
This happens because the script uses `grep -m 1` which stops reading input after the first match is found but the command on the other side of the pipe still wants to write to it.
If we use `head -n 1` instead, `grep` will read all its input but `head` will not, so theoretically this just moves the problem.
But in practice the size of the input is already reduced so much that the problem goes away (hopefully).
In `get-sns`, use `| head -n 1` instead of passing `-m 1` to `grep`.
Tested on CI on https://github.com/dfinity/nns-dapp/pull/5566 where this test was …
> Use head instead of grep -m

- frontend/src/tests/e2e/neuron-details.spec.ts
- frontend/src/tests/utils/e2e.test-utils.ts
In the neuron details e2e test we replace the neuron ID with a fixed value so that it doesn't cause the screenshot to be different each time.
When doing this we expect the existing neuron to have 19 digits, but neuron IDs can also have fewer than 19 digits.
And when the existing neuron ID doesn't match the expected pattern it's not replaced which results in test flakiness.
1. Relax the expected neuron ID pattern.
2. Expect the number of replacements for each call to `replaceContent` to be greater than 0 to help catch cases where nothing is replaced without having to download the screenshot.
Only tests.
not necessary
> Fix replacement of neuron ID in screenshot test
