dfinity/nns-dapp

- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/services/ckbtc-info.services.ts
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/services/imported-tokens.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/public/proposals.services.ts
- frontend/src/lib/services/public/sns.services.ts
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/services/sns.services.ts
- frontend/src/lib/services/utils.services.ts
- frontend/src/lib/utils/env.utils.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
- frontend/src/tests/lib/services/ckbtc-info.services.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/services/imported-tokens.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
- frontend/src/tests/lib/services/utils.services.spec.ts
- frontend/src/tests/lib/utils/env.utils.spec.ts
- frontend/vitest.setup.ts
With `queryAndUpdate` we make 2 calls but sometimes we only want to do something for 1 of the calls.
For example, if there is an error in the query call, we just ignore it and wait for the update call.
The problem is that `queryAndUpdate` doesn't always do 2 calls and there is some logic to determine whether to do 2 calls or not. If the user is not logged in, we only do a query call and it's also possible to pass in a strategy, which might also depend on the value of `FORCE_CALL_STRATEGY`.
Altogether this makes knowing which strategy is currently being used, and thus whether we are doing 1 or 2 calls, and thus whether the current call is the last call or if another call is still following, quite fragile.
In this PR, we make `queryAndUpdate` pass the actually used strategy to the `onLoad` …
> Simplify 'last call' logic for queryAndUpdate

- CHANGELOG-Nns-Dapp-unreleased.md
Changelog entry was missing from https://github.com/dfinity/nns-dapp/pull/5560
Added missing changelog entry.
no
> Changelog entry for dissolve delay issue

- frontend/.gitignore
- frontend/.prettierignore
- frontend/src/lib/services/public/app.services.ts
- frontend/src/lib/services/public/sns.services.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
We had `public` in several `.*ignore` files to avoid acting on the build output in `/frontend/public`.
But this also matched paths with `public` deeper down in the path.
1. Change `public` to `/public` in `frontend/.gitignore` and `frontend/.prettierignore`.
2. Format file that were previously ignored by `prettier`.
not tested, just CI.
not necessary
> Only ignore `/public` instead of `public`

- frontend/src/lib/components/proposal-detail/VotingCard/NnsVotingCard.svelte
- frontend/src/lib/constants/mockable.constants.ts
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/lib/services/icp-accounts.services.ts
- frontend/src/lib/utils/ckbtc.utils.ts
- frontend/src/lib/utils/env.utils.ts
- frontend/src/tests/utils/mockable-constants.test-utils.ts
- frontend/vitest.setup.ts
`isForceCallStrategy` and `notForceCallStrategy` only depend on `FORCE_CALL_STRATEGY`.
By putting them in a different file, it creates additional dependencies for workers that depend on anything else in that file.
I noticed this while making a PR to initialize `FORCE_CALL_STRATEGY` randomly for a percentage rollout and logging what it was initialized to, because I noticed 2 log lines every time I loaded the app: 1 from the main app and 1 from a worker.
1. Move `isForceCallStrategy` and `notForceCallStrategy` into same file as `FORCE_CALL_STRATEGY`.
2. Update imports.
3. Add default mock values for the functions to satisfy the compiler.
By adding a log statement, tested that `frontend/src/lib/constants/mockable.constants.ts` is now loaded once instead of twice.
not necessary
> Move isForceCallStrategy and notForceCallStrategy to mockable.constants.ts

- rs/backend/src/state.rs
- rs/backend/src/state/tests.rs
This is the follow-up to https://github.com/dfinity/nns-dapp/pull/5431
In that PR we stored the TVL state to stable memory but we couldn't yet restore the TVL state from stable memory because we didn't have a release that made sure there was TVL state to be restored from stable memory.
After the most recent upgrade we now do so we can complete the TODOs left in that PR.
1. Load TVL state from stable memory.
2. Decode loaded TVL state into canister state.
1. Remove test that checks TVL state is not decoded.
2. Update test to make sure that TVL state is decoded.
covered
> NNS1-3281: Decode TVL state from stable memory

- .github/workflows/update-next.yml
We have a GitHub workflow to create gix-components or ic-js bump PRs.
Usually the person requesting the bump PR can also approve it themselves.
But sometimes peterpeterparker requests one and then I approve it.
So it's useful to see who requested the PR.
Mention the workflow actor in the PR description.
Created https://github.com/dfinity/nns-dapp/pull/5587
not necessary
> Include actor in bump PR description

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/sns-neuron.utils.ts
- frontend/src/tests/lib/derived/sns/sns-sorted-neurons.derived.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/lib/utils/sns-neuron.utils.spec.ts
We hide neurons with zero stake.
The exact logic we use for this is that we hide neurons for which the `stake+maturity < fee` (or `< 0` for SNS).
The problem is that this fails to take staked maturity into accounts.
It's tricky to get a neuron with staked maturity without stake because if the neuron doesn't have a dissolve delay, the staked maturity is automatically reverted to normal maturity. So the repro steps are:
1. Stake a neuron
2. Set a dissolve delay on the neuron.
3. Wait for maturity > fee to build up.
4. Dissolve the neuron.
5. Disburse the neuron.
6. Add a dissolve delay to the neuron.
7. Stake the maturity.
In the test environment, steps 2-4 can be replaced with just adding maturity.
Take staked maturity into account for wether to hide NNS and SNS neurons.
1. Unit tests …
> Don't hide neurons which only have staked maturity

- frontend/src/lib/pages/Tokens.svelte
- frontend/src/tests/lib/pages/Tokens.spec.ts
Imported tokens should always be shown to the user, regardless of the hide-zero-balance filter. This will help avoid confusion if a user can’t find a custom token after importing it due to the filter being active.
- Exclude imported tokens from the zero-balance filter.
- Added and tested that it fails w/o changes.
Not necessary.
> Ignore zero balance filter for imported tokens

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/mockable.constants.ts
We want to re-enable the update calls that are disabled via FORCE_CALL_STRATEGY.
Because this may result in higher subnet load, we want to first roll this out for 10% of sessions.
1. Initialize `FORCE_CALL_STRATEGY` on app load, to `"query"` 90% of the time and to `undefined` 10% of the time.
2. Output what it was initialized to, in case we need to know this later for trouble shooting.
1. Manually tested by checking the logged value and by adding additional logging in `queryAndUpdate`.
2. `FORCE_CALL_STRATEGY` itself has existing test coverage so it should work either way.
> FOLLOW-1337: Disable FORCE_CALL_STRATEGY for 10% of sessions

- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/page-objects/App.page-object.ts
Enabling query+update for `listNeurons` causes some flakiness in the `neuron-increase-stake.spec.ts` e2e test.
We have a cache in `governance.api-service.ts` but it only caches certified responses. Making more certified calls means that we hit the cache more often, which can also result in seeing stale data.
When topping up a neuron by making a direct transfer to the neuron account, the app doesn't know the neuron is being topped up so it doesn't invalidate the cache. So to see the result we need to reload the page in the e2e test.
I also found a missing `await` in the function which navigates back as far as possible which caused it to sometimes not realize it had already navigated.
And there was a race condition between the e2e test navigating back (and not waiting for the navigation to …
> Fix flakiness in neuron-increase-stake.spec.ts

- scripts/vote
In local testing it can be convenient to quickly vote one or all proposals through.
Especially since snsdemo8 has a neuron with a lot of voting power.
Added a script that can be used to vote on one or all proposals without having to look up neuron IDs.
not necessary
> A script to vote on proposals

- frontend/src/lib/routes/Wallet.svelte
- frontend/src/tests/lib/routes/Wallet.spec.ts
Depending on which response arrives first, reloading the imported token page could automatically navigate the user to the tokens page, which is unintended behaviour. This happens because the check for whether the current token is unknown occurs before the imported tokens are fully loaded.
- Wait for the imported tokens being loaded before checking for navigation.
- Updated. The current test fails after changes.
Not necessary.
> Fix navigation on imported reload

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
I found a bug that the "no proposals" message is not shown when query+update is enabled (`FORCE_CALL_STRATEGY = undefined`) and the user is not signed in.
This happened because `nothingFound` was not updated if `$filteredProposals.certified === false && notForceCallStrategy()`. That is if the proposals are the result of a query response, while we also expect an update response.
The first problem is that when the user is not signed in, by default [we don't follow the query call with an update call](https://github.com/dfinity/nns-dapp/blob/a86684b1625ddf972d92052e2ba8e3d31feb21ac/frontend/src/lib/services/utils.services.ts#L72-L74).
So the assumption that because `notForceCallStrategy()`, the query call will be followed by an update call, is not true when the user is not signed in. This …
> Fix showing "no proposals" when not signed in

- frontend/src/lib/routes/Wallet.svelte
- frontend/src/tests/lib/routes/Wallet.spec.ts
In PR [#5596](https://github.com/dfinity/nns-dapp/pull/5596), we began checking for the loading of imported tokens to handle navigation from the wallet page for unknown tokens. This fixed the targeted issue but unintentionally broke redirection to the tokens page after sign-out. To restore the sign-out redirection, we also need to consider the login state.
- Ignore imported token readiness when signed out, as we don’t load them in this state.
- Added.
Not necessary.
> Ignore imported tokens for redirection when signed out

- dfx.json
> bot: Update snsdemo to release-2024-10-09

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
A race condition in `NnsProposals.svelte` was exposed by `e2e/proposals.spec.ts` when query+update is enabled.
The problem is that `loading = false` is set when any request for proposals finishes.
But if there are multiple simultaneous requests, an old request can finish while a new request is still in flight.
Then `loading = false` will be set because of the old request while we should still be showing skeleton cards because of the new request.
1. Create an opaque "token" every time we load proposals. When we finish loading proposals, check if the current token is still the same and only set `loading = false` if it is.
2. Wrap this logic in a function which is shared between `findProposals` and `findNextProposals`.
1. Added a unit test which makes multiple simultaneous requests.
2. Run …
> Fix race condition in proposal loading

- scripts/vote
Voting on a lot of proposals can be quite slow.
Call the script multiple times in parallel when voting on multiple proposals.
The `&` at the end of the command runs the command in the background.
At the end we wait for all the processes before exiting the script.
Tested manually
not necessary
> Make vote script vote in parallel

- frontend/src/lib/components/accounts/ImportTokenForm.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/accounts/ImportTokenForm.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/page-objects/ImportTokenForm.page-object.ts
Despite being disabled, the ledger canister field is too prominent in the "Add Index Canister" modal.
- Use the CanisterId component in the "Add Index Canister" modal.
- Additionally, update the placeholder to avoid confusing users with the incorrect canister format.
- Updated
Not necessary.
> Imported ledger input update

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/lib/services/imported-tokens.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
To avoid confusion and ensure consistency with the inability to add other existing tokens, ICP should not be importable.
- Extend validation to prevent importing the ICP ledger canister id.
- Updated.
Not necessary.
> Import icp validation

- Cargo.lock
- Cargo.toml
The IC repo has failed to make a release for the past 2 weeks.
There have been release tags so I tried updating to `release-2024-10-11_14-35-base` but the Cargo build of `icrc-ledger-types` is actually broken at that commit.
The Cargo build works at the latest (untagged) commit `45eee81e4604c07306e29622aac41c600b024185` so let's update to that.
Ran `scripts/update-ic-cargo-deps --ref 45eee81e4604c07306e29622aac41c600b024185`.
CI passes
not necessary
> Update IC cargo deps to 45eee81e4

- .github/actions/build_nns_dapp/action.yaml
- .github/workflows/checks.yml
- .github/workflows/update-aggregator.yml
- .github/workflows/update-didc.yml
- .github/workflows/update-proposals.yml
- .github/workflows/update-snsdemo.yml
- Dockerfile
- dfx.json
- scripts/setup
The current `didc` version (that is the output of `didc --version`) is `0.4.0` which is installed from release `2024-05-14`.
While trying to debug why the recent "Update sns_aggregator candid bindings" [failed](https://github.com/dfinity/nns-dapp/actions/runs/11338847183), I got very confused because I had a different version installed.
So I want to change our scripts to check that you have the correct version installed.
For this, I need to add what is the correct version to our repo config.
To obvious name for this is `DIDC_VERSION` but we already use `DIDC_VERSION` to denote the current release.
So before adding `DIDC_VERSION` we should rename `DIDC_VERSION` to `DIDC_RELEASE` to more accurately reflect what it is.
Rename `DIDC_VERSION` in `dfx.json` (and everywhere that refers to it) to …
> Rename DIDC_VERSION to DIDC_RELEASE

- scripts/nns-dapp/download-ci-wasm
CI is currently failing when trying to download `nns-dapp.wasz.gz` from a GitHub CI run with the following error:
```
error downloading dfinity~nns-dapp~QD3EC4.dockerbuild: error extracting zip archive: zip: not a valid zip file
```
Example failure: https://github.com/dfinity/nns-dapp/actions/runs/11344052055/job/31548002318
I have no idea why this is happening but passing the artifact name to `gh run download` seems to help.
Pass `-n nns-dapp` to `gh run download` in `scripts/nns-dapp/download-ci-wasm`.
CI passes again.
not necessary
> Specify artifact name in download-ci-wasm

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/api.constants.ts
There are plans to wind down the Internet Computer Association neuron in the future (refer [to this forum post](https://forum.dfinity.org/t/strengthening-governance-by-aligning-neuron-28s-voting-power-under-neuron-27/35957) for more information). To make this clearer to users who follow this neuron, we’re changing its name.
- Change the neuron name.
- Manually
> Change ICA neuron name

- declarations/used_by_sns_aggregator/sns_governance/sns_governance.did
- declarations/used_by_sns_aggregator/sns_ledger/sns_ledger.did
- declarations/used_by_sns_aggregator/sns_root/sns_root.did
- declarations/used_by_sns_aggregator/sns_swap/sns_swap.did
- declarations/used_by_sns_aggregator/sns_wasm/sns_wasm.did
- dfx.json
- rs/sns_aggregator/src/types/ic_sns_governance.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.rs
- rs/sns_aggregator/src/types/ic_sns_root.rs
- rs/sns_aggregator/src/types/ic_sns_swap.rs
- rs/sns_aggregator/src/types/ic_sns_wasm.rs
- scripts/update_ic_commit
"Update sns_aggregator candid bindings" [failed](https://github.com/dfinity/nns-dapp/actions/runs/11338847183/job/31540786783) because ledger and Index Candid files were moved to a different directory in https://github.com/dfinity/ic/pull/1682
After fixing the path in the script, I had to also update the candid files to the new commit, because we have a [test](https://github.com/dfinity/nns-dapp/blob/a360d0281792040f8930f089c59aef9996188024/.github/workflows/checks.yml#L140-L143) that checks that the current code matches what would be generated at the current version in `dfx.json` and without updating `dfx.json` it would try to download from the new path at the old version which also fails.
The important changes are in the first commit and updating the candid and bindings is in the second …
> Download ledger.did from new path

- .github/actions/vitest/action.yml
- .github/workflows/checks.yml
Frontend unit tests can take quite long to run. Typically about 12 minutes.
If we split running the tests in 2 jobs, we don't have to wait as long.
1. Created a GitHub action to run a shard of frontend unit test.
2. Used the new action to split frontend unit tests into 2 shards.
Ran CI with both the old and the new job: https://github.com/dfinity/nns-dapp/actions/runs/11367971323
All `svelte-tests`:
```
Test Files  559 passed (559)
Tests  4455 passed | 3 skipped (4458)
Start at  14:39:08
Duration  708.75s (transform 17.17s, setup 500.00s, collect 988.65s, tests 102.32s, environment 257.01s, prepare 66.20s)
```
`vitest-shard-1-of-2`:
```
Test Files  280 passed (280)
Tests  2423 passed | 2 skipped (2425)
Start at  14:38:38
Duration  374.15s (transform 15.70s, setup 263.12s, collect 536.14s, …
```
> Shard frontend tests

- frontend/src/tests/lib/components/neuron-detail/actions/NnsAutoStakeMaturity.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsAutoStakeMaturity.spec.ts
A recent PR in gix-components (https://github.com/dfinity/gix-components/pull/505) prevents click evens in unit tests from clicking on disabled checkboxes.
This revealed that the checkboxes in `NnsAutoStakeMaturity.spec.ts` and `SnsAutoStakeMaturity.spec.ts` were always disabled and working while they should not have been working.
While there was a test that the checkbox could be disabled, there was not test checking that the checkbox could also be enabled.
1. Add missing test coverage that the checkbox can be enabled.
2. Make sure the checkbox is enabled in the tests that need it to be enabled.
3. Drive-by fix: Use `beforeEach` instead of `afterEach`.
Temporarily updated gix-components dependency to make sure these 2 tests work with the new gix-comeponents.
not necessary
> Enable checkbox in auto stake maturity tests

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/components/common/MenuItems.svelte
With https://github.com/dfinity/gix-components/pull/498 the bottom logo in the menu is now directly taking space in the menu DOM. So we no longer need to add a bottom margin below the Source code button.
1. Ran `npm run update:gix`.
2. Removed the bottom margin in the menu footer.
Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
> Bump gix-components and stop hiding bottom logo and menu collapse button

- frontend/src/tests/lib/components/ui/Hash.spec.ts
- frontend/src/tests/page-objects/Hash.page-object.ts
- frontend/src/tests/page-objects/Tooltip.page-object.ts
Make the test easier to maintain.
In particular this helps with updating the test dependencies because the rendered container is no longer the document body so the way this test tries to find the tooltip doesn't work.
1. Use page objects.
2. Expect explicit values instead of constructing values the same way the code under test does.
3. Escape the element ID passed to `body.querySelectorAll` because apparently these are not allowed to start with a digit. This could be done with `CSS.escape` but unfortunately that's not supported in Playwright tests.
The test still passes.
I did not verify that this work with the new dependencies, but if it doesn't we should fix it in the page object, not in the test.
not necessary
> Use page objects for Hash.spec.ts

- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
- frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/sale/ParticipateSwapModal.spec.ts
- frontend/src/tests/lib/pages/Canisters.spec.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/nns-reward-event.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
In newer versions of `vitest`, `SpyInstance` is no longer available and `MockInstance` should be used instead.
Replace `SpyInstance` with `MockInstance` in unit tests.
Still pass.
not necessary
> Replace SpyInstance with MockInstance

- rs/backend/src/tvl.rs
- rust-toolchain.toml
The [automatic update PR](https://github.com/dfinity/nns-dapp/pull/5644) had lint failures because Rust 1.82.0 wants a different syntax for type casts from `u64` to `u128`.
```
error: casts from `u64` to `u128` can be expressed infallibly using `From`
--> rs/backend/src/tvl.rs:171:27
|
171 |         let locked_u128 = state.total_locked_icp_e8s as u128;
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: an `as` cast can become silently lossy if the types change in the future
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_lossless
= note: `-D clippy::cast-lossless` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::cast_lossless)]`
help: use `u128::from` instead
|
171 |         let …
```
> Update rust version to 1.82.0

- frontend/src/tests/e2e/import-token.spec.ts
- frontend/src/tests/utils/e2e.test-utils.ts
The ledger and index canister of ckRED are hard coded in `frontend/src/tests/e2e/import-token.spec.ts`.
But the canister IDs are not guaranteed to remain the same in snsdemo.
In particular, with the latest snapshot, they are different, resulting in test failures in the [automatic update PR](https://github.com/dfinity/nns-dapp/pull/5645).
1. Add a utility function that calls `dfx` to get a canister ID.
2. Use the new function to get the correct canister IDs in the e2e test.
The test passes locally with a newer snapshot and still passes on current CI as well.
not necessary
> Get canister ID with dfx in e2e test

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/page-objects/MenuItems.page-object.ts
When the menu is collapsed, the menu footer (with TVL and code/theme buttons) is moved out of view, but it still takes up space in the DOM. This means the scrollbar appears sooner than necessary on small screens.
1. Use `{#if}` to remove the menu footer when the menu is collapsed.
2. Use Svelte animation to animate the dis/reappearance instead of CSS transition. Use `cubicIn` and `cubicOut` because they make sure the element is always smaller than the space it has, which avoids strange looking reflowing of the content.
> Remove menu footer when menu is collapsed

- scripts/sns/aggregator/test-fast
The aggregator test on CI [is flaky](https://github.com/dfinity/nns-dapp/actions/runs/11403403979/job/31730884616?pr=5652).
Waiting for the lifecycle to change timed out because swap canisters no longer update their state on every heartbeat but only once a minute.
Increase the timeout when waiting for the lifecycle to change.
Not tested except for on CI.
not necessary
> Wait longer for lifecycle in aggregator test

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-10-17_03-07-scheduler-changes-guestos-revert

- frontend/src/app.html
Chrome is warning about the deprecation of `apple-mobile-web-app-capable` which should be replaced by `mobile-web-app-capable`.
> [!WARNING]  
> meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes"
A similar change was applied in Flutter. See https://github.com/flutter/flutter/issues/154596.
- https://web.dev/learn/pwa/web-app-manifest#designing_your_pwa_experience
> [!CAUTION]
> Warning: Before the web app manifest spec was defined, several browsers, including Safari on iOS/iPadOS and Chrome on Android, supported custom <meta> elements to describe the application experience, such as apple-mobile-web-app-capable. Do not use these <meta> elements today; it's no longer recommended, and may harm the …
> feat: replace deprecated meta-tag apple-mobile-web-app-capable

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/canisters/AddCyclesModal.spec.ts
- frontend/src/tests/lib/modals/canisters/CreateCanisterModal.spec.ts
- frontend/src/tests/lib/modals/canisters/LinkCanisterModal.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/icp-ledger.services.spec.ts
- frontend/src/tests/lib/services/icrc-index.services.spec.ts
- frontend/src/tests/lib/services/imported-tokens.services.spec.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/services/sns-sale.services.spec.ts
- frontend/src/tests/lib/services/sns-vote-registration.services.spec.ts
- frontend/src/tests/mocks/proposal.mock.ts
To make the tests more robust we should not mock stores but use real stores.
By doing so, I also found a bug:
In https://github.com/dfinity/nns-dapp/pull/4244 I removed `sns_amount_not_enough_stake_neuron` because I thought it was not used. But it turned out it was used and cleaning up the tests exposed that, so I restored it in this PR as well.
1. Stop mocking `toastsStore` functions.
2. Expect the full contents of the store.
3. Expect the store to be empty before it's filled.
4. Expect actual messages instead of label keys.
5. Restore `sns_amount_not_enough_stake_neuron`. I also removed `a neuron` from the message, in line with the intent of https://github.com/dfinity/nns-dapp/pull/4244
1. The updated tests still pass.
2. In one case the test showed that the toast was showing a label …
> Stop mocking toastsStore

- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/utils/env.utils.ts
- frontend/src/tests/lib/utils/env.utils.spec.ts
When connecting from localhost to a non-local environment (such as DevEnv or mainnet) we add `.raw` to the SNS aggregator URL.
This was originally done to avoid being redirected by the boundary node to the service worker, because that would result in CORS issues when connecting from localhost.
But:
1. The boundary node no longer redirects to the service worker
2. Raw URLs stopped working on DevEnv ([slack thread](https://dfinity.slack.com/archives/CGA566TPV/p1727177718754779))
So adding `.raw` to the aggregator URL is no longer necessary and also breaks.
Time to remove this code.
1. Stop adding `.raw` to the SNS aggregator URL.
2. Remove `addRawToUrl` as it is no longer user.
Tested manually:
1. From localhost to localhost
2. From localhost to DevEnv
3. From DevEnv to DevEnv
4. From …
> Stop adding .raw to aggregator URL

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/icp-accounts.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
There was a [forum post](https://forum.dfinity.org/t/i-having-trouble-transferring-icp-from-the-nns-dapp/36038) from a user who kept getting errors when trying to transfer ICP.
In the end it turned out to be a problem with their computer's time settings.
To avoid this situation in the future we want to provide better error messages.
1. Remove the `labelKey` parameter from `transferError` as `transferError` is only called in 1 place with a hardcoded `labelKey` argument.`
2. In `transferError` use the originally passed-in `labelKey` as default but use a different `labelKey` if the error is `TxTooOldError` or `TxCreatedInFutureError`.
3. Add new messages for the new label keys.
1. Add missing test coverage for a generic error from `sendICP`.
2. Add tests for `TxTooOldError` and …
> NNS1-3391: Add error messages for incorrect transaction timestamps

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/nns-vote-registration.services.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
While voting, we update the toast multiple times to show the status of the voting.
The toast also shows the proposal ID and topic or type. But whether it shows topic or type is inconsistent between toasts.
Consistently identify the proposal by its topic in vote registration toasts.
Tests are updated.
> Show proposal type in vote registration

- scripts/get-neurons
- scripts/propose-install-canister
- scripts/vote
When testing, it can be useful to replace one of the NNS canisters with a custom built version.
This can be tricky because for some of the canisters we are not the controller so they need to be installed via proposal, which requires a lot of arguments to be constructed for a shell command.
It would be convenient to have a script that does this for you.
1. Extract `scripts/get-neurons` from `scripts/vote` to get neurons of an identity.
2. Add `scripts/propose-install-canister` which constructs and calls the `ic-admin` command to propose installing a canister.
Tested manually with
```
scripts/propose-install-canister --canister nns-dapp --wasm nns-dapp.wasm.gz --arg-did-file nns-dapp-arg-local.did 
scripts/propose-install-canister --canister nns-governance --wasm …
```
> Add scripts/propose-install-canister

- frontend/src/lib/components/ic/AmountDisplay.svelte
- frontend/src/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.svelte
- frontend/src/lib/modals/neurons/NeuronVisibilityRow.svelte
- frontend/src/lib/types/neuron-visibility-row.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
- frontend/src/tests/lib/modals/neurons/NeuronVisibilityRow.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
The design of form has been changed and now includes the staked ICP in neuron visibility row.
Still the rows needs to be sorted based on staked amount, this functionality added in a [seperate PR.](https://github.com/dfinity/nns-dapp/pull/5676)
1. Add label color to AmountDisplay to control the color from parent.
2.  Add stake to NeuronVisibilityRowData and update createNeuronVisibilityRowData to provide stake data
not necessary
> Add staked amount to neuronVisibilityRow

- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/utils.services.ts
- frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
- frontend/src/tests/lib/services/utils.services.spec.ts
After updating the dependencies, the test ["should update votable neurons after voting"](https://github.com/dfinity/nns-dapp/blob/29fffda7583518c59991a1c01f31836305475f24/frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts#L138) is broken. The logs show that the service, after calling queryNeurons, first receives the certified response and then the uncertified query (with the current test dependencies the uncertified one comes first). For an unknown reason, the store listener is triggered only once, for the second call (which became an uncertified response, since it's the last one), which breaks the logic [in NnsVotingCard](https://github.com/dfinity/nns-dapp/blob/29fffda7583518c59991a1c01f31836305475f24/frontend/src/lib/components/proposal-detail/VotingCard/NnsVotingCard.svelte#L117) …
> Ignore query call after certified without finally

- frontend/src/tests/lib/components/common/SignInGuard.spec.ts
- frontend/src/tests/lib/components/common/SignedInOnly.spec.ts
- frontend/src/tests/lib/components/header/AccountSyncIndicator.spec.ts
- frontend/src/tests/lib/components/layout/UniverseSplitContent.spec.ts
- frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
- frontend/src/tests/lib/components/proposal-detail/ProposalSystemInfoProposerEntry.spec.ts
- frontend/src/tests/lib/components/proposal-detail/ProposalVotingSection.spec.ts
- frontend/src/tests/lib/components/proposals/NnsProposalsFilters.spec.ts
- frontend/src/tests/lib/components/transaction/TransactionReview.spec.ts
- frontend/src/tests/lib/pages/Launchpad.spec.ts
- frontend/src/tests/mocks/auth.store.mock.ts
- frontend/src/tests/routes/app/canister/page.spec.ts
- frontend/src/tests/routes/app/canisters/page.spec.ts
- frontend/src/tests/routes/app/neuron/page.spec.ts
- frontend/src/tests/routes/app/neurons/page.spec.ts
- frontend/src/tests/routes/app/settings/page.spec.ts
These were missed in https://github.com/dfinity/nns-dapp/pull/5571
We should not mock stores.
1. Replace `authStoreMock.next({ identity: undefined});` with `setNoIdentity();`.
2. Replace `authStoreMock.next({ identity: mockIdentity});` with `resetIdentity();`.
3. Remove ` vi.spyOn(authStore, "subscribe").mockImplementation(mutableMockAuthStoreSubscribe);`
4. Remove `authStoreMock` and `mutableMockAuthStoreSubscribe`.
5. Replace `beforeAll` with `beforeEach` where encountered.
6. Remove a few encountered cleanup `afterAll`s as there is no point in doing cleanup when all the tests are finished.
Only tests. Still pass.
not necessary.
> Remove authStoreMock and mutableMockAuthStoreSubscribe

- frontend/src/tests/lib/components/accounts/BalancesObserver.spec.ts
- frontend/src/tests/lib/components/accounts/IcrcBalancesObserver.spec.ts
- frontend/src/tests/lib/components/accounts/IcrcWalletTransactionsObserver.spec.ts
- frontend/src/tests/lib/components/accounts/TransactionsObserver.spec.ts
- frontend/src/tests/lib/services/worker-balances.services.spec.ts
- frontend/src/tests/lib/services/worker-transactions.services.spec.ts
Because [vi.doMock is not hoisted to the top of the file](https://vitest.dev/api/vi.html#vi-domock), only the next dynamic import of the module will be mocked. This could lead to unpredictable errors when some modules are not mocked (e.g., ReferenceError: Worker is not defined).
- Replace doMock with mock.
- Pass
not necessary.
> Replace doMock with mock

- scripts/github-rerun
Sometimes when a test fails because of a network issue or other flakiness, we want to rerun the test.
Unfortunately, the rerun can only be triggered after all the other tests have also finished.
For that it can be useful to keep trying to rerun in a loop until it succeeds.
Add `scripts/github-rerun` to which you can pass the URL of a run and it will try to rerun that run once a minute until it reruns.
Tried manually with
```
scripts/github-rerun https://github.com/dfinity/snsdemo/actions/runs/11514250845/job/32052488208
```
and
```
scripts/github-rerun https://github.com/dfinity/snsdemo/actions/runs/11514250846
```
not necesssary
> Script to rerun failed GitHub actions run

- frontend/src/tests/e2e/neuron-details.spec.ts
There is a duplicate replacement for neruon id in neuron-details.spec.ts which is not needed. 
This issue is created when `NNS1-3349-add-neuron-details-spec` into `NNS1-3349-add-neuron-visibility-toggle` branch, later on `NNS1-3349-add-neuron-details-spec` is updated and removed that duplicate, because these changes are introduced and deleted in `NNS1-3349-add-neuron-details-spec` branch and when we we squash merge, the main had no clue about what happened in neuron-details.spec.ts , however on `NNS1-3349-add-neuron-visibility-toggle` there was still changes.
This was a result of squash merge strategy to main, fast-forward merging strategy and not merging base branch changes into side branches before merging the side branches to main.
This leaked duplicate was first found …
> Delete duplicate replacement in neuron-details.spec.ts

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-10-23_03-07-ubuntu20.04

- frontend/src/lib/services/neurons.services.ts
https://github.com/dfinity/nns-dapp/pull/999 removed `skipCheck` from `listNeurons` and `loadNeuron`.
But it left some traces in the function type and comments.
Remove the references to the parameter that no longer exists.
Lint passes.
not necessary
> Remove skipCheck left-overs

- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
Increasing a neurons' stake is a 2 step process:
1. Transfer ICP to the neuron's account.
2. Notify the governance canister to refresh the neurons.
Because this process can be interrupted after step 1, we need to be able to finish a half completed process.
Currently the nns-dapp canister has a list of neuron accounts for each user and it watches every ICP ledger transaction to see if it is to a neuron account and then it refreshes that neuron.
We want to stop keeping this list in the nns-dapp canister and we want to stop watching every transaction.
So instead we will check from the frontend if a neuron's stake matches its account's balance and refresh if needed.
This PR just adds a service function to check if the balance matches and refresh if it doesn't.
It also uses existing …
> FOLLOW-244: Add refreshNeuronIfNeeded service

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/tests/fakes/governance-api.fake.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/lib/routes/NeuronDetail.spec.ts
Increasing a neurons' stake is a 2 step process:
1. Transfer ICP to the neuron's account.
2. Notify the governance canister to refresh the neurons.
Because this process can be interrupted after step 1, we need to be able to finish a half completed process.
Currently the nns-dapp canister has a list of neuron accounts for each user and it watches every ICP ledger transaction to see if it is to a neuron account and then it refreshes that neuron.
We want to stop keeping this list in the nns-dapp canister and we want to stop watching every transaction.
So instead we will check from the frontend if a neuron's stake matches its account's balance and refresh if needed.
In this PR we call the service added in https://github.com/dfinity/nns-dapp/pull/5696 from the `NnsNeuronDetail` component.
1. …
> FOLLOW-244: Refresh neuron from NeuronDetail page

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
After upgrading the test dependencies (https://github.com/dfinity/nns-dapp/pull/5482), the Wallet test doesn’t pass. This could be an issue specific to [the test](https://github.com/dfinity/nns-dapp/pull/5482/files#r1806490235), but using get instead of $ in areas that don’t rely on dynamic updates might be a good idea.
- Replace $ with get.
- Pass
not necessary
> Replace $ with get

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/NnsStakeNeuron.svelte
- frontend/src/lib/constants/constants.ts
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/NnsStakeNeuronModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
There was a recent change in the governance canister where new neurons are created with a dissolve delay of 7 days.
1. Add a sentence in the stake modal to inform the user that their ICP will be locked.
2. Populate the dissolve delay input field with the current dissolve delay of the neuron instead of 0.
1. Change the new neuron returned in the unit test to have a dissolve delay of 7 days.
2. Test that the input field starts out being set to 7.
3. Change the expectation of the dissolve delay increase by reducing by the initial dissolve delay.
4. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
> NNS1-3397: Initialize dissolve delay to 7 days

- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
When a neuron's account balance is out of sync with the neuron stake, we refresh the neuron in the background when the user visits the neuron detail page.
To make it clear what happened we want to show a toast to the user if the neuron was refreshed.
1. Show a toast if the neuron was refreshed in the background.
1. Unit test updated.
2. Tested manually after disabling the refresh functionality in the nns-dapp canister locally.
covered by existing entry
> FOLLOW-244: Show a toast when neuron is refreshed

- frontend/src/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.svelte
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
When setting neuron visibility of one neuron, you are offered to select other neurons you might want to change.
Currently you can deselect all neurons and click "Confirm" and it will say visibility was changed successfully.
1. Disable the Confirm button when all neurons are deselected.
1. Unit test added to test that the confirm button is disabled.
2. Unit test updated to make sure the confirm button is enabled when testing the event trigger.
3. Tested manually.
not necessary
> Disable confirm button when no neurons are selected

- frontend/src/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.svelte
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
When setting neuron visibility of one neuron, you are offered to select other neurons you might want to change.
If all neurons are selected and you deselect the "Apply to all neurons" checkbox, all neurons become unselected.
If you arrived at this modal from the details page of one specific neuron it would be useful to keep that neuron selected when unselecting all. Because the confirm button is anyway disable when none are selected and you intended to change that neuron to start with.
When deselecting all neurons, if there is a default neuron, keep the default neuron selected.
1. Refactor checkbox checking in unit test.
2. Add missing unit test for deselecting all without default neuron.
3. Add unit test for deselecting all with default neuron.
not necessary
> Keep default neuron selected on deselect-all

- scripts/nns-dapp/e2e-test-metrics-present
`sed` works slightly different on Mac than on Linux.
One difference is that it does not support the `p` command.
`scripts/nns-dapp/e2e-test-metrics-present` uses `sed` to output the metric names without comments or values.
This can actually more easily be done with `grep`.
The `-o` flag on `grep` makes it output just the matches rather than the full line.
Change `scripts/nns-dapp/e2e-test-metrics-present` to use `grep` instead of `sed` so that it works on Mac as well.
1. Tested manually on Mac.
2. CI runs on Linux and [still passes](https://github.com/dfinity/nns-dapp/actions/runs/11629035979/job/32385359427?pr=5712).
not necessary
> Make e2e-test-metrics-present work on Mac

- frontend/src/tests/lib/components/header/AccountDetails.spec.ts
The first test in `AccountDetails.spec.ts` sets a value on accounts stores and the other tests rely on this value being set.
This means that if test are run individually or in a different order, they fail.
Move the setup from the one test to `beforeEach`.
The last test was failing before when run as the `.only` test and now it passes.
not necessary
> Remove order dependence from AccountDetails.spec.ts

- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/tests/lib/api-services/governance.api-service.spec.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
This code should have been removed in https://github.com/dfinity/nns-dapp/pull/3946
Remove `stakeNeuronIcrc1` from API.
The code was unused. Tests have been removed.
not necessary
> Remove unused stakeNeuronIcrc1 code

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-10-31_03-09-ubuntu20.04

- scripts/dfx-canister-url
- scripts/nns-dapp/e2e-test-metrics-present
`dfx` 0.24.1 uses ic-http-certification instead of icx-proxy which means that metrics now need to be requested via a `.raw` URL locally just like on mainnet.
This breaks [e2e-test-metrics-present](https://github.com/dfinity/nns-dapp/blob/main/scripts/nns-dapp/e2e-test-metrics-present).
`e2e-test-metrics-present` actually already tries to use a raw URL by passing `--raw` to `dfx-canister-url` [here](https://github.com/dfinity/nns-dapp/blob/8e2701a57ed725f30e23aa5277fb179f1deacd99/scripts/nns-dapp/e2e-test-metrics-present#L21).
But `dfx-canister-url` ignore this flag on local.
Since raw URLs are now required on local, we should stop ignoring the flag.
Remove the code that sets `RAW_PART` to the empty string for the local network.
1. Manually ran `scripts/dfx-canister-url  --raw nns-dapp` to …
> Allow dfx-canister-url to make raw local URLs

- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
A test added in https://github.com/dfinity/nns-dapp/pull/5394 relies on accounts being present but is no placed inside the `describe("accounts loaded", () => {` which does the required accounts setup.
It doesn't fail because the `icrcAccountsStore` isn't properly reset between tests.
1. Reset `icrcAccountsStore` in top-level `beforeEach` in `frontend/src/tests/lib/pages/CkBTCWallet.spec.ts`.
2. Place `it('should have canister links in "more" popup'` inside `describe("accounts loaded"`.
1. The test failed after adding the `icrcAccountsStore.reset()` and passed again after moving the test inside the `describe`.
not necessary
> Reset accounts store in CkBTCWallet.spec.ts

- frontend/src/tests/routes/app/tokens/page.spec.ts
Some tests in `routes/app/tokens/page.spec.ts` depend on the `ENABLE_CKTESTBTC` feature flag being disabled.
But they do not disable the feature flag.
They only pass because other tests disable the feature flag and the `overrideFeatureFlagsStore` isn't properly reset between tests.
1. Reset `overrideFeatureFlagsStore` in `beforeEach`.
2. `overrideFeatureFlagsStore.setFlag("ENABLE_CKTESTBTC", false);` in the `beforeEach` of those `describe` blocks that were implicitly relying on this.
1. Test failed after adding the `reset` and passed again after adding the `setFlag`.
not necessary
> Reset overrideFeatureFlagsStore in routes/app/tokens/page.spec.ts

- frontend/vitest.setup.ts
Test can accidentally share state because we have a lot of global stores which keep their state between tests.
This can result in confusing and difficult to debug behavior from tests.
If we reset every store before each test we eliminate one source of dependencies of test on the order in which they are run.
1. Spy on `writable` from `"svelte/store"` by wrapping the call to `writable` in a function that records a way to reset the created store.
2. Reset each of these stores in a global `beforeEach` functions.
1. Resetting all stores caused some tests to fail. These tests have been fixed in other PRs such as https://github.com/dfinity/nns-dapp/pull/5716, https://github.com/dfinity/nns-dapp/pull/5722 and https://github.com/dfinity/nns-dapp/pull/5723.
not necessary
> Reset every store before each test

- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/tests/lib/api-services/governance.api-service.spec.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
Staking a neuron requires 2 steps: transferring the stake and claiming the neuron.
Both steps are done in the canister code in ic-js.
But it's possible that the process get interrupted in between.
In this case the nns-dapp canister finishes the process.
We want to move this fallback mechanism to the frontend.
So the frontend should be able to claim a neuron as a separate step.
The governance API already has a `claimOrRefreshNeuron` function but it requires a `neuronId` as parameter so it can really only be used for neurons that already exist.
1. Add `claimOrRefreshNeuronByMemo` which allows claiming a neuron for which we do not know the neuron ID yet.
2. Add `claimOrRefreshNeuronByMemo` to api-service as well.
2. Tested end to end in another branch.
not necessary
> FOLLOW-244: Add API to claim a neuron

- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
Staking a neuron requires 2 steps: transferring the stake and claiming the neuron.
Both steps are done in ic-js.
But it's possible that the process gets interrupted in between.
In this case the nns-dapp canister finishes the process.
We want to move this fallback mechanism to the frontend.
This PR adds a service function which can detect unclaimed neurons from transactions and known neuron accounts.
1. Add `claimNeuronsIfNeeded` function.
1. Add unit tests.
2. Tested manually end-to-end in another branch.
not yet
> FOLLOW-244: Add service to claim unclaimed neurons

- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
When the frontend sees a staking transaction without a corresponding neuron, it tries to claim the neuron in case claiming it was interrupted.
We don't need to do this more than once so we store the account identifier to at least not do it more than once per session.
1. If we find a staking transaction, add the neuron account identifier to `checkedNeuronSubaccountsStore` and if it was already there, don't try to claim the neuron.
1. Unit test added. Tested that the test fails without the new code.
not necessary
> FOLLOW-244: Do not try to claim the same neuron multiple times in a session

- scripts/deploy-devenv
- scripts/dfx-snapshot-install
- scripts/dfx-snapshot-start
- scripts/nns-dapp/release-sop
- scripts/nns-dapp/test-proposal-payload
- scripts/nns-dapp/upgrade-downgrade-test
A script runs `pgrep -l replica` to check for replica processes, but it can't receive false positives from a process called `replicatord`.
```sh
$ pgrep -l replica
781 replicatord
95113 replica
```
- The script checks for exact matches with the keyword `replica`.
I couldn't run the script that starts the snapshot without this change because it was complaining about a process (`replicatord`) matching the pattern. This change allowed me to run it without issues. I also tried to start a second snapshot, and it correctly informed me that a replica was already running.
> Enforces an exact match of replica processes

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/mocks/transaction.mock.ts
Staking a neuron requires 2 steps: transferring the stake and claiming the neuron.
Both steps are done in ic-js.
But it's possible that the process gets interrupted in between.
In this case the nns-dapp canister finishes the process.
We want to move this fallback mechanism to the frontend.
The functionality was added in previous PRs. Here was call the service function from the wallet component to make it actually functional.
1. Call `claimNeuronsIfNeeded` from `NnsWallet`.
1. Tested manually after disabling the functionality in the canister, by reloading the page as soon as the staking process is started.
2. Unit tests added for main account, subaccount and hardware wallet account.
> FOLLOW-244: Claim unclaimed neurons from the frontend

- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/periodic_tasks_runner.rs
https://github.com/dfinity/nns-dapp/pull/5706 removed the functionality to top up neurons from the nns-dapp canister.
Because `TopUpNeuron` transactions could be on the queue when the canister is upgraded, I didn't remove the `MultiPartTransactionToBeProcessed::TopUpNeuron` enum value yet.
Now that the current version on mainnet no longer adds `TopUpNeuron` to the queue, it should be safe to remove this value from the enum type.
1. Remove `TopUpNeuron` from `MultiPartTransactionToBeProcessed`.
CI passes.
not necessary
> FOLLOW-244: Remove MultiPartTransactionToBeProcessed::TopUpNeuron

- rs/backend/src/accounts_store.rs
- rs/backend/src/periodic_tasks_runner.rs
`AccountsStore.neuron_accounts` was only used to detect if a transaction is a neuron top-up transaction.
Now that the nns-dapp canister no longer does neuron refreshing for neuron top-ups, we no longer need to add new neurons to `neuron_accounts`.
This is one or multiple PRs to eventually remove the `neuron_accounts` field entirely.
Remove the code that adds new entries to `AccountsStore.neuron_accounts`.
Existing tests still pass so apparently this functionality wasn't tested.
not necessary
> FOLLOW-244: Stop inserting into AccountsStore.neuron_accounts

- frontend/src/lib/themes/mixins/_confirmation-modal.scss
All modals show text left align but no the confirmation modal. This MR fixes this.
- Confirmation modals text is now left aligned 
It can be tested [here](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/neuron/?u=qsgjb-riaaa-aaaaa-aaaga-cai&neuron=11196078873928904437).
> Aligns text to the left for confirmation modal

- frontend/src/tests/lib/services/public/sns.services.spec.ts
Some tests in `sns.services.spec.ts` subscribe to `snsAggregatorStore` and try to get/create a wrapper inside the listener function. But because the test never unsubscribe, the listeners continue being called during other tests.
If another test adds different data that the subscribing test doesn't expect, it looks like one test fails while another test is running.
Tests that subscribe to a store should also unsubscribe. But in this case, subscribing it totally unnecessary and just makes the test more complicated.
1. Rewrite the tests to not use subscribe.
1. The 2 changed tests still pass and fail if the call to `loadSnsProjects()` is removed.
2. In another branch a new test I tried to add was failing because of this, and unsubscribing fixed it.
not necessary
> Remove subscribe from sns.services.spec.ts

- .config/spellcheck.dic
- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
- rs/backend/src/canisters/governance.rs
- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/periodic_tasks_runner.rs
Staking a neuron requires 2 steps: transferring the stake and claiming the neuron.
Both steps are done in ic-js.
But it's possible that the process gets interrupted in between.
In this case the process needs to be finished later.
This is now done in the frontend so it no longer needs to be done in the backend.
1. Remove logic to detect stake neuron transaction and claim neurons from the nns-dapp canister code.
1. Unit test removed.
existing entry updated
> FOLLOW-244: Stop claiming neurons in the nns-dapp canister

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
- scripts/nns-dapp/migration-test.canister
The nns-dapp backend canister stores neuron accounts to be able to detect neuron top-up transactions.
The canister no longer does the neuron top-ups so the neuron accounts aren't used anymore.
So we can stop storing them in stable memory during upgrades.
We can't change the structure of the stable memory so now we just store an empty map in pre-upgrade, and read nothing (of type `Reserved`) in post-upgrade. This is forward and backward compatible.
I originally thought changing the encoding will require multiple steps, but this way it can be done in one step.
There will be additional PRs to remove the `neuron_accounts` field completely.
1. When encoding `AccountsStore`, write and empty `HashMap<AccountIdentifier, candid::Empty>` instead of `neuron_accounts`.
2. When decoding …
> FOLLOW-244: Stop storing neuron accounts in stable memory

- dfx.json
- frontend/src/lib/constants/environment.constants.ts
We are currently using the `app` network canister for the beta release.
We want to move the beta release to Orbit for more secure management and make the `app` canister available of ad-hoc testing again.
1. Add a `beta` network to `dfx.json` which has all the same values as `mainnet` and `app` except for the `nns-dapp` canister ID, which is the one controlled by the NNS team Orbit station.
2. Set `IS_TEST_MAINNET` to true for the `beta` network in addition to the `app` network so that we show the warning banner.
1. Manually tested that the warning banner is show when the network is set to `beta` or `app`.
2. Ran `DFX_NETWORK=beta ./config.sh` and inspected that the arguments are as described [here](https://dfinity.slack.com/archives/D04PTGSF6KX/p1730224706878919).
not necessary
> Add beta network to dfx.json

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/public/sns.services.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
We were seeing errors in NNS dapp because it tried to call `get_buyer_state` on the swap canister of an aborted swap while that canister was out of cycles. But we should not be trying to call anything on aborted swaps because we don't care about aborted swaps.
Multiple things were happening.
1. We load aggregator data into `snsAggregatorIncludingAbortedProjectsStore`, [here](https://github.com/dfinity/nns-dapp/blob/94df88c1e01a9677ccbd760f6483edde53c6c11f/frontend/src/lib/services/public/sns.services.ts#L51C5-L51C47).
From that store, we derive [snsAggregatorStore](https://github.com/dfinity/nns-dapp/blob/94df88c1e01a9677ccbd760f6483edde53c6c11f/frontend/src/lib/stores/sns-aggregator.store.ts#L34), which has aborted SNS filtered out.
2. But on the Launchpad, when we try to load the swap …
> Don't build wrappers for aborted SNSes

- dfx.json
> bot: Update snsdemo to release-2024-11-06

- scripts/nns-dapp/release
When creating the upgrade proposal for nns-dapp, `ic-admin` requires a `--arg-sha256` parameter, which is currently missing in the release script. This omission results in the following error message:
```
thread 'main' panicked at rs/registry/admin/src/main.rs:5472:28:
Must provide a sha256 checksum for the upgrade arg
```
This requirement seems to have been added in https://github.com/dfinity/ic/pull/1640
- Add missing parameter.
- Created the latest release using these changes.
Not necessary.
> Add missing arg-sha256 parameter to release

- frontend/src/lib/modals/proposals/VoteConfirmationModal.svelte
- frontend/src/lib/themes/mixins/_confirmation-modal.scss
The content of the Dialog component (ConfirmationModal) has been updated in the designs.
- Align the modal content to the left.  
-  Update the text size.  
-  Adjust the gap between the icon and title
[Design reference](https://www.figma.com/design/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?node-id=5486-51881&t=VtiplDFURAt0K5JU-4)
[Testable version](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Before:
After:
Before:
After:
**Thumbs-up/down Icons will be replaced with the new ones in a follow up PR.**
Before:
After:
Before:
After:
Not necessary.
> NNS1-3435: Applies new styles to ConfirmationModal's content

- frontend/package-lock.json
- frontend/src/lib/modals/proposals/VoteConfirmationModal.svelte
We have a new design for the `VoteConfirmationModal`.
-  Update the gix dependency to include new icons.
-  Add a wrapper around the icons in the `VoteConfirmationModal`.
[Design reference](https://www.figma.com/design/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?node-id=5486-51881&t=mmR64uy0BVpSlsyi-4)
[Testable version]()
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Not necessary.
> NNS1-3435: New icon with color hints

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/icp-ledger.services.ts
- frontend/src/tests/lib/services/icp-ledger.services.spec.ts
There was a bug when the user followed the following sequence:
* I have two HWs, A and B.
* HW A controls the neuron
* I connect HW B and try to perform something for neuron A.
* The NNS dapp tells me it is the wrong HW
* I connect HW A to fix it.
* I get this error: `Sorry, none of your principals is the controller of the neuron.`.
The reason was because the wrong identity was cached in `getLedgerIdentity`.
* Do not cache identities at all.
* Add a test scenario that checks the bug and change the test that checks that identites are cached.
> Fix caching of ledger identity

- frontend/src/lib/modals/proposals/VoteConfirmationModal.svelte
Use `&` operator for combined class selectors
- Prevent style leaking by scoping yes/no styles to icon-wrapper
Not necessary.
> NNS1-3435: use & operator for combined class selectors

- frontend/src/lib/services/public/sns.services.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
We want to create SNS wrappers based on aggregator data to avoid unnecessary calls to SNS-W and root canisters.
To do this we need to be able to wait for the `snsAggregatorStore` to be loaded if wrappers are requested before the aggregator data is loaded.
In this PR we add just a function to get the data from the `snsAggregatorStore` after it is loaded.
1. Add `getLoadedSnsAggregatorData` which waits for the `snsAggregatorStore` to have defined data and then returns that data.
2. Tested manually in another branch.
not necessary
> Add getLoadedSnsAggregatorData

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/toy_data.rs
The nns-dapp canister used to have a list of all the users' neuron accounts.
This was used to detect neuron top-up transactions as a fallback when neuron top-up failed in the frontend.
The fallback mechanism has now been moved to the frontend so we stopped populating the `neuron_accounts` field in the `AccountsStore` in the nns-dapp canister.
This PR removes the unused `neuron_accounts` field.
A future PR will remove the `neurons_created_count` field from the stats, as it will now always be 0 because the data from which it was derived is gone.
1. Remove the unused `neuron_accounts` field from `AccountsStore`.
1. Stop populating the `neuron_accounts` field in `toy_data.rs`.
not necessary
> Remove neuron_accounts field from AccountsStore

- frontend/src/tests/workflows/NnsProposalDetail.spec.ts
To be able to do this, mock behavior needs to be defined in `beforeEach` rather than the top-level scope.
This PR does that for `NnsProposalDetail.spec.ts`.
1. Mock `proposalsApi.queryProposal` in `beforeEach`.
2. Remove mocking of `markdownToHTML` as it seems to be unnecessary.
3. Add `vi.restoreAllMocks();` in `beforeEach`.
Still passes.
not necessary
> Restore all mocks in NnsProposalDetail.spec.ts

- frontend/src/tests/lib/api/agent.api.spec.ts
- frontend/src/tests/lib/api/icp-ledger.api.spec.ts
- frontend/src/tests/lib/api/nns-dapp.api.spec.ts
- frontend/src/tests/lib/api/proposals.api.spec.ts
- frontend/src/tests/lib/api/sns-governance.api.spec.ts
- frontend/src/tests/lib/api/sns-sale.api.spec.ts
- frontend/src/tests/lib/api/sns-wrapper.api.spec.ts
- frontend/src/tests/lib/api/sns.api.spec.ts
I tried running all tests with `vi.restoreAllMocks()` in `beforeEach` in `vitests.setup.ts` and found a number of tests that failed as we result.
Of the failing tests, this PR fixes the ones under `frontend/src/tests/lib/api/`.
1. Replace top-level calls to `vi.mock` that define mock behavior with `vi.spyOn` in `beforeEach`.
2. Move calls to `vi.spyOn` in `describe` scope into `beforeEach`.
3. Move calls to `mockResolvedValue` and `mockImplementation` on mocks from `describe` scope to `beforeEach`.
4. Remove `vi.clearAllMocks` as its behavior is a subset of `vi.restoreAllMocks`.
Still pass.
not necessary
> Add vi.restoreAllMocks to API tests

- frontend/src/tests/lib/pages/SnsWallet.spec.ts
The `'should have canister links in "more" popup'` test in `SnsWallet.spec.ts` relies on `icrcLedgerApi.queryIcrcBalance` being mocked. But this happens in the `beforeEach` of a `describe` block which the test is not a part of.
So the test fails when run separately with `it.only()`.
1. Put the test inside the `describe("loading accounts"` block.
The test passes when run separately with `it.only`.
not necessary
> Fix test order dependency in SnsWallet.spec.ts

- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
These tests in `ckbtc-minter.services.spec.ts` relied on `"should update balance"` to mock `minterApi.updateBalance` and failed when run individually (with `it.only`):
1. `should reload after update balance`
2. `should start and stop busy`
3. `should not start and stop busy`
1. Mock `minterApi.updateBalance` in top-level `beforeEach`.
The 3 tests now all pass when run with `it.only`.
not necessary
> Mock updateBalance in ckbtc-minter.services.spec.ts

- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
The logic for SNS reward status calculation is outdated on the front end. Although we haven’t received error reports recently, after discussing with a backend developer, it was suggested to sync the logic.
Presumably, the backend fixes led to the related code changes:
**1. SNS list_proposals reward status filtering does not exclude old SNS-1 proposals.**
There is a new field is reward_event_end_timestamp_seconds. Older proposals do not populate this field, since they predate it.
Currently, the correct way to determine whether a proposal is associated with a reward event is to look at both the new field, as well as the old one, to wit reward_event_round.
[Added here.](https://github.com/dfinity/nns-dapp/pull/5766/files#diff-bc794365fb0826c7ec5cc7d9ab15121c6bc9630e990e7bd8751b8b84273601b6R30 …
> Sync the SNS rewards status logic calculation with the backend

- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
`icrc-accounts.services.spec.ts` has multiple tests that require `console.error` to be mocked.
So of these tests do not mock `console.error` and so they depend on another test doing it before them and can't be run individually.
1. Mock `console.error` in 2 tests that depend on it but didn't mock it before.
1. These tests can now be run individually while before they would fail when run individually.
not necessary
> Mock console.error in icrc-accounts.services.spec.ts

- frontend/src/tests/lib/services/neurons.services.spec.ts
The following tests fail when `describe("list neurons"` is skipped:
```
FAIL  src/tests/lib/services/neurons.services.spec.ts > neurons-services > disburse > should disburse neuron
FAIL  src/tests/lib/services/neurons.services.spec.ts > neurons-services > disburse > should sync account balance
FAIL  src/tests/lib/services/neurons.services.spec.ts > neurons-services > spawnNeuron > should spawn a neuron from maturity
FAIL  src/tests/lib/services/neurons.services.spec.ts > neurons-services > mergeNeurons > should merge neurons
FAIL  src/tests/lib/services/neurons.services.spec.ts > neurons-services > splitNeuron > should update neuron
FAIL  src/tests/lib/services/neurons.services.spec.ts > neurons-services > splitNeuron > should add transaction fee to the amount
```
They fail with this …
> Mock queryNeurons in neurons.services.spec.ts

- frontend/src/tests/lib/services/sns-finalization.services.spec.ts
The tests in `sns-finalization.services.spec.ts` that do not expect calls to `queryFinalizationStatus` still need `queryFinalizationStatus` to be spied on. Currently they rely on other tests to set up the spy, which means these tests fail when run individually.
1. Spy on `queryFinalizationStatus` in 2 tests that require it but didn't do so.
The tests failed before when run individually and now pass.
not necessary
> Fix test order dependency in sns-finalization.services.spec.ts

- frontend/src/tests/lib/services/wallet-uncertified-accounts.services.spec.ts
Test `"should toast error"` fails when run individually because it relies on other tests mocking `queryIcrcToken`.
Mock `queryIcrcToken` in  `"should toast error"`.
The test now passes when run individually.
not necessary
> Mock queryIcrcToken in wallet-uncertified-accounts test

- frontend/package-lock.json
- frontend/src/tests/mocks/neurons.mock.ts
Upgrade to the next version of ic-js to get the `votingPowerRefreshedTimestampSeconds` field of the neuron.
- npm run upgrade:next;
- Add a new field to the mocked neuron.
- Pass.
Not necessary.
> Upgrade ic js

- frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
- frontend/src/tests/lib/components/canister-detail/RemoveCanisterControllerButton.spec.ts
- frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronHotkeysCard.spec.ts
- frontend/src/tests/lib/components/neuron-detail/actions/NnsAutoStakeMaturity.spec.ts
- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronHotkeysCard.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsAutoStakeMaturity.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseDropdown.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseList.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseNavList.spec.ts
- frontend/src/tests/lib/components/universe/UniverseAccountsBalance.spec.ts
I tried running all tests with `vi.restoreAllMocks()` in `beforeEach` in `vitests.setup.ts` and found a number of tests that failed as a result.
Of the failing tests, this PR fixes the ones under `frontend/src/tests/lib/components/`.
1. Replace top-level calls to `vi.mock` that define mock behavior with `vi.spyOn` in `beforeEach`.
2. Move calls to `vi.spyOn` in `describe` scope into `beforeEach`.
3. Move calls to `mockResolvedValue` and `mockImplementation` on mocks from `describe` scope to `beforeEach`.
4. Call `vi.restoreAllMocks()` in top-level `beforeEach`.
5. Remove `vi.clearAllMocks` as its behavior is a subset of `vi.restoreAllMocks`.
Still …
> Add vi.restoreAllMocks to components tests

- frontend/src/tests/lib/derived/universes-accounts-balance.derived.spec.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/utils/auth.utils.spec.ts
- frontend/src/tests/lib/utils/utils.spec.ts
- frontend/src/tests/lib/worker-utils/timer.worker-utils.spec.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
I tried running all tests with `vi.restoreAllMocks()` in `beforeEach` in `vitests.setup.ts` and found a number of tests that failed as a result.
Several PRs have been merged to fix such failing test. This PR fixes the remaining ones.
A follow-up PR will enforce `vi.restoreAllMocks()` in `vitest.setup.ts` and after that all other calls to `vi.restoreAllMocks()` can be removed again.
1. Replace top-level calls to `vi.mock` that define mock behavior with `vi.spyOn` in `beforeEach`.
2. Move calls to `vi.spyOn` in `describe` scope into `beforeEach`.
3. Move calls to `mockResolvedValue` and `mockImplementation` on mocks from `describe` scope to `beforeEach`. …
> Make remaining tests work with vi.restoreAllMock()

- frontend/src/tests/lib/components/canister-detail/UnlinkctionButton.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/FollowSnsTopicSection.spec.ts
- frontend/src/tests/lib/modals/accounts/IcpTransactionModal.spec.ts
- frontend/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsStakeMaturityModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsStakeNeuronModal.spec.ts
- frontend/vitest.setup.ts
This PR makes sure all mocks are restored before each test.
I thought all tests were already prepared in earlier PRs but some were apparently missed on my first pass.
This PR fixes all the remaining tests as well.
A follow-up PR will remove now unnecessary calls to `vi.restroreAllMock()` from individual tests.
1. Call `vi.restoreAllMocks()` in `beforeEach` in `vitest.setup.ts`.
2. Fix all remaining tests that were missed before.
All tests pass.
not necessary
> Always vi.restoreAllMocks() before each test

- Cargo.lock
- Cargo.toml
> bot: Update IC Cargo Dependencies to release-2024-11-14_03-07-base

- scripts/ic-admin-propose
- scripts/propose-install-canister
Creating a proposal via `ic-admin` is always tedious because you need to construct arguments for `--nns-url`, `--secret-key-pem` and `--proposal`.
For the sake of upgrading a canister, `scripts/propose-install-canister` does this for you, but for other types of proposals it's still a hassle.
1. Extract `scripts/ic-admin-propose` from `scripts/propose-install-canister` to create the necessary arguments for arbitrary proposals.
2. Use `scripts/ic-admin-propose` in `scripts/propose-install-canister`.
3. Use `webserver-port` instead of `replica-port`. It does not seem to make a difference but when switching to PocketIC, `webserver-port` gives the correct port to use and `replica-port` no longer works.
1. Used `scripts/propose-install-canister` to upgrade nns-dapp locally with
``` …
```
> Add scripts/ic-admin-propose

- frontend/src/tests/lib/components/neuron-detail/NeuronNavigation.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeader.spec.ts
- frontend/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/src/tests/lib/components/neurons/MakeNeuronsPublicBanner.spec.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
- frontend/src/tests/lib/modals/neurons/ChangeNeuronVisibilityModal.spec.ts
- frontend/src/tests/lib/modals/neurons/FollowNeuronsModal.spec.ts
- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/lib/services/actionable-proposals.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/stores/neurons-table-order-sorted-neuron-ids-store.spec.ts
- frontend/src/tests/lib/stores/neurons.store.spec.ts
- frontend/src/tests/workflows/NnsProposalDetail.spec.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
This PR does so for `neuronsStore`.
1. Remove resetting of `neuronsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop calling neuronsStore.reset() in beforeEach

- scripts/dfx-server-origin
- scripts/ic-admin-propose
Some scripts require a URL to the replica that depends on the dfx network being used.
It's useful to have this in a separate script to be able to reuse it.
I want to use this later to make `scripts/sns/aggregator/get-sns` support networks other than mainnet.
1. Extract the code to get the server URL from `scripts/ic-admin-propose` and create a new script `scripts/dfx-server-origin` with it.
Manually tried using `propose-install-canister` (which uses `scripts/ic-admin-propose`) to install nns-dapp on `local` and on `devenv_dskloet`.
not necessary
> Add scripts/dfx-server-origin

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
The latest nns-dapp upgrade failed because the stable memory couldn't be decoded.
```
Decoding stable memory failed. Error: "Fail to decode argument 4 from table14 to reserved"
```
In my understanding, anything should be able to be decoded to type `candid::Reserved` and with local testing this is the case but apparently there are edge cases where this is not true.
It's still not clear to me why it failed but I was able to reproduce the failure against golden test data and the changes in this PR fixed it.
I'll try to continue to look into this more to understand what really happened but meanwhile it's good to have a releasable repo again.
Decode unused `neuron_accounts` as its original type `HashMap<AccountIdentifier, NeuronDetails>` instead of `candid::Reserve`.
1. I tried upgrading …
> Decode neuron_accounts into original type instead of Reserved

- .github/workflows/checks.yml
- scripts/dfx-server-origin
- scripts/sns/aggregator/get-sns
`scripts/sns/aggregator/get-sns` is a script to conveniently get some information about any SNS based on the name or any of its canister IDs.
Currently it only works with mainnet SNSes but while trying to reproduce out-of-cycles SNSes locally, I found it useful to be able to use this locally.
1. Add `--canister` flag to `scripts/dfx-server-origin` to support adding a canister as the subdomain in the origin. This is useful to create an SNS aggregator URL.
2. Add `--network` flag to `scripts/sns/aggregator/get-sns`.
3. Download aggregator pages if the network is not `mainnet` (if it is `mainnet`, then we use the pages present in the repo).
4. Connect to the aggregator based on the `--network` flag to get the current data.
1. I used the script manually to get data from `mainnet`, `local` and …
> Support other networks for get-sns script

- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
For the periodic following confirmation feature, some UI elements will rely on a neuron’s inactivity state. In this PR, a new utility function to calculate these states is introduced.
Inactivity states:
- Losing rewards.
- And an extra state when to notify user that the neuron will lose rewards soon.
- New constants related to the activity state (from ic / VotingPowerEconomics).
- New util functions.
- Added.
Not necessary.
> Neuron action state utils

- frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts
- frontend/src/tests/lib/components/proposals/NnsProposalsFilters.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/derived/icp-accounts.derived.spec.ts
- frontend/src/tests/lib/derived/paths.derived.spec.ts
- frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/routes/Neurons.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/stores/feature-flags.store.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
This PR does so for `overrideFeatureFlagsStore`.
1. Remove resetting of `overrideFeatureFlagsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop calling overrideFeatureFlagsStore.reset() in beforeEach

- frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
- frontend/src/tests/lib/components/accounts/SelectDestinationAddress.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseDropdown.spec.ts
- frontend/src/tests/lib/components/universe/UniverseAccountsBalance.spec.ts
- frontend/src/tests/lib/derived/sns/sns-accounts.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/universes-accounts.derived.spec.ts
- frontend/src/tests/lib/modals/accounts/IcrcTokenTransactionModal.spec.ts
- frontend/src/tests/lib/modals/neurons/DisburseSnsNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsDisburseMaturityModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/transaction/TransactionModal.spec.ts
- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/sns-accounts.services.spec.ts
- frontend/src/tests/lib/services/wallet-uncertified-accounts.services.spec.ts
- frontend/src/tests/lib/stores/icrc-accounts.store.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
This PR does so for `icrcAccountsStore`.
1. Remove resetting of `icrcAccountsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop calling icrcAccountsStore.reset() in beforeEach

- frontend/src/lib/utils/utils.ts
- frontend/src/tests/lib/utils/utils.spec.ts
Removes an unused utility function that was introduced in #610 and last used in #999. The function hasn't been used in two years, so it is safe to delete.
- Removes createChunks utility function
- Removed tests
Not necessary
> housekeeping: removes createChunks utility

- frontend/src/lib/utils/utils.ts
Removes an unused utility function that was introduced in #594 and later removed in #5446. The markdown component has been moved to GIX, making this function unnecessary.
- Removes targetBlankLinkRenderer utility function
Not necessary
> housekeeping: removes targetBlankLinkRenderer utility

- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/types/responsive-table.ts
- frontend/src/lib/utils/neurons-table-order-sorted-neuron-ids-store.utils.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/lib/utils/responsive-table.utils.ts
- frontend/src/lib/utils/sort.utils.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/lib/utils/tokens-table.utils.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/lib/modals/common/ResponsiveTableSortModal.spec.ts
- frontend/src/tests/lib/utils/responsive-table.utils.spec.ts
- frontend/src/tests/lib/utils/sort.utils.spec.ts
Move sorting utility functions from `responsive-table.utils` to `sort.utils` to reuse them outside of the tables.
Note: the changes should be easy to review by commit.
1. Moved `type Comparator`, `createAscendingComparator`, `createDescendingComparator`, `mergeComparators` and `negate` into sort.utils.ts.
2. Renamed generic type `RowDataType` to `DataType`.
3. Updated imports.
- Related tests moved to `sort.utils.spec`.
Not necessary.
> Sort utils

- frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
Some code that mocks `createAgent` was added in https://github.com/dfinity/nns-dapp/pull/5785 but was not meant to be merged.
Remove the unintended code.
Still passes
not necessary
> Remove debugging code

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/stores/sns-aggregator.store.ts
- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
When an SNS swap canister runs out of cycles, the next time the SNS aggregator tries to fetch the data for this SNS, it will overwrite its existing data (at least the data that comes from the swap canister) with empty default data.
This means it will no longer have a value for the `lifecycle` field and this breaks the code that tries to filter out SNSes which are aborted.
We should probably fix the aggregator to not drop information when the canister runs out of cycles but this will take longer.
In the meantime it's better to hide one SNS than for the entire NNS dapp to break.
1. Filter out SNSes without `lifecycle` in addition to SNSes with `lifecycle === SnsSwapLifecycle.Aborted` in the aggregator store.
2. Filter out SNSes without `lifecycle` when creating SNS summaries.
1. Unit tests …
> Filter out SNSes without lifecycle

- frontend/src/lib/utils/utils.ts
Removes an unused utility function that was introduced in #882 and later removed in #5636. 
- Removes `mapPromises` utility function
Not necessary
> housekeeping: removes mapPromises utility

- frontend/src/lib/canisters/nns-dapp/nns-dapp.certified.idl.js
- frontend/src/lib/canisters/nns-dapp/nns-dapp.did
- frontend/src/lib/canisters/nns-dapp/nns-dapp.idl.js
- frontend/src/lib/canisters/nns-dapp/nns-dapp.types.ts
- rs/backend/nns-dapp.did
- rs/backend/src/stats.rs
- scripts/nns-dapp/e2e-test-metrics-present.keys
- scripts/nns-dapp/estimate-upgrade-cycles
The `neurons_created_count` metric was derived from the `neuron_accounts` field that was removed in https://github.com/dfinity/nns-dapp/pull/5767 so it will now always be zero.
So we should just remove it.
Remove `neurons_created_count` from the exported metrics.
Not tested. Relying on CI.
not necessary
> FOLLOW-244: Remove neurons_created_count from metrics

- frontend/src/lib/utils/date.utils.ts
- frontend/src/tests/lib/utils/date.utils.spec.ts
NNS1-3450 will download a csv where show the users the date at which their neuron will dissolve. Eg:
| Neuron Id  |  Dissolve Delay | Dissolve Date |
| ------------- | ------------- |-------------|
| 12345  | 1day, 1hours  | Nov 22, 2024 |
- Adds new date utility function `getFutureDateFromDelayInSeconds`
- Unit tests
Not necessary
Prev PR: #5812 | Next PR: #5836
> NNS1-3450: New utility function to generate a user-friendly date string after a delay.

- frontend/src/tests/lib/components/header/LinkToCanisters.spec.ts
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
- frontend/src/tests/lib/modals/neurons/NeuronVisibilityRow.spec.ts
Importing `vi` is no longer required as it is global.
- Removes the `vi` import
Not necessary
> housekeeping: removes unnecessary `vi` imports

- frontend/src/lib/utils/env.utils.ts
- frontend/src/tests/lib/utils/env.utils.spec.ts
Removes an unused utility function that was introduced in #2377 and later removed in #5668. It doesn't contain any business logic.
- Removes `isLocalhost` utility function
Not necessary
> housekeeping: removes isLocalhost utility

- frontend/src/lib/utils/date.utils.ts
- frontend/src/tests/lib/utils/date.utils.spec.ts
Downloaded files should include a timestamp in their name indicating the day the file was generated. For example:
- `neurons_20241112.csv`
- `neurons_<accountId>_20241112.pdf`
- Adds a new utility function to generate a timestamp from a provided date with the format `YYYYMMDD`
- Unit tests
Not necessary
> NNS1-3450: New utility date to generate a compact timestamp

- frontend/src/lib/utils/export-to-csv.utils.ts
- frontend/src/tests/lib/utils/export-to-csv.utils.spec.ts
CSV files can include metadata that appears before the table. For example:
- Adds a new parameter `metadata` that if present is render before the table. When present it shifts the table two columns to the right.
- Unit test
- Manually tested in #5813
Not necessary
Prev PR: #5812 | Next PR: #5813
> NNS1-3450: Adds a metadata field to generate Csv

- frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeader.spec.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/derived/sns/sns-sorted-neurons.derived.spec.ts
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/stores/sns-neurons-table-order-sorted-neuron-ids-store.spec.ts
- frontend/src/tests/lib/stores/sns-neurons.store.spec.ts
This PR does so for `snsNeuronsStore`.
1. Remove resetting of `snsNeuronsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop calling snsNeuronsStore.reset() in beforeEach

- frontend/src/lib/stores/neurons.store.ts
- frontend/src/tests/lib/stores/neurons.store.spec.ts
After periodic confirmation is activated, we need to notify users about their neurons that could soon lose rewards, so they can take action to avoid it. To simplify this, it’s better to have a derived store containing all the affected neurons, sorted by the time they start losing rewards.
- New `soonLosingRewardNeuronsStore` store.
- Added.
Not necessary.
> Soon losing rewards store

- frontend/src/tests/lib/derived/icrc-canisters.derived.spec.ts
- frontend/src/tests/lib/derived/icrc-universes.derived.spec.ts
- frontend/src/tests/lib/derived/selected-universe.derived.spec.ts
- frontend/src/tests/lib/derived/sns/sns-selected-project.derived.spec.ts
- frontend/src/tests/lib/derived/universes.derived.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/services/icrc-canisters.services.spec.ts
- frontend/src/tests/lib/services/icrc-tokens.services.spec.ts
- frontend/src/tests/lib/services/public/app.services.spec.ts
- frontend/src/tests/lib/stores/icrc-canisters.store.spec.ts
- frontend/src/tests/lib/utils/universes.utils.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
This PR does so for `defaultIcrcCanistersStore`.
1. Remove resetting of `defaultIcrcCanistersStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop calling defaultIcrcCanistersStore.reset() in beforeEach

- frontend/src/lib/api/canisters.api.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
Topping up a canister is a 2-step process:
1. Transfer ICP to a subaccount of the CMC
2. Notify the CMC of the transfer
Because the process might be interrupted between the 2 steps, the nns-dapp canister listens for all transactions to see if any might be a canister top-up transaction by an NNS dapp user.
We want the NNS dapp to stop listening for all transactions so we want to move this fallback mechanism to the frontend.
In this PR we add just an API function that will be needed to notify the CMC from the frontend.
1. Add `notifyTopUpCanister` to CMC API.
2. Tested manually in another branch with more changes.
not yet
> FOLLOW-244: Add notifyTopUpCanister to CMC API

- frontend/src/lib/services/canisters.services.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
Topping up a canister is a 2-step process:
1. Transfer ICP to a subaccount of the CMC
2. Notify the CMC of the transfer
Because the process might be interrupted between the 2 steps, the nns-dapp canister listens for all transactions to see if any might be a canister top-up transaction by an NNS dapp user.
We want the NNS dapp to stop listening for all transactions so we want to move this fallback mechanism to the frontend.
In this PR we add a service function that will be used to check if the CMC needs to be notified and to do so if needed.
It only checks the most recent transaction to see if it is a funding transaction. It's theoretically possible to have a funding transaction that is followed by another transaction that's not the corresponding burn transaction. This was discussed with …
> FOLLOW-244: Add notifyTopUpIfNeeded to canisters service

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/CanisterDetail.svelte
- frontend/src/tests/lib/pages/CanisterDetail.spec.ts
Topping up a canister is a 2-step process:
1. Transfer ICP to a subaccount of the CMC
2. Notify the CMC of the transfer
Because the process might be interrupted between the 2 steps, the nns-dapp canister listens for all transactions to see if any might be a canister top-up transaction by an NNS dapp user.
We want the NNS dapp to stop listening for all transactions so we want to move this fallback mechanism to the frontend.
1. Call the service function that was added in https://github.com/dfinity/nns-dapp/pull/5857 from `CanisterDetails` to actually do the notifying if needed.
2. Tested manually by removing the top-up functionality from the backend canister and reloading the page in the middle of the top-up process.
> FOLLOW-244: Notify for unfinished canister top-ups from the frontend

- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
- frontend/src/tests/page-objects/AccountMenu.page-object.ts
We want to be consistent in how we test components using page objects.
- Migrate `AccountMenu` tests to only use PageObjects
- They work as before
Not necessary
> housekeeping: Migrate AccountMenu tests to utilize a page object

- frontend/src/tests/page-objects/jest.page-object.ts
This function was added in #2817 but never used.
- Removes `isInputElement` function
Not necessary
> housekeeping: Removes unused function isInputElement 

- scripts/vote
I was trying to use `scripts/vote` to vote on a proposal on my DevEnv but it didn't do anything because I was using the wrong identity which didn't have any neurons.
This was confusing because the script didn't output anything and didn't give any error.
Provide some useful output about the neurons and number of proposals.
Tested manually by specifying a wrong identity and a correct identity.
not necessary
> Give useful output in scripts/vote

- frontend/src/lib/components/ui/Banner.svelte
- frontend/src/lib/components/ui/BannerIcon.svelte
- frontend/src/tests/lib/components/ui/Banner.spec.ts
- frontend/src/tests/lib/components/ui/BannerIcon.spec.ts
- frontend/src/tests/lib/components/ui/BannerIconTest.svelte
- frontend/src/tests/lib/components/ui/BannerTest.svelte
- frontend/src/tests/page-objects/Banner.page-object.ts
- frontend/src/tests/page-objects/BannerIcon.page-object.ts
Currently, there are already a couple of custom banner implementations done in the nns-dapp. All of them look almost the same. Since several banners are planned for the upcoming periodic confirmation feature, it’s a good opportunity to introduce a banner as a component ([here](https://www.figma.com/design/x8dk5axQUf8Bi43uUsqCHc/NNS-Production-%26-Hand-over?node-id=4127-45761) is the design for it). For the first iteration, it is planned to include it in the nns-dapp codebase to test whether it meets all the needs for periodic confirmation and to replace the currently presented banners. Afterward, it can be moved to the gix-components.
- New components: Banner and BannerIcon. Since they need to be used together, both are included in the same PR.
- POs and unit tests added.
Not necessary
> Generic banner component

- frontend/src/lib/services/icp-transactions.services.ts
- frontend/src/lib/services/sns-sale.services.ts
`getCurrentIdentity` doesn't return a promise; thus, it is not necessary to `await` it.
- Remove `await` from some calls to `getCurrentIdentity`
- Tests work as before
Not necessary
> housekeeping: Removes the need to wait for getCurrentIdentity

- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
For the periodic confirmation feature, the time until the neuron starts losing rewards should be displayed. A function to retrieve this value in seconds has been added here.
- New util `secondsUntilLosingReward`.
- Refactor relater utils to use it.
- Added.
not necessary
> secondsUntilLosingReward util

- frontend/src/lib/services/icp-transactions.services.ts
- frontend/src/tests/lib/services/icp-transactions.services.spec.ts
The `.some` function returns `false` when the transactions array is empty because it cannot find `null` (`oldestTxId`). This is an error, as it should handle this case.
You can reproduce the issue by following these steps:
-  Navigate to the transactions page of a SubAccount with no transactions.
-  The `InfiniteScroll` will never be disabled as expected [here](https://github.com/dfinity/nns-dapp/blob/74767085476d849d58943233ea36da723aedf96a/frontend/src/lib/components/accounts/UiTransactionsList.svelte#L22).
-  However, since we check the size of transactions [here](https://github.com/dfinity/nns-dapp/blob/74767085476d849d58943233ea36da723aedf96a/frontend/src/lib/components/accounts/UiTransactionsList.svelte#L16), the bug does not have an impact.
- Added a check to `oldestTxId` to …
> fix: Checks for empty transactions to define getTransactions as completed

- frontend/src/lib/components/header/ExportNeuronsButton.svelte
- frontend/src/lib/utils/export-to-csv.utils.ts
- frontend/src/tests/lib/components/header/ExportNeuronsButton.spec.ts
- frontend/src/tests/lib/utils/export-to-csv.utils.spec.ts
The report functionality for transactions requires more complex `.csv` structures, as shown in the screenshot. To achieve this, we need to introduce the concept of datasets, which are small tables within the file. All datasets will share the same headers.
- Refactors `generateCsvFileToSave` to handle datasets across multiple levels.  
- Introduces a new function, `combineDatasetsToCsv`, to merge multiple datasets into one.  
- Updates `ExportNeuronsButton`, the existing consumer of `generateCsvFileToSave`, to supply a dataset.  
- Added new tests for the updated API.  
-  Refactored existing tests for the new API.
Not necessary
> NNS1-3480: Refactors generateCsvFileToSave to manage datasets for more complex CSV files

- frontend/src/lib/components/ui/Banner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/types/i18n.d.ts
We want all our content to be defined in our `en.json` file. This includes content tags related to assistive technology, such as `aria-label`.
- Replaces the existing hardcoded `aria-label` values with their translations
Not necessary
> housekeeping: Refactors hardcoded aria-label values to use translations

- frontend/src/lib/components/header/AccountMenu.svelte
- frontend/src/lib/components/header/LinkToSettings.svelte
- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
- frontend/src/tests/page-objects/AccountMenu.page-object.ts
`SettingsButton` is a button that triggers a page redirect. An anchor is a more semantically correct HTML element for such a component.
It can be checked [here](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
- Refactors `SettingsButton` into `LinkToSettings`
- Updates impacted tests
- Manually tested
Not necessary
> housekeeping: Refactors SettingsButton into a link

- frontend/src/lib/api/governance.api.ts
- frontend/src/lib/identities/ledger.identity.ts
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
- frontend/src/tests/lib/modals/neurons/NeuronVisibilityRow.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
In the scope of [NNS1-3269](https://dfinity.atlassian.net/browse/NNS1-3269), we want to replace the term "hardware wallet" with "ledger device" for greater accuracy.
#5860 addressed this change for user-facing content and their tests. This and subsequent PRs will implement the change in the codebase. We will split it into multiple PRs to facilitate easier review.
- Changes `Hardware Wallet` to `Ledger Device`.
- Changes `Hardware wallet` to `Ledger device`.
Not necessary
Prev. PR: #5860
[NNS1-3269]: https://dfinity.atlassian.net/browse/NNS1-3269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NNS1-3269: Renames Hardware Wallet to Ledger Device

- frontend/src/lib/api/icrc-ledger.api.ts
- frontend/src/lib/api/sns.api.ts
- frontend/src/lib/components/accounts/HardwareWalletListNeuronsButton.svelte
- frontend/src/lib/components/neurons/AddUserToHotkeys.svelte
- frontend/src/lib/constants/ledger.constants.ts
- frontend/src/lib/modals/accounts/AddAccountModal.svelte
- frontend/src/lib/modals/accounts/IcpTransactionModal.svelte
- frontend/src/lib/modals/neurons/IncreaseNeuronStakeModal.svelte
- frontend/src/lib/modals/neurons/NnsStakeNeuronModal.svelte
- frontend/src/lib/services/icp-ledger.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/seed-neurons.services.ts
- frontend/src/lib/types/wallet.context.ts
- frontend/src/lib/utils/neuron.utils.ts
In the scope of [NNS1-3269](https://dfinity.atlassian.net/browse/NNS1-3269), we want to replace the term "hardware wallet" with "ledger device" for greater accuracy.
It continues the work started in #5860 and #5882
- Changes `hardware wallet` to `Ledger device` in `src/lib/**`.
Not necesary
Prev. PRs: #5860 #5882
[NNS1-3269]: https://dfinity.atlassian.net/browse/NNS1-3269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NNS1-3269: Renames hardware wallet to Ledger device in src/lib

- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/types/transaction.ts
- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/lib/utils/icrc-transactions.utils.ts
- frontend/src/lib/utils/transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
- frontend/src/tests/lib/utils/transactions.utils.spec.ts
Transactions need to be adapted to a user-friendly format. We already have a function called `mapIcpTransaction` that assists with this, but it is too specific to its current use case.
We can split it into two functions: a generic one that resolves transaction information and a specific one for the transactions table.
This first PR introduces changes that will allow for the implementation of a more generic function in a second PR, which will be reused in a third PR.
- Renames `mapIcpTransaction` to `mapIcpTransactionToUi`.  
-  Moves the logic for differentiating between transaction types `Send` and `Receive` from `transactionName` to `getTransactionType` in both `icp-transactions` and `icrc-transactions`.  
-  Introduces a new type for `Receive` in `AccountTransactionType`.
- Removes the …
> NNS1-3480: Refactors mapIcpTransaction to allow for the introduction of a more generic function

- frontend/src/lib/stores/icp-swap.store.ts
- frontend/src/tests/lib/stores/icp-swap.store.spec.ts
- frontend/src/tests/mocks/icp-swap.mock.ts
We want to show USD values of assets. For this we want to use data from ICP Swap.
In this PR we add a Svelte store to keep this data in.
1. Add `icpSwapTickersStore`.
2. Added mock data for unit tests.
not yet
> Add icpSwapTickersStore

- frontend/src/lib/components/neurons/MakeNeuronsPublicBanner.svelte
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/routes/Staking.svelte
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
- frontend/src/tests/page-objects/Staking.page-object.ts
As part of the periodic confirmation feature, a banner should be displayed on the Staking and ICP Neurons pages whenever a neuron is losing or about to lose rewards. This implementation ensures the banner is displayed on the specified pages.
- [Display LosingRewardsBanner on staking page](https://github.com/dfinity/nns-dapp/commit/8a40a32d21d37e6340f8487119b592533894799d). 
- [Display LosingRewardsBanner on neurons page](https://github.com/dfinity/nns-dapp/commit/9975b6b9c3d9f84a427fdc6a6f8a06b2a6d8db18).
- Replaced the bottom margin of `MakeNeuronsPublicBanner` with a gap on `NnsNeurons`.
- Added.
Not necessary.
> Display confirm following banner

- frontend/src/lib/api/icp-swap.api.ts
- frontend/src/lib/stores/icp-swap.store.ts
- frontend/src/lib/types/icp-swap.ts
- frontend/src/tests/lib/api/icp-swap.api.spec.ts
- frontend/src/tests/mocks/icp-swap.mock.ts
- frontend/vitest.setup.ts
We want to show USD values of assets. For this we want to use data from ICP Swap.
In this PR we add an API function to load ticker data from the ICP Swap API.
1. Move `IcpSwapTicker` type from the store to a type module so it can be resused in the API layer.
2. Add `queryIcpSwapTickers` which fetchers tickers from the ICP Swap API.
1. Add missing ICP Swap URL to unit test environment.
2. Add unit tests for successful and failing request.
not yet
> Add queryIcpSwapTickers API

- frontend/src/lib/services/icp-swap.services.ts
- frontend/src/tests/lib/services/icp-swap.services.spec.ts
We want to show USD values of assets. For this we want to use data from ICP Swap.
This PR adds a function to load ticker data and put it into the store.
1. Add `loadIcpSwapTickers`. We don't have product requirements yet so for now we don't do anything with an error except logging it on the console.
not yet
> Add service to load ICP Swap tickers

- frontend/src/lib/derived/icp-swap.derived.ts
- frontend/src/tests/lib/derived/icp-swap.derived.spec.ts
We want to show USD values of assets. For this we want to use data from ICP Swap.
This PR creates a stored derived from the tickers store, which holds ckUSDC prices of all available tokens based on their ledger canister ID. This depends on the `ckUSDC_ICP` ticker being available and `XYZ_ICP` tickers being available for the relevant tokens.
1. Add `icpSwapUsdPricesStore`.
1. Add unit tests.
not yet
> Add derived store with token prices in ckUSDC

- frontend/src/lib/derived/icp-swap.derived.ts
- frontend/src/lib/services/icp-swap.services.ts
- frontend/src/lib/stores/icp-swap.store.ts
- frontend/src/tests/lib/derived/icp-swap.derived.spec.ts
- frontend/src/tests/lib/services/icp-swap.services.spec.ts
- frontend/src/tests/lib/stores/icp-swap.store.spec.ts
I thought there was a requirement for the ICP Swap exchange rates to be updated every 10 minutes.
So I added a timestamp in the store to see when they were last updated.
But this turned out to be a misunderstanding and we want the exchanges rates to remain fixed until the session ends (within 30 minutes).
So there is no need to have a timestamp in the store.
Remove `lastUpdateTimestampSeconds` from `icpSwapTickersStore` and make the array of tickers the stored data.
Updated
not necessary
> Remove timestamp from icpSwapTickersStore

- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
This is a follow-up to #5891. It introduces a new function, `mapIcpTransactionToReport`, which provides information for the report.
A third PR will follow to extract smaller functions from `mapIcpTransactionToReport` and `mapIcpTransactionToUI` for reuse between both.
- New `mapIcpTransactionToReport` function
- Unit tests for the function
Not necessary
Prev. PR: #5891
> NNS1-3480: New util function mapIcpTransactionToReport 

- frontend/src/lib/services/icp-swap.services.ts
- frontend/src/tests/lib/services/icp-swap.services.spec.ts
We agree with PM to load exchange rates only once per session.
1. In `loadIcpSwapTickers` if the store is already loaded, do nothing.
not yet
> Load ICP Swap tickers once per session

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/derived/icp-tokens-list-visitors.derived.ts
- frontend/src/lib/derived/tokens-list-base.derived.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/lib/utils/user-token.utils.ts
- frontend/src/tests/lib/derived/tokens-list-base.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-visitors.derived.spec.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
- frontend/src/tests/mocks/tokens-page.mock.ts
ICP Swap provides exchange rates per token based on ledger canister ID.
So in the tokens table, to get the exchange rate of a token, we need to know its ledger canister ID.
`UserTokenBase` is the base type of row data used in the tokens table.
In this PR we just make sure that the ledger canister ID is available for each token in the table.
This can then be used in later PRs to get the exchange rate.
1. Add `ledgerCanisterId` field to `UserTokenBase`.
2. When constructing instances of `UserTokenBase`, add `ledgerCanisterId`.
1. Unit tests have been updated.
2. Tested manually in another branch that we can display dollar values in the tokens table.
not yet
> Add ledgerCanisterId to UserTokenBase

- rs/backend/src/accounts_store.rs
- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/periodic_tasks_runner.rs
[get_transaction_type](https://github.com/dfinity/nns-dapp/blob/b1bc79f602907794dac188d7a2000fb654e0fe90/rs/backend/src/accounts_store.rs#L888) never returns `ParticipateSwap`. And as far as I can tell, it never did.
So there is no point in checking if `transaction_type` matches `ParticipateSwap`.
Also, if it would match `ParticipateSwap`, we wouldn't do anything once the `MultiPartTransactionToBeProcessed` comes out of the queue.
1. Remove `TransactionType::ParticipateSwap`.
2. Stop matching against `TransactionType::ParticipateSwap`.
3. Turn the `match` into a simple `if` since we now only match against a single remaining type.
4. Stop passing now unused parameters to `process_transaction_type`.
5. Remove `MultiPartTransactionToBeProcessed::ParticipateSwap`.
6. Stop matching against …
> Remove ParticipateSwap transaction type from backend

- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/NeuronFollowingCard.svelte
- frontend/src/tests/lib/components/neuron-detail/NeuronFollowingCard/Followee.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NeuronFollowingCard/FolloweeTest.svelte
- frontend/src/tests/page-objects/Followee.page-object.ts
For the periodic confirmation modal, we need to display the neuron followings. We already have a component for this—Followee.svelte. However, the current `Followee` component is hard to reuse because:
1. It relies on the context store.
2. It provides functionality specific to the neuron details page (e.g., opening voting history).
In this PR, we make the component more reusable by introducing a `neuron` prop to pass the neuron directly and an `isInteractive` prop for rendering a text-only version.
- Added a neuron prop (replacing the usage on the NeuronInfo from the context store).
- Unit tests have been updated and extended to test the isInteractive.
Not necessary.
> Refactor Followee Component

- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/periodic_tasks_runner.rs
Since https://github.com/dfinity/nns-dapp/pull/5738, the backend no longer claims unclaimed neurons.
We still left the `MultiPartTransactionToBeProcessed::StakeNeuron` enum value behind, in case there were still instances of it in the queue.
Now that the nns-dapp canister has been upgraded, we can safely clean up this enum value completely.
1. Remove `MultiPartTransactionToBeProcessed::StakeNeuron`.
2. Stop matching against `MultiPartTransactionToBeProcessed::StakeNeuron`.
1. In the test `push_then_take_next`, use `CreateCanisterV2` instead of `StakeNeuron`.
not necessary
> Remove MultiPartTransactionToBeProcessed::StakeNeuron

- frontend/scripts/build.csp.mjs
When trying to load the ICP Swap tickers URL, we get an error because of the Content Security Policy.
1. Add the `${{ICP_SWAP_URL}}` placeholder to the content security policy template such that the canister replaces it with the URL from the canister args during installation. We do the same for the SNS aggregator URL.
1. Tested manually on DevEnv. Without this we can't load ICP Swap tickers and with this we can.
not yet
> Add ICP Swap URL to CSP

- .github/workflows/build.yml
- scripts/canister_ids
- scripts/canister_ids.mainnet.golden
- scripts/canister_ids.test
If we want to deploy to DevEnv from another machine, we first need to import the canister IDs with
```
./scripts/canister_ids --import-from-index-html https://qsgjb-riaaa-aaaaa-aaaga-cai.$USER-ingress.devenv.dfinity.network/ --network devenv_$USER
```
to be able to deploy with the correct canister IDs in the canister args.
We do this during the release process, for example.
1. Include the `icp-swap` canister ID in the IDs that get imported with `scripts/canister_ids --import-from-index-html`
1. Test updated.
not necessary
> Support icp-swap in canister import

- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/lib/components/ui/NeuronTag.svelte
- frontend/src/lib/modals/neurons/NeuronVisibilityRow.svelte
- frontend/src/lib/types/neuron-visibility-row.ts
- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/lib/modals/neurons/NeuronVisibilityRow.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/page-objects/NeuronIdCell.page-object.ts
- frontend/src/tests/page-objects/NeuronTag.page-object.ts
- frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronCardTitle.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts
For inactive neurons, a 🔴 red tag (styled as `danger`) needs to be shown. Currently, in many places, the information for neuron tags is provided as a `string` and rendered using the base `Tag` component. With this PR, we replace the `string` with `NeuronTagData` for tag data type and replace the `Tag` component with the `NeuronTag` component.
Note: The neuron tag will be extended with the status in a separate PR.
- Add size property to the NeuronTag.
- Replace string with NeuronTagData for the neuron tag data.
- Replace Tag with NeuronTag component for neuron tags.
- Added NeuronTagPo
- Updated tests to use it.
Not necessary
> Refactor neuron tag

- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/lib/types/tokens-page.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
We want to show USD values in the tokens table.
In this PR we add a field `balanceInUsd` to `UserTokenData`, so that it can be used in a later PR to display USD values.
1. Add `balanceInUsd` field to `UserTokenData` type.
2. In `tokensListUserStore` populate the `balanceInUsd` field if price data is available.
1. Unit tests added with price data loaded and not loaded.
2. Tested manually in a branch with more changes.
not yet
> Add balanceInUsd to UserTokenData

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
https://github.com/dfinity/nns-dapp/pull/5913 added `balanceInUsd` for the data provided for the tokens table.
For the accounts table we need to do the same for `icpTokensListUser` as we did for `tokensListUserStore`.
1. In `icpTokensListUser` populate the `balanceInUsd` field if price data is available.
1. Unit tests added with price data loaded and not loaded.
2. Tested manually in a branch with more changes.
not yet
> Add balanceInUsd to UserTokenData for accounts page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/stores/sns-aggregator.store.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts
As discussed [here](https://dfinity.slack.com/archives/C03H6QEPW5D/p1733263773416409) and [here](https://dfinity.slack.com/archives/C039M7YS6F6/p1733302975333649), we have a situation with the SNS `CYCLES-TRANSFER-STATION`. They have decided to change all their metadata, resulting in the name and token being displayed as `---`.
This first PR introduces a method to override the values we receive from the SNS-Aggregator, allowing the rest of the application to use them.
- Checks a dictionary of "broken" SNSs for matches and overrides `name` and `token.symbol` for any that are found.
- Unit test for the aggregator store derived data to verify that when `rootCanisterId` is present in the dictionary, the values for `name` and `token.symbol` are replaced.
> Fix: Adds an override for the name and token.symbol values for abandoned SNS

- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
- frontend/src/tests/routes/app/tokens/page.spec.ts
In order to have exchange rate data available, we need to call `loadIcpSwapTickers`.
1. Call `loadIcpSwapTickers()` from the tokens pages.
not yet
> Load ICP Swap tickers on tokens page

- frontend/src/lib/routes/Accounts.svelte
- frontend/src/tests/lib/routes/Accounts.spec.ts
In order to have exchange rate data available, we need to call `loadIcpSwapTickers`.
1. Call `loadIcpSwapTickers()` from the accounts pages.
not yet
> Load ICP Swap tickers on account page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/stores/sns-aggregator.store.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts
As discussed [here](https://dfinity.slack.com/archives/C03H6QEPW5D/p1733263773416409) and [here](https://dfinity.slack.com/archives/C039M7YS6F6/p1733302975333649), we have a situation with the SNS `CYCLES-TRANSFER-STATION`. They have decided to change all their metadata, resulting in the name and token being displayed as `---`.
This second PR moves abandoned SNSs to the bottom of both the `nsAggregatorStore` and any alphabetical sort.
- Adds the hidden character `"\u200B"` to the beginning of the name of an abandoned SNS, so alphabetical sorting pushes them to the end.
- Sorts `nsAggregatorStore` by the temporal parameter `isAbandoned`.
- Unit test for the aggregator store derived data to verify that sort functionality works as expected.
Prev. PR: #5915
> Fix: Pushes abandoned SNS to the bottom of the nsAggregatorStore

- frontend/src/lib/components/neuron-detail/NeuronFollowingCard/Followee.svelte
- frontend/src/lib/components/neurons/NnsLosingRewardsNeuronCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neurons/NnsLosingRewardsNeuronCard.spec.ts
- frontend/src/tests/page-objects/Card.page-object.ts
- frontend/src/tests/page-objects/Followee.page-object.ts
- frontend/src/tests/page-objects/NnsLosingRewardsNeuronCard.page-object.ts
For the confirm following modal, we need to display inactive neurons with it's following. Here we add a neuron list item component that later will be used.
Note: In a later PR, the style of the Followee component will be slightly adjusted.
- New NnsLosingRewardsNeuronCard component.
- [Refactor FolloweePo to return the same title for active and inactive components.](https://github.com/dfinity/nns-dapp/pull/5909/commits/eecd8958f02a086a4d11fa416f68ca28e997398c)
- Added NnsLosingRewardsNeuronCardPo.
- Added test for NnsLosingRewardsNeuronCard.
- Tested locally in another branch.
Not necessary.
> Losing rewards neuron card

- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
On desktop, token values are already right-aligned.
On mobile they seemed to be right aligned because the row has `justify: space-between` but now that we have 2 different values, the smaller dollar value is left-aligned relative to the original token value.
Apply `align-items: flex-end` to the token values element.
Before:
After:
not necessary
> Align dollar values right on mobile

- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/ui/UsdValueBanner.spec.ts
- frontend/src/tests/page-objects/UsdValueBanner.page-object.ts
At the top of both the tokens page and the neurons page we want to show a banner with the total value in USD of the listed assets.
This PR adds a first version of that banner component, not yet used on any page.
Switching the USD/ICP values and error state will be added in subsequence PRs.
1. Add banner component.
not necessary
> Add banner to show total USD value

- frontend/package-lock.json
- frontend/src/lib/components/neurons/LosingRewardsBanner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/LosingRewardNeuronsModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neurons/LosingRewardNeuronsModal.spec.ts
- frontend/src/tests/lib/components/neurons/LosingRewardsBanner.spec.ts
- frontend/src/tests/page-objects/LosingRewardNeuronsModal.page-object.ts
- frontend/src/tests/page-objects/LosingRewardsBanner.page-object.ts
- frontend/src/tests/page-objects/NnsLosingRewardsNeuronCard.page-object.ts
Users should not only be notified about neurons that are losing rewards but also be able to refresh all these neurons to keep them active. To achieve this, the Confirm Following modal was created. It displays all inactive neurons along with their followings.
Out of scope:
- Refresh api call.
- The gaps in the Following component need to be adjusted to match the new design.
- Tags status.
- Page reload after navigation to the neuron details page.
- New LosingRewardNeuronsModal component.
- Should fetch known neurons, to display them in the following neurons component.
- Display the modal from the LosingRewardsBanner.
- Unit tests updated.
- Tested manually in a separate branch.
| Dark | Light |
| <img width="216" alt="image" …
> Losing rewards modal

- frontend/src/lib/utils/icp-transactions.utils.ts
TypeScript was inferring a string type for `transactionDirection` when it should specifically be either "credit" or "debit". Adding an explicit type union improves type safety and prevents potential bugs from assigning invalid values.
- Added literal type union `"credit" | "debit"` to `transactionDirection` variable
Not necessary
Not necessary
> refactor: add explicit type annotation for transactionDirection

- frontend/src/lib/utils/icp-transactions.utils.ts
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
`getTransactionInformation` was throwing an error while its consumers were expecting an `undefined` and they will handle the error.
- `getTransactionInformation` should return `undefined` if the transaction type is unknown.
- New unit tests for `mapIcpTransactionToUi` check for a toast message when an error is thrown.
Not necessary.
> fix: error handling for getTransactionInformation

- frontend/src/lib/components/header/AccountMenu.svelte
- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
- frontend/src/tests/page-objects/AccountMenu.page-object.ts
We want to show the new `ExportIcpTransactionsButton` in the `AccountMenu` so it can be used by our users.
It is behind the  feature flag `ENABLE_EXPORT_NEURONS_REPORT`
It can be tested [here](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
- Displays `ExportIcpTransactionsButton` in `AccountMenu` when `ENABLE_EXPORT_NEURONS_REPORT` is `true`
- Component tests
Prev. PR: #5887
> NNS1-3480: adds ExportIcpTransactionsButton to AccountMenu

- frontend/src/lib/components/header/ExportIcpTransactionsButton.svelte
- frontend/src/lib/services/export-data.services.ts
- frontend/src/tests/lib/components/header/ExportIcpTransactionsButton.spec.ts
- frontend/src/tests/lib/services/export-data.services.spec.ts
We want to retrieve neuron transactions when generating a report for all transactions. We aim to request transactions for both Neurons and Accounts simultaneously, allowing us to parallelize these calls to the Ledger Canister.
- Changes `getAccountTransactionsConcurrently` to handle generic entities(neurons or accounts)
- Unit test for the new logic that parallelizes both types of entities: accounts and neurons.
Prev. PR: #5941
> NNS1-3480: Neurons Transactions

- frontend/src/lib/pages/Tokens.svelte
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/TokensPage.page-object.ts
Using the banner component from https://github.com/dfinity/nns-dapp/pull/5932 on the tokens page.
1. Calculate the sum of USD values in `frontend/src/lib/pages/Tokens.svelte`.
2. Add `UsdValueBanner` if `ENABLE_USD_VALUES` is enabled.
not yet
> Add USD value banner on tokens page

- frontend/src/lib/utils/projects.utils.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
This is a follow-up to #5918 regarding the display of SNS projects in the Launchpad section. We aim to sort them in descending order, from newest to oldest. 
This initial PR introduces a function to sort based on `swapOpenTimestampSeconds`. 
The subsequent PR will implement the requirements outlined in [NNS-3497](https://dfinity.atlassian.net/jira/software/c/projects/NNS1/boards/333?selectedIssue=NNS1-3497).
-  New descending sort function based on SNS summary `swapOpenTimestampSeconds`.
- Unit tests
Not necessary
> NNS1-3497: new function to sort SNS projects from newest to oldest

- scripts/canister_ids.mainnet.golden
We have a script `./scripts/canister_ids` which can import canister IDs based on an existing deployed NNS dapp canister on any network.
We also have a test that tests that this works for `mainnet`.
With the latest nns-dapp mainnet upgrade, there is a new canister ID imported for ICP Swap.
So the test started [failing](https://github.com/dfinity/nns-dapp/actions/runs/12234467204/job/34123959181) on CI and we need to update the golden state to make the test pass again.
Update golden mainnet canister IDs.
CI should pass again.
not necessary
> Update golden mainnet canister IDs with ICP Swap canister ID

- frontend/src/lib/stores/neurons.store.ts
The `neuronsStore` was initially changed to hold only neurons with valid stake #719. However, it was later modified to retain all neurons, while a `derivedStore` would provide the subset #1476.
The comment is outdated and leads to confusion.
- Removes outdated comment
Not necessary
Not necessary
> docs: remove wrong comment for the neuronsStore

- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/lib/derived/icp-swap.derived.ts
- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/derived/tokens-list-user.derived.ts
- frontend/src/tests/lib/derived/icp-swap.derived.spec.ts
We loaded token prices from ICP Swap.
If this results in an error, we want to show `-/-` as USD values and show an error state with tooltip.
There can be 2 reasons why there is an error:
1. Fetching the ICP Swap data fails.
2. Parsing the ICP Swap data fails.
In this PR we add an extra possible `"error"` value to the derived store `icpSwapUsdPricesStore` and use it if parsing the ICP Swap data fails.
1. Set `icpSwapUsdPricesStore` to `"error"` if there is an error when parsing ICP Swap tickers or if there is an unreasonable value.
not yet
> Add error state to icpSwapUsdPricesStore

- frontend/src/lib/components/ui/TooltipIcon.svelte
- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/ui/UsdValueBanner.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/UsdValueBanner.page-object.ts
If we can't load token prices from ICP Swap, we should show an orange tooltip icon with explanation.
1. Add `--tooltip-icon-color` CSS variable to customize tooltip icon color.
2. Use a different tooltip icon color and text if `icpSwapUsdPricesStore` is in error state.
3. 
2. Tested manually by hardcoding a bad response in `frontend/src/lib/api/icp-swap.api.ts`.
not yet
> Show error tooltip in USD value banner

- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/ui/UsdValueBanner.spec.ts
USD prices in NNS dapp are based on the ckUSDC price in ICP Swap.
Since ckUSDC is not strictly the same as USD, we should mention this.
Mention "ckuSDC" in the tooltip that is shown next to the ICP exchange rate.
Unit tests updated.
not yet
> Mention ckUSDC in tooltip about ICPSwap

- frontend/src/lib/derived/icp-swap.derived.ts
- frontend/src/lib/services/icp-swap.services.ts
- frontend/src/lib/stores/icp-swap.store.ts
- frontend/src/tests/lib/derived/icp-swap.derived.spec.ts
- frontend/src/tests/lib/services/icp-swap.services.spec.ts
We loaded token prices from ICP Swap.
If this results in an error, we want to show `-/-` as USD values and show an error state with tooltip.
There can be 2 reasons why there is an error:
1. Fetching the ICP Swap data fails.
2. Parsing the ICP Swap data fails.
In this PR we set the error state when fetching the data fails.
1. Add `"error"` as a possible value for `initIcpSwapTickersStore`.
2. Forward `"error"` from `initIcpSwapTickersStore` to `icpSwapUsdPricesStore` (which already has the state for when parsing fails).
3. Set `"error"` when the API call fails in the service.
2. Added manually by adding `throw new Error()` in the API function.
not yet
> Show error state when ICPSwap API call fails.

- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/ui/UsdValueBanner.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/page-objects/UsdValueBanner.page-object.ts
At the top of the tokens page, we want to show the total value of the user's tokens.
If we don't have price data for some tokens, we treat these tokens as having no value.
To indicate this, we show an extra tooltip if the user owns any tokens which we ignored in computing the total.
1. Add `hasUnpricedTokens` prop to `UsdValueBanner`.
2. If the prop is true, show an extra tooltip.
3. Pass `hasUnpricedTokens` from `Tokens.svelte` based on whether the user has any tokens with positive `balance` but undefined `balanceInUsd`.
not yet
> Show tooltip when price data is missing for some tokens

- frontend/src/lib/components/ui/NeuronTag.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/ui/NeuronTag.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/Tag.page-object.ts
Neurons that are about to start missing rewards need to be marked with a tag to draw users' attention, indicating that action needs to be taken to avoid missing rewards. This PR introduces a "warning" state to the `NeuronsTag` component and applies it to the tags for "missing soon" neurons.
- Added a "warning" neuron tag status.
- Introduced a "...to confirm" tag.
- Added.
Not necessary.
> Missing rewards soon tag

- frontend/src/lib/constants/routes.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/SignInReporting.svelte
- frontend/src/lib/routes/Reporting.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/routes/(app)/(nns)/reporting/+layout.svelte
- frontend/src/routes/(app)/(nns)/reporting/+page.svelte
- frontend/src/tests/lib/routes/Reporting.spec.ts
- frontend/src/tests/page-objects/ReportingPage.page-object.ts
- frontend/src/tests/routes/app/reporting/layout.spec.ts
- frontend/src/tests/routes/app/reporting/page.spec.ts
This new page will display all reporting functionalities currently found in the `AccountMenu`. 
This first iteration introduces the page without any logic. Subsequent pull requests will migrate the Export components from the `AccountMenu` to this page.
- New Reporting page
- Unit tests for the route's layout and page
- Unit tests for the page
Not yet
Next PR: #5965
> NNS1-3485: initial setup for the new reporting page

- frontend/src/lib/components/header/AccountMenu.svelte
- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/routes/Reporting.svelte
- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/page-objects/AccountMenu.page-object.ts
- frontend/src/tests/page-objects/ReportingTransactionsButton.page-object.ts
Moves the existing `ExportIcpTransactionsButton` from the `AccountMenu` to the `Reporting` page.
A follow up PR will handle the changes(styles, copy, ...)
- Moves component and tests to a new location.
- Renames the component to fit the new location.
- Moves tests but none added.
Not necessary.
> NNS1-3485: migrates ExportTransactions component from AccountMenu to Reporting page

- frontend/src/lib/components/accounts/IcrcWalletPage.svelte
- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/routes/Wallet.svelte
- frontend/src/tests/lib/components/accounts/WalletPageHeading.spec.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
- frontend/src/tests/page-objects/WalletPageHeading.page-object.ts
Like on the tokens and account page we also want to show your balance in USD on the wallet pages.
1. Add `ledgerCanisterId` prop to `WalletPageHeading` component to identify the token for the ICP Swap price data.
2. Add USD price and tooltip to `WalletPageHeading` component.
3. Pass `ledgerCanisterId` prop from `NnsWallet` and `IcrcWalletPage`.
4. Load ICPSwap tickers from `Wallet` component to make sure the data is available.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/wallet/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> Show USD balance on wallet page

- frontend/src/lib/components/header/AccountMenu.svelte
- frontend/src/lib/components/reporting/ReportingNeuronsButton.svelte
- frontend/src/lib/routes/Reporting.svelte
- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingNeuronsButton.spec.ts
- frontend/src/tests/page-objects/AccountMenu.page-object.ts
- frontend/src/tests/page-objects/ReportingNeuronsButon.page-object.ts
Moves the existing `ExportNeuronsButton` from the `AccountMenu` to the `Reporting` page.
A follow up PR will handle the changes(styles, copy, ...)
- Moves component and tests to a new location.
- Renames the component to fit the new location.
- Moves tests, but none were added.
Not necessary.
> NNS1-3485: migrate ExportNeurons component to new page

- frontend/src/lib/utils/export-to-csv.utils.ts
- frontend/src/tests/lib/utils/export-to-csv.utils.spec.ts
The new `showSaveFilePicker` browser API allows users to define where the file will be saved and its name. Some manual tests are producing the error below, which requires further investigation. The feature will be disabled until the issues are resolved.
```
Error exporting neurons: FileSystemAccessError: Failed to save file using File System Access API
at Uq (index.BHFanVrx.js:18:481)
at async LS (index.BHFanVrx.js:21:354)
at async HTMLButtonElement.D (index.BHFanVrx.js:21:23629)
Caused by: SecurityError: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.
```
Disabling the feature until we are able to reproduce it locally.
- Skips the `showSaveFilePicker` code path.
- Skipped tests until we make use of it.
Not necessary
> NNS1-3485: disables showSaveFilePicker download method

- frontend/package-lock.json
- frontend/src/tests/mocks/neurons.mock.ts
We want to pull in the latest changes to make the reset following api accessible for the nns-dapp.
Related ic-js pr: https://github.com/dfinity/ic-js/pull/787
- npm run upgrade:next.
- Add new fields to the mock - the reason why the CI action upgrade is failing.
- Should pass.
Not necessary.
> Upgrade next ic js

- frontend/src/lib/components/neurons/LosingRewardsBanner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/LosingRewardNeuronsModal.svelte
- frontend/src/lib/types/i18n.d.ts
There are a couple of texts that are supposed to be the same across multiple elements. To avoid duplication, we moved these labels to a single place.
- Move description and confirm labels.
- Pass.
Not necessary.
> Move losing rewards labels

- frontend/.prettierrc
- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/lib/components/ui/UsdValueBanner.svelte
For the second time in 2 days I ran into issues with whitespace caused by `prettier` reformatting.
Yesterday I had to add `prettier-ignore` in https://github.com/dfinity/nns-dapp/pull/5974 to avoid test breakage.
Today I need to fix a tooltip padding issue caused by whitespace introduced by `prettier`.
Bad:
Good:
Instead of keep adding `prettier-ignore` I decided to change the `prettier` configuration to be strict about whitespace in HTML.
1. Set `"htmlWhitespaceSensitivity": "strict"` in `frontend/.prettierrc`.
2. Remove `` added in https://github.com/dfinity/nns-dapp/pull/5974
3. Remove whitespace that caused bad tooltip padding.
1. Ran `npm run format` manually. Also changed some incorrect indentation to check that that is still formatted nicely.
2. Checked manually that the tooltip …
> Fix whitespace caused by prettier

- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/routes/Reporting.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/lib/routes/Reporting.spec.ts
- frontend/src/tests/page-objects/ReportingTransactionsButton.page-object.ts
We want to use all neurons not only the non-empty ones thus we need to fetch them directly from the governance canister.
It can be checked [here](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/tokens/)
- Fetch all neurons from the governance canister and sort by stake
- Disable button while async work is happening
- Styled the button
- Unit test to ensure that transactions for neurons are fetched when provided
- Unit test to check that neurons are sorted by stake
- Unit test to check that the button is disable while async operations
Not necessary.
> NNS1-3485: gets all neurons(non-empty and empty) in ReportingTransactionsButton 

- frontend/src/lib/i18n/en.json
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
In case there are inactive neurons, the user should be able to reset their voting-power-refreshed timestamp. In this PR, we add the service that performs this action.
- Added `refreshVotingPowerForNeurons` service.
- Added.
Not necessary.
> Refresh voting power service

- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/utils/icp-transactions.utils.spec.ts
- frontend/src/tests/lib/utils/icrc-transactions.utils.spec.ts
Translations for the operations `Mint` and `Burn` were incorrectly labeled as `Receive` and `Send`. They have been changed to `Mint` and `Burn`.
- Changes translations
> NNS1-3485: fixes translations for the operations mint and burn

- frontend/src/tests/lib/utils/neuron.utils.spec.ts
One test is [flaky](https://github.com/dfinity/nns-dapp/actions/runs/12276181573/job/34252843443) because the mocked data was created during test initialization with the current time value, assuming it wouldn't change. However, the system time was updated before every test with the current time using `vi.useFakeTimers().setSystemTime(Date.now())`. This results in a failed test due to date rounding in `nowInSeconds`.
- Use the same time for both mock data calculation and system time.
- Pass.
Not necessary.
> Fix flaky test

- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/periodic_tasks_runner.rs
https://github.com/dfinity/nns-dapp/pull/5862 removed the canister top-up functionality from the backend canister.
It left some TODOs to do after the next release.
There has now been a release so we can remove `MultiPartTransactionToBeProcessed::TopUpCanisterV2` now.
Remove `MultiPartTransactionToBeProcessed::TopUpCanisterV2`.
CI passes
not necessary
> FOLLOW-244: Remove MultiPartTransactionToBeProcessed::TopUpCanisterV2

- frontend/src/lib/components/ic/AmountWithUsd.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
- frontend/src/tests/lib/components/ic/AmountWithUsd.spec.ts
- frontend/src/tests/page-objects/AmountWithUsd.page-object.ts
In the tokens table we display token amounts with amount in USD.
We want to do the same, using the same style, for stake in the projects table and neurons table.
This PR factors out a component to display the 2 amounts to be reused in other tables.
1. Add `AmountWithUsd` based on `TokenBalanceCell`.
2. Use `AmountWithUsd` in `TokenBalanceCell`.
2. Existing tests pass.
not necessary
> Add AmountWithUsd component

- frontend/src/lib/derived/icp-tokens-list-user.derived.ts
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/utils/token.utils.spec.ts
The function `getUsdValue` defined in `frontend/src/lib/derived/icp-tokens-list-user.derived.ts` would be useful to reuse to display neuron stake in USD.
Move `getUsdValue` to `frontend/src/lib/utils/token.utils.ts`.
not necessary
> Move getUsdValue to utils

- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/mocks/staking.mock.ts
We want to show USD values for neuron stakes in the projects table.
In this PR we just provide the values but don't render them yet.
1. Add `stakeInUsd` field to `TableProject` type.
2. Populate `stakeInUsd` in `getTableProjects` if `icpSwapUsdPrices` is passed and a price it available for the relevant projects.
2. Tested manually in another branch with more changes.
not yet
> Add stakeInUsd to TableProject

- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronRewardStatusAction.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronRewardStatusActionTest.svelte
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/FollowNeuronsButton.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronRewardStatusAction.page-object.ts
In the case where a neuron hasn't been used for a long period of time (currently defined as 6 + 1 months), its followings are reset. To avoid confusion, it was decided to display a special type of inactive status with additional information in the description and a "Set Following" button, instead of "Confirm Following"
**Note:** Currently, the component looks suboptimal with such a long description. This issue will be addressed in a separate PR.
- New `isNeuronFollowingReset` util.
- Display additional Neuron reward state.
- Updated unit tests.
- Tested manually:
Not necessary.
> Reset following neuron state

- frontend/src/lib/components/staking/ProjectStakeCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/page-objects/ProjectStakeCell.page-object.ts
- frontend/src/tests/page-objects/ProjectsTableRow.page-object.ts
Similar to the USD values in the tokens table we want to show USD values in the projects table.
1. Use `AmountWithUsd` in `ProjectStakeCell` if `ENABLE_USD_VALUES_FOR_NEURONS` is enabled.
2. Load ICP Swap tickers in `ProjectsTable.svelte` when signed in and the feature flag is enabled.
not yet
> Show stake in USD in projects table

- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
Currently, the meaning of the neuron rewards status might not be very clear. To improve this, we are adding an info icon with a description of this indicator.
- Added description to the neuron rewards status action field 
- Tested manually
Not necessary.
> Neuron rewards status info

- frontend/src/lib/modals/neurons/LosingRewardNeuronsModal.svelte
- frontend/src/tests/lib/components/neuron-detail/actions/ConfirmFollowingButton.spec.ts
- frontend/src/tests/lib/components/neurons/LosingRewardNeuronsModal.spec.ts
- frontend/src/tests/lib/components/neurons/LosingRewardsBanner.spec.ts
- frontend/src/tests/page-objects/LosingRewardNeuronsModal.page-object.ts
If there are inactive neurons, the user should be able to reset their voting-power-refreshed timestamp. In this PR, we add a ["Confirm Following" button](https://github.com/dfinity/nns-dapp/pull/5990) to the modal that displays the user’s inactive neurons.
- Add the `ConfirmFollowingButton` to the modal.
- Close the modal when all inactive neurons are refreshed.
- Added.
Not necessary.
> Confirm following from banner

- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronRewardStatusAction.spec.ts
- frontend/src/tests/page-objects/NnsNeuronRewardStatusAction.page-object.ts
If there are inactive neurons, the user should be able to reset their voting-power-refreshed timestamp from the neuron details page. In this PR, we add a ["Confirm Following" button](https://github.com/dfinity/nns-dapp/pull/5990) to the neuron status field. It should be shown for all statuses except when the followings of a neuron have already been reset.
- Add the `ConfirmFollowingButton` to the `NnsNeuronRewardStatusAction` component.
- Updated.
- Tested locally:
https://github.com/user-attachments/assets/70d159fc-ee22-408e-b013-097f16a36e54
Not necessary.
> Refresh voting power from details

- dfx.json
- frontend/src/tests/e2e/ckbtc.spec.ts
[The automatic update](https://github.com/dfinity/nns-dapp/pull/6009) had test failure.
It appears that the ckBTC checker, which replaces the KYT canister (see https://github.com/dfinity/snsdemo/pull/427 and https://github.com/dfinity/snsdemo/pull/435), has lower fees.
1. Update the snsdemo release.
2. Update the end-to-end test that failed in the automatic update.
Updated
not necessary
> Update snsdemo to release-2024-12-11

- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/stores/sns-neurons-table-order-sorted-neuron-ids-store.ts
- frontend/src/lib/types/neurons-table.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
We want to show USD values in the neurons tables, similar to the tokens table and the projects table.
In this PR we just add the USD stake to the `TableNeuron` objects. It will be displayed in future PRs.
1. Add `stakeInUsd` field to `TableNeuron` type.
2. Populate `stakeInUsd` in and `tableNeuronsFromNeuronInfos` and `tableNeuronsFromSnsNeurons`.
3. Make `icpSwapUsdPrices` temporarily an optional parameter until we pass it from all the components callers in future PRs. Then they will be tested too.
1. Unit tests adapted.
2. Tested manually (including future changes) at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> Add stakeInUsd field to TableNeuron

- frontend/src/lib/stores/toasts.store.ts
- frontend/src/lib/types/toast.ts
- frontend/src/lib/utils/i18n.utils.ts
We want to define the types of potential messages that can be passed to the `toast` store. We can extract this list of potential messages from `I18n`.
https://github.com/user-attachments/assets/17c7d582-bf7b-42f4-b873-8aee9c2919a5
We can't enforce just `I18n` keys as we have some places were we programmatically pass the value and we don't have control on the type.
- Types `labelKey` based on `I18n` nested keys.
Not necessary
> refactor: types toast messages 

- frontend/src/lib/components/neurons/NeuronsTable/NeuronStakeCell.svelte
- frontend/src/lib/components/staking/ProjectStakeCell.svelte
- frontend/src/lib/components/tokens/TokensTable/TokenBalanceCell.svelte
- frontend/src/tests/lib/components/neurons/NeuronsTable/NeuronsTable.spec.ts
- frontend/src/tests/page-objects/NeuronStakeCell.page-object.ts
- frontend/src/tests/page-objects/NeuronsTableRow.page-object.ts
We want to show USD values in the neurons tables, similar to the tokens table and the projects table.
This PR adds support for rendering the `stakeInUsd` field in the `NeuronsTable` components.
Still missing (for future PRs):
1. Passing `icpSwapUsdPrices` to `tableNeuronsFromNeuronInfos` and `tableNeuronsFromSnsNeurons`.
2. Calling `loadIcpSwapTickers` on the neurons table page to make sure data is available.
1. Render stake in USD in `NeuronStakeCell.svelte` if `ENABLE_USD_VALUES_FOR_NEURONS` is enabled.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> Support rendering stake in USD in NeuronsTable

- frontend/src/lib/services/reporting.services.ts
- frontend/src/tests/lib/services/reporting.services.spec.ts
- frontend/src/tests/mocks/icp-transactions.mock.ts
Users can select a date range before generating a report. We need to filter the results in the front end and stop fetching pages if we exceed the `from` date.
The ledger canister returns transactions sorted by date, with the newest transaction listed first and the oldest transaction listed last.
```
Present                                                                     Past
(now)                                                                      (t)
0-----------------------[TO]-----------------[FROM]--------------------------->t
|                        |                     |                            |
|                        |                     |                            |
Current time        Newer limit            Older limit                   Earliest
transaction
- …
```
> feat: filters icp ledger transactions based on range if provided

- frontend/src/lib/components/accounts/SelectNetworkDropdown.svelte
Fix warning which becomes an error with Svelte v5 tooling (PR #6020).
```
/Users/daviddalbusco/projects/dfinity/nns-dapp/frontend/src/lib/components/accounts/SelectNetworkDropdown.svelte
62:6  error  `<span>` cannot be a child of `<option>`. `<option>` only allows these children: `<#text>`. The browser will 'repair' the HTML (by moving, removing, or inserting elements) which breaks Svelte's assumptions about the structure of your components.
https://svelte.dev/e/node_invalid_placement(node_invalid_placement)  svelte/valid-compile
```
- Remove `span` in `option`.
> fix: <span> cannot be a child of <option>

- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/lib/components/common/EmptyCards.svelte
- frontend/src/lib/components/project-detail/CommitmentProgressBar.svelte
- frontend/src/lib/components/ui/ProposalStatusTag.svelte
- frontend/src/tests/lib/components/accounts/IcrcBalancesObserverTest.svelte
- frontend/src/tests/lib/components/accounts/IcrcWalletTransactionsObserverTest.svelte
- frontend/src/tests/lib/directives/IntersectionTest.svelte
Fix warning which becomes an error with Svelte v5 tooling (PR #6020).
```
19:5  error  Self-closing HTML tags for non-void elements are ambiguous — use `<div ...></div>` rather than `<div ... />`
https://svelte.dev/e/element_invalid_self_closing_tag(element_invalid_self_closing_tag)  svelte/valid-compile
```
- e.g. `<div />` -> `<div></div>`
> chore: self-closing HTML tags for non-void elements are ambiguous

- frontend/src/lib/components/reporting/ReportingDateRangeSelector.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/reporting.ts
- frontend/src/tests/lib/components/reporting/ReportingDateRangeSelector.spec.ts
- frontend/src/tests/page-objects/ReportingDateRangeSelector.page-object.ts
Users can filter their export by choosing one of three options: all, this year, or last year.
A follow up PR will introduce a new component `ReportingDateRangeSelector` that will onrchestrate the `dateRange` filter by passing it down to both, the `ReportingDateRangeSelector` and to `ReportingTransactionsButton`.
- Adds a new component called `ReportingDateRangeSelector` to change the value of the date range filter.
- Unit tests
Not necessary
> NNS1-3486: adds ReportingDateRangeSelector 

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
The `attach_canister` function in the backend is unnecessarily much indented.
This can be avoided by inverting 2 `if`s and using early returns.
Make sure to enable "ignore whitespace" when reviewing.
1. Change
```
if Self::validate_canister_name(&request.name) {
...
} else {
AttachCanisterResponse::NameTooLong
}
```
to
```
if !Self::validate_canister_name(&request.name) {
return AttachCanisterResponse::NameTooLong;
}
...
```
2. Change
```
if let Some(mut account) = self.accounts_db.db_get_account(&account_identifier) {
...
} else {
AttachCanisterResponse::AccountNotFound
}
```
to
```
let Some(mut account) = self.accounts_db.db_get_account(&account_identifier) else {
return AttachCanisterResponse::AccountNotFound;
};
...
```
Added a missing test for …
> Simplify attach_canister with early returns

- frontend/src/lib/components/accounts/CkBTCInfoCard.svelte
- frontend/src/lib/routes/Settings.svelte
Fix warning which becomes an error with Svelte v5 tooling (PR #6020).
```
/Users/daviddalbusco/projects/dfinity/nns-dapp/frontend/src/lib/components/accounts/CkBTCInfoCard.svelte
85:15  error  `<div>` cannot be a descendant of `<p>`. When rendering this component on the server, the resulting HTML will be modified by the browser (by moving, removing, or inserting elements), likely resulting in a `hydration_mismatch` warning
https://svelte.dev/e/node_invalid_placement_ssr(node_invalid_placement_ssr)  svelte/valid-compile
```
- Transform container `p` into a `div`.
> fix: <div> cannot be a child of <p>

- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/stores/neurons-table-order-sorted-neuron-ids-store.ts
- frontend/src/lib/stores/sns-neurons-table-order-sorted-neuron-ids-store.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
In order to display neuron stakes in USD we need token price data to factor into the calculation.
1. Make `icpSwapUsdPrices` non-optional parameter to `tableNeuronsFromNeuronInfos` and `tableNeuronsFromSnsNeurons`. It can still be `undefined` but should only be so when the ICPSwap data isn't loaded yet.
2. Pass `icpSwapUsdPrices` from `NnsNeurons` and `SnsNeurons` components to display in the tables.
3. Include `icpSwapUsdPrices` in `tableNeuronsToSortStore` and `snsTableNeuronsToSortStore`. This currently has no effect but might if we ever include `stakeInUsd` in the ordering logic. It's good to have for completeness.
1. Unit tests added for `NnsNeurons` and `SnsNeurons`.
2. Since the USD price currently has no effect on ordering, there's nothing to test for …
> Pass icpSwapUsdPricesStore when constructing table neurons

- frontend/src/lib/services/reporting.services.ts
- frontend/src/lib/types/reporting.ts
- frontend/src/lib/utils/reporting.utils.ts
- frontend/src/tests/lib/utils/reporting.utils.spec.ts
We want to convert the selected radio value into a `DateRange` object that can be used when fetching the translations.
- New utility `convertPeriodToNanosecondRange` to convert a reporting period into a transaction date range.
- Unit tests
Not necessary
> NNS1-3486: new util function to convert from period to dateRange

- frontend/src/lib/routes/Neurons.svelte
- frontend/src/tests/lib/routes/Neurons.spec.ts
If the user deep links to the neurons table page, the ICPSwap tickers will not have been loaded yet.
1. Call `loadIcpSwapTickers` from `Neurons` route if `ENABLE_USD_VALUES_FOR_NEURONS` is enabled.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/staking/
not yet
> Load ICPSwap ticker on neurons tabel page

- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
Users should be able to refresh the voting power timestamp of a neuron to avoid missing voting rewards. A new API, `RefreshVotingPower`, is designed for this purpose. However, currently, the Ledger API does not support this type of transaction. This PR addresses the issue and provides a workaround. The `setFollowees` API is used for hardware HW neurons, as updating following and voting resets the voting power timestamp in the same way as the `RefreshVotingPower` call.
**Note:** The topic used to confirm the current state of the neuron does not matter, except for NeuronManagement, which can only be handled by controllers.
- Update `refreshVotingPowerForNeurons` service to call `setFollowees` with the current value for HW neurons.
- Added.
- Tested locally to confirm that it is possible to …
> Add HW support to refreshVotingPower

- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/services/reporting.services.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/lib/services/reporting.services.spec.ts
- frontend/src/tests/lib/utils/reporting.utils.spec.ts
We want to filter transactions by a specific period.
Follow up PR will hook the `PeriodDateRangeSelector` to the `PeriodTransactionsButton` so users selection will be propagated to the service.
- Forwards the `period` property from the `ReportingTransactionsButton` to the service.
- Changes the utility `filterTransactionsByRange` to exclude dates that are equal to `to` this.https://github.com/dfinity/nns-dapp/blob/bc7b3b64cafd286bb76a5996ae29447849220163/frontend/src/lib/types/reporting.ts#L6
- New unit tests for the component
- Updated test for the service
Not necessary
> NNS1-3486: updates reporting transactions button to provide period to the service

- frontend/src/lib/components/neuron-detail/ConfirmFollowingBanner.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/fakes/governance-api.fake.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/page-objects/ConfirmFollowingBanner.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
If a neuron is inactive, users should be notified to prevent rewards missing . This PR adds a banner with a description to the neuron details page to inform users about the neuron’s inactive status.
- Added `ConfirmFollowingBanner` component.
- Show `ConfirmFollowingBanner` on neuron details page.
- Added.
Not necessary
> Confirm following banner

- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/page-objects/ProjectsTable.page-object.ts
Similar to the tokens page, we want to show a banner with total stake in USD on the staking page.
1. Add utility function to add of `stakeInUsd` ignoring undefined stakes. Analogous to [getTotalBalanceInUsd](https://github.com/dfinity/nns-dapp/blob/5152fa635d0080fa3ed59ed53daf6afb4660412f/frontend/src/lib/utils/token.utils.ts#L337).
2. Add `UsdValueBanner` to `ProjectsTable` component when `ENABLE_USD_VALUES_FOR_NEURONS` is enabled and the user has some stake.
1. Unit tests added for `getTotalStakeInUsd`.
2. Unit tests added for `ProjectsTable`.
3. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/
not yet
> Show total stake in USD banner on projects page

- frontend/src/lib/components/accounts/WalletPageHeading.svelte
- frontend/src/lib/components/common/HeadingSubtitleWithUsdValue.svelte
- frontend/src/tests/lib/components/common/HeadingSubtitleWithUsdValue.spec.ts
- frontend/src/tests/page-objects/HeadingSubtitleWithUsdValue.page-object.ts
- frontend/src/tests/page-objects/WalletPageHeading.page-object.ts
On the wallet page, we show the account balance in USD in the heading subtitle.
We want to do something similar on the NNS and SNS neuron details page.
To make this easier, in this PR we extract a component to show a heading subtitle with USD value.
1. Extract `HeadingSubtitleWithUsdValue` from `WalletPageHeading`.
2. Use `HeadingSubtitleWithUsdValue` in `WalletPageHeading` if `ENABLE_USD_VALUES` is enabled.
2. Page objects adjusted.
3. Tested manually.
not necessary
> Extract HeadingSubtitleWithUsdValue

- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/page-objects/NnsNeurons.page-object.ts
We want to show people the total value for their NNS neuron in USD and ICP.
1. Add `UsdValueBanner` on `NnsNeurons` if `ENABLE_USD_VALUES_FOR_NEURONS` is enabled.
2. Support `TableNeuron` in `getTotalStakeInUsd` as the code would be identical as for `TableProject`.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=qsgjb-riaaa-aaaaa-aaaga-cai
not yet
> Add USD banner on NNS neurons page

- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/page-objects/NnsNeuronPageHeading.page-object.ts
Want to show the stake in USD on the neuron details page similar to how we show the account balance on the wallet page.
This PR does it for NNS neurons. Another PR will do SNS neurons.
And a third PR will make sure token prices are loaded when the neuron page is deep linked.
1. Use `HeadingSubtitleWithUsdValue` which was extracted in https://github.com/dfinity/nns-dapp/pull/6037 in `NnsNeuronPageHeading`. Some of the slot content is temporarily duplicate between with and without feature flag.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neuron/?u=qsgjb-riaaa-aaaaa-aaaga-cai&neuron=7894867686608507388
not yet
> Show stake in USD on NNS neuron details

- .github/repo_policies/BOT_APPROVED_FILES
According to this [slack thread](https://dfinity.slack.com/archives/CH4CADCJX/p1733844276935979), files changed by bots must be listed in `.github/repo_policies/BOT_APPROVED_FILES`.
This is supposed to be enforced starting 2025 but [this workflow](https://github.com/dfinity/nns-dapp/actions/runs/12405804323/job/34633261245?pr=6040) just failed because of it.
I looked at recent PRs made by bots and added the files changed by them to `.github/repo_policies/BOT_APPROVED_FILES`.
No idea how to test this without merging first and then running the bots.
not necessary
> Add BOT_APPROVED_FILES

- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/page-objects/SnsNeurons.page-object.ts
We want to show people the total value for their SNS neurons in USD and ICP.
Analogous to https://github.com/dfinity/nns-dapp/pull/6038
1. Add `UsdValueBanner` on `SnsNeurons` if `ENABLE_USD_VALUES_FOR_NEURONS` is enabled.
2. Show `-/-` instead of `0.00` if the token price for this SNS is not known.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neurons/?u=bd3sg-teaaa-aaaaa-qaaba-cai
not yet
> Show total USD stake banner on SNS neurons page

- frontend/src/tests/lib/components/reporting/ReportingDateRangeSelector.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactions.spec.ts
- frontend/src/tests/lib/routes/Reporting.spec.ts
- frontend/src/tests/page-objects/ReportingDateRangeSelector.page-object.ts
- frontend/src/tests/page-objects/ReportingPage.page-object.ts
- frontend/src/tests/page-objects/ReportingTransactions.page-object.ts
We want to be consistent and removed named parameters when not necessary.
Addresses this comment: https://github.com/dfinity/nns-dapp/pull/6032#discussion_r1890418487
- removes named parameters from Reporting related page-objects
Not necessary
> refactor: remove named parameters from Reporting page-objects

- frontend/src/lib/components/sns-neuron-detail/SnsNeuronPageHeading.svelte
- frontend/src/lib/pages/SnsNeuronDetail.svelte
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronPageHeading.spec.ts
- frontend/src/tests/page-objects/SnsNeuronPageHeading.page-object.ts
Want to show the stake in USD on the neuron details page similar to how we show the account balance on the wallet page.
https://github.com/dfinity/nns-dapp/pull/6039 did it for NNS neurons.
This PR does it for SNS neurons.
And a third PR will make sure token prices are loaded when the neuron page is deep linked.
1. Use `HeadingSubtitleWithUsdValue` in `SnsNeuronPageHeading`. Some of the slot content is temporarily duplicate between with and without feature flag.
2. Pass the `ledgerCanisterId` from `SnsNeuronDetail` to `SnsNeuronPageHeading` as it's needed to find the token price.
2. Manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neuron/?u=bd3sg-teaaa-aaaaa-qaaba-cai&neuron=d09433a0369029e7b1114df00138c0cf5bbbef6d0d150c0aa6dd0fd67 …
> Show stake in USD on SNS neuron details

- frontend/src/lib/routes/NeuronDetail.svelte
- frontend/src/tests/fakes/sns-aggregator-api.fake.ts
- frontend/src/tests/lib/routes/NeuronDetail.spec.ts
- frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
If the user deep links to the neuron details page, the ICPSwap tickers will not have been loaded yet.
1. Call `loadIcpSwapTickers` from `NeuronDetail.svelte` if `ENABLE_USD_VALUES_FOR_NEURONS` is enabled.
2. Support setting `ledgerCanisterId` in fake SNS aggregator API.
3. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/neuron/?u=bd3sg-teaaa-aaaaa-qaaba-cai&neuron=d09433a0369029e7b1114df00138c0cf5bbbef6d0d150c0aa6dd0fd67a75f985
not yet
>  Load ICPSwap ticker on neuron details page

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/constants/routes.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/page-objects/MenuItems.page-object.ts
We want to be able to navigate to the portfolio page by clicking an element in the navigation bar.
Follow up PR will introduce the new Route.
- New entry in the navigation bar.
- Unit test to check for the presence of the link base on the feature flag `ENABLE_PORTFOLIO_PAGE`
Not necessary
> feat(nav): add new navigation entry for Portfolio

- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
On the projects table page, if you don't have any neurons, we show a banner inviting you to stake a neuron.
For this reason, and because your total stake with 0 neurons is always $0, we hide the total USD value banner on the projects table page if we show the other banner.
The problem is that the logic used for this just checked if the total USD value of neurons was 0. But if there is an error loading ICP Swap tickers, we calculate your total stake in USD as 0 as well, but we do want to show the banner in an error state.
So we need to check the actual number of neurons instead of using the total value as a shortcut for not having neurons.
1. Check if the user has any neurons to decide on showing the USD value banner.
1. Add a unit test testing the error state of the banner.
2. Tested …
> Fix: Show error in USD banner on projects page

- frontend/src/lib/components/accounts/UiTransactionsList.svelte
- frontend/src/tests/lib/components/accounts/UiTransactionsList.spec.ts
- frontend/src/tests/page-objects/UiTransactionsList.page-object.ts
We fixed a minor bug in https://github.com/dfinity/nns-dapp/pull/5874 that prevented the `completed` property from being set to `true` for empty transactions. The `UiTransactionsList` uses this property to disable the list once we have fetched all the items. However, it renders an Empty component when there are no transactions, which obscured the bug.
This PR aims to simplify the logic and enhance readability.
* Refactor code to simplify the logic deciding what to render in the `UiTransactionsList`
- Added a new test to check the `Spinner`.  
- Added checks to existing tests for UI elements.
Not necessary
> refactor: UiTransactionsList rendering logic

- frontend/package-lock.json
- frontend/src/tests/mocks/neurons.mock.ts
To access the [new fields](https://github.com/dfinity/ic-js/pull/794) of the neuron info, we need to upgrade the ic-js version.
- Added new fields to the mock NeuronInfo.
- Pass.
Not necessary.
> Upgrade ic-js next version

- frontend/src/routes/(app)/(nns)/portfolio/+layout.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/routes/app/portfolio/layout.spec.ts
We need a new route to display the Portfolio page.
- Creates a new route in the (nns) group for the portfolio page.
- Unit test that the page renders with the appropriate title.
Not necessary.
> feat: add Portfolio route

- frontend/package-lock.json
We want to pull in the latest changes.
* Ran `npm run update:gix` locally
* CI should pass
* The pulled in changes should have been tested before being committed to their repositories.
Not necessary
> chore: bump gix-components to latest

- frontend/src/lib/components/common/MenuItems.svelte
Follow up on this [one](https://github.com/dfinity/nns-dapp/pull/6046/files#diff-4f5601a1438e042ad0712ce95604c71e170f9e38b927559aa2f438928b909f69R53)
Ticket: [NNS1-3510](https://dfinity.atlassian.net/browse/NNS1-3510)
- Replaces the `Portfolio` page icon with the `IconHome` icon.
Not necessary
[NNS1-3510]: https://dfinity.atlassian.net/browse/NNS1-3510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(ui): replace portfolio icon with IconHome

- frontend/src/lib/utils/page.utils.ts
- frontend/src/routes/(app)/(home)/+layout.svelte
- frontend/src/routes/(app)/(home)/+page.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/lib/utils/page.utils.spec.ts
- frontend/src/tests/routes/app/home/layout.spec.ts
- frontend/src/tests/routes/app/home/page.spec.ts
The new portfolio page will be the default landing page for users in the nns-dapp.  
Ticket: [NNS1-3510](https://dfinity.atlassian.net/browse/NNS1-3510)
- The `home` route will render the `Portfolio` page if the feature flag is enabled.
- Set route utilities to default to the `/portfolio` route if there is no match with the current path.
- Unit test the behavior of the utils function when `ENABLE_PORTFOLIO_PAGE` is enabled.
- Unit test the behavior of the home route when `ENABLE_PORTFOLIO_PAGE` is enabled.
Not necessary
[NNS1-3510]: https://dfinity.atlassian.net/browse/NNS1-3510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(nav): set AccountsPortfolio as default menu page

- frontend/src/lib/components/accounts/LedgerNeuronHotkeyWarning.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/LedgerNeuronHotkeyWarning.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/page-objects/LedgerNeuronHotkeyWarning.page-object.ts
- frontend/src/tests/page-objects/NnsWallet.page-object.ts
To prevent missing rewards for ledger neurons, we display a warning on the HW wallet page.
- Add `LedgerNeuronHotkeyWarning` component.
- Display `LedgerNeuronHotkeyWarning` .
- Added.
- Tested locally that the banner is closable.
Not necessary.
> Ledger neuron hotkey warning

- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronVotingPowerSection.svelte
- frontend/src/lib/components/neurons/NnsNeuronAmount.svelte
- frontend/src/lib/components/neurons/NnsNeuronDetailCard.svelte
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronDetailCard.spec.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/VotingNeuronListItem.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
New fields representing the voting power of a neuron have recently been introduced to the governance canister (https://github.com/dfinity/ic/blob/release-2024-12-06_03-16-base/rs/nns/governance/canister/governance.did#L741-L743), and the original votingPower field has been marked as [deprecated](https://github.com/dfinity/ic/blob/d9fe2076f677a08734bed90c67b1c3f4056ed621/rs/nns/governance/canister/governance.did#L740). With this PR, `votingPower` is replaced by `decidedVotingPower`, which more accurately reflects the current voting power state of a neuron.
**Note**: The new fields are marked as optional to maintain backward compatibility of the type, but they are expected to always be provided.
- Replace `NeuronInfo.votingPower` with `NeuronInfo.decidingVotingPower`.
- Updated.
Not …
> Deprecate voting power

- frontend/src/lib/components/neurons/NnsNeuronsMissingRewardsBadge.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronsMissingRewardsBadge.spec.ts
- frontend/src/tests/page-objects/NnsNeuronsMissingRewardsBadge.page-object.ts
When the user has Nns neurons that haven’t been active and are set to start losing rewards in 30 days or less, a red circle needs to be displayed next to the “Neuron Staking” sidebar item and on in the Neuron Staking page table to indicate that action is required.
In this PR, we introduce the indicator component, which will be used in the navigation menu and the projects table.
- New `NnsNeuronsMissingRewardsBadge` component.
- Added.
Not necessary.
> Nns missing rewards indicator

- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/page-objects/MenuItems.page-object.ts
When the user has Nns neurons that haven’t been active and are set to start losing rewards in 30 days or less, a red circle needs to be displayed next to the “Neuron Staking” sidebar item and on in the Neuron Staking page table to indicate that action is required.
In this PR, we add the indicator component next to the “Neuron Staking” navigation entry.
- Display the indicator in the menu.
- Test the presence of the indicator component. The logic is tested in the `NnsNeuronsMissingRewardsBadge.specs` file.
Not necessary.
> Display missing rewards indicator in navigation

- frontend/src/lib/components/reporting/ReportingNeurons.svelte
- frontend/src/lib/routes/Reporting.svelte
To maintain a consistent structure like that of `ReportingTransactions`, we want to apply a similar approach to the Neurons.
- New component `ReportingNeurons` to encapsulate the content and the button.
Not necessary
> refactor: extract neuron content into dedicated component

- frontend/src/lib/components/staking/ProjectTitleCell.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/page-objects/ProjectTitleCell.page-object.ts
When the user has Nns neurons that haven’t been active and are set to start losing rewards in 30 days or less, a red circle needs to be displayed next to the “Neuron Staking” sidebar item and on in the Neuron Staking page table to indicate that action is required.
In this PR, we add the indicator component in the projects table.
- Display the indicator in the table.
- Test the presence of the indicator component. The logic is tested in the NnsNeuronsMissingRewardsBadge.specs file.
Not necessary
> Display missing rewards indicator in projects table

- frontend/src/lib/components/portfolio/LoginCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
The portfolio page needs a dedicated login card to allow the user to login from this page.
Ticket [NNS1-3510](https://dfinity.atlassian.net/browse/NNS1-3510)
https://github.com/user-attachments/assets/1c551e5e-45f1-44e6-ac44-a9076a1adf24
- Creates new LoginCard component with authentication form
- Not necessary as there is no logic
Not necessary
Prev. PR: #6069
[NNS1-3510]: https://dfinity.atlassian.net/browse/NNS1-3510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): add login card component for portfolio page

- frontend/src/lib/components/neurons/MakeNeuronsPublicBanner.svelte
- frontend/src/lib/components/ui/Banner.svelte
- frontend/src/lib/components/ui/UsdValueBanner.svelte
Update the banner backgrounds to align with the design.
- Replace the background variable for the identified banners, using background-color instead of background for improved clarity.
- Tested locally:
| 🌝 | 🌚 |
| <img width="1235" alt="image" src="https://github.com/user-attachments/assets/33bb3c0e-f058-4325-89c7-6277cfefcf4e" /> | <img width="1231" alt="image" src="https://github.com/user-attachments/assets/877ff493-e037-4b7f-9a30-a33614879f80" /> |
| <img width="789" alt="image" src="https://github.com/user-attachments/assets/fd2ba1a3-8898-4d45-bc73-f88492bdb641" /> | <img width="803" alt="image" src="https://github.com/user-attachments/assets/cdd7a5d2-1696-4c8e-ba08-acdc1caa6ca4" /> |
| <img width="793" alt="image" …
> Update banners background

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/routes/(app)/(home)/+layout.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
The new page for the Portfolio route features a layout with the following sections:  
* Top section
* `TotalAssetsCard`: that takes 100% the width when the user is logged in but only 1/3 of the space when the `LoginCard` is present.
* `LoginCard` occupies 2/3 of the space when displayed and appears as the first card on mobile devices.
* Main section
* Cards will take up 50% of the available space, and the stack will appear on small screens.
https://github.com/user-attachments/assets/7bfbe843-ef68-45bf-801e-4e1cdca3a705
- New `Portfolio` page component  
-  Renders the new `Portfolio` page under the `Portfolio` route  
-  Displays the appropriate layout in the `(app)/(home)/layout` when the feature toggle is on; the `Portfolio` page is the default page
- Unit tests to verify that the …
> feat: implement Portfolio page with base layout

- frontend/src/lib/components/common/CalloutWarning.svelte
- frontend/src/lib/components/neurons/AddUserToHotkeys.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Add a warning to the HW neuron creation form to inform the user about the consequences of not creating a hotkey for the new neuron.
- Add a static warning.
- Tested locally to confirm that the warning is displayed.
| 🌚 | 🌝 |
| <img width="622" alt="image" src="https://github.com/user-attachments/assets/1e83f3a9-7cf0-48d5-a4c3-df829847bc24" /> | <img width="615" alt="image" src="https://github.com/user-attachments/assets/368da8e6-2e94-4e34-a6b1-6dc235d65be4" /> | 
Not necessary.
> Add a warning HW neurons staking step 2

- frontend/src/lib/components/neurons/AddUserToHotkeys.svelte
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/page-objects/AddUserToHotkeys.page-object.ts
[A warning was recently added](https://github.com/dfinity/nns-dapp/pull/6076) to the HW neuron creation form to inform users about the consequences of not creating a hotkey for the new neuron. This warning is intended to be part of the periodic confirmation feature, which is not yet available. However, it was mistakenly added without being gated behind the feature flag.
- Move the warning behind a feature flag.
- Added.
Not necessary.
> Hide the banner behind the feature flag

- .github/workflows/checks.yml
We keep build artifacts for 3 days as specified [here](https://github.com/dfinity/nns-dapp/blob/b8e278aa4361df2abe0cd9cc7dda69b591cb73e5/.github/workflows/build.yml#L52).
We have a script for downloading build artifacts, which we test for the main branch.
This test fails if artifacts for the latest commit to the main branch have already expired, as can be seen [here](https://github.com/dfinity/nns-dapp/actions/runs/12592378031/job/35096899373?pr=6089).
Skip the test if the latest commit is too old.
This should be rare so hopefully on the next commit the test will run again.
The test passes with
```
```
not necessary
> Skip download test if last commit is too old

- frontend/src/lib/components/accounts/ImportTokenForm.svelte
- frontend/src/lib/components/common/InProgress.svelte
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/header/AccountSyncIndicator.svelte
- frontend/src/lib/components/ic/GetTokensModal.svelte
- frontend/src/lib/components/launchpad/ProjectCard.svelte
- frontend/src/lib/components/neuron-detail/NeuronSelectPercentage.svelte
- frontend/src/lib/components/project-detail/ParticipateButton.svelte
- frontend/src/lib/components/ui/Hash.svelte
- frontend/src/lib/components/ui/SkeletonCard.svelte
- frontend/src/lib/components/ui/SkeletonProjectCard.svelte
- frontend/src/lib/components/ui/SkeletonProposalCard.svelte
- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/modals/neurons/NnsStakeNeuronModal.svelte
- frontend/src/lib/modals/neurons/VotingHistoryModal.svelte
- frontend/src/lib/pages/NnsAccounts.svelte
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/pages/SnsNeurons.svelte
- frontend/src/lib/pages/Tokens.svelte
Through our codebase, we have multiple files where we import Gix dependencies on different lines. Since we don't use modules and always import everything from the root, I don't see any benefit in this duplication.
I used this script to find the files:
```
find ./src -type f -name "*.svelte" | while read -r file; do
count=$(grep -c 'from "@dfinity/gix-components"' "$file")
if [ "$count" -gt 1 ]; then
echo -e "Found ${count} gix-components imports in:${NC} $file"
fi
done
```
In the future, we can rely on ESLint or Prettier to prevent this issue:
```
"rules": {
"import/no-duplicates": "error"
}
```
```
{
"plugins": ["prettier-plugin-organize-imports"],
"organizeImportsSkipDestructiveCodeActions": true
}
```
-  Consolidates duplicate Gix imports into a single entry when duplicates are …
> refactor: consolidate Gix imports when duplicates are present

- frontend/src/lib/routes/Reporting.svelte
- frontend/src/routes/(app)/(nns)/reporting/+page.svelte
- frontend/src/tests/page-objects/ReportingRoute.page-object.ts
- frontend/src/tests/routes/app/reporting/page.spec.ts
We want to ensure that the correct page is displayed when the user is logged in, rather than the sign-in page.
- Added a `testId` to the Reporting page
- Unit test to verify that the `Reporting` page is displayed when signed in.
Not necessary
> test: clean up the tests for the Reporting route

- frontend/src/tests/e2e/design.spec.ts
A "$" was missing in the TVL replacement in https://github.com/dfinity/nns-dapp/pull/6093
I didn't catch this before because I had seen the test pass.
But the screenshots are only checked after all the tests finish by checking if any of the screenshot files were updated and I had forgotten about this.
Add the missing "$".
[This run](https://github.com/dfinity/nns-dapp/actions/runs/12600053915/job/35118450954?pr=6092) on [this PR](https://github.com/dfinity/nns-dapp/pull/6092) passes, including the screenshot check.
not necessary
> Add missing $ in TVL replacement

- frontend/src/lib/components/portfolio/NoTokensCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/lib/types/i18n.d.ts
We want to display a `Card` to users without tokens, directing them to the Tokens page.
Design comments:
- There are no mobile or tablet designs yet, so we will keep it simple for now.  
- The icon is slightly different from the design, with the colors being a darker. We need to check with the design team to see if this additional icon is necessary.  
- The button padding is also slightly different from the design, as we are using Gix styles.
Design reference:
Implementation:
Ticket [NNS1-3519](https://dfinity.atlassian.net/browse/NNS1-3519)
- New component `NoTokensCard` with a link to the `/tokens/` page.
- It will be added together with the logic for checking if the correct `Card` is displayed on the `Portfolio` page.
Not necessary.
Prev. PR: #6086 
[NNS1-3519]: …
> feat: add NoTokensCard component for empty tokens portfolio state

- .config/spellcheck.dic
- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api/governance.api.ts
- frontend/src/lib/constants/api.constants.ts
Neither neurons 27 and 28 used to known neurons but we present them in the UI as if they are known neurons.
Now 27 is an actual known neuron and 28 should no longer be a known neuron.
So neither needs special treatment anymore.
Stop injecting these 2 neurons into the known neurons results.
1. Tested manually.
2. Surprisingly no unit tests failed so apparently this was not tested.
> Remove hardcoded known neurons

- Cargo.lock
- Cargo.toml
- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/src/canisters/ledger.rs
Handles #6099
* Fixes the casting issue required since https://github.com/dfinity/ic/commit/b1f4339d483be025eb7a52c6ee997d22a8d1b382
* Run script `scripts/nns-dapp/test-exports --wasm nns-dapp_test.wasm.gz --update-golden --flavour test`
* See CI
> Update IC Cargo Dependencies to release-2025-01-03_03-07-base

- frontend/src/lib/components/portfolio/NoNeuronsCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/NoNeuronsCard.spec.ts
- frontend/src/tests/page-objects/NoNeuronsCard.page-object.ts
We want to display a Card to users without neurons, directing them to the Neurons page.
Design comments:
- There are no mobile or tablet designs yet, so we will keep it simple for now.
- The icon is different from the design. We need to check with the design team to see if this additional icon is necessary.
- The button padding is also slightly different from the design, as we are using Gix styles.
Design reference:
Implementation:
- New component `NoNeuronsCard` with a link to the /staking page.
- Unit test 
Not necessary.
Prev. PR: #6087
> feat: add NoNeuronsCard component for empty Neurons portfolio state

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
To support moving the fallback logic for canister creation to the frontend, we want to add a `block_index` field to the `NamedCanister` type stored in the canister.
See [this doc](https://docs.google.com/document/d/1hjMSTzjnVbU9Q4rJk233M3uNcKC-RLhme25nahHpTZg/edit?tab=t.0#heading=h.qtiuv2x3gsjy) for details.
In this PR we don't yet add the new field but change the logic to make it easier to add a new field.
1. Change the code in `attach_canister` to be more generic so it requires fewer changes when we add the `block_index` field to `NamedCanister`.
2. Change `rename_canister` so it changes only the name and keeps everything else from the canister. Currently "everything else" is just the canister ID but this is more resilient when we add more fields.
1. New unit tests were added to expand …
> Refactor attach_canister to prepare for block_index

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/modals/transaction/QrWizardModal.svelte
- frontend/src/tests/lib/modals/transaction/MockQRCodeReaderModal.svelte
- frontend/src/tests/lib/modals/transaction/QrWizardModal.spec.ts
Coinbase incorrectly uses `dfinity:` instead of `icp:` as the token symbol in the QR payment URI. We've asked them to fix this but so far they haven't. So we work around this by allowing `dfinity:` in place of `icp:`.
1. Don't reject the payment URL from the QR code if the prefix is `dfinity:` but the required token is ICP.
1. Added a `MockQRCodeReaderModal` component which has just a text input to fake what was scanned by the QR code reader.
2. Added missing unit tests using the `MockQRCodeReaderModal`.
3. Add unit tests for `dfinity:` prefix.
> NNS1-3527: Allow dfinity: prefix for ICP payments

- declarations/used_by_sns_aggregator/sns_governance/sns_governance.did
- declarations/used_by_sns_aggregator/sns_ledger/sns_ledger.did
- declarations/used_by_sns_aggregator/sns_root/sns_root.did
- declarations/used_by_sns_aggregator/sns_swap/sns_swap.did
- declarations/used_by_sns_aggregator/sns_wasm/sns_wasm.did
- dfx.json
Yesterday, [proposals candid bindings were updated](https://github.com/dfinity/nns-dapp/pull/6101) to IC release `release-2025-01-03_03-07-base`.
But today, the IC release marked "Latest" is `release-2024-12-06_03-16-sandboxes7k-secfix` which is based on an old release.
Instead of using that for the sns_aggregator bindings as it done in the [bot PR](https://github.com/dfinity/nns-dapp/pull/6107), let's use the same release as was used yesterday.
Ran
```
scripts/update_ic_commit --crate sns_aggregator --ic_commit release-2025-01-03_03-07-base
scripts/sns/aggregator/mk_nns_types.sh
```
as would be done by [.github/workflows/update-aggregator.yml](https://github.com/dfinity/nns-dapp/blob/main/.github/workflows/update-aggregator.yml).
not necessary
> Update sns_aggregator candid bindings

- frontend/src/lib/services/sns-accounts-balance.services.ts
- frontend/src/lib/services/wallet-uncertified-accounts.services.ts
- frontend/src/routes/(app)/(nns)/tokens/+page.svelte
The `excludeRootCanisterIds` parameter has not been used for a long time because we filter the canisters before passing them to the function.
Additionally, there is a leftover from [this change](https://github.com/dfinity/nns-dapp/pull/4444/files#diff-987b8deb5a94449419857056024e572fc65d6a43a9156cee3517fd3b723b2b3cR28), and `Promise.all` is no longer necessary since we only have one promise.
- Removes the `excludeRootCanisterIds` parameter and the filtering logic from both `uncertifiedLoadSnsesAccountsBalances` and `uncertifiedLoadAccountsBalance`
-  Removes `Promise.all` from `uncertifiedLoadSnsesAccountsBalances` as we only fetch SnsAccounts.
- The `excludeRootCanisterIds` feature was not tested so nothing to change.
Not necessary
> refactor: simplifies logic for uncertifiedLoadSnsesAccountsBalances and uncertifiedLoadAccountsBalance

- frontend/src/lib/components/neurons/LosingRewardsBanner.svelte
- frontend/src/lib/modals/neurons/LosingRewardNeuronsModal.svelte
- frontend/src/tests/lib/components/neurons/LosingRewardNeuronsModal.spec.ts
- frontend/src/tests/lib/components/neurons/LosingRewardsBanner.spec.ts
To reuse the “Losing Rewards” modal on the neuron details page, it should be possible to provide a specific neuron, rather than all inactive neurons.
- Added a neurons property to the LosingRewardNeuronsModal component.
- Provided and used the new prop instead of relying on the $soonLosingRewardNeuronsStore.
- Update LosingRewardNeuronsModal tests.
- Moved tests related to the soonLosingRewardNeuronsStore to LosingRewardsBanner.spec.
Not necessary.
> Refactor losing rewards modal

- rs/backend/nns-dapp.did
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/tests.rs
- rs/backend/src/accounts_store/tests.rs
- rs/backend/src/accounts_store/toy_data.rs
We want to move the fallback logic for canister creation to the frontend.
See [this doc](https://docs.google.com/document/d/1hjMSTzjnVbU9Q4rJk233M3uNcKC-RLhme25nahHpTZg/edit?tab=t.0#heading=h.qtiuv2x3gsjy) for details.
In this PR we add an optional `block_index` field to canister details (`AttachCanisterRequest` for setting and `CanisterDetails` for getting) and support storing the `block_index` in the backend canister.
The `block_index` refers to the index of the funding transaction for creating the canister.
1. Add `block_index` field to `CanisterDetails`, `AttachCanisterRequest` and `NamedCanister`.
2. In `attach_canister` store the `block_index` for new canisters or update the `block_index` for existing canister.
2. Tested manually that canister creation still …
> SECFIND-244: Add optional block_index to canister details

- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
- frontend/src/lib/components/neuron-detail/actions/ConfirmFollowingActionButton.svelte
- frontend/src/lib/components/neurons/LosingRewardsBanner.svelte
- frontend/src/lib/components/neurons/NnsLosingRewardsNeuronCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/LosingRewardNeuronsModal.svelte
- frontend/src/lib/modals/neurons/NnsNeuronModals.svelte
- frontend/src/lib/types/nns-neuron-detail.modal.ts
- frontend/src/tests/fakes/governance-api.fake.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronRewardStatusAction.spec.ts
- frontend/src/tests/lib/components/neurons/LosingRewardNeuronsModal.spec.ts
- frontend/src/tests/lib/components/neurons/NnsLosingRewardsNeuronCard.spec.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/page-objects/ConfirmFollowingActionButton.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronModals.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronRewardStatusAction.page-object.ts
To provide users with a clearer understanding of what they are confirming, we need to display the confirmation dialog, including the current following state, on the neuron detail page when they click ‘Confirm Following’ (using the same dialog as in the LosingRewardsBanner).
- Add `clickable` prop to NnsLosingRewardsNeuronCard to support not clickable neuron cards.
- Add `LosingRewardNeuronsModal` to available NNS neuron modals.
- Display `LosingRewardNeuronsModal` instead of calling `refreshVotingPower`.
- Minor text changes.
- Move "call refreshVotingPower" test from `NnsNeuronRewardStatusAction.spec` to `NnsNeuronDetail.spec`.
- Tested locally that it works.
https://github.com/user-attachments/assets/0a4b778f-5a98-4e5a-a58d-68ebeadc348f
Not necessary.
> Neuron confirm following confirmation

- frontend/src/lib/utils/test-support.utils.ts
- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/utils/ckbtc.utils.spec.ts
- frontend/src/tests/utils/mockable-constants.test-utils.ts
- frontend/vitest.setup.ts
Our unit tests have always been quite brittle because we need to remember to clean up all global state between each test.
Often tests fail when run in a different order because one test accidentally depends on state left behind by other tests.
This has improved a lot now that we always [reset all stores](https://github.com/dfinity/nns-dapp/pull/5724) and [restore all mocks](https://github.com/dfinity/nns-dapp/pull/5788), but there are still other cleanups that need to be performed in tests.
This PR proposes a generic way of registering a cleanup in the file that defines the thing that needs to be cleaned up, instead of in every test. As a proof of concept, it is then used to automatically call `resetMockedConstants();` in every test that (transitively) imports …
> registerCleanupForTesting

- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
When the user is not authenticated, we display the `NoTokensCards` and the `NoNeuronsCard`.
Design discrepancies:
* The design shows these cards with disabled links. Since there is no semantic meaning for a disabled link, I will leave it as is until we determine whether to replace the link with a disabled button.
* Adds new methods to the Portfolio page object
* Added unit test
Not necessary.
> test(portfolio): adds tests for unauthenticated state

- frontend/src/tests/fakes/sns-governance-api.fake.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/utils/console.test-utils.ts
These 2 tests in `SnsProposalDetail.spec.ts`:
```
"should navigate to the proposal from the previous Sns"
"should navigate to the proposal from the next Sns"
```
are currently logging errors like this:
```
{
certified: false,
strategy: 'query_and_update',
error: t [Error]: No proposal for given proposalId 19
at Object.queryProposal (/Users/dskloet/dev/nns-dapp/tree4/frontend/src/tests/fakes/sns-governance-api.fake.ts:327:11)
at fn (/Users/dskloet/dev/nns-dapp/tree4/frontend/src/tests/utils/module.test-utils.ts:158:33)
at wrapMaybePaused (/Users/dskloet/dev/nns-dapp/tree4/frontend/src/tests/utils/module.test-utils.ts:140:20)
at Module.pausableFunctions.<computed> (/Users/dskloet/dev/nns-dapp/tree4/frontend/src/tests/utils/module.test-utils.ts:157:14)
at Module.mockCall …
```
> Fix errors logged in SnsProposalDetail.spec.ts

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
The `Portfolio` page features a card displaying the total assets owned by the user. In this initial iteration, we only showcase the Tokens. A follow-up PR will introduce the concept of Neurons. A final PR will provide both Tokens and Neurons from the `Portfolio` route to the page.
Design discrepancies:
- The `UsdValueBanner` is used to display the assets. We will re-evaluate this with the design team in a later iteration.
- Missing title
- Icon slot should not be displayed
- Icp Conversion Rate should not be displayed
- Spacing, font size and card styles are different
Design reference:
Implementation:
- Adds `UsdValueBanner` to display total assets.  
- Exposes `totalTokensBalanceInUsd` prop from the `Portfolio` page to manage tokens.  
- Adds logic to display `NoTokensCard` when the …
> feat(portfolio): implement total assets calculation for tokens

- frontend/src/lib/api/canisters.api.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
We want to recover from interrupted canister creation in the frontend code.
To do this we should be able to notify the CMC and attach a canister without first making a transfer, as the transfer has already happened before the process got interrupted.
See [this doc](https://docs.google.com/document/d/1hjMSTzjnVbU9Q4rJk233M3uNcKC-RLhme25nahHpTZg/edit?tab=t.0#heading=h.qtiuv2x3gsjy) for details.
1. Add `notifyAndAttachCanister` which can be used to recover canister creation based on an existing ICP transfer.
2. Cleaned up the existing test on which the new test was based, by using fake time instead of stubbing out `setTimeout` and not mocking `console.log` as nothing gets logged and this just makes debugging harder.
3. Tested manually in a branch with the end-to-end …
> SECFIND-244: Add notifyAndAttachCanister to canisters API

- frontend/src/lib/components/proposal-detail/NnsProposal.svelte
- frontend/src/lib/components/proposals/ActionableSnses.svelte
- frontend/src/lib/derived/actionable-proposals.derived.ts
- frontend/src/lib/derived/actionable-universes.derived.ts
- frontend/src/lib/pages/SnsProposalDetail.svelte
- frontend/src/tests/lib/derived/actionable-proposals.derived.spec.ts
- frontend/src/tests/lib/derived/actionable-universes.derived.spec.ts
We want to sort the selectable universes based on their number of actionable proposals.
For this `selectable-universes.derived.ts` needs to depend on `actionableProposalCountStore` from `actionable-proposals.derived.ts`.
But this causes a circular dependency because of other derived stores in `actionable-proposals.derived.ts` which already depend on `selectable-universes.derived.ts`.
1. Move the derived stores in `actionable-proposals.derived.ts` that depend on `selectable-universes.derived.ts` to a new file named `actionable-universes.derived.ts`.
2. Update imports.
1. Move tests for the moved stores to a corresponding test file.
not necessary
> NNS1-3504: Split actionable-proposals.derived.ts

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
The `Portfolio` page features a card that displays the total assets owned by the user. In this second iteration, Neurons are used to calculate wealth. A final PR will provide both Tokens and Neurons from the `Portfolio` route to the page.
The same design discrepancies mentioned in #6121 remain.
- Exposes the `tableProjects` prop on the `Portfolio` page to receive the list of all projects and the total amount staked.
- Adds logic to display the `NoNeuronsCard` when the neurons balance is zero.  
- Unit test to verify the presence of the `NoNeuronsCard` based on the neurons balance.  
- Unit test to confirm that a primary action appears in the `NoNeuronsCard` when the token balance exceeds zero.
- Unit test to ensure that the `UsdValueBanner` displays the correct value based on the token …
> feat(portfolio): implement total staked calculation for projects

- frontend/src/lib/services/canisters.services.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
We want to recover from interrupted canister creation in the frontend code.
We want to do this by detecting canister creation funding transactions without a corresponding canister.
See [this doc](https://docs.google.com/document/d/1hjMSTzjnVbU9Q4rJk233M3uNcKC-RLhme25nahHpTZg/edit?tab=t.0#heading=h.qtiuv2x3gsjy) for details.
This PR adds a service function to do this, but does not yet use it.
1. Add `notifyAndAttachCanisterIfNeeded` which can be passed a list of transactions and a list of canisters. If the transactions contain a canister creation funding transaction that does not correspond to an existing canister, it will try to recover the canister creation process.
2. Tested manually in a branch with the end-to-end solution.
not yet
> SECFIND-244: Add notifyAndAttachCanisterIfNeeded service

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
Currently, the NNS dapp backend canister monitors every transaction on the ICP ledger in order to catch canister creation funding transactions for which the notify+attach process might have been interrupted.
We want to remove this logic from the backend and perform it in the frontend in order to simplify the responsibilities of the backend canister.
In this PR we check if loaded transactions contain any canister creation funding transactions for which there is no corresponding canister.
This is done if the user visits the wallet page after visiting the canisters page.
Since it should be rare for canister creation to be interrupted, we assume that when it happens, a user will look around for their canister and eventually trigger the recovery process.
1. In `NnsWallet`, if the canisters are …
> Recover from interrupted canister creation in frontend

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/derived/selectable-universes.derived.ts
- frontend/src/tests/lib/derived/selectable-universes.derived.spec.ts
- frontend/src/tests/lib/pages/ActionableProposals.spec.ts
On the voting page we want to sort the universes (both in the selector and in the actionable proposals) based on the number of actionably proposals or otherwise alphabetically.
Both the selector and the actionable proposals sections are rendered based on `selectableUniversesStore`.
(This store is also used for other things, such as [finding the currently selected universe](https://github.com/dfinity/nns-dapp/blob/58b8d349c2912b678f69b1060342430f6992fb12/frontend/src/lib/components/accounts/IcrcWalletPage.svelte#L166), which is why it can still also contain non-voting universes such as ckBTC.)
1. Sort `selectableUniversesStore` based on actionable proposal count and title.
1. Simplify the existing tests for `selectableUniversesStore`. Because of the re-ordering, the tests were confusing in …
> NNS1-3504: Sort selectable universes by actionable proposals

- .github/repo_policies/BOT_APPROVED_FILES
#6041 defined a list of approved bot files. #6134 is failing because `root-toolchain.toml` is not allowed.
Handles: #6134
Adds `rust-toolchain.toml` to `.github/repo_policies/BOT_APPROVED_FILES`.
- Once merged, it should be possible to rebase #6134 and merge
Not necessary
> chore(ci): add rust-toolchain configuration to BOT_APPROVED_FILES

- frontend/scripts/build.csp.mjs
Based on suggestion https://github.com/dfinity/oisy-wallet/pull/4165#pullrequestreview-2541785546 :
`const svelteKitStartScript = /(<script>)([\s\S]*?)(<\/script>)/gm;`
This regular expression does not match upper case <SCRIPT> tags.
It is possible to match some single HTML tags using regular expressions (parsing general HTML using regular expressions is impossible). However, if the regular expression is not written well it might be possible to circumvent it, which can lead to cross-site scripting or other security issues.
Some of these mistakes are caused by browsers having very forgiving HTML parsers, and will often render invalid HTML containing syntax errors. Regular expressions that attempt to match HTML should also recognize tags containing such syntax errors.
To fix the problem, we …
> fix(build): Bad HTML filtering regexp

- frontend/src/tests/lib/components/canister-detail/CanisterPageHeading.spec.ts
- frontend/src/tests/utils/actions.test-utils.ts
- frontend/src/tests/utils/custom-event.test-utils.spec.ts
- frontend/src/tests/utils/custom-event.test-utils.ts
- frontend/vitest.setup.ts
`CustomEvent.detail` and `CustomEvent.bubbles` are getters rather than properties.
Because of this, they are not taken into account when comparing events in unit tests.
Concretely, this means that, for example, if we change `Send` to `Receive` in [this test](https://github.com/dfinity/nns-dapp/blob/2898582db3a21587755960ee7da580a74a163587/frontend/src/tests/lib/components/tokens/TokensTable.spec.ts#L334), the test doesn't fail.
1. Create `CustomEventForTesting` which exposes `.detail` and `.bubbles` as props.
2. Stub `CustomEvent` with `CustomEventForTesting` in `vitest.setup.ts`.
1. Added a unit test that demonstrates the bad behavior of `CustomEvent`.
2. Added a unit test that shows that the problem no longer appears unless we `vi.unstubAllGlobals();`
3. Verified that without my change …
> Add CustomEventForTesting for proper event comparison

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/universe/SelectUniverseList.svelte
- frontend/src/lib/constants/canister-ids.constants.ts
- frontend/src/lib/stores/sns-aggregator.store.ts
- frontend/src/tests/lib/components/universe/SelectUniverseList.spec.ts
The Cycles-Transfer-Station SNS was renamed to `----` and made unusable by impossible proposal fees and transaction fees.
To let people see their former balance and neurons we are keeping it on the Tokens and Staking pages for now but we're hiding it from the Voting page.
1. Move `CYCLES_TRANSFER_STATION_ROOT_CANISTER_ID` from `frontend/src/lib/stores/sns-aggregator.store.ts` to `frontend/src/lib/constants/canister-ids.constants.ts`.
2. Hide the former "Cycles-Transfer-Station" SNS from the `SelectUniverseList` which (since the tokens/neurons tables UIs) is only used on the Voting page.
1. Simplify test setup by using `setSnsProjects` instead of mocking `snsProjectsCommittedStore`.
2. Add a unit test with a project with the same root canister ID as "Cycles-Transfer-Station".
3. Tested …
> NNS1-3504: Hide Cycle Transfer Station from Voting page

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
- frontend/src/tests/page-objects/PortfolioRoute.page-object.ts
- frontend/src/tests/routes/app/portfolio/page.spec.ts
The `Portfolio` route needs to load the balances for NNS, ICRC, ckBTC, and SNS. This information, along with the projects, is passed down to the `Portfolio` page, which displays it in various cards. Since we will show their value in USD, we also need to load information from `IcpSwap`.
This first PR loads all the tokens. A subsequent PR will handle the Projects.
[NNS1-3520](https://dfinity.atlassian.net/browse/NNS1-3520)
Note: UX/UI improvements will be done later. Eg: loading states, padding, typography, ...
- Resets the `resetBalanceLoading` set upon navigation to request accounts only once per page.
- Loads  ICRC, ckBTC, and SNS accounts
- Loads IcpSwapTickers
- Unit tests to verify that all data is fetched.  
- Unit test to render the Portfolio page with the correct total assets value …
> feat(portfolio): implement token data loading in route

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/routes/app/portfolio/page.spec.ts
Follows up on #6139 by loading the project information and passing it to the portfolio page.
[NNS1-3520](https://dfinity.atlassian.net/browse/NNS1-3520)
- Loads `tableProjects` and passes it down to the Portfolio page
- Extends Portfolio route unit test with Projects stake. 
Not necessary
[NNS1-3520]: https://dfinity.atlassian.net/browse/NNS1-3520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portfolio): implement projects data loading in route

- .github/repo_policies/BOT_APPROVED_FILES
#6041 defined a list of approved bot files. #6134 is failing because `Cargo.toml` is not allowed.
Handles: #6134
Adds `Cargo.toml` to `.github/repo_policies/BOT_APPROVED_FILES`.
- Once merged, it should be possible to rebase #6148 and merge
Not necessary
> chore(ci): add Cargo.toml configuration to BOT_APPROVED_FILES

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
The Portfolio page displays a list of tokens that behaves differently based on specific rules.
The `getTopTokens` function encapsulates the following logic:  
- It should return up to four tokens.  
- When the user is logged out, the function returns the top four tokens, listing ICP first, followed by the cK tokens.  
- When the user is logged in, it returns the tokens with the highest `balanceInUsd`. If ICP is present, it should be the first item in the list.
-  Added a new descending comparator, `compareTokensByUsdBalance`
-  Introduced a new utility, `getTopTokens`
-  Created unit tests for `getTopTokens`
-  [ ] Add an entry to the changelog (if necessary). Not necessary.
> feat(portfolio):  add getTopTokens utility for TokensCard

- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Use a shorter duration format for the ‘missing rewards’ tag to improve the UI.
Samples:
- 7d 23h — 7 days to confirm
- 7d 11h — 7 days to confirm
- 7d 1h — 7 days to confirm
- 6d 2h — 6 days, 2 hours to confirm
- Update tag text logic.
- Added.
Not necessary.
> Missing rewards tag hours

- frontend/src/lib/components/neuron-detail/NnsNeuronVotingPowerSection.svelte
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronVotingPowerSection.spec.ts
- frontend/src/tests/page-objects/NnsNeuronVotingPowerSection.page-object.ts
To highlight missing rewards, we display voting power in red when rewards are reduced.
- Update styling when deciding vp is less than potential.
- Added.
Not necessary.
> Display voting power in red when rewards are reduced

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
- Calls `getTopTokens` on the Portfolio page to retrieve the list of top tokens based on rules #6153.  
-  Renders the `TokensCard` on the Portfolio page with the top tokens.
- Unit test to verify the presence of the component when the user has tokens.  
-  Unit test to check the contents of the TokensCards when the user has tokens.
Not necessary
> feat(portfolio): integrate Tokens card into Portfolio page

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
The Portfolio page displays a list of projects that behaves differently based on specific rules.
The `getTopProjects` function encapsulates the following logic:  
- It should return up to four projects.  
- When the user is logged out, the function returns the top four projects, listing ICP first, followed by three sorted by name. This is similar to how we do it in the Staking page when the user is logged out.
- When the user is logged in, it returns the projects with the highest `stakeInUsd`. If ICP is present, it should be the first item in the list.
-  Added a new descending comparator, `compareProjectsByUsdBalance`
- Exported `compareIcpFirst` and `compareByProjectTitle` from _staking.utils_ to build the sorting comparator.
-  Introduced a new utility, `getTopProjects`
-  Created unit …
> feat(portfolio): new utility to get top projects for the ProjectsCard

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/routes/app/portfolio/page.spec.ts
On the Portfolio page, we want to display a list of our important tokens: ICP, ckBTC, ckETH, and ckUSDC.
- The portfolio route loads `tokensListVisitorsStore` for use when the user is not signed in.  
- The portfolio page displays the `NoTokensPage` when the user is signed in but has no tokens.
- Unit tests for the route to verify that the tokens are displayed when the user is not signed in.  
-  Unit tests for the page to ensure that the correct card is displayed based on the user's sign-in status.
Not necessary
> feat(portfolio): load visitor tokens for unauthenticated state

- frontend/src/lib/components/portfolio/ProjectsCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/ProjectsCard.spec.ts
- frontend/src/tests/page-objects/ProjectsCard.page-object.ts
The `ProjectsCard` component on the Portfolio page displays the total USD amount of staked in projects and a list of up to four projects. If there is a difference of 1 or more with the number of top Tokens it shows a information message.
Related PRs:
- Get top tokens #6159 
- Adds the `ProjectsCard` component.
- Unit tests for the component  
-  New page object for the component 
- Manually tested in [E2E environment](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Not necessary
> feat(portfolio): implement ProjectsCard component 

- frontend/src/lib/components/ui/IcpExchangeRate.svelte
- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/components/ui/IcpExchangeRate.spec.ts
- frontend/src/tests/lib/components/ui/UsdValueBanner.spec.ts
- frontend/src/tests/page-objects/IcpExchangeRate.page-object.ts
- frontend/src/tests/page-objects/UsdValueBanner.page-object.ts
Extracts the Icp exchange rate section from the `UsdValueBanner` component for reuse in other components, such as the Portfolio `TotalAssetsCard`.
- New `IcpExchangeRate` component.
- Introduces `IcpExchangeRate` in `UsdValueBanner` 
- Unit tests for the new component
- Updates existing tests
Not necessary
> refactor(ui): extract IcpExchangeRate into standalone component

- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/lib/components/ui/UsdValueHeadless.svelte
- frontend/src/tests/lib/components/ui/UsdValueHeadless.spec.ts
- frontend/src/tests/lib/components/ui/UsdValueHeadlessTest.svelte
- frontend/src/tests/page-objects/UsdValueHeadless.page-object.ts
Extract the logic from the `UsdValueBanner` component into a headless component for use with different UIs. This will be utilized by the total assets card on the Portfolio page.
- New `UsdValueHeadless` component.
- Introduces `UsdValueHeadless` in `UsdValueBanner` 
- Unit tests for the new component
- Updates existing tests
Not necessary
> refactor(ui): extract UsdValueBanner logic into headless component

- frontend/src/lib/derived/debug.derived.ts
- frontend/src/lib/services/app.services.ts
- frontend/src/lib/services/network-economics.services.ts
- frontend/src/lib/stores/network-economics.store.ts
- frontend/src/tests/lib/services/network-economics.services.spec.ts
- frontend/src/tests/lib/stores/network-economics.store.spec.ts
- frontend/src/tests/mocks/network-economics.mock.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, they may change in the future. Therefore, we want to retrieve them from the API. In this PR, we add the service and store to use them in the following PRs.
- New `networkEconomicsStore` store.
- New `loadNetworkEconomicsParameters` service (intentionally no error toasts, because this doesn't block more important activities).
- Added.
Not necessary.
> Get network economics service

- frontend/src/lib/components/portfolio/TotalAssetsCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/TotalAssetsCard.spec.ts
- frontend/src/tests/page-objects/TotalAssetsCard.page-object.ts
We want to display the total value of the user's portfolio on the Portfolio page.
- Adds the `TotalAssetsCard` component.
- Unit tests for the component  
-  New page object for the component 
- Manually tested in [E2E environment](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Not necessary
> feat(portfolio): implement TotalAssetsCard component

- frontend/src/lib/services/app.services.ts
- frontend/src/tests/lib/services/app.services.spec.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, they may change in the future. Therefore, we want to retrieve them from the API. In this PR, we load the network parameters on app init.
- Load network parameters on app init.
- Added.
Not necessary.
> Load network economics

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
We want to show the top staked tokens card in the Portfolio page.
- Calls `getTopStakedTokens` on the Portfolio page to retrieve the list of top staked tokens  
- Renders the `StakedTokensCard` on the Portfolio page with the top staked tokens.
- Unit test to verify the presence of the component when the user has staked tokens.  
- Unit test to check the contents of the `StakeTokensCard` when the user has tokens.
- Unit test to check that the `StakedTokensCard` shows an informational row when it has less items than the `HeltTokensCard`
Not necessary
> feat(portfolio): integrate staked tokens card into Portfolio page

- frontend/src/lib/components/ui/IcpExchangeRate.svelte
The `display: none` rule wasn't working because, when nested inside `.exchange-rate`, Svelte's CSS scoping created a more specific selector. This interfered with the media query's ability to toggle the visibility of utility classes effectively.
- Fix the style by moving it out from the parents scope
Not necessary
> fix(styles): IcpExchangeRate specificity conflict

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
Determines whether to display an info row in a card based on specific rules. The criteria for showing the info row are as follows:  
1. When the other card has more tokens than the current card.  
2. When the other card is empty (has 0 tokens).  
3. When both cards have fewer than 3 tokens (for visual balance).
- New `shouldShowInfoRow` utility
- Unit tests
Not necessary
> feat(portfolio): add info row visibility utility

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
- frontend/src/tests/routes/app/portfolio/page.spec.ts
We want to display the total value of user assets on the Portfolio page. The value will be shown in USD and ICP, along with a tooltip to calculate the portfolio's value in ICP.
- Adds `TotalAssetsCard` to the Portfolio page
- Adds unit tests to the Portfolio page to ensure the component renders correctly.  
- Adds unit tests to the Portfolio route to verify that all components render as expected.
Not necessary
> feat(portfolio): integrate total assets card into the Portfolio page

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/components/portfolio/HeldTokensCard.spec.ts
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
There is a relationship between the `HeldTokensCard` and the `StakedTokensCard`. Based on this relationship, we display or hide an additional row with a static message to achieve visual balance between the heights of the cards. 
The logic for this can be found in #6181. 
Live demo can be found [here](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network)
- Updates `HeldTokensCard` to receive the number of staked tokens and determine whether to display the `InfoRow`.
- Updates the Portfolio page to provide the number of staked tokens to `HeldTokens`.
- Updates `StakedTokensCard` to utilize a new utility function for deciding whether to display the `InfoRow`.
- Includes some minor CSS changes.
- Update tests based on the new logic
Not necessary
> feat(portfolio): implement token cards relationship management

- frontend/src/lib/derived/network-economics.derived.ts
- frontend/src/tests/lib/derived/network-economics.derived.spec.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, they may change in the future. Therefore, we want to retrieve them from the API. 
In this PR, we add derived stores to retrieve values related to periodic confirmation.
- New strores.
- Added.
Not necessary.
> Voting power economics derived stores

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/reporting/ReportingDateRangeSelector.svelte
On small screens, the date range options are displayed in a row, but they do not look neat. We want to stack them on small screens.
Before:
https://github.com/user-attachments/assets/5a00ef25-9148-48d0-bed0-bb1d75ec6ee5
After:
https://github.com/user-attachments/assets/e40d0354-8284-4e75-bb65-b327f240f08e
- Changes the layout of the radio options from a row to a column.
- Manually tested
> fix(ui): stack date range options on small screens in the Reporting page

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/lib/components/portfolio/TokensCardHeader.svelte
The header of the `HeldTokensCard` and `StakedTokensCard` can be extracted into a small component to simplify their implementations. Additionally, this is useful because the designs require a special type of link for mobile viewports.
[Design](https://www.figma.com/design/3P3MBRLwECLuxN5b5iuWiA/NNS-Portfolio-Overview?node-id=111-77539&t=deMCSzrYqw1lOvRL-4)
https://github.com/user-attachments/assets/de13179f-d3c2-481d-a89d-8ddc3de2787d
- Extracts common markup and styles from the `HeldTokensCard` and `StakedTokensCard` into this new component.
- Overrides mobile styles for the `button` and `secondary` classes to make it look like the design.
Not necessary
> refactor(portfolio): extract TokensCard header into standalone component

- frontend/src/lib/canisters/ic-management/ic-management.canister.ts
- frontend/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
- frontend/src/lib/services/app.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/utils.services.ts
- frontend/src/lib/stores/sns.store.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/mocks/nns-dapp.canister.mock.ts
- frontend/src/tests/mocks/sns-response.mock.ts
- frontend/src/tests/page-objects/IcpExchangeRate.page-object.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
- frontend/src/tests/page-objects/TokensTable.page-object.ts
- frontend/src/tests/page-objects/UsdValueBanner.page-object.ts
- scripts/check-relative-imports
We don't want to have relative imports in our codebase. The reason is to avoid issues related to how different tools sort Svelte imports. 
The initial version of the script was not checking for local relative imports `./` 
Follow up of #6146
- Change the regex to match files to `.`
- Fix existing cases
- Run `./scripts/fmt-frontend` to sort imports based on rules
- The [first commit](https://github.com/dfinity/nns-dapp/pull/6193/commits/ae1bec126f2137e119496ed894167f7d4bff2994) [highlights previously unnoticed issues](https://github.com/dfinity/nns-dapp/actions/runs/12868009402/job/35873823334?pr=6193). 
- The [second commit](https://github.com/dfinity/nns-dapp/pull/6193/commits/885790f6f83d5f3d2648493fd8e3508bda8558cb) addresses those issues -> green pipeline
Not necessary
> fix(scripts): enhance import checker to include local imports

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/tests/lib/components/portfolio/HeldTokensCard.spec.ts
- frontend/src/tests/lib/components/portfolio/StakedTokensCard.spec.ts
We want to display two digits of precision for the native price of a token, similar to how it appears in the Tokens and Staging routes.
- Calls `formatTokenV2` with `detailed: false` to round the amount to the nearest digit.
- Adds a test to verify that rounding is applied correctly.
Not necessary
> fix(portfolio): change native token price precision to 2 digits

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/accounts_store.rs
Creating a canister takes 3 steps:
1. Transferring ICP to the CMC.
2. Notifying the CMC to create the canister.
3. Attaching the canister to the user account on the NNS dapp.
If the process is interrupted after step 1 or 2, the user might end up without ICP and without canister.
To avoid this we have code in the nns-dapp backend canister to detect transactions from step 1 and perform step 2 and 3.
Since https://github.com/dfinity/nns-dapp/pull/6132 we do this in the frontend so we no longer need to do it in the backend.
This PR stops doing this in the backend.
This allows a lot of code to be removed from the backend canister. This will be done in subsequent PRs.
1. Stop pushing `CreateCanisterV2` to `multi_part_transactions_processor` when a canister creation funding transaction is …
> Remove canister creation fallback from backend canister

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/LoginCard.svelte
- frontend/src/lib/components/portfolio/NoStakedTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
We have new icons for the Portfolio page:
- Updated the icons in the header of the `HeldTokensCard` and `StakedTokensCard`.  
- Updated the icon in the `LoginCard`.
Not necessary
> feat(portfolio): update token cards with new icons

- frontend/src/lib/modals/neurons/UpdateVotingPowerRefreshedModal.svelte
- frontend/src/tests/e2e/periodic.spec.ts
- frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronModals.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronTestnetFunctionsCard.page-object.ts
- frontend/src/tests/page-objects/UpdateVotingPowerRefreshedModal.page-object.ts
To ensure that the user can confirm following and does not miss voting rewards, we have added an end-to-end (e2e) test that attempts to confirm the following of an inactive neuron.
- Update page objects.
- Added an e2e test.
- Yes
Not necessary.
> Periodic confirmation e2e test

- scripts/check-relative-imports
We want to avoid relative imports in our codebase to prevent issues with how different tools sort Svelte imports. 
Currently, there are exceptions for `@import` and `@use` declarations, but these are unnecessary since the grep command only searches for JS/TS declarations.
Follow up on #6146.
- Removes unnecessary checks for SCSS declarations.
- Should pass as before
Not necessary
> refactor(scripts): remove redundant import validation checks

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
We don't want to display the `CYCLES_TRANSFER_STATION` project in either of the TokenCards shown on the Portfolio page.
- Update `getTopHeldTokens` to exclude the `CYCLES_TRANSFER_STATION` project.  
- Update `getTopStakedTokens` to exclude the `CYCLES_TRANSFER_STATION` project.
- Updated tests to check that filtering is being applied
Not necessary
> refactor(portfolio): exclude CTS project from token cards

- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
On very small screens, the staked balance column header spans two lines, and the text is not aligned to the right like the rest of the column.
Before:
After:
- Align text to the right in small screens
Not necessary
> styles(portfolio): align text right HeldTokensCard on mobile screens

- frontend/src/lib/types/staking.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
We want users to have cue that their tokens are loading. The `UserToken` value already has this functionality, represented by `UserTokenLoading`. The goal is to implement a similar feature for the `ProjectTable`. 
In this initial iteration, I'm adding a new property instead of changing the existing `stake` property to minimize the impacted area.
Relates to #5199
- Added a new property `isStakeLoading`, which is `true` while the neurons have not yet loaded.
- Updated tests to check the new value when neurons have not loaded yet
Not necessary
> feat(portfolio): add a stake loading state field to ProjectTable

- frontend/src/lib/components/portfolio/SkeletonTokensCard.svelte
Some users on certain networks may experience high loading times for their assets. We want to display loading states during this period.
This first PR introduces a new skeleton component specifically for the Portfolio page. We already have a `SkeletonCard`, but since this is the entry point for the application, we want it to resemble the final cards as closely as possible.
https://github.com/user-attachments/assets/3c6126b2-8b63-42c0-9437-4de68e78310c
- New skeleton component for the Portfolio page.
- Not necessary, as this is a pure UI component. Future PRs will integrate it into the Portfolio page, where we will test its visibility when needed.
Not necessary
> feat(portfolio):  implements SkeletonTokensCard component

- frontend/playwright.config.ts
Chrome end-to-end tests have become very flaky [(example failure](https://github.com/dfinity/nns-dapp/actions/runs/12892772450/job/35947946500)).
I believe it's because GitHub has update Chrome on some of its runners to a version that no longer supports the headless mode used by the version of Playwright we use.
```
- [pid=12021][err] [0121/175345.791888:WARNING:chrome_main_linux.cc(80)] Read channel stable from /opt/google/chrome/CHROME_VERSION_EXTRA
- [pid=12021][err] Old Headless mode has been removed from the Chrome binary. Please use the new Headless mode (https://developer.chrome.com/docs/chromium/new-headless) or the chrome-headless-shell which is a standalone implementation of the old Headless mode (https://developer.chrome.com/blog/chrome-headless-shell).
- [pid=12021][err] 
``` …
> Disable Chrome Playwright tests

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/mockable.constants.ts
We want to re-enable the update calls that are disabled via FORCE_CALL_STRATEGY.
Because this may result in higher subnet load, we have first rolled it out to 10% of sessions in [this PR](https://github.com/dfinity/nns-dapp/pull/5593).
Just before that rollout, subnets got overloaded for unrelated reasons, but are now back to normal.
So we will proceed to 30% to see if it has any effect on subnet load.
1. Initialize `FORCE_CALL_STRATEGY` on app load, to `"query"` 70% of the time and to `undefined` 30% of the time.
Not tested.
> FOLLOW-1337: Disable FORCE_CALL_STRATEGY for 30% of sessions

- frontend/src/lib/components/portfolio/TotalAssetsCard.svelte
- frontend/src/tests/lib/components/portfolio/TotalAssetsCard.spec.ts
- frontend/src/tests/page-objects/TotalAssetsCard.page-object.ts
We want to inform users that something is loading by displaying a spinner in the asset cards.
https://github.com/user-attachments/assets/22743f6c-2df8-4a9d-86d5-d651713eda01
- Added a prop `isLoading` to control the display of the `Spinner`.  
- Updated styles to ensure the `Spinner` fits properly.
- Unit tests to verify that the `Spinner` displays correctly based on the new prop.
Not necessary.
> feat(portfolio): adds a loading state to the total assets card

- frontend/src/lib/services/ckbtc-info.services.ts
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/services/neurons.services.ts
- frontend/src/lib/services/public/sns-proposals.services.ts
- frontend/src/lib/services/utils.services.ts
- frontend/src/tests/lib/services/utils.services.spec.ts
While debugging end-to-end test flakiness I had difficulty understanding which calls were being made because not all calls to `queryAndUpdate` define a log message.
1. Make the `logMessage` parameter of `queryAndUpdate` non-optional.
2. Specify a log message for all calls missing a log message.
1. Update the tests to specify a log message in every call.
not necessary
> Make logMessage mandatory in queryAndUpdate

- frontend/src/lib/modals/neurons/UpdateVotingPowerRefreshedModal.svelte
`finally` was mistakenly used instead of `catch`, which doesn't do anything.
Note: no other instances of incorrect `finally` usage were found.
Replace `finally` with `catch`. Implicitly tested by the [e2e test](https://github.com/dfinity/nns-dapp/blob/472b179d3515fed65c4056abac9a76247d8745d7/frontend/src/tests/e2e/periodic.spec.ts).
- No tests, because this is a test feature.
Not necessary.
> Fix the inappropriate usage of finally

- frontend/src/lib/api/governace-test.api.ts
- frontend/src/lib/services/nns-neurons-dev.services.ts
The periodic confirmation end-to-end test is currently flaky. After a lot of investigation, I found the following:
1. We have a neurons cache in `api-services/governance.api-service.ts`. This cache only caches certified  responses ([link](https://github.com/dfinity/nns-dapp/blob/472b179d3515fed65c4056abac9a76247d8745d7/frontend/src/lib/api-services/governance.api-service.ts#L144)).
2. `updateNeuron`, uses a [test API](https://github.com/dfinity/nns-dapp/blob/472b179d3515fed65c4056abac9a76247d8745d7/frontend/src/lib/api/governace-test.api.ts#L19), which doesn't invalidate the above cache.
3. `listNeurons` by default makes a [query call](https://github.com/dfinity/nns-dapp/blob/472b179d3515fed65c4056abac9a76247d8745d7/frontend/src/lib/services/neurons.services.ts#L287), except for [30 …
> Fix periodic e2e test flakiness

- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/schema/proxy/migration.rs
- rs/backend/src/main.rs
Now that NNS dapp has stopped tracking ICP transactions, the only other thing that's done in the heartbeat is to try to make progress on the accounts migration. The accounts migration finished a long time ago so we should remove the entire heartbeat.
This PR removes the heartbeat from the nns-dapp canister.
The rest of the migration code should be cleaned up in separate PRs.
1. Remove `canister_heartbeat`.
2. Mark unused functions with `#[allow(dead_code)]`.
1. Existing tests should pass.
2. Updated golden exports with
```
scripts/nns-dapp/test-exports --wasm nns-dapp_production.wasm.gz --update-golden --flavour production
scripts/nns-dapp/test-exports --wasm nns-dapp_test.wasm.gz --update-golden --flavour test
```
not necessary
> Remove heartbeat from nns-dapp canister

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/nns-dapp.did
- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
- rs/backend/src/multi_part_transactions_processor.rs
- rs/backend/src/perf.rs
- rs/backend/src/stats.rs
- scripts/nns-dapp/e2e-test-metrics-present.keys
- scripts/nns-dapp/migration-test.canister
Now that the nns-dapp canister no longer process transactions for the purpose of recovering from neuron staking/top-up and canister creation/top-up, a number of exports stats have become irrelevant:
1. `block_height_synced_up_to`: we are no longer syncing any blocks
2. `seconds_since_last_ledger_sync`: same
3. `neurons_topped_up_count`: topping up neurons only happens in the frontend now
4. `transactions_to_process_queue_length`: we no longer have a queue of transactions to process
5. `exceptional_transactions_count`: we don't process transactions so also don't run into transactions we can't parse
6. `periodic_tasks_count`: we don't do any periodic tasks anymore
1. Remove the irrelevant stats from the Rust data type.
2. Remove the irrelevant stats from the Candid data type.
3. Stop …
> SECFIND-244: Remove irrelevant canister stats

- frontend/src/lib/components/portfolio/SkeletonTokensCard.svelte
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
Loading all the information for the Portfolio page may take some time. We want to display loading indicators to enhance the user experience.
https://github.com/user-attachments/assets/807d6d1f-8742-4ec0-a642-409eef735e8f
- Logic to decide the type of card to display: `empty`, `skeleton`, or `full`, depending on the data.  
- Provide boolean to the total assets card if any content is loading.
- Added unit test for the transition between not signed in, loading and loaded
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Not necessary
> feat(portfolio): implement page loading states

- rs/backend/src/accounts_store.rs
- rs/backend/src/accounts_store/tests.rs
While cleaning up the canister code I noticed missing test coverage for failure cases of `create_sub_account`.
1. Add a constant for `MAX_SUB_ACCOUNT_ID`.
2. Add `Debug` and `PartialEq` traits to `CreateSubAccountResponse` and `SubAccountDetails` required to make assertions on such values.
1. Add tests for response content, name too long, too many subaccounts and account not found.
not necessary
> Add test coverage for create_sub_account

- frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
- frontend/src/tests/lib/derived/sns/sns-filtered-actionable-proposals.derived.spec.ts
- frontend/src/tests/lib/derived/sns/sns-filtered-proposals.derived.spec.ts
- frontend/src/tests/lib/modals/sns/proposals/SnsFilterStatusModal.spec.ts
- frontend/src/tests/lib/modals/sns/proposals/SnsFilterTypesModal.spec.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-filters.services.spec.ts
- frontend/src/tests/lib/stores/sns-filters.store.spec.ts
- frontend/src/tests/lib/stores/sns-proposals.store.spec.ts
This PR does so for `snsProposalsStore` and `snsFiltersStore`.
1. Remove resetting of `snsProposalsStore` and `snsFiltersStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting snsProposalsStore and snsFiltersStore in beforeEach

- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
- frontend/src/tests/lib/derived/icrc-canisters.derived.spec.ts
- frontend/src/tests/lib/derived/imported-tokens.derived.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/routes/Wallet.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/services/imported-tokens.services.spec.ts
- frontend/src/tests/lib/stores/imported-tokens.store.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
This PR does so for `importedTokensStore` and `failedImportedTokenLedgerIdsStore`.
1. Remove resetting of `importedTokensStore` and `failedImportedTokenLedgerIdsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting importedTokensStore and failedImportedTokenLedgerIdsStore in beforeEach

- frontend/src/tests/lib/components/accounts/BitcoinEstimatedAmountReceived.spec.ts
- frontend/src/tests/lib/components/accounts/BitcoinKYTFee.spec.ts
- frontend/src/tests/lib/components/accounts/CkBTCInfoCard.spec.ts
- frontend/src/tests/lib/components/accounts/CkBTCTransactionsList.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCReceiveModal.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
- frontend/src/tests/lib/services/ckbtc-info.services.spec.ts
- frontend/src/tests/lib/services/ckbtc-minter.services.spec.ts
- frontend/src/tests/lib/stores/bitcoin.store.spec.ts
- frontend/src/tests/lib/stores/ckbtc-info.store.spec.ts
- frontend/src/tests/lib/stores/ckbtc-pending-utxos.store.spec.ts
- frontend/src/tests/lib/stores/ckbtc-retrieve-btc-statuses.store.spec.ts
This PR does so for `ckBTCInfoStore`, `bitcoinAddressStore`, `ckbtcRetrieveBtcStatusesStore` and `ckbtcPendingUtxosStore`.
1. Remove resetting of `ckBTCInfoStore`, `bitcoinAddressStore`, `ckbtcRetrieveBtcStatusesStore` and `ckbtcPendingUtxosStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting some btc related stores in beforeEach

- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, they may change in the future. Therefore, we want to retrieve them from the API.
In this PR, we mark the current periodic confirmation utilities as deprecated and add sibling utilities that expect the voting power economics properties to be in the argument. The utilities will be replaced in upcoming PRs.
- Add sibling utils. The only logic change is that the new utilities assume the neuron is active when a voting power parameter is not available.
- Added. They are similar to the old version utilities.
Not necessary.
> Economics based periodic confirmation utils

- frontend/src/tests/lib/components/proposal-detail/VotingCard/NnsVotingCard.spec.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
- frontend/src/tests/lib/pages/SnsNeurons.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons-check-balances.services.spec.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
- frontend/src/tests/lib/stores/checked-neurons.store.spec.ts
- frontend/src/tests/lib/stores/vote-registration.store.spec.ts
This PR does so for `voteRegistrationStore` and `checkedNeuronSubaccountsStore`.
1. Remove resetting of `voteRegistrationStore` and `checkedNeuronSubaccountsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting voteRegistrationStore and checkedNeuronSubaccountsStore in beforeEach

- frontend/src/tests/lib/components/project-detail/ParticipateButton.spec.ts
- frontend/src/tests/lib/components/project-detail/ProjectStatusSection.spec.ts
- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
- frontend/src/tests/lib/services/sns-sale.services.spec.ts
- frontend/src/tests/lib/services/sns-swap-metrics.services.spec.ts
- frontend/src/tests/lib/stores/sns-swap-metrics.store.spec.ts
- frontend/src/tests/lib/stores/sns-ticket.store.spec.ts
- frontend/src/tests/lib/utils/sns.utils.spec.ts
This PR does so for `snsTicketsStore` and `snsSwapMetricsStore`.
1. Remove resetting of `snsTicketsStore` and `snsSwapMetricsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting some more SNS related stores in beforeEach

- frontend/src/tests/lib/derived/sns-aggregator.derived.spec.ts
- frontend/src/tests/lib/derived/sns-parameters.derived.spec.ts
- frontend/src/tests/lib/derived/sns-swap-canister-accounts.derived.spec.ts
- frontend/src/tests/lib/derived/sns/sns-selected-project-new-tx-data.derived.spec.ts
- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
- frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts
- frontend/src/tests/lib/stores/sns-derived-state.store.spec.ts
- frontend/src/tests/lib/stores/sns-lifecycle.store.spec.ts
- frontend/src/tests/lib/stores/sns.store.spec.ts
This PR does so for `snsAggregatorIncludingAbortedProjectsStore`, `snsDerivedStateStore`, `snsLifecycleStore` and `snsSwapCommitmentsStore`.
1. Remove resetting of `snsAggregatorIncludingAbortedProjectsStore`, `snsDerivedStateStore`, `snsLifecycleStore` and `snsSwapCommitmentsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting some SNS related stores in beforeEach

- frontend/src/lib/components/neuron-detail/ConfirmFollowingBanner.svelte
- frontend/src/tests/lib/components/neuron-detail/ConfirmFollowingBanner.spec.ts
- frontend/src/tests/lib/pages/NnsNeuronDetail.spec.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, actual values are already being retrieved from the API (they are the same for now but may be updated in the future). The general idea is that if the parameters are unavailable, we consider the neuron active.
In this PR, we migrate `ConfirmFollowingBanner` from constants to the voting power economics store.
- Switch from constants to related stores.
- Do not show the component without voting power economics available (it is loaded on dapp initialisation).
- Added.
Not necessary.
> Migrate ConfirmFollowingBanner to voting power economics

- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/tests/lib/api-services/governance.api-service.spec.ts
- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/pages/NnsProposalDetail.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/workflows/NnsProposalDetail.spec.ts
- frontend/src/tests/workflows/NnsProposals.spec.ts
https://github.com/dfinity/nns-dapp/pull/6114 added `registerCleanupForTesting` to make test cleanup more robust.
1. Use `registerCleanupForTesting` to register `resetNeuronsApiService` as cleanup function.
2. Stop exporting `resetNeuronsApiService`.
3. Stop calling `resetNeuronsApiService` in individual tests.
1. Existing tests pass.
2. Verified that without registering the cleanup function, tests fail.
not necessary
> Register resetNeuronsApiService cleanup

- frontend/src/tests/e2e/multi-tab-auth.spec.ts
- frontend/src/tests/page-objects/App.page-object.ts
In #6199, we will change the root page from the `tokens` page to the `portfolio`.  
In #6225, we modified tests that were redirecting to `/` by enabling the feature flag and reloading the page to ensure they function correctly. 
This PR addresses  one missing case from #6225.
- Updated the expectations for navigating to `/`.
- Extended the `AppPo` to return the `PortfolioPo`.
- Should pass as before.
Not necessary
> test(porfolio): enable ENABLE_PORTFOLIO_PAGE in missing e2e test

- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/neurons/NnsLosingRewardsNeuronCard.svelte
- frontend/src/lib/components/neurons/NnsNeuronCardTitle.svelte
- frontend/src/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.svelte
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/stores/neurons-table-order-sorted-neuron-ids-store.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/neurons/NnsLosingRewardsNeuronCard.spec.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/page-objects/NnsLosingRewardsNeuronCard.page-object.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, actual values are already being retrieved from the API (they are the same for now but may be updated in the future). The general idea is that if the parameters are unavailable, we consider the neuron active.
In this PR, we migrate the getNeuronTags function (and its callers) to the voting power economics utilities.
- Switch to ...VPE utils in getNeuronTags ([changes](https://github.com/dfinity/nns-dapp/pull/6241/files#diff-b570daeb2a65094f5bd1d1b823bcf3025de7af68555903e0c2061d2f8b029e8fR555-R581)).
- Update all callers to provide startReducingVotingPowerAfterSeconds argument.
- Updated.
Not necessary.
> Migrate getNeuronTags to voting power economics

- rs/backend/src/accounts_store.rs
In https://github.com/dfinity/nns-dapp/pull/5739 we removed `neuron_accounts` from `AccountsStore` and stopped encoding it onto stable memory.
We also decoded its slot from stable memory into `candid::Reserved` which should be able to decode any type.
But this failed during canister upgrade because of the decoding skipping quota which exists to prevent attacks with requests with large amounts of unparsed data.
So in https://github.com/dfinity/nns-dapp/pull/5805 we changed it to decode into the original type `HashMap<AccountIdentifier, NeuronDetails>`.
Now that we no longer have a large map in stable memory, it is safe to decode into `candid::Reserved` as we do with other unused fields.
1. Decode unused neuron accounts as `candid::Reserved` once again.
2. Remove unused type …
> Decode unused neuron accounts as candid::Reserved

- frontend/src/lib/derived/neurons.derived.ts
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/tests/lib/components/neurons/NnsNeuronsMissingRewardsBadge.spec.ts
- frontend/src/tests/lib/derived/neurons.derived.spec.ts
Currently, the voting power parameters are hardcoded as half a year and one month. However, actual values are already being retrieved from the API (they are the same for now but may be updated in the future). The general idea is that if the parameters are unavailable, we consider the neuron active.
In this PR, we replace the constants based `shouldDisplayRewardLossNotification` function with `shouldDisplayRewardLossNotificationVPE`.
- Replace in `soonLosingRewardNeuronsStore`.
- Replace in NnsNeuronDetail for ConfirmFollowingBanner visibility.
- Updated. The NnsNeuronDetail was already covered because of the partly duplicated logic in the ConfirmFollowingBanner [here](https://github.com/dfinity/nns-dapp/pull/6236/files#diff-1cfb1fc9513a792bdab9ae3014a9012736bbf26f57001b3c1adcbddb51d769feR1 …
> Switch to shouldDisplayRewardLossNotificationVPE

- frontend/src/lib/utils/tokens-table.utils.ts
- frontend/src/tests/lib/utils/tokens-table.utils.spec.ts
We want to allow the user to change the order in the tokens table by clicking on the table headers, similar to the neurons table.
When clicking the "Projects" header, the tokens should be ordered alphabetically by name.
When clicking the "Balance" header, the tokens should be ordered by:
1. USD value of the balance
2. Tokens without exchange rate but positive balance before tokens with zero balance.
3. Within tokens with the same (probably 0) USD value, they should be sorted by:
1. ICP first
2. Known ck tokens
3. Imported tokens
4. Failed imported tokens
5. Other tokens
6. Alphabetically
This PR adds the sorting functions.
It does not add the functionality in the table.
1. Add necessary compare functions.
2. Tested manually (with additional changes) at …
> NNS1-3548: Add compare functions for tokens table

- frontend/src/tests/lib/pages/CanisterDetail.spec.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/routes/app/home/page.spec.ts
- frontend/vitest.setup.ts
We have code to prevent tests from doing `fetch`. When `fetch` happens during tests it typically means that they should have mocked an API call that's being used.
But this code wasn't working because it uses mocking and `vi.restoreAllMocks()` was being called after the setup was done.
1. Mock `global.fetch` in `beforeEach` instead of directly in `vitest.setup.ts`.
1. Add missing API mocking in tests that started failing.
not necessary
> Fix preventing global fetch in tests

- rs/backend/src/accounts_store.rs
The nns-dapp canister no longer processes ICP transactions so we don't need to keep track of which block height we are at with processing transactions.
1. Remove field `block_height_synced_up_to` from `AccountsStore`.
2. When encoding the `AccountsStore` to stable memory, write `None` in the slot of `block_height_synced_up_to`.
3. Ignore the slot of  `block_height_synced_up_to` when decoding the `AccountsStore` from stable memory.
This was was already not used anymore so no tests needed to be changed.
not necessary
> Remove block_height_synced_up_to from AccountsStore

- frontend/src/lib/components/sns-neuron-detail/FollowSnsTopicSection.svelte
- frontend/src/lib/modals/sns/neurons/NewSnsFolloweeModal.svelte
- frontend/src/tests/lib/components/sns-neuron-detail/FollowSnsTopicSection.spec.ts
- frontend/src/tests/page-objects/FollowSnsTopicSection.page-object.ts
- frontend/src/tests/page-objects/Hash.page-object.ts
- frontend/src/tests/page-objects/NewSnsFolloweeModal.page-object.ts
1. Add test IDs and page objects for components.
2. Change `FollowSnsTopicSection.spec.ts` to use page objects.
1. Test still passes.
2. Test now also passes with the change from https://github.com/dfinity/nns-dapp/pull/6263
not necessary
> Use page objects in FollowSnsTopicSection.spec.ts

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/constants/mockable.constants.ts
With https://github.com/dfinity/nns-dapp/pull/6205 we changed the deployment of disabling `FORCE_CALL_STRATEGY` from 10% to 30%.
The [proposal](https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=134977) for the release with this change was executed today at 11:23 CET.
Looking at graphs for the [SNS subnet](https://grafana.mainnet.dfinity.network/d/ic-health/ic-health?orgId=1&var-period=$__auto&from=2025-01-27T08:23:00.000Z&to=2025-01-27T14:23:00.000Z&timezone=utc&var-datasource=PE62C54679EC3C073&var-ic=mercury&var-ic_subnet=x33ed-h457x-bsgyx-oqxqf-6pzwv-wkhzr-rm2j3-npodi-purzm-n66cg-gae&var-dc=$__all&var-instance=$__all&var-instance_host=$__all) and the [NNS subnet](https://grafana.mainnet.dfinity.network/d/ic-health/ic-health?orgId=1&var-period=$__auto&from=2025-01-27T08 …
> Disable FORCE_CALL_STRATEGY for 100% of sessions

- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.spec.ts
- frontend/src/tests/page-objects/SnsFollowee.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronFollowingCard.page-object.ts
1. Update page objects.
2. Change `SnsNeuronFollowingCard.spec.ts` to use page objects.
1. Test still passes.
2. Test now also passes with the change from https://github.com/dfinity/nns-dapp/pull/6263
not necessary
> Use page objects in SnsNeuronFollowingCard.spec.ts

- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
- frontend/src/lib/components/neurons/LosingRewardsBanner.svelte
- frontend/src/lib/derived/neurons.derived.ts
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
During the migration to the voting power economics API, two versions of the same utilities existed (e.g., isNeuronLosingRewards and isNeuronLosingRewards**VPE**). The obsolete, constant-based utilities have been removed.
To keep the codebase clean, this PR removes the **VPE** postfix from these functions. Additionally, we replace the word "losing" with "missing" to reflect a shift in terminology during feature development. Other renamings will follow in upcoming PRs.
- Rename periodic confirmation related neuron utils.
- Pass.
Not necessary.
> Rename periodic confirmation related utils

- rs/backend/src/accounts_store.rs
The nns-dapp canister no longer processes ICP transactions so we don't need to keep track of the last time we processed transactions.
1. Remove field `last_ledger_sync_timestamp_nanos` from `AccountsStore`.
2. When encoding the `AccountsStore` to stable memory, write `0u64` in the slot of `last_ledger_sync_timestamp_nanos`.
3. Ignore the slot of  `last_ledger_sync_timestamp_nanos` when decoding the `AccountsStore` from stable memory.
This was was already not used anymore so no tests needed to be changed.
not necessary
> Remove last_ledger_sync_timestamp_nanos from AccountsStore

- frontend/src/lib/components/accounts/LedgerNeuronHotkeyWarning.svelte
- frontend/src/lib/components/neuron-detail/ConfirmFollowingBanner.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
- frontend/src/lib/components/neuron-detail/actions/ConfirmFollowingActionButton.svelte
- frontend/src/lib/components/neuron-detail/actions/ConfirmFollowingButton.svelte
- frontend/src/lib/components/neurons/AddUserToHotkeys.svelte
- frontend/src/lib/components/neurons/LosingRewardsBanner.svelte
- frontend/src/lib/components/neurons/NnsLosingRewardsNeuronCard.svelte
- frontend/src/lib/components/neurons/NnsNeuronsMissingRewardsBadge.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/LosingRewardNeuronsModal.svelte
- frontend/src/lib/types/i18n.d.ts
To keep the codebase clean, this PR renames the labels. The word "losing" has been replaced with "missing" to reflect a shift in terminology during feature development.
- Label keys rename.
- No changes.
Not necessary.
> Rename periodic confirmation related labels

- rs/backend/src/accounts_store.rs
We received an alert that the number of accounts in the NNS dapp has passed 280'000 and is getting close to the limit of 300'000.
Based on the dashboard, it looks like the number of accounts is growing with about 100 per day.
So if we increase both the limit and the alerting limit by 30k, it should last as another 9 months or so.
1. Increase the hard account limit from `300_000` to `330_000`.
No tested.
not necessary
> Increase account limit from 300k to 330k

- frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts
Discussed in https://github.com/dfinity/nns-dapp/pull/6258#discussion_r1932056272, `role=link` used in the test "renders role and aria-label passed" of `NnsNeuronCard` is actually no valid property. The component expect `role: undefined | "button" | "checkbox"`.
- Change test role to `button`
> test: invalid NnsNeuronCard role link

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
To simplify the token import process, the user can import a custom CK token by clicking a link, and the import token form will be pre-filled with the parameters from the URL (e.g. //nns.ic0.app/tokens/?import-ledger-id=m7h5t-euaaa-aaaaa-qabia-cai&import-index-id=myg3h-jmaaa-aaaaa-qabiq-cai). Having the ledger canister ID is sufficient to add an imported token.
In this PR, we fill in the form and automatically start validation.
1. Validate the canister IDs provided in the URL.
2. If the ID(s) are valid, fill in the form.
3. Start validation.
**Out of scope:**
- Additional handling of same tokens import.
- Sign-out flow.
- Add logic to start the import token process by URL.
- Added.
https://github.com/user-attachments/assets/22143018-db80-45eb-a4ab-336dfd12de89
Not …
> Import token by url

- rs/backend/src/accounts_store.rs
The nns-dapp canister no longer tops up neurons or keeps track of the number of topped up neurons.
1. Remove field `neurons_topped_up_count` from `AccountsStore`.
2. When encoding the `AccountsStore` to stable memory, write `0u64` in the slot of `neurons_topped_up_count`.
3. Ignore the slot of  `neurons_topped_up_count` when decoding the `AccountsStore` from stable memory.
This was was already not used anymore so no tests needed to be changed.
not necessary
> Remove neurons_topped_up_count from AccountsStore

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/tests/lib/components/tokens/TokensTable.spec.ts
We want to allow people to sort the tokens table based on name or balance.
The tokens table is used on the tokens page but also on the ICP accounts page.
On the accounts page we don't want to enable sorting.
This PR supports sorting in the tokens table be specifying the `order` prop on the `TokensTable` component.
We should not specify this prop on the accounts page.
On the tokens page we would use the `$tokensTableOrderStore` as the `order prop to persist the order between navigation.
BUT! We can not enable this on the tokens page yet either because the sort button on mobile interferes with the settings button for "hide zero balances".
So this PR only supports the functionality in the component but does not yet enable it on the page.
1. Support sorting based on either balance or title in …
> Support sorting in TokensTable

- frontend/src/tests/routes/app/portfolio/page.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
- frontend/src/tests/utils/ckusd.test-utils.ts
- frontend/src/tests/utils/ckusdc.test-utils.ts
We want to simplify the setup of the ckUSDC canister, similar to how we do it for [ckETH](https://github.com/dfinity/nns-dapp/blob/7a668d6280e0f0d022484430a95d2ad9e8f139f0/frontend/src/tests/utils/cketh.test-utils.ts#L10)
- New test utility function to set up the ckUSDC canister
-  Replaces manual setups with calls to this function
Not necessary
> test(utils): add ckUSDC canister test setup utility

- frontend/src/tests/e2e/canisters.spec.ts
- frontend/src/tests/page-objects/Canisters.page-object.ts
We've observed [flakiness](https://github.com/dfinity/nns-dapp/actions/runs/13017255077/job/36309718238?pr=6276) in the canisters end-to-end test.
I was not able to reproduce this, but while looking into the test I noticed something which seemed brittle.
On line 63, the test gets canister card page objects, and then reuses those objects on 88 and below, even though the test navigates to a different page (and back) on the lines in between.
And when it arrives, on line 88, those cards are not even on the page (it's showing skeleton cards).
The test relies on the fact that getting the name of the card in `expect(await myCanisterCard.getCanisterName()).toBe(newCanisterName);` causes the test to wait for the name to exist in the DOM.
This seems very brittle and it would be better to explicitly …
> Improve canisters e2e test

- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
The importTokenLedgerId comes from $pageStore (derived from app/stores/page), which dispatches an update twice on page load (presumably due to the Svelte hydration mechanism). This results in reading the canister ID from the URL twice, and if the ID format is incorrect, the error warning appears twice as well.
To prevent this, we introduce a flags to check the URL params only once. I also considered adding two derived stores (one per parameter), but flags offer a leaner solution.
- Use local flags to avoid multiple validation calls.
- The test was changed and verified that it fails w/o the fix.
Not necessary.
> Fix URL parameter double validation

- frontend/src/lib/stores/projects-table.store.ts
- frontend/src/lib/types/staking.ts
- frontend/src/tests/lib/stores/projects-table.store.spec.ts
We want to allow the user to change the order in the projects table by clicking on the table headers, similar to the neurons table.
To remember the order between navigations (not between sessions) we will use a store, similar to the [neuronsTableOrderStore](https://github.com/dfinity/nns-dapp/blob/main/frontend/src/lib/stores/neurons-table.store.ts).
1. Add `projectsTableOrderStore`.
2. Add `ProjectsTableOrder` type.
not necessary
> NNS1-3548: Add projectsTableOrderStore

- frontend/src/lib/components/proposal-detail/NnsProposal.svelte
- frontend/src/lib/pages/Canisters.svelte
- frontend/src/lib/pages/NnsProposalDetail.svelte
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/lib/stores/routes.store.ts
- frontend/src/routes/(app)/(nns)/reporting/+layout.svelte
- frontend/src/routes/(app)/(nns)/settings/+layout.svelte
- frontend/src/routes/(app)/(u)/(detail)/proposal/+layout.svelte
- frontend/src/routes/(app)/+layout.svelte
- frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
- frontend/src/tests/lib/stores/routes.store.spec.ts
- frontend/src/tests/routes/app/reporting/layout.spec.ts
- frontend/src/tests/routes/app/settings/layout.spec.ts
The Accounts page features a custom back button that currently redirects users to the Tokens page. This is no longer always accurate, as users can now access this page from the Portfolio page.
Since users can also navigate from the Accounts page to the Wallet page, we cannot rely on a local solution. The Accounts layout will be unmounted, resulting in the loss of this information.
This first PR modifies the existing solution used by the Proposal page to redirect back to either the Proposals or Launchpad by tracking the referrer. To gain more insight than just the last jump, the current single value has been changed to a list of referrers.
A follow-up PR will use this updated store in the Accounts layout to track how users enter the page and determine where to navigate when they click the …
> refactor(navigation): enhance referrer path tracking with list

- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
We want to allow the user to change the order in the projects table by clicking on the table headers, similar to the neurons table.
When clicking the "Nervous Systems" header, the projects should be ordered alphabetically by name.
When clicking the "Neurons" header, the projects should be ordered number of neurons.
When clicking the "Stake" header, the projects should be ordered by:
1. USD value of the stake
2. Projects without exchange rate but positive number of neurons before projects with zero neurons.
3. Within projects with the same (probably 0) USD stake, ICP should be sorted before others.
This PR adds the sorting functions.
It does not add the functionality in the table.
1. Add necessary compare functions.
2. Tested manually (with additional changes) at …
> NNS1-3548: Add compare functions for projects table

- frontend/package-lock.json
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
We want to pull in the latest changes to make the get the the ICP to XDR conversion rate certified.
Related ic-js pr: https://github.com/dfinity/ic-js/pull/830
- Run `npm run upgrade:next`
- Add new fields to the mock - the reason why the CI action upgrade is failing.
- Should pass as before
Not necessary
> chore: bump ic-js

- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
We want to allow sorting the tokens table.
On desktop, sorting the table is done by clicking on the table column header.
But on mobile, there is an icon in the top-right to open a sorting modal.
However, the tokens table already has an icon in the top right.
Until we have a better solution for that, we've decided to just not allow sorting the tokens table on mobile so that we can already allow sorting the tokens table on desktop.
This PR adds a prop to the `ResponsiveTable` component to control whether the sorting icon should be displayed on mobile.
1. Add `disableMobileSorting` prop to `ResponsiveTable` to hide the sorting icon button.
not yet
> NNS1-3548: Allow disabling table sorting on mobile

- frontend/src/lib/api/canisters.api.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
It has been flagged as a security concern not to use a certified query when reading the ICP to XDR conversion rate.
This is a follow up of https://github.com/dfinity/ic-js/pull/830 to make the call as a certified one.
[SECFIND-421](https://dfinity.atlassian.net/browse/SECFIND-421)
- Pass the `certified` flag to `getIcpToCyclesConversionRate` to make it an update call
- Updated unit test to check that the flag is provided
Not necessary
[SECFIND-421]: https://dfinity.atlassian.net/browse/SECFIND-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(security): enable certified calls for ICP/XDR conversion rate

- frontend/src/lib/modals/accounts/ImportTokenModal.svelte
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
When imported token validation fails (for reasons other than an invalid ID format or token duplication), clicking the Cancel button does not close the modal, which is undesirable. This happens because the Cancel button only updates showImportTokenModal but does not remove import-ledger-id from the URL, causing the modal to remain open ([the logic to open the modal](https://github.com/dfinity/nns-dapp/blob/1e511c6d974104c2fa1746cc4ec107bcb01c29a0/frontend/src/lib/pages/Tokens.svelte#L158))
- Remove query params from URL on cancel.
- Drive-by changes: Ensure consistent behavior by dispatching dispatch("nnsClose") before navigating to the already imported token.
- Added and verified that it fails w/o this fix.
Not necessary.
> Import by url cancel fix

- frontend/src/tests/utils/icp-swap.test-utils.spec.ts
- frontend/src/tests/utils/icp-swap.test-utils.ts
Setting the `icpSwapTickersStore` in tests can be confusing because we usually want certain USD prices for certain tokens, but the tickers are such that they specify how many of a token go in 1 ICP.
This means you have to divide in order to get the actual value you should set.
1. Add a test util function where you can specify the USD values you want for each token and it will set the tickers store such that the derived `icpSwapUsdPricesStore` has the given USD prices.
2. Tried to use it in an existing test but will update existing tests in a separate PR.
not necessary
> Add setIcpSwapUsdPrices test util

- frontend/src/lib/derived/routes.derived.ts
- frontend/src/tests/lib/derived/routes.derived.spec.ts
The Accounts page features a custom back button that currently redirects users to the Tokens page. However, this is no longer always accurate, as users can now access this page from the Portfolio page.
Since users can also navigate from the Accounts page to the Wallet page, we cannot rely on a local solution. The Accounts layout will be unmounted, resulting in the loss of this information.
This second PR follows up on #6274 by creating a derived store that checks the entry page for the Accounts page, whether it is the Portfolio or the Tokens page.
A third PR will utilize this derived store in the Accounts layout to determine the appropriate redirect.
- New derived store to calculate the last visited page: Tokens or Portfolio, defaulting to Tokens if neither was selected.
- Added unit …
> feat(navigation): add derived store for last tokens/portfolio visit

- frontend/src/tests/lib/components/proposal-detail/NnsProposal.spec.ts
- frontend/src/tests/lib/components/proposal-detail/NnsProposalProposerPayloadEntry.spec.ts
- frontend/src/tests/lib/components/proposals/NnsProposalsFilters.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts
- frontend/src/tests/lib/derived/proposals.derived.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/lib/pages/SnsProposals.spec.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
- frontend/src/tests/lib/stores/actionable-proposals-segment.store.spec.ts
- frontend/src/tests/lib/stores/proposals.store.spec.ts
This PR does so for `actionableProposalsSegmentStore`, `proposalsStore`, `proposalsFiltersStore` and `proposalPayloadsStore`.
1. Remove resetting of `actionableProposalsSegmentStore`, `proposalsStore`, `proposalsFiltersStore` and `proposalPayloadsStore` in `beforeEach` of individual tests.
Still pass.
not necessary
> Stop resetting some proposals related stores in beforeEach

- frontend/src/tests/lib/pages/Canisters.spec.ts
- frontend/src/tests/mocks/canisters.mock.ts
There is no reason to mock stores. We should use the real stores in tests.
1. Use real `canistersStore` in `Canisters.spec.ts`.
2. Remove `mockCanistersStoreSubscribe`.
Test-only change. Tests still pass.
not necessary
> Stop mocking canistersStore

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/state.rs
- rs/backend/src/state/partitions.rs
- rs/backend/src/state/partitions/tests.rs
- rs/backend/src/state/with_accounts_in_stable_memory.rs
2 reasons for this refactoring:
1. The backup/restore of `State` is currently a bit convoluted - it creates an AccountsStore with `AccountsDbAsMap` and replace it with `AccountsDbAsUnboundedStableBTreeMap` afterwards. This will be changed in a future PR. However, the functionalities of reading/writing bytes from/to managed memory are clear and useful, so they are moved to separate functions.
2. `PartitionsMaybe` will be removed, and the `Partitions` will be moved out of `State` in the next PR. When that happens, it makes less sense to have the logic to read/write managed memory in `State`, but rather `Partitions`. `State` will mostly care about how itself can be encoded/decoded
Extract reading/writing bytes logic from `save_heap_to_managed_memory`/`recover_heap_from_managed_memory` to …
> Refactor reading/writing stable memory bytes into Partitions

- rs/backend/src/accounts_store.rs
- rs/backend/src/state.rs
- rs/backend/src/state/partitions.rs
- rs/backend/src/state/tests.rs
- rs/backend/src/state/with_accounts_in_stable_memory.rs
- rs/backend/src/stats/tests.rs
`Partitions` is already "global", in the sense that even in unit tests ([ic_stable_structures::VectorMemory](https://github.com/dfinity/stable-structures/blob/69ed47f9b5001af67d650c714cd56ec3ee0ef2bb/src/lib.rs#L38)) is an `Rc<RefCell<Vec<u8>>>`, and operations to various memory partitions read/write from/to the bytes owned by the `Rc`. Therefore, it makes sense for `Partitions` to be a `thread_local!` variable. On the other hand, `PartitionsMaybe` is only useful when there can be 2 cases (raw/managed memory), which is no longer the case after the migration.
1. Define `PARTITIONS` `thread_local` variable and add accessors
2. Remove everything related to `PartitionsMaybe` and simplify dead code
N/A since it's mostly trivial refactoring. Tests under `rs/backend/src/state/tests.rs` should …
> Persist Partitions into a thread_local variable and remove PartitionsMaybe

- frontend/src/lib/components/reporting/ReportingNeuronsButton.svelte
- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/utils/reporting.save-csv-to-file.utils.ts
- frontend/src/lib/utils/reporting.utils.ts
- frontend/src/tests/lib/components/reporting/ReportingNeuronsButton.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/lib/utils/reporting.save-csv-to-file.utils.spec.ts
- frontend/src/tests/lib/utils/reporting.utils.spec.ts
#6255 introduced a bug in how `neuronId`s are rendered in the CSV file. Unit tests did not catch this issue because they focused on the generated data structure rather than the final string that appears in the CSV.
This first PR separates the reporting utilities into a secondary utility. This change is necessary because of how Vitest handles spies. The `generateCsvFileToSave` function would create a closure on `saveGeneratedCsv`, which would require mocking the entire file. This separation allows for the creation of new tests that can spy on the final value included in the CSV.
A follow-up PR will update the existing tests in `ReportingNeuronsButton` and `ReportingTransactionsButton` to verify the CSV string instead of the data structure.
A third PR will address the bug.
No logical …
> refactor(utils): extract csv to file generation utilities

- rs/backend/nns-dapp.did
- rs/backend/src/accounts_store.rs
- rs/backend/src/stats.rs
- scripts/nns-dapp/migration-test.canister
`accounts_db_stats_recomputed_on_upgrade` is no longer useful after the migration of accounts to stable structures. It is always `opt false`, which can be verified by `dfx canister --ic call qoctq-giaaa-aaaaa-aaaea-cai get_stats | grep accounts_db_stats_recomputed_on_upgrade`
Remove everything related to `accounts_db_stats_recomputed_on_upgrade`
N/A
[Previous](https://github.com/dfinity/nns-dapp/pull/6298) | [Next](https://github.com/dfinity/nns-dapp/pull/6302)
> Remove everything related to accounts_db_stats_recomputed_on_upgrade

- frontend/vitest.setup.ts
IDE and [CI](https://github.com/dfinity/nns-dapp/actions/runs/13110241729/job/36572373003?pr=6322) throws following errors when validating `tsconfig.spec`
> Error: vitest.setup.ts(47,5): error TS2698: Spread types may only be created from object types.
> Error: vitest.setup.ts(49,39): error TS2339: Property 'writable' does not exist on type 'unknown'.
- Infer types for `importOriginal`
> chore: fix importOriginal in vitest.setup

- Cargo.lock
- Cargo.toml
- rs/proposals/Cargo.toml
- rs/proposals/src/def.rs
The [automatic IC cargo deps update PR](https://github.com/dfinity/nns-dapp/pull/6312) failed because `ic_protobuf::registry::node_operator::v1::RemoveNodeOperatorsPayload` no longer exists. We should now use `registry_canister::mutations::do_remove_node_operators::RemoveNodeOperatorsPayload` instead.
1. Branched from the automatic update PR.
2. Added `registry-canister` dependency.
3. Used `registry_canister::mutations::do_remove_node_operators::RemoveNodeOperatorsPayload` instead of `ic_protobuf::registry::node_operator::v1::RemoveNodeOperatorsPayload`.
1. Was able to build nns-dapp canister.
2. Created a RemoveNodeOperators proposal with `scripts/ic-admin-propose propose-to-remove-node-operators aaaaa-aa`.
3. Checked that the proposal rendered correctly with the old code.
4. Checked …
> Update IC deps and use RemoveNodeOperatorsPayload from registry_canister

- frontend/package.json
Same as in Gix-cmp or OISY (PR [#4354](https://github.com/dfinity/oisy-wallet/pull/4354)), this PR sets up a `prepare` step in `package.json` to sync SvelteKit. By doing so, the `.svelte-kit/ts-config.json` file is generated.
The NNS dapp does not strictly require this setup yet, but it will be necessary when upgrading to Svelte v5. See the failing tests job [here](https://github.com/dfinity/nns-dapp/actions/runs/13107110902/job/36563668448?pr=6020).
This "minor change" was announced in this [CHANGELOG](https://github.com/sveltejs/kit/blob/main/packages/kit/CHANGELOG.md#2160).
> build: prepare sveltekit sync to prevent breaking change

- frontend/src/lib/derived/routes.derived.ts
- frontend/src/tests/lib/derived/routes.derived.spec.ts
Following a similar approach to #6285, the Wallets page will feature multiple return pages based on how it was accessed. 
Currently, there are two entry points:
* The Accounts page, when clicking any account except the NNS account.
* The NNS account page, when navigating from the Accounts page to the NNS account and then to the wallet.
A new entry point will be added to allow navigation back from the Portfolio page when the user clicks on a token in the `HeldTokensTable`.
A follow-up PR will update the Wallet's layout to make use of this store.
Note: It is easier to review by hiding the whitespaces
-  A new derived store has been created to determine the return destination from the Wallet page.
-  Unit tests have been implemented for this new derived store.
Not necessary
> feat(navigation): implement wallet page entry point tracking

- frontend/src/lib/components/portfolio/TotalAssetsCard.svelte
The `secondary-amount` class was not applied in the `TotalAssetsCard` component because it was incorrectly placed. The linter did not detect this issue, but the new version did, as noted in #6318.
Before:
After: 
- Change style
Not necessary
> fix(styles): add missing TotalAssetsCard style

- frontend/src/routes/(app)/(u)/(detail)/wallet/+layout.svelte
- frontend/src/tests/routes/app/wallet/layout.spec.ts
The tokens page has three potential entry points:  
-  The Accounts page, accessed by clicking any account except the NNS account.  
-  The NNS account page, reached by navigating from the Accounts page to the NNS account and then to the wallet.  
-  A new entry point will be added to allow navigation back from the Portfolio page when the user clicks on a token in the HeldTokensTable.  
This PR follows up on #6321 by redirecting users from the Tokens page based on how they entered.
Note: Tests are easier to read by hiding the whitespaces.
- Uses the new store `walletPageOrigin` to decide where to navigate back from Portfolio page.
- Added unit test to check that navigation is correct when coming from Portfolio page.
Not necessary
> feat(navigation): implement contextual back navigation for Tokens page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/reporting.utils.ts
- frontend/src/tests/lib/components/reporting/ReportingNeuronsButton.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
#6255 introduced a bug in how neuron IDs are rendered in the CSV file. Unit tests did not catch this issue because they focused on the generated data structure rather than the final string that appears in the CSV.
#6308 and #6310 improved the tests, and this final PR fixes the issue.
Note: Values can be copied by navigating the sheet and using `cmd+c` in all clients. When double-clicking a cell, I have encountered different behaviors:  
* Excel removes the equation and quotes.  
* Sheets and Numbers do not.
Some tests conducted in the development environment:  
* [Excel](https://onedrive.live.com/personal/c1392d169c907bfd/_layouts/15/doc.aspx?resid=C1392D169C907BFD!s68841b824cb747639537909bf40260bc&cid=c1392d169c907bfd&login_hint=habibfernandez%40gmail.com&ct=1738597106959&wdOrigin=OFFICEC …
> fix(reporting): correct neuronId formatting in CSV output

- rs/backend/nns-dapp-exports-production.txt
- rs/backend/nns-dapp-exports-test.txt
- rs/backend/nns-dapp.did
- rs/backend/src/main.rs
- rs/backend/src/perf.rs
When nns-dapp processed transactions, it also stored a list of recent transactions that it wasn't able to parse.
nns-dapp no longer processes transactions so we also no longer need this list of "exceptional" transactions.
1. Remove code related to exceptional transaction, as it is no longer used.
not necessary
> Remove get_exceptional_transactions

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/tests/lib/components/portfolio/HeldTokensCard.spec.ts
- frontend/src/tests/page-objects/HeldTokensCard.page-object.ts
We want signed-in users to be able to navigate to their wallets from their top positions on the Portfolio page.
Note that the Tokens page also allows users to access the wallet even if they are not logged in. We want to avoid this behavior on the Portfolio page to maintain consistency with the Staked Tokens card (nextPr), as we do not allow this on the Staking page.
https://github.com/user-attachments/assets/fd25259d-64b7-4540-ba00-7731d25fa68a
A follow-up PR will add the behavior to the staked tokens card.
- Make `HeldTokensCard` rows clickable if user is signed-in.
- Added unit tests to verify that the correct tag is rendered: a `div` when not signed in and an `a` when signed in.
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/portf …
> feat(portfolio): add authenticated wallet navigation from top token positions

- frontend/src/lib/components/proposal-detail/VotingCard/NnsVotingCard.svelte
- frontend/src/lib/constants/mockable.constants.ts
- frontend/src/lib/pages/NnsNeuronDetail.svelte
- frontend/src/lib/services/icp-accounts.services.ts
- frontend/src/lib/utils/call.utils.ts
- frontend/src/lib/utils/ckbtc.utils.ts
- frontend/src/tests/utils/mockable-constants.test-utils.ts
- frontend/vitest.setup.ts
We have 2 helpers `isForceCallStrategy` and `notForceCallStrategy` which are defined in `"$lib/constants/mockable.constants"`.
This is causing problems with the migration to Svelte v5.
But also, since they are not constants, they don't belong in `constants`.
1. Move the helper functions to `"$lib/utils/call.utils"`.
2. Remove them from mockable constants test setup.
1. Existing tests should pass.
2. I haven't tested it with Svelte v5 but it's a good change in itself even if it doesn't help with v5.
not necessary
> Move FORCE_CALL_STRATEGY helpers to utils

- rs/backend/nns-dapp.did
- rs/backend/src/main.rs
https://github.com/dfinity/nns-dapp/pull/5283 added a test to make sure `nns-dapp.did` matches the public interface in `main.rs` by adding a `candid_method` annotation to each canister method.
If necessary the method would be split in to a separate `_impl` function to put the annotation on.
But that PR forgot `create_toy_accounts`.
1. Split `create_toy_accounts_impl` from `create_toy_accounts`.
2. Add `candid_method` annotation.
3. Add `create_toy_accounts` to `nns-dapp.did`.
`test_implemented_interface_matches_declared_interface_exactly` passes.
not necessary
> Annotate create_toy_accounts_impl with candid_method

- frontend/src/lib/derived/routes.derived.ts
- frontend/src/tests/lib/derived/routes.derived.spec.ts
Following a similar approach to #6321, the neurons page will include multiple return pages based on how it was accessed.
Currently, there is only one entry point: the Staking page, which is accessed by clicking on any `ProjectsTable` row.
A new entry point will be added in #6342, so we need to know the origin to determine where to navigate back.
A follow-up PR will update the Neuron's layout to utilize this store.
- A new derived store has been created to determine the return destination from the Neuron's page.
- Unit tests have been implemented for this new derived store.
Not necessary
> feat(navigation): implement Neuron's page entry point tracking 

- frontend/src/tests/lib/api-services/sns-aggregator.api-service.spec.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
- frontend/src/tests/lib/api/icp-index.api.spec.ts
- frontend/src/tests/lib/api/icp-ledger.api.spec.ts
- frontend/src/tests/lib/components/accounts/CkBTCUpdateBalanceButton.spec.ts
- frontend/src/tests/lib/components/accounts/LedgerNeuronHotkeyWarning.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingNeuronsButton.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactions.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalCard.spec.ts
- frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/IncreaseSnsDissolveDelayModal.spec.ts
- frontend/src/tests/lib/modals/sns/sale/ParticipateSwapModal.spec.ts
- frontend/src/tests/lib/pages/CkBTCWallet.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/sns-sale.services.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
- frontend/src/tests/lib/stores/writable-stored.spec.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
- frontend/src/tests/lib/utils/reporting.utils.spec.ts
- frontend/src/tests/lib/utils/utils.spec.ts
- frontend/src/tests/lib/worker-utils/timer.worker-utils.spec.ts
- frontend/vitest.setup.ts
All tests should start with a clean slate. But it can be tricky to remember to clean up everything in the `beforeEach` of each test file.
1. Call `vi.clearAllTimers()`, `vi.useRealTimers()` and `localStorage.clear()` in `beforeEach` of `frontend/vitest.setup.ts`.
2. Remove these calls from `beforeEach` of individual tests.
Still pass.
not necessary
> Reset timers and localStorage before all tests

- frontend/package-lock.json
- frontend/package.json
https://github.com/advisories/GHSA-9crc-q9x8-hgqq
1. Ran `npm i vitest@2.1.9`.
2. Ran `npm i @vitest/coverage-v8@2.1.9`.
CI should pass
not necessary
> Update vitest from 2.1.3 to 2.1.9

- frontend/src/routes/(app)/(u)/(list)/neurons/+layout.svelte
- frontend/src/tests/routes/app/neurons/layout.spec.ts
The Neuron's page has two potential entry points:  
-  The Staking page, accessed by clicking on any row in the `ProjectsTable`.  
-  The Portfolio page, accessed by clicking on any of the stake tokens (#6342).  
This PR follows up on #6343 by redirecting users from the Neuron's page based on their entry method.
- Uses the new store `neuronsPageOrigin` to determine the navigation point when returning from the Neurons page.
- Split the current test into a check button and a navigation check that returns to the Staking page.  
-  Add a unit test to verify that navigation is correct when coming from the Portfolio page.
Not necessary
> feat(navigation): implement contextual back navigation for Neuron's page

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/tests/lib/components/portfolio/StakedTokensCard.spec.ts
- frontend/src/tests/page-objects/StakedTokensCard.page-object.ts
We want signed-in users to navigate to their wallets from their top positions on the Portfolio page.
This follows up on #6335. It adds navigation to the rows of the staked tokens table. Similar to the held tokens card, navigation will only be available to signed-in users.
https://github.com/user-attachments/assets/1e7e52e3-f24b-439d-9fb3-f171001c4ed6
- Make `StakedTokensCard` rows clickable if user is signed-in.
- Added unit tests to verify that the correct tag is rendered: a `div` when not signed in and an `a` when signed in, with the appropriate href value passed.
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/portfolio/)
> feat(portfolio): add authenticated neurons navigation from top projects

- scripts/nns-dapp/release-beta
We want to control to Beta NNS dapp canister with orbit for better security.
NOTE: beta.nns.ic0.app does not yet point to the canister managed by this script.
1. Add a script which guides a team member through setting up their orbit environment and requesting the installation of nns-dapp on the orbit controlled canister.
1. Tested manually together with @yhabib 
not necessary
> Script to release beta on orbit

- build-config.sh
`build-config.sh` is a script used in `scripts/setup` to set config variables defined in `dfx.json` as bash variables.
https://github.com/dfinity/nns-dapp/pull/5628 added `"DIDC_VERSION": "didc 0.4.0",` to `dfx.json`.
Because this has a space, it breaks when trying to run this line from the output of `build-config.sh`, which breaks `scripts/setup`:
```
DIDC_VERSION=didc 0.4.0
```
1. Use `@sh` instead of `tostring` to create a quoted shell string.
1. Was able to run `scripts/setup` again.
2. Also tried adding `"`, `\` and `'` in the variables and they are all quoted correctly.
not necessary
> Fix build-config.sh

- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/neurons/NnsLosingRewardsNeuronCard.spec.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts
- frontend/src/tests/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.spec.ts
- frontend/src/tests/lib/pages/NnsNeurons.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
In today's implementation, you can have neurons that are unlocked but have been inactive for so long that the "confirm following" warning appears. This is undesired, so the followee confirmation warning shouldn't be shown if the neuron cannot vote.
This PR ensures that the "missing rewards" tags are not shown for neurons that do not have enough dissolve delay to vote.
- Update tag generation logic.
- Updated.
Not necessary.
> No missing rewards tags for not votable neurons

- frontend/static/assets/libs/dummy-proposals.utils.js
- scripts/propose-to/propose-xdr-icp-conversion-rate
Since CMC has a default xdr/icp conversion rate at initialization, and we stopped using such conversion rate proposals in the mainnet a long time ago, it no longer makes sense to send such proposals in testing.
* Remove `scripts/propose-to/propose-xdr-icp-conversion-rate`
* Remove exchange rate proposal from `frontend/static/assets/libs/dummy-proposals.utils.js`
Tested on a local replica for making dummy proposals. Dummy proposals are still created, just without the conversion rate proposals:
> Remove the script to send conversion rate proposals since it's no longer needed

- scripts/add-controller
Once we move to using `dfx` with PocketIC we will be able to impersonate other principals when making `dfx` requests.
This makes it possible to become a controller of any canisters.
1. Add `add-controller` script to add a controller to a canister without having to be the controller.
1. Tested manually.
2. Can't be tested on CI yet because we don't use `dfx` with `--pocketic` yet on CI.
not necessary
> add-controller script

- rs/backend/src/accounts_store.rs
https://github.com/dfinity/nns-dapp/pull/6239 removed the `hardware_wallets_and_sub_accounts` field from `AccountsStore`.
This field was also encoding to and decoded from stable memory.
In order not to violate the skipping quote when decoding `AccountsStore`, we had to continue decoding it as `HashMap<AccountIdentifier, AccountWrapper>` until we could encode an empty structure by deploying a release.
Now that we've had a release we can decode to `candid::Reserved`, encode to `HashMap::<AccountIdentifier, candid::Empty>` and remove the `AccountWrapper` type.
1. Remove `AccountWrapper`.
2. Encode the `hardware_wallets_and_sub_accounts` slot as `HashMap::<AccountIdentifier, candid::Empty>`.
3. Decode the `hardware_wallets_and_sub_accounts` slot as `candid::Reserved`.
1. Downgrade-upgrade …
> Remove AccountWrapper

- scripts/nns-dapp/release-beta
For convenience when verifying a Beta upgrade request on Orbit.
1. Add verification instructions in the Orbit request summary.
2. Drive-by: Add an emoji to the "All checks passed" output for easier discovery of the `--skip-checks` flag.
Created this request:
https://orbitwallet.io/en/dashboard?reqid=eaff3b60-493a-4b9c-9fa7-04ebec5bc5dc&sid=fv4dp-biaaa-aaaal-amrua-cai
not necessary
> Add verification instructions to release-beta

- scripts/deploy-devenv
- scripts/dfx-snapshot-install
- scripts/dfx-snapshot-start
- scripts/nns-dapp/release-sop
- scripts/nns-dapp/test-proposal-payload
- scripts/nns-dapp/upgrade-downgrade-test
We want to start using PocketIC to create snsdemo snapshots.
When running a PocketIC snapshot, there is no `replica` process running.
We use `pgrep replica` in several places to check if a replica is running.
For now I'm not checking the scripts output so it still calls it a "replica" when `dfx start` is running, regardless of whether it's PocketIC or not.
1. Where we check `pgrep replica`, also check `pgrep pocket-ic`.
2. In `scripts/nns-dapp/test-proposal-payload` use `dfx info webserver-port` instead of `dfx info replica-port`, which is required when running PocketIC and also works fine without it.
1. Manually ran `scripts/nns-dapp/test-proposal-payload` with and without PocketIC snapshot.
2. Relying on CI for the others.
not necessary
> Prepare for PocketIC snapshots

- frontend/src/tests/lib/components/accounts/SelectAccountDropdown.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsAvailableMaturityItemAction.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronAdvancedSection.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronDissolveDelayItemAction.spec.ts
- frontend/src/tests/lib/components/neuron-detail/NnsNeuronPageHeading.spec.ts
- frontend/src/tests/lib/components/neurons/NnsNeuronCard.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactions.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/lib/components/universe/SelectUniverseCard.spec.ts
- frontend/src/tests/lib/derived/icp-tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/derived/tokens-list-user.derived.spec.ts
- frontend/src/tests/lib/modals/accounts/ReceiveModal.spec.ts
- frontend/src/tests/lib/modals/neurons/DisburseNnsNeuronModal.spec.ts
- frontend/src/tests/lib/modals/neurons/IncreaseNeuronStakeModal.spec.ts
- frontend/src/tests/lib/modals/neurons/MergeNeuronsModal.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/sale/ParticipateSwapModal.spec.ts
- frontend/src/tests/lib/pages/NnsAccounts.spec.ts
- frontend/src/tests/lib/pages/NnsWallet.spec.ts
- frontend/src/tests/lib/routes/Accounts.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/services/sns-sale.services.spec.ts
- frontend/src/tests/routes/app/accounts/page.spec.ts
`resetAccountsForTesting` is a [function](https://github.com/dfinity/nns-dapp/blob/7c6bc968bf90465bc7f75ef9fd4731b1a81597fd/frontend/src/tests/utils/accounts.test-utils.ts#L114) that resets 2 stores and does nothing else.
So there is no need to call this in `beforeEach`.
1. Remove `resetAccountsForTesting` in `beforeEach` of individual tests.
2. Remove `resetAccountsForTesting` inside tests where it's immediately followed by `setAccountsForTesting`.
Still pass.
not necessary
> Remove resetAccountsForTesting from beforeEach

- frontend/package-lock.json
- frontend/package.json
1. Keep our dependencies up to date.
2. A bug in agent-js that caused invalid signatures on `read_state` retries was fixed.
3. The new version supports better logging to investigate further invalid signature issues.
1. Ran `npm i @dfinity/agent@latest`.
1. Existing tests pass.
2. Tested the extra logging in a separate branch.
not necessary
> Update @dfinity/agent from 2.1.3 to 2.3.0

- frontend/src/tests/lib/utils/proposals.utils.spec.ts
I noticed [flakiness](https://github.com/dfinity/nns-dapp/actions/runs/13242022571/job/36959348708) in `frontend/src/tests/lib/utils/proposals.utils.spec.ts` which seemed to result from the test especting `nowInSeconds` to always return the same value during the test.
1. Call `vi.useFakeTimers()` in `beforeEach` in `frontend/src/tests/lib/utils/proposals.utils.spec.ts`.
1. I changed `Date.now` to always increase by 1 second on every call to see if any other tests had similar problems but this was the only test that failed.
not necessary
> Use fake timers in proposals.utils.spec.ts

- frontend/src/lib/components/ic/AmountDisplay.svelte
There is a visual bug in Safari that affects the display of numbers and text within an `inline-grid` and a `baseline`. This bug causes the numbers to overlap the text.
Before:
https://github.com/user-attachments/assets/b32535cd-bdcf-426f-974b-6ca1c7e34759
After:
https://github.com/user-attachments/assets/49b69220-155c-40af-baea-4793fc95f0c5
Fixes [NNS1-3606](https://dfinity.atlassian.net/browse/NNS1-3606)
- Change display from `inline-grid` to `inline-flex` as it breaks in Safari.
- Manually tested in Safari using [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/accounts/?u=qsgjb-riaaa-aaaaa-aaaga-cai)
Not necessary
[NNS1-3606]: https://dfinity.atlassian.net/browse/NNS1-3606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> fix(styles): correct number and text overlap in Safari

- scripts/get-transactions
- scripts/sns/find-failed-neurons
A while ago there was a bug where we didn't enforce the minimum neuron stake for SNS neurons in the UI.
This caused some people to transfer tokens to a governance canister subaccount, after which they couldn't create a neuron because the stake wasn't enough.
At the time I created a script to find such transactions that didn't turn into neurons to get an idea of the magnitude of the problem. I never got around to adding the script to the repo but this is that.
1. Add helper script `scripts/get-transactions` which gets a range of transactions from index and archive canisters.
2. Add `scripts/sns/find-failed-neurons` which based on a date range and SNS looks for staking transactions that didn't result in a neuron. Outputs the amount and a link to the account on the dashboard.
Tested …
> Add scripts/sns/find-failed-neurons

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/api/agent.api.ts
- frontend/src/tests/lib/api/agent.api.spec.ts
- frontend/src/tests/lib/api/canisters.api.spec.ts
- frontend/src/tests/lib/api/imported-tokens.api.spec.ts
- frontend/src/tests/mocks/agent.mock.ts
People have been getting "invalid signature" errors but the team has had difficulty debugging what's happening.
To help debug, we will store some debug information which can help debug the issue the next time someone reports the issue.
1. Listen for errors which contain `"Invalid signature"`.
2. When we see such an error, store data relevant for debugging (but not the message body, for privacy) in localStorage.
3. Log the debug info from localStorage on page load for easy discovery.
2. Tested manually in https://github.com/dfinity/nns-dapp/pull/6381 which has extra code to deliberately create an invalid signature.
3. Fixed existing unit tests which returned `undefined` for `createAgent` as the returned agent is now expected to have a `log` field.
> Store and log debug info on invalid signature

- frontend/src/lib/components/proposals/ProposalCard.svelte
The proposal cards have titles that are usually predefined based on the type of proposal. These titles contain spaces, so when their length exceeds the width of the card, the text automatically breaks into lines. However, sometimes these titles are custom, and their format may lack spaces but include underlines.
Before: 
After:
Relates to [NNS1-3615](https://dfinity.atlassian.net/browse/NNS1-3615)
- Adds CSS property to the titles to break down text based on natural boundaries using `break-word`.
- Manually tested by modifying the translations file locally with a custom breaking title.
Not necessary
[NNS1-3615]: https://dfinity.atlassian.net/browse/NNS1-3615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(styles): improve text wrapping in proposal card titles

- frontend/src/lib/components/accounts/TransactionCard.svelte
- frontend/src/lib/components/common/JsonPreview.svelte
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/common/TreeJson.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/ExpandableProposalNeurons.svelte
- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/lib/components/proposals/FiltersWrapper.svelte
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
Svelte v5 requires the web animation API which is not supported in emulated testing environment. That is why we added some "test safe transition directive" to Gix components (see PR https://github.com/dfinity/gix-components/pull/573) and why we are using those transitions in this PR.
- Relates to the Svelte v5 migration PR #6020
- Requires Gix-cmp bumped in PR #6394
- Use `testSafe...` directives instead of directly using transition of Svelte
> feat: use test safe transitions

- frontend/src/tests/lib/components/common/MenuItems.spec.ts
- frontend/src/tests/lib/components/neurons/LosingRewardsBanner.spec.ts
- frontend/src/tests/lib/pages/NnsProposals.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
In several tests we use `advanceTime()`, [which calls](https://github.com/dfinity/nns-dapp/blob/164f78620a9c9e420bd02a661548ad19cb3fe6be/frontend/src/tests/utils/timers.test-utils.ts#L22) `await vi.runOnlyPendingTimersAsync()` to make a UI transition finish before continuing with the test.
Using `advanceTime()` without parameter, makes time advance as much as is necessary to run the currently pending timers.
With Vitest 3, this no longer works in certain cases. I'm not sure why exactly but it's possible that there or additional timers before the transition timers, such that only those are passed and we're still waiting for the transition timers.
Passing an explicit number of milliseconds to `advanceTime()` makes sure that the transition timers are included in the timers being run.
1. Pass …
> Advance specific time to pass transition

- frontend/package-lock.json
- frontend/package.json
- frontend/src/tests/lib/pages/SnsProposalDetail.spec.ts
- frontend/src/tests/lib/pages/SnsWallet.spec.ts
- frontend/vitest.config.ts
To update Svelte to v5, we need to update `vitest`.
This PR updates just `vitest` and `@vitest/coverage-v8`.
One susprising change in Vitest 3, is that `spyOn` now reuses a mock if a method is already spyed on.
This means that you might think you're creating a new mock which has been called 0 times, but actually it was already called several times before.
1. Ran `npm i vitest@latest`
2. Ran `npm i @vitest/coverage-v8@latest`
3. Address deprecation warning that "basic" reporter will go away by using "default" instead in `vitest.config.ts`.
4. Add `spyQueryProposalApi.mockClear();` after creating a new spy to reset counters since the mock is not a new mock.
5. Increase an `advanceTime` in `frontend/src/tests/lib/pages/SnsWallet.spec.ts` to make sure the transition is passed. This was missed …
> Update vitest from 2.1.9 to 3.0.5

- scripts/create_neurons
To test the pagination for `list_neurons`, introduced in https://github.com/dfinity/ic-js/pull/833, an account must have more than 500 neurons. Ideally, this account should be an Internet Identity to evaluate its behavior in the UI and when generating a report.
The script will create the specified number of neurons, which will be controlled by the provided `principalId`.
Here’s an example of how to create 100 neurons for a given principal:
```
scripts/create_neurons -c 100 -p <principalId>
```
- Added new script.
- Tested locally
Not necessary
> feat(neurons): add script to create neurons

- frontend/src/lib/components/accounts/TransactionCard.svelte
- frontend/src/lib/components/common/JsonPreview.svelte
- frontend/src/lib/components/common/MenuItems.svelte
- frontend/src/lib/components/common/TreeJson.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/ExpandableProposalNeurons.svelte
- frontend/src/lib/components/proposals/ActionableProposalCountBadge.svelte
- frontend/src/lib/components/proposals/FiltersWrapper.svelte
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
- frontend/src/lib/components/universe/SelectUniverseCard.svelte
Revert #6396 because thanks to a different way of mocking the transitions for test purposes (without vite), those workaround are not needed anymore when migrating to Svelte v5.
New solution to mock the animation for test purposes with Svelte v5 providing by Testing Library in https://github.com/testing-library/svelte-testing-library/issues/284#issuecomment-2651620976
Revert #6396
I tested the revert and new way of mocking with Svelte v5 in #6404. The tests did not throw the keyword `TypeError: Cannot set properties of undefined (setting 'onfinish')`.
> feat: revert "use test safe transitions"

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/modals/proposals/NnsProposalsFilterModal.svelte
- frontend/src/lib/utils/proposals.utils.ts
- frontend/src/tests/lib/modals/proposals/NnsProposalsFilterModal.spec.ts
- frontend/src/tests/lib/utils/proposals.utils.spec.ts
To improve the user experience, proposal topics need to be displayed in a sorted order ([the ticket](https://dfinity.atlassian.net/browse/NNS1-3491)). This applies to the topic filter and the follow neuron topic list.
In this PR, we address the topic filter sorting. The follow neurons modal will be updated in a separate PR.
**Expected order:**
1. Governance.
2. SNS & Neurons' Fund.
3. All Except Governance, and SNS & Neurons' Fund. (not available in Topic filter)
4. Rest topics (ExchangeRate included) sorted alphabetically.
- Add sortNnsTopics util.
- Use it to sort topic filter.
- Updated.
> Topic filter sorting

- frontend/src/lib/components/universe/SelectUniverseNav.svelte
While the mobile gaps were reduced, the universe selector gaps on tablet and larger screens were [affected negatively](https://github.com/dfinity/nns-dapp/pull/6327/files#diff-dbb5a4699f2c5c767017edd873a5f737fcfa8cbcda4d587641c25fe2345d49fcL52) (see the screenshots).
- Restore the initial tablet+ margins.
| | |
| Before | ![Screenshot 2025-02-12 at 10 26 41](https://github.com/user-attachments/assets/94f97732-a1b0-4802-9656-173add9c927e) |
| After | ![Screenshot 2025-02-12 at 10 20 40](https://github.com/user-attachments/assets/e0b7fdf2-045c-4f18-842d-3c9e50b3b303) | 
Not necessary.
> Fix universe select gaps

- scripts/nns-dapp/migration-test.linters
In #6363, the merge queue [failed](https://github.com/dfinity/nns-dapp/actions/runs/13266920098/job/37036770632) due to a broken pipe. This PR implements the recommendation made [here](https://github.com/dfinity/nns-dapp/pull/6363#issuecomment-2651448888).
- Changes `grep -q` `grep ... > /dev/null`.
- Pipeline should pass as before
Not necessary
> fix(ci): resolve broken pipe issue in merge queue

- scripts/nns-dapp/release-sop
`release-sop` assumes that `cargo audit --json` will either
* succeed and not output any issues, or
* fail and output issues
But `cargo audit` has been failing without outputting anything on stdout, and the following error on stderr:
```
error: not found: Couldn't load Cargo.lock: I/O operation failed: parse error: parse error: invalid Cargo.lock format version: `4`
```
This went unnoticed because the `release-sop` script assumed success because there was no output on stdout.
1. Only assume there are no vulnerabilities if `cargo audit` succeeds.
1. Manually ran the command on an old commit without issues, on an old commit with issues and on a new commit with the above error.
not necessary
> Fail on cargo audit error

- frontend/src/lib/components/neurons/EditFollowNeurons.svelte
- frontend/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/src/tests/page-objects/EditFollowNeurons.page-object.ts
- frontend/src/tests/page-objects/FollowTopicSection.page-object.ts
To improve the user experience, proposal topics need to be displayed in a sorted order ([the ticket](https://dfinity.atlassian.net/browse/NNS1-3491)). This applies to the topic filter and the follow neuron topic list.
In this PR, we address the follow neurons modal.
**Expected order:**
1. Governance.
2. SNS & Neurons' Fund.
3. All Except Governance, and SNS & Neurons' Fund.
4. Rest topics (ExchangeRate included) sorted alphabetically.
- Display topics in a specific order.
- Added.
Not necessary.
> Sort follow neuron topics

- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/page-objects/MergeNeuronsModal.page-object.ts
In #6391, the merge queue failed due to a flaky test. The investigation revealed that the issue occurs when scrolling down to the button while the skeleton is present. At other times, the component loads, and the button moves out of the viewport, resulting in this strange behavior.
- It waits for the component to render and for the skeleton to disappear before clicking.
- Should pass as before.
Not necessary.
> fix(tests): resolve flaky test due timing in the CI

- frontend/src/lib/components/neurons/FollowNnsTopicSection.svelte
- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/modals/proposals/NnsProposalsFilterModal.svelte
- frontend/src/lib/types/filters.ts
- frontend/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/src/tests/lib/modals/proposals/NnsProposalsFilterModal.spec.ts
- frontend/src/tests/page-objects/FilterModal.page-object.ts
- frontend/src/tests/page-objects/FollowNnsTopicSection.page-object.ts
To improve UX, a divider should be displayed to visually separate popular topics from the other topics (which are sorted alphabetically).
- Add separator to topic filter.
- Add separator to follow neuron list.
- Added.
| Topic Filter | Following Modal |
| <img width="522" alt="image" src="https://github.com/user-attachments/assets/e68222ca-4537-4431-8425-5214221dbaac" /> | <img width="621" alt="image" src="https://github.com/user-attachments/assets/816b257f-d0be-45b6-a764-3c569dbed916" /> | 
Not necessary.
> Topics separator

- frontend/src/tests/lib/components/accounts/SelectNetworkDropdown.spec.ts
- frontend/src/tests/page-objects/Dropdown.page-object.ts
- frontend/src/tests/page-objects/SelectNetworkDropdown.page-object.ts
1. Add `SelectNetworkDropdownPo` which just extends `DropdownPo`.
2. Add extra functionality to `DropdownPo`.
3. Use `SelectNetworkDropdownPo` in `SelectNetworkDropdown.spec.ts`.
not necessary
> Use page objects in SelectNetworkDropdown.spec.ts

- frontend/src/tests/e2e/following.spec.ts
- frontend/src/tests/page-objects/AddHotkeyModal.page-object.ts
- frontend/src/tests/page-objects/CanisterDetail.page-object.ts
- frontend/src/tests/page-objects/ConfirmationModal.page-object.ts
- frontend/src/tests/page-objects/FollowNnsTopicSection.page-object.ts
- frontend/src/tests/page-objects/MergeNeuronsModal.page-object.ts
- frontend/src/tests/page-objects/NewFolloweeModal.page-object.ts
- frontend/src/tests/page-objects/NnsAddMaturityModal.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/NnsNeuronsFooter.page-object.ts
- frontend/src/tests/page-objects/RenameCanisterModal.page-object.ts
- frontend/src/tests/page-objects/SpawnNeuronModal.page-object.ts
- frontend/src/tests/page-objects/UpdateVotingPowerRefreshedModal.page-object.ts
We have several page object function that wait for the component to be absent by calling `await this.waitForAbsent()` or `await this.waitForClosed()`.
But a component can't control its own presence; it must be controlled by the parent component.
So these functions don't work when the component is tested directly but only if the parent is tested.
This makes some page object method less useful than they could be.
The right thing to do it to move the `waitForAbsent()` call to the page object of the parent component.
1. Remove `this.waitForAbsent()` calls from page objects and instead wait for the component to be absent on the calling side.
1. All the changed code is test-only code.
2. I made sure I didn't miss any callers by renaming the affected method and then renaming them back after …
> Remove this.waitForAbsent() from page objects

- frontend/src/lib/components/neurons/KnownNeuronFollowItem.svelte
- frontend/src/tests/lib/modals/neurons/NewFolloweeModal.spec.ts
- frontend/src/tests/page-objects/KnownNeuronFollowItem.page-object.ts
- frontend/src/tests/page-objects/NewFolloweeModal.page-object.ts
1. Change `data-tid` of `KnownNeuronFollowItem` to be the same across items.
2. Add `KnownNeuronFollowItemPo`.
3. Update `NewFolloweeModal.page-object.ts`
3. Use page objects in `NewFolloweeModal.spec.ts`
Tests only
not necessary
> Use page objects in NewFolloweeModal.spec.ts

- scripts/github-mark-ready
I like to make sure tests pass before marking a PR as ready to review.
But this means I have to remember to get back to the PR to check if the tests passed and then mark it ready for review.
Add `scripts/github-mark-ready` which watches a specified PR and marks it as ready for review after the tests have passed.
Optionally marking it as "merge when ready".
Used manually for 2 separate PRs.
not necessary
> Script to mark PR as ready after tests pass

- rs/backend/src/accounts_store.rs
We have a hard account limit after which no more accounts can be added.
This is to prevent too many accounts being created at once.
But when we approach that number organically, the number should be increased.
We have alerts set up to warn us when we approach the limit.
So those alerts should be increased as well when the limit is increased.
Add a comment pointing to an example of how to increase the alert limits.
No tested
not necessary
> Add comment about increasing account limit

- frontend/src/lib/stores/canisters-errors.store.ts
- frontend/src/tests/lib/stores/canisters-errors.store.spec.ts
Sometimes, canisters may become non-operative, such as when they run out-of-cycles. We need to be aware of these situations so we can update the UI accordingly.
This new store contains a map of canisters and their errors.
Out of scope: Parsing errors and making them usable.
- New store `canistersErrorsStore`
- Unit tests for the store
Not necessary
> feat(store): new store to track canister errors

- frontend/src/tests/lib/components/common/TextInputForm.spec.ts
- frontend/src/tests/page-objects/TextInputForm.page-object.ts
Most tests in `TextInputForm.spec.ts` were already using page objects, but not all of them.
Make the remaining tests also use page objects.
Still pass
not necessary
> Use page objects in TextInputForm.spec.ts

- frontend/src/tests/lib/components/common/TextInputForm.spec.ts
The `required` attribute on `input` elements is not enforced in unit tests.
But after updating to Svelte 5 and related dependency updates, it is required.
This causes `TextInputForm.spec.ts` to fail because it tries to submit a form without required input.
1. Enter some text before trying to submit the form.
1. Test still passes.
2. Test now also passes in https://github.com/dfinity/nns-dapp/pull/6020
not necessary
> Enter text in TextInputForm.spec.ts

- frontend/package-lock.json
- frontend/package.json
Keeping dependencies up-to-date.
This may also be necessary for Svelte 5 but doesn't cause issues to do separately.
Ran `npm i jsdom@latest`.
Still pass
not necessary
> Update jsdom to 26.0.0

- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
`AccountMenu.spec.ts` tries to add event listeners on elements that may not exist.
If the menu is not opened during a test, the `addEventListener` call will wait for the element to appear, which will fail.
But because the `addEventListener` call is not awaited, the test passes before it fails.
However, with the Svelte 5 (and related dependencies) update, this is caught and causes the test to fail.
1. Only add the `addEventListener("click", mockLinkClickEvent)` in tests that actually click on links and only after the menu is opened.
1. Test still passes.
2. Test now also passes in https://github.com/dfinity/nns-dapp/pull/6020 if I add some extra `advanceTime()` calls.
not necessary
> Avoid failing orphaned promises in AccountMenu.spec.ts

- frontend/src/lib/services/canisters.services.ts
- frontend/src/lib/stores/checked-block-indices.store.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
- frontend/src/tests/lib/stores/checked-block-indices.store.spec.ts
If canister creation gets interrupted and next time we see a canister funding transaction without a corresponding canister, we try to notify the CMC to create and attach the canister again.
Since this is only a fallback mechanism, we don't need to do this more than once per transaction per sessions.
Additionally, there is a bug in Svelte that causes `$:` blocks to sometimes not run, even though a dependency variable has changed. I've noticed this several times in `NnsWallet`. This bug seems to have been fixed (or at least changed) in Svelte 5. As a result, it actually tries to perform the canister creation fallback twice when the account balances are loaded uncertified and certified. This causes a test failure.
1. Add a store to keep track of block indices for which we've tried canister …
> CMC notify fallback only once per session

- config.json
- config.sh
- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/utils/env-vars.utils.ts
- scripts/nns-dapp/test-config-assets/app/arg.did
- scripts/nns-dapp/test-config-assets/app/env
- scripts/nns-dapp/test-config-assets/mainnet/arg.did
- scripts/nns-dapp/test-config-assets/mainnet/env
We want to integrate Plausible to the nns-dapp. We also want to use two different accounts one for mainnet and another one for everything else. For that we need an env. variable.
The rest of the setup can be found in #6445.
Note: the plausible domain is used to send the data to a particular Plausible account. 
1. Add an `plausible-domain`  in `mainnet` and `general` sections of `config.json`.
2. Support Plausible Domain in `config.sh`.
3. Create `PLAUSIBLE_DOMAIN` in `frontend/src/lib/constants/environment.constants.ts`.
4. Ran `./scripts/nns-dapp/test-config --update` to update golden files.
1. Ran config scripts and observed:
1. `DFX_NETWORK=mainnet ./config.sh` -> `VITE_PLAUSIBLE_DOMAIN=nns.ic0.app`
2. `DFX_NETWORK=local ./config.sh` -> `VITE_PLAUSIBLE_DOMAIN=test.nns.ic0.app`
2. …
> chore(metrics): add plausible domain configuration per network

- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/services/analytics.services.ts
- frontend/src/tests/lib/services/analytics.services.spec.ts
As announced in this [forum post](https://forum.dfinity.org/t/internet-identity-and-nns-dapp-analytics/40859), we aim to integrate an online analytics solution to monitor errors and aggregate usage data for the NNS dapp.
Here are some key points about Plausible:
-  No cookies or personal data collection.
-  Aggregates anonymized metrics.
-  Data sovereignty.
-  Hosted in the EU, ensuring strong privacy protections.
-  Complies with GDPR, PECR, and CCPA.
-  Publicly accessible analytics dashboard for community oversight.
-  Minimal data collection focused on critical metrics.
-  Lightweight.
This PR follows up on #6450 by using this new env. variable to expose a service that allows initializing the tool.
- New service to initialize the tool and return a list of cleanup functions.
- Added …
> feat(metrics): service to initialize plausible analytics

- scripts/github-mark-ready
`scripts/github-mark-ready` lets you automatically mark a PR as "Ready for review" once all the checks has passed.
Currently you need to pass the URL of which PR you want to mark as ready.
With this PR you don't have to pass a URL if you want it to apply to the PR of your current branch.
1. Determine `$PR` and `$REPO` automatically from the current branch when no argument is passed.
Manually
not necessary
> Automatically derive PR for github-mark-ready

- frontend/src/lib/utils/error.utils.ts
- frontend/src/tests/lib/utils/error.utils.spec.ts
We want to track canisters being out of cycles so we can display appropriate information in the ui. For that we need first to be able to identify an error as a canister out-of-cycles error.
This PR adds a util to identify such an error. Follow-up PRs will make use of it to fill the store introduce in #6464.
- Util to identify canisters out-of-cycle errors based on the error.message. 
- Unit test for the util.
Not necessary
> feat(errors): util for canister out-of-cycles errors

- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/services/analytics.services.ts
- frontend/src/tests/lib/services/analytics.services.spec.ts
Now that we have confirmed the tool works, we can remove its configuration from the devenv and e2e environments. This way, we will only load it for the following networks:
- mainnet
- betta and app
- Do not default the env. variable `PLAUSIBLE_DOMAIN` to empty string.
- Do not load Plausible if no domain has been loaded.
- Unit test the behavior based on the presence of the `domain` property.
Not necessary
Next PR: #6458
> refactor(analytics): conditionally load plausible based on domain presence

- config.json
We want to only load Plausible for `mainnet`, `beta` and `app` networks.
- Moved Plausible test domain from the default to the app and beta section in config.json.
- Ran `./scripts/nns-dapp/test-config --update` but no changes were generated.
- Ran config scripts and observed:
- `DFX_NETWORK=mainnet ./config.sh` -> `VITE_PLAUSIBLE_DOMAIN=nns.ic0.app`
- `DFX_NETWORK=beta ./config.sh` -> `VITE_PLAUSIBLE_DOMAIN=test.nns.ic0.app`
- `DFX_NETWORK=app ./config.sh` -> `VITE_PLAUSIBLE_DOMAIN=test.nns.ic0.app`
- `DFX_NETWORK=local ./config.sh` -> `VITE_PLAUSIBLE_DOMAIN=`
Not necessary
Prev. PR: #6459
> chore(analytics): restrict plausible to mainnet, app and beta networks

- .github/workflows/update-aggregator.yml
This [workflow](https://github.com/dfinity/nns-dapp/actions/runs/13460808242/job/37615415855) failed due to a missing reviewer.
Note: The PR was successfully created [here](https://github.com/dfinity/nns-dapp/pull/6473), and we were notified via Slack about this [issue](https://dfinity.slack.com/archives/C05G2RZFJAJ/p1740154645386359). I believe the flow is correct, as it does not block the changes while also notifying the team to update the file.
- Removes reviewers.
- Manually tested in [here](https://github.com/dfinity/nns-dapp/actions/runs/13461983809)
Not necessary
> chore(workflows): remove reviewers

- .github/workflows/update-next.yml
- .github/workflows/update-sns-aggregator-response.yml
Following up on #6479, we want to use the Node version defined in `config.json` throughout our project to maintain a consistent approach to the Node version. 
This PR updates the last two references to `.nvmrc`.
- Changes `NODE_VERSION` source from `.nvmrc` to `config.json`.
- Actions should run as before.
Not necessary
> chore(ci): migrate remaining node version references to config.json

- frontend/src/tests/lib/modals/neurons/DisburseSnsNeuronModal.spec.ts
https://github.com/dfinity/nns-dapp/pull/1409 added a test with the following line in `DisburseSnsNeuronModal.spec.ts`:
```
await waitFor(() => expect(syncSnsAccounts).not.toBeCalled());
```
This doesn't work because if `syncSnsAccounts` has not already been called, this will pass immediately.
The test will not wait to see if perhaps `syncSnsAccounts` will be called soon after.
Later https://github.com/dfinity/nns-dapp/pull/4455 refactored the code to remove `syncSnsAccounts`. It changed the code to call `loadSnsAccounts` (a subset of the functionality of `syncSnsAccounts`) instead. And it changed the test to replace `syncSnsAccounts` with `loadSnsAccounts`.
But `loadSnsAccounts` is in fact called during the test, inside `executeTransaction` in `DisburseSnsNeuronModal.svelte`.
But this …
> Fix bug in DisburseSnsNeuronModal.spec.ts

- scripts/freeze
- scripts/unfreeze
To test NNS dapp behavior with frozen canisters.
Canisters must be on a subnet where they use cycles.
1. `scripts/freeze` to set freezing threshold to the maximum.
2. `scripts/unfreeze` to set freezing threshold lower and top up cycles if necessary.
```
$ ALFA_LEDGER="$(scripts/sns/aggregator/get-sns --network local --json alfa | jq -r '.canister_ids.ledger_canister_id')"
$ scripts/freeze $ALFA_LEDGER
Freezing threshold was set to 18446744073709551615 seconds.
$ scripts/unfreeze $ALFA_LEDGER 
Freezing threshold was set to 2592000 seconds.
$ scripts/unfreeze  --cycles 58826881309068 $ALFA_LEDGER 
Freezing threshold was set to 2592000 seconds.
Transfer sent at block height 77
Using transfer at block height 77
Canister was topped up with 508000000 cycles!
```
not necessary
> Scripts to (un)freeze canisters

- frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
- frontend/src/tests/lib/modals/neurons/DisburseSnsNeuronModal.spec.ts
- frontend/src/tests/page-objects/DisburseSnsNeuronModal.page-object.ts
1. Add test ID in `DisburseSnsNeuronModal.svelte`.
2. Add `DisburseSnsNeuronModalPo` page object.
3. Use page object in `DisburseSnsNeuronModal.spec.ts`.
pass
not necessary
> Use page objects in DisburseSnsNeuronModal.spec.ts

- frontend/src/tests/e2e/portfolio.spec.ts
The Portfolio page is expose to the same issues as in #6093. This PR applies the same solution.
- In the screenshot test, if the `TVL` is "$99", replace it in the DOM with "$4'500'001'000".
- Tested in [6498](https://github.com/dfinity/nns-dapp/pull/6498)
Not necessary.
> test(portfolio): stabilize screenshot tests by normalizing TVL value

- frontend/src/tests/lib/pages/ProjectDetail.spec.ts
During the `"should participate without user interaction if there is an open ticket."` test in `ProjectDetail.spec.ts`, the `SaleInProgressModal` becomes visible and then invisible, after which the commitment should have appeared. Meanwhile `querySnsSwapCommitment` is first called twice and then once more.
The test expects to catch all of this without making sure that the process is paused at any point in time. This is very brittle because it depends on the framework waiting asynchronously at various steps.
With the Svelte 5 update this breaks, unsurprisingly.
The solution is to make sure that the test is blocked in states that we want to expect on.
1. Return unresolved promises from `querySnsSwapCommitment` and only resolve them after verifying the state of the component.
2. Verify that …
> Make ProjectDetail.spec.ts more robust

- frontend/src/lib/components/ic/AmountDisplay.svelte
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/components/ic/AmountDisplay.spec.ts
We may encounter issues loading SNS governance-related information; for instance, their canister might be out of cycles. We want to differentiate these scenarios to display an appropriate visual indicator in the UI.
This first PR updates `AmountDisplay` to accommodate the new Token type that will be used in later PRs to represent failed loaded actionable SNSs.
- Updates `AmountDisplay` to behave the same if `UnavailableTokenAmount` or `FailedTokenAmount`
- Updated tests for the new type of Token.
- Manually tested with #6485
Not yet
Next PR: #6502
> refactor(ui): unify AmountDisplay for unavailable and failed token amounts

- frontend/src/lib/stores/actionable-sns-proposals.store.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
Follow up on #6503 to introduce the Failed token when building the `TableProjects` if the actionable SNS fails.
Subsequent PRs will utilize this new field in the UI to display a warning message with a tooltip.
Note: A default value of `[]` has been defined for `failedActionableSnsesStore` in `getTableProjects` to minimize the changes required for this PR.
- Updates `actionable-sns-proposals.store.ts` to expose the data type of the `FailedActionableSnsesStore`
- Updates `getNeuronAggregateInfo` to return a payload with a `FailedTokenValue` for the stake if the actionable proposal failed.
- Added new unit test
- Manually tested with https://github.com/dfinity/nns-dapp/pull/6485
Not yet
Prev. PR: #6503 | Next PR: #6504
> feat(store): add support for failed actionable SNS proposals in TableProjects

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/staking/ProjectTitleCell.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/stores/actionable-sns-proposals.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
- frontend/src/tests/page-objects/ProjectTitleCell.page-object.ts
Follows up on #6502 to introduce the Warning and Tooltip in the Projects Table.
Note: The default value of `[]` remains set for `failedActionableSnsesStore` in `getTableProjects` due to https://github.com/dfinity/nns-dapp/blob/017d92c6cd860cac3114e991f9acd24fd2092bc4/frontend/src/routes/(app)/(nns)/portfolio/%2Bpage.svelte#L58
- Updates `ProjectTitleCell` to display a warning icon and a tooltip if the `stake` is of type `FailedTokenAmount`.  
-  Updates `ProjectsTable` to pass `failedActionableSnses` to `getTableProjects`.  
-  Exposes a `TooltipPo` through the `ProjectsTableRowPo`.
- Added new unit test
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/staking/)
Prev. PR: #6502 | Next PR: #6505
> feat(ui): add warning indicators for failed Projects

- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/routes/app/portfolio/page.spec.ts
Last PR in the series adds warnings and raises awareness of failed actionable proposals within the dapp. This final update introduces the `failedActionableSnsesStore` in the Portfolio route when calling `getTableProjects`, preventing failed sns from being loaded.
You can find all changes in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/staking/).
- Updates the Portfolio route to pass the `failedActionableSnsesStore` when calling `getTableProjects`.
-  Removes the default value for `failedActionableSnsesStore` in `getTableProjects`.
- Added new unit test
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/staking/)
Not necessary
Prev. PR: #6504
> feat(portfolio): integrate failed SNS detection in projects table

- scripts/nns-dapp/estimate-upgrade-cycles
Starting with `dfx` 0.25.0, canister calls to mainnet using unencrypted identities is no longer allowed.
Use `--identity anonymous` when getting mainnet stats.
This partially unbroke https://github.com/dfinity/nns-dapp/pull/6494
not necessary
> Anonymous get_stats call

- frontend/src/lib/utils/format.utils.ts
- frontend/src/tests/lib/utils/format.utils.spec.ts
The nns-dapp displays monetary values in various sections: the portfolio, tokens, and projects page. These values can sometimes be large numbers with decimals that are overly detailed for these components. 
This first PR introduces a utility for displaying monetary values according to the following rules:
* For values less than CHF 1,000 — Display 2 decimal points. Example: CHF 420.69
* For values between CHF 1,000 and CHF 1,000,000 — Display the whole number with 0 decimal points. Example: CHF 1,996
* For values between CHF 1,000,000 and CHF 1,000,000,000 — Display millions with an “M” and 2 decimal points. Example: CHF 1.50M / CHF 24.8M / CHF 420.69M
* For values greater than CHF 1,000,000,000 — Display billions with a “B” and 2 decimal points. Example: CHF 1.50B / CHF 24.8B / CHF …
> feat(utils): add monetary value formatter with dynamic precision

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/lib/components/portfolio/TokensCardHeader.svelte
We aim to centralize the formatting of amounts for the HeldTokens and StakedTokens cards. This will be utilized in a follow-up PR to format currencies using the new utility.
- Moves formatting logic to the shared card header component.
Not necessary
> refactor(ui): centralize token card amount formatting

- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/pages/Tokens.svelte
Since the tokens table now displays fiat values alongside token balances, users may want to sort by them instead of being restricted to the fixed alphabetical order currently enforced. To enable this, we need to allow users to sort the table via the extended table settings popover, as there are no column headers on mobile.
Besides sorting, the settings popover will also include table-specific controls, such as the HideZeroBalancesToggle for the tokens table.
The task: https://dfinity.atlassian.net/browse/NNS1-3603
- Refactor: Move the settings popover to ResponsiveTable, adding a slot for custom controls (used for HideZeroBalancesToggle in the tokens table).
- Pass.
Not necessary.
> Move settings popover to ResponsiveTable

- .config/spellcheck.dic
- .config/spellcheck.toml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/docker-main.yaml
- .github/workflows/nightly.yaml
- .github/workflows/reproducible.yaml
- .github/workflows/tag.yaml
The nns-dapp uses an Ubuntu runner that will be deprecated on April 1st. We need to upgrade it to a later version before that date. Full message can be found [here](https://dfinity.slack.com/archives/CH4CADCJX/p1740558752499169).
Note: Upgrading the version of Ubuntu caused `cargo spellcheck` to [fail](https://github.com/dfinity/nns-dapp/actions/runs/13569728867/job/37935146081) while attempting to load the `en-GB` dictionary.
- Upgraded the version to `ubuntu-22.04`.
- Changed the `spellcheck.toml` language to American English.
- Added missing words to the spellcheck dictionary.
Not necessary.
> chore(ci): upgrade github actions runner to ubuntu-22.04

- frontend/src/lib/components/ui/ResponsiveTableSortControl.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/ui/ResponsiveTableSortControl.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTableSortControlTest.svelte
- frontend/src/tests/page-objects/Chip.page-object.ts
- frontend/src/tests/page-objects/ChipGroup.page-object.ts
- frontend/src/tests/page-objects/ResponsiveTableSortControl.page-object.ts
To improve the UX, we are introducing the ability to control table sorting from the settings popover. This ensures that table visibility can also be managed on mobile devices, where sorting headers are not available. With this PR, we add a chip-based sorting control component, which will be used in the table settings popover.
Demo: https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/tokens/
- Add ResponsiveTableSortControl component.
- Chip and ChipGroup POs.
- ResponsiveTableSortControl specs.
- Tested in draft PR: https://github.com/dfinity/nns-dapp/pull/6524
Not yet.
> Responsive table sort control

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
Sometimes SNS canisters may be down, preventing us from receiving the requested information. For example, when a canister goes out of cycles, we cannot retrieve the stake from the governance canister. In such situations, we want to avoid allowing any user interactions that are meaningless. 
This PR disables row navigation for SNS whose governance canister is unresponsive.
- Sets the Neurons table row link to undefined if the canister doesn't respond.
- Updates the test.
> fix(ui): disable navigation for unresponsive SNS neurons

- Dockerfile
The Reproducible Docker Builds job started [failing](https://github.com/dfinity/nns-dapp/actions/runs/13643019276) last night due a new version of [rustup](https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html). 
The main change is:
> rustup will no longer automatically install the active toolchain if it is not installed.
- Parse `rust-toolchain.toml` to obtain the Rust version and targets.  
- Fix the `rustup` version to prevent similar problems in the future.
- Install the toolchain for the version specified in `rust-toolchain`.  
- Install the targets defined in `rust-toolchain`.
- [Reproducible Docker Build should pass](https://github.com/dfinity/nns-dapp/actions/runs/13655885529)
Not necessary
> fix(ci): adapt docker build to new rustup behavior

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
For the upcoming changes to the Portfolio page, we need to display certain values of the Open Proposals, such as the minimum and maximum commitment. We want to present these with special formatting. Please see the attached screenshot.
This PR introduces a new utility for the Portfolio page to format numbers accordingly.
- Adds a new utility to format participation on the portfolio page.
- New unit tests.
Not necessary.
> feat(portfolio): add participation amount formatter util

- .config/spellcheck.dic
- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/scripts/build.csp.mjs
- frontend/src/lib/api/location.api.ts
- frontend/src/tests/lib/api/location.api.spec.ts
We introduced location services in [GIX-1546](https://dfinity.atlassian.net/browse/GIX-1546) for SNS swaps to restrict participation from users in certain countries.
One of these services, `api.geoiplookup.net`, has been unreliable for a long time, so we plan to replace it with a new one.
In this PR, we introduce a new fallback service, `api.iplocation.net`, and remove the code related to the unreliable service.
[NNS1-3065](https://dfinity.atlassian.net/browse/NNS1-3065)
- Sets `getLocationFromIpLocation` as the primary service for obtaining location.
- Adds `getLocationFromIpSb` as the secondary service in case the primary fails.
- Updates our CSP rules to include the new service domain.
- Removes `getLocationFromGeoIP` based on `api.geoiplookup.net` since it no longer functions.
- …
> refactor(geo): replace fallback location service for SNS swap restrictions

- frontend/src/lib/services/icrc-accounts.services.ts
There is a typo in the codebase
- Replaces `isCanisterOufOfCycles` with `isCanisterOutOfCycles`.
Not necessary.
> fix(typo): corrects typo in a variable name

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
For the upcoming changes to the Portfolio page, we need a percentage of a project's minimum ICP participation for the project to be successful. 
This PR introduces a new utility to extract values from a `FullProjectCommitmentSplit` and perform the calculation.
- New portfolio utility to calculate the percentage of the minimum commitment that has already been raised.
- Added unit tests
Not necessary
> feat(portfolio): add minimum commitment percentage calculator

- Dockerfile
The Reproducible Docker Builds [failed](https://github.com/dfinity/nns-dapp/actions/runs/13643019276)due a new version of [rustup](https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html) due to a new version of rustup. 
#6529 introduced this new version but also required additional changes because the auto-installation of the toolchain is no longer done automatically.
This change appears to be unintended, as it has been addressed in the latest [patch](https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md#1281---2025-03-05) of rustup.
This PR updates the `rustup` version to the fixed release and cleans the unnecessary code.
- Updates the `rustup` version to the latest patch.
- Removes unnecessary code that was used to install the toolchain with `rustup`.
- The pipeline should …
> chore(ci): update rustup to 1.28.1 and remove toolchain install workaround

- frontend/src/tests/lib/components/proposal-detail/ProposalNavigation.spec.ts
In the Svelte v5 branch, a test for a logo is failing because, instead of referencing the SVG, the content is inlined. I assume you don't want to test whether the SVG is inlined or not, but rather test if the expected logo is used. Therefore, this PR imports the logo and uses the result for comparison purposes.
> test: import logo

- frontend/src/lib/components/portfolio/SkeletonTokensCard.svelte
Reported in the Svelte v5 branch
```
ESLint:
Self-closing HTML tags for non-void elements are ambiguous — use `<div ...></div>` rather than `<div ... />`
https://svelte.dev/e/element_invalid_self_closing_tag(element_invalid_self_closing_tag)
(svelte/valid-compile)
```
> fix: lint self closing tag

- frontend/src/routes/(app)/(nns)/project/+layout.svelte
- frontend/src/tests/routes/app/project/layout.spec.ts
This PR follows up on #6543 by utilizing the new derive store to redirect the user to the correct page after clicking the back button on the layout.
[NNS1-3640](https://dfinity.atlassian.net/browse/NNS1-3640)
- Implement back navigation in Project page layout.
- Added unit test
Not necessary
[NNS1-3640]: https://dfinity.atlassian.net/browse/NNS1-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(navigation): implement dynamic back navigation for Project page

- .github/workflows/checks.yml
Currently, the `small-tests` action fails on CI because of outdated [golden data](https://github.com/dfinity/nns-dapp/actions/runs/13790391836/job/38568471111?pr=6561)
- Update the value.
- All checks should be green.
Not necessary.
> chore(ci): update golden data for small-tests

- frontend/src/lib/components/portfolio/LaunchProjectCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/LaunchProjectCard.spec.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/page-objects/LaunchProjectCard.page-object.ts
We want to display all ongoing swaps on the Portfolio page. This first PR introduces a new Card component that will be used to present information about the ongoing launch, including details about the commitment, neuron fund, and time remaining.
[NNS1-3640](https://dfinity.atlassian.net/browse/NNS1-3640)
- Added a new Card component.  
-  Created a purchase order for the new component.  
-  Extended the mock utility `createSummary` to support testing.  
- Added unit tests for the new component
- Manually tested together with other changes in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Not necessary
[NNS1-3640]: https://dfinity.atlassian.net/browse/NNS1-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portfolio): add ongoing swap status card

- frontend/src/lib/utils/error.utils.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/services/icrc-transactions.services.spec.ts
- frontend/src/tests/lib/utils/error.utils.spec.ts
- frontend/src/tests/routes/app/tokens/page.spec.ts
#6465 introduced a method for tracking specific errors based on the error message payload. This functionality broke after the following change: https://github.com/dfinity/ic/pull/3465.
The [recommendation](https://dfinity.slack.com/archives/CGA566TPV/p1741614348749269?thread_ts=1741613964.837469&cid=CGA566TPV) is to utilize the fields instead of parsing the message.
Please note that we need to use type guards to retrieve information about the errors, as it is not currently propagated to the client app.
- Refactor `isCanisterOutOfCyclesError` to narrow down  error's type and utilize the `error_code` information.
- Updated tests based on new implementation.
Not necessary
> fix(errors): update cycles detection to use error codes

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/components/portfolio/LaunchProjectCard.spec.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
New requirements have been established for displaying minimum and maximum participation in the new Launch cards on the Portfolio page. 
This PR refactors #6531 to accommodate these changes.
- Increase granularity of `formatParticipation`
- Updates tests
Not necessary
> refactor(portfolio): increase participation amount precision

- frontend/src/lib/components/portfolio/LaunchProjectCard.svelte
We want to update some styles of the `LaunchProjectCard`, specifically how it renders the link to the swap page on small screens and how long titles can affect the size of the card.
Before:
https://github.com/user-attachments/assets/5a6b9fb7-8678-4629-8e1e-98ad5acf2e1d
After:
https://github.com/user-attachments/assets/99fa16a2-86cc-45f8-9cc7-52f2991b5486
[NNS1-3640](https://dfinity.atlassian.net/browse/NNS1-3640)
- Adds styles to render the swap link as a button instead of a link on small screens.  
- Adds styles to truncate the card titles to prevent breaking the card size.  
- Modifies the styles for the dot buttons.
Not necessary
[NNS1-3640]: https://dfinity.atlassian.net/browse/NNS1-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> style(portfolio): improve LaunchProjectCard mobile styles

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/canisters/SelectCyclesCanister.svelte
As reported in [Slack](https://dfinity.slack.com/archives/C01S03NBM7S/p1742021219737869), the TopUp canister flow can be confusing. This is because both input fields remain disabled until the frontend receives the exchange rate from ICP to Cycles.
We want to inform users that something is happening by displaying a spinner.
https://github.com/user-attachments/assets/39bfb86c-d497-4969-90a0-bf0f912b1599
- Add `Spinner` to both input field as long as there is not value for `icpToCyclesExchangeRate`
> feat(ui): add loading indicators to canister topup exchange fields

- frontend/src/lib/components/portfolio/TokensCardHeader.svelte
We want to simplify and reuse the link button styles from Gix to make the portfolio tokens card more consistent with the rest of the app.
-Reuse link classes from Gix and remove redundant styles.
- E2E tests should pass as before
Not necessary.
> refactor(styles): standardize portfolio card links buttons with gix styles

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/sns-neuron-detail/SnsNeuronVotingPowerSection.svelte
Following up on the work done in #6138, we also want to hide details about voting power behind an accordion-like component for SNS neurons. This way, users must proactively click to expand and see the details. This change will simplify the complexity of the UI.
Before:
After:
https://github.com/user-attachments/assets/806512ef-9044-49c7-8f2c-e28b3be6cd63
[NNS1-3660](https://dfinity.atlassian.net/browse/NNS1-3660)
Use `KeyValuePairInfo` to conceal the voting calculation logic.
- Should pass as before
[NNS1-3660]: https://dfinity.atlassian.net/browse/NNS1-3660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(neurons): collapse SNS voting power details into expandable section

- frontend/src/lib/components/portfolio/StackedCards.svelte
We want to introduce visual improvements to the dots displayed in the `StackedCard`.
Before:
After:
- Adjusts the spacing for the dot buttons in the footer of the `StackedCard`.
- Updates screenshots.
Not necessary.
[NNS1-3641]: https://dfinity.atlassian.net/browse/NNS1-3641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(ui): adjust stacked card navigation dots spacing

- frontend/src/lib/components/neurons/NnsStakeNeuron.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/SplitNnsNeuronModal.svelte
- frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
- frontend/src/lib/types/i18n.d.ts
In the scope of [NNS1-3671](https://dfinity.atlassian.net/browse/NNS1-3671), we aim to display the USD value of transaction fees. We already have a component for this purpose, but it is not utilized consistently. This PR eliminates redundant one-time implementations and reuses the existing component. A follow-up PR will introduce the new logic to display the USD fee value.
- Reuse `TransactionFormFee` in the SplitNeuronModals components for both NNs and SNs.
- Remove redundant translations since they all use the same key.
- Test should pass as before.
Not necessary.
[NNS1-3671]: https://dfinity.atlassian.net/browse/NNS1-3671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(transactions): reuse transaction fee component in SplitStake modals

- frontend/src/lib/components/transaction/TransactionFormFee.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/token.utils.ts
- frontend/src/tests/lib/components/transaction/TransactionFormFee.spec.ts
- frontend/src/tests/page-objects/TransactionFormFee.page-object.ts
Following up on #6597, we want to display the USD value for transactions. In this PR, we are adding a new section to the `TransactionFormFee` to show the fee in dollars. 
We use the same data source for the token prices as in the rest of the application, icp-swap.
[NNS1-3671](https://dfinity.atlassian.net/browse/NNS1-3671)
- Displays the USD value of the transaction fee
- Adds unit tests for the component
Not yet.
[NNS1-3671]: https://dfinity.atlassian.net/browse/NNS1-3671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(transactions): display fee amount in USD

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/ui/InputWithError.svelte
We want to simplify the errors displayed by the `InputWithError` component.
Before:
After:
- Removes icon and color text overrides from the error message.
- Existing tests should continue to pass as they did before.
> style(ui): simplify input error message presentation

- frontend/src/lib/components/ic/AmountDisplay.svelte
- frontend/src/lib/components/ui/AmountInputFiatValue.svelte
- frontend/src/tests/lib/components/ui/AmountInputFiatValue.spec.ts
- frontend/src/tests/page-objects/AmountInputFiatValue.page-object.ts
In the scope of [NNS1-3671](https://dfinity.atlassian.net/browse/NNS1-3671), we want to display the USD value of inputs when the user enters a non-fiat value. This PR introduces a new component that will later be used by the `AmountInput` to show the fiat value.
- Adds a new component, `AmountInputFiatValue`, to display the USD value and balance.  
- Exposes a CSS variable to style the `font-weight` of `AmountDisplay` for consumers.
- Added unit tests.  
-  Manually tested alongside other changes in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network)
Not necessary
[NNS1-3671]: https://dfinity.atlassian.net/browse/NNS1-3671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): create fiat value display component for inputs

- .config/spellcheck.dic
- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/common/NewMaxButton.svelte
- frontend/src/lib/components/neurons/NnsStakeNeuron.svelte
- frontend/src/lib/components/ui/AmountInput.svelte
- frontend/src/lib/components/ui/Input.svelte
- frontend/src/lib/components/ui/InputWithError.svelte
- frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
- frontend/src/tests/lib/components/ui/AmountInput.spec.ts
- frontend/src/tests/lib/modals/accounts/CkBTCTransactionModal.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsStakeNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/sale/ParticipateSwapModal.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/page-objects/AmountInput.page-object.ts
We want to display the USD value of a transaction being done in ICP. This PR follows up on #6599 and incorporates this new component in the `AmountInput`. Any component that uses it will automatically show the USD value. Displaying the balance or maximum value is already available but will be addressed in a follow-up PR, as it requires changes in the consumers.
https://github.com/user-attachments/assets/3ee55f1e-164b-4fc9-9232-e676b9d24029
[NNS1-3671](https://dfinity.atlassian.net/browse/NNS1-3671)
- Expose the newly added slot Gix component `Input` to the nns-dapp `Input`.
- Created a new version of `MaxButton` to be used until the designs for the `DayInput` are ready.
- Display `AmountInputFiatValue` in the newly added slot of `InputWithError`.
- Updated tests to check for the usd …
> feat(inputs): integrate USD value display in amount fields

- frontend/src/lib/components/ui/AmountInputFiatValue.svelte
- frontend/src/tests/lib/components/ui/AmountInputFiatValue.spec.ts
We want to handle invalid user inputs. The input already checks for the numeric type but users can still enter non-finite numbers. In this case we want to show a placeholder text to the user.
https://github.com/user-attachments/assets/cb03fc06-36c2-4d08-8760-d4a76ca23f0b
[NNS1-3671](https://dfinity.atlassian.net/browse/NNS1-3671)
- Validate user input and render placeholder for invalid values
- Added unit tests to cover invalid inputs
Not necessary
[NNS1-3671]: https://dfinity.atlassian.net/browse/NNS1-3671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(validation): handle non-finite numbers in amount inputs

- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/components/ui/ResponsiveTable.spec.ts
- frontend/src/tests/lib/modals/accounts/AddAccountModal.spec.ts
We want to stay up-to-date with the tooling for best practices and security reasons ([see related PR](https://github.com/dfinity/nns-dapp/pull/6020)).
Some tests broke after the upgrade, so this PR updates them to ensure they pass with the new setup.
- **ProjectsTable.spec.ts** – `runResolvedPromises` is no longer sufficient, likely due to animations. Using `advanceTimersByTime(500+)` resolves the issue.
- **ResponsiveTable.spec.ts** – After the upgrade, CSS expressions in the `style` attribute may include extra spaces, especially in manually composed styles. Adjusted the test to handle this.
- **AddAccountModal.spec.ts** – Added a wait to ensure the content is rendered before assertions run.
- Yes.
Not necessary.
> Svelte v5 test fix 3

- frontend/src/lib/components/transaction/TransactionFormFee.svelte
- frontend/src/tests/lib/components/transaction/TransactionFormFee.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
We want to hide extra zeros from the transaction transfer fee, as they do not provide any value to the users. The number of zeros being hidden depends on the token and its decimal part.
Before:
After:
[NNS1-3705](https://dfinity.atlassian.net/browse/NNS1-3705)
- Hide extra decimal zeros from transfer fee
- Update the unit tests to reflect the new expectations for the transfer fee.
Not necessary.
[NNS1-3705]: https://dfinity.atlassian.net/browse/NNS1-3705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(format): trim trailing zeros in transfer fee display

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/modals/neurons/SplitNnsNeuronModal.svelte
- frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/modals/neurons/SplitNnsNeuronModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SplitSnsNeuronModal.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
Similar to #6602, we want to implement client validation to check whether the value provided by the user for splitting a neuron is valid. If it is not valid, we will display a message below the input field instead of using a toast message.
In this PR, we address both flows: NNS and SNS for splitting neurons.
Before:
https://github.com/user-attachments/assets/756f468c-a134-462e-91da-8161642d8eae
After:
https://github.com/user-attachments/assets/291ae9e7-13d7-4eea-9ea8-f2da0796e6f6
[NNS1-3690](https://dfinity.atlassian.net/browse/NNS1-3690)
- Refactor `isValidInputForm` from a utility function to a type predicate. This change helps TypeScript recognize that `amount` is defined when `isValidInputForm` returns true.  
- Move the validation to the `split` closure for better clarity.  
- Remove …
> refactor(validation): adds inline error message for neuron split modal

- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
There was an outage when the `action` field from the `ProposalData` (from SNS Governance) cannot be parsed. There is an agent-js bug which makes the candid parsing fail. However, even if the candid parsing bug is fixed, it was unclear whether the NNS Dapp would be able to show the SNS proposal correctly if it's unaware of the new action variant (and `action` is decoded to null). This PR tries to prove that it indeed can, by removing any access to the `action` field.
- Remove `SnsProposalDataMap::actionData`
- Remove any access to `actionData`, which all happen to be dead code
- Stop converting `action` in `mapProposalInfo`
Note that after those changes, the only place `SnsAction` (from `@dfinity/sns`) is used is `frontend/src/lib/api/sns-dummy.api.ts`, which is for SUBMITTING proposals, …
> Removing anything related to SnsAction

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/NnsStakeNeuron.svelte
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
We want to inform users that the amount of ICP they are attempting to stake is invalid. We already do this for staking SNS tokens and for transactions.
Before:
https://github.com/user-attachments/assets/d921509d-e8b1-46c1-8a88-c4e5eb139cb6
After:
https://github.com/user-attachments/assets/ffdfa369-a330-4baf-be64-e20a4289f134
[NNS1-3688](https://dfinity.atlassian.net/browse/NNS1-3688)
- Adds front-end validation to the `NnsStakeNeuron` component
- Extends tests to verify that error messages are presented when the input is invalid.
[NNS1-3688]: https://dfinity.atlassian.net/browse/NNS1-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(validation): add ICP stake amount verification

- frontend/src/lib/constants/routes.constants.ts
- frontend/src/lib/derived/routes.derived.ts
- frontend/src/lib/utils/page.utils.ts
- frontend/src/tests/routes/app/accounts/layout.spec.ts
- frontend/src/tests/routes/app/neurons/layout.spec.ts
We don't want to expose the `/portfolio` in the navigation menu of the app to avoid multiple entries for the same page and improve data quality.
- Change relative link in the navigation bar from `/portfolio` to `/`.
- Update `pathForRouteId` to recognize `/` as a potential route to be used for the portfolio page.
- Update tests
Not necessary.
> refactor(nav): standardize portfolio route to root path

- frontend/src/lib/i18n/en.json
- frontend/src/tests/lib/components/accounts/WalletPageHeading.spec.ts
- frontend/src/tests/lib/components/common/HeadingSubtitleWithUsdValue.spec.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
We want to simplify the text in the exchange rate tooltip.
- Change copy for `token_price_source`
- Update tests to check against the translation key.
not necessary
> refactor(content): simplify exchange rate source text

- frontend/src/lib/i18n/en.json
The current [link](https://internetcomputer.org/docs/current/tokenomics/nns/neurons-fund) to the NF documentation is no longer correct so we want to replace it with a link to the new [learn hub](https://learn.internetcomputer.org/hc/en-us).
More info can be found [here](https://dfinity.slack.com/archives/C039M7YS6F6/p1742986063183969)
- Update link 
not necessary
> fix(docs): update neurons fund documentation link

- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.svelte
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.spec.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicItem.page-object.ts
Migrating from following by type to following by topic to improve neuron management.
In the new “Follow” modal, all topics will be displayed with the ability to select them for following in the next step.
This PR adds the component that will be used in the topic list. The full component structure can be found in the draft pr - https://github.com/dfinity/nns-dapp/pull/6610.
Currently **DEMO NOT WORKING** because of the missing aggregator update.
[Demo](https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/neuron/?u=7tjcv-pp777-77776-qaaaa-cai&neuron=a12652a79755ee2158248250b9038a35a87adbd53674d789b318bf024e1d2989)
1. `__featureFlags.ENABLE_SNS_TOPICS.overrideWith(true)`
2. Click `Follow Neurons` button on the sns neuron detail page. …
> sns topics: Topic item component

- frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte
- frontend/src/tests/lib/pages/SnsNeuronDetail.spec.ts
- frontend/src/tests/page-objects/SnsNeuronDetail.page-object.ts
- frontend/src/tests/page-objects/SnsNeuronFollowingCard.page-object.ts
- frontend/src/tests/page-objects/SnsTopicDefinitionsModal.page-object.ts
Migrating from following by type to following by topic to improve neuron management.
To help users better understand how SNS topics are structured - specifically, which types belong to which topics - a new modal has been added. Here, we make the "View topic definitions" button open the modal.
- Replace the link with the button.
- Open the modal on click.
- Added.
https://github.com/user-attachments/assets/32fcdbd4-1c9f-40f2-b28d-1e2edd2c6f9e
Not yet.
> Show sns topic definitions

- frontend/src/routes/(app)/(u)/(detail)/proposal/+layout.svelte
- frontend/src/tests/routes/app/proposals/layout.spec.ts
This PR follows up on #6632 by utilizing the new derive store to redirect the user to the correct page after clicking the back button on the layout.
- Implement back navigation in Proposal page layout.
- Added unit test
Not necessary
[NNS1-3638]: https://dfinity.atlassian.net/browse/NNS1-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(navigation): implement dynamic back navigation for Proposal page

- frontend/src/lib/components/transaction/TransactionFromAccount.svelte
In #6606, we moved the account balance below the input field when the appropriate component was used. To do this, we had to hide the original balance from the header. However, there was a bug in the condition that caused the string `Source` to be displayed twice. This PR addresses the issue.
Before:
After:
- Fix the condition to display the text within the `TransactionFromAccount` component.
not necessary
> fix(ui): remove duplicate source text in transaction form

- frontend/src/lib/components/ui/IcpExchangeRate.svelte
- frontend/src/tests/lib/components/portfolio/TotalAssetsCard.spec.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/components/ui/IcpExchangeRate.spec.ts
- frontend/src/tests/lib/components/ui/UsdValueBanner.spec.ts
After the upgrade of Svelte5, the IcpExchangeRate is wrongly rendering when a child is not displayed because of a meadia query.  It seems that Svelte5 preservers newlines as text nodes while v4 was not doing this. 
In this PR, we fix the regression by removing the whiltespace between the elements.
Before:
After:
- Remove new line from `TooltipIcon` child.
- Updated tests to not expect an empty text node. Note, that we rely on styling to make the two text nodes look the way they look on mobile devices.
Not necessary.
> fix(ui): resolve svelte5 whitespace rendering in exchange rate tooltip

- frontend/src/lib/derived/routes.derived.ts
- frontend/src/routes/(app)/(u)/(detail)/proposal/+layout.svelte
- frontend/src/tests/lib/derived/routes.derived.spec.ts
- frontend/src/tests/routes/app/proposals/layout.spec.ts
The Proposal page includes a back button in its layout. Currently, there are two ways to access this page:  
-  From the Proposals page for all proposals.  
-  From the Launchpad page to create a new SNS proposal.  
We will introduce a third option when the Portfolio page displays the Proposal cards. We aim to implement a mechanism similar to #6543 to determine the appropriate navigation based on how the user accessed the page.  
A follow-up PR will utilize this new store from the route's layout.
- A new derived store will define the navigation path back from the Proposal page.
Add unit tests for the new derived store.
not necessary.
[NNS1-3638]: https://dfinity.atlassian.net/browse/NNS1-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> feat(navigation): add contextual back navigation for proposals

- frontend/package-lock.json
As mentioned [here](https://dfinity.slack.com/archives/C01S03NBM7S/p1743493126160569)
> There is a vulnerability in an npm lib used in hw wallet cli and nns dapp. It affects tar-fs and allows link following / path traversal if a maliciously crafted tar file is extracted. I assigned low risk because IIUC we don't extract malicious tar files.
[SCAVM-1127](https://dfinity.atlassian.net/browse/SCAVM-1127)
- Run `npm audit` to validate the vulnerability.
- Run `npm audit fix` to upgrade the version of the dependency.
- Pipeline should pass as before.
Not necessary.
[SCAVM-1127]: https://dfinity.atlassian.net/browse/SCAVM-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(deps): update tar-fs to patch security vulnerability

- frontend/src/lib/api/proposals.api.ts
- frontend/src/tests/lib/api/proposals.api.spec.ts
For the upcoming SNS proposals on the Portfolio page, we want to display these proposals along with their SNS icons. To achieve this, we need to disable the `omitLargeFields` flag in the request. This flag was introduced in #5187 to address issues with payloads that are too large when using filters on the `/proposals` page. This PR adds a flag to request the entire payload. Since it will be used to fetch proposals related to the topic `SnsAndCommunityFund`, it seems safe.
Note: In the past, issues arose when the payload exceeded approximately 3MB (3145728 bytes). Our current payload is around 60k, which would allow for up to 50 proposals, while the estimate is to have no more than 5 at a time.
- Exposes flag in `queryProposals`.
- Adds unit test to check that property is part of request …
> feat(api): add option to include large proposal fields

- scripts/nns-dapp/download-ci-wasm
- scripts/sns/aggregator/release-template
I had to debug the scripts and fix these small issues before I could use the ./scripts/sns/aggregator/release-template script.
* scripts/nns-dapp/download-ci-wasm now also downloads sns_aggregator.wasm.gz, now just the nns-dapp.
* use the correct init argument during the SNS Aggregator upgrade proposal generation.
> fix(sns_aggregator_release): Small fixes to make the release smoother

- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/lib/utils/sns-topics.utils.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/lib/utils/sns-topics.utils.spec.ts
To simplify handling of SNS tokens (e.g., using them as object keys), we transform them from the backend type (e.g. `{ DappCanisterManagement: null }`) into a string (e.g. "DappCanisterManagement").
Initially, the transformation function was added to the aggregator DTO utils, but since it will be widely used for reading/writing topics via the API, it makes sense to move it to the sns-topic utils.
- Rename and move dto-utils/`convertDtoToTopic` to sns-topic-utils/`snsTopicKeyToTopic`.
- Rename `getSnsTopicKey` to `snsTopicToTopicKey` to align function names.
- Moved.
!necessary.
> refactor: snsTopicKeyToTopic

- frontend/package-lock.json
- frontend/package.json
As mentioned [here](https://dfinity.slack.com/archives/C01S03NBM7S/p1743579132405449)
> The vite dev server, if exposed in the internal network could give access to files it is not supposed to. 
Additionally, I took the opportunity to upgrade all Vite-related dependencies to the latest version.
[SCAVM-1130](https://dfinity.atlassian.net/browse/SCAVM-1130)
- Run `npm audit` to validate the vulnerability.
- Run `npm i -d vite@latest` to upgrade to latest.
- Run `npm i -d vitest@latest` to upgrade to latest.
- Run `npm i -d @vitest/coverage-v8@latest` to upgrade to latest.
- Pipeline should pass as before.
Not necessary.
[SCAVM-1130]: https://dfinity.atlassian.net/browse/SCAVM-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(deps): update vite related dependencies to patch security vulnerability

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/routes/app/portfolio/page.spec.ts
We want to update the portfolio layout for users who are not signed in by hiding the `TotalAssetsCard`. This way, it only displays the `LoginCard` and any SNS cards if there are any swaps or proposals open.
https://github.com/user-attachments/assets/cae929a6-befa-453c-9bd6-2911f6974372
- Hide `TotalAssetsCard` when user is not signed in.
- Update size of the `LoginCard` based on the presence of the sns cards.
- Update unit tests expectations.
> refactor(portfolio): simplify pre-login page layout

- frontend/package-lock.json
- frontend/package.json
#6020 upgraded the nns-dapp to svelte@5. During this process, we directed the project to use a specific version of gix-components to ensure compatibility with the correct version of Svelte. Now that the upgrade is complete, we want to revert to pointing to the next version to easily incorporate the latest changes in gix-components into the project.
- Manually change the version in `package.json` to `next`.
- Run `npm i` to update `package-lock.json`.
- Not necessary.
Not necessary
> chore(deps): revert gix-components to next version

- frontend/src/tests/e2e/portfolio.spec.ts
[sns-demo](https://github.com/dfinity/snsdemo/pull/461) recently added a new ongoing swap to help develop features for the Portfolio page. End-to-end tests have become unreliable because we now have multiple cards on the Portfolio page that change every 5 seconds. Additionally, continuous integration can sometimes take longer, resulting in mismatched screenshots.
- Overwrite `setInterval` in Portfolio end-to-end tests with a no-op callback.
Not necessary.
> test(e2e): fix flaky carousel animations

- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
For the upcoming SNS proposals on the Portfolio page, we want to display these proposals in a specific card. The `Proposal` type is quite generic, so we will map it to a `CreateServiceNervousSystem` proposal that the card will consume. Additionally, we can remove the unnecessary fields.
- Adds a new utility to map the proposal to the card data.
- Adds unit tests for the utility functions.
- Manually tested along with other changes in #6590
Not necessary.
[NNS1-3638]: https://dfinity.atlassian.net/browse/NNS1-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portfolio): add SNS proposal card data mapper util

- rs/backend/src/assets.rs
- rs/backend/src/tvl.rs
- rs/sns_aggregator/src/assets.rs
- rs/sns_aggregator/src/fast_scheduler.rs
- rust-toolchain.toml
There is a new version of Rust. The automatic job #6661 fails due to some Clippy errors. This PR addresses the changes from #6661 and fixes those errors.
- Fork #6661 into this branch.
- Fix errors
Not necessary.
> chore(deps): update rust to 1.86.0

- frontend/package-lock.json
- frontend/package.json
Another week, anoter security issue in vite. Similarly to latest incidents (https://github.com/dfinity/gix-components/pull/610 and https://github.com/dfinity/gix-components/pull/614), we are not affected but, for the state of the art, let's bump vite to resolve [CVE-2025-31486](https://github.com/advisories/GHSA-xcj6-pq6g-qj4x).
- Bump vite v6.2.5
- Bumo related dev dependencies
> build: bump vite (CVE-2025-31486)

- frontend/src/lib/components/portfolio/NewSnsProposalCard.svelte
- frontend/src/lib/components/portfolio/VotesResult.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/components/portfolio/NewSnsProposalCard.spec.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
- frontend/src/tests/page-objects/NewSnsProposalCard.page-object.ts
We want to display NSN proposals for creating an SNS directly on the Portfolio page. A new card will be used to present this information, showing basic details about the proposal and the current voting status.
This initial PR creates the new component, which will later be utilized by the Portfolio page.
[NNS1-3637](https://dfinity.atlassian.net/browse/NNS1-3637)
Note: The differences in the remaining time copy are intentional to ensure consistency between the Portfolio cards.
Design reference:
Screenshots:
- New components `VotesResult` and `NewSnsProposalCard`
- New copy for the component
- New unit tests and page object for the new component.
- Tested in [devenv]() with other changes
Not necessary.
[NNS1-3637]: https://dfinity.atlassian.net/browse/NNS1-3637?atlOrigin=eyJpIjoiNWRkNTljNzYx …
> feat(portfolio): add SNS creation proposal card

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/BasePortfolioCard.page-object.ts
- frontend/src/tests/page-objects/LaunchProjectCard.page-object.ts
- frontend/src/tests/page-objects/NewSnsProposalCard.page-object.ts
- frontend/src/tests/page-objects/StackedCards.page-object.ts
Following up on #6663, we want to display the SNS proposals for creating a new SNS on the Portfolio page. This PR utilizes the new card component, `NewSnsProposalCard`, to showcase all the open SNS proposals provided through the props.
It sorts them into two groups: ongoing swaps and open proposals. Each group is then sorted by the duration until the deadline.
[NNS1-3637](https://dfinity.atlassian.net/browse/NNS1-3637)
- Compose list of cards for the `StackedCards` component, prioritizing ongoing swaps over NNS proposals for new SNSs.
- Unit tests for the new component.
Not yet.
[NNS1-3637]: https://dfinity.atlassian.net/browse/NNS1-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portfolio): integrate SNS proposal cards into stacked cards on the portfolio page

- frontend/src/lib/services/public/sns.services.ts
- frontend/src/tests/lib/components/launchpad/Proposals.spec.ts
- frontend/src/tests/lib/services/public/sns.services.spec.ts
For the upcoming SNS proposals on the Portfolio page, we want to display these proposals along with their SNS icons. To achieve this, we need to disable the `omitLargeFields` flag in the request. This PR follows up on the work done in #6647 and exposes the flag in the service.
The service lacked tests, so this PR adds the minimum necessary to ensure that the flag functions as intended while maintaining the previous behavior as the default.
- Exposes flag in `loadProposalsSnsCF`.
- Adds unit test to check that property is properly forwarded to `queryProposals`.
Not necessary
[NNS1-3638]: https://dfinity.atlassian.net/browse/NNS1-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(services): expose large fields flag for SNS proposals

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/pages/Portfolio.spec.ts
We want to display upcoming projects on the portfolio page. Specifically, we aim to show a card for open proposals to create a new SNS. These cards have to be sorted by `deadlineTimestampSeconds`.
- Sorts proposals in ascending order by `deadlineTimestampSeconds`.
- Adds tests to verify that proposals are sorted in the `StackedCards`.
Not necessary.
[NNS1-3638]: https://dfinity.atlassian.net/browse/NNS1-3638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portfolio): sort SNS proposals by deadline

- frontend/src/lib/api/sns-governance.api.ts
- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/types/sns.ts
- frontend/src/lib/utils/sns-topics.utils.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/lib/utils/sns-topics.utils.spec.ts
- frontend/src/tests/mocks/sns-topics.mock.ts
Followed up on the [ic-js PR](https://github.com/dfinity/ic-js/pull/882), using the cleaner way to import types from `@dfinity/sns`.
- Change SNS topics related type sources.
- Should pass.
Not necessary.
> Cleanup SnsTopic types

- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/types/sns.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
Followed up on the [setFollowing](https://github.com/dfinity/nns-dapp/pull/6646) API PR — this adds the service to set following by topics.
- New related to sns-topics types.
- New setFollowing service.
- Added.
Not necessary.
> Set following service

- frontend/src/lib/types/sns.ts
- frontend/src/lib/utils/sns-topics.utils.ts
- frontend/src/tests/lib/utils/sns-topics.utils.spec.ts
- frontend/src/tests/mocks/sns-neurons.mock.ts
Adds utility functions needed to support setting followings by topic. Their usage can be found in [this draft PR](https://github.com/dfinity/nns-dapp/pull/6610/files).
- getSnsTopicFollowings
- isSnsNeuronsAlreadyFollowing
- addSnsNeuronToFollowingsByTopics
- removeSnsNeuronFromFollowingsByTopics
- Added.
Not necessary
> Sns topic utils

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepNeuron.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepNeuron.svelte.spec.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicStepNeuron.page-object.ts
After selecting topics in the [first step](https://github.com/dfinity/nns-dapp/pull/6697), the user needs to enter a neuron ID. This PR adds the component that will be used as the second step in the follow by SNS Topics [modal](https://github.com/dfinity/nns-dapp/pull/6699).
- New component.
- Added.
Not yet.
> Neuron step in follow by Sns topics modal

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicFollowee.svelte
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.svelte
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepTopics.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepTopics.svelte.spec.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicFollowee.page-object.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicItem.page-object.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicStepTopics.page-object.ts
Adds the first step component to the "Follow SNS Neurons by Topic" modal, showing topics to follow and current follow state.
- Rename TopicFollowee props and callbacks to better align with other components.
- New component FollowSnsNeuronsByTopicStepTopics
- Added.
Not yet.
> Topics step in follow by Sns topics modal

- frontend/src/lib/components/portfolio/TotalAssetsCard.svelte
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/components/portfolio/TotalAssetsCard.spec.ts
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/TotalAssetsCard.page-object.ts
We want to optimize the display of the `TotalAssetsCard` based on the presence of StackedCards. When there are no Cards, we aim to maximize the horizontal space. However, when Cards are present, we want to maximize the vertical space.
With `StackedCards`:
Without `StackedCards`:
- Add conditional CSS styles when no cards are present.
- Adds unit tests to both the `TotalAssetsCard` and the `Portfolio` page based on the presence of SNS cards or not.
Not necessary.
[NNS1-3641]: https://dfinity.atlassian.net/browse/NNS1-3641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(portfolio): optimize total assets card layout 

- scripts/nns-dapp/release-beta
The `scripts/nns-dapp/release-beta` creates an Orbit proposal to release the nns-dapp to Beta. Voters should ideally review the proposal before casting their votes. Currently, the instructions for reviewing the proposal are as follows:
```
1. git fetch
2. git checkout $COMMIT
3. git merge-base --is-ancestor HEAD origin/main && echo OK || echo \"Commit is not on main branch!\"
4. ./scripts/docker-build
5. sha256sum nns-dapp.wasm.gz"
```
This is very helpful for understanding what is happening, but it is a bit cumbersome to operate since one has to copy and paste each line.
- Adds a one-liner with instructions to verify the proposal.
Not necessary.
> chore(scripts): simplify beta release verification steps

- frontend/package-lock.json
- frontend/src/tests/fakes/sns-governance-api.fake.ts
- frontend/src/tests/lib/components/proposal-detail/VotingCard/SnsVotingCard.spec.ts
- frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
In the scope of [NNS1-3666](https://dfinity.atlassian.net/browse/NNS1-3666), we need to filter proposals by topic. To achieve this, we must upgrade to the latest version of [ic-js](https://github.com/dfinity/ic-js/pull/886). The automatic job #6703 cannot upgrade the ic-js version to the latest because it introduced a new field in the response of `list_proposals`, which needs to be updated in the nns-dapp mock responses.
- Checked out #6703 and created a new branch.  
- Updated the response for the `list_proposals` mocks
- For now, tests should pass as before.
Not necessary
> chore(deps): bump ic-js and fix update list_proposals response structure

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/stores/busy.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte.spec.ts
As we’re switching from type-based to topic-based voting delegation, here we use the setFollowing API to remove user’s topic-based following directly from the topic description section.
- Add new busy screen initiator.
- Call setFollowing to remove the following.
- Updated.
Not yet.
> feat(sns-topics): Remove sns topic following

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte.spec.ts
As we’re switching from type-based to topic-based voting delegation, this adds a check to ensure that the user-entered neuron ID exists. The same approach is currently used for the NS-function based followings https://github.com/dfinity/nns-dapp/blob/8385e6a7130d9f5118362f85c9b61a551b2cb39b/frontend/src/lib/services/sns-neurons.services.ts#L613
- Calls querySnsNeuron before updating the following, to ensure the neuron exists.
- Updated.
Not yet.
> feat(sns-topics): Validate neuron ID

- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/lib/modals/sns/proposals/SnsFilterStatusModal.svelte
- frontend/src/lib/modals/sns/proposals/SnsFilterTypesModal.svelte
- frontend/src/tests/lib/modals/sns/proposals/SnsFilterStatusModal.spec.ts
- frontend/src/tests/lib/modals/sns/proposals/SnsFilterTypesModal.spec.ts
In the scope of [NNS1-3666](https://dfinity.atlassian.net/browse/NNS1-3666), we want to prepare the `SnsProposalsFilters` to support a new type of filter, the `SnsFilterTopicsModal`. This PR does the preliminary work of updating the components to Svelte 5, so the next PRs can focus on the new functionality rather than refactoring.
- Refactors `SnsProposalsFilters` to Svelte 5.
- Refactors `SnsFilterTypesModal` to Svelte 5.
- Refactors `SnsFilterStatusModal` to Svelte 5.
- Updated tests to check that cb `closeModal` is being called instead of event being forwarded.
- Tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Not necessary.
[NNS1-3666]: https://dfinity.atlassian.net/browse/NNS1-3666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
> refactor(filters): migrate SNS proposal filters to svelte 5

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte
- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
As part of the switch to topic-based voting delegation, we move error handling from the setFollowing service to the component. This allows us to show different error messages when users add or remove followings, instead of the same one.
- Added new error texts to have them inside the feature labels block.
- Moved the error handling.
- Updated.
Not yet.
> refactor(sns-topics): Move setFollowing error handling to component

- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte
- frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte
As part of the switch to topic-based voting delegation, this PR fixes an issue where the modal could only be opened once due to the modal value in [SnsNeuronModals](https://github.com/dfinity/nns-dapp/blob/950641f6bc5626a0821d29e50f37aac7e5a51693/frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte#L48) not being reset. Now it properly resets by calling `closeModal()` callback on `nnsClose` event of the Modal .
- Call `closeModal` on `nnsClose` event.
Not yet.
> fix(sns-topics): Fix close event

- frontend/src/lib/utils/sns-topics.utils.ts
- frontend/src/tests/lib/utils/sns-topics.utils.spec.ts
As part of the transition to **topic-based voting delegation**, this updates the `getTopicInfoBySnsTopicKey` util to accept a simplified argument — just a list of topics.
Although this util isn’t currently used in the UI, it will be used in a new derived store to determine which topic should be displayed on the proposal details page.
[Jira Ticket → NNS1-3677](https://dfinity.atlassian.net/browse/NNS1-3677)  
[Live Demo](https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/)
- Refactoring.
- Updated.
Not yet.
> refactor(sns-topics): Change getTopicInfoBySnsTopicKey arguments

- frontend/src/lib/stores/sns-filters.store.ts
- frontend/src/lib/types/filters.ts
- frontend/src/tests/lib/stores/sns-filters.store.spec.ts
We want to enable users to filter SNS proposals by topic. This filtering will be saved in local storage to enhance the user experience. This PR extends the `sns-filters.store` to support filtering by topic. Follow-up PRs will utilize this new entry in the store to filter proposals and update the store based on user interactions with the new topic filter modal.
- Extends `sns-filters.store` with `setTopics ` and `setCheckTopics`.
- Adds new tests to cover the latest entries in the store.
Not necessary.
> feat(store): add topic filtering support to SNS filters

- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/types/filters.ts
- frontend/src/tests/lib/modals/common/FilterModalTest.svelte
The `FilterModalTest` is a utility component used to test the `FilterModal` component. To migrate the latter to utilize the existing `FilterModal.page-object`, we first need to enhance this utility component. Additionally, this PR refactors it to make use of Svelte 5.
- Refactors `FilterModalTest` to Svelte 5.
-  Moves types to a central location for use by both `FilterModal` and `FilterModalTest`.
- Tests should pass as before.
Not necessary.
> refactor(tests): exposes more from FilterModal in FilterModalTest

- frontend/src/tests/lib/modals/common/FilterModal.spec.ts
- frontend/src/tests/lib/modals/common/FilterModalTest.svelte
- frontend/src/tests/page-objects/FilterModal.page-object.ts
Follow up on #6730 to migrate tests to utilize the existing page object. This will simplify the addition of more test cases later to cover the changes required for the new SNS filter modal for topics.
- Refactors `FilterModal` tests to utilize the existing page object.  
- Extends `FilterModalTest` with the necessary events.
- Adds a new test to cover the existence of `Separator` based on props.
Not necessary.
> refactor(tests): migrate filter modal tests to page object pattern

- frontend/src/lib/modals/common/FilterModal.svelte
Similar to #6730, this PR cleans up and migrates the `FilterModal` component to Svelte 5. This update simplifies the introduction of the new changes required for the proposals filter and the SNS topics filter.
- Migrates `FilterModal` to Svelte 5 syntax.
- Should pass as before
Not necessary.
> refactor(modal): migrate filter component to new simplified syntax

- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/types/filters.ts
- frontend/src/tests/lib/modals/common/FilterModal.spec.ts
The new filter for SNS proposals by topic needs to display separators between the options:  
-  Between critical topics and non-critical topics.
-  Between non-critical topics and the custom filter for proposals without a topic.
- Extends `FIlterModal` to display additional separators based on conditions.
- Adds unit tests to check the logic for the separators.
Not necessary.
> feat(proposals): add conditional separators to FilterModal

- frontend/src/lib/services/sns-neurons.services.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
As part of the transition to **topic-based voting delegation**, this PR adds a new service `removeNsFunctionFollowees` to remove all followings for a specified NS function.  
It will be used later to handle unfollowing the "Catch-all" function.
[Jira Ticket → NNS1-3744](https://dfinity.atlassian.net/browse/NNS1-3744)  
https://github.com/user-attachments/assets/297ceff7-c9ab-4278-b075-9560f376fee5
- Add new service `removeNsFunctionFollowees `.
- Added.
Not yet.
> (sns-topics): Remove NSfunction followees service

- frontend/src/lib/modals/common/FilterModal.svelte
- frontend/src/lib/modals/sns/proposals/SnsFilterTopicsModal.svelte
- frontend/src/tests/lib/modals/sns/proposals/SnsFilterTopicsModal.spec.ts
We want users to be able to filter proposals by topic. This PR introduces a new modal component similar to `SnsFilterStatusModal` and `SnsFilterTypesModal`. It uses the `FilterModal` component to display a list of topics, enabling users to select which ones they want to filter out.
- New modal to filter proposals by topic.
- Unit tests for the new component
Not necessary.
> feat(proposals): add SNS proposal topic filter modal

- frontend/src/lib/components/proposal-detail/ProposalSystemInfoEntry.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalSystemInfoSection.svelte
- frontend/src/tests/lib/components/sns-proposals/SnsProposalSystemInfoSection.spec.ts
- frontend/src/tests/page-objects/KeyValuePair.page-object.ts
- frontend/src/tests/page-objects/SnsProposalSystemInfoSection.page-object.ts
As part of the transition to **topic-based voting delegation**, this PR adds topic information to the proposal page.
[Jira Ticket → NNS1-3677](https://dfinity.atlassian.net/browse/NNS1-3677)  
[Live Demo](https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/)
- Display topic info on the page.
- Update KeyValuePair PO to getInfoText.
- Verify that the topic is rendered.
Not yet.
> (sns-topics): Display sns topic info on proposal page

- frontend/src/lib/stores/sns-unsupported-filter-by-topic.store.ts
- frontend/src/tests/lib/stores/sns-unsupported-filter-by-topic.store.spec.ts
We want users to filter proposals by topic; however, not all SNS may have upgraded to the latest version, so not all will support this feature. Therefore, the canister added a new field to the [response](https://github.com/dfinity/ic/blob/579b8ba3a31341f354f4ddb3d60ac44548a91bc2/rs/sns/governance/canister/governance.did#L383) that can be used to determine which filter to display to the user: topics or types.
This PR introduces a new store to track those projects that don't support yet this new API.
Note: As of today, most existing projects support the new API. The approach is to track those that do not support it and update the UI accordingly.
- New store to track a list of all sns that don't support the new API.
- Unit tests for …
> feat(proposals): add SNS topic filtering support store

- frontend/src/lib/services/public/sns-proposals.services.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
Following up on #6740, we want to use the new store to track projects that do not support the new API for listing proposals by topic. This will later be used by the `SnsProposalsFilter` component to determine which filter to display: Topics or Types.
- Track projects that do not support the new API in the `unsupportedFilterByTopicCanistersStore` using their rootCanisterId.
- Unit tests to cover the new logic in the service.
Not necessary.
> feat(proposals): track SNS projects not supporting topic filter

- frontend/src/lib/services/sns-filters.services.ts
- frontend/src/tests/lib/services/sns-filters.services.spec.ts
We want to track the topics filter for SNS proposals in the same way we track other filters, such as types and status. The store was already updated in #6732. This PR initializes the filter similarly to the `topics` filter, providing a default value when the store lacks any value. A follow-up PR will load the store from local storage, ensuring a better user experience.
- Sets the default value for the topics field in the sns `snsFiltersStore` when no filter is defined.
- Adds a test for the existing code regarding the default value of the `type` filter.  
- Adds tests for the new `topics` filter.
Not necessary.
Next PR: #6745
[NNS1-3666]: https://dfinity.atlassian.net/browse/NNS1-3666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …
> feat(proposals): initialize default topic filter state

- frontend/src/lib/components/universe/SelectUniverseList.svelte
- frontend/src/lib/constants/canister-ids.constants.ts
- frontend/src/lib/stores/sns-aggregator.store.ts
- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/tests/lib/stores/sns-aggregator.store.spec.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
A new SNS has been discontinued. Since we do not yet have a long-term solution for the nns-dapp, we will apply the same approach used for the first project discontinuation.
This PR refactors the existing code to handle a list rather than a single element.
- Create a list of discontinued projects.  
- Move these projects to the bottom of the tokens and neurons table.  
- Rename the token or project for better visibility.  
- Update tests to check for multiple discontinued projects.
Not necessary.
> feat(sns): handle discontinued project

- frontend/src/lib/services/public/sns-proposals.services.ts
- frontend/src/lib/services/sns-filters.services.ts
We want to keep our codebase clean by removing unused functions and outdated to-dos.
- Removes `registerVoteDemo`, which was added in #1756 and has not been used for a long time.  
- Removes the `TODO` from #4142, as it is no longer applicable since we now define default values for the filters.
- Removing the untested code is unnecessary.
Not necessary.
> chore(cleanup): remove unused code

- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.svelte
Due to `preventDefault`, clicking on the visual part of the checkbox in the topic item component didn’t update its visible state.
- Remove preventDefault property.
**Before**
https://github.com/user-attachments/assets/45d2a11e-bce8-42c0-b2d0-76681cc1a3c7
**After**
https://github.com/user-attachments/assets/ad67d05f-e6de-4479-b565-8a6c6177d116
Not necessary.
> feat(sns-topics): Fix checkbox selection

- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
We want to track the topics filter for SNS proposals in the same way we track other filters, such as types and status. 
This PR creates a new utility to generate a list of filters based on existing topics and persisted filters. The filters are sorted according to the following logic:
-  First, critical topics are sorted alphabetically.
-  Second, non-critical topics are sorted alphabetically.
-  Lastly, a special filter shows all proposals without a topic.
- New utility to create a list of filters from topics and saved filters. If there are no topics, the filter list will be empty.
- Unit tests for this new util.
Not necessary.
Prev. PR: #6744 | Next PR: #6746
[NNS1-3666]: …
> feat(proposals): add sorted topic filter list util

- frontend/src/lib/services/sns-filters.services.ts
- frontend/src/tests/lib/services/sns-filters.services.spec.ts
We want to track the topics filter for SNS proposals just as we track other filters, such as `types` and `status`. This PR utilizes the utility created in #6745 to load the filters when the user loads the application.
- Load the SNS proposals and filter topics similar to the types.
- Add a unit test for loading the topics.
Not necessary.
Prev. PR: #6745
> feat(proposals): load topic filters on application start

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepTopics.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepTopics.svelte.spec.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicModal.page-object.ts
- frontend/src/tests/page-objects/FollowSnsNeuronsByTopicStepTopics.page-object.ts
As part of the transition to **topic-based voting delegation**, this PR adds navigation to and from the "Deactivate Catch-all" step. 
[Jira Ticket → NNS1-3744](https://dfinity.atlassian.net/browse/NNS1-3744)  
https://github.com/user-attachments/assets/acd4be1d-1a37-4416-b709-3674fb4db3d5
- Display "Deactivate catch all" button when catchAllLegacyFollowings present.
- Provide navigation to "Deactivate catch all" step and back.
- Added.
Not yet.
> feat(sns-topics): Display deactivate catch all step

- frontend/src/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.svelte
- frontend/src/tests/lib/components/sns-neuron-detail/SnsNeuronFollowingCard.spec.ts
As part of the transition to topic-based voting delegation, this PR introduces minor updates to the "Voting Delegation" section to align with the UI design.
- Do not display legacy followings when topics are available.
- Always display the link to topic definitions when topics are available.
| Collapsed | Expanded |
| <img width="786" alt="image" src="https://github.com/user-attachments/assets/ad734c2c-a2ef-476a-8205-1c07a54d79f5" /> | <img width="783" alt="image" src="https://github.com/user-attachments/assets/733952ce-8c6e-4b7e-b02b-2946b4c3d583" /> | 
- Add the visibility logic for the block elements.
- Added.
Not necessary.
> (sns-demo): Adjusting sns-following card content

- frontend/src/lib/derived/sns-topics.derived.ts
- frontend/src/tests/lib/derived/sns-topics.derived.spec.ts
For the upcoming "Following by Topic" feature in SNS projects, not all projects currently support topic filtering. Therefore, we want to create a derived store that indicates whether a specific project supports this feature. 
The conditions for a project to support it are:
* The feature flag is enabled.
* The SNS aggregator returns topics for the project.
* The governance canister of the SNS supports filtering by topics.
- New derived store
- Unit tests for the derived store.
Not necessary.
> feat(store): add SNS topic feature support detection

- frontend/src/lib/components/ui/Highlight.svelte
- frontend/src/lib/constants/stores.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/ui/Highlight.spec.ts
- frontend/src/tests/page-objects/Highlight.page-object.ts
We want to display special messages to users to notify them of new features in the nns-dapp. These messages should appear only once. After closing them, they should be saved locally on the device and not shown again.
This PR introduces a new component, `Highlight`, designed for this purpose. The logic for when and where to display it will be determined by the component's consumers.
On mobile devices, the component will be displayed at the center top, while on tablet and desktop devices, it will appear at the bottom right.
[NNS1-3749](https://dfinity.atlassian.net/browse/NNS1-3749)
- Add a new component, `Highlight`, to display a one-time device message.
- Unit tests for the component.
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/) …
> feat(ui): implement Highlight component for one-time announcements

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/sns-proposals/SnsProposalsFilters.svelte
- frontend/src/tests/lib/components/sns-proposals/SnsProposalsFilters.spec.ts
- frontend/src/tests/page-objects/SnsProposalFilters.page-object.ts
We want users to filter proposals for a specific project by topic. To achieve this, a new button will appear on the proposals page, displaying a modal with all available topics for filtering.
This button will be visible only if:
-  The feature flag is enabled
-  The SNS aggregator returns topics for the specific project
-  The SNS Governance canister supports listing proposals by topic
https://github.com/user-attachments/assets/ceab85d5-13ec-48fe-b82d-e999ca82b851
- Conditionally render button to open topics modal.
- Show `SnsFilterTopicsModal` if topics modal button was clicked.
- Added tests to check that appropriate buttons is displayed.
- Rename some methods returning page-objects to be consistent.
[NNS1-3666]: …
> feat(proposals): integrate sns topic filtering button and modal

- frontend/src/routes/+layout.svelte
The Highlight component was [integrated](https://github.com/dfinity/nns-dapp/pull/6766) without the tutorial link to avoid blocking progress. This PR adds the missing URL.
- Add tutorial link.
- Verified locally that the link works. It currently leads to a blank page, as the tutorial hasn’t been published yet.
Not necessary.
> i18n(sns-topics): Add tutorial link

- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte.spec.ts
This PR improves the user experience when attempting to add a voting delegation that has already been set.
Previously, if a delegation already existed for the selected topic(s) and the entered neuron ID, the user encountered a confusing error message:  
**"There was an error while adding a followee. topic_following must contain at least one element."**
This PR handles that case explicitly and displays a more descriptive message:  
**"A voting delegation for the selected topic(s) and the entered neuron ID has already been set."**
- Catch and display already-following error.
- Added.
- Verified locally that it works.
https://github.com/user-attachments/assets/26d4658b-d224-44e6-b0cf-9bddf4ac4638
Not necessary.
> Sns topics/already following error

- frontend/src/lib/derived/network-economics.derived.ts
- frontend/src/tests/lib/derived/network-economics.derived.spec.ts
We want to start using the minimum dissolve delay from the API instead of the hardcoded value `NNS_MINIMUM_DISSOLVE_DELAY_TO_VOTE`. This change is necessary because the value may change in the near future, and we want the application to respond accordingly.
This first PR introduces a store that retrieves this value from the network economics API.
It defaults to the existing value while the API defines it: [thread](https://dfinity.slack.com/archives/C039M7YS6F6/p1746198021862419?thread_ts=1746197917.500179&cid=C039M7YS6F6).
[NNS1-3762](https://dfinity.atlassian.net/browse/NNS1-3762)
- Derived store to expose the `neuronMinimumDissolveDelayToVoteSeconds` value.
- Adds unit tests.
Not yet.
[NNS1-3762]: https://dfinity.atlassian.net/browse/NNS1-3762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> feat(store): add minimum dissolve delay from network economics

- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/derived/icrc-universes.derived.ts
- frontend/src/lib/utils/sns-proposals.utils.ts
We want to upgrade TypeScript to at least version `5.5`, as it introduced significant improvements to [inferred type predicates](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates).
Note: We cannot upgrade to the latest version yet because TypeScript ESLint is lagging behind.
- Bump TS to 5.5  
-  Remove a few instances of filter-type assertions that are no longer required.
- Pipeline should pass as before.
Not necessary.
> chore(deps): bump typescript to 5.5

- frontend/src/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.svelte
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepTopics.svelte.spec.ts
Currently, there is a way to skip the confirmation step for the "Catch-all" legacy following by clicking the **X icon** on the "Catch-all" following tag instead of using the **"Deactivate catch-all"** button. This is not the desired flow.
[NNS1-3791](https://dfinity.atlassian.net/browse/NNS1-3791).
- Removed the ability to delete the "Catch-all" legacy following using the X icon on its tag, in order to enforce the confirmation step.
- Added.
- Verified locally that the button is not being rendered.
Not necessary.
[NNS1-3791]: https://dfinity.atlassian.net/browse/NNS1-3791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(sns-topics): Hide remove button from the legacy followee tag

- frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte
- frontend/src/lib/modals/sns/neurons/SnsTopicDefinitionsModal.svelte
- frontend/src/tests/lib/modals/sns/neurons/SnsTopicDefinitionsModal.svelte.spec.ts
We want to apply the same sorting used for the proposals filter #6745 in other parts of the application. This requires that consumers of the list of topics retrieve them from the derived store `createSnsTopicsProjectStore` instead of directly from the topics store.
This PR prepares the component to consume this store, so once the store returns the sorted topics, they will be automatically used. Additionally, it has been migrated to Svelte 5.
[NNS1-3792](https://dfinity.atlassian.net/browse/NNS1-3792)
- Replace direct access to `snsTopicsStore` with `createSnsTopicsProjectStore`.  
- Refactor the component to use runes instead of the reactive syntax `$:`.
- Tests should pass as before since there were no functional changes.
Not necessary.
[NNS1-3792]: …
> refactor(topics): use derived store for topic list access

- frontend/package-lock.json
- frontend/package.json
Upgrades vite to handle security vulnerability.
[GHSA-859w-5945-r5v3](https://github.com/advisories/GHSA-859w-5945-r5v3)
[SCAVM-1177](https://dfinity.atlassian.net/browse/SCAVM-1177)
- Run `npm run vite@latest`
Not necessary
[SCAVM-1177]: https://dfinity.atlassian.net/browse/SCAVM-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): upgrade vite to 6.3.5 to patch security vulnerability

- frontend/src/lib/derived/sns-topics.derived.ts
- frontend/src/tests/lib/derived/sns-topics.derived.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsTopicDefinitionsModal.svelte.spec.ts
We want to apply the same sorting used for the proposals filter #6745 in other parts of the application.
This PR implements the sorting logic directly in the derived store. Since there is no need to retain the original data, we can apply it directly to the store and avoid duplication.
The sorting logic is as follows:
- First, critical topics are sorted alphabetically.
- Second, non-critical topics are sorted alphabetically.
[NNS1-3792](https://dfinity.atlassian.net/browse/NNS1-3792)
https://github.com/user-attachments/assets/0660382f-3027-4f7b-b32f-c5dc0e42bfa5
- Introduce sorting logic to `createSnsTopicsProjectStore`.
- Add test to validate new sorting logic.
- Fix existing tests to easily visualize sorting.
- Tested in beta.
Not necessary.
[NNS1-3792]: …
> feat(topics): implement topic priority sorting in store

- frontend/src/lib/utils/sns-proposals.utils.ts
- frontend/src/tests/lib/utils/sns-proposals.utils.spec.ts
With the introduction of sorting topics directly in the derived store in #6788, it is no longer necessary to sort them before providing them to the filters on the proposals page.
-  Removed the sorting operation from `generateSnsProposalTopicsFilterData`.
-  Removed outdated test since sorting no longer occurs at the utility level.
-  [ ] Add entry to changelog (if necessary). 
Not necessary.
> refactor(proposals): eliminate duplicate sort operation

- frontend/src/lib/components/neuron-detail/NnsNeuronPageHeading.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronRewardStatusAction.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronVotingPowerSection.svelte
- frontend/src/lib/components/neurons/NnsLosingRewardsNeuronCard.svelte
- frontend/src/lib/components/neurons/NnsNeuronCardTitle.svelte
- frontend/src/lib/derived/neurons.derived.ts
- frontend/src/lib/modals/neurons/ChangeBulkNeuronVisibilityForm.svelte
- frontend/src/lib/pages/NnsNeurons.svelte
- frontend/src/lib/stores/neurons-table-order-sorted-neuron-ids-store.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/derived/network-economics.derived.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
- frontend/src/tests/mocks/network-economics.mock.ts
We want to start using the minimum dissolve delay from the API instead of the hardcoded value `NNS_MINIMUM_DISSOLVE_DELAY_TO_VOTE`. 
This first PR is a follow-up of #6781 and updates an existing util and all its consumers to use the new store instead of using the local constant.
[NNS1-3762](https://dfinity.atlassian.net/browse/NNS1-3762)
- Update `hasEnoughDissolveDelayToVote` to expect the dissolve delay.  
- Update `soonLosingRewardNeuronsStore` to provide the dissolve delay to `hasEnoughDissolveDelayToVote`.  
- Update `getNeuronTagsUnrelatedToController` to provide the dissolve delay to `hasEnoughDissolveDelayToVote`.
- Update unit tests to satisfy the new API.
- Change `neuronMinimumDissolveDelayToVoteSeconds` in `mockNetworkEconomics` to replicate the former behavior with the …
> refactor(utils): migrate to network economics minimum dissolve delay

- .config/spellcheck.dic
- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/FollowNnsTopicSection.svelte
- frontend/src/lib/components/neurons/FollowTopicSection.svelte
- frontend/src/lib/components/sns-neuron-detail/FollowSnsTopicSection.svelte
- frontend/src/tests/lib/components/neurons/EditFollowNeurons.spec.ts
- frontend/src/tests/lib/components/neurons/FollowTopicSection.spec.ts
We have an issue with the "Add Followee" button, which becomes partially hidden after adding a followee (#6715).
This problem relates to how Svelte calculates dynamic spaces for our `Collapsible` component.  As this flow will be change in a near future to to use topic following similar to how the SNS governance is handled, the propose solution is to force `Collapsible` to re-calculate its height by updating one prop.
Before:
https://github.com/user-attachments/assets/e7a5d55c-56d6-41de-981c-e9a54d0c67ce
After:
https://github.com/user-attachments/assets/1d12ed49-3f3a-4494-ae45-925ab5f59d69
Closes #6715.
- Temporarily change a prop to retrigger the height calculation.
- Refactor to Svelte 5.
- Update unit tests
- Tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.df …
> fix(ui): add followee button visibility after addition

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/portfolio/StackedCards.svelte
This PR follows up on #6798 and introduces a swiping effect for touch devices for the `StackedCard` component, making navigation easier on mobile devices.
https://github.com/user-attachments/assets/3a6337ed-57d4-4503-8cb0-13d7eedfc33a
- Introduce a swipe gesture to navigate back and forth within the stacked cards component.
- There are no logical changes, so tests should pass as before.  
- I manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/) on my mobile by following the steps outlined [here](https://www.notion.so/dfinityorg/NNS-dapp-on-DevEnv-2882138a87fa45c39bf0966591c3dd73#929a5ccd7edd4b428efbc765aedf4d84).
-  [x] Add an entry to the changelog (if necessary). 
[NNS1-3641]: …
> feat(portfolio): add swipe navigation to stacked cards

- frontend/src/lib/components/neurons/NeuronsTable/NeuronVoteDelegationCell.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/neurons-table.ts
- frontend/src/tests/page-objects/NeuronVoteDelegationCell.page-object.ts
To improve the overview of a user’s vote delegation state, it’s planned to display the delegation status icon directly in the neuron table by adding a new column: “Vote Delegation” (see screenshot).
This PR adds a new component that will be used as the cell content for this column in both the NNS and SNS tables.
[Draft MVP PR](https://github.com/dfinity/nns-dapp/pull/6802/files)
[Demo](https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/)
- Add voteDelegationState to TableNeuron type.
- New `NeuronVoteDelegationCell` component.
- Only PO is created. The spec will be added later.
Not necessary.
> feat(delegation-state-column): New NeuronVoteDelegationCell component

- frontend/src/lib/components/neurons/NeuronsTable/NeuronActionsCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronDissolveDelayCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronIdCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronMaturityCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronStakeCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronStateCell.svelte
- frontend/src/lib/components/neurons/NeuronsTable/NeuronsTable.svelte
Since changes are planned for some NeuronsTable components, it’s a good opportunity to migrate them to Svelte 5.
- Change neuron table components to svelte 5 syntax.
- Should pass.
Not necessary.
> refactor: Migrate NeuronsTable components to svelte 5

- frontend/src/lib/utils/neurons-table.utils.ts
- frontend/src/tests/lib/utils/neurons-table.utils.spec.ts
To improve the overview of a user’s vote delegation state, it’s planned to display the delegation status icon directly in the neuron table by adding a new column: “Vote Delegation” (see screenshot).
This PR adds a new util to calculate the vote delegation status.
[Draft MVP PR](https://github.com/dfinity/nns-dapp/pull/6802/files)
[Demo](https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/)
- Add getSnsNeuronVoteDelegationState util.
- Added.
Not necessary.
> feat(delegation-state-column): getSnsNeuronVoteDelegationState util

- frontend/src/lib/pages/Portfolio.svelte
We aim to display proposals for new SNS projects on the Portfolio page that were approved before the swap begins. This PR prepares the Portfolio page to introduce the pre-swap cards by migrating to runes.
[NNS1-3639](https://dfinity.atlassian.net/browse/NNS1-3639)
-  Refactored the page to use runes.
-  Tests should pass as before since there were no logical changes.
-  [ ] Add an entry to the changelog (if necessary)
Not necessary.
[NNS1-3639]: https://dfinity.atlassian.net/browse/NNS1-3639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(portfolio): migrate page component to runes

- frontend/src/lib/api/icrc-index.api.ts
- frontend/src/tests/lib/api/icrc-index.api.spec.ts
We want to utilize the new function exposed by ic-js to [list subaccounts](https://github.com/dfinity/ic-js/pull/906), enabling users to easily retrieve the list of all subaccounts for an ICRC canister.
Note: This PR introduces a new canister object based on the NextGeneration Index canister. The existing one will be deprecated eventually, so a follow-up PR will migrate the existing methods to the new canister.
[NNS1-3793](https://dfinity.atlassian.net/browse/NNS1-3793)
- Add a new canister object for the Next Generation IndexCanister.  
- Add an API function to call `list_subaccounts`.
- Add unit tests for the API function.
Not necessary.
[NNS1-3793]: https://dfinity.atlassian.net/browse/NNS1-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> feat(api): add new method listSubaccounts

- frontend/src/lib/components/portfolio/StackedCards.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/StackedCards.spec.ts
- frontend/src/tests/page-objects/StackedCards.page-object.ts
The `StackedCards` component displays controls below the cards, allowing users to:  
1. Identify their current card in the total.  
2. Navigate between the cards.  
However, in scenarios with too many cards (projects), the dots may overflow. This PR introduces an alternative set of controls using buttons (previous and next) for card navigation.
https://github.com/user-attachments/assets/cb4c518c-2f31-4d86-a4bf-73f74e1d6852
- Add alternative controls when there are too many cards.
- Add a unit test for the new behavior.  
- Update existing tests to ensure that only one type of control is being rendered.
- Tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
Not necessary
[NNS1-3641]: …
> feat(portfolio): add alternative navigation controls to stacked cards

- frontend/src/lib/pages/SnsWallet.svelte
We aim to introduce changes to the `SnsWallet` component. This PR refactors the component using runes to simplify the addition of new features.
[NNS1-3793](https://dfinity.atlassian.net/browse/NNS1-3793)
- Refactor `SnsWallet` to use runes.
- All tests should pass as before since no logical changes were made.
-  [ ] Add an entry to the changelog (if necessary). 
Not necessary.
[NNS1-3793]: https://dfinity.atlassian.net/browse/NNS1-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(wallet): migrate SNS wallet to runes

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/StackedCards.page-object.ts
We want to display proposals for new SNS projects on the Portfolio page that were approved before the swap begins. This PR utilizes the new card introduced in #6811 to showcase adopted proposals for new projects.
The order for displaying cards within the stacked card component is as follows:
1. Ongoing swaps
2. Proposals for new projects
3. Adopted proposals for new projects.
[NNS1-3639](https://dfinity.atlassian.net/browse/NNS1-3639)
- Update Portfolio page to expected a new prop for adopted proposals.
- Sort adopted proposals based on the swap start.
- Unit tests for the new prop in the page.
- Unit tests for checking the sorting is applied to each group of cards.
Not yet.
[NNS1-3639]: https://dfinity.atlassian.net/browse/NNS1-3639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> feat(portfolio): integrate adopted SNS proposal cards

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/StackedCards.page-object.ts
- frontend/src/tests/routes/app/portfolio/page.spec.ts
We want to display proposals for new SNS projects on the Portfolio page that were approved before the swap begins. This PR follows #6822 and loads adopted proposals, passing them to the Portfolio page for display in the stacked card set.
https://github.com/user-attachments/assets/0969d4ab-764f-401e-8a74-c121fa35b9af
[NNS1-3639](https://dfinity.atlassian.net/browse/NNS1-3639)
- Retrieve the list of adopted proposals and provide them to the Portfolio page.
- Add a test to verify that the expected number of cards is displayed when passing one ongoing swap, one adopted SNS project proposal, and one open SNS project proposal.
[NNS1-3639]: https://dfinity.atlassian.net/browse/NNS1-3639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portfolio): load adopted SNS proposals for display

- frontend/src/lib/api/icrc-index.api.ts
- frontend/src/tests/lib/api/icrc-index.api.spec.ts
The ic-js library [introduced](https://github.com/dfinity/ic-js/pull/562) the next-generation version of ICRC index canisters. The nns-dapp was using the old implementation until the new one was introduced in #6815, which added a new method. The goal is to migrate existing methods to the next-generation version and deprecate the old one from ic-js.
- Migrate the `getLedgerId` API method to use the next-generation index canister.
- Update `getLedgerId` tests to use mocks and spies for the next-generation canisters.  
- Refactor `getTransactions` tests to follow the same structure as the other tests.
Not necessary.
> refactor(api): migrate getLedgerId to next-gen index canister

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/assets.rs
The Security Team has recommended introducing a Permissions Policy for the application to explicitly enable the necessary native features.
This is inspired by the [II configuration](https://github.com/dfinity/internet-identity/blob/39633b45d3aad1f0d3c92f90809b60fd35906625/src/internet_identity/src/http.rs#L93) but is configured for the nns-dapp.
The required permissions are:
-  Camera: for QR code flow.
-  Clipboard: for read and write access.
Note: Some features are not yet supported by major browsers, so we are receiving warnings.
[SECFIND-226](https://dfinity.atlassian.net/browse/SECFIND-226)
- Add a list of permissions to `security_headers`
- Manually tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
[SECFIND-226]: …
> feat(security): restrict native feature permissions

- frontend/src/lib/api/icrc-index.api.ts
- frontend/src/tests/lib/api/icrc-index.api.spec.ts
The ic-js library [introduced](https://github.com/dfinity/ic-js/pull/562) the next-generation version of ICRC index canisters. The nns-dapp was using the old implementation until the new one was introduced in #6815, which added a new method. The goal is to migrate existing methods to the next-generation version and deprecate the old one from ic-js.
- Migrate the `getTransactions` API method to use the next-generation index canister.
- Remove `indexCanister` as it is no longer used.
- Update `getTransactions` tests to use mocks and spies for the next-generation canisters.  
-  [ ] Add an entry to the changelog (if necessary)
Not necessary.
> refactor(api): migrate getTransactions to next-gen index canister

- rs/backend/src/state/partitions.rs
- rust-toolchain.toml
#6840 is attempting to upgrade Rust to the latest version but is [failing](https://github.com/dfinity/nns-dapp/actions/runs/15060150698/job/42333677679?pr=6840). The compiler appears to have become smarter and can now detect that the `#[must_use]` attribute has no effect when applied to methods of a trait implementation.
- Upgrade Rust to 1.87
- Remove `#[must_use]` from trait implementation.
- Pipeline should pass as before
Not necessary.
> chore(deps): upgrade rust to 1.87 and fix warnings

- frontend/src/lib/components/portfolio/TotalAssetsCard.svelte
- frontend/src/lib/components/ui/UsdValueBanner.svelte
- frontend/src/lib/components/ui/UsdValueHeadless.svelte
- frontend/src/tests/lib/components/ui/UsdValueHeadlessTest.svelte
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR prepares the `UsdValueHeadless` component by migrating it to Svelte 5.
- Refactor `UsdValueHeadless` to runes.
- Update consumers of `UsdValueHeadless` to use the new syntax.
- Updated demo component for tests.
- Pipeline should pass as before.
Not necesasry.
> refactor(portfolio): migrate USD value display to runes

- frontend/src/lib/utils/format.utils.ts
- frontend/src/tests/lib/utils/format.utils.spec.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. When hidden, the design requires the "hidden" character to be displayed multiple times, depending on the context and available space. This PR adds a new utility to generate these "hidden" characters.
-  Added a new utility.
-  Added unit tests.
-  [ ] Add an entry to the changelog (if necessary)
Not necessary
> feat(utils): add hidden balance character generator

- frontend/src/lib/constants/stores.constants.ts
- frontend/src/lib/stores/balance-privacy-option.store.ts
- frontend/src/tests/lib/stores/balance-privacy-option.store.spec.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR introduces a new writable store, which is a store that is saved in local storage, to track the user's selection of `hide/show`.
- Add new writable store.
- Add unit tests for the store.
Not necessary.
> feat(balances): add balance display settings store

- frontend/src/lib/constants/stores.constants.ts
- frontend/src/lib/derived/balance-privacy-active.derived.ts
- frontend/src/lib/stores/balance-privacy-option.store.ts
- frontend/src/tests/lib/derived/balance-privacy-active.derived.spec.ts
- frontend/src/tests/lib/stores/balance-privacy-option.store.spec.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR adds a new derived store to determine whether the balances should be visible. The logic is as follows:
* If the user is signed in and has marked the option to hide the balance, it will return `true`.
* In all other cases, it will return `false`.
- Add new derived store.
- Add unit tests for the derived store.
Not necessary.
> feat(store): add balance visibility logic

- frontend/src/lib/components/project-detail/ProjectProposal.svelte
- frontend/src/tests/lib/components/project-detail/ProjectProposal.spec.ts
We want to show an info-box about where to find an Sns project's proposal in case the nns-dapp can't load it.
This PR introduces this new box with links to the dashboard and vpGeek. Additionally, there is a link to a forum post.
- Remove toast message when a proposal can't load from the proposal details.
- Show info box if proposal can't be loaded but we have the `proposalId`.
> feat(launchpad): implement alternative info box for proposal's info

- CHANGELOG-Nns-Dapp-unreleased.md
- rs/backend/src/assets.rs
#6779 introduced Permissions Policy for the application to explicitly enable the necessary native features.
The initial implementation was missing the permissions for HW:
- hid
- usb
- Adds permissions for `hid` and `usb`.
- Tested by mstrasinskis in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
> feat(security): add hardware wallet permissions policy

- frontend/src/lib/components/ui/UsdValueHeadless.svelte
- frontend/src/tests/lib/components/ui/UsdValueHeadless.spec.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR modifies the `UsdValueHeadless` component to format the amount either as a number or the hidden characters.
https://github.com/user-attachments/assets/1dacdc62-5afd-488c-93f4-7516c42592a9
Note: This PR does not yet provide a way to toggle the hidden/show value.
- Format amounts based on the hide balance toggle.
- Unit test to cover the hidden value.
Not necessary.
> feat(display): implement hidden balance formatting in the USD value banner

- frontend/src/lib/components/ic/AmountDisplay.svelte
- frontend/src/lib/components/ic/AmountWithUsd.svelte
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR migrates two existing components to use Svelte runes, simplifying future changes to implement the visibility toggle.
- Migrates `AmountWithUsd` to runes.
- Migrates `AmountDisplay` to runes.
- No logical changes have been made, so the tests should pass as they did before.
Not necessary.
> refactor(ui): migrate Amounts components to svelte 5

- .github/CODEOWNERS
- .github/workflows/update-ic-cargo-deps.yaml
- scripts/nns-dapp/release-beta
The name of the [nns-team](https://github.com/orgs/dfinity/teams/nns-team) has changed to [governance-team](https://github.com/orgs/dfinity/teams/governance-team). More information can be found [here](https://dfinity.slack.com/archives/CGJND92DA/p1747828796597669?thread_ts=1747671441.856149&cid=CGJND92DA) and [here](https://dfinity.slack.com/archives/CGJND92DA/p1747740057505439).
- Update references from the old team name to the new one.
Not necessary.
Not necessary.
> chore: update team name to governance-team

- frontend/src/lib/components/ui/PrivacyAwareAmount.svelte
- frontend/src/tests/lib/components/ui/PrivacyAwareAmount.spec.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR adds a new component that determines whether to display the provided value or hide it with placeholder characters. This component will later be used by various other components.
- New component `PrivacyAwareAmount`
- Unit tests for the new component.
Not necessary.
> feat(ui): add privacy-aware amount display

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/lib/components/portfolio/TokensCardHeader.svelte
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR migrates the two cards displaying balances in the Portfolio page to use Svelte runes, simplifying future changes to implement the visibility toggle.
- Migrate `HeldTokensCard` to runes.
- Migrate `StakedTokensCard` to runes.
- Migrate `TokensCardHeader` to runes.
- No logical changes have been made, so the tests should pass as they did before.
Not necessary.
> refactor(portfolio): migrate balance cards to runes

- frontend/src/lib/components/accounts/UiTransactionsList.svelte
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/components/proposals/UniverseWithActionableProposals.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
We want to upgrade the version of Gix in the nns-dapp to address an issue with Infinite Scrolling. The latest version of GIX introduced a breaking change to `InfiniteScroll` when migrating it to Svelte 5.
This PR prepares consumers of these components for the upgrade by migrating them to runes.
- Refactor `UiTransactionsList` to support runes.
- Refactor `NnsProposalsList` to support runes.
- Refactor `SnsProposalsList` to support runes.
- Refactor `UniverseWithActionableProposals` to support runes.
- Pipeline should work as before.
Not necessary.
> refactor(lists): migrate consumers of infinite scroll components to runes

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/package-lock.json
- frontend/src/lib/components/accounts/IcrcWalletTransactionsList.svelte
- frontend/src/lib/components/accounts/UiTransactionsList.svelte
- frontend/src/lib/components/neuron-detail/Ballots/Ballots.svelte
- frontend/src/lib/components/proposals/NnsProposalsList.svelte
- frontend/src/lib/components/proposals/UniverseWithActionableProposals.svelte
- frontend/src/lib/components/sns-proposals/SnsProposalsList.svelte
- frontend/src/lib/pages/NnsProposals.svelte
- frontend/src/lib/pages/NnsWallet.svelte
- frontend/src/lib/pages/SnsProposals.svelte
We want to upgrade the version of Gix in the nns-dapp to address an issue with Infinite Scrolling. The latest version of GIX introduced a breaking change to `InfiniteScroll` when migrating it to Svelte 5.
This PR builds on top of #6859 and refactors how these components consume the `InfiniteScroll`.
Note: This upgrade fixes the issue of all lists not fetching next pages.
Before:
Not all votes are being loaded: 
https://github.com/user-attachments/assets/4b71cf51-d18f-427e-a9f7-97f67adc4fa4
Not all proposals for a project are being loaded by scrolling:
https://github.com/user-attachments/assets/b81273ff-3d87-4b7d-a881-4fe0cb39c2b9
After:
All votes are being loaded: 
https://github.com/user-attachments/assets/bcf125c9-f567-48d7-9d30-b3b4c29b0291
All proposals for a project are being loaded …
> fix(scroll): upgrade gix to restore infinite scrolling

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/TokensCardHeader.svelte
- frontend/src/tests/lib/components/portfolio/HeldTokensCard.spec.ts
- frontend/src/tests/lib/components/portfolio/StakedTokensCard.spec.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR adds the `PrivacyAwareAmount` to the portfolio header cards.
- Wrap the amount value with the `PrivacyAwareAmount`.
- Add a unit test to cover the hide flow.
Not necessary.
> feat(portfolio): integrate privacy display in headers cards

- frontend/src/lib/components/header/ToggleBalancePrivacyOption.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/header/ToggleBalancePrivacyOption.spec.ts
- frontend/src/tests/page-objects/ToggleBalancePrivacyOption.page-object.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR creates a new component that will be displayed in the menu entries.
Note: The [Figma designs](https://www.figma.com/design/29OdZHbNaOk9RkrfESucjb/NNS-1.03-WIP?node-id=12650-33136&t=dnaTDwnUEaOXBmlH-4) display a differently styled checkbox. This change in the checkbox design should be implemented consistently across all instances.
Note: This video is taken from a PR with additional changes.
https://github.com/user-attachments/assets/39949c19-66d2-4992-9d22-6d98ac5c5ff7
- New component to be displayed in the Menu with a toggle to change between privacy modes.
- Add a unit test to cover the new component.
Not yet.
[NNS1-3721]: …
> feat(menu): create balance privacy toggle component

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/header/AccountMenu.svelte
- frontend/src/tests/lib/components/header/AccountMenu.spec.ts
- frontend/src/tests/lib/components/header/ToggleBalancePrivacyOption.spec.ts
- frontend/src/tests/page-objects/AccountMenu.page-object.ts
- frontend/src/tests/page-objects/ToggleBalancePrivacyOption.page-object.ts
We want to introduce a toggle that allows users to hide or show their balances on the main pages. This PR builds on #6865 and utilizes this new component to display the option in the apps menu.
https://github.com/user-attachments/assets/39949c19-66d2-4992-9d22-6d98ac5c5ff7
- Introduce new entry in `AccountMenu` to toggle privacy mode.
- Add a unit test to cover the new entry in the menu.
- Tested in [devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.yhabib-ingress.devenv.dfinity.network/)
> feat(menu): integrate balance privacy toggle in account menu

- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/tests/lib/api-services/governance.api-service.spec.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
This PR introduces a basic API to disburse maturity to the user’s main account only (sub-account and external address support planned for later).
[Jira](https://dfinity.atlassian.net/browse/NNS1-3740)
- Add `disburseMaturity` api.
- Add `disburseMaturity` api-service which additionally invalidates the cache.
- Added.
Not yet.
> feat(disburse-maturity): api

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/portfolio/LaunchProjectCard.svelte
- frontend/src/lib/components/portfolio/NewSnsProposalCard.svelte
- frontend/src/lib/themes/mixins/_portfolio.scss
Ongoing swap cards on the Portfolio page should feature a rocket icon in their background. Additionally, both ongoing swaps and new SNS proposals should have a custom color for their tags.
https://github.com/user-attachments/assets/54b9ed0b-e0ea-4255-91cb-1978c691d1c3
- Added a background icon to the `LaunchedProjectCard`.
- Introduced a mixin for custom styles for the `Tag`, which is used in the `LaunchedProjectCard` and `NewSnsProposalCard`.
- Not necessary.
> style(portfolio): ui tweaks to portfolio cards

- frontend/src/lib/components/proposal-detail/VotesResultsConditionStatus.svelte
We want to change how the voting results are displayed for a proposal. This PR adds a new component based on `VotesResultsMajorityDescription` to render a collapsible area with a title and an icon. The icon will change based on the condition, and the content can be collapsed or uncollapsed from the outside.
Note: `VotesResultsMajorityDescription` will be remove in a later iteration.
Note 2: Screenshot has been taken with other changes not present in this PR.
[NNS1-3753](https://dfinity.atlassian.net/browse/NNS1-3753)
- A new component to display the status of a condition for a proposal to pass.
- Unit tests for the new component.
Not necessary.
[NNS1-3753]: https://dfinity.atlassian.net/browse/NNS1-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> feat(proposals): add collapsible vote condition status component

- frontend/src/lib/components/neuron-detail/NnsAvailableMaturityItemAction.svelte
- frontend/src/lib/components/neuron-detail/NnsNeuronMaturitySection.svelte
As part of the Svelte 5 upgrade, it’s better to modernize the component syntax before applying further changes.
- Upgrade NnsAvailableMaturityItemAction.
- Upgrade NnsNeuronMaturitySection.
- Should pass.
Not required.
> refactor: Maturity section to svelte 5

- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/mocks/neurons.mock.ts
This PR introduces a function to calculate total disbursements.
[Jira](https://dfinity.atlassian.net/browse/NNS1-3740)
- Add `totalMaturityDisbursementsInProgress` util.
- Added.
Not yet
> feat(disburse-maturity): Total maturity util

- frontend/src/lib/components/proposal-detail/IneligibleNeuronsCard.svelte
- frontend/src/lib/components/proposal-detail/VotingCard/NnsVotingCard.svelte
- frontend/src/tests/lib/components/proposal-detail/VotingCard/NnsVotingCard.spec.ts
- frontend/src/tests/page-objects/IneligibleNeuronList.page-object.ts
- frontend/src/tests/page-objects/VotingCard.page-object.ts
Since the governance canister now provides `neuronMinimumDissolveDelayToVoteSeconds` via the network economics API, it should also be used when displaying the minimum dissolve delay in the ineligible neuron description.
- Use the `neuronMinimumDissolveDelayToVoteSeconds` parameter for the displayed ineligible reason.
- Added.
Not necessary.
> Update minimum dissolve delay for ineligibility reason

- frontend/src/lib/components/proposal-detail/VotesResults.svelte
We want to change how the voting results for a proposal are displayed. This PR improves the user experience by rotating the expand icon to indicate what action will occur the next time users click on it.
https://github.com/user-attachments/assets/4f329583-95b0-4838-a59a-2be55ceea3ca
[NNS1-3753](https://dfinity.atlassian.net/browse/NNS1-3753)
- Styles have been added to rotate the icon based on the expanded state of both collapsible regions.
- The feature has been manually tested.
Not necessary.
[NNS1-3753]: https://dfinity.atlassian.net/browse/NNS1-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(votes): add expand icon rotation feedback

- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
This PR introduces a function to calculate if the provided maturity is enough for disbursement.
[Jira](https://dfinity.atlassian.net/browse/NNS1-3740)
- Add `isEnoughMaturityToDisburse ` util.
- Added.
Not yet
> feat(disburse-maturity): isEnoughMaturityToDisburse

- frontend/src/lib/components/neuron-detail/NnsAvailableMaturityItemAction.svelte
- frontend/src/lib/components/neuron-detail/actions/NnsDisburseMaturityButton.svelte
- frontend/src/lib/constants/neurons.constants.ts
- frontend/src/lib/i18n/en.json
- frontend/src/lib/modals/neurons/NnsNeuronModals.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/nns-neuron-detail.modal.ts
- frontend/src/lib/utils/neuron.utils.ts
- frontend/src/tests/lib/components/neuron-detail/NnsAvailableMaturityItemAction.spec.ts
- frontend/src/tests/lib/components/neuron-detail/actions/NnsDisburseMaturityButton.spec.ts
- frontend/src/tests/lib/utils/neuron.utils.spec.ts
- frontend/src/tests/page-objects/NnsAvailableMaturityItemAction.page-object.ts
This PR adds (behind the flag) the "Disburse" button to the neuron page.
[Jira](https://dfinity.atlassian.net/browse/NNS1-3740)
- New `NnsDisburseMaturityButton` component.
- Display disburse maturity button on page.
- Added a new modal key "disburse-maturity" to display a modal (comes later).
- Added.
Not yet
> feat(disburse-maturity): Display "disburse" button

- HACKING.md
"Too many open files" errors were blocking the setup process, this was due to the operating system's default limits on file descriptors.
Increased the `ulimit -n` for the script's environment to `65536`. This ensures processes have enough file descriptor capacity to complete without errors. 
Should pass CI.
N/A
> fix(setup): increase open file limit for builds

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neuron-detail/NeuronSelectPercentage.svelte
In the NNS/SNS disburse maturity modals, the 'Disburse' button's width fluctuates when insufficient percentage is selected due to the disabled button being wrapped by a Tooltip. This PR ensures the button maintains a consistent 100% width, improving its visual appearance.
- Make the inner button to be 100%.
- Tested manually
| ![Screenshot 2025-06-08 at 19 40 18](https://github.com/user-attachments/assets/8d84e253-926a-4c1e-839b-33a6116fce05) | ![Screenshot 2025-06-08 at 19 40 06](https://github.com/user-attachments/assets/b133cb3d-303f-4a82-93ce-1e50429166e2) |
> Fix disabled button width

- frontend/src/lib/api/governance.api.ts
- frontend/src/lib/modals/neurons/NnsDisburseMaturityModal.svelte
- frontend/src/lib/services/neurons.services.ts
- frontend/src/tests/lib/modals/neurons/NnsDisburseMaturityModal.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
The UI components already support custom destinations via account identifier (hex string).
This PR ensures the correct API call is made using the provided destination.
- Added `toAccountIdentifier` field to the disburse maturity API.
- Passed the `toAccountIdentifier` value from the components to the API layer for use in the request.
- Updated.
- Tested locally that disbursement works with the custom account identifier.
> feat(disburse-maturity): destination for disbursement

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/neurons/NnsStakeNeuron.svelte
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
The Staking form input validation doesn't reset the error message once the user corrects the provided amount.
Before:
https://github.com/user-attachments/assets/c04cceae-c0be-426c-9fcc-506e9c399dd0
After: 
https://github.com/user-attachments/assets/00c44243-3db9-405f-99eb-cee51a974829
- Reset error message if no error condition is met.
- Unit test to cover the flow.
> fix(validation): clear stake amount error on valid input

- frontend/src/lib/utils/format.utils.ts
- frontend/src/tests/lib/utils/format.utils.spec.ts
#6601 introduced fiat values in transaction forms. The next step in the transaction wizard modal, the Review step, should also display fiat values. This PR introduces a new utility function that can be used by both the transaction form modal and the transaction summary modal.
[NNS1-3756](https://dfinity.atlassian.net/browse/NNS1-3756)
- Add new utility to format fiat values with support for very small numbers
- Unit tests
[NNS1-3756]: https://dfinity.atlassian.net/browse/NNS1-3756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(utils): fiat value formatter with support for small amounts

- frontend/src/lib/components/transaction/TransactionFormFee.svelte
#6947 introduced a new utility to format fiat values, including support for small amounts. This PR utilizes this utility and refactors the consumer into runes.
[NNS1-3756](https://dfinity.atlassian.net/browse/NNS1-3756)
- Refactor the component to use runes.
- Use the utility instead of custom logic in the component.
- Remove the unused slot from the component.
- Tests should pass as they did before since there are no logical changes.
[NNS1-3756]: https://dfinity.atlassian.net/browse/NNS1-3756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(transactions): migrate fee fiat display to shared util  

- frontend/src/lib/modals/transaction/TransactionModal.svelte
#6946 introduced a [bug](https://github.com/dfinity/nns-dapp/pull/6946/files#diff-935873ba23201df42a1b8c0aa09851f9e7898c3b7c6d8f199740b353be690789L185) by migrating a slot with a default value into a snippet was rendering both the slot and a default value. 
[NNS1-3756](https://dfinity.atlassian.net/browse/NNS1-3756)
| <img width="643" alt="Screenshot 2025-06-16 at 18 26 52" src="https://github.com/user-attachments/assets/12b9b35d-78e8-410f-b0c5-a8571a97578b" /> |  <img width="639" alt="Screenshot 2025-06-16 at 18 26 26" src="https://github.com/user-attachments/assets/9ddf7725-9294-4df3-abc6-1fcbc68d9c96" /> |
- Fix slot rendering with a default value.
- Manually tested.
[NNS1-3756]: https://dfinity.atlassian.net/browse/NNS1-3756?atlOrigin=eyJpIjoiNWRk …
> fix(transactions): resolve duplicate content rendering

- frontend/src/lib/components/neurons/ConfirmDissolveDelay.svelte
- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/sns-neurons/ConfirmSnsDissolveDelay.svelte
To assist users during the neuron stake process, the dapp will display fiat values alongside the token amount. This initial PR prepares the component by migrating it to runes.
[NNS1-3756](https://dfinity.atlassian.net/browse/NNS1-3756)
- Refactor `SetDissolveDelay` component to runes.
- Refactor `ConfirmSnsDissolveDelay` component to runes.
- Refactor `ConfirmDissolveDelay` component to runes.
- Unit tests should pass as they did before, since no logical changes were introduced.
[NNS1-3756]: https://dfinity.atlassian.net/browse/NNS1-3756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(staking): migrate components to runes

- frontend/src/lib/components/neurons/ConfirmDissolveDelay.svelte
- frontend/src/lib/components/neurons/SetDissolveDelay.svelte
- frontend/src/lib/components/sns-neurons/ConfirmSnsDissolveDelay.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/sns-neurons/ConfirmSnsDissolveDelay.spec.ts
- frontend/src/tests/lib/modals/neurons/NnsStakeNeuronModal.spec.ts
To assist users during the neuron stake process, the dapp will display fiat values alongside the token amount. This PR sows the fiat value of the staked amount.
| ![Screenshot 2025-06-17 at 07 56 51](https://github.com/user-attachments/assets/56ae342f-9fee-450a-ba93-d502f9511c42) | <img width="665" alt="Screenshot 2025-06-17 at 13 38 58" src="https://github.com/user-attachments/assets/7be9374b-6226-46bd-b52a-4f45236482da" /> |
| <img width="648" alt="Screenshot 2025-06-17 at 14 39 16" src="https://github.com/user-attachments/assets/9d6ed1ed-eebf-4002-aa24-d09b7c94d96e" /> | <img width="641" alt="Screenshot 2025-06-17 at 14 39 32" src="https://github.com/user-attachments/assets/6b84ca65-a808-4166-8a3d-2d7bbd554e23" /> | …
> feat(staking): add fiat value to neuron set dissolve delay 

- frontend/src/lib/services/analytics.services.ts
- frontend/src/tests/lib/services/analytics.services.spec.ts
Plausible Analytics does not track query parameters. The nns-dapp uses query parameters for nested pages like `projects`, `universes`, and `proposals`.
This PR introduces a new method in the analytics object to manually track page views by calling [TrackPageview](https://plausible-tracker.netlify.app/globals#trackpageview).
- Method to track page views
- Unit test for the new method.
> feat(analytics): expose manual page view tracking method

- frontend/src/lib/utils/analytics.utils.ts
- frontend/src/tests/lib/utils/analytics.utils.spec.ts
Plausible Analytics does not track query parameters. The nns-dapp uses query parameters for nested pages like `projects`, `universes`, and `proposals`.
This PR introduces a utility that sluggifies universe and project names, making them easier to read in the report.
Some examples:
* ckBTC -> ck-btc
* ckUSDC -> ck-usdc
* Internet Computer -> internet-computer
- New utility to sluggify a project name.
- Unit tests for the new util.
> feat(analytics): add project name sluggification util

- frontend/src/lib/derived/analytics.derived.ts
- frontend/src/tests/lib/derived/analytics.derived.spec.ts
Plausible Analytics does not track query parameters. The nns-dapp uses query parameters for nested pages like `projects`, `universes`, and `proposals`.
This PR introduces a new derived store to get a map of universes/projects and slugs.
- New derived store.
- Unit tests for the new store.
> feat(store): add project slug derived store

- frontend/src/lib/utils/analytics.utils.ts
- frontend/src/tests/lib/utils/analytics.utils.spec.ts
Plausible Analytics does not track query parameters. The nns-dapp uses query parameters for nested pages such as `projects`, `universes`, and `proposals`.
#6974 introduced a utility to "translate" the dapp query parameters into user-friendly paths. This PR adds default values to the conversion, so if the project or universe is unknown to the dapp, we will use the `canisterId` as before.
- Default conversion to original project/universe value.
- Add conversion for `neuron` page.
- New tests to cover the default case.
- New tests to cover the `neuron` page.
> feat(analytics): add path parameter fallbacks

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/proposal-detail/VotesResults.svelte
- frontend/src/tests/lib/components/proposal-detail/VotesResults.spec.ts
#6892 introduced an alternative method for displaying voting progression in proposals. It relies on the 2/3 rule, but this is not precise enough. This PR updates the logic to utilize `minimum_yes_proportion_of_exercised`.
[NNS1-3753](https://dfinity.atlassian.net/browse/NNS1-3753)
- Update logic.
- Improve tests descriptions
- New test case for `2/3 < x < 0.67`
[NNS1-3753]: https://dfinity.atlassian.net/browse/NNS1-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(proposals): use precise threshold for vote calculations

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/lib/utils/tokens-table.utils.ts
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/components/tokens/TokensTable.svelte.spec.ts
- frontend/src/tests/lib/pages/Tokens.spec.ts
- frontend/src/tests/lib/utils/tokens-table.utils.spec.ts
The ICP token and ICP neurons should be displayed at the top of the tokens and staking tables. This second PR applies the new comparators and updates the existing ones to always prioritize ICP.
[NNS1-3914](https://dfinity.atlassian.net/browse/NNS1-3914)
- Apply new comparators.  
- Refactor existing ones to prioritize ICP.
- Update tests.
[NNS1-3914]: https://dfinity.atlassian.net/browse/NNS1-3914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tables): prioritize ICP in token and neuron lists

- frontend/src/lib/components/neuron-detail/actions/SpawnNeuronButton.svelte
Svelte5 enables reusing pieces of code that remove duplication from our code base. This PR simplifies `SpawnNeuronButton` by reusing the child.
- Create snippet and reuse in component.
> refactor(neurons): extract spawn button snippet

- frontend/src/lib/components/launchpad/CardList.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/Launchpad2.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/launchpad/CardList.spec.ts
- frontend/src/tests/lib/pages/Launchpad2.spec.ts
- frontend/src/tests/mocks/proposal.mock.ts
- frontend/src/tests/page-objects/CardList.page-object.ts
- frontend/src/tests/page-objects/Launchpad2.page-object.ts
As part of the Launchpad redesign, a new component is needed to implement the updated layout. In its basic view, it displays upcoming launch cards (similar to the Portfolio page) alongside launched SNS projects. 
This PR introduces that new component, which will replace the current Launchpad component later.
**Out of scope for this PR:**
- Loading states (e.g., skeletons)
- Mobile-specific layouts
https://dfinity.atlassian.net/browse/NNS1-3906
- New Launchpad2 component.
- Added.
> feat(launchpad2): Launchpad2 component

- frontend/src/lib/components/launchpad/CardList.svelte
- frontend/src/lib/pages/Launchpad2.svelte
As part of the Launchpad redesign, the upcoming launch cards should be displayed in a slider style on mobile (single row, horizontal scrolling). This PR introduces a new property to CardList component `mobileHorizontalScroll`, that enables the required styles.
CardList:
- New `mobileHorizontalScroll` prop.
- Styles for optional horizontal scrolling.
- Tested locally:
[mobile-slider.webm](https://github.com/user-attachments/assets/76d2d3d9-9cc7-415d-af19-356bab661ef5)
> feat(launchpad2): Cards mobileHorizontalScroll style

- frontend/src/lib/constants/constants.ts
- frontend/src/lib/modals/sns/neurons/SnsIncreaseStakeNeuronModal.svelte
- frontend/src/lib/modals/sns/neurons/SnsStakeNeuronModal.svelte
- frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
#6985 introduces events for SNS participation flows. This PR adds a `fiatAmount` parameter to these events based on the conversion at that specific time.
Note: If the conversion is unavailable, the property will not be provided.
- Add `fiatAmount` property to custom events.
- Manually tested.
> feat(analytics): add fiat values to participation events

- frontend/package-lock.json
- frontend/src/lib/api/governance.api.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
Upgrade the nns-dapp to the latest version of ic-js, which includes the `getMetrics` method. 
Note: The latest version introduces a breaking change due to a method being renamed to correct a typo.
[NNS1-3935](https://dfinity.atlassian.net/browse/NNS1-3935)
- Run `npm run upgrade:next`
- Rename `getLastestRewardEvent` into `getLatestRewardEvent`
- CI should pass as it did before since no changes were introduced.
[NNS1-3935]: https://dfinity.atlassian.net/browse/NNS1-3935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): upgrade ic-js 

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/tests/lib/utils/staking.utils.spec.ts
Unresponsive projects should be moved to the bottom of the projects table unless a special sorting has been applied.
| <img width="423" alt="Screenshot 2025-07-03 at 13 58 08" src="https://github.com/user-attachments/assets/7372a2ca-1080-48ab-80b4-430519ae7c00" /> | <img width="419" alt="Screenshot 2025-07-03 at 13 57 46" src="https://github.com/user-attachments/assets/613ab851-3fa1-4781-a188-7a9178a40e63" /> | 
[NNS1-3941](https://dfinity.atlassian.net/browse/NNS1-3941)
- New comparator to check for unresponsive projects based on the staked amount.
- Tests to existing sorting rules with new comparator.
[NNS1-3941]: https://dfinity.atlassian.net/browse/NNS1-3941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> fix(projects): prioritize responsive projects in table

- rs/sns_aggregator/src/types/slow.rs
- rs/sns_aggregator/src/types/upstream.rs
- rs/sns_aggregator/src/upstream.rs
The latest reward event of an SNS contains data that is useful for computing metrics that are relevant to end users / NNS dapp users, e.g., the DAO's voting activity. 
Call and aggregate the responses from `SnsGov.get_latest_reward_event`.
Manual + CI.
> feat(sns_aggregator): Scrape latest reward events from SNS Governance

- frontend/src/lib/api-services/governance.api-service.ts
- frontend/src/lib/api/governance.api.ts
- frontend/src/tests/lib/api/governance.api.spec.ts
The nns-dapp will use the [get_metrics](https://github.com/dfinity/ic-js/pull/977) method from the Governance canister to display new information to users. This first PR adds support for this new method in the API layer.
[NNS1-3934](https://dfinity.atlassian.net/browse/NNS1-3934)
- New `getGovernanceCachedMetrics` api call and service
- Unit tests the new api call
[NNS1-3935]: https://dfinity.atlassian.net/browse/NNS1-3935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NNS1-3934]: https://dfinity.atlassian.net/browse/NNS1-3934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): add governance metrics endpoint support

- frontend/src/lib/services/app.services.ts
- frontend/src/tests/lib/services/app.services.spec.ts
The nns-dapp will use the [get_metrics](https://github.com/dfinity/ic-js/pull/977) method from the Governance canister to present new information to users. This PR loads the data as soon as users log in, making it available for any page of the application.
Prev. PR #7042
[NNS1-3934](https://dfinity.atlassian.net/browse/NNS1-3934)
- Call `loadGovernanceMetrics` when the user is logged in.
- Unit tests for loading the data.
[NNS1-3935]: https://dfinity.atlassian.net/browse/NNS1-3935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NNS1-3934]: https://dfinity.atlassian.net/browse/NNS1-3934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(auth): initialize governance metrics on login

- frontend/src/lib/derived/viewport.derived.ts
- frontend/src/tests/lib/derived/viewport.derived.spec.ts
New designs for the nns-dapp define different DOM structures for mobile and non-mobile desktops. Although CSS media queries can handle such cases, they would create too many unnecessary DOM nodes. This PR introduces a new store that exposes the viewport size and a derived store to determine if it is mobile (less than 576px) or not. 
Note: It hardcodes the value of the small breakpoint, but this will be updated to a global constant later.
[NNS1-3922](https://dfinity.atlassian.net/browse/NNS1-3922)
- New store for the viewport.
- Unit tests.
[NNS1-3922]: https://dfinity.atlassian.net/browse/NNS1-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(store): add viewport size detection

- frontend/src/lib/components/launchpad/UpcomingProjectCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/launchpad/UpcomingProjectCard.spec.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/page-objects/UpcomingProjectCard.page-object.ts
As part of the Launchpad redesign, the upcoming project card needs to be updated. This PR introduces a new `UpcomingProjectCard` component.
https://dfinity.atlassian.net/browse/NNS1-3902
- Add `UpcomingProjectCard` component.
- Added.
- Tested locally
| M | D |
| <img width="471" alt="image" src="https://github.com/user-attachments/assets/84ed0b9a-f800-4f2b-926e-b21a63cb5aa7" /> | <img width="382" alt="image" src="https://github.com/user-attachments/assets/78797e0a-ca23-4943-a743-118826842a45" /> |
> feat(launchpad2): Upcoming project card

- frontend/package-lock.json
- frontend/src/tests/mocks/governance-metrics.mock.ts
#7075 attempts to upgrade the version of ic-js to include the [new field](https://github.com/dfinity/ic-js/pull/983) `total_potential_voting_power`. However, it fails due to a breaking change in the NNS governance candid, which introduced a new mandatory field in the response of `get_metrics`.
- Bump ic-js by running `npm run upgrade:next`
- Fix mock
> chore(deps): bump ic-js

- frontend/src/lib/components/portfolio/ApyCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/ApyCard.spec.ts
- frontend/src/tests/page-objects/ApyCard.page-object.ts
The nns-dapp will display information to users about their staking power and exploitation. This PR introduces new cards based on the API defined in #7065.
| Narrow | Mobile | Desktop |
|--------|--------|--------|
| ![Screenshot 2025-07-08 at 01 46 49](https://github.com/user-attachments/assets/d6b5c42b-a03e-4f26-b5ad-8a5cb2c1a7e6) | ![Screenshot 2025-07-08 at 01 47 12](https://github.com/user-attachments/assets/89b02c4a-a459-4aa6-b65f-ac13078bcd3b) | ![Screenshot 2025-07-08 at 01 47 32](https://github.com/user-attachments/assets/48246e86-073d-4372-aa68-154ff8f33b49) | 
Note: This PR does not add the new card to the portfolio page where all the cars are displayed. This will be addressed in a follow-up.
[NNS1-3922](https://dfinity.atlassian.net/browse/NNS1-3922)
- New card with information …
> feat(staking): add rewards information card

- config.json
- declarations/used_by_proposals/nns_governance/nns_governance.did
- declarations/used_by_proposals/nns_registry/nns_registry.did
- declarations/used_by_proposals/sns_wasm/sns_wasm.did
- declarations/used_by_sns_aggregator/sns_governance/sns_governance.did
- declarations/used_by_sns_aggregator/sns_ledger/sns_ledger.did
- declarations/used_by_sns_aggregator/sns_root/sns_root.did
- declarations/used_by_sns_aggregator/sns_swap/sns_swap.did
- declarations/used_by_sns_aggregator/sns_wasm/sns_wasm.did
- rs/proposals/src/canisters/nns_governance/api.rs
- rs/proposals/src/canisters/nns_registry/api.rs
- rs/proposals/src/canisters/sns_wasm/api.rs
- rs/sns_aggregator/src/types/ic_sns_ledger.patch
Reverts dfinity/nns-dapp#7078
Reason: not all required types were updated. We will try another approach after restoring the state to what it was before 7078 got merged.
> Revert "chore: Bump IC types"

- frontend/src/lib/components/launchpad/OngoingProjectCard.svelte
- frontend/src/tests/lib/components/launchpad/OngoingProjectCard.spec.ts
In the ongoing SNS project card, the "Cap, ICP" field was incorrectly displaying the direct commitment. This PR corrects it by using `max_direct_participation_icp_e8s` instead.
- Change the field source.
- Updated.
> feat(launchpad2): Fix cap.icp source

- frontend/src/lib/utils/launchpad.utils.ts
- frontend/src/routes/(app)/(nns)/launchpad/+page.svelte
- frontend/src/tests/lib/utils/launchpad.utils.spec.ts
- frontend/src/tests/routes/app/launchpad/page.spec.ts
This PR enables the newly implemented `Launchpad2` component (from the redesign) behind a feature flag, replacing the old one.
- Now that all cards are merged, the old ones have been replaced in the [Launchpad utils](https://github.com/dfinity/nns-dapp/pull/7092/files#diff-a0d1fb112de70a1db4d133cb87a1e8a8e8029e52f60cc2fc531946933ef78e7fR29).
- Preload necessary data and conditionally render the redesigned Launchpad content component depending on the feature flag.
- Added tests for the required data loading.
- Additional content related tests will be added in the cleanup phase (https://dfinity.atlassian.net/browse/NNS1-3919)
> feat(launchpad2): Display redesigned launchpad

- frontend/src/lib/components/portfolio/ApyCard.svelte
- frontend/src/lib/components/portfolio/ApyFallbackCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/ApyFallbackCard.spec.ts
- frontend/src/tests/page-objects/ApyFallbackCard.page-object.ts
The nns-dapp will display information about staking power on the portfolio page using the new ApyCard. However, this requires a significant amount of data to load, and issues may arise. This PR introduces a new component to be shown in case of an error or loading state.
| Mobile | Desktop |
| <img width="570" alt="Screenshot 2025-07-09 at 11 53 05" src="https://github.com/user-attachments/assets/75463976-1c71-4189-8c1c-12421a494d7c" /> | <img width="1685" alt="Screenshot 2025-07-09 at 12 00 08" src="https://github.com/user-attachments/assets/4b640ff7-ec0b-4371-9d83-da22600abeff" /> |
| <img width="554" alt="Screenshot 2025-07-09 at 11 58 52" src="https://github.com/user-attachments/assets/0ab9a505-2857-476b-b8e5-1419acbddef0" /> | <img width="1648" alt="Screenshot …
> feat(staking): add APY card fallback states

- frontend/src/lib/components/launchpad/CreateSnsProposalCard.svelte
- frontend/src/lib/components/portfolio/VotesResult.svelte
In the new design, the voting results block displays icons instead of labels on desktop. This PR updates the styles of the voting results component accordingly.
- Display icons only on desktop.
- Hide description on mobile.
- Update text styles.
- Tested manually:
| M | D |
| <img width="395" alt="image" src="https://github.com/user-attachments/assets/1dc68b38-9b47-487d-9c45-a3a1a44dbf44" /> | ![Screenshot 2025-07-09 at 17 24 00](https://github.com/user-attachments/assets/8fbd5408-942d-462a-97e0-5060c432b86d) |
> feat(launchpad2): Create Sns proposal card styles

- frontend/src/lib/components/ui/TooltipIcon.svelte
The nns-dapp displays tooltips with an icon in various parts of the application. The icon has a predefined size of 20px, which is no longer compatible with the new font sizes defined in the app. This PR allows the icon size to be set as a prop, enabling consumers to define it as needed.
[NNS1-3922](https://dfinity.atlassian.net/browse/NNS1-3922)
- Expose a new prop to define the icon size, with a default value of 20.
- All existing tests should pass as before.
[NNS1-3922]: https://dfinity.atlassian.net/browse/NNS1-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tooltips): add configurable icon size

- frontend/src/lib/derived/sns-metrics.derived.ts
- frontend/src/lib/derived/sns-reward-event.derived.ts
- frontend/src/lib/types/sns-aggregator.ts
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/derived/sns-metrics.derived.spec.ts
- frontend/src/tests/lib/derived/sns-reward-event.derived.spec.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/mocks/sns-aggregator.mock.ts
- frontend/src/tests/utils/sns.test-utils.ts
The aggregator was recently upgraded to expose new SNS-related data:
- SNS metrics
- Latest reward event
These are needed for the updated Launchpad and Portfolio pages. To make this data easily accessible, this PR introduces two new derived stores—one for each of the new data fields.
- Add new DTO types matching the updated aggregator response.
- Add `RewardEvent` DTO-to-IC converter.
- Add `snsRewardEventStore` derived store.
- Add `snsMetricsStore` derived store.
- Update mock data.
- Add tests for the new stores and the converter.
> Add Metrics and RewardEvent derived stores

- frontend/src/lib/derived/sns-latest-reward-event.derived.ts
- frontend/src/lib/derived/sns/sns-projects.derived.ts
- frontend/src/lib/modals/sns/sale/ParticipateSwapModal.svelte
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/tests/lib/derived/sns-latest-reward-event.derived.spec.ts
- frontend/src/tests/lib/derived/sns-metrics.derived.spec.ts
- frontend/src/tests/lib/derived/sns/sns-projects.derived.spec.ts
- frontend/src/tests/mocks/sns-projects.mock.ts
- frontend/src/tests/routes/app/launchpad/page.spec.ts
Recently, the new aggregator data was integrated into the nns-dapp ([#7109](https://github.com/dfinity/nns-dapp/pull/7109)).  
This follow-up PR adds the new data to the `SnsFullProject` type, which should simplify access to the `metrics` and `latestRewardEvent` fields.
- Extend SnsFullProject with new fields: `metrics` and `latestRewardEvent`.
**(drive-by refactoring):** rename SnsRewardEventStore to LatestSnsRewardEventStore.
- Updated
> feat(launchpad2): Add new fields to SnsFullProject

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/services/icrc-accounts.services.ts
- frontend/src/lib/utils/error.utils.ts
- frontend/src/tests/lib/utils/error.utils.spec.ts
The nns-dapp fails to process errors when canisters are uninstalled. This leads to incorrect loading states in the UI and a poor user experience as users wait for something to happen. This change will be applied to the ledger and index canisters.
- Treat all canister errors the same when loading transactions and accounts.
- Update unit tests to check util against different error codes.
> fix(errors): improve canister error detection

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
This PR hides the calculation of APY rewards behind the feature flag to avoid issues with accounts with many neurons and projects.
- Hide `getStakingRewardData` behind a feature flag.
- Tested in beta that performance of the nns-dapp is not degraded.
> feat(performance): gate APY calculations behind flag

- frontend/src/lib/components/launchpad/ProjectCard2.svelte
- frontend/src/lib/utils/projects.utils.ts
- frontend/src/tests/lib/components/launchpad/ProjectCard2.spec.ts
- frontend/src/tests/lib/utils/projects.utils.spec.ts
- frontend/src/tests/page-objects/ProjectCard2.page-object.ts
In the redesigned project cards, the ICP in treasury should be displayed.  
This PR replaces the placeholder with the real value based on the aggregator metrics.
- Add new utility: `snsProjectIcpInTreasuryPercentage`.
- Display actual ICP treasury value.
- Updated.
> feat(launchpad2): Display ICP in treasury

- frontend/src/lib/components/portfolio/ApyCard.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/tests/lib/components/portfolio/ApyCard.spec.ts
The new APY card can be displayed for users with or without staking power. The CTA in the button should be tailored to each situation.
[NNS1-3922](https://dfinity.atlassian.net/browse/NNS1-3922)
- Conditionally display link text based on `stakingPowerUSD`.
- Unit test the conditional.
[NNS1-3922]: https://dfinity.atlassian.net/browse/NNS1-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(portoflio): customize Apy card CTA based on staking power

- frontend/src/lib/derived/icp-swap.derived.ts
- frontend/src/tests/lib/derived/icp-swap.derived.spec.ts
#7038 introduced a filter for tokens based on their volume over the last 24 hours. This change eliminates unexpected values, such as outdated ones. However, it also removes pairs from tokens with low liquidity. Therefore, this PR applies the filtering only when multiple entries for the same pair are present.
[NNS1-3938](https://dfinity.atlassian.net/browse/NNS1-3938)
- Update the derived store to filter duplicate tickers base on `volume_usd_24h`.
- Update tests.
[NNS1-3938]: https://dfinity.atlassian.net/browse/NNS1-3938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tickers): filter duplicate tickers by volume

- frontend/src/lib/components/launchpad/ProjectCard2.svelte
This PR restores the link to the project details page, which was mistakenly hidden in [#7126](https://github.com/dfinity/nns-dapp/pull/7126).
- Update styles.
- Verified manually that the link is there
> feat(launchpad2): Fix navigation link visibility

- frontend/src/lib/components/ui/TooltipIcon.svelte
The `TooltipIcon` is used in clickable cards to allow users to open the tooltips without navigating away. The element needs to block the default behavior.
- Add a `preventDefault` event to the wrapper of the Tooltip.
- Manually tested.
> fix(tooltip): prevent navigation on icon click

- scripts/nns-dapp/num_proposals.sh
#7153 introduced a new banner on the home page that displays general information about the SNS projects. One of the values shown is "Proposals Executed." This script calculates those proposals. For example:
Based on script by @aterga, modified by @mstrasinskis.
[NNS1-3841](https://dfinity.atlassian.net/browse/NNS1-3841)
- Add script
- Run it locally.
[NNS1-3841]: https://dfinity.atlassian.net/browse/NNS1-3841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(scripts): add SNS executed proposals script

- frontend/src/tests/e2e/accounts.spec.ts
- frontend/src/tests/e2e/canisters.spec.ts
- frontend/src/tests/e2e/ckbtc.spec.ts
- frontend/src/tests/e2e/design.spec.ts
- frontend/src/tests/e2e/disburse.spec.ts
- frontend/src/tests/e2e/following.spec.ts
- frontend/src/tests/e2e/import-token.spec.ts
- frontend/src/tests/e2e/merge-neurons.spec.ts
- frontend/src/tests/e2e/neuron-details.spec.ts
- frontend/src/tests/e2e/neuron-increase-stake.spec.ts
- frontend/src/tests/e2e/neurons-table.spec.ts
- frontend/src/tests/e2e/neurons.spec.ts
- frontend/src/tests/e2e/periodic.spec.ts
- frontend/src/tests/e2e/portfolio.spec.ts
- frontend/src/tests/e2e/proposals.spec.ts
- frontend/src/tests/e2e/sns-governance.spec.ts
- frontend/src/tests/e2e/sns-participation.spec.ts
- frontend/src/tests/utils/e2e.test-utils.ts
CSS animation may be non-deterministic in screenshot taking, this adds a utility to force disabling them for the page.
Added utility to disable css animations
Tests should pass.
> chore(test-e2e): add utility to disable css animations on the page

- frontend/src/lib/components/portfolio/ApyFallbackCard.svelte
- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/lib/services/staking-rewards.service.ts
- frontend/src/lib/stores/staking-rewards.store.ts
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/routes/+layout.svelte
- frontend/src/tests/routes/app/portfolio/page.spec.ts
- frontend/src/tests/routes/layout.spec.ts
The calculation for the Staking Rewards was triggered on any page change. This avoids it, and recalculates it only when a dependency really changes.
Introduced a reusable store. Update the tests.
Tested manually + tests should pass.
> feat(staking rewards): create a global store to reuse data across pages

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/page-objects/PortfolioPage.page-object.ts
Give more visibility to the new APY card before and after login. This PR introduces the new card from #7173 on the Portfolio page and moves the Upcoming Projects card down to the new SNS section, along with the SNS banner.
| M | D |
| <img width="419" height="799" alt="Screenshot 2025-07-24 at 16 17 31" src="https://github.com/user-attachments/assets/6ba84f65-3aaa-4ea9-89de-062d3ae798e3" /> | <img width="1481" height="855" alt="Screenshot 2025-07-24 at 16 16 48" src="https://github.com/user-attachments/assets/8e3f89b5-4540-43fe-901b-88abf3647277" /> |
| <img width="520" height="701" alt="Screenshot 2025-07-24 at 16 17 17" src="https://github.com/user-attachments/assets/6859c310-35b6-4039-bd73-c04cfa791abd" /> | <img width="1467" height="858" alt="Screenshot 2025-07-24 …
> feat(portfolio): reorganize cards for APY prominence

- frontend/src/lib/components/portfolio/ApyCard.svelte
- frontend/src/lib/components/portfolio/ApyFallbackCard.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/lib/routes/Staking.spec.ts
- frontend/src/tests/page-objects/ProjectsTable.page-object.ts
To make users aware of their current staking rewards, this PR adds new cards to the Staking page.
[Jira task → NNS1-3993](https://dfinity.atlassian.net/browse/NNS1-3993)
- Migrated `ProjectsTable` to svelte5.
- Loaded the necessary data for staking rewards calculation inside `ProjectsTable`.
- Added `onStakingPage` mode to `ApyCard` and `ApyFallbackCard` (disables link rendering).
- Rendered `ApyCard` on the Staking page.
- Added unit tests for card visibility.
| M | D |
| <img width="352" height="472" alt="image" src="https://github.com/user-attachments/assets/0d45e73f-8ff7-49d6-9034-f4e18350b106" /> | <img width="1066" height="798" alt="image" src="https://github.com/user-attachments/assets/44110a1c-aebc-4494-bb7a-6754dcb04594" /> |
> Display staking-rewards card on staking page

- frontend/src/lib/pages/Portfolio.svelte
- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/lib/utils/staking.utils.ts
- frontend/src/lib/utils/tokens-table.utils.ts
- frontend/src/tests/lib/pages/Portfolio.spec.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
The Portfolio page now displays tokens and projects only when the user is signed in. Additionally, ICP should always be visible, even if the user has zero tokens or staked. This PR introduces changes to the utility functions without causing any breaking changes in how consumers expect the data.
[NNS1-3999](https://dfinity.atlassian.net/browse/NNS1-3999)
- Expose utilities to locate the ICP project and token.  
- Update `getTopHeldTokens` to consistently return ICP and the top three tokens by stake. Additionally, remove the authentication dependency.
- Update `getTopStakedTokens` to consistently return ICP and the top three projects by stake. Additionally, remove the authentication dependency.
Side change: 
- Rename `filterCyclesTransferStation` into `filterAbandonedProjects` for …
> feat(portfolio): update utils to prioritize ICP in token and project lists

- HOWTO.md
- frontend/src/lib/i18n/en.governance.json
- frontend/src/lib/types/i18n.d.ts
A new action proposal, `FulfillSubnetRentalRequest`, has been added. This PR introduces support for the i18n aspect of the proposal, allowing it to be rendered in the nns-dapp.
Relevant links:
* https://github.com/dfinity/ic-js/pull/993
* https://github.com/dfinity/nns-dapp/pull/7165
* https://github.com/dfinity/nns-dapp/pull/7113
* https://github.com/dfinity/ic/pull/5835/files#diff-47cb67467f37606a03f7785a62befc6771b11fa71b463741d6fd826c21f05cb4
- Add translations to for the new type
- Not possible
> feat(i18n): add translations for new proposal action FulfillSubnetRentalRequest

- frontend/src/lib/components/portfolio/StartStakingCard.svelte
- frontend/src/lib/pages/Portfolio.svelte
Fix some visual issues in the Portfolio page.
| <img width="1472" height="852" alt="Screenshot 2025-07-28 at 12 36 52" src="https://github.com/user-attachments/assets/d3f4be6f-9cfa-4ded-82ff-f5bbc58f6efe" /> | <img width="1474" height="851" alt="Screenshot 2025-07-28 at 12 37 35" src="https://github.com/user-attachments/assets/f8aa83a5-34cc-4755-970d-7ca06e2559fd" /> | 
- Make the SNS banner span the full width when there are no ongoing proposals.  
-  Align the button on the `StartStakingCard` to the bottom.
- Visual tests.
> style(portfolio): fix banner width and button alignment

- frontend/src/lib/components/ui/TooltipIcon.svelte
The `TooltipIcon` component exposes a prop to define the icon size, but it is not sufficient to ensure that the container does not exceed the specified size. This PR reuses the value to set the size of the icon's wrapper, ensuring consistency.
Note: The issue becomes apparent when one table has the icon while the other does not, as the former occupies a few more pixels of space.
| <img width="1472" height="830" alt="Screenshot 2025-07-28 at 16 23 54" src="https://github.com/user-attachments/assets/879773e3-d942-490f-bf47-e7569998c57c" /> | <img width="1469" height="834" alt="Screenshot 2025-07-28 at 16 23 31" src="https://github.com/user-attachments/assets/ff2c72a4-4f4c-4759-986c-116aebf92451" /> | 
- Use the icon size to determine the container …
> fix(tooltips): constrain icon wrapper to specified size

- frontend/src/lib/components/portfolio/LaunchpadBanner.svelte
- frontend/src/lib/pages/Portfolio.svelte
After the latest design iteration (where the SNS launchpad banner was moved to the bottom of the page), layout issues appeared across multiple viewport sizes. This PR addresses those visual inconsistencies.
https://dfinity.atlassian.net/browse/NNS1-4001
- Updated styles to improve banner responsiveness and alignment.
- Added shadow to the banner.
- Known issue: between 1025px and 1079px, the bottom banner’s height is slightly misaligned. Since this range isn't a focus area and no standard breakpoint covers it in `nns-dapp`, it was intentionally left as-is to reduce complexity and improve maintainability (see screenshots).
| 1024-1079 | 1080+ |
| <img width="1762" height="1546" alt="Screenshot 2025-07-28 at 15 54 13" …
> Adjust launchpad banner to different modes

- frontend/package.json
The snapshot script is not very useful because it assumes a snapshot is called in a specific way, which is not typically the case.
- Remove script.
- Not necessary.
> chore(scripts): remove snapshot script

- HOWTO.md
The HOWTO document includes a section on what to do when there is a new Action Proposal. However, this document is significantly out of sync, as it mentions steps that are no longer necessary.
More information can be found [here](https://dfinity.slack.com/archives/C039M7YS6F6/p1753692298241839?thread_ts=1752675655.965359&cid=C039M7YS6F6)
- Update the Action section in the HOWTO document.
- Not necessary.
> docs(howto): update action proposal instructions

- frontend/src/lib/components/portfolio/NoStakedTokensCard.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/components/ui/ResponsiveTable.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/stores/feature-flags.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/routes/+layout.svelte
- frontend/src/tests/lib/components/staking/ProjectsTable.spec.ts
- frontend/src/tests/routes/layout.spec.ts
- frontend/src/tests/utils/e2e.test-utils.ts
Some minor changes were missing to be reverted, this PR addresses them.
Fixed:
- remove the "Farewell, Spawn Neuron!" message
- reinstate the old column layout for the Projects page
- align the design of empty portfolio cards (bold / non-bold)
Tested manually. Updated tests. Tests should pass.
> chore(revert changes): fix leftover differences from prod after the revert

- config.json
- dfx.json
Note: This PR was spun off from #7143
* Updated `snsdemo` version in `config.json`.
> chore(deps): update snsdemo to release-2025-07-09

- frontend/src/lib/components/launchpad/CardFrame.svelte
- frontend/src/lib/components/launchpad/ProjectCard2.svelte
The cards of projects in which the user hasn’t participated are currently displayed with a white background, which is not in sync with the design. This happened because the same card frame component is used for all other Launchpad cards. This PR addresses the issue by applying a dimmed background to these project cards.
- Added a `dimmed` prop and applied it to the relevant project cards.
- Verified manually.
| Before | Afrer |
| <img width="1068" height="338" alt="image" src="https://github.com/user-attachments/assets/9d8a01f4-4f8d-46a6-965b-131b5687e34a" /> | <img width="1067" height="337" alt="image" src="https://github.com/user-attachments/assets/a62f407e-cb8b-41db-acb9-b5aa90ba4d0e" /> |
> style(launchpad2): Update project card background

- frontend/src/lib/components/staking/ProjectsTable.svelte
#7172 introduced the `ApyCard` on the Staking page. It uses `tokensListVisitorsStore` to calculate the total staking amount, but this is incorrect. This store contains the generic tokens displayed before a user signs in, resulting in an inaccurate value when calculating `totalTokensBalanceInUsd`.
- Replace `tokensListVisitorsStore` with `tokensListUserStore` for properly calculating APY.
- Tests should pass as before.
> fix(apy): use correct token store for balance calculation in Staking page

- frontend/src/tests/utils/e2e.test-utils.ts
- scripts/sns/aggregator/test-fast
CI pipeline has been flaky in the last days. Several checks require on the context to be ready and this sometimes is taking longer.
This PR follows up #7252.
- Increase timers for the aggregator tests.
- Check that network is idle for II.
- CI should pass.
> chore(ci): improve CI flakiness

- frontend/src/lib/components/portfolio/NoHeldTokensCard.svelte
Currently, when logged out, the "View Tokens" link navigates to the ICP tokens page, which is not desirable, as it should link to the All Tokens page.
- Update the link.
> fix(portfolio): "View Tokens" link when logged-out

- frontend/src/lib/components/portfolio/HeldTokensCard.svelte
- frontend/src/lib/components/portfolio/StakedTokensCard.svelte
- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/pages/SignInTokens.svelte
- frontend/src/lib/pages/Tokens.svelte
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/portfolio.utils.ts
- frontend/src/routes/+layout.svelte
- frontend/src/tests/lib/components/portfolio/HeldTokensCard.spec.ts
- frontend/src/tests/lib/components/portfolio/StakedTokensCard.spec.ts
- frontend/src/tests/lib/utils/portfolio.utils.spec.ts
- frontend/src/tests/routes/layout.spec.ts
- frontend/src/tests/utils/e2e.test-utils.ts
A variety of improvements before the release.
- Simplify the logic for displaying the info row to show it only when SNS tables have an uneven number of elements.  
-  Remove the Highlight component, as it was originally implemented in #7220 but was missed during the revert in #7227.  
-  Standardize the gap size for table pages to 24px on desktop.
- Enable portfolio utils tests
- Update tests for the new show info row logic.
> style(ui): polish table layouts and components

- Cargo.lock
- Cargo.toml
There is a vulnerability on the transient dependency `slub`. More information can be found [here](https://github.com/dfinity/nns-dapp/security/dependabot/122).
- Bump version of affected vulnerability.
- CI should pass.  
- Conduct a manually triggered vulnerability check.
> fix(deps): patch slub dependency vulnerability

- frontend/src/lib/components/proposal-detail/ProposalSummary.svelte
Markdown headings that wrap a link were losing their heading styles, breaking visual hierarchy (see [report](https://dfinity.slack.com/archives/C01SBGL2AQL/p1755846244950189)).
- Ensure heading styles apply even when the heading text is wrapped in an `<a>` tag.
- Manually verified H1–H6 with and without nested links.
| <img width="923" height="412" alt="image" src="https://github.com/user-attachments/assets/357e1b94-d7a5-4074-aa8c-4637d736f478" /> | <img width="922" height="400" alt="image" src="https://github.com/user-attachments/assets/0bebeb04-da4f-4ce6-89f7-8d2b3ba74c21" /> |
> fix(markdown): preserve heading styles when headings contain links

- frontend/src/lib/components/staking/ProjectsTable.svelte
- frontend/src/lib/components/tokens/TokensTable/TokensTable.svelte
- frontend/src/lib/components/ui/ResponsiveTableSortControl.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/types/responsive-table.ts
- frontend/src/tests/lib/components/tokens/TokensTable.svelte.spec.ts
Align the sort label name of the tokens column.
Provided a way to override the label.
Updated tests.
> chore(table sorting): change naming of token sort chip

- frontend/src/lib/components/canisters/CanisterCardSubTitle.svelte
- frontend/src/lib/components/canisters/CanisterCardTitle.svelte
- frontend/src/lib/modals/canisters/CreateCanisterModal.svelte
Fix visual issues with the Canister cards.
- Remove trailing `>`
- Card title should display `Copy` icon in the same line.
- Visually tested
> style(cards): fix title layout and remove extra character

- rs/sns_aggregator/src/state.rs
This PR fixes the following issue: if there's no SNS (e.g., in local deployment), then there's no page at the path `/v1/sns/list/page/0/slow.json` listing SNS projects. Consequently, the NNS dapp fails to pull the list of all deployed SNS and keeps displaying an error.
This PR fixes how the number of deployed SNS is determined: instead of using `max_index + 1` it uses `upstream_data.len()` which is equivalent if there's at least one SNS (e.g., in production) and also correct in case of no SNS (e.g., in local deployment).
This PR has been tested manually by deploying the SNS aggregator along with the NNS dapp and confirming that the NNS dapp can successfully load the list of all deployed SNS.
> fix(sns_aggregator): ensure last page exists

- frontend/package-lock.json
https://github.com/dfinity/gix-components/pull/707 fixed an issue on how `svg` are render as part of code blocks in the Markdown component.
This issue has arisen with the II proposal that was rendered incorrectly in the nns-dapp, causing problems when attempting to validate the payload.
* https://dashboard.internetcomputer.org/proposal/138188
* https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=138188
This PR fixes it as shown in the following screenshot:
[NNS1-4082](https://dfinity.atlassian.net/browse/NNS1-4082)
- Bump gix to latest.
- Validate the payload with the new rendering output and getting `1c18791e243e9c00cfb124320df7b11a216660cf9f9616a39e8565f62f3a2236`
[NNS1-4082]: https://dfinity.atlassian.net/browse/NNS1-4082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> fix(deps): update gix for markdown SVG rendering

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/project-detail/ProjectInfoSection.svelte
#7169 introduced a minor bug in the Projects page by displaying an `<` symbol before the Token Value label.
| <img width="651" height="410" alt="Screenshot 2025-09-01 at 17 28 04" src="https://github.com/user-attachments/assets/a0b1d0fa-bba4-4d3f-9b8e-711a1c02ac69" /> | <img width="626" height="399" alt="Screenshot 2025-09-01 at 17 28 51" src="https://github.com/user-attachments/assets/d686a609-a9ba-4212-affe-cff4e50e8bc5" /> |
- Remove symbol
> fix(ui): remove extra character from a Project's page details

- frontend/src/lib/constants/environment.constants.ts
- frontend/src/lib/derived/ckbtc-universes.derived.ts
- frontend/src/lib/services/ckbtc-tokens.services.ts
- frontend/src/lib/services/icrc-canisters.services.ts
- frontend/src/lib/stores/feature-flags.store.ts
- frontend/vitest.setup.ts
The nns-dapp currently shows many errors when any of the CK canisters are unavailable. This behavior prevents the use of the latest version of the nns-dapp in the [monorepo dependencies](https://github.com/dfinity/ic/blob/c04b07cb230cb0c2efd19b8aad97f31aa42ecf79/MODULE.bazel#L567-L583).
More info [here](https://dfinity.slack.com/archives/C01S03NBM7S/p1755184658526049)
- New feature flag to disable loading CK canisters.
- Skip loading CK canisters if FF is true.
- Manually tested locally with a version of snsdemo that does not install CK canisters.
> feat(config): disable CK tokens through feature flag

- frontend/package-lock.json
- frontend/src/lib/utils/sns-aggregator-converters.utils.ts
- frontend/src/tests/lib/components/sns-proposals/SnsProposalSystemInfoSection.spec.ts
- frontend/src/tests/lib/derived/sns-topics.derived.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicItem.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicStepTopics.svelte.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/SnsTopicDefinitionsTopic.spec.ts
- frontend/src/tests/lib/utils/sns-aggregator-converters.utils.spec.ts
- frontend/src/tests/lib/utils/sns-topics.utils.spec.ts
- frontend/src/tests/mocks/sns-topics.mock.ts
The latest upgrade of candid files in [ic-js](https://github.com/dfinity/ic-js/pull/1032/files#diff-684ab36c5e16fec984732ec9c53e9fe5690f4dddf1ddd713d7fd48a210de5707R1051) introduced a new field, `extension_operations`, to the `InfoTopic` field. This change requires that the nns-dapp be updated to initialize this new field. Since the front end does not need it and the value is not exposed by the Aggregator, this PR initializes it to an empty value, `[]`.
NOTE: If the value is needed in the future, a proper adaptation will be made at that time.
- Add `extension_operations` field
- Initialize new property to `[]`
> fix(aggregator): handle new InfoTopic extension field

- frontend/src/lib/components/alfred/Alfred.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
Randomly spotted a missing i18n key in the `<Alfred />` search modal.
- Extract text and use i18n key
> feat: missing i18n in Alfred search modal

- frontend/package-lock.json
- frontend/package.json
There is a vulnerability reported by `npm audit`:
```
vite  6.0.0 - 6.3.5
Vite middleware may serve files starting with the same name with the public directory - https://github.com/advisories/GHSA-g4jq-h2w9-997c
Vite's `server.fs` settings were not applied to HTML files - https://github.com/advisories/GHSA-jqfw-vq24-v9c3
node_modules/vite
1 low severity vulnerability
To address all issues, run:
npm audit fix
```
- Run `npm audit fix`
> fix(deps): patch vite security vulnerability

- frontend/src/lib/services/public/app.services.ts
- frontend/src/lib/stores/auth.store.ts
- frontend/src/lib/utils/dev.utils.ts
- frontend/src/routes/(app)/(home)/+layout.svelte
- frontend/src/routes/(app)/(home)/+page.svelte
- frontend/src/routes/(app)/(nns)/portfolio/+page.svelte
- frontend/src/routes/(app)/+layout.svelte
- frontend/src/routes/(app)/+layout.ts
- frontend/src/routes/+layout.svelte
In Safari, **nns-dapp** occasionally hangs during initialization (about once every couple of weeks for a user), showing only the app background.
The issue could not be reproduced with the same browser version, but the provided DevTools logs suggest a problem in the `AuthStore.sync` function.
To help pinpoint the root cause, additional logs have been added. ~~These logs are enabled **only in Safari** to avoid polluting logs for other users.~~
- Added extra logs around the suspected issue location, ~~scoped to Safari only~~.
- ~~Verified that the new logs appear only in Safari.~~
> Extra logs for safari

- frontend/src/lib/utils/staking-rewards.utils.ts
- frontend/src/tests/lib/utils/staking-rewards.utils.spec.ts
The FX provider may be unresponsive or failing. The Rewards UI should handle this situation by displaying a card with relevant information for the user.
| <img width="1135" height="516" alt="Screenshot 2025-09-26 at 11 50 28" src="https://github.com/user-attachments/assets/30585616-337e-4b6c-a241-fee6e772c4e5" /> | <img width="1217" height="543" alt="Screenshot 2025-09-26 at 11 49 37" src="https://github.com/user-attachments/assets/73aa315f-1fb2-49b7-a974-91d7b162be9c" /> | 
| <img width="873" height="812" alt="Screenshot 2025-09-26 at 11 50 44" src="https://github.com/user-attachments/assets/8b34fd89-bdde-4130-89e9-aec3909a4eea" /> | <img width="897" height="783" alt="Screenshot 2025-09-26 at 11 50 01" …
> feat(rewards): handle FX provider unavailability

- .github/workflows/checks.yml
The Update SNS Aggregator Response is failing due some white spaces. Eg: #7373
Tested by locally running:
```
diff -w <(scripts/sns/aggregator/get-sns PokedBots) <(echo "Name:   PHASMA
Symbol: PHASMA
Aggregator URL:         https://3r4gx-wqaaa-aaaaq-aaaia-cai.icp0.io/v1/sns/root/nb7he-piaaa-aaaaq-aadqq-cai/slow.json
Root canister ID:       nb7he-piaaa-aaaaq-aadqq-cai
Governance canister ID: ni4my-zaaaa-aaaaq-aadra-cai
Ledger canister ID:     np5km-uyaaa-aaaaq-aadrq-cai
Index canister ID:      n535v-yiaaa-aaaaq-aadsq-cai
Swap canister ID:       n223b-vqaaa-aaaaq-aadsa-cai
Transaction fee:      1
Minimum neuron stake: 500000
Proposal fee:         5000000")
```
- Ignore white spaces when diffing the expectation to the result.
- Locally tested
> fix(test): ignore whitespace in SNS response diff

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/stores/toasts.store.ts
- frontend/src/lib/utils/error.utils.ts
- frontend/src/tests/lib/components/accounts/ImportTokenModal.spec.ts
- frontend/src/tests/lib/modals/sns/neurons/FollowSnsNeuronsByTopicModal.svelte.spec.ts
- frontend/src/tests/lib/pages/IcrcWallet.spec.ts
- frontend/src/tests/lib/services/canisters.services.spec.ts
- frontend/src/tests/lib/services/ckbtc-convert.services.spec.ts
- frontend/src/tests/lib/services/ckbtc-info.services.spec.ts
- frontend/src/tests/lib/services/icp-accounts.services.spec.ts
- frontend/src/tests/lib/services/icp-transactions.services.spec.ts
- frontend/src/tests/lib/services/icrc-accounts.services.spec.ts
- frontend/src/tests/lib/services/icrc-index.services.spec.ts
- frontend/src/tests/lib/services/icrc-transactions.services.spec.ts
- frontend/src/tests/lib/services/imported-tokens.services.spec.ts
- frontend/src/tests/lib/services/neurons.services.spec.ts
- frontend/src/tests/lib/services/public/proposals.services.spec.ts
- frontend/src/tests/lib/services/public/sns-proposals.services.spec.ts
- frontend/src/tests/lib/services/sns-accounts-balance.services.spec.ts
- frontend/src/tests/lib/services/sns-neurons.services.spec.ts
- frontend/src/tests/lib/services/sns-sale.services.spec.ts
- frontend/src/tests/lib/services/sns.services.spec.ts
- frontend/src/tests/lib/services/vote-registration.services.spec.ts
- frontend/src/tests/lib/utils/error.utils.spec.ts
Following the already-done error deduplication task.
To make the UI more user-friendly, technical error details are now hidden by default to the user.
Hid error details, simplified messages.
Updated tests.
> chore(messages): simplify error messages

- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/types/reporting.ts
- frontend/src/lib/utils/date.utils.ts
- frontend/src/lib/utils/reporting.utils.ts
- frontend/src/tests/lib/utils/date.utils.spec.ts
- frontend/src/tests/lib/utils/reporting.utils.spec.ts
The nns-dapp will introduce a date range selector for the Reporting Transactions feature. This initial PR prepares some of the utils to support this new case.
Note: The implementation uses the local date and time to accommodate the user's timezone. It is then converted to UTC in nanoseconds, as this is the format supported by the API.
[NNS1-4134](https://dfinity.atlassian.net/browse/NNS1-4134)
- Extend `formatDateCompact` to support delimiters on the dates.
- Extend `convertPeriodToNanosecondRange` to support custom date range with provided `from` and `to`.
- Added unit tests to both utils.
- Manually tested in a larger PR #7374 
[NNS1-4134]: https://dfinity.atlassian.net/browse/NNS1-4134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(utils): extend reporting utils for custom date range

- CHANGELOG-Nns-Dapp-unreleased.md
- frontend/src/lib/components/reporting/ReportingDateRangeSelector.svelte
- frontend/src/lib/components/reporting/ReportingTransactions.svelte
- frontend/src/lib/components/reporting/ReportingTransactionsButton.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/reporting.utils.ts
- frontend/src/tests/lib/components/reporting/ReportingDateRangeSelector.svelte.spec.ts
- frontend/src/tests/lib/components/reporting/ReportingTransactionsButton.spec.ts
- frontend/src/tests/page-objects/ReportingDateRangeSelector.page-object.ts
- frontend/src/tests/page-objects/ReportingTransactionsButton.page-object.ts
- frontend/src/tests/page-objects/jest.page-object.ts
- frontend/src/tests/types/page-object.types.ts
Allow users to export their transactions for a custom period, limited to one full year. Following up on #7390, this PR adds the necessary changes to the Transactions form to select a custom date range.
Notes:
* The maximum range is one year.  
* If the user only selects `from`, `to` is set to `today`.  
* If the user changes `from` to a date older than a year, `to` is updated to the latest possible value.
[NNS1-4134](https://dfinity.atlassian.net/browse/NNS1-4134)
| Header | Header |
| <img width="379" height="793" alt="Screenshot 2025-10-01 at 13 18 52" src="https://github.com/user-attachments/assets/1cb34230-705b-4515-8d5b-27d4eef8192c" /> | <img width="408" height="797" alt="Screenshot 2025-10-01 at 13 18 31" …
> feat(reporting): add custom date range selection

- frontend/package-lock.json
To handle the following vulnerability:
```
tar-fs  2.0.0 - 2.1.3
Severity: high
tar-fs has a symlink validation bypass if destination directory is predictable with a specific tarball - https://github.com/advisories/GHSA-vj76-c3g6-qr5v
node_modules/tar-fs
```
- Bump the version with `npm audit fix`
> chore(deps): bump tar-fs from 2.1.3 to 2.1.4

- frontend/src/lib/components/alfred/Alfred.svelte
- frontend/src/lib/i18n/en.json
- frontend/src/lib/stores/transaction-memo-option.store.ts
- frontend/src/lib/types/i18n.d.ts
- frontend/src/lib/utils/alfred.utils.ts
- frontend/src/tests/lib/components/alfred/Alfred.spec.ts
Support the transaction memo for both ICP and ICRC1 addresses for ICP transaction flows. This PR adds the options to the Command Palette for users to turn it on/off. The feature will be added in a follow-up PR.
Note: The feature is not persisted in localStorage. Users will have to turn it on on every session.
- Add a memo option to the Command Palette.
- Change side: Move some translations to the translations file.
- Added unit tests for the change.
> feat(commands): add transaction memo toggle option
